### ISSUE TITLE
SurfaceMesh: Adding faces generates multiple edges between vertices

### ISSUE THREAD

**Issue by Wouter92** [CGAL/cgal#1002]
After adding all vertices to my new SurfaceMesh, I add faces. 
The problem is that after adding the second face, some vertices have multiple edges between them, eg. edge v0 -> v1 appears two or more times in the mesh. 
This happens however only on my Kubuntu Desktop computer and not on my Arch Linux laptop. I made sure to use the same version of the CGAL and Boost libraries on both computers (4.8 and 1.60). 

I am thinking this is maybe a platform-dependent bug in CGAL? Anyway, if that is true, it happens inside the add_face method (eg. incorrectly checking if an edge already exists in the mesh?).

**Comment by afabri** [comment]
Please put a small cpp on a gist

**Comment by Wouter92** [comment]
I put a small cpp with the two different outputs I got in a gist [here](https://gist.github.com/Wouter92/f2946ed87cd33a44a51655811e68ce7f). 
The outputArch.txt is correct because it does not mention two edges between v3 and v0. Additionally, in outputKubuntu.txt some edges are clearly wrong (eg. edge between v3 and v1 must be between v3 and v2).

**Comment by afabri** [comment]
The mistake you make is to  write `vhit(m.halfedge(vd),m)`.  It should be `vhit(vd,m)`.
With what you write, you circulate around the source vertex of `m.halfedge(vd)`.
