### ISSUE TITLE
Polyhedron demo: polyline of point set selection not displayed anymore

### ISSUE THREAD

**Issue by sgiraudot** [CGAL/cgal#1006]
It seems there was a regression at some point: when selecting a point set with `point_set_selection_plugin`, there used to be a green polyline displayed when moving the mouse. It is not visible anymore (although the selection in itself still works fine, it is impossible to see what is going to be selected in realtime while moving the mouse).

**Comment by lrineau** [comment]
Is the bug in CGAL-4.8 or only in `master`?

**Comment by sgiraudot** [comment]
Both (I just tested 4.8).

**Comment by lrineau** [comment]
@maxGimeno: once you work on this bug, make sure your working branch and the PR are based on `releases/CGAL-4.8-branch`.

**Comment by maxGimeno** [comment]
Apparently this issue has been fixed by #1007 , so this PR can be closed.

**Comment by lrineau** [comment]
Thanks, Maxime.
