### ISSUE TITLE
NewKernel_d LA::solve always throws with Interval_nt

### ISSUE THREAD

**Issue by mglisse** [CGAL/cgal#1016]
In LA.h, the test `b.isApprox(m*a)` doesn't look like something that is likely to succeed with intervals. This makes computing alpha-complexes 20 times slower than a simple `return true`. I have completely forgotten what this is all about, so I need some time, I'm filing the issue so I don't forget.

**Comment by mglisse** [comment]
See branch cgal-dev/NewKernel_d-solve_check-glisse .

**Comment by lrineau** [comment]
Please add:
> Fix #1016
in the PR you will create.

I think the PR should be base on `releases/CGAL-4.8-branch`. Please rebase your branch onto it before the creation of the PR (and be careful to choose CGAL-4.8-branch as the base of the PR).

**Comment by lrineau** [comment]
Fixed by #1023.
