### ISSUE TITLE
PMP::isotropic_remeshing silently failing

### ISSUE THREAD

**Issue by kekkooo** [CGAL/cgal#1017]
Hi,
I have compiled CGAL 4.8 from source ( release download , not git pull )
I'm using the new isotropic_remeshing function on a Polyhedron_3 defined as 
typedef CGAL::Simple_cartesian<double> K;
typedef CGAL::Polyhedron_3<K, CGAL::Polyhedron_items_with_id_3>     Polyhedron_3;
Polyhedron_3 Poly; 
the polyhedron stores the convex hull of a point set, obtained using convex_hull_3.
when calling  PMP::isotropic_remeshing( faces(Poly), target, Poly );
the program stops without error messages or assert failures, I tried also to compile CGAL in debug mode and still there are no information about what is happening.

Thanks

**Comment by afabri** [comment]
please put a program and data on a gist.

andeas

On 17/04/2016 16:24, Francesco Usai wrote:
> Hi,
> I have compiled CGAL 4.8 from source ( release download , not git pull )
> I'm using the new isotropic_remeshing function on a Polyhedron_3 defined as
> typedef CGAL::Simple_cartesian K;
> typedef CGAL::Polyhedron_3 Polyhedron_3;
> Polyhedron_3 Poly;
> the polyhedron stores the convex hull of a point set, obtained using
> convex_hull_3.
> when calling PMP::isotropic_remeshing( faces(Poly), target, Poly );
> the program stops without error messages or assert failures, I tried
> also to compile CGAL in debug mode and still there are no information
> about what is happening.
>
> Thanks
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/CGAL/cgal/issues/1017>
>

-- 
Andreas Fabri, PhD
Chief Officer, GeometryFactory
Editor, The CGAL Project

phone: +33.492.954.912    skype: andreas.fabri

**Comment by kekkooo** [comment]
https://gist.github.com/kekkooo/c61c97b89b348c22a63d8c2f98cee5f8

(first time I use gist, I hope it is done properly )

**Comment by janetournois** [comment]
I proposed the above pull request to try avoiding this to happen again.
Thanks @kekkooo for the report
