### ISSUE TITLE
Polyhedron_demo : Segfault when trying to mesh some items with Mesh_3 plugin

### ISSUE THREAD

**Issue by maxGimeno** [CGAL/cgal#1020]
When trying to mesh an infinite item, or an open item, or some others in the Mesh_3 plugin, the meshing fails ( which is probably normal in most cases) and the demo segfaults. I Think some tests should be performed on the polyhedron before starting to mesh, and an error box should appear and stop the operation instead of letting the demo crash.

**Comment by lrineau** [comment]
I agree: before we promote that demo to an application for users, it will have to be bullet-proof.
