### ISSUE TITLE
BGL copy_face_graph use deprecated code?

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#1033]
It seems I have merged #728 too soon. The code fails to compile with `-DCGAL_NO_DEPRECATED_CODE`:

https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.9-Ic-28/BGL/TestReport_lrineau_Ubuntu-Latest-NO_DEPRECATED_CODE.gz

**Comment by lrineau** [comment]
Cc: @afabri @sloriot

**Comment by sloriot** [comment]
Where is this file coming from? I don't see it in master

**Comment by sloriot** [comment]
From afabri/BGL-copy_face_graph

**Comment by sloriot** [comment]
I close the issue since it refers to a branch not merged in master.

**Comment by lrineau** [comment]
The bug is probably in `copy_face_graph`, from PR #728, merged in `master`. Andreas just added a test of that function.

**Comment by sloriot** [comment]
I bet this is a missing include (`Polyhedron_3.h` is not including `graph_traits_Polyhedron_3.h` when not using deprecating code).

**Comment by afabri** [comment]
just fixed it.  In fact we do not have a testsuite for this function. And I mainly wrote it as we have an ICE with an old VC++ in the skeletonization testsuite.

**Comment by lrineau** [comment]
That is strange that the compilation error was only with the platform with `-DCGAL_NO_DEPRECATED_CODE`.
