### ISSUE TITLE
Range tree takes a lot of space

### ISSUE THREAD

**Issue by freud14** [CGAL/cgal#1047]
Hi,

When using the Range_tree_2 class (probably Range_tree_d also) with 1 million points, the structure takes 4.5GB in memory. Is that normal for just 1 million points?

Here is the code: https://gist.github.com/freud14/3a93be3fb1f79bbfc03e80a12bab1347

Thank you.

Frédérik

**Comment by freud14** [comment]
Alright, it seems that each node of the range tree takes 80 bytes and each range tree takes 40 bytes. With 1 million points, it gives ~1 million range trees and ~40 million nodes. If we do the calculation, it gives ~3.5GB for that + probably memory I forgot to take into account and it is close to the 4.5GB. So yeah, it seems normal. I think I'll use a Kd-tree instead. 

Also, is there a data structure for range querying a set of iso-rectangles?

Thank you.

**Comment by afabri** [comment]
The implementation dates back from the eighties. The focus was on design, not so much on efficiency.
