### ISSUE TITLE
Non-deterministic build process causes random build failures due to missing includes

### ISSUE THREAD

**Issue by joachim-reichel** [CGAL/cgal#1048]
1. include/CGAL/IO/io.h needs to include \<CGAL/assertions.h\>

2. The content of the all_files.cpp files is not deterministic. For example, the missing include shows up if io.cpp ends up as first include in src/CGAL/all_files.cpp. This makes such problems extremely difficult to debug. In my case it happened consistently on 2 of ~15 architectures in an automated build environment, but never when built manually. Independent of the missing include build results should be deterministic and reproducible, see https://reproducible-builds.org/ .

**Comment by lrineau** [comment]
For 1, see #1025. I will try to publish 4.8.1 soon.

**Comment by joachim-reichel** [comment]
Ok, someone else was faster.

For 2, in some places the glob result is already sorted, e.g. in examples/CMakeLists.txt. Maybe every file(GLOB ...) operation should immediately be followed by a SORT operation.

**Comment by joachim-reichel** [comment]
Patch to sort the results of all remaining file(GLOB ...) operations.
[sort-file-glob-results.diff.txt](https://github.com/CGAL/cgal/files/242860/sort-file-glob-results.diff.txt)

**Comment by mglisse** [comment]
The first part of the patch matches what Laurent wrote in https://sympa.inria.fr/sympa/arc/cgal-develop/2015-03/msg00005.html , so you both seem to agree on the direction :-)
