### ISSUE TITLE
Polyhedron demo : drawing error in edit_polyhedron_item

### ISSUE THREAD

**Issue by janetournois** [CGAL/cgal#1054]
For a non-triangulated polyhedral surface, when the deformation plugin is started (with Ctrl-E), the non-triangle faces are not displayed completely, only one "subtriangle" is.
 
See snapshots of the polyhedron
 ![poly](https://cloud.githubusercontent.com/assets/11311305/14954399/64adf006-1072-11e6-8da3-ae3197af0214.png)
and the polyhedron in edit mode
![poly_edit](https://cloud.githubusercontent.com/assets/11311305/14954400/65b94298-1072-11e6-9412-6f2775df57ac.png)

cc @maxGimeno

**Comment by sloriot** [comment]
A polyhedron item which is not a pure triangle mesh should not be converted to an edit polyhedron item.

**Comment by sloriot** [comment]
@maxGimeno see [`Polyhedron_3::is_pure_triangle()`](http://doc.cgal.org/latest/Polyhedron/classCGAL_1_1Polyhedron__3.html#a4f088c2a8091b885f98b28f0f9f5bf30)

**Comment by janetournois** [comment]
ok, then the plugin should not be `applicable()`

**Comment by sloriot** [comment]
IIRC, all polyhedron items in the list are turned into a edit polyhedron item. Skipping the non triangulated one is the best option.
