### ISSUE TITLE
Incorrect segment colors in Surface mesh segmentation 

### ISSUE THREAD

**Issue by Namdhari** [CGAL/cgal#1064]
The max_segment value being calculated in the function
Polyhedron_demo_mesh_segmentation_plugin::colorize_segmentation().
Is different from the number of segments got from function
nb_segments = segmentation_from_sdf_values()

Is this behaviour correct ?

**Comment by sloriot** [comment]
max_segment=nb_segments-1 (the first segment is assigned the id 0)

**Comment by Namdhari** [comment]
I had put logs and got followiing for two test runs ,

> Segmentation is completed. Number of segments : 3
> max_segment 0
> Segmentation is completed. Number of segments : 5
> max_segment 3
> 

In ideal case it should have been what you mentioned
max_segment=nb_segments-1 (the first segment is assigned the id 0)

**Comment by sloriot** [comment]
How can I reproduce one of these runs?

**Comment by Namdhari** [comment]
Okay the mesh I used is proprietary,
Let me check with some other mesh. I will share the mesh, and the parameters used for segmentation.
Please excuse I should have provided that detail already :)

**Comment by Namdhari** [comment]
![segmentation_issue](https://cloud.githubusercontent.com/assets/5296582/15068291/ee6e7152-1393-11e6-997c-f9990cc83b01.png)

Changes I did
> --- a/Polyhedron/demo/Polyhedron/Plugins/Surface_mesh/Mesh_segmentation_plugin.cpp
> +++ b/Polyhedron/demo/Polyhedron/Plugins/Surface_mesh/Mesh_segmentation_plugin.cpp
> @@ -339,9 +339,10 @@ void Polyhedron_demo_mesh_segmentation_plugin::colorize_segmentation(
>          facet_it->set_patch_id(static_cast<int>(segment_id));
>          max_segment = (std::max)(max_segment, segment_id);      
>      }
> +    std::cout << "max_segment" << max_segment << std::endl;
>   for(std::size_t i = 0; i <= max_segment; ++i)
>      {
>   QColor aColor = color_map_segmentation[(max_segment - i) % color_map_segmentation.size()];
>          color_vector.push_back(aColor);     
>      }    
>  }


logs
> Segmentation is completed. Number of segments : 3
> max_segment 1

**Comment by Namdhari** [comment]
attaching Model file
[Dinopet_stripped.off.cluster.obj.zip](https://github.com/CGAL/cgal/files/251795/Dinopet_stripped.off.cluster.obj.zip)

**Comment by sloriot** [comment]
I did not realize you were talking about the input parameter. Yes this is totally expected, checkout the note here:

http://doc.cgal.org/latest/Surface_mesh_segmentation/index.html#title5

**Comment by Namdhari** [comment]
By default, in the Polyhedron Demo, the Extract Segment check box is checked. However when it is checked, it extracts clusters. 
And when unchecked it extracts segments. 
Its confusing, by default it should be unchecked and a user should mark it checked when he wants to see the segments.

Please clarify

**Comment by sloriot** [comment]
Except if I missed something, the default behavior in the demo is the one described in the research article, that is extract segments. If you're talking about how things are phrased in the ui feel free to submit a pull request.
