### ISSUE TITLE
Mesh Segmentation doc refers to k-means++ but in code K_MEANS_INITIALIZATION is used

### ISSUE THREAD

**Issue by Namdhari** [CGAL/cgal#1065]
I the function partition() inside Surface_mesh_segmentation/Surface_mesh_segmentation.h
 K_MEANS_INITIALIZATION  EM Fitter is being used. The doxygen mentions K-means++ for which I think PLUS_INITIALIZATION enum value should be passed as a paramter to the fitter ?

**Comment by lrineau** [comment]
Notes to CGAL developers:
- Ilker is still in `package_info/Surface_mesh_segmentation/maintainer` but is no longer a CGAL developer. I imagine that GeometryFactory is the maintainer.
(Cc @sloriot @afabri )
- Please fix the `maintainer` file.

**Comment by sloriot** [comment]
What is written in the doc is correct. k-mean algorithm is used but the initialisation of k-mean is using the technique from k-mean++ 

    if(init_type == K_MEANS_INITIALIZATION) {
      K_means_clustering k_means(number_of_centers, data,
                                 K_means_clustering::PLUS_INITIALIZATION,
                                 number_of_runs, maximum_iteration);
