### ISSUE TITLE
Polyhedron demo: modal windows do not open

### ISSUE THREAD

**Issue by sgiraudot** [CGAL/cgal#1077]
Plugins that use modal window do not work anymore (for example _normal estimation_ for point sets). The window does not open and nothing happens. This seems to be caused by the merge of PR https://github.com/CGAL/cgal/pull/1040 (reverting it solves the issue).

**Comment by lrineau** [comment]
I suspect that the modifications to `init()` is the cause: the `QMainWindow* mw` pointer is initialized by a call to that function.

**Comment by sgiraudot** [comment]
The bug is only partially fixed: still no window for some actions (_Add Point Sets_ and _Add Polylines_ in file menu for example).
