### ISSUE TITLE
Unable to download GMP and  MPFR

### ISSUE THREAD

**Issue by DolphinSong** [CGAL/cgal#1078]
Hello,
I downloaded and installed the recent 4.8 version.
During the installation, two errors occurred telling that unable to download the pre-compiled gmp and mpfr libraries. 
regards,
Teng

**Comment by sloriot** [comment]
Paths look good. Could you try again?

**Comment by lrineau** [comment]
@DolphinSong I have tried myself and it worked.

That was probably a temporary network issue.

**Comment by DolphinSong** [comment]
I tried on my laptop and now it worked thanks alll.
