### ISSUE TITLE
Ignore degenerate faces in SDF calculation

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#1094]
When building the AABB-tree used to evalute the sdf function, degenerate faces can be safely ignored.

We need to benchmark a few runs to see if this incurs a noticeable performance degradation.
Also we should look whether the traits class concept should be updated.

**Comment by mickey9294** [comment]
Can you show me the specific way to avoid the impact of degenerate faces?

**Comment by sloriot** [comment]
in your case, you can remove the edges of length zero using for example [`collapse_edge()`](http://doc.cgal.org/latest/BGL/group__PkgBGLEulerOperations.html#gab97c0d071b0d768e22a4fc171a8ca664)
