### ISSUE TITLE
Macos homebrew formula installs 4.7 instead of 4.8 

### ISSUE THREAD

**Issue by dcoeurjo** [CGAL/cgal#1096]
When using the MacOSX install guideline (http://www.cgal.org/download/macosx.html), we don't have the last stable release of CGAL. 
The homebrew formula (https://github.com/Homebrew/legacy-homebrew/blob/master/Library/Formula/cgal.rb) needs to be updated (from 4.7 to 4.8)

**Comment by lrineau** [comment]
You should report the issue to the Homebrew project. The CGAL project has not any developer using Homebrew.

**Comment by dcoeurjo** [comment]
I'm also just pointing out a mistake on the website that suggests that following the macosx install, you'll get the last release. 

Maybe you could just add something saying that CGAL is not maintaining the homebrew/port receipts and that the version may differ from stable one

**Comment by lrineau** [comment]
You are right. That is a bug of our web site.

**Comment by dcoeurjo** [comment]
(FYI: CGAL4.8 is pending on homebrew, https://github.com/Homebrew/homebrew-core/pull/321)

**Comment by sloriot** [comment]
Fixed by d0bcc9113c84a8c896af7fcddde1bd7c6866398f
