### ISSUE TITLE
Remove duplicated implementation

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#1107]
Try removing the file [`Mesh_3/include/CGAL/internal/Mesh_3/split_in_polylines.h`](https://github.com/CGAL/cgal/blob/master/Mesh_3/include/CGAL/internal/Mesh_3/split_in_polylines.h) by replacing its usage by the function in [`BGL/include/CGAL/boost/graph/split_graph_into_polylines.h`](https://github.com/CGAL/cgal/blob/master/BGL/include/CGAL/boost/graph/split_graph_into_polylines.h).

A usage example is provided in [`simple_mcfskel_example.cpp`](https://github.com/CGAL/cgal/blob/master/Surface_mesh_skeletonization/examples/Surface_mesh_skeletonization/simple_mcfskel_example.cpp)

**Comment by lrineau** [comment]
CC @fabri, that is the author of [`Mesh_3/include/CGAL/internal/Mesh_3/split_in_polylines.h`](https://github.com/CGAL/cgal/blob/master/Mesh_3/include/CGAL/internal/Mesh_3/split_in_polylines.h).

Andreas, will you have time to prepare a new implementation of `<CGAL/internal/Mesh_3/split_in_polylines.h>` that uses `<CGAL/boost/graph/split_graph_into_polylines.h>`?

**Comment by sloriot** [comment]
I already ask @maxGimeno

**Comment by lrineau** [comment]
Andreas added that file in 18bbaede12e9831192b167cdd95d5c895a01f8e7. Andreas and Maxime will decide who has time for that task.
