### ISSUE TITLE
Document CGAL::Dual

### ISSUE THREAD

**Issue by mglisse** [CGAL/cgal#1112]
Reading the documentation of CGAL-BGL, it says we can use faces as vertices, but doesn't really explain how. There is just one example for arrangements, that uses the undocumented class Dual. Maybe it is explained somewhere, but it deserves more documentation.

**Comment by afabri** [comment]
I agree that we might add a section in the User Manual.
But note that there is another example. See the link in the ref man page of [Dual](https://cgal.geometryfactory.com/CGAL/Manual_doxygen_test/CGAL-4.9-Ic-58/output/BGL/classCGAL_1_1Dual.html)

andreas

**Comment by mglisse** [comment]
Ah, the documentation page for `Dual` is new in 4.9. It seems that the issue is essentially already fixed, thanks!
