### ISSUE TITLE
Using boost::hash with Point

### ISSUE THREAD

**Issue by freud14** [CGAL/cgal#1116]
Hi,

I don't know if this is the best place to post this as it is more of a feature request (that I'm willing to program) than an issue but here we go.

I would like to be able to use a boost unordered_map (or STL's) but the boost::hash traits is not implemented in CGAL. I was thinking of implementing it but I don't know how to deal with the different numeric types. I was thinking to use the CGAL::to_double function to convert the field type of the point to double and then passing each coordinate to boost::combine_hash to get the final hash. 

The only problem with this method is the lost of precision with double. However, it will respect the fact that if two points are equal, then the hash will be the same. 

What do you think?

Thank you.

Frédérik

**Comment by mglisse** [comment]
I am not convinced with using to_double generically. I believe you should rely on the number type being hashable, and hash_combine the lot. This would already work for double (and thus Epick::Point_2). It would then move the issue to hashing other number types, which is relevant as well. We might decide to use to_double on a case by case basis then (we may need CGAL_IA_FORCE_TO_DOUBLE to guarantee consistent results). Note that for intervals, hashing seems quite hard...

**Comment by freud14** [comment]
Thank you for your answer and sorry for the late answer. So, a general implementation with hash_combine would work for double and would later need to implement hashing functions for the other number types. I do not know what is CGAL_IA_FORCE_TO_DOUBLE and how intervals are used in CGAL but I suppose that it is not needed for a general hashing function. 

The only other problem I see is if the hashing should take into account if the point is in homogenous coordinates or Cartesian coordinates or just hashing the Cartesian coordinates would work without taking into account the coordinates type of the point.

Thank you.

**Comment by mglisse** [comment]
I don't think we can hash homogeneous points, since we don't canonicalize their representation. If the 2D points (1,2,3) and (2,4,6) are the same, they should have the same hash, which seems hard to guarantee. Asking for the corresponding Cartesian coordinates would in most cases use type Quotient, and we would need to make sure that Quotient(1,3) and Quotient(2,6) have the same hash, which means canonicalizing them. But that's not part of the concept for RT. Converting to double as you suggested might be the only general way, but we don't guarantee enough precision for it to really work.

At least for now, I would (static_)assert that Kernel_tag (or Rep_tag, don't know which one is more blessed) is Cartesian_tag and just hash the Cartesian coordinates. We can see later about the homogeneous case if there is demand (I strongly doubt there will be, the homogeneous kernels are seldom used by anyone, and every few years we discuss deprecating them).

**Comment by afabri** [comment]
For homogenous points you could hash `to_double(canonical(p.x())`
instead of `p.hx()`

For the exact lazy constructions it will be impossible
to guarantee the same hash for different  approximations.

What is the goal of hashing?

**Comment by mglisse** [comment]
Did you mean `FT x=p.x();simplify(x);double d=to_double(x)`? I can't find a function `canonical`... It should work for some types, I don't know if it is worth it. Note that this can be seen as hashing `p.x()`, while `simplify` and `to_double` could be part of the hashing function for `Quotient`.

**Comment by afabri** [comment]
Sorry for my sloppyness.  I also do not know if it is worth it. I only wanted to sketch how to overcome the problem you mention for Homogeneous. And point out another problem.

**Comment by freud14** [comment]
I just checked the code and `simplify` should do it for `Quotient`. Also, why not just hash the numerator and the denominator separately?

> What is the goal of hashing? 

To use hash tables.

**Comment by mglisse** [comment]
When hashing `Quotient<Gmpz>`, it makes sense to canonicalize (`simplify`), hash separately the numerator and denominator, and combine. If for some reason you end up hashing `Quotient<double>` or `Quotient<some_minimal_RT>` where `simplify` does nothing (or fails to compile), hashing separately numerator and denominator would give you a different hash for (x,y) and (2*x,2*y).

Note that storing points directly in a hash table is seldom the right choice. Quite often it is preferable to store an index or a vertex handle.

**Comment by sgiraudot** [comment]
@freud14 did you manage to do something with this issue since last year?

**Comment by freud14** [comment]
Non, I haven't taken the time.

**Comment by lrineau** [comment]
ping @maxGimeno

**Comment by lrineau** [comment]
I think we can close this issue, now that #3973 is merged: kernel objects are now hashable if they number types are. A few exception for kernel objects where the comparison operator is not trivial.
