### ISSUE TITLE
Infinite loop in Labled_mesh_domain_3

### ISSUE THREAD

**Issue by maxGimeno** [CGAL/cgal#1119]
When meshing a gray image, if the parameters are set in a certain way, the functor that sets the initial points (in Mesh_3/include/CGAL/Labled_mesh_domain_3.h, l.635)  will get stuck in a while() loop. 
 To reproduce, try to mesh the skull with 
- iso_value =0
- value_outside = 3
- transform = std::less
  
  In the Polyhedron_demo, when this is happening, clicking the "Stop" button will not stop the meshing_thread.

**Comment by sloriot** [comment]
@lrineau will #1115 fix this issue?

**Comment by lrineau** [comment]
No.




Le 30 mai 2016 16:09, à 16:09, Sebastien Loriot <notifications@github.com> a écrit:

**Comment by lrineau** [comment]
@maxGimeno Could you verify if that issue is still a valid issue?

**Comment by maxGimeno** [comment]
It seems so.

**Comment by sloriot** [comment]
You are trying to mesh an infinite domain which is not possible.
