### ISSUE TITLE
mpn_sqr not defined on GMP < 4.3.2

### ISSUE THREAD

**Issue by bo0ts** [CGAL/cgal#113]
The macro `mpn_sqr` is not defined by GMP prior to version 4.3.2. CentOS 6 currently ships with GMP 4.3.1, so this should work out of the box.

This has been discussed before here: http://cgal-discuss.949826.n4.nabble.com/Error-on-installing-CGAL-on-LINUX-CentOS-td4659148.html

and a suggested workaround by @mglisse in `Number_types/include/CGAL/Mpzf.h` was:

    // GMP-4.3.0 is missing mpn_sqr.
    #ifndef mpn_sqr
    #define mpn_sqr(dest,a,n) mpn_mul_n(dest,a,a,n)
    #endif

but apparently that fix got lost along the way.

**Comment by lrineau** [comment]
Do you suggest we add the workaroun in CGAL? Have you tested that I does fix the issue?

**Comment by bo0ts** [comment]
Well, @mglisse said he will add better version checking and this might just have fallen through the cracks and it might be better not to use MPZF in that case at all. I don't know enough to make that decision.

**Comment by mglisse** [comment]
@lrineau could you look for Number_types-oldgmp-glisse in your mailbox? (around May 2014) I am not sure what the status is...

**Comment by lrineau** [comment]
@mglisse: I found out a mail that said I you deal with the integration of the branch. Then I forgot. At last that will never happen again.. Everything is easier to deal with, with Github pull-requests: we cannot forget a pull-request.

**Comment by lrineau** [comment]
Fixed by the merged pull-request #115
