### ISSUE TITLE
copy_face_graph requires that vertex, and face descriptors are hashable

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#1133]
The new function `CGAL::copy_face_graph` does not compile if the vertex and faces descriptors of the source mesh are not hashable for Boost. The code use:
```C++
  // internal f2f and v2v
  boost::unordered_map<sm_vertex_descriptor, tm_vertex_descriptor> v2v_;
  boost::unordered_map<sm_face_descriptor, tm_face_descriptor> f2f_;
```

Two bugs:
  1. That requirement does not seem to be documented.
  2. OpenMesh descriptors are not hashable.

**Comment by afabri** [comment]
Concerning OpenMesh I've sent a mail to Jan Moebius that it would maybe a good idea to add `hash_value(..)`  and specializations of `std::hash<T>` to their handle classes.

**Comment by lrineau** [comment]
I reopen this issue, because I think that `CGAL::copy_face_graph` should be usable on our models of `FaceGraph`, without any added code. That is the point  2. in my report, see https://github.com/CGAL/cgal/issues/1133#issue-158646734.

**Comment by afabri** [comment]
As you told me  there is an overload of `hash_value(..)` in an example. We could put that in the file with the graph_traits specialization for OpenMesh, and wrap it in an `#ifdef`so that it can be deactivated as soon as OpenMesh supports hashing natively.

**Comment by OlegJakushkin** [comment]
It is still an open issue for OpenMesh users (e.g.  http://stackoverflow.com/questions/43557498/how-to-turn-a-surface-mesh-into-a-polyhedron/43571060#43571060) Is there a quick workaround?

**Comment by sloriot** [comment]
If you add the missing include directive `#include <CGAL/boost/graph/graph_traits_PolyMesh_ArrayKernelT.h>` it should work
