### ISSUE TITLE
The specializations of boost::graph_traits for OpenMesh meshes are not documented

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#1145]
http://doc.cgal.org/latest/BGL/group__PkgBGLTraits.html

Most of the specializations of `boost::graph_traits` are documented here. However, the ones for OpenMesh meshes, from `<CGAL/boost/graph/graph_traits_PolyMesh_ArrayKernelT.h>` and `<CGAL/boost/graph/graph_traits_TriMesh_ArrayKernelT.h>`, are not documented.

**Comment by lrineau** [comment]
@sloriot @afabri If you have little time, I think this issue is easy to fix.

**Comment by lrineau** [comment]
This bug, filled several months ago, was originally scheduled for CGAL-4.8.2. I have the impression that nobody even consider it as a bug, but me. Should we close it or let it be in the pool of unscheduled issues?

**Comment by afabri** [comment]
I can add a table, where all types that need a CGAL wrapper around an openmesh type are an `unspecified_type`, as in the long run the specialization of `boost:graph_traits`  should be in the OpenMesh library.  It is still reasonable to have it in the manual for the categories.

**Comment by lrineau** [comment]
Fixed by #1448.
