### ISSUE TITLE
degenerate faces in a polygon soup

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#1152]
I get a segfault with this [program](https://gist.github.com/afabri/f1fa1552e8421c95d35a52f471429d35).
It has a face with three identical vertex indices (as it may happen when reading STL data).

**Comment by sloriot** [comment]
@afabri  that would require a change in the API of `orient_polygon_soup` as we should be able to discard polygons (I guess it makes no senses to keep a polygon that have at least one degenerate edge). Do you agree?

**Comment by sloriot** [comment]
This can be solved by having a function filtering the range of input polygons. `PMP::filter_degenerate_polygons()` that will remove a polygon as soon as two vertex index are identicals

**Comment by sloriot** [comment]
A possible implementation can be found [here](https://github.com/sloriot/cgal/commit/1782e5cfdffe9117f973fed169bb53fd92a68a6f)

**Comment by sloriot** [comment]
`PMP::filter_isolated_vertices()` in a soup

**Comment by sloriot** [comment]
`PMP::filter_geometrically_degenarate_polygons()`
