### ISSUE TITLE
Mesh_3 plugin should be able to mesh surfaces with border  inside a closed polyhedral domain

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#1157]
Feature request: Load several meshes, potentially with borders) that are inside or that intersect a closed polyhedral domain, and create a tetrahedral mesh.

**Comment by lrineau** [comment]
I am working on something really close, today. I will contribute the feature back to CGAL.

**Comment by lrineau** [comment]
Will be address by @afabri in #2143...

**Comment by lrineau** [comment]
@afabri: I do not think that the PR #2143 solves this issue, because the PR does not modify the demo.

**Comment by janetournois** [comment]
I'm working on it

**Comment by lrineau** [comment]
Fixed in `master` (for 4.11), by #2200.
