### ISSUE TITLE
Polyhedron Demo untriangulate faces

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#1159]
It is not clear to me what it is supposed to do. 
![capture](https://cloud.githubusercontent.com/assets/3263539/16008606/04166958-3179-11e6-920f-901ab928343d.JPG)

And triangulate faces, does not give me a triangulated mesh.   @sloriot

**Comment by afabri** [comment]
There is no function such as `PMP::untriangulate_faces()`, that is the code is just in the plugin.

We should add code that avoids that a vertex is more than once on the border of a face to the untriangulate code.

As what we see is nevertheless a valid mesh, we have problably a bug in `PMP::triangulate_faces()` @janetournois

**Comment by sloriot** [comment]
Finding which edge to remove to get a quad mesh from a triangle mesh is what is done by the quad-blossom algorithm and it requires a perfect-matching (that does not existing for an arbitrary triangle mesh). In may opinion this plugin should be removed.

**Comment by janetournois** [comment]
the plugin generates faces with more that 4 vertices, actually

**Comment by afabri** [comment]
I guess all we have to do is to add the test that the join does not make a vertex appear twice on the border.  Asymptotically not a good algorithm, but not a practical problem. 

I added you, Jane, as  `PMP::triangulate_faces()` seems not to be complete.

**Comment by sloriot** [comment]
I suggest we remove this plugin. @afabri  do you agree?

**Comment by afabri** [comment]
I agree.

**Comment by sloriot** [comment]
@maxGimeno  Could you take care of that?
