### ISSUE TITLE
Polyhedron Demo: Operations->Operations on Polyhedra -> Clip Polyhedra

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#1163]
Feature Request:  When not closed it would be nice if the segments on the clip plane would be put into a selection for  further processing.  @maxGimeno

**Comment by sloriot** [comment]
@afabri what application do you have in mind?

**Comment by afabri** [comment]
for example hole filling with something  nicer than just huge triangles. But it is not am important feature request.

**Comment by sloriot** [comment]
Hole filling will itself select the boundary edges so I think this issue can be closed.
