### ISSUE TITLE
Timeout in a test/Intersections_3/test_intersections_3.cpp

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#117]
Our daily testsuite (private for developers) shows a new problem in `master`: https://cgal.geometryfactory.com/CGAL/Members/testsuite/CGAL-4.7-I-52/Intersections_3/TestReport_lrineau_x86-64_Linux-Fedora19_llvm-clang-with-g++-4.8.gz

The test `test_intersections_3` on that platform is too long and is killed after 20 minutes.

**Comment by lrineau** [comment]
Nobody seems interested by that bug. I remove it from 4.7.

Meanwhile, I have discovered that the timeout occurred since CGAL-4.5. I think commit 9353573dec248f7cc7aa8ccc3b7f90f2130714a0 introduced the bug.

**Comment by sloriot** [comment]
Fixed by d77da3f15bb507185e80611c4ca92e530f417036: now the ratio is 10.
