### ISSUE TITLE
Bugs in Shortest_path 

### ISSUE THREAD

**Issue by maxGimeno** [CGAL/cgal#1179]
There are several bugs in the Shortest_path computation :

- When a source point is put on an edge, depending on where the request has been made, the shortest path might be wrong (see picture below).
![screen_path](https://cloud.githubusercontent.com/assets/11310805/16079440/e714158a-3303-11e6-842b-e19bbcc2db88.png)

- When the request and the source point are on the same edge, there is an assertion (see picture below).
![screen_path1](https://cloud.githubusercontent.com/assets/11310805/16079473/09092f68-3304-11e6-8015-dd31c0a6d868.png)

I think the problem is located in Surface_mesh_shortest_path/include/CGAL/Surface_mesh_shortest_path/Surface_mesh_shortest_path.h, in the function visit_shortest_path(Cone_tree_node* startNode, const Point_2& startLocation, Visitor& visitor) (line 1545)

**Comment by sloriot** [comment]
@Hippocrates do you want to fix it or shall I do it?

**Comment by Hippocrates** [comment]
I'll take a look at it this weekend. I'm suspecting that these two issues have a similar root cause.
