### ISSUE TITLE
Add Surface_mesh<P>::Point_iterator

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#118]
Polyhedron_3 has such an iterator.

In fact requested by a user.

**Comment by lrineau** [comment]
Could it be considered as a bug fix for CGAL-4.6.1? I plan to release CGAL-4.6.1 by the end of this week.

**Comment by lrineau** [comment]
You have opened an issue. Should not it be a pull-request instead?

**Comment by bo0ts** [comment]
Good feature. I think I did not add this because when `Property_map` was still documented it was obvious how to get this It is basically:

    Surface_mesh<P> sm;
    Property_map<P> prop = sm.points();
    const P* begin = prop.data();
    const P* end   = prop.data() + sm.number_of_vertices();

Now, this isn't possible anymore and we might want to consider adding a function that can turn each `Surface_mesh` property map into a range.

**Comment by afabri** [comment]
Note that accessing data does not skip deleted vertices.
Also I am wondering if we do not want a generic wrapper. Just as the Vertices_around_face_iterator works for any FaceGraph by calling next(), we could have basically a (https://gist.github.com/afabri/6a77a8d8a3f4ddd18aba)[transform iterator]

**Comment by lrineau** [comment]
Why was that issue closed? Is is fixed? Was the issue somehow invalid? I need to know to add labels to the bug.

**Comment by afabri** [comment]
closed by accident, as not closed at all.

**Comment by bo0ts** [comment]
We can perform the check for a removed with `is_removed`, a manually constructed `Vertex_index`, and by storing a reference to the `Surface_mesh`. That would be almost the same as using an `Index_iterator` + `Property_map` to build this iterator.

While those are safer I think that having fast iteration (and continuous storage guarantees!) over properties is a really nice feature, that came in handy when building Surface_mesh demos. So we might want to implement the fast version of that iterator and make `!sm.has_garbage()` a precondition.

**Comment by afabri** [comment]
The person who had contacted me, explicitly mentioned that he removed elements.

**Comment by bo0ts** [comment]
Would it be out of the question to call `collect_garbage` before the operation? Maybe both ranges (`point_range`/`raw_point_range`) and the corresponding general wrapper would be a satisfactory solution.

**Comment by afabri** [comment]
out of question as it may invalidate "pointers" stored in properties.

**Comment by visorz** [comment]
Thank you for looking for a solution to such a feature. A suggested transform_iterator by A. Fabri works for CGAL::centroid( ) but not for CGAL::bounding_box( ). It would be great, if you had a solution / workaround for that, too. Here is the [MWE Gist](https://gist.github.com/visorz/a6e1f6a2e3ded3519109)

**Comment by bo0ts** [comment]
@visorz That is not a CGAL issue. Your functor has a reference member and hence no assignment operator can be generated by the compiler. The `bounding_box` function makes assignments between iterators and this makes your code fail. Instead of storing a reference you can store a raw pointer or a `boost::reference_wrapper`. Please see this gist: https://gist.github.com/bo0ts/eb5c58e138f3e120aeb5

**Comment by visorz** [comment]
Thank you alot for your explanation and fix. The version I am using to iterate over points equally on Polyhedron_3 and Surfacemesh is [here](https://gist.github.com/visorz/7061fd1be9377e79dc08). It does not work with BOOST_FOREACH macro but I don't use that anyway.

**Comment by sloriot** [comment]
@afabri What is the status of this issue?

**Comment by sloriot** [comment]
@afabri Status?

**Comment by afabri** [comment]
no idea.

**Comment by bo0ts** [comment]
IMO this is solved by using a transform_iterator. @visorz simply had an implementation issue.
