### ISSUE TITLE
Segmentation fault in Polyhedron_3::split_edge

### ISSUE THREAD

**Issue by agodde** [CGAL/cgal#1188]
In the example Polyhedron/polyhedron_prog_cube.cpp: Using the halfedge data structure HalfedgeDS_vector instead of HalfedgeDS_default for the Polyhedron_3 type results in a segmentation fault in a call to the function split_edge(Halfedge_handle h).

The attached gist contains the example with a simple change of line 32 from

typedef CGAL::Polyhedron_3<Kernel> Polyhedron;

to

typedef CGAL::Polyhedron_3<CGAL::Polyhedron_traits_3<Kernel>,
                                                CGAL::Polyhedron_items_3,
                                                CGAL::HalfedgeDS_vector> Polyhedron;

(plus the include for HalfedgeDS_vector.h)

[polyhedron_prob_cube.cpp with HaldedgeDS_Vector](https://gist.github.com/agodde/e1e3eeb03babf459cc60d0498449cf72)

**Comment by sloriot** [comment]
From [here](http://doc.cgal.org/latest/HalfedgeDS/classCGAL_1_1HalfedgeDS__vector.html) : <i>The capacity is restricted to the reserved size. Allocations are not possible beyond the capacity without calling reserve again. All handles and iterators are invalidated upon a reserve call that increases the capacity</i>.

**Comment by sloriot** [comment]
Calling `P.reserve(22,22,22);` fixes the segfault.

**Comment by agodde** [comment]
Shouldn't this be mentioned in the documentation of Polyhedron_3 since it changes how one can use the Euler split operations?

**Comment by sloriot** [comment]
Well, IMO it's more a property of `HalfedgeDS_vector` that is used as implementation for `Polyhedron_3` (which is just a wrapper around it). I tend to think that if one picks up a non default parameter, he should refer to the doc of that parameter. BTW I observe an issue in `is_valid()` so there must be another issue.

**Comment by agodde** [comment]
What issue in `is_valid()` are you talking about? The `CGAL_precondition(P.is_valid())` macro succeeds for me.
