### ISSUE TITLE
Read OFF files with colors, or with color maps

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#119]
I would like that the polyhedron demo is able to read an OFF file for which facets have:
  - either an integer
  - or a color.

That is a feature that is in the [OFF file format documented on the GeomView web site](http://www.geomview.org/docs/html/OFF.html).

**Comment by sloriot** [comment]
cc @maxGimeno

**Comment by lrineau** [comment]
Andreas already has a branch on that topic. @afabri
