### ISSUE TITLE
Extending ROI/Control vertices partially working

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#1197]
![screenshot from 2016-06-23 13-26-00](https://cloud.githubusercontent.com/assets/1224632/16301683/fa166036-3946-11e6-8661-119481a021e1.png)

I selected the ROI and then only one control point. I used the mouse wheel to extend the region.

In the package, note that the ROI is the region that is allowed to move, and they contains the control vertices.

cc @maxGimeno

**Comment by maxGimeno** [comment]
This is the expected behaviour. The wheel event adds vertices of the
selected type in the radio-buttons. In your example, if you want ROIs
instead of Controls,  you have to select ROI before movig the wheel.

2016-06-23 13:34 GMT+02:00 Sebastien Loriot <notifications@github.com>:

**Comment by sloriot** [comment]
No I wanted the set of control vertices to be expended, that is the one-ring neighborhood of the control vertex selected should have been selected
