### ISSUE TITLE
Infinite loop during CGAL::Delaunay_triangulation_3

### ISSUE THREAD

**Issue by cdcseacave** [CGAL/cgal#120]
Re-posting this issue here, as on stackoverflow I found no help:
http://stackoverflow.com/questions/30648926/infinite-loop-during-cgaldelaunay-triangulation-3

Any suggestions would be greatly appreciated!

Thank you!

**Comment by lrineau** [comment]
The bug was invalid. It was actually a bug in @cdcseacave code. The issue and solution was [found by @afabri, and explained on StackOverflow](http://stackoverflow.com/a/30849264/1728537).
