### ISSUE TITLE
Contribute Mesh_3/Sizing_field_with_aabb_tree.h to CGAL

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#1200]
`Sizing_field_with_aabb_tree` was introduced in the experimental package "Mesh_3-protecting_balls-branch" in the old SVN repository. See CGAL/cgal-attic@d502917981b48624fec0091ff929ff061d43857e and previous commits.

**Note:** the current implementation uses `domain.signed_geodesic_distance(..)`, that is not part of the concept `MeshDomainWithFeatures_3`.

**Comment by lrineau** [comment]
Note to myself: The more recent version is `~/Git/*/src/nurbsMRepX/include/CGAL/Mesh_3/Sizing_field_with_aabb_tree.h`.

**Comment by janetournois** [comment]
Since PR #1893, the more recent version is in `CGAL/Mesh_3/experimental`
