### ISSUE TITLE
Demo mesh_3_plugin: display the meshing parameters in the "info" of the created c3t3 item

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#1202]
When one mesh something (3D image, polyhedron), the terminal displays, for example:
```
Meshing file "anchor"
  angle: 25
  edge size bound: 0.071999999999999995
  facets size bound: 0.025000000000000001
  approximation bound: 0
  tetrahedra size bound: 0.071999999999999995
```

Can this be copied in the "tooltip info" of the c3t3 item that is created?

**Comment by janetournois** [comment]
it could also appear in the "statistics" right-click menu of the c3t3 item
