### ISSUE TITLE
Polyhedron demo : save snapshot broken

### ISSUE THREAD

**Issue by janetournois** [CGAL/cgal#1208]
- open anything you like in polyhedron demo
- do File -> save snapshot
- open the image in your favorite viewer : it's all gray

@maxGimeno can you please have a look at this? we really need it to prepare slides

**Comment by janetournois** [comment]
I just post a snapshot to illustrate the issue. A quick zoom shows that the screen resolution is not enough. ![cube_with_constraints](https://cloud.githubusercontent.com/assets/11311305/16485922/d8a53528-3ec1-11e6-959c-fa0304452cd4.png)

**Comment by lrineau** [comment]
I agree that a snapshot of the screen is not enough. There should be way a to snapshot different tiles of the screen in a higher resolution, and then combine them in a hi-res image. The mechanism used by QGLViewer is a good. Maxime (@maxGimeno) should find a way to adapt the QGLViewer code to our newer way of using projections matrices.
