### ISSUE TITLE
Generation of a selection item

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#1210]
@maxGimeno : When a polyhedron item is selected, and when the widget of the selection tool is displayed, but no selection item created, the selection item should be created automatically when I make, for example, a sharp angle selection. That is there should be no need for me to first click on the button "Create Selection Item".

**Comment by sloriot** [comment]
@afabri  remember that for technical reason it is not possible to do it for operations involving the mouse (selecting a simplex). However, any operation that is inside the dock widget is indeed possible.
