### ISSUE TITLE
Instancing a CGAL::Transformation of type Reflection does not work

### ISSUE THREAD

**Issue by amineBach** [CGAL/cgal#1216]
Hello,

The instanciation of an Reflection does not seem to work.

```
#include <QCoreApplication>

#include <CGAL/Cartesian.h>
#include <CGAL/Aff_transformation_2.h>
typedef CGAL::Cartesian<double> Kernel;
typedef CGAL::Aff_transformation_2<Kernel> Transformation;

int main(int argc, char *argv[])
{
    QCoreApplication a(argc, argv);

    Transformation rational_rotate(CGAL::ROTATION,  1, 100); //OK
    Transformation translate(CGAL::TRANSLATION, CGAL::Vector_2<Kernel>(-2, 0)); //OK

    CGAL::Point_2<Kernel> A( 1, 2);
    CGAL::Point_2<Kernel> B( 3.0, 4.0);

    CGAL::Line_2<CGAL::Cartesian<double> > AB(A,B);
    Transformation Refl(CGAL::REFLECTION, AB); //KO

    return a.exec();
}
```

**Comment by sgiraudot** [comment]
Reflections are not supported by `CGAL::Aff_transformation_2` (see [the list of constructors on the official documentation](http://doc.cgal.org/latest/Kernel_23/classCGAL_1_1Aff__transformation__2.html#a47f305715cb75778048ea7329b5c02dc), only constructors for rotations and translations are provided).

**Comment by tilsche** [comment]
Why not keep it open as a feature request? This would have been very useful for me some time ago.

**Comment by sgiraudot** [comment]
Alright, I'm reopening it.
