### ISSUE TITLE
Segmentation fault when adding constraint into CDTPlus

### ISSUE THREAD

**Issue by petersadro** [CGAL/cgal#122]
Hello,

I've based my triangulation on the polygon_2 example in the documentation.
I've run into a segfault that happens very rarely, but I've found a simple repro case.

Am I giving the algorithm incorrect data?  I see a segfault when inserting the 4th constraint.  Some of them are very near parallel.  I've checked using Line_2 using the constraint endpoints, and they are just nearly parallel.

This data is from the 57,778th polygon.  All previous were successful.

My test program, data file, and backtrace are in the following gist:
https://gist.github.com/petersadro/1a3b2ade8e7bc660aed9

**Comment by lrineau** [comment]
Seems a valid bug:
* a `CGAL::Constrained_triangulation_plus_2<CDT_2>`
* `CDT_2` uses the exact-exact kernel, and the `CGAL::Exact_intersections_tag `.
It should not crash.

**Comment by lrineau** [comment]
@afabri: the segfault happens in new lines added by the branch `Triangulation_2-NewPolylineConstraint-GF`, merged Jan 2015 in `master`. The bug can be reproduced, at least on my machine, using a build of `master` as `CGAL_DIR`.

I have forked and modified the Gist: https://gist.github.com/lrineau/a85b0cb62cb881513f29
The modifications are:
  - add proper extensions to files,
  - add a file `CMakeListst.txt`

**Comment by lrineau** [comment]
Hi @petersadro. Andreas has found a fix for that bug: in the commit c80a9aa.

That commit will be tested tonight, and hopefully merged in the branch `releases/CGAL-4.6-branch` tomorrow.

I hope to publish the bug-fix release CGAL-4.6.1 next week.

**Comment by lrineau** [comment]
@petersadro What is the license of your test program and data? Can we integrate them in CGAL? If you agree, please say that you agree that we license those files under GPLv3+.

**Comment by petersadro** [comment]
Yes, the test program is of my own writing - based on the CGAL examples.  
You can incorporate and license it under GPLv3+.

Thanks for the fast turnaround.  I will pull 4.6.1 once it's labeled.  Thank you

**Comment by lrineau** [comment]
Fixed by #126.
