### ISSUE TITLE
Apply point set algorithms on a selection

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#1230]
This is a feature request.   @sgiraudot should have a look how that can be done with his new Point_set class under development.

**Comment by sgiraudot** [comment]
This is developed in feature branch [Polyhedron_demo-Point_set_algorithms_on_selection-GF](https://github.com/CGAL/cgal-dev/tree/Polyhedron_demo-Point_set_algorithms_on_selection-GF).

**Comment by lrineau** [comment]
If the branch is ready for a pull request, there is still a chance that it is integrated in CGAL-4.9-beta.

**Comment by lrineau** [comment]
Fixed by #1283.
