### ISSUE TITLE
VCM Features Estimation

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#1234]
It is applicable to point sets, but it is not clear what it does. The popup  widget mentions "Normals" what it does not do at all. The parameters should be explained. Do the parameters have reasonable initial values.  @sgiraudot  Please fix that before Siggraph.

**Comment by sloriot** [comment]
It creates polylines that are sharp features in the point set.

**Comment by lrineau** [comment]
@sgiraudot Are you working on this issue?

**Comment by sgiraudot** [comment]
It's done here: https://github.com/CGAL/cgal/pull/1297

The plugin creates a point set item of points estimated to be on the sharp feature which is explained in the manual along with the parameters.

**Comment by lrineau** [comment]
I have merged the trivial PR #1297 that fixes this issue.
