### ISSUE TITLE
assertion violation using cgal with openscad

### ISSUE THREAD

**Issue by pilloutche** [CGAL/cgal#1237]
when i tried to make a difference between 2 objects into openscad (one complex stl object with one cube() structure), the cgal returned an error (into openscad console output) : 

[...]
Compiling design (CSG Tree generation)...
Rendering Polygon Mesh using CGAL...
ERROR: CGAL error in CGALUtils::applyBinaryOperator difference: CGAL ERROR: assertion violation! Expr: itl != it->second.end() File: /opt/mxe/usr/x86_64-w64-mingw32.static/include/CGAL/Nef_3/SNC_external_structure.h Line: 1102 
Geometries in cache: 4
Geometry cache size in bytes: 3639488
CGAL Polyhedrons in cache: 1
CGAL cache size in bytes: 64860608
[...]

I followed the file  cgal/Nef_3/include/CGAL/Nef_3/SNC_external_structure.h
there is an assertion violation on line 1149 (not line 1102 or i use an old version of the source and the bug is perhaps already corrected)

Perhaps it could help to debug some error on the source program...

**Comment by sloriot** [comment]
Hard to tell what's wrong without seeing the calling code nor the input data.

**Comment by sgiraudot** [comment]
This issue can't be fixed without seeing the calling code. Please reopen it if you are willing to share some piece of code that can help fix it.
