### ISSUE TITLE
PMP::triangulate_hole() fails on holes that have zero-area spikes.

### ISSUE THREAD

**Issue by efifogel** [CGAL/cgal#1238]
The function fails to triangulate holes that have zero area spikes.
In particular, it fails to triangulate holes that have zero areas.
It even fails to triangulate zero-area triangles.

I haven't checked the other variants, namely,  triangulate_and_refine_hole(), and triangulate_refine_and_fair_hole(); they should be checked as well.

While less desired, you may want to consider retaining this limitation, but document it. That is, explicitly state that holes that have zero area spikes are not supported. (Consider a better description though...)

I have some off files that demonstrate the problem, but I cannot upload them for some reason. (The system rejects my attempts with "Something went wrong...".

I also have a program that triangulates all holes of a polyhedron. I cannot seem to upload it either...

**Comment by janetournois** [comment]
Hi Efi,
thanks for your report.

I will have a look at the issues you mention. Can you please try to send me your data by email directly?

**Comment by efifogel** [comment]
Hi Jane,

Attached are 4 simple off files.
The first 3 have holes with zero area.
The 4th has a hole that is a polygon with spikes (1 dimensional features).

Attached also is a simple program that successfully handles such irregular
holes.
It iterates over border halfedges. When the halfedge borders a spike, it
only introduces a triangle, not necessarily triangulating the entire hole.
As new halfedges are added to the list of halfedges as the traversal
advances, all holes are eventually triangulated.

Efi

   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by afabri** [comment]
Hi Efi. It's great to get your real-world input, and we will work on it.

Unless I am wrong the current implementation assumes that the polyline describing the hole is not self-intersecting.  So even a sequence as (0,0), (1,0), (1,1), (0.5,0) (0,1) (0,0) probably fails.
So one might first detect the intersections, which splits the hole in several holes.

**Comment by janetournois** [comment]
Hi Efi,

I have just added something to the documentation of `PMP::triangulate_hole()`.

However, it would be nice to implement what you asked, and I would like to have your input data to test it. I could not download them. Can you please re-send them, via github or private email?
Thank you!

Jane.
