### ISSUE TITLE
line_2 and segment_2 intersection return wrong result

### ISSUE THREAD

**Issue by PhucDL** [CGAL/cgal#1243]
I have a cgal line: line = (-0.0322768, -616704, -4.09592e+008), 
and a segment: seg = (-224.382, -1311.43) (-224.382, -623.426).

then I perform intersection between those two:
CGAL::cpp11::result_of<Intersect_2(Line_2, Segment_2)>::type
				intersect_point = intersection(line, seg);

the result intersection_point is NULL (it should be point_2 (-224.382, -664.162) )

**Comment by sloriot** [comment]
What kernel are you using?

**Comment by PhucDL** [comment]
I'm new to CGAL, so by kernel you mean something like this : CGAL::Simple_cartesian<double> ?

**Comment by sloriot** [comment]
yes

**Comment by PhucDL** [comment]
Sorry, the tag in previous comments got ommited by github, here is my full code:
`typedef CGAL::Simple_cartesian<double>		K;`
`typedef K::Segment_2						Segment_2;`
`typedef K::Line_2							Line_2;`
`typedef K::Intersect_2						Intersect_2;`
and my intersection code:
`CGAL::cpp11::result_of<Intersect_2(Line_2, Segment_2)>::type
				intersect_point = intersection(line, seg);`

**Comment by sloriot** [comment]
If it works when using CGAL::Exact_predicates_exact_constructions_kernel instead of CGAL::Simple_cartesian<double>, then read http://www.cgal.org/FAQ.html#inexact_NT

**Comment by PhucDL** [comment]
I tested and it worked fine, thank you very much !
