### ISSUE TITLE
Documentation bug for boost::graph_traits<Polyhedron_3>

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#1251]
The documentation of specializations of `boost::graph_traits`, for 4.8.1, are in [the documentation page of the group `PkgBGLTraits`][PkgBGLTraits].

[PkgBGLTraits]: http://doc.cgal.org/4.8.1/BGL/group__PkgBGLTraits.html

There is a bug, in a description of two iterator types, for `Polyhedron_3`:

  Member              |             Value
------------------------|----------------------------------
halfedge_iterator  |  Polyhedron_3::Halfedge_iterator
face_iterator         |  Polyhedron_3::Face_iterator

It cannot be true, because the value types of the iterators of the polyhedron are not descriptors but directly the pointed type.

**Comment by sloriot** [comment]
Fixed by 4c4e5b384fe05d374b5ccf910aa7a8b28567357d

**Comment by afabri** [comment]
damned. assigned to 2 people who immediately fix it.
