### ISSUE TITLE
Isotropric remeshing: Why must face_index be an internal property?

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#1256]
I wonder why you request it to be an internal property and not an optional named parameter?

**Comment by janetournois** [comment]
Actually, it is used only internally by `PMP::connected_components()`, which is itself computed iff the `face_index_map` is not provided.
It could be added as an additional named parameter, indeed. Do you think it would be better?

**Comment by sloriot** [comment]
If we stay with the internal property, then the default Polyhedron cannot be used, right?

**Comment by janetournois** [comment]
Sounds right... The internal `face_index` map should be initialized, as said in the documentation, and done in the demo... There is no internal `face_index` map in the default Polyhedron, right?
The best version could be that is there is no internal map, nor a `face_index_map` provided as in `PMP::connected_components()`, then a basic default one is built internally.

**Comment by sloriot** [comment]
I agree
