### ISSUE TITLE
AABB tree plugin crashes

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#1278]
probably because my model has zero length edges, that is zero area faces.  We should only put non-zero faces in the AABB tree.  @sloriot  Do you agree?

**Comment by sloriot** [comment]
in the demo we can indeed use a filter iterator.

**Comment by afabri** [comment]
@maxGimeno   Can you please fix that before Siggraph.

**Comment by lrineau** [comment]
Something similar has already been done in PR #1102, so that the AABB_tree used in the Surface_mesh_segmentation does not crash with degenerated faces.
