### ISSUE TITLE
Add light display on point sets with normals in Polyhedron demo

### ISSUE THREAD

**Issue by sgiraudot** [CGAL/cgal#1282]
When point sets have normals, a better and clearer display can be done using light (similarly to a polyhedron).

(@maxGimeno If you add this to your todo-list, this is [the commit](https://github.com/CGAL/cgal-dev/commit/455843e1bf01faf87eda7994b4c715d7ea173b6d) where we worked on it together last time, although you can't use it directly because it modifies other unrelated files – sorry about that, I should have separated it.)

**Comment by lrineau** [comment]
Thanks Simon.

**Comment by lrineau** [comment]
@maxGimeno That is a low-priority issue.
