### ISSUE TITLE
add option for decreasing meshing verbosity

### ISSUE THREAD

**Issue by nschloe** [CGAL/cgal#1286]
When meshing tets (cf [Mesher_3](https://github.com/CGAL/cgal/blob/master/Mesh_3/include/CGAL/Mesh_3/Mesher_3.h)), lots of output is put to `std::cerr`, e.g., [here](https://github.com/CGAL/cgal/blob/master/Mesh_3/include/CGAL/Mesh_3/Mesher_3.h#L398). The verbosity can partly be controlled at compile time.

It's be awesome if there was a runtime parameter for setting the verbosity (in particular turning off all non-error output); cf. [this mshr bug](https://bitbucket.org/fenics-project/mshr/issues/52/unwanted-output-while-meshing-a-sphere).

**Comment by lrineau** [comment]
If I understand well, `mshr` defines the macro `CGAL_MESH_3_VERBOSE` to 1, to turn on the verbose displays on `std::cerr`. And this issue is about the possibility to turn them off again at runtime, even with `CGAL_MESH_3_VERBOSE` defined to 1?

That makes sense. Would you suggest an API for that?

**Comment by sloriot** [comment]
if `CGAL_MESH_3_VERBOSE` is defined you could have a set of free functions with static variables inside to change the verbosity level and also change the stream the output is put in.
