### ISSUE TITLE
Signed distance  

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#1288]
When computing the signed distance for the points on a cutplane to a model there are some points with a suspicious color.
![capture](https://cloud.githubusercontent.com/assets/3263539/16985598/d6f71b0e-4e81-11e6-9b3c-336c0e1c9a1f.JPG)

When I move the cutplane slightly they disappear. I am wonderung if that is due to the usage of Simple_cartesian instead of Epic.  What do you think @sloriot

**Comment by sloriot** [comment]
With or without tbb? you can also try compiling with epic to be sure the cut_plugin

**Comment by lrineau** [comment]
Andreas, please give a way to reproduce the error. Can it be reproduced with the `elephant.off` data file?

**Comment by lrineau** [comment]
The data set is probably not a closed surface, and the inside-outside of it is not well defined. That may explain why the sign of the distance is locally not right.
Maxime (@maxGimeno) will prepare a PR that warns the user when the function is applied to a polyhedron with holes.
