### ISSUE TITLE
jet smoothing for points with normals does not work

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#1306]
In the polyhedron demo
- load   *.xyz
- jet smoothing does something  OK
- estimate normals  OK
- jet smoothing does something  NO

@maxGimeno please fix

**Comment by maxGimeno** [comment]
@afabri can you please be more specific ? I reproduced your steps and nothing seems wrong to me. Is this the normals disappearance ?

**Comment by afabri** [comment]
There is  no reason for not applying smoothing to points with normals.

**Comment by maxGimeno** [comment]
It is applied.

2016-07-27 17:18 GMT+02:00 Andreas Fabri <notifications@github.com>:

**Comment by lrineau** [comment]
Yesterday, we have tried to apply the smoothing to points with normals, and it worked: we got a smoothed points set, without normals.

**Comment by lrineau** [comment]
Without further precision, I close this bug because it really worked for us.

Reopen the bug with details if you will have a bug.

**Comment by afabri** [comment]
I cannot reproduce it in master. Probably I did something wrong. Sorry.
