### ISSUE TITLE
Rendering mode for point sets with normals

### ISSUE THREAD

**Issue by palliez** [CGAL/cgal#1311]
For point sets with normals the "points" mode depicts shaded points. 
It may be relevant to add another "raw points" to depict the unshaded points.

**Comment by lrineau** [comment]
That "shaded points" (points with lightning, depending on their normal) is a very new feature of the demo. I agree there should be an extra drawing mode, that displays the point like they were previously.

@sgiraudot @maxGimeno

**Comment by afabri** [comment]
Can you at the same time add the possibility to change the point size.

**Comment by lrineau** [comment]
> Can you at the same time add the possibility to change the point size.

I have created #1320. Let's not use the same issue entry for different feature requests, because that prevent the proper tracking of issues/requests.

**Comment by lrineau** [comment]
This issue has been fixed by the merge of #1323. Thanks, Maxime.
