### ISSUE TITLE
Snapshot to clipboard

### ISSUE THREAD

**Issue by palliez** [CGAL/cgal#1314]
Very nice-to-have feature: copy current client to clipboard, with transparent background. So that we do not need to go through files and quickly prepare image layouts in ppt or keynote. 

Note: the current shortcut ctrl+c overrides this function from qglviewer. this means one should verify whether qglviewer does this already with transparent background or not.

**Comment by lrineau** [comment]
@maxGimeno That is related to #1244.

*Note that this feature request is of lower priority than the dockerization of our wiki.*
