### ISSUE TITLE
Affine transform applicable to point sets

### ISSUE THREAD

**Issue by palliez** [CGAL/cgal#1315]
It would be good to be able to apply the affine transform to point sets. 
Note also that I was not able to see how to specify the said transform.

**Comment by maxGimeno** [comment]
If everything wworks fine, this plugin adds a green wireframe item of the selected polyhedron_item, that you can manipulate with Ctrl and the mouse (just like a cutting plane). Once you set it to the desired position, you go to the Operations menu and validate it, which will replace the wireframe item by a new polyhedron_item.

 What was your problem exactly ?

**Comment by lrineau** [comment]
@maxGimeno You talk about polyhedron items but Pierre would like to apply an affine transformation to a *points set* item.

**Comment by maxGimeno** [comment]
@lrineau I know but the second part of the message was a bug report, unless I misunderstood.
