### ISSUE TITLE
Normalize

### ISSUE THREAD

**Issue by palliez** [CGAL/cgal#1316]
In addition to affine transform: it would be good to be able to normalize a point set of mesh in a unit box while keeping aspect ratio (so that max coord. extend is 1).

**Comment by lrineau** [comment]
That could be a local action to the point set item: "Normalize coordinates in [0, 1]".

... Or that could be an global action of the affine transformation plugin: whatever is the selected item (surface mesh, polyhedron or point set), normalize its coordinates. That could be useful too.

**Comment by afabri** [comment]
I see that in the affine transformation. It could at the same time have buttons for turning by 90 degree, mirroring, scaling, what I cannot do with the mouse.

**Comment by lrineau** [comment]
The affine transformation plugin could have a widget that:
  - displays the transformation matrix, if the transformation is done using the mouse movements,
  - allow to enter or modify that matrix,
  - also have a set of buttons to enter predefined transformations:
   - rescale to [0,1],
   - predefined rotations and symetries.

**Comment by lrineau** [comment]
Fixed by #1565.
