### ISSUE TITLE
Mesh smoothing

### ISSUE THREAD

**Issue by palliez** [CGAL/cgal#1317]
It is possible to fair - but this requires constraining vertices. 
does it make sense to add a menu for smoothing? Laplacian with or without volume preserving, with feature preserving (aniso smoothing) when detected.

**Comment by lrineau** [comment]
@janetournois Can you comment?

@palliez I must admit I have not fully understood. Can you be a bit more specific?

**Comment by janetournois** [comment]
I absolutely makes sense, but it's a lot more work than adding a menu. 
The `Polygon_mesh_processing::fair()` function requires those constrained points.

I would like to add all the state-of-the-art surface mesh smoothing methods to the PMP package and add them to the demo.

**Comment by janetournois** [comment]
There is a chance we can work on this in 2017. Do you have more suggestions of published/state-of-the-art/prototype code that we would like to have published in CGAL?
Thanks for your input!

**Comment by lrineau** [comment]
Follow-up: it will be [proposed as a GSoC subject in 2017][1]. Let's hope CGAL will be accepted as a GSoC organization this year.

[1]: https://cgal.geometryfactory.com/CGAL/Members/wiki/GSoC_2017/GSOC17_draft_Project#Mesh_Smoothing_and_Shape_Smoothing

**Comment by sgiraudot** [comment]
Was this project accepted for the GSoC this year?

**Comment by afabri** [comment]
Yes. See [here](https://summerofcode.withgoogle.com/organizations/5926060504907776/#4839851680595968).  The mentor is @janetournois

**Comment by sgiraudot** [comment]
Good news!
