### ISSUE TITLE
Intallation documentation: fix TTB-related instructions for non-Windows systems

### ISSUE THREAD

**Issue by cjamin** [CGAL/cgal#1326]
It seems the [TBB installation instructions](http://doc.cgal.org/latest/Manual/installation.html#title56) are not correct for non-Windows systems. For example, the compiled libs are not in `bin` but in `lib`. Here are [more information coming from TBB documentation](https://www.threadingbuildingblocks.org/docs/help/tbb_userguide/Linux_OS.html). Could any Linux guy check all this and fix the documentation, please?

**Comment by janetournois** [comment]
@cjamin has this been fixed since you posted the issue?

**Comment by cjamin** [comment]
No, I don't think so.

**Comment by janetournois** [comment]
ok!
