### ISSUE TITLE
URL with fragments are not working in the cgal-dev wiki

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#1327]
The conversion from Mediawiki to Github Wiki has not preserved the internal links of a page (links to fragments). For example, at https://github.com/CGAL/cgal-dev/wiki/Guidelines-Directory_Structure_for_Packages, the link "below" does not work. There are other links in the same page. The name of fragments seem all wrong.

**Comment by akobel** [comment]
Fixed (for that particular site and https://github.com/CGAL/cgal-dev/wiki/Guidelines-Source_Code_Management_GIT). General observations:
- fragments should be checked for - vs _
- ../ links went astray
- some other completely off links where I did not notice (or pay attention for) a straightforward pattern
