### ISSUE TITLE
the directory structure introduced in the wiki is outdated

### ISSUE THREAD

**Issue by MoniqueTeillaud** [CGAL/cgal#1329]
our wiki page Guidelines-Directory_Structure_for_Packages
says: "The directory structure of a package named Package should be as follows:"
        and it shows demo/ as a directory
and below: "demo/ contains the demo programs for the package.” 
(That page does not mention GraphicsView.)

But Triangulation_2/demo/Triangulation_2 does not contain the demo programs for Triangulation_2. So the info given in the developers wiki is wrong. 
As you explained, the demos are in GraphicsView instead, which no developer has a chance to learn when looking at this wiki page.

**Comment by maxGimeno** [comment]
I edited the [demo-subdirectory](https://github.com/CGAL/cgal/wiki/Directory-Structure-for-Packages#demo-subdirectory) to specify the difference between 3D packages and 2D packages.

**Comment by janetournois** [comment]
@sloriot what is the next task for that issue?

**Comment by sloriot** [comment]
I don't know,

**Comment by MoniqueTeillaud** [comment]
IMHO, the update makes the page better than it was, but the new page is still not crystal clear. 
This is what readers see, in order:

1- Section https://github.com/CGAL/cgal/wiki/Directory-Structure-for-Packages#directory-structure says: 
" The directory structure of a package named Package **should** be as follows:
... +--- demo/<demodir>/ ..." 

2- Then https://github.com/CGAL/cgal/wiki/Directory-Structure-for-Packages#demo-subdirectory explains the contents of demo/

3- Then suddenly a surprise: "Note that if 3D packages have their own demo directory, 2D packages have theirs located in GraphicsView/demo/."
So he discovers after reading a few screen pages that what was introduced above was not true... 
 
It would be better to introduce the true directory structure from the beginning.

**Comment by maxGimeno** [comment]
I moved the new phrase : 
[demo-subdirectory](https://github.com/CGAL/cgal/wiki/Directory-Structure-for-Packages#demo-subdirectory)

**Comment by MoniqueTeillaud** [comment]
The section Directory structure
https://github.com/CGAL/cgal/wiki/Directory-Structure-for-Packages#directory-structure
should be fixed. 

Note: I don't receive notifications any more, though I am subscribed to this issue. I onlt came here by chance. Is it because it was "closed"?  
In any case, it should be re-opened.

**Comment by lrineau** [comment]
Let's reopen the issue, and close it only once everybody is happy with the wording.

**Comment by maxGimeno** [comment]
I added a (Only for 3D Packages) on the demo line in the structure. (see [directory-structure](https://github.com/CGAL/cgal/wiki/Directory-Structure-for-Packages#directory-structure)).

**Comment by MoniqueTeillaud** [comment]
Now the danger is that people developing 2d simply ignore demos, if they are "only for 3d packages"... 

I would prefer to remove this note in the list of subdirectories. Instead, add a few words in the paragraph that introduces demo/ :

-> for instance
"demo/ contains the demo programs for the package. Contrary to example programs, demo programs are not expected to be usable on all platforms. Demo programs may depend on platform-specific software and may require user interaction. They are compiled but not run in the test suite. Demo programs for 2D packages should instead be placed in the GraphicsView/ package. See Section demo subdirectory for a more detailed description of this subdirectory."

**Comment by maxGimeno** [comment]
[done](https://github.com/CGAL/cgal/wiki/Directory-Structure-for-Packages#directory-structure)

**Comment by MoniqueTeillaud** [comment]
I'd say it is ok now. Thanks.
