### ISSUE TITLE
restore tables of contents in guidelines wiki pages

### ISSUE THREAD

**Issue by MoniqueTeillaud** [CGAL/cgal#1330]
We had a table of contents on each wiki page in our good old wiki at GF. 
There are none on the github wiki, which makes it quite hard to find anything there. 
The guidelines are crucial for developers... 

Concretely, the only way to find information is to look at the old wiki guidelines, and find the info using links and tables of contents, which is quite easy. 
But the info is possibly outdated. So we must search for the same info on the github wiki and check for updates. This takes a lot of time, and success is not guaranteed since many links are broken.

**Comment by lrineau** [comment]
I actually think that the GitHub wiki is actually a pretty bad piece of software. They have been ignoring the feature request https://github.com/isaacs/github/issues/215 for more than two years. I begin to doubt that the opting of GitHub wikis is a good choice. Sébastien, don't you think that we should stay in Mediawiki and open a choosen set of pages to the public?

**Comment by sloriot** [comment]
Indeed

**Comment by sloriot** [comment]
I wrote a [script](https://github.com/CGAL/cgal/wiki/Scripts#add_toc_to_github_wiki_pagepy) to generate them. See
