### ISSUE TITLE
Mesh_domain_with_polyline_features_3::add_features_and_incidences in the documention but not in the code

### ISSUE THREAD

**Issue by SLopezBRGM** [CGAL/cgal#1333]
In the class `Mesh_domain_with_polyline_features_3`, the documention mentions the method [`add_features_and_incidences`][doc] to add 1-dimensional features in the domain with their incidences with 2-dimensional features of the domain whereas there is no such method in the code.
It seems to be replaced by `add_features_with_context` and has a distinct interface.

[doc]: https://doc.cgal.org/4.10/Mesh_3/classCGAL_1_1Mesh__domain__with__polyline__features__3.html#a6337c1f9b0224beccaaa5e7a5be85a59

**Comment by janetournois** [comment]
Thanks Simon for your report! I will have a look to fix it asap

**Comment by lrineau** [comment]
`add_features_with_context` should not be documented as such. The API is ad-hoc and inelegant. It should be replaced by a review API. Maybe the API of `add_features_and_incidences` is the right one.

**Comment by lrineau** [comment]
That was eventually fixed in CGAL `master` branch. Will be in CGAL-4.12, due 2018 Q1, but with a different API.
