### ISSUE TITLE
Move Functors to the Kernel

### ISSUE THREAD

**Issue by janetournois** [CGAL/cgal#1341]
The `AABB_traits.h` file contains implementations of the functors
- ~~Compute_closest_point_3~~ `Construct_closest_point_3`
- `Compare_distance`

They should both be moved to the Kernel

This issue is related to #260

**Comment by HoffmannMichael** [comment]
Construct_closest_point_3 ?

**Comment by janetournois** [comment]
That's right! I will change it in issue #1340 too. Thanks

**Comment by afabri** [comment]
You can assign this to me if you want

**Comment by afabri** [comment]
The branch Kernel_23-Construct_closest_point_3-GF  now has two functions `closest_point()`.
@janetournois   Can you change AABB_traits so that it uses the new function please.

@sloriot  I am not sure what to do with Compare_distance.  I am also not sure where to put the functions in include/CGAL/internal/AABB_tree/nearest_...h    Should these be functors as well?

**Comment by janetournois** [comment]
it's done. 
I have made some comments on github inside the cgal-dev branch, but it concerns the question you asked to @sloriot

**Comment by janetournois** [comment]
`Compare_distance` is already the functor of the Kernel

**Comment by janetournois** [comment]
actually `Compare_distance_3` already is a functor of the Kernel. Overloads that are in AABB_traits.h should be moved there

**Comment by afabri** [comment]
Is it just overloads?? In the code we see in a comment:

>  // This should go down to the GeomTraits, i.e. the kernel
>  // and the internal implementation should change its name from.
>  // do_intersect to something like does_contain (this is what we compute,
> // this is not the same do_intersect as the spherical kernel)
>  class Compare_distance {

**Comment by janetournois** [comment]
You should check the implementation, but the clearest name could maybe be `do_overlap`
