### ISSUE TITLE
Doxygen Warning

### ISSUE THREAD

**Issue by gdamiand** [CGAL/cgal#1342]
Using doxygen version 1.8.12, a lot of warnings are generated

`warning: ignoring unsupported tag SHOW_GROUPED_MEMBER_INCLUDES = at line 544, file doc_dxy/BaseDoxyfile`

`warning: Tag XML_SCHEMA at line 1587 of file doc_dxy/BaseDoxyfile has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"`

`warning: Tag XML_DTD at line 1593 of file doc_dxy/BaseDoxyfile has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"`

The solution is simply to remove these tags in the doc/resources/BaseDoxyfile.in file.

(<s>Note that the problem with Doxygen 1.8.11 that too too many things are exported in tags, indicated [here](https://cgal.geometryfactory.com/CGAL/Members/wiki/Guidelines/Doxygen_Specification_Documentation/Building_the_Documentation#doxygen), seems to be solved in 1.8.12; but the problem of missing treeview is still there</s> Correction: the bug is still there.).

**Comment by lrineau** [comment]
@gdamiand Please precise which version is *the last version* of Doxygen, This issue might be still open in a few months (years?).

**Comment by gdamiand** [comment]
Done.

**Comment by sloriot** [comment]
There is some on going work in `cgal-dev/Documentation-official_doxygen-GF`

**Comment by sloriot** [comment]
See also https://bugzilla.gnome.org/show_bug.cgi?id=763471 and https://github.com/doxygen/doxygen/pull/452

**Comment by sloriot** [comment]
Fixes by #1787
