### ISSUE TITLE
UseCGAL.cmake causes build spam due to deprecated CMake features.

### ISSUE THREAD

**Issue by elfprince13** [CGAL/cgal#1352]
```
find_package(CGAL COMPONENTS Core)
include(${CGAL_USE_FILE})
```

 results in `Directory not found` spam when compiling on platforms that support multiple build profiles (Debug, Release, etc). This is because of it's outdated use of link_directories.

**Comment by lrineau** [comment]
It is a know issue that our CMake script use deprecated feature. CGAL started using CMake since CMake version 2.4, and even since we require CMake>=2.8.11, parts of our scripts have not yet been upgraded to use recent features of CMake. That is a scheduled topic for next CGAL developers meeting, in early September.

Our the message `Directory not found`, can you please specify how to reproduce it? Which operating system? Which compiler toolset? And which CMake version?

**Comment by elfprince13** [comment]
I'm using cmake 3.5.2 on OS X El Capitan 10.11.6, and the Xcode 7.3.1 toolchain. The actual error messages are:
```
ld: warning: directory not found for option '-L/Users/myusername/pathtosomeprojecthere/deps/CGAL/lib/Debug'
ld: warning: directory not found for option '-L/opt/local/lib/Debug'
```

Obviously the correct search paths don't have `/Debug` appended to the end, but because `link_directories` doesn't play well with multiple build profiles, not much can be done about it. Also, **every target** in my project that uses CGAL emits this messages, which quickly builds up to a lot of noise.

**Comment by lrineau** [comment]
As for the CMake Generator, do you use the one for Xcode or Makefiles?

**Comment by elfprince13** [comment]
When I build the CGAL libraries themselves I just use the Makefile generator, as once the libraries are compiled I don't need to look into it again, however the project which depends on CGAL is using the Xcode generator.

**Comment by elfprince13** [comment]
Here is the problem region:
```
  if (CGAL_HEADER_ONLY)
    add_definitions(-DCGAL_HEADER_ONLY)
    link_directories    ( ${CGAL_3RD_PARTY_LIBRARIES_DIRS} )
    link_libraries      ( ${CGAL_3RD_PARTY_LIBRARIES}      )
  else()
    link_directories    ( ${CGAL_LIBRARIES_DIR} ${CGAL_3RD_PARTY_LIBRARIES_DIRS} )
    link_libraries      ( ${CGAL_LIBRARIES}     ${CGAL_3RD_PARTY_LIBRARIES}      )
endif()
```

Is it safe to assume that anything which should be linked has already been added to `${CGAL_LIBRARIES}` and `${CGAL_3RD_PARTY_LIBRARIES}` and that the `_DIR` variables are essentially extraneous? If so, I am considering a modification that would simply allow a configuration variable to be set to skip the `link_directories` and `link_libraries` commands, so end-users could call `target_link_libraries` instead, on an as-needed basis.
