### ISSUE TITLE
BGL tests : compilation error with recent OpenMesh

### ISSUE THREAD

**Issue by janetournois** [CGAL/cgal#1360]
I am now using OpenMesh-6.2 and I get the following error when I compile the test `graph_concept_OpenMesh.cpp` inside the BGL package.

The error is the following : 
> CGAL\cgal-dev\STL_Extension\include\CGAL/hash_openmesh.h(31): error C2084: the function
> 'size_t OpenMesh::hash_value(const OpenMesh::BaseHandle &)' already has a body in
> C:\3rdPartyLibs\OpenMesh-6.2\include\OpenMesh/Core/Mesh/Handles.hh(110)

We should take into account the version number to define this function or not

**Comment by lrineau** [comment]
@sloriot @afabri 
This issue is selected for the milestone `4.8.2`. Do we have the resources to work on it rather soon? Once the branch for CGAL-4.9 is created, it will be difficult to maintain the branch for CGAL-4.8.2.

**Comment by lrineau** [comment]
Actually, I found out that `<CGAL/hash_openmesh.h>` is a file that was added to CGAL-4.9, and was not in CGAL-4.8.x. I have re-assigned the bug to 4.9 instead of 4.8.2.

**Comment by lrineau** [comment]
Fixed by #1377.
