### ISSUE TITLE
Windows installer proposes C:\Program Files\CGAL-4.7 as installation directory, by default

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#137]
[The web site of CGAL, for Windows, recommands to use `C:\dev\CGAL-4.7` as installation directory](http://www.cgal.org/download/windows.html), but our Windows installer proposes `C:\Program Files\CGAL-4.7` by default. See [the `.onInit` macro, in the source code of the installer](https://github.com/CGAL/cgal/blob/releases/CGAL-4.6-branch/wininst/developer_scripts/script_cgal.nsi#L313).

We should try to change that for CGAL-4.7...

CC @afabri

**Comment by afabri** [comment]
We should at the same time address this:

When I click in the installer on "Installation Instructions"
I get here:  file:///C:/Program%20Files/CGAL-4.6.1/doc_html/index.html

BUG: This are NOT the installation instructions.
BUG: Also the link text "Table of Contents"is wrong

**Comment by sloriot** [comment]
See #509
