### ISSUE TITLE
Wrong check in QP_solver_impl.h

### ISSUE THREAD

**Issue by schinabr** [CGAL/cgal#1370]
Hello, gents.
Check this post: http://stackoverflow.com/questions/39174015/cgal-quadratic-solver-from-iterator-exception

A solution is thrown when the example in the post is ran replacing variable "relationships" by this one:
std::array<CGAL::Comparison_result, numAConstraints> relationships 
              = { CGAL::LARGER,CGAL::LARGER,CGAL::LARGER,CGAL::LARGER, };

Notice how bizarre is the behavior here. By simply changing the constraint set through "relationships", an exception is thrown. The offender line is in QP_solver_impl.h (line #1155 "CGAL_qpe_assertion(check_basis_inverse())").

By commenting the line, the program finds a reasonable solution which agrees with a solution found by a competing library.

Thank you,
A-

**Comment by sloriot** [comment]
I'm not a QP_solver expert but reading the documentation of [`CGAL::Quadratic_program_solution`](http://doc.cgal.org/latest/QP_solver/group__PkgQPSolverFunctions.html#gac769fb5f56983e35bec295b26501df7f), it is written that `ET` must be an exact number type while in you case it is `double`.
