### ISSUE TITLE
Static variables in CGAL_ImageIO package

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#1386]
- [ ] `CGAL_ImageIO/include/CGAL/ImageIO/gif_impl.h:39:      static TYPE NAME = VALUE;`
- [ ] `CGAL_ImageIO/include/CGAL/ImageIO/gif_impl.h:79:static int EGApalette[16][3] = {`
- [ ] `CGAL_ImageIO/include/CGAL/ImageIO/gif_impl.h:639:  static byte *ptr = NULL;`
- [ ] `CGAL_ImageIO/include/CGAL/ImageIO/gif_impl.h:640:  static int   oldYC = -1;`
- [ ] `CGAL_ImageIO/include/CGAL/ImageIO/bmp_impl.h:47:  static int _VERBOSE_BMP_ = 1;`
- [ ] `CGAL_ImageIO/include/CGAL/ImageIO/bmp_impl.h:53:static int _VERBOSE_BMP_ = 1;`
- [ ] `CGAL_ImageIO/include/CGAL/ImageIO/recbuffer_impl.h:67:  static int _VERBOSE_ = 0;`
- [ ] `CGAL_ImageIO/include/CGAL/ImageIO/recbuffer_impl.h:73:static int _VERBOSE_ = 0;`
- [ ] `CGAL_ImageIO/include/CGAL/ImageIO/reech4x4_impl.h:64:  static int _VERBOSE_REECH_ = 0;`
- [ ] `CGAL_ImageIO/include/CGAL/ImageIO/reech4x4_impl.h:70:static int _VERBOSE_REECH_ = 0;`
- [ ] `CGAL_ImageIO/include/CGAL/ImageIO/recline_impl.h:64:  static int _VERBOSE_RECLINE_ = 0;`
- [ ] `CGAL_ImageIO/include/CGAL/ImageIO/recline_impl.h:70:static int _VERBOSE_RECLINE_ = 0;`
- [ ] `CGAL_ImageIO/include/CGAL/ImageIO_impl.h:76:  static PTRIMAGE_FORMAT firstFormat = NULL;`
- [ ] `CGAL_ImageIO/include/CGAL/ImageIO_impl.h:82:  static PTRIMAGE_FORMAT inrimageFormat = NULL;`
- [ ] `CGAL_ImageIO/include/CGAL/ImageIO_impl.h:88:  static Remove_supported_file_format rsff;`
- [ ] `CGAL_ImageIO/include/CGAL/ImageIO_impl.h:92:CGAL_UNUSED static Remove_supported_file_format &rsff_dummy_ref = XXXXX_rsff();`
- [ ] `CGAL_ImageIO/include/CGAL/ImageIO_impl.h:98:static PTRIMAGE_FORMAT firstFormat = NULL;`
- [ ] `CGAL_ImageIO/include/CGAL/ImageIO_impl.h:105:static PTRIMAGE_FORMAT InrimageFormat = NULL;`
- [ ] `CGAL_ImageIO/include/CGAL/ImageIO_impl.h:111:static Remove_supported_file_format rsff;`
- [ ] `CGAL_ImageIO/include/CGAL/ImageIO_impl.h:332:    static int errnum;`

**Comment by afabri** [comment]
@lrineau Do you think it makes sense to work on this issue?

**Comment by lrineau** [comment]
No: in a well-behaved application, the I/O should be done in a single dedicated thread. Let's postpone that until a user/customer complains.

Anyway the fix is rather simple: all those `static` variables could be made `static` and atomic. For all the `*format` variables, there would be extra code to use compare-and-swap atomic operations, and deal with the deallocation of unneeded data if two threads try to initialize the format at the same time.

**Comment by sloriot** [comment]
Shall we close the issue then?

**Comment by lrineau** [comment]
Let's close the issue until a real use case pops up.
