### ISSUE TITLE
Static variables in Number_type package

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#1387]
- [x] `Number_types/include/CGAL/Sqrt_extension/convert_to_bfi.h:58:  static Cache_type cache;`
- [x] `Number_types/include/CGAL/Lazy_exact_nt.h:488:  static double relative_precision_of_to_double;`
- [x] `Number_types/include/CGAL/Mpzf.h:139:  static std::vector<T> data;`
- [x] `Number_types/include/CGAL/Mpzf.h:159:    static CGAL_MPZF_TLS T data_ = 0;`
- [x] `Number_types/include/CGAL/Mpzf.h:183:    static thread_local cleaner obj;`
- [x] `Number_types/include/CGAL/Interval_nt.h:216:  static Test_runtime_rounding_modes tester;`
- [x] `Number_types/include/CGAL/Counted_number.h:37:    static unsigned long s_neg_count, s_add_count, s_sub_count,`
- [x] `Number_types/include/CGAL/GMP/Gmpzf_type.h:487:  static Gmpz s;`

**Comment by afabri** [comment]
I don't see where Counted_number.h is used.

**Comment by lrineau** [comment]
@sloriot @afabri Can you please check what has been "fixed" by PR #1375, check the corresponding checkbox at https://github.com/CGAL/cgal/issues/1387#issue-174031770 and maybe close this issue?

**Comment by afabri** [comment]
PR #1375  only addresses that the relative precision of a `Lazy_exact_nt`  is now thread local and that this gets documented.

**Comment by lrineau** [comment]
OK, so this issue remains. Thanks.

**Comment by afabri** [comment]
Nothing to do for Interval_nt, as it is a test whether GCC's -frounding-math option has been forgotten.

**Comment by afabri** [comment]
@lrineau I  think it is ready for testing

**Comment by lrineau** [comment]
It seems this issue has been eventually fixed by #1734.
