### ISSUE TITLE
Static variables in Box_intersection_d package

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#1388]
- [x] `Box_intersection_d/include/CGAL/Box_intersection_d/segment_tree.h:278: static int level = -1;`
- [x] `Box_intersection_d/include/CGAL/Box_intersection_d/Box_d.h:42:    static std::size_t n;`

**Comment by afabri** [comment]
@sloriot can you please check

**Comment by lrineau** [comment]
Fixed by #1420.
