### ISSUE TITLE
Static variables in STL_Extension package

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#1396]
- [x] `STL_Extension/include/CGAL/assertions_impl.h:47:  static Failure_behaviour _error_behaviour = THROW_EXCEPTION;`
- [x] `STL_Extension/include/CGAL/assertions_impl.h:52:  static Failure_behaviour _warning_behaviour = CONTINUE;`
- [x] `STL_Extension/include/CGAL/assertions_impl.h:125:  static Failure_function _error_handler = _standard_error_handler;`
- [x] `STL_Extension/include/CGAL/assertions_impl.h:130:  static Failure_function _warning_handler = _standard_warning_handler;`
- [x] `STL_Extension/include/CGAL/Concurrent_compact_container.h:84:    static unsigned int erase_counter(const Element &) { return 0; }`
- [x] `STL_Extension/include/CGAL/Concurrent_compact_container.h:98:    static unsigned int erase_counter(const Element &e)`
- [x] `STL_Extension/include/CGAL/Handle_with_policy.h:255:    static Char_allocator alloc;`
- [x] `STL_Extension/include/CGAL/Handle_with_policy.h:736:    static Bind bind;`
- [x] `STL_Extension/include/CGAL/Handle_with_policy.h:768:    static Rep_allocator allocator;`
- [x] `STL_Extension/include/CGAL/vector.h:180:    static`
- [x] `STL_Extension/include/CGAL/Handle_for.h:53:    static Allocator   allocator;`
- [x] `STL_Extension/include/CGAL/is_streamable.h:62:    static typename boost::remove_cv<typename boost::remove_reference<T>::type>::type const & x;`
- [x] `STL_Extension/include/CGAL/is_streamable.h:63:    static typename boost::remove_cv<typename boost::remove_reference<T>::type>::type  & y;`
- [x] `STL_Extension/include/CGAL/Spatial_lock_grid_3.h:598:    static tbb::atomic<unsigned int> last_id;`

**Comment by afabri** [comment]
Nothing to do for
- STL_Extension/include/CGAL/is_streamable.h
- STL_Extension/include/CGAL/Spatial_lock_grid_3.h
- STL_Extension/include/CGAL/Concurrent_compact_container.h
so you might shorten the above list.

**Comment by afabri** [comment]
@sloriot  can you please check that all items are addressed, so that it could be added to a testsuite.

**Comment by sloriot** [comment]
What should I check?

**Comment by afabri** [comment]
That you can tick the boxes

**Comment by afabri** [comment]
Based on the mail discussion with Marc we do nothing for `Handle_for`.
Based on a private discussion with Laurent we do nothing for `Handle_with_policy` as it is used in code that is rarely used.

**Comment by lrineau** [comment]
I think we can now close this bug. Maybe we should open another one for `Handle_with_policy`.
