### ISSUE TITLE
Static variables in CGAL_Core package

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#1397]
- [x] `CGAL_Core/include/CGAL/CORE/geom3d/point3d.h:171:static Point3d ORIGIN_3D(0.0, 0.0, 0.0);`
- [x] `CGAL_Core/include/CGAL/CORE/geom3d/point3d.h:172:static Point3d X_UNIT_3D(1.0, 0.0, 0.0);`
- [x] `CGAL_Core/include/CGAL/CORE/geom3d/point3d.h:173:static Point3d Y_UNIT_3D(0.0, 1.0, 0.0);`
- [x] `CGAL_Core/include/CGAL/CORE/geom3d/point3d.h:174:static Point3d Z_UNIT_3D(0.0, 0.0, 1.0);`
- [x] `CGAL_Core/include/CGAL/CORE/Expr_impl.h:71:  static Expr Zero(0);`
- [x] `CGAL_Core/include/CGAL/CORE/Expr_impl.h:76:  static Expr One(1);`
- [x] `CGAL_Core/include/CGAL/CORE/ExprRep.h:925:  static Operator Op;`
- [x] `CGAL_Core/include/CGAL/CORE/CoreAux_impl.h:154:  static gmp_randstate_t rstate;`
- [x] `CGAL_Core/include/CGAL/CORE/CoreAux_impl.h:155:  static bool initialized = false;`
- [x] `CGAL_Core/include/CGAL/CORE/poly/Curves.h:395:   static double RED_COMP[] = {0.9, 0.8, 0.7, 0.6, 0.8, 0.8, 0.7};`
- [x] `CGAL_Core/include/CGAL/CORE/poly/Curves.h:399:   static double GREEN_COMP[] = {0.5, 0.9, 0.3, 0.9, 0.7, 0.55, 0.95};`
- [x] `CGAL_Core/include/CGAL/CORE/poly/Curves.h:403:   static double BLUE_COMP[] = {0.8, 0.3, 0.8, 0.5, 0.4, 0.85, 0.35};`
- [x] `CGAL_Core/include/CGAL/CORE/poly/Poly.h:106:  static  int COEFF_PER_LINE;        // pretty print parameters`
- [x] `CGAL_Core/include/CGAL/CORE/poly/Poly.h:111:  static Polynomial polyWilkinson;         // a sample polynomial`
- [x] `CGAL_Core/include/CGAL/CORE/poly/Poly.h:112:  static int NT_TYPE; // NT_TYPE = 1 if NT is integer type (int,long,BigInt)`
- [x] `CGAL_Core/include/CGAL/CORE/poly/Poly.h:272:  static Polynomial<NT> zeroP;`
- [x] `CGAL_Core/include/CGAL/CORE/poly/Poly.h:279:  static NT c[] = {1};`
- [x] `CGAL_Core/include/CGAL/CORE/poly/Poly.h:280:  static Polynomial<NT> unityP(0, c);`
- [x] `CGAL_Core/include/CGAL/CORE/poly/Sturm.h:85:  static int N_STOP_ITER;    // Stop IterE after this many iterations. This`
- [x] `CGAL_Core/include/CGAL/CORE/extLong_impl.h:54:  static extLong NaNLong(true);`
- [x] `CGAL_Core/include/CGAL/CORE/extLong_impl.h:60:  static extLong posInfty(EXTLONG_MAX);`
- [x] `CGAL_Core/include/CGAL/CORE/extLong_impl.h:66:  static extLong negInfty(EXTLONG_MIN);`
- [x] `CGAL_Core/include/CGAL/CORE/Filter.h:183:    static double d = DBL_MAX;`
- [x] `CGAL_Core/include/CGAL/CORE/BigFloat_impl.h:87:  static BigFloat Zero(0);`
- [x] `CGAL_Core/include/CGAL/CORE/BigFloat_impl.h:93:  static BigFloat One(1);`
- [x] `CGAL_Core/include/CGAL/CORE/Real_impl.h:55:  static Real Zero(0);`
- [x] `CGAL_Core/include/CGAL/CORE/MemoryPool.h:91:  static MemoryPool<T, nObjects> memPool;`
- [x] `CGAL_Core/include/CGAL/CORE/CoreDefs.h:48:      static TYPE NAME = VALUE;`

**Comment by afabri** [comment]
@sloriot: Can we remove the subdirectory geom3d ?

**Comment by sloriot** [comment]
If you want but you'll need to also remove `CORE/geometry3d.h`. Or shall you simply want me to check the geom3d cases?

**Comment by afabri** [comment]
@sloriot please check/tick and potentially declare ready for testing

**Comment by sloriot** [comment]
Which PR?

**Comment by lrineau** [comment]
@sloriot: PR #1744

**Comment by lrineau** [comment]
Fixed by #1744.
