### ISSUE TITLE
Static variables in Bounding_volumes package

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#1399]
- [ ] `Bounding_volumes/include/CGAL/Approximate_min_ellipsoid_d/Khachiyan_approximation_impl.h:608:    static int id = 0;`
- [ ] `Bounding_volumes/include/CGAL/Approximate_min_ellipsoid_d/Approximate_min_ellipsoid_d_debug.h:108:        static Logger instance;`
- [ ] `Bounding_volumes/include/CGAL/Approximate_min_ellipsoid_d/Approximate_min_ellipsoid_d_debug.h:211:        static Timer instance;`

**Comment by afabri** [comment]
I suggest to close this issue, as it is debugging code, which  one would do in a single thread anyways.
