### ISSUE TITLE
Static variables in Linear_cell_complex package

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#1405]
- [x] `Linear_cell_complex/include/CGAL/Linear_cell_complex_storages.h:68:    static Null_handle_type null_handle;`

**Comment by afabri** [comment]
Guillaume wrote me that this issue is solved by #1511

**Comment by lrineau** [comment]
Fixed by #1511.

**Comment by gdamiand** [comment]
@lrineau Why you reopened this issue ? It is indeed fixed by #1511 and now integrated in master.

**Comment by lrineau** [comment]
By error! ☺️
