### ISSUE TITLE
Static variables in Algebraic_kernel_d package

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#1407]
- [x] `Algebraic_kernel_d/include/CGAL/Algebraic_kernel_d/Bitstream_descartes_E08_tree.h:61:    static Triangle my_pascal;`
- [x] `Algebraic_kernel_d/include/CGAL/Algebraic_kernel_d/Bitstream_descartes_E08_tree.h:172:    static Mn_cache mn_cache_;`
- [x] `Algebraic_kernel_d/include/CGAL/Algebraic_kernel_d/Bitstream_descartes_rndl_tree_traits.h:137:      static Self x = Self(kernel);`
- [x] `Algebraic_kernel_d/include/CGAL/Algebraic_kernel_d/Algebraic_real_d_1.h:107:    static Self x = Self(0);`
- [x] `Algebraic_kernel_d/include/CGAL/Algebraic_kernel_d/Shear_controller.h:99:          static std::vector<Int> value_order_;`
- [x] `Algebraic_kernel_d/include/CGAL/Algebraic_kernel_d/Bitstream_descartes_rndl_tree.h:178:    static std::vector< Integer > factorial;`
- [x] `Algebraic_kernel_d/include/CGAL/Algebraic_kernel_d/Algebraic_curve_kernel_2.h:404:      static Algebraic_curve_kernel_2 ack_2_instance;`
- [x] `Algebraic_kernel_d/include/CGAL/RS/rs2_calls.h:42:                static bool first=true;`

**Comment by afabri** [comment]
@sloriot please check/tick and potentially declare ready for testing
