### ISSUE TITLE
Static variables in Kernel_d package

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#1413]
- [x] `Kernel_d/include/CGAL/Kernel_d/Vector__.h:95:  static allocator_type MM;`
- [ ] `Kernel_d/include/CGAL/Kernel_d/debug.h:42:static int debugthread=3141592;`
- [x] `Kernel_d/include/CGAL/Kernel_d/Matrix__.h:168:static allocator_type MM;`

**Comment by lrineau** [comment]
Fixed by #1490.
