### ISSUE TITLE
Static variables in Combinatorial_map package

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#1415]
- [x] `Combinatorial_map/include/CGAL/internal/Combinatorial_map_internal_functors.h:364:  static typename CMap::size_type res;`
- [x] `Combinatorial_map/include/CGAL/internal/Combinatorial_map_internal_functors.h:671:  static bool value;`

**Comment by gdamiand** [comment]
Solved in the branch Generalized_map-gdamiand, but not yet integrated.

**Comment by lrineau** [comment]
Let us know once your have a pull-request number. In the pull-request message, you can insert `fix #<issue number>`, like "fix #1415", and that will create cross-links between this issue and the corresponding PR.

**Comment by gdamiand** [comment]
fix by #1697
