### ISSUE TITLE
Problem with has_on predicate

### ISSUE THREAD

**Issue by myirci** [CGAL/cgal#1431]
Hello,

When I run the program given below, I get the output as " 0 0 0 1 1 1", that is the predicate "has_on" does not work although I used Exact_predicates_inexact_constructions_kernel. When I changed the kernel to Exact_predicates_exact_constructions_kernel, then the output becomes "1 1 1 1 1 1" as expected. 

Is this a bug or am I doing something wrong?

Thank you.

`#include \<iostream\>

#include \<CGAL/Exact_predicates_inexact_constructions_kernel.h\>
// #include \<CGAL/Exact_predicates_exact_constructions_kernel.h\>

using Kernel  = CGAL::Exact_predicates_inexact_constructions_kernel;
// using Kernel  = CGAL::Exact_predicates_exact_constructions_kernel;
using Point3  = Kernel::Point_3;
using Plane3  = Kernel::Plane_3;

int main(void) {

    Point3 p1(1.4, 4.3, 6.4);
    Point3 p2(9.8, 5.0, 4.9);
    Point3 p3(0.6, 3.9, 8.0);
    Point3 p4(1, 4, 6);
    Point3 p5(9, 5, 4);
    Point3 p6(0, 3, 8);

    Plane3 pl_1(p1, p2, p3);
    Plane3 pl_2(p4, p5, p6);

    std::cout << pl_1.has_on(p1) << " " << pl_1.has_on(p2) << " " << pl_1.has_on(p3) << " " << pl_2.has_on(p4) << " " << pl_2.has_on(p5) << " " << pl_2.has_on(p6) << std::endl;

    return 0;
}`

**Comment by lrineau** [comment]
If the **construction of planes** are **inexact** then they do not pass exactly through the input points.

**Comment by myirci** [comment]
Ok, Thank you.  Since the plane is not exactly constructed, the plane might not pass through its constructing points.
