### ISSUE TITLE
Documenting and checking exactness of geometric primitives

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#1433]
_Section [Documenting and checking exactness of geometric primitives](https://cgal.geometryfactory.com/CGAL/Members/wiki/Meetings/Zurich16#Documenting_and_checking_exactness_of_geometric_primitives) of CGAL developers meeting a Zurich'16._
- Shall we document for `CGAL::Epick` the list of constructions that are known to be exact?
- Or document the representation of CGAL geometrical objects, in CGAL kernels?
- Or can we add a machinery so that the compiler can warn about non-exact constructions?

**Comment by lrineau** [comment]
Michael (@HoffmannMichael) volunteered to make a proposal for the changes to be made in the CGAL manual.

**Comment by sgiraudot** [comment]
@HoffmannMichael do you have any update on this issue?

**Comment by HoffmannMichael** [comment]
No updates, still on my todo list.

Am 20.07.2017 um 14:42 schrieb Simon Giraudot <notifications@github.com<mailto:notifications@github.com>>:


@HoffmannMichael<https://github.com/hoffmannmichael> do you have any update on this issue?

**Comment by lrineau** [comment]
Michael, I imagine it is still on your TODO list. That is just a reminder... if you have time.
