### ISSUE TITLE
create_new_release needs bash

### ISSUE THREAD

**Issue by nschloe** [CGAL/cgal#1440]
The file `Scripts/developer_scripts/create_new_release` says
```bash
#!/bin/sh
```
but uses Bash functionality (like pushd). It should be
```bash
#!/bin/bash
```

**Comment by lrineau** [comment]
Thanks.

How did you found out? Which shell can be used to check such things? Has bash a pedantic mode to warn about that?

**Comment by nschloe** [comment]
> How did you found out? 

I simply ran it and it failed. `sh` points to `sh` on my machine, perhaps to `bash` on yours such that you never saw the error.

**Comment by lrineau** [comment]
Do you know which shell is `/bin/sh` on your system? What is displayed by `sh - -version` ?

**Comment by nschloe** [comment]
```
$ ll `which sh`
lrwxrwxrwx 1 root root 4 Feb 17  2016 /bin/sh -> dash
```
https://en.wikipedia.org/wiki/Almquist_shell (default Ubuntu/Debian).

**Comment by lrineau** [comment]
Thanks.
