### ISSUE TITLE
Epick_d.cpp disabled on clang

### ISSUE THREAD

**Issue by mglisse** [CGAL/cgal#1458]
Clang, which identifies itself as gcc-4.2, skips the test Epick_d.cpp. Please improve the version check or revert the corresponding set of commits. Testing with clang is way more important than avoiding a red mark on a completely obsolete platform, on which people can still install redhat developer toolset 2.1 to get gcc-4.8 (rhel/centos) or clang (mac).

**Comment by lrineau** [comment]
Fix by #1464: by a use of `BOOST_GCC` from `<boost/config.hpp>` instead of reading `__GNUC__`.

**Comment by mglisse** [comment]
Thanks :-)
