### ISSUE TITLE
Documentation: links to demos (and dlls) are broken

### ISSUE THREAD

**Issue by cjamin** [CGAL/cgal#1475]
See http://doc.cgal.org/latest/Manual/packages.html

**Comment by lrineau** [comment]
I am working on it. I have uploaded all precompiled demo but the Polyhedron_3 demo (because the script collecting the demos was not updated on picasso.geometryfactory.com).

**Comment by lrineau** [comment]
I just uploaded the Polyhedron_3. I have also uploaded the Otr2 demo, it does not seem to be linked.

http://doc.cgal.org/latest/Manual/packages.html#PkgOptimalTransportationReconstruction2Summary

@palliez @cjamin, do you want to add the link to the demo in the package overview?

**Comment by cjamin** [comment]
Sure, I think it would be nice.

**Comment by lrineau** [comment]
Then add a line similar to 
```
\cgalPkgDemo{2D Mesh Generator,constrained_delaunay_triangulation_2.zip}
```
in the package description. For the zip file, I have named it `otr2.zip`. For the title of the link, I let you choose.

**Comment by cjamin** [comment]
Done in PR #1499
