### ISSUE TITLE
Remove the pseudo package "Conic_2" from CGAL

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#1478]
@afabri There exists a "package" Conic_2, that contains almost nothing and is never used. Please remove it.

**update:** my greps were wrongs. The `CGAL::Conic_2<K>` is indeed used by CGAL kernels, and even used by two algorithm packages, for `Min_ellipse_2` and a traits class of Arr_2.

**Comment by afabri** [comment]
$ grep  "Conic_2.h" -r */include
Bounding_volumes/include/CGAL/Min_ellipse_2/Optimisation_ellipse_2.h:#include <CGAL/Conic_2.h>
Kernel_23/include/CGAL/user_classes.h:#include <CGAL/Conic_2.h>

I guess the plan was to move it into the kernel.    Any idea @HoffmannMichael  ?

**Comment by lrineau** [comment]
The files are indeed included twice, and that is why my dependency checker found that package, but the class `Conic_2` is never used.

**Comment by afabri** [comment]
Cartesian_base.h  has an
#include <CGAL/ConicCPA2.h>

**Comment by HoffmannMichael** [comment]
Yes, this was supposed to go into the kernel at some point.
I guess that's not gonna happen

**Comment by afabri** [comment]
I suggest to dispatch the files to Kernel_23 Homogeneous_kernel, Cartesian_kernel.

**Comment by lrineau** [comment]
When yesterday I had check the content of the package, I had the impression that it was not used (headers included by kernels headers but not used), but I was wrong. I close this issue.

Andreas proposes to dispatch the headers to the normal kernel packages, and I agree. That is the subject of PR #1479 (that just popped up while I was writing this comment).
