### ISSUE TITLE
A file from Generator (LGPL) includes a file from PCA (GPL)

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#1484]
`Generator/include/CGAL/random_convex_set_2.h` includes `<CGAL/centroid.h>` from PCA!

**Comment by afabri** [comment]
Should be solved by  510d550c8804ad7d934a4fee978771e7fafc41f3

**Comment by mglisse** [comment]
Why is that so bad? centroid.h is apparently LGPL, same license. Is there some new policy that packages are not allowed to use each other?

**Comment by lrineau** [comment]
The reason is https://github.com/CGAL/cgal/projects/1.

We want to find out and fix dependencies between packages.

**Comment by mglisse** [comment]
My issue might be with the definition of "fix".
PCA is supposed to be a GPL package. However, it contains 3 LGPL files (including the one that defines centroids). You might want to split those 3 files to a "foundation" package if that helps. I am not convinced this commit is an improvement; sure, centroid.h is overkill, but 1 line is more readable than inlining a copy of the code for every use, and the licenses are consistent...

**Comment by afabri** [comment]
I had not read the license header of centroid.h as for my little head it was a GPL package.
An extra package makes not really sense.
I am wondering if it would not make sense to add `centroid(), barycenter()`,  and `bounding_box()` to the Kernel, even if it deals with a range of input objects.

I never understood how `bounding_box()` made it into a package called _Principal Component Analysis_

**Comment by mglisse** [comment]
> add `centroid(), barycenter()`, and `bounding_box()` to the Kernel

If the licenses / copyright make sense, the authors don't mind, and it doesn't interact badly with Barycentric_coordinates_2 or some other packages that might do something similar, that sounds good to me. Note that the kernel_23 package already has a mix of copyrights, some files belong to the Utrecht-ETH-Inria-MPI-Tel-Aviv group, others to just Inria or GeometryFactory. I don't know how far you want to go with fixing the license/copyright. Just the licenses?

**Comment by HoffmannMichael** [comment]
I don't like the idea of repeating code, however trivial, for the sake of license separation.
Moving the mentioned functions to the kernel makes sense and should not take away too much from PCA.

**Comment by lrineau** [comment]
I agree the functions and headers could be moved to the kernel package (if the legal matters do not object), but what about the documentation pages?

**Comment by afabri** [comment]
The documentation should also move.
In fact these functions exist there already, but just for a fixed number of arguments and not for a range.

Note also that we have functions `bbox_2()`and `bbox_3()` for ranges in the kernel.

**Comment by lrineau** [comment]
https://github.com/CGAL/cgal/commit/510d550c8804ad7d934a4fee978771e7fafc41f3 is a good fix for this issue, because it uses the abstraction of the geometry used in the Generator package:
  -  `typedef typename Traits::Sum             Sum;`
  -  `typedef typename Traits::Scale           Scale;`

**Comment by lrineau** [comment]
Will be fixed by PR #1530.
