### ISSUE TITLE
A file from BGL includes a file from T_2

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#1485]
`BGL/include/CGAL/Triangulation_vertex_base_with_id_2.h` should be move to the `Triangulation_2` package.

**Comment by afabri** [comment]
Fixed by aff1a00c291035a577b57e3d31aea4e0c663449d, where I do the same for files that should be in the packages Polyhedron and HalfedgeDS

**Comment by lrineau** [comment]
Fixed by 7ff83d1, from PR #1530.
