### ISSUE TITLE
A header from Ak_d (LGPLv3) includes a header from Arr_2 (GPLv3)

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#1495]
`<CGAL/Algebraic_kernel_d/Curve_analysis_2.h>` from Algebraic_kernel_d (LGPLv3+) includes `Arrangement_on_surface_2/include/CGAL/Arr_enums.h` (under GPLv3+).

That breaks the license.

**Comment by afabri** [comment]
More specifically this is about the `enum CGAL::Arr_parameter_space`   which has no explanatory text in the [reference manual page](http://doc.cgal.org/latest/Arrangement_on_surface_2/group__PkgArrangement2Enums.html#ga105a37ce7c8b8008c1b76ef5524c1998).

Questions to @efifogel and @ericberberich 
- Can this be generalized to an enum that makes sense in more than the arrangement package? With another name then. 
- Or should it be moved into the Algebraic_kernel package?

**Comment by lrineau** [comment]
Ping?

**Comment by lrineau** [comment]
Fixed by #1584.
