### ISSUE TITLE
Documentation of Arr_curve_end

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#1498]
The [manual](http://doc.cgal.org/latest/Arrangement_on_surface_2/group__PkgArrangement2Enums.html#ga29246893be4be2ad9a8fbc249f49f0b5)  says 
  that `Arr_curve_end`   is used by models of the `ArrangementOpenBoundaryTraits_2` concept.

I can't find that in any model. 

But I find another enum that has similar looking names in [Arr_algebraic_segment_traits_2](http://doc.cgal.org/latest/Arrangement_on_surface_2/classCGAL_1_1Arr__algebraic__segment__traits__2.html#ad530631780d2cf6e1a859def9710a8d1)

@efif can you please have a look and explain.

**Comment by lrineau** [comment]
CC @efifogel 

(Note for @afabri: "@efif" does not refer to anybody.)

**Comment by efifogel** [comment]
It appears in the geometry traits that are models of the
ArrangementOpenBoundaryTraits_2 concept, namely:

Arr_geodesic_arc_on_sphere_traits_2.h
Arr_linear_traits_2.h
Arr_polycurve_basic_traits_2.h
Arr_polycurve_traits_2.h
Arr_rational_arc_traits_2.h
Arr_rational_function_traits_2.h
Arr_tracing_traits_2.h

So, what is exactly the problem?

PS, indeed efifogel is my user name in github, bitbucket, and docker. They
have to match (or at least had to match in the past), but I respect
'efif'....



   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by afabri** [comment]
I do not see `Arr_curve_end` in any of the documentation of the models.

**Comment by efifogel** [comment]
Right. It's documented only in the concept.

   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/
