### ISSUE TITLE
Doxygen output documentation has duplicated entries

### ISSUE THREAD

**Issue by gdamiand** [CGAL/cgal#1510]
See [CombinatorialMap](http://doc.cgal.org/latest/Combinatorial_map/classCombinatorialMap.html) concept.

All functions seems duplicated, note that only some of them are duplicated in their short version.

**Comment by sloriot** [comment]
fixed by a9840bf87c716fd0ec9159db70efc2392e8f6434

**Comment by gdamiand** [comment]
Thanks @sloriot !
