### ISSUE TITLE
Polyhedron demo: selection widget must not stretch

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#1522]
When there are 3 widgets and I remove one of them, the Selection widget stretches vertically. It should stay compact, and at worst add whitespace in its lower part.   @maxGimeno 
![capture](https://cloud.githubusercontent.com/assets/3263539/18957715/674a000c-8660-11e6-87c8-44b23f0f2cfa.PNG)

**Comment by lrineau** [comment]
Fixed by #1549 in CGAL-4.9.1.
