### ISSUE TITLE
Polyhedron demo : change radius of spheres in polylines graph

### ISSUE THREAD

**Issue by janetournois** [CGAL/cgal#1531]
The scenario 
- Open a `file.polylines.txt`
- Right click on the item --> `Display corners with radius`
The radius I have choosen is too large (resp. too small), I want to change it
- Right click again --> `Display corners with radius`

Another set of spheres is drawn (a second one), with the new radius, but the initial ones remain.

Also, the `Corner spheres` sub-item cannot be removed from the Geometric Objects list without deleting its master item.

@maxGimeno

**Comment by maxGimeno** [comment]
Actually you can remove a Corner sphere by setting it's radius to 0 or less. I will add a tooltip to make it clearer.

**Comment by lrineau** [comment]
There is a bug: the old set of spheres is not removed. If you set the radius to 1, then 2, then 0, the display will show spheres with radii 1 and 2. One can see them all in wire mode.

**Comment by maxGimeno** [comment]
yes I know, this is the first bug Jane reported in this issue. Fixes following.

**Comment by maxGimeno** [comment]
@lrineau It was actually the same bug than @janetournois  already reported: the list of spheres were not cleared as it should be, so nothing was erased. This is fixed with #1541

**Comment by lrineau** [comment]
Fixed by #1541.
