### ISSUE TITLE
Triangulation from 2D points that belongs to a regular meshgrid

### ISSUE THREAD

**Issue by tarasboulba** [CGAL/cgal#1538]
Hello,

Is there a way to accelerate the triangulation computation when the input points (2D points actually) belong to a regular meshgrid ? For example, I have a depth map where pixels are regularly spaced. I have an algorithm that identify significant pixels in this depth map (non coplanar points) and I use the CGAL delaunay triangulation (under Matlab 2010a) after removing the non-significant points. I would need to accelerate the triangulation and maybe there is a way to do so by assuming that my 2D points are just a subpart of a regular meshgrid. Or integer points, that would do the same. 

thanks in advance for your help,

**Comment by sloriot** [comment]
General questions should be asked on the cgal-discuss mailing list. Issues are mainly meant for reporting bugs. You'll have a broader audience on cgal-discuss. If you post on cgal-discuss, you should give the order of magnitude of points kept vs points removed from the grid.

 See http://www.cgal.org/mailing_list.html

I close this issue.
