### ISSUE TITLE
Polyhedron demo: Erase all - another problem

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#1546]
In master:
- Load an off
- tet mesh it
- show tetrahedra
- Select "Intersection"
- File -> Erase All   ==> The program hangs

@maxGimeno please fix this

**Comment by lrineau** [comment]
If the bug is in CGAL-4.9, please fix it in a branch created from `cgal/releases/CGAL-4.9-branch` instead of `cgal/master`.

**Comment by lrineau** [comment]
Fixed by #1549 in CGAL-4.9.1.
