### ISSUE TITLE
Periodic_triangulation: supress warning

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#1547]
In a `switch` statement with a locate type, there is no `case` for `OUTSIDE_CONVEX_HULL`, as this makes no sense for periodic triangulations,  and as the enum comes from the non-periodic case.

clang issues a warning:

> CGAL-4.10-Ic-15/include/CGAL/Periodic_2_Delaunay_triangulation_2.h:423:12: warning: enumeration values 'OUTSIDE_CONVEX_HULL' and 'OUTSIDE_AFFINE_HULL' not handled in switch [-Wswitch]

Shall we
- have another enum
- add a case and put as comment that it cannot happen, so that nobody cleans the code
- suppress the warning [like this ](http://stackoverflow.com/questions/20078941/how-to-use-pragma-clang-diagnostics)

@MoniqueTeillaud it is not your package, but it concerns the periodic space.

**Comment by sloriot** [comment]
I close the issue this is related to #1540
