### ISSUE TITLE
Fill the documentation of CGAL::dihedral_angle

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#1561]
I have merged #1530 but I forgot that it included the addition of `CGAL::dihedral_angle` into the CGAL kernel.

Its [current documentation](https://cgal.geometryfactory.com/CGAL/doc/master/Kernel_23/namespaceCGAL.html#ab88c71fd1918c6b97134c39026da8f15) is:
> returns the dihedral angle of .... between -180 and 180 degree.

That must be fixed ASAP!
@afabri @janetournois 

Only `Kernel_23/doc/Kernel_23/CGAL/Kernel/global_functions.h` has been modified, so far, but there is also a new function `Compute_dihedral_angle_3` in the kernel.

**Comment by sloriot** [comment]
See also this small feature that we decided to closed as Mesh_3 was not using it anymore:
https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/kernel_23_CADA_3

**Comment by lrineau** [comment]
Compared to the small feature quoted above, the current code returns angles in degrees, instead of radians.

**Comment by afabri** [comment]
Let me add the documentation of the functor. It will also have ...
And I had planned to subcontract the ... to Jane -- without telling her.

**Comment by janetournois** [comment]
ok, just let me know when the PR is ready. I will check the "..."

**Comment by lrineau** [comment]
The documentation from the small feature is right (if you substitute "degrees" to radian":
> returns an approximation of the signed dihedral angle in the tetrahedron abcd of edge ab. The sign is negative if orientation(a,b,c,d) is NEGATIVE and positive otherwise. The angle is given in radian.
 Precondition: a,b,c and a,c,d are not collinear

Maybe also change the name of parameters `(a, b, c, d)`.`

**Comment by afabri** [comment]
@lrineau  Note that I did myself what I had planned to be done by Jane, so it is ready for testing (at least for me)
