### ISSUE TITLE
Regular_triangulation_3: enable parallel insertion of points with info

### ISSUE THREAD

**Issue by cjamin** [CGAL/cgal#157]
This part of the documention is wrong:
http://doc.cgal.org/latest/Triangulation_3/classCGAL_1_1Regular__triangulation__3.html#a1ebfde115587b38df5b640cf280e427d
The points are never inserted in parallel.

It has been fixed for Delaunay_triangulation_3 here: https://github.com/CGAL/cgal/pull/58

We should do the same for Regular_triangulation_3.

**Comment by sloriot** [comment]
Done in #440
