### ISSUE TITLE
Including Triangulation_vertex.h and Triangulation_full_cell.h in multiple cpp files causes linking issue.

### ISSUE THREAD

**Issue by dyershov** [CGAL/cgal#158]
While using both regular triangulations and Delauney triangulations from CGAL 4.6, I've encountered an issue of using `Triangulation_vertex.h` and `Triangulation_full_cell.h` in multiple `*.cpp` files. Specifically, I would receive the following linking errors:
`... In function 'CGAL::operator>>(std::istream&, CGAL::No_vertex_data&)':MeshSimplicial.cpp:(.text+0x490): multiple definition of 'CGAL::operator>>(std::istream&, CGAL::No_vertex_data&)' ...`
and an identical error with `No_full_cell_data` instead of `No_vertex_data`.

It looks like the bug is in both header files, where `operator>>` and `operator<<` are declared and implemented outside of class declarations. Adding `inline` in front of both of these operators in both files resolved the issue.

Thanks,
Dmitry Yershov

**Comment by lrineau** [comment]
Samuel (@horasio) are you still around?

**Comment by lrineau** [comment]
Fix in `master` by 7e6e3f62bab0a405cb15aeb4a47fccefbe3992bb.
