### ISSUE TITLE
CMake error when WITH_CGAL_Qt5 is set to ON then OFF

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#1580]
Steps to reproduce, in a empty build directory:
- configure CGAL by default
- _do not compile_ yet,
- add `-DWITH_CGAL_Qt5=OFF`
- then compile CGAL libraries
- verify that the CGAL_Qt5 lib was not created,
- and then compile any CGAL program using the produced`CGALConfig.cmake`.
  That gives a CMake error about the imported target `CGAL::CGALQt5` being missing.

@CGAL/geometryfactory Can you please confirm the bug?

Cc: @afabri

I am not sure if the bug is in `master` or if it was already in CGAL-4.9.

**Comment by janetournois** [comment]
Is building any of the examples of CGAL, with `CGAL_DIR=`the newly created build directory a correct test?

**Comment by lrineau** [comment]
Yes, that was supposed to allow to reproduce the bug.

... There was a typo in by first message: that must be  `-DWITH_CGAL_Qt5=OFF` and not ` `-DWITH_CGALQt5=OFF`.

**Comment by janetournois** [comment]
I had locally fixed the typo before testing

**Comment by maxGimeno** [comment]
I can't reproduce either. Maybe it is cache related.

**Comment by sgiraudot** [comment]
I managed to reproduce it using master and trying to configure `Point_set_processing_3_Examples`:

```
-- The C compiler identification is GNU 6.2.0
-- The CXX compiler identification is GNU 6.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at /home/simon/CGAL/master/build/test/CGAL_Qt5LibConfig.cmake:9 (get_property):
  get_property could not find TARGET CGAL::CGAL_Qt5.  Perhaps it has not yet
  been created.
Call Stack (most recent call first):
  /home/simon/CGAL/master/build/test/CGALConfig.cmake:68 (include)
  CMakeLists.txt:9 (find_package)


-- Build type: Release
-- USING CXXFLAGS = ' -frounding-math -O3 -DNDEBUG'
-- USING EXEFLAGS = ' '
-- Targetting Unix Makefiles
-- Using /usr/bin/c++ compiler.
-- Code taken from Git branch: master
-- Requested component: MPFR
-- Requested component: GMP
-- Found Eigen3: /usr/local/include/eigen3 (found suitable version "3.2.90", minimum required is "3.1.0") 
-- Configuring incomplete, errors occurred!
See also "/home/simon/CGAL/master/Point_set_processing_3/examples/Point_set_processing_3/build_test/CMakeFiles/CMakeOutput.log"
```

**Comment by lrineau** [comment]
The reason is that the first run of cmake created a file `CGAL_Qt5LibConfig.cmake`, that persists. And our `CGALConfig.cmake` globs on `*LibConfig.cmake` instead of hard-coding the list of libraries configured with success.

That is a real bug of our CMake scripts. ... yet another one.

**Comment by lrineau** [comment]
@afabri: This issue is the one that hit you today.
