### ISSUE TITLE
GraphicsView's Input / Ouput

### ISSUE THREAD

**Issue by MaelRL** [CGAL/cgal#1590]
The `save` / `load` functions of the GraphicsView demos are (at least for the Triangulation-related items) often misleading.

For example, the constrained Delaunay triangulation demo only offers to save in .edg or .poly, but regardless of the choice, outputs through `<< cdt` which is a different output (the TDS'). Another example is that if you want to load a CDT, you have to save it as a `.cgal` and drag it in, because the loader only allows you to see .edge, .plg or .poly files.

**Comment by lrineau** [comment]
I assign the bug to Andreas. I think he wrote those I/O.

**Comment by sgiraudot** [comment]
@afabri ping

**Comment by afabri** [comment]
We should look at the demos and add IO in the [Well known text](https://en.wikipedia.org/wiki/Well-known_text) format wherever that makes sense, instead of our own format.

**Comment by lrineau** [comment]
You can easily add output function that write valid WKT files, but it seems rather complicated to write a valid parser for WKT files. Do we really want to write our own I/O functions?

**Comment by sloriot** [comment]
I guess there should be even support in SFCGAL. @mhugo, @mborne, and @vmora: could you tell us how is the reading of WTK handled in SFCGAL?

**Comment by mhugo** [comment]
@sloriot There is a simple WKT writer here https://github.com/Oslandia/SFCGAL/blob/master/src/detail/io/WktWriter.cpp and a reader here https://github.com/Oslandia/SFCGAL/blob/master/src/detail/io/WktReader.cpp

**Comment by afabri** [comment]
@mhugo   Thank you for the links. Was it considered an option to use the WKT IO from boost?  With relatively little effort (see [here](https://gist.github.com/maxGimeno/e9c824a598113babd1fb92e08dbd3ceb)) were able to use that for CGAL.
