### ISSUE TITLE
Arrangement_2:  Maybe a bug.

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#1593]
This [testsuite ](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.10-Ic-25/Arrangement_on_surface_2/TestReport_lrineau_Ubuntu-latest-GCC6-Release.gz)

reports:

Arrangement_on_surface_2/test_rational_function_traits_2.cpp:250:5:   required from here
[include/CGAL/Arr_rat_arc/Rational_arc_d_1.h:1833:25](https://github.com/CGAL/cgal/blob/master/Arrangement_on_surface_2/include/CGAL/Arr_rat_arc/Rational_arc_d_1.h#L1833): warning: 
enum constant in boolean context [-Wint-in-bool-context]
 { return (this->_info && Base::IS_DIRECTED_RIGHT); }           ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~

and this is maybe a bug and it should be a single `&`  and not two.
@efifogel can you please check.

**Comment by ericberberich** [comment]
as the compiler writes replace && with &.... this->_info is used as a bitarray

**Comment by lrineau** [comment]
Fixed by #1595.
