### ISSUE TITLE
http://doc.cgal.org/ does not follow Responsive Web Design

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#16]
I have received a mail from "Google Webmaster Tools Team" that says that the documentation pages generated by Doxygen, on http://doc.cgal.org/, do not follow the Responsive Web Design, and have mobility issues. The mail also says that in future the Google ranking of those pages maybe decreased because of the issue.

https://developers.google.com/web/fundamentals/layouts/rwd-fundamentals/

I wonder what we can do. I will forward the question to the Doxygen project.

**Comment by lrineau** [comment]
For those who have access to Google Web Tools for http://doc.cgal.org/, the link of the alert is [here][link] (the message may be in French only; I do not know if the Google Tools provide a translation).

[link]: https://www.google.com/webmasters/tools/site-message-view?hl=fr&siteUrl=http://doc.cgal.org/&message-filter=all&grid.r=0&msgid=AB9YKzLhHiPKtKqIzxdor-JbVurTV9CbhlF2yQVyZUc__wk3mKI_P7Xwr5EtAWkKYH8J-lkX1p2w

**Comment by pranavkantgaur** [comment]
@lrineau Yes, I have also faced issues surfing http://doc.cgal.org/ on android device. I am not able to properly scroll the documentation pages.

**Comment by lrineau** [comment]
I have filled a bug in the Doxygen bug tracker:
  https://bugzilla.gnome.org/show_bug.cgi?id=746144
but I wonder if that topic should not be discussed in the Doxygen mailing lists instead.

**Comment by efifogel** [comment]
Just a side remark, I'm not an expert on this, but from my experience, I
can tell that "responsive" Web design is a compromise that not always makes
a page look better on some devices, and also makes it look worse on the
main target device, that is, a normal screen in our case.
In my opinion, for a Web page to display nicely, it must be manually
adapted to specific devices (e.g., screan size and resolution).

   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by pranavkantgaur** [comment]
@lrineau Following the directions given [here](http://coactionos.com/embedded%20design%20tips/2014/01/07/Tips-Integrating-Doxygen-and-Bootstrap/), Bootstrap can be integrated with Doxygen to fulfil the responsive web design requirements.

**Comment by lrineau** [comment]
Interesting!
@afabri, @CGAL/cgal-web-editors (esp. Clément, Philipp), what do you think of that?

**Comment by bo0ts** [comment]
That sounds like a good thing to do, although I'm not sure I like the solution in the link. The HTML output of Doxygen is quite stable, but we shouldn't rely too much on it. But coming up with a more robust solution - short of providing a separate Doxygen generator - does not seem possible.

**Comment by bo0ts** [comment]
This now has become a more pressing issue since [Google will soon rank website which work on mobile higher than websites which don't](http://blogs.wsj.com/digits/2015/04/20/websites-prep-for-googles-mobilegeddon/?mod=LS1) and doc.cgal.org is [failing the mobile-friendly test](https://www.google.com/webmasters/tools/mobile-friendly/?url=http%3A%2F%2Fdoc.cgal.org).

**Comment by lrineau** [comment]
I know. That is why I have opened this bug as soon as Google warned me, last month.

I find them a bit quick in the process...

**Comment by lrineau** [comment]
The following project seems more popular (more forks, more watch) than the link given by @pranavkantgaur at 
https://github.com/CGAL/cgal/issues/16#issuecomment-93902551

https://github.com/Velron/doxygen-bootstrapped

(Cc: @cjamin)

By the way, that is the oldest issue that is still open.

**Comment by lrineau** [comment]
Fix yesterday.
