### ISSUE TITLE
Use Gmpzf when Mpzf is not usable

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#1615]
@mglisse @afabri 

When `Mpzf` is not usable (32 bits), Marc says that we can now use `Gmpzf` instead of `MP_Float`. See
https://github.com/CGAL/cgal/pull/1548#issuecomment-255365331. Perf improvements are expected.

**Comment by mglisse** [comment]
I don't think the perf improvement is very large, but it must have existed at the time or I wouldn't have bothered using it in Exact_ring_selector. The patch would just remove `defined(CGAL_HAS_THREADS) || ` there.

**Comment by sloriot** [comment]
@mglisse @lrineau @afabri  shall we postpone to 4.11?

**Comment by lrineau** [comment]
The change seems small. But on which platforms will we test it? Only 32 bits platforms?

**Comment by mglisse** [comment]
I think there is no hurry about it and it can be postponed forever, relevant platforms can use Mpzf (or cannot use Gmpzf either because no GMP).

**Comment by lrineau** [comment]
I confirm that the only test platforms where the Number_types testsuite says "Mpzf is not supported on this platform" are only the `-32` Linux platforms. Even on 64 bits Windows platform, GMP probably uses the int64 type.

**Comment by lrineau** [comment]
I close this issue because the possible performance improvement is only for 32 bits platforms, that we only support as second class platforms. We do not have time to spend on this issue.
