### ISSUE TITLE
Add -DCGAL_PROFILE to check_headers

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#1622]

**Comment by afabri** [comment]
@lrineau Is that still needed? Why should  it be done? Is it trivial? Can you delegate it?

**Comment by lrineau** [comment]
@maxGimeno, now that you know pretty well the code of "check_headers", can you add the flag `-DCGAL_PROFILE`? I have no idea why I though it was important. Probably that addition will trigger new compilation errors.
