### ISSUE TITLE
Add L-infinity distance for 2D and 3D points in the Kernel

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#1624]
Add `Compute_L_infinity_distance_2` and `Compute_L_infinity_distance_3` into the Kernel.

See [here](http://doc.cgal.org/latest/Segment_Delaunay_graph_Linf_2/index.html#title0) for a definition.

**Comment by afabri** [comment]
I consider it as really non-trivial to add a function to the kernel. Not that Maxime was not capable to  do it, but it needs a lot of reverse-engineering, as it is not documented at all.

It might make sense, that I add it, and that I at the same time keep track of what I did.

**Comment by lrineau** [comment]
Note that it was asked (without any priority) by a customer of ours.

**Comment by afabri** [comment]
@maxGimeno :  Can you please do the same for the 3D function, taking my PR as recipe.

**Comment by sloriot** [comment]
I suggest to do it in the same branch as documentation wise, the free function will be in the same group.

**Comment by maxGimeno** [comment]
I would need access to @afabri  's repository to do so.
