### ISSUE TITLE
Box_intersection_d duplicates

### ISSUE THREAD

**Issue by MaelRL** [CGAL/cgal#1629]
In the package `Box_intersection_d`, the documentation says that the algorithm will return boxes intersections only once per pair of boxes, and that a box trivially intersects itself and thus is not reported either. The boxes carry an id such that this uniqueness is preserved.

In practice, this is not always the case: if one uses a `Box_d`, or a `Box_with_info_d` without specifying the `IDpolicy`, the box's id is simply the memory address of the box, casted as a size_t. This is all fine if one passes a container of pointers to Boxes to `CGAL::Box_self_intersection_d()`. However, if one passes Boxes by const references, the boxes are copied to go from `CGAL::Box_self_intersection_d()` to `box_intersection_custom_predicates_d()` that uses two different containers. This means that the same box has two different addresses and thus the function will return that any box intersects itself because `Traits::Id(box_1)` is different from `Traits_id(box_2)`, even though `box_1` and `box_2` are (geometrically) the same.

Even if `Box_with_info_d` is undocumented, this happens for `Box_d` too.

This can be avoided by simply passing boxes by pointer, but it could either be changed so that it also works for const ref, or given a big warning in the documentation (and maybe the code) not to pass by const ref if the default policy is being used.

Also, the `Box_with_info_d` could have a default template for `Idpolicy` similarly to `Box_with_handle_d` so that it doesn't necessarily go to the `ID_FROM_MEMORY_ADDRESS`.

**Comment by sloriot** [comment]
Indeed in `box_self_intersection_d()`, if a range of non pointer is passed, the box are copied and if the policy is `ADDRESS` then identical boxes cannot be filtered out (neither can identical pairs). One simple fix in the case `ADDRESS` policy is used is to internally use the address of the boxes. This implies also having a transform iterator to get a range of pointers.

**Comment by sloriot** [comment]
Alternatively, we could also simply have a static assertion to avoid this scenario.

**Comment by MaelRL** [comment]
The first report is somewhat wrong on a couple of points :
- the default policy of a simple box is not the address, but the explicit so it's fine.
- `box_self_intersection_d` not working with address-based IDs is documented, although it is not the most visible thing.

There are two possibilities:
- make it a bit clearer in the documentation
- make the code work with address-based IDs. The latter can be achieved by always using pointers, and thus if we are passed values, we switch to pointers, something like :

```
// box traits adapter: given a traits using values, create a pointer-based traits class
template<class Box_value_traits_d>
struct Box_traits_d_adapter {
    typedef typename boost::remove_cv<
              typename boost::remove_reference<
                typename Box_value_traits_d::Box_parameter>::type>::type  Box;

    typedef const Box*                                          Box_parameter;
    typedef typename Box::NT                                    NT;
    typedef typename Box::ID                                    ID;

    static NT  min_coord(Box_parameter b, int dim) { return Box_value_traits_d::min_coord(*b, dim);}
    static NT  max_coord(Box_parameter b, int dim) { return Box_value_traits_d::max_coord(*b, dim);}
    static ID  id(Box_parameter b)                 { return Box_value_traits_d::id(*b);}
    static int dimension()                         { return Box_value_traits_d::dimension();}
};

[...]

template< class RandomAccessIter, class Callback, class BoxTraits >
void box_self_intersection_d(
    RandomAccessIter begin, RandomAccessIter end,
    Callback callback,
    BoxTraits box_traits,
    std::ptrdiff_t cutoff,
    Box_intersection_d::Topology topology,
    typename boost::enable_if<
      boost::is_pointer<
        typename std::iterator_traits<RandomAccessIter>::value_type> >::type* =0)
{
    // Copying rather than calling 'box_intersection_d(begin, end, begin, end, ...'
    // is necessary because the 'std::partition' and range splits on the first range
    // would be messed up by sorts on the second range otherwise.
    typedef typename std::iterator_traits<RandomAccessIter>::value_type val_t;
    std::vector< val_t> i( begin, end);
    box_intersection_d( begin, end, i.begin(), i.end(),
        callback, box_traits, cutoff, topology, Box_intersection_d::COMPLETE);
}

// If the range's value type is boxes (and not box pointers) and if the id
// is determined by the address of the box, then copying the values will mean
// that the same box will have different IDs, meaning that a pair of the same
// box will be returned as a valid intersection, which shouldn't be the case.
//
// If the range's value type is boxes, we thus convert it to a range of pointers.
template< class RandomAccessIter, class Callback, class BoxTraits >
void box_self_intersection_d(
    RandomAccessIter begin, RandomAccessIter end,
    Callback callback,
    BoxTraits,
    std::ptrdiff_t cutoff,
    Box_intersection_d::Topology topology,
    typename boost::disable_if<
      boost::is_pointer<
        typename std::iterator_traits<RandomAccessIter>::value_type> >::type* =0)
{
  typedef typename std::iterator_traits<RandomAccessIter>::value_type val_t;
  typedef Box_intersection_d::Box_traits_d_adapter<BoxTraits>         Box_ptr_traits;

  std::vector<const val_t*> box_ptr;
  box_ptr.reserve(std::distance(begin, end));
  while(begin != end)
    box_ptr.push_back(&*begin++);

  std::vector<const val_t*> box_ptr_copy(box_ptr.begin(), box_ptr.end());

  box_intersection_d(box_ptr.begin(), box_ptr.end(),
                     box_ptr_copy.begin(), box_ptr_copy.end(),
                     callback, Box_ptr_traits(), cutoff, topology,
                     Box_intersection_d::COMPLETE);
}
```

Problem: I don't know when the IDs is based on the address of the box, so this code always switch to pointers, even when it's not needed. Thus, we go from creating a copy of a vector of boxes to creating two vectors of pointers to boxes. Could it still be acceptable because creating two vectors of pointers would potentially use less time / space than a copy of a vector of boxes ?

Also, we can't use a static assertion because we can't know when the ID is address-based.

**Comment by MaelRL** [comment]
Although creating two vectors of pointers is indeed cheaper in time and memory, the box_intersection_d algorithms run a lot more slowly (something like 3x) on pointer ranges rather than value ranges. The fact that it is much slower on pointer range is not created by the wrappers around the traits and callback mechanisms, you get the same ratio if you just run any example once with values, once with pointers.

On a random box range of 300000 boxes for `box_self_intersection_d`, it goes from

```
Creating duplicate value vertex took 0.005142s
Computation took 24.3184s
```
to

```
Creating duplicate pointer vertex took 0.001163s
Creating duplicate pointer vertex took 0.000775s
Computation took 77.8717s
```
so it's not a nice thing to force that internal switch to pointer.

Conclusion: won't add this feature and will just add a more visible warning not to use `box_self_intersection_d` with address-based IDs.

**Comment by MaelRL** [comment]
For the record, one needs some callback wrapper too, something like
```
template<typename Callback, typename Box_t>
struct Callback_wrapper
{
  typedef typename boost::result_of<Callback(const Box_t&, const Box_t&)>::type result_type;

  Callback_wrapper(Callback& f) : f_(&f) { }

  result_type operator()(const Box_t* a, const Box_t* b) { return _->operator()(*a, *b); }

private:
  Callback* f_;
};
```
