### ISSUE TITLE
Polyhedron demo wait cursor

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#1645]
@maxGimeno : I do not see a wait cursor when I do jet smoothing on a point set, although the function `QApplication::setOverrideCursor(Qt::WaitCursor)` is called right before the call to the smoothing function. 

[Googling](http://www.informit.com/articles/article.aspx?p=1405544&seqNum=3) I found that the function `QApplication::processEvents()` might help, and it does.

This raises the following questions
- When is this needed?  Does this have to do with TBB?
- Is this only needed for VC++?  @janetournois can you reproduce this?
- Is there any drawback when we call  `QApplication::processEvents()` ?

**Comment by janetournois** [comment]
what do you want me to test? If I can see the wait cursor? or if `QApplication::processEvents()` has an impact? If so, where should it be added?

**Comment by lrineau** [comment]
My crystal ball told me that if `processEvent()` has any effect after an override of the cursor, that might be because you try to override the cursor from a non-graphical thread. I have not had a look at the code to confirm. Just my 2 cents.

**Comment by janetournois** [comment]
same pb on my machine (vs2015, Qt 5.7)
