### ISSUE TITLE
Polyhedron demo: point set selection display looks bad

### ISSUE THREAD

**Issue by sgiraudot** [CGAL/cgal#1653]
This is probably tightly linked with https://github.com/CGAL/cgal/issues/1652 but I'm filling a different issue as it might be solved differently.

When loading a point set with "large" coordinates (see https://github.com/CGAL/cgal/issues/1652), the polyline used to display the selection rectangle looks bad: most of the time, it's not even a rectangle and if feels like its hitting walls and stopping at random locations. The selection, in the end, is fine and corresponds to the real rectangle the user traced (not the one displayed), as it is based on the projection on the screen, not on the polyline item. This makes the selection quite hard to use.

I guess the problem appears also if we load polylines with large coordinates.

So I can see 2 ways of correcting this bug:
- correcting https://github.com/CGAL/cgal/issues/1652 should do it (if we find a way to fix it, which I'm not sure we can)
- using 2D drawing on the window instead of a "fake" 2D rectangle drawed through a polyline object. I know this is possible as we talked about it with @maxGimeno. Of course, this would only solve the selection, not the polylines in general that can look bad with large coordinates.

**Comment by maxGimeno** [comment]
I will do a fix for this issue using the second way in a short time.

**Comment by afabri** [comment]
It works on Windows/VC++

**Comment by afabri** [comment]
the fix
