### ISSUE TITLE
Add a tag Parallel_if_available?

### ISSUE THREAD

**Issue by sgiraudot** [CGAL/cgal#1658]
When using parallelism with CGAL and TBB, if often find myself using the following piece of code to handle it:

```c++
#ifdef CGAL_LINKED_WITH_TBB
typedef CGAL::Parallel_tag Concurrency_tag;
#else
typedef CGAL::Sequential_tag Concurrency_tag;
#endif
```

Is it something that could be useful in CGAL? I understand that in some cases, one might want to execute some code in sequential mode even if TBB is present, but I'm pretty sure that in many cases, a user (like me) would simply want to activate parallelism as soon as TBB is available (which is what my piece of code above does) and fall back to sequential mode if it is not.

We can imagine adding a tag that does this, for example `CGAL::Parallel_if_available_tag`, `CGAL::Parallel_if_possible_tag` or `CGAL::Parallel_if_tbb_enabled_tag` (not sure about the name to choose).

**Comment by sloriot** [comment]
See https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Patch_to_concurrency_in_CGAL

**Comment by lrineau** [comment]
Simon, can you have a look at the discussion about the latest proposal of the small feature? Tell us if you approve the choices we made in the last proposal.

And next step will be to actually implement the proposal.

I Cc. @cjamin who is involved in the discussion as well.

**Comment by sgiraudot** [comment]
The proposal looks good to me and is indeed what I had in mind. It's also clearly an improvement to generate an error if `CGAL::Parallel_tag` is given without TBB available (that's already the case in `Point_set_processing`, I took care of that a while ago using static assertions).

I'm not a fan of the chosen names though:
- `CGAL_TBB_IS_AVAILABLE` is definitely better than `CGAL_LINK_WITH_TBB`, but for consistency (for example with `CGAL_EIGEN3_ENABLED`), I would prefer `CGAL_TBB_ENABLED` (although maybe we use the _is available_ expression too for other libraries, I don't know).
- `CGAL::Default_concurrency_tag` does not seem specific enough to me. It should be clear that it's a way to choose "the best solution available" (is that always the case?)

Do I need to add these remarks to the wiki page?

**Comment by sloriot** [comment]
Note that we could rename `CGAL_EIGEN3_ENABLED` to `CGAL_EIGEN3_IS_AVAILABLE` with a backward compatibility `#define` somewhere. I also prefer the `_IS_AVAILABLE` suffix

**Comment by sloriot** [comment]
Note that we could rename `CGAL_EIGEN3_ENABLED` to `CGAL_EIGEN3_IS_AVAILABLE` with a backward compatibility `#define` somewhere. I also prefer the `_IS_AVAILABLE` suffix

**Comment by sloriot** [comment]
Note that we could rename `CGAL_EIGEN3_ENABLED` to `CGAL_EIGEN3_IS_AVAILABLE` with a backward compatibility `#define` somewhere. I also prefer the `_IS_AVAILABLE` suffix

**Comment by cjamin** [comment]
I prefer the `_IS_AVAILABLE` suffix too. The other suffixes currently used in CGAL have always confused me.

**Comment by mglisse** [comment]
Or `CGAL_USE_TBB` and `CGAL_USE_EIGEN3`? (like zlib, ntl, gmp, etc)

**Comment by cjamin** [comment]
That's exactly the kind of names I find confusing. But maybe it's just me...

**Comment by lrineau** [comment]
I agree with Clément: `CGAL_USE_TBB` is particularly confusing, because the code will actually use TBB features only if the `Parallel_tag` is used. That is why we come up with `CGAL_TBB_IS_AVAILLABLE`. All the `CGAL_USE_*` should probably be renamed, unless they are actually commanding the CGAL code to use the `*`.

**Comment by mglisse** [comment]
I don't understand your point. If I compile a program that does 1+1 with -DCGAL_USE_ZLIB, I don't expect the program will suddenly start compressing my addition. Besides, it is not true that the code will only use TBB if Parallel_tag is used, that's the whole point of this discussion, it will also use TBB with the Default_parallelism_tag. If you all want to use ugly long _IS_AVAILABLE names, go ahead, I don't care, but I really don't find it clearer.

**Comment by janetournois** [comment]
Can we find a conclusion on that issue?
My vote also goes to the `IS_AVAILABLE` suffix, even if some other macros should be renamed for the sake of uniformity in the future

**Comment by cjamin** [comment]
As said above, the proposal is in [this small feature](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Patch_to_concurrency_in_CGAL), which is waiting for pre-approval by an editor I guess.

**Comment by janetournois** [comment]
ping @sloriot @afabri

**Comment by sgiraudot** [comment]
Can an editor (other than @lrineau and @cjamin who are authors) check and pre-approve [the small feature](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Patch_to_concurrency_in_CGAL) so we can move on with this issue? @sloriot or @afabri maybe?

**Comment by afabri** [comment]
It IS pre-approved by Clement who is the parallel expert and Laurent, so it should be good enough.

**Comment by sgiraudot** [comment]
I did not think the authors could pre-approve their own small features but okay.

**Comment by afabri** [comment]
I just added a comment on the small feature page.
