### ISSUE TITLE
Add simple functions to Poisson Reconstruction

### ISSUE THREAD

**Issue by sgiraudot** [CGAL/cgal#1659]
The Poisson reconstruction package is currently overly complicated to use. The [example](http://doc.cgal.org/latest/Poisson_surface_reconstruction_3/index.html#title4) is 400 lines long because there are lots of things the user needs to do to perform reconstruction (even defining by hand a bounding sphere).

Although I understand such a complicated API can be useful if the user wants to do something specific, it seems to me that currently, most users simply copy-paste parts of the example to use the package on their own, which seems highly suboptimal (that is even what is done in our own Polyhedron demo, there is a single file `Surface_reconstruction_plugin_impl.cpp` that has a huge function to deal with Poisson alone).

I suggest that in addition of the current API, we provide one or several function(s) similarly to what is done with [Advancing Front Surface Reconstruction](http://doc.cgal.org/latest/Advancing_front_surface_reconstruction/index.html#title5). Basically, functions that take as parameters:
- Input and property maps
- Parameters
- Output (a `CGAL::Polyhedron_3` for example)

What would be inside these functions is pretty much already provided by the example…

(I'm posting this issue both as a mean to start a discussion and as a reminder for myself, as I will probably take care of it.)

**Comment by lrineau** [comment]
Now fixed in `master` (for CGAL-4.11) by #2160.
