### ISSUE TITLE
Polyhedron demo: bugs in Scene_spheres_item

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#1667]
I am using `Scene_spheres_item`, independently from a `Scene_c3t3_item `, and I have seen bugs:

  1. in the constructor of `CGAL::Sphere_3`, the second argument is the **squared** radius! In the code of `Scene_c3t3_item` and `Scene_spheres_item`, the second argument is treated as a radius (a distance).

  2. For memory efficiency, `Scene_spheres_item` should store an array of spheres+colors, instead of an array of pointer+colors. Actually, I wonder why `addSphere` that not add to `d->centers`, `d->radius`and `d->colors` directly, instead of storing the data twice.

  3. The removal of *one* sphere in `Scene_spheres_item::remove_sphere` is quadradic:
```C++
void Scene_spheres_item::remove_sphere(CGAL::Sphere_3<Kernel> *sphere)
{
  Q_FOREACH(Sphere_pair pair_, d->spheres)
    if(pair_.first == sphere)
    {
      d->spheres.removeAll(pair_);
      break;
    }
}
```

This issue is not a priority, but you should consider having a look at it once you have time.

**Comment by maxGimeno** [comment]
How is it quadratic ? I thought the worst case was 2*N.

**Comment by lrineau** [comment]
You are right.
