### ISSUE TITLE
where can I find the .cpp file in CGAL

### ISSUE THREAD

**Issue by sutongkui** [CGAL/cgal#1676]
I download the source code of CGAL in Github, but I just find the .h file,no .cpp, where can I get it? cause there is only declaration of function in the class of .h, but i want to see the source code of the function. Thanks. such as AABB_tree.h, but where is the AABB_tree.cpp?

**Comment by lrineau** [comment]
CGAL is a library of C++ templates, and that is why most of the code is in C++ headers. The .cpp files you can find in CGAL are examples and applications, in the `examples/` and `demo/` sub-directories.

Have a look at `<CGAL/AABB_tree.h>` and you will see that the code is there.

**Comment by sutongkui** [comment]
yes,it is, but that's just examples and demos, what i want to find is the .cpp file corresponding to the .h file, such as there is a declaration of function  **get_nearest_point** in AABB_tree.h, but i want to know how it achieved, i mean its definition?

**Comment by sutongkui** [comment]
yes,it is, but that's just examples and demos, what i want to find is the .cpp file corresponding to the .h file, such as there is a declaration of function get_nearest_point in AABB_tree.h, but i want to know how it achieved, i mean its definition?

Thanks


Best!
Tongkui Su@smail.nju.edu.cn

 
From: Laurent Rineau
Date: 2016-11-09 21:05
To: CGAL/cgal
CC: Su Tongkui; State change
Subject: Re: [CGAL/cgal] where can I find the .cpp file in CGAL (#1676)
CGAL is a library of C++ templates, and that is why most of the code is in C++ headers. The .cpp files you can find in CGAL are examples and applications, in the examples/ and demo/ sub-directories.
Have a look at <CGAL/AABB_tree.h> and you will see that the code is there.
―

**Comment by sloriot** [comment]
As pointed out by @lrineau, the code is in the header file, mostly outside of the class `AABB_tree` in `CGAL/AABB_tree.h`. For example
