### ISSUE TITLE
Polyhedron_demo : Create Point Set From Vertices

### ISSUE THREAD

**Issue by maxGimeno** [CGAL/cgal#1680]
When trying to create a point set from a polyhedron using the Point_set_from_vertices_plugin, there is an assertion that fails and the demo crashes.
To reproduce, simply load an off and click on Operations->Create Point Set from Vertices.

**Comment by afabri** [comment]
@sgiraudot do you have a PR for this issue?

**Comment by sgiraudot** [comment]
Fixed by https://github.com/CGAL/cgal/pull/1691.
