### ISSUE TITLE
Approximate Haussdorf distance between two surface meshes

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#17]
We need a tool that computes an approximate (symmetric) Haussdorf distance between two surface meshes.

It would be useful for tests validation:
- in `Mesh_3`, we could use it to verify that the surfacic part of the output `c3t3` is a good approximation of the surface of the input domain (when the domain is composed from polyhedra).
- same with the ongoing work on `Constrained_Delaunay_triangulation_3`.

That tool could use the `AABB_tree` twice, to compute the one-way distance. Maybe we would need to compute a uniform sampling of the surfaces.

**Comment by sloriot** [comment]
I do have something working and doing exactly this

**Comment by lrineau** [comment]
I'll add a WG for the developers meeting. The goal will be try to adapt your code to the needs of `CDT_3` and `Mesh_3`.

**Comment by pranavkantgaur** [comment]
@lrineau 
I am also implementing 3D CDT using CGAL based on paper "Meshing Piecewise Linear Complexes By Constrained Delaunay Triangulations" by Hang Si.

Can you please share the reference on which the implementation of CDT_3 is based? 
Is it possible for us to access that code right now?

**Comment by lrineau** [comment]
Le Friday 13 March 2015 03:58:52 pranav a écrit :
> @lrineau 
> I am also implementing 3D CDT using CGAL based on paper "Meshing Piecewise
> Linear Complexes By Constrained Delaunay Triangulations" by Hang Si.
> 
> Can you please share the reference on which the implementation of CDT_3 is
> based?  Is it possible for us to access that code right now?

@pranav Our ongoing implementation is based on the same article, and it is not 
yet ready to be published. Please do not discuss that point in this bug. That 
is off-topic. Contact me privately if you want to discuss more about that.

-- 
Laurent Rineau, PhD
R&D Engineer at GeometryFactory           http://www.geometryfactory.com/
Release Manager of the CGAL Project       http://www.cgal.org/

**Comment by pranav** [comment]
I think you've got the wrong @pranavkantgaur :)

**Comment by lrineau** [comment]
@sloriot  We eventually have not talked about that at the developers meeting. But I still need the feature. Can you tell me (privately or not) in which branch and files I can see the current implementation?

**Comment by sloriot** [comment]
The branch is Polygon_mesh_processing-GF and the first implementation is in Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/distance.h

This is just a first step, the sampling is not statisfactory currently but the branch Gene

**Comment by lrineau** [comment]
Thanks. I can see that the "mesh" is already an abstraction. That is good because I want the distance between a polyhedron, and a set of triangles taken from a 3D triangulation.

**Comment by myirci** [comment]
There is a software for exactly doing this which also generates visual output. It is not open source but freely available. It is developed by VCG lab Italy. The same lab develops the opensource MeshLab. For more information you can visit:
http://vcg.isti.cnr.it/activities/surfacegrevis/simplification/metro.html
http://vcg.isti.cnr.it/publications/papers/metro.pdf
