### ISSUE TITLE
Assertion !is_zero(den) building an alpha shape

### ISSUE THREAD

**Issue by mglisse** [CGAL/cgal#1700]
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
    #include <CGAL/Delaunay_triangulation_3.h>
    #include <CGAL/Alpha_shape_3.h>

    #include <fstream>
    #include <vector>

    typedef CGAL::Exact_predicates_inexact_constructions_kernel Kernel;
    typedef CGAL::Alpha_shape_vertex_base_3<Kernel> Vb;
    typedef CGAL::Alpha_shape_cell_base_3<Kernel> Fb;
    typedef CGAL::Triangulation_data_structure_3<Vb, Fb> Tds;
    typedef CGAL::Delaunay_triangulation_3<Kernel, Tds> Triangulation_3;
    typedef CGAL::Alpha_shape_3<Triangulation_3> Alpha_shape_3;
    typedef Kernel::Point_3 Point_3;

    int main() {
      std::vector<Point_3> lp;
      lp.emplace_back(0.52, 0.38, 0.02);
      lp.emplace_back(0.54, 0.38, 0.02);
      lp.emplace_back(0.46, 0.66, 0.06);
      lp.emplace_back(0.48, 0.66, 0.06);
      lp.emplace_back(0.54, 0.66, 0.06);
      lp.emplace_back(0.56, 0.66, 0.06);
      lp.emplace_back(0.58, 0.66, 0.06);
      lp.emplace_back(0.42, 0.68, 0.06);
      lp.emplace_back(0.44, 0.7 , 0.06);
      lp.emplace_back(0.46, 0.72, 0.06);
      lp.emplace_back(0.48, 0.72, 0.06);
      lp.emplace_back(0.46, 0.24, 0.08);
      lp.emplace_back(0.48, 0.24, 0.08);
      lp.emplace_back(0.36, 0.28, 0.08);
      lp.emplace_back(0.38, 0.28, 0.08);
      lp.emplace_back(0.4 , 0.28, 0.08);
      lp.emplace_back(0.42, 0.28, 0.08);
      lp.emplace_back(0.52, 0.28, 0.08);
      lp.emplace_back(0.54, 0.28, 0.08);
      lp.emplace_back(0.54, 0.3 , 0.08);
      Alpha_shape_3 as(lp.begin(), lp.end(), 0, Alpha_shape_3::GENERAL);
    }

> terminate called after throwing an instance of 'CGAL::Assertion_exception'
>   what():  CGAL ERROR: assertion violation!
> Expr: ! CGAL_NTS is_zero(den)
> File: /usr/include/CGAL/constructions/kernel_ftC3.h
> Line: 185

**Comment by sloriot** [comment]
If you use the default Alpha-shape with inexact constructions, alpha values are constructions and the class cannot be safely used. If you use a Kernel with exact constructions or set the `ExactAlphaComparisonTag` to `Tag_true` like in this [`example`](http://doc.cgal.org/latest/Alpha_shapes_3/Alpha_shapes_3_2ex_alpha_shapes_exact_alpha_8cpp-example.html) the error goes away. It is somehow documented [here](http://doc.cgal.org/latest/Alpha_shapes_3/index.html#title6).
