### ISSUE TITLE
improve CGAL feedback form

### ISSUE THREAD

**Issue by MoniqueTeillaud** [CGAL/cgal#1705]
[cgal-discuss] CGAL Feedback form
16 Nov 2016, at 12:57, 
Patricio German Barletta Roldan <pbarletta@gmail.com> wrote:

Hi,
the question "6. Which Parts of CGAL Do You Use or Plan to Use?" only allows 1 answer. I think this kind of question may have many aswers.

Regards

**Comment by afabri** [comment]
fixed
