### ISSUE TITLE
IDs (displayed with CTRL+I) are not refreshed after an Euler operations

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#1706]
I have tried to display the IDs, using <kbd>Ctrl+I</kbd>, and at the same time use Euler operations on the polyhedron, to add a face to the border. After the Euler operation succeeded, the IDs were not refreshed.

**Comment by maxGimeno** [comment]
Actually it works, just keep in mind that CTRL+I only displays the ids of the selected item, if it is of type "Scene_print_interface_item". So you need to select the polyhedron_item, then get the focus back on the viewer, and only then you can use CTRL+I and it should work. At least it works for me.

**Comment by sloriot** [comment]
DId you explicitly call set id? Because if you create a need face or vertex, its id will not be set.

**Comment by maxGimeno** [comment]
The ids are reset every time you ask for their display.

Le 29 nov. 2016 2:30 PM, "Sebastien Loriot" <notifications@github.com> a
écrit :

**Comment by sloriot** [comment]
what is the status of this issue?
