### ISSUE TITLE
Isotropic_remeshing : problem with vertex_is_constrained_map

### ISSUE THREAD

**Issue by maxGimeno** [CGAL/cgal#1716]
In the doc for isotropic_remeshing, it is written for vertex_is_constrained_map that its type is a class model of ReadablePropertyMap.
 The problem is that a "put()" function is still required, or else the code won't compile. 
 @janetournois is the doc wrong or is this a bug in Isotropic_remeshing ?

**Comment by maxGimeno** [comment]
There is also a problem with "protect_constraints" : in the doc, it only says that it will protect the constrained edges, but in reality it also protects the constrained vertices.

**Comment by maxGimeno** [comment]
There is also a problem with "protect_constraints" : in the doc, it only says that it will protect the constrained edges, but in reality it also protects the constrained vertices.

**Comment by lrineau** [comment]
Jane, if the bug is in CGAL-4.9, create a PR against it, otherwise, target `master`.

**Comment by janetournois** [comment]
This is a doc bug, and it's in CGAL-4.9, indeed.
I will create a PR for it asap.
Thanks @maxGimeno

**Comment by lrineau** [comment]
Fixed by #1722.
