### ISSUE TITLE
Documentation error in PMP

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#1719]
Doc bug introduced by #1638:
https://cgal.geometryfactory.com/CGAL/Manual_doxygen_test/CGAL-4.10-Ic-57/Polygon_mesh_processing.log
> doc/Polygon_mesh_processing/Polygon_mesh_processing.txt:416: Warning: unable to resolve reference to `Polygon_mesh_processing/compute_normals_example_Polyhedron.cpp' for \ref command

**Comment by afabri** [comment]
fixed
