### ISSUE TITLE
i canr build on osx

### ISSUE THREAD

**Issue by texrg** [CGAL/cgal#172]
in documentation is 
cd examples/Straight_skeleton_2 
directory non exist
ano other way not working cmake with parameters nothin create

lib will create but example,demos etc not

**Comment by lrineau** [comment]
The directory `examples/Straight_skeleton_2/` does exist in CGAL-4.6!

If you have an issue compiling CGAL example, please copy-paste the CMake errors, or the compilation errors, here.
