### ISSUE TITLE
Handling the last dont_submit files

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#1728]
Follow up of #1446

Some `dont_submit` files are remaining:
- [x] `Installation` : 4 files related to the `changes.html` file
- [ ] `wininst` : some files are ignored. Can the whole directory be ignored?
- [ ] `Three` : Only the documentation,  while waiting for a review.
- [x] `Operations_on_polyhedra` :  will disappear soon with a merge of a small feature

**Comment by lrineau** [comment]
@sloriot: Why have you assign this task to Maxime? For all items in the list, you need to know a lot about the internals of the CGAL project to be able to conclude.

**Comment by sloriot** [comment]
I'm sure he can investigate how things work for creating the windows installer from the script that is in the docker container (my guess was that the whole directory can be ignored by the release creation script) and propose something for Installation.

**Comment by lrineau** [comment]
@maxGimeno I have reassigned the issue to you. Discuss with Sébastien for the details.

**Comment by sgiraudot** [comment]
@maxGimeno any update on this issue? Are you still working on it?

**Comment by maxGimeno** [comment]
Still waiting for clear instructions.
Low priority.

**Comment by lrineau** [comment]
- For `Installation/`: we should try to convert our changes.html to a Markdown file,
- for `wininst/`, the `dont_submit` file can be removed,
- for `Three/doc`, that is one good reason to keep `dont_submit` files.
