### ISSUE TITLE
CGAL_Qt5_FOUND returns false

### ISSUE THREAD

**Issue by johndpope** [CGAL/cgal#1735]
I ran

 brew install cgal
Warning: cgal-4.9 already installed

# using macports
#sudo port install cgal
#sudo port install cgal +qt5 +universal +demos # with the demos

presumably brew doesn't have cgal qt5 support?

```
if ( CGAL_FOUND AND CGAL_Qt5_FOUND AND Qt5_FOUND )

//do stuff
else()

  message(STATUS "NOTICE: This demo requires CGAL and Qt5, and will not be compiled.")

endif()


```

I'm seeing CGAL_Qt5_FOUND returning false - and throwing error.

**Comment by maxGimeno** [comment]
Hello. You can check the path cmake is using for Qt5, maybe it is wrong ?

**Comment by lrineau** [comment]
Unfortunately, the CGAL project does not maintain the CGAL macport. You should fill a bug in the macports bug tracker.

**Comment by elahea2020** [comment]
I have this issue on ubuntu 18.04. Any idea how I can resolve it? 

I get this: Impossible to draw, CGAL_USE_BASIC_VIEWER is not defined.
 
When I try to run Triangulation_2/examples/Triangulation_2/draw_triangulation_2.cpp

**Comment by maxGimeno** [comment]
Hello, 
You are probably missing the path to Qt5 in your cmake config(Qt_dir/Qt_version/architecture//lib/cmake/Qt5).
