### ISSUE TITLE
install CGAL and issue about libQGLViewer

### ISSUE THREAD

**Issue by ahu-carry** [CGAL/cgal#1746]
in the installation,when I do: qmake.exe nmake,,,I can't find the generated DLL files.
also the Command Prompt show these:

(too many so I choose a few words...)

C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1157) : erro
r C2144: 语法错误:“void”的前面应有“;”
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1157) : erro
r C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1157) : erro
r C2086: “int WINGDIAPI”: 重定义
        C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1152
) : 参见“WINGDIAPI”的声明
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1157) : erro
r C2146: 语法错误: 缺少“;”(在标识符“glBindTexture”的前面)
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1157) : erro
r C2182: “APIENTRY”: 非法使用“void”类型
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1157) : erro
r C2086: “int APIENTRY”: 重定义
        C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1152
) : 参见“APIENTRY”的声明
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1157) : erro
r C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1157) : erro
r C2556: “int glBindTexture(GLenum,GLuint)”: 重载函数与“void glBindTexture(GL
enum,GLuint)”只是在返回类型上不同
        ..\..\Qt\Qt5.0.1\5.0.1\msvc2010\include\GLES2/gl2.h(480) : 参见“glBindT
exture”的声明
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1157) : erro
r C2371: “glBindTexture”: 重定义；不同的基类型
        ..\..\Qt\Qt5.0.1\5.0.1\msvc2010\include\GLES2/gl2.h(480) : 参见“glBindT
exture”的声明
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1158) : erro
r C2144: 语法错误:“void”的前面应有“;”
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1158) : erro
r C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1158) : erro
r C2086: “int WINGDIAPI”: 重定义
        C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1152
) : 参见“WINGDIAPI”的声明
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1158) : erro
r C2146: 语法错误: 缺少“;”(在标识符“glBitmap”的前面)
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1158) : erro
r C2182: “APIENTRY”: 非法使用“void”类型
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1158) : erro
r C2086: “int APIENTRY”: 重定义
        C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1152
) : 参见“APIENTRY”的声明
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1158) : erro
r C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1159) : erro
r C2144: 语法错误:“void”的前面应有“;”
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1159) : erro
r C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1159) : erro
r C2086: “int WINGDIAPI”: 重定义
        C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1152
) : 参见“WINGDIAPI”的声明
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1159) : erro
r C2146: 语法错误: 缺少“;”(在标识符“glBlendFunc”的前面)
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1159) : erro
r C2182: “APIENTRY”: 非法使用“void”类型
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1159) : erro
r C2086: “int APIENTRY”: 重定义
        C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1152
) : 参见“APIENTRY”的声明
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1159) : erro
r C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1159) : erro
r C2556: “int glBlendFunc(GLenum,GLenum)”: 重载函数与“void glBlendFunc(GLenum
,GLenum)”只是在返回类型上不同
        ..\..\Qt\Qt5.0.1\5.0.1\msvc2010\include\GLES2/gl2.h(484) : 参见“glBlend
Func”的声明
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1159) : erro
r C2371: “glBlendFunc”: 重定义；不同的基类型
        ..\..\Qt\Qt5.0.1\5.0.1\msvc2010\include\GLES2/gl2.h(484) : 参见“glBlend
Func”的声明
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1160) : erro
r C2144: 语法错误:“void”的前面应有“;”
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1160) : erro
r C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1160) : erro
r C2086: “int WINGDIAPI”: 重定义
        C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1152
) : 参见“WINGDIAPI”的声明
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1160) : erro
r C2146: 语法错误: 缺少“;”(在标识符“glCallList”的前面)
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1160) : erro
r C2182: “APIENTRY”: 非法使用“void”类型
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1160) : erro
r C2086: “int APIENTRY”: 重定义
        C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1152
) : 参见“APIENTRY”的声明
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1160) : erro
r C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1161) : erro
r C2144: 语法错误:“void”的前面应有“;”
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1161) : erro
r C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1161) : erro
r C2086: “int WINGDIAPI”: 重定义
        C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1152
) : 参见“WINGDIAPI”的声明
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1161) : erro
r C2146: 语法错误: 缺少“;”(在标识符“glCallLists”的前面)
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1161) : erro
r C2182: “APIENTRY”: 非法使用“void”类型
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1161) : erro
r C2086: “int APIENTRY”: 重定义
        C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1152
) : 参见“APIENTRY”的声明
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1161) : erro
r C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1162) : erro
r C2144: 语法错误:“void”的前面应有“;”
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1162) : erro
r C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1162) : erro
r C2086: “int WINGDIAPI”: 重定义
        C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1152
) : 参见“WINGDIAPI”的声明
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1162) : erro
r C2146: 语法错误: 缺少“;”(在标识符“glClear”的前面)
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1162) : erro
r C2182: “APIENTRY”: 非法使用“void”类型
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1162) : erro
r C2086: “int APIENTRY”: 重定义
        C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1152
) : 参见“APIENTRY”的声明
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1162) : erro
r C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1162) : erro
r C2556: “int glClear(GLbitfield)”: 重载函数与“void glClear(GLbitfield)”只是
在返回类型上不同
        ..\..\Qt\Qt5.0.1\5.0.1\msvc2010\include\GLES2/gl2.h(489) : 参见“glClear
”的声明
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1162) : erro
r C2371: “glClear”: 重定义；不同的基类型
        ..\..\Qt\Qt5.0.1\5.0.1\msvc2010\include\GLES2/gl2.h(489) : 参见“glClear
”的声明
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1163) : erro
r C2144: 语法错误:“void”的前面应有“;”
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1163) : erro
r C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1163) : erro
r C2086: “int WINGDIAPI”: 重定义
        C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1152
) : 参见“WINGDIAPI”的声明
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1163) : erro
r C2146: 语法错误: 缺少“;”(在标识符“glClearAccum”的前面)
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1163) : erro
r C2182: “APIENTRY”: 非法使用“void”类型
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1163) : erro
r C2086: “int APIENTRY”: 重定义
        C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1152
) : 参见“APIENTRY”的声明
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1163) : erro
r C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1164) : erro
r C2144: 语法错误:“void”的前面应有“;”
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1164) : erro
r C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1164) : erro
r C2086: “int WINGDIAPI”: 重定义
        C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1152
) : 参见“WINGDIAPI”的声明
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1164) : erro
r C2146: 语法错误: 缺少“;”(在标识符“glClearColor”的前面)
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1164) : erro
r C2182: “APIENTRY”: 非法使用“void”类型
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1164) : erro
r C2086: “int APIENTRY”: 重定义
        C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1152
) : 参见“APIENTRY”的声明
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1164) : erro
r C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1164) : erro
r C2556: “int glClearColor(GLclampf,GLclampf,GLclampf,GLclampf)”: 重载函数与“
void glClearColor(GLclampf,GLclampf,GLclampf,GLclampf)”只是在返回类型上不同
        ..\..\Qt\Qt5.0.1\5.0.1\msvc2010\include\GLES2/gl2.h(490) : 参见“glClear
Color”的声明
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1164) : erro
r C2371: “glClearColor”: 重定义；不同的基类型
        ..\..\Qt\Qt5.0.1\5.0.1\msvc2010\include\GLES2/gl2.h(490) : 参见“glClear
Color”的声明
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1165) : erro
r C2144: 语法错误:“void”的前面应有“;”
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1165) : erro
r C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1165) : erro
r C2086: “int WINGDIAPI”: 重定义
        C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1152
) : 参见“WINGDIAPI”的声明
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1165) : erro
r C2146: 语法错误: 缺少“;”(在标识符“glClearDepth”的前面)
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1165) : erro
r C2182: “APIENTRY”: 非法使用“void”类型
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1165) : erro
r C2086: “int APIENTRY”: 重定义
        C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1152
) : 参见“APIENTRY”的声明
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1165) : erro
r C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1166) : erro
r C2144: 语法错误:“void”的前面应有“;”
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1166) : erro
r C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1166) : erro
r C2086: “int WINGDIAPI”: 重定义
        C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1152
) : 参见“WINGDIAPI”的声明
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1166) : erro
r C2146: 语法错误: 缺少“;”(在标识符“glClearIndex”的前面)
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1166) : erro
r C2182: “APIENTRY”: 非法使用“void”类型
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1166) : erro
r C2086: “int APIENTRY”: 重定义
        C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1152
) : 参见“APIENTRY”的声明
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1166) : erro
r C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1167) : erro
r C2144: 语法错误:“void”的前面应有“;”
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1167) : erro
r C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1167) : erro
r C2086: “int WINGDIAPI”: 重定义
        C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1152
) : 参见“WINGDIAPI”的声明
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1167) : erro
r C2146: 语法错误: 缺少“;”(在标识符“glClearStencil”的前面)
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1167) : erro
r C2182: “APIENTRY”: 非法使用“void”类型
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1167) : erro
r C2086: “int APIENTRY”: 重定义
        C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1152
) : 参见“APIENTRY”的声明
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1167) : erro
r C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1167) : erro
r C2556: “int glClearStencil(GLint)”: 重载函数与“void glClearStencil(GLint)”
只是在返回类型上不同
        ..\..\Qt\Qt5.0.1\5.0.1\msvc2010\include\GLES2/gl2.h(492) : 参见“glClear
Stencil”的声明
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1167) : erro
r C2371: “glClearStencil”: 重定义；不同的基类型
        ..\..\Qt\Qt5.0.1\5.0.1\msvc2010\include\GLES2/gl2.h(492) : 参见“glClear
Stencil”的声明
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1168) : erro
r C2144: 语法错误:“void”的前面应有“;”
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1168) : erro
r C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1168) : erro
r C2086: “int WINGDIAPI”: 重定义
        C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1152
) : 参见“WINGDIAPI”的声明
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1168) : erro
r C2146: 语法错误: 缺少“;”(在标识符“glClipPlane”的前面)
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1168) : erro
r C2182: “APIENTRY”: 非法使用“void”类型
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1168) : erro
r C2086: “int APIENTRY”: 重定义
        C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1152
) : 参见“APIENTRY”的声明
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1168) : erro
r C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1169) : erro
r C2144: 语法错误:“void”的前面应有“;”
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1169) : erro
r C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1169) : erro
r C2086: “int WINGDIAPI”: 重定义
        C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1152
) : 参见“WINGDIAPI”的声明
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1169) : erro
r C2146: 语法错误: 缺少“;”(在标识符“glColor3b”的前面)
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1169) : erro
r C2182: “APIENTRY”: 非法使用“void”类型
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1169) : erro
r C2086: “int APIENTRY”: 重定义
        C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1152
) : 参见“APIENTRY”的声明
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1169) : erro
r C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1170) : erro
r C2144: 语法错误:“void”的前面应有“;”
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1170) : erro
r C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1170) : erro
r C2086: “int WINGDIAPI”: 重定义
        C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1152
) : 参见“WINGDIAPI”的声明
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1170) : erro
r C2146: 语法错误: 缺少“;”(在标识符“glColor3bv”的前面)
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\GL/gl.h(1170) : fata
l error C1003: 错误计数超过 100；正在停止编译
Generating Code...
NMAKE : fatal error U1077: “"d:\Program Files\Microsoft Visual Studio 2010\VC\B
IN\x86_amd64\cl.EXE"”: 返回代码“0x2”
Stop.
NMAKE : fatal error U1077: “"d:\Program Files\Microsoft Visual Studio 2010\VC\B
IN\nmake.exe"”: 返回代码“0x2”
Stop.

I'm Chinese,a university student,pool in English,but a wish you can solve my question,Thanks T_T
(I can't come to this website all the time,here is my e-mail address:xxxxtjqmc@126.com,Thank you again!)

**Comment by sloriot** [comment]
The issue seems to be about compiling libQGLViewer. You should post directly there. I close the issue, feel free to reopen it if I missed something.
