### ISSUE TITLE
BGL: improvement of `split_graph_into_polylines`

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#1766]
If I have a graph that has attributes attached to edges, and not only to vertices, I would like to be able to get those attributes in the visitor used by `split_graph_into_polylines`.

Suggestion of implementation: 
- in the copy of the graph, attach to each edge the `edge_descriptor` of the original edge,
- in `duplicate_terminal_vertices`, for each couple of `remove_edge`/`add_edge`, the attribute must be transferred,
- the visitor should have a function `add_edge`.

**Comment by sloriot** [comment]
@lrineau you have a PR fixing that, right?

**Comment by lrineau** [comment]
I am working on a branch. The PR is still not ready. I think it will make into CGAL-4.10.

**Comment by lrineau** [comment]
See #1793.

**Comment by lrineau** [comment]
Fixed by #1793.
