### ISSUE TITLE
Need extra properties in statistics...

### ISSUE THREAD

**Issue by palliez** [CGAL/cgal#1770]
It is possible to compute statistics and list properties on polyhedral surfaces. 
I think it would be important to also list:
- genus (trivial from Euler formula once we have components, boundaries, etc)
- stats per face 
- size of bbox

**Comment by lrineau** [comment]
> stats per face

What do you mean? I am pretty sure you do not want to add a piece of information for each face of the surface (non-practicle once the surface as more than hundreds of faces) , but I do not see how to interpret that differently.

**Comment by maxGimeno** [comment]
And the bbox's size is already in the Info dockwindow of every item

**Comment by janetournois** [comment]
@maxGimeno can you please add the genus to the polyhedral surfaces statistics?

@palliez can you please be more specific about "stats per face"?

**Comment by palliez** [comment]
Stats on faces (when pure triangle):
- about area: min, max, median, mean 
- about shape: min altitude, aspect ratio (min, max, mean), where aspect ratio is longest edge divided by smallest altitude

**Comment by lrineau** [comment]
I reopen the issue, because the genus is not computed.

**Comment by maxGimeno** [comment]
Sorry I had the branch in local, I guess I wanted to wait for the integration of the first part and then I forgot.

**Comment by lrineau** [comment]
The computation of the genus is now implemented, by @maxGimeno in #2019. This issue is now fully completed, and closed.
