### ISSUE TITLE
Feature needed: Hide cutting plane

### ISSUE THREAD

**Issue by palliez** [CGAL/cgal#1774]
(For @maxGimeno ?)

I was unable to create a snapshot of a tet mesh where the cutting plane (grid) is hidden. 
It would be very good to be able to hide it. 

pierre

**Comment by maxGimeno** [comment]
If your master is up to date, you should be able to uncheck "show grid" in the context menu of your c3t3 item (right click in the list or shift right click on the item in the viewer).

**Comment by maxGimeno** [comment]
See #1477
