### ISSUE TITLE
Poisson reconstruction when points have no normals

### ISSUE THREAD

**Issue by palliez** [CGAL/cgal#1778]
Poisson crashes when executed with point sets that have no normal attributes. 
It would be nice to check and prevent execution.

**Comment by maxGimeno** [comment]
In Master, if the point_set has no normals, we estimate them. With sphere_1K.xyz, I have no problem. Maybe you have a really old branch, or maybe the crash is in the normal estimation of your point_set ?

**Comment by lrineau** [comment]
I close this issue, for now. Pierre, reopen it if you can reproduce it with a recent version of the demo.
