### ISSUE TITLE
Fix our .travis.yml file

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#1779]
Our `.travis.yml` triggers jobs that are too long to finish before the timeout.

The solution is to decompose our current jobs (g++ and clang++) into multiple shorter jobs.

**Comment by lrineau** [comment]
Actually, a full support a Travis would also add the building of demos and tests. But, before that, we will need a solution for the polyhedron demo, that by itself might require more than 50mn to build.

**Comment by maxGimeno** [comment]
Should we make a job per package P that compiles CGAL and the examples for P ?
