### ISSUE TITLE
Segfault of the Polyhedron demo when closing it

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#178]
This happens if any item is present while the demo is closed

**Comment by maxGimeno** [comment]
It should be corrected. It was due to a misplaced macro in Polyhedron_demo_scale_space_reconstruction_plugin

**Comment by sloriot** [comment]
No it's not. I should have mentioned that I only compiled Polyhedron_3 and off_plugin.

**Comment by lrineau** [comment]
Is not that bug already fixed?

**Comment by sloriot** [comment]
@maxGimeno implemented 28b8c3bf6bc8ac512edae55c50827f94103b1115 which seems to fix the segfault but item destructors seem to be no longer called now when closing the app (while being called when item are removed).

**Comment by lrineau** [comment]
The call to `deleteLater()` in CGAL/cgal-public-dev@28b8c3bf does not work because, when the destructor of the `Scene` is called, the event loop of the application is already closed.

See the documentation: http://doc.qt.io/qt-5/qobject.html#deleteLater

**Comment by lrineau** [comment]
I will deal with that issue. The solution is to use only one `QOpenGLFunctions` object: the base class of the `Viewer`.

**Comment by lrineau** [comment]
Fixed by CGAL/cgal-public-dev@1d2657b0692ab729d7ff4bd3c4b8a3717ddd48b9

The same should be applied to Mesh_3 demo, to fix the issue #203.

**Comment by lrineau** [comment]
I have implemented the same in Mesh_3. See CGAL/cgal-public-dev@94a793621d18dea62482a0b659d5e6c2e5b5ac16
