### ISSUE TITLE
Segment_Delaunay_graph_Linf_2 testsuite does not compile without GMP

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#1780]
Compilation error without GMP:

https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.9.1-I-168/Segment_Delaunay_graph_Linf_2/TestReport_cgaltester_x86-64_Darwin-13.0_Apple-clang-5.1_Release-LEDA-without-GMP.gz

**Comment by afabri** [comment]
I think this is what I reported in Issue #731

**Comment by lrineau** [comment]
Indeed.
