### ISSUE TITLE
Detect -I .../include/CGAL

### ISSUE THREAD

**Issue by mglisse** [CGAL/cgal#1790]
Hello,
it happens quite regularly that some users add .../include/CGAL (sometimes in addition to .../include) to their include path and get "mysterious" errors as a result. I think it might help to add a file CGAL/stddef.h (or some other standard header that usually gets included early) that just contains a `#error` line explaining what the problem is. An alternative would be to test in CGAL/gmp.h (since that's often where the errors start) that after including gmp.h some macro (__GNU_MP_VERSION for instance) is defined.

**Comment by afabri** [comment]
I also noticed it in some CMakeList.txt of examples directories. That had the effect that when I set CGAL_DIR to something else than the root of my branch build, say to a particular release, the code
got compiled with a blend of the package and the release. whereas I had thought to compile with
the headers of the particular release.

**Comment by lrineau** [comment]
@afabri You mix things up.

* You are talking about  `-I../../include`.
* Marc is talking about `-I../include/CGAL`, that is a non-sense because CGAL headers names are like`<CGAL/Point_2.h>`, and not `<Point_2.h>`.

**Comment by lrineau** [comment]
@mglisse Is the PR #1807 what you had in mind?

**Comment by mglisse** [comment]
Yes, thanks :smile:.
