### ISSUE TITLE
One error in examples/reconstruction_structured.cpp on Windows10_MSVC2017-Debug-64bits

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#1817]
```
------------------------------------------------------------------
- ProgramOutput.reconstruction_structured.x64_Cygwin-Windows10_MSVC2017-Debug-64bits
------------------------------------------------------------------
CGAL::Random()::get_seed() = 1484084526
CGAL::Random()::get_seed() = 1484084526
Shape detection... done
Point set structuring... done
Advancing front... CGAL error: assertion violation!
Expression : ! CGAL_NTS is_zero(den)
File       : C:\CGAL\test\CGAL-4.10-Ic-98\include\CGAL/constructions/kernel_ftC3.h
Line       : 185
Explanation: 
Refer to the bug-reporting instructions at http://www.cgal.org/bug_report.html
```
https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.10-Ic-98/Advancing_front_surface_reconstruction_Examples/TestReport_afabri_x64_Cygwin-Windows10_MSVC2017-Debug-64bits.gz

it might worth to retry with the same seed, and try to debug the issue.

(I have assigned the issue to several of you, because I am not sure who is in charge of Advancing_front_surface_reconstruction.)

**Comment by sgiraudot** [comment]
The structured reconstruction depends on point set structuring, so I'm pretty sure this is related to https://github.com/CGAL/cgal/issues/1818. I'll investigate.

**Comment by sgiraudot** [comment]
(Turns out it's not related.)

**Comment by afabri** [comment]
This reveals a bug in Advancing_front_surface_reconstruction.
At some point the algorithm computes the squared radius of a circumsphere of an almost degenerate cell ( = tetrahedron).   The cell is almost degenerate as the structuring means to generate points on planes. As the squared_radius function is not exact we hit a division by 0.
