### ISSUE TITLE
first_intersection() returns centroid in 3 out of 4 cases instead of skipping it in AABB_ray_shooting_example.cpp

### ISSUE THREAD

**Issue by adrian-bodenmann** [CGAL/cgal#1821]
In http://doc.cgal.org/latest/AABB_tree/ 3.3 Ray Shooting the explanation says:

> As the centroid is computed with floating point arithmetic the first face hit by the ray may be the face of the centroid. The skip functor takes care of ignoring the face.

However, in 3 out of 4 cases first_intersection() returns the centroid ([https://gist.github.com/adrian-bodenmann/dfa880e3ef9a3ad20c5838d5cc7c7ec4#file-aabb_ray_shooting_example_bugreport-cpp](https://gist.github.com/adrian-bodenmann/dfa880e3ef9a3ad20c5838d5cc7c7ec4#file-aabb_ray_shooting_example_bugreport-cpp).) The `Skip struct` defined before the main function is not used, which I suppose was meant to prevent this. 
Changing line 64 to 
`Ray_intersection intersection = tree.first_intersection(ray, Skip(fd));`
solves the issue, but outputs a messge `ignoref0` (counting up each time: `ignoref1`, `ignoref2`, `ignoref3`).

tetrahedron.off is in your CGAL installation folder in examples/AABB_tree/data, or alternatively available at 
[https://github.com/CGAL/cgal/blob/master/AABB_tree/test/AABB_tree/data/tetrahedron.off](https://github.com/CGAL/cgal/blob/master/AABB_tree/test/AABB_tree/data/tetrahedron.off)

**Comment by lrineau** [comment]
*Note: I have assigned this issue to Andreas, Sébastien, and Philipp. Philipp did most of the implementation of `first_intersection` (mentored by Andreas and Sébastien), in October-November 2015. Then the code was slightly modified by Andreas and Sébastien recently, in April-May 2016.*

**Comment by sloriot** [comment]
Thanks for the report, the example was indeed not using the functor. Fixed by #1833

**Comment by sloriot** [comment]
About the 3 out of 4, it is due to the inexact construction of the centroid. The point is not exactly on the face and thus the face is not reported.

**Comment by adrian-bodenmann** [comment]
I think the face *is* reported. 
3 out of 4 cases it just reports the centroid, which is correct (as it is the intersection with the closest face), but not the one what we are interested in. That's why the functor Skip should be used. 
In the 4th case when it is on the face (1 0 0) (0 1 0) (0 0 1) (with centroid (0.333 0.333 0.333) it returns (0 0 0), so I think that is correct, i.e. the face / intersection is reported.

**Comment by adrian-bodenmann** [comment]
Ah, now I understood what you meant: The intersection at (0.333 0.333 0.333) is not reported [but others still may be reported].

It seems to be the case that the 3 other intersections with the 3 faces with a corner at (0 0 0) are indeed reported: 
If I add 
`std::cout << "Number of intersected primitives: " << tree.number_of_intersected_primitives(ray) << std::endl;`
before 
`const Point* p = boost::get<Point>(&(intersection->first));`
it returns 
`Number of intersected primitives: 3`

**Comment by lrineau** [comment]
Fixed by #1833 in the CGAL-4.9.1 branch.
