### ISSUE TITLE
first_intersection() doesn't always return the intersection closest to the point of the ray query

### ISSUE THREAD

**Issue by adrian-bodenmann** [CGAL/cgal#1822]
The code at [https://gist.github.com/adrian-bodenmann/1727c845bfa38cb29851a757dab44d61](https://gist.github.com/adrian-bodenmann/1727c845bfa38cb29851a757dab44d61) returns
`First intersection: 0.4 0.5 -0`
instead of 
`First intersection: 0.4 0.5 0.1`

Tested on Windows 7, Visual Studio 2013, CGAL 4.9

**Comment by sloriot** [comment]
Thanks for the report, see #1833

**Comment by lrineau** [comment]
Fixed by #1833 in the CGAL-4.9.1 branch.
