### ISSUE TITLE
Pre-fill issues in Github

### ISSUE THREAD

**Issue by sgiraudot** [CGAL/cgal#1828]
Github offers a way to [pre-fill issues](https://github.com/blog/2111-issue-and-pull-request-templates) (as you can see [for example here](https://github.com/wallabag/wallabag/issues/new)). I think we should do this for the CGAL repository to help the users fill a comprehensive issue (there are lots of issues where we need to ask questions about the configuration or even for a code sample). This could also be a way to give pointers to the most frequent problems (for example, users who have a weird output just because they did not use the right kernel, etc.).

I suggest we discuss what to put in the message here. Here's a first draft:

> ## Issue details
> 
> _Describe your issue. Please be specific (compilation error, runtime error, unexpected behavior, wrong results, etc.)._
> 
> ## Source code
> 
> _If your issue arises by using CGAL in your own source code, please provide a minimalist example that we can compile easily to reproduce the bug. If your issue arises from using a CGAL program (demo, example, etc.), please let us know which one. Helping you solving an issue is much easier and efficient if we can reproduce it._
> 
> ## Environment
> 
> * Operating system (Windows/Mac/Linux, 32/64 bits):
> * Compiler:
> * Release or debug mode
> * Specific flags used (if any):
> * CGAL version:
> * Boost version:
> * Other libraries versions if used (Eigen, TBB, etc.):
> 
> ## Frequently encountered issues
> 
> * Kernel: are you using an exact or inexact kernel?
> * (...)

For this last section, we should maybe discuss what to put and where to redirect the user (documentation, wiki, etc.).

**Comment by lrineau** [comment]
There is also a way to have a link at the top of the "new issue" form:

![](https://help.github.com/assets/images/help/pull_requests/Contributing-guidelines.jpg)

See https://help.github.com/articles/setting-guidelines-for-repository-contributors/

**Comment by sgiraudot** [comment]
Nice, that will be better than the "Frequently encountered issues" that I talk about (we can give a link to a section of the documentation for example).

**Comment by sgiraudot** [comment]
Solved by https://github.com/CGAL/cgal/pull/1839.
