### ISSUE TITLE
Doc: links to `SearchTraits` not generated

### ISSUE THREAD

**Issue by cjamin** [CGAL/cgal#1831]
The links to `SearchTraits` from outside of the Spatial_searching package are not generated. Examples:
* http://doc.cgal.org/latest/Point_set_shape_detection_3/classEfficientRANSACTraits.html#a633c37821ace1e5fb43d515f7e6a51e2
* http://doc.cgal.org/latest/Snap_rounding_2/classSnapRoundingTraits__2.html#a5a2eb027ae79905194171906edb3c608

And I'm having the same issue when trying to add a link to `SearchTraits` in the "is model of" section of `Epick_d`.

Any clue what's happening?

**Comment by sloriot** [comment]
Add Spatial_searching in `dependencies` of those packages.

**Comment by lrineau** [comment]
What prevents us from having all packages depend on all the other packages?⁣

Envoyé par BlueMail ​

Le 13 janv. 2017 13:28, à 13:28, Sebastien Loriot <notifications@github.com> a écrit:

**Comment by sloriot** [comment]
Increase of the compilation time, more likely to be exposed to a doxygen bug

**Comment by cjamin** [comment]
Thank you Sébastien, it works!

**Comment by lrineau** [comment]
Fixed by #1835 and #1836.
