### ISSUE TITLE
Create CMake list support for LAStools

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#1846]
[LAStools](https://github.com/LAStools/LAStools) currently has a Makefile and a project file for Microsoft Developer Studio.  It would be nice to come up with a decent support for CMake for building the library LASlib and the tools. We are mainly interested in the library, so that the examples and demos of CGAL can read _las_ files, but to increase the chance that CMake makes it into LAStools we also should do the work for the tools.

**Comment by lrineau** [comment]
@afabri Can you please push your prototype of support for CMake in afabri/LAStools?

**Comment by lrineau** [comment]
ping @afabri!

**Comment by afabri** [comment]
It is already pushed See this [commit](https://github.com/afabri/LAStools/commits/Add_CMakeLists-GF)  in its own branch.

**Comment by lrineau** [comment]
@sgiraudot

**Comment by sgiraudot** [comment]
All the changes @afabri and I made (including the `CMakeLists` for LASlib) are in the following branch: https://github.com/afabri/LAStools/tree/integration

I think one more thing we could do is add a `LASlibConfig.cmake`, but I'm not sure how to do that. I created a [`FindLIBlas.cmake`](https://github.com/CGAL/cgal-public-dev/blob/Point_set_processing-Las_IO-GF/Installation/cmake/modules/FindLASLIB.cmake) in my branch to read LAS, but in practice it does not find anything by itself (it just creates the needed variables in CMake, which is sufficient to make it usable with CGAL).

**Comment by lrineau** [comment]
1. Is this issue still valid?
2. If it is, what is expected from Maxime?

**Comment by maxGimeno** [comment]
@afabri @sgiraudot ping

**Comment by sgiraudot** [comment]
This issue is still valid. I think what is left to do is making a good `FindLASLIB.cmake` file, but most importantly we need to decide how we handle LASlib (this will be discussed at the developer meeting).

I don't think Maxime has anything to do right now.

**Comment by sgiraudot** [comment]
This issue was fixed by https://github.com/CGAL/cgal/pull/2138.
