### ISSUE TITLE
Add test_merge_of_branch in Travis

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#1847]
Calling the script `test_merge_of_branch` in the Travis job would be interesting.
To avoid issue when the branch has conflict with master, I guess the call should be make in the first common parent commit.

**Comment by sloriot** [comment]
@lrineau we can close the issue as it was implemented a while ago, right?

**Comment by lrineau** [comment]
Yes, sure. Thanks for pointing that out.
