### ISSUE TITLE
AABB first_intersection prints to standard out

### ISSUE THREAD

**Issue by funchal** [CGAL/cgal#1850]
https://github.com/CGAL/cgal/blob/40a54cf/AABB_tree/include/CGAL/internal/AABB_tree/AABB_ray_intersection.h#L183

**Comment by lrineau** [comment]
@sloriot: Sébastien, should this line be replaced by a `CGAL_error_msg`, or should the display be removed completely?

**Comment by sloriot** [comment]
That's a bug fixed by #1853
