### ISSUE TITLE
Loading a large OFF takes ages

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#1865]
## Issue Details

I tried loading a big mesh (350k vertices) and it takes more than 20s while it tooks a few second with 4.9

**Comment by afabri** [comment]
In the Polyhedron demo or in a standalone.cpp ?
For a Polyhedron_3 or for a Surface_mesh, or both?

**Comment by sloriot** [comment]
See the label: 3D demo.
With polyhedron. It is fast with Surface_mesh but the result is not what I'd expect...
![screenshot from 2017-01-30 08-49-07](https://cloud.githubusercontent.com/assets/1224632/22415612/1091e4cc-e6c9-11e6-853b-aaf148feb546.png)
