### ISSUE TITLE
Give access to `Primitive_helper::get_datum` in AABB_tree

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#1872]
In the AABB_tree package, when one uses a query to get something-and-primitive-id, there is no easy way to get the datum, from the ID. I propose that we add:
```C++
auto AABB_tree::datum(Primitive_id) const;
```
where the return type would actually be given by a traits class.

Everything is currently implemented in the internal file `<CGAL/internal/AABB_tree/Primitive_helper.h>`.

**Comment by lrineau** [comment]
cc @janetournois, who requested that function just 10 minutes ago, while I had already discuss that with Sébastien a few days ago... We need that method.

**Comment by sloriot** [comment]
Note that in case of shared data it might not be trivial and currently impossible if the tree contains several meshes. cc @maxGimeno

**Comment by lrineau** [comment]
Nothing in the documentation of AABB tree says that primitive IDs must be unique. For all I know, all primitives could return `0` as ID. That means that we cannot have an API taking IDs as input.

So I fix my demand:
```C++
auto AABB_tree::datum(Primitive) const;
```

My need is a way to generically compute the datum of a given primitive, without the need to know if the AABB tree has shared data or not. That functionality is already in `<CGAL/internal/AABB_tree/Primitive_helper.h>` but it should be exposed in a documented function.
