### ISSUE TITLE
Detect documentation bugs

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#1874]
## Issue Details

SInce the documentation is not inline for all packages, we should guarantee that documented header and real headers are the same. For example, we document `#include <CGAL/IO/output_surface_facets_to_off.h>` for `CGAL::output_surface_facets_to_off ()` while this header does not exist  (the real header is `CGAL/IO/Complex_2_in_triangulation_3_file_writer.h`)

- [ ] The simple thing we can do it to update `test_merge_of_branches` to check that any header in `doc/PKG/CGAL` exists. There might be false positive if the header is not in the package but I'm pretty sure we can workaround these.
- [ ] The second part of this issue is to fix the errors

**Comment by lrineau** [comment]
Maxime, Sébastien and I assigned that issue to you. The priority will be decided later, at https://github.com/orgs/CGAL/projects/1. That issue will be a good exercise to improve again your scripting skills. You can choose your prefered scripting language (between shell/bash and Python).

**Comment by lrineau** [comment]
The priority is actually rather high, because we would like to fix those kind of bugs before CGAL-4.10-beta1, due next week.

**Comment by lrineau** [comment]
...in two weeks, actually.
