### ISSUE TITLE
Implicit conversion of Weighted_Point_3 to Point_3

### ISSUE THREAD

**Issue by MaelRL** [CGAL/cgal#1878]
The small feature for `Weighted_point_3` has the following:

>  **Conversion point <-> weighted point. Make things consistent between 2,3D and dD?**
> 
>     decision during the CGAL meeting (March 2016): we will remove the implicit conversion,
>     but we postpone this change. 
> In dD, weighted points are not convertible to bare points (Marc's decision when writing the kernel,
> see also below); in 2,3D, they are. Having such an implicit conversion has pros (predicates and 
> functors written for bare points - and more generally any code dealing with points - works 
> automatically with weighted points) and cons (risk of losing the weight by an implicit conversion
> without getting an error or a warning).--Cjamin 18:04, 27 May 2016 (CEST) 

Looking at the branch that was integrated, this change was not included in the end.

I was working on updating regular periodic triangulations and this resulted in a bug when simply calling `construct_weighted_circumcenters(wp1, wp2, wp3, wp4)` due to a generic class (on the way) not finding a match for the functor using weighted points and defaulting to a conversion of `Weighted_Point_3` into `Point_3`.

Is the consensus still on the removal of the conversion ? Can it be done now ? Is there anything more subtle to do than removing the constructors and providing the extra functions where it relied on the implicit conversion ?

 @cjamin, @mglisse, @lrineau, @MoniqueTeillaud, @janetournois

**Comment by MaelRL** [comment]
An example of problem that shows up when preventing the conversion:

Function calls like `construct_plane(p,q,r)` (`p`, `q`, `r` being of type `Weighted_Point_3`) in `Regular_triangulation_3.h` will break.

More subtle, now that `Regular_triangulation_3` derives from a `Triangulation_3` templated by `Weighted_point_mapper_3<Gt>`, it also means that calling a base function in `Triangulation_3` from `Regular_triangulation_3`, e.g. `tetrahedron(T3::Point, T3::Point, T3::Point, T3::Point)`, will not work, because `T3::Point` is actually `Weighted_point_3`.

Either these geometric functions should then have an overload for `Weighted_point_3` (in function_objects.h / respective class constructors), or the code in T3 / RT3 should explicit use `Point_3` `tetrahedron(construct_point_3(T3::Point), construct_point_3(T3::Point), construct_point_3(T3::Point), construct_point_3(T3::Point) )`, which looks a bit silly when the `Triangulation_3` is not the base of a `Regular_triangulation_3` (and there is also the problem of getting back the proper traits, `Gt`, and not `Weighted_point_mapper_3<Gt>`)

**Comment by lrineau** [comment]
That's exactly why that is not so simple. How is that handled in dD? @cjamin, @mglisse?

**Comment by cjamin** [comment]
In dD, `Regular_triangulation` inherits from `Triangulation<Regular_triangulation_traits_adapter<Traits>, ...>`. This adapter adapts some functors so that they drop the weight when appropriate. I guess it's about the same as what you call `Weighted_point_mapper_3`.

The whole thing is a bit tricky and I don't remember the details. Please have a look at the code and come back to me if you have questions.

**Comment by MaelRL** [comment]
For tracking: Andreas is working to remove the implicit conversions, in [this branch](https://github.com/afabri/cgal/commits/Kernel_Weighted_point_without_conversion-GF).
