### ISSUE TITLE
Demos runtime issue using Qt-5.5

### ISSUE THREAD

**Issue by janetournois** [CGAL/cgal#188]
Hi,

because this info can be useful to users of CGAL demos using QGLViewer and Qt5 under Windows 8 and MSVC 2013, please let me point out the following issue.

At runtime, starting a demo that uses QGLViewer 2.6.2 or 2.6.3 with Qt-5.5.0,
on Windows 8, with MSVC 2013, needs to set the following environment variable
`QT_QPA_PLATFORM_PLUGIN_PATH=%QTDIR%\plugins\platforms\`
(in my case `QTDIR` is "..QT-5.5.0\5.5\msvc2013_64")

Otherwise, the `QApplication` constructor crashes at runtime.
Hope it helps!

**Comment by lrineau** [comment]
We should read http://doc.qt.io/qt-5/windows-deployment.html carefully.

**Comment by lrineau** [comment]
Jane (@janetournois), was it eventually documented somewhere?

**Comment by janetournois** [comment]
I don't think so. Do you want me to add something to the installation manual?

**Comment by sloriot** [comment]
See 470e96e7

**Comment by janetournois** [comment]
this issue is about MSVC2013, while the commit you mention is about MSVC2015

**Comment by sloriot** [comment]
Sorry I read the thread too quickly, it is indeed not related.

**Comment by lrineau** [comment]
The issue is actually about all versions of Qt 5.5, on Windows, whatever compiler is used.

**Comment by lrineau** [comment]
Jane, what do you think we should write in the installation manual?

There is that page http://doc.qt.io/qt-5/windows-deployment.html about deploying on Windows. But that mostly explain how to deploy a Qt5 application to a machine that does not have Qt5.

The variable `QT_QPA_PLATFORM_PLUGIN_PATH` is documented in the documentation page for [`QGuiApplication`][1]. In my opinion that variable is not needed if the developer has installed Qt5 and not moved it afterward.

There is also [that StackOverflow answer][2] that explains how Qt5 hardcodes the paths in various files.

[1]: http://doc.qt.io/qt-5/qguiapplication.html
[2]: http://stackoverflow.com/a/17640221/1728537

**Comment by janetournois** [comment]
I think we could add something in the installation section, in a subsection about Qt5 for Windows.

Simply mentioning that the variable QT_QPA_PLATFORM_PLUGIN_PATH should be set as said in QGuiApplication is enough imho.
We would just give the CGAL users the clues to be able to use it.

Deployment on Windows is somehow another issue, not directly related to this one.

**Comment by lrineau** [comment]
As I said, I think that for most users that variable will not be needed. I think that your installation was special: you copied and moved an existing installation.

For a brand new installation of Qt5, Qt5 hardcodes its own paths somewhere (in binaries, and optionally in a file `qt.conf`), and no variable is needed, I think.

**Comment by cjamin** [comment]
On Windows 7 64-bit, I did not have to set this variable.

**Comment by janetournois** [comment]
I'll try a new installation.
@cjamin did you let it install in "Program Files" and such automatic places, or id you choose another place?

**Comment by cjamin** [comment]
I chose another place.

**Comment by lrineau** [comment]
See also https://github.com/GillesDebunne/libQGLViewer/issues/17

**Comment by janetournois** [comment]
Our conclusion is that some paths are hardcoded by the Qt5 installer.
So, copying an installation from one place to another on the same computer, or to another computer, breaks these hardcoded paths.

The environment variable QT_QPA_PLATFORM_PLUGIN_PATH should be set only if one has such a copy-pasted installation of Qt5.
