### ISSUE TITLE
Remnants of SVN in headers & documentation

### ISSUE THREAD

**Issue by MaelRL** [CGAL/cgal#1892]
The [File header documentation](http://doc.cgal.org/latest/Manual/devman_code_format.html#secfile_header) and some headers (e.g. [this one](https://github.com/CGAL/cgal/blob/master/AABB_tree/include/CGAL/internal/AABB_tree/Primitive_helper.h)) still mention SVN.

Is there any reason not to clean it? Should it be updated to do the same with Git or just completely removed?

**Comment by sloriot** [comment]
I would vote for removing them

**Comment by afabri** [comment]
@lrineau any opinion on this?

**Comment by lrineau** [comment]
It seems that most of the existing headers (2852 out of 3032) have `$URL$` and `$Id$`.

I would not recommend that we forcefully remove those SVN keywords from all headers.

I propose a choice, for a discussion:
- The first possibility is to deprecate the use of those headers: remove their mention from the documentation.
- The second possibility is to restore a usage of those keywords: for example, the release creation script could substitute them to give of the mapping between the Git layout and the tarball layout.

**Comment by afabri** [comment]
In order to get what from the second possibility?

**Comment by lrineau** [comment]
> mapping between the Git layout and the tarball layout

For example, the file `CGAL-x.y/include/CGAL/Has_timestamp.h` of the tarball would mention in `$Id: $` its full path in the Git layout: `STL_Extension/include/CGAL/Has_timestamp.h`, as well as the "Date" and the hash of the last commit that modified it. Maybe the `$URL: $` could point to the file in the Github website, so that the use can access the history, or other contextual information given by the Github user interface.

**Comment by sgiraudot** [comment]
Can we carry on this discussion and take a decision?

I like the second possibility, with the drawback that it can create broken links on old releases.

**Comment by sloriot** [comment]
I'm adding the dev-meeting flag

**Comment by MaelRL** [comment]
Putting the path of the file with the commit hash (of the release), e.g.
[https://github.com/CGAL/cgal/blob/75a9c1fbc2e8f72f6a09eb3e98fe37dffb47ca85/Mesh_3/include/CGAL/Mesh_3/Robust_weighted_circumcenter_filtered_traits_3.h](https://github.com/CGAL/cgal/blob/75a9c1fbc2e8f72f6a09eb3e98fe37dffb47ca85/Mesh_3/include/CGAL/Mesh_3/Robust_weighted_circumcenter_filtered_traits_3.h) allows to have the Git path, the hash, the date, and is a safe link.

**Comment by MaelRL** [comment]
See https://github.com/CGAL/cgal/pull/2606 for the new uses of the tags $URL$ and $ID$.
