### ISSUE TITLE
Polyhedron demo - `off_plugin` crashes on some input

### ISSUE THREAD

**Issue by janetournois** [CGAL/cgal#1897]
## Issue Details

For some input `off` files, the `off_plugin` crashes. I attach one example. It may be that the data inside is corrupted, but the demo should not crash. It should for example send an error pop-up message.

## Environment

* Operating system : Windows, 64 bits
* Compiler: msvc 2016
* Release
* CGAL version: `master`
[x29_plane.zip](https://github.com/CGAL/cgal/files/766560/x29_plane.zip)

**Comment by sloriot** [comment]
Same on my linux. I bet this comes from the triangulation of non-triangular faces.

**Comment by sloriot** [comment]
Seems that at least one face is degenerated:
```
  0 -23.532 9.6370000000000005
  0 -23.532 9.6370000000000005
  0 -14.292999999999999 2.4350000000000001
  0 -14.292999999999999 2.4350000000000001
```

**Comment by sloriot** [comment]
First face is :
```
4 1 1 0 0
```

**Comment by sloriot** [comment]
This [commit](https://github.com/sloriot/cgal/commit/f013db43ab17a767d12f1101ffb1d20f0f9e31ad) is a possible fix for the issue.
Drawbacks:
- This slow down the reading since we check for duplicated vertex indices
- I guess `read_OFF` should read the OFF no matter what. The handling of degenerate faces (filtering) should be done in the soup item itself, with probably a warning.

What do you think?

**Comment by janetournois** [comment]
I think the degenerate face should be part of the polygon soup, and not discarded. We could then have algorithms to detect them/remove them/fix the polygon soup.

**Comment by lrineau** [comment]
@sloriot, https://github.com/CGAL/cgal/issues/1897#issuecomment-278948659:
> This [commit][c] is a possible fix for the issue.
> Drawbacks:
>  -  This slow down the reading since we check for duplicated vertex indices
> -   I guess read_OFF should read the OFF no matter what. The handling of degenerate faces (filtering) should be done in the soup item itself, with probably a warning.
> 
> What do you think?

[c]: https://github.com/sloriot/cgal/commit/f013db43ab17a767d12f1101ffb1d20f0f9e31ad

I agree read_OFF should just read the OFF, and then let the code using the polygon soup do the verification/processing.
