### ISSUE TITLE
Warning in script_cgal.nsi

### ISSUE THREAD

**Issue by bo0ts** [CGAL/cgal#190]
When building a CGAL installer using `script_cgal.nsi` the warning

> 1 warning:
>   install function "StrReplace" not referenced - zeroing code (0-31) out

is issued. Can someone familiar with nsis confirm that the code is actually dead and that we can remove it?

**Comment by lrineau** [comment]
As far as I can see, the `StrReplace` function/macro can be removed, as well as the files `ReplaceInFile.nsh` and `StrRep.nsh`.
