### ISSUE TITLE
missing links in wiki

### ISSUE THREAD

**Issue by MoniqueTeillaud** [CGAL/cgal#1903]
https://github.com/CGAL/cgal/wiki/Examples-and-Demo-Programs

"See Sections sec:examples_subdirectory 4.3 and sec:demo_subdirectory 4.4"

I guess that there should be hyperlinks to the corresponding sections.

**Comment by maxGimeno** [comment]
I added the [missing linkslink](https://github.com/CGAL/cgal/wiki/Examples-and-Demo-Programs#introduction)

**Comment by lrineau** [comment]
I have verified that the links are added.
