### ISSUE TITLE
Better handling of the initialization of index map

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#1918]
When using polyhedron with ids, the default index property map do not have their ids initialized. This is an issue in algorithms than rely on it being initialized.

Recently, in `copy_face_graph()` I've introduced a mechanism that always initialize the id map (if writable) which is a bad thing if the user does not expect the ids of its const polyhedron to be modified.

We need to find a workaround for this.

**Comment by MaelRL** [comment]
For tracking: the same mechanism is also used in the implementation of the DooSabin subdivision method (`subdivision_hosts_impl_3.h`).

**Comment by janetournois** [comment]
Note also for PMP : in `CGAL/Polygon_mesh_processing/border.h`, a warning message is displayed via `std::cerr` when a face index map is provided but the indices of the two first faces of the face range are the same wrt this property map.
It is not very satisfactory either.
If a better workaround is found, it should be used there too.

**Comment by sloriot** [comment]
I also saw that some methods in Subdivision_methods are using explicitly unordered maps (that code could be updated).

**Comment by sloriot** [comment]
One solution is to document a function signature to be called and say in the documentation of this function can be called by ADL. I guess this could be a concept like `InitializableIndexMap`.

Function signature could be something like.
`size_type initialize_index_map(size_type, imap, descriptor_range, pm)`

@CGAL/geometryfactory  what do you think?

**Comment by lrineau** [comment]
How would you make the ADL-call compile when the function does not exist?

**Comment by sloriot** [comment]
The function relying on it will document that the pmap must be a model of the concept which means that the function must exist.
