### ISSUE TITLE
Warning in the Polyhedron demo on Windows

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#1924]
- [x] The first one is only in 32  bits: https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.10-Ic-133/Polyhedron_Demo/TestReport_afabri_x64_Cygwin-Windows8_MSVC2013-Release-32bits.gz and that is probably a known one (@sgiraudot?)

- [x] The other one is new, and was hidden by red cells because of the timeout:
```
C:\CGAL\test\CGAL-4.10-Ic-133\cmake\platforms\x64_Cygwin-Windows8_MSVC2013-Release-64bits\test\Polyhedron_Demo\Plugins\Surface_mesh\Scene_polyhedron_shortest_path_item.cpp(144) : warning C4267: 'argument' : conversion from 'size_t' to 'int', possible loss of data
C:\CGAL\test\CGAL-4.10-Ic-133\cmake\platforms\x64_Cygwin-Windows8_MSVC2013-Release-64bits\test\Polyhedron_Demo\Plugins\Surface_mesh\Scene_polyhedron_shortest_path_item.cpp(194) : warning C4267: 'argument' : conversion from 'size_t' to 'GLsizei', possible loss of data
```
https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.10-Ic-133/Polyhedron_Demo/TestReport_afabri_x64_Cygwin-Windows8_MSVC2013-Release-64bits.gz

Cc: @janetournois @afabri

**Comment by sgiraudot** [comment]
For the first one, we indeed saw it already (maybe not in here).

There is a problem in the counting iterator where the difference type is not correct. But anyway we change it, we get a warning (sometimes a different if I remember correctly). This is one of those warnings on which we spent quite a long time and couldn't find a solution except disable it…

I did not look at the code for the second one, but it looks more like a regular warning that is easy to fix.

**Comment by lrineau** [comment]
So the "fix" for the first warning is a few lines of `#pragma`, to deactivte the warning?

**Comment by lrineau** [comment]
The second type of warnings are fixed but not the first one.
https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.10-Ic-142/Polyhedron_Demo/TestReport_afabri_x64_Cygwin-Windows8_MSVC2013-Release-32bits.gz

**Comment by lrineau** [comment]
... As Jane pointed out (in a private communication), the first warning seems fixed too.
