### ISSUE TITLE
Mesh_3: create a piecewise-manifold criteria, for polyhedral complexes

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#1925]
Even if the 2D surface of the mesh domain is not manifold, it is usually piecewise-manifold, being non-manifold only at the 1D curve segments of the domain. There could be a special piecewise-manifold criterion, that ensures that the only non-manifold edges of the c3t3 should be edges corresponding to the 1D curve segments of the domain.

Cc: @janetournois

**Comment by lrineau** [comment]
Each 1D-curve of the domain could have a property that qualifies the topology of surfaces incident to the curve. For a polyhedral complex, for each edge of the curve, we can compute the number of incident facets of the polyhedra, and store the max of that number on the whole curve.

Note that it can be different from the number of incident patches, because a T-junction, for example, can be between only two patches, or even only one that self-intersects.

Given that knowledge, the manifold criterion could be enforced for edges where the number of incident sheets of surfaces is smaller or equal to 2.

**Comment by janetournois** [comment]
The manifold criterion does not try to fix manifoldness where features are protected.
Elsewhere, it seems that PR #7754 does what you want.

@lrineau do you agree that ##7754 fixes this issue?
