### ISSUE TITLE
Polyhedron demo: port plugins to use Surface_mesh

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#1931]
We would like to port plugin of the "polyhedron demo" to use the BGL API and the `Surface_mesh` class instead of `Polyhedron_3`.

The rational (taken from #1932): 
> We should use the Scene_surface_mesh_item where it is possible, as it is more efficient in terms of memory consumption. We should integrate the plugins by package, to dispatch tests and to avoid a too important difference with the current master branch.

- [x] AABB_tree (#1953)
- [ ] Convex_decomposition
- [ ] Convex_hull
- [x] IO
- [ ] Mesh_2
- [ ] Mesh_3
- [x] Operations_on_polyhedra (#1941)
- [ ] PCA
- [ ] PMP
- [ ] Point_set
- [ ] Subdivision_methods
- [ ] Surface_mesh
- [ ] Surface_mesh_deformation

Here is the list of files that include `Scene_polyhedron_item.h` *and* do not include `Scene_surface_mesh_item.h`:

  - [ ] `Scene_c3t3_item.h`
  - [ ] `Scene_nef_polyhedron_item.cpp`
  - [ ] `Scene_polygon_soup_item.cpp`
  - [ ] `Scene_polyhedron_item.cpp`
  - [ ] `Plugins/AABB_tree/Cut_plugin.cpp`
  - [ ] `Plugins/PCA/Create_bbox_mesh_plugin.cpp`
  - [ ] `Plugins/PCA/Pca_plugin.cpp`
  - [ ] `Plugins/PCA/Scene_polyhedron_transform_item.h`
  - [ ] `Plugins/PCA/Edit_box_plugin.cpp`
  - [ ] `Plugins/Mesh_3/Detect_sharp_edges_plugin.cpp`
  - [ ] `Plugins/Mesh_3/Optimization_plugin_cgal_code.cpp`
  - [ ] `Plugins/Mesh_3/Mesh_3_plugin.cpp`
  - [ ] `Plugins/IO/OFF_io_plugin.cpp`
  - [ ] `Plugins/IO/GOCAD_io_plugin.cpp`
  - [ ] `Plugins/IO/Surf_io_plugin.cpp`
  - [ ] `Plugins/IO/STL_io_plugin.cpp`
  - [ ] `Plugins/IO/VTK_io_plugin.cpp`
  - [ ] `Plugins/Convex_decomposition/Nef_plugin.cpp`
  - [ ] `Plugins/Surface_mesh_deformation/Edit_polyhedron_plugin.cpp`
  - [ ] `Plugins/Surface_mesh_deformation/Scene_edit_polyhedron_item.h`
  - [ ] `Plugins/Point_set/Surface_reconstruction_plugin.cpp`
  - [ ] `Plugins/Point_set/Point_set_shape_detection_plugin.cpp`
  - [ ] `Plugins/Surface_mesh/Remeshing_plugin.cpp`
  - [ ] `Plugins/Surface_mesh/Mesh_simplification_plugin.cpp`
  - [ ] `Plugins/Surface_mesh/Mesh_segmentation_plugin.cpp`
  - [ ] `Plugins/Surface_mesh/Shortest_path_plugin.cpp`
  - [ ] `Plugins/Surface_mesh/Remeshing_plugin_cgal_code.cpp`
  - [ ] `Plugins/Surface_mesh/Parameterization_plugin.cpp`
  - [ ] `Plugins/Convex_hull/Convex_hull_plugin.cpp`
  - [ ] `Plugins/Convex_hull/Kernel_plugin.cpp`
  - [ ] `Plugins/Operations_on_polyhedra/Clip_polyhedron_plugin.cpp`
  - [ ] `Plugins/Operations_on_polyhedra/Point_set_from_vertices_plugin.cpp`
  - [ ] `Plugins/PMP/Inside_out_plugin.cpp`
  - [ ] `Plugins/PMP/Point_inside_polyhedron_plugin.cpp`
  - [ ] `Plugins/PMP/Polyhedron_slicer_plugin.cpp`
  - [ ] `Plugins/PMP/Corefinement_plugin.cpp`
  - [ ] `Plugins/PMP/Polyhedron_stitching_plugin.cpp`
  - [ ] `Plugins/PMP/Repair_polyhedron_plugin.cpp`
  - [ ] `Plugins/PMP/Surface_intersection_plugin.cpp`
  - [ ] `Plugins/PMP/Distance_plugin.cpp`
  - [ ] `Plugins/PMP/Selection_plugin.cpp`
  - [ ] `Plugins/PMP/Join_and_split_polyhedra_plugin.cpp`
  - [ ] `Plugins/PMP/Hole_filling_polyline_plugin.cpp`
  - [ ] `Plugins/PMP/Hole_filling_plugin.cpp`
  - [ ] `Plugins/PMP/Jet_fitting_plugin.cpp`
  - [ ] `Plugins/PMP/Isotropic_remeshing_plugin.cpp`
  - [ ] `Plugins/PMP/Mean_curvature_flow_skeleton_plugin.cpp`
  - [ ] `Plugins/PMP/Triangulate_facets_plugin.cpp`
  - [ ] `Plugins/Mesh_2/Mesh_2_plugin.cpp`
  - [ ] `Plugins/Subdivision_methods/Subdivision_methods_plugin.cpp`
  - [ ] `Scene_polyhedron_item_k_ring_selection.h`
  - [ ] `Scene_polyhedron_item_decorator.h`

That task will be assigned to Maxime (@maxGimeno) and targets CGAL-4.11. Hopefully the "polyhedron demo" will have a better name in six months.

**Comment by afabri** [comment]
In order to minimize the effort not all plugins are needed to work on Polyhedron and Surface_mesh. For example I would exclude the shortest path plugin. In order to demo it, it is enough to convert from a Surface_mesh toa Polyhedron.

Also the plugins with a lot of interaction should just be ported, as it seems a rather big effort to make them work on both at the same time.

**Comment by maxGimeno** [comment]
Edit : 
- [x] AABB_tree
-[ ] Convex_decomposition
-[ ] Convex_hull
-[x] IO
-[ ] Mesh_2
-[ ] Mesh_3
-[x] Operations_on_polyhedra
-[ ] PCA
-[ ] PMP
-[ ] Point_set
-[ ] Subdivision_methods
-[ ] Surface_mesh
-[ ] Surface_mesh_deformation

**Comment by maxGimeno** [comment]
travis failed

**Comment by maxGimeno** [comment]
It shouldn't be closed yet, there is a lot of other PR waiting and some not done yet about this.

**Comment by lrineau** [comment]
The closing of this bug is automatic, for each PR that contains the text "fix #1931" in its description. Something I reopened this issue myself, but they are too many. Now I will let you deal with this issue, reopen it and update as any times as needed.

**Comment by lrineau** [comment]
Actually, this issue should be replaced by one of yours, like #1932.
