### ISSUE TITLE
CGAL sample failed on Mac while I run it well on Windows

### ISSUE THREAD

**Issue by lcj0117** [CGAL/cgal#1938]
_Please use the following template to help us solving your issue._

## Issue Details
Here is the run time error, I try to run the sample 'skeletonization'(the example extracts a medially centered skeleton from a given mesh) under Xcode on my Mac, but it always give the error, I can not solve this, also I run it well on my Windows.
"
CGAL error: precondition violation!
Expression : rows > 0
File       : /usr/local/Cellar/cgal/4.9/include/CGAL/Eigen_matrix.h
Line       : 109
Explanation: 
Refer to the bug-reporting instructions at http://www.cgal.org/bug_report.html
libc++abi.dylib: terminating with uncaught exception of type CGAL::Precondition_exception: CGAL ERROR: precondition violation!
Expr: rows > 0
File: /usr/local/Cellar/cgal/4.9/include/CGAL/Eigen_matrix.h
Line: 109
Program ended with exit code: 9
"
## Source Code

#define CGAL_EIGEN3_ENABLED

#include <CGAL/Simple_cartesian.h>
#include <CGAL/Polyhedron_3.h>
#include <CGAL/IO/Polyhedron_iostream.h>
#include <CGAL/boost/graph/graph_traits_Polyhedron_3.h>
#include <CGAL/boost/graph/properties_Polyhedron_3.h>
#include <CGAL/extract_mean_curvature_flow_skeleton.h>
#include <fstream>
#include <boost/foreach.hpp>

typedef CGAL::Simple_cartesian<double>                        Kernel;
typedef Kernel::Point_3                                       Point;
typedef CGAL::Polyhedron_3<Kernel>                            Polyhedron;
typedef boost::graph_traits<Polyhedron>::vertex_descriptor    vertex_descriptor;
typedef CGAL::Mean_curvature_flow_skeletonization<Polyhedron> Skeletonization;
typedef Skeletonization::Skeleton                             Skeleton;
typedef Skeleton::vertex_descriptor                           Skeleton_vertex;
typedef Skeleton::edge_descriptor                             Skeleton_edge;

// This example extracts a medially centered skeleton from a given mesh.
int main(int argc, char* argv[])
{
//    std::ifstream input((argc>1)?argv[1]:"/Users/lcj／elephant.off");
    std::ifstream input("/Users/lcj／elephant.off");
    Polyhedron tmesh;
    input >> tmesh;
    Skeleton skeleton;
    
    CGAL::extract_mean_curvature_flow_skeleton(tmesh, skeleton);
    std::cout << "Number of vertices of the skeleton: " << boost::num_vertices(skeleton) << "\n";
    std::cout << "Number of edges of the skeleton: " << boost::num_edges(skeleton) << "\n";
    // Output all the edges of the skeleton.
    std::ofstream output("skel.cgal");
    BOOST_FOREACH(Skeleton_edge e, edges(skeleton))
    {
        const Point& s = skeleton[source(e, skeleton)].point;
        const Point& t = skeleton[target(e, skeleton)].point;
        output << "2 " << s << " " << t << "\n";
    }
    output.close();
    // Output skeleton points and the corresponding surface points
    output.open("correspondance.cgal");
    BOOST_FOREACH(Skeleton_vertex v, vertices(skeleton))
    BOOST_FOREACH(vertex_descriptor vd, skeleton[v].vertices)
    output << "2 " << skeleton[v].point << " "
    << get(CGAL::vertex_point, tmesh, vd)  << "\n";
    system("pause");
    
    return 0;
}

## Environment

* Operating system:Mac 64bits
* Compiler:XCode
* Release or debug mode:Debug
* Specific flags used (if any):
* CGAL version:4.9
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):Eigen 3.3.2, Boost 1.63.0

**Comment by afabri** [comment]
@lcj0117 Was there a real problem? If yes, then it might be interesting for others how you solved it.
