### ISSUE TITLE
Documentation of `side_of_triangle_mesh` (Polygon Mesh Processing)

### ISSUE THREAD

**Issue by gnzlbg** [CGAL/cgal#1945]
I am trying to find out if `side_of_triangle_mesh` returns correct results when the casted ray intersects a triangle (or multiple of them) along a line segment and/or exactly on a point in the triangle edges or a triangle vertex. 

The documentation is a bit un clear. Maybe it would be possible to clarify if it can handle these cases, and also which algorithm it uses (e.g. cite the paper).

The documentation also does not state the complexity of the algorithm used. Is it linear in the number of triangles? Logarithmic? From looking at the implementation I guess it would be logarithmic since it does ray intersections against an AABB tree but it would be nice if it would be stated in the description.

**Comment by sloriot** [comment]
Degenerate cases should be handled correctly. It is not specified in particular for this class because it is the case everywhere in the library. The algorithm use a classical method that compute the number of intersected triangles by a ray emanating from the query point. I'm not sure there exists a publication. Maybe it is cited in Dave Eberly's book. The queries are speed up using an AABB-tree.

**Comment by gnzlbg** [comment]
> The algorithm use a classical method that compute the number of intersected triangles by a ray emanating from the query point.

Yes, i was just wondering what does it do when the ray intersects a vertex, that is shared by multiple triangles (e.g. it should be counted only once), or an edge (should be counted only once as well), or when the ray lies exactly on the triangle plane, in which case whether the intersection should be counted or not depends on the vertices of the adjacent triangles (or triangles even farther away). 

The tests don't seem to be very exhaustive either, they just throw an elephant mesh to it, but I cannot find any mesh that looks like explicitly constructed to try to break the algorithm. Maybe I missed those?

**Comment by sloriot** [comment]
The triangle-ray intersection predicate detects when the ray shoots an edge, a vertex, or the interior of a triangle. In case the intersection is not in the interior of the triangle, another random ray is taken. In practice, it was faster than having a map to eliminate other incident faces incident to the simplex shot.

**Comment by gnzlbg** [comment]
Ah I see! Is the direction of the ray truly random? Or are the other "Cartesian" directions attempted first? Like typically one shoots the ray in the direction of the side that's closer to the point in the AABB of the root of the AABB tree. I've seen solutions that then proceed to shoot rays in the other Cartesian directions, but is also trivial to construct cases in which for a given point these all present degenerate ray-triangle intersections (this is harder to do if the ray direction is truly random). I've seen some of these solutions that then sample a set of points around the original point as well, and start shooting rays till they achieve "consensus" but these "fallbacks" fail when the point is closer to the boundary. 

Does CGAL has a 100% robust solution to it? I am a bit more interested with correctness than speed, but I can understand that 100% robustness might be impractical, in particular when one must really try hard to construct these cases which are not found trivaly in the wild.

**Comment by sloriot** [comment]
The first ray is along one axis, the direction depends on the position in the bbox. In case of failure, we decided it was not worth doing it for the other directions. For the random directions, a point is taken uniformly on the sphere so in practice you will always find a good candidate.
The predicates are robust if you use a kernel with exact predicates.

**Comment by gnzlbg** [comment]
> The first ray is along one axis, the direction depends on the position in the bbox. I

Nice, this matched my expectations. 

> For the random directions, a point is taken uniformly on the sphere so in practice you will always find a good candidate.

Do you mean something like having a bounding sphere of the AABB tree, and picking a random point on its surface, and then casting a ray to that?

**Comment by sloriot** [comment]
well, we only need a random direction, so we pick a point on the unit sphere and then the ray if origin -> this point, translated at the query point.

**Comment by gnzlbg** [comment]
Thanks a lot, this clarifies all my questions!

**Comment by gnzlbg** [comment]
It would still be great if a summary of @sloriot answers could be added to the docs of `side_of_triangle_mesh` :) Thanks a lot for answering my questions!

**Comment by lrineau** [comment]
I think @gnzlbg is right. Adding those precisions to the CGAL documentation would be an improvement. Let's reopen the bug.

**Comment by lrineau** [comment]
Fixed by #2085.
