### ISSUE TITLE
Surface_mesh: bug in is_border(Vertex_index)

### ISSUE THREAD

**Issue by emazin** [CGAL/cgal#1949]
## Issue Details

There's an obvious bug in line 2183 of cgal/Surface_mesh/include/CGAL/Surface_mesh/Surface_mesh.h (line 1717 on master),
        **return (!(is_valid(h) && is_border(h)));**

Negation here breaks the logic, and the use of is_valid() is inconsistent with the rest of the function.

## Source Code
 bool is_border(Vertex_index v, bool check_all_incident_halfedges = true) const
    {
        Halfedge_index h(halfedge(v));
       ....
        **return (!(is_valid(h) && is_border(h)));**
    }

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): **any**
* Compiler: **any**
* Release or debug mode: **any**
* Specific flags used (if any): **N/A**
* CGAL version: **4.9**
* Boost version: **N/A**
* Other libraries versions if used (Eigen, TBB, etc.): **N/A**

**Comment by lrineau** [comment]
Thanks for the report. It is now fixed in our `master` branch.
