### ISSUE TITLE
Arrangement_2: Non-symetrical observer notification of insert/remove edge

### ISSUE THREAD

**Issue by chgans** [CGAL/cgal#1956]
## Issue Details

As initially reported on the [cgal-discuss mailing list](https://sympa.inria.fr/sympa/arc/cgal-discuss/2017-03/msg00004.html). The notification order when calling the free-function insert/remove edge is not symetrical:

### When inserting a (isolated) segment:
- Before create vertex
- After create vertex
- Before create vertex
- After create vertex
- Before create Edge
- After create edge

### When removing a (isolated) segment:
- Before remove edge
- Before remove vertex
- After remove vertex
- Before remove vertex
- After remove vertex
- After remove edge

Please note the 'remove vertex' surrounded by 'begin remove edge' and 'after remove edge', this is not the case when inserting a segment.

### Expected
I think it is important to have a consistent notification ordering, and i think the 'insert' case is the correct behaviour, as per documentation: ```before_foo_bar()``` is called **just** before foo-ing a bar. and ```after_foo_bar()``` is called **just** after foo-ing a bar.

## Source Code

The early call to ```_notify_before_remove_edge``` is at L4425 of Arrangement_on_surface_2_impl.h, function:
```C++
template <typename GeomTraits, typename TopTraits> 
typename Arrangement_on_surface_2<GeomTraits, TopTraits>::DFace*
Arrangement_on_surface_2<GeomTraits, TopTraits>::
_remove_edge(DHalfedge* e, bool remove_source, bool remove_target)
```

## Environment

KUbuntu 64 bits, with distro provided CGAL and boost, no other dependencies or 'weird' flag/macros. ...

**Comment by sloriot** [comment]
IMO, this is correct. If  a vertex is removed  then it's already too late to notify that an incident edge is being removed. The _before remove edge_ should be the first one, then comes the notification for its vertices.

**Comment by chgans** [comment]
Absolutely agree, the problem is not who of the vertex/edge come first, the problem is that the before/after are inter-leaved.
You *should* get:
-  Before remove edge <===========
- After remove edge <===========
- Before remove vertex
- After remove vertex
- Before remove vertex
- After remove vertex

Instead you *do* get:
- Before remove edge  <============
- Before remove vertex
- After remove vertex
- Before remove vertex
- After remove vertex
- After remove edge <===========

**Comment by lrineau** [comment]
@sloriot: Do you agree with @chgans in https://github.com/CGAL/cgal/issues/1956#issuecomment-284700090?

**Comment by efifogel** [comment]
He is correct, and it should be fixed.
I'll make sure it's done for 4.11

   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by sloriot** [comment]
Actually, the pb I think is in the insertion of a segment, "Before create Edge" should be the first one.

**Comment by efifogel** [comment]
When you insert a curve, and the vertices of the endpoints do not exist,
you can do one of two:
1. Insert the curve using the insert(arr, curve) free function, or
2 create the vertices first (as isolated vertices) and then insert the
curve using the member function arr.insert_at_vertices(curve).
The notification in both cases should be identical; thus, the order in the
remove should be fixed.

We could consider introducing another set of notifications that notify when
an edge is inserted using the global function.

   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/
