### ISSUE TITLE
Incorrect CGAL_VERSION when HEADER_ONLY is set to ON

### ISSUE THREAD

**Issue by VincentRouvreau** [CGAL/cgal#1958]
## Issue Details

I compile CGAL in the nominal way in a folder /home/workspace/CGAL-4.9 (cmake . && make)
I compile CGAL with HEADER_ONLY set to ON in a folder /home/workspace/CGAL-4.9_HO (cmake  -DCGAL_HEADER_ONLY=ON . && make)
An external CMake is importing CGAL. When cmake it :
```
cmake -DCGAL_DIR=/home/workspace/CGAL-4.9 .
-- CGAL version: 4.9.1000.
```

```
cmake -DCGAL_DIR=/home/workspace/CGAL-4.9_HO .
 -- CGAL version: 4.7.900.
```

## Source Code

An external almost empty CMakeLists.txt :
```
cmake_minimum_required(VERSION 2.6)
project(cgal_cmake_test)

find_package(CGAL)
message(STATUS "CGAL version: ${CGAL_VERSION}.")
```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Ubuntu 16.04
* Compiler: The CXX compiler identification is GNU 5.4.0 
* Release or debug mode: both
* Specific flags used (if any): -DCGAL_HEADER_ONLY=ON
* CGAL version: 4.9
* Boost version: 1.53.0
* Other libraries versions if used (Eigen, TBB, etc.): Eigen3, TBB, GMP, GMPXX

**Comment by maxGimeno** [comment]
I wonder if the problem is in the external CMake. In the CGALConfig.cmake generated in header only, the values are right (4.9.1000)

**Comment by sloriot** [comment]
What version of cmake are you using?

**Comment by maxGimeno** [comment]
Strange, when I try it I get 
> -- CGAL version: 4.9.1000.

like it should. 
Can you check 
 > /home/workspace/CGAL-4.9_HO/CGALConfig.cmake 

and tell us if the values are OK in there ?

**Comment by VincentRouvreau** [comment]
Thank you for the reactivity.
My CMake is 3.2.2.
You can close the issue, I feel bad...
I indicate a wrong CGAL version repository, and find_package found the default CGAL installed through apt-get...
It was CGAL-4.9-HO and not CGAL-4.9_HO

```
cmake -DCGAL_DIR=/home/workspace/CGAL-4.9-HO .
 -- CGAL version: 4.9.1000.
```

Sorry for the noise, and thank you again.

Vincent.
