### ISSUE TITLE
Improve loading of polylines

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#1963]
Right now it is painful to open a polyline file containing many polylines. For example opening 100000 segments takes ages. Also the std::cerr for each polyline should be removed.

We should have a look at what is going on. @maxGimeno, could you have a look?

**Comment by maxGimeno** [comment]
I guess most of the time is taken by the cerr... I'll check deeper when I remove it.

**Comment by sloriot** [comment]
It's not the case, I've already done that locally.

**Comment by maxGimeno** [comment]
Ach, it's a shame.
