### ISSUE TITLE
Arr_trapezoid_ric_point_location: Strange warning when adding/removing edges

### ISSUE THREAD

**Issue by chgans** [CGAL/cgal#1967]
## Issue Details

When a ```Arr_trapezoid_ric_point_location``` is attached to an ```Arrangement_2```, after an isolated inner CCB is added to the arrangement, and then the edges are removed one by one, the locator will raise a strange warning, although nothing wrong was done on the arrangement.

## Source Code

```C++

#include <CGAL/Cartesian.h>
#include <CGAL/Arr_segment_traits_2.h>
#include <CGAL/Arrangement_2.h>
#include <CGAL/Arr_walk_along_line_point_location.h>
#include <CGAL/Arr_trapezoid_ric_point_location.h>

typedef CGAL::Exact_predicates_exact_constructions_kernel Kernel;
typedef Kernel::FT                                        Number_type;
typedef CGAL::Arr_segment_traits_2<Kernel>                Traits;
typedef Traits::Point_2                                   Point;
typedef Traits::X_monotone_curve_2                        Segment;
typedef Traits::Curve_2                                   Curve;
typedef CGAL::Arrangement_2<Traits>                       Arrangement;

typedef CGAL::Arr_trapezoid_ric_point_location<Arrangement>   TrapezoidLocator;

int main (int /*argv**/, char ** /*argv*/)
{
    Arrangement arrangement;
    TrapezoidLocator locator(arrangement);

    // First create a new face
    auto v1 = arrangement.insert_in_face_interior(Point(0, 0), arrangement.unbounded_face());
    auto v2 = arrangement.insert_in_face_interior(Point(0, 1), arrangement.unbounded_face());
    auto v3 = arrangement.insert_in_face_interior(Point(1, 1), arrangement.unbounded_face());
    auto v4 = arrangement.insert_in_face_interior(Point(1, 0), arrangement.unbounded_face());
    auto e1 = arrangement.insert_at_vertices(Segment(v1->point(), v2->point()), v1, v2);
    auto e2 = arrangement.insert_at_vertices(Segment(v2->point(), v3->point()), v2, v3);
    auto e3 = arrangement.insert_at_vertices(Segment(v3->point(), v4->point()), v3, v4);
    auto e4 = arrangement.insert_at_vertices(Segment(v4->point(), v1->point()), v4, v1);

    // To trigger the warning, we need to add an extra inner CCB in the unbounded face ...
    auto v5 = arrangement.insert_in_face_interior(Point(2, 2), arrangement.unbounded_face());
    auto v6 = arrangement.insert_in_face_interior(Point(3, 3), arrangement.unbounded_face());
    auto e5 = arrangement.insert_at_vertices(Segment(v5->point(), v6->point()), v5, v6);

    // ... then start removing the edges
    arrangement.remove_edge(e5);
    arrangement.remove_edge(e4);
    arrangement.remove_edge(e3);
    arrangement.remove_edge(e2);
    arrangement.remove_edge(e1); // This one will generate a warning

    return 0;
}
```
Which gives:
```
CGAL warning: check violation!
Expression : lt1==POINT && lt2==POINT
File       : /usr/include/CGAL/Arr_point_location/Trapezoidal_decomposition_2_impl.h
Line       : 1781
Explanation: 
Refer to the bug-reporting instructions at http://www.cgal.org/bug_report.html
```

## Environment

KUbuntu 16.10, with distro provided CGAL-4.8.1, boost-1.61.0.2 and gcc-6.1.1.

**Comment by lrineau** [comment]
Efi, can you please comment on the issue report? Is that warning intended? What is the appropriate action?

**Comment by efifogel** [comment]
We are looking into it.
Sorry for not responding.

   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by lrineau** [comment]
Is there any change you come up with a fix in the following week? This issue is the last one that is blocking CGAL-4.9.1.

**Comment by efifogel** [comment]
It's unlikely to be addressed in the next 2 weeks; hopefully during the
week after.
I think it's not a 4.9.1 show blocker.

   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by lrineau** [comment]
Thanks Efi for your answer. I reassign this issue to CGAL-4.10.

**Comment by lrineau** [comment]
4.10 is about to be released. I have to reassign this issue to 4.11.
Note that the issue was reported mid-March.

**Comment by efifogel** [comment]
Yes, I'll make sure to fix it this time.

   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by afabri** [comment]
@efifogel any news on this one?

**Comment by efifogel** [comment]
No. I'm trying to get help from someone who is familiar with the
trapezoidal code.
I'll try again this week...

   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by lrineau** [comment]
This issue is fixed in the `master` branch of CGAL (targetting CGAL-4.13), by the merge of the PR #3093.
