### ISSUE TITLE
CMake scripts: CGAL_DONT_OVERRIDE_CMAKE_FLAGS is not honored in CGAL_SetupFlags.cmake

### ISSUE THREAD

**Issue by uranix** [CGAL/cgal#1968]
When using the following code 
```
find_package(CGAL REQUIRED)
set(CGAL_DONT_OVERRIDE_CMAKE_FLAGS TRUE)
include(${CGAL_USE_FILE})
```
in my project's CMakeLists.txt the CMAKE_CXX_FLAGS are still populated with CGAL default flags.
Looking through the code of [CGAL_SetupFlags.cmake](https://github.com/CGAL/cgal/blob/9a6a1bcc9ba7adcc50202dedd6fe7a7a33da36e4/Installation/cmake/modules/CGAL_SetupFlags.cmake#L38-L49) it seems that flags are added unconditionally.

Here's a minimal example of CMakeLists.txt:
```
cmake_minimum_required(VERSION 3.0)

find_package(CGAL REQUIRED)
set(CGAL_DONT_OVERRIDE_CMAKE_FLAGS TRUE)

message(STATUS "Before include >>> ${CMAKE_CXX_FLAGS} <<<")
include(${CGAL_USE_FILE})
message(STATUS "After include >>> ${CMAKE_CXX_FLAGS} <<<")
```
producing
```
-- Before include >>>  <<<
-- Build type: Release
-- USING CXXFLAGS = '-g -O2 -fdebug-prefix-map=/build/cgal-J8tiIX/cgal-4.9=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -frounding-math -O3 -DNDEBUG'
-- USING EXEFLAGS = '-Wl,-z,relro -Wl,--as-needed '
-- Targetting Unix Makefiles
-- Using /usr/bin/c++ compiler.
-- Requested component: MPFR
-- Requested component: GMP
-- After include >>> -g -O2 -fdebug-prefix-map=/build/cgal-J8tiIX/cgal-4.9=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -frounding-math <<<
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/test
```

* Operating system: Debian GNU/Linux 9.0 (stretch) x86_64
* Compiler: g++ (Debian 6.3.0-6) 6.3.0 20170205
* Release or debug mode: Release and Debug modes
* Specific flags used (if any): None
* CGAL version: 4.9-1 (331eac693ae48e62e73bc9a810945b03d9d52c12)
* Boost version: 1.62.0
* Other libraries versions if used (Eigen, TBB, etc.): None

**Comment by maxGimeno** [comment]
The variable CGAL_DONT_OVERRIDE_CMAKE_FLAGS is set to FALSE by default using the `option` cmake function. That means that you can set it to true through the cmake command like this:
cmake -DCGAL_DONT_OVERRIDE_CMAKE_FLAGS=true your_path
or, if you need to use `set` in your CMakeLists.txt, it means you want to override the option, which means you need to use : 
set(CGAL_DONT_OVERRIDE_CMAKE_FLAGS TRUE CACHE BOOL "enter a new description")

**Comment by uranix** [comment]
My fault, thank you!
