### ISSUE TITLE
Test CGAL with MSVC 2015

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#197]
We should test CGAL-4.7 with Microsoft Visual Studio 2015, before the release of CGAL-4.7-beta1.

**Comment by janetournois** [comment]
I will be taking care of this before the beta release

**Comment by janetournois** [comment]
The first testsuite is happening tonight. We should have a column for CGAL-4.7-Ic-107 tomorrow morning.

**Comment by janetournois** [comment]
The testsuite [CGAL-4.7-Ic-109](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.7-Ic-109.shtml) did work (though there are some errors to be fixed).

Delaunay needs to be fixed to run the testsuite on a regular basis.

**Comment by lrineau** [comment]
For CGAL-4.7-beta2 we have done manual launch of the testsuite. The automation of that testsuite will be later.

**Comment by lrineau** [comment]
Now that we have an automatic testsuite on `sosno.geomtryfactory.com`, let's close this bug.
