### ISSUE TITLE
random_points_in_sphere_3

### ISSUE THREAD

**Issue by MoniqueTeillaud** [CGAL/cgal#1978]
See http://doc.cgal.org/latest/Generator/classCGAL_1_1Random__points__in__sphere__3.html
"The class Random_points_in_sphere_3 is an input iterator creating points uniformly distributed in an open sphere."

This does not make any sense...

In an ideal word, the class should be named Random_points_in_ball_3. To avoid complications I propose to leave the name as is, and to only modify the explanation.
-> 
"The class Random_points_in_sphere_3 is an input iterator creating points uniformly distributed in an open ball."
The name will still be wrong but at least users will be given a way to understand what the class is doing. 

I wanted to do this as a PR, but I could not find the file containing the documentation in https://github.com/CGAL/cgal/tree/master/Generator/doc/Generator 

(Note that there might be other occurrences of this wrong sentence elsewhere in the manual...)

**Comment by afabri** [comment]
grep is your friend
