### ISSUE TITLE
Assertion fail on polyhedron_3_to_nef_3

### ISSUE THREAD

**Issue by CloudComputer** [CGAL/cgal#1979]
## Issue Details

When trying to construct Nef_Polyhedron from Polyhedron I get the assertion fail.
`CGAL_assertion(pe_prev->is_border() ||
                     !internal::Plane_constructor<Plane>::get_plane(pe_prev->facet(),pe_prev->facet()->plane()).is_degenerate());`

![error](https://cloud.githubusercontent.com/assets/14849839/24087675/0fc0e7d6-0d5d-11e7-8e16-1c07568e598b.png)

I have insured that the meshes are closed, valid and triangular.
The off file you need is attached.

[out2.zip](https://github.com/CGAL/cgal/files/853860/out2.zip)

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows 32
* Compiler: MSVC 2012
* Release or debug mode: debug 
* Specific flags used (if any):
* CGAL version: 3.90
* Boost version: 1.59.0
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by afabri** [comment]
The data set has 77 degenerate faces.

**Comment by sloriot** [comment]
You can try using the function `OFF_to_nef_3` available in  `include/CGAL/OFF_to_nef_3.h`.

**Comment by CloudComputer** [comment]
In fact, I do not need Nef_Polyhedron. I just want to do Boolean operations by the data set. Maybe due to the presence of degenerate faces, it will still lead to assertion fail. Should I learn ways of  removing degenerate faces without changing its shape?
Does anyone have some good ideas?
