### ISSUE TITLE
API/ABI changes review for CGAL

### ISSUE THREAD

**Issue by lvc** [CGAL/cgal#1980]
The review of API/ABI changes for CGAL since 4.6.1 version: https://abi-laboratory.pro/tracker/timeline/cgal/

The report is updated regularly. Hope it will be helpful for users and maintainers of the library.

Created with the help of open-source abi-tracker tool: https://github.com/lvc/abi-tracker

Thank you.

![cgal-1](https://cloud.githubusercontent.com/assets/1517837/24100451/c1142bb2-0d8d-11e7-93a1-b01148a5240a.png)

![cgal-2](https://cloud.githubusercontent.com/assets/1517837/24100456/c56774a8-0d8d-11e7-8ac5-085937b87fe4.png)

## Environment
* Linux x86_64
* GCC 4.9
* CGAL 4.6.1 and higher

**Comment by lrineau** [comment]
Thanks for the information. That is nice to see.

I close the bug because I do not see what we should change.

Anyway, the future of CGAL will be header-only pretty soon.
