### ISSUE TITLE
Inconsistency in doc for TriangulationDSFaceBase_2 Concept

### ISSUE THREAD

**Issue by flm8620** [CGAL/cgal#1987]
In the doc of [TriangulationDSVertexBase_2 Concept](http://doc.cgal.org/latest/TDS_2/classTriangulationDSVertexBase__2.html), It says 

> Refines:
> TriangulationDataStructure_2::Vertex

While for [TriangulationDSFaceBase_2 Concept](http://doc.cgal.org/latest/TDS_2/classTriangulationDSFaceBase__2.html), there is no such line indicating refinement relationships

Is this a negligence or it's intended?

**Comment by lrineau** [comment]
Thanks. I will be fixed in CGAL-4.10.
