### ISSUE TITLE
Doc bugs with Doxygen 1.8.13

### ISSUE THREAD

**Issue by sgiraudot** [CGAL/cgal#1995]
## Issue Details

Using the Doxygen version https://github.com/CGAL/doxygen/tree/release_1_8_13_patched, I have two graphical bugs in the doc:
* The footer is hiding the bottom of the page (on most pages, you can't read the last sentence)
* On a reference manual, when you click on a class on the left menu, the right page is displayed, but the menu is buggy: it is not the element that you clicked on that is unfolded but the first element of the list (usually, `Concepts`, or `Named Parameters` in PMP for example).

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Debian GNU/Linux Testing 64b
* CGAL version: master

**Comment by sgiraudot** [comment]
I just noticed another bug: the table of content (the floating menu on the right) is not generated anymore on the pages accessible from the front page (Getting Started, Tutorials, etc.). The bug only affects these pages, not the user manual pages.

**Comment by lrineau** [comment]
* I have fixed most of the issues in #2366.
* The table of content is fixed too, in commit dcb5e191fdb920bad3b976762a7434ca1ca17fd3 of #2366.

**Comment by lrineau** [comment]
About the issue of the unfolded element, in the navtree, I think we should open another issue.
