### ISSUE TITLE
Use of git-merge, update the github wiki

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#1999]
This issue was very briefly discussed at the CGAL Developers Meeting at Sophia, 2017. We decided that @sloriot should handle it.

## Issue Details

The [Guidelines] in the wiki recommend to use git-merge, while Laurent thinks it is a bad idea (because it generates spurious commits in branches). Discuss a better procedure and update the github wiki.

[Guidelines]: https://github.com/CGAL/cgal/wiki/Git-FAQ#my-branch-is-really-old-i-would-like-to-update-it-to-get-latest-update-from-master

**Comment by sloriot** [comment]
@lrineau what do you think we should use? Simply merge master in the branch?
@ericberberich do you remember why we wanted to avoid merging master in a feature branch?

**Comment by lrineau** [comment]
Whatever we recommend, it should be done scarcely, to fix a problem, and not just to "update the branch".

I recommend merging `master` in the branch.

**Comment by maxGimeno** [comment]
Done [here](https://github.com/CGAL/cgal/wiki/Git-FAQ#my-branch-is-really-old-i-would-like-to-update-it-to-get-latest-update-from-master)

**Comment by lrineau** [comment]
Thanks Maxime and Mael.
