### ISSUE TITLE
Notifications for modifications to the Github wiki

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#2000]
Listed as an undone task at https://cgal.geometryfactory.com/CGAL/Members/wiki/Meetings/Zurich16

## Issue Details

The wiki was made public.

Problem: now anybody can edit the wiki, and the admins don't even get a notification!

Edit: @SaillantNicolas See the recent comment at https://github.com/CGAL/cgal/issues/2000#issuecomment-1386710064.

**Comment by MaelRL** [comment]
This stackoverflow [question](https://stackoverflow.com/questions/8407917/how-can-you-track-or-be-notified-of-changes-to-github-wikis) offers some possible directions.

**Comment by MaelRL** [comment]
Small (accidental?) foreign incursion: https://github.com/CGAL/cgal/wiki/_Footer/_history

**Comment by lrineau** [comment]
@MaelRL How have you found out out the modification? Did you get a notification?

**Comment by MaelRL** [comment]
Accidentally caught it in https://github.com/orgs/CGAL/dashboard, where wiki modifications show up.

**Comment by sloriot** [comment]
We can use https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows# and send an email after logging to cgal.gf.com for example. cc @SaillantNicolas

**Comment by sloriot** [comment]
Closing without saying how we can now get notifications if a bit frustrating :)

**Comment by lrineau** [comment]
This old issue was closed by the merge of PR https://github.com/CGAL/cgal/pull/7272.

Now the email mailing list `cgal-dev-commits` receives email notifications for any change to the Github CGAL public wiki.
