### ISSUE TITLE
CGAL web site too slow from USA or Australia?

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#2001]
Discussed at https://cgal.geometryfactory.com/CGAL/Members/wiki/Meetings/Sophia17

## Issue Details

Users are complaining that the website and the doc are "so slow as to be unusable" from USA and New Zealand. "Seems like the server drops connections."

https://doc.cgal.org and https://www.cgal.org are hosted on a Pro2014 mutualized hosting, at OVH. For 1€/month, we could buy the CDN option, to have multiple Points of Presence (PoP) in the world.

https://www.ovh.com/fr/hebergement-web/cdn.xml

**Comment by afabri** [comment]
Note that I asked on the cgal-discuss mailing list, and nobody replied. Not even @gdamiand

**Comment by gdamiand** [comment]
The problem seems solved now (I also observed the problem last week).

**Comment by afabri** [comment]
@gdamiand  wrote: The problem seems solved now (I also observed the problem last week).

**Comment by afabri** [comment]
@lrineau you can close this issue.
