### ISSUE TITLE
Polyhedron demo : convert `Surface_mesh_item` to `Polyhedron_item` and vice versa

### ISSUE THREAD

**Issue by janetournois** [CGAL/cgal#2007]
## Issue Details

Because some packages are not available yet with the BGL API, and the `CGAL::copy_face_graph` function is available, it would be nice to have a conversion tool between `Surface_mesh_item` and `Polyhedron_item` in the demo. 

## Source Code

todo : Add a conversion tool to both items

**Comment by afabri** [comment]
If you look at the list of finalized plugins we got pretty close, so I would not spend time on that now.

**Comment by lrineau** [comment]
We are talking about something that can be implemented in 30 minutes, and could be useful right now.

**Comment by janetournois** [comment]
it would also be useful to test if plugins work the same with both data structures

**Comment by lrineau** [comment]
Fixed in `master` (for 4.11).
