### ISSUE TITLE
Polyhedron demo : add `Load as...`

### ISSUE THREAD

**Issue by janetournois** [CGAL/cgal#2008]
## Issue Details
When we open a file (e.g. a `mesh.cgal`), choose a plugin to open it (e.g. `C3t3_io_plugin`), and click "Always open with...", it is never possible to make another decision while keeping the demo open.

Let's say I want to open a `.off` file as a `Surface_mesh`, and later another as a `Point_set`. They will all be opened as `Surface_mesh`, and then I need to use the conversion tool, which is not always available, and/or not always complete.

## Source Code

Todo : Add a "Load as..." submenu in the `File` menu, that allows to change your mind on the plugin to use to open some new file (as if the extension has never been met before, or the "always" checkbox never clicked).

**Comment by lrineau** [comment]
If could be implemented within the file dialog of the usual "Load" action, with a special `nameFilters` where all pair (extension, loader) would appear as an entry, and if the user selects a precise filter entry, then its loader would be choosen.

**Comment by maxGimeno** [comment]
Wouldn't it be easier to add an option in the Preferences dialog that resets the default loaders ?
