### ISSUE TITLE
Document the Mesh_3 manifold criterion

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#2009]
After the merge of #1876, the next step is to document the feature.

**Comment by janetournois** [comment]
I'm working on it, in the branch [janetournois/Mesh_3-document_manifold_criterion-jtournois](https://github.com/janetournois/cgal/tree/Mesh_3-document_manifold_criterion-jtournois)

**Comment by janetournois** [comment]
TODO : we need to precise the conditions on the input. It does not only have to be manifold : the sharp edges should either be protected, or cut away, to be able to terminate.
