### ISSUE TITLE
Segfault in Mesh_3 demo

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#203]
Mesh_3 demo, open a file (either an OFF or an image), create a mesh, then Lloyd. Segfault!

Cc @janetournois @maxGimeno @afabri

**Comment by maxGimeno** [comment]
Corrected

**Comment by lrineau** [comment]
I still have a memory corruption when doing the same operation as described above, just after I click on the button of the Lloyd dialog box:
> *** Error in `./Mesh_3': malloc(): memory corruption (fast): 0x0000000001a5e1e1 ***

And I have a segfault at the exit of the application, as soon as at least one item is created: open the demo, open an OFF file (works also with an image), then exit the application: segfault, related to the QOpenGLFunctions object, in the destructor of `Scene_item`. What is strange is that the segfault does not occur when one destroy the item manually, before quitting the application.

**Comment by lrineau** [comment]
I can no longer reproduce the bug after  CGAL/cgal-public-dev@94a7936

Can you confirm?
