### ISSUE TITLE
Polyhedron_demo : enhancements for some plugins

### ISSUE THREAD

**Issue by maxGimeno** [CGAL/cgal#2035]
## Issue Details
We should
- [x] test if the polyhedron is manifold during the selection-edition
- [x] add a widget specifying the current mode (selection, edition, ...) 
- [ ] the constraint deformation plane should be filled and not transparent (edit_polyhedron_plugin)
- [x] Make the statistics exportable

**Comment by maxGimeno** [comment]
There is still a point that is not finished, this issue should not have been closed yet.

**Comment by sloriot** [comment]
It was closed automatically.
