### ISSUE TITLE
Polyhedron_demo: enhance color management, and camera actions

### ISSUE THREAD

**Issue by maxGimeno** [CGAL/cgal#2037]
## Issue Details

- [x] When loading multiple files, assigning a different color to each generated item (or/and add an option, when several items are selected, "Assign a different color to each item", or something like that), would greatly clarify a scene that has many items and save us the time to do it manually.

- [x] Add an option to put the camera orthogonal to the selected face or point selection (using PCA)

**Comment by lrineau** [comment]
Fixed in `master` (for 4.11) by #2062.
