### ISSUE TITLE
Polyhedron_demo: Unify the 3D demos

### ISSUE THREAD

**Issue by maxGimeno** [CGAL/cgal#2038]
## Issue Details
Integrate all the 3D demos in the polyhedron_demo
Integration of T3 and P3T3 demos might pose a  problem with the "animation" mode.

**Comment by lrineau** [comment]
Remaining 3D demos in CGAL:
- AABB Tree,
- Alpha_shapes_3
- Circular_kernel_3
- Linear_cell_complex
- Periodic_3_triangulation_3
- **Polyhedron** 
- Surface_mesher
- Triangulation_3

**Comment by maxGimeno** [comment]
Priority:
-[x] Alpha_shape_3
-[ ] AABB_Tree : cf andreas and jane 
-[ ] Surface_mesher cf laurent : VTK's marching cube ?
