### ISSUE TITLE
Polygon Mesh Processing: Add an example for isotropic_remeshing

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#2043]
where we use a property map.

See  [cgal-discuss] How to constrain edge in refine function in Polygon Mesh Processing Package

**Comment by maxGimeno** [comment]
There is a "isotropic_remeshing_of_patch_example" that uses a pmap for the selection. Is that not sufficient ?

**Comment by MaelRL** [comment]
That example is not used anywhere in the doc (it should at least be put in the example list of the doc).

**Comment by sloriot** [comment]
The [doc](https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__meshing__grp.html#gad3d03890515ae8103bd32a30a3486412) refers to the example [Polygon_mesh_processing/corefinement_difference_remeshed.cpp](https://doc.cgal.org/latest/Polygon_mesh_processing/Polygon_mesh_processing_2corefinement_difference_remeshed_8cpp-example.html#a7) and it uses a property map to handle constrained edges.
