### ISSUE TITLE
Bug in CGAL::PMP::is_outward_oriented()

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#2048]
## Issue Details

The is a bug in [`PMP::is_outward_oriented()`][doc]. It was [reported by a user on the `CGAL-discuss` mailing list][mail].

  [doc]: http://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__orientation__grp.html#gad71360b56f0d5340bf3006febd49286c`
  [mail]: https://sympa.inria.fr/sympa/arc/cgal-discuss/2017-04/msg00017.html

> Greetings,
> 
> I have one mesh whose normals are pointing outwards, but the function
> `CGAL::Polygon_mesh_processing::is_outward_oriented()` returns
> otherwise.
> 
> I have checked the code and the average of the normals of the faces
> incident to the min-vertex is used, which conceptually I doubt should
> work… And it doesn’t work in my case (unless I made a mistake
> somewhere), you can download my OFF file, along with the code I used,
> there:
> https://www.dropbox.com/sh/49as9yt139v6kxk/AABXI3Nh4ZfqCEDWHyv8Q-Zja?dl=0
> 
> If other ways to compute the normal were used (eg by using the area of
> the face as a weight), then the x-component of the vector could be
> negative (as is used by cgal), but I am wondering if that would always
> work. I think not.
> 
> Any comments appreciated, cheers,
> Hugo Ledoux

# The Problem

The current code is computing the vertex normal of a vertex with the lowest `x` coordinate, and then try to conclude on the coordinate of that normal.

* First problem: the computation of the vertex normal is currently wrong (issue #2047).
* Anyway, even if it is was computed correctly, `is_outward_oriented()` would make a Boolean decision based on a construction, that is inexact even with the `Epick` kernel.

# A Proposed Solution

A possible other implementation would be the following: try to find an extreme faces of the mesh, and test is the normal of that face is pointing to the right side.

More concretely:

1. Find a vertex `v` with the maximum `z` coordinate. Can be done using the predicate `Kernel::Compare_z_3`.
2. Among the incident edges to that vertex `v`, find one of the edges `e` with the <s>maximal</s> **minimal** slope, using `Kernel::Compare_slope_3` from the PR #1795. (text **updated** after https://github.com/CGAL/cgal/issues/2048#issuecomment-293601105)
3. Then, around that edge `e`, there are two faces (because the mesh is without borders) , and take the face `f` for which the other edge incident to `f` and `v` has the <s>maximal</s> **minimal** slope. (text **updated**)

My claim is that that face `f` appears in the superior envelop of the mesh (with a projection along the `z`-axis), and that a vertical ray piercing that face should *enter* the object delimited by the mesh. That means that the `z`-coordinate of the normal of `f` can tell if the mesh is correctly oriented: it is >0 if and only if the mesh is oriented outwardly.

Note: `f` cannot be vertical, because that would mean that all edges incident to `v` are vertical, and that would violate a precondition on the mesh (should not be auto-intersecting).

Cc: @afabri

**Comment by sloriot** [comment]
I think you don't need `Kernel::Compare_slope_3`, simply `Kernel::Compare_z_3` with the adjacent vertices.

**Comment by sloriot** [comment]
I might be missing something but in the case of a cube I does not seem to be working.

**Comment by lrineau** [comment]
You are right: I mixed up minimal and maximal. I have updated the text at https://github.com/CGAL/cgal/issues/2048#issue-220695956.

**Comment by lrineau** [comment]
In the following case, if you just compare the z coordinates, you choose the wrong edge.

![case](https://cloud.githubusercontent.com/assets/5746675/24964573/eff1840e-1fa1-11e7-8610-7328388fc690.png)

**Comment by sloriot** [comment]
I think your proposal is correct.

**Comment by janetournois** [comment]
I am starting to work on it

**Comment by lrineau** [comment]
Fixed by #2057 in `CGAL-4.10-branch` and `master`.
