### ISSUE TITLE
Polyhedron_demo: Use a recent opengl context when possible

### ISSUE THREAD

**Issue by maxGimeno** [CGAL/cgal#2055]
## Issue Details
It should be possible to implement a recent OpenGL context and check if it is valid. If not, keep the 2.1, but in the case it is possible, it would allow us to use geometry shaders and many features that would be really appreciated. 
This would permit to fix the polyhedron_item's flat mode with draw one side problem, and make it easier to make decent transparency in the future.

**Comment by lrineau** [comment]
In my opinion we should try to set the OpenGL surface format to "4.3 compatibility profile", the created format still has a compatibility profile, and fallback to 2.0 in case it does not.
```c++
inline QGLContext* createOpenGLContext()
{
    QOpenGLContext *context = new QOpenGLContext();
    QSurfaceFormat format;
    format.setVersion(4,3);
    format.setProfile(QSurfaceFormat::CompatibilityProfile);
    context->setFormat(format);
    QGLContext *result = QGLContext::fromOpenGLContext(context);
    result->create();
    if(result->format().profile() != QGLFormat::CompatibilityProfile) {
      // impossible to get a 4.3 compatibility profile, retry with 2.0
      format.setVersion(2,0);
      context->setFormat(format);
      result = QGLContext::fromOpenGLContext(context);
    }
    Q_ASSERT(result->format().profile() == QGLFormat::CompatibilityProfile);
    Q_ASSERT(result->isValid());
    return result;
}
```

About 4.3 versus 4.5: there is nothing in [OpenGL version 4.4 and 4.5][history] that we may expect to use. Even the Compute Shader was already in 4.3 (2012), and 4.3 is old enough that we can expect all recent machine with "3.2 compatibility profile" will also have "4.3 compatibility profile".

  [history]: https://www.khronos.org/opengl/wiki/History_of_OpenGL

**Comment by maxGimeno** [comment]
> and fallback to 2.0 in case it does not.

You meant 2.1, that's what we currently have.

**Comment by sloriot** [comment]
This issue is very critical to me. Not being able to see face orientation is a real issue for me.

**Comment by lrineau** [comment]
If that is so critical, then the old code should be re-used when the two-side mode is disabled. Anyway, that should be discussed in a dedicated issue, and not in this one.

**Comment by sloriot** [comment]
See #2103
