### ISSUE TITLE
Flipped segment with data does not contain original data

### ISSUE THREAD

**Issue by lecopivo** [CGAL/cgal#2063]
Problem
---

I use segments with data, in particular `CGAL::Arr_curve_data_traits_2<Segment_traits_2, int>::Curve_2`,the data is integer in this case. The problem is that if I call `flip()` function on a segment then the resulting segment does not have the data of the original segment.

Code 
-------

Example code reproducing this behavior:
```
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/Arr_segment_traits_2.h>
#include <CGAL/Arr_curve_data_traits_2.h>

typedef CGAL::Exact_predicates_exact_constructions_kernel	Kernel;
typedef Kernel::Point_2						Point_2;
typedef Kernel::Segment_2					Segment_2;
typedef CGAL::Arr_segment_traits_2<Kernel>			Segment_traits_2;
typedef CGAL::Arr_curve_data_traits_2<Segment_traits_2, int>	Traits_2;
typedef Traits_2::Curve_2					Curve_2;


int main(){
  Point_2 p1 = {0.0,0.0};
  Point_2 p2 = {1.0,0.0};

  Segment_2 s = {p1,p2};
  Curve_2 c = {s,42};
  Curve_2 fc = c.flip();

  std::cout << "Curve: " << c << std::endl;
  std::cout << "Curve id: " << c.data() << std::endl;
  std::cout << "Flipped curve: " << fc << std::endl;
  std::cout << "Flipped curve id: " << fc.data() << std::endl;
}
```

###  Output
```
Curve: 0 0 1 0
Curve id: 42
Flipped curve: 1 0 0 0
Flipped curve id: 0
```
### Expected output
```
Curve: 0 0 1 0
Curve id: 42
Flipped curve: 1 0 0 0
Flipped curve id: 42
```

Additional problems
---

I also encounter problems while doing Boolean operations on polygons whose segments have data. Doing unions and intersections works fine but when I do difference or symmetric difference then some of the edges lose its data. This is illustrated  on the picture below

![screenshot from 2017-04-19 14-27-21](https://cloud.githubusercontent.com/assets/6596305/25180044/b9ae6586-250c-11e7-8951-6b8982483e22.png)

The shapes from left to right: 
red box(A)
green box(B)
reversed version of A
arrangement created by combining A and B
union of A and B
intersection of A and B
difference of A and B
symmetric difference of A and B

As you can see, some of the edges lost their color for some reason.

Maybe this is intended behavior, but it is quite unexpected.

**Comment by efifogel** [comment]
The member function c.flip() is not required by the concepts
Traits_2::Curve_2 or Traits_2::X_monotone_curve_2. However,
Construct_opposite_2 is required by the traits concept and it does not
assign the data of the input x-monotone curve to the newly constructed one
either, and I think it should.

First, the code would look like:

typedef Traits_2::Curve_2	Curve_2;
Curve_2 fc = traits.construct_opposite_2_object()(c);

To implement properly, we need to introduce another category to the
traits that indicates whether
Construct_opposite_2 is supported.

Anyhow, I'll do it.


   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/
