### ISSUE TITLE
Centroid : seg. fault while debugging

### ISSUE THREAD

**Issue by Ethiy** [CGAL/cgal#2066]
## Issue Details

This is a runtime error. On Release mode nothing happens, but once on a debug mode, I get a segmentation fault in my code when calling  `CGAL::centroid()`. I am using the Epeck kernel and the corruption can be traced back to a `CGAL::Lazy` method.

## Source Code

```cpp
#include <CGAL/Exact_predicates_exact_constructions_kernel.h>

typedef CGAL::Exact_predicates_exact_constructions_kernel Kernel;
typedef Kernel::Point_2 Point_2;

Point_2 point_a(
        CGAL::centroid(
                    facet_a.outer_boundary()[0],
                    facet_a.outer_boundary()[1],
                    facet_a.outer_boundary()[2]
        )
 );
```

When debugging using QtCreator, the bug traces back to the last line of this private method defined in `Lazy.h`:

```cpp
 static const Self & zero()
  {
#ifdef CGAL_HAS_THREADS
    static boost::thread_specific_ptr<Self> z;
    if (z.get() == NULL) {
        z.reset(new Self(new Lazy_rep_0<AT, ET, E2A>()));
    }
    return * z.get();
#else
    static const Self z = new Lazy_rep_0<AT, ET, E2A>();
    return z;
#endif
  }

  Self_rep * ptr() const { return (Self_rep*) PTR; }
};
```
## Environment

* Operating system: Ubuntu 16.04 / 64bits
* Compiler: gcc 5 
* Debug mode
* CGAL version: ~~4.9~~ -> 4.7-4 (provided by aptitude)
* Boost version: 1.58

**Comment by lrineau** [comment]
Could you please post a minimal but complete example? Have a look at https://stackoverflow.com/help/mcve

My 2-cents guess would be that you are using that code in a multi-threaded context, where several threads share objects from the Epeck kernel. That kernel is not thread-safe for that usage.

**Comment by Ethiy** [comment]
I misspoke earlier when describing the environement, It was CGAL-4.7-4 not 4.9. I tried to reproduce the bug without success for now. I think it will take me more time to reproduce this bug.
P.S: I tried to launch apply the `CGAL::centroid` function in a separate thread without success.

**Comment by lrineau** [comment]
Thanks for your answer. I have closed the issue. Reopen it if you manage to reproduce the bug.

**Comment by Ethiy** [comment]
I traced back the error in my program. In the example, I stated before, `facet_a` is a `Polygon_with_holes`. At a certain point, I get an empty `facet_a` for some reason that eluded me until now. And that is why I get a seg.fault.
The point I am trying to make here is:
 * why does the `centroid` function do not raise an `std:: invalid_argument` exception when getting `Handle`s to nothing, 
 * and, why does the `Polygon::operator[] (size_t index) ` not throw an `std::out_of_range` error when accessing unexisting vertices?

**Comment by sloriot** [comment]
@riaqn I don't see how this could fail but if you have a NAN coordinate. Could you post the input too?

**Comment by riaqn** [comment]
Here you go:
[part0.off.txt](https://github.com/CGAL/cgal/files/1968003/part0.off.txt)

This is a huge file so I don't know if it will be helpful at all. I guess to minimalize it is necessary to debug.

**Comment by riaqn** [comment]
Here you go. This is a huge file.

[human.off.gz](https://github.com/CGAL/cgal/files/1968048/human.off.gz)
