### ISSUE TITLE
Centroid : segfault in debug mode, followup.

### ISSUE THREAD

**Issue by Ethiy** [CGAL/cgal#2073]
_This issue is a followup to an issue that raised this bug. The ealier issue #2066 was closed by @lrineau waiting for a minimal example. So I am opening a new Issue since I cannot reopen the last one._

## Issue Details

In my code, I am looping over a lot of Polygons. For some reason that I did not discover until now, I got an empty polygon and when I ask for the centroid of the first three vertices I get a segfault. So I was wandering why does CGAL check for errors in two occasions:

* The `Polygon::operator[] (size_t index)` do not throw an `std::out_of_range` type error when accessing unexisting vertices,
* The `centroid(p, r, q)` function do not raise an `std::invalid_argument` type exception when getting `Handles` pointing to nothing.

If one of these exceptions were raised it would have been easier to debug.

## Source Code

```cpp
#include <CGAL/Exact_predicates_exact_constructions_kernel.h>
#include <CGAL/Polygon_with_holes_2.h>

using Kernel = CGAL::Exact_predicates_exact_constructions_kernel;
using Polygon_with_holes = CGAL::Polygon_with_holes_2<Kernel>;
using Point_2 = Kernel::Point_2;

int main()
{
    Polygon_with_holes empty_polygon;
    Point_2 point_a(
        CGAL::centroid(
            empty_polygon.outer_boundary()[0],
            empty_polygon.outer_boundary()[1],
            empty_polygon.outer_boundary()[2]
        )
    );
}
```

## Environment

This was tested on two platforms:

- Ubuntu:
  * Operating system : Ubuntu 16.04
  * Compiler: gcc5
  * Release or debug mode: Debug
  * Specific flags used (optionnal): (-std=c++11)
  * CGAL version: 4.7-4
  * Boost version: 1.58.0

- Mac:
  * Operating system : OsX 10.12
  * Compiler: Apple LLVM version 8.1.0 (clang-802.0.42)
  * Release or debug mode: Release/Debug
  * Specific flags used (optionnal): (-std=c++11) -stdlib=libc++
  * CGAL version: 4.9
  * Boost version: 1.62.0

**Comment by sloriot** [comment]
I have added a precondition in #2083. We can't do anything about `centroid()` to check that points provided are valid.

**Comment by Ethiy** [comment]
Thanks for your response.

**Comment by lrineau** [comment]
The PR #2083, that adds the precondition, has been merged in `master`. It will be in CGAL-4.11-beta1, planned for mid-summer 2017.
