### ISSUE TITLE
Polyhedron_demo: bugs in deformation

### ISSUE THREAD

**Issue by maxGimeno** [CGAL/cgal#2076]
## Issue Details

I found two bugs in deformation : 
- ~~Deform a mesh, then clear rois, and deform again. The first transformation is lost.~~
- Deform a mesh with a rotation, create a new group and deform it. The last rotation is applied a second time to the first group.

**Comment by sloriot** [comment]
The first point is not a bug, it's a feature. Use update geometry to avoid loosing it.

**Comment by sloriot** [comment]
The idea is that the energy is minimized onto input coordinates rather than on those of an iteratively deformed model.
