### ISSUE TITLE
Polyhedron demo segfault

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#2080]
## Issue Details

Load an off file
Add a selection item
Reload the off file   (I wanted to reload after having selected/isotropic remeshed)

seg fault.

@maxGimeno I guess you must first remove or clear the selection item.

**Comment by maxGimeno** [comment]
Actually you don't need a selection, if you call reload_item on a polyhedron_item you get a segfault anyways. I'll fix this.

**Comment by lrineau** [comment]
Fixed by #2082.
