### ISSUE TITLE
Using  Side_of_triangle_mesh in Mesh_3

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#2084]
Mesh_3 `Polyhedral_mesh_domain_3` should be using `Side_of_triangle_mesh` as an implementation detail.  `TriangleAccessor_3` concept should also be replaced by `FaceListGraph`.
If we want to avoid a dependency between packages, we could leave `Polyhedral_mesh_domain_3` as his, (deprecated it?) and introduced a new class working on models of `FaceListGraph`. This new class can be put in PMP.

**Comment by lrineau** [comment]
I agree with @sloriot. I wonder if that would conflict with the work done in #1983, that makes Mesh_3 compatible with `CGAL::Surface_mesh`. Cc @afabri

**Comment by janetournois** [comment]
I'm working on it
