### ISSUE TITLE
Segment_Delaunay_graph_2::insert runtime error

### ISSUE THREAD

**Issue by Firoon** [CGAL/cgal#2087]
## Issue Details

CGAL ERROR: assertion violation!
Expr: is_valid()
File: d:\cgal-4.9.1_x86\x86\include\cgal\segment_delaunay_graph_2\segment_delaunay_graph_2_impl.h
Line: 699

at i == 5 in [this small example](https://pastebin.com/mhm6SEwd)

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Win 10, x64
* Compiler: VC++ 12.0, x86
* Release or debug mode: debug and release
* Specific flags used (if any):
* CGAL version: 4.9 and 4.9.1
* Boost version: 1.59.0
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by afabri** [comment]
The documentation of  [`CGAL::Segment_Delaunay_graph_traits_2`](http://doc.cgal.org/latest/Segment_Delaunay_graph_2/classCGAL_1_1Segment__Delaunay__graph__traits__2.html) says that the number type must support exact arithmetic operations.  As this is not the case for  `CGAL::Exact_predicates_inexact_constructions_kernel` you must use  [`CGAL::Segment_Delaunay_graph_filtered_traits_2`](http://doc.cgal.org/latest/Segment_Delaunay_graph_2/classCGAL_1_1Segment__Delaunay__graph__filtered__traits__2.html)

**Comment by Firoon** [comment]
Many thanks for your help, it's worked
