### ISSUE TITLE
Lazy kernel and reference-returning kernel functions

### ISSUE THREAD

**Issue by MaelRL** [CGAL/cgal#2088]
Despite `Construct_point_3` providing `const Point_3& operator()(const Weighted_point_3& wp)` (which just returns `wp.point()`), code like:    
```
typedef K::Point_3                      Point_3;
typedef K::Weighted_point_3             Weighted_point_3;
typename K::Construct_point_3 cp = K().construct_point_3_object();
const Weighted_point_3 * points[4] = {&p0, &p1, &p2, &p};

std::sort(points, points + 4,
      boost::bind<Comparison_result>(K().compare_xyz_3_object(),
        boost::bind<const Point_3&>(
          cp, boost::bind<const Weighted_point_3&>(Dereference<Weighted_point_3>(), _1)),
        boost::bind<const Point_3&>(
          cp, boost::bind<const Weighted_point_3&>(Dereference<Weighted_point_3>(), _2)))
              == SMALLER);
```
cannot be used because the Lazy kernel will returns a temporary when `cp` is called, which then goes out of scope and `compare_xyz_3_object()` is called on garbage.

Obviously, writing `bind<const Point_3>` and taking a copy is enough, but it's a useless copy for all the other kernels.

I don't really have any insight in the Lazy kernel so no real solution, but I'm opening an issue because it seems quite undesirable.

**Comment by sloriot** [comment]
When calling `cp` you create a new node in the DAG so it is not a reference to the point of the weighted point (which does not exists since it's also a node in the DAG). You should use `result_of` to get the correct return type.
