### ISSUE TITLE
Use std::isfinite in CGAL::is_finite

### ISSUE THREAD

**Issue by mglisse** [CGAL/cgal#2092]
CGAL::is_finite(double) is implemented "manually" in double.h. C++11 has std::isfinite, and at least with gcc on x86_64 that generates better code (essentially abs(x)<inf instead of 3 comparisons).

This duplicates code in CORE/Filter.h to define CGAL_CORE_finite.

Compiler support: visual studio 2013 and later should have `std::isfinite`, as well as any C++11 compiler. For anything older, either this is Microsoft and there is `_finite`, or there is support for C99 and `isfinite`, or there is support for BSD and `finite`. This is more or less what CORE/Filter.h does (except that it skips the C99 version).

One suggestion would be to replace what we have in double.h by the code of CORE/Filter.h. Otherwise, at least add one case that calls std::isfinite.

I doubt this has any real impact on performance, it is more a low-priority cleanup.

**Comment by mglisse** [comment]
> Not really a cleanup: I Added yet another #elif !defined CGAL_CFG_NO_CPP0X_ISFINITE.

Good enough for me, at least we should get good code from sensible compilers this way.

**Comment by lrineau** [comment]
Fixed by #2833.
