### ISSUE TITLE
Polyhedron Incremental Builder bug

### ISSUE THREAD

**Issue by jjforsythe** [CGAL/cgal#2094]
## Issue Details

The first step of the function test_facet_indices()  checks an array of vertex indices for equal values. It does not currently compare all pairs of values (specifically against the last index in the array). This leads to test_facet_indices() returning true for invalid faces.

Also, the function test_facet_indices() is does not appear in the reference: http://doc.cgal.org/latest/Polyhedron/classCGAL_1_1Polyhedron__incremental__builder__3.html

Variables i and k are iterated over. In order for every pair of indices to be compared the i index should take values in the range [1, n] instead of [0, n-1]. As k<i it is clear that the nth entry is never compared against currently.

As a simple example to check for equal values in the array [1 ,3, 3]:

The current code checks (i,k) values: (1,0) only. This checks only indices[0] == indices[1], therefore missing the equal pair.

The code should check (i,k) values: (1,0), (2,0), (2,1). This checks indices[0] == indices[1], indices[0] == indices[2] and indices[1] == indices[2], where the 3rd operation is 3 == 3 -> true.

## Code

Polyhedron_incremental_builder_3.h
Line 757:     for ( std::size_t i = 0; i < n; ++i) {
In function: test_facet_indices( std::vector< std::size_t> indices)
```
std::size_t n = indices.size() - 1;
    // Test if a vertex is not twice in the indices
    for ( std::size_t i = 0; i < n; ++i) {
        CGAL_precondition( indices[i] < new_vertices);
        // check if vertex indices[i] is already in the sequence [0..i-1]
        for ( std::size_t k = 0; k < i; ++k) {
            if ( indices[k] == indices[i])
                return false;
        }
    }
```
Suggested fix: Change line to:
`  for ( std::size_t i = 1; i <= n; ++i) {
`

**Comment by sloriot** [comment]
The function is not documented on purpose. If you look at the implementation of `test_facet()` you will see that it is calling `test_facet_indices()` after having put the first id at the end of the sequence.
