### ISSUE TITLE
Bug in doc in blocks with only template functions

### ISSUE THREAD

**Issue by sgiraudot** [CGAL/cgal#2095]
## Issue Details

I noticed a strange bug in the CGAL documentation: most blocks of function headers are justified (the background takes all the width of the page) but some are just aligned to the left (the background stops after the text). For example, [see in Surface Mesh](http://doc.cgal.org/latest/Surface_mesh/classCGAL_1_1Surface__mesh.html), the bug happens for the section _Related Functions_.

I've made some tests, and it seems that this happens for sections that _only_ contain template functions or methods (I have checked and this is not only a bug with related functions). As soon as you add a function (or method) that is not template to the section, then the bug disappears (or similarly, go to other sections and remove all functions/methods that are not template, the bug appears).

I'm not sure if this is a bug of Doxygen or of our own usage of Doxygen (I did not find an issue related to this in the Doxygen tracker, although I'm not sure what keywords to use to describe it).

## Environment

* CGAL version: latest (official documentation)

**Comment by sloriot** [comment]
I tried with our patched version of 1.8.13 and the same issue is there too.

**Comment by lrineau** [comment]
@sloriot What can we do? Is that still the case with 1.8.14 ?

**Comment by sloriot** [comment]
The issue is still here in the latest version. I guess this is something that should be reported to doxygen since we are not doing anything special with related functions AFAIK.

**Comment by afabri** [comment]
Can somenbody who already reported bugs to doxygen (@sloriot ??)  create a minimal example and report.
