### ISSUE TITLE
Polyhedron demo, Qt5, Scene_combinatorial_map_item is no longer working

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#210]
Since the refactoring for new OpenGL and Qt5, the class  `Scene_combinatorial_map_item` has been left behind:
  - it is no longer used by the demo,
  - the code was problematic.

However, the corefinement plugin uses it to display the result of the corefinement.

**Comment by lrineau** [comment]
Cc @sloriot, @maxGimeno, @gdamiand, @afabri

**Comment by sloriot** [comment]
Fixed by 086ffc76 and 00775658
