### ISSUE TITLE
Add a "draw two side" option in the context menu of Polyhedron item

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#2103]
When ticked, it will fill the vector of normals and use the same shader as for polygon soups. When unticked, the vector of normals is cleared. Special care need to be taken when multicolors are ON.

**Comment by lrineau** [comment]
This should be discussed. I do not see why the polyhedron item should have a per-item "two-side" option where there is already a global option "Draw two sides" in the View menu of the application.

**Comment by sloriot** [comment]
Fine, this option should be used then.

**Comment by sloriot** [comment]
Which means that right now this is buggy.

**Comment by lrineau** [comment]
I agree. The "Draw two sides" mode is buggy with the polyhedron item in flat mode (or flat+edges). Actually, it is buggy when the option "Draw two sides" is unchecked. The current implementation compute the facets normals in the fragment shader, and there is no way to compute an oriented normal in the fragment shader.

**Comment by lrineau** [comment]
This should be fixed ASAP in the 4.10 branch, independently from the possible speed optimization that could be implemented using #2055.

**Comment by lrineau** [comment]
Fixed by #2104.
