### ISSUE TITLE
Document the possible Function types in isosurface example

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#2107]
## Issue Details

Alec Jacobson posted [CGAL function pointer callback in isosurface example](http://www.alecjacobson.com/weblog/?p=4034)  so we (@janetournois) might take that up and improve CGAL. 

**Edit**: Note that that discussion started as the issue #2753. --Laurent Rineau, 2018/02/14

**Comment by lrineau** [comment]
Alec Jacobson had to understand how to use `std::bind`. `std::function` is a solution. Usage of `auto` and `decltype` could have been another one. If there anything to change in CGAL, that would only be the documentation. The classes are already templated by the callable type (via the parameter `Function`):
  - [`CGAL::Implicit_surface_3<Traits, Function>`](http://doc.cgal.org/4.10/Surface_mesher/classCGAL_1_1Implicit__surface__3.html)
  - [`CGAL::Implicit_mesh_domain_3<Function, BGT>`](http://doc.cgal.org/4.10/Mesh_3/classCGAL_1_1Implicit__mesh__domain__3.html)

**Comment by lrineau** [comment]
In Mesh_3, [`CGAL::Implicit_mesh_domain_3<Function, BGT>`](http://doc.cgal.org/4.10/Mesh_3/classCGAL_1_1Implicit__mesh__domain__3.html) is dealt with in PR #2739, commit https://github.com/CGAL/cgal/pull/2739/commits/81e1d318dd48c1ffee5ca4e06fe1955fe655bd53 and later ones.

In Surface_mesher... I will try to adopt the same ideas...

**Comment by lrineau** [comment]
#2829 is a fix for Surface_mesher.

**Comment by lrineau** [comment]
#2829 was merged in CGAL-4.12, and fixed this issue.
