### ISSUE TITLE
mesh_a_3d_gray_image.cpp does not compile - CGAL 4.9.1 (homebrew) - Mac OSX 10.12.4

### ISSUE THREAD

**Issue by r03ert0** [CGAL/cgal#2116]
## Issue Details

I can't compile the example `mesh_a_3d_gray_image.cpp`. I am using CGAL 4.9.1 (installed with homebrew), on a Mac with OSX 10.12.4.

I copied into an empty directory the example from http://doc.cgal.org/latest/Surface_mesher/Surface_mesher_2mesh_a_3d_gray_image_8cpp-example.html

Next I used
```
cgal_create_cmake_script
cmake .
make
```

This is the error log:
```
Scanning dependencies of target mesh_a_3d_gray_image
[ 50%] Building CXX object CMakeFiles/mesh_a_3d_gray_image.dir/mesh_a_3d_gray_image.cpp.o
[100%] Linking CXX executable mesh_a_3d_gray_image
Undefined symbols for architecture x86_64:
  "_readImage(char const*)", referenced from:
      CGAL::Image_3::read(char const*) in mesh_a_3d_gray_image.cpp.o
  "triLinInterp(point_image const*, float, float, float, float)", referenced from:
      CGAL::Gray_level_image_3<double, CGAL::Point_3<CGAL::Epick> >::operator()(CGAL::Point_3<CGAL::Epick>) const in mesh_a_3d_gray_image.cpp.o
  "CGAL::Image_3::private_read(point_image*)", referenced from:
      CGAL::Image_3::read(char const*) in mesh_a_3d_gray_image.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [mesh_a_3d_gray_image] Error 1
make[1]: *** [CMakeFiles/mesh_a_3d_gray_image.dir/all] Error 2
make: *** [all] Error 2
```
## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Mac OSX 10.12.4
* CGAL version: 4.9.1

**Comment by afabri** [comment]
Get inspired by examples/Mesh_3/CMakeLists.txt

For example you need `find_package(CGAL COMPONENTS ImageIO)`

**Comment by r03ert0** [comment]
Thank you!
I had to install the version of cgal with Qt.
First I unistalled my current version `brew uninstall --force cgal`,
Next, `brew install cgal --with-imaging`,
Then `cgal_create_cmake_script` to get a `CMakeList.txt` file,
I added `find_package(CGAL COMPONENTS ImageIO)` as you suggested,
And finally `cmake .`, `make`, and everything works.

**Comment by r03ert0** [comment]
Hello,
I'm running again into the same problem. The last time it was solved by `brew install cgal --with-imaging`. However, the `--with-imaging` switch doesn't work anymore... Is there a new way of getting the ImageIO components installed?
thank you !
## Environment
* OS: Mac OS 10.14.4
* cgal: stable 4.14 (bottled)
* cmake version 3.14.1

**Comment by lrineau** [comment]
[**@r03ert0**](https://github.com/r03ert0) commented on [Apr 8, 2019, 8:34 AM GMT+2](https://github.com/CGAL/cgal/issues/2116#issuecomment-480702070 "2019-04-08T06:34:28Z - Replied by Github Reply Comments"):
> Hello,
> I'm running again into the same problem. The last time it was solved by `brew install cgal --with-imaging`. However, the `--with-imaging` switch doesn't work anymore... Is there a new way of getting the ImageIO components installed?
> thank you !
> ## Environment
> * OS: Mac OS 10.14.4
> * cgal: stable 4.14 (bottled)
> * cmake version 3.14.1

Indeed the brew package maintainers have decided to remove all options from Brew packages: https://github.com/Homebrew/homebrew-core/issues/31510. We do not know yet if we want to fork and create a [brew tap][1] for CGAL.

[1]: https://docs.brew.sh/Taps

However, it is now very easy to download the CGAL tarball and use it has header-only. That would be the easiest way to use CGAL with its support for compressed 3D images.
