### ISSUE TITLE
Shape_detection_3: Crash due to empty point indices in is_same

### ISSUE THREAD

**Issue by ochilan** [CGAL/cgal#2118]
## Issue Details

When detecting primitives in slightly more complex point clouds (in my case interiors of buildings with some tens or hundred thousand points) the RANSAC primitive detection sometimes crashes in the `is_same` function of `Shape_base`. The problem appears to be that `m_indices` is empty in some cases. Indeed, the size of `m_indices` of the other objects are being checked for their size, but not of the object we are in. Should it simply be checked for emptyness as well? What are the cases when `m_indices` can be empty at the time `is_same` is called?

## Source Code

I necessary I could try to devise an example but maybe a logical mistake can already be found without an example.

## Environment

* Operating system: Arch Linux 64-bit
* Compiler: gcc
* Release or debug mode: Both
* CGAL version: 4.9.1
* Boost version: 1.63.0

**Comment by sgiraudot** [comment]
This issue was already reported (https://github.com/CGAL/cgal/issues/1818) and was fixed in 4.10: https://github.com/CGAL/cgal/pull/1819
