### ISSUE TITLE
Robustify Surface_mesh_deformation

### ISSUE THREAD

**Issue by maxGimeno** [CGAL/cgal#2124]
## Issue Details

When used on a graph with degenerated faces, the Surface_mesh_deformation generates points with NaN values, which will obviously cause problems, for instance in the normal calculation of the facets of the deformation graph.

It seems the problem occurs in the linear solver. 

It would be great if we could find a workaround to avoid those NaN values.
## Source Code
I used the deformation plugin of the Polyhedron demo with a degenerated triangulated quad to detect the problem.
## Environment
* Release or debug mode:debug
* Other libraries versions if used (Eigen, TBB, etc.):Eigen3

**Comment by maxGimeno** [comment]
A check has been added to prevent that bug.

**Comment by lrineau** [comment]
Do you know which PR solved the issue? I would like to close the issue proper, with the correct milestone.

**Comment by maxGimeno** [comment]
No, I couldn't find it. I have the commit though : it is ddb77488ae749ca39b7674c20eea7bace52f5427

**Comment by MaelRL** [comment]
https://github.com/CGAL/cgal/pull/1983

You can search commit hashes on the github interface and it'll find issues/PRs.

**Comment by lrineau** [comment]
Thank. It's PR #1983.
