### ISSUE TITLE
Improve orient_polygon_soup

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#2125]
I hit an infinite loop in `orient_polygon_soup` because a polygon was containing two identical consecutive vertices. I have a fix for that case in a [branch](https://github.com/sloriot/cgal/tree/PMP-orient_polygon_soup_remove_degenerate_edges). 

The question I have is what should we do in case a vertex is more than once in a polygon but not consecutive. I think we can split the polygon in two at that vertex but it changes the requirements of the function. Since `is_polygon_soup_a_polygon_mesh()` is able to detect these issues, we should be able to fix them. Maybe we should have another function that is fixing the polygons as the purpose of `orient_polygon_soup()` is more about fixing the non-manifold issues and face orientation in a mesh (and not the polygons).

@janetournois @afabri what do you think?

**Comment by afabri** [comment]
If the function does repair something it should be another function.

**Comment by janetournois** [comment]
I agree that it should be in another function. Maybe something like `fix_degeneracies()`. It would include
- fixing polygons with 2 identical and consecutive vertices by merging them
- fixing polygons with 2 identical and not consecutive vertices, by splitting the polygon into two polygons
- what else?

**Comment by sloriot** [comment]
Actually it is a duplicate of #1152, as soon as two vertices are identical keeping the polygon is useless (it become an edge or a vertex).
