### ISSUE TITLE
Polyhedron demo visualisation bug on Mac OS

### ISSUE THREAD

**Issue by danston** [CGAL/cgal#2128]
## Issue Details

[data.zip](https://github.com/CGAL/cgal/files/1014167/data.zip)

When running the CGAL Polyhedron demo on my Mac OS, I have some visualisation issues. I attach three test point clouds (a torus, a cylinder, and a shuttle) and a set of screenshots. With the torus, the point visualisation mode does not work, I do not see any points (screen 1). The same for points+normals mode, I see normals, but I do not see points (screen 2). The shaded point mode works (screen 3).

If I then apply shape detection algorithm, then again I do not see any result (screen 4). Actually, after shape detection, the only mode, which works, is shaded points, but only if I disable the group (screen 5), together with the group none of the modes works (screen 6 for splats).

I did a similar example with a cylinder. In this case, I can see the points (screen 1), but when I use the points+normals mode, all normals are disattached from the points (screen 2).

For a shuttle example, I can see points, but they do not make any sense (screen 1 with points and screen 2 with points+normals).

I tested all these point clouds in MeshLab and they are visualised correctly there. In addition, I  did the torus example on Linux, and again everything was working as expected.

The same happens for other point clouds. So, it looks like always a problem with visualising points, but maybe I am doing something wrong. Please let me know.

**To reproduce the error (if it is a one), it should be the following configuration:**

MacBook Pro 2016, 2.9 GHz Intel Core i7, 16 GB 2133 MHz LPDDR3, Radeon Pro 460 4096 MB Intel HD Graphics 530 1536 MB, Mac OS Sierra.

**I compiled the latest release version of the CGAL public-dev with** 
* libQGLViewer 2.6.4
* Qt 5.8.0_2
* Eigen 3.3.3
* TBB 2017
* VTK 7.1.1_1 
* MFR 3.1.5 
* Boost 1.64.0_1 

 The compiler is Apple LLVM 8.1.0 (clang-802.0.42), target x86_64-apple-darwin16.5.0

**Comment by maxGimeno** [comment]
What do you call "the latest release version of the CGAL public-dev" ?

**Comment by danston** [comment]
Sorry, maybe I was not clear enough. I meant that I cloned the cgal-public-dev from github, checked out the master branch, and then built the release version of the demo from Polyhedron/demo/Polyhedron. Is it more clear or your question is related to something else? Thanks.

**Comment by lrineau** [comment]
There is no `master` branch in the repository `cgal-public-dev`! :-\

In that directory, please type:

    git log -n1

and give us the result. That way we will know the exact version of the code you have compiled.

**Comment by danston** [comment]
commit 46cffc0dd70ce91b7a5b3494593353cfa3356c6d (HEAD -> master, cgal/master)
Merge: c754fc70d2 cbd73f4274
Author: Laurent Rineau <laurent.rineau@cgal.org>
Date:   Tue May 9 12:19:29 2017 +0200

    Merge pull request #2064 from MaelRL/Kernel-Fix_coplanar_orientation_doc-GF
    
    Improve documentation of concept CoplanarOrientation_3
    
    (Via a merge of 'cgal/releases/CGAL-4.10-branch')

**Comment by danston** [comment]
Sorry for the late answer. This is what I get. I compiled everything as in the tutorial here: [https://github.com/CGAL/cgal/wiki/Information-for-New-Developers](https://github.com/CGAL/cgal/wiki/Information-for-New-Developers) and then here: [https://github.com/CGAL/cgal/wiki/Branch-Build](https://github.com/CGAL/cgal/wiki/Branch-Build)

**Comment by lrineau** [comment]
Alright. Now I understand.You did not have just a checkout of cgal-dev, but the refined setup we use, with multiple remote repositories.

**Comment by danston** [comment]
Ok, this is what I should have written. Next time I will be more precise :)

**Comment by lrineau** [comment]
Fixed by #2147.
