### ISSUE TITLE
Windows, FPU.h: replace `_control_fp` by intrisics

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#2135]
In CGAL.4.10, in <CGAL/FPU.h>,  the macros `CGAL_IA_SETFPCW` and `CGAL_IA_GETFPCW` are implemented using `_controlfp_s`, instead of using macros from `<xmmintrin.h>`.

If the platform is Windows x64, with `_M_X64` defined, [only the SSE2 FPU is used][*], and we can probably define `CGAL_SAFE_SSE2` and use the macros from `<xmmintrin.h>`.

  [*]: https://msdn.microsoft.com/en-us/library/e9b52ceh.aspx

**Comment by mglisse** [comment]
Uh, strange, I specifically remembered that VS used a mix of x87/sse for floating point in all modes. Apparently I was wrong...
I doubt that using intrinsics will win much compared to _controlfp. On the other hand, this should mean that we can remove `|| defined _M_X64` in the definition of CGAL_FPU_HAS_EXCESS_PRECISION, I don't remember if that matters on windows.

**Comment by mglisse** [comment]
After reading FPU.h, I don't expect any performance gain from this. Still, you are welcome to remove `|| defined _M_X64` before the definition of CGAL_FPU_HAS_EXCESS_PRECISION and add it before CGAL_SAFE_SSE2 instead. I cannot test windows myself.
The thing that could help is changing the definition of CGAL_IA_FORCE_TO_DOUBLE (see `#elif 1`), but that requires using the fenv pragma, and I believe you already did some experiments a few years ago ( https://cgal.geometryfactory.com/CGAL/Members/wiki/Staging_Area/Floating_point_optimizations_control ).

**Comment by lrineau** [comment]
Actually on Windows, `_controlfp_s` is a black-box function, that seems costly, and that the compiler probably cannot inline. Unfortunately, I do not know if and where we can find it source code. That is why my hope is that the implementation from `<xmmintrin.h>` would be cheaper to use.

**Comment by lrineau** [comment]
> Note that the implementation in xmmintrin.h calls into another black box: `_mm_getcsr` and/or `_mm_setcsr`. Also, my memory of experimenting with changing the rounding mode is that the actual change is orders of magnitude more expensive than a function call. But still, I am in favor of the change you propose, if only because it documents the situation more clearly, and may be a necessary step for further optimization anyway.

`_mm_getcsr` and `_mm_setcsr` are not black boxes. They are documented as compiler intrinsics on MSDN: 

https://docs.microsoft.com/en-us/cpp/intrinsics/compiler-intrinsics?view=vs-2019
> If a function is an intrinsic, the code for that function is usually inserted inline, avoiding the overhead of a function call and allowing highly efficient machine instructions to be emitted for that function. An intrinsic is often faster than the equivalent inline assembly, because the optimizer has a built-in knowledge of how many intrinsics behave, so some optimizations can be available that are not available when inline assembly is used.

https://docs.microsoft.com/en-us/cpp/intrinsics/x64-amd64-intrinsics-list?view=vs-2019

The issue with `controlfp` and `control87` seems to be that the API is given the mask as if it was for the x87 FPU, and then the code has to "translate" that to the mask for SSE. Plus the function call, and it probably explains why the calls to `_controlfp_s` are costly on Windows.
