### ISSUE TITLE
Is there a "concept" about computing "integral" of a "Polynomial"?

### ISSUE THREAD

**Issue by JloveU** [CGAL/cgal#2140]
## Issue Details

I 'm going to use Polynomial in CGAL.
And I need functions of "integral" and "differential".
I have foundthat for "differential" as "PolynomialTraits_d::Differentiate Concept Reference" at [CGAL 4.9.1 - Polynomial: PolynomialTraits_d::Differentiate Concept Reference](http://doc.cgal.org/latest/Polynomial/classPolynomialTraits__d_1_1Differentiate.html).
But I have not found that for "integral".

Is there a "concept" about computing "integral" of a "Polynomial"?

## Source Code

None.

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):
* Compiler:
* Release or debug mode:
* Specific flags used (if any):
* CGAL version: 4.9.1
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by sloriot** [comment]
I don't think so.
