### ISSUE TITLE
Mesh_cell_base_3 is not a model of MeshCellBase_3

### ISSUE THREAD

**Issue by MaelRL** [CGAL/cgal#2144]
`Mesh_cell_base_3` requires `invalidate_circumcenter()` but does not implement it, hoping that the regular cell base will implement it. However, the documentation says that the regular cell base should simply be a model of `RegularTriangulationCellBase_3`, which does not require `invalidate_circumcenter()` either.

Additionally, the regular cell base `Cb` of `Mesh_cell_base_3` defaults to `Regular_triangulation_cell_base_3` in the documentation, but in practice defaults to `Regular_triangulation_cell_base_with_circumcenter_3` (and rightfully so, since it will not compile with `Regular_triangulation_cell_base_3`).

Should there be a concept `RegularTriangulationCellBaseWithWeightedCircumcenter_3`? Or a more generic `TriangulationCellBaseWithCircumcenter_3` that says something like "with a circumcenter adapted to the metric"?

**Comment by lrineau** [comment]
Just for Mesh_3, the concept `RegularTriangulationCellBaseWithWeightedCircumcenter_3` is sufficient. I vote for it.

Cc @janetournois @cjamin

**Comment by cjamin** [comment]
I agree.

**Comment by janetournois** [comment]
me too

**Comment by MaelRL** [comment]
Since `invalidate_circumcenter` is moved to this new concept, should it also be renamed `invalidate_weighted_circumcenter` on the way, since `RegularTriangulationCellBase_3` requests `weighted_circumcenter` and not `circumcenter` ?

**Comment by lrineau** [comment]
I would even rename it to `invalidate_weighted_circumcenter_cache()`.

**Comment by MaelRL** [comment]
Making the changes in the implicit conversion removal branch for convenience (https://github.com/CGAL/cgal/pull/2102), since it changes a lot of vertex/cell concepts.
