### ISSUE TITLE
Cgal and CMAKE

### ISSUE THREAD

**Issue by ujjwalrathod007** [CGAL/cgal#2150]
_Please use the following template to help us solving your issue._

## Issue Details

_Describe your issue. Please be specific (compilation error, runtime error, unexpected behavior, wrong results, etc.)._
I have the problem of CMAKE and CGAL. The error is it cannot find the CMakeList.txt. the exct error is as following,
CMake Error: The source directory "C:/CGAL-4.10-doc_html.tar" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

My setting in CMAKE are as following

Where is the sourse code? C:/CGAL-4.10-doc_html.tar
Where to build? C:/CGAL-4.10-doc_html.tar

I have already created a new environment variable.

## Source Code

_If your issue arises by using CGAL in your own source code, please provide a minimalist example that we can compile easily to reproduce the bug. If your issue arises from using a CGAL program (demo, example, etc.), please let us know which one. Helping you solving an issue is much easier and efficient if we can reproduce it._

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Win 10 64 bit
* Compiler: Cmake
* Release or debug mode:
* Specific flags used (if any):
* CGAL version: letest
* Boost version:No need
* Other libraries versions if used (Eigen, TBB, etc.): Visual studio 2015

**Comment by lrineau** [comment]
1. A `.tar` should be uncompressed before you can use its content.
2. Anyway, the tarball that contains the sources of CGAL is `CGAL-4.10.tar.gz`, and not `CGAL-4.10-doc_html.tar.gz`.
3. On Windows you should use the Windows installer: [`CGAL-4.10-Setup.exe`][l].

  [l]: https://github.com/CGAL/cgal/releases/download/releases%2FCGAL-4.10/CGAL-4.10-Setup.exe
