### ISSUE TITLE
Polyhedron demo: Feature request for displaying indices

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#2165]
## Issue Details

* Additionally to "I", this should be switchable in the popup window when I right-click an item
* It could be configurable to see vertex/edge/face indices
* It would be cool, if I could enter a vertex id, and then the camera zooms to this vertex.

**Comment by lrineau** [comment]
Maxime, is not it fixed by #2204?

**Comment by maxGimeno** [comment]
Oops, yes it is.
