### ISSUE TITLE
Polyhedron Demo: bug in Convert to Polyhedron

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#2170]
## Issue Details

@maxGimeno Load 2 Surface_mesh. Convert the first to a Polyhedron is ok. Convert the second segfaults.

**Comment by maxGimeno** [comment]
I cannot reproduce.

**Comment by lrineau** [comment]
I do not expect any answer from Andreas. I close the bug. We'll see if somebody wants to reopen it.
