### ISSUE TITLE
Qualify CGAL::sign

### ISSUE THREAD

**Issue by mglisse** [CGAL/cgal#2187]
In most places in CGAL, we call `CGAL::sign` or the equivalent `CGAL_NTS sign`, which works fine. However, a few places, in particular Polygon_mesh_processing/internal/Side_of_triangle_mesh/Ray_3_Triangle_3_traversal_traits.h:182, internal/corefinement/predicates.h, Nef_S2/Sphere_circle.h, call it with just `sign`. This causes ambiguity for external number types that already have a sign function defined.

**Comment by sloriot** [comment]
Should be fixed by #2188.
Side question: do you see any reason to keep `CGAL_NTS`?

**Comment by mglisse** [comment]
> Should be fixed by #2188.

Thanks.

> Side question: do you see any reason to keep CGAL_NTS?

I don't have an opinion about that.

**Comment by lrineau** [comment]
Fix in the branch of 4.10.

**Comment by mglisse** [comment]
Hello,

you seem to have missed Nef_S2/Sphere_circle.h 😞

**Comment by afabri** [comment]
@mglisse  can you just do it, or do you want to wait for Sebastien to come back from vacation?

**Comment by mglisse** [comment]
What is the expected level of testing for this kind of change (adding `CGAL::` in a few places) these days? Is testing 1 or 2 files, then relying on travis+testsuite good enough?

**Comment by afabri** [comment]
Running the Nef_3 and Nef_S2 testsuite should do it.

**Comment by lrineau** [comment]
Fixed by #2282.
