### ISSUE TITLE
Submit patch to Boost Bimap to remove a warning in Mesh_3

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#219]
See the patch at https://github.com/CGAL/cgal/issues/45#issuecomment-126593795

**Comment by sloriot** [comment]
[Done](https://github.com/boostorg/bimap/pull/2)

**Comment by lrineau** [comment]
The PR is done for several months. Is that the correct way to submit patches to Boost developers? Should not we also send a mail to a mailing list?

**Comment by sloriot** [comment]
For this specific case, we should indeed send an email to the list to check if there is a maintainer willing to merge the PR.

**Comment by sloriot** [comment]
The PR was merged.
