### ISSUE TITLE
Misleading warning message in Surface_mesh

### ISSUE THREAD

**Issue by sgiraudot** [CGAL/cgal#2195]
## Issue Details

Using the `operator>>()` with Surface_mesh, the user can run into the following message:

```
"Warning: Facets don't seem to be oriented. Loading a Soup of polygons instead."
```

But if we look at the code, here is what happens:

```cpp
      Face_index fi = sm.add_face(vr);
      if(fi == sm.null_face())
      {
       std::cout<< "Warning: Facets don't seem to be oriented. Loading a Soup of polygons instead."<<std::endl;
       sm.clear();
       return is;
      }
```
It seems to me this message is very misleading:
* From what I understand, this is much closer to an _Error_ than to a _Warning_
* The program does not "_load a Soup of polygons instead_" as suggested, it actually does nothing and returns an empty surface mesh

Note also that this behavior is not documented.

## Environment

* CGAL version: master

**Comment by janetournois** [comment]
The message could at least be "Error: ... . Try to load a soup..."

**Comment by afabri** [comment]
@lrineau: Shall we set the failbit  `is.setstate(std::ios::failbit)`

**Comment by lrineau** [comment]
Yes, the failbit seems the right way to report the error.

**Comment by lrineau** [comment]
But anyway the message "Loading a Soup of polygons instead." should be in the demo only.

**Comment by lrineau** [comment]
I reopen this issue, because, now that #2265 is merged in `master`, the code
```C++
std::cout<< "Warning: Facets don't seem to be oriented. Loading a Soup of polygons instead."<<std::endl;
```
should be in the I/O plugin of the demo.

**Comment by afabri** [comment]
That is already done this way in [Surface_mesh_io_plugin.cpp](https://github.com/CGAL/cgal/blob/master/Polyhedron/demo/Polyhedron/Plugins/IO/Surface_mesh_io_plugin.cpp#L65)

**Comment by lrineau** [comment]
Maxime just told me that there is already a message in the internal console of the application. I close the issue.
