### ISSUE TITLE
IO for Polygon Soups

### ISSUE THREAD

**Issue by sgiraudot** [CGAL/cgal#2196]
## Issue Details

I'm opening this issue just to start a discussion on the input/output functions for polygons soups, especially:
- the current OFF reader
- a PLY reader to develop

So far, we already have a function that can interpret OFF input as a polygon soup, namely `read_OFF()`. But this function is in the `Polyhedron_IO` package (although it never actually refers to a Polyhedron), and it is not documented. Note that it is used in [the example for polygon soup orientation](http://doc.cgal.org/latest/Polygon_mesh_processing/index.html#PolygonSoupExample), which makes me think it _should_ be documented.

For PLY, we already have a PLY reader (with a new version in [pull request](https://github.com/CGAL/cgal/pull/2138) along with LAS) but for points only. There is not that much of work to do if we want to handle face graphs and polygon soups in addition (basically, write something to handle the PLY lists of indices).

### Questions

1. Do you think it would make sense to move `read_OFF()` into Polygon Mesh Processing? There could be an IO section in there (and polygon soups are used there, for example for orientation)

2. In that case, do we also want to add `read_PLY()`? I'm not really fond of these names, it seems to me that they should be more precise, for example `read_off_polygon_soup()` and `read_ply_polygon_soup()` (similarly to what we have with `read_off_points()` and `read_ply_points()`).

3. For `Point_set_3`, I made an `operator>>()` that automatically calls the right reader (between `XYZ`, `OFF`, `PLY` and soon `LAS`) by analysing the first line of the stream (that contains a tag, except for `XYZ`). Do we want the same thing for `Surface_mesh`, for example? It could select between `OFF` and `PLY`. And as it works similarly to `Point_set_3`, we could similarly recover additional properties in `PLY` in automatically generated property maps.

**Comment by gdamiand** [comment]
1. I agree that this function could be move into Polygon Mesh Processing and documented.

2. I also agree that the name read_OFF is not correct (moreover it seems in conflict with the small feature add generic read and write functions). Why not define a unique function read_model_as_polygon_soup that analyse the header of the file ? (and you can do the same for read_model_as_points)

**Comment by sgiraudot** [comment]
(I'm reopening it, it's only half-solved: there is still a small feature to do to document and unify what exists in non-documented code.)

**Comment by afabri** [comment]
The PR #2657 is related. There as well I am looking for the right spot  where to document `read_STL()`.

**Comment by lrineau** [comment]
Is that solved?

**Comment by sloriot** [comment]
There should be a proper IO package where all those IO functions should be documented. This is not done yet (if I'm not mistaken all the functions are in `Polyhedron_IO` without documentation).

**Comment by sgiraudot** [comment]
As far as i know, yes, the functions are in `Polyhedron_IO` and not documented, this won't be fixed in 4.12.
