### ISSUE TITLE
SparseLinearAlgebraTraits_d concepts and models

### ISSUE THREAD

**Issue by MaelRL** [CGAL/cgal#2197]
According to the matrix concept ([doc](http://doc.cgal.org/latest/Solver_interface/classSparseLinearAlgebraTraits__d_1_1Matrix.html)), a function `get_coef(i,j)` should be offered by models.

The models `CGAL::Eigen_sparse_matrix<T>` and the symmetrical version do not offer this function. Why was `get_coef()` not added to those classes / Should `get_coef()` be removed from the concept ?

**Comment by sloriot** [comment]
IMO, it is an heritage from Taucs and since it was not used by any algorithm in CGAL it simply did not get ported to the Eigen model.

**Comment by sloriot** [comment]
I checked back to CGAL 3.9 and it was not used there (Eigen models was introduced in 4.0).

**Comment by afabri** [comment]
@sloriot so do you suggest to remove it?

**Comment by sloriot** [comment]
Yes, I suggest to remove it but AFAIR, @MaelRL might need it.

**Comment by MaelRL** [comment]
I already cleaned `get_coef` from the parameterization package (except one instance that apparently went through the net, but it's easily fixed).

Removing that function from the concept creates imbalance between the vector and the matrix, though: the former has a read access but not the latter.

**Comment by sgiraudot** [comment]
It seems to me that reading a coefficient should be possible even if it's not used so far. So why not simply implement `get_coef` for the Eigen model that misses it? I expect it should be quite straightforward.

From what I see, this is more a doc bug (incomplete model), I wouldn't change the concept but make the model consistent.

**Comment by MaelRL** [comment]
Fixed by #2469.
