### ISSUE TITLE
BGL : vertices(Graph_with_descriptor_with_graph) is not a CGAL::Range

### ISSUE THREAD

**Issue by janetournois** [CGAL/cgal#2199]
## Issue Details

The result type of `vertices(Graph_with_descriptor_with_graph)` does not implement the concept [CGAL::Range](http://doc.cgal.org/latest/Circulator/classRange.html)

For example, applying `begin()`, `end()`, or `empty()` to it does not compile.

## Source Code

see for example the commit 0c0177e4324c51cd4bdc8305600b7955f055b71a
The function `empty()` does not compile because `begin()` and `end()` cannot be applied to a `std::pair` (which is the actual return type).

## Environment

* CGAL version: current master

**Comment by sloriot** [comment]
The same holds for edges, faces, ...

**Comment by sloriot** [comment]
Fixed by #1861
