### ISSUE TITLE
Strange warning in demo/Triangulation_3, since the switch to Qt5/OpenGL-3

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#221]
https://cgal.geometryfactory.com/CGAL/Members/testsuite/CGAL-4.7-Ic-102/Triangulation_3_Demo/TestReport_cgaltester_x86-64_Darwin-13.0_Apple-clang-3.2_Release.gz
```
test/Triangulation_3_Demo/Viewer.cpp:1562:18: warning: comparison of two values with different enumeration types ('Viewer::Mode' and 'Viewer::selectionMode') [-Wenum-compare]
    if(m_curMode != NORMAL && m_showTrackball)
       ~~~~~~~~~ ^  ~~~~~~
1 warning generated.
```

https://cgal.geometryfactory.com/CGAL/Members/testsuite/CGAL-4.7-Ic-102/Triangulation_3_Demo/TestReport_lrineau_Fedora-rawhide.gz
```
test/Triangulation_3_Demo/Viewer.cpp:1562:21: warning: comparison between ‘enum Viewer::Mode’ and ‘enum Viewer::selectionMode’ [-Wenum-compare]
     if(m_curMode != NORMAL && m_showTrackball)
                     ^
```

There must be something fishy in the code...

**Comment by lrineau** [comment]
Cc @maxGimeno

**Comment by maxGimeno** [comment]
Fixed by 1f976a in CGAL-Qt5_support-GF
