### ISSUE TITLE
installation manual should be updated: explain the Github download page

### ISSUE THREAD

**Issue by MoniqueTeillaud** [CGAL/cgal#2211]
Hi

The directory structure when downloading CGAL 4.10 has changed, is not any more what is written there: http://doc.cgal.org/latest/Manual/installation.html#title6

Monique

**Comment by lrineau** [comment]
Can you tell what is wrong in that section? As far as I can see the layout is still that one.

**Comment by MoniqueTeillaud** [comment]
ok, now I understand: you don't get the same layout when you download
CGAL-4.10.zip or Source code (zip) on https://github.com/CGAL/cgal/releases
though both are of course giving source code. 
I had not noticed that before (and I don't guess the rationale at first sight...)

Then maybe I should rename my issue to something like: _explain what "Source code" is on the github release page_ .

**Comment by sloriot** [comment]
Closing this issue that has been fixed by #4304
