### ISSUE TITLE
seg fault segmentation plugin

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#2222]
## Issue Details

Load a mesh,  Operations -> Segmentation.  Hit the Segment button results in a segfault

## Environment

* Operating system Windows 32/64 bits

* CGAL version: master

**Comment by lrineau** [comment]
The report is not precise enough. `master` does not say which Git hash tag was the `HEAD` of `master` at the time you compiled.

I tried with a fresh build of `master` (d878561809d99f659bd834588befb52da0ea98bf), on my Linux machine (Fedora 25, up-to-date), and it worked.

Have you rebuild (or removed) all the plugins? The symptoms look like a binary-incompatibility.

**Comment by maxGimeno** [comment]
Actually I fixed a similar bug in #2268. It was a missing invalidateOpenGLBuffers() call, that sometimes resulted in a segfault.
