### ISSUE TITLE
Polyhedron demo: orthographic projection is broken

### ISSUE THREAD

**Issue by sgiraudot** [CGAL/cgal#2240]
## Issue Details

When I click on "Orthographic projection", the display _does_ switch to orthographic projection: but as soon as I click somewhere on the scene, it goes back to the default one. If I unset and set it again, it does the same (I can only see the orthographic projection of the fixed view, it goes away as soon as I move the scene).

## Environment

* Operating system: Debian GNU/Linux 64b
* Compiler: g++
* Release
* CGAL version: master

**Comment by lrineau** [comment]
Fixed in 4.10.1 and `master` by #2243.
