### ISSUE TITLE
compilation of code failing at extrac() in io.h

### ISSUE THREAD

**Issue by luca-penasa** [CGAL/cgal#2246]
## Issue Details

Compilation of code against trunk fail at CGAL/IO/io.h at 
```cpp
template < class T >
inline
void
read(std::istream& is, T& t, const io_Extract_insert&)
{
	extract(is, t);
}
```

error is:
```
[...]/CGAL/IO/io.h:315: error: missing template arguments before ‘(’ token
  extract(is, t);
         ^
```
is this a known issue? I was not able to find out where extract is defined. Can anybody help in figure out how to debug it?

## Source Code

unable to provide code

## Environment

* Operating system arch linux, 64 
* Compiler: gcc 7.1.1
* Release or debug mode: Release
* Specific flags used (if any):
* CGAL version: latest git trunk
* Boost version: 1.64.0
* Other libraries versions if used (Eigen, TBB, etc.): code included through libigl

**Comment by lrineau** [comment]
Your report does not have enough information to find what happened.

Could you try to point out which code lead to that compilation error?

**Comment by luca-penasa** [comment]
I can understand. Does anybody know where the extract method is defined?
I solved commenting out that line for now... Unfortunately don't have the time to go through a detailed analysis...

I suspect this error popped out when I included a libigl include:
 <igl/copyleft/cgal/trim_with_solid.h>
which makes use of the cgal include 
<CGAL/Exact_predicates_exact_constructions_kernel.h>

thus it could be probably a missing include that should be made before this last one, but I don't know where extract is supposed to be defined in CGAL...

**Comment by lrineau** [comment]
There are overloads of `extract` in the following CGAL headers:
```
include/CGAL/Ray_3.h
include/CGAL/Direction_2.h
include/CGAL/Point_3.h
include/CGAL/Line_2.h
include/CGAL/Ray_2.h
include/CGAL/Direction_3.h
include/CGAL/Weighted_point_2.h
include/CGAL/Circle_2.h
include/CGAL/Vector_2.h
include/CGAL/Vector_3.h
include/CGAL/Point_2.h
include/CGAL/Sphere_3.h
include/CGAL/Weighted_point_3.h
```

**Comment by luca-penasa** [comment]
thank you very much... seems like moving the include  <igl/copyleft/cgal/trim_with_solid.h> from the header to the implementation solved the issue. Not sure what the problem was... Sorry for the waste of time...

Thank you for cgal btw 👍 
Luca
