### ISSUE TITLE
Polyhedron demo : select newly created item

### ISSUE THREAD

**Issue by janetournois** [CGAL/cgal#226]
When a new item is created, many plugins try to select the new item with code like
```c++
int item_id = scene->addItem(new Scene_polyhedron_selection_item(poly_item, mw));
scene->setSelectedItem(item_id);
```
This does not succeed to make the new item selected and does not help using some plugins.

We should probably use the function
```C++
void MainWindow::selectSceneItem(int i)
```

**Comment by lrineau** [comment]
As I said in a private discussion, the function `Scene::setSelectedItem` could emit a dedicated signal, connected to a `MainWindow::selectSceneItem`.

**Comment by sloriot** [comment]
Do you have a plugin in mind? and a way to reproduce the issue?

**Comment by janetournois** [comment]
Sure.
One example is the selection plugin. Do the following
> open an off file
> click "Operations -> Selections".

Now, have a look to the list of available "Operations".
Next, click on the initial polyhedron item from the list, and have a look to "Operations" again
Finally, click on the selection item from the list, and list "Operations".

This simple test shows that the item selected is the polyhedron item and not the selection item.

**Comment by sloriot** [comment]
Fixed by CGAL/cgal-dev-public@1a21950c and CGAL/cgal-dev-public@63dca733

**Comment by lrineau** [comment]
Those commits do not exist, according to Github. In the source of the Github message, you must specify the full commit hash. Then Github only displays a short version of the hash.

**Comment by sloriot** [comment]
No, the issue was that I wrote cgal-dev-public instead of cgal-public-dev
