### ISSUE TITLE
Problem building CGAL 4.3

### ISSUE THREAD

**Issue by myu20** [CGAL/cgal#2260]
## Issue Details

I have errors when trying to build CGAL 4.3. I am using version 4.3 instead of the latest release because I want to use the package [optimal-mrpp-continuous](https://github.com/rutgers-arc-lab/optimal-mrpp-continuous), which uses version 4.3. I tried using the the package with CGAL 4.10 but encountered runtime errors.

CGAL was installed from [cgal-releases-CGAL-4.3.tar.gz](https://github.com/CGAL/cgal/releases/tag/releases%2FCGAL-4.3) at /home/chaohui/CGAL-4.3

The errors are:
`libCGAL is configured`
`-- Sources for CGAL component library 'CGAL_Core/CMakeLists.txt' detected
CMake Error at Installation/src/CMakeLists.txt:81 (add_subdirectory):`
`add_subdirectory given source`
 `"/home/chaohui/CGAL-4.3/CGAL_Core/src/CGAL_Core/CMakeLists.txt" which is
  not an existing directory.`
`Call Stack (most recent call first):`
 ` Installation/src/CMakeLists.txt:139 (configure_component)`

`-- Sources for CGAL component library 'CGAL_ImageIO/CMakeLists.txt' detected
CMake Error at Installation/src/CMakeLists.txt:81 (add_subdirectory):`
 `add_subdirectory given source`
  `"/home/chaohui/CGAL-4.3/CGAL_ImageIO/src/CGAL_ImageIO/CMakeLists.txt" which
  is not an existing directory.`
`Call Stack (most recent call first):`
  `Installation/src/CMakeLists.txt:139 (configure_component)`

`-- Sources for CGAL component library 'CGAL_Qt4/CMakeLists.txt' detected
CMake Error at Installation/src/CMakeLists.txt:81 (add_subdirectory):`
 `add_subdirectory given source`
  `"/home/chaohui/CGAL-4.3/GraphicsView/src/CGAL_Qt4/CMakeLists.txt" which is
  not an existing directory.`
`Call Stack (most recent call first):`
  `Installation/src/CMakeLists.txt:139 (configure_component)`

`-- Sources for CGAL component library 'CGAL_Qt3/CMakeLists.txt' detected
CMake Error at Installation/src/CMakeLists.txt:81 (add_subdirectory):`
 `add_subdirectory given source`
  `"/home/chaohui/CGAL-4.3/Qt_widget/src/CGAL_Qt3/CMakeLists.txt" which is not
  an existing directory.`
`Call Stack (most recent call first):`
  `Installation/src/CMakeLists.txt:139 (configure_component)`

`-- Sources for CGAL component libraries 'CGAL_Core/CMakeLists.txt;CGAL_ImageIO/CMakeLists.txt;CGAL_Qt3/CMakeLists.txt;CGAL_Qt4/CMakeLists.txt' detected`
`== Generating build files (DONE) ==`

`-- Configuring incomplete, errors occurred!`

## Environment

* Operating system: Ubuntu 14.04 64 bit
* Compiler: CMake 3.7.0
* Release or debug mode:
* Specific flags used (if any):
* CGAL version: 4.3
* Boost version: 1.54
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by lrineau** [comment]
At the time of CGAL-4.3, CMake 3.0 and later versions where not supported. That might be the bug we fixed by PR #132. Try to apply its patch to CGAL-4.3. 

But nothing is guaranteed. CMake -4.3 is no longer supported by the CGAL project.

**Comment by myu20** [comment]
Thanks, this worked.
