### ISSUE TITLE
create_new_release: Unable to connect to a repository at URL 'svn+ssh://scm.gforge.inria.fr/svn/cgal/tags/internal-releases'

### ISSUE THREAD

**Issue by nschloe** [CGAL/cgal#2262]
When running `create_new_release`, and SVN error occurs:
```
./trunk/Scripts/developer_scripts/create_new_release 
svn: E210002: Unable to connect to a repository at URL 'svn+ssh://scm.gforge.inria.fr/svn/cgal/tags/internal-releases'
svn: E210002: To better debug SSH connection problems, remove the -q option from 'ssh' in the [tunnels] section of your Subversion configuration file.
svn: E210002: Network connection closed unexpectedly
```

**Comment by lrineau** [comment]
Subversion is no longer supported by the CGAL project.

That script must be run from inside a **Git** working directory containing a checkout of https://github.com/CGAL/cgal.

Anyway, the script is not documented, and should not be used by CGAL users, but only by the release manager (who is me, by the way).

If you want to create a release tarball from the Git layout, use [`Scripts/developer_scripts/create_new_release`][*] instead. It is not documented either, but that one is not reserved for the release manager.

  [*]: https://github.com/CGAL/cgal/blob/master/Scripts/developer_scripts/create_internal_release

**Comment by nschloe** [comment]
I don't quite understand. I mean, I _did_ use `Scripts/developer_scripts/create_new_release`, and from a Git layout too. Not renaming the checkout folder to `trunk` leads to the error
```
svn: E155007: '/path/to/trunk' is not a working copy
```
which is why you see `./trunk` in the original post.

**Comment by lrineau** [comment]
Sorry, I meant  [`Scripts/developer_scripts/create_internal_release`][*].

  [*]: https://github.com/CGAL/cgal/blob/master/Scripts/developer_scripts/create_internal_release

**Comment by nschloe** [comment]
> Scripts/developer_scripts/create_new_release

The same svn error occurs when using that script.

**Comment by lrineau** [comment]
I wrote, in https://github.com/CGAL/cgal/issues/2262#issuecomment-315772967:
> Sorry, I meant `Scripts/developer_scripts/create_internal_release`.

**Comment by nschloe** [comment]
Ah yes, got that mixed up. With `internal`, I'm still getting
```
fatal: ambiguous argument 'cgal/master..': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```
but the script seems to do something anyways.
