### ISSUE TITLE
Polyhedron_demo: Remaining plugins that needs to work with Surface_mesh

### ISSUE THREAD

**Issue by maxGimeno** [CGAL/cgal#2271]
## Issue Details

There are still plugins that need work for use with a Surface_mesh:

- [x] the Remeshing_plugin should be integrated into the Mesh_3_plugin.
- [x] Surf_io_plugin and Surf_to_sm_io_plugin should be merged and depend on the Polyhedron_mode.
- [x] the Fairing_plugin is not touched

**Comment by lrineau** [comment]
I close this tracking issue. The remaining task seems #2278 (remove the `remeshing_plugin` that uses `Surface_mesher`).
