### ISSUE TITLE
Support of Qt5 in cgal_create_cmake_script and cgal_create_CMakeLists

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#228]
There is a support for Qt3 in the script `cgal_create_cmake_script` and a support for Qt4 in `cgal_create_CMakeLists`. Those supports should be removed, or upgraded to support Qt5.

**Comment by lrineau** [comment]
There is also something in `developer_scripts/cgal_generate_cmake_script.cmake`.

**Comment by sloriot** [comment]
@lrineau  It looks like this ticket can be closed, right?

**Comment by lrineau** [comment]
Yes, I think so. We no longer care if those scripts support Qt4/Qt5 or not.
