### ISSUE TITLE
Runtime error of QP_solver testsuite with LEDA or GMPXX

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#2283]
The testsuite of QP_solver has [two runtime errors](https://cgal.geometryfactory.com/CGAL/testsuite/results-4.11-Ic-71.shtml#QP_solver) in the columns
  - Apple-clang-5.1_Darwin-13.0_Release-LEDA-without-GMP
  - Fedora-Release_

`Fedora-Release` is the only column for which GMPXX is activated, and `*LEDA-without-GMP` is the only one using LEDA as a replacement for GMP. Maybe QP_solver's testsuite does not like that the exact number type is not `CGAL::Gmpq`.

(Cc @mglisse for advices on gmpxx)

(The official maintainer of that package QP_solver if Bernd. I do no know to who I should assign the issue.)

**Comment by mglisse** [comment]
My guess would be that it is related to reading "123.456" from an istream into a rational, for which we have special code in CGAL, but this test probably doesn't use it.

**Comment by mglisse** [comment]
I suggest the following, if someone wants to handle it.
```
--- a/QP_solver/include/CGAL/QP_models.h
+++ b/QP_solver/include/CGAL/QP_models.h
@@ -29,6 +29,7 @@
 #include <CGAL/algorithm.h>
 #include <CGAL/QP_solver/basic.h>
 #include <CGAL/QP_solver/functors.h>
+#include <CGAL/IO/io.h>
 #include <vector> 
 #include <map>
 #include <iomanip>
@@ -1067,7 +1068,7 @@ private:
   template<typename NumberType>
   bool number(NumberType& entry) {
     // whitespace(); the following >> should care for this
-    from >> entry;
+    from >> CGAL::iformat(entry);
     return from.good();
   }
```

**Comment by lrineau** [comment]
I can reproduce the issue on my machine (with `-DWITH_GMPXX=ON`), and I have verified that this PR fixes the issue.
