### ISSUE TITLE
CGAL 4.10 compilation failures with Cray C++ compiler

### ISSUE THREAD

**Issue by kynan** [CGAL/cgal#2316]
## Issue Details

Building CGAL release 4.10 using Cray compilers fails as follows:
```
[ 16%] Building CXX object src/CGAL/CMakeFiles/CGAL.dir/all_files.cpp.o
CC-135 crayc++: ERROR File = [...]/CGAL-4.10/include/CGAL/Interval_nt.h, Line = 185
  The namespace "CGAL::internal" has no member "get_static_minimin".
      return IA(-CGAL_IA_MIN_DOUBLE, CGAL_IA_MIN_DOUBLE);
                 ^

CC-135 crayc++: ERROR File = [...]/CGAL-4.10/include/CGAL/Interval_nt.h, Line = 185
  The namespace "CGAL::internal" has no member "get_static_minimin".
      return IA(-CGAL_IA_MIN_DOUBLE, CGAL_IA_MIN_DOUBLE);
                                     ^

CC-135 crayc++: ERROR File = [...]/CGAL-4.10/include/CGAL/Interval_nt.h, Line = 737
  The namespace "CGAL::internal" has no member "get_static_minimin".
                        scale == 0 ? CGAL_IA_MIN_DOUBLE : scale);
                                     ^
```

## Environment

* Operating system: SUSE Linux Enterprise Server 11 (x86_64)
  * kernel: Linux 3.0.101-0.47.102-default #1 SMP Tue Jun 6 10:51:55 UTC 2017 (ca3a20f) x86_64 x86_64 x86_64 GNU/Linux
* Compiler: Cray cce 8.5.8
* Release or debug mode: Release
* CGAL version: 4.10
* Boost version: 1.61.0
* Other libraries versions if used (Eigen, TBB, etc.): GMP 6.1.2, MPFR 3.1.5

**Comment by mglisse** [comment]
Uh, indeed, the declaration in FPU.h seems to be in the global namespace instead of `CGAL::internal`, this configuration is not tested so we didn't notice. Note that to arrive there, you have CGAL_CFG_NO_LIMITS and CGAL_CFG_DENORMALS_COMPILE_BUG, meaning that your compiler has quite a few issues (or our tests are bad) and it is likely other things will fail anyway.

**Comment by lrineau** [comment]
As far as I can see on [C++ compiler support][1], the Cray compiler version 8.5 should be conformant to C++ (even C++11). The issue seems that the floating point model is not IEEE 754, and CGAL rely on it. Maybe there is a compiler switch to make it conform to IEEE 754?

  [1]: http://en.cppreference.com/w/cpp/compiler_support

@kynan The CGAL project does not have any Cray machine or Cray compiler, and that compiler is not support by CGAL. I see that you work for the FEniCS project. How important is the CGAL support for Cray? Anyway, you will have to help us on that.

**Comment by mglisse** [comment]
Seems that there is an option `-h ieeeconform` (and weaker `-h fp1` or other numbers, but it is possible that only `-h fp0` works, which is equivalent to the ieeeconform option). We could consider adding that in the same place we add `-frounding-math`? In any case, we should move `get_static_minimin` to its intended namespace.

**Comment by lrineau** [comment]
@mglisse, https://github.com/CGAL/cgal/issues/2316#issuecomment-319018027:
> Seems that there is an option `-h fp0` (and weaker `-h fp1` or other numbers, but it is possible that only `-h fp0`works). We could consider adding that in the same place we add `-frounding-math`? In any case, we should move `get_static_minimin` to its intended namespace.

If @kynan or his project help us test the patch, I fully agree to add it the same way we add `-frounding-math`.

**Comment by kynan** [comment]
Sure, happy to test a patch. /cc @wdeconinck

**Comment by mglisse** [comment]
https://github.com/CGAL/cgal-public-dev/commits/cray-glisse
Only the part about -h fp0 is important. I only added it to CXXFLAGS, I don't know if it is also needed for linking.
I moved `get_static_minimin` to the right namespace, but since nothing is including the file where it is defined (except for one testcase 😕 ), that's pretty useless. This whole function is strange, why should it return a (non-const) reference?

**Comment by kynan** [comment]
@mglisse `-h fp0` does indeed do the trick. I needed to also add `-h fPIC` to `CGAL_CXX_FLAGS` to get it to build. Anything else I can do to help you test?

**Comment by kynan** [comment]
Sorry, spoke too soon! I can build @mglisse's branch, but CGAL 4.10 still fails with the very same error. This looks more like a missing include to me?

**Comment by mglisse** [comment]
> I needed to also add -h fPIC to CGAL_CXX_FLAGS to get it to build.

Strange, I would expect cmake to handle that itself. It looks like cmake doesn't know about this flag, you should report it to them.

> I can build @mglisse's branch, but CGAL 4.10 still fails with the very same error.

That's normal, my branch hasn't been merged into 4.10.

> This looks more like a missing include to me?

In header-only mode, there is indeed a missing include, but it should only affect platforms without denormals, so `-h fp0` is supposed to be fine.

**Comment by lrineau** [comment]
@mglisse, will you create a PR against CGAL-4.10-branch?

**Comment by kynan** [comment]
Is there a flag to disable denormals handling in the CMake configuration?

**Comment by mglisse** [comment]
> Is there a flag to disable denormals handling in the CMake configuration?

No. But since CGAL doesn't work if you disable denormals, why would you want to do that?

**Comment by kynan** [comment]
So there's no current workaround for the 4.10 release with Cray? As mentioned, adding `-h fp0` alone didn't do the trick for me.

**Comment by mglisse** [comment]
@kynan your messages are unclear, I was apparently exactly the opposite of what you were saying. `-h fp0` **enables** denormal handling. Did you use it when configuring CGAL-4.10, or only when building your application? How exactly did you specify it?

**Comment by kynan** [comment]
As stated in the issue I cannot build CGAL release 4.10 due to above failure. I understood adding `-h fp0` would cause the header with the missing include to not be required?

**Comment by lrineau** [comment]
I think `<CGAL/FPU.h>` should include `<CGAL/Interval_arithmetic_impl.h>`, at least when `CGAL_CFG_DENORMALS_COMPILE_BUG` is defined.

**Comment by mglisse** [comment]
> As stated in the issue I cannot build CGAL release 4.10 due to above failure. I understood adding `-h fp0` would cause the header with the missing include to not be required?

Yes, that's supposed to be the case. Didn't that work? How did you specify it exactly? What was cmake's output (does it still say you don't have limits?)?

**Comment by kynan** [comment]
I configured with `-DCGAL_CXX_FLAGS="-h fp0 -fPIC"` and the build still fails with
```
CC-135 crayc++: ERROR File = CGAL-4.10/include/CGAL/Interval_nt.h, Line = 185
  The namespace "CGAL::internal" has no member "get_static_minimin".

      return IA(-CGAL_IA_MIN_DOUBLE, CGAL_IA_MIN_DOUBLE);
                 ^

CC-135 crayc++: ERROR File = CGAL-4.10/include/CGAL/Interval_nt.h, Line = 185
  The namespace "CGAL::internal" has no member "get_static_minimin".

      return IA(-CGAL_IA_MIN_DOUBLE, CGAL_IA_MIN_DOUBLE);
                                     ^

CC-135 crayc++: ERROR File = CGAL-4.10/include/CGAL/Interval_nt.h, Line = 737
  The namespace "CGAL::internal" has no member "get_static_minimin".

                        scale == 0 ? CGAL_IA_MIN_DOUBLE : scale);
                                     ^
```

**Comment by mglisse** [comment]
So cmake printed:
> -- Performing Test CGAL_CFG_NO_LIMITS - Failed
or maybe
> -- Performing Test CGAL_CFG_NUMERIC_LIMITS_BUG - Failed
?
That's what needs investigating.

**Comment by kynan** [comment]
Yes to the former:
> -- Performing Test CGAL_CFG_NO_LIMITS - Failed
No to the latter:
> -- Performing Test CGAL_CFG_NUMERIC_LIMITS_BUG - Success

**Comment by mglisse** [comment]
And probably a failure also for CGAL_CFG_DENORMALS_COMPILE_BUG. I am surprised that even with `-h fp0` cray's compiler absolutely refuses to handle denormals...
A workaround for cgal-4.10 will have to be an ugly hack, say declaring `namespace CGAL { namespace internal { double& get_static_minimin(); }}` in your code before including CGAL headers.

**Comment by mglisse** [comment]
> I think <CGAL/FPU.h> should include <CGAL/Interval_arithmetic_impl.h>, at least when CGAL_CFG_DENORMALS_COMPILE_BUG is defined.

That should only be needed/wanted with CGAL_HEADER_ONLY, and get_static_minimin seems to be missing `inline` in that case...

**Comment by kynan** [comment]
Yes:
> -- Performing Test CGAL_CFG_DENORMALS_COMPILE_BUG - Failed

Where do I best put this hack for being able to build CGAL itself? `CGAL/FPU.h`?

**Comment by mglisse** [comment]
Oops, I had forgotten that this was also causing issues while compiling CGAL. Then the easiest is for you to manually apply https://github.com/CGAL/cgal-public-dev/commit/d1e1bff3e25cd37d585dcefd5c1e7c1f9f325cee to the sources.

**Comment by kynan** [comment]
That seems to have done the trick, thanks @mglisse !

**Comment by lrineau** [comment]
Marc, don't you want to create a PR from https://github.com/CGAL/cgal-public-dev/commits/cray-glisse?

I am already ready to publish 4.10.1.

**Comment by mglisse** [comment]
Supposedly the branch now also works in header-only mode. I haven't done any testing at all though. Proper testing using only gcc would involve forcing the tests to fail so we use the same code as cray.

**Comment by lrineau** [comment]
@mglisse Is not there a build farm or something like that, at Inria, that could give us access to a Cray?

Otherwise, we could either:
1. have a gcc platform, in the testsuite, that defines `CGAL_CFG_NO_LIMITS` and `CGAL_CFG_DENORMALS_COMPILE_BUG`, or
2. have a special pull-request, that defines the two macros.

The first solution could test the workaround indefinitely, and the second one would test it only if the PR is merged in `integration`.

You could also test locally, defining the two macros in `CMAKE_CXX_FLAGS` in your local `CMakeCache.txt`.

**Comment by mglisse** [comment]
> @mglisse Is not there a build farm or something like that, at Inria, that could give us access to a Cray?

Hahaha. No.

> You could also test locally, defining the two macros in CMAKE_CXX_FLAGS in your local CMakeCache.txt.

That was my plan, when I can find enough time......

**Comment by lrineau** [comment]
Well... let's not care about `CGAL_HEADER_ONLY` for now. If you create the PR today or tomorrow (against the branch `releases/CGAL-4.11-branch`), there is still a chance it will get merged before CGAL-4.11 is published.

**Comment by afabri** [comment]
@kynan Hi Florian, not many of us have access to a Cray or a compiler for a Cray. I think ideally you find out how to fix that and make a pull request. So at least other CGAL-on-Cray users profit. Or convince your institute to give us access, and pay a day of work to us for finding out for you.

**Comment by afabri** [comment]
@kynan Hi Florian,  did you find any time to look into this, or did you give up and use something else than CGAL?

**Comment by lrineau** [comment]
We wont try to fix that one.
