### ISSUE TITLE
Assertion thrown on specific Triangle_3 Triangle_3 intersection test.

### ISSUE THREAD

**Issue by SteveAuroraLabs3d** [CGAL/cgal#2319]
## Issue Details

A triangle triangle 3D intersection test asserts when a vertex of one lies on the face of the other.

The following error is thrown
**Line 458 intersection_3_1_impl.h
CGAL_precondition(! s1.is_degenerate () && ! s2.is_degenerate () );**
when the following triangles are used:

x, y, z
0.045769477844238279,0.07539492797851563,0.013735383987426759
0.036645412445068359,0.060013595581054686,0.013735383987426759
0.049645965576171874,0.050098735809326174,0.013735383987426759

0.044114555358886719,0.066831237792968748,0.013735383987426759
0.044415161132812499,0.066367233276367191,0.014259093284606934
0.044114555358886719,0.066307533264160154,0.014259093284606934

The intersection is identified as a degenerate segment3 rather thean a Point3 . Then when the segment is checked it is asserted as degenerate.

## Source Code

```
using Kernel = CGAL::Simple_cartesian<double>;
using Tri3 = Kernel::Triangle_3;
using Point3 = Kernel::Point_3;

Tri3 ta(P[0], pa[1], pa[2]);
Tri3 tb(pb[0], pb[1], pb[2]);

Tri3 ta(
	Point3(0.045769477844238279,0.07539492797851563,0.013735383987426759),
	Point3(0.036645412445068359,0.060013595581054686,0.013735383987426759),
	Point3(0.049645965576171874,0.050098735809326174,0.013735383987426759)
);

Tri3 ta(
	Point3(0.044114555358886719,0.066831237792968748,0.013735383987426759),
	Point3(0.044415161132812499,0.066367233276367191,0.014259093284606934),
	Point3(0.044114555358886719,0.066307533264160154,0.014259093284606934)
);

auto intersect = intersection(ta, tb);
```
In Triangle_3_Triangle_3_intersection.h:
```
    Triangle_Line_Inter inter1 = intersection_coplanar(t1,*line,k);
    Triangle_Line_Inter inter2 = intersection_coplanar(t2,*line,k);
```
The type of inter1 & inter2 are Segment3 Where one is actually a Point3.

## Environment
* Ubuntu 17.04 64
* GCC 6.3.0-12ubuntu2 20170406
* DEBUG mode

#define CGAL_VERSION 4.7
#define CGAL_VERSION_NR 1040701000
#define CGAL_SVN_REVISION 99999
#define CGAL_GIT_HASH 8030a2952469e87a91fa016c27d643790a17daa6
CGAL_INTERSECTION_VERSION = 2
#define BOOST_VERSION 106200

**Comment by sloriot** [comment]
You are using a Kernel with inexact constructions. If you replace `CGAL::Simple_cartesian<double>` by `CGAL::Exact_predicates_exact_constructions_kernel` you will no longer get the error.

See this [FAQ entry](http://www.cgal.org/FAQ.html#inexact_NT) for more details.
