### ISSUE TITLE
CGAL_INCLUDE_DIR (ADVANCED) and CGAL_LIBRARIES (ADVANCED) not found

### ISSUE THREAD

**Issue by zhujunpengguizhou** [CGAL/cgal#2327]
-- CMAKE_BUILD_TYPE 
-- CMAKE_BUILD_TYPE 
-- DOXYGEN_MINIMUM_VERSION=1.7
-- SPHINX_MINIMUM_VERSION=1.1
-- POSTGRESQL_MINIMUM_VERSION=9.2.0
-- POSTGIS_MINIMUM_VERSION=2.0.0
-- GNU_CXX_MINIMUM_VERSION=4.6
-- CLANG_CXX_MINIMUM_VERSION=
-- MSVC_CXX_MINIMUM_VERSION=18.0
-- dir='/home/pipelinedb/pgrouting-2.4.1/cmake'
-- POSTGRESQL_PG_CONFIG is /bin/pg_config
-- POSTGRESQL_EXECUTABLE is POSTGRESQL_EXECUTABLE-NOTFOUND
-- POSTGRESQL_VERSION_STRING in FindPostgreSQL.cmake is PostgreSQL 9.5.3
-- POSTGRESQL_INCLUDE_DIR: /home/pipelinedb/pipelinedb/include/pipelinedb/server
-- POSTGRESQL_LIBRARIES: /home/pipelinedb/pipelinedb/lib
-- PGSQL_VERSION=95
-- Boost version: 1.60.0
-- Boost headers were found here: /home/pipelinedb/boost_1_60_0
-- Boost version: 1.60.0
-- Found the following Boost libraries:
--   thread
-- Boost version: 1.60.0
-- Found the following Boost libraries:
--   thread
--   system
-- CGAL_INCLUDE_DIR=CGAL_INCLUDE_DIR-NOTFOUND;/home/pipelinedb/CGAL-4.10
-- CGAL_LIBRARIES=CGAL_LIBRARIES-NOTFOUND;/home/pipelinedb/CGAL-4.10/lib
-- BOOST_THREAD_LIBRARIES=/home/pipelinedb/boost_1_60_0/stage/lib/libboost_thread.so;/home/pipelinedb/boost_1_60_0/stage/lib/libboost_system.so
-- GMP_LIBRARIES=/usr/lib64/libgmp.so
-- Found CGAL: CGAL_INCLUDE_DIR-NOTFOUND;/home/pipelinedb/CGAL-4.10, CGAL_LIBRARIES-NOTFOUND;/home/pipelinedb/CGAL-4.10/lib, /home/pipelinedb/boost_1_60_0/stage/lib/libboost_thread.so;/home/pipelinedb/boost_1_60_0/stage/lib/libboost_system.so, /usr/lib64/libgmp.so
Building the library names
-- Created /home/pipelinedb/pgrouting-2.4.1/build/lib/pgrouting--2.4.1.sql
-- Created /home/pipelinedb/pgrouting-2.4.1/build/lib/pgrouting.control
-- Creating lib/pgrouting--2.4.1.sig
Building the updating files
  -- Created lib/pgrouting--2.0.0--2.4.1.sql
  -- Created lib/pgrouting--2.0.1--2.4.1.sql
  -- Created lib/pgrouting--2.1.0--2.4.1.sql
  -- Created lib/pgrouting--2.2.0--2.4.1.sql
  -- Created lib/pgrouting--2.2.1--2.4.1.sql
  -- Created lib/pgrouting--2.2.2--2.4.1.sql
  -- Created lib/pgrouting--2.2.3--2.4.1.sql
  -- Created lib/pgrouting--2.2.4--2.4.1.sql
  -- Created lib/pgrouting--2.3.0--2.4.1.sql
  -- Created lib/pgrouting--2.3.1--2.4.1.sql
  -- Created lib/pgrouting--2.3.2--2.4.1.sql
  -- Created lib/pgrouting--2.4.0--2.4.1.sql
-- LIBS_TO_INSTALL=
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CGAL_INCLUDE_DIR (ADVANCED)
   used as include directory in directory /home/pipelinedb/pgrouting-2.4.1
   used as include directory in directory /home/pipelinedb/pgrouting-2.4.1
   used as include directory in directory /home/pipelinedb/pgrouting-2.4.1
   used as include directory in directory /home/pipelinedb/pgrouting-2.4.1
   used as include directory in directory /home/pipelinedb/pgrouting-2.4.1
   used as include directory in directory /home/pipelinedb/pgrouting-2.4.1
   used as include directory in directory /home/pipelinedb/pgrouting-2.4.1
   used as include directory in directory /home/pipelinedb/pgrouting-2.4.1
   used as include directory in directory /home/pipelinedb/pgrouting-2.4.1/src/common/src
   used as include directory in directory /home/pipelinedb/pgrouting-2.4.1/src/common/src
   used as include directory in directory /home/pipelinedb/pgrouting-2.4.1/src/dijkstra/src
   used as include directory in directory /home/pipelinedb/pgrouting-2.4.1/src/dijkstra/src
   used as include directory in directory /home/pipelinedb/pgrouting-2.4.1/src/allpairs/src
   used as include directory in directory /home/pipelinedb/pgrouting-2.4.1/src/allpairs/src
   used as include directory in directory /home/pipelinedb/pgrouting-2.4.1/src/astar/src
   used as include directory in directory /home/pipelinedb/pgrouting-2.4.1/src/astar/src
   used as include directory in directory /home/pipelinedb/pgrouting-2.4.1/src/driving_distance/src
   used as include directory in directory /home/pipelinedb/pgrouting-2.4.1/src/driving_distance/src
   used as include directory in directory /home/pipelinedb/pgrouting-2.4.1/src/ksp/src
   used as include directory in directory /home/pipelinedb/pgrouting-2.4.1/src/ksp/src
   used as include directory in directory /home/pipelinedb/pgrouting-2.4.1/src/tsp/src
   used as include directory in directory /home/pipelinedb/pgrouting-2.4.1/src/tsp/src
   used as include directory in directory /home/pipelinedb/pgrouting-2.4.1/src/alpha_shape/src
   used as include directory in directory /home/pipelinedb/pgrouting-2.4.1/src/alpha_shape/src
   used as include directory in directory /home/pipelinedb/pgrouting-2.4.1/src/bd_astar/src
   used as include directory in directory /home/pipelinedb/pgrouting-2.4.1/src/bd_astar/src
   used as include directory in directory /home/pipelinedb/pgrouting-2.4.1/src/bdDijkstra/src
   used as include directory in directory /home/pipelinedb/pgrouting-2.4.1/src/bdDijkstra/src
   used as include directory in directory /home/pipelinedb/pgrouting-2.4.1/src/trsp/src
   used as include directory in directory /home/pipelinedb/pgrouting-2.4.1/src/trsp/src
   used as include directory in directory /home/pipelinedb/pgrouting-2.4.1/src/max_flow/src
   used as include directory in directory /home/pipelinedb/pgrouting-2.4.1/src/max_flow/src
   used as include directory in directory /home/pipelinedb/pgrouting-2.4.1/src/contraction/src
   used as include directory in directory /home/pipelinedb/pgrouting-2.4.1/src/contraction/src
   used as include directory in directory /home/pipelinedb/pgrouting-2.4.1/src/pickDeliver/src
   used as include directory in directory /home/pipelinedb/pgrouting-2.4.1/src/pickDeliver/src
   used as include directory in directory /home/pipelinedb/pgrouting-2.4.1/src/vrp_basic/src
   used as include directory in directory /home/pipelinedb/pgrouting-2.4.1/src/vrp_basic/src
   used as include directory in directory /home/pipelinedb/pgrouting-2.4.1/src/withPoints/src
   used as include directory in directory /home/pipelinedb/pgrouting-2.4.1/src/withPoints/src
CGAL_LIBRARIES (ADVANCED)
    linked by target "pgrouting-2.4" in directory /home/pipelinedb/pgrouting-2.4.1

-- Configuring incomplete, errors occurred!
See also "/home/pipelinedb/pgrouting-2.4.1/build/CMakeFiles/CMakeOutput.log".

And CGAL was installed
-- Up-to-date: /usr/local/lib64/CGAL/CGAL_SetupBoost.cmake
-- Up-to-date: /usr/local/lib64/CGAL/list_of_whitelisted_headers.cmake
-- Up-to-date: /usr/local/lib64/CGAL/FindBLAS.cmake
-- Up-to-date: /usr/local/lib64/CGAL/CGAL_UseBLAS.cmake
-- Up-to-date: /usr/local/lib64/CGAL/CGAL_Macros.cmake
-- Up-to-date: /usr/local/lib64/CGAL/FindLAPACK.cmake
-- Up-to-date: /usr/local/lib64/CGAL/CGAL_UseMKL.cmake
-- Up-to-date: /usr/local/lib64/CGAL/CGAL_UseRS3.cmake
-- Up-to-date: /usr/local/lib64/CGAL/UseESBTL.cmake
-- Up-to-date: /usr/local/lib64/CGAL/FindOpenGL.cmake
-- Up-to-date: /usr/local/lib64/CGAL/FindRS3.cmake
-- Up-to-date: /usr/local/lib64/CGAL/CGAL_UseRS.cmake
-- Up-to-date: /usr/local/lib64/CGAL/list_of_documented_headers.cmake
-- Up-to-date: /usr/local/lib64/CGAL/process_dependencies.cmake
-- Up-to-date: /usr/local/lib64/CGAL/CGAL_GeneratorSpecificSettings.cmake
-- Up-to-date: /usr/local/lib64/CGAL/CGALLibConfig.cmake.in
-- Up-to-date: /usr/local/lib64/CGAL/UseCGAL.cmake
-- Up-to-date: /usr/local/lib64/CGAL/CGALConfigVersion.cmake
-- Installing: /usr/local/lib64/CGAL/CGALConfig.cmake
-- Up-to-date: /usr/local/share/man/man1/cgal_create_cmake_script.1
-- Installing: /usr/local/lib64/libCGAL.so.13.0.0
-- Up-to-date: /usr/local/lib64/libCGAL.so.13
-- Up-to-date: /usr/local/lib64/libCGAL.so
-- Removed runtime path from "/usr/local/lib64/libCGAL.so.13.0.0"
-- Up-to-date: /usr/local/lib64/CGAL/CGALExports.cmake
-- Installing: /usr/local/lib64/CGAL/CGALExports-release.cmake
-- Installing: /usr/local/lib64/CGAL/CGALLibConfig.cmake
-- Installing: /usr/local/lib64/libCGAL_Core.so.13.0.0
-- Up-to-date: /usr/local/lib64/libCGAL_Core.so.13
-- Up-to-date: /usr/local/lib64/libCGAL_Core.so
-- Removed runtime path from "/usr/local/lib64/libCGAL_Core.so.13.0.0"
-- Up-to-date: /usr/local/lib64/CGAL/CGAL_CoreExports.cmake
-- Installing: /usr/local/lib64/CGAL/CGAL_CoreExports-release.cmake
-- Installing: /usr/local/lib64/CGAL/CGAL_CoreLibConfig.cmake
-- Installing: /usr/local/lib64/libCGAL_ImageIO.so.13.0.0
-- Up-to-date: /usr/local/lib64/libCGAL_ImageIO.so.13
-- Up-to-date: /usr/local/lib64/libCGAL_ImageIO.so
-- Removed runtime path from "/usr/local/lib64/libCGAL_ImageIO.so.13.0.0"
-- Up-to-date: /usr/local/lib64/CGAL/CGAL_ImageIOExports.cmake
-- Installing: /usr/local/lib64/CGAL/CGAL_ImageIOExports-release.cmake
-- Installing: /usr/local/lib64/CGAL/CGAL_ImageIOLibConfig.cmake

And ~/.basrc
BOOST_INCLUDE_DIRS="/home/pipelinedb/boost_1_60_0"
BOOST_LIBRARYDIR="/home/pipelinedb/boost_1_60_0/stage/lib"
BOOST_ROOT="/home/pipelinedb/boost_1_60_0"

CGAL_INCLUDE_DIR="/home/pipelinedb/CGAL-4.10"
CGAL_LIBRARIES="/home/pipelinedb/CGAL-4.10/lib"

why pgrouting was not installed?

**Comment by zhujunpengguizhou** [comment]
CGAL version 4.10 and  os centos 7

**Comment by xarthurx** [comment]
@JunpengCode How did you solve it?
