### ISSUE TITLE
Polyhedron demo: Save as

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#2334]
## Issue Details

This is a feature request.

When I want to save a polyhedron it offers me the gocad format.  That will rarely be the first choice. 
Also the directory where I saved should be remebered for the next save as.

**Comment by sgiraudot** [comment]
I agree, I have the same problem with point sets: if all IO plugins are compiled, the default choice is LAS (which is far from being the most common format, I would choose PLY as default which is the closest we have from a standard that can embed properties).

From what I understand, formats are stored alphabetically (by their descriptions), so we do not control the default choice (it's just the first in alphabetical order). One possible hack would be to willingly use a description starting with a letter close to A for the format we want as default, but that's not really clean nor handy.

I don't know if there is another way to control this? Anyway, as @lrineau said he was not satisfied with the way we handle IO in the demo, that can be part of the discussion.

**Comment by afabri** [comment]
@sgiraudot do you know where in the code this happens, or do we have to ask @maxGimeno ?

**Comment by sgiraudot** [comment]
I don't know.

**Comment by lrineau** [comment]
We should add @sloriot in the discussion, because he is the author of the "loaders". Maybe he remembers where that logic can be tweaked in the code.

**Comment by sgiraudot** [comment]
Just a thought on what could be nice (from a plugin dev's point of view): when creating an IO plugin, there could be an attribute/method `priority()` that the user would fill and that the loader would use to sort the plugins. Then, we could just set a priority accordingly to the other existing IO plugins when creating a new one. For example, if I'm making a new IO plugin that's super cool and that should be the default, I'll put a priority higher than everyone else. On the opposite, if I create a very specific plugin for a very obscure format, I would put a low priority.
