### ISSUE TITLE
No matching signal for...

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#234]
```
demo/Segment_Delaunay_graph_2/Segment_voronoi_2
QMetaObject::connectSlotsByName: No matching signal for on_actionSaveConstraints_triggered()
demo/Segment_Delaunay_graph_Linf_2/Segment_voronoi_linf_2
QMetaObject::connectSlotsByName: No matching signal for on_actionSaveConstraints_triggered()
demo/Stream_lines_2/Stream_lines_2
QMetaObject::connectSlotsByName: No matching signal for on_actionGenerate_triggered()
```

**Comment by philaris** [comment]
For Segment_voronoi_linf_2, I just adapted Segment_voronoi_2, which seems to have the same issue. I think neither demo (Segment_voronoi_2, Segment_voronoi_linf_2) supports saving any constraints. My guess is that the Segment_voronoi_2 demo was adapted from a demo with more capabilities. However, I do not know much about graphical user interfaces or Qt, so somebody more knowledgeable should help and suggest if and how something should be removed.
