### ISSUE TITLE
Proper installation of FindCGAL.cmake

### ISSUE THREAD

**Issue by rlalik** [CGAL/cgal#2344]
## Issue Details

Installing of FindCGAL.cmake using custom target doesn't work for me. It will also not work in a system using sandboxes to install package (e.g. Gentoo) since it tries to install outside sandbox). There is a better way of installing the file. Additionally all the Find*.cmake modules should be installed in CMAKE_ROOT not in a custom destination. below is my proposition of changes in CMakeFiles.txt. I made it for 4.10 but should be easily convertable to current git structure.

## Source Code

Patch for CMakeLists.txt for 4.10, should be applied for Installation/CMakeLists.txt in git tree

```patch
--- CMakeLists.txt 2017-08-11 14:23:51.220889932 +0200
+++ CMakeLists.txt 2017-08-11 15:09:54.982021108 +0200
@@ -880,9 +880,6 @@
   ${CMAKE_CURRENT_SOURCE_DIR}/scripts/cgal_create_cmake_script_with_options)
 install(PROGRAMS ${scripts} DESTINATION ${CGAL_INSTALL_BIN_DIR})
 
-install(DIRECTORY ${CGAL_MODULES_REL_DIR}/                DESTINATION ${CGAL_INSTALL_CMAKE_DIR} )
-install(FILES     ${CGAL_MODULES_REL_DIR}/UseCGAL.cmake   DESTINATION ${CGAL_INSTALL_CMAKE_DIR} )
-
 if ( GMP_IN_AUXILIARY )
   install(DIRECTORY auxiliary/gmp/include/ DESTINATION ${CGAL_INSTALL_INC_DIR} )
   install(DIRECTORY auxiliary/gmp/lib/     DESTINATION ${CGAL_INSTALL_LIB_DIR} )
@@ -914,9 +911,8 @@
 
 if ( NOT "${CMAKE_ROOT}" STREQUAL "" )
   if ( EXISTS ${CMAKE_ROOT}/Modules )
-    add_custom_target( install_FindCGAL
-                      COMMAND ${CMAKE_COMMAND} -E copy ${CGAL_MODULES_DIR}/FindCGAL.cmake ${CMAKE_ROOT}/Modules
-                    ) 
+    install(DIRECTORY ${CGAL_MODULES_DIR}/ DESTINATION $ENV{DESTDIR}${CMAKE_ROOT}/Modules PATTERN "*.cmake")
+    install(FILES ${CGAL_MODULES_DIR}/test_MPFI.cpp DESTINATION $ENV{DESTDIR}${CMAKE_ROOT}/Modules)
   endif()
 endif()
```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Gentoo
* Compiler:
* Release or debug mode:
* Specific flags used (if any):
* CGAL version: 4.10
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by lrineau** [comment]
I wonder why we still have that file `FindCGAL.cmake`. CGAL uses the Config mode of the `find_package` command. All what it does is to display a nicer message to the user, but only *if CMake managed to find `FindCGAL.cmake` but not `CGALConfig.cmake`.

I recommend that we remove `FindCGAL.cmake` completely.

**Comment by lrineau** [comment]
The file `FindCGAL/cmake` has been removed from the `master` branch of CGAL, by #2375.
