### ISSUE TITLE
Documentation modifications highlighted in release

### ISSUE THREAD

**Issue by imiordanov** [CGAL/cgal#2346]
## Issue Details

The CGAL documentation has been modified to account for the [small feature](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Add_function_insert_in_hole_to_Triangulation_data_structure_2) that introduced the function insert_in_hole() to TDS_2. Online, the documentation for TDS_2 [shows the modification highlighted](http://doc.cgal.org/latest/TDS_2/classTriangulationDataStructure__2.html#a7e1be0c88bbda220a8b9b67d48f77c52).

I was the one who submitted the small feature, so I'm not sure if I missed some step during the process. If I should take the steps to correct this issue, I will do so as soon as possible.

## Environment

* Online documentation

**Comment by afabri** [comment]
I guess you have to remove the ` /************* START OF MODIFICATIONS ***************/`

**Comment by imiordanov** [comment]
Sure, the fix itself is pretty easy: it suffices to remove the macros `\cgalModifBegin` and `\cgalModifEnd`. 
However, I'm not sure how to proceed now that the branch in which I did the small feature doesn't exist anymore. So I opened the issue to point out the problem, and ask for suggestions...

**Comment by MaelRL** [comment]
It's only a small doc fix, so you can simply create a new branch in your cgal repository (no need to put it in the INRIA/cgal-public-dev repos) and open a new pull request.

Since it was integrated in 4.10, the PR should be opened with respect to the 4.10 branch (that is: new pull request > base for: CGAL/cgal > base: release/CGAL-4.10 etc.).

**Comment by imiordanov** [comment]
OK, thank you!
I don't seem to be able to assign the issue to myself, but I will commit the fix within the day.
