### ISSUE TITLE
Picking of items randomly working

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#237]
If you have several polyhedron items in the polyhedron demo, pressing the left mouse button while holding the Shift key will select the polyhedron item under the mouse.
This no longer works correctly.

cc @maxGimeno

**Comment by maxGimeno** [comment]
Fixed in CGAL/cgal-public-dev @69fd6e1266f9afb04644a2f21f5370583f540c6d

**Comment by lrineau** [comment]
I confirm the bug is fixed.
