### ISSUE TITLE
Hexahedral Mesh Extraction

### ISSUE THREAD

**Issue by earthling2304** [CGAL/cgal#2376]
## Project Summary
Hexahedral meshing has been proven to be significantly faster in the solving of most partial differential equations and other complicated problems for physical simulations, for two reasons: the number of cells is lower by about 10-25%, as compared to tetrahedral meshing, and hexahedral cells approximate the frame fields more accurately. But hex-meshing is a hard problem and is often done by parametrizing tetrahedral meshes and extracting hexahedral meshes using certain heuristic rules. The algorithm to be implemented is delineated in the paper by Lyon et al - 'HexEx: Robust Hexahedral Mesh Extraction'. My work was to incorporate the algorithm to create hexahedral meshes using combinatorial maps package in CGAL.

The algorithm assumes a parametrization for tetrahedral meshes as input. A dummy parametrization was used to test the algorithm, this is yet to be tested with parametrizations more faithful to the original topology of the input object, such as [CubeCover](http://www.mi.fu-berlin.de/en/math/groups/ag-geom/publications/db/2011_Nieser-Reitebuch-Polthier_CubeCover.pdf).  The discrepancies with dummy parametrization was unforeseen and implementing a good method for parametrization of tetrahedral meshes is yet to be done.

[Documentation and future work](https://docs.google.com/document/d/1Csd8-aKrFbMXecQ_2Hcf2FkdewuE8IpfpP7P5CdC_xI/edit?usp=sharing)

The work was done in the branch: https://github.com/CGAL/cgal-public-dev/tree/gsoc-2017-HexEx-vasudha.

## Commits
https://github.com/CGAL/cgal-public-dev/commit/7b39029 minor changes -  final
https://github.com/CGAL/cgal-public-dev/commit/2cf523e to visualise parametrized mesh
https://github.com/CGAL/cgal-public-dev/commit/6716378 conditions to check creation of hexahedra
https://github.com/CGAL/cgal-public-dev/commit/214b81d more minor changes
https://github.com/CGAL/cgal-public-dev/commit/9b29e74 small changes
https://github.com/CGAL/cgal-public-dev/commit/72a7530 commented frame_field.h
https://github.com/CGAL/cgal-public-dev/commit/0ef7b43 saving mesh in results
https://github.com/CGAL/cgal-public-dev/commit/f52e999 adding results-5
https://github.com/CGAL/cgal-public-dev/commit/424ede5 adding results-4
https://github.com/CGAL/cgal-public-dev/commit/1438711 adding results-3
https://github.com/CGAL/cgal-public-dev/commit/170e0ef adding results-2
https://github.com/CGAL/cgal-public-dev/commit/681900d Merge branch 'gsoc-2017-HexEx-vasudha' of github.com:CGAL/cgal-public-dev into gsoc-2017-HexEx-vasudha
https://github.com/CGAL/cgal-public-dev/commit/b781bcd minor changes
https://github.com/CGAL/cgal-public-dev/commit/c504a7e adding results-1
https://github.com/CGAL/cgal-public-dev/commit/f52319a Two small corrections
https://github.com/CGAL/cgal-public-dev/commit/9e04ada hexes sewn correctly
https://github.com/CGAL/cgal-public-dev/commit/c4a55a2 Add a viewer for GMap
https://github.com/CGAL/cgal-public-dev/commit/189d712 cleaning code
https://github.com/CGAL/cgal-public-dev/commit/c4c0371 modularising code for use
https://github.com/CGAL/cgal-public-dev/commit/787aed9 information about the tests
https://github.com/CGAL/cgal-public-dev/commit/53331eb test cases added in tests/ to directly use the parametrized tet mesh as input
https://github.com/CGAL/cgal-public-dev/commit/74f3fc1 works- saving parametrization
https://github.com/CGAL/cgal-public-dev/commit/7d206d8 adding parametrization as info
https://github.com/CGAL/cgal-public-dev/commit/6aa210f postprocessing added
https://github.com/CGAL/cgal-public-dev/commit/7cc0976 post_processing flip detection
https://github.com/CGAL/cgal-public-dev/commit/b378153 testing for inconsistencies
https://github.com/CGAL/cgal-public-dev/commit/abd9de5 using combinatorial maps, till connection extraction- seems to work correctly
https://github.com/CGAL/cgal-public-dev/commit/957dddc Update test2 to display map info
https://github.com/CGAL/cgal-public-dev/commit/c2b2ed4 testing for sew-3
https://github.com/CGAL/cgal-public-dev/commit/a6538ca test for sewing
https://github.com/CGAL/cgal-public-dev/commit/167db08 Merge branch 'gsoc-2017-HexEx-vasudha' of github.com:CGAL/cgal-public-dev into gsoc-2017-HexEx-vasudha
https://github.com/CGAL/cgal-public-dev/commit/0f1b9f7 Bug fix in triangulation to lcc
https://github.com/CGAL/cgal-public-dev/commit/00d9b44 connection extraction- Using output_points to map an integer grid point to a single point in hex mesh domain to prevent ov
https://github.com/CGAL/cgal-public-dev/commit/324edcd to prevent overlapping hexes- using a single parametrization per point, according to the location with respect to input te
https://github.com/CGAL/cgal-public-dev/commit/de86377 sewing the hexes together
https://github.com/CGAL/cgal-public-dev/commit/3c758ee with parametrized_LCC loaded as input
https://github.com/CGAL/cgal-public-dev/commit/ce9da55 storing hex handles as hash map- before fully implementing
https://github.com/CGAL/cgal-public-dev/commit/be45adf removing from lfs
https://github.com/CGAL/cgal-public-dev/commit/b0f9c8c commit without lfs
https://github.com/CGAL/cgal-public-dev/commit/b195629 handling singularities
https://github.com/CGAL/cgal-public-dev/commit/cfcf573 without lfs commit
https://github.com/CGAL/cgal-public-dev/commit/2daa8bd sanitization with singularity check
https://github.com/CGAL/cgal-public-dev/commit/27e8ddc with sanitize
https://github.com/CGAL/cgal-public-dev/commit/2d4d9d6 new commit with lfs
https://github.com/CGAL/cgal-public-dev/commit/1edc448 Add one example (which works) for save and load of a gmap.
https://github.com/CGAL/cgal-public-dev/commit/39c64f3 interior vertex attributes identified and added to LCC. Delay is caused by triple nested loop on line 42 in geometry_extra
https://github.com/CGAL/cgal-public-dev/commit/6ed3a69 fixed the problems with does_intersect() taking too long, and arguments for make_hexahedron() were modified. Considerable 
https://github.com/CGAL/cgal-public-dev/commit/fc3b58a added geometry extarction and dart extraction in a single function dart_extraction(). Using Tetrahedral_3::has_on_bounded_
https://github.com/CGAL/cgal-public-dev/commit/c364709 loading and saving lcc using >> and <<
https://github.com/CGAL/cgal-public-dev/commit/02d957f temporary changes
https://github.com/CGAL/cgal-public-dev/commit/b257e76 testing the para matrices- small edits
https://github.com/CGAL/cgal-public-dev/commit/5b2116b testing the para matrices
https://github.com/CGAL/cgal-public-dev/commit/318494a parametrization matrix in g
https://github.com/CGAL/cgal-public-dev/commit/e9de916 each tet has an index
https://github.com/CGAL/cgal-public-dev/commit/9ecb375 Parametrization and tetrahedral mesh stored in mesh/, changing the structure used for transition functions
https://github.com/CGAL/cgal-public-dev/commit/d638517 euler_angles.txt
https://github.com/CGAL/cgal-public-dev/commit/d876792 debugged frame field
https://github.com/CGAL/cgal-public-dev/commit/5e56282 added closest_frame fucntion
https://github.com/CGAL/cgal-public-dev/commit/b1e54f0 add_smoothing_terms function added, changes to Edge_handle and sorting of vertices according to boundary/not
https://github.com/CGAL/cgal-public-dev/commit/ca8e5f2 calculations for rotation matrices
https://github.com/CGAL/cgal-public-dev/commit/aeae678 adding rotation matrix
https://github.com/CGAL/cgal-public-dev/commit/de2cbd1 updated the function add_local_optim_constraints
https://github.com/CGAL/cgal-public-dev/commit/19a32ff added add_local_optim_constraints
https://github.com/CGAL/cgal-public-dev/commit/1a6ec2d add_normal_constraints function added
https://github.com/CGAL/cgal-public-dev/commit/f080d8b geomextr modified, adding frame fields
https://github.com/CGAL/cgal-public-dev/commit/b02ac0e geometry extraction added, need to add integer grid map to be able to test
https://github.com/CGAL/cgal-public-dev/commit/00c7a3b more updates
https://github.com/CGAL/cgal-public-dev/commit/71ddaf6 updates in sanitization
https://github.com/CGAL/cgal-public-dev/commit/f7bfb1c dart handle to face handle map
https://github.com/CGAL/cgal-public-dev/commit/94d4965 modified transition functions
https://github.com/CGAL/cgal-public-dev/commit/a98433d added map for transition functions
https://github.com/CGAL/cgal-public-dev/commit/b465565 Merge branch 'gsoc-2017-HexEx-vasudha' of github.com:CGAL/cgal-public-dev into gsoc-2017-HexEx-vasudha
https://github.com/CGAL/cgal-public-dev/commit/34a0da5 before testing
https://github.com/CGAL/cgal-public-dev/commit/3b363f8 Bug fix in triangulation3 to lcc
https://github.com/CGAL/cgal-public-dev/commit/64e8cd4 need to add a few things to sanitization.h, but committing the changes for the day
https://github.com/CGAL/cgal-public-dev/commit/ca7ed2f Remove output file from git repo
https://github.com/CGAL/cgal-public-dev/commit/1133244 Remove exec from git repo
https://github.com/CGAL/cgal-public-dev/commit/f9ccf62 Bug fix plus re-add the possibility to use command line
https://github.com/CGAL/cgal-public-dev/commit/09987fd Use const ref in order to avoid copy of GMap at each function call git add CMakeLists.txt Half_face_and_transition.h func.
https://github.com/CGAL/cgal-public-dev/commit/aea29f6 fixed getting the name of the file correctly
https://github.com/CGAL/cgal-public-dev/commit/bda600d minor changes
https://github.com/CGAL/cgal-public-dev/commit/ae3a954 Merge branch 'gsoc-2017-HexEx-vasudha' of github.com:CGAL/cgal-public-dev into gsoc-2017-HexEx-vasudha
https://github.com/CGAL/cgal-public-dev/commit/cdce758 sanitization-small changes
https://github.com/CGAL/cgal-public-dev/commit/975379e Bugfix in copy for GMap.
https://github.com/CGAL/cgal-public-dev/commit/39d1985 Debug code
https://github.com/CGAL/cgal-public-dev/commit/83295b2 throws errors with generalized maps
https://github.com/CGAL/cgal-public-dev/commit/f8dfa5c different headers
https://github.com/CGAL/cgal-public-dev/commit/87c4a26 extract_transition_function updates
https://github.com/CGAL/cgal-public-dev/commit/522d65c more mild changes
https://github.com/CGAL/cgal-public-dev/commit/8429a81 few changes- still needs debugging
https://github.com/CGAL/cgal-public-dev/commit/dea5b4b added structure to store each face with transitions
https://github.com/CGAL/cgal-public-dev/commit/324c556 added transition function extraction- need to test and refine the code
https://github.com/CGAL/cgal-public-dev/commit/df20b17 minor
https://github.com/CGAL/cgal-public-dev/commit/2de6f6a minor
https://github.com/CGAL/cgal-public-dev/commit/9244919 HexExtr header added
https://github.com/CGAL/cgal-public-dev/commit/f8640d1 Add version that works without c++11
https://github.com/CGAL/cgal-public-dev/commit/b0b4d46 Merge branch 'gsoc-2017-HexEx-vasudha' of github.com:CGAL/cgal-public-dev into gsoc-2017-HexEx-vasudha
https://github.com/CGAL/cgal-public-dev/commit/3704e1a Allow to use or not the viewer for HexEx; export only the cells in the complex.
https://github.com/CGAL/cgal-public-dev/commit/9e11389 Add an option to select some cells when importing from a T3 triangulation.
https://github.com/CGAL/cgal-public-dev/commit/6a036df minor changes
https://github.com/CGAL/cgal-public-dev/commit/8b414c2 triangulation exported as tri.off
https://github.com/CGAL/cgal-public-dev/commit/ed10141 updated CMake
https://github.com/CGAL/cgal-public-dev/commit/d829f5b Storing triangulation in LCC
https://github.com/CGAL/cgal-public-dev/commit/092eab1 Storing triangulation in LCC

**Comment by citystrawman** [comment]
Thank you. BTW my question is: does cgal support hexahedron? (I am new to cgal and I also want to use cgal to generate hexahedron)

**Comment by sloriot** [comment]
There is no hexahedron mesh generator in CGAL as of today.

**Comment by gdamiand** [comment]
Hexahedra are supported in CGAL through the linear cell complex data structure. But indeed there is not (yet) hexahedron mesh generator in CGAL.

You can have a look to this project (based on cgal lcc) https://gitlab.liris.cnrs.fr/gdamiand/3d-query-replace/.
