### ISSUE TITLE
0xC0000005 in Constrained_triangulation_2

### ISSUE THREAD

**Issue by toodef** [CGAL/cgal#2382]
## Issue Details
I cant't make constrained triangulation becouse CGAL failed with 0xC0000005. 

The error traceback:

1. `Constrained_triangulation_2<Gt,Tds,Itag>::insert_constraint(Vertex_handle  vaa, Vertex_handle vbb)`
The input values are: (vaa->point(): 3550 228; vbb->point(): 3582 174)
2.  `insert_constraint(vaa,vi);`
The input values are: (vaa->point(): 3550 228; v-->point(): 3575.24 185.408)
3. `find_intersected_faces( vaa, vbb, intersected_faces, conflict_boundary_ab, conflict_boundary_ba, vi);`
4. `++current_face;`
5. `increment();`

## Source Code
The source code, that i used, seems like:
```
typedef CGAL::Exact_predicates_inexact_constructions_kernel K;
typedef CGAL::Exact_intersections_tag Itag;
typedef CGAL::Constrained_triangulation_2<K, CGAL::Default, Itag> CDT;

std::vector<std::pair<CDT::Point, CDT::Point>> cdt_lines;

for (auto line: lines)
    cdt_lines.push_back(std::make_pair(CDT::Point(line[0][0], line[0][1]), CDT::Point(line[1][0], line[1][1])));

CDT cdt(cdt_lines.begin(), cdt_lines.end());
```
## Environment

* Operating system (Windows 10 64 bits):
* Compiler: cl.exe
* Release mode
* CGAL version: 4.10
* Boost version: 1.63
* Other libraries: Eigen 3.2.4

**Comment by MaelRL** [comment]
According to the [documentation](https://doc.cgal.org/latest/Triangulation_2/classCGAL_1_1Constrained__triangulation__2.html), the tag `Exact_intersections_tag` is meant to be used in conjunction with an exact arithmetic type, but you are using the kernel:`CGAL::Exact_predicates_inexact_constructions_kernel`.

Do you still encounter this behaviour if you use CGAL::Exact_predicates_exact_constructions_kernel` ? 
If so, please provide the input data.

**Comment by toodef** [comment]
My new code looks like:
```
typedef CGAL::Exact_predicates_exact_constructions_kernel K;
typedef CGAL::Exact_intersections_tag Itag;
typedef CGAL::Constrained_triangulation_2<K, CGAL::Default, Itag> CDT;

std::vector<std::pair<CDT::Point, CDT::Point>> cdt_lines;

for (auto line: lines)
    cdt_lines.push_back(std::make_pair(CDT::Point((double)line[0][0], (double)line[0][1]), CDT::Point((double)line[1][0], (double)line[1][1])));

CDT cdt(cdt_lines.begin(), cdt_lines.end());
```

Is i'm correctly understand you? Using of `Constrained_triangulation_plus_2` also doesn't solve problem.

The lines that i get in `insert_constraint` is contains [there](https://github.com/CGAL/cgal/files/1257011/lines.txt).

This is how i store lines:
```
std::ofstream out("lines.txt");
for ( ; it != last; it++) {
    out << (*it).first << " " << (*it).second << std::endl;
    insert_constraint((*it).first, (*it).second);
}
```

The error traceback is changed. Now i get error from:
1. `Constrained_triangulation_2<Gt,Tds,Itag>::insert_constraint(Vertex_handle  vaa, Vertex_handle vbb)`
2. `Triangulation_2<Gt, Tds>::includes_edge(Vertex_handle va, Vertex_handle vb, Vertex_handle & vbb, Face_handle& fr, int & i) const`
3. `orient = orientation(va->point(), vb->point(), v->point());`
where: va->point() is (1879.64 14.1818), vb->point() is (1886 16), v->point() is (1879 14)

**Comment by toodef** [comment]
Sorry, that's my mistake. I didn't notice, that libgmp-10.dll loads from another directory.
