### ISSUE TITLE
CGAL 4.10 compilation failures with Intel 17

### ISSUE THREAD

**Issue by kynan** [CGAL/cgal#2384]
## Issue Details

Building CGAL release 4.10 using Intel 17 compilers fails as follows:
```
[ 16%] Building CXX object src/CGAL/CMakeFiles/CGAL.dir/all_files.cpp.o
In file included from [...]/CGAL-4.10/include/CGAL/Kernel/global_functions.h(31),
                 from [...]/CGAL-4.10/include/CGAL/Cartesian/Cartesian_base.h(30),
                 from [...]/CGAL-4.10/include/CGAL/Simple_cartesian.h(28),
                 from [...]/CGAL-4.10/include/CGAL/Bbox_2_Line_2_intersection_impl.h(31),
                 from [...]/CGAL-4.10/src/CGAL/Bbox_2_intersections.cpp(28),
                 from [...]/CGAL-4.10/build/src/CGAL/all_files.cpp(1):
[...]/CGAL-4.10/include/CGAL/Kernel/global_functions_2.h(362): error: invalid argument to attribute "deprecated"
  CGAL_DEPRECATED_MSG("This function is deprecated. CGAL::compare_slope() should be used instead")
  ^

In file included from [...]/CGAL-4.10/include/CGAL/Kernel/global_functions.h(31),
                 from [...]/CGAL-4.10/include/CGAL/Cartesian/Cartesian_base.h(30),
                 from [...]/CGAL-4.10/include/CGAL/Simple_cartesian.h(28),
                 from [...]/CGAL-4.10/include/CGAL/Bbox_2_Line_2_intersection_impl.h(31),
                 from [...]/CGAL-4.10/src/CGAL/Bbox_2_intersections.cpp(28),
                 from [...]/CGAL-4.10/build/src/CGAL/all_files.cpp(1):
[...]/CGAL-4.10/include/CGAL/Kernel/global_functions_2.h(372): error: invalid argument to attribute "deprecated"
  CGAL_DEPRECATED_MSG("This function is deprecated. CGAL::compare_slope() should be used instead")
  ^
```

## Environment

* Operating system: SUSE Linux Enterprise Server 11 (x86_64)
  * kernel: Linux 3.0.101-0.47.102-default #1 SMP Tue Jun 6 10:51:55 UTC 2017 (ca3a20f) x86_64 x86_64 x86_64 GNU/Linux
* Compiler: Intel 17.0.3.20170404
* Release or debug mode: Release
* CGAL version: 4.10
* Boost version: 1.61.0
* Other libraries versions if used (Eigen, TBB, etc.): GMP 6.1.2, MPFR 3.1.5

**Comment by lrineau** [comment]
That is strange. Last version of the CGAL-4.10.x branch was tested rather successfully:
https://cgal.geometryfactory.com/CGAL/testsuite/results-4.10.1-I-205.shtml

**Comment by lrineau** [comment]
Well, our tests were done with the 2017 *update 4* version of the compiler (Version 17.0.4.196 Build 20170411), while yours is with the *update 3* (17.0.3.20170404). That may explain the difference.

**Comment by kynan** [comment]
Am I understanding correctly that it seems to be [ending up with this definition](https://github.com/CGAL/cgal/blob/releases/CGAL-4.10/Installation/include/CGAL/config.h#L472) of `CGAL_DEPRECATED_MSG`?

**Comment by lrineau** [comment]
@kynan Can you try again with the *update 4* of the Intel Compiler 2017?

**Comment by kynan** [comment]
We don't have 17.0.4 unfortunately. I can confirm that it builds fine when I configure with `-DCGAL_CXX_FLAGS="-DCGAL_NO_DEPRECATION_WARNINGS=1"`. For the moment I can live with that.

**Comment by lrineau** [comment]
I have managed to compile both CGAL `master` and CGAL-4.10 with Intel Compiler 17.0.3, on Linux (Fedora 26), and it worked.

You will have to tell us more how to reproduce the build failure.

**Comment by kynan** [comment]
Do you have a maintainers email I could send the CMake cache file to? Or anything else that would be of use?

**Comment by lrineau** [comment]
Use my CGAL address:  `laurent.rineau`  with `@` and the domain `cgal.org`.
