### ISSUE TITLE
Polyhedron demo: minor feature requests

### ISSUE THREAD

**Issue by MaelRL** [CGAL/cgal#2390]
@maxGimeno, please find below a bunch of feature requests / bug reports for the polyhedron demo. Thanks!

* It would be nice to be able to reload all selected items.
* More generally, right click should apply -- if possible -- the desired action  (e.g. set colors, set flat/edge/etc., ...) to all selected items, not just whichever is under the cursor.
* ctrl-R / F5 as shortcut to reload items ?
* Some better management of many small items would be nice: handling 100 items which all contain a single segment is very slow.
* It would be helpful to have the possibility to visualize the canonical axes and the origin; similarly, to be able to draw a (xOy) grid (see medit shortcuts 'A' and 'G') through the origin (same thing as the cut plane, without cutting) 
* The color preview is rather unfaithful to the final result. Maybe an option to disable whichever lighting changes the colors so much so that, for example, the white color actually produces white and not dark grey (especially true when `draw two side` is unselected). 
* Clicking a point (loaded from a `.xyz)` with ctrl-click should give the position of the point, not the position of w/e sub-part of the drawn square that represents the point I am clicking (something like that should exist in the selection plugin, I guess).

Minor bugs:
* View > Dock windows > Some windows are duplicated ?
* On the slider for point size, the first click seems bugged (it just closes the slider) and one must first slide before clicking.

**Comment by MaelRL** [comment]
Some additional minor stuff in the right click menu of an item:

- `Zoom to index` should not prompt the error when "cancel" is used
- `Display [vertices/faces/etc] IDs` are marked as selected when some (e.g. OFF) item is loaded, but no items are shown. Requires to deselect and reselect for the IDs to show up.

**Comment by MaelRL** [comment]
Similar to the last item above: when an item is refreshed, indices disappear (as they should), but `Right click > Display all IDs` is not switched to `off` (and so you have to click twice to enable them on the new item).

**Comment by MaelRL** [comment]
If you choose to show tetrahedra on a loaded `.mesh`, you cannot create a Bbox of the mesh anymore (which should probably be called `Create Mesh Bbox` rather than `Create Bbox Mesh` (?)).

**Comment by MaelRL** [comment]
After an item has been reloaded, the cut plane cannot be moved without deselecting and reselecting the item.

**Comment by MaelRL** [comment]
- When "Saving as", the file type `OFF files to Surface_mesh` doesn't really make sense. I guess it's a remnant from reading.
- Surface mesh items have `number of faces` while Polyhedron items have `number of facets`
- Polyhedron items have an extra field `number of isolated vertices` that is not mirrored for surface mesh items.

**Comment by MaelRL** [comment]
I feel like the cut plane's `Show Tetrahedra` should be enabled by default when generating a 3D mesh.

**Comment by MaelRL** [comment]
Also, as bug: you can't save a c3t3 item if `Show  Tetrahedra` is enabled, you've got to deselect it first.

**Comment by MaelRL** [comment]
Bug: refreshing a point set resets the point size.

**Comment by MaelRL** [comment]
@maxGimeno Feel free to edit and strike items in this issue directly.

**Comment by maxGimeno** [comment]
@MaelRL I'm pretty sure only you can do that. I'd rather keep my PR updated :)

**Comment by lrineau** [comment]
@MaelRL, have a look at #2759. Maybe there are remaining items that are not implemented. You should create a new issues to discuss them with @maxGimeno.
