### ISSUE TITLE
Mysterious button

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#2395]
![screenshot from 2017-09-06 13-08-47](https://user-images.githubusercontent.com/1224632/30108937-a6aa16ea-9304-11e7-8920-92d5764dbbfe.png)
In the selection widget, what is `PushButton`?

**Comment by sgiraudot** [comment]
Oops, probably a default button I added by mistake when I reorganized the plugin… I'll fix it.

**Comment by sgiraudot** [comment]
(Actually it did not come from #2044, see the screenshots, but from f1a3ea95a386b246fd715af82cf5527d07f3bd90. I still fixed it.)
