### ISSUE TITLE
clean collapse_edge and surface mesh simplification docs

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#2397]
Copied from cgal-discuss:

Hello,
here
<https://doc.cgal.org/latest/Surface_mesh_simplification/classEdgeCollapsableSurfaceMesh.html>  
it is actually described what results the collapse_edge function produces,
therefore I believe it would be helpful that at least this explanation is
copied (if not moved) to the  collapse_edge doc
<https://doc.cgal.org/latest/BGL/group__PkgBGLEulerOperations.html#gab97c0d071b0d768e22a4fc171a8ca664> 
.

Best Regards,
IM

I even think that the doc is not up-to-date as IIRC @maxGimeno did a modification so that the same vertex is always kept. The doc of Surface mesh simplification must also be cleaned up.

**Comment by maxGimeno** [comment]
I did that modification, but only in a local branch. Never pushed it.
