### ISSUE TITLE
Linking boost to CGAL on Windows

### ISSUE THREAD

**Issue by thijsvanlankveld** [CGAL/cgal#24]
I think the linking process of boost should be fixed, at least on Windows using Visual Studio when working from the master branch.

I've just upgraded to boost 1.57.0, prompting me to run CMake again for CGAL. This led to two issues:
Firstly, CMake cannot correctly find boost even though I have correctly set all relevant variables. I have set the following environment variables (partially redundantly):
* BOOST_ROOT = [...]\boost-1_57_0
* BOOST_DIR = %BOOST_ROOT%
* BOOST_INCLUDEDIR = %BOOST_ROOT%\
* BOOST_LIBRARYDIR = %BOOST_ROOT%\lib64
I can get some of the required variables in CMake to be set automatically by manually setting BOOST_ROOT in CMake to the same value it already has.

Secondly, after CMake generates the solution files, when trying to run an application requiring boost, it cannot find the boost_threads[...] library, even though this lib is in BOOST_LIBRARYDIR, which is set in the PATH environment variable. I can probably fix this by manually setting the directories used by the project.

Both of these issues can be fixed by manual interaction, but this shouldn't be necessary with a build system like CMake and the correct CMakeLists.

**Comment by lrineau** [comment]
@Thijs, can you open CMake again, and add an entry `Boost_DEBUG` of type `BOOL` and set it to `TRUE`. Then remove your Boost variables, and retry configure? I would like to see the output.

**Comment by thijsvanlankveld** [comment]
@lrineau never mind; there was a typo in the BOOST_ROOT variable; after fixing the typo it works again.
