### ISSUE TITLE
libQGLViewer drawing of text is broken

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#240]
The drawing of text is fine if no item is displayed.
![cgal-geometryfactory-com_load1](https://cloud.githubusercontent.com/assets/5746675/9057441/4e1544d8-3a9a-11e5-9ded-22d5ac91b046.png)
but once there is a Polyhedron item drawn, the drawing is corrupted:
![cgal-geometryfactory-com_load1](https://cloud.githubusercontent.com/assets/5746675/9057410/22bea9a0-3a9a-11e5-8f89-fc44c9052e97.png)

I do not schedule that issue for 4.7-beta.

**Comment by lrineau** [comment]
cc @maxGimeno

**Comment by sloriot** [comment]
Fixed by CGAL/cga-public-dev@9257bf2c
