### ISSUE TITLE
Subdivision in the demo

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#2403]
When calling a subdivision method, it would be nice to have a dialog box popping up asking for the number of iterations (it is important for sqrt_3, otherwise the boundary will never be refined since at least 2 iterations are required).

**Comment by sloriot** [comment]
@maxGimeno and @lrineau : It would be nice to have it for 4.11 as Sqrt3 subdivision is introduced in 4.11

**Comment by lrineau** [comment]
Fixed by #2405.
