### ISSUE TITLE
Add load LCC in Polyhedron demo

### ISSUE THREAD

**Issue by gdamiand** [CGAL/cgal#2411]
## Issue Details

I would like to be able to load and visualize an LCC in the Polyhedron demo.

I also would like to have two options to enable/disable random color for faces and volumes.

The option random color for faces can also be interesting for other data-structures such as surface mesh, polyhedron.

The option random color for volumes can also be interesting for tds3.

**Comment by lrineau** [comment]
We have already have in the demo several item types that are multicolor. The colors are not random, but deterministically chosen. The porting of LCC items will benefit from the same tools.

Currently Maxime and I have started a major reorganization of the demo, and the porting of LCC to the demo will wait until the reorganization is achieved. It should be fine at the next CGAL developers meeting.
