### ISSUE TITLE
Test /permissive- with Visual Studio 2017

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#2414]
Recent versions of Visual C++ 2017 have a new flag to enable a better conformance to the C++ norm: `/permissive-`.

https://blogs.msdn.microsoft.com/vcblog/2016/11/16/permissive-switch/

I think we should try this flag, in on of our VC++2017.

IMO, that is not a priority task, but it could be done during the reorganization of our Windows testsuite.

**Comment by janetournois** [comment]
Do you think this should be changed in the CGAL CMakelists, or in the testsuite setup itself?

**Comment by lrineau** [comment]
First we should try in our testsuite setup.

And then... I do not think we can impose that flag on our users: it can break their own code. But at least I would like to verify that the CGAL code is already ready to be compiled with `/permissive-`.

**Comment by maxGimeno** [comment]
I added both to the VC15 Debug and Release testsuites.

**Comment by lrineau** [comment]
*Note that VC++ in MSVS 2017 is numbered 14.1, and not 15.*

Actually, we want to test VC++ 2017 with and without those flags. I suggest you add it only to the Debug testsuite, for example.

**Comment by maxGimeno** [comment]
ok, done

**Comment by jjpepper** [comment]
`Nef_polyhedron_3` can't be #included with this flag on.  Simply create an empty visual studio 2017 project with the conformance mode (`/permissive-`) turned on (can be found in the C++/Language project setting), simple compile a single translation unit with `#include <CGAL/Nef_polyhedron_3.h>` and it fails.

Link for information about the flag is [here](https://docs.microsoft.com/en-us/cpp/build/reference/permissive-standards-conformance).

Here's a sample of the errors:

```
1>c:\users\jessepepper\source\repos\vcpkg\installed\x64-windows\include\cgal\internal\static_filters\angle_3.h(156): error C2589: '(': illegal token on right side of '::'
1>c:\users\jessepepper\source\repos\vcpkg\installed\x64-windows\include\cgal\internal\static_filters\angle_3.h(164): note: see reference to class template instantiation 'CGAL::internal::Static_filters_predicates::Angle_3<K_base>' being compiled
1>c:\users\jessepepper\source\repos\vcpkg\installed\x64-windows\include\cgal\internal\static_filters\do_intersect_3.h(321): error C2589: '(': illegal token on right side of '::'
1>c:\users\jessepepper\source\repos\vcpkg\installed\x64-windows\include\cgal\internal\static_filters\do_intersect_3.h(327): note: see reference to class template instantiation 'CGAL::internal::Static_filters_predicates::Do_intersect_3<K_base,SFK>' being compiled
1>c:\users\jessepepper\source\repos\vcpkg\installed\x64-windows\include\cgal\nef_polyhedron_3.h(224): error C3203: 'SNC_structure': unspecialized class template can't be used as a template argument for template parameter 'Map', expected a real type
1>c:\users\jessepepper\source\repos\vcpkg\installed\x64-windows\include\cgal\nef_polyhedron_3.h(2021): note: see reference to class template instantiation 'CGAL::Nef_polyhedron_3<K,I,M>' being compiled
1>c:\users\jessepepper\source\repos\vcpkg\installed\x64-windows\include\cgal\nef_polyhedron_3.h(1066): error C3203: 'SNC_structure': unspecialized class template can't be used as a template argument for template parameter 'R', expected a real type
1>c:\users\jessepepper\source\repos\vcpkg\installed\x64-windows\include\cgal\nef_polyhedron_3.h(407): error C3203: 'SNC_structure': unspecialized class template can't be used as a template argument for template parameter 'Map', expected a real type
1>c:\users\jessepepper\source\repos\vcpkg\installed\x64-windows\include\cgal\nef_polyhedron_3.h(407): note: This diagnostic occurred in the compiler generated function 'CGAL::Nef_polyhedron_3<K,I,M>::Nef_polyhedron_3(II,II,const CGAL::Vector_3<KN> &,bool)'
1>c:\users\jessepepper\source\repos\vcpkg\installed\x64-windows\include\cgal\nef_3\snc_const_decorator.h(57): error C2955: 'CGAL::SNC_structure': use of class template requires template argument list
1>c:\users\jessepepper\source\repos\vcpkg\installed\x64-windows\include\cgal\nef_3\snc_sphere_map.h(44): note: see declaration of 'CGAL::SNC_structure'
1>c:\users\jessepepper\source\repos\vcpkg\installed\x64-windows\include\cgal\nef_3\snc_decorator.h(53): note: see reference to class template instantiation 'CGAL::SNC_const_decorator<Map>' being compiled
1>        with
1>        [
1>            Map=int
1>        ]
1>c:\users\jessepepper\source\repos\vcpkg\installed\x64-windows\include\cgal\nef_3\snc_point_locator.h(69): note: see reference to class template instantiation 'CGAL::SNC_decorator<int>' being compiled
1>c:\users\jessepepper\source\repos\vcpkg\installed\x64-windows\include\cgal\nef_3\snc_point_locator.h(154): note: see reference to class template instantiation 'CGAL::SNC_point_locator<SNC_decorator>' being compiled
1>        with
1>        [
1>            SNC_decorator=CGAL::SNC_decorator<int>
1>        ]
1>c:\users\jessepepper\source\repos\vcpkg\installed\x64-windows\include\cgal\nef_polyhedron_3.h(409): note: see reference to class template instantiation 'CGAL::SNC_point_locator_by_spatial_subdivision<CGAL::SNC_decorator<int>>' being compiled
1>c:\users\jessepepper\source\repos\vcpkg\installed\x64-windows\include\cgal\nef_3\snc_const_decorator.h(62): error C2955: 'CGAL::SNC_structure': use of class template requires template argument list
1>c:\users\jessepepper\source\repos\vcpkg\installed\x64-windows\include\cgal\nef_3\snc_sphere_map.h(44): note: see declaration of 'CGAL::SNC_structure'
1>c:\users\jessepepper\source\repos\vcpkg\installed\x64-windows\include\cgal\nef_3\snc_const_decorator.h(67): error C2955: 'CGAL::SNC_structure': use of class template requires template argument list
1>c:\users\jessepepper\source\repos\vcpkg\installed\x64-windows\include\cgal\nef_3\snc_sphere_map.h(44): note: see declaration of 'CGAL::SNC_structure'
1>c:\users\jessepepper\source\repos\vcpkg\installed\x64-windows\include\cgal\nef_3\snc_const_decorator.h(68): error C2955: 'CGAL::SNC_structure': use of class template requires template argument list
1>c:\users\jessepepper\source\repos\vcpkg\installed\x64-windows\include\cgal\nef_3\snc_sphere_map.h(44): note: see declaration of 'CGAL::SNC_structure'
```

**Comment by jjpepper** [comment]
Those errors above are produced with `/permissive-` but without `/std:c++latest` (just the C++14 default).  This actually wasted me half a day as I didn't realise one of my libraries was set to /permissive- and one not.  :-(

**Comment by jjpepper** [comment]
And it happens with the boost and cgal coming directly from vcpkg.  BTW there also seems to be an issue with the cgal vcpkg dependencies (it doesn't declare dependencies on all the boost things it needs).

**Comment by lrineau** [comment]
Which CGAL version have you tested? I think some of the compilation errors you reported might already be fixed in CGAL-4.12-beta1 (published yesterday).

**Comment by lrineau** [comment]
(As for the cgal vcpkg dependencies, report the issue to the vcpkg maintainers.)

**Comment by lrineau** [comment]
@jasjuang seems to be the CGAL vcpkg maintainer. He is the author of https://github.com/Microsoft/vcpkg/pull/2894, submitted yesterday.

**Comment by jjpepper** [comment]
Thanks.  @jasjuang, I submitted just submitted a cgal issue today: https://github.com/Microsoft/vcpkg/issues/2902

**Comment by jjpepper** [comment]
Sorry, I missed the question about the version. Just using 4.11.  We're
using vcpkg so updating to 4.12b is a little bit of a pain, and we have a
simple short term fix (don't use the switch).  It'd be good to know if it's
getting fixed soon as our code is going to be ported to Linux soon.

**Comment by ras0219-msft** [comment]
@lrineau For future use, you can point users to `vcpkg install cgal --head` to tell us to grab the "tip of trunk" for situations like this where you've fixed a bug on master but we haven't updated to your latest release yet :)

**Comment by jjpepper** [comment]
Thanks Robert. Very handy to know.

**Comment by lrineau** [comment]
@jjpepper There is an ongoing work to support `/permissive-`. We might be able to support it fully in CGAL-4.12-beta2, coming in about a week.

**Comment by lrineau** [comment]
@as0219-msft https://github.com/CGAL/cgal/issues/2414#issuecomment-369338967:
> @lrineau For future use, you can point users to `vcpkg install cgal --head` to tell us to grab the "tip of trunk" for situations like this where you've fixed a bug on master but we haven't updated to your latest release yet :)

Is that tested somewhere?

**Comment by ras0219-msft** [comment]
Our current CI only tests the latest stables.

Are you concerned about the vcpkg build invocation breaking (for example, our patches / cmake call) or your code breaking w.r.t. dependency versions inside vcpkg?

**Comment by lrineau** [comment]
Yes, as the release manager of CGAL, my motto is "if it is not tested, it can be assumed broken". So, I would not recommend to our users something that is not tested: it could be broken for each change of the internals of CMake scripts in CGAL.

Maybe our future appveyor script should test `vcpkg install --head`.

**Comment by lrineau** [comment]
Fixed by #2886.

**Comment by lrineau** [comment]
@jjpepper: This bug is now fixed in CGAL `master`, and the fix will soon be published in the release CGAL-4.12-beta2.

**Comment by jjpepper** [comment]
Thanks very much @lrineau.

**Comment by tomkulaga** [comment]
I've found some issues compiling with /permissive-
`` c:\dev\cgal-4.11\include\cgal\sweep_line_2\arr_overlay_traits_2.h(410): error C2760: syntax error: unexpected token 'identifier', expected ';' ``
``c:\dev\cgal-4.11\include\cgal\aabb_traits.h(290): error C3861: 'longest_axis': identifier not found``

Those are the start.

Tested with CGAL 4.11 and 4.12beta1/2  and boost 1.65_1 and 1.67_beta All fail with /permissive- but are fine without the /permissive- flag

**Comment by tomkulaga** [comment]
Hi, Sorry, here are some more detials


```
#include <QDebug>
//#include <CGAL/AABB_traits.h>  <--UNCOMMETING THIS LINE CASUES COMPILE ERROR
#include <CGAL/Exact_predicates_exact_constructions_kernel.h>

using K_AABB = CGAL::Exact_predicates_exact_constructions_kernel;



int main(int argc, char *argv[])
{
	qDebug() << "Hello World" << endl;
	return 0;
}
```
here is the error:

Compile Command used by MSVC: 
`D:\Program Files (x86)\Microsoft Visual Studio\Preview\Community\VC\Tools\MSVC\14.14.26329\bin\HostX86\x64\CL.exe /c /IC:\dev\QtPCB_msvc\Sandbox /IC:\dev\QtPCB\build\CMake\Sandbox /IC:\dev\QtPCB_msvc\Sandbox\Sandbox_autogen\include_Debug /IC:\dev\QtPCB\build\CMake\Sandbox\..\..\..\include /IC:\local\boost_1_67_0_b1_rc2 /I"C:\dev\CGAL-4.12-beta2\auxiliary\gmp\include" /I"C:\dev\CGAL-4.12-beta2\include" /I"C:\dev\QtPCB\build\CMake\Sandbox\..\..\..\external\explicit-9.1.2018\include" /I"C:\dev\QtPCB\build\CMake\Sandbox\..\..\..\external\multidim-2.2.2018" /ID:\Qt\5.10.0\msvc2017_64\include /ID:\Qt\5.10.0\msvc2017_64\include\QtCore /I"D:\Qt\5.10.0\msvc2017_64\.\mkspecs\win32-msvc" /ID:\Qt\5.10.0\msvc2017_64\include\QtOpenGL /ID:\Qt\5.10.0\msvc2017_64\include\QtWidgets /ID:\Qt\5.10.0\msvc2017_64\include\QtGui /ID:\Qt\5.10.0\msvc2017_64\include\QtANGLE /ID:\Qt\5.10.0\msvc2017_64\include\QtSvg /Zi /nologo /W3 /WX- /diagnostics:classic /MP4 /Od /Ob0 /D WIN32 /D _WINDOWS /D _SCL_SECURE_NO_WARNINGS /D _SCL_SECURE_NO_DEPRECATE /D QT_CORE_LIB /D QT_USE_QSTRINGBUILDER /D QT_NO_KEYWORDS /D CMAKE_PROJECT_NAME=Sandbox /D _CRT_SECURE_NO_WARNINGS /D BOOST_ALL_DYN_LINK /D BOOST_TEST_DYN_LINK /D CGAL_USE_MPFR /D CGAL_USE_GMP /D CGAL_USE_CORE=1 /D BOOST_ALL_DYN_LINK=1 /D QT_OPENGL_LIB /D QT_WIDGETS_LIB /D QT_GUI_LIB /D QT_SVG_LIB /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:strict /fp:except- /Zc:wchar_t /Zc:forScope /Zc:inline /GR /std:c++14 /Fo"Sandbox.dir\Debug\\" /Fd"Sandbox.dir\Debug\vc141.pdb" /Gd /TP /wd4503 /FC /errorReport:prompt  -Zc:throwingNew /bigobj /permissive- C:\dev\QtPCB\source\Sandbox\main.cpp C:\dev\QtPCB_msvc\Sandbox\Sandbox_autogen\mocs_compilation.cpp`

**Comment by lrineau** [comment]
Thanks @tomkulaga. So you use `/std:c++14` in addition to `/permissive-`. And Boost 1.67beta1. That probably explains the difference with our test platform.

Anyway, for CGAL-4.12, we plan to support `/std:c++latest` in addition to `/permissive-` (with Boost-1.67beta1 as well). Probably before the end of the week we will have the fix.

**Comment by tomkulaga** [comment]
Just wanted to let you know i repeated my above tests with /std:c++latest and /std:c++17 and I still have issues

**Comment by lrineau** [comment]
We had difficulties with the C++17 mode of VC++ deprecating a lot of things we use. Our work is still ongoing, in PR #2985.

**Comment by tomkulaga** [comment]
Hi,

Ive tried the latest 4.12 release and I still get the same exact issue. test code as aobve

> c:\dev\cgal-4.12\include\cgal\aabb_traits.h(305): error C3861: 'longest_axis': identifier not found

compile command

`2>    D:\Program Files (x86)\Microsoft Visual Studio\Preview\Community\VC\Tools\MSVC\14.14.26412\bin\HostX86\x64\CL.exe /c /IC:\dev\QtPCB_msvc\Sandbox /IC:\dev\QtPCB\build\CMake\Sandbox /IC:\dev\QtPCB_msvc\Sandbox\Sandbox_autogen\include_Debug /IC:\dev\QtPCB\build\CMake\Sandbox\..\..\..\include /IC:\local\boost_1_67_0 /I"C:\dev\CGAL-4.12\auxiliary\gmp\include" /I"C:\dev\CGAL-4.12\include" /I"C:\dev\QtPCB\build\CMake\Sandbox\..\..\..\external\explicit-9.1.2018\include" /I"C:\dev\QtPCB\build\CMake\Sandbox\..\..\..\external\multidim-2.2.2018" /ID:\Qt\5.11.0\msvc2017_64\include /ID:\Qt\5.11.0\msvc2017_64\include\QtCore /I"D:\Qt\5.11.0\msvc2017_64\.\mkspecs\win32-msvc" /ID:\Qt\5.11.0\msvc2017_64\include\QtOpenGL /ID:\Qt\5.11.0\msvc2017_64\include\QtWidgets /ID:\Qt\5.11.0\msvc2017_64\include\QtGui /ID:\Qt\5.11.0\msvc2017_64\include\QtANGLE /ID:\Qt\5.11.0\msvc2017_64\include\QtSvg /Zi /nologo /W3 /WX- /diagnostics:classic /MP4 /Od /Ob0 /D WIN32 /D _WINDOWS /D _SCL_SECURE_NO_WARNINGS /D _SCL_SECURE_NO_DEPRECATE /D QT_CORE_LIB /D QT_USE_QSTRINGBUILDER /D QT_NO_KEYWORDS /D CMAKE_PROJECT_NAME=Sandbox /D _CRT_SECURE_NO_WARNINGS /D BOOST_ALL_DYN_LINK /D BOOST_TEST_DYN_LINK /D CGAL_USE_MPFR /D CGAL_USE_GMP /D CGAL_USE_CORE=1 /D BOOST_ALL_DYN_LINK=1 /D QT_OPENGL_LIB /D QT_WIDGETS_LIB /D QT_GUI_LIB /D QT_SVG_LIB /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:strict /fp:except- /Zc:wchar_t /Zc:forScope /Zc:inline /GR /std:c++latest /Fo"Sandbox.dir\Debug\\" /Fd"Sandbox.dir\Debug\vc141.pdb" /Gd /TP /wd4503 /FC /errorReport:prompt  -Zc:throwingNew /bigobj /permissive- C:\dev\QtPCB\source\Sandbox\main.cpp
`

I'm using a shared lib build of CGAL, with all 4 libs built, no changes made in the cmake config.

**Comment by lrineau** [comment]
@tomkulaga Could you send us that file `C:\dev\QtPCB\source\Sandbox\main.cpp`, so that we can test it locally? (You can upload it on https://gist.github.com/ and copy the link here.)

**Comment by tomkulaga** [comment]
@lrineau
The code snippet I pasted above is the entirety of main.cpp.

Sorry should have mentioned that.

Does that snippet compile on your end?

It seems on my end the inclusion of AABB_traits triggers the compile error, in the most simplest of code.

Should I try in header only mode?

**Comment by lrineau** [comment]
I created a minimal gist, with the `CMakeLists.txt` and `test-bug.cpp`:
https://gist.github.com/341b7fd0002c988797dbf05d57504e62

On Linux it compiles fine.

@janetournois Could you try with CGAL-4.12 (or master) and `/permissive- /std:c++latest`?

**Comment by janetournois** [comment]
I just tested the compilation of this example, with
- Visual 2017, 64 bits
- CGAL-4.12-beta2 (header only)
- boost 1.67 beta1
- `/permissive- /std:c++latest`

and it compiles fine too.

With the same configuration and CGAL-4.12-beta2 not header only, I get warnings in `CGAL/handle_for.h`, but no errors.

**Comment by tomkulaga** [comment]
How about dull version?

**Comment by tomkulaga** [comment]
Dll sorry

**Comment by janetournois** [comment]
dll version of CGAL?

**Comment by tomkulaga** [comment]
Yup. The build shared libs cmake flag

**Comment by lrineau** [comment]
@tomkulaga 
> `D:\Program Files (x86)\Microsoft Visual Studio\Preview\Community\VC\Tools\MSVC\14.14.26412\bin\HostX86\x64\CL.exe`

You are actually using a preview version of Visual Studio 2017 version 15.7, where as we tested with Visual Studio 2017 version 15.6. That must be it.

**Comment by tomkulaga** [comment]
I'll give 15.6 a try on my end using your first and report back

**Comment by janetournois** [comment]
Ok thanks.
"build shared libs" is what I did in the non-header only version.

**Comment by tomkulaga** [comment]
Oops overlooked that. Sorry

**Comment by lrineau** [comment]
[**@lrineau**](https://github.com/lrineau) commented on [Apr 26, 2018, 1:51 PM GMT+2](https://github.com/CGAL/cgal/issues/2414#issuecomment-384612791 "2018-04-26T11:51:36Z - Replied by Github Reply Comments"):
> @tomkulaga 
> > `D:\Program Files (x86)\Microsoft Visual Studio\Preview\Community\VC\Tools\MSVC\14.14.26412\bin\HostX86\x64\CL.exe`
> 
> You are actually using a preview version of Visual Studio 2017 version 15.7, where as we tested with Visual Studio 2017 version 15.6. That must be it.

The question, now, is: is that a *bug* of that preview version of 15.7, that will be fixed, or will it be the behavior of the future official VC++ 2017 version 15.7?

I can see why the code is tricky to compile: it a nested class `Sort_primitives` of a class template `template<typename GeomTraits, typename AABBPrimitive, typename BboxMap> AABB_traits`, we have a unqualified call to a static member function of AABB_traits, that is even defined latter in the class. I am not sure myself if that is a valid C++ code, that happens to compile with gcc and clang, or if that is a bug of VC++.

The easy workaround is a qualified call, instead of non-qualified.

**Comment by lrineau** [comment]
I can confirm the compilation error with MSVC 2017 15.7 Preview 4.
