### ISSUE TITLE
Add a test of `/std:c++latest` with  Visual C++ 2017.

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#2415]
Newest versions of VC++2017 have a new flags `/std:c++latest`, to enable the bleeing-edge support of C++ (C++14, C++17, and later). I think one of our testsuite configuration should test that flag.

https://docs.microsoft.com/en-us/cpp/what-s-new-for-visual-cpp-in-visual-studio

See also [the documentation of the `/std` option](https://docs.microsoft.com/en-us/cpp/build/reference/std-specify-language-standard-version).

**Comment by lrineau** [comment]
It could be the same configuration as for `/permissive-` of #2414.

**Comment by afabri** [comment]
Note that even the latest version of boost uses std::unary_function.  This can be seen in our [testsuite  ](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.12-Ic-57/Installation/TestReport_afabri_x64_Cygwin-Windows10_MSVC2017-Release-64bits-extra_flags.gz)Maybe we should pollute the namespace `std::`

**Comment by lrineau** [comment]
See also [the documentation of the `/std` option](https://docs.microsoft.com/en-us/cpp/build/reference/std-specify-language-standard-version).

`/std:c++latest` now enables some C++20 features implemented in MSVC 2017. There is `/std:c++17` to enable only C++17.

I think some of our users will like to use `/std:c++latest`. We should support it, if Boost supports it as well.

**Comment by afabri** [comment]
`OpenMesh` is not yet `/std:c++latest`-ready.

**Comment by janetournois** [comment]
just note that on Friday I added `/std:c++latest` to our MSVC2017-Debug testsuite (on Gauguin).
So it has been tested since [-4.12-Ic-225](https://cgal.geometryfactory.com/CGAL/testsuite/results-4.12-Ic-225.shtml)

**Comment by maxGimeno** [comment]
I downloaded the currently latest stable released of eigen, the 3.3.4, on gauguin, and updated the setup_common accordingly.
