### ISSUE TITLE
make_mesh_3 returns empty mesh for domain with planar 1D features (sequel to #1501)

### ISSUE THREAD

**Issue by jpanetta** [CGAL/cgal#2416]
I am still encountering cases where make_mesh_3 produces an empty mesh like in [my previous issue](https://github.com/CGAL/cgal/issues/1501).

I had no problems with the "paranoid" solution Laurent [originally suggested](https://github.com/CGAL/cgal/issues/1501#issuecomment-250161654)
of always running init_c3t3. But when I downloaded a fresh copy of CGAL, I realized the more sophisticated solution that actually made it into 4.9.1 (from [this commit](https://github.com/CGAL/cgal/pull/1506/commits/9ba4132a38b6587ab38618a66a30eddf708e6566)) doesn't always work (despite working on my previous example).

I've uploaded a new failing example [here](https://gist.github.com/jpanetta/74ccf23cdd6bdc763d1a21ab5680833d). Last time, all tetrahedra of
the feature curve samples' Delaunay triangulation had circumcenters falling outside the meshing domain. This time, there are exactly 3 circumcenters inside, circled below:

![visualization](https://user-images.githubusercontent.com/15096451/30320972-b606ab26-97b4-11e7-8dce-e6697f58a7f2.png)

After helper.update_restricted_facets(), there are 12 facets in the c3t3 (shown in blue), so the current check decides no further initialization is necessary. However, the mesher immediately returns an empty c3t3, whereas when I bypass the check and call init_c3t3 myself, I get a good mesh (shown in translucent gray above).

For what it's worth, the three tetrahedra whose circumcenters are in the domain look degenerate and lie entirely outside the domain.

**Comment by lrineau** [comment]
I confirm the issue. After two steps of Delaunay refinement, the list of facets in the restricted Delaunay triangulation gets empty.

I knew it was possible. I have pushed a modification to you Gist: https://gist.github.com/lrineau/c1aa80871bfdb590d1abc38cb8651b57/revisions

Its calls again `init_c3t3`, and then `refine_mesh_3`, in case the intermediate mesh gets empty. But that is only a hack.
