### ISSUE TITLE
MD5 checksum mismatch for source code releases

### ISSUE THREAD

**Issue by vvzh** [CGAL/cgal#2417]
Hi,

When downloading CGAL release 4.8 from https://github.com/CGAL/cgal/releases/tag/releases%2FCGAL-4.8 I found that MD5 checksum of source code tarball (https://github.com/CGAL/cgal/archive/releases/CGAL-4.8.tar.gz) does not match with one specified in https://github.com/CGAL/cgal/releases/download/releases%2FCGAL-4.8/md5sum.txt.

The same issue applies to other releases as well, I checked source tarballs of CGAL 4.8.1 and 4.11-beta1.

Should I trust these files? Does this mismatch indicate some malicious changes to the content?

**Comment by lrineau** [comment]
The links named `Source code (zip)` and `Source code (tar.gz)` are links generated by Github. They contains a tarball of the git repository, checked-out at the tag corresponding to the release. Those tarballs follow the layout of the Git repository, and are really different from the "release tarballs" pointed by the link above, named for example `CGAL-4.8.tar.xz` and `CGAL-4.8.zip`. That explains why the md5sum differ.

**Comment by vvzh** [comment]
Thanks for the explanation.
