### ISSUE TITLE
syntax update for UseCGAL.cmake with modern cmake

### ISSUE THREAD

**Issue by jasjuang** [CGAL/cgal#2420]
## Issue Details

In my downstream project, I would love to simply use `include( ${CGAL_USE_FILE} )` in my CMakeLists but the problem is `UseCGAL.cmake` is using a lot of outdated cmake syntax. For example, modern cmake uses `target_include_directories` instead of `include_directories` , `target_compile_definitions` instead of `add_definitions`, `target_link_libraries` instead of `link_libraries`. These old syntax are causing a lot of troubles when exporting targets for my downstream project. Can someone please update it?

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Ubuntu 16.04
* Compiler: GCC 5.4
* CGAL version: Latest
* Boost version: 1.58

**Comment by lrineau** [comment]
There is a long ongoing task that is dedicated to refreshing CGAL CMake scripts to newest CMake features (mostly imported targets and interface properties). The work is done in #1436. The branch of that PR is rather old, and I will have to refresh it. I plan to work again on that low-priority task at the next CGAL developers meeting, 13-17 november 2017.

**Comment by jasjuang** [comment]
@claashk Thanks for sharing the link, I will watch it later and see how I can improve my cmake scripts!

**Comment by lrineau** [comment]
Fixed by #1436.
