### ISSUE TITLE
Hole fill should refuse filling a hole if it has a null edge

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#2430]
This will end up breaking an assertion if the hole is made of 3 vertices.

**Comment by sloriot** [comment]
@kkatrio When you have time, it would be nice if you can handle this issue.

**Comment by kkatrio** [comment]
ok, will do.

**Comment by kkatrio** [comment]
When trying to fill a hole which is created by at least one null edge, then I get either "Returning no output. No possible triangulation is found!" or "Returning no output. Filling hole with extra triangles is not successful!", depending on if I tried with DT or not. Should I try something in particular to reproduce the issue?

**Comment by sloriot** [comment]
Did you try with a hole made only of 3 vertices?

**Comment by lrineau** [comment]
Fixed by #2932.
