### ISSUE TITLE
Polyhedron demo:  Filling small holes can be surprising 

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#2431]
## Issue Details

The hole filling in the Polyhedron demo will also consider the border of an isolated triangle (or the border any small connected component) as a hole.   For a triangle this leads to two triangular faces sharing three vertices and three edges.  And this surface is not dealt with, for example in the surface mesh simplification.

**Comment by afabri** [comment]
@sloriot can you assign this to someone, and if it is you?  This seems to be serious.

**Comment by sloriot** [comment]
What can we do? if you check the box to ask for the filling of the hole to not intersect the mesh, then it will not be selected. I don't see what else we could do (except if you are concerned only with the case of 3 vertices already connected and but the one of k coplanar vertices).

**Comment by sloriot** [comment]
The _real_ issue comes from simplification that shouldn't crash. For the hole filling the self-intersection test will filter out those elements (those isolated triangles should be filtered out using `remove_small_connected_components()` for example)

**Comment by lrineau** [comment]
The merge of PR #3310 has closed this issue, but the message was:
> Somehow fixes #2431

Do you want to reopen the issue?
