### ISSUE TITLE
Polyhedron demo: bad surface mesh display on large coordinates

### ISSUE THREAD

**Issue by sgiraudot** [CGAL/cgal#2433]
## Issue Details

The Surface Mesh item in the demo has a bad display when using large coordinates (which makes it non-aligned with other objects that have the exact same coordinates).

## Source Code

Consider the following OFF file:

```
OFF
3 1 0
8000000 5000000 0.3
8000002.3 5000001.5 -0.11
8000001.1 5000003.92 0.999
3 0 1 2
```

You can view the problem with 2 simple methods:
* Open it once with the Polyhedron OFF reader and once with the Surface Mesh OFF reader: the triangle is not the same
* Or open it with the Surface Mesh OFF reader, select all edges: the selection item is not aligned with the edges of the surface mesh (same if you create a polyline)

Visually, Polylines, Point Sets and Polyhedron seem to agree on the coordinates, so my guess is that the problem comes from the Surface Mesh item.

**Comment by lrineau** [comment]
Fixed by #2437.
