### ISSUE TITLE
Feature Request:  read_stl()

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#2436]
## Issue Details

Although the Polyhedron demo can read meshes given as a STL-file, we do not have a function similiar to `read_OFF(..)`.  
This would be nice to have, so that people do not first have to convert them with other tools (such as Meshlab, or the Polyhedron demo), as suggested on [stackexchange](https://3dprinting.stackexchange.com/questions/3070/how-can-i-convert-stl-file-to-off-to-use-in-cgal)

**Comment by HunorSzabo** [comment]
I am also supporting the idea. It would be a nice functionality, eliminating the cumbersome process of converting .stl to .off.

**Comment by afabri** [comment]
In fact there is an [undocumented function](https://github.com/CGAL/cgal/blob/master/Polyhedron_IO/include/CGAL/IO/STL_reader.h) that almost does the job, but it should be extended to also read binary STL.  I guess we can limit us to triangle faces as that seems to cover the typcial use case according to the [wikipedia](https://en.wikipedia.org/wiki/STL_(file_format)).

**Comment by HunorSzabo** [comment]
Nice, I didn't know this function exists. Will give it a try soon. Thanks

**Comment by HunorSzabo** [comment]
I tried with a few files and so far only one worked `03 042 082.stl` worked `simple_plate.stl` didn't  work, these are only 2 examples. 
will try to figure debug the reson. 

[test_read_stl_function.zip](https://github.com/CGAL/cgal/files/1322164/test_read_stl_function.zip)

**Comment by afabri** [comment]
So far binary STL is not supported.

**Comment by HunorSzabo** [comment]
True, I missed your remark above about the binary STL support. I assume it wouldn't be hard to extend it, right? I will try to look after it.

**Comment by afabri** [comment]
Well, the code only supports binary, and the file `03 042 082.stl`  is also binary, so the problem is elsewhere. Are there faces that are not triangles?

**Comment by HunorSzabo** [comment]
No, that shouldn't be the case. Maybe solidworks adds some metadata to the file, or doesn't follow the strict file format, but then freecad wouldn't be able the solidwork's exported `.stl`.
