### ISSUE TITLE
Polyhedron demo log

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#2439]
The starting log of the polyhedron is rarely used. IMO, we better have it store internally and displayed on demand. The reason for this is that when I load a lot of times the demo my terminal gets polluted and I'd like to avoid redirected the output to `/dev/null` as I might need the output of some actions.

**Comment by janetournois** [comment]
What about deciding in cmake whether the log should be written to the terminal, or to a log file? (or maybe not at all)

**Comment by sloriot** [comment]
Note that I'm not talking about a log file but rather an entry in the menu `Show startup log`.

**Comment by janetournois** [comment]
Yes, but what would you do if the demo does not launch? We should be able to (optionally) get the log in the terminal.

And the log of the following operations could be saved to a log file too. I suggested that a few days ago. We could then be more verbose when writing the plugins, to save in a log file the parameters of each operation ran, to help debugging when something crashes and we can't remember easily what parameters we've used to make it crash.

**Comment by sloriot** [comment]
`Polyhedron --verbose`

**Comment by sloriot** [comment]
With a fresh OS install, I no longer have log messages at startup. Only
```
Enable scripts.
Execution of script ":/cgal/Polyhedron_3/javascript/lib.js"
Write setting... done.
```
remains.
@maxGimeno @lrineau any idea why?

**Comment by maxGimeno** [comment]
Have you compiled any plugin ?

**Comment by sloriot** [comment]
of course

**Comment by sloriot** [comment]
Qt 5.91 and libQGLViewer 2.6.3

**Comment by lrineau** [comment]
@sloriot: On my new laptop, I had to tweak settings in `$HOME/.config/QtProject/qtlogging.ini`.
