### ISSUE TITLE
Clipping box item

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#2440]
I don't know what the clipping box should be doing but with bac04522 when I click on `Clip` after the generation of the box with `elephant` selected, edges outside the box are no longer displayed but faces are. Also the `clip` button stays pressed. 

No idea if the issues is also in 4.11

**Comment by maxGimeno** [comment]
The plugin doesn't exist in 4.11, so the bug cannot be there :)

The button behavior is perfectly normal. The only problem is that the clipping part is missing from the flat_shader, so it doesn't work with polyhedron_item in flat mode. I'm currently fixing that.
