### ISSUE TITLE
Polyhedron demo : bugs in the `mesh_3_plugin`

### ISSUE THREAD

**Issue by janetournois** [CGAL/cgal#2453]
## Issue Details

I am trying to mesh in the demo a given `Polyhedron` (the problem is the same with `Surface_mesh` with a very small tetrahedron size, and the output mesh is always more or less the same, with very few simplices compared to what I expect.

Then, the `C3t3` is displayed with the cut plane, and when I click "Show tetrahedra", it is only possible to have the intersected tetrahedra in "wire" mode. The "flat+edges" mode displays the same as the "wire" mode.

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows
* Compiler: msvc2013
* Release or debug mode: Release
* Specific flags used (if any): CGAL_HEADER_ONLY
* CGAL version: master
* Boost version: 1.59

**Comment by janetournois** [comment]
cc @maxGimeno

**Comment by maxGimeno** [comment]
This should fix the displaying bug, but for the tet_sizing It is broken at least since 4.10. I suggest someone that actualy knows how this is supposed to work lokks into it.

**Comment by lrineau** [comment]
Was the bug already in 4.11?

**Comment by maxGimeno** [comment]
The visual bug is only in 4.12 but the other one appeared in 4.11
