### ISSUE TITLE
Running ransac on Polyhedron created from '.stl'

### ISSUE THREAD

**Issue by HunorSzabo** [CGAL/cgal#2457]
I created a `polyhedron` out of `.stl` and I would like to run `ransac` over it to detect `cone`s and `cylinder`s, but as of now I am stuck of getting the `normal`s of the `polyhedron` to set it on `ransac` by `ransac.set_input(...)`.

Could you give me a general roadmap(links, steps to follow, etc) to make this possible?

## Source Code
So far I just read the file and created a `polyhedron` see below:

```
typedef CGAL::Exact_predicates_inexact_constructions_kernel  Kernel;
typedef Kernel::Point_3 Point;
typedef Kernel::Vector_3 Vector;
typedef std::vector<CGAL::cpp11::array<double, 3> > Points_3;
typedef CGAL::cpp11::array<int,3> Facet;
typedef std::vector<Facet> Surface;
typedef Kernel::Iso_cuboid_3 Iso_cuboid;
typedef CGAL::Polyhedron_3<Kernel> Polyhedron;

void CGALPartAnalysis::readFile(string filename) {
    std::ifstream stream(filename);
    if(stream) {
        std::cout << "File is read to stream " << std::endl;
    } else {
        std::cerr << "Error! Cannot open file " << std::endl;
    }
    if (CGAL::read_STL(stream, meshPoints, mesh))
    {
        std::cout << "File is loaded" << std::endl;
    } else {
        std::cerr << "Error: invalid STL file" << std::endl;
    }
}

void CGALPartAnalysis::convertPolyhedron() {

    cout << "Mesh size: " << mesh.size() << endl;//

    cout << "MeshPoints size: " << meshPoints.size() << endl;

    if (CGAL::Polygon_mesh_processing::is_polygon_soup_a_polygon_mesh(this->mesh)) {
        CGAL::Polygon_mesh_processing::polygon_soup_to_polygon_mesh(this->meshPoints, this->mesh, this->polyhedron);
    }
....
```
Any general guideline would be more than welcome. Thanks for your suggestions :)

**Comment by sloriot** [comment]
The current operations works only for points with normals. You need to compute the normal associated to each vertex (with [`compute_vertex_normals()`](https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__normal__grp.html#ga240ed0a1f5efbea472f998fada07e112) for example).

The point property map will be `boost::property_map<Polyhedron, boost::vertex_point_t>`, the normal property map the one used for computing the normals (like [here](https://doc.cgal.org/latest/Polygon_mesh_processing/Polygon_mesh_processing_2compute_normals_example_Polyhedron_8cpp-example.html) for example) and the range type will be `CGAL::Iterator_range<boost::graph_traits< Polyhedron const>::vertex_iterator>`. You can access the range using the function `vertices(poly)`.

**Comment by HunorSzabo** [comment]
Nice, thank you for the lightning fast response. Will jump on it right now and perhaps later on may ask for some additional details. Thank you.

**Comment by HunorSzabo** [comment]
```
    for(vertex_descriptor vd: vertices(polyhedron)){
        Vector n = CGAL::Polygon_mesh_processing::compute_vertex_normal(vd, polyhedron);
        pointWithVector.push_back(make_pair(vd->point(), n));
    }
```
Works nice, I did something like above and then I used pointWithVector as set_input argument.
