### ISSUE TITLE
Collect DLLs used by pre-compiled demos, for CGAL-4.11

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#2458]
Saturday night, the testsuite on gauguin will collect the binaries of all Qt5 demos, with the reference platform `x64_Cygwin-Windows10_MSVC2017-Release-64bits`. That will include all binaries from the polyhedron demo, but also other small 3D demos, and from all the 2D demos.

The task is to prepare the zip file of all the dependencies:
  - `boost_thread` and its dependencies (for demos using CGAL_Core),
  - gmp+mpfr
  - all Qt5 dlls used by our platform,
    - and the `platform/` directory of Qt5,
  - maybe TBB,
  - maybe VTK, if the platform uses it,
  - ... others?

**Comment by janetournois** [comment]
it also needs `QGLViewer`

**Comment by janetournois** [comment]
The test of the demo for vs2017 Release 64 bits should first be enriched with all its dependencies
Tomorrow, CGAL-4.12-Ic-50 should have VTK and TBB working.

**Comment by lrineau** [comment]
It seems there is runtime error, probably with TBB.

**Comment by janetournois** [comment]
The full list of dependencies is ready (someone with an empty environment Windows VM should maybe test it)

**Comment by lrineau** [comment]
You can try with the content of the file https://cgal.geometryfactory.com/~lrineau/demos-CGAL-4.12-Ic-55_afabri-test031020170045-x64_Cygwin-Windows10_MSVC2017-Release-64bits-cmake.tar.gz, that contains the demos precompiled from the internal release CGAL-4.12-Ic-55, last night.

**Comment by janetournois** [comment]
I already tried on Gauguin, but it's worth trying on an environment that has none of the needed dependencies

**Comment by janetournois** [comment]
@lrineau can we close this issue? I think you have checked the list of dependencies on a VM, right?

**Comment by lrineau** [comment]
I have to check first with the real demos binaries. The were supposed to be built last week-end. I'll check tomorrow.

**Comment by lrineau** [comment]
Can you gather the DLLs somewhere I can easily find them?

**Comment by janetournois** [comment]
they are in a zip on the desktop of Gauguin

**Comment by lrineau** [comment]
Done. See https://github.com/CGAL/cgal-web/pull/72
