### ISSUE TITLE
Do not display wire for spheres of the polyline item

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#246]
The wireframe for the sphere endpoint of the polylines should not be displayed. They are messing up the color.

cc @maxGimeno

**Comment by lrineau** [comment]
I disagree. Maybe the default should be to draw the spheres in flat mode. But sometimes I prefer to visualize in wireframe (edges only, not flat+edges) to see what is "inside" the spheres.

**Comment by sloriot** [comment]
Yes but you don't want both at the same time. Otherwise you wonder whether there is a black sphere hidden in the colored one.

**Comment by maxGimeno** [comment]
Fixed in CGAL/cgal-public-dev@ccedb330aac07523b0a6d74e8e898b2d84a6eb0e

**Comment by sloriot** [comment]
Fixed
