### ISSUE TITLE
Assertion failure with isotropic_remeshing

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#2464]
The attached program fails with master, 4.11, and  4.10 with the following assertion:
```
terminate called after throwing an instance of 'CGAL::Assertion_exception'
  what():  CGAL ERROR: assertion violation!
Expr: pid == patch1 || pid == patch2
File: CGAL/Polygon_mesh_processing/internal/Isotropic_remeshing/remesh_impl.h
Line: 1374
Aborted
```
The program runs without pb with 4.9

[isotropic_remeshing_example.zip](https://github.com/CGAL/cgal/files/1329303/isotropic_remeshing_example.zip)

**Comment by lrineau** [comment]
Fixed by #2519.
