### ISSUE TITLE
Source vertices in the shortest path polyhedron plugin are hardly visible

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#247]
It would be nice to increase the size of the source points.
To reproduce the pb, open a polyhedron and call `Make Shortest Path`. They left click a point while holding shift to define a source point.

cc @maxGimeno

**Comment by maxGimeno** [comment]
Done in CGAL/cgal-public-dev@f90f19a666468842bc39fe8f4d357d58fdf9820a

**Comment by sloriot** [comment]
Issue is fixed
