### ISSUE TITLE
Solver Interface: documentation is split between /doc/CGAL and /include/CGAL

### ISSUE THREAD

**Issue by MaelRL** [CGAL/cgal#2470]
The documentation of the package `Solver_interface` is rendering incompletely (see https://doc.cgal.org/latest/Solver_interface/classCGAL_1_1Eigen__sparse__matrix.html) because it is split between `/doc/CGAL/XXX.h` and `/include/CGAL/XXX.h`. All the documentation of the latter is then ignored.

They should be merged.

**Comment by afabri** [comment]
@sloriot Can the input come from mixed source and just tell that in a doxygen config file?

**Comment by sloriot** [comment]
Nope we need to put the doc in the header.
