### ISSUE TITLE
Mesh clipping failure (Windows/Ubuntu)

### ISSUE THREAD

**Issue by Aspirisha** [CGAL/cgal#2473]
## Issue Details

So, I have the following problem: having a triangular mesh, I want to leave only that part of it which lies inside a specific volume (this volume is also represented via CGAL Triangular mesh).

I have found [this](https://stackoverflow.com/questions/45467149/substract-closed-mesh-from-surface-cgal)  answer, and I have tested it on two platforms: on windows and on Linux (Ubuntu). For the testing purposes, I intersect a unit cube with a triangular prism, which should give me two triangles (the bottom and the top of the cube).

On windows (in release build) the solution causes following runtime error (when running google test using the code similar to [this](https://github.com/CGAL/cgal/blob/master/Polygon_mesh_processing/test/Polygon_mesh_processing/test_pmp_clip.cpp)):

> unknown file: error: SEH exception with code 0xc0000005 thrown in the test body. 

On Ubuntu in debug build, I get assertion failure:

> Expr: s != LEFT_TURN
> File: /usr/local/include/CGAL/Triangulation_2.h
> Line: 812" thrown in the test body

I hadn't dived into the sources of the CGAL yet and decided to start with just commenting out the above assertions. After that, I have got the correct result, and the Valgrind was also happy (no memory problems, for example, were detected). In the release build under Ubuntu, everything also works fine.

Maybe, I am doing something wrong, but I don't understand, what can be the problem.

## Source Code

```C++
class MeshProcessorTest {
        typedef CGAL::Simple_cartesian<double> K;
        typedef K::Ray_3 Ray;
        typedef K::Line_3 Line;
        typedef K::Point_3 Point;
        typedef K::Triangle_3 Triangle;
        typedef CGAL::Polyhedron_3<K,
        CGAL::Polyhedron_items_3,
        CGAL::HalfedgeDS_list> CgalPolyhedron;
        typedef CGAL::Surface_mesh<Point> Triangle_mesh;

        Triangle_mesh create_unit_cube() {
            Triangle_mesh cube;
            // all faces will be ccw
            std::vector<std::vector<int>> cube_faces = { { 0,1,2 },{ 0,2,3 },{ 0,3,4 },{ 4,3,7 },{ 7,3,2 },
            { 7,2,6 },{ 1,6,2 },{ 1,5,6 },{ 0,4,1 },{ 1,4,5 },{ 4,7,5 },{ 5,7,6 } };

            std::vector<Point> cube_vertices = { { 0,0,0 },{ 0,1,0 },{ 1,1,0 },{ 1,0,0 },{ 0,0,1 },{ 0,1,1 },{ 1,1,1 },{ 1,0,1 } };
            // let x be right, y forward, z up
            for (Point &p : cube_vertices) {
                cube.add_vertex(p);
            }

            for (auto &f : cube_faces) {
                cube.add_face(Triangle_mesh::Vertex_index(f[0]),
                    Triangle_mesh::Vertex_index(f[1]), Triangle_mesh::Vertex_index(f[2]));
            }

            return cube;
        }

        Triangle_mesh create_triangle_prism() {
            std::vector<Point> points = { MeshProcessorTest::Point{ 0,0,0 }, MeshProcessor::Point{ 0,1,0 },MeshProcessor::Point{ 1,0,0 } };
            Triangle_mesh prism;
            for (const Point &p : points) {
                prism.add_vertex({ p.x(), p.y(), -1 });
                prism.add_vertex({ p.x(), p.y(), 2 });
            }

            for (int i = 1; i < points.size(); i++) {
                prism.add_face(Triangle_mesh::Vertex_index(2 * i - 2), Triangle_mesh::Vertex_index(2 * i - 1),
                    Triangle_mesh::Vertex_index(2 * i + 1));
                prism.add_face(Triangle_mesh::Vertex_index(2 * i - 2), Triangle_mesh::Vertex_index(2 * i + 1),
                    Triangle_mesh::Vertex_index(2 * i));
            }
            for (int i = 2; i < points.size(); i++) {
                // bottom
                prism.add_face(Triangle_mesh::Vertex_index(0), Triangle_mesh::Vertex_index(2 * i - 2),
                    Triangle_mesh::Vertex_index(2 * i));
                // top
                prism.add_face(Triangle_mesh::Vertex_index(1), Triangle_mesh::Vertex_index(2 * i + 1),
                    Triangle_mesh::Vertex_index(2 * i - 1));
            }
            prism.add_face(Triangle_mesh::Vertex_index(2 * points.size() - 2), Triangle_mesh::Vertex_index(2 * points.size() - 1),
                Triangle_mesh::Vertex_index(1));
            prism.add_face(Triangle_mesh::Vertex_index(2 * points.size() - 2), Triangle_mesh::Vertex_index(1),
                Triangle_mesh::Vertex_index(0));

            return prism;
        }

    public:
        void clip() {
            Triangle_mesh cube = create_unit_cube();
            Triangle_mesh prism = create_triangle_prism();
            // check if it's ok
            {
                std::ofstream output("cube.obj");
                CgalPolyhedron polyhedron;
                CGAL::copy_face_graph(cube, polyhedron);
                CGAL::print_polyhedron_wavefront(output, polyhedron);
            }
            {
                std::ofstream output("prism.obj");
                CgalPolyhedron polyhedron;
                CGAL::copy_face_graph(prism, polyhedron);
                CGAL::print_polyhedron_wavefront(output, polyhedron);
            }

            // this line causes error on Windows platform and assertion failure on Ubuntu
            PMP::clip(cube, prism, false);

            {
                std::ofstream output("clipped.obj");
                CgalPolyhedron polyhedron;
                CGAL::copy_face_graph(cube, polyhedron);
                CGAL::print_polyhedron_wavefront(output, polyhedron);
            }
        }
    };

    TEST(meshcutter, Clip0) {
        MeshProcessorTest mp;
        mp.clip();
    }

```
## Environment

* Operating system Windows and Ubuntu
* Compiler: 
    * cl.exe C/C++ Optimizing Compiler Version 19.00.23506 for x64 (Windows)
    * gcc 5.4.0 (Ubuntu)
* Release or debug mode: 
    * Release (Windows)
    * Debug (Ubuntu)
* Specific flags used (if any):
* CGAL version: 4.11
* Boost version: 1.65 
* Other libraries versions if used (Eigen, TBB, etc.): None

**Comment by sloriot** [comment]
First note that this is undocumented code. Try replacing `typedef CGAL::Simple_cartesian<double> K;` by `CGAL::Exact_predicates_inexact_constructions_kernel.h`.

**Comment by Aspirisha** [comment]
Thank you for the answer! You are right, the feature is undocumented, but internally the failure is caused by the corefine(...) function, which in turn is official.  

I have tried your suggestion and changed the kernel, but unfortunately, at least on windows, the error is still there.

**Comment by Aspirisha** [comment]
Guys! 
I am awfully sorry! This problem was due to me running the code on windows from git-bash console. Under git-bash the exception is thrown, but under e.g. normal console everything is fine. I am very confused! 
I haven't re-tested the code on Ubuntu yet, but I guess maybe there I have also done something wrong. I think, we should close the issue.
