### ISSUE TITLE
how_to_cite_cgal.html

### ISSUE THREAD

**Issue by gdamiand** [CGAL/cgal#2474]
## Issue Details

There are two problems in the https://doc.cgal.org/latest/Manual/how_to_cite_cgal.html web page.

* edition is empty in the bibtex entries
* html links are broken

**Comment by sloriot** [comment]
should be fixed by #2463

**Comment by lrineau** [comment]
It is fixed: https://cgal.geometryfactory.com/CGAL/Manual_doxygen_test/CGAL-4.12-Ic-52/output/Manual/how_to_cite_cgal.html

**Comment by lrineau** [comment]
Now fixed at https://doc.cgal.org/latest/Manual/how_to_cite_cgal.html as well.

(Cc @afabri)
