### ISSUE TITLE
New runtimes errors of Segment_Delaunay_graph_2 with recent compilers

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#2479]
## Issue Details

A lot of test and examples of Sdg_2 have runtime errors, in the recent Fedora testsuite, with g++-7.2.1:

https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.12-I-54/Segment_Delaunay_graph_2_Examples/TestReport_lrineau_Fedora-Release.gz

```
------------------------------------------------------------------
- ProgramOutput.sdg-count-sites.Fedora-Release
------------------------------------------------------------------
CGAL::Random()::get_seed() = 1506928648
SDGDS is ok... Segment Delaunay graph is NOT valid...sdg-count-sites: 
[...]/sdg-count-sites.cpp:32: int main(): Assertion `sdg.is_valid(true, 1)' failed.
./cgal_test_with_cmake: line 70: 24932 Aborted                 (core dumped) ./sdg-count-sites

```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Linux Fedora 
* Compiler: g++ 7.2.1
* Release or debug mode: Release
* CGAL version: `master`, cd085f88806f7524f080869227a6c4738fbb9eef
* Boost version: 1.63.0

**Comment by sgiraudot** [comment]
I can't reproduce it using g++-7 on Debian (but the provided version is 7.2.0-8, not 7.2.1, that might be the reason why).

**Comment by lrineau** [comment]
I can reproduce the issue on my Fedora.

**Comment by lrineau** [comment]
I can reproduce with:
  - `-O3 -CGAL_DEBUG`, or
  - `-O3`

but not with
  - `-O2`, or
  -`-O2 -DCGAL_NDEBUG`.

**Comment by lrineau** [comment]
I have also tried with:
  - `-O3 -fsanitize=address`, and
  - `-O3 -fsanitize=address -DCGAL_NDEBUG`

and in both case the program compiles and runs fine.

**Comment by lrineau** [comment]
I do not know how to debug that code. I give up for the moment.

**Comment by MaelRL** [comment]
Do you remember where did you set the seed in the code ?

Incidentally (@maxGimeno), the printing of the seeds at the start of the program output seems gone from some packages, see for example:
https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.1-Ic-53/Segment_Delaunay_graph_2_Examples/TestReport_lrineau_Fedora-Release.gz. Is that normal?

**Comment by lrineau** [comment]
> Incidentally (@maxGimeno), the printing of the seeds at the start of the program output seems gone from some packages, see for example:
> [cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.1-Ic-53/Segment_Delaunay_graph_2_Examples/TestReport_lrineau_Fedora-Release.gz](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.1-Ic-53/Segment_Delaunay_graph_2_Examples/TestReport_lrineau_Fedora-Release.gz). Is that normal?

Actually, the printing of the seed seems to be removed when `CGAL_HEADER_ONLY` is defined. Now that it is the default, since CGAL-5.0, only the rare platforms with `CGAL_NO_HEADER_ONLY` will display the seed. See:
https://github.com/CGAL/cgal/blob/eb9b8e6c52c2ccaace56e977f7e43a6702a6b382/Random_numbers/include/CGAL/Random.h#L233-L242

**Comment by MaelRL** [comment]
I don't have any hit on this error for any testsuite beyond CGAL 4.12; maybe it can be closed?
