### ISSUE TITLE
Polyhedron demo:  multi-colored point set -> unicolor

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#2481]
## Issue Details

Given a point set with points with several colors, add a feature to give them a single color.

@maxGimeno can you please add that.

**Comment by sloriot** [comment]
Do you mean dropping the color property?

**Comment by maxGimeno** [comment]
There is already the ShadedPoints that ignores the color value, given
normals.

2017-10-02 17:25 GMT+02:00 Sebastien Loriot <notifications@github.com>:

**Comment by afabri** [comment]
No idea if it is better to drop the color or not. Maybe do it as you do it for a surface (colorized by Surface Mesh Segmentation, for example).
