### ISSUE TITLE
Split packages with sub-packages

### ISSUE THREAD

**Issue by bo0ts** [CGAL/cgal#249]
We have a few packages which are logically but not physically separated. Those are:

- Arrangement_on_surface_2 (contains Sweep_line_2)
- Kinetic_data_structures (contains Kinetic_framework)
- Point_set_processing_3 (contains Property_map)
- Triangulation_2 (contains TDS_2)
- Triangulation_3 (contains TDS_3)

splitting them should not:

- complicate anything
- cause ownership issues (contained packages have no package_info in most cases)

but it would:

- make scripts that handle documentation a lot easier
- make documentation building from a release possible
- improve uniformity

We should move code and documentation of the sub-packages into their own packages.

**Comment by afabri** [comment]
I started taking care of this.

**Comment by MoniqueTeillaud** [comment]
A question, just to make sure that I understand well:
for T2 (and T3), does it mean that we should split the package into 2 
packages? i.e. have 2 directories Triangulation_2/ and 
Triangulation_data_structure_2/ instead of only one?

I guess that I don't have an objection. It is easy to do for the manual 
(there are already 2 different sub-directories). But it looks more 
complicated for the code and testsuite.

**Comment by afabri** [comment]
Hi Monique, you understand it correctly.  To get started I did this split for the documentation only, in the branch  CGAL-split_packages-GF.   I also moved some examples, and few header files.   There are several warnings about \refs where I need @sloriot or @bo0ts  to help me.   
I am motivated to move include/CGAL/*.h files.
I am motivated to move test files, but I am not motivated to split test files in several files.

**Comment by MoniqueTeillaud** [comment]
Hi Andreas
I hope that testfiles for T3 and TDS3 are different, but honestly I 
don't quite remember. And I have no clue for T2/TDS2.
good luck!

**Comment by lrineau** [comment]
The branch Andreas has created for that task seems to be `cgal-dev/CGAL-split_packages-GF`.

**Comment by afabri** [comment]
@bo0ts, could you have a look, if what I did fits your needs.
What I finally have not done, is to dispatch header files for the Kinetic_ ...   packages

**Comment by lrineau** [comment]
If that is not easy to split the code of Kinetic, would it be easier to *merge the documentation* (split in two) of that package?

The two user manual could be merged into one (one being a sub-section of the other). And I imagine reference manual are easy to merge.

**Comment by afabri** [comment]
The package is not that important for me.
Also I think that for what Philip wants to automatize
it is good enough that doc is split.
I went the extra mile for the other packages.

**Comment by lrineau** [comment]
I had not understood what you did. Now I have. It seems you did split the documentation of the two Kinetic chapters into two different "CGAL packages" (directories at the root of the Git layout). I agree that is sufficient.

**Comment by sloriot** [comment]
I fixed the documentation building errors. See CGAL/cgal-dev@04aafa27(this one is far from perfect since it implies duplicating examples), CGAL/cgal-dev@baf91459, and CGAL/cgal-dev@8601e5ef

**Comment by afabri** [comment]
Can't we include examples from other packages?

Or should we reduce the examples in the chapter
about property maps to some toy examples?

I would favor the latter.

**Comment by sloriot** [comment]
Nope because of the different layout between release and branch. Well we certainly could but what's the point of inlining twice the same example? Maybe \ref is working.

I think we should change the examples in Property_map and/or refer to those in `Point_set_processing`

**Comment by afabri** [comment]
Twice the same example is ok (without copying the cpp, but refering to it), if ni one chapter we want to explain property maps, and in another chapter point set processing.
But, again, would it not be better to have trivial examples in the property map user manual?

**Comment by sloriot** [comment]
Yes, that's what I meant by "I think ..."

**Comment by afabri** [comment]
Note that even in 4.6  the examples are there two times. So nothing was added.

**Comment by bo0ts** [comment]
@afabri I looked through the commits and this is exactly what I had in mind when I wanted to split the packages.

Currently I don't see an easy way to inline examples from another package without duplicating the source code.

**Comment by afabri** [comment]
The long term goal is to have property map specific examples
instead of copying them.
