### ISSUE TITLE
Polyhedron_demo_hole_filling_plugin should be dynamic properties instead of the linear search in get_hole_visualizer()

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#250]
See https://github.com/CGAL/cgal/issues/236#issuecomment-127354458

**Comment by sloriot** [comment]
Fixed in CGAL/cgal-public-dev@3291077b, CGAL/cgal-public-dev@3291077b, and CGAL/cgal-public-dev@e3c53da3
