### ISSUE TITLE
Is CGAL available on any of the C++ package manager available for all platforms.  

### ISSUE THREAD

**Issue by justinjk007** [CGAL/cgal#2527]
Is it available anywhere like that. Why not ?

Is it possible for you guys to add it to [Hunter](https://github.com/ruslo/hunter). They have documentation on how to add packages with dependencies and I know CGAL has boost as one of the dependencies which hunter already have .

**Comment by HunorSzabo** [comment]
Would be nice to have it with [Conan](https://github.com/conan-io/conan) as well.

**Comment by justinjk007** [comment]
The only problem I have with Conan is you have to have python installed and then install Conan via python. 
For a C++ package manger all I should need is C++ tools/Compiler.

Plus CGAL is already a CMake project so adding it to hunter seems pretty easy.

**Comment by mglisse** [comment]
https://anaconda.org/conda-forge/cgal ?

**Comment by lrineau** [comment]
I don't think that is the role of the CGAL upstream developers to maintain the various packages of CGAL around the world.

You already mentioned three cross-platform package managers, and there are a lot of platform-specific package managers: 
  - brew, macports for macOS,
  - nuget, pkg, for Windows,
  - a lot of package managers for each Linux distribution.

We cannot cope with those numbers.

**Comment by justinjk007** [comment]
@lrineau I agree with that point, but there are cross platform package mangers designed just for C++ like Hunter or Conan. They could at-least look into those. From what I understand if you are already using cmake Setting up your package and uploading the binaries are very easy for Hunter.

**Comment by justinjk007** [comment]
@mglisse I don't understand, is that package for python or C++, why are they asking to install Python and what is conda ?

**Comment by lrineau** [comment]
@justinjk007 I do not know Hunter, and it seems you do know it. Could you create the Hunter package yourself?

**Comment by justinjk007** [comment]
If its fine with you then I can look into adding CGAL into Hunter. I have never added packages before but I will find time this week and add it to Hunter, thanks for allowing me to do so. I am very excited and will furiously go through there documentation to do so thanks.

**Comment by lrineau** [comment]
Good! Let us know if you encounter any difficulty. We will try and help as much as possible.

**Comment by justinjk007** [comment]
Thank you very much

**Comment by justinjk007** [comment]
Ok, so I have been digging around couple of places and found out that Conan package manager already have CGAL added by somebody. I think everyone is moving towards conan now. Also for Windows, microsoft is working on [vcpkg](https://github.com/Microsoft/vcpkg), some body also added CGAL there too, about 6 hours ago. So I can easily install CGAL now on all platforms very easily now. Package managing in C++ got better.
