### ISSUE TITLE
Platform x64_Cygwin-Windows10_MSVC2013-Release-64bits has the compilation flags of a Debug platform

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#2531]
https://cgal.geometryfactory.com/CGAL/testsuite/results-4.11-I-94.shtml#platform8

**Comment by maxGimeno** [comment]
I replaced the build type by Release. I didn't see anything else, if I missed it please tell me.

**Comment by lrineau** [comment]
One common error is to let `/DNDEBUG`, whereas the CGAL testsuite only supports `/DCGAL_NDEBUG`.

You can have a look at the flags in the first table at the [CGAL testsuite][1] and compare with the flag the platform uses when you try it.

[1]: https://cgal.geometryfactory.com/CGAL/testsuite/results-4.12-Ic-63.shtml

**Comment by maxGimeno** [comment]
I replaced all the /DNDEBUG in the Release platforms of Gauguin.

2017-10-12 16:00 GMT+02:00 Laurent Rineau <notifications@github.com>:
