### ISSUE TITLE
Prerequisites problem in PMP does_bound_a_volume()

### ISSUE THREAD

**Issue by maxGimeno** [CGAL/cgal#2543]
## Issue Details
In the source code of PMP::does_bound_a_volume(), in corefinement, there is an assertion checking if the input triangle mesh is closed, but there is no mention of this prerequisite in the doc. I am not sure if the prerequisite is missing in the doc or if the assertion should not be there. 

@sloriot  what do you think ?

**Comment by janetournois** [comment]
As explained in the [Definitions](https://doc.cgal.org/latest/Polygon_mesh_processing/index.html#coref_def_subsec) section of the user manual, the fact of bounding a volume makes sense only if the input triangulated surface is closed.
We could add a precondition in the doc if you think it is not clear.

**Comment by maxGimeno** [comment]
I do. I also think that the documentation for the NamedParameters of this function is a bad copy-paste, as it mention `tm1` and `tm2` when there is only `tm` in the arguments.
