### ISSUE TITLE
Workaround a Boost warning in CGAL::Random::uniform_int

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#2555]
## Issue Details

@janetournois, in https://github.com/CGAL/cgal/pull/2315#issuecomment-337274878:
> note that we could consider moving my fix of commit fb4f08731791cf11220886e70b6d039d818284c6 to `CGAL::Random::uniform_int`
In boost 1.59.0 (at least), `boost/random/linear_congruential.hpp` hardcodes
`typedef boost::uint32_t result_type;` which leads to a conversion warning

**Comment by afabri** [comment]
@lrineau @janetournois   Where does the problem show up?

**Comment by janetournois** [comment]
It should show up if you use (with boost 1.59 at least)
```
CGAL::Random random(0);
random.uniform_smallint(std::size_t(0), std::size_t(20));
```

**Comment by afabri** [comment]
What puzzles me is that in [test_Random.cpp](https://github.com/CGAL/cgal/blob/master/Random_numbers/test/Random_numbers/test_Random.cpp#L60) we test it with `std::ptrdiff_t` and we don't get a warning.  I  thought maybe it is related to the fact that `std::size_t` is unsigned, but when I try it with `unsigned int` there is also no warning.

**Comment by janetournois** [comment]
boost hard codes `boost::uint32_t`. Maybe it is compatible with `unsigned int`?

**Comment by afabri** [comment]
Where??

**Comment by janetournois** [comment]
in `boost/random/linear_congruential.hpp`

**Comment by lrineau** [comment]
https://github.com/CGAL/cgal/issues/2555#issuecomment-365925561:
> boost hard codes `boost::uint32_t`. Maybe it is compatible with `unsigned int`?

On Windows and Linux 64 bits `int` is a 32 bits type. See https://en.wikipedia.org/wiki/64-bit_computing#64-bit_data_models
