### ISSUE TITLE
Polyhedron demo feature request: length of polyline item

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#2556]
## Issue Details

This is a feature request: 
I would be interested to know the length of a polyline, either coming from a selection or from a geodesic shortest path. This could be displayed in the statistics. If there is more than one polyline one might display the length of the shortest and of the longest polyline, or alternatively only show it if there is a single polyline.

@maxGimeno can you please add that.

**Comment by afabri** [comment]
Can you please also dump the length of the polyline after each click in the polyline selection.

**Comment by maxGimeno** [comment]
What is a polyline selection ?

**Comment by afabri** [comment]
Path between vertices
