### ISSUE TITLE
STEP(B-Rep) conversion to STL(Nef-Polyhedron), loss of information, stability?

### ISSUE THREAD

**Issue by HunorSzabo** [CGAL/cgal#2566]
Dear Developers of CGAL,

I would like to elaborate on a few topics came up during the usage of CGAL in our project. 
As of CGAL doesn't have `.STEP/.STP ` support we need to convert our `.STEP/.STP` files(already having B-Rep information) to `.STL` and than to Nef-Polyhedron(B-Rep of CGAL). 

Unfortunately, after reading the `.STL`, creating the polyhedron fails at the "`is_polygon_soup_a_polygon_mesh`" without the check we get: "`Expr: fd != boost::graph_traits<PM>::null_face()`"
this happens approx. 30% of the time (20 files tried, 6 failed) as I noticed this is correlated with the size of the mesh, mesh under 8000 points work fine, but above that starts failing. 

My thread is not explicitly about the error, but more like the practicaly of this method i.e. 
Do you think we could make the `.STL` to `B-Rep` conversion work in 98% of the cases or this is not achievable? 
Could you suggest better approach? The conversion to `.STL` causes  some instability(loss of information), would work better directly using `.STEP` files  since that already includes `B-Rep`, unfortunately this is not supported by CGAL. Is there any alternative approach?

I am happy to provide more information, please feel free to ask for clarification, details if I missed something important,
Thank you for you help and for the great job you are doing on this project,
Best,
Hunor

**Comment by afabri** [comment]
What is the STWP B-Rep?  A polyhedral surface or a Nurnbs patch? 
Concerning the STL file, maybe share it with us so that we can have a look, comment, fix,....

**Comment by sgiraudot** [comment]
@HunorSzabo Can you provide the STL file? The error suggests the polyhedron embedded is not orientable, but it is hard to tell without having a look at the data. The conversion will work 100% of the case if the polyhedron in the file is orientable and 0% otherwise...

**Comment by HunorSzabo** [comment]
@sgiraudot @afabri  Apologies for the late answer, I hoped I can fix the issue with the STP->STL conversion but seems like it doesn't really work. 
I attached the [simplest example](https://drive.google.com/file/d/1r4iAN1-HTX_6bFhRpSPo4CGANZ4nzRYo) I found. 
[Image of the part](https://drive.google.com/file/d/1GNNuGzStT2oFvCMRO783PNjguPL08ff8/view?usp=sharing)

**Comment by sloriot** [comment]
It's not clear if the step file already contains the triangulated surface of if it only contains nurbs/spline patches. Some parts being inconsistant I suspect the latter. There are some non-manifold edges (or even maybe non-manifold vertices) in the STL file. You can call the function [`orient_polygon_mesh()`](https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__orientation__grp.html#gaadc5bac3072b11d2313e40043c729d0a) to duplicate those elements and be able to load the model as polyhedron. But as I said there is some cleaning need then because some adjacent patches are not correctly connected.

**Comment by HunorSzabo** [comment]
Thank you for the guidance @sloriot , I tried to call orient_polygon_mesh(), it failed and resulted in an invalid polyhedron, I will try to deeper understand the problem. 

On the other hand to isolate the issue, I tried to use a really [simple cube example](https://drive.google.com/file/d/1gYBhj75tfOqtSyfZ3jabGBAeQwdixOA7/view?usp=sharing)([figure](https://drive.google.com/file/d/1qU8Ol9CvslTUML9y6xYqUG_blcKcnpeA/view?usp=sharing))
)) which also failed, it only contains triangulated surfaces, but it is still failing.

**Comment by HunorSzabo** [comment]
Thank you for the guidance @sloriot , I tried to call orient_polygon_mesh(), it failed and resulted in an invalid polyhedron, I will try to deeper understand the problem. 

On the other hand to isolate the issue, I tried to use a really [simple cube example](https://drive.google.com/file/d/1gYBhj75tfOqtSyfZ3jabGBAeQwdixOA7/view?usp=sharing)([figure](https://drive.google.com/file/d/1qU8Ol9CvslTUML9y6xYqUG_blcKcnpeA/view?usp=sharing))
which also failed, it only contains triangulated surfaces, but it is still failing. 

Based on blender there are not non manifold edges in this file.

**Comment by sloriot** [comment]
I could open `simple.stl` in the demo without any issue and it was a valid polyhedron (no need to call the orientation function). I suspect you have some issue in your code.

**Comment by afabri** [comment]
The other test_file.stl can also be loaded in the CGAL Polyhedron demo. Loading it you get a polygon soup. This can then be converted into an oriented surface, which looks like below.  Running the self-intersection test you see in brown triangles that intersect. My guess is that you have points on your triangles which have close but not identical coordinates. So maybe you can snap them. 

![image](https://user-images.githubusercontent.com/3263539/33183019-7ddcaa34-d076-11e7-8402-46fd693bf1b0.png)

**Comment by HunorSzabo** [comment]
I am happy to hear that the issue is on my side, many thanks for checking the test files and for the explanation. I will try to diff my code with the `CGAL Polyhedron demo`.

It is quite simple what I put together:
```
typedef CGAL::Exact_predicates_inexact_constructions_kernel  Kernel;
typedef std::vector<CGAL::cpp11::array<double, 3>> Points_3;
typedef CGAL::cpp11::array<int,3> Facet;
typedef std::vector<Facet> Surface;
typedef Kernel::Iso_cuboid_3 Iso_cuboid;

typedef CGAL::Polyhedron_3<Kernel> Polyhedron;

..... 

    Points_3 meshPoints;
    Surface mesh;
    Polyhedron polyhedron;
..... 

void readFile(string filename) {
    std::ifstream stream(filename);
    if(stream) {
        std::cout << "File is read to stream " << std::endl;
    } else {
        throw std::invalid_argument("Error! Cannot open file");
    }
    if (CGAL::read_STL(stream, meshPoints, mesh))
    {
        std::cout << "File is loaded" << std::endl;
    } else {
        throw std::invalid_argument("Error: invalid STL file");
    }
}

void CGALPartAnalyzer::convertPolyhedron() {
    bool orientedStuff = CGAL::Polygon_mesh_processing::orient_polygon_soup(this->meshPoints, this->mesh);
    std::cout << "Orientation succeded? " << (orientedStuff ? "Yes" : "No") << endl;
    if (CGAL::Polygon_mesh_processing::is_polygon_soup_a_polygon_mesh(this->mesh)) {
        CGAL::Polygon_mesh_processing::polygon_soup_to_polygon_mesh(this->meshPoints, this->mesh, this->polyhedron);
    }
    if(!polyhedron.is_valid() || polyhedron.empty()) {
        throw std::invalid_argument("Error: Invalid face-graph, not valid or empty.");
    }
}
```

**Comment by HunorSzabo** [comment]
@afabri , @sloriot  
I see now, that I missed to set binary mode of the input stream. `simple.stl` works without any issue, however, after I call `CGAL::Polygon_mesh_processing::polygon_soup_to_polygon_mesh(meshPoints, mesh, polyhedron);` on `test_file.stl` I still get an invalid polyhedron checking with `polyhedron.is_valid()`. 

So as you can see on my code snippet above I call `bool orientedStuff = CGAL::Polygon_mesh_processing::orient_polygon_soup(meshPoints, mesh);`  

The only problem is that after this I am getting stuck with an assert(`is_closed(tmesh) ../Polygon_mesh_processing/measure.h:498`) during the calculation of the volume:
`auto volume = CGAL::Polygon_mesh_processing::volume(polyhedron);`.

I tried to fix that by `CGAL::Polygon_mesh_processing::stitch_borders(mesh);` or running the `hole_filling_example ` but still I get stuck with the `is_closed(tmesh)` assert.

Could you give me a guideline how should I proceed to get rid of those bordered edges and determine the volume.

Thank you for your time and help!

**Comment by sloriot** [comment]
As I said, fixing your mesh to make it close requires splitting some edges to make them match with supposedly adjacent one. Right now there is no high level tool in CGAL doing the job. What you need to do is to consider all border edges that did not have a match using stitching (there is also an epsilon-stitching that is available in the polyhedron demo if you want to have a look). Then for each segment end point that does not have a matching other segment endpoint, you need to find if there exists another segment _almost_ containing the endpoint and split that segment. If you find a projection for all those vertices then another call to stitch will close the mesh.

Note that if you simply want to compute the volume, you can disable the CGAL assertions by defining `CGAL_NDEBUG`.

I'm closing the issue as there is no pb nor issue in CGAL here.
