### ISSUE TITLE
Missing types in BGL concepts

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#2570]
`HalfedgeGraph`, `FaceGraph`, `HalfedgeListGraph`, and `FaceListGraph` concepts do not document the types the user must provide through `graph_traits` .

**Comment by afabri** [comment]
But isn't it enough that there is a [`\refines IncidenceGraph`](https://cgal.geometryfactory.com/CGAL/doc/master/BGL/classHalfedgeGraph.html)

**Comment by MaelRL** [comment]
https://cgal.geometryfactory.com/CGAL/doc/master/BGL/classEdgeListGraph.html is missing a link to http://www.boost.org/doc/libs/1_65_1/libs/graph/doc/Graph.html.

**Comment by sloriot** [comment]
I don't think `face_descriptor` and `halfedge_descriptor` nor their iterator counterparts are mentioned anywhere in boost :)
