### ISSUE TITLE
CGAL Swig bindings for convex_hull_3 and cylinders

### ISSUE THREAD

**Issue by Pranava29** [CGAL/cgal#2581]
Hi,

## Issue Details

We are looking for swig java bindings for 3D convex hulls and cylinders. We went through your [swig project](https://github.com/CGAL/cgal-swig-bindings) and could not find the required java library or examples for these shapes after building the cgal-swig project.

We found that we can build the required package using the instructions given here https://github.com/CGAL/cgal-swig-bindings/wiki/User_package but is this the right way to go about for optimal performance? 

## Environment

* Operating system: macOS Sierra 10.12.6
* Compiler: CGAL folder generated on building swig project. Runtime: Using  ```-Djava.library.path=libs/``` where i stored .jnilib files in the libs folder
* Release or debug mode:
* Specific flags used (if any):
* CGAL version: 4.11
* Boost version:  
* Other libraries versions if used (Eigen, TBB, etc.): Eigen - 3.3.4

**Comment by sloriot** [comment]
The performances will depend on how you wrote the wrappers but you must have the same performances using `User_package` compared to a _regular_ package.

**Comment by Pranava29** [comment]
Thank you @sloriot for your response.
Also i wanted to know, if we ever wanted support from CGAL or GeometryFactory to add such java bindings (adding bindings for Cylinders or 3d convex hulls for instance) to the existing/custom swig cgal project, how do we proceed ?

**Comment by sloriot** [comment]
Depending on the task, we estimate the time we'll have to spend and you get a quote. You can contact @afabri to get more information.
