### ISSUE TITLE
Polyhedral_complex_mesh_domain_3 doc incomplete

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#2586]
Looking at the [constructor](https://cgal.geometryfactory.com/CGAL/doc/master/Mesh_3/classCGAL_1_1Polyhedral__complex__mesh__domain__3.html#a8337b598d679bd000b08fdbcaeb5f3df), the fact that the incident subdomains in the pairs must be the subdomains respectively on the negative and positve size of the mesh is not documented.
In addition, there is a rendering issue in the doc. My guess is that you should remove one `/` before `/// Constructor`.

**Comment by lrineau** [comment]
Fixed by 576a3799eb299d185b332f1ce17098c42bb9b249 in #3873.
