### ISSUE TITLE
Intersection detection between compound geometries

### ISSUE THREAD

**Issue by Pranava29** [CGAL/cgal#2597]
##Problem/Question
Im looking for a way to detect intersection between compound geometries. Each compound geometry is a list of different types of geometries (say cylinders, 3D convex hulls, spheres, etc.). I'm looking for a way to detect conflict/intersection between two or more compound geometries. Once an intersection is detected, i would like to know which one intersected.

1. Can you please suggest a way to deal with this problem? I would like to know if there is a data structure in CGAL which would hold such geometries
2. Does adding 3d vertices to delaunay's 3d triangulation result in a similar 3d convex hull as adding the 3d vertices to the 3d_convex_hull constructor?

**Comment by sloriot** [comment]
How is your geometry specified? Are they triangle meshes?

**Comment by MaelRL** [comment]
For your second question, the 3D triangulation is indeed a set of bounded cells who form a partition of the bounded volume whose boundary is the convex hull, and a set of unbounded cells on the "other" side.

Thus, if you grab all the faces opposite to the infinite vertex, you will get the  convex hull.

**Comment by Pranava29** [comment]
@sloriot , the geometries for various shapes are different
Cylinder - Shape_detection_3
3D Convex hull - generated from a set of 3d vertices by 
Sphere - Shape_detection_3 / Kernel shape

**Comment by Pranava29** [comment]
thanks @MaelRL

**Comment by Pranava29** [comment]
@sloriot , 
Hi, do you need any more clarification from my end?

**Comment by sloriot** [comment]
The package [Intersecting Sequences of dD Iso-oriented Boxes](https://doc.cgal.org/latest/Box_intersection_d/index.html) can be used for filtering your intersection if you have many primitives and also for all the triangles of your primitives.
The orientation predicate can also be used to determine if a primitive is inside the convex hull (in case the convex hull boundary is free from intersection).
There is no cylinder object in CGAL.

**Comment by Pranava29** [comment]
Thanks @sloriot  for your quick response.

I thought cylinders are possible with Point_set_shape_detection_3 library. 

https://doc.cgal.org/latest/Point_set_shape_detection_3/classCGAL_1_1Shape__detection__3_1_1Cylinder.html

**Comment by sloriot** [comment]
There is no geometric type nor geometric predicates involving cylinders (except for shape detection as pointed out).
I close the issue as there is not much we can do.
