### ISSUE TITLE
Wrong functor required/used

### ISSUE THREAD

**Issue by bo0ts** [CGAL/cgal#260]
The AABBGeomTraits require the functor [Compute_closest_point_3](http://doc.cgal.org/latest/AABB_tree/classAABBGeomTraits.html#a97e587bad84dcd1e90d00fb18a134762), but this signature is never used in `AABB_tree` code.

The class `AABB_traits`  provides a functor `Closest_point` which calls the free function `internal::nearest_point_3` which seems to be used instead. Note that even if this functor is renamed it is still in the wrong class (should be in the geomtraits).

**Comment by sgiraudot** [comment]
Can this issue be fixed? @palliez, you are one of the maintainer (with Camille Wormser who I can't find on GitHub), can you have a look at this?

**Comment by janetournois** [comment]
this issue is fixed by PR #1340.

However, `Compute_closest_point_3` should still be moved to the Kernel. I create a new issue for that.

**Comment by sloriot** [comment]
#1356 reverted the merge of the #1340 that was incomplete and not meant for 4.9
