### ISSUE TITLE
Polyhedron demo: depth propblems with QGLViewer 2.7.0

### ISSUE THREAD

**Issue by maxGimeno** [CGAL/cgal#2601]
## Issue Details
For some reason, in the latest QGLViewer version, the depth component of the fragments that are read during a selection is always 1, which makes the selection fail. It needs to be investigated and fixed.

## Environment
* Other libraries versions if used (Eigen, TBB, etc.): QGLViewer v2.7.0

**Comment by lrineau** [comment]
Is that still an actual bug?

**Comment by maxGimeno** [comment]
Nope, i forgot to mention it in #2607, but I am pretty sure i fixed the problem in there.

**Comment by lrineau** [comment]
Let's wait for #2904 and then @sloriot will try again.
