### ISSUE TITLE
Update search Search_traits_3 requirements

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#261]
The `AABB_tree<AT>` internally use the spatial searching and in particular instantiates Search_traits_3 with AT. This implies according to that page that the concept `AABBTraits` must be a Kernel.

A clean solution is adding a new concept in Spatial searching that describes requirements of the template parameter of Search_traits_3. Then we can say that AABBTraits refines this concept. For consistency, we do the same for the template parameter of Search_traits_2.

**Comment by sgiraudot** [comment]
@palliez, you are one of the maintainers of the package, what do you think about this?

Can anybody take care of this?

**Comment by janetournois** [comment]
I'm doing it
