### ISSUE TITLE
Small viewer for all CGAL data-structure; use the viewers in examples

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#2611]
Tasks discussed on Wedneday during theh CGAL meeting at Sophia Antipolis, November 13-17, 2017:
> Small viewer for all CGAL data-structure; use the viewers in examples

https://cgal.geometryfactory.com/CGAL/Members/wiki/Meetings/Sophia17bis#Wednesday_Morning

@gdamiand is leading the effort, and work with @maxGimeno 

There are two steps:
1. Have a simple viewer usable for most data structures in CGAL.
2. Factorize the code with the code in `demo/Polyhedron/`.

**Comment by afabri** [comment]
@gdamiand Did you make a PR for the pre-approved small feature?

**Comment by gdamiand** [comment]
Not yet; There is one technical point concerning CMake and qglviewer and I am waiting @lrineau feedback. Maybe we will discuss this with Laurent at the next dev meeting ?

**Comment by afabri** [comment]
so we can change the milestone to 4.13

**Comment by gdamiand** [comment]
The pr is done: cf [PR2835](https://github.com/CGAL/cgal/pull/2835)
