### ISSUE TITLE
warning: catching polymorphic type 'class CGAL::Uncertain_conversion_exception' by value [-Wcatch-value=]

### ISSUE THREAD

**Issue by mglisse** [CGAL/cgal#2615]
> include/CGAL/Filtered_predicate.h:171:7: warning: catching polymorphic type 'class CGAL::Uncertain_conversion_exception' by value [-Wcatch-value=]

This appears to be a new warning in gcc-8, which triggers all over the place in CGAL. Apparently we are supposed to catch Uncertain_conversion_exception by reference instead.

**Comment by afabri** [comment]
Does that concern all exceptions?

**Comment by lrineau** [comment]
Yes. That is a FAQ on StackOverflow, and a good answer is https://stackoverflow.com/a/2023045/1728537.

**Comment by lrineau** [comment]
That is already fixed since July 2017 (by PR #2287), in CGAL-4.11. Only CGAL-4.10.x or before are impacted.

**Comment by mglisse** [comment]
> Does that concern all exceptions?

Only those that are polymorphic (virtual functions). If you throw an int, you can catch it by value.

> That is already fixed since July 2017

Uh, that's the second time I got confused that way in a very short time. Ah, both were actually on the same day, I was on the wrong branch and didn't notice 😞  Sorry.

Actually, we are still catching by value in a few places if I am not on the wrong branch again: Mesh_3/archive/applications/thread_queue.h, Polyhedron/demo/Polyhedron/MainWindow.cpp, Polyhedron/demo/Polyhedron/Plugins/Mesh_2/Mesh_2_plugin.cpp...

**Comment by lrineau** [comment]
> Actually, we are still catching by value in a few places if I am not on the wrong branch again: Mesh_3/archive/applications/thread_queue.h, Polyhedron/demo/Polyhedron/MainWindow.cpp, Polyhedron/demo/Polyhedron/Plugins/Mesh_2/Mesh_2_plugin.cpp...

You are right. That is strange the g++8 have in the test suite do not warn on the bad `catch` we have in `demo/Polyhedron/`. For the one in `Mesh_3/archive/`... it is obvious it is an attic zone that is no longer tested.
