### ISSUE TITLE
periodic 3d alpha-shape memory corruption

### ISSUE THREAD

**Issue by mglisse** [CGAL/cgal#2616]
When I compile on linux-x86_64 with a recent gcc or clang and specify the flag `-fsanitize=address`, then run this program on the file http://geometrica.saclay.inria.fr/team/Marc.Glisse/tmp/sphere1, the sanitizer complains. Surprisingly, while the error is during the alpha-shape initialization for gcc and during the filtration computation for clang, both eventually stop in `NT_converter<double, CGAL::Gmpq>`. clang's `-fsanitize=memory` complains somewhere in std::map instead.

This is with @MaelRL 's branch P3T3-Fix_Gabriel_functions-GF. I am using Tag_true because I was getting some infinite filtration values. With CGAL-4.11 I was getting assertion failures during circumradius computations. Without the sanitizer I get weird crashes in our code later on, which made me suspect some memory corruption. scanf is because one sanitizer was complaining about ifstream...

```c++
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/Periodic_3_Delaunay_triangulation_traits_3.h>
#include <CGAL/Periodic_3_Delaunay_triangulation_3.h>
#include <CGAL/Alpha_shape_3.h>
#include <CGAL/iterator.h>

#include <stdio.h>
#include <vector>

using K = CGAL::Exact_predicates_inexact_constructions_kernel;
using PK = CGAL::Periodic_3_Delaunay_triangulation_traits_3<K>;
using mytag = CGAL::Tag_true;
using DsVb = CGAL::Periodic_3_triangulation_ds_vertex_base_3<>;
using Vb = CGAL::Triangulation_vertex_base_3<PK, DsVb>;
using AsVb = CGAL::Alpha_shape_vertex_base_3<PK, Vb, mytag>;
using DsCb = CGAL::Periodic_3_triangulation_ds_cell_base_3<>;
using Cb = CGAL::Triangulation_cell_base_3<PK, DsCb>;
using AsCb = CGAL::Alpha_shape_cell_base_3<PK, Cb, mytag>;
using Tds = CGAL::Triangulation_data_structure_3<AsVb, AsCb>;
using P3DT3 = CGAL::Periodic_3_Delaunay_triangulation_3<PK, Tds>;
using Alpha_shape_3 = CGAL::Alpha_shape_3<P3DT3,mytag>;
using Point_3 = PK::Point_3;
using Alpha_value_type = Alpha_shape_3::FT;
using Object = CGAL::Object;

int main(int argc, char* const argv[]) {
  if (argc != 2) {
    std::cerr << "Error: want exactly one argument, name of file\n";
    abort();
  }

  std::vector<Point_3> lp;
  double x,y,z;
  FILE*f=fopen(argv[1],"r");
  while(fscanf(f,"%lf %lf %lf",&x,&y,&z)==3)
    lp.emplace_back(x,y,z);

  P3DT3 pdt(PK::Iso_cuboid_3(-1,-1,-1,1,1,1));
  pdt.insert(lp.begin(), lp.end(), true);
  if (pdt.is_triangulation_in_1_sheet()) pdt.convert_to_1_sheeted_covering();
  else abort();
  std::cerr << "Periodic Delaunay computed.\n";

  Alpha_shape_3 as(pdt, 0, Alpha_shape_3::GENERAL);
  std::cerr << "Alpha_shape_3 initialized.\n";

  std::vector<Object> the_objects;
  std::vector<Alpha_value_type> the_alpha_values;

  auto disp = CGAL::dispatch_output<Object, Alpha_value_type>(std::back_inserter(the_objects), std::back_inserter(the_alpha_values));

  as.filtration_with_alpha_values(disp);
}
```

**Comment by MaelRL** [comment]
You cannot set `ExactAlphaComparisonTag` to `Tag_true` if you're using periodic triangulations. See code/doc: 
```
  // The Exact Comparison Tag cannot be used in conjonction with periodic triangulations
  // because the periodic triangulations' point() function return a temporary
  // value while the lazy predicate evaluations that are used when the Exact tag
  // is set to true rely on a permanent and safe access to the points.
```

I'm a bit confused that you can even compile... The line:
```
  CGAL_static_assertion(
   (boost::is_same<ExactAlphaComparisonTag, Tag_false>::value) ||
   (boost::is_same<typename Dt::Periodic_tag, Tag_false>::value));
```
is supposed to catch that (and does so for me when I try to compile your example).

Workaround is what I mentioned when I fixed the traits: you need a safe access to the points of the periodic triangulation. If you rely a lot on that exact tag, I can add a `CGAL::Periodic_3_triangulation_3_with_stored_points` which puts all values of `tr.point(c,i)` for all cell handles `c` and indices `i` in a container and overloads `tr.point()`. What do you think ?

**Comment by mglisse** [comment]
> You cannot set ExactAlphaComparisonTag to Tag_true if you're using periodic triangulations.

Ah, right, I remembered it couldn't be used with regular triangulations, and it was periodic instead, sorry about that, not a bug then.

**Comment by mglisse** [comment]
> I'm a bit confused that you can even compile...

I had tried with 4.11 (compiles and asserts at runtime) and with your branch fixing some issue in P3T3, which is also based on 4.11, but apparently not with master, I really should have done that.

**Comment by mglisse** [comment]
And this whole thing came because I was too tired last night, the inexact version actually gives good results in this case (I compared with Epeck right now), so don't take this report as a reason to increase the priority for handling Tag_true. Sure, if you fix it that's good (sorry, I don't know that code and have no opinion on the best approach), but we still have alternatives, and your new check in 4.12 will nicely prevent accidents.

**Comment by MaelRL** [comment]
No problem, I was confused by the missing static assertion because I thought I added it with P3RT3-based alpha shapes (which made it in 4.11), but it was with P2(D)T2-based alpha shapes, which didn't make it.
