### ISSUE TITLE
Is there a way to generate a cylindrical shape in CGAL?

### ISSUE THREAD

**Issue by Pranava29** [CGAL/cgal#2618]
## Issue Details
I'm working on a problem to detect intersection of shapes in 3D. One of the shapes i'm supposed to check is a cylinder. I'm given 2 points (they form the axis of the cylinder) in space and the diameter of the cylinder. Is there a way to generate a cylinder in space or an equivalent mesh/shape?

**Comment by GilesBathgate** [comment]
As an unofficial answer:

Essentially if you need to create a polyhedron with faces that approximate the shape of a cylinder then you can just use the Polyhedron incremental builder: https://doc.cgal.org/latest/Polyhedron/classCGAL_1_1Polyhedron__incremental__builder__3.html

To calculate the geometry given height and radius you could look at my code for reference: https://github.com/GilesBathgate/RapCAD/blob/master/src/module/cylindermodule.cpp

The CGAL team could potentially give you a better answer.
