### ISSUE TITLE
Error (I think) intersecting two Triangle_3

### ISSUE THREAD

**Issue by mpbeede** [CGAL/cgal#2619]
## Issue Details

I am using the newest CGAL available on Debian as a package--it is NOT the newest version.  After the holiday I will try to install the newest version.

I have an example program.  It intersects two triangles.  One is in the plane Z=0, the other is entirely above that plane, but CGAL computes an intersection that is a line segment.  I am not an expert on C++ or computational geometry, so I may have simply done something wrong.

## Source Code

/*
 * This program demonstrates a possible CGAL bug:
 * 
 * - There are two triangles defined and intersected.
 * - t[0] lies in the plane z == 0.
 * - t[1] does not have any point with z <= 0,
 *   the smallest z value is around 0.66.  Clearly, the
 *   triangles do not intersect (right?)
 *
 * The program prints 
 *   0 1.8 0 0.818182 0.818182 0
 * indicating that CGAL computed a line segment as the
 * intersection.
 *
 * On my system it is sensitive to the exact numeric values
 * used. If I truncate more than a few digits, no inter-
 * section is computed.
*
 * To build, put in empty directory:
 *   cgal_create_cmake_script
 *   cmake .
 *   make
 */

#include <iostream>
#include <CGAL/Simple_cartesian.h>
typedef CGAL::Simple_cartesian<double> K;
typedef K::Point_3 Point;
typedef K::Segment_3 Segment;
typedef K::Triangle_3 Triangle;

using namespace std;

double k1 = 0.3333333432674407958984375;
double k2 = 1.39999997615814208984375;

main()
{
   Triangle t[] = {{{ 2,2,0 }, { 0,0,0 }, { 0,2,0 }},
                   {{ 2*k1, 1, 2*k1 }, { k1,k2,k1 }, { k1,k2,4*k1 }}};
   if ( auto i = intersection(t[0],t[1]) )
      if ( const Point *t = boost::get<Point>(&*i) )
         cout << *t << endl;
      else if ( const Segment *t = boost::get<Segment>(&*i) )
         cout << *t << endl;
      else
         cout << "???" << endl;
   return 0;
}

## Environment

* Linux 64 bit, Debian 8.8
* Compiler: gcc version 6.3.0 20170516 (Debian 6.3.0-18)
* Release or debug mode: 
* Specific flags used (if any): defaults 
* CGAL version: 4.9-1+b2
* Boost version: libboost 1.62
* Other libraries versions if used (Eigen, TBB, etc.): none

**Comment by sloriot** [comment]
You are using a kernel with inexact constructions so what you observe is due to floating point computation. If you replace the kernel by `CGAL::Exact_predicates_exact_constructions_kernel` you should get the correct result. If you just want to know it the two triangles intersect, you can use a kernel with exact predicates only (like `CGAL::Exact_predicates_inexact_construction_kernel`) and the function `do_intersect()`.

See also this FAQ [entry](https://www.cgal.org/FAQ.html#inexact_NT)

**Comment by mpbeede** [comment]
Thanks much.  Sorry for the incorrect report.
