### ISSUE TITLE
How to calculate volume of a polyhedron/mesh?

### ISSUE THREAD

**Issue by HunorSzabo** [CGAL/cgal#2620]
Hi,

I am wondering if there are some examples of calculation the volume of a polyhedron?

When I just call  `CGAL::Polygon_mesh_processing::volume(polyhedron); ` I will get the following exception:

```
CGAL ERROR: assertion violation!
Expr: is_closed(tmesh)
File: CGAL\include\CGAL/Polygon_mesh_processing/measure.h
Line: 498
```

Thank you for your time and effort,
Best,
Hunor

**Comment by sloriot** [comment]
The assertion is telling you that your mesh is not closed, so no volume is defined.

**Comment by HunorSzabo** [comment]
Thank you for the extremely quick answer. It should be closed, but I can patch this by fixing the holes I suppose? This is the file I was using: https://drive.google.com/file/d/1r4iAN1-HTX_6bFhRpSPo4CGANZ4nzRYo/view?usp=sharing
