### ISSUE TITLE
Issue with BOOST_FOREACH on Visual Studio 2015

### ISSUE THREAD

**Issue by janetournois** [CGAL/cgal#2627]
## Issue Details

The use of `BOOST_FOREACH()` seems to corrupt the data when used while modifying the mesh.

In PR #2626, replacing the use of `BOOST_FOREACH()` by c++11 range-"for" loop in the lines corresponding to code modifying the mesh was enough to fix the seg fault.

We had already met that issue in PR #2304, with visual 2015 and 2017.

We could have a `CGAL_FOREACH()` that uses the c++11 for loop for visual >= 2015, and `BOOST_FOREACH()` otherwise.

## Source Code

This is the way our test crashes :
```
void fct(TM& tm)
{
  is_valid(tm); //crashes here
  if(some_boolean_that_evaluates_to_false_in_our_case)
  {
     // code using BOOST_FOREACH, not executed
   }
}
int main()
{
  TM tm;
  is_valid(tm);
  fct(tm);
} 
```
## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows 64 bits
* Compiler: visual 2015
* Release or debug mode: Release with -O2 (Release with -O1 is fine)
* Specific flags used (if any):
* CGAL version: master
* Boost version: 1.59

cc @sloriot

**Comment by sloriot** [comment]
This has been fixed in the master branch targetting CGAL-5.0 by the removal of all `BOOST_FOREACH`.
