### ISSUE TITLE
CGAL Doxygen doc: MathJax CDN shutting down

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#2633]
https://www.mathjax.org/cdn-shutting-down/

> The MathJax CDN hosted at cdn.mathjax.org will be shutting down on April 30, 2017. 
Current and future releases available on other CDN providers.

That did not break about usage because:

> [Updated 2017/04/10]
>
> We will implement a temporary redirect on cdn.mathjax.org to redirect users to cdnjs.

We will have to do something in our Doxygen configuration, because the 
temporary redirection from cdn.mathjax.com to another provider will 
disappear.

As far as I remember, the documentation at https://doc.cgal.org/ will not break, because we ship a copy of MathJax. But all locally compiled/downloaded documentation will have the issue.

**Comment by sloriot** [comment]
Doxygen now recommands https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/
Shall I update our file to that one?

**Comment by lrineau** [comment]
I agree. I imagine that it is also valid for older versions of Doxygen?

What should we do for our old documentation, for previous CGAL version, that is already online?

**Comment by sloriot** [comment]
It is valid for any version.
For the old doc, only 4.11 is relying on cdn.mathjax.org (previous releases are OK). I guess there is a bug in the doc creation script.

**Comment by sloriot** [comment]
`Scripts/developer_scripts/run_doxygen_testsuite` has been updated and 
`-DCGAL_DOC_MATHJAX_LOCATION:STRING=../../MathJax \` was removed by @maxGimeno.
@maxGimeno is there any reason?

**Comment by maxGimeno** [comment]
Probably a mistake

**Comment by sloriot** [comment]
OK I pushed a fix also in #2763

**Comment by sloriot** [comment]
The release of 4.11.1 will fix the pb so we should be good for old versions.

**Comment by lrineau** [comment]
Fixed by #2763.
