### ISSUE TITLE
Polyhedron demo: the multi-selection is broken

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#264]
In the Polyhedron demo, one used to be able to select several items in the scene. That seems to be broken, now. At least in the Siggraph branch.

cc @sloriot

**Comment by lrineau** [comment]
The culprit is the commit 63dca733dccc06aa97889ae3496c261c559ecc4a. I have reverted it in the Siggraph branch.

**Comment by lrineau** [comment]
@sloriot: What was the goal of the commit 63dca733dccc06aa97889ae3496c261c559ecc4a? Do you think the functionality can be restored without breaking the multi-selection in the scene? Because the multi-selection is crucial for several plugins of the polyhedron demo.

**Comment by lrineau** [comment]
Self-answer: commit 63dca733dccc06aa97889ae3496c261c559ecc4a solves #226.

**Comment by sloriot** [comment]
Fixed by CGAL-public-dev@bd1b89c
