### ISSUE TITLE
AABB tree with GCC 4.8.2

### ISSUE THREAD

**Issue by MaelRL** [CGAL/cgal#2640]
To quote https://github.com/libigl/libigl/issues/650:

> 
> Hello,
> 
> The front page of libigl states 
> 
> > The include/igl/copyleft/cgal/*.h headers depend on CGAL. It has come to our attention that CGAL does not work properly with GCC 4.8.
> 
> I cannot find anything related to that in your open or closed issues, could you please detail us what are the issues so that we can look into fixing them?
> 
> Thank you.

In that issue, I was pointed to http://cgal-discuss.949826.n4.nabble.com/Bugs-in-AABBTree-td4660077.html. The AABB tree does use `nth_element` which was bugged in GCC 4.8.2 (see https://gcc.gnu.org/bugzilla/show_bug.cgi?id=58800).

Is this GCC bug indeed the root cause of the problem ? Can we simply add a macro to switch and use `partial_sort` if the compiler is matching that GCC version (if so, need to check exactly when it appeared for them) ?

**Comment by lrineau** [comment]
I remember a discussion where we decided to document the issue and not try to work around it, because we thought that specific gcc version was not wildspread. Any Linux distribution have upgraded to 4.8.3 or later.

If we have time to design a workaround, I am not against it. We were just lazy.

**Comment by lrineau** [comment]
There was a bug introduced in gcc 4.8.2, and then fixed in gcc 4.8.3. Do we really want to write a workaround (such as rewriting our own `std::nth_element`), just to support one buggy version of gcc?

I think we should close this issue with the label `wontfix`.

**Comment by MaelRL** [comment]
It's also from a > 5 years old release of GCC, but I just disliked the dramatic message on libigl.

It's at the very bottom of my priority list though, so I'm alright to close it.

**Comment by afabri** [comment]
Is it only nth element??  Wat about using [the one from boost](https://www.boost.org/doc/libs/1_67_0/libs/range/doc/html/range/reference/algorithms/mutating/nth_element.html) then:
