### ISSUE TITLE
Polyhedron demo : display of non-convex faces

### ISSUE THREAD

**Issue by janetournois** [CGAL/cgal#2648]
## Issue Details

In the demo, there is a small issue with the display of non-convex faces of a polygon mesh.
It seems that the convex hull of the cell is colored, instead of only the "inside" of the CDT_2 computed from the borders.

See for example this snapshot :
![non_convex](https://user-images.githubusercontent.com/11311305/33484486-bee41c06-d6a2-11e7-97fb-b31f71aff19b.png)

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows
* Compiler: msvc2013
* Release or debug mode: Release
* CGAL version: master
* Boost version: 1.65.1

**Comment by janetournois** [comment]
cc @maxGimeno

**Comment by maxGimeno** [comment]
polyhedron_items are able to display non convex quads, but not the current version of sm_item. 
See here for a fix (the one in the API breaking branch currently beeing reviewed) :  https://github.com/maxGimeno/cgal/commit/2c9d8cb78ff0cb72038cba1eddd6f07b677474be

**Comment by lrineau** [comment]
Is this bug fixed in `master`?

**Comment by maxGimeno** [comment]
I think so : 
![image](https://user-images.githubusercontent.com/11310805/43509881-2ca4011c-9574-11e8-8440-cb5547e51185.png)
