### ISSUE TITLE
Polyhedron demo : show isolated vertices

### ISSUE THREAD

**Issue by janetournois** [CGAL/cgal#265]
In the Polyhedron demo, when an off file containing isolated vertices is opened, the Polyhedron item that appears in the list of items does not contain these vertices.
Also, the number of vertices displayed in the lower part of the window is the number of vertices of the "connected" polyhedron (or its different non-degenerate connected components).

It would be nice to display the isolated vertices, at least in "points" display mode, and to see the total number of vertices in the lower part of the window.

@maxGimeno , can you do something about it?

**Comment by sloriot** [comment]
A temporary solution is to use the off_to_xyz plugin at loading...

**Comment by janetournois** [comment]
ok, but then one can't use the PMP algorithms on the item, right?

**Comment by sloriot** [comment]
Just proposing a temporary display "hack"

**Comment by janetournois** [comment]
I found a better "hack".
Open the off file in a polyhedron item,
right-click on it and do "save as..."
The saved .off file does not contain the isolated vertices.

This works. 

However, it would still be nice to at least have a message in the Console when an off file is opened to know that there are isolated vertices in the input file

**Comment by sloriot** [comment]
What about printing their number in the infos if there are some?
The display of points is using that of the faces so it would need to create a new array to display them.

**Comment by janetournois** [comment]
It would be fine for me.
The main issue IMO is that there is no way to check whether the input HAS isolated vertices using the Polyhedron demo

**Comment by afabri** [comment]
Isn't it a bug that saving an off with isolated vertices removes them?

**Comment by janetournois** [comment]
somehow, yes

**Comment by sloriot** [comment]
Fixed by CGAL/cgal-public-dev@7216473

**Comment by lrineau** [comment]
Will you integrate that commit in 4.7? I am wandering if that pop-up could break existing scripts that we have. The pop-up is an interactive tool. It should not pop if a script is in action.

**Comment by sloriot** [comment]
Yes.
If you think it can be issue then we should not show a message box but only a message on the console (but this might be not seen).
