### ISSUE TITLE
(Automatic?) build of demo/Polyhedron into a AppImage

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#2650]
[AppImage] is a way to provide a self-contained application for Linux, that does not require any dependency, because all the dependencies are embedded in the AppImage file. That is similar to [Snaps] or [FlatPak].

[AppImage]: https://appimage.org/
[Snaps]: https://snapcraft.io/
[Flatpak]: https://flatpak.org/

The standard libraries of Linux (libc, among others) are not in the set of embedded dependencies. That is why, when you want to distribute an AppImage that will work on almost all Linux distribution, you need to compile on an old one, and use the fact that the set of standard libraries is backward compatible: a build on an old Linux will run fine on a more recent Linux.

From our Docker image `cgal/testsuite-docker:centos6` (that supports RHEL 6 and CentOS6, two ancient Linux distributions), I have derived an image with the tools needed to create `AppImage` files for a Qt5 demo: https://github.com/lrineau/bundle-CGAL-3D-demo.

This task is to use that image (maybe recompile it if necessary) and build the `master` version of the Polyhedron demo into an `AppImage` file.

If that process could be automatize to that every Sunday we have a new version of the Polyhedron demo, that would be even better.

**Comment by lrineau** [comment]
cc @sloriot, who needs that build for a user.

**Comment by lrineau** [comment]
Actually, the Docker image no longer builds. I have added you as a collaborator. If you find you to fix it, please commit the patch to the `Dockerfile`.

**Comment by maxGimeno** [comment]
I fixed the building problem, but I think libc is too old on that system, I get this error : 
linuxdeployqt: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /tmp/.mount_linuxdS9w3W5/usr/bin/../lib/libQt5Core.so.5)
when running the scripts in the container. 

> you need to compile on an old one, and use the fact that the set of standard libraries is backward compatible: a build on an old Linux will run fine on a more recent Linux.

Does it mean I cannot run yum update before installing libc ?

**Comment by lrineau** [comment]
I reopen until I have set up a cron job using this.

**Comment by sloriot** [comment]
@maxGimeno do you know the status of this issue? We could setup the cron for the user running the doxygen testsuite.

**Comment by maxGimeno** [comment]
Well it is supposed to be working. Either @lrineau forgot to close it, or he didn't set his cron.

**Comment by lrineau** [comment]
@maxGimeno Please check if that script `Scripts/developer_scripts/Bundle_polyhedron_demo_with_appimage.sh` still work and build the polyhedron demo correctly. It probably does not have all the third-party libraries.
