### ISSUE TITLE
check_headers does not test all documented header

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#2655]
With `cmake -DCGAL_ENABLE_CHECK_HEADERS`, that enables the special target `check_pkg_headers` that tests the individual compilation of all the documented headers. That is even tested by Travis.

That feature depends on a generated file, that is not automatically regenerated: `Installation/cmake/modules/list_of_documented_headers.cmake`... and it is not up-to-date.

Question for other CGAL developers (@CGAL/geometryfactory for example): should there be an automatic check preventing pull-requests to add new documented headers without modification of that file?

**Comment by lrineau** [comment]
(Anyway, the bug #2654 is not detected by `check_pkg_headers`.)

**Comment by maxGimeno** [comment]
note to myself : use cexecute_process to call a script in a CMakeLists.txt

**Comment by maxGimeno** [comment]
is it fixed by #2784, which automates the creation of the list and checks it in travis ?

**Comment by lrineau** [comment]
Yes, that is fixed by #2784.
