### ISSUE TITLE
Issues/TODO after the new CMake scripts

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#2656]
That is a follow-up to #1436, eventually merged into `master`.

Now, there are TODOs and bugs:

## TODO
- [ ] Documentation
- [x] <s>a kind of preconfiguration for pure-header-only?</s>

## Bugs
- [x] In header-only, compilation errors on Windows (at least MSVC 2017): https://github.com/CGAL/cgal/pull/1436#issuecomment-349259858 (**Edit:** fixed by #2859)

**Comment by cjamin** [comment]
Regarding the MSVC bug: unfortunately, I don't have MSVC 2017 for now, but here are a few questions/suggestions:
- Do you have a way to check if CGAL_CAN_USE_CXX11_THREAD_LOCAL is defined for this test?
- If yes, could you try to force the use of Boost.Thread like it's done for GCC?

**Comment by janetournois** [comment]
I am experimenting a few issues with MSVC 2013 with the new scripts :
- when configuring CGAL : `CGAL_HEADER_ONLY` is not available in the cmake-gui
- after configuring CGAL : the solution file `CGAL.sln` contains the target `CGAL_Qt5_moc_and_resources` which fails to compile (lots of warnings [C4273](https://msdn.microsoft.com/fr-fr/library/35bhkfb6.aspx) and errors [C2491](https://msdn.microsoft.com/fr-fr/library/62688esh.aspx). It does not prevent from using the non-header-only build of `master`
- without configuring CGAL : running cmake-gui on the Polyhedron demo, with `CGAL_DIR=/my/cgal/root` works almost fine, but CGAL Core is not found.

**Comment by lrineau** [comment]
@afabri I would need help, about MSVC 2017, Release, with `CGAL_HEADER_ONLY=ON`. There are runtime issue such as [that one]:
```
------------------------------------------------------------------
- ProgramOutput.theta_exact.x64_Cygwin-Windows10_MSVC2017-Release-64bits
------------------------------------------------------------------
t4n20.v is generated. 
t4n20.plt is generated. 
class CORE::ConstDoubleRep
CGAL error: assertion violation!
Expression : ! blocks.empty()
File       : C:\CGAL\test\CGAL-4.12-I-166\include\CGAL/CORE/MemoryPool.h
Line       : 158
Explanation: 
Refer to the bug-reporting instructions at http://www.cgal.org/bug_report.html
```
[that one]: https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.12-I-166/Cone_spanners_2/TestReport_afabri_x64_Cygwin-Windows10_MSVC2017-Release-64bits.gz

Several packages show the same issue. I have chosen `Cone_spanners_2` on purpose:
  - its test results [are fully green but for that platform][test results],
  - the testsuite seems short to run (58s in [Debug]).

[test results]: https://cgal.geometryfactory.com/CGAL/testsuite/results-4.12-I-166.shtml#Cone_spanners_2
[Debug]: https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.12-I-166/Cone_spanners_2/TestReport_afabri_x64_Cygwin-Windows10_MSVC2017-Debug-64bits.gz

**Comment by lrineau** [comment]
@afabri @janetournois About what I wrote in the previous message (https://github.com/CGAL/cgal/issues/2656#issuecomment-365910614), I think that is not specific to MSVC 2017. That test column is the only one that tests `CGAL_HEADER_ONLY=TRUE` on Windows. The problem is probably related to C++11 + `CGAL_HEADER_ONLY`, and should be reproducible with MSVC 2015 as well, as soon as CGAL assertions are not disabled.

**Comment by janetournois** [comment]
I can reproduce exactly the same assertion violation with MSVC 2015, Debug mode

**Comment by janetournois** [comment]
And I confirm the 2 first bugs I had mentioned on Dec. 14 are fixed.

**Comment by lrineau** [comment]
I re-open this issue, because #2846 does not fix all items of the issue.

**Comment by lrineau** [comment]
Now only the documentation part is still TO-DO. I postpone to 4.12. For 4.12-beta1, the explanation will be in the announcement mail only.
