### ISSUE TITLE
Update MSVC 2017 to update 15.5 on gauguin

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#2664]
On the [vs2017 release notes](https://www.visualstudio.com/en-us/news/releasenotes/vs2017-relnotes):
> Release Date: December 4, 2017 - Visual Studio 2017 version 15.5

gauguin MSVC2017 should be updated.

**Comment by janetournois** [comment]
It's done, updated to version 15.5.1.

If tests do not reveal any error, can you please update the setup files in CGAL "infrastructure" folder, please, @maxGimeno ?
(according to the local git on Gauguin, most of them are different from what is saved in "infrastructure")

**Comment by janetournois** [comment]
It seems that the update went well, and we can close this issue

**Comment by maxGimeno** [comment]
Ok, I committed the changes

**Comment by lrineau** [comment]
> Ok, I committed the changes

Where is it?

**Comment by maxGimeno** [comment]
Î
There :)
