### ISSUE TITLE
Doxygen generates non utf-8 html files (windows)

### ISSUE THREAD

**Issue by janetournois** [CGAL/cgal#2667]
## Issue Details

I have tested two different versions of Doxygen which both generate non-utf-8 characters.
- **1.8.3.1** does not deal with "é" and simple accents, for example in `Alpha_shapes_3\index.html`
See for example line 131 :
> <div class="textblock"><p><a class="anchor" id="Chapter_3D_Alpha_Shapes"></a> </p><div id="autotoc" class="toc"></div>  <dl class="section author"><dt>Authors</dt><dd>Tran Kai Frank Da, S꣡****stien Loriot, and Mariette Yvinec</dd></dl>
or line 136 :
> <p>As mentioned in Edelsbrunner's and M****'s paper <a class="el" href="citelist.html#CITEREF_em-tdas-94">[2]</a>, </p>

- **1.8.13** creates non-utf-8 characters, for example in `Algebraic_foundations/classCGAL_1_1Coercion__traits.html`, the typedefs are polluted by "Ã‚Â"
![capture](https://user-images.githubusercontent.com/11311305/33762428-b54a31b6-dc0c-11e7-8570-a64f1d39a095.PNG)

## Environment

* Operating system : Windows 64 bits
* Compiler: visual 2013 (both in IDE and using nmake)
* CGAL version: master

**Comment by lrineau** [comment]
@sloriot Should it be reported upstream?

**Comment by sloriot** [comment]
is 1.8.13 the compiled shipped by doxygen or one that you compiled yourself?

**Comment by lrineau** [comment]
>  1.8.13 the compiled shipped by doxygen or one that you compiled yourself?

You mean "shipped by cygwin"?

@janetournois, which doxygen did you use?

**Comment by janetournois** [comment]
My Doxygen 1.8.13 is the one I downloaded from [the Doxygen webpage](http://www.doxygen.nl/download.html#srcbin)

**Comment by albert-github** [comment]
I checked the page: https://doc.cgal.org/latest/Algebraic_foundations/structCGAL_1_1Coercion__traits.html and here I don't see any strange characters. Same accounts for the file Alpha_shapes_3\index.html

**Comment by lrineau** [comment]
I think that is an old issue. I close it. Jane, please reopen if if I closed it by error.
