### ISSUE TITLE
Request: CGAL::find_interior_point(PlaneIterator begin, PlaneIterator end)

### ISSUE THREAD

**Issue by bombax** [CGAL/cgal#268]
In my program I use the halfspace_intersection_3.h code a lot. I found myself at one point needing to find an interior point of the polyhedron enclosed by a set of planes.

Now of course I could just call CGAL::halfspace_intersection_3(...), then use the polyhedron to figure out an interior point (like averaging the points). But I don't need to compute the whole polyhedron in this case so this is slow.

What I've done now is add the code

``` cpp
#include <CGAL/Convex_hull_3/dual/interior_polyhedron_3.h>
#include <CGAL/internal/Exact_type_selector.h>
...
        Interior_polyhedron_3<CGALKernel, CGAL::internal::Exact_field_selector<void*>::Type> poly;
        CGAL_assertion_code(bool interior_point_found = )
        poly.find(planes.begin(), planes.end());
        CGAL_assertion_msg(interior_point_found, "finalizeTree: problem when determing a point inside the intersection");
        Point inside = poly.inside_point();
```

But it would be much nicer with a convenience function for this as documented here: http://doc.cgal.org/latest/Convex_hull_3/group__PkgConvexHull3Functions.html#ga6118d2c46934c541669ab871f8e1fd24

Thanks!

**Comment by sgiraudot** [comment]
This issue has been opened for a year. Do we want this feature in CGAL or not? Who can take care of it?

**Comment by sloriot** [comment]
The code provided by the user is correct. We just need someone to wrap it in a function.
