### ISSUE TITLE
Read-safe multithreading with Lazy_exact_nt

### ISSUE THREAD

**Issue by alecjacobson** [CGAL/cgal#2685]
I can't seem to find any discussion in [the documentation](https://doc.cgal.org/latest/Number_types/classCGAL_1_1Lazy__exact__nt.html) the thread safety (or lack thereof) when using `CGAL:: Lazy_exact_nt`, e.g., via `CGAL::Epeck`. I'm worried that this type uses non-atomic reference counting implying that even _reading_ a variable could result in a race condition and subsequent memory violation.

In my specific case, I have a giant list of points that should be reduced to constrained Delaunay triangulations (in my simplified code below, I put every 4 points into a CDT). _Conceptually_, my problem is [embarassingly parallel](https://en.wikipedia.org/wiki/Embarrassingly_parallel) with respect to the "points". However, my points are constructed via arithmetic involving common points, so I understand that the lazy evaluation makes this a non-trivial dependency graph (simulated below by a simple addition of the first point to all others). Still, my problem is completely parallel with respect to the outputs: no CDT depends on any other one.

Here's a minimal-ish reproducible example:

```c++
#define SERIAL

#include <vector>
#include <CGAL/Exact_predicates_exact_constructions_kernel.h>
#include <CGAL/Vector_2.h>
#include <CGAL/Point_2.h>
#include <CGAL/Constrained_Delaunay_triangulation_2.h>
#include <CGAL/Constrained_triangulation_plus_2.h>
#include <cmath>
#include <cassert>
#include <thread>
#include <vector>
#include <algorithm>

template<
  typename Index, 
  typename FunctionType>
inline bool parallel_for(
  const Index loop_size, 
  const FunctionType & func)
{
  assert(loop_size>=0);
  if(loop_size==0) return false;
  // Estimate number of threads in the pool
  // http://ideone.com/Z7zldb
  const static size_t sthc = std::thread::hardware_concurrency();
  const size_t nthreads = (sthc==0?8:sthc);
  // Size of a slice for the range functions
  Index slice = 
    std::max(
      (Index)std::round((loop_size+1)/static_cast<double>(nthreads)),(Index)1);
  // [Helper] Inner loop
  const auto & range = [&func](const Index k1, const Index k2, const size_t t)
  {
    for(Index k = k1; k < k2; k++) func(k);
  };
  // Create pool and launch jobs
  std::vector<std::thread> pool;
  pool.reserve(nthreads);
  // Inner range extents
  Index i1 = 0;
  Index i2 = std::min(0 + slice, loop_size);
  {
    size_t t = 0;
    for (; t+1 < nthreads && i1 < loop_size; ++t)
    {
      pool.emplace_back(range, i1, i2, t);
      i1 = i2;
      i2 = std::min(i2 + slice, loop_size);
    }
    if (i1 < loop_size)
    {
      pool.emplace_back(range, i1, loop_size, t);
    }
  }
  // Wait for jobs to finish
  for (std::thread &t : pool) if (t.joinable()) t.join();
  return true;
}
 
int main(int argc, char *argv[])
{

  typedef CGAL::Epeck Kernel;
  typedef CGAL::Triangulation_vertex_base_2<Kernel>  TVB_2;
  typedef CGAL::Constrained_triangulation_face_base_2<Kernel> CTFB_2;
  typedef CGAL::Triangulation_data_structure_2<TVB_2,CTFB_2> TDS_2;
  typedef CGAL::Exact_intersections_tag Itag;
  typedef CGAL::Constrained_Delaunay_triangulation_2<Kernel,TDS_2,Itag> CDT_2;
  typedef CGAL::Constrained_triangulation_plus_2<CDT_2> CDT_plus_2;

  std::vector< CGAL::Point_2<CGAL::Epeck> > points(100000);
  points[0] = CGAL::Point_2<CGAL::Epeck>(0,1);
  for(int i = 1;i<points.size();i++)
  {
    points[i] = points[(i-1)%5]+(CGAL::Vector_2<CGAL::Epeck>(i%7,i%11))/CGAL::Epeck::FT(3);
  }

  std::vector< CDT_plus_2 > cdts(points.size()/4);
#ifdef SERIAL
  for(int i = 1;i<cdts.size();i++)
#else
  parallel_for(cdts.size(),[&](int i)
#endif
  {
    CDT_plus_2 cdt;
    cdt.insert_constraint(points[4*i+0],points[4*i+1]);
    cdt.insert_constraint(points[4*i+2],points[4*i+3]);
  }
#ifndef SERIAL
  );
#endif

}
```

Use `#define SERIAL` to control whether the code executes in serial (should exit cleanly) or in parallel (usually causes `EXC_BAD_ACCESS` fault).

_FWIW @qnzhou expressed a thought that perhaps this reference counting is easy to fix using atomic integers_

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Mac
* Compiler: Apple LLVM version 9.0.0 (clang-900.0.39.2)
* Release or debug mode: either
* Specific flags used (if any): 
* CGAL version: 1040911000
* Boost version: 106400
* Other libraries versions if used (Eigen, TBB, etc.): (std::thread-based parallel_for borrowed from libigl)

**Comment by afabri** [comment]
Hi Alec, a known issue, and there is even a pull request ( #648).  It is more than a reference counting problem, as it may happen that nodes in the DAG of lazy objects get updated, simply because some orientation test of three points happens, and triggers an exact evaluation.  Note that the PR slows down things, which explains why  it is not yet in master.

**Comment by alecjacobson** [comment]
Thanks. Good to know this is being addressed. Maybe it'd complicate things too much, but I'd be happy to explicitly specify that I want a slower-but-parallelizable type: e.g., `CGAL::Pepeck`

Meanwhile, does the current documentation have a warning about race-conditions someplace? I think most naive users like myself would assume reading is safe and might not even know that `CGAL::Epeck` uses the lazy type by default (instead just think of it as "a rational number type"). Might be nice to add a warning...

**Comment by lrineau** [comment]
Well... my PR #648 is two years old, now. We cannot really say we have being addressing the issue. It was not merged because of the important penalty of the implementation I chose. Andreas found out a slow-down by a factor 2, on Windows, even if only one thread was used. On my Linux machine, I remember it was a slowdown of 30% (running time×1.3).

Actually, `CGAL::Epeck` does not use the lazy objets, if the macro `CGAL_DONT_USE_LAZY_KERNEL` is defined. I do not know if our test suite tests that scenario, and it might be broken.

Even with `CGAL_DONT_USE_LAZY_KERNEL` defined, the `CGAL::Epeck` uses reference-counting, but that is easy to make thread-safe, with atomic counters instead of plain counters: that was the first commit of the PR: https://github.com/CGAL/cgal/pull/648/commits/72297f99e2f68d2a29dc4abf39344b6a6adf453a.

**Comment by lrineau** [comment]
**Update:** with `CGAL_DONT_USE_LAZY_KERNEL` defined, Epeck still uses the `Lazy_exact_nt`. You should try `CGAL::Simple_cartesian<CGAL::Gmpq>`, that uses the reference counting mechanism of `CGAL::Handle_for`.

**Comment by alecjacobson** [comment]
Thanks. 

So I can use `CGAL::Simple_cartesian<CGAL::Gmpq>` for thread-safe exact constructions like in my example above? Which version of CGAL would I need for that?

**Comment by lrineau** [comment]
> So I can use CGAL::Simple_cartesian<CGAL::Gmpq> for thread-safe exact constructions like in my example above? Which version of CGAL would I need for that?

Actually no, because of the reference counting. You would need at least to apply the patch of https://github.com/CGAL/cgal/commit/72297f99e2f68d2a29dc4abf39344b6a6adf453a, that implement a thread-safe reference counting, using atomics.

**Comment by sloriot** [comment]
If you have GMPXX installed, you can also use `CGAL::Simple_cartesian<mpq_class>` (including first `<CGA/mpq_class>` with a non patched CGAL release (as there will be no reference counting).

**Comment by lrineau** [comment]
I was about to say that the solution with `mpq_class` is not tested, but I have verified and it is probably wrong. I think `mpq_class` is the number of Epeck in two of our test platforms:
- `ArchLinux-clang-Release`, and
- `Fedora-Release`.

They both define the CMake variable `WITH_GMPXX=ON`.

**Comment by alecjacobson** [comment]
Thanks. I quickly tried my example above and things seem to work OK (no crashes at least).

I'll test with my actual program later, but is there a general sense of how `mpq_class` compares to `Lazy_exact_nt` in terms of performance?

**Comment by lrineau** [comment]
`CGAL::Simple_cartesian<mpq_class>`, without any filters, is expected to be quick slow, compared to `CGAL::Epeck`.

**Comment by lrineau** [comment]
> `CGAL::Simple_cartesian<mpq_class>`, without any filters, is expected to be quick slow, compared to `CGAL::Epeck`.

I meant "quite slow" (and not "quick slow"). (Thanks @sloriot.)

**Comment by alecjacobson** [comment]
Suppose I wanted to define a new thread-safe Lazy evaluation number type _from outside_ CGAL, but essentially using the [PR 648](https://github.com/CGAL/cgal/pull/648/files) patches on top of `Lazy_exact_nt`, what steps would I need to take?

I'd like to then pass this type into CGAL to use CDT etc.

**Comment by mglisse** [comment]
To get sensible performance, you can try something like
`struct My_epeck : CGAL::Filtered_kernel_adaptor<CGAL::Type_equality_wrapper<CGAL::Simple_cartesian<mpq_class>::Base<My_epeck>::Type, My_epeck>,true> {};`

(i.e. replace Lazy_exact_nt with mpq_class in the declaration of Epeck when the lazy kernel is disabled)

**Comment by elfprince13** [comment]
Just got bitten by this: I suspect that you could do a really fast lock-free implementation based on [LLX/SCX](https://dl.acm.org/citation.cfm?id=2484273).
