### ISSUE TITLE
3D demo: Mesh_3 plugin crashes on all data

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#2689]
## Issue Details

Compile the Polyhedron demo with the off_plugin and the mesh_3_plugin, open any off file, even `sphere.off`, try to mesh it... Crash! It seems to be during the display of the c3t3.

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Linux Fedora 27 64 bits
* Release or debug mode: release with debuginfo and assertions
* CGAL version: master (8f3e2298022aa1a7d93b39d244c01856a9e1f9ff)

**Comment by sloriot** [comment]
@maxGimeno haven't you fixed that issue?

**Comment by maxGimeno** [comment]
Yes, see #2773 and #2693

**Comment by lrineau** [comment]
My fault. I opened two very similar issues:
  - issue https://github.com/CGAL/cgal/issues/2692
  - this one https://github.com/CGAL/cgal/issues/2689
