### ISSUE TITLE
Segment_tree_3 usage: How to do zero-width (point) window_query?

### ISSUE THREAD

**Issue by bombax** [CGAL/cgal#269]
I'm using a segment_tree_3 in construction of a BSP tree to find out what input hulls the leaves are contained in. What I really want to do is do a window_query of a point. But when I try putting in a zero-width Interval, CGAL throws an error "invalid window; ignoring query" or something.

My solution has been to use a small pertubation, like

``` cpp
segTree.window_query(Interval(Pure_interval(Key(point.x(), point.y(), point.z()),
                                            Key(point.x()+1E-5, point.y()+1E-5, point.z()+1E-5)),
                                         (Hull*)0), back_inserter(items));
```

But I don't think this is very pretty. How would I use Segment_tree_3 to ask "Which 3D-intervals (bounding boxes) contain this point?"

**Comment by sloriot** [comment]
cc @afabri

**Comment by sgiraudot** [comment]
@afabri, you are the package maintainer, what do you think about this issue? Is there a reason why a point can't be used as a query?

**Comment by afabri** [comment]
I think it should also work for a point

**Comment by afabri** [comment]
@bombax    If I understand you correctly, the solution is to call [Segment_tree_d::enclosing_query](http://doc.cgal.org/latest/SearchStructures/classCGAL_1_1Segment__tree__d.html#a3e1409f32a09139b795c9346a6c4a7e0)

**Comment by MaelRL** [comment]
Feel free to reopen if the suggestion didn't fit the need.
