### ISSUE TITLE
Add redirection from Sweep_line_2 to Sweep_surface_2

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#2699]
This is due to a package renaming. See #2236

**Comment by afabri** [comment]
@lrineau Can't you delegate this?

**Comment by lrineau** [comment]
Too complicated, where the task is really simple.

In the `.htaccess` file, I already have:
```
RedirectPermanent /latest/Surface_modeling/ /latest/Surface_mesh_deformation/
RedirectPermanent /latest/Surface_reconstruction_points_3/ /latest/Poisson_surface_reconstruction_3/
```

@sloriot, is that sufficient to add the following line?
```
RedirectPermanent /latest/Sweep_line_2/ /latest/Surface_sweep_2/
```

What should we do to test that the redirection is the right one?

**Comment by sloriot** [comment]
Yes. After the release it should redirect that [url](https://doc.cgal.org/latest/Sweep_line_2/).

**Comment by lrineau** [comment]
Done.

For the current version 4.11, I have used a symbolic link, so that both names point to the same resources.
