### ISSUE TITLE
Upgrade to recent Doxygen version

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#2706]
Now Google will [favor web page using a responsive design][1]. https://doc.cgal.org/ will be impacted, because with the version of Doxygen we use, 1.8.4, the CSS uses hardcoded values. Recent versions of Doxygen 1.8.12 or later, if I remember well, have a new CSS that is more compliant with responsible design.

  [1]: https://ez.no/Blog/Responsive-Design-and-its-Impact-on-SEO

@sloriot, do we have any remaining issue with the [CGAL documentation compiled with our fork of 1.8.13][2]?

  [2]: https://cgal.geometryfactory.com/CGAL/Manual_doxygen_test/CGAL-4.12-I-131/output2/Manual/index.html

**Comment by afabri** [comment]
@sloriot  ping.

**Comment by lrineau** [comment]
@CGAL/geometryfactory: I have created a new label, named `release blocker`, that should be assign to issues/PR that cannot be delayed to a later release.

**Comment by sloriot** [comment]
I guess we don't.

**Comment by afabri** [comment]
You guess we don't **what**?   Block the release or remaining issues?

**Comment by sloriot** [comment]
I don't think they are remaining issues. There used to be an issue tracking pbs by @sgiraudot but IIRC @lrineau addressed all of them.

**Comment by lrineau** [comment]
OK, so for CGAL-4.12, the plan will be that the official Doxygen document is the one compiled with our fork of Doxygen 1.8.13. @sloriot, do you agree?

That would mean a minor patch to `Maintenance/public_release/scripts/prepare_release`, probably only at line 38:
https://github.com/CGAL/cgal/blob/b5dd4568fd09703fa980265a65b943b72430a96d/Maintenance/public_release/scripts/prepare_release#L31-L42
and to `Scripts/developer_scripts/run_doxygen_testsuite` as well
https://github.com/CGAL/cgal/blob/b5dd4568fd09703fa980265a65b943b72430a96d/Scripts/developer_scripts/run_doxygen_testsuite#L67-L69
so that https://cgal.geometryfactory.com/CGAL/doc/master/ is now compiled from Doxygen 1.8.13.

**Comment by sloriot** [comment]
OK.

**Comment by lrineau** [comment]
@maxGimeno, could you modify those two scripts? It is probably sufficient to move from `output/` (or `output1/`) to `output2/`.

**Comment by lrineau** [comment]
Now that the PR #2821 wrote by Maxime is merged, the [documentation of`master`][d] is now updated, and the release preparation script has been fixed to.

  [d]: https://cgal.geometryfactory.com/CGAL/doc/master/Manual/index.html

**Comment by lrineau** [comment]
@sloriot, @maxGimeno:
There is a problem.
https://cgal.geometryfactory.com/CGAL/Manual_doxygen_test/CGAL-4.12-Ic-179/index.html
![screenshot_20180220_095736](https://user-images.githubusercontent.com/5746675/36414973-1c6dfea6-161c-11e8-89c7-706cfd328797.png)

You can see that Doxygen 1.8.4 has detected an issue (a warning), but not the other versions. Where the warning seems relevant.

**Comment by lrineau** [comment]
The logs says:
> /home/cgal-testsuite/cgal_doc_build/CGAL-4.12-Ic-179/doc/BGL/BGL.txt:67: Warning: unable to resolve link to `Triangulation_2::Edge' for \link command
