### ISSUE TITLE
Use implementation-defined (or C++11) thread_local qualifiers, instead of Boost.Thread

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#271]
Use `thread_local` (C++11), `__thread` (g++, clang, Intel C++), or `__declspec(thread)` instead of thread-local storage from Boost.Thread.

Probably more efficient, and that will reduce the dependency to pre-compiled libraries of Boost.

References:
- C++11: http://en.cppreference.com/w/cpp/language/storage_duration
- Wikipedia: https://en.wikipedia.org/wiki/Thread-local_storage#C_and_C.2B.2B

Warning: there is an issue with thread-local storage and Microsoft Windows before Vista (XP and before).

See also #273.

**Comment by afabri** [comment]
I am facing a problem in Residue_type.h as VC++  does not to allow to declare a variable being thread_local and having at the same time a dll interface
https://msdn.microsoft.com/en-us/library/40a45kxx.aspx?f=255&MSPPError=-2147217396

**Comment by sloriot** [comment]
I think the export is not needed in the case `CGAL_HAS_THREAD` since the variables have internal initialization and does not need to be accessed from outside.

**Comment by afabri** [comment]
I am wondering if it is not as follows:
- We do not need the export when the variable is thread_local.
- But we need it, in case of single-thread   or boost::thread_specific_ptr.

**Comment by lrineau** [comment]
* Exporting a variable through DLL boundaries is a design error. The use of that variable should be wrapped in a function or a class method.
* Anyway, the headers-only refactoring is probably the best solution.

**Comment by sloriot** [comment]
@afabri Can we close this issue?

**Comment by lrineau** [comment]
The issue about `Residue_type.h` still has no solution.
There will be discussion about that with @cjamin and @gdamiand at the meeting.

**Comment by sloriot** [comment]
@cjamin @gdamiand is the remaining issue mentioned by @lrineau solved?

**Comment by cjamin** [comment]
I did not really look into it, but in header-only mode, [CGAL_DLL_EXPORT is "empty"](https://github.com/CGAL/cgal/blob/master/Installation/include/CGAL/export/helpers.h) so maybe that answer the question?

**Comment by gdamiand** [comment]
If I correctly understand, the problem is only on Windows ? If yes I cannot test...

**Comment by sgiraudot** [comment]
Can someone using Windows test it so we know if it's solve by the header-only mode? @afabri ? @janetournois ?

**Comment by janetournois** [comment]
I have just tested `Residue.cpp` under visual studio 2015 (no boost lib required), in header-only mode, and everything went smoothly.
Is this enough? Otherwise, tell me which tests I should make

**Comment by sgiraudot** [comment]
Thanks Jane. If I understand well, the problem comes from the `thread_local` qualifiers and I'm not sure this is tested in `Residue.cpp`.

@afabri can you be more specific about the bug? You said:

> I am facing a problem in Residue_type.h as VC++ does not to allow to declare a variable being thread_local and having at the same time a dll interface
> https://msdn.microsoft.com/en-us/library/40a45kxx.aspx?f=255&MSPPError=-2147217396

Is it a code of yours that generates an error or one of CGAL examples?

**Comment by sgiraudot** [comment]
@afabri Can we close this issue?

**Comment by lrineau** [comment]
I think we should open a specific issue about the issue in `Residue.cpp`. The problem is that `Residue.h` offer a variable in the exported API of the DLL, instead of using a function that would return a reference. The API has to be changed, because it was buggy even before we changed the implementation of our thread-local variables.

**Comment by afabri** [comment]
The exported symbol is not part of the documented API.  As the variable is a const double there is no need to make it atomic or thread local, and the header only code solves the problem.

**Comment by afabri** [comment]
@lrineau @sloriot   I think this  could get the status ready for testing.

**Comment by lrineau** [comment]
Le Tuesday, November 8, 2016 7:17:43 AM CET 
Andreas Fabri a écrit :
> @lrineau @sloriot   I think this  could get the status 
ready for testing.

I do not understand. This is an issue, not a pull-request.

**Comment by afabri** [comment]
I had written, it, and 20sec later I removed it, but the mail was out. Sorry.

**Comment by lrineau** [comment]
#1641 fixed the last remaining issue.
