### ISSUE TITLE
Continuous integration for Windows

### ISSUE THREAD

**Issue by maxGimeno** [CGAL/cgal#2715]
We should try AppVeyor as a replacement for travis for Windows continuous integration.

**Comment by sloriot** [comment]
Shall the issue be closed and appveyor service disconnected from our repo?

**Comment by maxGimeno** [comment]
I do think so.

**Comment by lrineau** [comment]
I think I have removed the AppVeyor connection, now.

**Comment by sloriot** [comment]
I think it would be useful to add in the issue with we drop this solution. @maxGimeno @lrineau please update.
