### ISSUE TITLE
test/Classification: a CMake bug when C++11 is not available but TBB is

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#2719]
In `master`, when C++11 cannot be used but TBB is available, there is a CMake error in `test/Classification/`:
https://cgal.geometryfactory.com/CGAL/testsuite/results-4.12-I-135.shtml#Classification

**Comment by sgiraudot** [comment]
Should be fixed by https://github.com/CGAL/cgal/pull/2690/commits/1caff91adef4fd43e09b519a3929f527cfa46759.

**Comment by sgiraudot** [comment]
Fixed by https://github.com/CGAL/cgal/pull/2690.
