### ISSUE TITLE
Test and adapt to Boost 1.66 on Windows (auto-linking)

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#2725]
Boost 1.66 has been published a week before Chrismas, and we have not yet tried it on Windows (we have a test on Linux, with the ArchLinux distro, but it is fully yellow because the CMake support of Boost 1.66 is incomplete).

Boost 1.66 has modified its naming scheme for libraries, in the 'versioned' variant, that is used on Windows. That probably means that our support for auto-linking will fail with it.

@afabri, or @janetournois, I think you should try CGAL (any version) with Boost 1.66 in Windows (with MSVC), to see how bad things are.

In my opinion our release branch for 4.11.1 and `master` should eventually support Boost 1.66 and its new naming scheme.

**Comment by afabri** [comment]
I confirm that cmake declares an error during configuration. The workaround is to specify the required libraries by hand, as the libraries now also encode the architecture.
Remains the question if CGAL should follow this new naming scheme.

**Comment by lrineau** [comment]
The "solution" is to wait for CMake 3.11. The fix was merged last week in CMake: https://gitlab.kitware.com/cmake/cmake/merge_requests/1625.
