### ISSUE TITLE
Corefine adjacency output is random

### ISSUE THREAD

**Issue by seb-tourneux** [CGAL/cgal#2727]
## Issue Details

For two consecutive executions of corefine functions, I get different adjacency output.
Some vertices index are swapped or permuted. 

## Environment

* Operating system : Linux, Debian 8
* Compiler: clang
* CGAL version: 4.11

**Comment by sloriot** [comment]
What do you call an "adjacency output"?

**Comment by seb-tourneux** [comment]
Basically vertices order change

**Comment by sloriot** [comment]
Try setting the seed of the default random generator by calling for example before doing the operation. `CGAL::get_default_random()=CGAL::Random(0);`.

**Comment by seb-tourneux** [comment]
Setting the seed did not work

**Comment by sloriot** [comment]
are you using `Polyhedron_3` or `Surface_mesh` as mesh data structure? The only thing that I can imagine could make it non deterministic are the sorting of descriptors which should be deterministic for `Surface_mesh` as based on indices while for `Polyhedron_3` they are based on memory addresses.

**Comment by lrineau** [comment]
Hi @seb-tourneux,
Could you please comment on this old issue, so that we can close it (or not)? I see you were active recently in a newer one (#3415).

**Comment by seb-tourneux** [comment]
I didn't manage to exhibit my problem with a simple piece of code or from the examples.
I'm closing the issue, and will create a new one in the future if somehow I manage to exhibit the bug.
Thank you
