### ISSUE TITLE
The manual of the dD Spatial Searching is self-conflicting

### ISSUE THREAD

**Issue by efifogel** [CGAL/cgal#2729]
## Issue Details

In the user manual (1.2 Range Searching) it says, and I quote:

> The fuzziness of the query object is specified by a parameter ϵ used to define inner and outer approximations of the query object. Points in the interior of the inner approximation are always reported and points that are not in the closure of the outer approximation are never reported.
> Other points may or may not be reported. For exact range searching, the fuzziness parameter ϵ is set to zero.

However, the reference of the Fuzzy_sphere says, and I quote:

> Attention
>     The fuzziness of a Fuzzy_sphere is specified by a parameter ϵ denoting a maximal allowed distance to the boundary of a sphere. If the distance to the boundary is greater than ϵ, points inside the object are always reported and points outside the sphere are never reported. Points whose distance to the boundary is less than or equal to ϵ may or may not be reported. Subsequently, points on the inner and outer spheres may or may not be reported. Specifically when ϵ=0, points on the sphere of radius r may or may not be reported.

So which one is correct?
I assume that the latter is the correct one. However, if this is the case, the former should be rephrased.

**Comment by MaelRL** [comment]
I don't see the conflict, the first paragraph doesn't say that points on the sphere will always (or never) be reported when the fuzziness is zero.

Related to https://github.com/CGAL/cgal/pull/1808.

**Comment by efifogel** [comment]
I believe it does. Read it again carefully. Notice the phrase "not in the
closure of the outer"...
It says that if you set eps to zero you get all points the distance of
which is less then r and no point the distance of which is equal to or
greater then r.
Typically, we use the term "exact" to indicate the opposite of limited
precision, but here, in the last sentence, it is used to indicate the
opposite of "approximate", and so the last sentence actually reiterates the
above.
If you have doubts about the conflict, then this last sentence simply
settles it...(I mean, the conflict).


   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by MaelRL** [comment]
> Points in the interior of the inner approximation are always reported

d(c, x) < r - epsilon ==> always reported
> points that are not in the closure of the outer approximation are never reported.

d(c, x) > r + epsilon ==> never reported

Going to zero, this gives conditions on d(c,x) < r and d(c,x) > r. Nothing for d(c,x)=r.

"Exact" just means that there is no fuzziness parameter, but it is still "might or might not be" for the border of the inner and outer spheres (which are actually the same in the case of epsilon = 0).

**Comment by efifogel** [comment]
No, notice the word "closure"; it has a very specific meaning in geometry
and topology.
The phrase "points that are not in the closure of the outer approximation
are never reported." implies that d(c, x) *>=* r + epsilon ==> never
reported.

BW, are you absolutely certain that the code implements "d(c, x) > r +
epsilon ==> never reported" (and not the '>=' option)?

   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by MaelRL** [comment]
I'm not following: although what the inner and outer approximations are not really defined, we are in a nice metric space so the closure is going to be the closed ball whether we are considering the open ball or something else as approximation. Then, not in the closed ball <=> the distance to `c` is _strictly_ greater than `r + epsilon`.

I must be missing something in  the above, then.

I guess everything would fall into place if it is `>=` because then when we go to epsilon = 0, the interior of the ball is always reported and the sphere d(c, x) = r is never reported, and there's no "might or might not". In that case, the first quote needs a clarification to say that the boundary of the outer approximation is never reported and the warnings in the reference manuals are wrong.

**Comment by efifogel** [comment]
On 12 January 2018 at 11:17, Mael Rouxel-Labbé <notifications@github.com>
wrote:

> I'm not following: although what the inner and outer approximations are
> not really defined, we are in a nice metric space so the closure is going
> to be the closed ball whether we are considering the open ball or something
> else as approximation. Then, not in the closed ball <=> the distance to c
> is *strictly* greater than r + epsilon.
>
> I must be missing something in the above, then.
>

I don't blame you; it's written in a confusing (or misleading) way.

> I guess everything would fall into place if it is >= because then when we
> go to epsilon = 0, the interior of the ball is always reported and the
> sphere d(c, x) = r is never reported, and there's no "might or might not".
> In that case, the first quote needs a clarification to say that the
> boundary of the outer approximation is never reported and the warnings in
> the reference manuals are wrong.
>

Right.

I wrote a small program and made few experiments. I never got points the
distance of which is exactly (r + epsilon) reported.
Of course, this is not a proof that they are indeed never reported, but I
would guess that it is easier to implement it this way...

**Comment by MaelRL** [comment]
It makes more sense with the `contains()` function too. 

It'd be nice to clarify the definitions of the the inner and outer approximations as open sets, but it's not true for the fuzzy box, which IIRC has 3 sides open and 3 that are closed.  Maybe those details should be taken to the warnings in the reference manual. For the user manual, how would you clarify the `closure of the outer approximation` part ?

**Comment by lrineau** [comment]
Efi, this bug should be fixed, now, in the release branches for 4.11 and 4.12, and also in `master`.
