### ISSUE TITLE
Install OpenMesh in Travis

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#2731]
@maxGimeno  Please install OpenMesh in Travis. Do it in a dedicated pull-request, because it might break something: the `CHECK` line will probably no longer pass until we fix the issue.

**Comment by afabri** [comment]
I am not sure if it is relevant for this PR, but it would make sense to tar -x   OpenMesh.tgz with a quiet option as I have to scroll too much for example [here](https://travis-ci.org/CGAL/cgal/jobs/357804482)

**Comment by maxGimeno** [comment]
I'll look into it. In the meantime, you should use the raw log and ctrl+F instead of scrolling for hours in the calssic logs, that are almost always too long to be usable.

**Comment by lrineau** [comment]
By the way, let's close this issue, now that we have OpenMesh installed in Travis.
