### ISSUE TITLE
bug with Plane_3.to_2d()?

### ISSUE THREAD

**Issue by hugoledoux** [CGAL/cgal#2733]
## Issue Details

I first define 5 points in 3D (forming an horizontal plane), then fit a plane through them with the least-square function, and then project each of the original points to the plane with the function Plane_3.to_2d(). The projection returns wrong values, such as:
```
Projection of points to the plane:
1.38039e+27 -379197
1.38039e+27 -379207
...
```

Maybe because the coefficients of the plane are not exactly 0, but -4.3906e-26 for instance?

If I translate the plane by z=-200 then it is okay...

Without Eigen this problem doesn't exists, with it always. Tested on macOS and Ubuntu with CGAL 4.11 and Eigen 3.3.4

## Source Code

https://gist.github.com/hugoledoux/f763636492dc72fb9f3fb77932b84c56

## Environment
 
macOS 10.13.2

with CGAL v4.11 installed with brew
$ brew info cgal
cgal: stable 4.11 (bottled)
Computational Geometry Algorithm Library

$ brew info eigen
eigen: stable 3.3.4 (bottled), HEAD

**Comment by lrineau** [comment]
Fixed by #2735. Will be in CGAL-4.11.1, and CGAL-4.12.
