### ISSUE TITLE
Travis fails way too often on `apt-get`

### ISSUE THREAD

**Issue by sgiraudot** [CGAL/cgal#2740]
## Issue Details

As we have lots of lines in our Travis testsuite, the probability that at least one fails at `apt-get` is quite high (I have no memory of a recent pull request where I did not have to restart it by hand at least 3 or 4 times). It's quite annoying as the PR appears red and we have to check by hand every red cross to see if it does correspond to an `apt-get` failure.

Would it be possible to improve the scripts such that this happens less often? I don't know if it's possible, but what I have in mind:

1. Do the `apt-get` command
2. Check if it executed properly (I imagine this is possible)
3. If not, sleep for like 10 seconds and try again (do that until it works)

I think that could help a lot. What do you think?

**Comment by MaelRL** [comment]
Still seems to fail at least once per build, e.g. the last build of master : https://travis-ci.org/CGAL/cgal/builds/336596369.
