### ISSUE TITLE
Simplify Polygon_2 (too many points)

### ISSUE THREAD

**Issue by letarg0** [CGAL/cgal#2744]
I add two Polygon_2 each together (union)

```
 P.push_back (Point_2 (0, 0));
 P.push_back (Point_2 (1, 0));
 P.push_back (Point_2 (1, 1));
 P.push_back (Point_2 (0, 1));
 
Polygon_2 Q;
 Q.push_back (Point_2 (1, 0));
 Q.push_back (Point_2 (2, 0));
 Q.push_back (Point_2 (2, 1));
 Q.push_back (Point_2 (1, 1));
 // Obliczamy sumę P oraz Q. 

Polygon_with_holes_2 unionR;  
if (CGAL::join (P, Q, unionR))
  {
```
output:**(0 0) (1 0) (2 0) (2 1) (1 1) (0 1)**

How I can simplify output list of points? I get too many points. I have to get only rectangle (4 points). (0,0) (2,0) (2,1) (0,1)....Is any function to simplify polygon?

**Comment by sloriot** [comment]
I would extract the points of the polygon into a container (like `std::vector`) and remove a point from the container if that point is [`collinear()`](https://doc.cgal.org/latest/Kernel_23/group__collinear__grp.html) with the point before and after it in the container (considering the container as a cycle). Then recreate a polygon from the remaining points.

**Comment by letarg0** [comment]
@sloriot Can You show me a code? I'm beginer
