### ISSUE TITLE
Check why icons color are missing

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#2750]
Compare [that page](https://doc.cgal.org/latest/Algebraic_foundations/annotated.html) to [that page](https://cgal.geometryfactory.com/CGAL/Manual_doxygen_test/CGAL-4.12-Ic-151/master/Algebraic_foundations/annotated.html). Post processing should be replacing the small icons but it seems it is no longer the case for recent version of doxygen.

**Comment by maxGimeno** [comment]
They dropped the <img> tags to use a <span class> instead.

**Comment by lrineau** [comment]
Make it work with both the old and newer version of Doxygen. As that is just "search a pattern and replace it", you can keep the current search-and-replace, and add another one with the new pattern.

**Comment by maxGimeno** [comment]
That does not deal with the fact that only classes are still present in the html code.
