### ISSUE TITLE
Use Lambda with 

### ISSUE THREAD

**Issue by alecjacobson** [CGAL/cgal#2753]
Is it possible to pass a lambda to `Implicit_mesh_domain_3` ?

Something like this:

```c++
// Domain
typedef CGAL::Exact_predicates_inexact_constructions_kernel K;
typedef K::FT FT;
typedef K::Point_3 Point;
typedef FT (Function)(const Point&);
typedef CGAL::Implicit_mesh_domain_3<Function,K> Mesh_domain;

// Triangulation
typedef CGAL::Mesh_triangulation_3<Mesh_domain>::type Tr;
typedef CGAL::Mesh_complex_3_in_triangulation_3<Tr> C3t3;

// Criteria
typedef CGAL::Mesh_criteria_3<Tr> Mesh_criteria;
...
  auto sphere_function = [&](const Point& p)->FT 
  { 
    return CGAL::squared_distance(p, Point(CGAL::ORIGIN))-1; 
  };
  Mesh_domain domain(sphere_function, K::Sphere_3(CGAL::ORIGIN, 2.));
```

Currently I get a type error:

```
./mesh_implicit_sphere.cpp.cpp:181:15: error: no matching constructor for initialization of 'Mesh_domain' (aka 'Implicit_mesh_domain_3<double (const Point_3<CGAL::Epick> &), CGAL::Epick>')
  Mesh_domain domain(sphere_function, K::Sphere_3(CGAL::ORIGIN, 2.));
              ^      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/CGAL/Implicit_mesh_domain_3.h:71:3: note: candidate constructor not viable: no known conversion from '(lambda at ./mesh_implicit_sphere.cpp.cpp:177:26)' to 'double (&)(const CGAL::Point_3<CGAL::Epick> &)' for 1st argument
  Implicit_mesh_domain_3(const Function& f,
  ^
/usr/local/include/CGAL/Implicit_mesh_domain_3.h:85:3: note: candidate constructor not viable: requires single argument 'src', but 2 arguments were provided
  Implicit_mesh_domain_3(const Self& src);
  ^
```

**Comment by lrineau** [comment]
Yes, that is possible. The problem is to use the right type for the type `Function`. In your example, that is:
```C++
typedef FT (Function)(const Point&);
```
that is: a function with one parameter of type `const Point&` and `FT` as return type.

But your functor is a lambda expression. Even if its signature seems to be the right one, its type is not identical to `Function`. See [that StackOverlow question, and answers](https://stackoverflow.com/q/7951377/1728537).

Actually, as lambda expression with no capture is implicitly convertible to a function pointer, your example could work, with a tiny modification: move the capture `[&]` of your lambda, and make it empty `[]`:
```c++
auto sphere_function = [](const Point& p)->FT 
  { 
    return CGAL::squared_distance(p, Point(CGAL::ORIGIN))-1; 
  };
```
and it should work.

Alternatively, you can modify the parameter of `CGAL::Implicit_mesh_domain_3`, and use the real type of your lambda expression:
```C++
typedef CGAL::Exact_predicates_inexact_constructions_kernel K;
typedef K::FT FT;
typedef K::Point_3 Point;

auto sphere_function = [&](const Point& p)->FT 
{ 
  return CGAL::squared_distance(p, Point(CGAL::ORIGIN))-1; 
};

// THIS line is the important modification:
typedef declype(sphere_function) Function; 

typedef CGAL::Implicit_mesh_domain_3<Function,K> Mesh_domain;

// Triangulation
typedef CGAL::Mesh_triangulation_3<Mesh_domain>::type Tr;
typedef CGAL::Mesh_complex_3_in_triangulation_3<Tr> C3t3;

// Criteria
typedef CGAL::Mesh_criteria_3<Tr> Mesh_criteria;
/// [...]
Mesh_domain domain(sphere_function, K::Sphere_3(CGAL::ORIGIN, 2.));

```

**Comment by alecjacobson** [comment]
Belated thanks for the answer. What if I want to capture?

**Comment by lrineau** [comment]
On Tuesday, December 18, 2018 1:03:42 AM CET Alec Jacobson wrote:
> Belated thanks for the answer. What if I want to capture?

That is very similar. The lambda will no longer be convertible to a function 
pointer, but anyway the modification of the code I proposed uses the real type 
of the lambda:

```
typedef declype(sphere_function) Function; 

```

-- 
Laurent Rineau, PhD
R&D Engineer at GeometryFactory           http://www.geometryfactory.com/
Release Manager of the CGAL Project       http://www.cgal.org/
