### ISSUE TITLE
All our Windows test platforms should have /INCREMENTAL:NO /DEBUG:NONE in linker flags

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#2761]
https://cgal.geometryfactory.com/CGAL/testsuite/results-4.12-I-141.shtml

In the linker flags of Windows platforms, you can see that the linker flags are really different from a Windows platform to another.

So save disk space and CPU time, the flags `/INCREMENTAL:NO /DEBUG:NONE` should be in all Windows platforms.

**Comment by maxGimeno** [comment]
Should I add them to the linker flags of the Debug and ReleaseWithDebugInfo too ?

**Comment by lrineau** [comment]
You can add those flags to the general linker flags, independent from the build config:
  - `CMAKE_EXE_LINKER_FLAGS`,
  - `CMAKE_MODULE_LINKER_FLAGS`,
  - `CMAKE_SHARED_LINKER_FLAGS`, and
  - `CMAKE_STATIC_LINKER_FLAGS`.

**Comment by afabri** [comment]
@maxGimeno What has to be reviewed/tested by whom?

**Comment by maxGimeno** [comment]
I don't know, if the testsuite says the flags are where they should be then it's ok. If they are not there then it is not ok.

**Comment by maxGimeno** [comment]
From what I see in [the testsuite](https://cgal.geometryfactory.com/CGAL/testsuite/results-4.12-Ic-173.shtml) 
the flags are here. I close the issue.

**Comment by lrineau** [comment]
Please refresh the copies of config files in `Maintenance/infrastructure/` (as a PR).. Add `fix #2761` in the commit message or in the PR message, so that this issue is then closed automatically.
