### ISSUE TITLE
Algebraic_kernel_d/Shear_controller  calls `srand()`

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#2764]
## Issue Details

CGAL code should not seed a global random number generation function as it is done [here](https://github.com/CGAL/cgal/blob/master/Algebraic_kernel_d/include/CGAL/Algebraic_kernel_d/Shear_controller.h#L62)

This should probably use `CGAL::Random` instead.

@ericberberich can you by any chance comment on  this?

**Comment by afabri** [comment]
This is adresses by PR #2712

**Comment by lrineau** [comment]
I have added "Fix #2764." to the description of #2712, so that Github can automatically close this issue once #2712 is merged.
