### ISSUE TITLE
no access available to stored_polyhedra in Polyhedral_mesh_domain_with_features_3.h

### ISSUE THREAD

**Issue by RizzerOnGitHub** [CGAL/cgal#2766]
Polyhedral meshes in Mesh_3/include/CGAL/Polyhedral_mesh_domain_with_features_3.h are created  using a Polyhedron object which is assigned to the private variable stored_polyhedra.

There does not seem to be an accessor function available which returns the value of stored_polyhedra.

The mesh's Polyhedron is used, for instance, by the FEniCS project in the mshr tool (a tool enabling manipulation of meshes and conversion to the format used by FEniCS, https://bitbucket.org/fenics-project/mshr), 
e.g. l.110 in  mshr / src / Polyhedral_multicomponent_mesh_domain_with_features_3.h 
( https://bitbucket.org/fenics-project/mshr/src/4eb031eb52c0b98261cdb9f5d9a3d02f2cd05907/src/Polyhedral_multicomponent_mesh_domain_with_features_3.h?at=master&fileviewer=file-view-default#Polyhedral_multicomponent_mesh_domain_with_features_3.h-110 )

The FEniCS authors make the Polyhedron accessible by patching the CGAL source code, (mshr/3rdparty/cgal.patch, for CGAL 4.9)

But shouldn't CGAL already be providing an accessor function for the stored_polyhedra property?

**Comment by afabri** [comment]
@lrineau:  Is that trivial to add and do you agree to it (you marked if for 4.12)?  Let me know if you want me to add  it.

**Comment by lrineau** [comment]
If we agree to the API, that is a trivial addition: just an accessor.

**Comment by lrineau** [comment]
That patch however rely a lot on the internals of the implementation, and I cannot ensure that the implementation will not change in a way that no longer permit that API:
https://bitbucket.org/fenics-project/mshr/src/4eb031eb52c0b98261cdb9f5d9a3d02f2cd05907/3rdparty/cgal.patch?at=master

**Comment by RizzerOnGitHub** [comment]
Thanks @afabri and @lrineau .  My thinking is that mshr can be updated if the particulars of the Polyhedron change (can use CGAL_VERSION to allow for API variations if necessary).  The important thing for mshr is that it has access to the Polyhedron. 

It gets used in get_disconnected_components( ), l.117 in Polyhedron_utils.h, 
https://bitbucket.org/fenics-project/mshr/src/4eb031eb52c0b98261cdb9f5d9a3d02f2cd05907/src/Polyhedron_utils.h?at=master&fileviewer=file-view-default#Polyhedron_utils.h-117
Specifically, mshr uses the public API for Polyhedron, with Polyhedron::Vertex_const_iterator  and p.vertices_begin() .

From CGAL's perspective it probably makes more sense to return the std::vector<Polyhedron> rather than the stored_polyhedra[0] that mshr wants to use.  mshr can then apply it's own test on whether the vector contains the expected number of polyhedra or not.

**Comment by lrineau** [comment]
@RizzerOnGitHub The PR #2823 has been merged in CGAL `master` branch. That fix will be in CGAL-4.12-beta1, coming soon.

**Comment by RizzerOnGitHub** [comment]
Thank you!
