### ISSUE TITLE
Polyhedron demo: clipping box surprising behaviors

### ISSUE THREAD

**Issue by sgiraudot** [CGAL/cgal#2768]
## Issue Details

I'm using the Clipping Box plugin with a point set.

1) To move the clipping box faces/edges/etc., there is no modifier key. It could be nice that it only moved when holding `shift` for example (holding `ctrl` makes it turn around, which is good). I don't know if it is a wanted behavior or not, but that is kind of related to the next point.

2) I move the clipping box around, click on "clip", then hide the clipping box, when I try to turn around my point set with click+hold, it doesn't work because it actually moves the hidden clipping box. This is not really user-friendly, it would be better if the box was ignored if it is hidden (note that if the box was only moved when using a modifier key, it would not really be a problem, see previous point).

3) If I deleted the clipping box, the clipping remains active: it can be quite surprising, for example when you delete all items of a scene (including a clipping box) and load another object, you can sometimes see _nothing_ (if the new object is out of the clipping box). Clipping should be switched-off if the clipping box is deleted.

**Comment by maxGimeno** [comment]
1. It is a wanted feature, that was asked when I developped it.
2. It is fixed in the branch fixing all the "minor" features required by @MaelRL : #2759 
3. This is worrying, I remember removing the clipping in the destructor of the item. I'll check and fix it in the branch of #2759
