### ISSUE TITLE
Add text of licenses to the zip file of precompiled DLLs of demo

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#2769]
Maxime, when you prepare the zip file of all DLLs that are dependencies of our CGAL demos, you forgot to include the text of licenses of the libraries we use. For those under LGPL/GPL, that is mandatory, as far as I know.

The file is the one at https://github.com/CGAL/cgal-web/blob/6048f3b5ae2f41e79537786921ffb8a45cbe4020/demo/4.11/CGAL-demoDLLs.zip

It has a `licenses/` subdir, that I have copy-pasted from a previous version of that file. But there are new dependencies: LAS,VTK, maybe others. Read the licenses of those dependencies, and check if that is mandatory to ship the text of the licenses, with the binaries. I think the licenses of Qt5 is missing too.

Unzip the file, add the missing files, rezip the files, and then create a PR in the repo `CGAL/cgal-web` with the new file in Git.

**Comment by afabri** [comment]
Where is the file that is supposed to contain the license information, so that I can check it.

**Comment by maxGimeno** [comment]
https://github.com/CGAL/cgal-web/blob/6048f3b5ae2f41e79537786921ffb8a45cbe4020/demo/4.11/CGAL-demoDLLs.zip in the "license" dir.

**Comment by afabri** [comment]
As @lrineau  pointed   out, in the zip file I also see dlls for las,  opencv, tbbruntime, vtk, zlib. 
@maxGimeno Did you check if we need license files for them as well?

**Comment by maxGimeno** [comment]
Sorry I gave you the wrong link. It was https://github.com/maxGimeno/cgal-web/blob/ebc2a0864c66a1e6844afc94c0696f1674a4c1c7/demo/4.11/CGAL-demoDLLs.zip.
Yes I checked for every dll if we need the license.

**Comment by afabri** [comment]
It is complete now, so we can merge.

**Comment by lrineau** [comment]
https://github.com/CGAL/cgal-web/pull/72 is merged, now.
