### ISSUE TITLE
Polyhedron demo, 32 bits, in the CGAL-4.11.1 branch: a compilation error

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#2770]
There is a strange compilation error in last testsuite of the release branch `releases/CGAL-4.11-branch`. It is strange because it only occurs on one platform, whereas the compilation error speak about missing class members.

```
...\Polyhedron_Demo\Plugins\IO\PLY_to_xyz_io_plugin.cpp(37) : error C2039: 'read_ply_point_set' : is not a member of 'Scene_points_with_normal_item'
...\Polyhedron_Demo\Plugins\IO\PLY_to_xyz_io_plugin.cpp(79) : error C2039: 'write_ply_point_set' : is not a member of 'Scene_points_with_normal_item'
...\Polyhedron_Demo\Plugins\IO\PLY_to_xyz_io_plugin.cpp(37) : error C2039: 'read_ply_point_set' : is not a member of 'Scene_points_with_normal_item'
...\Polyhedron_Demo\Plugins\IO\PLY_to_xyz_io_plugin.cpp(79) : error C2039: 'write_ply_point_set' : is not a member of 'Scene_points_with_normal_item'
```
https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.11.1-I-110/Polyhedron_Demo/TestReport_afabri_x64_Cygwin-Windows8_MSVC2013-Debug-32bits.gz

**Comment by sgiraudot** [comment]
If I remember correctly, these class methods are inside `#ifdef` conditions with some CPP11 features, so there must be an inconsistency between cmake detected features and Boost flags. I can check that later on.

**Comment by lrineau** [comment]
@sgiraudot, did you have a look?

**Comment by sgiraudot** [comment]
Not yet, I'll have a look today.

**Comment by lrineau** [comment]
Simon, is there a PR for this issue? Can you write the number?

**Comment by sgiraudot** [comment]
The decision we took was to not fix this bug and to remove Qt5 from this platform to avoid testing the demo. I don't know how that works (or if there is a PR for this, I can't find). Maybe @maxGimeno knows?

**Comment by maxGimeno** [comment]
2013 Debug 32-bits is never in the testsuite, so I don't know if my removal of Qt5 worked or not. There were no PR, that is for sure.

**Comment by lrineau** [comment]
@maxGimeno There should be a PR that syncs the files in `Maintenance/infrastructure/` with the real file. That PR would be a kind of proof that the `setup` files or CMake caches have been modified.
