### ISSUE TITLE
Platform MSVC2013-Debug-32bits completely broken

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#2771]
https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.12-Ic-159/Installation/TestReport_afabri_x64_Cygwin-Windows8_MSVC2013-Debug-32bits.gz

There is an issue with Boost atomic:
```
  Target "test_gmp_mpfr_dll" links to target "Boost::atomic" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
```

That is a warning, but obviously, that leads to a linker error later.

**Comment by afabri** [comment]
@maxGimeno  : My guess is that the atomic lib is just missing as before what Laurent cited you can see:

//Boost atomic library (debug)
Boost_ATOMIC_LIBRARY_DEBUG:FILEPATH=Boost_ATOMIC_LIBRARY_DEBUG-NOTFOUND

//Boost atomic library (release)
Boost_ATOMIC_LIBRARY_RELEASE:FILEPATH=Boost_ATOMIC_LIBRARY_RELEASE-NOTFOUND

//Boost chrono library (debug)
Boost_CHRONO_LIBRARY_DEBUG:FILEPATH=C:/3rdPartyLibs/boost_1_55_0/lib32/boost_chrono-vc120-mt-gd-1_55.lib

**Comment by maxGimeno** [comment]
Thank you, I switched to boost_1_57 as you are right, boost atomic is
missing from the local boost 1_55

2018-01-29 12:00 GMT+01:00 Andreas Fabri <notifications@github.com>:

**Comment by maxGimeno** [comment]
It is already done, he's ok with it because 1.55 is already tested by other
platforms.

2018-01-29 12:44 GMT+01:00 Andreas Fabri <notifications@github.com>:

**Comment by maxGimeno** [comment]
I had not seen a single run of this platform since my change. I think it always timeout.

**Comment by lrineau** [comment]
I'll reopen this issue if the platform shows up with bad results.
