### ISSUE TITLE
CGAL Crash due to Mingw thread_local bug

### ISSUE THREAD

**Issue by etrinh** [CGAL/cgal#2783]
Following case #991

A bug in mingw  creates some crash in threaded environment:
https://sourceforge.net/p/mingw-w64/bugs/527/
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=83562

thread_local with C++ objects should be avoided with Mingw

**Comment by lrineau** [comment]
That is a complicated matter, because we cannot know which version of Mingw will fix the issue.

And that seems rather complicated to understand which variant of mingw is impacted. It seems to be the combination of `std::thread` from `libstdc++` with the win32 thread model. Is that right?

**Comment by sloriot** [comment]
Closing this issue. Feel free to reopen it if you have the pb with a recent version of CGAL
