### ISSUE TITLE
Strange error on gauguin: Permission denied

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#2796]
https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.12-Ic-167/Circular_kernel_3/TestReport_afabri_x64_Cygwin-Windows10_MSVC2013-Debug-64bits.gz

```
------------------------------------------------------------------
- ProgramOutput.test_Spherical_kernel_basics.x64_Cygwin-Windows10_MSVC2013-Debug-64bits
------------------------------------------------------------------
./cgal_test_with_cmake: line 70: ./test_Spherical_kernel_basics: Permission denied
```

"Permission denied"?! Maybe the exception rules for Windows Defender are not correctly setup on gauguin.

**Comment by janetournois** [comment]
I think they are... but we should check what's happening anyway
Sometimes "permission denied" happens on my machine when the compiler tries to delete a `.pdb` file. It happens occasionally with no explanation...

**Comment by janetournois** [comment]
The test went just fine last night, see :
https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.12-Ic-169/Circular_kernel_3/TestReport_afabri_x64_Cygwin-Windows10_MSVC2013-Debug-64bits.gz

**Comment by maxGimeno** [comment]
Windows's mysterious ways...
