### ISSUE TITLE
The NSIS installer should pull cgal_manual.zip from cgal.org instead of cgal.geometryfactory.com

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#280]
In `wininst/developer_scripts/script_cgal.nsi`, we have:

```
Section /o "HTML Manuals" DOC_Idx
  !ifndef FetchLocal
    !insertmacro DownloadFileFrom "https://cgal.geometryfactory.com/" "CGAL/4.7/Manual/" "cgal_manual.zip"  "$INSTDIR\doc_html"
  !endif  
SectionEnd
```

The `cgal_manual.zip` file should be hosted on doc.cgal.org instead of cgal.geometryfactory.com.

**Comment by sgiraudot** [comment]
This is still an opened issue. @lrineau do you think you will have the time to take care of it or do I assign it to someone else?

**Comment by lrineau** [comment]
I can deal with it. Again, less than one hour of work. I just need to remember I have to do it.

**Comment by afabri** [comment]
@lrineau   https://www.youtube.com/watch?v=Gs069dndIYk
