### ISSUE TITLE
std::uncaught_exception is deprecated

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#2806]
## Issue Details

The [testsuite](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.12-Ic-168/Property_map/TestReport_lrineau_Ubuntu-latest-GCC6-CXX1z.gz)  says that 

> include/CGAL/assertions.h:104:30: warning: 'bool std::uncaught_exception()' is deprecated [-Wdeprecated-declarations]
    (CGAL::possibly(EX)||std::uncaught_exception()?(static_cast<void>(0)): ::CGAL::assertion_fail( # EX , __FILE__, __LINE__))

**Comment by lrineau** [comment]
http://en.cppreference.com/w/cpp/error/uncaught_exception

With C++17, we should use `std::uncaught_exceptions()` instead.
