### ISSUE TITLE
warning: this statement may fall through [-Wimplicit-fallthrough=]

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#2809]
## Issue Details

This [testsuite](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.12-Ic-168/AABB_tree/TestReport_lrineau_Ubuntu-latest-GCC6-Release.gz) warns about _fall throughs_ that cannot happen:  It is a `switch` statement where the developer knows that the cases are exhaustive and each case has a `return`statement.

Shall we nevertheless add it (At the risk that another compiler complains about unreachable code)? Or shall we quiet the compiler with a `#pragma`?

**Comment by mglisse** [comment]
I don't know if there is a macro to make it portable, but with gcc, "default: __builtin_unreachable();" looks good to me (bonus: -fsanitize=unreachable (part of undefined) checks it at runtime). I doubt another compiler would complain about unreachable code, an enum is not restricted to the values it lists, and this is a template.

**Comment by sloriot** [comment]
`CGAL_FALLTHROUGH;`

Used for example in `Triangulation/include/CGAL/Regular_triangulation.h`

**Comment by mglisse** [comment]
You shouldn't use CGAL_FALLTHROUGH in cases that cannot fall through, that's way too misleading.

**Comment by afabri** [comment]
@mglisse Didn't you just explain that enums are not restricted to the values. So maybe we should use `default:` instread of the third and last `case:` ?

**Comment by mglisse** [comment]
> Didn't you just explain that enums are not restricted to the values.

Maybe I should have written "should not" instead of "cannot"? C++ doesn't restrict enum Sign to {-1,0,+1}, but our documentation does.

> So maybe we should use default: instread of the third and last case: ?

You could, that's the simplest, most minimal way to quiet the warning. I tend to prefer adding `default: CGAL_ASSUME(false);` because it is more symmetric, has better checking, and potentially generates slightly better code. But it doesn't seem that important here.
