### ISSUE TITLE
Merge `graph_traits` classes for all triangulation classes

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#2815]
In order to avoid duplicated code, all the `graph_traits` classes should be replaced by an implementation file (like what I did for OpenMesh).

I don't think there is any difference between all the implementation. @afabri  do you agree?

**Comment by afabri** [comment]
If it works it is a good idea. I am probably to blame for the copies.

**Comment by MaelRL** [comment]
There are some issues to fix along the way with the property maps (I didn't do in #2813 for time reasons). The `graph_has_property` are missing everywhere and the `get()` for property map is broken for some tags (for example the `vertex_point_t` with RT2).

**Comment by afabri** [comment]
@sloriot Why is the `#undef` in  the file graph_traits_OpenMesh.h  and not where the `#define` is?

**Comment by sloriot** [comment]
similar to `interface_macro.h`, the macro is defined by the includer.

**Comment by afabri** [comment]
Triangulation_hierarchy_2/Triangulation_2/Constrained_triangulation_2 has 1/2/3 template parameters, which makes  it harder to generalize.

**Comment by sloriot** [comment]
@afabri  did you fix that recently?
