### ISSUE TITLE
Use apt instead of apt-get

### ISSUE THREAD

**Issue by kkatrio** [CGAL/cgal#2816]
## Issue Details

To avoid **apt-get**'s occasional failure to install packages during travis testing, maybe we can use **apt**, which is newer and probably does not suffer form same connectivity issues. This way we could avoid running apt-get in loop until it works.

thoughts? @maxGimeno  @lrineau

**Comment by lrineau** [comment]
Actually, [`apt` was only added in Ubuntu 16.04][*], so we probably cannot use it in Travis, that is rather conservative in its Ubuntu versions.

  [*]: https://itsfoss.com/apt-vs-apt-get-difference/

To be checked...

**Comment by lrineau** [comment]
See also https://askubuntu.com/a/446484/297468 for a quite summary of differences between `apt` and the former tools.

**Comment by maxGimeno** [comment]
They are only in Trusty (14.04).
