### ISSUE TITLE
sscanf_s() instead of sscanf()

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#2818]
## Issue Details

We use ` sscanf()`  in [` CGAL/IO/io.h`](https://github.com/CGAL/cgal/blob/master/Stream_support/include/CGAL/IO/io.h#L180) which triggers a warning for VC++ unless you  ` #define`   `_CRT_SECURE_NO_DEPRECATE`  and ` _CRT_SECURE_NO_WARNINGS`, which we do  in [CGAL_SetupCGALDependencies.cmake](https://github.com/CGAL/cgal/blob/master/Installation/cmake/modules/CGAL_SetupCGALDependencies.cmake#L115)

I replaced ` sscanf()` by ` sscanf_s()`, and made a performance test, reading 1mio points from a file. It goes up from 1.7 to 1.8 sec, that is it is negligible. 

In ` CGAL/IO/io.h` the function is used in a code section that is ` #ifdef`ed for VC++, but in CGAL_ImageIO is another occurence of it.   Shall I only change it for VC++, or can we switch to ` sscanf_s()`  for g++ and clang as well?

**Comment by efifogel** [comment]
Why not use c++ std::istringstream ? Is it slower?

   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by afabri** [comment]
It is in the function replacing operator>>(istream&,double&) for performance problems in some VC++ versionsOn Feb 10, 2018 10:23 PM, Efi Fogel <notifications@github.com> wrote:Why not use c++ std::istringstream ? Is it slower?

   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by lrineau** [comment]
The PR #2819 is now merged in `master`, for CGAL-4.12-beta1. I let you write to the user who requested the change. I do not manage to find out in which email it was.
