### ISSUE TITLE
Support CGAL_NORETURN on MSVC

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#2826]
## Issue Details

Followup to https://github.com/CGAL/cgal/pull/2712#pullrequestreview-96144636:

The proper patch would be to qualify `CGAL::assertion_fail` as [`__declspec(noreturn)`][doc]. All versions of MSVC support that attribute. The macro `CGAL_NORETURN` defined here:
https://github.com/CGAL/cgal/blob/a7a4966de82c48df461ed556e27582f527d7b7e2/Installation/include/CGAL/config.h#L527-L532
should be updated, to that `__declspec(noreturn)` is used with MSVC.

[doc]: https://msdn.microsoft.com/en-us/library/k6ktzx3s(v=vs.110).aspx

The documentation is clear:
> This `__declspec` attribute tells the compiler that a function does not return. As a consequence, the compiler knows that the code following a call to a `__declspec(noreturn)` function is unreachable. 

If `CGAL::assertion_fail` is qualified with `noreturn`, then anything after `CGAL_error()` or`CGAL_error_msg("oups")` is unreachable.

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows
* Compiler: MSVC
* CGAL version: master (before CGAL-4.12-beta1)

**Comment by afabri** [comment]
But don't we then still have a difference in Debug and Release compilations?  With `-DNDEBUG`  our assertions are void so the code coming aftetr the assertion IS reachable, otherwise it isn't and the compiler will issue a non-reachable warning.

**Comment by lrineau** [comment]
For the macros `CGAL_assertion` and `CGAL_assertion_msg` you are right. However the macros `CGAL_error` and `CGAL_error_msg`, that do not check any error condition, have the same effect in Debug and Release: they just call `assertion_fail`.
https://github.com/CGAL/cgal/blob/a7a4966de82c48df461ed556e27582f527d7b7e2/STL_Extension/include/CGAL/assertions.h#L346-L348

As for `CGAL_assertion` being a no-op in Debug,  that is why I created the macro `CGAL_assume`, that is equivalent to `CGAL_assertion` in Debug, but has also an in Release (and thus should be reserved to cases where the condition is really trivial to evaluate). In Release, `CGAL_assume` informs the compiler that the condition cannot be false, so that the compiler is allowed to optimize out the branches where the conditions would be false.

Its definition is in `<CGAL/assertion.h>` (here I quote only the definition in Release):
https://github.com/CGAL/cgal/blob/a7a4966de82c48df461ed556e27582f527d7b7e2/STL_Extension/include/CGAL/assertions.h#L93-L99

and the helper macro `CGAL_ASSUME` is set up in `<CGAL/config.h>`:
https://github.com/CGAL/cgal/blob/a7a4966de82c48df461ed556e27582f527d7b7e2/Installation/include/CGAL/config.h#L534-L545

**Comment by afabri** [comment]
For VC++ the declspec goes before the function as documented [here](https://msdn.microsoft.com/en-us/library/k6ktzx3s.aspx)

**Comment by lrineau** [comment]
The real documentation of where should be the `__declspec` is here:
https://docs.microsoft.com/en-us/cpp/cpp/declspec

But anyway you are right: it is before. As I said in a private discussion, the attributes (both those of gcc/clang, or the C++11 attributes), can be placed either before or directly after the name they qualify.
- [the documentation of C++ attributes](http://en.cppreference.com/w/cpp/language/attributes),
- [the documentation of gcc-style attributes](https://gcc.gnu.org/onlinedocs/gcc/Attribute-Syntax.html). And Clang is compatible with any syntax allowed by gcc.

So the `CGAL_NORETURN` macro can be moved before the declaration of `CGAL::assertion_fail`, and that way that will be compatible with all compilers.
