### ISSUE TITLE
std::iterator depreciation (c++17)

### ISSUE THREAD

**Issue by MaelRL** [CGAL/cgal#2832]
## Issue Details

`std::iterator<> ` is deprecated with C++17 with no replacement (replacement is "write the typedefs in the class") and is used in a few packages, mainly in `CGAL/iterator.h`.

`CGAL::unary_function` was introduced, so should `CGAL::iterator` be introduced too ?

**Comment by lrineau** [comment]
Yes, that would be the minimal/lazy solution.

In libstdc++, the definition of `std::iterator` is the straight-forward implementation of the [norm]:
```C++
template<typename _Category, typename _Tp, typename _Distance = ptrdiff_t,
         typename _Pointer = _Tp*, typename _Reference = _Tp&>
struct iterator
{
  /// One of the @link iterator_tags tag types@endlink.
  typedef _Category  iterator_category;
  /// The type "pointed to" by the iterator.
  typedef _Tp        value_type;
  /// Distance between iterators is represented as this type.
  typedef _Distance  difference_type;
  /// This type represents a pointer-to-value_type.
  typedef _Pointer   pointer;
  /// This type represents a reference-to-value_type.
  typedef _Reference reference;
};
```
[norm]: http://en.cppreference.com/w/cpp/iterator/iterator

**Comment by afabri** [comment]
@lrineau you can assign it to me.

**Comment by afabri** [comment]
Do you agree that we don't document `CGAL::iterator` ?

**Comment by lrineau** [comment]
Even if we put it in the `CGAL` namespace for convenience, `CGAL::iterator` is an implementation details we use. No need to document it, in my opinion.

**Comment by sloriot** [comment]
I think I agree with Andreas, I don't see why we would need to document it as it is an implementation detail that will not appear in the doc (as an implementation detail).
