### ISSUE TITLE
Compilation error when calling intersection with 3 planes with msvc

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#2848]
The following code does not compile with MSVC:
```c++
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>


typedef CGAL::Exact_predicates_inexact_constructions_kernel K;

int main()
{
   typedef K::Plane_3 Plane_3;
   Plane_3 p1,p2,p3;
   CGAL::cpp11::result_of<
      K::Intersect_3(Plane_3, Plane_3, Plane_3)
    >::type inter_res = intersection(p1, p2, p3);

   return 0;
}
```

while the following compiles:
```c++
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>


typedef CGAL::Exact_predicates_inexact_constructions_kernel K;

int main()
{
   typedef K::Plane_3 Plane_3;
   Plane_3 p1,p2,p3;
   
   typedef CGAL::cpp11::result_of<
      K::Intersect_3(Plane_3, Plane_3, Plane_3)
     >::type T;

   T t;
   K::Intersect_3 inter;
   t = inter(p1, p2, p3);

   return 0;
}
```

**Comment by lrineau** [comment]
Do you have more information, like the compilation error message?
In particular, in the following lines:
```C++
   T t;
   K::Intersect_3 inter;
   t = inter(p1, p2, p3);
```
which one does not compile?

**Comment by sloriot** [comment]
that's `intersection(p1, p2, p3);` that does not compile. I don't have the whole message only this:

```
jom: parallel job execution disabled for Makefile
[ 50%] Building CXX object CMakeFiles/autorefinement_sm.dir/autorefinement_sm.cpp.obj
autorefinement_sm.cpp
C:\cgal\git\Intersections_3\include\CGAL/Intersection_traits_3.h(127) : error C2248: 'CGAL::Plane_3<Kernel_>::Line_3' : cannot access private typedef declared in class 'CGAL::Plane_3<Kernel_>'
        with
        [
            Kernel_=CGAL::Epeck
        ]
        C:\cgal\git\Kernel_23\include\CGAL/Plane_3.h(47) : see declaration of 'CGAL::Plane_3<Kernel_>::Line_3'
        with
        [
            Kernel_=CGAL::Epeck
        ]
        C:\cgal\git\Polygon_mesh_processing\include\CGAL/Polygon_mesh_processing/internal/Corefinement/intersection_nodes.h(257) : see reference to class template instantiation 'CGAL::Intersection_traits<Plane_3,CGAL::Bbox_3,CGAL::Segment_3<Kernel_»' being compiled
        with
        [
            Kernel_=CGAL::Epeck
```

**Comment by lrineau** [comment]
Without the full error message that is difficult to guess... But my crystal ball tells me it might be a lookup error, when one of the overloads of `CGAL::internal::intersection(..)` is incorrectly found and tried by the compiler. Then the compiler substitutes `K::Plane_3` for the `K` template parameter, and obviously the instantiation attempt cannot go on. 

Please let them try with the explicit qualification by the CGAL namespace (`CGAL::intersection(p1, p2, p3)`), instead of the argument dependent lookup (`intersection(p1, p2, p3)`).

**Comment by sloriot** [comment]
Ah make senses! @afabri could you confirm that?

**Comment by lrineau** [comment]
Philipp Moeller already pointed out that our `CGAL::internal` namespace is a mess, and we should introduce specific namespaces barriers for the internal functions of the kernel.

I think the issue is that `CGAL::Epick` derives from `CGAL::internal::Static_filters`. That means that `CGAL::internal` is always in the set of namespaces to look for, for any ADL call involving any object of `CGAL::Epick`. That's though for compilers, and MSVC is the first to get easily confused with difficult lookup problems.

**Comment by sloriot** [comment]
Which also explains why it does compile with Simple_cartesian.

**Comment by lrineau** [comment]
@mglisse @bo0ts
Could you confirm that I am not completely wrong with my rant in https://github.com/CGAL/cgal/issues/2848#issuecomment-365990421?

**Comment by mglisse** [comment]
Note that the testcase also fails to compile for me with g++ on linux...

**Comment by sloriot** [comment]
I changed the milestone of this issue to 4.13-beta because the fix will be spread in a lot of files and it might produces conflicts with #2792. Once this PR is merged we will rename the internal namespace for the implementation of intersection functions and at the same time will remove the old macro CGAL_INTERSECTION_VERSION.

**Comment by lrineau** [comment]
#2792 is not planned for 4.12 anyway.

**Comment by afabri** [comment]
I guess we expect users to call `CGAL::intersection(p1,p2,p3)`  (which compiles),  so although I strongly support a cleanup, this is not a serious bug.

**Comment by lrineau** [comment]
I agree. That is particularly not a serious bug because there is that easy workaround: call with the `CGAL::` qualification.

**Comment by sloriot** [comment]
@afabri does your merged PR #2792 addressed this issue? (I'm only talking about the namespace, the old macro is removed in #3781)

**Comment by afabri** [comment]
@MaelRL it would make sense that somebody developing with g++ has a look.

**Comment by lrineau** [comment]
[**@afabri**](https://github.com/afabri) commented on [Jun 10, 2019, 10:21 AM GMT+2](https://github.com/CGAL/cgal/issues/2848#issuecomment-500333520 "2019-06-10T08:21:14Z - Replied by Github Reply Comments"):
> @MaelRL it would make sense that somebody developing with g++ has a look.

I do not understand, because the issue is about a compilation issue with MSVC only.

**Comment by afabri** [comment]
The code of the OP compiles with the master branch.

**Comment by lrineau** [comment]
@sloriot You are the original poster. Shall we just close this issue?

**Comment by sloriot** [comment]
I guess it is fixed by the new intersection namespace introduced.
