### ISSUE TITLE
Error compiling with Apple LLVM 6.1.0

### ISSUE THREAD

**Issue by jeffsteinke** [CGAL/cgal#286]
Hi,

We are experiencing compiler errors when including the following file in our source:

#include <CGAL/Exact_predicates_exact_constructions_kernel_with_sqrt.h>

In Promote.h, Xcode reports that it expects a "member name or ';' after declaration specifiers".  The error occurs on line numbers 55, 61, 66 where a static method check() is defined inside a struct.  check() appears to be used in Poly.cc.

As a test, we simply linked against libCGAL and libCGAL_Core and included the above header file.

Environment:
CGAL 4.6.2
Xcode 6.4 (6E35b)
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)

**Comment by afabri** [comment]
I do not see what you include.
Also what is Promote.h  and Poly.cc?  Both are not part of CGAL.

**Comment by jeffsteinke** [comment]
Sorry, the header file is "Exact_predicates_inexact_constructions_kernel.h".  Promote.h appears to be part of "CORE" (include/CGAL/CORE/Promote.h) as does Poly.tcc.

**Comment by lrineau** [comment]
@jeffsteinke I cannot reproduce that bug. Is it possible that your own code defines a macro named `check`? Can you reproduce that bug with an example code from CGAL, that uses only CGAL headers and nothing else?

**Comment by jeffsteinke** [comment]
Hi,

I was able to get it to work.  There was a configuration problem on my end.  Thanks for the help!

js

**Comment by lrineau** [comment]
Thanks for letting us know. I close the bug.
