### ISSUE TITLE
CGAL Nef_polyhedron_3 Union issue

### ISSUE THREAD

**Issue by JamesYangLim** [CGAL/cgal#2861]
## Issue Details

Hi, I am trying to union 53 blocks from OFF files. However, the result is not closed and seems incorrect. Has anyone seen this kind of behaviour from Nef_polyhedron_3 union? Is this a bug?

These blocks are just random generated.

## Data Files
[Zip containing the cube OFF input files and OFF output file, 14kB](https://drive.google.com/open?id=131SJXrdFGwu7XC2SAY1oAzrp7JD5tf28)

## Output Visualisation
The 53 Blocks look like this:

![53blocks00](https://user-images.githubusercontent.com/30457655/36460900-9e301620-16f5-11e8-9007-5cf33cd13c39.png)

After the union operation:

![unioned53blocks01](https://user-images.githubusercontent.com/30457655/36460923-b6a1fd68-16f5-11e8-8c18-f23c1eef5cc4.png)

Top view:

![topview00](https://user-images.githubusercontent.com/30457655/36461382-0a0255be-16f8-11e8-90c5-751318b1fd49.png)

## Source Code
```
#include "pch.h"
#include <CGAL/Polyhedron_3.h>
#include <CGAL/Surface_mesh.h>
#include <CGAL/Nef_polyhedron_3.h>
#include <CGAL/boost/graph/convert_nef_polyhedron_to_polygon_mesh.h>
#include <CGAL/Exact_predicates_exact_constructions_kernel.h>

#include <iostream>
#include <fstream>
#include <vector>

typedef CGAL::Exact_predicates_exact_constructions_kernel Kernel;
typedef Kernel::Point_3 Point_3;
typedef CGAL::Nef_polyhedron_3<Kernel> Nef_polyhedron_3;
typedef CGAL::Polyhedron_3<Kernel> Polyhedron_3;
typedef CGAL::Surface_mesh<Point_3> Mesh;

TEST(NefTest, unionTest)
{
	std::vector<Polyhedron_3> ps;

	for (int i = 0; i < 53; ++i)
	{
		Polyhedron_3 tempP;
		std::stringstream ss;
		ss << "C:\\Temp\\NefBoolean\\Mesh_" << i << ".off";
		std::ifstream input(ss.str().c_str());
		input >> tempP;
		input.close();
		ps.push_back(tempP);
	}

	std::vector<Nef_polyhedron_3> ns;
	for (auto p : ps)
	{
		ns.emplace_back(Nef_polyhedron_3(p));
	}

	Nef_polyhedron_3 unionedN(ns[0]);
	for (int i = 1; i < ns.size(); ++i)
	{
		unionedN += ns[i];
	}
	
	Mesh m;
	CGAL::convert_nef_polyhedron_to_polygon_mesh(unionedN, m);

	std::ofstream out;
	out.open("c:\\Temp\\OutputMesh.off");
	out << m;
	out.close();
}
```
## Environment

* Operating system (Windows 64 bits):
* Release mode
* CGAL version: 4.11
* Boost version: 1_66_0

**Comment by sloriot** [comment]
The operation with Nef is not an issue, the error you have comes from the conversion from Nef to a polygon mesh. In your output you have some non-manifold edges (edges incident to more that 2 faces) and this kind of data is not representable with a polygon mesh.

**Comment by JamesYangLim** [comment]
@sloriot  Thanks Sebastian, this is very helpful. May I suggest that it throws an exception just like Polyhedron_3 says that the surface is not simple.

**Comment by sloriot** [comment]
You can use the function [`is_simple()`](https://doc.cgal.org/latest/Nef_3/classCGAL_1_1Nef__polyhedron__3.html#a77bac0d5c8715c1257f628ac34b65f61) for that purpose.

**Comment by ankofl** [comment]
> The operation with Nef is not an issue, the error you have comes from the conversion from Nef to a polygon mesh. In your output you have some non-manifold edges (edges incident to more that 2 faces) and this kind of data is not representable with a polygon mesh.

@sloriot In other words, if two grids have touching edges, they cannot be combined?
