### ISSUE TITLE
CGAL-4.12-beta1 does not build on Fedora armv7hl

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#2879]
The [build task for armv7hl](https://koji.fedoraproject.org/koji/taskinfo?taskID=25348734) failed with this log:

https://kojipkgs.fedoraproject.org//work/tasks/8734/25348734/build.log

```
[ 58%] Building CXX object src/CGAL_Qt5/CMakeFiles/CGAL_Qt5.dir/__/__/include/CGAL/Qt/moc_GraphicsViewNavigation.cpp.o
cd /builddir/build/BUILD/CGAL-4.12-beta1/build/src/CGAL_Qt5 && /usr/bin/c++  -DCGAL_Qt5_EXPORTS -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_SVG_LIB -DQT_WIDGETS_LIB -I/builddir/build/BUILD/CGAL-4.12-beta1/build/include -I/builddir/build/BUILD/CGAL-4.12-beta1/include -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtOpenGL -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtCore -isystem /usr/lib/qt5/./mkspecs/linux-g++ -isystem /usr/include/qt5/QtSvg  -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -march=armv7-a -mfpu=vfpv3-d16 -mtune=generic-armv7-a -mabi=aapcs-linux -mfloat-abi=hard -fPIC   -frounding-math -fPIC -std=gnu++11 -o CMakeFiles/CGAL_Qt5.dir/__/__/include/CGAL/Qt/moc_GraphicsViewNavigation.cpp.o -c /builddir/build/BUILD/CGAL-4.12-beta1/build/src/CGAL_Qt5/__/__/include/CGAL/Qt/moc_GraphicsViewNavigation.cpp
In file included from /builddir/build/BUILD/CGAL-4.12-beta1/include/CGAL/Qt/debug_impl.h:35,
                 from /builddir/build/BUILD/CGAL-4.12-beta1/src/CGAL_Qt5/debug.cpp:26,
                 from /builddir/build/BUILD/CGAL-4.12-beta1/build/src/CGAL_Qt5/all_files.cpp:4:
/builddir/build/BUILD/CGAL-4.12-beta1/include/CGAL/gl.h:35:14: fatal error: GLES3/gl3.h: No such file or directory
 #    include <GLES3/gl3.h>
              ^~~~~~~~~~~~~
compilation terminated.
```

Is there anything in CGAL that still need `<CGAL/gl.h>`?!

**Comment by lrineau** [comment]
A grep finds those files:
```
AABB_tree/include/CGAL/internal/AABB_tree/AABB_drawing_traits.h
GraphicsView/include/CGAL/Qt/debug_impl.h
Mesh_3/benchmark/Mesh_3/StdAfx.h
Polyhedron/demo/Polyhedron/include/Point_set_3.h
Polyhedron/demo/Polyhedron/opengl_tools.h
Surface_mesher/archive/include/CGAL/enriched_polyhedron.h
```

**Comment by lrineau** [comment]
In case we cannot fix the package, CGAL-4.12-beta1 will have to depend on `mesa-libGLES-devel`, in Fedora.

**Comment by maxGimeno** [comment]
Most of this is not used and can be removed without a problem, except I cannot test the benchmark of Mesh_3 as CMake won't configure, and I don't know what to do about the Surface_mesher archive, in which native gl calls remain, but I don't think the functions are used. What is the purpose of a directory "archive" ?

**Comment by maxGimeno** [comment]
Also, in Installation there are files (CGAL/Installation/cmake/modules/config/support/print_OPENGL_version.cpp and 
CGAL/Installation/cmake/modules/config/support/test_OPENGL.cpp) that test the OpenGL and glu version and test they link correctly.
 I think they can be removed,at least the test_OPENGL.cpp, for which I see no use at all.
 at list t

**Comment by cjamin** [comment]
You can remove the line in `Mesh_3/benchmark/Mesh_3/StdAfx.h`, it's only used for precompiled headers.

**Comment by maxGimeno** [comment]
Ok, thank you !

**Comment by sloriot** [comment]
`archive` was created as a transition state before removal so that it is not forgotten and see if maintainers will port the deprecated/experimental code.

**Comment by lrineau** [comment]
@maxGimeno That means that you can ignore any code in the `archives/` directories. The code is not maintained/tested anyway.

**Comment by maxGimeno** [comment]
Ok, so I just #if 0 the whole native GL code.

**Comment by lrineau** [comment]
No, remove it.

**Comment by lrineau** [comment]
There will a second beta, CGAL-4.12-beta2, to fix that issue. Let's try to publish it in about 10 days.
