### ISSUE TITLE
CGAL_VERSION and CGAL_VERSION_NR are wrong in beta releases

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#2881]
## Issue Details

In `CGAL-4.12-beta1/include/CGAL/version.h`, we can read:
```
#define CGAL_VERSION 4.12
#define CGAL_VERSION_NR 1041201000
```

I think:
-  `CGAL_VERSION` should be the real name `CGAL-4.12-beta1`, and
- `CGAL_VERSION_NR` should be something like `1041200910` to state that it is not an internal release, but it is not yet a gold release either.

We need to fix `create_new_release` around here:
https://github.com/CGAL/cgal/blob/4f95e55427249ead719eda67b36730e56e6b71e9/Scripts/developer_scripts/create_new_release#L291-L294

As for the new CMake scripts, those values are taken as input anyway:
https://github.com/CGAL/cgal/blob/4f95e55427249ead719eda67b36730e56e6b71e9/Scripts/developer_scripts/cgal_create_release_with_cmake.cmake#L1-L7

## Environment

* CGAL version: CGAL-4.12-beta1

**Comment by maxGimeno** [comment]
I suggest we add an argument like --beta int to decide if it is a beta release and which one it is. I guess the NR would reflect this beta release number like 0910 for beta1, 0920 for beta2, etc.

**Comment by lrineau** [comment]
I agree with both `--beta` and the numbering scheme.
