### ISSUE TITLE
Polyhedron Demo: Bugs with Polyline after Displaying Corners

### ISSUE THREAD

**Issue by sgiraudot** [CGAL/cgal#2882]
## Issue Details

When I have a polyline item, if I hit _Display corners with radius..._, then:
- operations on polylines are no longer available on the menu
- there does not seem to be a way to remove the corner spheres from the scene

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): GNU/Linux
* CGAL version: master

**Comment by maxGimeno** [comment]
Just set their radius to 0 to remove them.
