### ISSUE TITLE
Install SuiteSparse on test platforms

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#2893]
## Issue Details

SuiteSparse is not installed on any of our test platform, and the code of `orbifold.cpp` is not tested anywhere. See for example:
https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.12-Ic-188/Surface_mesh_parameterization_Examples/TestReport_lrineau_Debian-Testing.gz
```
-- NOTICE: The example `orbifold.cpp` will be compiled without the Sparsesuite library.
```

Cc: @MaelRL @afabri 

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): all
* CGAL version: 4.12-beta1

**Comment by lrineau** [comment]
Well, `orbifold.cpp` *is* tested, but without `SuiteSparse`.

**Comment by maxGimeno** [comment]
fixed by[#84](https://github.com/CGAL/cgal-testsuite-dockerfiles/pull/84)

**Comment by lrineau** [comment]
Now we have CMake warnings:
https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.12-Ic-192/Surface_mesh_parameterization_Examples/TestReport_lrineau_Ubuntu-Latest-CXX11.gz

**Comment by maxGimeno** [comment]
see #2907.
