### ISSUE TITLE
Replace use of cgalRequires by tparam

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#291]
Using `cgalRequires` generate a cross linked page `requires.html` that is useless and not good looking. Eventually the macro should disappear.

See [here](http://doc.cgal.org/4.6/STL_Extension/requires.html) for example.

**Comment by afabri** [comment]
In fact the requires in Quadruple seem to be rather strange.

Isn't it kind of normal that what you pass as argument is
not necessarily the type in the parameter list, but most
only be convertible, or constructible ?

Concerning Quadruple, don't we want to deprecate it?

**Comment by lrineau** [comment]
I agree that constructor of Quadruple seems useless!

As for depreciating it, are there CGAL packages using Quadruple in their API?

**Comment by bo0ts** [comment]
`Interpolation` and `Inscribed_areas` both use it.

     ./Interpolation/doc/Interpolation/CGAL/surface_neighbor_coordinates_3.h:102:Kernel> CGAL::Quadruple< OutputIterator, typename Kernel::FT, bool,
     ./Interpolation/doc/Interpolation/CGAL/surface_neighbor_coordinates_3.h:114:class InputIterator, class Kernel> CGAL::Quadruple< OutputIterator,
     ./Interpolation/doc/Interpolation/CGAL/surface_neighbor_coordinates_3.h:128:ITraits> CGAL::Quadruple< OutputIterator, typename ITraits::FT, bool, bool >
     ./Interpolation/doc/Interpolation/CGAL/surface_neighbor_coordinates_3.h:138:ITraits> CGAL::Quadruple< OutputIterator, typename ITraits::FT, bool, bool >
     ./Inscribed_areas/doc/Inscribed_areas/CGAL/Largest_empty_iso_rectangle_2.h:124:Quadruple<Point_2, Point_2, Point_2, Point_2>
