### ISSUE TITLE
Add -Wno-expansion-to-defined to the platform Ubuntu-latest-GCC6-CXX1z

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#2913]
Warning, CGAL CMake scripts add -Wall *after*.

**Comment by afabri** [comment]
If possible only for demos?

**Comment by lrineau** [comment]
See explanations here about the warning, here: https://bugs.webkit.org/show_bug.cgi?id=167643

**Comment by maxGimeno** [comment]
No more warnings like those in the said platform. I'm closing this issue.
