### ISSUE TITLE
Document Triangulation_2_projection_traits_3

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#2915]
The traits is now around for a while and is very useful. It should be documented.
Also an example in the Triangulation_2 package would be nice to have.

@lrineau as the author of the file I assigned you to issue (but @maxGimeno might want to do it).

**Comment by lrineau** [comment]
First we should decide:
- if a geom traits object is supposed to be lightweight, and passed by copy or by reference,
- if a geom traits is supposed to be used as a const object or not.

Those two aspects are not documented, in our concepts, but it is very important for the use of a geom traits with data.

**Comment by sloriot** [comment]
@mhsaar Here is the issue I was mentioning if you want to suggest a better name.

**Comment by sloriot** [comment]
@mhsaar Actually, the points don't need to be coplanar, it just sees the points as projected onto a given plane.

**Comment by mhsaar** [comment]
Before discussing the name, what is the intended behavior for constructions, say two intersecting segments ?
What happens if we give two Segment_3 that are coplanar in a Plane_3 that is not the plane that the class uses for projection ?

**Comment by sloriot** [comment]
In this precise case, using the code of the construction currently in master, you will get the intersection point of the two 3D segments. I remember having used this traits class for computing the silhouette of a triangle mesh given a view point.

**Comment by mhsaar** [comment]
In that case it should indeed exhibit the same behavior as the class I've implemented for CDT2 in a Plane_3. 
In that case I would suggest the name  Triangulation_2_coplanar_traits_3, a model of ConformingDelaunayTriangulationTraits_2

The implementation is intended for Epeck.  For all constructions I map the corresponding functors from 3d via using statements, same for predicates, up to lex compare stuff, for which I take functors from Triangulation_2_coplanar_traits_3.

Shall I put this into a pull request ?

**Comment by sloriot** [comment]
I don't get the difference with yours, maybe with the code it gets clearer (a gist or a draft PR is fine).
