### ISSUE TITLE
AABB tree: add move semantic (Why is copying in AABB_tree made private?)

### ISSUE THREAD

**Issue by skanti** [CGAL/cgal#2925]
https://github.com/CGAL/cgal/blob/72a6f22a382b4662196b6e495805ac5631aadf73/AABB_tree/include/CGAL/AABB_tree.h#L682

The copy constructor in `AABB_tree` is not public. It seems like making `std::vector<AABB_tree>` is not possible without some kind of hack. Any reason why it's there and should not be made `public`?

**Comment by lrineau** [comment]
How would you implement the copy constructor of a tree? A deep copy? We do not really want that a *deep copy* can be made implicit. What we could do is add a *move* constructor to AABB tree, so that `std::vector<AABB_tree>` can be used from C++11.

**Comment by skanti** [comment]
Yes please, do that. Otherwise solutions are hacks like this:

```
std::map<AABB_tree> myMap;
myMap.emplace(
    std::piecewise_construct,  // disambiguation hint
    std::forward_as_tuple(someInt),  // perfectly forward arguments to key_type constructor
    std::forward_as_tuple(polyhedron.facets_begin(), polyhedron.facets_end(),
        polyhedron));
```

**Comment by lrineau** [comment]
I have modified the title of the issue accordingly.

**Comment by lrineau** [comment]
This issue is now registered as a "feature request". You should know that the CGAL project is rather slow at dealing with feature request. However, if you submit a pull-request, then there is a good chance it would be integrated quickly.

**Comment by sloriot** [comment]
@lrineau should have pointed out that the handling of non-trivial pull requests from outside contributors to an existing package is only possible if there is something similar to a copyright assignement/transfert in place. So before coding anything consequent that is meant to be integrated into CGAL, get in touch with the maintainer of the package.

**Comment by lrineau** [comment]
Adding the move semantic to AABB_tree should hopefully be a non-significant contribution.
