### ISSUE TITLE
Dependency of Polygon_mesh_processing on Mesh_3

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#2936]
## Issue Details

In `Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/detect_features.h`
we include files  `Mesh_3/include/CGAL/Mesh_3/properties*.h`

I am not sure where to move that.

## Environment

* CGAL version: master

**Comment by sloriot** [comment]
My feeling is that these files should be included from Mesh_3 directly (before including `detect_features.h` in Mesh_3).

**Comment by lrineau** [comment]
I agree with @sloriot. Anyway, the calling code has to include `<CGAL/Mesh_3/properties_Surface_mesh.h>` or `<CGAL/Mesh_3/properties_Polyhedron.h>`.

**Comment by afabri** [comment]
`CGAL::detect_features()` was originally in Mesh_3, before it was moved to PMP. The files `<CGAL/Mesh_3/properties_*.h>` could be moved to the packages Polyhedron and Surface_mesh. That is what we did for the properties needed for BGL algorithms.

**Comment by sloriot** [comment]
@afabri  I agree, I did not see that the suffix was Polyhedron and Surface_mesh.
