### ISSUE TITLE
Mesh_3, bad choosing of initial points for an implicit surface (or an image)

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#294]
In Mesh_3, when the domain type is an implicit surface or a 3D image, the choosing of the initial points shoots random rays from the center of the bounding sphere. If that center is close to the border of the domain, that can create very close initial points.

A (slightly) better strategy could be that the code searches more initial points than wanted, and then try to find a subset of those points that are as far as possible from each other.

And maybe there should be a constructor of the domain that allows to specify the initial points, in case they are easy to compute without shooting random rays.

**Comment by aympelle** [comment]
An additional solution could be to add a constructor of the domain that takes the origin of rays (or several origins) as parameter.

**Comment by janetournois** [comment]
related to #923

**Comment by sgiraudot** [comment]
Is this issue still valid? I remember @lrineau that you've been working on this, but I can't find a branch (if there is one).

**Comment by lrineau** [comment]
I have been working on similar subjects, for other mesh domain types. For implicit domains, nothing has been done so far. That issue is in the long TODO-list for Mesh_3.

**Comment by janetournois** [comment]
I think we can close this issue, since PR #6978 and #7167 have really improved initial points placement
