### ISSUE TITLE
Dependency of Linear_cell_complex on Polyhedron

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#2949]
## Issue Details

```
Linear_cell_complex/include/CGAL/boost/graph/properties_Linear_cell_complex_for_combinatorial_map.h
27:#include <CGAL/boost/graph/properties_Polyhedron_3.h>

Linear_cell_complex/include/CGAL/Linear_cell_complex_constructors.h
24:#include <CGAL/IO/Polyhedron_iostream.h>
```

That makes Linear_cell_complex (LGPL) depend on the Polyhedron package.

That is something we should solve before CGAL-4.12-beta2.

## Environment

* CGAL version: master 9ebc4c0453509827f2f5e0d32b74e05a5fbb2c0c

**Comment by gdamiand** [comment]
The second problem can be solved easily, replacing #include <CGAL/IO/Polyhedron_iostream.h> by #include <CGAL/IO/File_writer_OFF.h>.

For the first one, this is more complicated. But maybe this is not a problem: indeed this does not make Linear_cell_complex (LGPL) depend on the Polyhedron package; but makes BGL LCC depend on BGL Polyhedron; this stay in the BGL package and thus this is correct (?)

**Comment by lrineau** [comment]
For the moment, what you call "BGL Polyhedron" is shipped in the Polyhedron package. So, for the moment, LCC cannot be used with the Polyhedron package.

**Comment by gdamiand** [comment]
Not LCC but only BGL LCC. If I use LCC outside BGL, it does not depend on Polyhedron and thus lgpl licence is fine.

**Comment by lrineau** [comment]
That is right.

What we are trying to compute now is a set of package-to-package dependencies. They are encoding in `<package>/package_info/<package>/dependencies`. For example, here is the full list of dependencies for LCC:
https://github.com/CGAL/cgal/blob/9ebc4c0453509827f2f5e0d32b74e05a5fbb2c0c/Linear_cell_complex/package_info/Linear_cell_complex/dependencies#L1-L29

That is true that it is an approximation of the truth, because you are right LCC as a whole does not depend on Polyhedron. But there are documented files of LCC that depend on Polyhedron.

And we try to reduce that set of dependencies. Several of the dependencies are due to bad programming design. For example, in Mesh_3, there was a dependency on Surface_mesh, for a class template specialization. By using a forward-declaration of `CGAL::Surface_mesh` instead of the inclusion of the header defining it, I have removed the dependency. And now the code is better, and slightly faster to compile.

So, that hunt of non-natural dependencies may serve a greater goal: better code, faster to compile.

**Comment by gdamiand** [comment]
The second problem should be solved by https://github.com/CGAL/cgal/pull/2953

I will have a deeper look at the first problem, not sure there is a simple solution.

**Comment by gdamiand** [comment]
For the first problem, in properties_Linear_cell_complex_for_combinatorial_map.h I use the two struct internal::Edge_index_accessor and internal::Point_accessor defined in properties_Polyhedron_3.h.

These two struct are small (about 10 lines of code each) thus I can copy/paste their code in properties_Linear_cell_complex_for_combinatorial_map.h (but this is not really pretty).

**Comment by afabri** [comment]
You can only copy it if you rename it or put it into a namespace. Let me see, if we can extract it and put it for example into BGL.

**Comment by afabri** [comment]
In which example or test is it used??

**Comment by gdamiand** [comment]
In some BGL tests, for example
  graph_concept_Linear_cell_complex.cpp
  test_bgl_read_write.cpp 
  test_Euler_operations.cpp

**Comment by afabri** [comment]
I moved the internal classes, so the dependency is gone. 
Concerning the file `properties_Linear_cell_complex_for_combinatorial_map.h `  it should better be included directly by LCC or CC, or do you document this header somewhere so that uses know that they have to include it in order to use a BGL-style algorithm?

**Comment by gdamiand** [comment]
Thanks @afabri !

About properties_Linear_cell_complex_for_combinatorial_map.h, it is include in graph_traits_Linear_cell_complex_for_combinatorial_map.h and it is documented that the specialization of BGL for LCC is defined in this file; thus I think it is correct ?
