### ISSUE TITLE
Segmentation fault when inserting segments into an arrangement

### ISSUE THREAD

**Issue by petersadro** [CGAL/cgal#296]
I am seeing a segmentation fault when inserting an array of 32 linear segments into an empty arrangement.  I am using EPEC kernel, and Arr_segment_traits_2 for the arrangement.

I've place a test program, and a data file which I can reproduce the error in a gist here:

<url>https://gist.github.com/petersadro/c12a869d2cc1ef84243e</url>

I am using CGAL 4.6.1-1.fc22 ( fedora 22 package )
compiling with gcc (GCC) 5.1.1 20150618 (Red Hat 5.1.1-4)

Again, if this is determined to be a valid issue, you may incorporate the prog/data in CGAL unit tests.

Thank you,
Peter Sadrozinski

**Comment by sloriot** [comment]
You have a degenerate segment in your input.
If you check `source!=target` before adding a segment in `segs` you won't have the crash.
Note that compiling in debug mode would have gave you an assertion failure complaining about a degenerate input.
