### ISSUE TITLE
AABB_primitive< Id, ObjectPropertyMap, PointPropertyMap>: property maps must be CopyAssignable

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#2962]
## Issue Details

In [the documentation of `AABB_primitive< Id, ObjectPropertyMap, PointPropertyMap>`][doc-4.12], it is said that the two property maps must be `DefaultConstructible`. 

[doc-4.12]: https://doc.cgal.org/4.12/AABB_tree/structCGAL_1_1AABB__primitive.html

`CopyAssignable` and `CopyConstructible` should also be mentioned.

## Environment

* CGAL version: 4.12

**Comment by sloriot** [comment]
Only `CopyConstructible` is needed since `CopyAssignable` and `DefaultConstructible` are needed only if the default values are used in the constructor (and the fact that you use it implies that you now they are also model of those 2 concepts.

**Comment by lrineau** [comment]
In this constructor:
```C++
  template<typename ConstPrimitiveIterator, typename ... T>
  AABB_tree<Tr>::AABB_tree(ConstPrimitiveIterator first,
                           ConstPrimitiveIterator beyond,
                           T&& ... t)
    : m_traits()
    , m_primitives()
    , m_p_root_node(NULL)
    , m_p_search_tree(NULL)
    , m_search_tree_constructed(false)
    , m_default_search_tree_constructed(false)
    , m_need_build(false)
  {
    // Insert each primitive into tree
    insert(first, beyond,std::forward<T>(t)...);
  }
```
the `AABB_traits` object `m_traits` is constructed by default, and thus also the
shared data it contains (with `AABB_primitive`: the pair with the two
property maps). That explains the requirement for `DefaultConstructible` (at least in the case of shared data).

And, in AABB_traits:
```C++
  template <typename ... T>
  void set_shared_data(T&& ... t){
    m_primitive_data=Primitive::construct_shared_data(std::forward<T>(t)...);
  }
```
Here the shared data is copy-assigned, and thus the property maps must also be `CopyAssignable` (at least in the case of shared data).

**Comment by sloriot** [comment]
OK, I've updated the PR
