### ISSUE TITLE
Floating point overflow when loading CGAL-vc140-mt-gd-4.10.1.dll

### ISSUE THREAD

**Issue by CathDoiron** [CGAL/cgal#2981]
## Issue Details

There is a floating point overflow when I load CGAL-vc140-mt-gd-4.10.1.dll.

>	CGAL-vc140-mt-gd-4.10.1.dll!CGAL::internal::`dynamic initializer for 'infinity''() Line 128	C++

This is in the file include\CGAL\FPU.h, at line 128:
const double infinity = HUGE_VAL;

This line is exactly the same with CGAL 4.11.1, so I believe the same issue occurs with the latest CGAL version.

It only happens with Visual Studio 2015. It looks like the definition of HUGE_VAL changed in math.h between Visual Studio 2013 and 2015.

## Source Code

```
static void sigFPEHandler(int sig, int num)
{
    printf("FPE: %d\n", num);
}

void enableFloatingPointExceptions()
{
    unsigned int prevFpu = 0;
    _controlfp_s(&prevFpu, _EM_UNDERFLOW | _EM_INEXACT, _MCW_EM);

    if (SIG_ERR == signal(SIGFPE, (void (__cdecl *)(int))sigFPEHandler))
    {
        printf("Couldn't set signal SIGFPE");
    }
}

int main( int argc, char *argv[] )
{
    enableFloatingPointExceptions();
    HMODULE h = ::LoadLibrary(L"D:\\3rdParty\\CGAL\\bin\\CGAL-vc140-mt-gd-4.10.1.dll");
    return 0;
}
```

## Environment

CGAL 4.10.1
Windows 10 64 bits
Visual Studio 2015
Same issue in debug (CGAL-vc140-mt-gd-4.10.1.dll) and in release (CGAL-vc140-mt-4.10.1.dll).

**Comment by lrineau** [comment]
With CGAL, if you set the exception mask of the FPU like you did, with `_EM_UNDERFLOW | _EM_INEXACT`, you will get a lot of exceptions. What did you expect?

**Comment by CathDoiron** [comment]
No I used CGAL with Visual Studio 2010 and 2013 before, and I didn't get any floating point exceptions (_EM_INVALID, _EM_ZERODIVIDE or _EM_OVERFLOW). Now with Visual Studio 2015, the library won't even load because of this _EM_OVERFLOW.

I know I will have _EM_INEXACT exceptions, this is why I disable them.

**Comment by lrineau** [comment]
That code dates from a long time ago: https://github.com/CGAL/cgal/commit/66e685efae6edc405175aeb0568f82e8701e64d6

Maybe it's time to use `std::numeric_limits<double>::infinity()` on all platforms.

Would it solve your issue?

**Comment by CathDoiron** [comment]
You can check `std::numeric_limits<double>::has_infinity` if you still support old compilers.

I will modify the code, recompile CGAL, and test again to see if I still have an overflow.

**Comment by CathDoiron** [comment]
Yes issue is fixed when I use `std::numeric_limits<double>::has_infinity` instead of `HUGE_VAL`.

**Comment by lrineau** [comment]
`std::numeric_limits<double>::has_infinity` must be `true` on all the platforms CGAL support (implementing IEEE 754).

The problem, long ago, was about compilers with incomplete or buggy support of the header `<limits>`. But all the platforms CGAL support now have a correct `<limits>` header, as far as I know. We can certainly drop the use of `HUGE_VAL`, and use `std::numeric_limits<double>::infinity()` instead.

I still do not understand how the implementation of `HUGE_VAL` can trigger an overflow with MSVC. But that does not matter.

**Comment by mglisse** [comment]
AFAICS internal::infinity is used in a single place in Interval_nt.h, we might as well remove the variable infinity and use numeric_limits directly in Interval_nt.h. We already use numeric_limits in several other files.

**Comment by lrineau** [comment]
@mglisse You are right. That would be the more readable.

**Comment by CathDoiron** [comment]
Awesome. Thank you gentlemen.
