### ISSUE TITLE
Minor bug in C3T3_helper.h

### ISSUE THREAD

**Issue by SLopezBRGM** [CGAL/cgal#300]
Line 1165 of `C3T3_helpers.h` replace:
```C++
if ( c3t3_.triangulation().is_infinite(ch) )
        return false;
```
with :
```C++
if ( c3t3_.triangulation().is_infinite(ch) )
        return Subdomain();
```
In case of generic indexes for `Subdomain` the conversion `false` -> `Subdomain_index` may fail.

**Comment by lrineau** [comment]
Thanks, Simon.

I have pushed that patch in our `integration` branch. CGAL/cgal-dev@bb7828e2ae392e5419176a58c1fdfb7e551c8b2c

Once it is tested, I will recommit it in `master`.
