### ISSUE TITLE
Mesh_domain_with_features_3: add `add_corner()` and `add_corner_with_context()`

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#3011]
## Issue Details

Feature request: in the class template `CGAL::Mesh_domain_with_features_3`, you may need to add isolated vertices as corners, in the mesh (like the tip of a 3D cone), or register that a corner is incident to specific surfaces (imagine the intersection of a 1D polylines, like a well, with a surface).

(Cc @SLopezBRGM)

**Comment by MaelRL** [comment]
`add_corner()` is already being added as part of P3M3 (https://github.com/CGAL/cgal/pull/2658/commits/d6f0061181e1e3a35e1c0e0345b6c2082fbb5849).

It can be cherry-picked or I can look into the context version, as you prefer.

**Comment by lrineau** [comment]
I knew we had already talked about that! I searched in the PR and issues, but did not found the discussion. I had forgot that it was in the P3M3 branch.

Well, ... anyway that new feature will only be in CGAL-4.13, so why not through your branch?

The point about `add_corner_with_context()` is how can we declare that a corner is incident to a given surface patch. With `add_corner()`, that corner may be incident to a surface patch, but not incident to any curve incident to the patch. We should have a way to declare that incidence.

**Comment by lrineau** [comment]
You are right: that could be added to 4.12 as non-documented functions. That would be useful.

**Comment by MaelRL** [comment]
See a6d8d4a and 6c88391.

**Comment by lrineau** [comment]
Fixed by the merge of #3073.
