### ISSUE TITLE
General kernel support in Mesh_skeletonization

### ISSUE THREAD

**Issue by riaqn** [CGAL/cgal#3024]
## Issue Details

Currently there are some uses of double in the code of Mesh_skeletonization, making it impossible to use kernel other than inexact ones.

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Linux 64bit
* Compiler: gcc 7.3.1
* Release or debug mode: release
* Specific flags used (if any):
* CGAL version: 4.11
* Boost version:1.66.0
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by sloriot** [comment]
Are you simply reporting a documentation error or are you really interested by having the code working on points from an exact construction kernel? In the latter case, what do you expect to get compared to using floating point?

**Comment by riaqn** [comment]
Hi @sloriot  thanks for the reply.

I don't know - I was using it to contract a mesh(for only once) and while the source mesh is free of self-intersection, the meso_skeleton() is not. So I assume it might have to do with the exact-ness.

**Comment by sloriot** [comment]
The meso-skeleton is by construction not guaranteed to no self-intersect. The only guarantee you have is that it has the same topology as the input mesh.

**Comment by riaqn** [comment]
Hmm, do you know if there is anything I can do to achieve the same goal?

**Comment by sloriot** [comment]
I don't think we have anything like that in CGAL for now.
