### ISSUE TITLE
Question on the effect of CMAKE_BUILD_TYPE for downstream project

### ISSUE THREAD

**Issue by jasjuang** [CGAL/cgal#3025]
## Issue Details

With the latest CGAL, when I build it without specifying `CMAKE_BUILD_TYPE`, I will get the below warning when configuring CMake, 

```
  =======================================================================

   CGAL performance notice:

   The variable CMAKE_BUILD_TYPE is set to "".  For performance reasons, you
   should set CMAKE_BUILD_TYPE to "Release".

   Set CGAL_DO_NOT_WARN_ABOUT_CMAKE_BUILD_TYPE to TRUE if you want to disable
   this warning.

  =======================================================================
```

after specifying `CMAKE_BUILD_TYPE` to Release and build it, while I am using CGAL with my downstream with 

```
find_package(CGAL REQUIRED)

target_link_libraries(${PROJECT_NAME} CGAL::CGAL)
```

I get the same warning if I didn't set `CMAKE_BUILD_TYPE` to Release for my downstream project. Which is a bit confusing to me because if CGAL is already compiled with Release mode upstream, why do I need to also compile in Release mode for the downstream to get optimal performance from CGAL? Is this a bug or is it something I am missing?

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Ubuntu 16.04 LTS
* Compiler: GCC 5.4
* CGAL version: Latest
* Boost version: 1.58

**Comment by sloriot** [comment]
Are you using CGAL in header only, without initial configuration of the library?

**Comment by lrineau** [comment]
@jasjuang Actually CGAL is a library of templates, and as such almost all of its code is compiled only during the compilation of the downstream project, when CGAL templates are used (instantiated). That is why that is important, for a project using CGAL, to use the compiler optimizations.

**Comment by jasjuang** [comment]
@lrineau Thanks a lot for the explanation.
