### ISSUE TITLE
Feature Request: make mst_orient_normals keep the original indices or return information on how the indices are ordered

### ISSUE THREAD

**Issue by jasjuang** [CGAL/cgal#3033]
## Issue Details

I have a set of colored point cloud and the normals are calculated with pca_estimate_normals or jet_estimate_normals. The problem is the estimated normals might have wrong orientation, so we need to use mst_orient_normals to re-orient it to the right direction, but the problem is the indices are re-organized by mst_orient_normals as shown in line 635 of https://github.com/CGAL/cgal/blob/master/Point_set_processing_3/include/CGAL/mst_orient_normals.h

This is a problem because now we can't relate the original color indices with the re-oriented points anymore. Is it possible to make mst_orient_normals keep the original indices or return information on how the indices are ordered in order for me to match with the color?

What would be even better is if mst_orient_normals can support color point cloud as an input. Would this be easier to implement?

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Ubuntu 16.04
* Compiler: GCC 5.4
* Release or debug mode: Release
* CGAL version: Latest
* Boost version: 1.58
* Other libraries versions if used (Eigen, TBB, etc.): Eigen 3.3.90

**Comment by sloriot** [comment]
I'm pretty sure you can already do that using the point and normal property maps. You only have to provide a different container to be sorted while your points stay where they are. That's what is done basically in the following [example](https://doc.cgal.org/latest/Spatial_sorting/Spatial_sorting_2sp_sort_using_property_map_3_8cpp-example.html).

**Comment by jasjuang** [comment]
@sloriot Thank you so much for the pointer.
