### ISSUE TITLE
PMP::do_intersect not working with custom vpm

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#3047]
The following program does not compile I think it should:

https://gist.github.com/sloriot/e2cbd672d700708d850e714a6cf363f9

**Comment by maxGimeno** [comment]
It is documented that the two property map types must be the same. It is not the case in your program, so I don't think it is a bug. 
We can still change the doc and make it work though.

**Comment by sloriot** [comment]
Right I remember now. Actually, the use case I was trying was to test the intersection of two shapes, one being the transformation of the other using a property map doing the transformation on the fly. If this is not too complicated to have it would be nice. I re-tag it to feature request then.
