### ISSUE TITLE
Adding a function transform in PMP

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#3048]
Add a transform function in PMP that is taking a mesh and apply a `CGAL::Aff_transformation_3` on it.

**Comment by sloriot** [comment]
It can be used in the demo plugin I guess (that should basically contain all the code).

**Comment by maxGimeno** [comment]
The demo does not use an Aff_transformation_3, it uses QMatrix4x4.

**Comment by lrineau** [comment]
Fixed in `master` (for CGAL-4.13), by the merge of PR #3052.
