### ISSUE TITLE
Install redirect

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#3072]
The following redirects (not 100% sure of the syntax)
https://gist.github.com/sloriot/0261c0462a396f0db76a297c9d08d1d3

must be installed in the doc due to changes introduced by #2608

**Comment by sloriot** [comment]
I found the issue when I looked on google for `Kernel_traits` that gave me this broken link: https://doc.cgal.org/latest/Kernel_23/classCGAL_1_1Kernel__traits.html

**Comment by lrineau** [comment]
Done. Thanks.
