### ISSUE TITLE
compilation error with visual studio2010 

### ISSUE THREAD

**Issue by Simona787** [CGAL/cgal#3078]
_Please use the following template to help us solving your issue._

## Issue Details

 I found that variadic templates  are using in CGAL/include/Propertymap.h, such as template<int N, typename ...T> in the 334th row, but it seems that  vs2010 doesn't support  variadic templates. Becuase here comes something compilation errors when I use some cgal functions in my own project. And for some reason I can not change the compiler.

so, I wonder if it is possible for me to modify the  source codes in CGAL/include/Propertymap.h to solve these problems?

## Source Code
![error](https://user-images.githubusercontent.com/17819275/39758017-3a9a77b6-5301-11e8-929e-c7b1c1ea6bf8.png)

## Environment

* Operating system (Windows10 ,X64/):
* Compiler: vs2010
* Release or debug mode:release, win32
* Specific flags used (if any):
* CGAL version:4.12
* Boost version:1.65
* Other libraries versions if used (Eigen, TBB, etc.):Eigen3

**Comment by afabri** [comment]
You need at least VS 2013.   What we write on [Supported Platforms](https://doc.cgal.org/latest/Manual/installation.html#title7) in the manual is outdated.

**Comment by lrineau** [comment]
Actually you need Visual Studio 2012 or later. We dropped the support for Visual Studio 2010 since 4.10, without any announcement. We have been pretty bad at those announcement in the past. We will try to fix that.

**Comment by Simona787** [comment]
thanks

**Comment by Simona787** [comment]
thanks
