### ISSUE TITLE
std::equal_to<T>::result_type deprecated in C++17

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#3083]
## Issue Details

See [cppreference ](http://en.cppreference.com/w/cpp/utility/functional/equal_to)

Warning in the [`Kernel_d` testsuite](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.13-Ic-6/Kernel_d/TestReport_afabri_x64_Cygwin-Windows10_MSVC2017-Debug-64bits.gz)

Note that we get the warning also for many other functors of the STL, for example when they are used in `Compose` classes in [`<CGAL/function_objects.h>`](https://github.com/CGAL/cgal/blob/master/STL_Extension/include/CGAL/function_objects.h).

We probably should also deprecate them.   
@mglisse, @lrineau   Do we have to use `result_of`or `invoke_result` instead ([cppreference](http://en.cppreference.com/w/cpp/types/result_of))

## Environment

* Compiler: VC++ 2017
* CGAL version:  master

**Comment by lrineau** [comment]
[**@afabri**](https://github.com/afabri) commented on [May 10, 2018, 12:47 PM GMT+2](https://github.com/CGAL/cgal/issues/3083#issue-321889199 "2018-05-10T10:47:14Z - Replied by Github Reply Comments"):
> @mglisse, @lrineau   Do we have to use `result_of`or `invoke_result` instead ([cppreference](http://en.cppreference.com/w/cpp/types/result_of))

I think our `CGAL::cpp11::result_of` will have to be implemented in term of `std::invoke_result` (or `boost::result_of`) for C++20 and later.
```c++
#if CGAL_CXX11
#  include <type_traits>
#else // C++<11
#  include <boost/utility/result_of.hpp>
#endif // end C++<11

namespace CGAL {
  namespace cpp11 {
#if CGAL_CXX20
    template <typename Signature> class result_of;

    template <typename F, typename... Args>
    class result_of<F(Args...)> : public std::invoke_result<F, Args...> {};
#elif CGAL_CXX11
  using std::result_of
#else // C++<11
  using boost::result_of;
#endif // 
  } // end cpp11
} // end CGAL
```

Then, once drop the support for C++03 and only support C++11 or later, we can switch to the API of `std::invoke_result`, with variadic templates: we will create a `CGAL::cpp20::invoke_result`, being a `using std::invoke_result` (if C++>=20) or a reimplementation using `std::result_of`.
```c++
// now we require C++11 or later
#include <type_traits>

namespace CGAL {
  namespace cpp20 {
#if CGAL_CXX20
    using std::invoke_result;
#else // C++<20
    template <typename F, typename... Args> using invoke_result = result_of<F(Args...)>;
#endif // end C++<20
  } // end cpp20
} // end CGAL
```

We can even do both during a transition period.
