### ISSUE TITLE
How to link CGAL with Intel MKL 2018

### ISSUE THREAD

**Issue by sunshinemyson** [CGAL/cgal#3103]
## Issue Details

I want to link CGAL with intel MKL 2018 to accelerate CGAL math operation performance on my Intel E2699 V4 CPU. But i found that findMKL.cmake not update for MKL 2018, some library already out of date. 

## Source Code
env variable setted:
MKL_INC_DIR=/opt/intel/mkl/include
MKL_LIB_DIR=/opt/intel/mkl/lib/intel64
INTEL_RTL_LIB_DIR=/opt/intel/compilers_and_libraries_2018.2.199/linux/compiler/lib/intel64_lin
cmake -WITH_MKL=ON

I failed at check_function_exists(${_name}_ ${_prefix}_${_name}_${_combined_name}_f2c_WORKS) in findMKL.cmake. which ${_name}_ is SGEMM_
## Environment

* Operating system (Linux, 64 bits):
* Compiler: gcc 5.4.0
* Release or debug mode: Release
* Specific flags used (if any):
* CGAL version: 4.12
* Boost version: 
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by lrineau** [comment]
Actually, I do not think CGAL supports MKL any more. In my opinion, the file `Installation/cmake/modules/FindMKL.cmake` should be removed from CGAL. The upstream `FindBLAS` and `FindLAPACK` modules shipped by CMake, seem to support MKL, at least up to its version 10. But MKL 2018 does not seem supported.

Which operation do you expect to accelerate, using it with CGAL? Now in CGAL we use the Eigen3 library for almost all our linear system resolutions. It seems MKL can be used with Eigen3: https://eigen.tuxfamily.org/dox/TopicUsingIntelMKL.html
