### ISSUE TITLE
Document the CGAL CMake API

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#3105]
## Issue Details

With CGAL 4.12, the CMake API of CGAL has been modernized. In CGAL-4.13 we should now document how to use CGAL with CMake.

*(Actually, I thought there was already an issue entry for that but I cannot find it.)*

Here is a draft: https://github.com/CGAL/cgal/wiki/How-to-use-CGAL-with-CMake-or-your-own-build-system

**Comment by lrineau** [comment]
Once, that task is done, we should open an other one, more complicated, that would document how to use CGAL *without* CMake.

**Comment by MaelRL** [comment]
Related to https://github.com/CGAL/cgal/issues/4015 and similar.
