### ISSUE TITLE
radius error in Min_circle_2

### ISSUE THREAD

**Issue by OldwolfJiang** [CGAL/cgal#3120]
i have a problem with CGAL, i want to calculate a minimun circle.
src data are as follows: (count 5)

            pt1 = 1187.5005, 987.1543
            pt2 = 1310.9678, 1099.8071
            pt3 = 1472.0121, 1083.7139
            pt4 = 1490.8005, 954.9678
            pt5 = 1375.3855, 893.277

The result of the calculation is:  1342.12 999.014 24046.9 (x y r)
Obviously,the radius is wrong.
I don't know where the problem is, please help find bug, thank you very much!
so,I don't know if I'm using it correctly,I get the following parameters for the circle:
```c++
typedef  CGAL::Exact_predicates_exact_constructions_kernel		clExactK;
typedef  CGAL::Min_circle_2_traits_2<clExactK>				clExactTraits2;
typedef  CGAL::Min_circle_2<clExactTraits2>		        		clExactTraitsMinCircle2;
typedef  clExactK::Point_2				                                clExactPoint2;

	clExactTraitsMinCircle2  mc2(mPts, mPts + count, false);
	if (mc2.is_valid() == false)
	{
		cx = 0;
		cy = 0;
		r = 0;
		return Errs::Err_Data_Error;
	}

	cx = mc2.circle().center().approx().x().inf();
	cy = mc2.circle().center().approx().y().inf();
	r = mc2.circle().squared_radius().approx().inf();
	std::cout << mc2.circle();
```

**Comment by MaelRL** [comment]
`r` is the **squared** radius. It looks correct to me:
```
cx/cy/sqr: 1342.12 999.014 24046.9
radius: 155.071
squared distance to p0: 24046.9
squared distance to p1: 11129.5
squared distance to p2: 24046.9
squared distance to p3: 24046.9
squared distance to p4: 12287.1
points on the min circle: 3
```

However, you should not use `approx().inf()` as a way to approximate your exact result as `approx()` returns an interval whose width might be arbitrarily large. You should instead call `exact()` to reduce the size of the interval and use [`CGAL::to_double()`](https://doc.cgal.org/5.0/Algebraic_foundations/group__PkgAlgebraicFoundationsRef.html#ga1f1bcd74fce34fd532445590bbda5cd5) afterwards.
