### ISSUE TITLE
Parametric intersection two cubic Bezier curves

### ISSUE THREAD

**Issue by alecjacobson** [CGAL/cgal#3125]
@psarahdactyl and I are a bit lost in the [2D arrangements documentation](https://doc.cgal.org/latest/Arrangement_on_surface_2/index.html). It appears to be _very_ powerful and maybe overkill for what I'd like to. 

I have as input two cubic planar Bezier curves represented by quadruplets of 2d points A={a1,a2,a3,a4} and B={b1,b2,b3,b4}. I'd like to find out if they intersect. 

If they intersect...
- ...at disconnected set of points, I'd like to gather the parameter(s) {t0,t1,t2,...} along A and the parameter(s) {s0,s1,s2,...} along B of the intersection point(s) 

and/or

- ...along a shared subcurve, then the parameter interval [t0,t1] along A and the parameter interval [s0,s1] along B.

Is there an easy way to achieve this?

**Comment by psarahdactyl** [comment]
Okay, thank you. That is what I'm doing as of now. 

I was wondering if it's possible to calculate this for _many_ Bezier curves and take advantage of the [compute_subcurves()](https://doc.cgal.org/latest/Surface_sweep_2/group__PkgIntersectionOfCurves2.html#ga057822eb7bc42f6ef55914ba772d9f9c) function, while still maintaining the indices of the original input curves.
Is there a way to keep track of this information in the 2D arrangements? For example, in [Box_with_handle_d()](https://doc.cgal.org/latest/Box_intersection_d/classCGAL_1_1Box__intersection__d_1_1Box__with__handle__d.html#a8d0e71d7a688db452289e6da1d7f26ee), I can use an iterator to keep track of the input with a [Handle](https://doc.cgal.org/latest/Circulator/classHandle.html). Does this exist for a 2D arrangement?

**Comment by sloriot** [comment]
Try [Arrangement_with_history_2](https://doc.cgal.org/latest/Arrangement_on_surface_2/classCGAL_1_1Arrangement__with__history__2.html)

**Comment by psarahdactyl** [comment]
Thank you! This is exactly what I need.
