### ISSUE TITLE
MATHJAX_RELPATH is wrong, in Doxygen 1.8.13

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#3134]
## Issue Details

The commit 5e81643b5369cc4b0c2425ac48d8131dd4d387b5 let MathJax choose the default for the location of MathJax (variable `MATHJAX_RELPATH` in Doxyfile). However, the default of that variable:
  - is `http://cdn.mathjax.org/mathjax/latest` for Doxygen<=1.8.13
  - is `https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/` since DOxygen 1.8.14.

and the old URL `http://cdn.mathjax.org/mathjax/latest` is blocked by Firefox when a CGAL developer uploads his/her documentation to a web service served by https: (such our own server https://cgal.geometryfactory.com/).

@sgiraudot had that issue this morning.

What could be do? Could we "let doxygen decide what is MATHJAX_RELPATH by default" only if we detect Doxygen 1.8.14 or later?

**Comment by sloriot** [comment]
That's pretty strange, I though the default was https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2.
After checking it seems to be the old URL. So a fix similar to 1.8.4 should be sufficent.
