### ISSUE TITLE
How to use CGAL in a project using CMake (previously FindCGAL.cmake)

### ISSUE THREAD

**Issue by janetournois** [CGAL/cgal#3137]
## Issue Details

Some external projects are using CGAL, and each of them has its home-made `FindCGAL.cmake`, that is often not very adapted to dealing with branch-development, nor the header-only version of CGAL, etc.

What would you think of submitting a `FindCGAL.cmake` to `CMake` to get rid of this issue?

**Comment by sloriot** [comment]
There is no need for a FindCGAL since CGAL is using the [config mode](https://cmake.org/cmake/help/v3.0/command/find_package.html) of cmake (like QT5 is doing). Maybe an entry in the documentation should be added (in a section mentioning integration with other projects?).

**Comment by janetournois** [comment]
Ok I understand.
An entry in the documentation, explaining how to use config mode to use CGAL would certainly be helpful

**Comment by lrineau** [comment]
Replaced by #3105.
