### ISSUE TITLE
ZLIB not correctly set up on gauguin

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#3146]
In [the testsuite, last Friday night](https://cgal.geometryfactory.com/CGAL/testsuite/results-4.13-Ic-27.shtml):
```
Installation/TestReport_afabri_x64_Cygwin-Windows10_MSVC2013-Debug-64bits.gz:   ERROR:    execution   of link_to_CGAL_ImageIO
Installation/TestReport_afabri_x64_Cygwin-Windows10_MSVC2013-Release-64bits.gz:   ERROR:    execution   of link_to_CGAL_ImageIO
Installation/TestReport_afabri_x64_Cygwin-Windows10_MSVC2015-Debug-64bits.gz:   ERROR:    execution   of link_to_CGAL_ImageIO
Installation/TestReport_afabri_x64_Cygwin-Windows10_MSVC2017-Debug-64bits.gz:   ERROR:    execution   of link_to_CGAL_ImageIO
```

On Gauguin, ZLIB seems to be correctly found at the compilation (headers) and link time (`.lib` files), but not at runtime: the directory containing the `.dll` should be in the `PATH`.

There is also a shell error in the logs:
```
/cygdrive/c/CGAL/reference_platforms/setup_common: line 64: C:/3rdPartyLibs/zlib-1.2.11/build_msvc2013: Is a directory
```

**Comment by janetournois** [comment]
Since I'm the one who changed that, I'm taking care of it. Thank you for the report

**Comment by janetournois** [comment]
it should be fixed now
