### ISSUE TITLE
to_double(Lazy_alpha_nt_3) relative precision

### ISSUE THREAD

**Issue by mglisse** [CGAL/cgal#3153]
`to_double(Lazy_exact_nt)` has a mechanism with `get_relative_precision_of_to_double`, etc so that it only uses to_double on the interval if the precision is good enough. Otherwise it computes the exact value and converts that one to double. `to_double(Lazy_alpha_nt_3)` seems to be missing a similar scheme and returns the middle of the interval, even if the interval is [-inf,+inf].

As a workaround, it is possible for users to do it themselves, calling `a.approx()`, computing the relative precision, etc. But this all seems undocumented.

**Comment by mglisse** [comment]
While I am looking at this, what would you think of having `to_double(Interval_nt)` throw an exception when the relative precision is not good enough? I think I'll need something like that for Epack_d ('a' for approximate, with filtered constructions), although of course I can always create and specialize my own version of NT_converter.

**Comment by sloriot** [comment]
Having it for the general `to_double` does not seem good IMO. I would use another function name if you want to make it throw. On the other hand at least the issue wouldn't be silent and if we really want to have the middle an interval we should use a dedicated function.

**Comment by mglisse** [comment]
> Having it for the general to_double does not seem good IMO.

What about the general NT_converter? Otherwise I'll just create NT_converter2 that does what I want :wink: 
(that's all independent of the alpha-shape case)
