### ISSUE TITLE
Polyhedron_3 to  Nef_polyhedron_3 failed

### ISSUE THREAD

**Issue by xichuangtech** [CGAL/cgal#3155]
## Issue Details

I have an off file.When trying to construct Nef_Polyhedron from Polyhedron I get the error.

![20180606180231](https://user-images.githubusercontent.com/17584452/41031622-aa3b37e0-69b3-11e8-865b-f274f9388111.png)

[test.zip](https://github.com/CGAL/cgal/files/2075635/test.zip)

and when I  clip the Polyhedra,the application get an crash.
![65grf1btbz xw aov6z _ h](https://user-images.githubusercontent.com/17584452/41031799-380a2612-69b4-11e8-978c-719bc0fd4a14.png)

## Environment

Operating system (Windows/Mac/Linux, 32/64 bits): Windows 10 64
Compiler: MSVC 2017
Release or debug mode: debug
Specific flags used (if any):
CGAL version: 4.11
Boost version: 1.66
Other libraries versions if used (Eigen, etc.):

**Comment by lrineau** [comment]
Did you close the issue intentionally? Have you found out why that crashed?
