### ISSUE TITLE
Change name of Surface_reconstruction_points_3, and URLs redirections

### ISSUE THREAD

**Issue by sgiraudot** [CGAL/cgal#316]
The package _Surface Reconstruction from Point Sets_ should be renamed _Poisson Surface Reconstruction_. It used to be the only reconstruction method in CGAL so the name made sense at that time. But with the addition of the other reconstruction packages, the list of packages becomes confusing:

- Surface Reconstruction from Point Sets
- Scale-Space Surface Reconstruction
- Advancing Front Surface Reconstruction

For consistency, I think this would be better:

- Poisson Surface Reconstruction
- Scale-Space Surface Reconstruction
- Advancing Front Surface Reconstruction

In addition, now that there are several reconstruction methods available, wouldn't it be a good idea to move them to a specific _Surface Reconstruction_ category? Currently, they are in _Mesh Generation_, but reconstruction is a slightly different topic (for example, Poisson reconstruction does not generate any mesh but only an implicit function - that can be meshed by the CGAL mesher of course).

**Comment by sloriot** [comment]
The renaming is a good idea as well as the new category

**Comment by sloriot** [comment]
If we change the name of the directory in the repo, we should add a rewrite rule for the doc website so that queries for the old url format are not lost

**Comment by sloriot** [comment]
The file to update is `.htaccess` in the cgal-web repo (jekyll branch)

**Comment by lrineau** [comment]
I think that the redirection will apply to the URLs http://doc.cgal.org/latest/Surface_reconstruction_points_3/ and similar. The `.htaccess` that does the redirections for that web site is not the same as `.htaccess` in the `jekyll` branch of [`CGAL/cgal-web`](https://github.com/CGAL/cgal-web/). As far as I know, the `.htaccess` of http://doc.cgal.org/ is not managed using Git.

**Comment by lrineau** [comment]
Now that the PR #319 is merged, that leaves us with the question of the redirections. Should we let that bug open until we fix also the redirections?

**Comment by sloriot** [comment]
I think so. The redirection should be here only when latest will point onto 4.8

**Comment by lrineau** [comment]
Even before that, we can test the redirections as soon as the documentation for 4.8 is published at http://doc.cgal.org/4.8/. Once `4.8/` becomes `latest/`, it is just a matter of changing `s/4.8/latest/` in the regular expression.

**Comment by sloriot** [comment]
I created #752 specifically
