### ISSUE TITLE
casting Eigen types to CGAL types and vice versa (question)

### ISSUE THREAD

**Issue by TheodoreT** [CGAL/cgal#3161]
Hi to all, I am trying to understand how to cast an Eigen type matrix with points to CGAL type variables. For example let's say that I have some points that form a cube and are stored in an Eigen::MatrixXd container, for example:

```
  // Inline mesh of a cube
  const Eigen::MatrixXd cubeV= (Eigen::MatrixXd(8,3)<<
  0.0,0.0,0.0,
  0.0,0.0,1.0,
  0.0,1.0,0.0,
  0.0,1.0,1.0,
  1.0,0.0,0.0,
  1.0,0.0,1.0,
  1.0,1.0,0.0,
  1.0,1.0,1.0).finished();
```
Now I would like to process these points in the cgal library in order to apply some processing, for example [mesh reconstruction](https://doc.cgal.org/latest/Poisson_surface_reconstruction_3/index.html). 
However you can see that the input points to the cgal functions are of the form:

`std::vector<Pwn> points;`

where `Pwn` corresponds to:

```
// Types
typedef CGAL::Exact_predicates_inexact_constructions_kernel Kernel;
typedef Kernel::Point_3 Point;
typedef Kernel::Vector_3 Vector;
typedef std::pair<Point, Vector> Pwn;
```
or in the second example of the form:

`PointList points`;

where again `PointList` corresponds to:

```
// Types
typedef CGAL::Exact_predicates_inexact_constructions_kernel Kernel;
typedef Kernel::Point_3 Point;
typedef CGAL::Point_with_normal_3<Kernel> Point_with_normal;
typedef std::vector<Point_with_normal> PointList;
// or it can also be
// typedef std::vector<Point> PointList; // so I do not consider the normals
```
Thus, I wanted to ask how I can cast my `Eigen::MatrixXd` matrix to `Pwn` or `PointList` types so that I can use them with the cgal functions like in the example. I am not that experienced with both Eigen and CGAL libraries, I tried to use some naive `for` loop and `push_back` solution but without success.

**Comment by afabri** [comment]
Hello,
Copying is straightforward, and a reinterpret cast probably needs `Eigen::RowMajor` layout. For both see this [example](https://gist.github.com/afabri/4ac12bdc89fead1f009fe878c3b2e0f0).
Maybe the page [Eigen: Reshape and Slicing](https://eigen.tuxfamily.org/dox/group__TutorialReshapeSlicing.html) helps, and maybe the Eigen mailing list or @eigenteam can help.

**Comment by TheodoreT** [comment]
@afabri many thanks for the examples. I got an understanding now. Actually it was much simpler than I thought, but I guess since my experience is limited I was making things more complex than they were.
