### ISSUE TITLE
CGAL/Piecewise_smooth_surface_mesh_default_edges_criteria_3.h

### ISSUE THREAD

**Issue by bradrothenberg** [CGAL/cgal#317]
Hi,

I am having trouble finding this file:

CGAL/Piecewise_smooth_surface_mesh_default_edges_criteria_3.h

which is the last include in polyhedron_remesher.cpp.

Thanks!

Bradley

**Comment by sloriot** [comment]
The example you mention is not in the official CGAL release. For historical reasons we have files in a repo that do not target the release that are in a [`dont_submit`](https://github.com/CGAL/cgal/blob/master/Surface_mesher/dont_submit) per package. The example is outdated. I suggest to have a look at the Polyhedron [plugin](https://github.com/CGAL/cgal/blob/master/Polyhedron/demo/Polyhedron/Polyhedron_demo_remeshing_plugin_cgal_code.cpp)  that has the polyhedron remeshing capability.
