### ISSUE TITLE
CGAL demo: Segfault on selection.txt loading (Polyhedron_3)

### ISSUE THREAD

**Issue by MaelRL** [CGAL/cgal#3174]
## Issue Details

Loading [this .OFF](https://gist.github.com/MaelRL/90282691493cc8c8784f5e6504317fec) with [this .selection.txt](https://gist.github.com/MaelRL/1dde89e2b0c26a3086dac7bc156b7e3b) crashes the demo when using default loading plugins.

Works fine when selecting surface mesh for both.

## Environment

Release / master branch

**Comment by maxGimeno** [comment]
I can't reproduce. What are the default plugins ? 
#3144 will probably fix this problem anyway.

**Comment by maxGimeno** [comment]
@MaelRL is this issue still there ?

**Comment by MaelRL** [comment]
It seems to work juts fine after recompiling (which I thought I had done before opening this...). Sorry for the false alarm!
