### ISSUE TITLE
Re-inserting point in a Periodic_3_regular_triangulation

### ISSUE THREAD

**Issue by DahnJ** [CGAL/cgal#3175]
## Issue Details

Inserting and removing the same point to the triangulation produces the error
`terminate called after throwing an instance of 'CGAL::Assertion_exception'
  what():  CGAL ERROR: assertion violation!
Expr: cells_with_too_big_orthoball.empty()
File: /usr/local/include/CGAL/Periodic_3_regular_triangulation_3.h
Line: 329
Aborted (core dumped)
`
Edit: The problem seems to happen when I remove all points from a periodic triangulation and then add *any* point. 

## Source Code

``` c++
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/Periodic_3_regular_triangulation_traits_3.h>
#include <CGAL/Periodic_3_regular_triangulation_3.h>

typedef CGAL::Exact_predicates_inexact_constructions_kernel K;
typedef CGAL::Periodic_3_regular_triangulation_traits_3<K>       Gt;
typedef CGAL::Periodic_3_regular_triangulation_3<Gt>             P3RT3;

int main()
{
  
  P3RT3 PT;

  P3RT3::Weighted_point wp (P3RT3::Bare_point(0.5,0.5,0.5),0.01);
   
  P3RT3::Vertex_handle v = PT.insert(wp);
  PT.remove(v);
  PT.insert(wp);
}
``` 
## Environment

* Operating system: Linux Mint 18.03
* Compiler: g++
* CGAL version: 4.12

**Comment by MaelRL** [comment]
Hello,

Thanks for the report. This is a known bug in the class `Periodic_3_regular_triangulation_3.h`: it is missing a virtual function to override the method `clear_covering_data()` of its base class (`Periodic_3_triangulation_3`).

There is a fix ready in the pull request #2658, which will be published in CGAL 4.13. Until then, you can easily patch the issue by adding the following lines in the class `Periodic_3_regular_triangulation_3.h`:

```
virtual void clear_covering_data()
{
  cells_with_too_big_orthoball.clear();
}
```
