### ISSUE TITLE
nearest_power_vertex() documentation states Weighted_point instead of Point

### ISSUE THREAD

**Issue by DahnJ** [CGAL/cgal#3178]
## Issue Details

I believe the documentation for [nearest_power_vertex()](https://doc.cgal.org/latest/Triangulation_3/classCGAL_1_1Regular__triangulation__3.html#aa21a64cca26abd84e7a1ce0e1ea753e4) is wrong, as it takes Point for argument and not Weighted_point. The code below produces the following error:
`
nearest_vertex_bug.cpp: In function ‘int main()’:
nearest_vertex_bug.cpp:18:58: error: no matching function for call to ‘CGAL::Regular_triangulation_3<CGAL::Epick>::nearest_power_vertex(Weighted_point)’
   T.nearest_power_vertex(Weighted_point(Point(0,0,0),0.1));
`

## Source Code

``` c++
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/Regular_triangulation_3.h>
typedef CGAL::Exact_predicates_inexact_constructions_kernel K;
typedef K::FT                                          Weight;
typedef K::Point_3                                     Point;
typedef K::Weighted_point_3                            Weighted_point;
typedef CGAL::Regular_triangulation_3<K>               Rt;

int main(){
  Rt T;
  T.nearest_power_vertex(Point(0,0,0));
  T.nearest_power_vertex(Weighted_point(Point(0,0,0),0.1));

  return 0;
}

```

## Environment

* Operating system: Linux Mint 18.03
* Compiler: g++
* CGAL version: 4.12

**Comment by MaelRL** [comment]
It's indeed supposed to be a bare point, thanks. It'll be fixed in #3179.
