### ISSUE TITLE
Invalid pixel values in volume plane picking

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#3181]
Using for example the attached file having segments  in [1, 2, 3] if I'm doing some picking after having creating the volumes planes, the only values for the pixel I have is 3 and 1.

[sphere.inr.gz](https://github.com/CGAL/cgal/files/2118340/sphere.inr.gz)

**Comment by maxGimeno** [comment]
From what I see in the debugger, it is the intConverter that doesn't work corectly IMHO: it gives 0 for 0.99, I guess we should take 1 instead.
