### ISSUE TITLE
File I/O buggy for larger triangulations

### ISSUE THREAD

**Issue by DahnJ** [CGAL/cgal#3184]
## Issue Details

I tried saving a tessellation generated by `CGAL::points_on_cube_grid_3` to a file and loading it from it again. Result varied with different number of points:

```
number_of_points = 100
T.is_valid(): 1
T == Tin: 1
Tin.is_valid(): 1
```

```
number_of_points = 1000
T.is_valid(): 1
T == Tin: 0
Tin.is_valid(): 1
``` 

``` 
number_of_points = 10000
T.is_valid(): 1
T == Tin: 0
terminate called after throwing an instance of 'CGAL::Assertion_exception'
  what():  CGAL ERROR: assertion violation!
Expr: false
File: /usr/local/include/CGAL/Regular_triangulation_3.h
Line: 2514
Aborted (core dumped)
``` 

## Source Code

``` c++
#include <iostream>
#include <fstream>
#include <vector>
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/Regular_triangulation_3.h>
#include <CGAL/point_generators_3.h>

typedef CGAL::Exact_predicates_inexact_constructions_kernel K;
typedef K::FT                                          Weight;
typedef K::Point_3                                     Point;
typedef K::Weighted_point_3                            Weighted_point;
typedef K::Vector_3				       Vector;
typedef CGAL::Regular_triangulation_3<K>               Rt;
typedef CGAL::Creator_uniform_3<double, Point> 	       Creator;

int main()
{
  Rt T;

  int number_of_points = 1000;
  std::vector<Point> points;
  std::vector<Weighted_point> weighted_points;
  points.reserve(number_of_points);
  
  CGAL::points_on_cube_grid_3( 1, number_of_points, std::back_inserter(points), Creator() );
  for (Point& p: points){
    Weight w = 0.005;
    weighted_points.push_back(Weighted_point(p,w));
  }
  
  T.insert(weighted_points.begin(), weighted_points.end());

  std::cout << "T.is_valid(): " <<  T.is_valid() << std::endl;
  std::ofstream fout("tess.txt");
  fout << T;

  Rt Tin;	
  std::ifstream fin("tess.txt");
  fin >> Tin;


  std::cout << "T == Tin: " << (T == Tin) << std::endl;
  std::cout << "Tin.is_valid(): " << Tin.is_valid() << std::endl;

 return 0;
}
```

## Environment

* Operating system: Linux Mint 18.03 
* Compiler: g++
* CGAL version: 4.12

**Comment by lrineau** [comment]
Input/ouputs of floating point numbers rounds the numbers, and the triangulation can be turned in a geometrically wrong triangulation after a save and a load from a file in ASCII.

Add `fout.precision(17);` before `fout << T;`. That makes the output of `double` be exact, in the sense that the loading of that number in memory, from the file, will produce the exact same number.

**Comment by lrineau** [comment]
An alternative is the use of binary input/output:
```c++
  std::ofstream fout("tess.txt", std::ios::binary);
  CGAL::set_binary_mode(fout);
  // [...]

  std::ifstream fin("tess.txt", std::ios::binary);
  CGAL::set_binary_mode(fint);
  // [...]
```

**Comment by afabri** [comment]
An alternative would also be that we change it to 17 and later back to the previous precision.

**Comment by DahnJ** [comment]
@lrineau thanks, setting the precision to 17 works for me. However, changing to binary produces output
```
T.is_valid(): 1
terminate called after throwing an instance of 'CGAL::Precondition_exception'
  what():  CGAL ERROR: precondition violation!
Expr: this != &*n
File: /usr/local/include/CGAL/Triangulation_ds_cell_base_3.h
Line: 167
Aborted (core dumped)
```
I am fine with using ascii, so I'm just reporting the error.

**Comment by lrineau** [comment]
[**@afabri**](https://github.com/afabri) commented on [Jun 21, 2018, 9:51 AM GMT+2](https://github.com/CGAL/cgal/issues/3184#issuecomment-399009534 "2018-06-21T07:51:19Z - Replied by Github Reply Comments"):
> An alternative would also be that we change it to 17 and later back to the previous precision.

I agree. For which data structure I/O should we do it? Only the 2D/3D triangulations?

@CGAL/developers  Do you see other CGAL data structures that are so sensible to floating-points rounding precision during I/O?

**Comment by maxGimeno** [comment]
I think it is not acceptable to load a different data structure from the one that was saved, error or not, so I'd say every data structure.

**Comment by afabri** [comment]
I am not sure if this is relevant, but for example for LAS data  I was told by an expert that he considers it as complete nonsense to write data with full precision if one knows the precision of measuring tools, so we might just document in the `operator<<()` that the user should think about the precision.
