### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by J-W-Schuetz** [CGAL/cgal#3185]
_Please use the following template to help us solving your issue._

## Issue Details

In documentation to "3D Mesh Generation" there is a function "facets_in_complex_3_to_triangle_mesh()" documented, which is not available.

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Debian
* Compiler:
* Release or debug mode:
* Specific flags used (if any):
* CGAL version: 4.12
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by sloriot** [comment]
I can see:
```
CGAL-4.12/include/CGAL/IO/facets_in_complex_3_to_triangle_mesh.h
48:void facets_in_complex_3_to_triangle_mesh(const C3T3& c3t3, TriangleMesh& graph) 
```
and the doc indicates that include file too.
