### ISSUE TITLE
How to work with hidden points in Regular_triangulation_3?

### ISSUE THREAD

**Issue by DahnJ** [CGAL/cgal#3186]
I am having trouble dealing with the hidden points in a regular triangulation. I am essentially attempting to use the triangulation as if the hidden points feature did not exist, i.e. hidden vertex is simply deleted. This leads me to a couple of questions.

1. Is there a way to (permanently) delete a hidden vertex? 

2. Is there something like `number_of_hidden_points()` as there [seems to be](https://doc.cgal.org/latest/Periodic_3_triangulation_3/index.html#title25) in periodic triangulations? If not, is iterating over cells and counting their hidden points a valid method? (i.e. is each hidden point always stored in only one cell?)

3.  Similarly to 2., how to traverse all hidden points (each once) - through iterating over all the cells?

Finally, I want to ask if it's okay to ask questions like this one on Github, i.e. not reporting a possible bug, merely asking about something that doesn't appear to be documented. Thank you.

**Comment by lrineau** [comment]
If you use `Triangulation_cell_base_3` instead of `Regular_triangulation_cell_base_3`, then the hidden points are not store, and will be never be restored.

**Comment by MaelRL** [comment]
First of all, note that when a vertex gets hidden, only the point (geometric location) is kept in memory in a cell. It's no longer a vertex of the triangulation in the sense that it'll not show up when you traverse vertices or be counted in `tr.number_of_vertices()`. About your questions:

1. You can't use `Triangulation_cell_base_3` for a `Regular_triangulation_3`, it needs a cell base with a weighted point and so it requires a class like `Regular_triangulation_cell_base_3`. The class `Regular_triangulation_cell_base_3` has a non documented template parameter, `Memory_policy` which is just a tag to say whether you keep or discard hidden points (see the file [here](https://github.com/CGAL/cgal/blob/master/STL_Extension/include/CGAL/Hidden_point_memory_policy.h)). So if you declare your regular triangulation as:
```
  typedef Regular_triangulation_vertex_base_3<Gt>        Vb;
  typedef Regular_triangulation_cell_base_3<
            Gt, Cbb, Discard_hidden_points>               Cb;
  typedef Triangulation_data_structure_3<Vb, Cb>          Tds;
  typedef Regular_triangulation_3<Gt,Tds>                 Triangulation;
```
then you'll discard hidden points.

2. If you look at the code of `number_of_hidden_points()` for the periodic triangulations, it's just traversing through the cells of the triangulation and counting the hidden points per cell. There is no such function for non-periodic triangulations but you can easily write the same function.

3. See above.

If something is not clear for you then usually that means it wasn't properly documented or it is a feature request. Both of them can be reported here without any problem.

**Comment by DahnJ** [comment]
@MaelRL thanks, that looks great. What is Cbb in ` typedef Regular_triangulation_cell_base_3<Gt, Cbb, Discard_hidden_points>               Cb;` though?

**Comment by MaelRL** [comment]
> The section "performance" still document that Triangulation_cell_base_3 is a way to avoid storing the hidden points.

The line slipped through #2102 and its small feature.

It is changed in #2658 (https://cgal.geometryfactory.com/~mrouxell/P3M3_doc_final/doc_output/Triangulation_3/#title27), although I see that I need to truncate that new line because this template parameter was not documented in #2658. I was probably debating whether to add it or not, and did not in the end.

Should probably be added in the future.

**Comment by MaelRL** [comment]
> @MaelRL thanks, that looks great. What is Cbb in typedef Regular_triangulation_cell_base_3<Gt, Cbb, Discard_hidden_points> Cb; though?

Sorry, `Cbb` is just defined as
```
typedef Triangulation_cell_base_3<Gt>                   Cbb;
```
I only extracted (a bit too quickly) code from some code in CGAL (you can find usages of the `Discard_hidden_points` in a couple of places by searching in the source).

**Comment by DahnJ** [comment]
@MaelRL thanks, would this then be a correct standalone example?
``` c++
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/Regular_triangulation_3.h>
#include <CGAL/tags.h>

typedef CGAL::Exact_predicates_inexact_constructions_kernel Gt;
typedef CGAL::Triangulation_cell_base_3<Gt>   Cbb;
typedef CGAL::Regular_triangulation_vertex_base_3<Gt>         Vb;
typedef CGAL::Regular_triangulation_cell_base_3<
           Gt, Cbb, CGAL::Discard_hidden_points>               Cb;
typedef CGAL::Triangulation_data_structure_3<Vb, Cb>          Tds;
typedef CGAL::Regular_triangulation_3<Gt,Tds>                 Rt;

int main()
{
  Rt T;
  return 0;
}
```
