### ISSUE TITLE
write_off on non-garbage collected Surface_mesh objects

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#3189]
`write_off()` is using `num_vertices()` and `num_faces()` which leads to errors if the surface mesh contains garbage.

**Comment by afabri** [comment]
Note that the same mistake (to forget that `std::distance()` applied on a random access iterator is just the pointer difference), is made  for [`exact_num_vertices()`](https://github.com/CGAL/cgal/blob/master/BGL/include/CGAL/boost/graph/internal/helpers.h#L138)

**Comment by maxGimeno** [comment]
Yes it does : 
> reindex.resize(sm.num_vertices());

**Comment by maxGimeno** [comment]
And it appears that std::distance(vertices(sm).begin, vertices(sm).end()) returns the right number. Are we sure that vertices() is a Random Acces Range in Surface_mesh ?

**Comment by MaelRL** [comment]
Index iterators of the surface mesh are only bidirectional, not random-access. Thus the `Vertex_range` is a also bidirectional range, not a random access range (cf https://doc.cgal.org/latest/Surface_mesh/classCGAL_1_1Surface__mesh.html#a81371c8abd2daaf53bb457945a3a7d15). So `std::distance(vertices(sm).begin, vertices(sm).end())` will return the correct number of non-deleted elements because deleted elements are skipped while iterating.

**Comment by maxGimeno** [comment]
Ah ! Thank's @MaelRL !

**Comment by lrineau** [comment]
[**@MaelRL**](https://github.com/MaelRL) commented on [Jun 26, 2018, 10:50 AM GMT+2](https://github.com/CGAL/cgal/issues/3189#issuecomment-400231792 "2018-06-26T08:50:15Z - Replied by Github Reply Comments"):
> Index iterators of the surface mesh are only bidirectional, not random-access. Thus the `Vertex_range` is also a bidirectional range, not a random access range (cf https://doc.cgal.org/latest/Surface_mesh/classCGAL_1_1Surface__mesh.html#a81371c8abd2daaf53bb457945a3a7d15). So `std::distance(vertices(sm).begin, vertices(sm).end())` will return the correct number of non-deleted elements because deleted elements are skipped while iterating.

Indeed, there are, in `master`::
https://github.com/CGAL/cgal/blob/5ceb529d0f5103557ce1d17b0bf2b3a302590f90/Surface_mesh/include/CGAL/Surface_mesh/Surface_mesh.h#L460-L467

But that is about to change, in https://github.com/CGAL/cgal/pull/3126/commits/eba8e449b2d6500964a0fe554b5bba24f2132d43 (from @sgiraudot 's PR #3126): the patch from Simon makes the iterator random access (at least declared as such), but when the `Surface_mesh` has garbage, the distance function will not be in constant time, but in linear time (see the patch in eba8e449b2d6500964a0fe554b5bba24f2132d43).

**Comment by maxGimeno** [comment]
That put aside, I see absolutely no problem with write_off() in Surface_mesh. It uses num_vertices() correctly, and when I write a sm with garbage, it does it correctly. I'll need a little more information on what is wrong here.

**Comment by maxGimeno** [comment]
So what do we do with this issue ?

**Comment by sloriot** [comment]
Fixed by #3190
