### ISSUE TITLE
2D arrangements overlapping lines (question)

### ISSUE THREAD

**Issue by psarahdactyl** [CGAL/cgal#3191]
## Issue Details

I have a question about 2D arrangements. I am trying to insert segments that overlap each other completely. I can have a long line with a shorter line on top of it, contained in its range. Or I can have two lines the exact same length in the exact same position. The problem occurs when the lines are completely vertical or horizontal. 

I sometimes get an assertion inside the bezier_x_monotone_2.h on line 1942. Then I am unable to make an arrangement out of it. Or sometimes it will make an arrangement -- although it says I have 8 curves, each inducing 1 edge, I'll get an arrangement with 7 edges. So one edge is deleted somehow.

Is this expected behavior?

## Environment

* Operating system (Windows 10 64 bits):
* Compiler: Visual Studio 2017
* Release or debug mode: debug
* CGAL version: 4.12

**Comment by sloriot** [comment]
It might be a bug, please try to come up with a minimal example showing the issue.

**Comment by efifogel** [comment]
Hi Sarah,

What you describe seems like a bug.
If it is indeed a bug, it is most likely to be in the Bezier traits.
It will be extremely useful if you can send to us a small test case that
causes the problem (a minimal set of Bezier curves).

PS, I've noticed that you made a small contribution. Thank you!
Just for my curiosity and if the information is not confidential, what is
the project you are working on? Are you at the industry or academia?
Feel free to send a private email message to efifogel@gmail.com.

Best,
Efi

   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by psarahdactyl** [comment]
Hi Sebastien and Efi,

I have come up with some files (in the format of [Bezier.dat](https://github.com/CGAL/cgal/blob/master/Arrangement_on_surface_2/examples/Arrangement_on_surface_2/Bezier.dat)) that reproduce the bug such that I can't make an arrangement out of the given points: 
* [lines.txt](https://github.com/CGAL/cgal/files/2220932/lines.txt)
* [rectangles.txt](https://github.com/CGAL/cgal/files/2220933/rectangles.txt)

I run the CGAL example Arrangement_on_surface_2/Bezier_curves.cpp with these files as the command-line arguments, and I get assertion errors in the file [Arr_geometry_traits/Bezier_x_monotone_2.h](https://github.com/CGAL/cgal/blob/master/Arrangement_on_surface_2/include/CGAL/Arr_geometry_traits/Bezier_x_monotone_2.h) on lines 1385 and 2598, respectively.

Also, on the following example I have:
* [exact-overlap.txt](https://github.com/CGAL/cgal/files/2220985/exact-overlap.txt)

I get different results depending on whether I use `insert(arr, curves.begin(), curves.end())` versus 
```
for(int i = 0; i < curves.size(); i++) 
{
    insert(arr, curves[i]);
}
```
Should there be a difference between these insertion methods?

I am a PhD student at the University of Toronto and I am trying to make a "what you see is what you cut" interface for laser cutters. I am using the arrangements to take users' designs and give back only the visible strokes.

Thanks,
Sarah

**Comment by efifogel** [comment]
On 23 July 2018 at 23:53, Sarah Kushner <notifications@github.com> wrote:

> Hi Sebastien and Efi,
>
> I have come up with some files (in the format of Bezier.dat
> <https://github.com/CGAL/cgal/blob/master/Arrangement_on_surface_2/examples/Arrangement_on_surface_2/Bezier.dat>)
> that reproduce the bug such that I can't make an arrangement out of the
> given points:
>
>    - lines.txt <https://github.com/CGAL/cgal/files/2220932/lines.txt>
>    - rectangles.txt
>    <https://github.com/CGAL/cgal/files/2220933/rectangles.txt>
>
> I run the CGAL example Arrangement_on_surface_2/Bezier_curves.cpp with
> these files as the command-line arguments, and I get assertion errors in
> the file Arr_geometry_traits/Bezier_x_monotone_2.h
> <https://github.com/CGAL/cgal/blob/master/Arrangement_on_surface_2/include/CGAL/Arr_geometry_traits/Bezier_x_monotone_2.h>
> on lines 1385 and 2598, respectively.
>
> Also, on the following example I have:
>
>    - exact-overlap.txt
>    <https://github.com/CGAL/cgal/files/2220985/exact-overlap.txt>
>
> I get different results depending on whether I use insert(arr,
> curves.begin(), curves.end()) versus
>
> for(int i = 0; i < curves.size(); i++)
> {
>     insert(arr, curves[i]);
> }
>
> Should there be a difference between these insertion methods?
>

They should produce equivalent arrangements. (That is, the incidence graphs
of the arrangements are equivalent.)
However, the 2 arrangements can have different representation (order of
faces can be different, etc.).

Thanks for reporting the bug(s) and providing the test cases.
My guess is that the bug(s) are in the code of the Bezier traits (and not
in the general code).
The first step in fixing the bug is isolating the erroneous traits
function. One way of doing it is warping the Bezier traits with the tracing
traits (the way done in the tracing_counting.cpp example).

If you want to help, have the time, and would like to expedite the
debugging process... please run the example extended with the tracing
traits. Then, go over each invocation of a traits function and look for the
one with the wrong result.

**Comment by efifogel** [comment]
Hi Sara,

In our lab at TAU, we maintain a page dedicated to projects that use code
developed at TAU; see http://acg.cs.tau.ac.il/projects. (last table is for
external projects.)
If you would like us to add an entry and corresponding page, please send an
email to efifogel@gmail.com and I'll tell you what we need to establish the
entry.

Best,
Efi

   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by efifogel** [comment]
I'm not I completely understand (what is a curve index?)
Notice that the observer reacts based on changes made to the topological
features, that is, vertex, halfedge, and face.
The point and curve are the geometric embeddings of the vertex and
halfedge.
The face feature does not have a geometric embedding in the code, but you
could think of a polygon as one.

   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/
