### ISSUE TITLE
Convex_hull_3 is not minimal

### ISSUE THREAD

**Issue by maxGimeno** [CGAL/cgal#3192]
## Issue Details

The function CGAL::convex_hull_3(InputIterator first, InputIterator beyond, Polyhedron_3& polyhedron,  const Traits& traits) does not create a minimal convex_hull, in the sense that some points are not extreme. 
## Source Code
call it on the cross.off, the result contains 20 vertices, where only 16 are expected.
## Environment

* CGAL version: ALL OF THEM

**Comment by lrineau** [comment]
[**@maxGimeno**](https://github.com/maxGimeno) commented on [Jun 27, 2018, 9:04 AM GMT+2](https://github.com/CGAL/cgal/issues/3192#issue-336101436 "2018-06-27T07:04:12Z - Replied by Github Reply Comments"):
> * CGAL version: master

The bug is probably also present in released version of CGAL.
