### ISSUE TITLE
Display bugs with polylines item

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#3200]
## Issue Details

I have created the file [cross (selection)-edges.polylines.txt](https://github.com/CGAL/cgal/files/2159194/cross.selection.-edges.polylines.txt) by loading the `cross.off`, then selection, sharp edges, and then save the selection as a polylines item.

If one loads that file with the polyhedron demo, I have strange display issues:

1. The item is displayed, whatever is its status (view/hide) in the
   scene. See the screenshot.
   ![screenshot_20180703_141231](https://user-images.githubusercontent.com/5746675/42219146-5d7a59b0-7eba-11e8-8530-7ff1e8cc0afa.png)

2. The display of corner balls (when activated) is wrong: they are white.
    ![screenshot_20180703_141500](https://user-images.githubusercontent.com/5746675/42219218-b67ad2b0-7eba-11e8-8479-5e22e12bf1f6.png)

I have cleaned by build directory. The only plugins are:
```
Plugins/IO/liboff_plugin.so 
Plugins/IO/libpolylines_io_plugin.so 
Plugins/IO/libstl_plugin.so 
Plugins/IO/libsurface_mesh_io_plugin.so 
Plugins/PMP/liborient_soup_plugin.so 
Plugins/PMP/libselection_plugin.so 
Plugins/PMP/libselection_sm_plugin.so
```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Linux Fedora 27
* Compiler: gcc 7.3.1
* Release or debug mode: Release, with debug info
* Specific flags used (if any): flags `-Og -g`, with assertions
* CGAL version: `master` 2d9000efded57d8e41e2cde175310c4a2eaf81b1
* Boost version: 1.64.0

@maxGimeno You can add this to the top-priority bugs: we need that demo working for Siggraph.

**Comment by maxGimeno** [comment]
#3198  fixes it.

**Comment by lrineau** [comment]
[**@maxGimeno**](https://github.com/maxGimeno) commented on [Jul 3, 2018, 4:03 PM GMT+2](https://github.com/CGAL/cgal/issues/3200#issuecomment-402168666 "2018-07-03T14:03:26Z - Replied by Github Reply Comments"):
> #3198  fixes it.

Partially: the colors of the corner balls are fixed, but the drawing of the polylines cannot be hidden. And I also can see the drawing of the *points* of the polylines. Both visibility and rendering mode of the item are ignored.
