### ISSUE TITLE
Polyhedron demo: `std::bad_alloc` when loading Surface Mesh

### ISSUE THREAD

**Issue by sgiraudot** [CGAL/cgal#3202]
## Issue Details

When loading the following one-facet OFF file:
```
OFF
5 1 0
-219.189358781456065 163.382991740848979 37.9785643023864168
-206.982635130200748 132.554175983545463 37.9785643023864168
-247.535946042803033 98.8178673201488209 37.9785643023864168
-248.009216608833725 99.386770355796898 37.9785643023864168
-267.685527043317165 123.039018224108759 37.9785643023864168
5 0 1 2 3 4
```

The program runs for a while and then returns a `std::bad_alloc`. This happens with `surface_mesh_io_plugin`, _not_ with `off_plugin` which loads the facet fine (so it's specific to the surface mesh item, not the polyhedron one).

From what I understand, the program goes to an infinite loop in the method `triangulate_convex_facet()` of the surface mesh item. Using `triangulate_facet()` instead works, but as @maxGimeno pointed out to me, the method is then suboptimal.

Note that the bug-generating facet seems to have a three aligned vertices, so it's exactly on the limit of being non-convex (don't know if this could be a trigger of this error).

(@janetournois maybe you can also help on this issue?)

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Debian 64 bits
* Compiler: clang
* Release or debug mode: Release
* CGAL version: master

**Comment by maxGimeno** [comment]
It is trivial, there is a basic error in the while loop. prev(he) should be prev(he_end). I'll PR a fix.
