### ISSUE TITLE
Polyhedron demo: various problems with POLYHEDRON_DEMO_PLUGINS_PATH

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#3204]
There are several problems, when a plugin is loaded from a directory specified by the environment variable `POLYHEDRON_DEMO_PLUGINS_PATH`.

1. We assume that the value of `POLYHEDRON_DEMO_PLUGINS_PATH` is a string, that encodes a list, with `:` as the separator character. On Windows that is obviously wrong, because all paths start with `C:/` or something similar. We need to use [`QDir::listSeparator()`] instead of hard-coding `:`...
  > [static] QChar QDir::listSeparator()
  > 
  > Returns the native path list separator: ':' under Unix and ';' under Windows.
  > 
  > This function was introduced in Qt 5.6.
  
  That is only since Qt 5.6, so we will have to use preprocessor conditionals to continue hardcoding `:`  for Qt<5.6.

2. When an external plugin (in an external directory) has a shared library as a dependency (a `.dll` or a `.so` file), then that dependency is not found by the dynamic loader, and the plugin does not load.

[`QDir::listSeparator()`]: http://doc.qt.io/qt-5/qdir.html#listSeparator

**Comment by afabri** [comment]
I suggest to require Qt 5.6 or not to offer plugins residing elsewhere.

**Comment by lrineau** [comment]
[**@afabri**](https://github.com/afabri) commented on [Jul 5, 2018, 12:06 PM GMT+2](https://github.com/CGAL/cgal/issues/3204#issuecomment-402673457 "2018-07-05T10:06:44Z - Replied by Github Reply Comments"):
> I suggest to require Qt 5.6 or not to offer plugins residing elsewhere.

That would require two uses of processor conditionals instead of just one. That is simpler the way I wrote it.

**Comment by maxGimeno** [comment]
> 2. When an external plugin (in an external directory) has a shared library as a dependency (a .dll or a .so file), then that dependency is not found by the dynamic loader, and the plugin does not load.
When I create an external plugin depending on a custom item, and get it in the demo by POLYHEDRON_DEMO_PLUGINS_PATH, the plugin loads and it work. Are you sure the problem exists with .so ?
I get an error in the Preferences saying it cannot find meta data for the item though, but I think it is because it tries to load it as a plugin.

**Comment by maxGimeno** [comment]
> I suggest to require Qt 5.6 or not to offer plugins residing elsewhere.

I even suggest we document that the demo requires Qt 5.9, at least for OSX (for the buggy internal shaders seen in  #3198 ).

**Comment by lrineau** [comment]
[**@maxGimeno**](https://github.com/maxGimeno) commented on [Jul 10, 2018, 9:29 AM GMT+2](https://github.com/CGAL/cgal/issues/3204#issuecomment-403728144 "2018-07-10T07:29:49Z - Replied by Github Reply Comments"):
> > I suggest to require Qt 5.6 or not to offer plugins residing elsewhere.
> 
> I even suggest we document that the demo requires Qt 5.9, at least for OSX (for the buggy internal shaders seen in  #3198 ).

Why not. In our platforms testing Qt5, "Debian stable" is the only platform that is stuck with an older version (Qt 5.7).

But Qt 5.9 is rather recent (May 2017). We should only do that if we have a strong motivation, because we certainly have users using an older version of Qt.

For the future, having 5.9 as the minimal version is a good choice, because that version if a LTS version (long time support).

**Comment by lrineau** [comment]
@janetournois @afabri The issues with the use of external plugins (via the environment variable `POLYHEDRON_DEMO_PLUGINS_PATH`) should now be fixed (in `master`).

**Comment by janetournois** [comment]
thank you!
