### ISSUE TITLE
Handling of non-manifold vertices

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#3206]
The way I wrote `copy_face_graph()` and internal functions used in Boolean operations through corefinement implies that if a mesh to be copied features a non-manifold vertex, only one umbrella of faces will have a new vertex created and assigned.

What do we want to do?
- keep the non-manifold vertex
- duplicate the vertex and resolved at the same time the non-manifold situation
- ignore the issue and requires that the mesh does not contain non-manifold vertices

**Comment by MaelRL** [comment]
I would go with the first, as in general I don't feel that it is a good idea to sneak repairing operations within functions that do not explicitly say so.

**Comment by sloriot** [comment]
I opted for a verbatim copy.
