### ISSUE TITLE
Polyhedron demo: Thin quad facets not displayed

### ISSUE THREAD

**Issue by sgiraudot** [CGAL/cgal#3212]
## Issue Details

In a polygon soup with some quad facets, some are not displayed (`Facet not displayed` is outputted on the terminal), see the three white holes on this screenshot:

![missing facets](https://user-images.githubusercontent.com/12890639/42442008-d46feb76-8369-11e8-81f7-9bff6b5beceb.png)

It's because of [this line of code](https://github.com/CGAL/cgal/blob/master/Polyhedron/demo/Polyhedron/triangulate_primitive.h#L124) that triangulates facets with >3 vertices: it ignores vertices if they are closer than a threshold `CGAL::square(0.0001*item_diag)`. I'm sure there is a reason behind this hack, but it really seems like a bad idea (facets _can be_ long and there's no reason not to display them - there's nothing wrong with the three undisplayed facets on my screenshot).

I can fix my case using 0.000001 instead of 0.0001 in the threshold (I tested and it works) but that's just as arbitrary as the original code. What happens if this filtering is not done at all and the facets are _just_ triangulated?

## Environment

* CGAL version: master

**Comment by maxGimeno** [comment]
The triangulation will crash and the demo too, IIRC.

**Comment by lrineau** [comment]
The triangulation should be robust. The issue can be that the normal of the facet is incorrectly constructed.

**Comment by maxGimeno** [comment]
Can't reproduce the old crashing behavior... Did we somehow improve compute_normals() ? Anyway I guess We can safely(ish) remove the distance check in the primitive_triangulation. 
I found out a bug in the read_off() for Surface_mesh though, seems that Euler::add_face() does like [this file](https://github.com/CGAL/cgal/files/766560/x29_plane.zip).
