### ISSUE TITLE
CGAL 4.12 fails to build with /Za flag in Visual Studio

### ISSUE THREAD

**Issue by jjpepper** [CGAL/cgal#3227]
## Issue Details

CGAL 4.12 issues a number of compiler errors when compiling in Microsoft Visual C++ 2017 (Visual Studio 15.7.1) when the [/Za](https://msdn.microsoft.com/en-us/library/0k0w269d.aspx?f=255&MSPPError=-2147217396) flag is used.  This is surprising because Microsoft specifically suggests enabling the flag for cross-platform development:

> https://msdn.microsoft.com/en-us/library/0k0w269d.aspx?f=255&MSPPError=-2147217396

## Errors
Here are the first few errors:
`vcpkg\installed\x64-windows\include\CGAL\Compact_container.h(1099): error C2990: 'CGAL::Compact_container': non-class template has already been declared as a class template`

`vcpkg\installed\x64-windows\include\CGAL\In_place_list.h(76): error C2990: 'CGAL::In_place_list': non-class template has already been declared as a class template`

## Environment

* Operating system (Windows, 64 bits):
* Compiler: Visual C++ 2017 (15.7.1)
* Release or debug mode: Release
* Specific flags used (if any): /Za
* CGAL version: 4.12
* Boost version: 1.67

**Comment by lrineau** [comment]
Visual Studio C++ is wrong on both errors:
```
vcpkg\installed\x64-windows\include\CGAL\Compact_container.h(1099)

vcpkg\installed\x64-windows\include\CGAL\In_place_list.h(76)
```
In both cases, the line is a friend declaration of a full specialization, and [that is perfectly valid](https://en.cppreference.com/w/cpp/language/friend#Template_friends).

CGAL is tested with `/std:c++latest /permissive-`, that [seem to be better options to verify the conformance to the standard](https://blogs.msdn.microsoft.com/vcblog/2016/11/16/permissive-switch/):
> The compiler switch `/Za` was an effort started decades ago to carve out a strictly portable behavior across several C++ compilers. The effort was stalled and we no longer recommend it for new projects.
