### ISSUE TITLE
Aff_transformation_3: Missing doc for Identity

### ISSUE THREAD

**Issue by maxGimeno** [CGAL/cgal#3235]
## Issue Details
The correct syntax for creating an Aff_transformation_3 from the Identity is CGAL::Aff_transformation_3(CGAL::IDENTITY). The problem is that the tag CGAL::IDENTITY is mentioned nowhere in the entire documentation. An example using it in Aff_transformtation_3  would also be nice.

Same for Aff_transformation_2.

**Comment by afabri** [comment]
Is that really a bug?   Can't we write `CGAL::Aff_transformation_3 ide(CGAL::Identity_transformation())`?

**Comment by maxGimeno** [comment]
@afabri is right, it is actually documented with `CGAL::Identity_transformation()`
