### ISSUE TITLE
Future of Surface_mesher

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#3237]
AFAIK, the only place where Surface_mesher is hard-coded is in Poisson surface reconstruction.

What is the plan for the future of `Surface_mesher`?
- remove the package and recommend using Mesh_3
- offer full compatibility: it means having wrapper for oracle + c2t3 working with Mesh_3
- ?

I open the issue to track the topic. The second option looks better from a user point of view.

Related issues:
- license checking of Surface_mesher should be using Mesh_3 in the end
- the macro `BLABLA_DEMO_USING_SURFACE_MESHER` in the demo can be removed
- ?

@lrineau @maxGimeno @MaelRL @janetournois please complete the issue if you see some important points to consider.

**Comment by sloriot** [comment]
@lrineau could you give your point of view on what should be done with the package?

**Comment by lrineau** [comment]
@afabri What do you think we should do?

**Comment by sloriot** [comment]
We should take all Surface_mesher examples and see if we can easily reimplement them using Mesh_3. If that's the case, then we can simply deprecate the Surface_mesher package.

**Comment by sloriot** [comment]
This issues was mentioned today again. We should reimplement the package with Mesh_3.

**Comment by lrineau** [comment]
> This issue was mentioned today again. We should reimplement the package with Mesh_3.

Unless one of us is specifically assigned to that task for a week, I do not think that will even be done.

**Comment by lrineau** [comment]
`Surface_mesher` is now announced as deprecated since CGAL-6.0 (about to be released).
