### ISSUE TITLE
Documentation on using Qt with CGAL

### ISSUE THREAD

**Issue by algo01** [CGAL/cgal#3238]
Hello, I am using CGAL on Fedora 27. I am searching for examples of using Qt to visualize CGAL arrangements. In particular, I am looking at the docs for CGAL 4.12 in the section "CGAL and the Qt Graphics View Framework". Also in the section: 2D Arrangements - Input/Output Stream. 

I would like to request a simple code example that shows how to import the relevant libraries, use the inserter to insert the arrangement into the Qt widget stream, and compile (maybe cgal_create_CMakeLists -c Core:Qt5).

Please compare to the documents for CGAL 3.1 section 16.2.1 "Hello Segment" code example.
https://doc.cgal.org/Manual/3.1/doc_html/cgal_manual/Qt_widget/Chapter_main.html

Unfortunately that example is using Qt3 or 4. Something like that updated in the current documentation would be very helpful!

Thanks

**Comment by maxGimeno** [comment]
You can look at the code here : 
[draw_surface_mesh](https://github.com/CGAL/cgal/blob/master/Surface_mesh/examples/Surface_mesh/draw_surface_mesh.cpp) and [header](https://github.com/CGAL/cgal/blob/master/Surface_mesh/include/CGAL/draw_surface_mesh.h).

The "basic viewer" is the simplest thing we have to visualize the content of a data strcture.

**Comment by algo01** [comment]
Hello and thank you for your reply. To tell you the truth, I gave up on CGAL and decided to use the Python library sympy with matplotlib for plotting. I was game to learn C++, but the learning curve with CGAL was too steep for what I wanted to accomplish.

Here's a good link on using computational geometry with Python, if anyone is interested:
http://blancosilva.github.io/post/2014/10/28/Computational-Geometry-in-Python.html

As for CGAL, it might be great for industrial users, but is totally unfriendly for newcomers. I would strongly suggest a much better tutorial on how to get some basic plots using Qt. 

Also, the arrangement demo is just ridiculous in terms of giving a well structured example one could modify. Just count out the number of files in this:

https://github.com/CGAL/cgal/tree/master/Arrangement_on_surface_2/demo/Arrangement_on_surface_2

**Comment by lrineau** [comment]
Any of the CGAL demo is too complicated for a newcomer. And actually it is also too complicated for anybody but the authors of it.

In CGAL-4.13, we also have simpler "graphical examples", as pointed by Maxime, in https://github.com/CGAL/cgal/issues/3238#issuecomment-428944134.

**Comment by AndrzejT** [comment]
> You can look at the code here :
> [draw_surface_mesh](https://github.com/CGAL/cgal/blob/master/Surface_mesh/examples/Surface_mesh/draw_surface_mesh.cpp) and [header](https://github.com/CGAL/cgal/blob/master/Surface_mesh/include/CGAL/draw_surface_mesh.h).
> 
> The "basic viewer" is the simplest thing we have to visualize the content of a data strcture.

I tried this (with MSVC 2017 and Qt 5.7), but it needs CGAL-vc140-mt-4.13.lib, which I can't generate ... I tried this 10 times ... .

**Comment by AndrzejT** [comment]
> You can look at the code here :
> [draw_surface_mesh](https://github.com/CGAL/cgal/blob/master/Surface_mesh/examples/Surface_mesh/draw_surface_mesh.cpp) and [header](https://github.com/CGAL/cgal/blob/master/Surface_mesh/include/CGAL/draw_surface_mesh.h).
> 
> The "basic viewer" is the simplest thing we have to visualize the content of a data strcture.

I tried to compile it, but it needs 'CGAL_Qt5-vc140-mt-4.13.lib', which is impossible to generate for me with cmake, MSVS 2017 and Qt 5.7 ... . Really tragic,

**Comment by maxGimeno** [comment]
Qt 5.7 is too old. You need at least Qt 5.9. After that you can cmake CGAL and check WITH_Qt5 to generate the CGAL_Qt5 lib you need.
