### ISSUE TITLE
Polyhedron Demo: how to add a plugin

### ISSUE THREAD

**Issue by zengjingcheng** [CGAL/cgal#3253]
## Issue Details

when I compile the polyhedron demo, I find that the operations don't have what I need. Then I find the files in the plugin, such as the classification_plugin. How can I add this tool in the polyhedron demo?

the other operations are good. But I can't use the classification.
In the preferences, the others are green but the classification is red.
The build didn't make any wrong.And it has the lib and the dll.

My version is 4.12beta2
and I built it in the VS2015

**Comment by zengjingcheng** [comment]
The classification plugin is compiled and it didnot have error, it had compiles a dll. So I didn't know whats wrong with the classification.

**Comment by maxGimeno** [comment]
If a line is displayed red in the preferences, then it has a tooltip with the error in it.

**Comment by MaelRL** [comment]
Feel free to reopen the issue if you encounter any further issue.
