### ISSUE TITLE
Unify face normal computation 

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#326]
The package Nef_3 has a file  [`CGAL/normal_vector_newell.h`](https://github.com/CGAL/cgal/blob/master/Nef_3/include/CGAL/normal_vector_newell_3.h)
This might be provided by the package Polygon mesh processing?
 Where does it differ from what we have in PMP?

**Comment by sloriot** [comment]
See also [Surface_mesh_skeletonization/include/CGAL/internal/Surface_mesh_skeletonization/get_normal.h](https://github.com/CGAL/cgal/blob/master/Surface_mesh_skeletonization/include/CGAL/internal/Surface_mesh_skeletonization/get_normal.h)

**Comment by sloriot** [comment]
In Nef this computes the normal of the plane containing a set of points.

**Comment by afabri** [comment]
It does not produce a unit length vector, and hence also works for Homogeneous<Gmpz>

**Comment by afabri** [comment]
I am wondering, if we should not have different functions for with and without the unit normal.  We have that for distances, where we only offer CGAL::squared_distance().

**Comment by janetournois** [comment]
this issue should be closed @sloriot @lrineau

**Comment by lrineau** [comment]
The PR #957 is still not merged. Why should this issue closed?

**Comment by sloriot** [comment]
This issue is not closed, #155 which is a duplicate is.
