### ISSUE TITLE
[Crash] Constrained 2D Delaunay triangulation: assertion violation!

### ISSUE THREAD

**Issue by yobeonline** [CGAL/cgal#3263]
## Issue Details
A crash occurs when inserting a set of constraints that forces the triangulation to split a constraint. See below.

![cgal_bis](https://user-images.githubusercontent.com/6747553/43446252-a5aa7932-94a8-11e8-9858-3d56dad1a79f.png)

On a debug executable, the following message is displayed:
>CGAL error: assertion violation!
Expression : false
File : C:\Sdk\CGAL\4.11.2\include\CGAL/Polyline_constraint_hierarchy_2.h
Line : 1013
Explanation:
Refer to the bug-reporting instructions at http://www.cgal.org/bug_report.html

This issue maybe a duplicate of [2999](https://github.com/CGAL/cgal/issues/2999) but since the fix for this issue has not been released yet, I am unable to test it here.

## Source Code

```c++
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/Constrained_Delaunay_triangulation_2.h>
#include <CGAL/Constrained_triangulation_plus_2.h>
#include <CGAL/Triangulation_face_base_2.h>
#include <CGAL/Triangulation_vertex_base_2.h>
#include <CGAL/Delaunay_triangulation_2.h>

using K = CGAL::Exact_predicates_inexact_constructions_kernel;

using Vb2 = CGAL::Triangulation_vertex_base_2<K>;
using Fb2 = CGAL::Constrained_triangulation_face_base_2<K>;

using TDS2 = CGAL::Triangulation_data_structure_2<Vb2,Fb2>;
using Itag2 = CGAL::Exact_predicates_tag;
using CDT2_Base = CGAL::Constrained_Delaunay_triangulation_2<K,TDS2,Itag2>;

using Triangulation = CGAL::Constrained_triangulation_plus_2<CDT2_Base>;
using point = Triangulation::Point;

void main(void)
{
  Triangulation t;

  point const p1(382150.50, 3946713.76);
  point const p2(382161.240, 3946717.95);
  point const p3(382157.120, 3946728.53);
  point const p4(382157.150, 3946709.90);
  point const p5(382155.03, 3946715.530);
  point const p6(382162.870, 3946718.59);

  { // green
    t.insert_constraint(p1,p2);
    t.insert_constraint(p2,p3);
    t.insert_constraint(p3,p1);
  }

  { // blue
    t.insert_constraint(p1,p4);
    t.insert_constraint(p4,p5);
    t.insert_constraint(p5,p1);
  }

  { // yelow
    t.insert_constraint(p4,p6);
    t.insert_constraint(p6,p5);
    t.insert_constraint(p5,p4);
  }
}
```

## Environment

* Windows 64 bits:
* Compiler: vs 2013 32 and 64
* Release or debug mode: both
* Specific flags used (if any): none
* CGAL version: 4.11.2
* Boost version: 1.65.1
* Other libraries versions if used (Eigen, TBB, etc.): none

**Comment by lrineau** [comment]
This issue is also fixed in CGAL-4.11.3, for the same reason: the cascading of intersections of segments is stopped by the bounded on ULP-distance between vertices.
