### ISSUE TITLE
Approximate Convex Decomposition of Volumes Bounded by Triangle Meshes

### ISSUE THREAD

**Issue by CUBERLEON** [CGAL/cgal#3270]
**Description**
The algorithm in this project was proposed by Khaled Mamou and Faouzi Ghorbel in the paper:
A simple and efficient approach for 3d mesh approximate convex decomposition. Groupe de recherche GRIFT, 2010.

It’s an efficient approach to decompose a concave 3D mesh into a set of nearly convex surfaces and is useful for skeleton extraction, patterns recognition applications and particularly for the increase of collision detection accuracy without significantly affecting its performance.

**Status**
The summary of the done work is available on Google Slides ([link](https://docs.google.com/presentation/d/12M4sW8Xv9cJrPV5efwInI_38uk59CbzM_t1Ja0v5RCc/edit?usp=sharing)).

**Commit log**
Branch: [_gsoc2018-approx_conv_decomp-cuberleon_](https://github.com/CGAL/cgal-public-dev/tree/gsoc2018-approx_conv_decomp-cuberleon).

f975b0966f update user manual
66955425e0 add benchmarks + update manuals
aa03434aa4 add segments postprocessing + bug fix
ec8db31d9d add missing named params + clean up
0f255afbc3 add _INTERNAL_ and a check function
839fabd4d1 Merge commit 'refs/pull/1/head' of github.com:CUBERLEON/cgal into gsoc2018-approx_conv_decomp-cuberleon
cad24f7ca8 pass on the dc
50d282c26e update convex hulls example
e072df310b remove unnecessary example
ce0e91048d add shortest concavity values image
6bd15b2a27 update plugin and doc
62e2615aa6 Merge commit 'refs/pull/1/head' of github.com:CUBERLEON/cgal into gsoc2018-approx_conv_decomp-cuberleon
24975bfa5c add shortest distances method parameter
f9a5e6a5df update image in doc
caf7560e5a add convex hulls named parameter
1b4b627942 aspell check + reworking
0951b59ecf minimum -> min
221d73db61 fix a bug with concavity values
b834062bcf add shortest distance computations
a02bdce133 add visualization of concavity values
57c0774a7c rename define for verbose output
0be534c793 refactoring + update the plugin
5bc45e9472 replace 4 spaces by 2 in the plugin
a909fd0809 add named parameter for minimum number of segments
7cf6bc9fd3 decomposition -> segmentation
47a69dca0a build fix
604b398e48 replace 4 spaces by 2
efaf4f93de update manuals
3a29a44b31 do not use an unordered map if not used
317913ffc4 renaming + ref man update
cb90f57cf2 rename header
af1a20d020 update doc
5c3e9d2c18 add Convex_hull_3 as dependencies
d40c16191a move protect macros
2c137c3c2b fix warning
fb60609a37 convex_decomposition -> approximate_convex_decomposition
a557078881 fix bibtex ref
940d66d435 add segmentation using concavity values example
9ba11a1e12 improve user manual
0644103c0f update user manual, add example
41dd3087bf remove unused meshes
51eea8c290 clean up examples
c2efc1918c add tests
486c1b5480 merge the folders of examples
96aace298c polish reference manual
038d165188 update reference manual descriptions
8ac3de52a4 merge packages + documentation integration
de856f3eea Add GPL license
d7a3355460 Replace remaining tabs with spaces
557c7a4624 Add concavity colors to the plugin
30f97ec2be Add decomposition extraction
5058616e39 using vpm
893c9b8e63 reorder template parameters + use conditional value for the tags
adb44c3a5f make the plugin use TBB if available
f51748db6e Improve the plugin's interface
5324e64f94 Add plugin, fix bug with candidate edges
05e6574ceb Improve backward compatibility
2681c105e1 Add parallelism with TBB
525c8e2128 Update comments
598ea835d1 Add ordered list of candidate edges
62579f1827 Add cluster ids to properties
173cd99d15 Add removal of redundant edges after decimation
197ce6567d Add fix for convex hull warnings
2aac9605b4 Add overloaded functions for NamedParameters
af69d5122c Add fixes for remarks
5695e748f5 Add more comments
6939ebfed4 Add complete Polyhedron support
c3319eb416 Improve Polyhedron support, more code cleanup
fe9f807bd8 Clean the code and update the comments, add working concavity example
b1460064da Fix bugs: first working but slow version
9d2881c1c1 Add first iteration implementation of the algorithm
92e59fa1be Build fix (an uncommented problematic line)
93c2b49275 Add the implementations of concavity value and dual graph
001e9e64e0 Update to API: remove cluster meshes
eb82ed6890 Add external API, the base of internal implementaion, and examples
66fb960ba3 Created the project's folder

**Comment by sloriot** [comment]
@CUBERLEON please provide the status of the project at the end of GSoC
