### ISSUE TITLE
Extending Generalized Barycentric Coordinates

### ISSUE THREAD

**Issue by kychern** [CGAL/cgal#3272]
### **Keyu Chen's GSoC 2018 Submission**

**Introduction**
This project aims at providing another two powerful generalized barycentric coordinates Harmonic coordinates and Maximum Entropy coordinates that possess a lot of important properties and can be used on a variety of general polygons. Moreover, this project will contribute some changes to the API and a tutorial program, in order to make the package more convenient and easy to understand for the final user.

**Report links**
[Google docs](https://docs.google.com/presentation/d/1foT5-RH1GwAVEUvInYbv5cEuTT_ANhaiUSHDFg8xl7s/edit?usp=sharing)

**Commit log**
https://github.com/CGAL/cgal-public-dev/commit/b399fa8 fixed typos and layout problems.
https://github.com/CGAL/cgal-public-dev/commit/864fce8 documentation update.
https://github.com/CGAL/cgal-public-dev/commit/0c99507 add Maximum_entropy_parameters class. remove TODO text.
https://github.com/CGAL/cgal-public-dev/commit/50c20c0 Reference Manual modifications.
https://github.com/CGAL/cgal-public-dev/commit/42b5991 add another Creation function.
https://github.com/CGAL/cgal-public-dev/commit/f48563d remove TODO text.
https://github.com/CGAL/cgal-public-dev/commit/5040b06 add Parameters template class.
https://github.com/CGAL/cgal-public-dev/commit/2244e1e add Barycentric_coordinates_2 citations.
https://github.com/CGAL/cgal-public-dev/commit/8b95522 additional figure.
https://github.com/CGAL/cgal-public-dev/commit/a5741e2 add MaximumEntropyParameters concept.
https://github.com/CGAL/cgal-public-dev/commit/b2bec5f add Maximum_entropy_parameters.h includings.
https://github.com/CGAL/cgal-public-dev/commit/4f184df modificate for `Parameters` class.
https://github.com/CGAL/cgal-public-dev/commit/70e0f71 typo fixed.
https://github.com/CGAL/cgal-public-dev/commit/ede6723 add `Parameters` template class for Maximum_entropy_2 class.
https://github.com/CGAL/cgal-public-dev/commit/80e112a parameterized Maximum_entropy_2 class with a new template `Parameters`.
https://github.com/CGAL/cgal-public-dev/commit/ecbd491 performance description for ME (unfinished).
https://github.com/CGAL/cgal-public-dev/commit/ab25f15 a typo.
https://github.com/CGAL/cgal-public-dev/commit/459c587 add Harmonic class to lists.
https://github.com/CGAL/cgal-public-dev/commit/d75767d add Prior and Solver concept.
https://github.com/CGAL/cgal-public-dev/commit/262bf6c add Harmonic coordinates citation.
https://github.com/CGAL/cgal-public-dev/commit/ec396dd add Solver concept.
https://github.com/CGAL/cgal-public-dev/commit/178a0d0 add Prior concept.
https://github.com/CGAL/cgal-public-dev/commit/ec736ae replace Vertex_range with Elements iterator.
https://github.com/CGAL/cgal-public-dev/commit/648c4e5 add CMakeLists.txt for benchmark test.
https://github.com/CGAL/cgal-public-dev/commit/67d2d7f add Maximum entropy coordinates benchmark tests.
https://github.com/CGAL/cgal-public-dev/commit/4c4ea04 update class and concept list.
https://github.com/CGAL/cgal-public-dev/commit/3393fcd update doxygen text with new API.
https://github.com/CGAL/cgal-public-dev/commit/ca633b4 add Maximum entropy coordinates citation.
https://github.com/CGAL/cgal-public-dev/commit/251c52b add MEC intruduction.
https://github.com/CGAL/cgal-public-dev/commit/ee59ef2 add a concave polygon.
https://github.com/CGAL/cgal-public-dev/commit/a9e5e78 delete old harmonic example picture.
https://github.com/CGAL/cgal-public-dev/commit/7e70c90 harmonic update(previous change).
https://github.com/CGAL/cgal-public-dev/commit/936010a update docs.
https://github.com/CGAL/cgal-public-dev/commit/99ae47e API update.
https://github.com/CGAL/cgal-public-dev/commit/fc378c0 remove suffix "_2" from Harmonic_mesh, solver and interpolator.
https://github.com/CGAL/cgal-public-dev/commit/a2ffbb4 add dependent including headers.
https://github.com/CGAL/cgal-public-dev/commit/3e8dfcd remove dependent including headers.
https://github.com/CGAL/cgal-public-dev/commit/de3915e clean up.
https://github.com/CGAL/cgal-public-dev/commit/72278a2 clean up the print information.
https://github.com/CGAL/cgal-public-dev/commit/50bab1f in default case, return boost::optional<OutputIterator>().
https://github.com/CGAL/cgal-public-dev/commit/3ca261b remove print_coordinates_information() function.
https://github.com/CGAL/cgal-public-dev/commit/302d251 add a sqrt object.
https://github.com/CGAL/cgal-public-dev/commit/756cf49 add template word.
https://github.com/CGAL/cgal-public-dev/commit/ce984d0 add separated partition class.
https://github.com/CGAL/cgal-public-dev/commit/c45d568 change int to size_t in all loops.
https://github.com/CGAL/cgal-public-dev/commit/80c105b add dependent headers.
https://github.com/CGAL/cgal-public-dev/commit/c8b701f remove some dependent headers.
https://github.com/CGAL/cgal-public-dev/commit/f3e0b42 clean up.
https://github.com/CGAL/cgal-public-dev/commit/a0ed086 update compute() interface.
https://github.com/CGAL/cgal-public-dev/commit/7d3ab58 add Harmonic_2 and Maximum_entropy_2 headers.
https://github.com/CGAL/cgal-public-dev/commit/3c24d45 add general container and point map.
https://github.com/CGAL/cgal-public-dev/commit/e7390e0 remove unnecessary files.
https://github.com/CGAL/cgal-public-dev/commit/00f5054 add Eigen solver.
https://github.com/CGAL/cgal-public-dev/commit/704c5f1 separate two prior function class.
https://github.com/CGAL/cgal-public-dev/commit/6f0a3a9 passing vector instead of elements parameters.
https://github.com/CGAL/cgal-public-dev/commit/3d75bde update new API (v2). clean up.
https://github.com/CGAL/cgal-public-dev/commit/8b3690e add general container and corresponding point maps.
https://github.com/CGAL/cgal-public-dev/commit/3bb9314 add point_map and input_range for new API design.
https://github.com/CGAL/cgal-public-dev/commit/3a2caff add C++ 11 standard.
https://github.com/CGAL/cgal-public-dev/commit/14a902c update API modification.
https://github.com/CGAL/cgal-public-dev/commit/cc410ce update constructor and Coordinate_2 type.
https://github.com/CGAL/cgal-public-dev/commit/4db149b add C++ 11 standard.
https://github.com/CGAL/cgal-public-dev/commit/5301510 change constructor of main class.
https://github.com/CGAL/cgal-public-dev/commit/ba0d8df clean up.
https://github.com/CGAL/cgal-public-dev/commit/5e055ed add random access range concept. clean up.
https://github.com/CGAL/cgal-public-dev/commit/e084f28 pass Point value to vertex Range, fix all CGAL_precondition bugs.
https://github.com/CGAL/cgal-public-dev/commit/1f029aa Test under new API.
https://github.com/CGAL/cgal-public-dev/commit/b2e08fd add Property map for Harmonic_2 (v1)
https://github.com/CGAL/cgal-public-dev/commit/6a258c5 add Property map for MEC (v1)
https://github.com/CGAL/cgal-public-dev/commit/d5a27e6 set up denser partition.
https://github.com/CGAL/cgal-public-dev/commit/53542f0 output differences between HM and Triangle coordinates.
https://github.com/CGAL/cgal-public-dev/commit/436708e add concave polygon example.
https://github.com/CGAL/cgal-public-dev/commit/8022557 normalization for coordinates.
https://github.com/CGAL/cgal-public-dev/commit/e6dd5bb clean up.
https://github.com/CGAL/cgal-public-dev/commit/bcfedd1 add HM_triangle_test
https://github.com/CGAL/cgal-public-dev/commit/9dfd0bd clean up
https://github.com/CGAL/cgal-public-dev/commit/edbbf77 add interpolator to compute interpolation coordinates for query point.
https://github.com/CGAL/cgal-public-dev/commit/5ec6672 clean up.
https://github.com/CGAL/cgal-public-dev/commit/4d8b4c7 add wrapper for Barycentric_coordinates::compute_triangle_coordinates()
https://github.com/CGAL/cgal-public-dev/commit/eb02362 temporarily remove cotangent weights concept.
https://github.com/CGAL/cgal-public-dev/commit/2f0db6a add example and test for Harmonic_2
https://github.com/CGAL/cgal-public-dev/commit/8a7d12d finished compute_harmonic_coordinates v2
https://github.com/CGAL/cgal-public-dev/commit/b398443 fix some neighbors missing bug.
https://github.com/CGAL/cgal-public-dev/commit/d897f5d add solver class
https://github.com/CGAL/cgal-public-dev/commit/c46312e finished solver class v1
https://github.com/CGAL/cgal-public-dev/commit/f01d02a rename interpolator concept
https://github.com/CGAL/cgal-public-dev/commit/5088ecc add cotangent concept for solver class
https://github.com/CGAL/cgal-public-dev/commit/871a0e2 add Triangulation_vertex_base_info_2 concept
https://github.com/CGAL/cgal-public-dev/commit/e8ae6d4 add Solver class interface design
https://github.com/CGAL/cgal-public-dev/commit/7f14a6b finished neighbor store and query function
https://github.com/CGAL/cgal-public-dev/commit/5ad2c59 test Harmonic_mesh class
https://github.com/CGAL/cgal-public-dev/commit/421cfcd add property map for mesh vertices
https://github.com/CGAL/cgal-public-dev/commit/fc2b79a clean-up
https://github.com/CGAL/cgal-public-dev/commit/a20cae6 add list_all_vertices() add get_neighbors()
https://github.com/CGAL/cgal-public-dev/commit/d5612d9 add locate interface for Harmonic_2
https://github.com/CGAL/cgal-public-dev/commit/0d16a08 add mesh generating result
https://github.com/CGAL/cgal-public-dev/commit/23e7de4 refine mesh generating step
https://github.com/CGAL/cgal-public-dev/commit/2f32bab add wrappers for mesh_create and locate
https://github.com/CGAL/cgal-public-dev/commit/ac8c651 add Harmonic coordinates example
https://github.com/CGAL/cgal-public-dev/commit/3afaa80 add Harmonic_2 and Maximum_entropy_2 includings
https://github.com/CGAL/cgal-public-dev/commit/10b0845 add Harmonic_2 folder
https://github.com/CGAL/cgal-public-dev/commit/143f2bc Basic structure for Harmonic_2 class
https://github.com/CGAL/cgal-public-dev/commit/6e6bb40 add MEC_non_convex_polygon_test.cpp (PASSED).
https://github.com/CGAL/cgal-public-dev/commit/0f5e3e2 clean up.
https://github.com/CGAL/cgal-public-dev/commit/98f4f73 Test exp() and sqrt() using with exact kernel.
https://github.com/CGAL/cgal-public-dev/commit/f57e27c add MEC_triangle_exact_test.cpp
https://github.com/CGAL/cgal-public-dev/commit/aff15a0 Try to fix bugs for exact kernel.
https://github.com/CGAL/cgal-public-dev/commit/c4deea1 add MEC_compare_with_gbc_test
https://github.com/CGAL/cgal-public-dev/commit/2c69846 add todo list
https://github.com/CGAL/cgal-public-dev/commit/7e4ede6 add type cast for exp() result.
https://github.com/CGAL/cgal-public-dev/commit/4f0b5a9 add MEC_triangle_inexact_test.cpp
https://github.com/CGAL/cgal-public-dev/commit/98a8680 passed triangle_coordinates_2 test
https://github.com/CGAL/cgal-public-dev/commit/357475c add Maximum_entropy example code
https://github.com/CGAL/cgal-public-dev/commit/bcfc522 add Maximum_entropy class

**Comment by sloriot** [comment]
@kychern please provide the status of the project at the end of GSoC
