### ISSUE TITLE
CGAL ERROR: assertion violation!

### ISSUE THREAD

**Issue by golo314** [CGAL/cgal#3273]
## Issue Details

I am getting an assertion violation when reading in a serialized surface mesh (saving works without any problems).

This is the error I am getting:
```
terminate called after throwing an instance of 'CGAL::Assertion_exception'
  what():  CGAL ERROR: assertion violation!
Expr: _idx < data_.size()
File: /usr/include/CGAL/Surface_mesh/Properties.h
Line: 173
Aborted
```
File is being saved as: SomeName.off

## Source Code

For saving a mesh I use:
```
  std::ofstream oFile{dir};
  if (oFile.is_open()) {
    CGAL::set_binary_mode(oFile);
    oFile << mesh;
    return true;
  } else {
    return false;
  }
```
For loading a mesh I use:
```
  std::ifstream iFile{dir};
  if (iFile.is_open()) {
    CGAL::set_binary_mode(iFile);
    iFile >> mesh;
    return true;
  } else {
    return false;
  }
```
## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Fedora 28 64bit
* Compiler: c++ (GCC) 8.1.1 20180712 (Red Hat 8.1.1-5)
* Release or debug mode: release
* Specific flags used (if any): N/A
* CGAL version: CGAL-4.11.1-1.fc28.x86_64
* Boost version: boost-1.66.0-8.fc28.x86_64
* Other libraries versions if used (Eigen, TBB, etc.): N/A

**Comment by MaelRL** [comment]
Could you please provide the file you are trying to read (ideally saved in ASCII)?

**Comment by golo314** [comment]
I am not sure if I can upload a file that is 3.4GB in size.

**Comment by lrineau** [comment]
How many vertices and facets in that mesh and in that file?

**Comment by golo314** [comment]
28,835,840 vertices
57,650,178 facets

**Comment by golo314** [comment]
Quick Update:
I downgraded the quality of the mesh to: 11,010,048 vertices and 22,006,786 facets.
The result is a new error:
what():  CGAL ERROR: precondition violation!
Expr: ! k.is_degenerate_3_object()(t)
File: /usr/include/CGAL/internal/Intersections_3/Triangle_3_Ray_3_intersection.h
Line: 450

**Comment by sloriot** [comment]
For the last error, I assume you are using the AABB-tree and some of your triangle face are degenerated. One way to avoid this problem is to not insert degenerate faces in the tree.

**Comment by golo314** [comment]
The weird thing is that I am getting the surface mesh from IO. I create a surface mesh and serialize it, then in another function I attempt to read the serialized mesh.

**Comment by sloriot** [comment]
did you set the precision of the stream to the max (something like `std::setprecision(17)`)?

**Comment by golo314** [comment]
From my code above:
`std::ofstream oFile{dir};
  if (oFile.is_open()) {
    CGAL::set_binary_mode(oFile);
    oFile << mesh;
    return true;
  } else {
    return false;
  }`

So no, I do not.

**Comment by sloriot** [comment]
The `operator<<` will write in the OFF format. The binary mode is not needed. You can use replace your code with: 
```
oFile << std::setprecision(17) << mesh;
```

**Comment by golo314** [comment]
Thank you, I will make the changes and let you know how it goes.

**Comment by golo314** [comment]
That fixed my problem!

Thank you so much for your help, I really appreciate it.

**Comment by afabri** [comment]
Let me also add a comment concerning the `set_binary_mode()`.   On Windows it also requires that the stream is open with `std::ios::binary`.
