### ISSUE TITLE
Generalized Region Growing

### ISSUE THREAD

**Issue by hoangvanthien** [CGAL/cgal#3276]
Thien Hoang's GSoC 2018 Submission

# Overview

This CGAL component implements the region growing algorithm for shape detection. The algorithm has been generalized to be working with any user-defined elements, connectivity method, and validity checking rules.

[Link to the final report](https://docs.google.com/document/d/1J9VncBENYJ48Uuj1nYwPJDBZsOt_R4EgQEEOxIKUXj8/)

# Commit log

https://github.com/CGAL/cgal-public-dev/commit/638c0f6fae Add benchmark file
https://github.com/CGAL/cgal-public-dev/commit/3a370338c6 Removed tbody tag in the time table
https://github.com/CGAL/cgal-public-dev/commit/34e4170f54 Fix missed authors in user manual
https://github.com/CGAL/cgal-public-dev/commit/af804e8914 Edit author list, fix ref links and time table
https://github.com/CGAL/cgal-public-dev/commit/1df9b416cc Add docs, tests; refine examples; fix small bugs
https://github.com/CGAL/cgal-public-dev/commit/02c1be96b1 Remove references in primitive types - fix bugs in release mode
https://github.com/CGAL/cgal-public-dev/commit/865d67c67a Add city_135.xyz
https://github.com/CGAL/cgal-public-dev/commit/3d6e920e80 Remove indices
https://github.com/CGAL/cgal-public-dev/commit/8791e82087 Hard code a mesh in another example
https://github.com/CGAL/cgal-public-dev/commit/2ff748e4af Completed example and test case for mesh
https://github.com/CGAL/cgal-public-dev/commit/8e74a2aade Change some types and adapt the 3D model to the index-based GRG
https://github.com/CGAL/cgal-public-dev/commit/cc44a8f09d Rework the 2d example for local testing
https://github.com/CGAL/cgal-public-dev/commit/0e1a06395c Use indices globally
https://github.com/CGAL/cgal-public-dev/commit/9729cdac77 Rename meshes to mesh, add the Conditions class
https://github.com/CGAL/cgal-public-dev/commit/af62aa9e5f Add connectivity and conditions classes for meshes
https://github.com/CGAL/cgal-public-dev/commit/7962c22912 Fix indicies and Conditions bugs after testing city_135
https://github.com/CGAL/cgal-public-dev/commit/f7a1dd6e95 Add index map as an option to optimize the speed
https://github.com/CGAL/cgal-public-dev/commit/ac75a7b299 Add kNN method, improve time performance
https://github.com/CGAL/cgal-public-dev/commit/f0854bb6c2 Make class Conditions work with Epeck
https://github.com/CGAL/cgal-public-dev/commit/80fc8cc4c4 Merge Traits classes; merge Connectivity classes
https://github.com/CGAL/cgal-public-dev/commit/db1804686e Add model for 3D Points, example usage, and data
https://github.com/CGAL/cgal-public-dev/commit/fa1620a75b Write file in PLY format and add more data
https://github.com/CGAL/cgal-public-dev/commit/5ef455a2f6 Add example usage for 2D Points RG and data test
https://github.com/CGAL/cgal-public-dev/commit/28f7a1cd46 Fix include links in Region_growing.h
https://github.com/CGAL/cgal-public-dev/commit/a2edf788db Add Element_with_properties and class Conditions
https://github.com/CGAL/cgal-public-dev/commit/6353cb3194 Change types of arguments and variables to comply with kd-tree
https://github.com/CGAL/cgal-public-dev/commit/3e4c5a51c0 Add kd-tree to class Connectivity for 2D Points
https://github.com/CGAL/cgal-public-dev/commit/fba1a713e5 Add const modifer and ref to variables, fix some technical details
https://github.com/CGAL/cgal-public-dev/commit/b2d9266b64030396b08c5c10aa9433bb58b55c1f Rephrase the comments
https://github.com/CGAL/cgal-public-dev/commit/a3dcc1a4d1 Add package structure v3
https://github.com/CGAL/cgal-public-dev/commit/5c64e7ebf9 Add package structure

**Comment by sloriot** [comment]
@hoangvanthien please provide the status of the project at the end of GSoC

**Comment by danston** [comment]
Merged in https://github.com/CGAL/cgal/pull/3864. The branch on cgal-public-dev is removed.
