### ISSUE TITLE
Batch of CGAL demo issues / suggestions

### ISSUE THREAD

**Issue by MaelRL** [CGAL/cgal#3277]
This is from the IGM branch, but it's not too far from master so the points below are hopefully still relevant.

- [x] Coloring operations such as "detect features" do not work when using a polyhedron item.

- [x] Transparency is broken when there is a selection item.

- [x] Ctrl+A (select all) is broken after splitting a mesh into multiple CCs.

- [x] Create mesh bbox on a mesh without faces segfaults. Can reproduce it by just selecting all faces and removing them before trying to create a box.

- [x] Canceling a change of ramp color changes the color to black instead of leaving it as it is. (and the color is bigger than the button when you change colors.)

- [x] Ramp extreme values are reset when you re-colorize (?).

- [x] Pressing "Zoom to min/max" does about the opposite of what you'd expect. Pressing it multiple times zooms out.

- [x] There seems to be some sort of caching for the colorizing item that does not take into account whether the mesh has been modified or not. If you colorize, move a vertex, re-colorize, nothing changes.

- [x] Selection item's clear() doesn't work for edges selected via the "sharp edges" tool... if you don't have "edges" selected in simplices. That's a bit... unclear.

- [x] Selection items dragged from a folder show up as unnamed.

- [x] There are some issues parsing tricky file names such as "asd.off-fixed.off", as well as for overwriting saves.

- <s>[ ] You can't overwrite a .COFF with a .OFF, it creates a new file.</s>

- [x] You can't measure with shift-click if you have a selection item open.

- [x] You can't see the white cross that appears when you re-select the center of the camera rotation if the camera is too close to a mesh.

Some suggestions:
- [x] The menu of operations in the selection item  (e.g. "Erase face from...") should not reset to a blank state once the operation has been applied.

- [x] The "clear" button in the selection should probably say something like "Clear current simplex type" or something like that, which is what it seems to be doing (although a rework of this part would probably be better).

- <s>[ ] The property to display should be above the color choice, the bar should be horizontal, that would waste less space.</s>

- [x] Selection files should save by default to the location that the corresponding mesh was opened from (if relevant).

- [x] `File -> Load script -> Esc`  => `Error: file to open is a directory: iostream error`

- [x] When generating a Polyline, the name has an incorect number. 

- [x] When trying to load a soup_item with surface_mesh, if there is an assertion in the first attempt, the demo will crash and never make it to the part where the soup is created. Maybe we could add a try in the surface_mesh_io_plugin that would catch such an assertion and trigger the part with the soup to prevent that.
## Environment
master, release

**Comment by afabri** [comment]
@MaelRL A great list!!

Addional Suggestions
- When I load a selection it has the name "unnamed" . Call it as the file.

**Comment by sgiraudot** [comment]
There's something that's probably a lot of work but I've been thinking about it for a while and it would be quite nice to have:

* a `Settings` options that opens a new window with all the possible settings of the demo gathered together. They could replace some of the current options of `View` such as `Set Maximum Text Items Displayed`, `Change Background Color`, etc. Plus, it would be very cool to add some other options like what default display the user wants to use for a mesh, for a point set, what default size of points should be used, what plug-in should be used for which input format to replace the current behavior with the selector window when we open a file, etc. (The list should be though over, but anyway, once we have the general mechanism, it will be easy to add/remove stuff from it.) And another important thing: these settings should be automatically saved (in a config folder, there's probably a boost library to handle that cross-platformly) and loaded again when starting the demo, so that we can have our own customized settings on our computers.

**Comment by maxGimeno** [comment]
@MaelRL what do you mean "the color is bigger than the button when you change colors" ?

**Comment by maxGimeno** [comment]
> You can't overwrite a .COFF with a .OFF, it creates a new file.
I don't see the problem. If you changed the name it's not overwriting, I don't know of any program or application that will let you do that. Or maybe I don't understand the issue.

**Comment by maxGimeno** [comment]
> The menu of operations in the selection item (e.g. "Erase face from...") should not reset to a blank state once the operation has been applied.

It does not. It changes according to the currently selected vertices. If you deleted all you selection, then it becomes blank. If vertices remain, then it only contains actions for the vertices, etc.

**Comment by maxGimeno** [comment]
> The "clear" button in the selection should probably say something like "Clear current simplex type" or something like that, which is what it seems to be doing (although a rework of this part would probably be better).

I agree that Clear is not obvious enough. From your insistance on that point, I wonder if you noticed the button "Clear Selection Item" that clears all the simplices.

**Comment by maxGimeno** [comment]
> the bar should be horizontal, that would waste less space

I strongly disagree. I find it much more convenient to have a tall widget than a large widget, that will take all the place of your scene. Furthermore, I think it would be less readable with the extrema written horizontally.

**Comment by afabri** [comment]
> The menu of operations in the selection item (e.g. "Erase face from...") should not reset to a blank state 
> once the operation has been applied.

When you try to little by little erase faces it is not practical to go from blank to "Create Polyhedron" after having selected a face, then switch to "Erase faces",which brings you back to blank/select/ "Create".

**Comment by afabri** [comment]
Selection files should not have "(selection)" as part of the name, as it is already part of the extension.

**Comment by maxGimeno** [comment]
@afabri ok, I'll see what i can do.

**Comment by afabri** [comment]
Also, is it possible to switch to only the OpenGL widget full screen with one key.

Also compute the bbox of two surface mesh items, and rescale and reposition one  to the bbox of the other (without changing the aspect ratio).

**Comment by maxGimeno** [comment]
@sgiraudot 
> And another important thing: these settings should be automatically saved (in a config folder, there's probably a boost library to handle that cross-platformly) and loaded again when starting the demo, so that we can have our own customized settings on our computers.

Qt manages that well, don't worry. We already have some settings saved after closure.

**Comment by MaelRL** [comment]
> @MaelRL what do you mean "the color is bigger than the button when you change colors" ?

See picture below, on which I changed the color of the top button: the colored area is larger than the boundary of the button. Might be some qt bug?

![0](https://user-images.githubusercontent.com/5074170/44710514-95da2b00-aaac-11e8-9b5f-cc7d27e6cc0d.png)

**Comment by maxGimeno** [comment]
Oh yeah, it's less visible on my screen, but I reproduce. Fixed.

**Comment by MaelRL** [comment]
Loading a `.mesh` and trying to change the color seems to lock up the demo.

**Comment by maxGimeno** [comment]
Is .mesh the format for c3t3 items ? If it is I don't reproduce.

**Comment by MaelRL** [comment]
It is. Restarted, recompiled master's demo, etc. and it still freezes when I try to change the color of a `.mesh` (or save it).

**Comment by MaelRL** [comment]
- [ ] "Select degenerate faces and boundary edges" should also select vertices in case the edges are also degenerate.
- [ ] When a new selection item, the "current tool" in the selection widget should be reset. More clearly with an example: with my last selection item, I have been splitting faces. I'm done, I close my selection widget and delete the selection item. Now, if I check for degenerate edges (and some are present), it will create a new selection item (but not open the selection widget) and the cursor is still in "editing: split faces", which is really not what it should be.
- [ ] opening .obj shows as "unamed".
- [ ] Can't select the vertices of a lone degenerate face in the edition tab

**Comment by maxGimeno** [comment]
> Can't select the vertices of a lone degenerate face in the edition tab

The selection uses an AABB_tree based on the faces, so if there is no face to intersect, nothing will be selected. Maybe something about closest_primitive() could be used in case no intersection is found...
@lrineau, @sloriot  what do you think ?

**Comment by MaelRL** [comment]
Maybe also offering a lasso-based selection for "move point" (and possibly other relevant operations)?

**Comment by maxGimeno** [comment]
You mean allowing several points to be moved at a same time ?

**Comment by sloriot** [comment]
> > Can't select the vertices of a lone degenerate face in the edition tab
> 
> The selection uses an AABB_tree based on the faces, so if there is no face to intersect, nothing will be selected. Maybe something about closest_primitive() could be used in case no intersection is found...
> @lrineau, @sloriot what do you think ?

Aren't the faces filtered out when building the aabb-tree?

**Comment by maxGimeno** [comment]
Ah yeas, you are right. There is no degenerate face in the tree. So... Just find the closest selection_primitive naively if there is somethinf under the cursor but nothing is found in the tree ? That doesn't sound very optimised but the other alternative I can think of is keeping 3 trees, one for each primitive type, which is not a good option I think.

**Comment by maxGimeno** [comment]
- [ ] When used with TBB, the distance_plugin has issues with its vertices color. It is not in the right order or something.
