### ISSUE TITLE
CGAL error: assertion violation!

### ISSUE THREAD

**Issue by easterngarden** [CGAL/cgal#3284]
## Issue Details

C:\dev\CGAL-4.12\build-examples\Surface_mesh_skeletonization\Debug>simple_mcfskel_example data/renault_subframe_segment_11.off
CGAL error: assertion violation!
Expression : CGAL::is_closed(tmesh)
File       : c:\dev\cgal-4.12\include\cgal\side_of_triangle_mesh.h
Line       : 155
Explanation:
Refer to the bug-reporting instructions at https://www.cgal.org/bug_report.html

C:\dev\CGAL-4.12\build-examples\Surface_mesh_skeletonization\Debug>MCF_Skeleton_example data/renault_subframe_segment_11.off
CGAL error: assertion violation!
Expression : CGAL::is_closed(tmesh)
File       : c:\dev\cgal-4.12\include\cgal\side_of_triangle_mesh.h
Line       : 155
Explanation:
Refer to the bug-reporting instructions at https://www.cgal.org/bug_report.html

## Source Code

This is just using CGAL example codes/app.

## Environment

* Operating system (Windows 10 64 bits):
* Compiler: Visual Studio 2017 C++
* Release or debug mode: debug
* Specific flags used (if any):
* CGAL version: 4.12
* Boost version: 1.67.0
[renault_subframe_segment_11.zip](https://github.com/CGAL/cgal/files/2295458/renault_subframe_segment_11.zip)

* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by sloriot** [comment]
As [documented](https://doc.cgal.org/latest/Surface_mesh_skeletonization/index.html#MCFSkelSecAPI-IO) the input mush be closed : _The input is a triangulated surface mesh,  (...) that has no boundary and that has only one connected component._
