### ISSUE TITLE
Polyhedron demo, plugins load error : The specified module could not be found.

### ISSUE THREAD

**Issue by EazeFang** [CGAL/cgal#3299]
## Issue Details

I am new to CGAL. After testing some "hello world" code. I complied the polyhedron demo by CMake step by step. but when I run the Polyhedron_3.exe，the console shows this error:

![image](https://user-images.githubusercontent.com/42734702/44711345-c340cc00-aae0-11e8-89f5-a847c6c056db.png)
I ensure the DLLs are in the right path.

but GUI shows correctly:
![image](https://user-images.githubusercontent.com/42734702/44711662-78738400-aae1-11e8-9fc8-3f17a36a009e.png)

this is my CMake configure:
![1535444700 1](https://user-images.githubusercontent.com/42734702/44710583-08fc9500-aadf-11e8-8180-175a9a5ab687.png)

![1535444831 1](https://user-images.githubusercontent.com/42734702/44710729-5f69d380-aadf-11e8-9e7a-c5a93002c159.jpg)

## Environment

* Windows 10 x64;
* Compiler vs 2013 X64;
* Release mode;
* CGAL version is 4.11.2;
* Boost version is 1.65.0;
* TBB version is 4.3;
* Qt version is 5.7.0;
* libQGLViewer is 2.6.4;

## my search results
I found this similar issue, but it was closed. It costs my two days to find the reason, anyone help? thanks a lot!
https://github.com/CGAL/cgal/issues/381

**Comment by sloriot** [comment]
Did you put CGAL dll's in the PATH? I guess dependency walker called on the plugin dll that cannot be loaded should also give you more information.

**Comment by EazeFang** [comment]
Ah ha!  It's solved by resetting the boost and CGAL environment variables.
