### ISSUE TITLE
operator << for Vec

### ISSUE THREAD

**Issue by gdamiand** [CGAL/cgal#3327]
## Issue Details

`operator <<` for `qglviewer::vec` class does not work.

## Source Code

The following simple code raises a link error: `undefined operator << for CGAL::qglviewer::Vec`.

```
#include <iostream>
#include <CGAL/Qt/qglviewer.h>
int main()
{
  CGAL::qglviewer::Vec v(1., 0., 0.);
  std::cout<<v<<std::endl;  
  return EXIT_SUCCESS;
}
```

I think `operator <<` in file `vec_impl.h` should be defined outside `CGAL::qglviewer` namespace.

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Linux
* Compiler:
* Release or debug mode:
* Specific flags used (if any):
* CGAL version:
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by lrineau** [comment]
The `operator<<`, defined in vec.h, should be defined in `CGAL::qglviewer` as well. If it was in the main namespace, then the argument dependent lookup would not apply, and the only way to call that operator would be
```c++
::operator<<(std::cout, vec);
```

**Comment by gdamiand** [comment]
Ok; but why my simple code (given above) does not link, while same version with QGLViewer does ?

**Comment by lrineau** [comment]
I do not know why that compiles with QGLViewer. The issue was already in it.

**Comment by gdamiand** [comment]
The linker error comes from the fact that operator << is declared outside any namespace in vec.h (which I think is correct) and defined in CGAL::qglviewer namespace in vec_impl.h (which is wrong).

@maxGimeno I can do a PR if you want.

**Comment by gdamiand** [comment]
Done.
