### ISSUE TITLE
polyhedron demo surface_intersection_plugin  error:  "QtPrivate::remove_reference"  using of class template requires template argument list

### ISSUE THREAD

**Issue by liang-god** [CGAL/cgal#3334]
release x64     vs2015    

this is the only one cannot run success!

![image](https://user-images.githubusercontent.com/29827175/45544900-3bcabb00-b84b-11e8-99ff-b6e5eb08566f.png)

![image](https://user-images.githubusercontent.com/29827175/45544926-4b4a0400-b84b-11e8-8455-9407b722f8e4.png)

so how to solve this? This is the source code.

**Comment by lrineau** [comment]
Probably the type `face_descriptor` is not defined in this context.

**Comment by liang-god** [comment]
> Probably the type `face_descriptor` is not defined in this context.

![image](https://user-images.githubusercontent.com/29827175/45603913-a9503480-ba61-11e8-8b9c-73cd4e1756c1.png)

At the 33 row,  I don't think that's the problem.

**Comment by liang-god** [comment]
I change the style to unicode(utf-8 BOM) .  It works!
But a new issue: failed to extract plugin meta  from this .dll.

With Note: No relevant classes found. No output generated.
