### ISSUE TITLE
Graphcut conflict with boost

### ISSUE THREAD

**Issue by danston** [CGAL/cgal#3335]
## Issue Details

When I include the <CGAL/Delaunay_triangulation_3.h> in my code, I get two compilation errors:

----------------

In file included from /Users/danisimo/Documents/pipeline/cgal-public-dev/Triangulation_3/include/CGAL/Delaunay_triangulation_3.h:40:
In file included from /Users/danisimo/Documents/pipeline/cgal-public-dev/Triangulation_3/include/CGAL/Triangulation_3.h:46:
In file included from /Users/danisimo/Documents/pipeline/cgal-public-dev/TDS_3/include/CGAL/Triangulation_data_structure_3.h:39:
In file included from /usr/local/include/boost/unordered_set.hpp:17:
/usr/local/include/boost/unordered/unordered_set.hpp:1355:20: **error: expected ';' at end of declaration
      node_pointer last_node = table::get_node(last);**
                   ^
/Users/danisimo/Documents/pipeline/cgal-public-dev/Surface_mesh_segmentation/include/CGAL/internal/auxiliary/graph.h:620:28: note: expanded from macro 'last_node'
#define last_node LAST_NODE.LAST_NODE

----------------

In file included from /Users/danisimo/Documents/pipeline/cgal-public-dev/Triangulation_3/include/CGAL/Delaunay_triangulation_3.h:40:
In file included from /Users/danisimo/Documents/pipeline/cgal-public-dev/Triangulation_3/include/CGAL/Triangulation_3.h:46:
In file included from /Users/danisimo/Documents/pipeline/cgal-public-dev/TDS_3/include/CGAL/Triangulation_data_structure_3.h:39:
In file included from /usr/local/include/boost/unordered_set.hpp:17:
/usr/local/include/boost/unordered/unordered_set.hpp:1749:20: **error: expected ';' at end of declaration
      node_pointer last_node = table::get_node(last);**
                   ^
/Users/danisimo/Documents/pipeline/cgal-public-dev/Surface_mesh_segmentation/include/CGAL/internal/auxiliary/graph.h:620:28: note: expanded from macro 'last_node'
#define last_node LAST_NODE.LAST_NODE

----------------

The problem disappears if I go to CGAL/internal/auxiliary/graph.h and substitute all instances of last_node by last_node_tmp, for example.

## Source Code
My code is quite complex and I do not have a simple example for reproducing the bug for the moment, but if you need it, please let me know and I will try to work it out.

## Environment

* Operating system: 
Mac 64 bits

* Compiler: 
Apple LLVM version 9.1.0 (clang-902.0.39.2)
Target: x86_64-apple-darwin17.7.0

* Release or debug mode:
both

* Specific flags used (if any):
-fdeclspec 

* CGAL version:
If I correctly found it, it is 3.9.

* Boost version:
1.67.0_1

* Other libraries versions if used (Eigen, TBB, etc.):
OpenCV 3.4.1_5
eigen 3.3.4
gdal 2.2.4_2
ma27
openblas 0.2.20_1

Thank you in advance!

**Comment by lrineau** [comment]
This bug was fixed since CGAL version 4.10.2 by the pull-request #2449. CGAL version 3.9 was published September 2011, and is no longer supported.

If you really want to have a chance with CGAL-3.9, then use a version of Boost older than 1.65.

**Comment by danston** [comment]
Ok, great. Thank you for pointing out! I did not update my cgal for a long time. I will then fix it.
