### ISSUE TITLE
Polyhedron demo: Bugs in display of some surface mesh

### ISSUE THREAD

**Issue by maxGimeno** [CGAL/cgal#3360]
## Issue Details
With some not triangule surface mesh, facets are not displayed.
## Source Code
OFF
4 1 0

0 0 1
1 0 0
1 1 1
2 1 1

4 0 2 1 3

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):
* Compiler:
* Release or debug mode:
* Specific flags used (if any):
* CGAL version:
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by lrineau** [comment]
Fixed by #3358.
