### ISSUE TITLE
AABB_tree: AABB_facegraph_triangle_primitive doesn't return the mesh 

### ISSUE THREAD

**Issue by maxGimeno** [CGAL/cgal#3364]
## Issue Details

When pushing more than one mesh into the tree, the ID is a pair containing a primitive id and a mesh, but when asking for the intersected primitives, only the primitive id is returned, so it is not usable.

**Comment by maxGimeno** [comment]
see #1872

**Comment by sloriot** [comment]
I wouldn't close it, this is another issue IMO.
