### ISSUE TITLE
Surface_mesh::join does not seem to link free elements correcly

### ISSUE THREAD

**Issue by Simon-Lopez** [CGAL/cgal#3375]
## Issue Details

When chaining free elements (vertices, faces and edges) in Surface_mesh::join method the role of self and other seem to be inverted.

## Environment
* CGAL version: latest

**Comment by Simon-Lopez** [comment]
The problem comes from the first part of the join method that adds an offset to all of the element imported from the other Surface_mesh object (the one that is joined into the current one), This offset invalidate the chain of *freed* elements.

**Comment by lrineau** [comment]
Fixed by #3377. Will by in CGAL-4.12.2 and CGAL-4.13.1.
