### ISSUE TITLE
Infinite loop in nn2

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#3380]
Initially reported on cgal-discuss (2014/07/04)

It seems that there is an infinite loop:
[inter_br.zip](https://github.com/CGAL/cgal/files/2454861/inter_br.zip)

**Comment by afabri** [comment]
`Delaunay_triangulation_2::get_boundary_of_conflicts()` does not produce a correct cyclic border.  This is maybe because it is called with an undocumented additional parameter. I investigate.

**Comment by MaelRL** [comment]
https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/DT2_strict_and_weak_conflict_zone might provide a little bit more info on the parameter. It's marked as stalled, but the code was integrated.

**Comment by lrineau** [comment]
We are safe here: the author of that rogue feature it Andreas.

It might be a good time to come back to it, and document it properly.

**Comment by MaelRL** [comment]
Bug was fixed in #3588, small feature to be  reverted in #3595.
