### ISSUE TITLE
CMake warning CMP0053 with recent CMake and old Qt

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#3388]
## Issue Details

https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.14-Ic-14/Surface_mesh_Examples/TestReport_afabri_x64_Cygwin-Windows10_MSVC2013-Release-64bits.gz

I think the `CMP0053` should be handled just like in `examples/Triangulation_3/`.

Please fix in the release branch for 4.13.1.

**Comment by maxGimeno** [comment]
The policy in both CMakeLists.txt  is set in the exact same way. The only difference I see is the minimum required version of cmake. Could it be related ? Should we ask for 2.8.12 instead of 2.8.11 ?

**Comment by lrineau** [comment]
Fixed by #3391.
