### ISSUE TITLE
CMake Error with Polyhedron Examples on master

### ISSUE THREAD

**Issue by DABH** [CGAL/cgal#3400]
_Please use the following template to help us solving your issue._

## Issue Details

`cd ~/cgal/Polyhedron/examples/Polyhedron/`
`cmake .`
yields
```
-- __cplusplus is 201402
--   --> Do not link with Boost.Thread
-- Boost version: 1.62.0
-- Boost include dirs: /usr/include
-- Boost libraries:    
-- Build type: 
-- USING CXXFLAGS = ' '
-- USING EXEFLAGS = ' '
-- Targetting Unix Makefiles
-- Using /usr/bin/g++ compiler.
-- Requested component: Qt5
-- Requested component: MPFR
-- Requested component: GMP
CMake Error at CMakeLists.txt:36 (target_link_libraries):
  Cannot specify link libraries for target "draw_polyhedron" which is not
  built by this project.


-- Configuring incomplete, errors occurred!
```
on `master`.  If relevant, this is CMake 3.7.2 on latest macOS.  Though I agree with CMake here, I see no other mentions of that target name in the CMakeLists.  I would like to be able to successfully run this example!...

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Mac x64
* Compiler: clang
* Release or debug mode: Release
* Specific flags used (if any):
* CGAL version: master
* Boost version: 1.62.0
* Other libraries versions if used (Eigen, TBB, etc.): Qt5 is enabled so this example should compile and run...

**Comment by lrineau** [comment]
That target should be created from the line above:
```cmake
  # create a target per cppfile
  file(GLOB cppfiles RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} ${CMAKE_CURRENT_SOURCE_DIR}/*.cpp)
  foreach(cppfile ${cppfiles})
    create_single_source_cgal_program( "${cppfile}" )
  endforeach()
```

The `file(GLOB  )` command should find `draw_polyhedron.cpp` and then create that target.

**Comment by DABH** [comment]
Hmm.  Do you have any ideas how to debug this then?  All the targets build properly if `CGAL_Qt5_FOUND` is not set, but if it is, then I keep getting that same error for `draw_polyhedron`.  Perhaps it is something due to my particular environment (I'm getting same results on Linux x64 with g++ 6.3.0 and CMake 3.7.2), or maybe CMake doesn't like this "static" reference to the "dynamically" created target?  Happy to try to help get to the bottom of this if you have any advice...

**Comment by lrineau** [comment]
Do you have that file `~/cgal/Polyhedron/examples/Polyhedron/draw_polyhedron.cpp`?

**Comment by DABH** [comment]
Oh no, seems it had gotten deleted on my machine and somehow I was just being blind  My apologies for the stupid mistake!
