### ISSUE TITLE
Issues with Basic Viewer / Draw Surface Mesh

### ISSUE THREAD

**Issue by DABH** [CGAL/cgal#3401]
## Issue Details

I had a difficult time getting the Basic Viewer to compile in my project (a place for improvement of CGAL docs perhaps?  (like tell us which Qt libs we need to link etc....)).  But when I finally managed, and I attempted to draw a Surface Mesh, I got the following compiler errors:

```
/usr/local/include/CGAL/draw_surface_mesh.h:193:27: error: no match for ‘operator/’ (operand types are ‘double’ and ‘CGAL::Null_functor::result_type {aka CGAL::Null_tag}’)
               (normal, 1.0/CGAL::sqrt(normal.squared_length()))); }
(many "notes"...)
/usr/local/include/CGAL/number_utils.h:104:16: error: no match for call to ‘(CGAL::Algebraic_structure_traits<CGAL::Lazy_exact_nt<CGAL::Gmpq> >::Sqrt {aka CGAL::Null_functor}) (const CGAL::Lazy_exact_nt<CGAL::Gmpq>&)’
     return sqrt( x );
```

I'd really like to be able to draw my little mesh so any help would be appreciated!

## Source Code

Here's some relevant code:
```
    typedef CGAL::Exact_predicates_exact_constructions_kernel Kernel;
    typedef CGAL::Surface_mesh<Kernel::Point_3> Mesh;
    typedef CGAL::Point_3<Kernel> Point;

    Mesh m;
...add faces etc....
    CGAL::draw(m);
    exit(0);
```
Is the issue I'm using this Kernel which is breaking draw?  If so is there an easy way I can copy my mesh to another object using a different kernel, just for sake of drawing?  Anyway, according to the docs, I'm pretty sure this should work and is a bug...   Thanks for any help!!

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Linux x64
* Compiler: g++ 6.3.0
* Release or debug mode: Release
* Specific flags used (if any): CGAL_USE_BASIC_VIEWER is #define'd
* CGAL version: master
* Boost version: 1.62.0
* Other libraries versions if used (Eigen, TBB, etc.): Qt5

**Comment by lrineau** [comment]
I do not know if that code was already tested with the `Epeck` kernel. Guillaume, have you ever tried?

**Comment by DABH** [comment]
I also tried something like
```c++
typedef CGAL::Simple_cartesian<double> IK;
typedef CGAL::Cartesian_converter<Kernel,IK> EK_to_IK;
EK_to_IK to_inexact;
CGAL::draw(to_inexact(mesh));
```
but that doesn't compile, I'm guessing I'm doing the conversion incorrectly or it's not supported for surface meshes.

**Comment by gdamiand** [comment]
No I didn't test with epeck, my fault.
I will do a path soon.

**Comment by gdamiand** [comment]
Here the patch [PR3405](https://github.com/CGAL/cgal/pull/3405).
