### ISSUE TITLE
Centroid of Volume Bounded by Surface Mesh

### ISSUE THREAD

**Issue by DABH** [CGAL/cgal#3402]
## Issue Details

I have a surface mesh that represents a closed volume.  CGAL's PMP has a function to compute the volume inside the surface, but I see no obvious way to get the centroid of that volume.  Does this functionality exist in CGAL already, or if not, could it be considered as a feature request?  Based on https://stackoverflow.com/a/42726252/4451284 I think the code would look extremely similar to the volume function for surface meshes https://github.com/CGAL/cgal/blob/master/Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/measure.h#L499 .  For now I will probably just manually write such a function, unless someone knows of a better way.  Thanks for any pointers!

**Comment by MaelRL** [comment]
AFAIK there is no such function right now.

Could maybe added to https://github.com/CGAL/cgal/blob/master/Principal_component_analysis_LGPL/include/CGAL/centroid.h in the range of 3D triangles, with a 3D tag.

**Comment by DABH** [comment]
Cool.  I'm not super familiar with all of the CGAL internals, so I'm probably not the best person to implement this, but here is the function I wrote in my code to make this work (basically like the volume function I linked to above).  This was only for the specific kernel I'm using and uses some scalar/vector types in my code, so it would need to be generalized -- but the algorithm is there.
```cpp
Vec3 CGAL_Mesh_Centroid(const CGAL::Surface_mesh<CGAL::Exact_predicates_exact_constructions_kernel::Point_3>& mesh)
{
    typedef CGAL::Exact_predicates_exact_constructions_kernel Kernel;
    typedef Kernel::Point_3 Point;
    typedef CGAL::Surface_mesh<Point> Mesh;
    typedef Mesh::Face_index face_descriptor;

    Kernel::Compute_volume_3 cv3;
    auto vpm = get_const_property_map(CGAL::vertex_point, mesh);

    Vec3 centroid(0,0,0);
    T vol=0.;
    BOOST_FOREACH(face_descriptor f, mesh.faces())
    {
        std::vector<Point> points;
        points.push_back(Point(0, 0, 0));
        points.push_back(get(vpm, target(halfedge(f, mesh), mesh)));
        points.push_back(get(vpm, target(next(halfedge(f, mesh), mesh), mesh)));
        points.push_back(get(vpm, target(prev(halfedge(f, mesh), mesh), mesh)));
        CGAL::Tetrahedron_3<Kernel> t(points[0], points[1], points[2], points[3]);
        std::vector<CGAL::Tetrahedron_3<Kernel> > tets;
        tets.push_back(t);

        T vol_i = CGAL::to_double(cv3(points[0], points[1], points[2], points[3]));

        if(fabs(vol_i)>(T)0.){
            vol += vol_i;
            Point ci = CGAL::centroid(tets.begin(), tets.end(), CGAL::Dimension_tag<3>());
            Vec3 cip;
            cip(1)=CGAL::to_double(ci[0]);
            cip(2)=CGAL::to_double(ci[1]);
            cip(3)=CGAL::to_double(ci[2]);
            centroid += vol_i*cip;
        }
    }

    centroid *= (T)1./vol;
    return centroid;
}
```
