### ISSUE TITLE
Delaunay_triangulation_3 fails with negative coordinates

### ISSUE THREAD

**Issue by seb-tourneux** [CGAL/cgal#3415]
## Issue Details

Delaunay_triangulation_3 appears to fail when at least one of the input points has at least one negative coordinate. The triangulate output no finite_cell.
If I transform the input points so all of them have positive coordinates, the triangulation succeed.

I am using Delaunay_triangulation_3 with this templates arguments :
CGAL::Delaunay_triangulation_3<K, Tds>
using K = CGAL::Exact_predicates_inexact_constructions_kernel;
using Tds = CGAL::Triangulation_data_structure_3<
		CGAL::Triangulation_vertex_base_3<K>,
		CGAL::Triangulation_cell_base_3<K>,
		CGAL::Parallel_tag>

## Environment

* CGAL version: 4.11

**Comment by sloriot** [comment]
You need to provide more details, we triangulated a lot of point clouds and the fact that a coordinate is negative is usually not an issue :)

**Comment by seb-tourneux** [comment]
Ok, my bad, it was a bug in my code.
Sorry for bothering you, have a nice day.
