### ISSUE TITLE
CGAL demo issues / feature requests

### ISSUE THREAD

**Issue by MaelRL** [CGAL/cgal#3430]
## Issue Details
- [x] Using edition mode on a non-triangle mesh crashes because of is_degen_triangle().
- [x] If the surface_mesh_item is selected during a collapse_edge, the wrong edge is collapsed.
- [x] Reloading a c3t3 with children crashes the demo.
- [x] Deleting / Moving an item scrolls the item list back to the top.

- [x] Deletion changes the order of the items if those items have been moved in the list prior to that deletion.

- <s>Can't change the color of the tentative hole-filling mesh.</s>

- [x] Detect sharp features + mesh editing results in a lot of wrong colors + some caching issues (recomputing the detect sharp features just loads the same wrong colors).

- [x] Move point + scrollwheel crashes the demo.

- [x] The console message when you call `remove_degenerate_faces` is wrong (looks like it interprets a Boolean return type as a number of faces removed).

- [x] Euler operations' "split edges" should be "split edge".

- [x] Color items when a selection item is present colors everything gray (possibly the same problem as with polylines item?).

- <s> Selecting both the mesh and the selection hides indices.  </s> 

- [x] Load file, select an edge, reload both ---> crash

- [x] NaN in an input file makes the demo crash. Fixed in #3532

- [x] Operation filters shouldn't be based only on the lowest items but also on menus/submenus names (e.g. if you search "coref" with a single mesh, you don't get anything because this is a submenu and not an operation).

- [x] "Tick plugins you don't want to load at start up" --> no "don't"

- [x] Shift-clicking coordinates depend on the camera position (when using transparency).

- [x] Collision detection: test items have a "reload from file" but it does nothing.

- [x] The length of normals in the mode "Pts + Normals" seems messed up: it seems to scale down the normals assuming the normals from the file have length 1, which might not be the case. Might need a setting "real length / scaled length".

- [x] Move an item in the list, and, without deselecting it, shift-click to another item to get a range. The result is not what is expected.

- [x] Using the operation search function and clearing the search results in missing operations whereas everything should be back.

- [x] Flip-edge selection (for example) is still visible after closing the selection widget.

- [x] "Look at" while the mesh is in a continuous rotation makes funky movements (just stop the rotation, I guess).

- [x] Degenerate triangles in an .OFF file (e.g. two points +  `3 0 1 0`) make the demo crash. see #3531 

- [x] `Set different colors` for a bunch of polylines use very dark colors hardly distinguishable.

- [x] Changing the transparency sucks all the RAM in before crashing.

- [x] Line thickness (and probably other things) do not actualize until camera moves.

- [x] The demo crashes when trying to load [this](https://gist.github.com/MaelRL/0d4da0f4a3a5b40867f18e84012b1746) (admittedly, it's an abomination and probably fails to triangulate its faces... but it shouldn't crash).

- [x] Some parameterizers, when failing, do not restore cursor properly (my bad, most likely...).

- [x] Fails to open [this file](https://gist.github.com/MaelRL/843a3be96f2d4256ca4ba348cb6d6150).

---
Some feature requests (developped in #3355 for convenience):

- [x] Add a Polygon generator that creates a polyline in Z=0 from 2D coords of a polygon. Don't forget to add the last point = the first point.

- [x] Be able to manipulate and save parameterization's UV mesh.
- <s> Add "is_valid_pm()" to statistics + a way to visualize non-valid parts?</s>
- [x] The selection of vertices/edges/faces could show the same highlighting (yellow-ish) than when using the edition mode.

- [x] Would be neat to have a "revert last operation" for all (or just some of) the Euler operations.
- [x] Change the thickness of multiple polylines items at a time (and other similar properties for similar items...).
- [x] It would be nice to be able to move multiple items up and down (at once) in the list of items.

**Comment by maxGimeno** [comment]
The two last ones are already done in #3225 .

**Comment by sloriot** [comment]
@MaelRL @maxGimeno  please reopen the issue if #3325 did not fix it completely.

**Comment by sloriot** [comment]
Got my answer, requires #3423.

**Comment by MaelRL** [comment]
I missed it in #3225 so I didn't give any feedback there, but I don't find the research function optimal: although it filters within the submenus, which is nice, one still has to navigate the menus to the desired action. Example: I type `degenerate` to remove degenerate faces, I still have to follow PMP > etc > etc > etc > remove degenerate faces. So, it basically saves (me) no time in the current version.

**Comment by maxGimeno** [comment]
> * `.xyz` with normals should open with normals showing (and not just points) by default.

Simon specifically asked me for the opposite, that's why I changed it. Actually it shows in shaded points mode. Furthermore, there is an option in the Preferences that lets you choose the default rendering mode for point sets.

**Comment by MaelRL** [comment]
I had seen the option, but I thought it'd make more sense to have that by super-default. I don't have a strong opinion on the subject so I withdraw that point :).

**Comment by maxGimeno** [comment]
> Show Vertex indices on mesh, load selection file, hide mesh, indices are still shown.

Where is the problem ? You want to filter only those on the selection item ?

**Comment by MaelRL** [comment]
IIRC, I mean "hiding both the mesh and the selection, indices are still showing."

**Comment by maxGimeno** [comment]
Nope, hiding both hides the indices.  Actually only the displayed indices for the selected item OR its associated selection item are showing, so you setill have your IDs when you work your selection.

**Comment by MaelRL** [comment]
Right, just hiding the mesh shows all the indices on top of the selection, which looks a bit strange. I don't have any preference about whether it should show everything or only the selection, it's fine as it is. 

Selecting both the mesh and the selection hides indices, though, which doesn't seem correct.

**Comment by MaelRL** [comment]
Last merge into master broke shift+clicking for point coordinates and it seems to now depend on the camera position.

**Comment by maxGimeno** [comment]
What do you mean ? I just tried and it looks fine to me. Can you be more specific ?

**Comment by maxGimeno** [comment]
>  Can't change the color of the tentative hole-filling mesh.
There is no such a thing. The tentative to fill the hole fills the hole. Then if you want to discard the patch, it removes the new faces. Furthermore, there is no new item in the list when you fill the holes, only the vizualizer. 
Is this a feature request or a misunderstanding of the plugin ?

**Comment by maxGimeno** [comment]
> Detect sharp features + mesh editing results in a lot of wrong colors + some caching issues (recomputing the detect sharp features just loads the same wrong colors).

When I re-compute the features I get the right colors. Editing a colored mesh will ALWAYS give you "wrong colors". The best I could do is compute some sort of medium color from the neighbors, but it will still be wrong for a lot of cases.

**Comment by maxGimeno** [comment]
> Move point + scrollwheel crashes the demo.

I don't reproduce. Is it still there for you ?

**Comment by MaelRL** [comment]
> Is this a feature request or a misunderstanding of the plugin ?

I assumed the result of the hole filling was stored in that because its color was blue, but it's actually referring to the red edge selection... So yeah, "misunderstanding the plugin".

> Editing a colored mesh will ALWAYS give you "wrong colors"

They could be de-activated, or re-computed, or something else... Surely there is something better than the mesh turning into Harlequin.

**Comment by maxGimeno** [comment]
>Color items when a selection item is present colors everything gray (possibly the same problem as with polylines item?).

I don't reproduce. Is this still in master ?

**Comment by maxGimeno** [comment]
>Selecting both the mesh and the selection hides indices.

Selecting more than one item hides the ids. it is expected behavior, I'm not sure it is worth it to modify the whole system to add an exception for the selection item. It is not that trivial.

**Comment by MaelRL** [comment]
Recompiled after yesterday's pushes and:
- Can't hide/show items without the camera changing positions, which makes it really tedious to inspect meshes with multiple parts;
- Changing the transparency sucks all the RAM in before crashing.

**Comment by maxGimeno** [comment]
You have an option in the Preferences for the visibility I believe. I'll look into the transparency.

**Comment by maxGimeno** [comment]
> Line thickness (and probably other things) do not actualize until camera moves. 

I don't reproduce

**Comment by maxGimeno** [comment]
> Degenerate triangles in an .OFF file (e.g. two points + 3 0 1 0) make the demo crash.

The bug is in surface_mesh, I'll create a dedicated issue.

**Comment by maxGimeno** [comment]
>Add "is_valid_pm()" to statistics + a way to visualize non-valid parts?

I am not sure this is useful. I don't see how e can get an invalid polygon mesh in the demo.

**Comment by maxGimeno** [comment]
>The selection of vertices/edges/faces could show the same highlighting (yellow-ish) than when using the edition mode.

What would be the point ? I did it for the edition part to avoid modifying the mesh in an unwanted way, but the selection is easily reversable. Plus this highlighting comes with a cost, so I don't think that's such a good idea.

**Comment by maxGimeno** [comment]
It would certainly make things easier
