### ISSUE TITLE
Core Memory pool: destruction order of static objects

### ISSUE THREAD

**Issue by HoffmannMichael** [CGAL/cgal#3432]
## Issue Details

Something seems to go wrong with the destruction order of objects in the memory pool implementation. Running the code below prints `N4CORE14ConstDoubleRepE` on stderr, which is triggered by `MemoryPool<>::free()` in case that `blocks` is empty. If building in debug mode, the assertion in the next line would be triggered.

The issue appears only with static objects, if the variable i is declared within main, things are fine. When removing the four `|| (defined(CGAL_HAS_THREADS)&&__GNUC__)` conditionals in `CORE/MemoryPool.h`, things seem fine as well.

## Source Code
```
#include <CGAL/Exact_predicates_exact_constructions_kernel_with_sqrt.h>

CGAL::Exact_predicates_exact_constructions_kernel_with_sqrt::FT i;

int main() { return 0; }
```
## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Linux (Red Hat 8.1.1-5)
* Compiler: g++ (GCC) 8.1.1 20180712 
* Release or debug mode:
* Specific flags used (if any): g++ -Wall -O3 -frounding-math -g -DNDEBUG -pthread -static -pipe -xc++ -std=c++11 -o program source -lCGAL -lCGAL_Core -lboost_thread -lboost_system -lmpfr -lgmp
* CGAL version: 4.11.1
* Boost version: 1_66
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by lrineau** [comment]
Michael, CGAL-4.11 is no longer supported. Do you have the same issue with CGAL-4.13 or CGAL-4.14?
