### ISSUE TITLE
Can't add a new face when two of the vertices are already part of one

### ISSUE THREAD

**Issue by aseverino** [CGAL/cgal#3442]
I'm trying to add a new face where `closest_vert` and `second_closest_vert` are already part of a valid `Surface_mesh` structure. They are border vertices, connect only to a face in the mesh.

When I try to connect them with `verts[0]` (which is an **isolated vertice**) to form a new triangle, I receive a `null_face` as a result.

`m_out.add_face(closest_vert, second_closest_vert, verts[0]);`

* CGAL version: 4.13

**Comment by sloriot** [comment]
Did you check that the orientation is valid? That is the call is correct and should not be `m_out.add_face(second_closest_vert, closest_vert, verts[0]);` ?
If `h` is a border halfedge, the call should be `m.add_face(source(h, m), target(h,m), m verts[0])`.

I'm closing the issue, please reopen it if you are still observing a bug. For reference I'm adding a test program.

```
#include <iostream>
#include <CGAL/Simple_cartesian.h>
#include <CGAL/Surface_mesh.h>

typedef CGAL::Simple_cartesian<double> K;
typedef K::Point_3 Point_3;

typedef CGAL::Surface_mesh<Point_3> Mesh;

int main()
{
  Mesh mesh;
  CGAL::make_triangle(Point_3(0,0,0), Point_3(1,0,0), Point_3(1,1,1), mesh);
  
  for(Mesh::Halfedge_index  h : mesh.halfedges())
  {
    if ( is_border(h, mesh) )
    {
      Mesh::Vertex_index v = mesh.add_vertex();
      Mesh::Face_index f = mesh.add_face(source(h, mesh), target(h, mesh), v);
      assert(f!=mesh.null_face());
      break;
    }
  }
  
  assert(num_faces(mesh)==2);
  return 0;
}
```
