### ISSUE TITLE
Non working links in documentation.

### ISSUE THREAD

**Issue by albert-github** [CGAL/cgal#3453]
## Issue Details 1
When looking at e.g. https://cgal.geometryfactory.com/CGAL/doc/master/AABB_tree/group__PkgAABBTreeRef.html

![main](https://user-images.githubusercontent.com/5223533/48411515-00147a80-e742-11e8-863b-7b6ab4f5c7a9.png)

And selecting in the dropdown box e.g. 4.12 we get

> Not Found
> 
> The requested URL /4.12/AABB_tree/group__PkgAABBTreeRef.html was not found on this server.

The same accounts for the other possibilities (except master) in this drop down box.

## Issue Details 2
When looking on the same page to the block:
![links](https://user-images.githubusercontent.com/5223533/48411686-9183ec80-e742-11e8-8269-1843769f59d9.png)
The links:
> Windows Demo: AABB Tree
> Common Demo Dlls: dlls

are dead. Here the cause might be 2-sided (based on the content of https://www.cgal.org/demo/):
 - missing  directories / links for e.g. 4.13, 4.14 and latest
 - missing examples on the right place.

**Comment by lrineau** [comment]
I have fixed the second issue, with commit https://github.com/CGAL/cgal-web/commit/f17f4cff098a296f22f3e0a0d75de105fb00f43b (in our web server).

We have redirections, so that when you ask for the demos of 4.14, then you get the latest version that was uploaded.

**Comment by sloriot** [comment]
For issue 1 it is expected as I renamed the groups for all the packages:
It used to be https://doc.cgal.org/4.12/AABB_tree/group__PkgAABB__tree.html

For the issue 2, I don't have dead links, maybe @lrineau already fixed them.

**Comment by lrineau** [comment]
@sloriot What do you propose to fix the first issue? Do you have in mind what kind of redirection scheme we should use?

**Comment by albert-github** [comment]
Thanks.
You are much faster than I'm.
When will it be visible on the site?

**Comment by lrineau** [comment]
[**@albert-github**](https://github.com/albert-github) commented on [Nov 13, 2018, 1:05 PM GMT+1](https://github.com/CGAL/cgal/issues/3453#issuecomment-438243003 "2018-11-13T12:05:13Z - Replied by Github Reply Comments"):
> When will it be visible on the site?

It is, already, but your cache may not allow you to see that.

With curl we can see the redirection:
```
% curl -I https://www.cgal.org/demo/4.14/AABB_demo.zip 
HTTP/1.1 302 Found
Set-Cookie: 300gpBAK=R4178757645; path=/; expires=Tue, 13-Nov-2018 13:22:27 GMT
Date: Tue, 13 Nov 2018 12:10:56 GMT
Content-Type: text/html; charset=iso-8859-1
Set-Cookie: 300gp=R393557482; path=/; expires=Tue, 13-Nov-2018 13:31:42 GMT
Server: Apache
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
Location: https://www.cgal.org:443/demo/4.13/AABB_demo.zip
X-IPLB-Instance: 5021
```
The redirection is the code `302` and the `Location:` field.

**Comment by albert-github** [comment]
I did a quick test and I can load the 2 mentioned zip files (Issue 2), thanks.

**Comment by albert-github** [comment]
I looked into the file: `Documentation/doc/resources/1.8.14/menu_version.js` and saw:
  `var current_version_local = '4.13-beta1'`
is this correct as it does not appear in the list underneath it.

Same accounts for the `1.8.4` and `1.8.13` versions.

**Comment by sloriot** [comment]
I've installed the redirect from 4.14+ -> earlier releases.
For the other way round I'll update #3361 with how to update it (as the doc is not hosted on the same server).

I guess we can close this issue now. Feel free to reopen it if I missed something.
