### ISSUE TITLE
Problematic external links in documentation (non literature)

### ISSUE THREAD

**Issue by albert-github** [CGAL/cgal#3457]
Ran a link check over the resulting documentation, from master, regarding inconsistencies / errors.
There are different categories of problems. 
This issue is regarding external link problems (non literature  as for this issue #3455 has been submitted). It is possible that a number of issues (like boost, wikipedia) are present a number of times as the source is used on multiple places.

Other problems(like doxygen problems) I'm investigating.

Find attached an overview of the non literature problematic links.

[links_non_literature.txt](https://github.com/CGAL/cgal/files/2585846/links_non_literature.txt)

**Comment by afabri** [comment]
As far as boost is concerned we do not link to a specific release, but prefer to get redirected to the latest one.

**Comment by albert-github** [comment]
Regarding boost (and other redirect to versions) I can imagine that the current approach is better.
The other redirects (http -> https) is in my opinionsomething different and should be fixed.
