### ISSUE TITLE
Incorrect reference in documentation.

### ISSUE THREAD

**Issue by albert-github** [CGAL/cgal#3458]
Running a link check I get the following mesage:

> Processing      file:///cygdrive/d/Programs/CGAL/cgal/build_official/doc_output/Three/group__PkgThreeRef.html
> 
> 
> List of broken links and other issues:
> file:///cygdrive/d/Programs/CGAL/cgal/build_official/doc_output/Manual/how_to_cite_cgal.html
>  Lines: 72, 154
>   Code: 200 (no message)
>  To do: Some of the links to this resource point to broken URI fragments
>         (such as index.html#fragment).
> The following fragments need to be fixed:
>         cgal:rlfg-pd-18b                Line: 154
> 

The link on line 154 of the file `group__PkgThreeRef.html` points into thin air  as the `#cgal:rlfg-pd-18b` does not exist in the file `how_to_cite_cgal.html` it just goes to `how_to_cite_cgal.html`.

**Comment by lrineau** [comment]
That piece of documentation (about `Three`) is experimental, and should not be in the CGAL documentation.

But, anyway, Maxime @maxGimeno, the issue pointed by @albert-github seems easy to fix.

**Comment by lrineau** [comment]
[**@albert-github**](https://github.com/albert-github) commented on [Nov 16, 2018, 10:02 AM GMT+1](https://github.com/CGAL/cgal/issues/3458#issuecomment-439327057 "2018-11-16T09:02:54Z - Replied by Github Reply Comments"):
> A similar issue might be the problems mentioned  in the attachment: [how.txt](https://github.com/CGAL/cgal/files/2588580/how.txt)
> 
> (When necessary I can submit a separate issue).

I should redirect `https://doc.cgal.org/4.14` to `https://doc.cgal.org/master`.

**Comment by lrineau** [comment]
[**@lrineau**](https://github.com/lrineau) commented on [Nov 16, 2018, 10:11 AM GMT+1](https://github.com/CGAL/cgal/issues/3458#issuecomment-439329127 "2018-11-16T09:11:10Z - Replied by Github Reply Comments"):
> [**@albert-github**](https://github.com/albert-github) commented on [Nov 16, 2018, 10:02 AM GMT+1](https://github.com/CGAL/cgal/issues/3458#issuecomment-439327057 "2018-11-16T09:02:54Z - Replied by Github Reply Comments"):
> > A similar issue might be the problems mentioned  in the attachment: [how.txt](https://github.com/CGAL/cgal/files/2588580/how.txt)
> > 
> > (When necessary I can submit a separate issue).
> 
> I should redirect `https://doc.cgal.org/4.14` to `https://doc.cgal.org/master`.

That is done.

**Comment by lrineau** [comment]
[**@albert-github**](https://github.com/albert-github) commented on [Nov 16, 2018, 10:28 AM GMT+1](https://github.com/CGAL/cgal/issues/3458#issuecomment-439333993 "2018-11-16T09:28:40Z - Replied by Github Reply Comments"):
> Problems are of course all the redirects that one has to create in case of a new release / version as the files are generated, in the cmake part of process, wouldn't there be a possibility to have the version set properly here?

Please explain what you suggest. What do you mean by *have the version set properly*?

**Comment by albert-github** [comment]
Indeed maybe a bit cryptic.

In the file `how_to_cite.html.in`, we see the section:

> @book{<a href="how_to_cite_cgal.html#cgal:eb-${CGAL_RELEASE_YEAR_ID}">cgal:eb-${CGAL_RELEASE_YEAR_ID}</a>,
>   title = {{CGAL} User and Reference Manual},
>   author = {{The CGAL Project}},
>   publisher = {{CGAL Editorial Board}},
>   edition = {{${CGAL_CREATED_VERSION_NUM}}},
>   year = ${CGAL_BUILD_YEAR4},
>   url = {<a href="https://doc.cgal.org/${CGAL_CREATED_VERSION_NUM}/Manual/packages.html">https://doc.cgal.org/${CGAL_CREATED_VERSION_NUM}/Manual/packages.html</a>}
> }

The interesting part here is: `https://doc.cgal.org/${CGAL_CREATED_VERSION_NUM}/Manual/packages.html` and probably especially `${CGAL_CREATED_VERSION_NUM}`.

In the file `how_to_cite.html` this is translated into: `https://doc.cgal.org/4.14/Manual/packages.html`. When drawn from the master branch this could be set properly to `master` and in case of a release one has to create a git branch and draw from this git-brach, adjust the version number corresponding to the branch. This would be something in the release procedure of CGAL (and is an internal decision / situation for you) but I assume that before the release such a branch is created on which the final tests / fixes are made before the release. In this way the different versions are separated and it is possible that no links (with the risk of unintentionally overwriting files during a build!) remain.

I hope this gives some more insight in my cryptic first description, otherwise please don't hesitate to drop an other line.

**Comment by lrineau** [comment]
Actually, `master` is a branch that can be published as a release at any time, or at least it should be that way. That is why the documentation of `master` fakes to be the documentation or CGAL-4.14. In my opinion the redirection is the right way to do. Could you be more specific about why you see the redirection as a problem?

**Comment by albert-github** [comment]
In respect to redirection I'm thinking about the *nix concept of soft links. Not sure if this is the same redirection as you are talking about.

It is of course all in the deployment process, as soon as a branch is released the documentation should not be updated from master anymore and master should update to the documentation in the 'next' directory, when something is wrong in deployment process this might not happen (and the deployment process of course is faulty and should be corrected).

**Comment by MaelRL** [comment]
Seems like the initial issue is similar to https://github.com/CGAL/cgal/issues/4635 (and fixed by the same PR? @sloriot)

@lrineau What's the status with respect to the redirection discussion?

**Comment by sloriot** [comment]
It should indeed by solve by #4643. I linked it.
