### ISSUE TITLE
2d delaunay triangulation generates TIN（Triangulated Irregular Network） too slow !

### ISSUE THREAD

**Issue by liang-god** [CGAL/cgal#3483]
I have 8 million points, and I want to generate the TIN. 
so, I use the 2d delaunay triangulation.
Unexpectedly, it takes me 180 seconds! 
Is there any way can speed_up?

this is my code:
```c++
typedef CGAL::Projection_traits_xy_3<Kernel>                                  P_xy_3_traits;
typedef CGAL::Triangulation_vertex_base_with_info_2<unsigned, P_xy_3_traits>  Vb;
typedef CGAL::Triangulation_data_structure_2<Vb>                              Tds;
typedef CGAL::Delaunay_triangulation_2<P_xy_3_traits,Tds>                     Delaunay_2;
```

**Comment by afabri** [comment]
Can you put the complete program on gist.github.com. And share the data set?

**Comment by afabri** [comment]
What is Kernel ? Do you use ` CGAL::Exact_predicates_inexact_constructions_kernel` ?

**Comment by liang-god** [comment]
> What is Kernel ? Do you use ` CGAL::Exact_predicates_inexact_constructions_kernel` ?

YES,It is!

**Comment by lrineau** [comment]
- What are the compilation flags that were used to compile the code? (I hope the optimizations are activated.)
- Note that the Delaunay triangulation code is a lot slower for data sets organized on a 2D regular grid (because of the degeneracy as regards to the in-circle predicate).

**Comment by afabri** [comment]
For 1mio random points with the projection traits it takes 1.2 sec and if they are on a grid 2.5.  I still have to check with the zip iterator.

**Comment by liang-god** [comment]
This is the image..
![image](https://user-images.githubusercontent.com/29827175/49075723-515c5800-f272-11e8-892d-eb7d40f1c997.png)

**Comment by afabri** [comment]
So, the performance is ok now?

**Comment by liang-god** [comment]
> So, the performance is ok now?

30 seconds when I activate optimizations
