### ISSUE TITLE
Undefined references using CGAL::draw()

### ISSUE THREAD

**Issue by chringer** [CGAL/cgal#3484]
## Issue Details

I'm trying to use the new `CGAL::draw()` method in my lib for a `CGAL::Triangulation_2`. I define `CGAL_USE_BASIC_VIEWER` and link successfully against CGAL_Qt5 and Qt5 as shown by `ldd`:

> user@pc:path$ ldd libMyLib.so | grep "libCGAL"
> 	libCGAL_Qt5.so.13 => /my_path/libCGAL_Qt5.so.13 (0x00007fab6a2bb000)
> 	libCGAL.so.13 => /my_path/libCGAL.so.13 (0x00007fab6a09f000)
> user@pc:path$ ldd libMyLib.so | grep "libQt5"
> 	libQt5Xml.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Xml.so.5 (0x00007f0894d14000)
> 	libQt5Script.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Script.so.5 (0x00007f08802ea000)
> 	libQt5OpenGL.so.5 => /usr/lib/x86_64-linux-gnu/libQt5OpenGL.so.5 (0x00007f0894cb8000)
> 	libQt5Svg.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Svg.so.5 (0x00007f0894c62000)
> 	libQt5Sql.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Sql.so.5 (0x00007f0894c17000)
> 	libQt5Widgets.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5 (0x00007f08715cf000)
> 	libQt5Gui.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5 (0x00007f0871096000)
> 	libQt5Core.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Core.so.5 (0x00007f0870bc7000)
> 	libQt5X11Extras.so.5 => /usr/lib/x86_64-linux-gnu/libQt5X11Extras.so.5 (0x00007f0894be3000)

When compiling my lib, however, I get the following linker errors:
> ../libMyLib.so.1.0.0: undefined reference to 'CGAL::QGLViewer::wheelEvent(QWheelEvent*)'
> ../libMyLib.so.1.0.0: undefined reference to 'CGAL::QGLViewer::postDraw()'
> ../libMyLib.so.1.0.0: undefined reference to 'CGAL::QGLViewer::setKeyDescription(unsigned int, QString)'
> ../libMyLib.so.1.0.0: undefined reference to 'CGAL::QGLViewer::initializeGL()'
> .... 
> collect2: error: ld returned 1 exit status

There are many more of such undefined references, all related to `CGAL::QGLViewer`.

Do I need to link against another (not documented) library? Thank you very much!

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Debian x64
* Compiler: g++ 6.3.0
* Release or debug mode: both
* Specific flags used (if any): `CGAL_USE_BASIC_VIEWER` 
* CGAL version: 4.13
* Boost version: 1.62.0
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by gdamiand** [comment]
There is no need of additional libraries, all these methods are supposed to be defined in libCGAL_Qt5.

For example when I do <code>nm libCGAL_Qt5.so.13.0.2|grep postDraw</code> in my computer, I found <code>0000000000089cf6 T _ZN4CGAL9QGLViewer8postDrawEv</code>.

**Comment by chringer** [comment]
Oh, indeed, I can confirm this is the case here as well:
> 000000000004fb10 T _ZN4CGAL9QGLViewer8postDrawEv

Mh. Now I'm totally confused.

**Comment by lrineau** [comment]
Can you please give the command line that the build system uses to link, and the full error log?

**Comment by chringer** [comment]
I'm currently investigating an issue, my lib seems to link both against CGAL versions 13.0.0 and 13.0.2. I'll come back after having seen into this in more detail.

**Comment by chringer** [comment]
I can now confirm that some old CGAL version was mixed into the build and caused the undefined references. Probably an old, installed CMake file of CGAL caused the errors; but I'm not really sure about this. Nevertheless, getting rid of all old CGAL versions and my build folder helped. Sorry about this and thanks for your fast help!
