### ISSUE TITLE
Boost in the developer manual

### ISSUE THREAD

**Issue by MoniqueTeillaud** [CGAL/cgal#35]
Fix (/remove) the section about Boost in the developer manual
http://doc.cgal.org/latest/Manual/devman_portability.html
(the list is not available)

**Comment by bo0ts** [comment]
I've compiled a list of all our boost includes and based on that a list of currently used Boost libraries [in a Gist](https://gist.github.com/bo0ts/dacb1a3100c49ea050d8#file-library-list). There are a few oddballs left which should not end up on a list of auto-allowed libraries and I've reviewed some of the more exotic includes and fixed them in a pending pull request.

**Comment by lrineau** [comment]
Should not it be discuss (again) at next developers meeting? Will Philipp be invited?

**Comment by bo0ts** [comment]
To me a discussion does not seem necessary. I think we agree that a list of default allowed Boost libraries is a good idea and we should be open to allow new libraries one a case-by-case basis.

A reasonable list would be:

- Algorithm
- Any
- Array
- Assign
- Bimap
- Bind
- Config
- Container
- Dynamic Bitset
- Foreach
- Format
- Function
- Graph
- Intrusive
- Iterator
- Lexical
- Tribool
- Math
- Member Function
- MPL
- Multi Array
- Multi Index
- Numeric
- Operators
- Optional
- Parameter (only when already used)
- Preprocessor
- Program Options (Demo Only)
- Property Map
- Pointer Container
- Random
- Range
- Ref
- Smart Pointers
- Static Assert
- Thread
- Timer
- Tuple
- Type Traits
- Unordered
- Utility
- Variant

Everything with a question mark is up for discussion. Entirely cosmetic libraries like Assign and Foreach but should be restricted to tests and examples only.

There are some places where we (I) use Boost.Test but it is such a pain on Windows that I can't recommend it to anyone.

**Comment by lrineau** [comment]
I think there should be a second list for Boost libraries that we allow to appear in the API of a CGAL component (such as Boost.Variant, Boost.Any). Because once a third-party library appears in the API, we cannot maintain the backward-compatibility in case there is a real issue with the third-party library.

**Comment by bo0ts** [comment]
That would be

- Any
- Array
- Function
- Graph
- Tribool (only one place, drop it)
- Optional
- Parameter (only when already used)
- Property Map
- Range
- Smart Pointers
- Tuple
- Utility
- Variant

**Comment by sloriot** [comment]
See #503

**Comment by lrineau** [comment]
The PR #503 has mixed up the set of Boost libraries that can be used internally to CGAL code, and the set of Boost libraries that can be used in the public API of CGAL.

Example: that is alight to Boost.Format in CGAL (such as in my current work, to format messages), but it cannot appear in the API.

**Comment by lrineau** [comment]
Should be a working group at the next develop meetings.
