### ISSUE TITLE
Exception thrown in PMP::remove_self_intersections

### ISSUE THREAD

**Issue by shareq2005** [CGAL/cgal#3504]
_Please use the following template to help us solving your issue._

## Issue Details

The issue is that PMP::remove_self_intersections runs into an exception.

Steps:
1. I have two intersecting closed surfaces, "Greenstone" and "Regolith", which have no self-intersections.
 2. I computed the difference of these two surfaces using PMP::corefine_and_compute_difference (Greenstone - Regolith). 
3. The CGAL kernel I used was Exact_predicates_inexact_constructions. Since I used this kernel, the resulting surface has a few precision related self-intersections. Now, to fix these self-intersections, I used the PMP::remove_self_intersections, which runs into an exception.

Here are the surface files:
- *Greenstone* - https://drive.google.com/file/d/19qhBtYF_gG07GBdgvlsTVTCywgKyK-yX/view?usp=sharing
- *Regolith* - https://drive.google.com/file/d/1bNiUr8ZEst6ZAGFH7heZ-7jI-GocHplc/view?usp=sharing
- *Greenstone cut by regolith* - This is the surface which is the result of corefine_and_compute_difference. This is the input surface that I pass onto PMP::remove_self_intersections. https://drive.google.com/file/d/1bNiUr8ZEst6ZAGFH7heZ-7jI-GocHplc/view?usp=sharing

## Source Code
```

#include "stdafx.h"
#include <fstream>

#include <CGAL/Surface_mesh.h>
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/Polygon_mesh_processing/repair.h>
#include <CGAL/Polygon_mesh_processing/corefinement.h>

typedef CGAL::Exact_predicates_inexact_constructions_kernel K;
typedef CGAL::Surface_mesh<K::Point_3> Mesh;
typedef Mesh::Vertex_index Vertex_index;
namespace PMP = CGAL::Polygon_mesh_processing;

int _tmain(int argc, _TCHAR* argv[])
{
   short sCheckErr = 0;
   
   Mesh cgal_mesh_1, cgal_mesh_2, cgal_mesh_out;

   std::ifstream stream1("M:\\test\\greenstone.off");
   CGAL::read_off(stream1, cgal_mesh_1);

   std::ifstream stream2("M:\\test\\regolith.off");
   CGAL::read_off(stream2, cgal_mesh_2);

   bool valid = true;
   if (!PMP::corefine_and_compute_difference(cgal_mesh_1, cgal_mesh_2, cgal_mesh_out))
      valid = false;

   if (valid) {
      if (PMP::does_self_intersect(cgal_mesh_out)) {
         PMP::remove_self_intersections(cgal_mesh_out);
      }
   }

   return sCheckErr;
}
```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows 64 bits
* Compiler: MSVC Visual Studio 2017
* Release or debug mode: Debug & Release
* Specific flags used (if any): 
* CGAL version: 4.13
* Boost version: 1.68
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by sloriot** [comment]
The error is due to a self-intersection in the input. If you update your code with:

```
   bool valid = true;
   try{
     valid = PMP::corefine_and_compute_difference(cgal_mesh_1, cgal_mesh_2, cgal_mesh_out,
                                                  CGAL::parameters::throw_on_self_intersection(true));
   }
   catch(CGAL::Polygon_mesh_processing::Corefinement::Self_intersection_exception)
   {
     bool all_fixed = PMP::remove_self_intersections(cgal_mesh_1);
     all_fixed &= PMP::remove_self_intersections(cgal_mesh_2);
     if (all_fixed)
       valid = PMP::corefine_and_compute_difference(cgal_mesh_1, cgal_mesh_2, cgal_mesh_out);
     else
       std::cerr << "Some self-intersections could not be fixed\n";
   }

   if (valid) {
    PMP::remove_self_intersections(cgal_mesh_out);
   }
   else
     std::cout << "Output is non-manifold and was not computed.\n";
```
You won't have the error (but the output is non-manifold and nothing will be computed).
