### ISSUE TITLE
is_plane is named is_sphere in the documentation.

### ISSUE THREAD

**Issue by cedricpradalier** [CGAL/cgal#3505]
This is an obvious typo, the function has been copy-pasted from the planar Nef package. It should be renamed is_sphere()

https://github.com/CGAL/cgal/blob/84151fe9b3614b0e6387ac8316d47fc92809ab6b/Nef_S2/include/CGAL/Nef_polyhedron_S2.h#L342

**Comment by lrineau** [comment]
Fixed by #3510.
