### ISSUE TITLE
D.shalfoop()->twin() = true;  Should it be '=='?

### ISSUE THREAD

**Issue by cedricpradalier** [CGAL/cgal#3506]
I am not sure about this one the types are inconsistent, so it looks like a missing '==' sign. Don't hesitate to close it if this is wrong.

https://github.com/CGAL/cgal/blob/b02d174ef2a5f6a930549bd3a098bb84a557b190/Nef_S2/include/CGAL/Nef_polyhedron_S2.h#L393

**Comment by lrineau** [comment]
Fixed by #3510.
