### ISSUE TITLE
Undefined control sequence in documentation of Bounding_volumes

### ISSUE THREAD

**Issue by albert-github** [CGAL/cgal#3522]
Undefined control sequence in documentation of Bounding_volumes

In the file:
```
../Bounding_volumes/doc/Bounding_volumes/CGAL/Approximate_min_ellipsoid_d.h
```
the commands `\vol` and `\mel` are used, resulting in

> Undefined control sequence

in
```
doc_output/Bounding_volumes/classCGAL_1_1Approximate__min__ellipsoid__d.html
```

The substitutions / form of the symbol to be used is unknown to me.

**Comment by lrineau** [comment]
Fixed by #3525, in the releases branches for 4.12.2, 4.13.1, and in `master`.
