### ISSUE TITLE
Improvements to be done for CGAL CMake scripts

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#3529]
## Issue Details

@afabri and [Max Lyon] (not on Github) showed me how hard it can be to configure the polyhedron demo of CGAL, on Windows.

[Max Lyon]: https://www.graphics.rwth-aachen.de/person/99/

### Various issues
- [x] `FindTBB` displays a message starting with `ERROR: `, for messages that are just warnings. It should check the variables `TBB_FIND_REQUIRED` and `TBB_FIND_QUIET`, and display messages accordingly.
- [x] Qt5 is hard to configure. If CMake does not auto-detect the install of Qt5, that is rather difficult to understand how should the CMake variable `Qt5_DIR` be filled. It is not the root of the installation of Qt5 on Windows.
- [ ] GMP/MPFR: if one uses a version of CGAL installed by the CGAL Windows installer, that is fine, but as soon as you use a git checkout of CGAL, things get complicated.
- [x] Boost... Boost installation layout is strange, on Windows. It is not strait forward to know what to fill in CMake.

### Various proposals

- All CGAL `CMakeLists.txt` should start with `find_package(CGAL REQUIRED)`, before any other `find_package`, so that CMake forces the users to first configure the path to `CGAL_DIR`. That would ensure that `CGALConfig.cmake` (and all the CGAL CMake machinery) is already included for all the remaining lines of the `CMakeLists.txt`.
- That way, we could fill `CMAKE_PREFIX_PATH` with the known standard installation paths for Qt5 and Booost.
- I also suggest that the `else()` sections of our `CMakeLists.txt` explain how to configure the missing dependencies. That could probably be easily done with the usage of the [`FeatureSummary`] module of CMake. OpenFlipper [already uses it](https://bitbucket.org/fenics-project/dolfin/pull-requests/275/use-cmakes-featuresummary-for-generating-a/diff).

[`FeatureSummary`]: https://cmake.org/cmake/help/v3.13/module/FeatureSummary.html

**Comment by lrineau** [comment]
@maxGimeno Can you have a look at this issue? It seems interesting. Maybe some of the points are already solved, but the others would be nice to fix. Let me know what you think of them...

**Comment by maxGimeno** [comment]
Well that seems like a bunch of very good ideas ! I'll look into it.

**Comment by lrineau** [comment]
@maxGimeno Is #4243 a full fix for this issue? It seems there are items not checked, in the top message.

**Comment by maxGimeno** [comment]
I'm not entirely sure for `That way, we could fill CMAKE_PREFIX_PATH with the known standard installation paths for Qt5 and Booost.`. The two other points are clearly addressed.

**Comment by lrineau** [comment]
@maxGimeno I let you clean up the TODO at https://github.com/CGAL/cgal/issues/3529#issue-389380428.

**Comment by lrineau** [comment]
@maxGimeno @afabri:
This issue has been closed by the merge of https://github.com/CGAL/cgal/pull/5162, but the GMP/MPFR entry in the [TODO list](https://github.com/CGAL/cgal/issues/3529#issue-389380428) is still unchecked.

**Comment by lrineau** [comment]
> @maxGimeno @afabri:
> This issue has been closed by the merge of #5162, but the GMP/MPFR entry in the [TODO list](https://github.com/CGAL/cgal/issues/3529#issue-389380428) is still unchecked.

I consider this task is DONE.
