### ISSUE TITLE
Assertion fail on 3D boolean operation

### ISSUE THREAD

**Issue by taus** [CGAL/cgal#353]
When trying to perform 3D boolean operations on Nef polyhedra i get the assertion fail

    CGAL error: assertion violation!
    Expression : G.mark(v1,0)==G.mark(v2,0)&& G.mark(v1,1)==G.mark(v2,1)
    File       : ./CGAL/include/CGAL/Nef_S2/SM_overlayer.h 
    Line       : 287

I have insured that the meshes are closed, valid and triangular. I have created a minimal example here: https://github.com/taus/CGALMinimal to demonstrate the error. The example includes a simple mesh creator and uses this to create two overlapping boxes. It then converts them to Nef polyhedra and tries to do a union. I have tried this in both CGAL 4.6.7 and the 4.7 beta.

**Comment by sloriot** [comment]
The meshes are self-intersecting and thus don't have a clean definition of inside/outside which explains why the nef code was not able to correctly mark the volume.
![screenshot from 2015-09-22 10 03 40](https://cloud.githubusercontent.com/assets/1224632/10013398/7cb1a438-6111-11e5-9f5b-27645c393b15.png)

**Comment by sloriot** [comment]
See [this function](http://doc.cgal.org/4.7/Polygon_mesh_processing/group__PkgPolygonMeshProcessing.html#ga0afb9e365a2f16f0591255b8df468885)

**Comment by taus** [comment]
Thank you. I got the impression from the documentation that the requirement for succesfully converting a polyhedron to nef was the "is_closed" predicate. I got it working now though. As a small heads up, in the header file polygon_mesh_processing.h, the inclusion of the file polygon_soup_to_polygon_mesh is missing the Polygon_mesh_processing/ directory.

**Comment by sloriot** [comment]
The first requirement is that the input is a valid polyhedral surface :)
Thanks for the bug-report. I just fixed it.
