### ISSUE TITLE
Multiple definitions of after_attach in Arrangement_on_surface_2

### ISSUE THREAD

**Issue by albert-github** [CGAL/cgal#3540]
## Issue Details
In the file `Arrangement_on_surface_2/doc/Arrangement_on_surface_2/CGAL/Arr_observer.h` I found 2 times the definition of `after_attach()` on lines 159 and 170 (for the documentation output see `doc_output/Arrangement_on_surface_2/classCGAL_1_1Arr__observer.html`)  I think the second case should be `after_detach()`:

> 149 /*!
> 150 issued just before the observer is attached to the arrangement instance
> 151 `arr`.
> 152 */
> 153 virtual void before_attach (const Arrangement_2& arr);
> 154
> 155 /*!
> 156 issued immediately after the observer has been attached to an
> 157 arrangement instance.
> 158 */
> 159 virtual void after_attach ();
> 160
> 161 /*!
> 162 issued just before the observer is detached from its arrangement instance.
> 163 */
> 164 virtual void before_detach ();
> 165
> 166 /*!
> 167 issued immediately after the observer has been detached from its
> 168 arrangement instance.
> 169 */
> 170 virtual void after_attach ();

*Side note*
This is the danger of having the actual definition (as in `Arrangement_on_surface_2/include/CGAL/Arr_observer.h`) and the documentation as in `Arrangement_on_surface_2/doc/Arrangement_on_surface_2/CGAL/Arr_observer.h` in separate files.

**Comment by sloriot** [comment]
I fully agree but when we ported our old documentation to doxygen, the safest and faster way to do it using separate files. At some point we are planning to merge them but it requires a lot of man power.

We greatly appreciate your help to spot all those issues in our documentation. If you have some extra checks  that could be added to our automatic testsuite we would be happy to integrate them.

**Comment by albert-github** [comment]
I'm trying to improve doxygen in respect to HTML output and especially in respect to  consistency of the XHTML data model and use CGAL as code base to check for problems.  So it is work in progress and CGAL can have some benefits as well when I spot problems in the CGAL code.

**Comment by lrineau** [comment]
Fixed by #3543.
