### ISSUE TITLE
Multiple definitions of construct_vector_2_object in Optimal_transportation_reconstruction_2

### ISSUE THREAD

**Issue by albert-github** [CGAL/cgal#3541]
## Issue Details
In the file `Optimal_transportation_reconstruction_2/doc/Optimal_transportation_reconstruction_2/Concepts/OptimalTransportationReconstructionTraits_2.h` I found 2 times the definition of after_attach()  (for the documentation output see `doc_output/Optimal_transportation_reconstruction_2/classOptimalTransportationReconstructionTraits__2.html`):

> 151   Construct_vector_2 `construct_vector_2_object();
> 152   Construct_vector_2 construct_vector_2_object();

**Comment by lrineau** [comment]
Fixed by #3543.
