### ISSUE TITLE
Multiple definitions of Vector_3 in Point_set_shape_detection_3

### ISSUE THREAD

**Issue by albert-github** [CGAL/cgal#3542]
## Issue Details
In the file `Point_set_shape_detection_3/doc/Point_set_shape_detection_3/Concepts/ShapeDetectionTraits.h` I found 2 times the definition of `Vector_3` (for the documentation output see `doc_output/Point_set_shape_detection_3/classShapeDetectionTraits.html`). I think the second definition should be `Vector_2`:

>  26   typedef unspecified_type Vector_3;
>  27   /// The sphere type, only required if you want to detect spheres or tori
>  28   typedef unspecified_type Sphere_3;
>  29   /// The line type, only required if you want to detect cylinders
>  30   typedef unspecified_type Line_3;
>  31   /// The plane type, only required if you want to detect planes
>  32   typedef unspecified_type Plane_3;
>  33   /// The 2D point type, only required if you want to detect tori
>  34   typedef unspecified_type Point_2;
>  35   /// The circle type, only required if you want to detect tori
>  36   typedef unspecified_type Circle_2;
>  37   /// The 2D vector type, only required if you want to detect tori
>  38   typedef unspecified_type Vector_3;
>

**Comment by lrineau** [comment]
Fixed by #3543.
