### ISSUE TITLE
Multiple definitions of QPSolverTraits  in QP_solver

### ISSUE THREAD

**Issue by albert-github** [CGAL/cgal#3546]
## Issue Details

In the files:
- `QP_solver/doc/QP_solver/fig_src/documentation/PD_D_iterator_example.cpp`
- `QP_solver/doc/QP_solver/fig_src/documentation/QP_solver_talk_example.cpp`
- `QP_soler/doc/QP_solver/fig_src/documentation/QP_solver_talk_implicit_example.cpp`

we see that the `struct QPSolverTraits` is defined, resulting in a lot of multiple definitions in the documentation, see `doc_output/QP_solver/structQPSolverTraits.html`

For me strange that the structure is only defined in the documentation section.
When looking at e.g. the master documentation, the QPSolverTRaits are not present, so it might have to do something with the way I create the documentation:
- `cmake -DDOXYGEN_EXECUTABLE=doxygen.exe ../Documentation/doc/`
- `make doc`
- `make doc`

in the later case please advise how to build the documentation without the mentioned files (and maybe other files as well).

**Comment by sloriot** [comment]
This directory should have been ignored. I fixed that.

**Comment by lrineau** [comment]
Fixed by #3543.

Note that fix was merged in the release branches for 4.12.2 and 4.13.1, and in `master` as well, for CGAL-4.14.
