### ISSUE TITLE
Polyhedron demo: we need a libscene_c3t3_item.cpp

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#355]
For the moment, in `master`, the `Scene_c3t3_item` class is a private class of the `mesh_3_plugin`, in the file `Polyhedron/demo/Polyhedron/Polyhedron_demo_mesh_3_plugin_cgal_code.cpp`.

That item class should have its own library, like for other scene items.

**Comment by lrineau** [comment]
@sloriot, because I am pretty sure you also worked in that issue in the branch https://github.com/CGAL/cgal-dev/tree/Polyhedron-clipping_snapping_new_snapping-GF

**Comment by sloriot** [comment]
Indeed, the work to isolate the code into header and  cpp is done in this branch.

**Comment by sloriot** [comment]
cc @maxGimeno

**Comment by maxGimeno** [comment]
I think this issue should be closed by now, as there is a scene_c3t3_item.cpp/.h in master.

**Comment by sloriot** [comment]
Fixed by #463
