### ISSUE TITLE
Wiki: regroup information related to new package

### ISSUE THREAD

**Issue by MaelRL** [CGAL/cgal#3563]
The different things to do when adding a new package such as updating the package list, running generate_travis, computing the new dependencies, the new licenses, etc.,  are split in the wiki between different pages (when present at all) and should be made it easier to find.

**Comment by maxGimeno** [comment]
I wrote a wiki page [here](https://github.com/CGAL/cgal/wiki/Travis-CI-Explaned-and-Check-List-for-a-New-Package)
Feel free to edit it or to report things you don't like to enhance it.

**Comment by MaelRL** [comment]
Thanks!

I have made some changes (it is also now [here](https://github.com/CGAL/cgal/wiki/Travis-CI-Explained-and-Check-List-for-a-New-Package) after fixing the typo in the title) and added some more crosslinks from other pages.

It is good to also have a page acting as a kind of FAQ that can be linked when someone's CI job fails.
