### ISSUE TITLE
Polygon_mesh_processing::isotropic_remeshing is running very slow

### ISSUE THREAD

**Issue by jasjuang** [CGAL/cgal#3565]
## Issue Details

I am trying to run the function `CGAL::Polygon_mesh_processing::isotropic_remeshing` for a 20000 vertices 40000 faces mesh, and it has been running over 3 hours and still not completed yet. Is this kind of run time expected? Please see below for the minimal code

```
typedef CGAL::Simple_cartesian<double> K;
typedef CGAL::Surface_mesh<K::Point_3> Mesh;

Mesh m;

std::ifstream input("input.off");
input >> m;
input.close();

CGAL::Polygon_mesh_processing::isotropic_remeshing(faces(m), 1.0, m);

std::ofstream output("output.off");
output << m;
output.close();
```

I can verify that the input mesh is correct because if I comment out `isotropic_remeshing`, `output.off` shows the same mesh as the input. I can also verify the isotropic_remeshing is functioning properly because if the input is simple square like 

```
Mesh::Vertex_index v0 = m.add_vertex(K::Point_3(0, 2, 0));
Mesh::Vertex_index v1 = m.add_vertex(K::Point_3(2, 2, 0));
Mesh::Vertex_index v2 = m.add_vertex(K::Point_3(0, 0, 0));
Mesh::Vertex_index v3 = m.add_vertex(K::Point_3(2, 0, 0));
Mesh::Vertex_index v4 = m.add_vertex(K::Point_3(1, 1, 0));
m.add_face(v3, v1, v4);
m.add_face(v0, v4, v1);
m.add_face(v0, v2, v4);
m.add_face(v2, v3, v4);
```

it remeshes instantly and the resulting output is correct. Is the run time dependent on the shape of the mesh or is it only dependent on the number of vertices and face?

I also noticed that it's only running on a single thread. Is there any way to speed it up by running multi-thread?

Here is the 20000 vertices 40000 faces mesh that I am testing with. [input.zip](https://github.com/CGAL/cgal/files/2700811/input.zip)

## Environment

* Operating system:  Ubuntu 18.04
* Compiler: GCC 7
* Release or debug mode: Release
* CGAL version: Latest
* Boost version: 1.65

**Comment by sloriot** [comment]
I can reproduce the issue, it is not expected.

**Comment by sloriot** [comment]
You mesh is not valid.
If you call  `CGAL::is_valid_polygon_mesh(m) ` it will return `false`.
Calling 
```
CGAL::Polygon_mesh_processing::remove_isolated_vertices(m);`
CGAL::Polygon_mesh_processing::duplicate_non_manifold_vertices(m);
```
will make it work.
Note that you'll need  #3568 if you are using 4.13 but 4.12 should work directly.

**Comment by jasjuang** [comment]
@sloriot Thanks, now I am getting the expected result, but #3568 doesn't seem to have a effect for me.

With `remove_isolated_vertices` and `duplicate_non_manifold_vertices`, no #3568 --> produce expected result

With `remove_isolated_vertices` and `duplicate_non_manifold_vertices`, with #3568 --> produce expected result

No `remove_isolated_vertices` and `duplicate_non_manifold_vertices`, no #3568 --> stuck

No `remove_isolated_vertices` and `duplicate_non_manifold_vertices`, with #3568 --> stuck

**Comment by sloriot** [comment]
`duplicate_non_manifold_vertices` is required in any case.
