### ISSUE TITLE
CGAL::output_to_medit() does not use consistent facet orientation

### ISSUE THREAD

**Issue by goran-w** [CGAL/cgal#3566]
## Issue Details

The orientation of surface facets and between-subdomain facets (triangles) resulting from CGAL::output_to_medit() are randomly oriented. This issue was discussed already in 2010 near the end of the following forum post:

http://cgal-discuss.949826.n4.nabble.com/CGAL-3d-Mesh-Triangulation-Facets-with-too-many-neighbors-facets-td2332420.html

I can provide a pull request with a fix (similar to the one suggested in the forum post) against CGAL 4.13. (We are using this orientation fix in order to ensure correctly oriented triangles.)

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows 10 64-bit
* Compiler: Visual Studio 2017
* CGAL version: 4.13

**Comment by sloriot** [comment]
What about using [`orient_to_bound_a_volume()`](https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__orientation__grp.html#gafdbc256d06536f6aca2558bc1a0156e2)?

**Comment by sloriot** [comment]
Maybe together with [`is_outward_oriented()`](https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__orientation__grp.html#gad71360b56f0d5340bf3006febd49286c) and [`reverse_face_orientations()`](https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__orientation__grp.html#ga21119757bf5835496ae1c9a6d4f5fa0a)

**Comment by goran-w** [comment]
> What about using [`orient_to_bound_a_volume()`]
> Maybe together with [`is_outward_oriented()`] and [`reverse_face_orientations()`]

Not clear how to apply that to C3T3/Triangulation before calling output_to_medit(). Also, subdomain-index pairs of facets should be taken into account. I'm finishing up my pull request so you can take a look, the fix is quite simple.

**Comment by sloriot** [comment]
Sorry you were using face graph as output.

**Comment by lrineau** [comment]
closed by the merge of #3567.

**Comment by goran-w** [comment]
@lrineau Sorry to add comment on my closed and merged issue, but I looked some more into this and noted that even though my merged fix makes the triangle orientations consistent, the "print twice" option still outputs two triangles with identical orientation (but possibly two different subdomain labels).

To get even more useful facet orientations we should swap the orientation again when printing the second triangle, like this:

```
  if ( print_each_facet_twice )
  {
    os << V[vh3] << ' ' << V[vh2] << ' ' << V[vh1] << ' ';
    os << get(facet_twice_pmap, *fit) << '\n';
  }
```

Then, with backface-culling enabled, an outer facet would be visible from both sides and a visible inner (between-subdomains) facet would have the "inside" subdomain label when viewed from inside either of its two subdomains. (NOTE: To instead make a visible inner facet have the "outside" (opposite) subdomain label, we could swap the condition for mirroring the facet - see below.)

To summarize, with this last proposed change we would be swapping the facet orientation 3 times:

* First, we mirror the facet if needed in order to get a consistent orientation per each subdomain-pair. This also matches the No_patch_facet_pmap_first/second implementation which always returns the lower subdomain label as first and the higher label as second (except for invalid labels (0 or -1) where both return the valid label). As noted above, the condition here could be inverted if we want to see the "opposite/neighbor" subdomain label when the triangle is viewed from inside a certain subdomain.

* Next, we flip the vertex order if needed due to the facet index parity.

* Finally, if printing facets twice, we flip the vertex order when printing the triangle again with the second (higher) subdomain label. This way we get two triangles with opposite orientation. (Which triangle gets which label is controlled by the condition of the initial mirroring.)

**Comment by lrineau** [comment]
@goran-w I agree. Please implement this small fix and create a second pull-request. CGAL-4.13.1 is not yet published, and we have time to get this fixed before I publish it.

**Comment by goran-w** [comment]
@lrineau Thanks! Besides flipping the duplicated triangles, I will invert the condition for initially mirroring the facet (as hinted above) since I just realized this is actually needed in order to get a consistent front-facing orientation when viewing (from outside) only the triangles with a specific subdomain label. 

This will also be more informative, since when looking from inside a certain subdomain you can easily tell if tetras from another subdomain are attached to some of the facets.

**Comment by goran-w** [comment]
@lrineau Additionally, since I have not tested my changes with Rebind_facet_pmap<>, i.e the cases where Medit_pmap_generator::print_twice() returns false, I will only perform the initial facet mirroring if print_each_facet_twice is true. 

(Note that this safe-guarding could mean that facet orientations will still be inconsistent when not printing twice, but it should then not be any worse than the pre-patch implementation.)
