### ISSUE TITLE
Typo in the documentation

### ISSUE THREAD

**Issue by copyme** [CGAL/cgal#3574]
On the page [https://doc.cgal.org/latest/Arrangement_on_surface_2/index.html](https://doc.cgal.org/latest/Arrangement_on_surface_2/index.html), there is 

>  You cannot access the coordinates of such points and obtain them as algebraic numbers, and only access to the approximate coordinates **in** possible

but it should be

> You cannot access the coordinates of such points and obtain them as algebraic numbers, and only access to the approximate coordinates **is** possible

**Comment by sloriot** [comment]
Thanks for the report, fixed in dc56732a6f.
