### ISSUE TITLE
Problem locating files regarding documentation problems.

### ISSUE THREAD

**Issue by albert-github** [CGAL/cgal#3585]
## Issue Details

I looked at the overnight test results in `https://cgal.geometryfactory.com/CGAL/Manual_doxygen_test/CGAL-4.14-Ic-92/logs_master/Hyperbolic_triangulation_2.log` and saw:
```
/home/cgal-testsuite/cgal_doc_build/CGAL-4.14-Ic-92/doc/Hyperbolic_triangulation_2/Hyperbolic_triangulation_2.txt:49: warning: unable to resolve reference to `fig__Hyperbolic_triangulation_2Euclidean_vs_hyperbolic&nbsp' for \ref command
/home/cgal-testsuite/cgal_doc_build/CGAL-4.14-Ic-92/doc/Hyperbolic_triangulation_2/Hyperbolic_triangulation_2.txt:65: warning: unable to resolve reference to `fig__Hyperbolic_triangulation_2Euclidean_vs_hyperbolic&nbsp' for \ref command
```

In my clone I was unable to reproduce the problem and I couldn't find any reference to the mentioned file or to a package / directory called `Hyperbolic_triangulation_2`.

Can you shine a light on this?

**Comment by MaelRL** [comment]
This is a new package being added in https://github.com/CGAL/cgal/pull/3283.

**Comment by albert-github** [comment]
I see that this package is not yet merged into the master and therefore not yet visible on the github server?

Problem is that doxygen doesn't see a separator. The code: `\cgalFigureRef{Hyperbolic_triangulation_2Euclidean_vs_hyperbolic}&nbsp...` (my dots for the rest of the line) results in `\ref Hyperbolic_triangulation_2Euclidean_vs_hyperbolic&nbsp...` and this is not a valid reference.replacing the first `&nbsp;` witgh a space should solve the message.

**Comment by imiordanov** [comment]
> I see that this package is not yet merged into the master and therefore not yet visible on the github master.
> 
> Problem is that doxygen doesn't see a separator. The code: `\cgalFigureRef{Hyperbolic_triangulation_2Euclidean_vs_hyperbolic}&nbsp...` (my dots for the rest of the line) results in `\ref Hyperbolic_triangulation_2Euclidean_vs_hyperbolic&nbsp...` and this is not a valid reference.replacing the first `&nbsp;` with a space should solve the message.

In fact I have removed the `&nbsp`, and I've verified that there is no warning during the compilation. I have also just committed the edit, so it should be OK in the next run.

**Comment by lrineau** [comment]
Replaced by #3283.
