### ISSUE TITLE
clip function: not returning correct clip volume for special case

### ISSUE THREAD

**Issue by borki23** [CGAL/cgal#3586]
I think I found an issue using the clip function from `Polygon_mesh_processing `.
In my case I have a cube and it should be clipped using an arbitrary 3D surface (not closed, no intersections). The part of the cube on one side of the surface should yield a new volume along with the surface inside the cube.
However, if I have a surface which vertices that lie directly on one of the cubes edges, the clip function returns the whole cube combined with the surface inside the cube. Here is an image:
https://i.postimg.cc/CLCcnxL7/sphere10-clip-Error-Copy.png
You can see that the original surface (darker red area around the cube) has a few points which lie directly on the cube edge. Also, the cube is still complete but has the surface area inside of it (brighter red area) is added and triangulated.
I think the clipping function should be able to handle such cases.
When I increase the surface size so that more triangles around the intersection area are used, the error disappears.

`CGAL::Surface_mesh<CGAL::Exact_predicates_inexact_constructions_kernel::Point_3> v1,Clipper;
/*
Create clipper and cube, by adding faces and points.
*/
CGAL::Polygon_mesh_processing::clip(v1, Clipper, CGAL::Polygon_mesh_processing::parameters::clip_volume(true));
`

CGAL-4.13 (header only and no MPFR/GMP)
Windows 10 x64

**Comment by lrineau** [comment]
To help us debug your issue, that would be better if you can share the input data set that exposes the bug.

[**@borki23**](https://github.com/borki23) commented on [Jan 10, 2019, 1:22 PM GMT+1](https://github.com/CGAL/cgal/issues/3586#issue-397806306 "2019-01-10T12:22:13Z - Replied by Github Reply Comments"):
> CGAL-4.13 (header only and no MPFR/GMP)

Note that we do not test CGAL without MPFR/GMP. It might works, because CGAL has a number types that can do exact computation (`CGAL::MP_Float`), but GMP and MPFR are documented as mandatory dependencies.

**Comment by sloriot** [comment]
I agree with @lrineau  please provide `v1` and `Clipper`.

**Comment by borki23** [comment]
Here you go. However I'm not quite sure if the precision has been altered during the print. Just tell me if you can recreate the error with these files.

[files.zip](https://github.com/CGAL/cgal/files/2745851/files.zip)

**Comment by sloriot** [comment]
It worked for me both with master and 4.13 release.

**Comment by sloriot** [comment]
```
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/Polygon_mesh_processing/clip.h>
#include <CGAL/Surface_mesh.h>

#include <iostream>
#include <fstream>

namespace PMP = CGAL::Polygon_mesh_processing;
namespace params = PMP::parameters;

typedef CGAL::Exact_predicates_inexact_constructions_kernel K;
typedef CGAL::Surface_mesh<K::Point_3> Surface_mesh;

int main()
{
  // test with a clipper mesh
  Surface_mesh tm1, tm2;

  std::ifstream("v1.off") >> tm1;
  std::ifstream("clipper.off") >> tm2;

  PMP::clip(tm1, tm2,
            params::clip_volume(true));
  
  std::ofstream("out.off") << tm1;

  return 0;
}
```

[out.zip](https://github.com/CGAL/cgal/files/2745961/out.zip)

**Comment by borki23** [comment]
When I load v1 from the files and do the clipping afterwards, it is working. This is not the case if I do the same for the clipper. 

I dynamically create v1 and clipper by adding points like
`v1.add_vertex(CGAL::Exact_predicates_inexact_constructions_kernel::Point_3(x,y,z));`

My assumption is that if there are rounding errors while adding the points or they have a much higher precision as needed, it could be that some points lie inside v1 and then a clipping is not possible?
Loading the files again cuts off extra precision and then the points do lie exactly on edges and then the clip operation is valid? 

No I have three options:
1) Using less precision and cut off numbers
2) Using another method to add points
3) Use a bigger clipper mesh.

**Comment by sloriot** [comment]
Dump your file doing `out << std::setprecision(17) << tm`.

**Comment by borki23** [comment]
Yes, I was thinkng of that aswell.
Could you try again with these files? 
I think the problem is due to the fact that points lie inside the cube. Therefore, I wil use a bigger mesh for clipping.
[data.zip](https://github.com/CGAL/cgal/files/2754733/data.zip)

**Comment by sloriot** [comment]
It is indeed the clipper that is too small. Computing the intersection curves, I got 2 polylines instead of one. Extending your surface will solve the pb. I'm closing this ticket.

**Comment by qpoisson** [comment]
@borki23   could you confirm that clip does work for non-closed clipper ?  I would like do a similar thing but the document claims that clipper should be closed.

**Comment by sloriot** [comment]
@qpoisson It will work if the clipper is sufficiently larger than the intersection with the model. Basically, the intersection curve of the clipper and the model must be a set of closed curves.
