### ISSUE TITLE
Invalid sha256 sum for 4.13 tar.gz

### ISSUE THREAD

**Issue by glyg** [CGAL/cgal#3589]
## Issue Details

The sha256sum given in https://github.com/CGAL/cgal/releases/download/releases%2FCGAL-4.13/sha256sum.txt does not correspond to the one obtained after downloading the file

**Comment by lrineau** [comment]
The link https://github.com/CGAL/cgal/archive/releases/CGAL-4.13.tar.gz is to a tarball generated by Github, that gives you the Git layout of CGAL repository, and not the flattened release layout.

Please download https://github.com/CGAL/cgal/releases/download/releases%2FCGAL-4.13/CGAL-4.13.tar.xz instead.
