### ISSUE TITLE
Subdivision_method_3 CatmullClark_subdivision regression Cgal 4.10 -> 4.11

### ISSUE THREAD

**Issue by seb-tourneux** [CGAL/cgal#3603]
## Issue Details

CatmullClark subdivision fails in some cases from CGAL 4.11 (failing in 4.11 and 4.13), while thoses case were handled properly in 4.10.

## Source Code

I am testing using the example _example/Subdivision_method_3/CatmullClark_subdivision.cpp_ with one subdivision step and this .off as input :

> OFF
> 5 2 0
> 
> 0 0 1
> 0 0 0
> 1 0 0
> 0.25 0 0.3
> 1 0 1
> 
> 4 0 1 2 3
> 4 3 2 4 0

Correct result using CGAL 4.10.2 :

> OFF
> 13 8 0
> 
> 0.125 0 0.875
> 0.125 0 0.125
> 0.875 0 0.125
> 0.46875 0 0.475
> 0.875 0 0.875
> 0.53125 0 0.3
> 0.28125 0 0.55
> 0 0 0.5
> 0.5 0 0
> 1 0 0.5
> 0.5 0 1
> 0.3125 0 0.325
> 0.5625 0 0.575
> 4  11 6 0 7
> 4  12 5 2 9
> 4  5 3 6 11
> 4  11 7 1 8
> 4  8 2 5 11
> 4  6 3 5 12
> 4  12 9 4 10
> 4  10 0 6 12

Wrong result using CGAL 4.11 and CGAL 4.13

> OFF
> 13 8 0
> 0.125 0 0.875
> 0.125 0 0.125
> 0.875 0 0.125
> 5.36871e+08 0 6.44245e+08
> 0.875 0 0.875
> 0 0 0.5
> 0.5 0 0
> 0.53125 0 0.3
> 0.28125 0 0.55
> 1 0 0.5
> 0.5 0 1
> 0.3125 0 0.325
> 0.5625 0 0.575
> 4 11 6 2 7
> 4 12 7 2 9
> 4 5 1 6 11
> 4 11 7 3 8
> 4 8 0 5 11
> 4 8 3 7 12
> 4 12 9 4 10
> 4 10 0 8 12

Notice that the 4th vertex is sent really far from its desired position (5.36871e+08 0 6.44245e+08).
It seems to fail in every configuration havong this same structure (two quads sharing two consecutive edges), independantly of vertices positions.

Thank you.

## Environment

* CGAL version: 4.11
* Boost version: 1.62.0

**Comment by MaelRL** [comment]
The problem comes from treating the degree of the vertex (`degree=2` being the problem here) as an unsigned size type and then computing `n-3` in CatmullClark's mask.

**Comment by MaelRL** [comment]
@seb-tourneux Thank you for the bug report. It will be fixed in #3604. There will not be any more bug fix releases for CGAL 4.11, but the bug will be fixed in the bug fix releases of CGAL 4.12 and 4.13 (and in the next releases of CGAL).

**Comment by seb-tourneux** [comment]
Thank you !
