### ISSUE TITLE
CGAL::Color: inconsistency between doc and code

### ISSUE THREAD

**Issue by sgiraudot** [CGAL/cgal#3620]
## Issue Details

The doc of `CGAL::Color` does not match its actual behavior.

The doc says:

```c++
/*!
creates a color with rgb-value `(0,0,0)`, i.e.\ black. 
*/ 
Color(); 
/*!
creates a color with rgb-value `(red,green,blue)`. 
*/ 
Color(unsigned char red, unsigned char green, unsigned char blue);
```

While the code does:

```c++
  Color(): _red(120), _green(120), _blue(120), _alpha(120) {}
  Color(unsigned char red,
	unsigned char green,
	unsigned char blue,
	unsigned char alpha = 120)
    : _red(red), _green(green), _blue(blue), _alpha(alpha)
  {}
```

I really don't know why these 120 values are used, they seem pretty random. The non-documented alpha value is not too bad, but being initialized to 120 by default means it's half-transparent, which seems also like a bad behavior (it should at least be 255 by default).

I'm intending to merge the doc and code (and get rid of the fake `.h` doc file) and do the following:
- keep the doc behavior (initialization to black, 0 0 0)
- document the alpha parameter
- take advantage of this change to get rid of the [color typedefs in classification](https://doc.cgal.org/latest/Classification/namespaceCGAL_1_1Classification.html#a821191c51c0d68935f3dd35413cdcd0a) and use the `CGAL::Color` class
- probably add a method `to_hsv()` that will return an array with the HSV values (which can be useful, and the code already exists in classification)

Anybody has an objection?
(I'll do a small feature so we can discuss it there anyway.)

**Comment by lrineau** [comment]
I agree.

**Comment by sgiraudot** [comment]
Also the constants (`BLACK`, `WHITE`, etc.) are documented as part of the class `CGAL::Color`, but they are not. That means that we have to call `CGAL::BLACK` for example instead of `CGAL::Color::BLACK`. I think it'd be better if they were really static constants of the class.

**Comment by lrineau** [comment]
[**@sgiraudot**](https://github.com/sgiraudot) commented on [Jan 24, 2019, 9:49 AM GMT+1](https://github.com/CGAL/cgal/issues/3620#issuecomment-457115348 "2019-01-24T08:49:30Z - Replied by Github Reply Comments"):
> Also the constants (`BLACK`, `WHITE`, etc.) are documented as part of the class `CGAL::Color`, but they are not. That means that we have to call `CGAL::BLACK` for example instead of `CGAL::Color::BLACK`. I think it'd be better if they were really static constants of the class.

I disagree. An enum can be part of the global CGAL namespace. That way they can be reused in different classes. All CGAL enums are supposed to be in `<CGAL/enum.h>. Qt did the same with all its enums: http://doc.qt.io/qt-5/qt.html#GlobalColor-enum.

**Comment by sgiraudot** [comment]
Alright, but it still needs to be documented differently then. And so far, it's not an enum but a set of global const variables:

```c++
namespace CGAL {

const Color BLACK  = Color(0, 0, 0);
const Color WHITE  = Color(255, 255, 255);
const Color GRAY   = Color(100,100,100);

const Color GREEN  = Color(0, 255, 0);

const Color DEEPBLUE   = Color(10, 0, 100);
const Color BLUE   = Color(0, 0, 255);
const Color VIOLET = Color(255, 0, 255);
const Color PURPLE = Color(100, 0, 70);

const Color RED    = Color(255, 0, 0);
const Color ORANGE = Color(235, 150, 0);
const Color YELLOW = Color(255, 255, 0);

} //namespace CGAL
```

**Comment by lrineau** [comment]
:astonished: We have a problem: that API cannot work in CGAL header-only. We must modify the API then.

**Comment by sloriot** [comment]
The issue mentioned above has been addressed with a breaking change announced in the release notes.
