### ISSUE TITLE
num_vertices( surfacemesh ) not BGL conform

### ISSUE THREAD

**Issue by visorz** [CGAL/cgal#363]
To write an algorithm suitable for CGAL::Polyhedron_3 and CGAL::Surfacemesh I try to use Boost Graph Library. In Surfacemesh's user [documentation](http://doc.cgal.org/latest/Surface_mesh/index.html#sectionSurfaceMeshConnectivity) there is no BGL equivalent to mesh.num_vertices( ) because num_vertices( surfacemesh ) returns both; existing and deleted vertices. 

IMO this brakes boost's intention to have same meaning on all graph data structures because it returns existing and deleted vertices only on Surfacemesh, not on Polyhedron. Please see the [MWE](https://gist.github.com/visorz/935633f736aae4d69fae) 

If there is a function remove_vertex( vd, graph ) then num_vertices( graph ) should not return the size of the underlying data structure with vertices marked as deleted, but the number of existing vertices in that graph. If I want the size of the DS I can request it from a specific Surfacemesh instance. Such a query is data structure dependent and would look different for all used graph DSs like Polyhedron_3 or libigl. So having to write DS dependent code when querying the DS is no surprise. But making a call to sm.collect_garbage( ) before using a BGL command to get the same result on different DSs is Surfacemesh specific and breaks a uniform BGL algorithm.

Please change that behaviour so that: `num_vertices( surfacemesh ) == surfacemesh.number_of_vertices( )`. Thank you.

**Comment by afabri** [comment]
num_vertices takes the deleted vertices into account as this allows to index into a std::vector storing properties.
This is similar to boost::filtered_graph<G> where num_vertices is the num'ber of vertices of the ubderlying graph.

**Comment by visorz** [comment]
Could you please add the reason to the documentation? It would clarify, that BGL accessors are not meant to create uniform handling of Surfacemesh and Polyhedron_3 for a deeper reason. Thank you.

**Comment by bo0ts** [comment]
Can we leave this ticket open until we have added the necessary documentation to fix this?

**Comment by sloriot** [comment]
@afabri could you update the documentation?

**Comment by afabri** [comment]
I added
>  It would be nicer to return the number of vertices withou
> taking removed vertices into account, but this would interact badly with 
> the underlying vertex/edge index mappings. The index mapping would no longer 
>  fall in the range `[0,num_vertices(g))`  which is assumed in many
>  of the algorithms.

taken and adapted from [`boost::filtered_graph`](http://www.boost.org/doc/libs/1_60_0/libs/graph/doc/filtered_graph.html)
