### ISSUE TITLE
Exact.cpp example from CGAL standard examples crashes

### ISSUE THREAD

**Issue by kobylkinks** [CGAL/cgal#3631]
Dear colleagues,

I'm newbie to CGAL library. I started exploring examples from the CGAL 4.13 distribution. I've tried to run exact.cpp example on my Windows 7 machine with VS2017 and Boost 1.69. I successfully compiled kernel23 solution, containing exact.cpp example (cmakegui+build in VS). But when I tried to run exact.exe I have encountered the following Windows error:

  BEX64
  Application name:	exact.exe
  Application version:	0.0.0.0
  Application time stamp(mark):	5c4ad4b5
  Module caused error:	libgmp-10.dll
  Module version:	0.0.0.0
  Module time stamp:	ae38ae20
  Exception shift:	0000000000060fa0
  Exception code:	c0000005
  Exception data:	0000000000000008
  OS:	6.1.7601.2.1.0.768.3
  Language code:	1049
  Additional info 1:	2544
  2:	2544bc37c14b363c359b4e4dc67cb531
  3:	a0a8
  4:	a0a8de77255a5a7aeb7956ac6dbd55f5

Is this an expectable error ? CGAL manual discusses this example as working. How can I set my VS environment to avoid such errors ?

**Comment by lrineau** [comment]
That is strange, because that setup has been tested. Would you mind recompile in Debug (without the macro `NDEBUG`) and retry?

**Comment by kobylkinks** [comment]
I think the problem was with my AV software.

**Comment by lrineau** [comment]
Thanks for letting us know @kobylkinks.
