### ISSUE TITLE
Provide pkg-config file

### ISSUE THREAD

**Issue by Salamandar** [CGAL/cgal#3633]
You are currently providing CMake files, but using CGAL with another build system is currently not easy.
Would it be possible to provide a pkg-config file to facilitate the integration ?

**Comment by lrineau** [comment]
We wont, because that kind of functionality already exists in CMake since 2.8.6:

https://blogs.kde.org/2011/11/09/cool-new-stuff-cmake-286-2-pkg-config-compatible-mode-added-use-eg-autotools
