### ISSUE TITLE
Testing without precompiled boost libraries

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#3652]
## Issue Details

In the testsuite [Blake_Windows_MSVCPreview](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.14-Ic-112/Hyperbolic_triangulation_2_Demo/TestReport_Blake_Windows_MSVCPreview-Release-64bits.gz) we try to find boost.thread.  However this is not needed starting with VC2015.  
We should have a testsuite where we do not have precompiled boost libs, and make sure that it works without them.

@maxGimeno  please have a look.

**Comment by maxGimeno** [comment]
As pointed out by the testsuite you reported in this issue, Blake doesn't use the precompiled boost libraries, so there is nothing to do here.
