### ISSUE TITLE
Default rational type without GMP/LEDA

### ISSUE THREAD

**Issue by mglisse** [CGAL/cgal#3663]
Conservatively, for CGAL-4.14, we kept `Quotient<MP_Float>` as the default rational type when neither GMP not LEDA is available. #3614 contains quite some discussion about this, and in particular alternate choices like cpp_rational and `Quotient<cpp_int>`. We need to decide eventually which one fits best, and possibly implement the necessary fixes for that.

**Comment by lrineau** [comment]
@mglisse Marc, do you have clearer ideas about this issue?

**Comment by mglisse** [comment]
(I quickly reread the linked PR)
I think that replacing Quotient<MP_Float> with Quotient<cpp_int> (without specializing simplify_quotient) would be a sensible choice (cpp_rational or Quotient<cpp_int> with simplify_quotient have a very different performance profile from Quotient<MP_Float>, and it becomes a political choice whether we are more interested in small or big numbers). However, to_double is broken for it, so that needs to be fixed first.
Platforms without GMP are not a big priority for me...

**Comment by sloriot** [comment]
Let's say we go for ` Quotient<cpp_int>` is there anything else to fix ?

**Comment by mglisse** [comment]
Other than to_double? to_interval seems to have special code for Quotient<MP_Float> to lower the risk of overflow. Overflow doesn't make the result wrong for intervals, it just makes it unlikely that the filter will say anything useful, and I don't know how often such rationals occur in practice. Apart from those, I think it is fine, but I don't want to make a strong promise...

**Comment by sloriot** [comment]
Should be fixed by #5937
