### ISSUE TITLE
How to re-insert edges after edge_collapse

### ISSUE THREAD

**Issue by n-m-ya** [CGAL/cgal#3690]
I want to increase and decrease the resolution of a  mesh read as Linear_cell_complex_for_combinatorial_map 
I did the simplification step using SMS::edge_collapse

## simplification code:
```c++
 int r = SMS::edge_collapse
   (lcc
    ,stop
    ,CGAL::parameters::halfedge_index_map(get(CGAL::halfedge_index, lcc))
             .vertex_index_map(get(boost::vertex_index, lcc))
             .get_cost(SMS::Edge_length_cost<LCC>())
   .get_placement(SMS::Midpoint_placement<LCC>())
    ); 
```
## Issue Details
 I want to store the removed edges through edge collapsing and re-inserting them . 

## Environment

* Operating system (fedora):
* CGAL version:4.13

**Comment by OpenByteDev** [comment]
why is this closed?
