### ISSUE TITLE
Remaining issues of the testsuite with LEDA instead of GMP

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#3702]
## Issue Details

We want to be able to replace `GMP` and `CGAL_Core` with `leda-numbers`. However there are many `CMakeLists.txt` testing for `CGAL_Core` explicitly...

### `CMakeLists.txt` reffering to CGAL_Core
```
Arrangement_on_surface_2/demo/Arrangement_on_surface_2/CMakeLists.txt
CGAL_Core/examples/Core/CMakeLists.txt
CGAL_Core/src/CGAL_Core/CMakeLists.txt
Cone_spanners_2/examples/Cone_spanners_2/CMakeLists.txt
Cone_spanners_2/test/Cone_spanners_2/CMakeLists.txt
GraphicsView/demo/Polygon/CMakeLists.txt
Kernel_23/test/Kernel_23/CMakeLists.txt
Surface_mesh_shortest_path/test/Surface_mesh_shortest_path/CMakeLists.txt
Surface_sweep_2/test/Surface_sweep_2/CMakeLists.txt
```

It should be fixed, so that the tests are actually compiled.

### Abstraction of Exact_nt_with_sqrt

Maybe `CGALConfig.cmake` could provide a CMake target `CGAL::Exact_nt_with_sqrt` that would be an abstraction of `CGAL_Core` and LEDA.

### Remaining issues in the testsuite
See https://github.com/CGAL/cgal/pull/3501#issuecomment-444522806
> warnings and errors remaing on platforms with LEDA:
- [ ] https://cgal.geometryfactory.com/CGAL/testsuite/results-4.14-Ic-61.shtml#Algebraic_kernel_d
- [ ] https://cgal.geometryfactory.com/CGAL/testsuite/results-4.14-Ic-61.shtml#Kernel_23
- [ ] https://cgal.geometryfactory.com/CGAL/testsuite/results-4.14-Ic-61.shtml#Polygon_mesh_processing
- [ ] https://cgal.geometryfactory.com/CGAL/testsuite/results-4.14-Ic-61.shtml#Arrangement_on_surface_2
- [ ] https://cgal.geometryfactory.com/CGAL/testsuite/results-4.14-Ic-61.shtml#Bounding_volumes
- [ ] https://cgal.geometryfactory.com/CGAL/testsuite/results-4.14-Ic-61.shtml#Envelope_3
- [ ] https://cgal.geometryfactory.com/CGAL/testsuite/results-4.14-Ic-61.shtml#NewKernel_d
- [ ] https://cgal.geometryfactory.com/CGAL/testsuite/results-4.14-Ic-61.shtml#QP_solver
- [ ] https://cgal.geometryfactory.com/CGAL/testsuite/results-4.14-Ic-61.shtml#Segment_Delaunay_graph_Linf_2
- [ ] https://cgal.geometryfactory.com/CGAL/testsuite/results-4.14-Ic-61.shtml#Segment_Delaunay_graph_Linf_2_Examples
- [ ] https://cgal.geometryfactory.com/CGAL/testsuite/results-4.14-Ic-61.shtml#Triangulation
- [ ] https://cgal.geometryfactory.com/CGAL/testsuite/results-4.14-Ic-61.shtml#Visibility_2
## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): all 
* Compiler: all 
* Release or debug mode: all 
* CGAL version: `master`/4.14

See the original discussion in https://github.com/CGAL/cgal/pull/3501.

**Comment by afabri** [comment]
Coudn't it be an `Exact_real` similar to [`Exact_rational`](https://github.com/CGAL/cgal/blob/master/Number_types/include/CGAL/Exact_rational.h) ?

**Comment by mglisse** [comment]
> Coudn't it be an `Exact_real` similar to [`Exact_rational`](https://github.com/CGAL/cgal/blob/master/Number_types/include/CGAL/Exact_rational.h) ?

s/real/algebraic/ ?

**Comment by afabri** [comment]
or `Exact_sqrt` ?

**Comment by lrineau** [comment]
[**@afabri**](https://github.com/afabri) commented on [Feb 25, 2019, 5:26 PM GMT+1](https://github.com/CGAL/cgal/issues/3702#issuecomment-467077609 "2019-02-25T16:26:34Z - Replied by Github Reply Comments"):
> or `Exact_sqrt` ?

For the moment, we do not have any number type that can represent exact squared roots without also having exact algebraic numbers. That is why all three types are the same:
  - `Exact_predicates_exact_constructions_kernel_with_sqrt`,
  - `Exact_predicates_exact_constructions_kernel_with_kth_root`, and
  - `Exact_predicates_exact_constructions_kernel_with_root_of`,

and are all implemented with `leda_real` or `CORE::Expr`. If one day we get a strange number type that implements only the exact `sqrt` operation in addition to field operations, then we will perhaps name it `Exact_sqrt`.

As far as I know, the name `Exact_algebraic` is the perfect qualification for both `leda_real` or `CORE::Expr`, and would be similar to the exising `Exact_rational`.

**Comment by mglisse** [comment]
> or `Exact_sqrt` ?

I think those are called "constructible numbers".

**Comment by afabri** [comment]
Would `Arithmetic_kernel` (and `Core_algebraic_number_traits` as a variant/precursor of `Arithmetic_kernel`  in the Arrangement package)  help in any way here, or is that something completely else???

**Comment by afabri** [comment]
We need yet another wrapper for big floats.
