### ISSUE TITLE
Replace/reimplement boost BGL named parameters

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#3706]
I've read this morning that there is an on going effort to replace boost named parameters in the BGL using "revamped Boost.Parameter interface".

Someone has to investigate what is the "revamped Boost.Parameter interface" and worse case, we should have our implementation of named parameters to avoid breaking when boost will remove the base class.

**Comment by sloriot** [comment]
@MaelRL: @lrineau mentioned that you might know something about the new boost parameters. Do you have anything to share?

**Comment by lrineau** [comment]
[**@sloriot**](https://github.com/sloriot) commented on [Feb 26, 2019, 10:48 AM GMT+1](https://github.com/CGAL/cgal/issues/3706#issuecomment-467371118 "2019-02-26T09:48:10Z - Replied by Github Reply Comments"):
> @MaelRL: @lrineau mentioned that you might know something about the new boost parameters. Do you have anything to share?

I mentioned @mglisse.

**Comment by mglisse** [comment]
> I mentioned @mglisse.

Sorry, I don't know anything about that.

**Comment by lrineau** [comment]
Well, at least @mglisse you follow the boost@lists.boost.org mailing list. I have seen you interact in a discussion about the BGL, last week. Maybe you have seen the new developments about Boost Parameters and C++14, by @CromwellEnage, from November 2018 to January 2019.

**Comment by mglisse** [comment]
> Well, at least @mglisse you follow the [boost@lists.boost.org](mailto:boost@lists.boost.org) mailing list. I have seen you interact in a discussion about the BGL, last week.

True. I know a bit about the BGL.

> Maybe you have seen the new developments about Boost Parameters and C++14, by @CromwellEnage, from November 2018 to January 2019.

Nope, I don't know anything about  boost parameters.

**Comment by lrineau** [comment]
[**@mglisse**](https://github.com/mglisse) commented on [Feb 26, 2019, 2:59 PM GMT+1](https://github.com/CGAL/cgal/issues/3706#issuecomment-467448359 "2019-02-26T13:59:29Z - Replied by Github Reply Comments"):
> > Maybe you have seen the new developments about Boost Parameters and C++14, by @CromwellEnage, from November 2018 to January 2019.
> 
> Nope, I don't know anything about  boost parameters.

Then, you can https://github.com/CGAL/cgal/issues/3706#issuecomment-467099130 were I summarize the situation that I have understood:
 1. @CromwellEnage has introduced C++14 features in Boost Parameters, planned for Boost 1.70, while keeping:
     - the compatibility with C++03 compilers,
     - and the public API of Boost Parameters.
 2. He is working now on a renewed version of the BGL, using the reworked Boost Parameters.

**Comment by CromwellEnage** [comment]
Hi, everyone!

I am indeed working on incorporating the new Boost.Parameter features into the BGL.  However, a resulting BGL interface upgrade likely won't be proposed until after the release of Boost 1.70.  In the meantime, I have been working with the BGL maintainers to fix any resulting breakages.  I'll try to keep a lookout here as well.

**Comment by sloriot** [comment]
@CromwellEnage Thanks for your message. Our issue is that we are using some internal/non-documented functions of the bgl named parameters so with your work it will most likely break. 
My main concern is whether we should make a move to the boost.parameter style or have an internal version of the bgl-like named parameter.

**Comment by CromwellEnage** [comment]
Gotcha.  I'll take a look at CGAL so I can determine how to help you make the best decision.

**Comment by sloriot** [comment]
Should be fixed by #4083
