### ISSUE TITLE
Polyhedron demo: bugs in `saveSnapshot()`

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#3710]
## Issue Details

I have tried the command `File`->`Save snapshot` to get a snapshot with a bigger resolution than my screen, and a lot got wrong.

The object I wanted to draw: a c3t3, with triangles and no tets.

![screenshot_20190226_161406](https://user-images.githubusercontent.com/5746675/53423385-2997a000-39d9-11e9-9fd9-fa2c1ab53f5d.png)

I have used Save snapshot:

![screenshot_20190226_161458](https://user-images.githubusercontent.com/5746675/53423460-49c75f00-39d9-11e9-9c18-9871858065fd.png)

Then I changed the width to 2000, and the oversampling to 2:

![screenshot_20190226_161544](https://user-images.githubusercontent.com/5746675/53423517-64013d00-39d9-11e9-981e-52ce686a4167.png)

The ratio seems to be preserved.

But the image I got was:
![test](https://user-images.githubusercontent.com/5746675/53423973-38cb1d80-39da-11e9-9f1f-a1b01f232e15.png)

Two issues:

1. Wrong ratio et wrong frustrum.

2. The anti-aliasing is wrong. In the following screenshot, I have turned the background color of the image viewer to yellow, and then zoomed a lot on the image. See that the rendering of the anti-aliased edges is wrong: it is blended with the background color, instead of being blended with the color of the triangles that are behind.

![screenshot_20190226_162447](https://user-images.githubusercontent.com/5746675/53424185-a8410d00-39da-11e9-90f0-a05e165cbfca.png)

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Linux Fedora 29
* Release or debug mode: Debug
* Specific flags used (if any): `-Og -g`
* CGAL version: `master` (fe5c2d0bb8a)

**Comment by maxGimeno** [comment]
For the first issue, the frustum is preserved if you check the option "keep frustum if needed". Maybe it shouldn't be an option, and always be on.
