### ISSUE TITLE
classify.h  Precision lost in float value 

### ISSUE THREAD

**Issue by liuxinren456852** [CGAL/cgal#3720]
## Issue Details
Unexpected behavior when I run the example(example_ethz_random_forest.cpp)
## Source Code
The program exception occurs in the classify_with_graphcut function of classify.h. It divides the data according to min_number_of_subdivisions and and recalculates the bounding box of the block using the float type. The float type has a loss of precision problem, which causes the new block bounding box (bboxes) to be smaller than the bounding box of the original data(bbox). The end result is that the size of the indices (L598) is smaller than the size of the input, which causes some points to be missed. So I recommend using the double type in bounding box calculations.
## Environment
* Operating system (Windows10 64 bits):
* Compiler: visual studio 2015
* Release or debug mode: Release
* Specific flags used (if any): WITH_TBB
* CGAL version: 4.13
* Boost version: 1.60

**Comment by sgiraudot** [comment]
Please use the provided template to report issues instead of removing it completely.

It is hard to tell whether you are reporting a bug, experiencing a non-satisfying result using the software or just commenting a piece of code.

**Comment by lrineau** [comment]
17343421f596d1c7a7bad71a3b35cbc5bd7ab5e4

**Comment by liuxinren456852** [comment]
Sorry, I have modified it according to the template requirements.

**Comment by liuxinren456852** [comment]
> Please use the provided template to report issues instead of removing it completely.
> 
> It is hard to tell whether you are reporting a bug, experiencing a non-satisfying result using the software or just commenting a piece of code.

Sorry, I have modified it according to the template requirements.

**Comment by afabri** [comment]
Did you experience that with your own data set?  Could you then share it with us ?

**Comment by sgiraudot** [comment]
Thanks for the report!

I managed to reproduce the bug. I'll make a fix right away.

**Comment by lrineau** [comment]
Fixed by #3726 in releases branches (future CGAL-4.12.2, CGAL-4.13.1), and in `master` (CGAL-4.14 and later).
