### ISSUE TITLE
What is the Constrained Delaunay Triangulation algorithm used by CGAL? Is there any reference?

### ISSUE THREAD

**Issue by YaolinHou** [CGAL/cgal#3722]
_Please use the following template to help us solving your issue._

## Issue Details

_Describe your issue. Please be specific (compilation error, runtime error, unexpected behavior, wrong results, etc.)._

## Source Code

_If your issue arises by using CGAL in your own source code, please provide a minimalist example that we can compile easily to reproduce the bug. If your issue arises from using a CGAL program (demo, example, etc.), please let us know which one. Helping you solving an issue is much easier and efficient if we can reproduce it._

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):
* Compiler:
* Release or debug mode:
* Specific flags used (if any):
* CGAL version:
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by afabri** [comment]
There is no reference.  @MaelRL can you close this issue please.

**Comment by lrineau** [comment]
@YaolinHou Have a look at the article "[Triangulations in CGAL][1]". You should find adequate references in it.

[1]: https://hal.inria.fr/inria-00167199
