### ISSUE TITLE
how to open .mesh file generated by CGAL program(example Mesh_3)

### ISSUE THREAD

**Issue by wangbowenll** [CGAL/cgal#3736]
_Please use the following template to help us solving your issue._

## Issue Details
I am a freshman , I run the example(mesh_3) configured by cmake-4.12. and open the mesh_3.sln file. after building, I run the Mesh_3/mesh_implicit_sphere.cpp and get a out.mesh file. but I dont know how to open it. I try open it with meshlab、blender and tecplot. but I failed. what should I do. i want to see the image of mesh and learn the way to open my own .mesh file in future.
![image](https://user-images.githubusercontent.com/43980713/53853786-d8536600-4001-11e9-80c7-cf59e78177e6.png)

_Describe your issue. Please be specific (compilation error, runtime error, unexpected behavior, wrong results, etc.)._

## Source Code

- my  source Code directory
     C:\dev\CGAL-4.13\examples\Mesh_3  
     it  is  the CGAL program  example

`#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/Mesh_triangulation_3.h>
#include <CGAL/Mesh_complex_3_in_triangulation_3.h>
#include <CGAL/Mesh_criteria_3.h>
#include <CGAL/Labeled_mesh_domain_3.h>
#include <CGAL/make_mesh_3.h>
// Domain
typedef CGAL::Exact_predicates_inexact_constructions_kernel K;
typedef K::FT FT;
typedef K::Point_3 Point;
typedef FT (Function)(const Point&);
typedef CGAL::Labeled_mesh_domain_3<K> Mesh_domain;
#ifdef CGAL_CONCURRENT_MESH_3
typedef CGAL::Parallel_tag Concurrency_tag;
#else
typedef CGAL::Sequential_tag Concurrency_tag;
#endif
// Triangulation
typedef CGAL::Mesh_triangulation_3<Mesh_domain,CGAL::Default,Concurrency_tag>::type Tr;
typedef CGAL::Mesh_complex_3_in_triangulation_3<Tr> C3t3;
// Criteria
typedef CGAL::Mesh_criteria_3<Tr> Mesh_criteria;
// To avoid verbose function and named parameters call
using namespace CGAL::parameters;
// Function
FT sphere_function (const Point& p)
{ return CGAL::squared_distance(p, Point(CGAL::ORIGIN))-1; }
int main()
{
  Mesh_domain domain =
    Mesh_domain::create_implicit_mesh_domain(sphere_function,
                                             K::Sphere_3(CGAL::ORIGIN, 2.));
  // Mesh criteria
  Mesh_criteria criteria(facet_angle=30, facet_size=0.1, facet_distance=0.025,
                         cell_radius_edge_ratio=2, cell_size=0.1);
  
  // Mesh generation
  C3t3 c3t3 = CGAL::make_mesh_3<C3t3>(domain, criteria);
  // Output
  std::ofstream medit_file("out.mesh");
  c3t3.output_to_medit(medit_file);
  return 0;
}
`

## Environment

* Operating system (Windows10, 64 bits+vs2017):
* Compiler:  visual studio 15 2017 win 64
* Release or debug mode: debug
* Specific flags used (if any): no 
* CGAL version:  cgal-4.13
* Boost version: boost  1.67
* Other libraries versions if used (Eigen, TBB, etc.): TBB +Engin

**Comment by MaelRL** [comment]
You can use a software called "medit" to open `.mesh` files, see https://www.ljll.math.upmc.fr/frey/software.html (at the bottom of the page) for a download link and https://hal.inria.fr/inria-00069921 for some documentation.

**Comment by wangbowenll** [comment]
> 您可以使用名为“medit”的软件打开`.mesh`文件，请参阅https://www.ljll.math.upmc.fr/frey/software.html（位于页面底部）以获取下载链接和[https：// hal.inria.fr/inria-00069921](https://hal.inria.fr/inria-00069921)有些文件。

dear professor, thanks for you help,I have opened it. about color and the cutting view,I will explorit by myself.
