### ISSUE TITLE
CGAL::optimal_convex_partition_2 failure.

### ISSUE THREAD

**Issue by wzmBeiJing** [CGAL/cgal#3737]
_Please use the following template to help us solving your issue._

## Issue Details

CGAL::optimal_convex_partition_2 can't decompose the data set 

## Source Code

#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/Partition_traits_2.h>
#include <CGAL/partition_2.h>
#include <CGAL/point_generators_2.h>
#include <CGAL/random_polygon_2.h>
#include <cassert>
#include <list>
typedef CGAL::Exact_predicates_inexact_constructions_kernel K;
typedef CGAL::Partition_traits_2<K>                         Traits;
typedef Traits::Point_2                                     Point_2;
typedef Traits::Polygon_2                                   Polygon_2;
typedef Polygon_2::Vertex_iterator                          Vertex_iterator;
typedef std::list<Polygon_2>                                Polygon_list;
typedef CGAL::Creator_uniform_2<int, Point_2>               Creator;
typedef CGAL::Random_points_in_square_2< Point_2, Creator > Point_generator;
void make_polygon(Polygon_2& polygon)
{
   polygon.push_back(Point_2(1.4, -4.2));
   polygon.push_back(Point_2(1.4, -3.4));
   polygon.push_back(Point_2(-0.2, -3.4));
   polygon.push_back(Point_2(-0.2, 7.8));
   polygon.push_back(Point_2(3, 7.8));
   polygon.push_back(Point_2(3, 5.4));
   polygon.push_back(Point_2(2.2, 5.4));
   polygon.push_back(Point_2(2.2, 3));
   polygon.push_back(Point_2(3.8, 3));
   polygon.push_back(Point_2(3.8, -0.2));
   polygon.push_back(Point_2(2.2, -0.2));
   polygon.push_back(Point_2(2.2, -1.0));
   polygon.push_back(Point_2(3, -1.0));
   polygon.push_back(Point_2(3, -1.8));
   polygon.push_back(Point_2(3.8, -1.8));
   polygon.push_back(Point_2(3.8, -2.6));
   polygon.push_back(Point_2(4.6, -2.6));
   polygon.push_back(Point_2(4.6, -3.4));
   polygon.push_back(Point_2(3.8, -3.4));
   polygon.push_back(Point_2(3.8, -4.2));
}
int main()
{
   Polygon_2    polygon;
   Polygon_list partition_polys;
   Traits       partition_traits;
/*
   CGAL::random_polygon_2(50, std::back_inserter(polygon),
                          Point_generator(100));
*/
   make_polygon(polygon);
   CGAL::optimal_convex_partition_2(polygon.vertices_begin(),
                                          polygon.vertices_end(),
                                          std::back_inserter(partition_polys),
                                          partition_traits);

   std::cout << "partition_polys_size:" << partition_polys.size() << std::endl;

   assert(CGAL::convex_partition_is_valid_2(polygon.vertices_begin(),
                                            polygon.vertices_end(),
                                            partition_polys.begin(),
                                            partition_polys.end(),
                                            partition_traits));
   return 0;
}
## Environment

* Operating system Linux,64 bits):linux 64bits
* Compiler:gcc 5.4
* Release or debug mode:
* Specific flags used (if any):
* CGAL version:4.7
* Boost version:1.58
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by MaelRL** [comment]
This is a known issue with the visibility structures within the decomposition algorithm. Some proper fix is still being developed, but there is already a band-aid fix that uses a brute force approach to ensure validity of the visibility structures. If you are not using very large polygons, you should not notice any run-time difference.

See [this issue](https://github.com/CGAL/cgal/issues/2575) for more details and [this comment](https://github.com/CGAL/cgal/issues/2575#issuecomment-343133446) in particular for the band-aid fix. Your case works when using that fix.

**Comment by lrineau** [comment]
Duplicate of #2575.
