### ISSUE TITLE
Polygon_with_holes_2 difference fails for valid input polygons with holes

### ISSUE THREAD

**Issue by ben243871694** [CGAL/cgal#3747]
## Issue Details

I try to compute an intersection on polygons with holes. 
- The first polygon (from which we subtract) has two holes, one of which is intersecting the outline at one vertex. 

<img width="214" alt="screenshot 2019-03-08 at 12 05 39" src="https://user-images.githubusercontent.com/26392770/54025378-a1fd1e80-419a-11e9-9f48-a5f76c8c024c.png">

- The second polygon (which we subtract) intersects the hole which is touching the outline at one vertex and it intersects the other hole of the first polygon at two vertices.

![screenshot 2019-03-08 at 12 01 19](https://user-images.githubusercontent.com/26392770/54025382-a4f80f00-419a-11e9-85fe-0f52f271a4ff.png)

Both polygons are valid polygons with holes.

It fails with the error:

> CGAL error: assertion violation!
> Expression : h->flag()!=NOT_VISITED
> File       : /usr/local/include/CGAL/Boolean_set_operations_2/Gps_on_surface_base_2.h
> Line       : 1207
> Explanation: 
> Refer to the bug-reporting instructions at https://www.cgal.org/bug_report.html
> libc++abi.dylib: terminating with uncaught exception of type CGAL::Assertion_exception: CGAL ERROR: assertion violation!
> Expr: h->flag()!=NOT_VISITED
> File: /usr/local/include/CGAL/Boolean_set_operations_2/Gps_on_surface_base_2.h
> Line: 1207
> Abort trap: 6

I'm assuming that when the input is valid, CGAL should not fail because the operations will produce valid polygons again since those polygon(-sets) are closed under these operations. Am I doing something wrong?

## Source Code
```
#include <sstream>
#include <iterator>

#include <CGAL/Exact_predicates_exact_constructions_kernel.h>
#include <CGAL/Boolean_set_operations_2.h>

typedef CGAL::Exact_predicates_exact_constructions_kernel Kernel;
typedef CGAL::Polygon_with_holes_2<Kernel>                Polygon_with_holes_2;
typedef std::list<Polygon_with_holes_2>                   Pwh_list_2;

int main() {
  std::stringstream ps("4  -2 2  -2 -2  2 -2  2 2  2  3  -2 -2  -1 1  -1 -1  3  0 -1  0 1  1 1");
  Polygon_with_holes_2 P;
  ps >> P;

  std::stringstream qs("3  0 -1  0 1  -1 1  0");
  Polygon_with_holes_2 Q;
  qs >> Q;

  Pwh_list_2 result;
  CGAL::difference(P, Q, std::back_inserter(result));

  return 0;
}
```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): MacOS 10.14
* Compiler: clang/LLVM
* Release or debug mode: Release
* Specific flags used (if any):
* CGAL version: 4.13 stable (via homebrew)
* Boost version: 1.68.0_1
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by sloriot** [comment]
The patch in https://github.com/CGAL/cgal/pull/3774 should fix the issue.
