### ISSUE TITLE
CGAL::optimal_convex_partition_2 failure!

### ISSUE THREAD

**Issue by wzmBeiJing** [CGAL/cgal#3750]
_Please use the following template to help us solving your issue._

## Issue Details
CGAL::optimal_convex_partition_2 failure.and output the log:
64 16 hides 96 16 from 48 16
80 40 hides 88 32 from 72 48
80 40 hides 96 24 from 72 48
88 32 hides 96 24 from 80 40
88 24 hides 88 32 from 88 8
88 32 hides 88 48 from 88 8
88 32 hides 88 48 from 88 24
88 48 hides 88 80 from 88 8
88 48 hides 88 80 from 88 24
88 48 hides 88 80 from 88 32
80 40 hides 80 104 from 80 32
80 104 hides 80 128 from 80 32
80 104 hides 80 128 from 80 40
72 80 hides 72 104 from 72 40

## Source Code
```
#define CGAL_PARTITION_BRUTE_FORCE_FIX

#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/Partition_traits_2.h>
#include <CGAL/partition_2.h>
#include <CGAL/point_generators_2.h>
#include <CGAL/random_polygon_2.h>

#include <fstream>
#include <iostream>
#include <sstream>

typedef CGAL::Exact_predicates_inexact_constructions_kernel K;
typedef CGAL::Partition_traits_2<K> Traits;
typedef Traits::Point_2 Point_2;
typedef Traits::Polygon_2 Polygon_2;
typedef Polygon_2::Vertex_iterator Vertex_iterator;
typedef std::list<Polygon_2> Polygon_list;
typedef CGAL::Creator_uniform_2<int, Point_2> Creator;
typedef CGAL::Random_points_in_square_2< Point_2, Creator > Point_generator;

void make_polygon_1(Polygon_2& polygon)
{
  polygon.push_back(Point_2(1.4, -4.2));
  polygon.push_back(Point_2(1.4, -3.4));
  polygon.push_back(Point_2(-0.2, -3.4));
  polygon.push_back(Point_2(-0.2, 7.8));
  polygon.push_back(Point_2(3, 7.8));
  polygon.push_back(Point_2(3, 5.4));
  polygon.push_back(Point_2(2.2, 5.4));
  polygon.push_back(Point_2(2.2, 3));
  polygon.push_back(Point_2(3.8, 3));
  polygon.push_back(Point_2(3.8, -0.2));
  polygon.push_back(Point_2(2.2, -0.2));
  polygon.push_back(Point_2(2.2, -1.0));
  polygon.push_back(Point_2(3, -1.0));
  polygon.push_back(Point_2(3, -1.8));
  polygon.push_back(Point_2(3.8, -1.8));
  polygon.push_back(Point_2(3.8, -2.6));
  polygon.push_back(Point_2(4.6, -2.6));
  polygon.push_back(Point_2(4.6, -3.4));
  polygon.push_back(Point_2(3.8, -3.4));
  polygon.push_back(Point_2(3.8, -4.2));
}

void make_polygon_2(Polygon_2& polygon)
{
  polygon.push_back(Point_2(64, 8));
  polygon.push_back(Point_2(64, 16));
  polygon.push_back(Point_2(48, 16));
  polygon.push_back(Point_2(48, 128));
  polygon.push_back(Point_2(80, 128));
  polygon.push_back(Point_2(80, 104));
  polygon.push_back(Point_2(72, 104));
  polygon.push_back(Point_2(72, 80));
  polygon.push_back(Point_2(88, 80));
  polygon.push_back(Point_2(88, 48));
  polygon.push_back(Point_2(72, 48));
  polygon.push_back(Point_2(72, 40));
  polygon.push_back(Point_2(80, 40));
  polygon.push_back(Point_2(80, 32));
  polygon.push_back(Point_2(88, 32));
  polygon.push_back(Point_2(88, 24));
  polygon.push_back(Point_2(96, 24));
  polygon.push_back(Point_2(96, 16));
  polygon.push_back(Point_2(88, 16));
  polygon.push_back(Point_2(88, 8));
}

void make_polygon_3(Polygon_2& polygon)
{
  polygon.push_back(Point_2(391, 374));
  polygon.push_back(Point_2(240, 431));
  polygon.push_back(Point_2(252, 340));
  polygon.push_back(Point_2(374, 320));
  polygon.push_back(Point_2(289, 214));
  polygon.push_back(Point_2(134, 390));
  polygon.push_back(Point_2( 68, 186));
  polygon.push_back(Point_2(154, 259));
  polygon.push_back(Point_2(161, 107));
  polygon.push_back(Point_2(435, 108));
  polygon.push_back(Point_2(208, 148));
  polygon.push_back(Point_2(295, 160));
  polygon.push_back(Point_2(421, 212));
  polygon.push_back(Point_2(441, 303));
}

int main()
{
  Polygon_2 polygon;
  Polygon_list partition_polys;
  Traits partition_traits;

  make_polygon_3(polygon);

  if(polygon.is_clockwise_oriented())
    polygon.reverse_orientation();

  std::ofstream out("input_polygon.cgal");

  out << polygon.size()+1 << "\n";
  for(const auto& pt : polygon.container())
    out << pt << " 0\n";
  out << polygon.container().front() << " 0\n";

  CGAL::optimal_convex_partition_2(polygon.vertices_begin(),
                                   polygon.vertices_end(),
                                   std::back_inserter(partition_polys),
                                   partition_traits);

  std::cout << "partition_polys_size:" << partition_polys.size() << std::endl;

  assert(CGAL::convex_partition_is_valid_2(polygon.vertices_begin(),
                                           polygon.vertices_end(),
                                           partition_polys.begin(),
                                           partition_polys.end(),
                                           partition_traits));

  int id = 0;
  for(const Polygon_2& pl : partition_polys)
  {
    std::stringstream oss;
    oss << "partition_polygon_" << id++ << ".cgal" << std::ends;
    std::ofstream out(oss.str().c_str());

    out << pl.size()+1 << "\n";
    for(const auto& pt : pl.container())
      out << pt << " 0\n";
    out << pl.container().front() << " 0\n";
  }

  return 0;
}

```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):linux 64bits
* Compiler:gcc
* Release or debug mode:
* Specific flags used (if any):
* CGAL version:4.13
* Boost version:1.58
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by MaelRL** [comment]
The input polygon you had in your code snipplet was not simple nor well oriented. It also seemed to be three polygons that have nothing to do with each other. If I separate them into three distinct polygons and fix the orientation, the algorithm runs fine.

**Comment by MaelRL** [comment]
I have cleaned your code into something that gives correct inputs to the program, see your origin message at the top of this thread.

**Comment by wzmBeiJing** [comment]
> I have cleaned your code into something that gives correct inputs to the program, see your origin message at the top of this thread.

i got it !thanks !

**Comment by wzmBeiJing** [comment]
> I have cleaned your code into something that gives correct inputs to the program, see your origin message at the top of this thread.

Hi,if i want to use the function"optimal_convex_partition_2" to decompose the polygon with holes.how to do?
thanks!

**Comment by rikba** [comment]
Hi @wzmBeiJing 

> Hi,if i want to use the function"optimal_convex_partition_2" to decompose the polygon with holes.how to do?

I use [CGAL::connect_holes](https://doc.cgal.org/latest/Boolean_set_operations_2/group__boolean__connect__holes.html#ga0c649fa14a7f93957b231d9a6bee29ae) to first convert the polygon with holes into a polygon without holes. Using the convex decomposition on this polygon still fails. It seems to have problems with those nexly generated edges from connecting the holes. Thus I offset the polygon by a tiny bit using [CGAL::create_interior_skeleton_and_offset_polygons_with_holes_2](https://doc.cgal.org/latest/Straight_skeleton_2/group__PkgStraightSkeleton2Functions.html#gac7686e47d2573e95dcca775d2525d51c) to remove those overlapping new edges.

Unfortunately, the offsetting process changes the polygon which is undesired in my case and I'd also be interested to perform the decomposition either directly on a polygon with holes or on the polygon without holes without offsetting.

**Comment by rikba** [comment]
> Unfortunately, the offsetting process changes the polygon which is undesired in my case and I'd also be interested to perform the decomposition either directly on a polygon with holes or on the polygon without holes without offsetting.

The brute force fix commented in https://github.com/CGAL/cgal/issues/2575 fixes the convex decomposition right after converting a polygon with holes into a polygon without holes.
