### ISSUE TITLE
Formula (?) in Periodic_2_triangulation_2

### ISSUE THREAD

**Issue by albert-github** [CGAL/cgal#3751]
## Issue Details

In the file: `Periodic_2_triangulation_2/doc/Periodic_2_triangulation_2/CGAL/Periodic_2_triangulation_2.h` there is 4 times the construct: `\pre $0 \\leqle i \\leqle 2$`, this probably has to be `\pre \f$0 \leq i \leq 2\f$` ( and this does work in a `\pre`, tested for 1.8.13) or `\pre \f$ i \in\{0,1,2\}\f$` as used with `periodic_point`.

**Comment by lrineau** [comment]
Fixed by #3769.
