### ISSUE TITLE
(X)HTML warning after documentation post processing (member-group)

### ISSUE THREAD

**Issue by albert-github** [CGAL/cgal#3755]
## Issue Details

During the post processing phase of `make doc_with_postprocessing` (X)HTML anchors of the form `<a name="member-group"></a>` are changed into `<a name="member-group" id="member-group"></a>`
This can (and does) lead to warning messages like:
```
: element a: validity error : ID member-group already defined
<td colspan="2"><h2 class="groupheader"><a name="member-group" id="member-group"
                                                                               ^
ID member-group already defined
```
I searched the output directory by means of `grep -n -r "member-group" doc_output | sed -e 's/<a name="member-group" id="member-group"><.a>//' | grep "member-group" but this didn't give any hit, so there is (as far as I can see) no reference to the "member-group" 'id' and thus the substitution is not necessary.

Unfortunately I have not been able to find the place where the substitution is done and thus I cann't give a suggestion for improvement.

**Comment by sloriot** [comment]
I could found some cases.
Is `member-group` the only issue or for example the following also an issue?
```
Minkowski_sum_2/classCGAL_1_1Small__side__angle__bisector__decomposition__2.html:135:<a name="details" id="details"></a><h2 class="groupheader">Definition</h2>
```

We can use `removeAttr("id");` if `name` is present and identical to fix that.

**Comment by albert-github** [comment]
The details is also an issue, but this is handled in #3754

**Comment by lrineau** [comment]
This bug is an upstream bug in Doxygen.

Take the file `doc_output/AABB_tree/classCGAL_1_1AABB__tree.html` created by Doxygen from `AABB_tree/include/CGAL/AABB_tree.h`. Each time there is a new group, such as:
```
    /// \name Types
    ///@{
```
then Doxygen creates a heading, with a `<a>` tag:
```
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="member-group"></a>
Types</h2></td></tr>
```
and **that** is the bug: in a given HTML file, it is invalid to have multiple `<a>` tags with the same `name` attribute.

Pyquery adds an `id` attribute to the `<a>` tag, copied from the `name` attribute. And that is valid. But that produces an invalid XHTML file, because the `name` attributes were not unique.

**Comment by albert-github** [comment]
@lrineau Normally I run `make doc` (when necessary twice) to generate the documentation, but is it possible to run just `doxygen` on all projects or on a single project?

**Comment by lrineau** [comment]
> @lrineau Normally I run `make doc` (when necessary twice) to generate the documentation, but is it possible to run just `doxygen` on all projects or on a single project?

You can run `make <pkg>_doc`, `make AABB_tree_doc` for example.

**Comment by albert-github** [comment]
Interesting and good to know, looks like it just does the doxygen call and the copy of the tag file.
Looks like the target doc does the same. So no pre / or postprocessing at all.

**Comment by sloriot** [comment]
Albert, will you make a patch to doxygen? If yes, shall we close this ticket?

**Comment by albert-github** [comment]
@sloriot In the back of my head I had the idea that I did something about it a while ago, so I searched the doxygen pull requests and found it again: doxygen/doxygen#6620. It might be good to ping (@doxygen) this pull request from the CGAL side as well.
