### ISSUE TITLE
(X)HTML validation error on multiple defined macro

### ISSUE THREAD

**Issue by albert-github** [CGAL/cgal#3756]
## Issue Details
I the files:
```
Arrangement_on_surface_2/doc/Arrangement_on_surface_2/CGAL/Arr_polycurve_traits_2.h
Arrangement_on_surface_2/doc/Arrangement_on_surface_2/CGAL/Arr_polyline_traits_2.h
```
we have the construct (note in both cases it speaks about 'curves'):
```
/// \ingroup PkgArrangementOnSurface2Macros
/// @{
/*!
 * If the macro is set to one, then \f$x\f$-monotone curves are always
 * directed from left-to-right.
 */
#define CGAL_ALWAYS_LEFT_TO_RIGHT
/// @}
```
running the (X)HTML checker on this results in:
```
doc_output/Arrangement_on_surface_2/group__PkgArrangementOnSurface2Macros.html:174: element a: validity error : ID gafe0299480c1e86ecbb89465252046f70 already defined
<a id="gafe0299480c1e86ecbb89465252046f70"></a>
                                          ^
ID gafe0299480c1e86ecbb89465252046f70 already defined
Document doc_output/Arrangement_on_surface_2/group__PkgArrangementOnSurface2Macros.html does not validate
```
and in the documentation it looks like:
![macros](https://user-images.githubusercontent.com/5223533/54084582-d1469380-4332-11e9-9ae5-8ef230553daf.jpg)

The `CGAL_ALWAYS_LEFT_TO_RIGHT` are compilation directives and have been added so a reference and some explanation is possible.

## Solution Suggestion
Create a new `.h` file (e.g. `Arr_compile_macros.h`) in `Arrangement_on_surface_2/doc/Arrangement_on_surface_2/CGAL/` directory with the definition of the macro and some explanation and remove the macro from the current files.

**Comment by lrineau** [comment]
Fixed by #3769.
