### ISSUE TITLE
Color array output support

### ISSUE THREAD

**Issue by ZoomDomain** [CGAL/cgal#376]
I think it would be easily possible for CGAL to support colored per triangle outputs. I am not that technical so I can only suppose, that you only can copy the input color of a block to the output color of the constituent triangles, and the result is that every triangle in the output would have a 1:1 array of colors?

This would be very useful in the age of color 3d printers, which are going to be a big thing this year, and i can already print 3d color objects if i could make the color mesh via CGAL, which i love. 

I build objects in CGAL with 1000 and even 4000 parts (because i only have a 32 bit pc this year) and it is impossible to color 4000 parts again after CGAL has merged them. it would be good for the future.

**Comment by ZoomDomain** [comment]
x3d format supports color per triangle files, so everything is in place to have color CGAL generated forms.

**Comment by sloriot** [comment]
What data structure are you talking about?

**Comment by ZoomDomain** [comment]
I mean about Nef Polygon and Nef Polyhedra colors. For example, there is a picture on the Nef Polyhedra overview page of a colored object made using CGAL.  ![color image](http://doc.cgal.org/latest/Manual/logo-lcc-small.png) 

Is it possible to color output mesh based on input mesh colors as in l'example de couleur?

**Comment by sloriot** [comment]
I don't think it is easy to put color that would be preserved by boolean operations with the current code of Nef.

**Comment by sgiraudot** [comment]
As @sloriot pointed out, the current code of Nef is not adapted to preserve colors with boolean operations. As it doesn't seem reasonable to assume this feature will be implemented anytime soon, I am closing the issue.
