### ISSUE TITLE
CGAL header-only error: undefined reference to `boost::detail::get_tss_data(void const*)'

### ISSUE THREAD

**Issue by marlinilram** [CGAL/cgal#3760]
_Please use the following template to help us solving your issue._

## Issue Details

I'm trying to use create_interior_skeleton_and_offset_polygons_with_holes_2, it returns a vector of boost::shared_ptr<Polygon_with_holes_2>. On my mac, when the program exits, it prompts error like 

dyld: lazy symbol binding failed: Symbol not found: __ZN5boost6detail12get_tss_dataEPKv 
dyld: Symbol not found: __ZN5boost6detail12get_tss_dataEPKv 

And I tried to compile it on centos 7 with gcc 4.8.5, it also has link error 

/usr/include/boost/thread/tss.hpp:84: undefined reference to `boost::detail::get_tss_data(void const*)' 

## Source Code

 ```
  double offset = 0.5;
  Polygon_2 outer ;
  outer.push_back( Point( 3, 0 ) );
  outer.push_back( Point( 3, 3 ) );
  outer.push_back( Point( 0, 3 ) );
  outer.push_back( Point( 0, 0 ) );  
  Polygon_2 hole ;
  hole.push_back( Point( 1, 1 ) );  
  hole.push_back( Point( 1, 2 ) );
  hole.push_back( Point( 2, 2 ) );
  hole.push_back( Point( 2, 1 ) );
  PolygonWithHoles poly( outer ) ;
  poly.add_hole( hole ) ;
  PolygonWithHolesPtrVector offset_polys = CGAL::create_interior_skeleton_and_offset_polygons_with_holes_2(offset, poly);

```
## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Mac and CentOS 7
* Compiler: LLVM 10.0.0 on Mac, gcc 4.8.5 on CentOS
* Release or debug mode: debug
* Specific flags used (if any): CMAKE_CXX_FLAGS "-g -Wall -std=c++11 -fPIC"
* CGAL version: 4.13
* Boost version: 1.68.0 on Mac, 1.53.0 on centos 7
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by lrineau** [comment]
Hi Lin,

All the errors you get on various platforms are consistent: as your program uses CGAL_Core, you must link it with the Boost Thread library.

**Comment by marlinilram** [comment]
Hi @lrineau , can you give me some clues about how to config CGAL to not to depend on boost thread lib? Thanks!

**Comment by lrineau** [comment]
`CGAL_Core` requires Boost Thread. There is not way to config it differently. Unless you compile with `-DCGAL_HAS_NO_THREADS`.
