### ISSUE TITLE
Crash in CGAL::Polygon_mesh_processing::clip

### ISSUE THREAD

**Issue by charlieqc** [CGAL/cgal#3763]
## Issue Details

CGAL crashed (Release mode, exception in Debug mode) when clipping my surface mesh.
CGAL::Polygon_mesh_processing::does_self_intersect(mesh) returns true on my mesh, so there are self-intersections somewhere. The self-intersections should be slight since I could not see it when I rendered my surface on the screen. I don't know if there any relation between the crash and self-intersection. I am just providing clues I much as I know.

The input surface OFF file can be found at the link below:
https://drive.google.com/file/d/1-67Xa-K0oypF-fwzA0gLF970q3TWak4s/view?usp=sharing

## Source Code

#include <fstream>

#if _MSC_VER
#pragma warning(push)
#pragma warning(disable : 4456 4702)
#endif

#include <CGAL/Exact_predicates_exact_constructions_kernel.h>
#include <CGAL/Polygon_mesh_processing/clip.h>
#include <CGAL/Polygon_mesh_processing/repair.h>
#include <CGAL/Surface_mesh.h>

#if _MSC_VER
#pragma warning(pop)
#endif

using EK = CGAL::Exact_predicates_exact_constructions_kernel;
using Mesh = CGAL::Surface_mesh<EK::Point_3>;
using Plane = EK::Plane_3;
namespace PMP = CGAL::Polygon_mesh_processing;

int test()
{
   Mesh mesh;
   std::ifstream ostream_off_file("D:/test_surface.off");
   bool succeed = CGAL::read_off(ostream_off_file, mesh);
   if (!succeed) {
      return -1;
   }

   Plane plane(0.0, 1.0, 0.0, -12750.0);
   try {// there was a crash(assertion failure) deep in PMP::clip
      PMP::clip(mesh, plane, PMP::parameters::clip_volume(false));
   } catch (...) {// exception caught in Debug mode
      throw std::exception("PMP::clip crashed due to assertion failure");
   }

   return 0;
}

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows 64 bit
* Compiler: Visual Studio 2017 MSVC
* Release or debug mode: crash in Release and exception in Debug
* Specific flags used (if any):
* CGAL version: 4.13
* Boost version: 1.68
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by sloriot** [comment]
The error is due to the self-intersection.
The self-intersection comes from a degenerate triangle.
 If you add `#include <CGAL/Polygon_mesh_processing/repair.h>` and call `PMP::remove_degenerate_faces(mesh);` (non-officially documented for now) it will work.
Note that with the following call `PMP::clip(mesh, plane, PMP::parameters::throw_on_self_intersection(true));` you would have seen an exception due to the self-intersection.

**Comment by charlieqc** [comment]
@sloriot
Thanks a lot for your non-officially solution. I added PMP::remove_degenerate_faces(mesh); right before my PMP::clip and it worked well. I'll keep you posted if I have follow-up questions.
