### ISSUE TITLE
CGAL Boolean Model

### ISSUE THREAD

**Issue by HzDexplorer** [CGAL/cgal#3776]
## Issue Details

Hello, I can't use this demo to solve my problem. It kept reporting mistakes.Please help me, thank you.

## Source Code

It's in the package.And there are two file with obj format in it.

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):64
* Compiler:VS2017
* Release or debug mode:debug
* Specific flags used (if any):Perhaps no.
* CGAL version: -4.13
* Boost version: -1.68.0
* Other libraries versions if used (Eigen, TBB, etc.): -version 3.0

[here is the code][url]，It has more than 10mb of memory，thanks

[url]: https://drive.google.com/open?id=19g4OrMtYGqcwFxy6Di21V-3-fgJrIG0Q

**Comment by afabri** [comment]
The link to "here is the code" does not work.   Also can you please put code on gist.github.com.

**Comment by lrineau** [comment]
Your zip file ships CGAL-4.7. We no longer support that version of CGAL.
