### ISSUE TITLE
Bug while checking filename format in Seam_mesh::add_seams

### ISSUE THREAD

**Issue by dominik-mokris-mtu** [CGAL/cgal#3782]
Hello everyone, I believe I have found a little bug.

## Issue Details

Function `Seam_mesh::add_seams(const char* filename, const VdContainer& tm_vds)` assumes `filename` to be of the form `*.selection.txt`. When called with a sufficiently long `filename`, a reasonable error message is printed:

    > ./CGAL-4.13-build/examples/Surface_mesh_parameterization/seam_Polyhedron_3 surface.off very_long_filename.txt
    Error: seams must be given by a *.selection.txt file

However, when `filename` is too short, CGAL crashes:

    > ./CGAL-4.13-build/examples/Surface_mesh_parameterization/seam_Polyhedron_3 surface.off short.txt
    terminate called after throwing an instance of 'std::out_of_range'
      what():  basic_string::substr
    Aborted

## Source Code

The culprit seems to be the line 1078 in `include/CGAL/boost/graph/Seam_mesh.h`:

     if(str.substr(str.length() - 14) != ".selection.txt") {

Instead, the correct check (in my view) would be something like

     if(str.length() < 14 || str.substr(str.length() - 14) != ".selection.txt") {

However, I would go as far as questioning whether the requirement on `filename` to be of the form `*.selection.txt` is really necessary. After all, we just need a text file with space-separated non-negative integers. Whether it's called `seams.selection.txt` or `seams.txt` or even `numbers.abc` seems irrelevant to the problem in question.

If there is a reason for it, I would recommend mentioning the requirement in the documentation as well.

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Linux 64 bits
* Compiler: g++
* Release or debug mode: Release
* Specific flags used (if any):
* CGAL version: 4.13
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by afabri** [comment]
Thank you @dominik-mokris-mtu for pointing this out.  We want to stick to the file extension, even if you are right that even  `abc.pdf` would work.  We agree that we might better document CGAL-proprietary file formats.

**Comment by dominik-mokris-mtu** [comment]
Good! I have just noticed the same problem in `examples/Surface_mesh_parameterization/square_border_parameterizer.cpp` on line 44, so a more systematic search might be required.

**Comment by lrineau** [comment]
Closed by #3783.
