### ISSUE TITLE
cgal-4.13 compilation error

### ISSUE THREAD

**Issue by yxmanfred** [CGAL/cgal#3790]
cgal-4.13 compilation error

Error C2679 binary '=': no operator found which takes a right-hand operand of type 'const CGAL::Triangulation_simplex_3<CGAL::Regular_triangulation_3<CGAL::Skin_surface_traits_3<K,true>,CGAL::Default,CGAL::Default>>' (or there is no acceptable conversion)	skin_surface_simple	h:\cgal-4.13\cgal-4.13\include\cgal\triangulated_mixed_complex_observer_3.h	131	

Error C2679 binary '=': no operator found which takes a right-hand operand of type 'const CGAL::Triangulation_simplex_3<CGAL::Regular_triangulation_3<CGAL::Skin_surface_traits_3<K,true>,CGAL::Default,CGAL::Default>>' (or there is no acceptable conversion)	skin_surface_subdiv_with_normals	h:\cgal-4.13\cgal-4.13\include\cgal\triangulated_mixed_complex_observer_3.h	131	

Error C2679 binary '=': no operator found which takes a right-hand operand of type 'const CGAL::Triangulation_simplex_3<CGAL::Regular_triangulation_3<CGAL::Skin_surface_traits_3<K,true>,CGAL::Default,CGAL::Default>>' (or there is no acceptable conversion)	skin_surface_subdiv	h:\cgal-4.13\cgal-4.13\include\cgal\triangulated_mixed_complex_observer_3.h	131	

Error C2679 binary '=': no operator found which takes a right-hand operand of type 'const CGAL::Triangulation_simplex_3<CGAL::Regular_triangulation_3<CGAL::Skin_surface_traits_3<K,true>,CGAL::Default,CGAL::Default>>' (or there is no acceptable conversion)	union_of_balls_simple	h:\cgal-4.13\cgal-4.13\include\cgal\triangulated_mixed_complex_observer_3.h	131	

Error C2679 binary '=': no operator found which takes a right-hand operand of type 'const CGAL::Triangulation_simplex_3<CGAL::Regular_triangulation_3<CGAL::Skin_surface_traits_3<K,true>,CGAL::Default,CGAL::Default>>' (or there is no acceptable conversion)	union_of_balls_subdiv	h:\cgal-4.13\cgal-4.13\include\cgal\triangulated_mixed_complex_observer_3.h	131	

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):windows 64bits
* Compiler: Visual Studio 2017
* Release or debug mode: debug and release
* Specific flags used (if any):
* CGAL version:4.13
* Boost version:1.63
* Other libraries versions if used (Eigen, TBB, etc.):eigen3

**Comment by sloriot** [comment]
What did you try to compile?

**Comment by MaelRL** [comment]
Bump @yxmanfred
