### ISSUE TITLE
Missing gmpxx.h in installer for Windows

### ISSUE THREAD

**Issue by bansan85** [CGAL/cgal#3795]
## Issue Details
Installer CGAL-4.14-beta2 for Windows do not embedded gmpxx.h. I think it should be.

I had to download gmp-5.0.1 and copy gmpxx.h to C:\dev\CGAL-4.14-beta2.64\auxiliary\gmp\include

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows 10
* CGAL version: 4.14-beta2

**Comment by lrineau** [comment]
No. We have decided not to support GMPXX on Windows, because the upstream GMP project does not support the Microsoft VC++ compiler. So we compiled GMP with MINGW, using the binary compatibility of the C ABI of the two compilers. But I do not know if nowdays the MINGW has a compatible C++ ABI.

**Comment by bansan85** [comment]
Thanks for the fast answer. I asked because I wanted to use the library libigl. Due to dependencies in theirs headers, I needed to have gmpxx.h. I successfully compile my code with gmpxx.h and without gmpxx.lib. So I wrongly thought you merged both .lib into one file.
