### ISSUE TITLE
Can CGAL generate 3d models automatically based on the vertexs?

### ISSUE THREAD

**Issue by GisKook** [CGAL/cgal#38]
Hello,
I have a demand.I hope I can generate 3d models automatically based on vertexs.Do CGAL helps?
Thanks,
zhangkai

**Comment by janetournois** [comment]
Hi Zhangkai,

what type of models would you like to generate?
You can for example compute the Delaunay triangulation of your vertices.

Jane.

**Comment by sloriot** [comment]
Please post on [cgal-discuss](http://www.cgal.org/mailing_list.html) as this is not an issue but a question.

Thanks.

**Comment by GisKook** [comment]
Hello Jane,
I want to generate a *.obj file.Does CGAL support Delaunay triangulation ?Or Is there a 3rd-party-library which had implemented Delaunay triangulation ?
Thanks,
Zhangkai

At 2015-04-07 15:43:22, "Jane Tournois" <notifications@github.com> wrote:
Hi Zhangkai,

what type of models would you like to generate?
You can for example compute the Delaunay triangulation of your vertices.

Jane.
