### ISSUE TITLE
Improve sharing of a demo setting

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#3802]
Right now sharing a complex scene (say more that one file) is complicated.
One step that would simplify that is to have an option to make the scene script file embed the files instead of pointing to existing local files.

If we go one step further, we could even imagine having a way to make the demo host the file online (gist/pastebin/...) so that we could share a URL that you open in the demo and get the scene loaded directly on the fly.

While writing that, I wonder whether we could not even have a way to _connect_ to another demo to get the current camera position to make 1 user remotely showing something.

**Comment by MaelRL** [comment]
In very minor:
- save script and load script should be next to each other in the menu
- the save script does not give an extension to the file, but the load script expects one (dunno which one)

**Comment by lrineau** [comment]
Pushing to a web service (like Gist) is usually just an HTTP POST request, but all the complexity is in the authentication scheme that has to be used before. For Gist, for example, that would require the user to setup a Github OAuth token for the application. And Gist limits the file size to 1MB, a least in the API.

**Comment by sloriot** [comment]
#3838 might be worth investigating for a possible base of the scene export.

**Comment by sloriot** [comment]
Here is how atom handle the sharing/collaboration
https://teletype.atom.io/
