### ISSUE TITLE
Improve doc for basic viewers

### ISSUE THREAD

**Issue by gdamiand** [CGAL/cgal#3803]
_Please use the following template to help us solving your issue._

## Issue Details

Add a chapter in CGAL manual; section Visualization, to explain the basic viewer.

Maybe during the next GSoc ?

**Comment by jingyangcarl** [comment]
Hi, Guillaume Damiand,

This is Jing Yang, I wonder if this refers to GSoC 2019 "Basic in Viewers in CGAL", which is to develop basic viewers for the data structure without a viewer?

Jing Yang

**Comment by sloriot** [comment]
there is now a full package
