### ISSUE TITLE
Polyhedron demo : zoom is reset each time "view" is on/off/on

### ISSUE THREAD

**Issue by janetournois** [CGAL/cgal#3809]
## Issue Details

Here is the problem I have with the demo :
- open two files (2 `.off` or 2 `.mesh`, or mixed, have the same issue)
- zoom to something of interest
- click (set to false) "view" for one of them : it gets hidden
- click (set to true) "view" for the same one : it comes back, but the zoom is reset to its default position (there is no rotation though)

@maxGimeno can you please have a look?

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows
* Compiler: msvc 2017
* Release or debug mode: Release
* CGAL version: master

**Comment by maxGimeno** [comment]
You can disable this behavior by un-checking the Visibility Changes Recenter option in Edit->Preferences.

I'll set the default behavior to false.

**Comment by janetournois** [comment]
Thank you!
(indeed imho the default behavior should be "false")
