### ISSUE TITLE
2D Convex hull of indices

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#3813]
Using the code given here:
https://stackoverflow.com/questions/43682852/cgal-convex-hull-of-points-with-info/43732224?noredirect=1#comment97521387_43732224

provide an integrated solution to get the convex hull of anything using a point property map
(traits with property like in spatial sorting for example).

**Comment by afabri** [comment]
A funny coincidence with what I do  for Partition in PR #3826.   Let's bundle forces, even if it still will have at least twice the number of lines than in libigl @alecjacobson  ==:>-

**Comment by afabri** [comment]
Is there a C++11 way to fill a vector with values 0..... n-1 ?  In CGAL examples I saw the boost::Counting_iterator.  I just found the [`boost::repeat_fun()`](https://www.boost.org/doc/libs/1_63_0/libs/assign/doc/index.html#repeat).  Or is a good old C style for loop just fine?
