### ISSUE TITLE
Missing demo zip files for CGAL-4.14 (referenced in documentation)

### ISSUE THREAD

**Issue by albert-github** [CGAL/cgal#3817]
## Issue Details
In the file: `Hyperbolic_triangulation_2/doc/Hyperbolic_triangulation_2/PackageDescription.txt` the file `https://www.cgal.org/demo/4.14/Hyperbolic_Delaunay_triangulation_2.zip` is referenced, but it does not exist

In the file: `Periodic_4_hyperbolic_triangulation_2/doc/Periodic_4_hyperbolic_triangulation_2/PackageDescription.txt` the file `https://www.cgal.org/demo/4.14/Periodic_4_hyperbolic_Delaunay_triangulation_2.zip` is referenced, but it does not exist

I see the files `constrained_delauney_triangulation_2.zip`, `demo_delauney_triangulation_2.zip` and `delauney_triangulation_2.zip` on the directory `https://www.cgal.org/demo/` but no idea which one belongs where.

**Note**
- that also all 3.* and 4.* versions, except the 3.4 version, map to the same file set
- that the current master (own build) points to 5.0 (e.g. https://www.cgal.org/demo/5.0/CGAL-demoDLLs.zip) but this version does not exist

**Comment by afabri** [comment]
@maxGimeno please fix

**Comment by albert-github** [comment]
Complete version 5.0 still does not exist, they should be accessible for the master version (e.g. from https://cgal.geometryfactory.com/CGAL/doc/master/Manual/packages.html#PartKernels).

**Comment by maxGimeno** [comment]
The fix for the missing demos has only been integrated 4 days ago. We are waiting for a master run that will compile them to get the result and ship it. It should be done by next Wednesday.

**Comment by albert-github** [comment]
@maxGimeno. @lrineau 
- <strike>Reaching the files to download took very long, looks like to be OK again.</strike>
- I could not reach https://www.cgal.org/demo/4.14/Hyperbolic_Delaunay_triangulation_2.zip, https://www.cgal.org/demo/4.14/Periodic_4_hyperbolic_Delaunay_triangulation_2.zip
- The 5.0 files are still not reachable, probably the 5.0 directory does not exist yet.

**Comment by maxGimeno** [comment]
The files are in [a PR for cgal-web]( https://github.com/CGAL/cgal-web/pull/75)
When it is merged, it should be available from the doc page

**Comment by albert-github** [comment]
- the mentioned pull request I cannot access (as it is probably in a non-public repository), any idea when this will be integrated (message from April 12, 209 indicated that it would be present on April 18, 2019).
- 5.0 directory: this means that documents cannot be validated, for the 4.14 release this was present long before the release (of course the 5.0 is a major release so there might be incompatibilities so old versions are not possible. Maybe a dummy link / file is a solution, a 404 message is a bit of a harsh message).

**Comment by maxGimeno** [comment]
- It should be integrated next week at worst.
- Then I guess I was wrong and it will be taken care of shortly. Maybe next week.

**Comment by maxGimeno** [comment]
the 5.0 directory shouldn't be necessary, the server searches for the latest existing files for the corresponding demo. It doesn't exist for the hyperbolic_triangulation demos, but it should work for all the others.

**Comment by albert-github** [comment]
I just tried: https://www.cgal.org/demo/5.0/circular_kernel.zip and get a 404 message. Link is from page https://cgal.geometryfactory.com/CGAL/Manual_doxygen_test/CGAL-5.0-Ic-15/master/Manual/packages.html the Windows Demo of 2D Circular Geometry Kernel.

**Comment by maxGimeno** [comment]
You are right, and it is definitly a bug. We'll see with @lrineau when he gets back. We are currently merging the missing 4.14 demos.

**Comment by maxGimeno** [comment]
Merged. The hyperbolic triangulation demos are now accessible.

**Comment by albert-github** [comment]
Confirmed: The mentioned 2 files https://www.cgal.org/demo/4.14/Periodic_4_hyperbolic_Delaunay_triangulation_2.zip and https://www.cgal.org/demo/4.14/Hyperbolic_Delaunay_triangulation_2.zip are now accessible.

I'm going to checkout the 4.14 branch and will run my hated / loved link check on it.

**Comment by albert-github** [comment]
I ran the link checker over the current head of the 4.14 branch (i.e. 4.14.1): and have some problems with:
```
https://www.cgal.org/demo/4.14.1/boolean_operations_2.zip
https://www.cgal.org/demo/4.14.1/envelope_3.zip
https://www.cgal.org/demo/4.14.1/boolean_operations_2.zip
https://www.cgal.org/demo/4.14.1/partition_2.zip
https://www.cgal.org/demo/4.14.1/straight_skeleton_2.zip
https://www.cgal.org/demo/4.14.1/envelope_3.zip
https://www.cgal.org/demo/4.14.1/nef_2.zip
https://www.cgal.org/demo/4.14.1/nef_2.zip
https://www.cgal.org/demo/4.14.1/partition_2.zip
https://www.cgal.org/demo/4.14.1/straight_skeleton_2.zip
```
The ones I tested give:

> 
> The page isn’t redirecting properly
> 
> An error occurred during a connection to www.cgal.org. 

and is redirecting to e.g. `https://www.cgal.org/demo/3.5/nef_2.zip`

**Comment by maxGimeno** [comment]
I checked, you get the download and the error page. There must be a problem somewhere, probably the same one that won't redirect from the doc of CGAL 5.0... We'll see that next week.

**Comment by lrineau** [comment]
I close this issue, and create a new one for the remaining buggy links: #3888.
