### ISSUE TITLE
Textual literature reference (in documentation)

### ISSUE THREAD

**Issue by albert-github** [CGAL/cgal#3818]
## Issue Details
I the file `Hyperbolic_triangulation_2/package_info/Hyperbolic_triangulation_2/long_description.txt` I see a reference:

>         Mikhail Bogdanov, Olivier Devillers, and Monique Teillaud. Hyperbolic
>         Delaunay complexes and Voronoi diagrams made practical. Journal of
>         Computational Geometry, 5(1):56–85, 2014.
>         URL: https://hal.inria.fr/hal-00961390,
>         doi:10.20382/jocg.v5i1a4.
> 

Wouldn't it better to have here a bibtex reference as well?

**Comment by lrineau** [comment]
The file `long_description.txt` is supposed to be read by humans. The current content of the file seems right to me.

And the reference is already quoted in the user manual of the chapter:

https://doc.cgal.org/4.14/Hyperbolic_triangulation_2/index.html#HT2_Design
