### ISSUE TITLE
CGAL::Polygon_mesh_processing::remove_self_intersections mesthod crashes 

### ISSUE THREAD

**Issue by tlchoque** [CGAL/cgal#3823]
_Please use the following template to help us solving your issue._

## Issue Details
When I tried to remove self intersections of a mesh with  about 600K vertices, the method crashes, when I test it with Meshlab, it says it is 2-manifold but has sel intersections.

CGAL error: assertion violation! Expression : std::unique(side_points.begin(), side_points.end())==side_points.end() File repair.h Line : 1066

## Source Code

const char* filename1 = "data/topo.off";
	const char* filename2 = "data/solid.off";
	std::ifstream input(filename1);

	cout << "starting" << endl;
	Mesh mesh1, mesh2;
	if (!input || !(input >> mesh1))
	{
		std::cerr << "First mesh is not a valid off file." << std::endl;
		return 1;
	}
	input.close();
	input.open(filename2);
	if (!input || !(input >> mesh2))
	{
		std::cerr << "Second mesh is not a valid off file." << std::endl;
		return 1;
	}

	if (!CGAL::Polygon_mesh_processing::does_self_intersect(mesh1))
		std::cout << "not self intersection ";
	else std::cout << "self intersection ";

	cout << endl;

	//------------------
	CGAL::Polygon_mesh_processing::remove_self_intersections(mesh1, PMP::parameters::preserve_genus(false));
	std::cout << "end removing self intersections" << endl;
	fillHoles(mesh1);
	std::ofstream output("manifold.off");
	output << mesh1;
	output.close();
	std::cout << "end repairing"<<endl;
	//------------------

## Environment

Visual Studio 2017 64 bits

**Comment by MaelRL** [comment]
Could you please provide the data sets, otherwise it'll be difficult to do anything.

**Comment by tlchoque** [comment]
Here is the drive link: https://drive.google.com/file/d/1G7bdHWnrdMDg6KfV5w7NEa1zShBRaKWS/view?usp=sharing

**Comment by sloriot** [comment]
I could reproduce the crash with 4.13 but it is fixed in 4.14 (and master).
