### ISSUE TITLE
Add new simplification policy

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#3835]
We are missing a policy that simplify as much as possible according to a global error.

Possible references:
- [Surface Simplification Using Quadric Error Metrics](https://www.ri.cmu.edu/pub_files/pub2/garland_michael_1997_1/garland_michael_1997_1.pdf)
- Hugues Hoppe (all his code is available under github is we want to give it a try)
- ...?

**Comment by sloriot** [comment]
@afabri could you complete the list of possible solutions from our past discussion?
Shall @maxGimeno take care of the implementation once we've decided which one is the best (maybe after trying Hoppe's code)?

**Comment by MaelRL** [comment]
Will be done during this year's gsoc with @baskinburak
