### ISSUE TITLE
Fix CMakeLists.txt in Surface_mesh_parameterization

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#386]
Does this make sense in the CMakeLists.txt of an example?

    # g++ 4.1 creates an infinite loop in Surface_mesh_parameterization
    # if strict-aliasing optimization is on (implied by -O2, -O3 and -Os).
    if (CMAKE_COMPILER_IS_GNUCXX)
      SET (CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -fno-strict-aliasing")
      SET (CMAKE_CXX_FLAGS_DEBUG   "${CMAKE_CXX_FLAGS_DEBUG}   -fno-strict-aliasing")

**Comment by sloriot** [comment]
I don't think so. We should create a PR and test it.

**Comment by lrineau** [comment]
`-fno-strict-aliasing` is a flag that asks the g++ compiler not to rely on the strict-aliasing assumption for its optimization. It could be that the code of the Surface_mesh_parameterization is buggy, and does aliases objects incorrectly.

**Comment by afabri** [comment]
but then we better fix the bug, and first of all see it in the testsuite.

**Comment by sloriot** [comment]
@afabri The polyhedron demo does not contains these flags, so you probably can clean up the cmakelists submit a PR and the testsuite will most probably looks good.
