### ISSUE TITLE
Compile error C2039: Point_2 not a member of CGAL::Triangulation_vertex_base_2 with CGAL 4.13.1

### ISSUE THREAD

**Issue by XrizZ** [CGAL/cgal#3865]
## Issue Details
When using Constrained_Delaunay_triangulation_2 in my project, I get the following compilation errors:

> Severity	Code	Description	File	Line	Suppression State

> Error	C2039	'Segment_2': is not a member of  
 'CGAL::Triangulation_vertex_base_2<K,CGAL::Triangulation_ds_vertex_base_2<void>>'	
 d:\work\dependencies\cgal\4.13.1\include\cgal\constrained_delaunay_triangulation_face_base_2.h	47	

> Error	C2039	'Point_2': is not a member of 
> 'CGAL::Triangulation_vertex_base_2<K,CGAL::Triangulation_ds_vertex_base_2<void>>'		d:\work\dependencies\cgal\4.13.1\include\cgal\constrained_delaunay_triangulation_face_base_2.h	46	

The two errors appear as soon as I add the line:
``typedef DelaunayTriangulation::Finite_vertices_iterator FiniteVerticesIterator;``

This issue came when I converted CGAL 4.6.3.1000 to 4.13.1 and changed the Platform Toolset from VC2013 to VC2017. I have not changed any code.

## Source Code

```
#include "pch.h"
#include <iostream>

// CGAL includes for triangulation
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/Constrained_Delaunay_triangulation_2.h>
#include <CGAL/Triangulation_conformer_2.h>
#include <CGAL/Triangulation_vertex_base_2.h>
#include <CGAL/Delaunay_mesh_face_base_2.h>
#include <CGAL/Cartesian.h>
#include <CGAL/Polygon_2.h>
#include <CGAL/Polygon_2_algorithms.h>
#include <CGAL/Delaunay_mesher_2.h>
#include <CGAL/Delaunay_mesh_size_criteria_2.h>

// CGAL typedefs and definitions
typedef CGAL::Exact_predicates_inexact_constructions_kernel K;
typedef CGAL::Triangulation_vertex_base_2<K> Vb;
typedef CGAL::Delaunay_mesh_face_base_2<Vb> Fb;
typedef CGAL::Triangulation_data_structure_2<Vb,Fb> Tds;
typedef CGAL::Constrained_Delaunay_triangulation_2<K, Tds> DelaunayTriangulation;

typedef CGAL::Delaunay_mesh_size_criteria_2<DelaunayTriangulation> Criteria;

typedef DelaunayTriangulation::Finite_vertices_iterator FiniteVerticesIterator;
typedef DelaunayTriangulation::Finite_faces_iterator FiniteFacesIterator;
typedef DelaunayTriangulation::Finite_edges_iterator FiniteEdgesIterator;
typedef DelaunayTriangulation::Face_circulator FacesCirculator;
typedef DelaunayTriangulation::Point_iterator PointIterator;
typedef DelaunayTriangulation::Vertex Vertex;
typedef DelaunayTriangulation::Vertex_handle VertexHandle;
typedef DelaunayTriangulation::Edge Edge;
typedef DelaunayTriangulation::Face Face;
typedef DelaunayTriangulation::Face_handle FaceHandle;
typedef DelaunayTriangulation::Triangle Triangle;

typedef CGAL::Cartesian<double> Metric;
typedef DelaunayTriangulation::Point Point;
typedef CGAL::Polygon_2<Metric> Polygon2D;
typedef CGAL::Bbox_2 BBox2D;

typedef CGAL::Delaunay_mesher_2<DelaunayTriangulation, Criteria> Mesher;

void someFunction(void)
{
	DelaunayTriangulation* adaptiveMesh = new DelaunayTriangulation();
}

int main()
{
	someFunction();
	std::cout << "Hello World!\n";
}
```

## Environment

* Operating system: Windows 64 bits
* Compiler: VC 2017
* debug mode
* CGAL version: 4.13.1
* Boost version: 1.70
* Other libraries versions if used (Eigen, TBB, etc.): Eigen3.7

Your input is greatly appreciated.

**Comment by MaelRL** [comment]
Is this really the source code you've used ? It is missing quite a few template parameters (for example, `Delaunay_mesh_size_criteria_2` must be templated by the constrained triangulation). Adding those template parameters (https://gist.github.com/MaelRL/66672f82527ce84c0e651a9d45b85d56), I had no compiling issue on 4.13.1 or master, but this was on Linux.

**Comment by sloriot** [comment]
I updated the code with backquote and they magically appear :)

**Comment by MaelRL** [comment]
```
typedef CGAL::Delaunay_mesh_face_base_2<Vb> Fb;
```
cannot work: `Delaunay_mesh_face_base_2` takes as template parameters a traits class and a face base class, and you're only passing it a vertex base (see [doc](https://doc.cgal.org/latest/Mesh_2/classCGAL_1_1Delaunay__mesh__face__base__2.html)).

Compiles just fine for me once this is fixed (e.g. `typedef CGAL::Delaunay_mesh_face_base_2<K> Fb;`)

**Comment by XrizZ** [comment]
@MaelRL Thank you so much! This fixed my issue. 

What a stupid mistake on my part - just a typo in the end.. interesting that I used incorrect code for years and CGAL 4.6 did not complain :D

**Comment by MaelRL** [comment]
Indeed, it is a little bit strange that it ever worked :). There was some cleaning of the Triangulation classes a little while ago (CGAL 4.11 if I recall correctly), which is probably what broke your code.
