### ISSUE TITLE
How to confirm the Subdomain_index order in std::pair<Subdomain_index，Subdomain_index>

### ISSUE THREAD

**Issue by wangbowenll** [CGAL/cgal#3870]
## Issue Details
Dear researcher
      I think the document polyhedral_complex_mesh_3 is unclear.Looking at the [constructor](https://doc.cgal.org/4.13.1/Mesh_3/classCGAL_1_1Polyhedral__complex__mesh__domain__3.html#a8337b598d679bd000b08fdbcaeb5f3df), the fact that the incident subdomains in the pairs must be the subdomains respectively on the negative and positve side of the mesh is not documented.so how to confirm the two Subdomain_indces order in std::pair<Subdomain_index，Subdomain_index>.Does  std::pair<0, 1> and std::pair<1, 0> have any difference ?  what rule I should follow about the sequence of inputing surface polyhedral surfaces and its <Subdomain_index,Subdomain_index> order? I wish i can get a more clear Tutorials.
     I change the Subdomain_index based on the [code](https://doc.cgal.org/4.13.1/Mesh_3/Mesh_3_2mesh_polyhedral_complex_8cpp-example.html).it generates a .mesh file.when open it, a part seems not to be meshed.so what am i missing?
![GJFVIE}}S300KMW10{2Y 9N](https://user-images.githubusercontent.com/43980713/56467590-86508d80-6453-11e9-96e7-ebdaaeb488ba.png)
![TIM图片20190421164458](https://user-images.githubusercontent.com/43980713/56467688-ed227680-6454-11e9-91f8-3991949f559d.png)

[demo.zip](https://github.com/CGAL/cgal/files/3101040/demo.zip)
thanks for you help
 ## Source Code
`#define CGAL_CONCURRENT_MESH_3
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>

#include <CGAL/Mesh_triangulation_3.h>
#include <CGAL/Mesh_complex_3_in_triangulation_3.h>
#include <CGAL/Mesh_criteria_3.h>

#include <CGAL/Polyhedral_complex_mesh_domain_3.h>
#include <CGAL/make_mesh_3.h>

#include <cstdlib>

// Domain
typedef CGAL::Exact_predicates_inexact_constructions_kernel K;
typedef CGAL::Mesh_polyhedron_3<K>::type Polyhedron;
typedef CGAL::Polyhedral_complex_mesh_domain_3<K> Mesh_domain;

#ifdef CGAL_CONCURRENT_MESH_3
typedef CGAL::Parallel_tag Concurrency_tag;
#else
typedef CGAL::Sequential_tag Concurrency_tag;
#endif

// Triangulation
typedef CGAL::Mesh_triangulation_3<Mesh_domain,CGAL::Default,Concurrency_tag>::type Tr;

typedef CGAL::Mesh_complex_3_in_triangulation_3<
  Tr,Mesh_domain::Corner_index,Mesh_domain::Curve_index> C3t3;

// Criteria
typedef CGAL::Mesh_criteria_3<Tr> Mesh_criteria;

// To avoid verbose function and named parameters call
using namespace CGAL::parameters;

const char* const filenames[] = {
  "data/patches/patch-01.off",
  "data/patches/patch-13.off",
  "data/patches/patch-20.off",
  "data/patches/patch-21.off",
  "data/patches/patch-23.off",
  "data/patches/patch-30.off",
 };

const std::pair<int, int> incident_subdomains[] = {
	std::make_pair(0, 2),
	std::make_pair(1, 2),
	std::make_pair(3, 0),
	std::make_pair(2, 3),
	std::make_pair(1, 3),
	std::make_pair(0, 1),
};

int main()
{
  const std::size_t nb_patches = sizeof(filenames) / sizeof(const char*);

  CGAL_assertion(sizeof(incident_subdomains) ==
                 nb_patches * sizeof(std::pair<int, int>));

  std::vector<Polyhedron> patches(nb_patches);

  for(std::size_t i = 0; i < nb_patches; ++i) {
    std::ifstream input(filenames[i]);
    if(!(input >> patches[i])) {
      std::cerr << "Error reading " << filenames[i] << " as a polyhedron!\n";
      return EXIT_FAILURE;
	  }
	else
	{
		std::cout << "reading " << filenames[i] << " as a polyhedron!\n";
	}
    }

  // Create domain
  Mesh_domain domain(patches.begin(), patches.end(),
                     incident_subdomains, incident_subdomains+nb_patches);

  
  domain.detect_features(); //includes detection of borders

  std::cout << "feature\n" ;
  

  // Mesh criteria
  Mesh_criteria criteria(edge_size = 8,
	  facet_angle = 25, facet_size = 8, facet_distance = 0.2,
	  cell_radius_edge_ratio = 3, cell_size =10);

  // Mesh generation
  C3t3 c3t3 = CGAL::make_mesh_3<C3t3>(domain, criteria);
  /*no_exude(),
	  perturb(sliver_bound = 10, time_limit = 15)*/

  // Output
  std::ofstream medit_file("demo.mesh");
  c3t3.output_to_medit(medit_file,false,true);

  return EXIT_SUCCESS;
}
`

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):(Windows10, 64 bits+vs2017):
* Compiler:15 2017 win 64
* Release or debug mode:debug
* Specific flags used (if any):
* CGAL version:cgal-4.13
* Boost version:boost 1.67
* Other libraries versions if used (Eigen, TBB, etc.):TBB +Engin

**Comment by janetournois** [comment]
Hi,
thank you for your input, I will prepare a pull request to improve the documentation.
The point is that the order in which subdomain indices are given should be consistent with the orientation of the input sub-polyhedra.
Jane.

**Comment by wangbowenll** [comment]
> Hi,
> thank you for your input, I will prepare a pull request to improve the documentation.
> The point is that the order in which subdomain indices are given should be consistent with the orientation of the input sub-polyhedra.
> Jane.

Hi,researcher Jane.
Thanks for your instruction. I am sorry to reply late to you. 
How can i know the orientation of the input sub-polyhedra.Which function should be called to know it.I know each polyhedral surface is oriented, and has two sides. And the sub-domain indices on both sides should be known. so when inputing a surface .its two sub domain indices should be constructed correspondly  into std::<subdomain index1,subdomain index2>. but for complex model.such as geological model.it often has more 10 subdomains.CGAL do not clearly have a regulation to guide the std::<subdomain index1,subdomain index2>,especially the each surface's inputing order. I check the order of input surface and its std::pair<>. but it often has exception:Expression : ! is_infinite(c->vertex(i))  and I think my model is closed and do not have isolated point.
Nowdays, i am  trying my best  to mesh a very complex geological model by CGAL .(picture1-4 is the model) i believe the library is reliable and strong.at the same time ,i worry i can not creat the domain even if i have the Stratum surface .off file. recently I am trying all the time.
![`_% A1@03G X)~9BUL}@B(H](https://user-images.githubusercontent.com/43980713/56802686-41619800-6853-11e9-9f5b-1175ce9cbeab.png)
![6R2O0JRS96O J B7{145P6N](https://user-images.githubusercontent.com/43980713/56802687-41619800-6853-11e9-9333-4416c0c7ed5b.png)
![333JE%F(MLKI~LJB5T9JPQ3](https://user-images.githubusercontent.com/43980713/56802688-41fa2e80-6853-11e9-9362-63d03946dff4.png)
![RFE1KB8B8}FP0AU)Y3O@)1Y](https://user-images.githubusercontent.com/43980713/56802689-41fa2e80-6853-11e9-81ba-bb6ee0eb76f0.png)

**Comment by sloriot** [comment]
Having an example input off file would help answering your question. It is know clear if you have several close surfaces or simply open surfaces, if they are corefined at the intersection, ...

**Comment by wangbowenll** [comment]
> 有一个示例输入文件将有助于回答您的问题。很清楚你是否有几个近表面或只是开放的表面，如果它们在十字路口是核心的，...

#3887 @sloriot 
Dear Sebastien Loriot
This is my question description.and recent days. I creat a very complex geological model. I think the subdomains divided are wrong.because the model have fault. it split the model two.so maybe  it  have problem. For such  type  model.Can CGAL  solve it?

**Comment by sloriot** [comment]
I'm not sure to understand what you mean. Do you have an issue because the OFF files are somehow confidential? If that's the case, you can share them in a private message instead.
My point is that to answer to your question about the orientation, it is important to know what kind of data you have.
An important precondition for the meshing algorithm to work correctly is that if your surfaces intersect, the intersection edges must  be part of the input surfaces.
For example this one is not a valid input:
![Screenshot from 2019-04-29 08-02-52](https://user-images.githubusercontent.com/1224632/56878618-455d0800-6a55-11e9-9b81-3441d249325e.png)
But this one is:
![Screenshot from 2019-04-29 08-03-07](https://user-images.githubusercontent.com/1224632/56878619-45f59e80-6a55-11e9-9273-70e7c68d65e3.png)

**Comment by wangbowenll** [comment]
> 我不太明白你的意思。你有问题，因为OFF文件是以某种方式保密的吗？如果是这种情况，您可以在私人消息中共享它们。
> 我的观点是，要回答有关方向的问题，了解您拥有的数据类型非常重要。
> 网格划分算法正常工作的一个重要前提是，如果曲面相交，则交点边必须是输入曲面的一部分。
> 例如，这个不是有效的输入： 但这个是：
> ![截图2019-04-29 08-02-52](https://user-images.githubusercontent.com/1224632/56878618-455d0800-6a55-11e9-9b81-3441d249325e.png)
> 
> ![截图2019-04-29 08-03-07](https://user-images.githubusercontent.com/1224632/56878619-45f59e80-6a55-11e9-9273-70e7c68d65e3.png)

Hi, sloriot .
@sloriot  I am so sorry .The OFF file is open.and  I will re-update it. Thanks for you guide. I know that the intersection edges must be part of the input surfaces.and my model meet the need.there is no isolated point in model. 
The fault is  a geological structure ,not error. a fault will split the structum two and generate up and down displacement respectly.(picture)
[off file.zip](https://github.com/CGAL/cgal/files/3126900/off.file.zip)
 so in  3D case. Creating input-polyhedra according to the model surface is difficult. I always failed to creat input-polyhedras. or I input wrong std::pair<subdomain index>.but i have tried many times,but there is still a exception"Expression : ! is_infinite(c->vertex(i)) ".I still try to achieve it .
![IMG_20190429_174930](https://user-images.githubusercontent.com/43980713/56889540-34d67d00-6aa9-11e9-89db-61ca19a02629.jpg)

**Comment by lrineau** [comment]
The pull-request #3873 will fix the documentation issue.
