### ISSUE TITLE
CGAL demo issues batch

### ISSUE THREAD

**Issue by MaelRL** [CGAL/cgal#3875]
### Bugs ###

- [x] indices only show up on the first viewer (other viewers say "too many elements")
- [x] the selection highlighting is not working properly: open a selection item, select some face, move to another viewer, the highlighting does not correspond to the cursor position
- [x] lcc being the default plugin to open .off meshes is unpractical because no operation is available
- [x] create clipping box crashes the demo
- [x] "Lighting..." doesn't do anything
- [x] Shouldn't be able to call functions if the input mesh does not meet preconditions, e.g. calling "does_self_intersect" on a quad mesh will return that everything is fine because the mesh is not triangulated, regardless of the geometry.
- [x] Filter items and shift+click do not play well together (segfaults). I can't really reproduce it, but maybe if you shift+click between filtered items...
- [x] If you try to offset mesh an item that is hidden, you can't change the values and the automatically computed suggestions are 0 (I imagine this is not restricted to offset meshing).
- [x] Failing to reload an item crashes the demo (take an .off, load it, change the number of a vertices to 1 fewer in the file, reload, kaputt).
- [x] recenter applies to all viewers (might be a feature?)
- [x] Camera twitching within 1s after a recenter is still present
- [x] Can't load polygon soups
- [x] Selection highlight doesn't move with the cursor when shift+clicking a selection
- [x] Selection highlight is wrong when the brush size is greater than a single simplex (ideally the selection highlight would be adapted to the brush's size)
- [x] Can't open OBJ
### Feature Requests ###
- [x] Nicer palette colors for some plugins. For example in VSA, the colors are objectively not aesthetic. Rather than purely random, which yields all type of ugly pinks and browns, it would be nicer to use some restricted color palette.

## Environment

* CGAL version: master

**Comment by maxGimeno** [comment]
>Shouldn't be able to call functions if the input mesh does not meet preconditions, e.g. calling "does_self_intersect" on a quad mesh will return that everything is fine because the mesh is not triangulated, regardless of the geometry.

The architecture used by Qt for the "applicable" system would make the demo freeze for a century anytime you open the menu "Operation" if you start calling mesh function to enable/disable action. The only viable option I think is to return a warning when the preconditions are not met, and interrupt the action, which is supposed to be done already. The real bug is that the self-intersection plugin does not perform this test before calling the algorithm.

**Comment by maxGimeno** [comment]
What is a Filter item ?

**Comment by MaelRL** [comment]
By "filter item", I meant the different kinds of selection, sorry. Apparently, you can't have multiple selection files (e.g. intersecting simplicies + selection) anymore, so this bug goes away too.

**Comment by maxGimeno** [comment]
>Failing to reload an item crashes the demo (take an .off, load it, change the number of a vertices to 1 fewer in the file, reload, kaputt).

Actually if you lie aboutthe number of vertices in an OFF file, reloading OR loading will lead to a crash, because the loader doesn't know how to detect that a call to an invalid index is out of bounds. The loaders expect the files to be coherent with there own standards, at least for the OFF.
I think fixing that peculiar bug would alter performance. @sloriot what do you think ?

**Comment by maxGimeno** [comment]
>Can't load polygon soups

I don't reproduce. Is it possible you loaded an off with the lcc_io_plugin and then tried to load a soup, which was created empty ? In that case, it is because the lcc_plugin became default after the first load and it failed to create  the soup, but the off_plugin works well.

**Comment by MaelRL** [comment]
That bug is from @sloriot, so I don't know.

**Comment by sloriot** [comment]
> That bug is from @sloriot, so I don't know
> > Can't load polygon soups
> 
> I don't reproduce. Is it possible you loaded an off with the lcc_io_plugin and then tried to load a soup, which was created empty ? In that case, it is because the lcc_plugin became default after the first load and it failed to create the soup, but the off_plugin works well.

I guess so.

**Comment by maxGimeno** [comment]
For the colors, I usually use the HSV model to play with generated colors, where VSA uses a cheat-sheet filled with randomish RGB values. Is the problem specific to VSA or should I think more about my color generation in general ?

**Comment by lrineau** [comment]
Adding "Under Testing" to an issue is useless. You should label the PR #3879 instead.

**Comment by maxGimeno** [comment]
I know, I must have mistaken it for a PR
