### ISSUE TITLE
Orientation of Polylines in Slicer Pkg:PMP

### ISSUE THREAD

**Issue by Cheney1989** [CGAL/cgal#3883]
# Issue Details

It is cool to find slicing for meshes in Polygon Mesh Processing package. I tested the example and other 3D objects for slicing. However, I found that the sliced polylines maybe randomly oriented (Do I miss some input parameters? I am new to CGAL). As you know, many users like me want to have the exterior polylines **CCW** oriented and the hole ones to be **CW**, so that we can build the tree of polylines (e.g. by ClipperLib) very conveniently.

## Environment

* Operating system:Windows64 bits
* Compiler:MSVC2015
* Release or debug mode:Release 
* Specific flags used (if any):
* CGAL version:4.14
* Boost version:1.70.0
* Other libraries versions if used (Eigen, TBB, etc.):Eigen

**Comment by sloriot** [comment]
#3910 should fix the issue. Could you give it a try an report any issue you might have?

**Comment by lrineau** [comment]
Fixed by the merge of #3910.
