### ISSUE TITLE
Surface_mesh_segmentation crashes when using complex mesh

### ISSUE THREAD

**Issue by JimmyTUM** [CGAL/cgal#3892]
Unable to run any of the Surface_mesh_segmentation examples on complex meshes (it works on simpler models). 

## Issue Details

Running any of the mesh segmentation examples on complex "off" files causes the following crash:

CGAL error: precondition violation!
Expression : ! K().collinear_3_object()(p,q,r)
File       : C:\dev\CGAL-4.13.1\include\CGAL/Kernel/function_objects.h
Line       : 1740
Explanation:
Refer to the bug-reporting instructions at https://www.cgal.org/bug_report.html

## Source Code

The issue is reproducible on any of the surface_mesh_segmentation examples.
Please use this ".off" file: https://syncandshare.lrz.de/dl/fiUfXA9gvXr1vXvCHG96M1SH/Window_Test.off

## Environment

* Windows 64 bits / Windows 10
* Debug mode
* CGAL version: 4.13.1
* Boost version: 1.66

**Comment by sloriot** [comment]
Your input model does not validate the prerequisite of the method, that is it has some degenerate faces (3 to be more precise).
You can try patching CGAL as follow:
```
--- a/Surface_mesh_segmentation/include/CGAL/internal/Surface_mesh_segmentation/SDF_calculation.h
+++ b/Surface_mesh_segmentation/include/CGAL/internal/Surface_mesh_segmentation/SDF_calculation.h
@@ -388,6 +388,7 @@ private:
     const Point p2 = get(vertex_point_map,target(next(halfedge(facet,mesh),mesh),mesh));
     const Point p3 = get(vertex_point_map,target(prev(halfedge(facet,mesh),mesh),mesh));
     const Point center  = centroid_functor(p1, p2, p3);
+    if (CGAL::collinear(p1, p2, p3)) return boost::none;
     Vector normal = normal_functor(p2, p1, p3);
     normal=scale_functor(normal,
                          FT(1.0/std::sqrt(to_double(normal.squared_length()))));
```
I'll have to run some benchmark to check it is not penalizing the code too much before pushing it into CGAL. 

Note that at least for the model attached, this segmentation method is probably not well suited since it is a CAO like object where the diameter is not always meaningful.

**Comment by Jimmy-Abualdenien** [comment]
thanks @sloriot ! Will give it a try and review.

**Comment by Jimmy-Abualdenien** [comment]
Unfortunately, after applying the fix proposed, I got an assertion error:
Expression : dmin >= 0
File       : C:\dev\CGAL-4.13.1\include\CGAL/internal/Intersections_3/Bbox_3_Segment_3_do_intersect.h
Line       : 215

**Comment by sloriot** [comment]
With the same input?

**Comment by Jimmy-Abualdenien** [comment]
Yes.

**Comment by sloriot** [comment]
Then I cannot reproduce. Which example are you running?

**Comment by afabri** [comment]
> 
> 
> Then I cannot reproduce. Which example are you running?

He wrote "any example". 


@Jimmy-Abualdenien the link to your data set no longer works.

**Comment by Jimmy-Abualdenien** [comment]
Yes, I'm using the same file. Here is a new link, not sure why the old one is not working anymore:
https://syncandshare.lrz.de/dl/fiUfXA9gvXr1vXvCHG96M1SH/Window_Test.off

Thanks.

**Comment by sloriot** [comment]
How do you read the file? The CGAL reader does not handle STOFF files (I don't remember how I read it the first time, probably converted it with awk).

**Comment by afabri** [comment]
@Jimmy-Abualdenien  is this still an issue?

**Comment by Jimmy-Abualdenien** [comment]
Thanks for following up, the error is still happening, see attached screenshot. I read the off file like this:
CGAL::read_off("data/Window350.off", mesh);

Attached the model that I've just tested with and the cpp class.

<img width="529" alt="error" src="https://user-images.githubusercontent.com/15197651/60106367-65632c00-9765-11e9-8ba3-887547ca78ee.PNG">


[Window350.zip](https://github.com/CGAL/cgal/files/3325708/Window350.zip)

[segmentation_from_sdf_values_LCC_example.zip](https://github.com/CGAL/cgal/files/3325710/segmentation_from_sdf_values_LCC_example.zip)

**Comment by JimmyTUM** [comment]
@sloriot @afabri Was my comment clear? do you need additional information? I'm also available for testing if you need.

Thanks!
~J
