### ISSUE TITLE
Point Set Processing: cleanup

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#3905]
## Issue Details

For 5.0 we should remove functionality that was deprecated long ago, such as [this](https://doc.cgal.org/latest/Point_set_processing_3/index.html#title4).

**Comment by lrineau** [comment]
[**@afabri**](https://github.com/afabri) commented on [May 6, 2019, 10:35 AM GMT+2](https://github.com/CGAL/cgal/issues/3905#issue-440595174 "2019-05-06T08:35:20Z - Replied by Github Reply Comments"):
> ## Issue Details
> 
> For 5.0 we should remove functionality that was deprecated long ago, such as [this](https://doc.cgal.org/latest/Point_set_processing_3/index.html#title4).

Andreas refers to:
> ## 2.3 Upgrading from pre-CGAL 4.12 Deprecated API
> The current API based on ranges and named parameters was introduced in CGAL 4.12. 
>
> The old API that used pairs of iterators along with usual C++ parameters (with some default values and overloads to handle optional parameters) is deprecated.
> 
> Warning
>     The deprecated API will be removed in CGAL 4.14, so we recommend to update your code.

That was deprecated only one year ago, and it was documented that it would be removed at the time of CGAL-4.14. Well... too late.

**Comment by sgiraudot** [comment]
I removed them in https://github.com/CGAL/cgal/pull/3739, I don't know if this will be integrated in 5.0.
