### ISSUE TITLE
Infinite loop in clip function

### ISSUE THREAD

**Issue by borki23** [CGAL/cgal#3907]
Hello,

I'm using the clip function to clip a cube using a surface mesh (see attached files). However, the clip function does not return. 
The code basically works like:
```c
PMP::clip(cube, surface, PM::parameters::clip_volume(true));
```
Further investigation revealed that the infinite loop runs at a `while` statement in
```c 
face_graphs_utils.h
``` 
at the following lines 
```c
 void append_patches_to_triangle_mesh(..)
...
    BOOST_FOREACH(halfedge_descriptor h_out, border_halfedges_source_to_link)
    {
      halfedge_descriptor candidate =
      opposite(next(opposite(h_out, output), output), output);
      while (!is_border(candidate, output))
        candidate = opposite(next(candidate, output), output);
      set_next(candidate, h_out, output);
    }
...
```
I cannot quite figure out what the problem is.
 Is it related to my mesh ? 
Why is it possible that such a infinite loop can occur?

Regards

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows 10 64 bit
* Compiler: MSVC 2017 64 bit
* Release or debug mode: Release/Debug
* Specific flags used (if any): CGAL_HEADER_ONLY
* CGAL version: 4.13 (I know an old version but if you cannot recreate this issue on a newer one I will switch)

[meshs.zip](https://github.com/CGAL/cgal/files/3147884/meshs.zip)

**Comment by MaelRL** [comment]
Your `surface` mesh self intersects, which violates the preconditions of the function. These self intersections are caused by some borders on your mesh (marked in red) that you probably do not intend to have:
![](https://i.imgur.com/qhTKRga.png)

In any case, you definitely should move to the newest version as there have been many improvements to the clipping functions in CGAL 4.14 (and now in master).

**Comment by MaelRL** [comment]
Note that you can use the named parameter `throw_on_self_intersection` and these preconditions will be checked (and it'll thus throw if they are violated).

See the [documentation page](https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__corefinement__grp.html#ga30082762ba2d947cba304e2884d96a99) for more info.

**Comment by borki23** [comment]
Thank you for the fast reply. 
I suppose the boundary is due to an actual hole in the mesh, right?
Therefore it is not possible to solve this issue using the function 
`CGAL::PMP::remove_self_intersections(surface)`?

If not I think I need to catch the exception or check the mesh myself using the function 
`CGAL::Polygon_mesh_processing::does_self_intersect(surface);`.

Regards

**Comment by MaelRL** [comment]
You have two holes, but only one creates a self-intersection (the lower one on the picture above). This self-intersection is just a combinatorial issue in your mesh: the edges on either side of the hole have the same geometry but different indices. You can fix this by calling [CGAL::Polygon_mesh_processing::stitch_borders(your_mesh)](https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__repairing__grp.html#ga15f047f56af2fee3e491120db4dc69a3).

The other hole looks worse, but has a little gap and thus there is no self-intersections. You could thus theoretically call `PMP::clip()` after fixing the first hole. In case you want to fix that other hole, calling either `PMP::remove_self_intersections()` or `PMP::stitch_borders` will do nothing, but we have a function `PMP::snap()` (see [this PR](https://github.com/CGAL/cgal/pull/3266)) coming up that you can call before `PMP::stitch_borders()`, which should just work fine for your case. The function you need to use is `PMP::experimental::snap_border_vertices_non_conforming()`.

**Comment by borki23** [comment]
Okay, I'll do so if I cannot figure out the error in the mesh creation.
Thank you very much :)
