### ISSUE TITLE
PMP: Error (?) in the testsuite

### ISSUE THREAD

**Issue by MaelRL** [CGAL/cgal#3908]
I was looking at [this](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.0-Ic-31/Polygon_mesh_processing/TestReport_afabri_x64_Cygwin-Windows10_MSVC2017-Debug-64bits.gz) testsuite. The summary says there's only an error in a snapping test. However, if you search for 'error' on the page, there is also an error in `remeshing_test`. For some reason, it does not show up on the summary.

@sloriot @janetournois is this some real issue in remeshing? (other platforms do not have this error.)

@maxGimeno @lrineau it seems a bit strange that the summary says successful execution despite failing on a precondition.

**Comment by maxGimeno** [comment]
The test is expected to fail, it is a test for the precondition verification or something like that. The fact that the remeshing fails is a successful test.  
See the comment in the test : 
```c++
//this test should make the precondition fail
  test_precondition("data/joint_refined.off",
    "data/joint-patch-toolargeconstraints.selection.txt");
```

**Comment by MaelRL** [comment]
I guess I couldn't find it in the other testsuites because they were all in release at the time.

Sorry!

**Comment by lrineau** [comment]
The code is:
https://github.com/CGAL/cgal/blob/f9ede3f36575c172c6ee2ad9ef269518df9efc83/Polygon_mesh_processing/test/Polygon_mesh_processing/remeshing_test.cpp#L76-L104

It tests that the assertion is triggered, and catch it. And the test fails only if the assertion is *not* triggered.

There should be a message, before the test, explaining what is about to happen.

**Comment by lrineau** [comment]
[**@MaelRL**](https://github.com/MaelRL) commented on [May 7, 2019, 9:00 AM GMT+2](https://github.com/CGAL/cgal/issues/3908#issuecomment-489958731 "2019-05-07T07:00:03Z - Replied by Github Reply Comments"):
> I guess I couldn't find it in the other testsuites because they were all in release at the time.
> 
> Sorry!

The reason is different: for a caught exception, on Linux with gcc, no message is displayed:
https://github.com/CGAL/cgal/blob/f9ede3f36575c172c6ee2ad9ef269518df9efc83/STL_Extension/include/CGAL/assertions_impl.h#L75-L95
