### ISSUE TITLE
Add missing overload for do_intersect

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#391]
Missing `Iso_cuboid_3` overloads:
- `do_intersect(Iso_cuboid_3,Plane_3)`
- `do_intersect(Iso_cuboid_3,Triangle_3)`
- `do_intersect(Iso_cuboid_3, Bbox_3)`

Missing overloads for `Point_3` (for consistency with 2D):
- `do_intersect(Point_3,Point_3)`
- `do_intersect(Point_3,Plane_3)`
- `do_intersect(Point_3,Line_3)`
- `do_intersect(Point_3,Ray_3)`
- `do_intersect(Point_3,Segment_3)`
- `do_intersect(Point_3,Iso_cuboid_3)`

Missing 2D overloads:
- `do_intersect(Triangle_2,Iso_rectangle_2)`

Missing intersection computation overloads:
- `intersection(Iso_cuboid_3,Plane_3)`
- `intersection(Iso_cuboid_3,Triangle_3)`
- `intersection(Iso_rectangle_2,Triangle_2)`

**Comment by GilesBathgate** [comment]
This looks good. With regards to the documentation would it also be worth adding a "see also" to CGAL::do_overlap() since as you suggest these function overloads supersede it.

**Comment by sgiraudot** [comment]
Can anybody take care of this?

**Comment by afabri** [comment]
What about `Iso_cuboid_3, Iso_cuboid_3`?

**Comment by lrineau** [comment]
I would want consistency, `Do_intersect_3` should have the overloads with (`Bbox_3, *something*).

**Comment by afabri** [comment]
The functions `intersection(Iso_cuboid_3,Plane_3)`,   `intersection(Iso_cuboid_3,Triangle_3)`, `intersection(Iso_rectangle_2,Triangle_2)` have too complicated results.

**Comment by lrineau** [comment]
https://github.com/CGAL/cgal/issues/391#issuecomment-362601084:
> The functions `intersection(Iso_cuboid_3,Plane_3)`,   `intersection(Iso_cuboid_3,Triangle_3)`, `intersection(Iso_rectangle_2,Triangle_2)` have too complicated results.

Well, not that complicated. That is similar to `Intersect_3(Triangle_3, Triangle_3)`: the result can be a convex polygon (then the result type is a `std::vector<Point_3>`).

I agree that might complicated, but if there is a need, that could be implemented anyway. I wonder if that might help @janetournois in her clipping a 3D triangulation by a box. We probably need `Iso_cuboid_3×Tetrahedron_3` as well. Let's add them on case by case, when they have a real use case.

**Comment by afabri** [comment]
Note that there are also few functions for sphere and tetrahedron.
