### ISSUE TITLE
By which means of 'cgal' should be adopted in carrying out triangulation of 3D polygon

### ISSUE THREAD

**Issue by mirro187187** [CGAL/cgal#3923]
## Issue Details
3D polygon boundary constraint is required

## Environment
* CGAL version:4.14
* Boost version:1.67

**Comment by sloriot** [comment]
There is no 3D constrained triangulation in CGAL if this is what you are looking for.

**Comment by mirro187187** [comment]
What means of cgal should be used to achieve Triangular mesh of 3D polygon ？

**Comment by sloriot** [comment]
For a 3D polygon you can try [`triangulate_hole_polyline()`](https://doc.cgal.org/latest/Polygon_mesh_processing/group__hole__filling__grp.html#ga8508fd49a2482ec7dcb3e1799234696a).

**Comment by mirro187** [comment]
> For a 3D polygon you can try [`triangulate_hole_polyline()`](https://doc.cgal.org/latest/Polygon_mesh_processing/group__hole__filling__grp.html#ga8508fd49a2482ec7dcb3e1799234696a).

thank you
