### ISSUE TITLE
cache openmesh in travis?

### ISSUE THREAD

**Issue by mglisse** [CGAL/cgal#3944]
Travis builds sometimes time out because downloading openmesh takes too long. Also, I don't know what kind of infrastructure they have at Aachen, but downloading the same file over and over, hundreds of times per day, does not sound very nice to them. Travis has the possibility to cache files. They do warn that "Large files that are quick to install but slow to download do not benefit from caching, as they take as long to download from the cache as from the original source", but it looks like they are talking about downloading the android SDK (Google has enough bandwidth) or similar high-profile things, not a smaller project from some university.
Possibly the issues with downloads are very temporary and this issue can be ignored.

**Comment by mglisse** [comment]
It seems to be back to downloading in about 2 seconds, I guess we can forget this issue.

**Comment by lrineau** [comment]
I think it will be a real pain for us to try to use the Travis caching. On the other hand, Openmesh/Aachen should try to work on that issue, by contributing to Debian and Ubuntu, for example.
