### ISSUE TITLE
Problems In Union tow Open Surface Mesh

### ISSUE THREAD

**Issue by HersheysChen** [CGAL/cgal#3946]
## Issue Details
I am a CGAL beginner . I have two open surface meshes with some overlap areas, and I wanna merge the two overlapped meshes by Boolean Operations use corefine_and_compute_union( ) function of Polygon Mesh Processing, but it does not work correctly. I run the example Polygon_mesh_processing/corefinement_mesh_union.cpp, and it breaks when calculate the intersections. 
Can anyone tell me whether the union boolean operation only correctly works when the input polygon meshes is closed. How can I merge/combine those open surface mesh ?
Thansk for your answer.

**Comment by sloriot** [comment]
Officially they must be closed. Unofficially, it works in some cases. Basically, all connected components must be involved in an intersection and the intersection polylines must be closed or reach the boundary of the meshes. If you share your input I can have a look at it.

**Comment by HersheysChen** [comment]
> Officially they must be closed. Unofficially, it works in some cases. Basically, all connected components must be involved in an intersection and the intersection polylines must be closed or reach the boundary of the meshes. If you share your input I can have a look at it.

Thanks for your answer, sloriot.
I will upload my open surface mesh data .
Thus the union boolean operation can not merge the open surface meshes, is there any other functions in CGAL can combine / merge the overlapped open surface meshes ?

**Comment by sloriot** [comment]
Do you have access to a file sharing service like google drive, wetransfer, ... ?

**Comment by HersheysChen** [comment]
> Do you have access to a file sharing service like google drive, wetransfer, ... ?

https://drive.google.com/open?id=1LrNAr120NAjZtU6VPdfZl8wL1hJZPk_X

**Comment by sloriot** [comment]
I could open the files. After fixing the self-intersections I could run the union operation but it seems the input do not match the conditions I mentioned and no output could be computed. I guess from your data, one option would be to do whatever is possible and have non-manifold patches imported. I could try to implement that for you but not within a month as I'm too busy for now.

**Comment by HersheysChen** [comment]
> I could open the files. After fixing the self-intersections I could run the union operation but it seems the input do not match the conditions I mentioned and no output could be computed. I guess from your data, one option would be to do whatever is possible and have non-manifold patches imported. I could try to implement that for you but not within a month as I'm too busy for now.

Much thanks for your answer,sloriot.
Maybe current CGAL union function is not very suitable for my data. It may lead to  self-intersection triangles and non-manifold when performing merging operation. I think I should use a high-quality mesh in the overlapped area rather than combine these two meshes together. Instead, I wanna find the outline of  overlapped area, and then join the low-quality mesh to the high-quality one in the non-overlapped area.

**Comment by sloriot** [comment]
Note that it is not specific to the CGAL union algorithm, on such input:
![Screenshot from 2019-05-24 09-19-21](https://user-images.githubusercontent.com/1224632/58309636-12fcbb80-7e05-11e9-8864-489ed3e563f3.png)
the union will always be non-manifold. You have to use a mesh "fusion" algorithm with some priority criteria. We have something currently under development but it is not yet public.
