### ISSUE TITLE
[Demo] Clipping+point set selection not working for data far away from origin

### ISSUE THREAD

**Issue by sgiraudot** [CGAL/cgal#3955]
## Issue Details

1. Open/generate a point set far away from origin
2. Clip something using orthographic mode (probably works with the box mode too)
3. Try to select something: nothing is selected

I guess this has to do with the trick used to avoid bad display with data far away from origin (the same thing works with points centered on the origin).

## Environment

* CGAL version: master

**Comment by lrineau** [comment]
Fixed by #4003.
