### ISSUE TITLE
it don't create Polygon with list data

### ISSUE THREAD

**Issue by mazwen** [CGAL/cgal#3960]
_Please use the following template to help us solving your issue._

## Issue Details

the point data 
15615830 41576520
16248930 35324640
21946850 29389320
27486490 36907400
21551160 46483060

## Source Code

	Polygon_2 pgn;

	X_monotone_curve_2 s1(Point_2(15615830, 41576520), Point_2(16248930, 35324640));
	pgn.push_back(s1);
	X_monotone_curve_2 s2(Point_2(16248930, 35324640), Point_2(21946850, 29389320));
	pgn.push_back(s2);
	X_monotone_curve_2 s3(Point_2(21946850, 29389320), Point_2(27486490, 36907400));
	pgn.push_back(s3);
	X_monotone_curve_2 s4(Point_2(27486490, 36907400), Point_2(21551167, 46483060));
	pgn.push_back(s4);
	X_monotone_curve_2 s5(Point_2(21551167, 46483060), Point_2(15615830, 41576520));
	pgn.push_back(s5);
	CGAL::Sign fx = pgn.orientation();
	if (!(fx == CGAL::COUNTERCLOCKWISE))
	{
		pgn.reverse_orientation();
	}

	Polygon_set_2 set2;
	set2.join(pgn);

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):
* Compiler:
* Release or debug mode:
* Specific flags used (if any):
* CGAL version:
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by afabri** [comment]
Can you please put a real .cpp file on [gist.github.com](https://gist.github.com/), that is with `#include`  and `typedef`.

**Comment by mazwen** [comment]
> Can you please put a real .cpp file on [gist.github.com](https://gist.github.com/), that is with `#include` and `typedef`.


#pragma comment(lib,"libgmp-10.lib")
#pragma comment(lib,"libmpfr-4.lib")

#include <CGAL/Exact_predicates_exact_constructions_kernel.h>
#include <CGAL/Gps_circle_segment_traits_2.h>
#include <CGAL/Boolean_set_operations_2.h>
#include <CGAL/Lazy_exact_nt.h>
#include <list>
#include <cstdlib>
#include <cmath>
#include "CGAL/Simple_cartesian.h"
typedef CGAL::Filtered_kernel<CGAL::Simple_cartesian<double>> Kernel;
//typedef CGAL::Exact_predicates_exact_constructions_kernel Kernel;
typedef Kernel::Point_2                                   Point_2;
typedef Kernel::Circle_2                                  Circle_2;
typedef CGAL::Gps_circle_segment_traits_2<Kernel>         Traits_2;
typedef CGAL::General_polygon_set_2<Traits_2>             Polygon_set_2;
typedef Traits_2::Polygon_2                               Polygon_2;
typedef Traits_2::Polygon_with_holes_2                    Polygon_with_holes_2;
typedef Traits_2::Curve_2                                 Curve_2;
typedef Traits_2::X_monotone_curve_2                      X_monotone_curve_2;
typedef Curve_2::Point_2								  Point_2_1;

**Comment by MaelRL** [comment]
Closing. Feel free to re-open if you can submit proper input and details about your issue.
