### ISSUE TITLE
The output file *.mesh of make_mesh_3 has self-intersection faces when generating mesh((triangle or tetrahedron) ) in 3D domain

### ISSUE THREAD

**Issue by zoelsherry** [CGAL/cgal#3962]
## Issue Details

When I run the example of `Mesh_3/mesh_polyhedral_domain.cpp` to generate 3D mesh(triangle or tetrahedron), the output mesh in \*.mesh file format has self-intersection faces. I didn't advert that until I used [TetGen](http://wias-berlin.de/software/index.jsp?id=TetGen&lang=1)(a software for generating tetrahedral meshes) to remesh the output mesh(\*.mesh file format).  The figure below shows the reasults of self-intersection detection using TetGen. Besides, here is my input file and output file.[input_and_output_file.zip](https://github.com/CGAL/cgal/files/3224400/input_and_output_file.zip). 
![image](https://user-images.githubusercontent.com/37893213/58429623-13cd7000-80d9-11e9-8871-9825f38269ea.png)

## Source Code

```c++
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/Mesh_triangulation_3.h>
#include <CGAL/Mesh_complex_3_in_triangulation_3.h>
#include <CGAL/Mesh_criteria_3.h>
#include <CGAL/Polyhedron_3.h>
#include <CGAL/boost/graph/helpers.h>
#include <CGAL/Polyhedral_mesh_domain_3.h>
#include <CGAL/make_mesh_3.h>
#include <CGAL/refine_mesh_3.h>

#define CGAL_LINKED_WITH_TBB
#define CGAL_CONCURRENT_MESH_3

// Domain
typedef CGAL::Exact_predicates_inexact_constructions_kernel K;
typedef CGAL::Polyhedron_3<K> Polyhedron;
typedef CGAL::Polyhedral_mesh_domain_3<Polyhedron, K> Mesh_domain;
#ifdef CGAL_CONCURRENT_MESH_3
typedef CGAL::Parallel_tag Concurrency_tag;
#else
typedef CGAL::Sequential_tag Concurrency_tag;
#endif
// Triangulation
typedef CGAL::Mesh_triangulation_3<Mesh_domain,CGAL::Default,Concurrency_tag>::type Tr;
typedef CGAL::Mesh_complex_3_in_triangulation_3<Tr> C3t3;
// Criteria
typedef CGAL::Mesh_criteria_3<Tr> Mesh_criteria;
// To avoid verbose function and named parameters call
using namespace CGAL::parameters;
int main(int argc, char*argv[])
{
  const char* fname = (argc>1)?argv[1]:"data/elephant.off";
  // Create input polyhedron
  Polyhedron polyhedron;
  std::ifstream input(fname);
  input >> polyhedron;
  if(input.fail()){
    std::cerr << "Error: Cannot read file " <<  fname << std::endl;
    return EXIT_FAILURE;
  }
  input.close();
  
  if (!CGAL::is_triangle_mesh(polyhedron)){
    std::cerr << "Input geometry is not triangulated." << std::endl;
    return EXIT_FAILURE;
  }
  // Create domain
  Mesh_domain domain(polyhedron);
  
  // Mesh criteria (no cell_size set)
  Mesh_criteria criteria(facet_angle=25, facet_size=0.15, facet_distance=0.008,
                         cell_radius_edge_ratio=3);
  
  // Mesh generation
  C3t3 c3t3 = CGAL::make_mesh_3<C3t3>(domain, criteria, no_perturb(), no_exude());
  // Output
  std::ofstream medit_file("out_1.mesh");
  c3t3.output_to_medit(medit_file);
  medit_file.close();
  // Set tetrahedron size (keep cell_radius_edge_ratio), ignore facets
  Mesh_criteria new_criteria(cell_radius_edge_ratio=3, cell_size=0.03);
  // Mesh refinement (and make the output manifold)
  CGAL::refine_mesh_3(c3t3, domain, new_criteria, manifold());
  // Output
  medit_file.open("out_2.mesh");
  c3t3.output_to_medit(medit_file);
  return EXIT_SUCCESS;
}
```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): **Windows, 64bits**
* Compiler: **Visual Studio 2017**
* Release or debug mode: **debug x64**
* Specific flags used (if any): 
* CGAL version: **CGAL-4.14**
* Boost version: **boost_1_70_0**
* Other libraries versions if used (Eigen, TBB, etc.): **Eigen 3.3.7**, **tbb2019_20190320oss_win**

**Comment by sloriot** [comment]
Do you know what tetgen is calling a self-intersection?

**Comment by zoelsherry** [comment]
> Do you know what tetgen is calling a self-intersection?
Two facets overlap each other, i.e., have the same node indices.

**Comment by lrineau** [comment]
`tetgen` reports that a facet is duplicated.

**Comment by lrineau** [comment]
I do not know exactly why, but I think you can work around that issue with extra parameters "`, false, false`" to `outpout_to_medit`, with this patch for example:
```patch
--- a/Mesh_3/examples/Mesh_3/mesh_polyhedral_domain.cpp
+++ b/Mesh_3/examples/Mesh_3/mesh_polyhedral_domain.cpp
@@ -72,7 +72,7 @@ int main(int argc, char*argv[])
 
   // Output
   medit_file.open("out_2.mesh");
-  c3t3.output_to_medit(medit_file);
+  c3t3.output_to_medit(medit_file, false, false);
 
   return EXIT_SUCCESS;
 }
```

**Comment by zoelsherry** [comment]
> I do not know exactly why, but I think you can work around that issue with extra parameters "`, false, false`" to `outpout_to_medit`, with this patch for example:
> 
> ```diff
> --- a/Mesh_3/examples/Mesh_3/mesh_polyhedral_domain.cpp
> +++ b/Mesh_3/examples/Mesh_3/mesh_polyhedral_domain.cpp
> @@ -72,7 +72,7 @@ int main(int argc, char*argv[])
>  
>    // Output
>    medit_file.open("out_2.mesh");
> -  c3t3.output_to_medit(medit_file);
> +  c3t3.output_to_medit(medit_file, false, false);
>  
>    return EXIT_SUCCESS;
>  }
> ```

> I do not know exactly why, but I think you can work around that issue with extra parameters "`, false, false`" to `outpout_to_medit`, with this patch for example:
> 
> ```diff
> --- a/Mesh_3/examples/Mesh_3/mesh_polyhedral_domain.cpp
> +++ b/Mesh_3/examples/Mesh_3/mesh_polyhedral_domain.cpp
> @@ -72,7 +72,7 @@ int main(int argc, char*argv[])
>  
>    // Output
>    medit_file.open("out_2.mesh");
> -  c3t3.output_to_medit(medit_file);
> +  c3t3.output_to_medit(medit_file, false, false);
>  
>    return EXIT_SUCCESS;
>  }
> ```

It still doesn't work. TetGen still tell me that a self-intersection was detected. why are the face indices in *.mesh repeated?
![repeat](https://user-images.githubusercontent.com/37893213/58536254-88f88c80-8222-11e9-956c-d75a24a3e394.PNG)
