### ISSUE TITLE
ARAP_parameterizer_3: Could not solve linear system

### ISSUE THREAD

**Issue by whatyougonnado** [CGAL/cgal#3963]
_Please use the following template to help us solving your issue._

## Issue Details

ARAP_parameterizer_3 is working like random.
When I run like

Almost it can be run, but sometimes it occurs 'Encounter Problem 6: Could not solve linear system'

## Source Code

	SMP::ARAP_parameterizer_3<PMesh> parameterizer;

	SMP::Error_code status = parameterizer.parameterize(pm, hd, uvpm, vipm, vpm);

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows 64 bits
* Compiler: VS2015
* Release or debug mode: Release

**Comment by MaelRL** [comment]
Please provide an example of input on which it fails.

**Comment by whatyougonnado** [comment]
I try to unfold this obj with this part (viewing using libigl)
![image](https://user-images.githubusercontent.com/21278478/58487853-493e9000-81a3-11e9-95b2-ac95e9e93acd.png)

and the output is like this (viewing using maya2017)
![image](https://user-images.githubusercontent.com/21278478/58487898-5bb8c980-81a3-11e9-8ac1-3a222065b6a2.png)

The log
First try
>Initial energy: 4683502.09991674
50 max iterations
Energy at iteration 1 : 3317.92552965
Energy at iteration 2 : 1434.10783838
Energy at iteration 3 : 967.80462098
Energy at iteration 4 : 696.22339776
Energy at iteration 5 : 524.04925710
Energy at iteration 6 : 407.50506186
Energy at iteration 7 : 324.68093560
Energy at iteration 8 : 263.70258903
Energy at iteration 9 : 217.63336672
Energy at iteration 10 : 182.14524325
Energy at iteration 11 : 154.38778013
Energy at iteration 12 : 132.40242615
Energy at iteration 13 : 114.79912627
Energy at iteration 14 : 100.56667571
Energy at iteration 15 : 88.95540376
Energy at iteration 16 : 79.40124159
Energy at iteration 17 : 71.47471399
Energy at iteration 18 : 64.84562938
Energy at iteration 19 : 59.25803989
Energy at iteration 20 : 54.51213589
Energy at iteration 21 : 50.45094652
Energy at iteration 22 : 46.95044364
Energy at iteration 23 : 43.91209924
Energy at iteration 24 : 41.25723781
Energy at iteration 25 : 38.92271849
Energy at iteration 26 : 36.85761248
Energy at iteration 27 : 35.02063210
Energy at iteration 28 : 33.37813182
Energy at iteration 29 : 31.90254724
Energy at iteration 30 : 30.57117146
Energy at iteration 31 : 29.36519236
Could not solve linear system
Energy at iteration 32 : 28.80422017
Encountered a problem: 6

Second try
>Initial energy: 4683502.09991674
50 max iterations
Energy at iteration 1 : 3317.92552965
Energy at iteration 2 : 1434.10783838
Energy at iteration 3 : 967.80462098
Energy at iteration 4 : 696.22339776
Energy at iteration 5 : 524.04925710
Energy at iteration 6 : 407.50506186
Energy at iteration 7 : 324.68093560
Energy at iteration 8 : 263.70258903
Energy at iteration 9 : 217.63336672
Energy at iteration 10 : 182.14524325
Energy at iteration 11 : 154.38778013
Energy at iteration 12 : 132.40242615
Energy at iteration 13 : 114.79912627
Energy at iteration 14 : 100.56667571
Energy at iteration 15 : 88.95540376
Energy at iteration 16 : 79.40124159
Energy at iteration 17 : 71.47471399
Energy at iteration 18 : 64.84562938
Energy at iteration 19 : 59.25803989
Energy at iteration 20 : 54.51213589
Energy at iteration 21 : 50.45094652
Energy at iteration 22 : 46.95044364
Energy at iteration 23 : 43.91209924
Energy at iteration 24 : 41.25723781
Energy at iteration 25 : 38.92271849
Energy at iteration 26 : 36.85761248
Energy at iteration 27 : 35.02063210
Energy at iteration 28 : 33.37813182
Energy at iteration 29 : 31.90254724
Energy at iteration 30 : 30.57117146
Energy at iteration 31 : 29.36519236
Could not solve linear system
Energy at iteration 32 : 28.80422017
Encountered a problem: 6

Third try(working!)
>Initial energy: 4683502.09991674
50 max iterations
Energy at iteration 1 : 3317.92552965
Energy at iteration 2 : 1434.10783837
Energy at iteration 3 : 967.80462098
Energy at iteration 4 : 696.22339784
Energy at iteration 5 : 524.04925713
Energy at iteration 6 : 407.50506187
Energy at iteration 7 : 324.68093560
Energy at iteration 8 : 263.70258902
Energy at iteration 9 : 217.63336671
Energy at iteration 10 : 182.14524325
Energy at iteration 11 : 154.38778011
Energy at iteration 12 : 132.40242613
Energy at iteration 13 : 114.79912626
Energy at iteration 14 : 100.56667569
Energy at iteration 15 : 88.95540375
Energy at iteration 16 : 79.40124158
Energy at iteration 17 : 71.47471398
Energy at iteration 18 : 64.84562938
Energy at iteration 19 : 59.25803989
Energy at iteration 20 : 54.51213589
Energy at iteration 21 : 50.45094652
Energy at iteration 22 : 46.95044364
Energy at iteration 23 : 43.91209924
Energy at iteration 24 : 41.25723781
Energy at iteration 25 : 38.92271849
Energy at iteration 26 : 36.85761248
Energy at iteration 27 : 35.02063133
Energy at iteration 28 : 33.37813068
Energy at iteration 29 : 31.90254584
Energy at iteration 30 : 30.57116989
Energy at iteration 31 : 29.36519068
Energy at iteration 32 : 28.26893114
Energy at iteration 33 : 27.26924771
Energy at iteration 34 : 26.35505270
Energy at iteration 35 : 25.51693381
Energy at iteration 36 : 24.74685046
Energy at iteration 37 : 24.03789030
Energy at iteration 38 : 23.38407364
Energy at iteration 39 : 22.78019591
Energy at iteration 40 : 22.22170012
Energy at iteration 41 : 21.70457345
Energy at iteration 42 : 21.22526303
Energy at iteration 43 : 20.78060701
Energy at iteration 44 : 20.36777804
Energy at iteration 45 : 19.98423658
Energy at iteration 46 : 19.62769227
Energy at iteration 47 : 19.29607175
Energy at iteration 48 : 18.98749168
Energy at iteration 49 : 18.70023610
Energy at iteration 50 : 18.43273790

I think that the problem is Round-off Error.
But, I  want to also know is there other reason or not and thanks for sharing nice lib, always.

**Comment by afabri** [comment]
Hi @whatyougonnado  when Mael asked for an example he meant an .obj file and not a screenshot.

**Comment by whatyougonnado** [comment]
The problem was my other code, not that part. Thus, I closed it.
