### ISSUE TITLE
the output file *.mesh of make_mesh_3 has duplicated facets

### ISSUE THREAD

**Issue by zoelsherry** [CGAL/cgal#3965]
> I do not know exactly why, but I think you can work around that issue with extra parameters "`, false, false`" to `outpout_to_medit`, with this patch for example:
> 
> ```diff
> --- a/Mesh_3/examples/Mesh_3/mesh_polyhedral_domain.cpp
> +++ b/Mesh_3/examples/Mesh_3/mesh_polyhedral_domain.cpp
> @@ -72,7 +72,7 @@ int main(int argc, char*argv[])
>  
>    // Output
>    medit_file.open("out_2.mesh");
> -  c3t3.output_to_medit(medit_file);
> +  c3t3.output_to_medit(medit_file, false, false);
>  
>    return EXIT_SUCCESS;
>  }
> ```

It still doesn't work. TetGen still tell me that a self-intersection was detected. why are the face indices in *.mesh repeated?
![repeat](https://user-images.githubusercontent.com/37893213/58536254-88f88c80-8222-11e9-956c-d75a24a3e394.PNG)

_Originally posted by @zoelsherry in https://github.com/CGAL/cgal/issues/3962#issuecomment-496811526_

## Issue Details

This is an issue following https://github.com/CGAL/cgal/issues/3962#issuecomment-496811526_ above.
When I run the example of `Mesh_3/mesh_polyhedral_domain.cpp` to generate 3D mesh(triangle or tetrahedron), I advert the output mesh in \*.mesh file format has duplicated faces. This results in error using [TetGen](http://wias-berlin.de/software/index.jsp?id=TetGen&lang=1)(a software for generating tetrahedral meshes) to remesh the output mesh(\*.mesh file format).  The figure below shows the duplicated indices in *out_2.mesh* and the error in TetGen. Besides, here is my input file and output file.
[input_and_output_file.zip](https://github.com/CGAL/cgal/files/3231193/input_and_output_file.zip)

![repeat](https://user-images.githubusercontent.com/37893213/58536813-23a59b00-8224-11e9-9faf-a81ebba93a0c.PNG)
![repeat2](https://user-images.githubusercontent.com/37893213/58537711-040f7200-8226-11e9-9c85-8617435f21ec.PNG)

## Source Code

```c++
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/Mesh_triangulation_3.h>
#include <CGAL/Mesh_complex_3_in_triangulation_3.h>
#include <CGAL/Mesh_criteria_3.h>
#include <CGAL/Polyhedron_3.h>
#include <CGAL/boost/graph/helpers.h>
#include <CGAL/Polyhedral_mesh_domain_3.h>
#include <CGAL/make_mesh_3.h>
#include <CGAL/refine_mesh_3.h>

#define CGAL_LINKED_WITH_TBB
#define CGAL_CONCURRENT_MESH_3

// Domain
typedef CGAL::Exact_predicates_inexact_constructions_kernel K;
typedef CGAL::Polyhedron_3<K> Polyhedron;
typedef CGAL::Polyhedral_mesh_domain_3<Polyhedron, K> Mesh_domain;
#ifdef CGAL_CONCURRENT_MESH_3
typedef CGAL::Parallel_tag Concurrency_tag;
#else
typedef CGAL::Sequential_tag Concurrency_tag;
#endif
// Triangulation
typedef CGAL::Mesh_triangulation_3<Mesh_domain,CGAL::Default,Concurrency_tag>::type Tr;
typedef CGAL::Mesh_complex_3_in_triangulation_3<Tr> C3t3;
// Criteria
typedef CGAL::Mesh_criteria_3<Tr> Mesh_criteria;
// To avoid verbose function and named parameters call
using namespace CGAL::parameters;
int main(int argc, char*argv[])
{
  const char* fname = (argc>1)?argv[1]:"data/elephant.off";
  // Create input polyhedron
  Polyhedron polyhedron;
  std::ifstream input(fname);
  input >> polyhedron;
  if(input.fail()){
    std::cerr << "Error: Cannot read file " <<  fname << std::endl;
    return EXIT_FAILURE;
  }
  input.close();
  
  if (!CGAL::is_triangle_mesh(polyhedron)){
    std::cerr << "Input geometry is not triangulated." << std::endl;
    return EXIT_FAILURE;
  }
  // Create domain
  Mesh_domain domain(polyhedron);
  
  // Mesh criteria (no cell_size set)
  Mesh_criteria criteria(facet_angle=25, facet_size=0.15, facet_distance=0.008,
                         cell_radius_edge_ratio=3);
  
  // Mesh generation
  C3t3 c3t3 = CGAL::make_mesh_3<C3t3>(domain, criteria, no_perturb(), no_exude());
  // Output
  std::ofstream medit_file("out_1.mesh");
  c3t3.output_to_medit(medit_file);
  medit_file.close();
  // Set tetrahedron size (keep cell_radius_edge_ratio), ignore facets
  Mesh_criteria new_criteria(cell_radius_edge_ratio=3, cell_size=0.03);
  // Mesh refinement (and make the output manifold)
  CGAL::refine_mesh_3(c3t3, domain, new_criteria, manifold());
  // Output
  medit_file.open("out_2.mesh");
  c3t3.output_to_medit(medit_file, false, false);
  return EXIT_SUCCESS;
}
```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): **Windows, 64bits**
* Compiler: **Visual Studio 2017**
* Release or debug mode: **debug x64**
* Specific flags used (if any): 
* CGAL version: **CGAL-4.14**
* Boost version: **boost_1_70_0**
* Other libraries versions if used (Eigen, TBB, etc.): **Eigen 3.3.7**, **tbb2019_20190320oss_win**

**Comment by janetournois** [comment]
Hi @zoelsherry 
actually, you should use `c3t3.output_to_medit(medit_file, true, true)` or  `c3t3.output_to_medit(medit_file, false, true)`.

You can have a look at the documentation written in CGAL/IO/File_medit.h (see below) and see that the third parameter decides whether facets will be written twice or not.

```
/**
 * @brief outputs mesh to medit format
 * @param os the stream
 * @param c3t3 the mesh
 * @param rebind if true, labels of cells are rebinded into [1..nb_of_labels]
 * @param show_patches if true, patches are labeled with different labels than
 * cells. If false, each surface facet is written twice, using label of
 * each adjacent cell.
 */
template <class C3T3>
void
output_to_medit(std::ostream& os,
                const C3T3& c3t3,
                bool rebind = false,
                bool show_patches = false)
```

Can you please confirm it's now ok for you?

Best regards,
Jane.

**Comment by lrineau** [comment]
@zoelsherry I close this issue. Please reopen it if you want to more precision. You can also continue discuss in this issue page even if it is officially closed.
