### ISSUE TITLE
Test CGAL on Microsoft Azure Pipelines

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#3966]
Last year [Microsoft has announced unlimited time and 10 parallel jobs][a] for open source projects, on its continuous integration product [Azure pipelines].

[a]: https://azure.microsoft.com/en-us/blog/announcing-azure-pipelines-with-unlimited-ci-cd-minutes-for-open-source/

[Azure pipelines]: https://azure.microsoft.com/en-us/services/devops/pipelines/

I think CGAL should try to benefit from that, starting by continuous integration on Windows, using `vcpkg` (and maybe chocolatey too) to help installing the missing dependencies.

[Azure pipelines] could also help us setting up an automatic way to publish Windows binaries for the 3D demo.

The integration with Github is good, of course, now that Microsoft has bought Github.

[Azure pipelines] can also be used to build and test on Linux and MacOS agents. The goal could be to test on Azur instead of Travis, to benefit from the 10 parallel jobs instead of 2.

**Comment by maxGimeno** [comment]
After some time spent trying different stuffs, here are my conclusions:
- On Windows: I got it to work with the NMake Makefiles JOM Generator, but it is far too long to be really useful. I expect a full testsuite to take around 3 hours to run.
- On Ubuntu: Having 10 jobs in parallel instead on 5 on Travis is not sufficient to make Azure as fast as Travis. Every operation takes twice the time it takes on Travis : the git chackout, the depencencies installation, ... So there is apparently no time to gain using Azure.+
