### ISSUE TITLE
Compilation Problem

### ISSUE THREAD

**Issue by iamh2o** [CGAL/cgal#3971]
## Issue Details

 I tried a fresh ./scripts/install.py and that failed.  I then tried setting g/g++ and clang/clang++, both cause the following crashes:

Trying to compile v0.6.3-beta on a new AWS p3.16xl instance, I'm getting the following error after a lot of failure messages that look like 
`/usr/lib/gcc/x86_64-linux-gnu/7.4.0/../../../../include/c++/7.4.0/bits/std_mutex.h:98:12: note: 'operator=' has been explicitly marked deleted here
    mutex& operator=(const mutex&) = delete;
           ^
`
This is the final error
`src/CMakeFiles/octopus.dir/build.make:452: recipe for target 'src/CMakeFiles/octopus.dir/io/read/htslib_sam_facade.cpp.o' failed
make[2]: *** [src/CMakeFiles/octopus.dir/io/read/htslib_sam_facade.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:280: recipe for target 'src/CMakeFiles/octopus.dir/all' failed
make[1]: *** [src/CMakeFiles/octopus.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
`

## Environment

* Operating system : ubuntu
* Compiler: Tried both g/g++ v 7.4.0-1 X && clang/clang++ v 9.0.0
* Release or debug mode:
* Specific flags used (if any): --clean -c clang -cxx clang++
* CGAL version: (how do i determine this?)
* Boost version:  1.58-dev
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by sloriot** [comment]
The issue does not seems to be related to the CGAL library at all.
I guess [here](https://github.com/luntergroup/octopus/issues) is the place you should report your issue.
