### ISSUE TITLE
Missing Intersections_23

### ISSUE THREAD

**Issue by maxGimeno** [CGAL/cgal#3972]
## Issue Details

There are missing intersections between linear kernel geometric types:

|do_intersect_3| Circ | Tet | Seg | Line | Plane |Tr | Ray | Cub | Sph | Bbox |
| ------------- | ---- | --- | --- | --- | ---- | -- | --- | --- | --- | ---- |
| Circle_3 |  :large_blue_circle: |  :large_blue_circle: |  :large_blue_circle: |  :large_blue_circle: |  :large_blue_circle: |  :large_blue_circle: |  :large_blue_circle: |  :large_blue_circle: |  :large_blue_circle: |  :large_blue_circle: |
| Tetrahedron_3|   :large_blue_circle: |  :heavy_check_mark: |   :heavy_check_mark: |   :heavy_check_mark: |   :heavy_check_mark: |   :heavy_check_mark: |   :heavy_check_mark: |   :heavy_check_mark: |   :heavy_check_mark: | :heavy_check_mark: |
| Segment_3    |   :large_blue_circle: |  :heavy_check_mark: |  :heavy_check_mark: |  :heavy_check_mark: |  :heavy_check_mark: |  :heavy_check_mark: |  :heavy_check_mark: |   :heavy_check_mark: |    :heavy_check_mark: |     :heavy_check_mark: |
| Line_3       |   :large_blue_circle: |  :heavy_check_mark: |  :heavy_check_mark: |  :heavy_check_mark: |  :heavy_check_mark: |  :heavy_check_mark: |  :heavy_check_mark: |   :heavy_check_mark: |  :heavy_check_mark: |       :heavy_check_mark: |
| Plane_3      |   :large_blue_circle: |  :heavy_check_mark: |  :heavy_check_mark: |  :heavy_check_mark: |  :heavy_check_mark: |  :heavy_check_mark: |   :heavy_check_mark: |   :heavy_check_mark: |   :heavy_check_mark: |     :heavy_check_mark: |
| Triangle_3   |   :large_blue_circle: |  :heavy_check_mark: |  :heavy_check_mark: |  :heavy_check_mark: |  :heavy_check_mark: |  :heavy_check_mark: |   :heavy_check_mark: |   :heavy_check_mark: |   :heavy_check_mark: |     :heavy_check_mark: |
| Ray_3        |   :large_blue_circle: |  :heavy_check_mark: |  :heavy_check_mark: |  :heavy_check_mark: |  :heavy_check_mark: |  :heavy_check_mark: |  :heavy_check_mark: |   :heavy_check_mark: |  :heavy_check_mark: |       :heavy_check_mark: |
| Iso_cuboid_3 |   :large_blue_circle: |  :heavy_check_mark: |  :heavy_check_mark: |   :heavy_check_mark: |   :heavy_check_mark: |  :heavy_check_mark: |  :heavy_check_mark: |   :heavy_check_mark: |   :heavy_check_mark: |    :heavy_check_mark: |
| Sphere_3     |   :large_blue_circle: |   :heavy_check_mark: |   :heavy_check_mark: |   :heavy_check_mark: |   :heavy_check_mark: |   :heavy_check_mark: |   :heavy_check_mark: |  :heavy_check_mark: |   :heavy_check_mark: | :heavy_check_mark: |
| Bbox_3       |   :large_blue_circle: |  :heavy_check_mark: |  :heavy_check_mark: |   :heavy_check_mark: |   :heavy_check_mark: |  :heavy_check_mark: |   :heavy_check_mark: |   :heavy_check_mark: |   :heavy_check_mark: |   :heavy_check_mark: |

|do_intersect_2| L | S | R | T | Rec | Circ | Bbox
| ------------- | - | - | - | - | --- | ---- | ---- |
| Line_2| :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:| :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :x: |
| Segment_2 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:| :heavy_check_mark: | :heavy_check_mark: | :x: | :x: |
| Ray_2 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:| :heavy_check_mark: | :heavy_check_mark: | :x: | :x: |
| Triangle_2 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:| :heavy_check_mark: | :heavy_check_mark: | :x: | :x: |
| Iso_rectangle_2| :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:| :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :x: |
|Circle_2 | :heavy_check_mark: | :x: | :x: | :x: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:  |
|Bbox_2 |  :x: | :x: | :x: | :x: | :x: | :heavy_check_mark: | :x: |

|Intersections_3| Tet | Seg | Line | Plane |Tr | Ray | Cub | Sph | Bbox |
| ------------- | --- | --- | --- | ---- | -- | --- | --- | --- | ---- |
| Tetrahedron_3|  :large_blue_circle: |  :x: |  :x: |  :x: |  :x: |  :x: |  :large_blue_circle:  |  :large_blue_circle: |  :large_blue_circle: |
| Segment_3    |  :x: |  :heavy_check_mark: |  :heavy_check_mark: |  :heavy_check_mark: |  :heavy_check_mark: |  :heavy_check_mark: |  :heavy_check_mark: |  :large_blue_circle: |    :heavy_check_mark: |
| Line_3       |  :x: |  :heavy_check_mark: |  :heavy_check_mark: |  :heavy_check_mark: |  :heavy_check_mark: |  :heavy_check_mark: |  :heavy_check_mark: |  :large_blue_circle: |  :heavy_check_mark: |
| Plane_3      |  :x: |  :heavy_check_mark: |  :heavy_check_mark: |  :heavy_check_mark: |  :heavy_check_mark: |  :heavy_check_mark: |  :x: |  :heavy_check_mark: |  :x: |
| Triangle_3   |  :x: |  :heavy_check_mark: |  :heavy_check_mark: |  :heavy_check_mark: |  :heavy_check_mark: |  :heavy_check_mark: |  :x: |  :large_blue_circle: |  :x: |
| Ray_3        |  :x: |  :heavy_check_mark: |  :heavy_check_mark: |  :heavy_check_mark: |  :heavy_check_mark: |  :heavy_check_mark: |  :heavy_check_mark: |  :large_blue_circle: |  :heavy_check_mark: |
| Iso_cuboid_3 |  :large_blue_circle: |  :heavy_check_mark: |  :heavy_check_mark: |  :x: |  :x: |  :heavy_check_mark: |  :heavy_check_mark: |  :large_blue_circle: |  :x: |
| Sphere_3     |  :large_blue_circle: |  :large_blue_circle: |  :large_blue_circle: |  :heavy_check_mark: |  :large_blue_circle: |  :large_blue_circle: |  :large_blue_circle: |  :heavy_check_mark: |  :large_blue_circle: |
| Bbox_3       |  :large_blue_circle: |  :heavy_check_mark: |  :heavy_check_mark: |  :x: |  :x: |  :heavy_check_mark: |  :x: |  :large_blue_circle: |  :x: |

|Intersections_2| L | S | R | T | Rec | Bbox |
| ------------- | - | - | - | - | --- | ---- |
| Line_2| :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:| :heavy_check_mark: | :heavy_check_mark: | :x: |
| Segment_2 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:| :heavy_check_mark: | :heavy_check_mark: | :x: |
| Ray_2 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:| :heavy_check_mark: | :heavy_check_mark: | :x: |
| Triangle_2 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:| :heavy_check_mark: | :heavy_check_mark: | :x: |
| Iso_rectangle_2| :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :x: |
| Bbox_2 | :x: | :x: | :x: | :x: | :x: | :x: |

:heavy_check_mark: done
:x: not done
:large_blue_circle: not wanted (because not linear)

**Comment by afabri** [comment]
There are also cases like tet-tet where the output can be complex and not in the kernel.

**Comment by sloriot** [comment]
What about Bbox_2?

**Comment by MaelRL** [comment]
A few remarks:
- The tables are missing `Point_[23]` (did you also check the undocumented existing do_intersect)?
- A lot of circle/sphere do_intersect/intersection are sometimes in the circular/spherical kernels. Could the table reflect that?
- For the BBox_[23]:
   * It would be useful to check that all do_intersect/intersection of iso_cuboid_[23] do not rely on Bbox_[23]. In `Intersections_2`, that was the case for example, and it's really bad because you convert from FT to the bbox's double.
   * I would think the intersection computations with bbox_[23] should not exist in the first place, for the same reason (`double`-based). As far as I understand, the do_intersect() with Bbox exists for the AABB tree so these could stay.

**Comment by maxGimeno** [comment]
* The table is missing Point because everything, absolutely everything, is implemented with point. Not putting it in was a simple gain of space.
* @sloriot kind of specifically asked for only linear kernel. Should I change it to include a signage system for the non-linear kernels ?
* A user specifically asked for intersections between Bbox_3, so I have to disagree with you about that.

**Comment by MaelRL** [comment]
I think Point_2 Point_2 was added by @lrineau recently. For 2D intersections, you should check https://github.com/CGAL/cgal/pull/3940 which is more up to date than master.

**Comment by maxGimeno** [comment]
You are right, P2/P2 is in master.

**Comment by lrineau** [comment]
Instead of checking in the documentation, with C++20 concepts, we can check that programmatically. With [this gist](https://gist.github.com/lrineau/34e599e08c3c0d98aba942f29f06a320), that can be compiled by gcc, with the compilation flag `-fconcepts`, here are the results, with `master` (7fc36ad2a58):
```
## Do_intersect 3D
CGAL::Point_3<CGAL::Epick>
✔✘✔✔✔✔✔✔✔✔✔
CGAL::Circle_3<CGAL::Epick>
✘✘✘✘✘✘✘✘✘✘✘
CGAL::Tetrahedron_3<CGAL::Epick>
✔✘✔✔✔✔✔✔✔✔✔
CGAL::Segment_3<CGAL::Epick>
✔✘✔✔✔✔✔✔✔✔✔
CGAL::Line_3<CGAL::Epick>
✔✘✔✔✔✔✔✔✔✔✔
CGAL::Plane_3<CGAL::Epick>
✔✘✔✔✔✔✔✔✔✔✔
CGAL::Triangle_3<CGAL::Epick>
✔✘✔✔✔✔✔✔✔✔✔
CGAL::Ray_3<CGAL::Epick>
✔✘✔✔✔✔✔✔✔✔✔
CGAL::Iso_cuboid_3<CGAL::Epick>
✔✘✔✔✔✔✔✔✔✔✔
CGAL::Sphere_3<CGAL::Epick>
✔✘✔✔✔✔✔✔✔✔✔
CGAL::Bbox_3
✔✘✔✔✔✔✔✔✔✔✔

## Do_intersect 2D
CGAL::Point_2<CGAL::Epick>
✔✔✔✔✔✔✔✔
CGAL::Line_2<CGAL::Epick>
✔✔✔✔✔✔✔✘
CGAL::Segment_2<CGAL::Epick>
✔✔✔✔✔✔✘✘
CGAL::Ray_2<CGAL::Epick>
✔✔✔✔✔✔✘✘
CGAL::Triangle_2<CGAL::Epick>
✔✔✔✔✔✔✘✘
CGAL::Iso_rectangle_2<CGAL::Epick>
✔✔✔✔✔✔✔✘
CGAL::Circle_2<CGAL::Epick>
✔✔✘✘✘✔✔✔
CGAL::Bbox_2
✔✘✘✘✘✘✔✘


## Intersection 3D
CGAL::Point_3<CGAL::Epick>
✔✘✔✔✔✔✔✔✔✔✔
CGAL::Circle_3<CGAL::Epick>
✘✘✘✘✘✘✘✘✘✘✘
CGAL::Tetrahedron_3<CGAL::Epick>
✔✘✘✘✘✘✘✘✘✘✘
CGAL::Segment_3<CGAL::Epick>
✔✘✘✔✔✔✔✔✔✘✔
CGAL::Line_3<CGAL::Epick>
✔✘✘✔✔✔✔✔✔✘✔
CGAL::Plane_3<CGAL::Epick>
✔✘✘✔✔✔✔✔✘✔✘
CGAL::Triangle_3<CGAL::Epick>
✔✘✘✔✔✔✔✔✘✘✘
CGAL::Ray_3<CGAL::Epick>
✔✘✘✔✔✔✔✔✔✘✔
CGAL::Iso_cuboid_3<CGAL::Epick>
✔✘✘✔✔✘✘✔✔✘✘
CGAL::Sphere_3<CGAL::Epick>
✔✘✘✘✘✔✘✘✘✔✘
CGAL::Bbox_3
✔✘✘✔✔✘✘✔✘✘✘

## Intersection 2D
CGAL::Point_2<CGAL::Epick>
✔✔✔✔✔✔✔✔
CGAL::Line_2<CGAL::Epick>
✔✔✔✔✔✔✘✘
CGAL::Segment_2<CGAL::Epick>
✔✔✔✔✔✔✘✘
CGAL::Ray_2<CGAL::Epick>
✔✔✔✔✔✔✘✘
CGAL::Triangle_2<CGAL::Epick>
✔✔✔✔✔✔✘✘
CGAL::Iso_rectangle_2<CGAL::Epick>
✔✔✔✔✔✔✘✘
CGAL::Circle_2<CGAL::Epick>
✔✘✘✘✘✘✘✘
CGAL::Bbox_2
✔✘✘✘✘✘✘✘
```

In particular, it seems we disagree on `intersection(Segment_3, Tetrahedron_3)`.
