### ISSUE TITLE
Need some guidance on CGAL development vith IDEs

### ISSUE THREAD

**Issue by ujur007** [CGAL/cgal#3976]
## Issue Details
I have rather a question. Why there is not any explanation on how to develop cgal projects using visual studio or IDEs? Though CGAL has quite a lot of documentation.
Isn't that necessary? I found some post regarding this on the internet but still, I am bit kind of confused on how to proceed further?

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows 10
* Compiler:Visual studio 2013
* Release or debug mode: Release
* Specific flags used (if any):
* CGAL version:latest 4.13.1
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by lrineau** [comment]
Hi,

Last summer [you asked the same question, in the CGAL-discuss mailing, about the Qt Creator IDE][1]. I do not know if you got correct answers.

[1]: list.http://cgal-discuss.949826.n4.nabble.com/CGAl-questions-td4663796.html

We cannot, in CGAL, document the features of various IDE. CGAL is library of C++ templates, in headers. It has headers, it has dependencies, and users are expected to know how to setup their IDE. The CGAL documentation cannot document that.

CGAL uses CMake at its build system generator. On Windows, CMake natively generate solutions for Visual Studio. Maybe you could use CMake to generate an adequate solution. By the way, [CMake be used directly by Qt Creator][2]

[2]: https://doc.qt.io/qtcreator/creator-project-cmake.html
