### ISSUE TITLE
CGAL::intersection throws Undecidable conversion of CGAL::Uncertain<T>

### ISSUE THREAD

**Issue by marlinilram** [CGAL/cgal#3991]
_Please use the following template to help us solving your issue._

## Issue Details

Hi, 
I tried to do two Polygon_2 intersections. The input data is simple but it throws 'Undecidable conversion of CGAL::Uncertain<T>'. I also tried to round it to int but no luck. Did I do anything wrong?

## Source Code

``` cpp
  Eigen::MatrixXd poly_1(4, 2);
  poly_1.row(0) << -337, -2942;
  poly_1.row(1) << -429, 1856;
  poly_1.row(2) << -4928, 1770;
  poly_1.row(3) << -4836, -3028;
  Eigen::MatrixXd poly_2(4, 2);
  poly_2.row(0) << -2904, 6995;
  poly_2.row(1) << -2904, -3663;
  poly_2.row(2) << 1594, -3663;
  poly_2.row(3) << 1594, 6995;

  typedef CGAL::Exact_predicates_exact_constructions_kernel K;
  typedef K::Point_2 Point;
  typedef CGAL::Polygon_2<K> Polygon_2;
  typedef CGAL::Polygon_with_holes_2<K> Polygon_with_holes_2;

  auto matrix_to_poly = [&](const Eigen::MatrixXd &poly) {
    Polygon_2 p;
    for (int i = 0; i < poly.rows(); ++i) {
      p.push_back(Point(poly(i, 0), poly(i, 1)));
    }
    return p;
  };

  Polygon_2 p_1 = matrix_to_poly(poly_1);
  Polygon_2 p_2 = matrix_to_poly(poly_2);

  std::list<Polygon_with_holes_2> intersected_polys;
  CGAL::intersection(p_1, p_2, std::back_inserter(intersected_polys));
```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Mac 
* Compiler: Apple LLVM version 10.0.0 (clang-1000.11.45.5)
* Release or debug mode: release/debug
* Specific flags used (if any): 
* CGAL version: 4.13
* Boost version: 1.68
* Other libraries versions if used (Eigen, TBB, etc.): Eigen

**Comment by mglisse** [comment]
When you post code, please, pretty please, do make it a complete program including `#include` lines so we can just compile it without wasting time reconstructing the example you just destructed...

**Comment by afabri** [comment]
> 
> 
> When you post code, please, pretty please, do make it a complete program including `#include` lines so we can just compile it without wasting time reconstructing the example you just destructed...

And put the self-contained .cpp on gist.guthub.com

**Comment by sloriot** [comment]
No error with
```c++
#include <CGAL/Exact_predicates_exact_constructions_kernel.h>
#include <CGAL/Boolean_set_operations_2.h>

int main()
{
  typedef CGAL::Exact_predicates_exact_constructions_kernel K;
  typedef K::Point_2 Point;
  typedef CGAL::Polygon_2<K> Polygon_2;
  typedef CGAL::Polygon_with_holes_2<K> Polygon_with_holes_2;

  
  std::vector<Point> pts1 = { {-337, -2942}, {-429, 1856},  {-4928, 1770}, {-4836, -3028} };
  std::vector<Point> pts2 = { {-2904, 6995}, {-2904, -3663}, {1594, -3663}, {1594, 6995} };

  Polygon_2 p_1(pts1.begin(), pts1.end());
  Polygon_2 p_2(pts2.begin(), pts2.end());

  std::list<Polygon_with_holes_2> intersected_polys;
  CGAL::intersection(p_1, p_2, std::back_inserter(intersected_polys));
  
}
```

closing the issue
