### ISSUE TITLE
Consistant orientation of intersection results

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#3992]
Make sure and document that primitives generated by a call to `Intersect_2` are counterclockwise oriented (when it makes sense).

**Comment by maxGimeno** [comment]
> when it makes sense

How do we decide that it is ccw ? if we intersect 2 Triangle_3, which one of the 2 determines the orientation of the intersection ? What normal do we take ?

**Comment by sloriot** [comment]
We are in 2D here.

**Comment by maxGimeno** [comment]
Intersect_3 in 2D ?

**Comment by sloriot** [comment]
`Intersect_2`, updated.

**Comment by maxGimeno** [comment]
That clarifies about everything :)
