### ISSUE TITLE
New errors in our Doxygen testsuite

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#3995]
Our Doxygen testsuite is showing new errors, in the overview:
https://cgal.geometryfactory.com/CGAL/Manual_doxygen_test/

![image](https://user-images.githubusercontent.com/5746675/59353029-5f5f5b00-8d22-11e9-98bf-fad541ee5822.png)

See for example the kind of new error that is shown:
```patch
diff -u -N -w ./doc_data/Classification.txt /home/cgal-testsuite/cgal_doc_build/CGAL-5.0-Ic-56/doc/scripts/first_doc_ref/Classification.txt
--- ./doc_data/Classification.txt	2019-06-10 21:33:06.598631356 +0200
+++ /home/cgal-testsuite/cgal_doc_build/CGAL-5.0-Ic-56/doc/scripts/first_doc_ref/Classification.txt	2019-06-10 21:25:10.213413051 +0200
@@ -485,11 +485,11 @@
       K_neighbor_query
   CGAL::Classification::Point_set_neighborhood::My_point_property_map
     Variables
-      reference
       input
       point_map
     Types
       value_type
+      reference
       key_type
       category
     Methods
```

It might be because of https://github.com/doxygen/doxygen/pull/7048.

Anyway, for sure it is in that range of merges:
```
527fa741 Merge pull request #7048 from albert-github/feature/bug_535853
83b75684 Merge pull request #7039 from albert-github/feature/issue_7038
0272374c Merge pull request #7041 from albert-github/feature/bug_warn_consistency
8b090a65 Merge pull request #7045 from albert-github/feature/issue_7043
```

What should we do? I think the patch of PR https://github.com/doxygen/doxygen/pull/7048 is right, and it fixes a bug that has been in Doxygen for years. And even if the PR title talks about C#, the bug was also in C++.

I think we should cherry-pick the PR in our special build of Doxygen 1.13.

**Comment by afabri** [comment]
So let's add @albert-github

**Comment by maxGimeno** [comment]
I agree with @lrineau , cherry-picking the fix in our fork sounds like a good idea.

**Comment by albert-github** [comment]
I think so too that the fix is applicable for C++ (as far as I can see / deduct it should have no effect in any other language as C#).

Where can I see the differences in the resulting code as I have, logically, no access to e.g. /home/cgal-testsuite/cgal_doc_build/CGAL-5.0-Ic-56/doc/scripts/first_doc_ref/Advancing_front_surface_reconstruction.txt? or was the difference only shown in this specially created output?

**Comment by maxGimeno** [comment]
`typedef const Segment_2*                     const_pointer;`
This type of line was wrongly classified before the fix. It lead to `const_pointer` being considered as a `Variable`  instead of a `Type`. But this doesn't seem to impact the generated doc.

**Comment by albert-github** [comment]
So the generated documentation was already correct?

**Comment by maxGimeno** [comment]
I think, as those are mostly (or entirely ?) coming from undocumented code, so it wouldn't impact the doc.

**Comment by lrineau** [comment]
Fixed by applying the patch to our versions of Doxygen:

https://cgal.geometryfactory.com/CGAL/Manual_doxygen_test/

![image](https://user-images.githubusercontent.com/5746675/59422792-38139700-8dd1-11e9-88a4-2d8f153a68c9.png)
