### ISSUE TITLE
Generate circle from random points using quadratic programming

### ISSUE THREAD

**Issue by vecbib** [CGAL/cgal#4001]
_Please use the following template to help us solving your issue._

## Issue Details
When I try to generate circle from a given set of points. The given set of points are literally placed in circle. It does not give me a circle back.
-2XoXi - 2YoYi + c >= -Xi^2 - yi^2

Xo > Xc - dx
Xo < Xc + dx
Yo > Yc - dy
Yo < Yc + dy

Points I use :  (Circle center is 2.5,2.5)

5,2.5,0;...
4.8097,3.26537,0;...
4.26777,3.91421,0;...
3.45671,4.34776,0;...
2.5,4.5,0;...
1.54329,4.34776,0;...
0.732233,3.91421,0;...
0.190301,3.26537,0;...
0,2.5,0;...
0.190301,1.73463,0;...
0.732233,1.08579,0;...
1.54329,0.652241,0;...
2.5,0.5,0;...
3.45671,0.652241,0;...
4.26777,1.08579,0;...
4.8097,1.73463,0;...

I use 
```
#include <CGAL/Gmpz.h>
typedef CGAL::Gmpzf ET;
```

## Source Code
```
// program and solution types
typedef CGAL::Quadratic_program<int> Program;
// typedef CGAL::Quadratic_program<double> Program; I tried double too.
typedef CGAL::Quadratic_program_solution<ET> Solution;

// assume points are eigen points
  Program qp(CGAL::LARGER, true, 0, true, 0);

  // Setting A matrix
  const int C = 0;
  const int X = 1;
  const int Y = 2;
  // set_a and b
  for (int i = 0; i < points.size(); ++i) {
    // set a
    qp.set_a(C, i, 1.0);
    qp.set_a(X, i, -2.00 * points[i].x());
    qp.set_a(Y, i, -2.00 * points[i].y());
    // set b
    // qp.set_b(i, -1.00 * points[i].norm());
    qp.set_b(i, -1.00 * points[i].norm());
  }

  // set u
  // x 
  // xc and yc are mean of points.
  // dx and dy are the max - min
  double x_up =  xc+ dx;
  double x_low =  xc - dx;
  // y 
  double y_up =  yc+ dy;
  double y_low =  yc - dy;
  qp.set_u(C, true, pos_big_num);
  qp.set_u(X, true, x_up);
  qp.set_u(Y, true, y_up);
  std::cout << "done set_u \n";
  // set l
  qp.set_l(C, true, neg_big_num);
  qp.set_l(X, true, x_low);
  qp.set_l(Y, true, y_low);
  std::cout << "done set_l \n";
  // set d
//   for (int i = 0; i < 3; ++i) {
//     for (int j = 0; j < 3; ++j) {
//       qp.set_d(i, j, 0.0);
//     }
//   }
  // continue set d
  qp.set_d(1, 1, -2.0); //  -Xi^2  // for some reason I have to multiply with 2. I was told in cgal example
  qp.set_d(2, 2, -2.0); //  - yi^2
  std::cout << "done set_d\n";
  // set c
  qp.set_c(C, 1.0);
  qp.set_c(X, 0.0);
  qp.set_c(Y, 0.0);
  std::cout << "done set_c\n";
  // set c0
//   qp.set_c0(0.0); // I tried comment and un-commenting this
  std::cout << "done set_c0 \n";
  Solution s = CGAL::solve_quadratic_program(qp, ET());   
  assert(s.solves_quadratic_program(qp));
  // output solution
  std::cout << s;

```

Code output : 

c_val = 2.22045e-15
radius = 0.5
center = (0,0.5 )

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Linux/64bits
* Compiler: g++
* Release or debug mode: release
* Specific flags used (if any):
* CGAL version: 4.13
* Boost version: 1.68.0
* Other libraries versions if used (Eigen, TBB, etc.): Eigen

**Comment by MaelRL** [comment]
The points you provide are not on a circle but on an ellipsis.

Furthermore, please provide self-contained code to reproduce the issue.
