### ISSUE TITLE
Bug in is_facet_convex

### ISSUE THREAD

**Issue by gdamiand** [CGAL/cgal#4002]
_Please use the following template to help us solving your issue._

## Issue Details

The function is_facet_convex has a bug. 

It returns true for some non convex faces, in some specific configurations.

## Source Code

Cf this gist https://gist.github.com/gdamiand/b830f0852c55ec9438bd44f20694a30b

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):
* Compiler:
* Release or debug mode:
* Specific flags used (if any):
* CGAL version:
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by MaelRL** [comment]
bump @gdamiand

**Comment by gdamiand** [comment]
Sorry for the delay; thanks @MaelRL for the ping.

Cf this example: https://gist.github.com/gdamiand/b830f0852c55ec9438bd44f20694a30b

Both faces are non convex; but the second test returns true.

**Comment by sloriot** [comment]
According to the current use of the function, I don't think it is really needed to have this function. @maxGimeno do you really think there is an added value? I mean for quads it is useless and for a face with more than 4 vertices, using the non-convex code should not really change anything performance wise. What do you think?

**Comment by gdamiand** [comment]
I agree with you @sloriot ; I think this code was added by @maxGimeno .
