### ISSUE TITLE
CGAL doesn't work on Windows 7 through C++/CLI project due to thread_local compatibility

### ISSUE THREAD

**Issue by izenja** [CGAL/cgal#4006]
I have an x64 C++/CLI project in which I make use of CGAL in unmanaged C++ source files (compiled as non-CLR). This works fine on Windows 10, but the application fails to load with an access violation and code 0x0000007b from LoadLibrary when loading the C++/CLI assembly on Windows 7 x64.

I've narrowed this down to the usage of thread_local in CGAL. If I remove the thread_local keywords in tss.h or force it to use boost thread (and use BOOST_THREAD_DYN_LINK) for the same purpose with a config.h modification, it works.

Can a configuration option be added to force using boost threads instead of thread_local for TSS to avoid this? Is there already a way to do this somehow without modifying config.h manually?

## Environment

* Operating system: Built on Windows 10 64bit. Issue arises on Windows 7 64bit.
* Compiler: Visual Studio 2017
* Release or debug mode: Release
* CGAL version: 4.13
* Boost version: 1.69

**Comment by lrineau** [comment]
There is nothing straight-forward. On way you can do that is `#undef` a macro just after the inclusion of `<CGAL/config.h>`. Add this before any other inclusion of CGAL headers:
```c++
#include <CGAL/config.h>
#undef CGAL_CAN_USE_CXX11_THREAD_LOCAL
```

But, as this trick is not a documented and supported behavior, you cannot assure you that it will stay valid in future versions of CGAL.

*(As it is not really a bug, I close this issue for book-keeping, but we can continue the discussion in it, if you wish.)*

**Comment by afabri** [comment]
I am not sure that it is worth it to make the effort,  if it was only for supporting Windows 7.
