### ISSUE TITLE
Add PMP::split

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#4007]
Similar to `clip` but all parts are kept. The code can be put in `PMP/clip.h`

Example code:
https://gist.github.com/sloriot/df4e257a35455578505f3dedd6a8a8ff

For the output, the mesh must first be created in the container and then filled (must be careful with the requirements of the output in the doc).

**Comment by MaelRL** [comment]
There's a "split" option when you clip in the polyhedron demo, so there is probably some code to scrap there too.
