### ISSUE TITLE
Remove and restore constraint with Constrained_triangulation_plus_2

### ISSUE THREAD

**Issue by vcloarec** [CGAL/cgal#4010]
Hello,

I wonder if if it is possible to restore a constraint after it has been removed with Constraint triangulation plus.

The code below returns a false value because the last  insert_constaint() method call returns a null constraint id : the constraint is not inserted as if it is still existing.
This null value seems result from the constraint_map of the hierarchy. The key value seems not be removed from the map when the constraint is removed.

Is this behavior is normal ?

Thanks

```
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/Triangulation_2.h>
#include <CGAL/Constrained_Delaunay_triangulation_2.h>
#include <CGAL/Constrained_triangulation_plus_2.h>


typedef CGAL::Exact_predicates_inexact_constructions_kernel                 K;
typedef CGAL::Polygon_2<K>                                                Polygon_2;
typedef CGAL::Exact_intersections_tag                                     Itag_;
typedef CGAL::Constrained_Delaunay_triangulation_2<K,CGAL::Default, Itag_> CDT;
typedef CGAL::Constrained_triangulation_plus_2<CDT>                       CDTP;

typedef CDTP::Point                                                       Point;
typedef CDTP::Constraint_id                                               Cid;
typedef CDTP::Vertex_handle                                               Vertex_handle;


bool testCDTP()
{
    CDTP cdtp;

    Vertex_handle handle1=cdtp.insert(Point(0,0));
    Vertex_handle handle2=cdtp.insert(Point(0,10));
    Vertex_handle handle3=cdtp.insert(Point(10,10));
    Vertex_handle handle4=cdtp.insert(Point(10,0));

    cdtp.insert_constraint(handle1,handle3);

    cdtp.remove_constraint(handle1,handle3);

    auto lastConstraintId=cdtp.insert_constraint(handle1,handle3);

    return (lastConstraintId != nullptr);

}
```

## Environment

* Operating system Linux debian 64 bits
* Compiler: GCC
* Release or debug mode: debug

* CGAL version: 4.13
* Boost version: 1.67

**Comment by afabri** [comment]
`insert_constraint()` returns a  `Constraint_id`.  You should call the function `remove_constraint()` with the constraint id, and not with the two vertex handles.  The latter comes from a time before a polyline could be considered as constraint.

**Comment by lrineau** [comment]
I close this issue, because it is not an issue. But @vcloarec you and Andreas can still continue discussing in it.

**Comment by vcloarec** [comment]
Thanks for your answer.
BUt the code below give the same resutl :
```

auto constraintId=cdtp.insert_constraint(handle1,handle3);

cdtp.remove_constraint(constraintId);

auto lastConstraintId=cdtp.insert_constraint(handle1,handle3);

return (lastConstraintId != nullptr);
```

**Comment by afabri** [comment]
I confirm.  This is fixed in master though.

I think if you modify the file Polyline_constraint_hierarchy_2.h

` void remove_constraint(Vertex_handle va, Vertex_handle vb)
  {
    remove_constraint(constraint_map[make_edge(va,vb)]);
    constraint_map.erase(make_edge(va,vb)); // AF added this
  }`

it should work (but you must call the remove function with the two vertex handles.

**Comment by vcloarec** [comment]
Thanks a lot for your workaround.
Do I need to recompile CGAL with this modification ?
Or maybe it is preferable to compile the master ...
Otherwise, do you know when the next release will be available with the fix in the current master ?

**Comment by afabri** [comment]
There is no need to recompile CGAL. In fact the library contains only a hand-full of non-template classes. In fact you can even use CGAL header only.  The next release is around September - we have a release every six months.  I will put the fix in the bug fix branch of the current release.
