### ISSUE TITLE
remove_vertex_from_constraint method with colinear vertices

### ISSUE THREAD

**Issue by vcloarec** [CGAL/cgal#4025]
Hello,

With the `remove_vertex_from_constraint` method of the `Constrained_triangulation_plus_2` class, it seems it is not possible to remove vertex when it is collinear with other vertices. When vertex are collinear and the second vertex is attempted to be removed, the number of vertices is still the same, not normal. But when the vertex are not collienar, the number of vertices decreases by one, normal.
The code below illustrates those behaviors.
When the `remove_from_constraint `is attempted on the third vertex, a crash appears for the two cases, collinear and no collinear.

When removing the second vertex, I think the bad behavior comes from the `insert_constraint` called in the method `remove_vertex_from_constraint` after the constraint is splitted. The `insert_constraint constraint` method add a constraint to rely the two sides of the constraint and there is the removed vertex on the inserted constraint and so, it is added to the constraint ...

When removing the third vertex, I don't know ...

```
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/Triangulation_2.h>
#include <CGAL/Constrained_Delaunay_triangulation_2.h>
#include <CGAL/Constrained_triangulation_plus_2.h>


typedef CGAL::Exact_predicates_inexact_constructions_kernel                 K;
typedef CGAL::Polygon_2<K>                                                Polygon_2;
typedef CGAL::Exact_intersections_tag                                     Itag_;
typedef CGAL::Constrained_Delaunay_triangulation_2<K,CGAL::Default, Itag_> CDT;
typedef CGAL::Constrained_triangulation_plus_2<CDT>                       CDTP;

typedef CDTP::Point                                                       Point;
typedef CDTP::Constraint_id                                               Cid;
typedef CDTP::Vertex_handle                                               Vertex_handle;



int countVertex(CDTP &cdtp, CDTP::Constraint_id id)
{
    auto v=cdtp.vertices_in_constraint_begin(id);

    int count=0;
    while(v!=cdtp.vertices_in_constraint_end(id))
    {
        count++;
        v++;
    }

    return count;
}


int main()
{
    CDTP cdtp;

    std::list<Point> pointsListCollinear;

    pointsListCollinear.push_back(Point(0,0));
    pointsListCollinear.push_back(Point(0,1));
    pointsListCollinear.push_back(Point(0,2));
    pointsListCollinear.push_back(Point(0,3));
    pointsListCollinear.push_back(Point(0,4));
    pointsListCollinear.push_back(Point(0,5));

    std::list<Point> pointsListNoCollinear;

    pointsListNoCollinear.push_back(Point(1,0));
    pointsListNoCollinear.push_back(Point(2,1));
    pointsListNoCollinear.push_back(Point(4,2));
    pointsListNoCollinear.push_back(Point(2,3));
    pointsListNoCollinear.push_back(Point(4,4));
    pointsListNoCollinear.push_back(Point(1,5));


    auto ctIdCollinear=cdtp.insert_constraint(pointsListCollinear.begin(),pointsListCollinear.end());
    auto ctIdNoCollinear=cdtp.insert_constraint(pointsListNoCollinear.begin(),pointsListNoCollinear.end());
    
    
    //******************************* attempt with the collinear constraint
    auto vertexToRemoveCollinear=cdtp.vertices_in_constraint_begin(ctIdCollinear);
    vertexToRemoveCollinear++;


    std::cout<<"attempt to remove vertex "<<(*vertexToRemoveCollinear)->point().x()<<" , "<<(*vertexToRemoveCollinear)->point().x();
    cdtp.remove_vertex_from_constraint(ctIdCollinear,vertexToRemoveCollinear);

    std::cout<<"number of subconstraints "<<cdtp.number_of_subconstraints()<<std::endl; //--> 5, expected 4
    std::cout<<"number of constraints "<<cdtp.number_of_constraints()<<std::endl; //--> 1
    std::cout<<"number of vertex in constraint "<<countVertex(cdtp,ctIdCollinear)<<std::endl; //--> 6, expected 5
    
    
    //******************************* attempt with the collinear constraint
    auto vertexToRemoveNoCollinear=cdtp.vertices_in_constraint_begin(ctIdNoCollinear);
    vertexToRemoveNoCollinear++;

    std::cout<<"attempt to remove vertex "<<(*vertexToRemoveNoCollinear)->point().x()<<" , "<<(*vertexToRemoveNoCollinear)->point().x();
    cdtp.remove_vertex_from_constraint(ctIdNoCollinear,vertexToRemoveNoCollinear);

    std::cout<<"number of subconstraints "<<cdtp.number_of_subconstraints()<<std::endl; //--> 4, ok
    std::cout<<"number of constraints "<<cdtp.number_of_constraints()<<std::endl;  //--> 1
    std::cout<<"number of vertex in constraint "<<countVertex(cdtp,ctIdNoCollinear)<<std::endl;  //--> 5, ok

    return 0;

}
```

## Environment

* Operating system : Linux 64 bits
* Compiler: gcc
* Release or debug mode: debug
* Specific flags used (if any):
* CGAL version: master
* Boost version: 1.67
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by afabri** [comment]
Note that the function `remove_vertex_from_constraint()`  is not part of the documented API, so the simple answer is that you are not supposed to call it, because you do not know the preconditions.  Let me nevertheless check if such a functionality could be added easily.

**Comment by vcloarec** [comment]
I had seen this method is not part of the documented API, but as the auto indentation purposed me that method, it was hard to resist to use it because it can be very convenient ...
As  I want to make a do/undo command, I just want the possibility to return to the state before insertion of a constraint with intersection. So I have to remove the vertices resulting from this insertion without removing the intersected constraint.

**Comment by afabri** [comment]
So we maybe should also work on `public:` and `private:` in our code. Thank you for pointing this out.

**Comment by afabri** [comment]
I had a closer look. Removing a vertex on a constraint does not remove the point, so you are right that the constraint will again pass through the point and there will be a vertex again.  I am not sure if we want to add a function that removes a vertex and the point, and consequently more vertices in case they happen to be at the same point.  

And there was indeed a bug that I fixed.  I added your issue. Note that there might be more problems with this function - as I wrote in the PR this functions is currently neither used internally, nor documented or tested (well I added your issue to the testsuite).

**Comment by vcloarec** [comment]
Hello, thanks for your closer look. I understand this function is not very used. But it could be interesting, as I have wrote in my previous post, to permit to return to the initial state before a constraint was inserted with an intersection with another constraint.

```
constraint_1=cdtp.insert_constraint(v1,v2);
constraint_2=cdtp.insert_constraint(v3,v4);
```
if (v1,v2) intersects (v3,v4) another vertex v5 will be created and it is part of the two constraints.

To return to the state before contraint_2 insertion, we have to remove the contraint_2 and the vertex v5.

If it is possible to remove constraint_2, it seems it is not possible to remove vertex v5 without removing constraint_1. The function `remove_vertex_from_constraint`, will not removed the vertex because it is collinear with vertices v1 and v2, and internally, the function would recreate a vertex because the point is still here.

A solution could be, inside the function `remove_vertex_from_constraint`, to remove the vertex before reinsert and concatenate the pieces of the constraint, namely before this line :

https://github.com/CGAL/cgal/blob/6ad4b3934ed06c071e5ef24697f1b44ad552d15b/Triangulation_2/include/CGAL/Constrained_triangulation_plus_2.h#L416

But, it is not the aim of the function. It would be the aim of a `remove_vertex_on_constraint`, a function which removes a vertex which is on a constraint and without removing the constraint.
Such function could be very convenient, for example, to return to the initial state before constraint insertion with intersection. Or simply to remove an unwanted point in a constraint.
What do you think about ?

**Comment by lrineau** [comment]
PR #4029 is now merged. @afabri, @MaelRL, the PR #4029 signals that is fixed this issue #4025, but the discussion seems to speak about something else. Should I close this issue?

**Comment by afabri** [comment]
The original issue (a crash) is fixed. The OP then added somehow a feature request.

**Comment by lrineau** [comment]
So the bug reported on CGAL-4.13.1 is fixed. I will close the issue.

@vcloarec Please open a new issue about the feature request. Note that there is a nice feature of Github to copy-paste a comment into a new issue:
> ![Screenshot_20190703_115431](https://user-images.githubusercontent.com/5746675/60582541-53970f80-9d89-11e9-9eea-721c986cf2cc.png)
