### ISSUE TITLE
The FindTBB.cmake is wrong or too old

### ISSUE THREAD

**Issue by zhouheng** [CGAL/cgal#4028]
## Issue Details

Hi,

I am using Intel TBB for Windows version 2019 update 6 and CMake 3.14.5. CGAL's FindTBB.cmake can't locate TBB correctly when I tried to build the demo Triangulation_3 in cmake gui. It is mainly due to the section commented with #-- Look for libraries. Nowadays, tbbvars.bat sets environment variable TBB_TARGET_ARCH instead of TBB_ARCH_PLATFORM. Also these env var set by tbbvars are not visible to cmake gui because they exist only in the command line context that invokes tbbvars. As a result, _TBB_LIBRARY_DIR is empty and FindTBB.cmake reports error "TBB not found". So the logic of FindTBB.cmake is wrong or too old. Correction is therefore requested.

For now I have to manually add the correct env var generated by tbbvars and change the wrong (or too old) TBB_ARCH_PLATFORM, etc. var in FindTBB.cmake to TBB_TARGET_ARCH, etc. 

## Source Code

C:\dev\CGAL-4.14\cmake\modules\FindTBB.cmake

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows 10/64 bit, version 1803
* Compiler: Visual Studio 2015
* Release or debug mode: N/A
* Specific flags used (if any): N/A
* CGAL version: 4.14
* Boost version: 1.67
* Other libraries versions if used (Eigen, TBB, etc.): TBB: Windows version 2019 update 6, CMake: 3.14.5

**Comment by lrineau** [comment]
@zhouheng Could you please try to replace the CGAL version of `FindTBB.cmake`, by [this one from VTK](https://raw.githubusercontent.com/Kitware/VTK/master/CMake/FindTBB.cmake), and let us know if that worked correctly?

**Comment by zhouheng** [comment]
Yes, your version works with the latest TBB. I am looking forward to see it merged in the new version of CGAL. Thank you.

**Comment by sloriot** [comment]
@maxGimeno could you please prepare a PR for that?

**Comment by lrineau** [comment]
Closed by the merge of PR #4085
