### ISSUE TITLE
AccessViolationException with CGAL_PROFILE

### ISSUE THREAD

**Issue by taus** [CGAL/cgal#403]
When running CGAL with CGAL_PROFILE defined, the `operator()` of `Profile_histogram_counter` throws an AccessViolationException on this line: `++counters[i];` The call comes from destructor `CGAL::Gmpq::~Gmpq()`. It looks like the root node of the counters map has been freed.

This happens when compiling with Visual Studio 2015.

**Comment by afabri** [comment]
Can you please provide a minimal example.
