### ISSUE TITLE
Deprecated code in CGAL/Qt

### ISSUE THREAD

**Issue by maxGimeno** [CGAL/cgal#4061]
## Issue Details
In Qt 5.13, the function `matrix()` from the painter has been deprecated. The warning specifies that `transform()` should be use dinstead. Modifications should be made accordingly.

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):ArchLinux
* Compiler:CLang
* Release or debug mode: both
* CGAL version: 4.13
* Other libraries versions if used (Eigen, TBB, etc.): Qt 5.13

**Comment by lrineau** [comment]
That is [commit e5640181 in the branch of Qt-5.13](https://code.qt.io/cgit/qt/qtbase.git/commit/?h=5.13&id=e5640181). Those functions have been marked with `[[deprecated]]` (or equivalent).
