### ISSUE TITLE
read objfile to Surface_mesh

### ISSUE THREAD

**Issue by simonasdmd** [CGAL/cgal#4062]
I want to use cgal to simplify the mesh of obj files. But I read the official documentation. The official document is to convert the OFF file to Surface_mesh. But how can I convert obj files to Surface_mesh? I hope to provide a method.

I can't solve the mesh simplification problem of obj files according to the official documentation.

https://doc.cgal.org/latest/Surface_mesh_simplification/index.html#Chapter_Triangulated_Surface_Mesh_Simplification
Please tell me how to convert obj files into Surface_mesh. I found read_OBJ in the code. But I don't know how to use it. If you can tell me, I am grateful.

**Comment by sloriot** [comment]
try:
```
#include <CGAL/IO/OBJ_reader.h>
using K = CGAL::Exact_predicates_inexact_constructions_kernel;
 
// Load OBJ
std::vector<K::Point_3> points_ref;
std::vector<std::vector<std::size_t> > faces_ref;

std::ifstream in(argv[1]);
if(!in || !CGAL::read_OBJ(in,points_ref,faces_ref))
{
   return 1;
}

Mesh sm;
namespace PMP = CGAL::Polygon_mesh_processing;
PMP::orient_polygon_soup(points_ref,faces_ref); // optional if your mesh is not correctly oriented
PMP::polygon_soup_to_polygon_mesh(points_ref, faces_ref, sm);
```

**Comment by simonasdmd** [comment]
@sloriot 
hi~ Thank you very much for your reply.
Is mesh the same as Surface_mesh? I ended up trying to simplify the grid of obj files. An example of seeing the official documentation is to use "SMS::edge_collapse". This uses Surface_mesh and is not a mesh. What should I do?
Please tell me, thank you very much.

**Comment by sloriot** [comment]
It is either `Surface_mesh` or `Polyhedron_3` or any model of the `Facegraph` concept. I don't the last part of your question but edge collapse function works for both.

**Comment by simonasdmd** [comment]
@sloriot 
hi~ 
I still can't solve this problem. Maybe I am a bit stupid. Please tell me the whole process. Grateful.

I want to use the obj file to complete the simplification. But the official document only has an OFF file. It converts the off file to Surface_mesh. Then use SMS::edge_collapse to simplify. But I don't know how to turn obj into Surface_mesh. Please tell me this process.
![image](https://user-images.githubusercontent.com/42527845/60854048-57b3a900-a231-11e9-9b8a-962b8ed97ae0.png)
How to use obj file to complete this process

**Comment by sloriot** [comment]
Please post the code you have on gist.github.com

**Comment by simonasdmd** [comment]
@sloriot 
I can only read the obj file here. I really don't know how to read it into Surface_mesh.
![image](https://user-images.githubusercontent.com/42527845/60864367-f81bc480-a255-11e9-9629-1872acc8e2f2.png)
![image](https://user-images.githubusercontent.com/42527845/60864416-24374580-a256-11e9-9331-b4f39225c659.png)

Really need help. From a person who is not talented enough.

[main.zip](https://github.com/CGAL/cgal/files/3371477/main.zip)

**Comment by sloriot** [comment]
You were almost there!

`int r = SMS::edge_collapse(*mesh, stop); ` should do what you want.

**Comment by simonasdmd** [comment]
@sloriot 
Thank you. Now I can already use SMS::edge_collapse. But I have encountered new problems. When reading an OBJ file. I found that many f indexes for obj files are negative. Will cause the program to crash. If it is a positive number, it will be fine. Is there a solution to this problem?
![image](https://user-images.githubusercontent.com/42527845/60869092-e8ee4400-a260-11e9-8389-dc7e33af60e2.png)


[Tile_0.zip](https://github.com/CGAL/cgal/files/3371780/Tile_0.zip)

**Comment by sloriot** [comment]
You can try to fix that after the call to `read_OBJ` but I'm afraid I cannot help if you have an obj file that does not respect the norm.

**Comment by simonasdmd** [comment]
@sloriot 
The obj file is exported by 3dmax. Meshlab and Maya can load it. But there will be problems with read_OBJ. Can you help me see if there is a solution?

**Comment by sloriot** [comment]
@maxGimeno could you please have a look if this is an issue with our OBJ reader?

**Comment by lrineau** [comment]
I think it is:
https://en.wikipedia.org/wiki/Wavefront_.obj_file#Vertex_indices
> If an index is positive then it refers to the offset in that vertex list, starting at 1. If an index is negative then it relatively refers to the end of the vertex list, -1 referring to the last element.

**Comment by simonasdmd** [comment]
@lrineau 
Hello there. I know that the negative index of the obj file is reciprocal. However, CGAL's read obj file currently seems to only support positive indexing. Can this problem be solved?

**Comment by sloriot** [comment]
While we fix it, you can fix it your self by doing the translation of indices in the polygon vector using the size of the point container.

I've open #4066 to track the fix.

**Comment by simonasdmd** [comment]
@sloriot 
hi~
I simplified the OBJ file after SMS::edge_collapse. The obj exported by the normal has no vertex normals. Only vertices and faces. I want to get the vertex normal corresponding to the face. What should I do?
A correct obj file should have vertex normals
![image](https://user-images.githubusercontent.com/42527845/60935098-5484ef80-a2fb-11e9-8a4d-e060e94f9b5d.png)
I am very eager to know about this problem.

**Comment by sloriot** [comment]
> So confused why I can not search such functions using document??

@tub-sgg Because it is not documented. It will be documented by #4255
