### ISSUE TITLE
Handle negative indices while reading OBJ

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#4066]
I think it is:
https://en.wikipedia.org/wiki/Wavefront_.obj_file#Vertex_indices
> If an index is positive then it refers to the offset in that vertex list, starting at 1. If an index is negative then it relatively refers to the end of the vertex list, -1 referring to the last element.

_Originally posted by @lrineau in https://github.com/CGAL/cgal/issues/4062#issuecomment-509539166_

**Comment by simonasdmd** [comment]
I would like to ask when this problem can be completed.

**Comment by maxGimeno** [comment]
It is done already, it is passing the tests. It should be integrated soon.

**Comment by sloriot** [comment]
FYI the branch as been merge in the 4.13 branch and will be merge in the upcoming minutes in the 4.14 branch and master branch.
