### ISSUE TITLE
SMS::edge_collapse exported data lacking vertex normal

### ISSUE THREAD

**Issue by simonasdmd** [CGAL/cgal#4071]
hi~
I simplified the OBJ file after SMS::edge_collapse. The obj exported by the normal has no vertex normals. Only vertices and faces. I want to get the vertex  normal corresponding to the face. What should I do?
A correct obj file should have vertex normals
![image](https://user-images.githubusercontent.com/42527845/60934947-b55ff800-a2fa-11e9-8f42-f361ba192a14.png)
I am very eager to know about this problem.

**Comment by sloriot** [comment]
It is not handled by the viewer but I guess we could have an option in the writer.

**Comment by simonasdmd** [comment]
@sloriot 
Hi~, this question is urgent for me.
Can this be done in the next version?

**Comment by maxGimeno** [comment]
with #4122, if your Mesh type is Surface_mesh, exporting in OBJ will write down the vertex normals too, if they are stored in a property_map called "v:normal", associating a Kernel::Vector_3 value to a vertex_descriptor key. In hte Polyhedron_demo it is always prodided, in a custom program I guess you'll need to call [compute_normals()](https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__normal__grp.html#ga14a7730a996879ba6e7589dfeaccff82). You can test it from the branch or wait until the release.
