### ISSUE TITLE
Mesh simplification: does CGAL supports stop condition using number(or ratio) of vertices?

### ISSUE THREAD

**Issue by LYHTHU** [CGAL/cgal#4087]
I can only find stop conditions using the number or ratio of the faces.

**Comment by MaelRL** [comment]
There is no such stop condition, but you can very easily write your own, based on [Count_stop_predicate](https://github.com/CGAL/cgal/blob/master/Surface_mesh_simplification/include/CGAL/Surface_mesh_simplification/Policies/Edge_collapse/Count_stop_predicate.h) (or the stop ratio). You will need to match the signature (see the [StopPredicate concept](https://doc.cgal.org/latest/Surface_mesh_simplification/classStopPredicate.html)) for `operator()` and you can grab the number of vertices in your mesh from the edge profile class (https://doc.cgal.org/latest/Surface_mesh_simplification/classEdgeProfile.html#a34d6305eb4c4e7b32938980c8d718acb).
