### ISSUE TITLE
Link error with CGAL 4.14 due to some 'inline' missing in write_ply_points.h

### ISSUE THREAD

**Issue by elombardi2** [CGAL/cgal#4090]
## Issue Details

Link error `multiple definition of void CGAL::internal::PLY::property_header_type<char>(std::ostream&)` when `write_ply_points.h` is included by several compilation unit.

This error is due to some `inline` missing in `write_ply_points.h`.

Suggested fix: [write_ply_points.zip](https://github.com/CGAL/cgal/files/3396344/write_ply_points.zip)

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Linux
* Compiler: gcc version 7.4.0
* Release or debug mode: debug & release
* Specific flags used (if any):
* CGAL version: 4.14 release
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by lrineau** [comment]
Closed by the merge of PR #4107.
