### ISSUE TITLE
ld: library not found for -lCGAL

### ISSUE THREAD

**Issue by waschbaer00** [CGAL/cgal#4092]
## Issue Details

The installation of CGAL is fine. The problem occurred when I use CGAL in my project. The cmake for my project is also fine, it is when I make the project, it tells me
```
 ld: library not found for -lCGAL
```
## Source Code: CMakeLists.txt in SUB directory

```
CMAKE_MINIMUM_REQUIRED(VERSION 3.4)
SET(EXECUTABLE_OUTPUT_PATH ../../cgal_test/bin)
SET(APP_NAME TestDetectPlanes)
ADD_EXECUTABLE( ${APP_NAME}  main_shape_detection.cpp )
TARGET_LINK_LIBRARIES( ${APP_NAME} ${CGAL_LIB})
TARGET_COMPILE_OPTIONS( ${APP_NAME} PRIVATE -std=c++11 )
```

## Source Code: CMakeLists.txt in TOP directory

```
SET(CGAL_ROOT "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/CGAL/")
find_package(Boost 1.69.0 REQUIRED COMPONENTS thread system)
include_directories(${Boost_INCLUDE_DIRS})
FIND_PACKAGE(CGAL 4.14 REQUIRED HINTS "${CGAL_ROOT}")
INCLUDE_DIRECTORIES(${CGAL_INCLUDE_DIRS})
```

## Environment

* Operating system : MacOS mojave 10.14.2
* CGAL version: 4.14
* Boost version: 1.70
* Other libraries versions if used: eigen 3.7
* CGAL install prefix path: thirdparty/CGAL/cgal_install
* CGALConfig.cmake path: thridparty/CGAL

**Comment by mglisse** [comment]
Did you see https://github.com/CGAL/cgal/wiki/How-to-use-CGAL-with-CMake-or-your-own-build-system ? I don't think CGAL_LIB is the variable you want.

**Comment by lrineau** [comment]
I agree with Marc Glisse. The correct usage of CMake is:
- in the sub-directory:
  ```cmake
  CMAKE_MINIMUM_REQUIRED(VERSION 3.4)
  SET(EXECUTABLE_OUTPUT_PATH ../../cgal_test/bin)
  SET(APP_NAME TestDetectPlanes)
  ADD_EXECUTABLE( ${APP_NAME}  main_shape_detection.cpp )
  TARGET_LINK_LIBRARIES( ${APP_NAME} CGAL::CGAL)
  ```
  Note that `CGAL::CGAL` replaces `${CGAL_LIB}`.
- in the top directory:
  ```cmake
  SET(CGAL_ROOT "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/CGAL/")
  find_package(Boost 1.69.0 REQUIRED COMPONENTS thread system)
  include_directories(${Boost_INCLUDE_DIRS})
  FIND_PACKAGE(CGAL 4.14 REQUIRED HINTS "${CGAL_ROOT}")
  ```

Note that I have removed the use of `${CGAL_INCLUDE_DIRS}` and `TARGET_COMPILE_OPTIONS`, because the linking with the imported targe `CGAL::CGAL`

You can read [this page] to get a better understanding of modern usage of CMake.

[this page]: https://pabloariasal.github.io/2018/02/19/its-time-to-do-cmake-right/
