### ISSUE TITLE
Testing CGAL takes loads of Gigs

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#4097]
I used to compile CGAL with examples, tests, and demo + ctest to check that everything is right in integration before the testsuite (or even in a branch modify things in various places). I noticed recently that my system was complaining that my disk is full. Today I looked and I noticed that a build of integration stop because I did not have any more disk spaces, after having filled more than 36Go.

@maxGimeno would you mind checking for example with the 4.13 branch if it was already the case? If not could you try to bisect to understand what went wrong?

I'm using:
`cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_examples=ON -DWITH_tests=ON -DWITH_demos=ON -DBUILD_TESTING=ON -DCMAKE_CXX_FLAGS="-Wall -Wextra" ../..`

**Comment by maxGimeno** [comment]
It was already like this in 4.12

**Comment by lrineau** [comment]
Debug builds are heavy. The [compile option `-gz`][gz] might help, if your toolchain supports it.

[gz]: https://gcc.gnu.org/onlinedocs/gcc/Debugging-Options.html
