### ISSUE TITLE
Mesh_3 still uses Do_intersect functor even if CGAL_MESH_3_NO_LONGER_CALLS_DO_INTERSECT_3 is defined

### ISSUE THREAD

**Issue by SLopezBRGM** [CGAL/cgal#41]
When `CGAL_MESH_3_NO_LONGER_CALLS_DO_INTERSECT_3` is defined one would expect that he does not have to implement the `Do_intersect` functor class (http://doc.cgal.org/latest/Mesh_3/classMeshDomain__3.html).

This is false and there are still parts of the code in Mesh_3 package that use it it even if `CGAL_MESH_3_NO_LONGER_CALLS_DO_INTERSECT_3` is defined .

**Comment by lrineau** [comment]
Thanks for the report Simon. I have marked it for 4.7, so that the bug report is not forgot.

**Comment by lrineau** [comment]
Fixed by #51
