### ISSUE TITLE
assertion error when combining pyramid and prism

### ISSUE THREAD

**Issue by benlaurie** [CGAL/cgal#4117]
## Issue Details

CGAL error: assertion violation!
Expression : (size_ == 2 && (v == first || v == second) ) || v==first
File       : /usr/local/include/CGAL/Polygon_mesh_processing/internal/Corefinement/intersection_impl.h
Line       : 141

## Source Code
```
#include <CGAL/Cartesian.h>
#include <CGAL/Surface_mesh.h>
#include <CGAL/Polygon_mesh_processing/corefinement.h>

typedef CGAL::Cartesian<double>     Kernel;
typedef Kernel::Point_3                    Point;
typedef CGAL::Surface_mesh<Point>          Mesh;

int main(int argc, char **argv)
    {
    Mesh cone;
    CGAL::make_pyramid(16,
         cone,
         Point(0, 0, 0),
         1,
         1);

    Mesh cylinder;
    CGAL::make_regular_prism(16,
        cylinder,
        Point(0, .1, 0),  // just above the base
        1,  // extend beyond the apex
        .5);

    Mesh combined;
    CGAL::Polygon_mesh_processing::corefine_and_compute_union(cone,
             cylinder,
             combined);

    }
```
## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): MacOS
* Compiler: FreeBSD clang version 6.0.0 (tags/RELEASE_600/final 326565) (based on LLVM 6.0.0)
Target: x86_64-unknown-freebsd11.2
Thread model: posix
* Release or debug mode:
* Specific flags used (if any):
* CGAL version: 4.13
* Boost version: 
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by sloriot** [comment]
You need to use a kernel with exact predicates like `CGAL::Exact_predicates_inexact_constructions_kernel` instead of `Cartesian<double>`.

See this [FAQ entry](https://www.cgal.org/FAQ.html#inexact_NT) for more details.
