### ISSUE TITLE
Boost config.hpp error

### ISSUE THREAD

**Issue by csverma610** [CGAL/cgal#4134]
Hello,

Although I followed the instructions, I am having tough time resolving the boost/config.hpp not found in 4.14 version on Ubuntu 18.04

The path to boost is correctly detected by the CMake.

/home/csverma/Disk/Software/System/Boost/Latest/lib/cmake/boost_headers-1.70.0                                                  
 boost_iostreams_DIR              /home/csverma/Disk/Software/System/Boost/Latest/lib/cmake/boost_iostreams-1.70.0                                                
 boost_serialization_DIR          /home/csverma/Disk/Software/System/Boost/Latest/lib/cmake/boost_serialization-1.70.0                                            
 boost_system_DIR                 /home/csverma/Disk/Software/System/Boost/Latest/lib/cmake/boost_system-1.70.0                                                   
 boost_thread_DIR                 /home/csverma/Disk/Software/System/Boost/Latest/lib/cmake/boost_thread-1.70.0     

I did not have any issue with 4.13. 

Thanks.
csv

_Please use the following template to help us solving your issue._

## Issue Details

_Describe your issue. Please be specific (compilation error, runtime error, unexpected behavior, wrong results, etc.)._

## Source Code

_If your issue arises by using CGAL in your own source code, please provide a minimalist example that we can compile easily to reproduce the bug. If your issue arises from using a CGAL program (demo, example, etc.), please let us know which one. Helping you solving an issue is much easier and efficient if we can reproduce it._

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):
* Compiler:
* Release or debug mode:
* Specific flags used (if any):
* CGAL version:
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by sloriot** [comment]
Sorry for the late reply. Do you still have the issue? is so could you provide the error message you have?

**Comment by MaelRL** [comment]
bump @csverma610
