### ISSUE TITLE
the problem about  CGAL::Uncertain_conversion_exception

### ISSUE THREAD

**Issue by KeepFaithMe** [CGAL/cgal#4135]
_Please use the following template to help us solving your issue._

## Issue Details

_Describe your issue. Please be specific (compilation error, runtime error, unexpected behavior, wrong results, etc.)._

## Source Code

_If your issue arises by using CGAL in your own source code, please provide a minimalist example that we can compile easily to reproduce the bug. If your issue arises from using a CGAL program (demo, example, etc.), please let us know which one. Helping you solving an issue is much easier and efficient if we can reproduce it._

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):
* Compiler:
* Release or debug mode:
* Specific flags used (if any):
* CGAL version:
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by KeepFaithMe** [comment]
when I use the PMP::isotropic_remeshing() method to remesh my data,there is a probelm.when the size of the data is small,such as the number of the faces or vertices just have Hundreds or thousands,this function is collection;but when the size of the data is to big,such as the szie of the data file is Hundreds KBS,the function can not execute exactly.And the error of tips is " CGAL::Uncertain_conversion_exception".so I do'nt konw what's wrong with the function.
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/Surface_mesh.h>

#include <CGAL/Polygon_mesh_processing/remesh.h>
#include <CGAL/Polygon_mesh_processing/border.h>

#include <boost/function_output_iterator.hpp>
#include <fstream>
#include <vector>

typedef CGAL::Exact_predicates_inexact_constructions_kernel K;
typedef CGAL::Surface_mesh<K::Point_3> Mesh;

typedef boost::graph_traits<Mesh>::halfedge_descriptor halfedge_descriptor;
typedef boost::graph_traits<Mesh>::edge_descriptor     edge_descriptor;

namespace PMP = CGAL::Polygon_mesh_processing;

struct halfedge2edge
{
	halfedge2edge(const Mesh& m, std::vector<edge_descriptor>& edges)
		: m_mesh(m), m_edges(edges)
	{}
	void operator()(const halfedge_descriptor& h) const
	{
		m_edges.push_back(edge(h, m_mesh));
	}
	const Mesh& m_mesh;
	std::vector<edge_descriptor>& m_edges;
};

int main()
{
	const char* filename = "C:/Users/10712/Desktop/test/02111/02111.off";
	std::ifstream input(filename);

	Mesh mesh;
	if (!input || !(input >> mesh) || !CGAL::is_triangle_mesh(mesh)) {
		std::cerr << "Not a valid input file." << std::endl;
		return 1;
	}
	
	double target_edge_length = 1;
	unsigned int nb_iter = 1; 

	std::cout << "Split border...";

	std::vector<edge_descriptor> border;
	PMP::border_halfedges(faces(mesh),
		mesh,
		boost::make_function_output_iterator(halfedge2edge(mesh, border)));
	PMP::split_long_edges(border, target_edge_length, mesh);

	std::cout << "done." << std::endl;

	std::cout << "Start remeshing of " << filename
		<< " (" << num_faces(mesh) << " faces)..." << std::endl;

	PMP::isotropic_remeshing(faces(mesh), target_edge_length, mesh, 
       PMP::parameters::number_of_iterations(nb_iter).protect_constraints(true));
	std::cout << "Remeshing done." << std::endl;
	return 0;
}

Operation System Windows:
Debug Mode
CGAL version 4.12.2

**Comment by janetournois** [comment]
Hi @KeepFaithMe 
can you please send some data so that we can try to reproduce this issue?
`isotropic_remeshing()` has already been run on quite big data sets, so it should not be the problem.

**Comment by KeepFaithMe** [comment]
Hi
      I am very happy to receive your reply!I will send you my data.This Model is a building Model,and I want to remesh this Model.This model is around 8M.The raw data for the building model was.obj, which I converted to.off using the Openctm's tools and remesh it.
       when I remesh this building model,The code I refer to is https://doc.cgal.org/latest/Polygon_mesh_processing/Polygon_mesh_processing_2isotropic_remeshing_example_8cpp-example.html#a4.The running time is very long and  wrong.I was very confused.
      If you konw what's problem it is,please tell me.I just used this open source library, so there's a lot I don't understand.


        Thanks again for your reply and looking forward to your reply.



         Thank you again!

      
    
      


------------------ 原始邮件 ------------------
发件人: "Jane Tournois"<notifications@github.com>;
发送时间: 2019年8月5日(星期一) 下午3:27
收件人: "CGAL/cgal"<cgal@noreply.github.com>;
抄送: "张川"<1071244263@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [CGAL/cgal] the problem about CGAL::Uncertain_conversion_exception (#4135)




Hi @KeepFaithMe
 can you please send some data so that we can try to reproduce this issue?
 isotropic_remeshing() has already been run on quite big data sets, so it should not be the problem.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


从QQ邮箱发来的超大附件

Building Model.off (7.59M, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=7e3761305218b099ded4b80f136404495b01505454070204140557520049025500514c520706534b580e5000030555545f000554357636244c5e0d545c0a514674580555594a59005f375c&t=exs_ftn_download&code=97a05d6f

**Comment by KeepFaithMe** [comment]
Hi Jane Tournois
       Bother you again. I think the reason for this error is the unreasonable target_edge_length setting, so I would like to ask if there is any way to calculate the side length of the model and set this value reasonably.If the amount of model data is too large and the target_edge_length is set too small, the program will run too long, so is there a good way to fix this.


This is just my thinking. If there is something wrong, please correct it.



       Looking forward to  you reply! thank you! 

       




------------------ 原始邮件 ------------------
发件人: "Jane Tournois"<notifications@github.com>;
发送时间: 2019年8月5日(星期一) 下午3:27
收件人: "CGAL/cgal"<cgal@noreply.github.com>;
抄送: "张川"<1071244263@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [CGAL/cgal] the problem about CGAL::Uncertain_conversion_exception (#4135)




Hi @KeepFaithMe
 can you please send some data so that we can try to reproduce this issue?
 isotropic_remeshing() has already been run on quite big data sets, so it should not be the problem.

**Comment by janetournois** [comment]
You can use the CGAL Polyhedron demo (see [here](https://doc.cgal.org/latest/Polyhedron/group__PkgPolyhedronRef.html) ) to get all the statistics on your data (size of the object, statistics on edge lengths, validity etc)

**Comment by janetournois** [comment]
Then send your data and we will have a look at it so that we can check if the problem comes from the remeshing function

**Comment by KeepFaithMe** [comment]
Hi Jane Tournois
      Thank you for you reply.I will try it.
      Thank you again.Everything goes well with you work and life.




------------------ 原始邮件 ------------------
发件人: "Jane Tournois"<notifications@github.com>;
发送时间: 2019年8月5日(星期一) 下午4:33
收件人: "CGAL/cgal"<cgal@noreply.github.com>;
抄送: "张川"<1071244263@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [CGAL/cgal] the problem about CGAL::Uncertain_conversion_exception (#4135)




You can use the CGAL Polyhedron demo (see here ) to get all the statistics on your data (size of the object, statistics on edge lengths, validity etc)
