### ISSUE TITLE
Isotropic remeshing creates self intersections

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#4144]
## Issue Details

* Load the mesh in the Polyhedron demo
* Select 60 degree edges
* Isotropic remesh :  0.0015,  3 iterations, 3 smoothings, protect, allow

[cheese_transformed-facets.zip](https://github.com/CGAL/cgal/files/3485856/cheese_transformed-facets.zip)

The resulting mesh has self intersections as well as triangles with very small angles

## Environment

* CGAL version: master

**Comment by janetournois** [comment]
I am investigating on this issue, and found out it is yet another problem of degenerate faces created by a collapse step.
