### ISSUE TITLE
[question] adding criterion to Mesh_criteria?

### ISSUE THREAD

**Issue by nschloe** [CGAL/cgal#4145]
I would like to add `cell_size` to my `Mesh_criteria` if it's not `nullptr`. To this end, I'm doing
```c++
  Mesh_criteria criteria;
  if (cell_size) {
    Sizing_field_wrapper size(cell_size);
    criteria = Mesh_criteria(
        CGAL::parameters::edge_size=edge_size,
        CGAL::parameters::facet_angle=facet_angle,
        CGAL::parameters::facet_size=facet_size,
        CGAL::parameters::facet_distance=facet_distance,
        CGAL::parameters::cell_radius_edge_ratio=cell_radius_edge_ratio,
        CGAL::parameters::cell_size=size
        );
  } else {
    criteria = Mesh_criteria(
        CGAL::parameters::edge_size=edge_size,
        CGAL::parameters::facet_angle=facet_angle,
        CGAL::parameters::facet_size=facet_size,
        CGAL::parameters::facet_distance=facet_distance,
        CGAL::parameters::cell_radius_edge_ratio=cell_radius_edge_ratio
        );
  }
```
Meh. Is is possible to create a `Mesh_criteria` object and _add_ a parameter?

**Comment by janetournois** [comment]
Hi @nschloe 

You can have a look in the undocumented header `CGAL\Mesh_3\mesh_standard_criteria.h`.

There are a `class Criteria`, with a function `void add(Criterion* criterion_)`, and the abstract class `Abstract_criterion` defines how a `Criterion` should be implemented.

Is this what you need?

**Comment by nschloe** [comment]
@janetournois I can't find the file you mention. Care to post a link?

**Comment by sloriot** [comment]
It is a new file in the master branch of CGAL. See here:
https://github.com/CGAL/cgal/blob/master/Mesh_3/include/CGAL/Mesh_3/mesh_standard_criteria.h

**Comment by nschloe** [comment]
I'm not sure how to use this. I had something like
```
    auto criteria = Mesh_criteria(
        CGAL::parameters::edge_size=edge_size,
        CGAL::parameters::facet_angle=facet_angle,
        CGAL::parameters::facet_size=facet_size,
        CGAL::parameters::facet_distance=facet_distance,
        CGAL::parameters::cell_radius_edge_ratio=cell_radius_edge_ratio
        );

    criteria.add(CGAL::parameters::cell_size=size);
```
in mind. How would you have to modify the above code to get it to work?

**Comment by sloriot** [comment]
You need to define a new criteria class that inherits from `Abstract_criterion` and that implements the pure virtual functions. The simplest example is probably [`Mesh_cell_criteria_3`](https://github.com/CGAL/cgal/blob/master/Mesh_3/include/CGAL/Mesh_cell_criteria_3.h).
