### ISSUE TITLE
isotropic_remeshing never returns even when is_valid_polygon_mesh is true

### ISSUE THREAD

**Issue by jasjuang** [CGAL/cgal#4148]
## Issue Details

For this specific mesh [test2.zip](https://github.com/CGAL/cgal/files/3490335/test2.zip) if I run the below code `isotropic_remeshing` will never return. Note that I already applied PR #4139 and #4129 and the problem is still there. Please let me know if you can replicate the problem.

## Source Code

```
typedef CGAL::Simple_cartesian<double> K;
typedef CGAL::Surface_mesh<K::Point_3> Mesh;

Mesh m;

std::ifstream input("test2.off");
input >> m;
input.close();

std::cout << CGAL::is_valid_polygon_mesh(m) << std::endl;

// never returns
CGAL::Polygon_mesh_processing::isotropic_remeshing(faces(m), 5.0, m)
```

## Environment

* Operating system: Ubuntu 18.04
* Compiler: GCC 7
* Release or debug mode: Release
* CGAL version: PR #4139 and manually applied #4129
* Boost version: 1.68

**Comment by janetournois** [comment]
Hi @jasjuang,
thank you for the report.
I can reproduce your problem, I'm trying to fix it.

**Comment by janetournois** [comment]
Hi @jasjuang 
The new PR #4149 should fix your issue.

**Comment by jasjuang** [comment]
@janetournois I can confirm PR #4149 fixes the minimal example I posted. However, in my actual application `Mesh m` is not directly read from a .off file, there's a lot of operations before it. When I run my application directly, it segfaults at `isotropic_remeshing`. However, if right before calling `isotropic_remeshing` I write the mesh into a .off file and then read it back immediately and pass it into `isotropic_remeshing` it works. That means the read/write to .off file somehow fixes something that makes `isotropic_remeshing` work. I am trying to figure out how I can reproduce this for you as simplified as possible. In the meantime, are you aware of how writing and reading to a .off file could potentially fix things?

**Comment by jasjuang** [comment]
After more testing, I realized #4149 actually causes segfault on some other meshes that `isotropic_remeshing` run successfully before. Meaning if I revert to master + #4139 `isotropic_remeshing` start working again. I think #4149 fixes this minimal example but at the same time, it broke some other cases.

**Comment by janetournois** [comment]
Thank you for that, I noticed the same thing and I am working on it today.

**Comment by janetournois** [comment]
Hi @jasjuang,
we are testing it further on our side, but the PR #4178 should fix the issue.
Thanks again for the report!

**Comment by jasjuang** [comment]
Thanks! I can confirm PR #4178 fixes this issue and didn't cause additional segfault on other meshes. Please merge!
