### ISSUE TITLE
Arr_2: Issue with visitor in post face insertion

### ISSUE THREAD

**Issue by MaelRL** [CGAL/cgal#4158]
## Issue Details

The doc of [after_split_face](https://doc.cgal.org/latest/Arrangement_on_surface_2/classCGAL_1_1Arr__observer.html#ae382d8a32ea9ef3fab11434705f57dea) says `the existing face f1 has been split, such that a portion of it now forms a new face f2`.

In practice, we don't always have that `f1` is the old face and `f2` is the new face.

For example: create a square with edges `<(0,0), (10,0), (10, 10), (0,10), (0,0)>` and then a triangle which partitions the square and the unbounded face into two faces. The triangle’s edges are `<(3,7), (7,7), (5,12), (3,7)>` (inserting segments one by one). For some insertions, `f2` is the old face.

Base code found [here](https://gist.github.com/MaelRL/7a1033ae0712ae992c1d448dfce516b6) (just need to plug-in the segment values).

**Comment by sloriot** [comment]
@efifogel Any chance you can fix it within a month or shall I try to fix it?

**Comment by sloriot** [comment]
The issue is actually not a code issue but a doc issue.

**Comment by efifogel** [comment]
Sorry, I guess I've missed it.
Anyhow, I see that you fixed it.
   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/
