### ISSUE TITLE
The dynamic_property_maps have no name

### ISSUE THREAD

**Issue by maxGimeno** [CGAL/cgal#4162]
## Issue Details
The dynamic-property_maps, if used on a surface_mesh, will internally call the `Surface_mesh::add_property()` function. The problem is that a dynamic_property_map has no `name` parmeter to forward to the surface_mesh, which makes it impossible to retrieve the property once added. 

I propose either :
-  to add an overload to the dynamic  `get()` functions that takes a `std::string name` as parameter, that would be forwarded to the surface_mesh
- or to add a `std::string name` to the` dynamic_XXX_property_t`<T> structs and the constructor to initialize it, so we can keep the boost `get()` API and still have a name to give to the surface_mesh.

That would help to BGLize the `read_off()` functions, within the scope of the reorganization of the CGAL IO functions.

@CGAL/geometryfactory what do you think ?

**Comment by sloriot** [comment]
What's the issue? it has an auto removal feature so why would you like to retrieve it? You are not supposed to loose the reference over it.

**Comment by maxGimeno** [comment]
What is the point of using the surface_mesh mechanism as an internal mechanism then ?

**Comment by sloriot** [comment]
You are supposed to keep the reference over the map otherwise it will be deleted.

**Comment by MaelRL** [comment]
Seems like this feature request is invalid ? @maxGimeno @sloriot

**Comment by sloriot** [comment]
Again I'm not sure to understand the question, but if I understand it correctly then it should be closed :)

**Comment by afabri** [comment]
Max Lyon told me that in OpenMesh they introduce with 8.1 a PropertyManager, and properties without name that get deleteted when the property handle goes out of scope.  It is maybe easier to discuss this the next time @sloriot is at GF.

**Comment by maxGimeno** [comment]
I don't need this anymore and don't remember why I said that. Probably I didn't understand how to use the dyamic properties. I think this issue can be closed now.
