### ISSUE TITLE
CGAL::Polygon_mesh_processing::sample_triangle_mesh(...) grid sampling omits faces for large heterogeneous polygon soup triangle mesh

### ISSUE THREAD

**Issue by mikeroberts3000** [CGAL/cgal#4164]
Hello there,

Thank you to the CGAL team for all your great work on this wonderful library. The purpose of this note is to report an issue with the surface sampling functionality in `CGAL::Polygon_mesh_processing::sample_triangle_mesh(...)`. In particular, it appears that some of my triangle mesh faces are being omitted from the sampling procedure. I'd be happy to provide a private download link to my complete standalone example that demonstrates the issue, including the triangle mesh data. See details below.

## Issue Details

1. I begin by generating a polygon soup representation of a scene that I obtained from an online content marketplace The details here are not important, other than to say that my data comes from "in-the-wild" art assets downloaded from the internet, and my scene contains several distinct objects. I generate a Vx3 vertex array and an Fx3 face array for the V vertices and F faces in my scene. I save these arrays as HDF5 files so I can easily interchange them between Python and C++.

2. I visualize my polygon soup using the Mayavi Python library, and confirm that there are no missing faces. See screenshot below. __Note that there are no holes in the roof of this triangle mesh.__
 
![visualize_mesh](https://user-images.githubusercontent.com/2341965/63296167-47a4d580-c283-11e9-8794-8c067d6f1acd.png)

Here is my complete visualization code.

```
import h5py
import mayavi.mlab
import numpy as np

mesh_vertices_hdf5_file = "mesh_vertices.hdf5"
mesh_faces_vi_hdf5_file = "mesh_faces_vi.hdf5"
mesh_faces_oi_hdf5_file = "mesh_faces_oi.hdf5"

with h5py.File(mesh_vertices_hdf5_file, "r") as f: mesh_vertices = f["dataset"][:]
with h5py.File(mesh_faces_vi_hdf5_file, "r") as f: mesh_faces_vi = f["dataset"][:]
with h5py.File(mesh_faces_oi_hdf5_file, "r") as f: mesh_faces_oi = f["dataset"][:]

# set the vertex object ID to the face object ID 
mesh_vertices_oi = np.zeros(mesh_vertices.shape[0])
mesh_faces_vi_   = mesh_faces_vi.reshape(-1)
mesh_faces_oi_   = (np.ones_like(mesh_faces_vi)*mesh_faces_oi[:,np.newaxis]).reshape(-1)
mesh_vertices_oi[mesh_faces_vi_] = mesh_faces_oi_

# map the vertex object ID to a color using the "jet" color map
mayavi.mlab.triangular_mesh(mesh_vertices[:,0], mesh_vertices[:,1], mesh_vertices[:,2], mesh_faces_vi, scalars=mesh_vertices_oi, colormap="jet", representation="surface", opacity=1.0)
mayavi.mlab.show()
```

3. I would like to sample points on this triangle mesh using CGAL. With this goal in mind, I load my vertex and face data into a C++ app. Next, I add all my vertices to a `CGAL::Surface_mesh` using the `CGAL::Surface_mesh::add_vertex(...)` function, proceeding one vertex at a time. Next, I add all my faces to my `CGAL::Surface_mesh` in a similar fashion using the `CGAL::Surface_mesh::add_face(...)` function, proceeding one face at a time. Next, I call the `CGAL::Polygon_mesh_processing::sample_triangle_mesh(...)` function to sample points on my mesh. Finally, I save the sampled points as an OBJ file and load the resulting point cloud in CloudCompare. See screenshot below. For visualization purposes, I have manually performed an axis-aligned crop on the resulting point cloud in CloudCompare. __Note that there is a large hole in the roof of this point cloud, indicating that some faces were not correctly sampled.__

![visualize_mesh_samples](https://user-images.githubusercontent.com/2341965/63296686-85eec480-c284-11e9-81c5-328fa74b6ee8.png)

Here is my complete triangle mesh sampling code.

```
#include <assert.h>
#include <iostream>
#include <string>

#include <armadillo>
#include <CGAL/Simple_cartesian.h>
#include <CGAL/Surface_mesh.h>
#include <CGAL/Polygon_mesh_processing/distance.h>

typedef CGAL::Simple_cartesian<double>      CGAL_K;
typedef CGAL::Surface_mesh<CGAL_K::Point_3> CGAL_Surface_mesh;
typedef CGAL_Surface_mesh::Vertex_index     CGAL_Vertex_index;
typedef CGAL_Surface_mesh::Face_index       CGAL_Face_index;

int main (int argc, const char** argv) {

    auto mesh_vertices_file = "mesh_vertices.hdf5";
    auto mesh_faces_vi_file = "mesh_faces_vi.hdf5";

    arma::mat mesh_vertices;
    arma::imat mesh_faces_vi;

    mesh_vertices.load(mesh_vertices_file, arma::hdf5_binary_trans);
    mesh_faces_vi.load(mesh_faces_vi_file, arma::hdf5_binary_trans);

    assert(mesh_vertices.n_cols == 3);
    assert(mesh_faces_vi.n_cols == 3);

    CGAL_Surface_mesh cgal_surface_mesh;
    cgal_surface_mesh.reserve(mesh_vertices.n_rows, 3*mesh_faces_vi.n_rows, mesh_faces_vi.n_rows);

    std::vector<CGAL_Vertex_index> cgal_vertex_indices;
    std::vector<CGAL_Face_index> cgal_face_indices;

    std::cout << "Adding vertices..." << std::endl;

    for (int i = 0; i < mesh_vertices.n_rows; i++) {
        auto cgal_vertex_index = cgal_surface_mesh.add_vertex(CGAL_K::Point_3(mesh_vertices(i,0), mesh_vertices(i,1), mesh_vertices(i,2)));
        cgal_vertex_indices.push_back(cgal_vertex_index);
    }

    std::cout << "Adding faces..." << std::endl;

    for (int i = 0; i < mesh_faces_vi.n_rows; i++) {
        auto cgal_face_index = cgal_surface_mesh.add_face(cgal_vertex_indices[mesh_faces_vi(i,0)], cgal_vertex_indices[mesh_faces_vi(i,1)], cgal_vertex_indices[mesh_faces_vi(i,2)]);
        cgal_face_indices.push_back(cgal_face_index);
    }

    std::cout << "Checking triangle mesh validity..." << std::endl;

    auto retval = cgal_surface_mesh.is_valid(true);
    assert(retval);

    std::cout << "Sampling triangle mesh..." << std::endl;

    std::vector<CGAL_K::Point_3> cgal_mesh_samples;
    CGAL::Polygon_mesh_processing::sample_triangle_mesh(cgal_surface_mesh, std::back_inserter(cgal_mesh_samples), CGAL::parameters::use_grid_sampling(true).grid_spacing(2.5));

    std::cout << "Saving output..." << std::endl;

    std::ofstream ofstream;
    ofstream.open("triangle_mesh_samples.obj", std::ios::out);

    for (auto s : cgal_mesh_samples) {
        ofstream << "v " << s[0] << " " << s[1] << " " << s[2] << std::endl;
    }

    ofstream.close();

    return 0;
}
```

Here is a corresponding Makefile.

```
ARMADILLO_INCLUDE_DIR:=/usr/local/include
ARMADILLO_LIB_DIR:=/usr/local/lib
ARMADILLO_EXTRA_CPP_FLAGS:=-DARMA_USE_HDF5

CGAL_INCLUDE_DIR:=/usr/local/include
CGAL_LIB_DIR:=/usr/local/lib

default:
	g++ sample_triangle_mesh.cpp \
	-o sample_triangle_mesh \
	-std=c++11 \
	-I$(ARMADILLO_INCLUDE_DIR) \
	-I$(CGAL_INCLUDE_DIR) \
	-L$(ARMADILLO_LIB_DIR) -larmadillo \
	-L$(CGAL_LIB_DIR) -lCGAL_Core -lCGAL \
	$(ARMADILLO_EXTRA_CPP_FLAGS)
```

## Source Code

See above.

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):

macOS 64 bit

* Compiler:

```
Mikes-MacBook-Pro-15-2018-Work-2:sample_triangle_mesh_example mike$ g++ --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

* Release or debug mode:

I'm not sure. I obtained CGAL using Homebrew by typing `brew install cgal`. I would assume that I have a release build, although I have encountered CGAL asserts during development. Does this mean I have a debug build?

* CGAL version:

```
Mikes-MacBook-Pro-15-2018-Work-2:sample_triangle_mesh_example mike$ brew info cgal
cgal: stable 4.14 (bottled)
Computational Geometry Algorithm Library
https://www.cgal.org/
/usr/local/Cellar/cgal/4.14_1 (3,292 files, 36.3MB) *
  Poured from bottle on 2019-08-18 at 12:00:41
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/cgal.rb
==> Dependencies
Build: cmake ✘
Required: boost ✔, eigen ✔, gmp ✔, mpfr ✔
==> Analytics
install: 4,337 (30 days), 17,054 (90 days), 62,465 (365 days)
install_on_request: 456 (30 days), 1,919 (90 days), 7,374 (365 days)
build_error: 0 (30 days)
```

* Boost version:

```
Mikes-MacBook-Pro-15-2018-Work-2:sample_triangle_mesh_example mike$ brew info boost
boost: stable 1.70.0 (bottled), HEAD
Collection of portable C++ source libraries
https://www.boost.org/
/usr/local/Cellar/boost/1.70.0 (13,983 files, 521.8MB) *
  Poured from bottle on 2019-08-18 at 12:00:33
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/boost.rb
==> Dependencies
Required: icu4c ✔
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 32,761 (30 days), 132,179 (90 days), 633,427 (365 days)
install_on_request: 12,114 (30 days), 45,819 (90 days), 200,115 (365 days)
build_error: 0 (30 days)
```

**Comment by mikeroberts3000** [comment]
Hi @maxGimeno, please do let me know if it would be helpful for me to send you the triangle mesh data for this example.

**Comment by maxGimeno** [comment]
Hi @mikeroberts3000 ,
yes I'd like an example data set, that would probably help me.

**Comment by mikeroberts3000** [comment]
Ah perfect ok. This is a temporary link, so please do let me know when you've downloaded the file. Thanks for looking into this 😄

https://www.dropbox.com/s/cqwxhbt8sx4sw1e/sample_triangle_mesh_example.zip?dl=0

**Comment by maxGimeno** [comment]
Thank you, I got it.

**Comment by maxGimeno** [comment]
So I extracted the roof part and sampled it, I don't get any big hole :

![image](https://user-images.githubusercontent.com/11310805/63342405-b2214880-c34b-11e9-95d4-1a45314963d4.png)

If you run that sampling on the whole mesh, which is kind of big, do the program actually finish, or does it crash at some point, like it does on my machine, because of the important (too important) number of resulting points ?

**Comment by maxGimeno** [comment]
Ok I got it. It is your input mesh that is not what you expect. There are 3600 isolated vertices, and a big hole in the roof ;) 
Here is the code I used earlier for my tests. You should use this to create your mesh, CGAL already provides ways to convert a soup into a surface_mesh : 
```cpp
#include <CGAL/Polygon_mesh_processing/distance.h>
#include <CGAL/Polygon_mesh_processing/orient_polygon_soup.h>
#include <CGAL/Polygon_mesh_processing/polygon_soup_to_polygon_mesh.h>


#include <fstream>
#include <armadillo>

int main(int argc, char**argv)
{

  if (argc != 3)
    return 1;
  //Conveniency typedefs;
  typedef CGAL::Exact_predicates_inexact_constructions_kernel Epick;
  typedef Epick::Point_3 Point_3;
  typedef CGAL::Surface_mesh<Point_3> Mesh;
  //Create a dummy mesh for the example

  Mesh m;

  auto mesh_vertices_file = "mesh_vertices.hdf5";
  auto mesh_faces_vi_file = "mesh_faces_vi.hdf5";

  arma::mat mesh_vertices;
  arma::imat mesh_faces_vi;

  mesh_vertices.load(mesh_vertices_file, arma::hdf5_binary_trans);
  mesh_faces_vi.load(mesh_faces_vi_file, arma::hdf5_binary_trans);

  assert(mesh_vertices.n_cols == 3);
  assert(mesh_faces_vi.n_cols == 3);

  Mesh cgal_surface_mesh;
  cgal_surface_mesh.reserve(mesh_vertices.n_rows, 3*mesh_faces_vi.n_rows, mesh_faces_vi.n_rows);

  std::vector<Point_3> pts;
  std::vector<std::vector<int> >faces;


  for (int i = 0; i < mesh_vertices.n_rows; i++) {
    pts.push_back(Point_3(mesh_vertices(i,0), mesh_vertices(i,1), mesh_vertices(i,2)));
  }

  for (int i = 0; i < mesh_faces_vi.n_rows; i++) {
    std::vector<int> face(3);
    face[0] = mesh_faces_vi(i,0);
    face[1] = mesh_faces_vi(i,1);
    face[2] = mesh_faces_vi(i,2);
    faces.push_back(face);
  }
  std::cout<<"soup filled"<<std::endl;
  CGAL::Polygon_mesh_processing::orient_polygon_soup(pts,faces);
  std::cout<<"soup oriented."<<std::endl;
  CGAL::Polygon_mesh_processing::polygon_soup_to_polygon_mesh(pts,faces,m);
  std::cout<<"mesh filled."<<std::endl;


  if (!m.is_valid()){
    std::cerr<<"mesh is invalid."<<std::endl;
    return 1;
  }
  std::cout << "Sampling triangle mesh..." << std::endl;

  std::vector<Point_3> sample_points;
  CGAL::Polygon_mesh_processing::sample_triangle_mesh(m, std::back_inserter(sample_points),  CGAL::parameters::use_grid_sampling(true).grid_spacing(2.5));

  std::cout << "Saving output..." << std::endl;

  std::ofstream out("pts.xyz");

  for (auto s : sample_points) {
    out << s[0] << " " << s[1] << " " << s[2] << std::endl;
  }

  out.close();

  return 0;
}
```

**Comment by mikeroberts3000** [comment]
Hi @maxGimeno, that is exciting news that you discovered what was causing this issue.

Can you clarify what you mean about isolated vertices? What is an isolated vertex? Is it a vertex that is not referenced by any face? Why don't I see the hole (caused by isolated vertices) in the Mayavi viewer or my own raycaster based on Embree?

Also, I tried very similar code to the code you posted and it triggered an assert when I tried to call   `CGAL::Polygon_mesh_processing::polygon_soup_to_polygon_mesh(...)`. The only difference is that your code uses `CGAL::Exact_predicates_inexact_constructions_kernel` and mine was using `CGAL::Simple_cartesian<double>`. Is there a reason why this difference would cause your code to work and mine to trigger an assert?

**Comment by maxGimeno** [comment]
An isolated vertex is a vertex that is not connected to anything. It generally indicates a problem in the connectivity, face sthat could not be added. 

I guess you don't visulaize the CGAL::Surface_mesh in the viewers you are  talking about. If you export your surface_mesh as an OFF file (with the << operator) and open it in a viewer that knows the OFF format, you will se the hole. The hole is not in the input, it is due to an error constructing the Surface_mesh from the input.
About the kernel choice, I don't get any error with `Simple_cartesian<double>`. 
Did you orient the soup before calling `polygon_soup_to_polygon_mesh()` ??

**Comment by mikeroberts3000** [comment]
There might be isolated vertices in the data I sent. But the viewer code I posted will only draw the non-isolated vertices.

You can test this yourself by keeping the vertices array fixed, and then changing the face array being visualized from mesh_faces_vi to mesh_faces_vi[0:10]. In other words, instructing Python to only draw the first 10 faces. In this case, nearly all the vertices have become isolated, because they are not referenced anywhere in the first 10 faces. So the viewer code I posted only shows non-isolated faces. Since the viewer code I posted doesn't show a hole on the roof, and only shows non-isolated vertices, I don't believe isolated vertices explain this issue.

**Comment by maxGimeno** [comment]
They don't. What I meant is that I tried your exact code, and exported the resulting CGAL::Surface_mesh. It had 3600+ isolated vertices and a hole in the roof.
Using the construction methods I posted, and exporting the resulting Surface_mesh, I get 380 or so isolated vertices, and no hole in the roof. What it shows is that in your code, the way you try to construct the Surface_mesh is wrong, and you get a corrupted mesh. It has nothing to do with the hdf5 files, it has to do with the internal CGAL data structure in the code. Using the code I gave, you should be able to get your points correctly, as it will sample a correct Surface_mesh. Currently, you are sampling an incorrect Surface_mesh with a hole in it, hence the hole in the point set.

To clarify it, the isolated vertices are not the probel, they only pointed me to the problem.

**Comment by mikeroberts3000** [comment]
Ah I understand 😄 Thank you for clarifying. I'll use the code you posted and report back ASAP. I'll also report the differences I find, if any, using `CGAL::Exact_predicates_inexact_constructions_kernel` and `CGAL::Simple_cartesian<double>`.

**Comment by mikeroberts3000** [comment]
Hi @maxGimeno, I tried your sample code. I got the following error when attempting to call `polygon_soup_to_polygon_mesh`.

```
CGAL error: precondition violation!
Expression : is_polygon_soup_a_polygon_mesh(polygons)
File       : /usr/local/include/CGAL/Polygon_mesh_processing/polygon_soup_to_polygon_mesh.h
Line       : 221
Explanation: Input soup needs to be a polygon mesh!
```

My exact code for constructing the relevant CGAL data structures is as follows.

```
typedef CGAL::Exact_predicates_inexact_constructions_kernel CGAL_K;
typedef CGAL::Surface_mesh<CGAL_K::Point_3>                 CGAL_Surface_mesh;

// ...

std::vector<CGAL_K::Point_3>            cgal_mesh_vertices;
std::vector< std::vector<std::size_t> > cgal_mesh_faces_vi;

for (int i = 0; i < mesh_vertices.n_rows; i++) {
    cgal_mesh_vertices.push_back(CGAL_K::Point_3(mesh_vertices(i,0), mesh_vertices(i,1), mesh_vertices(i,2)));
}

for (int i = 0; i < mesh_faces_vi.n_rows; i++) {
    cgal_mesh_faces_vi.push_back({static_cast<std::size_t>(mesh_faces_vi(i,0)), static_cast<std::size_t>(mesh_faces_vi(i,1)), static_cast<std::size_t>(mesh_faces_vi(i,2))});
}

CGAL::Polygon_mesh_processing::orient_polygon_soup(cgal_mesh_vertices, cgal_mesh_faces_vi);

CGAL_Surface_mesh cgal_surface_mesh;

// this call generates the error message above
CGAL::Polygon_mesh_processing::polygon_soup_to_polygon_mesh(cgal_mesh_vertices, cgal_mesh_faces_vi, cgal_surface_mesh);
```

**Comment by maxGimeno** [comment]
Ok, in Debug mode I also have it. It indicates that the input is not a 2-manifold. 
Here is a sample code to pre-process the soup and get it to pass the `is_polygon_soup_a_polygon_mesh` test:
```cpp
[...]
 if(!CGAL::Polygon_mesh_processing::is_polygon_soup_a_polygon_mesh(cgal_mesh_faces_vi)){
    std::cout<<"filtering soup..."<<std::endl;
    std::vector<std::vector<std::size_t> > valid_polygons;
    valid_polygons.reserve(faces.size());
    for(auto& polygon : cgal_mesh_faces_vi)
    {
      std::set<std::size_t> vids;
      bool to_remove=false;
      for(std::size_t id : polygon)
      {
        if (!vids.insert(id).second){
          to_remove=true;
          break;
        }
      }
      if (!to_remove) valid_polygons.push_back(polygon);
    }
    if (valid_polygons.size()!=cgal_mesh_faces_vi.size())
    {
      cgal_mesh_faces_vi.swap(valid_polygons);
      std::cout<<"soup filtered"<<std::endl;
    }
    else
      std::cout<<"No change."<<std::endl;
  }
  CGAL::Polygon_mesh_processing::orient_polygon_soup(cgal_mesh_vertices,cgal_mesh_faces_vi);
[...]
```
With that it should all be good !

**Comment by maxGimeno** [comment]
Or you can use 
```cpp
if(!CGAL::Polygon_mesh_processing::is_polygon_soup_a_polygon_mesh(cgal_mesh_faces_vi)){
  CGAL::Polygon_mesh_processing::repair_polygon_soup(cgal_mesh_vertices,cgal_mesh_faces_vi);
}
```
instead, it does more stuff but it should be more stable, for that very reason.

**Comment by mikeroberts3000** [comment]
That worked! Thank you so much for looking into this @maxGimeno 😄 To keep things simple, I just put the conditional call to `repair_polygon_soup(...)` in my code as you suggested and it worked perfectly.

I think this issue highlights three possible library improvements that could be considered in future. These points are debatable, but I'll mention them here anyway for posterity.

1. in my initial example, I called `Surface_mesh::is_valid(...)` to make sure that my mesh was well-formed before further processing. This call did not report any problems. In our discussion, you had mentioned that the way I constructed the Surface_mesh was incorrect, and the result was a corrupted mesh. Therefore, it would be helpful if there was some function, like `is_valid(check_for_corruption_extra_carefully=true)` or something, that I could call on a `Surface_mesh` to make sure that I constructed it correctly. Currently, `is_valid(...)` does not perform this check. As a result, the downstream surface sampling procedure failed silently because the input mesh was not well-formed.

2. The error message I got when calling `polygon_soup_to_polygon_mesh(...)` was confusing. The explanation in the error message is that the input polygon soup needs to be a polygon mesh. It was confusing to me that a function called `convert_X_to_Y` returns an error message that says, "the input needs to be a Y!" It would be helpful if there was a bit more detail and context in the error message, saying something like, "the input polygon soup needs to satisfy requirements A B and C before it can be converted to a polygon mesh, have you tried calling repair_polygon_soup?"

3. It is counterintuitive that grid sampling on a triangle mesh requires all of the additional structure imposed by the `Surface_mesh` class. If I am willing to deal with duplicate sample points along edges, it seems like grid sampling could process each polygon in a polygon soup independently. In my application, duplicate sample points are not a problem. Therefore, it would be helpful if CGAL provided a simple grid sampling tool for polygon soups, like the one that exists for meshes.

Anyyway, thank you again @maxGimeno for taking time to look at this issue closely and providing a fix 😄 You're a life saver!

**Comment by maxGimeno** [comment]
Thank you for your feedback !
 I'll work on something for your second and third points, but for the first one, the problem was not in the is_valid function. Let me explain further :

When you call `add_face()`, if the face is not valid the function will return `Surface_mesh::null_face()`, and not add anything. This is what you should have checked to detect the problem. Once out of the loop, you call `is_valid() ` and it returns `true`, as the bad faces were not added and resulting isolated vertices are not considered as invalid. You actually get a valid `Surface_mesh`, event though it does not match the structure contained in the input files. 

I'll make a PR to clarify the error message of `polygon_soup_to_polygon_mesh()` and try to provide a function for sampling a soup, and I'll ping you to get your opinion on it, if you don't mind.

**Comment by mikeroberts3000** [comment]
Ah that makes total sense. Yes please do 😄
