### ISSUE TITLE
Add Basic Viewers

### ISSUE THREAD

**Issue by jasmeet9323** [CGAL/cgal#4168]
### **Summary**

The goal of this project is to add basic viewers to several data structures of CGAL. The data structures for which Basic Viewers were created are - Voronoi Diagram, Periodic Triangulation 2, Nef Polyhedron and Arrangement 2.

### **Commit Log**

**Branch gsoc2019-add_basic_viewer-jasmeet**

63d1838b60 Merge remote-tracking branch 'cgal/master' into gsoc2019-add_basic_viewer-jasmeet
8250ae7ce0 Correct comment.
29209076b1 Offset Polygons only in the case of 2D data structures.
50bcc2c1c6 Fix the overlap of faces over edges. Edges visible in two-dimensional basic viewers now.
c94965a0e1 Minor fix in is_empty() method.
4eea525929 Merge remote-tracking branch 'jasmeet9323/cgal/gsoc2019-add_basic_viewer-jasmeet' into gsoc2019-add_basic_viewer-jasmeet
b188dabef4 Small Environment variable fix.
a943d8e479 Specialize draw() function for Nef_3 viewer
1565773fda Specialization of draw() function for P2T2, can be called together with another viewer now.
8c2f10fec6 Fix bug in is_empty() method which was making the viewer window crash.
899b6d9e09 Update draw() method call for Voronoi Diagram to be similar to other viewers.
596a186963 Update has_zero_*() methods to incorporate rays and lines.
a542fbdb45 Merge remote-tracking branch 'cgal/master' into gsoc2019-add_basic_viewer-jasmeet and resolve conflicts
2047eaa7db Add code of example to P2T2 documentation
09fcb98c65 Add the documentation header file draw_nef_3.h
35008aeeea Update draw_periodic_2_triangulation_2.h
ff2a498d9e Add documentation for Nef Polyhedron Viewer.
53bed9f541 Clean up draw_nef_3 example
e5986189a5 Correct vertex normals. Gourard Shading works.
79a86413ac Merge branch 'gsoc2019-add_basic_viewer-jasmeet' of https://github.com/jasmeet9323/cgal into gsoc2019-add_basic_viewer-jasmeet
ac5b76c0d1 Remove unused compute_vertex() method, display nef in one color
ae40ed9343 Update dependencies
16992e743e Add color to faces. Code cleanup
625ab7583d Count and tally the number of edges drawn for validation.
f9690fb852 Add face normal computation.
5b19e7d1a5 Add debug output. Classify newell_single_step_3 function using namespace CGAL to avoid ambiguity. Add example file to draw.
42c09f550d Add viewer for faces of Nef Polyhedron.
9995083b9e Add a visitor class to view the elements of Nef Polyhedron. Only vertices viewed for now.
6843c2ed69 Add viewer for Nef Polyhedra. Only points viewed for now.
d28a767b77 Merge branch 'gsoc2019-add_basic_viewer-jasmeet' of github.com:CGAL/cgal-public-dev into gsoc2019-add_basic_viewer-jasmeet
02254e998e Add dependency in Voronoi doc. Add draw_periodic_2_triangulation_2.h
628b24e57f Update headers, trying to deal with Travis CI errors.
720a0ad815 Merge branch 'gsoc2019-add_basic_viewer-jasmeet' of github.com:CGAL/cgal-public-dev into gsoc2019-add_basic_viewer-jasmeet
e661cfb261 Update documentation.
c412d3b0f7 Fix bugs in Voronoi Diagram Viewer. Format code. Fix bug in voronoi diagram documentation.
1401212d14 Remove old name doc file
1a3ba3d4e0 Change file name to match documentation
8096f38336 Add documentation for 2D Periodic Triangulation viewer.
f8bc47dbf6 Check visualization for Periodic Delaunay Triangulation as well. Change example to a delaunay triangulation.
a9eae8a297 Add Key description for Key D which displays the domain.
677cbc7c07 Add Periodic_2_triangulation_2 viewer. Add example - draw_periodic_2_triangulation_2.cpp.
e769c14b00 Change NULL to nullptr in buffer initialization.
e096af3133 Merge branch 'master' into gsoc2019-add_basic_viewer-jasmeet
58dec73f74 Update dependencies for Voronoi Diagram package: Add GraphicsView.
d1295ce338 Change order of constructor arguments so that existing derived classes from Basic_viewer which call this constructor set the arguments correctly.
1107041933 Remove header draw_voronoi from vd_2_point_location as a separate example is added. Change CMakLists.txt accordingly.
a48cb941ba Draw Dual Vertices in the voronoi diagram. Update doc image for drawing voronoi diagram.
ce1b306d00 Add m_buffer_for_mono_lines and m_buffer_for_colored_lines to view lines.
001fda493b Add documentation for voronoi diagram viewer.
43015b0059 Add special KeyPressEvent for rays. Format typedefs. Set cgal_test_suit = qEnvironmentVariableIsSet("CGAL_TEST_SUITE")
955a982a5f Add an example for Voronoi diagram basic viewer.
cd3cfc0bc5 Remove wireframe toggle button as it is unavailable in qOpenGLFunctions
ff5e9a3820 Add compute_face() functionality and get_second_point() to find intersection of ray with bounding box
2874ce940c Merge remote-tracking branch 'jasmeet9323/cgal/master' into gsoc2019-add_basic_viewer-jasmeet
4f9df720ea Toggle ray display with keypress R. Start adding face viewer
1cc0d12aa4 Revert formatting of the rest of Basic_viewer_qt.h file
1d4b6242f4 Show rays upto a bounding box
1a04afdae4 Experimenting with bounding box-ray intersection
1c852ed586 Add several points to display a ray.
abe9f2f7e4 Checking directions of rays.
a06f4f9aa2 Add method add_line(point, vector) in Basic_viewer_qt to view rays.
608ba3eee8 Start to implement infinite line in basic viewer.
d2eaef16d0 Add halfedges in viewer which are segments.
97d44ba776 Add viewer for Voronoi Diagram 2. Only points viewed for now.

**Branch gsoc2019-add_basic_viewer_arrangement-jasmeet**

009ef4955d Merge branch 'gsoc2019-add_basic_viewer_arrangement-jasmeet' of github.com:CGAL/cgal-public-dev into gsoc2019-add_basic_viewer_arrangement-jasmeet
4863d670a5 Add linear_traits_2 arrangement viewer. Cleanup typedefs.
2d80e5c0d9 Add linear_traits_2 arrangement viewer.
8d2889487e Add initial conic sections viewer.
b62159e4a2 Start implementing arrangement viewer for conic_arcs.
23775d8c6c Streamline typedef statements.
4b71d16b07 Change variable i->theta. Remove bug in angle calculation.
2366200ad2 Draw method for conic segments. Calclate start and end angles correctly.
f9b431ad2d Add a method to draw circular arcs in the basic viewer.
d81ff4a06e Only draw arcs that are linear in circular segment viewer. Viewer for circular arcs to be added.
545ab45d2d Add an alternate method to send points to the buffer before they are viewed. circular arc halfedges viewed as line segments for now.
52bdc24b24 Add viewer class for circle_segment_traits_2. Doesn't work right now.
68fc72576b Define Base and Derived classes to view different Arrangements(different GeomTraits_). Segment_2 arrangement viewer class added.
6ca9c528e2 Remove invalid typedef.
0917c6bc97 Add members geom_traits and top_traits to the viewer. Add some typedefs. Add keyPress event to toggle isolated vertices.
f451d23cae Merge branch 'gsoc2019-add_basic_viewer-jasmeet' into gsoc2019-add_basic_viewer_arrangement-jasmeet
8250ae7ce0 Correct comment.
29209076b1 Offset Polygons only in the case of 2D data structures.
0c2b9831e1 Add Arr_segment_2 viewer.

This commit log is recorded at Tue Aug 20 16:18:32 PDT 2019

**Comment by nimish-nsut** [comment]
I'm not able to build the program in bash and the mpfr package download is failing. how do I fix this?
![image](https://user-images.githubusercontent.com/58970986/71090286-adb94f00-21c8-11ea-8570-1123ddf07455.png)

**Comment by lrineau** [comment]
Eat a chocolate, and do it again.

**Comment by nimishdham** [comment]
> Eat a chocolate, and do it again.

didn't work.

**Comment by jasmeet9323** [comment]
See #5662. If nothing else, installing mpfr manually should work.

**Comment by lrineau** [comment]
The real issue is that mpfr.org is unreachable. And there is nothing vcpkg or CGAL can do about it.

**Comment by jasmeet9323** [comment]
> The real issue is that mpfr.org is unreachable. And there is nothing vcpkg or CGAL can do about it.

Oh yes, thanks. @nimishdham, nevermind my earlier comment.
