### ISSUE TITLE
Generalized Global Regularization

### ISSUE THREAD

**Issue by albicant** [CGAL/cgal#4170]
Gennadii Sytov's GSoC 2019 Submission

## Overview
This CGAL component implements the global regularization algorithm. The algorithm has been generalized so that it can be applied to various geometric primitives based on user-defined types of regularization and methods for querying neighbors.

[Link to the final report](https://docs.google.com/document/d/17Wvyb1ZiP8J-myLg9d0d7_X83xvxLeOOG13WVJyYwNM/edit?usp=sharing)

## Commit log
CGAL/cgal-public-dev@d6750f7d2c Changed the data file path in "test_216_segments.cpp"; Eddited the user manual.
CGAL/cgal-public-dev@a42eab27e8 Completed edits for the documentation.
CGAL/cgal-public-dev@66267bdea4 Work in progress: correcting the documentation.
CGAL/cgal-public-dev@1ee755c75f Added the documentation for the "Delaunay_neighbor_query_2", "Parallel_groups_2" and "Shape_regularization" classes.
CGAL/cgal-public-dev@5c42db7523 Documented and added preconditions to the angle and ordinate regularization classes.
CGAL/cgal-public-dev@c72c72b754 Angle & ordinate regularization 2 classes: made the "result" parameter in the "update" function a "const" type. Added documentation for concepts and referance manual page.
CGAL/cgal-public-dev@8c77c6ad86 Documentation: added the correct images
CGAL/cgal-public-dev@c0068ee49f Parallel_groups_2: Added the CGAL::abs() for the tolerance value; Work in progress: documentation
CGAL/cgal-public-dev@14507904b3 Work in progress: documentation
CGAL/cgal-public-dev@9a805515e6 Added the usage of CGAL::Timer to the examples; Cleaned up the code in tests and examples.
CGAL/cgal-public-dev@99c03f2873 Removed the "check_segments" function from the Angle_regularization_2 class; Work in progress: documentation
CGAL/cgal-public-dev@4fe026e9fe Work in progress: documentation
CGAL/cgal-public-dev@0491bc6573 Added an example with "real data"
CGAL/cgal-public-dev@cfaa50fc89 Cleaned up the code; Added some package description; Added concepts layout
CGAL/cgal-public-dev@17d1147fe9 Documentation: added examples to the "example.txt" file; Changed the outline for the user manual;
CGAL/cgal-public-dev@0a7c03a7a4 Added the examples for angle and ordinate regularization to the CMake file; Added the ability to provide the path for the folder to save .obj files
CGAL/cgal-public-dev@758a178704 Fixed a bug in the "Angle_regularization_2" class; Added the usage of "add_groups" for angle regularization to the "example_15_segments.cpp"
CGAL/cgal-public-dev@928bc124a2 Cleaned up the tests.
CGAL/cgal-public-dev@0b22564533 Added copyright comment to each .h file; Changed the example for 15 segments; Made an outline for the documentation.
CGAL/cgal-public-dev@16d69cb123 Refactored "test_ordinates_100_segments".
CGAL/cgal-public-dev@a71169c500 Added an example for 15 segments
CGAL/cgal-public-dev@4e4857ec3e Refactored the test for 216 segments; Added test for 100 segments ordinate regularization; Added the functionality to set tolerance in the "Parallel_groups_2" class; Removed the OSQP solver settings display; Changed max_bound in the "Angle_regularization_2" class to 90 degrees.
CGAL/cgal-public-dev@0cbcc3d2f5 Modified the bounds in the test_216_segments; Work in progress: test_ordiantes_150_random_segments.
CGAL/cgal-public-dev@6201a2e5a0 Refactored test_100_random_segments; Removed the "check_groups()" function from the angle_regularization class. Added the "example_100_random_segments" to the examples folder.
CGAL/cgal-public-dev@5bd5f13f7f Refactored test_3_segments; Added tests for 0, 1, and 2 segments.
CGAL/cgal-public-dev@05641fa490 Refactored the test for 4 segments.
CGAL/cgal-public-dev@e489441a6d Fixed all warnings; removed the "check_segments" function from the "Ordinate_regularization_2" class;  Removed generating a group of indices from the "Delaunay_neighbor_query_2" and added this functionality to the ".cpp" files.
CGAL/cgal-public-dev@4e2fb78a36 Added a test for 100 generated segments.
CGAL/cgal-public-dev@8517805563 Added a test for 4 segments; Fixed bugs : added the "check_segments" function to the "Angle_regularization_2" and "Ordinate_regularization_2" classes.
CGAL/cgal-public-dev@9789bf9bc0 Implemented a temporary saver class to save segments into "obj" files. Conditions classes: changed "m_eps" to "m_moe" and made it dependent on max_bound.
CGAL/cgal-public-dev@e571bf6cda Fixed bugs, fixed warnings, cleaned up the code.
CGAL/cgal-public-dev@d192238efc Work in progress: tests
CGAL/cgal-public-dev@d0248d53e2 Changed the CMakeLists.txt file in the examples folder; Changed "#include "osqp.h"" to "#include <osqp/osqp.h>" in the "OSQP_solver.h" file.; segment_regularization.cpp: was testing the saver-function for the ".obj" file format.
CGAL/cgal-public-dev@87685fceb7 Made all functions which were possible a "const" type; Moved the theta_max and d_max variables to the constructors; Refactored the "parallel_groups()" function in the "Angle_regularization_2" class to work with the "OutputIterator";  Removed the "add_groups_ function from the all classes; Refactored the "add_group()" function to be more generic;
CGAL/cgal-public-dev@011dbbb48d Made the "Conditions_angles_2" and "Conditions_ordinates_2" classes constant; Removed "auto" from function's parameters; Cleaned up empty spaces in the "Shape_regularization" class; Removed the "private"  section from the "Segment_data_2" structure.
CGAL/cgal-public-dev@c50ffd2974 Completed the implementation of the "Parallel_groups_2" class.
CGAL/cgal-public-dev@a887121955 Work in progress: the "Parallel_groups_2" class
CGAL/cgal-public-dev@ce0fb7ab77 Added the  functionality to work with groups to the "Angle_regularization_2" and "Ordinate_regularization_2" classes.
CGAL/cgal-public-dev@1eefe94520 Refactored the "Delaunay_neighbor_query_2" class.
CGAL/cgal-public-dev@cfb45e88d7 Cleaned up the "Segment_data_2" structure: got rid of m_angle; Added a "normalize" function to utils.h
CGAL/cgal-public-dev@33186326c4 Cleaned up the "Grouping_segments_2" class, created "Conditions_angles_2" and "Conditions_ordinates_2" classes. Created a "Parallel_groups" structure. Fixed a bug in the "Delaunay_neighbour_query_2" class.
CGAL/cgal-public-dev@bdd35bf5d3 Cleaned up the code in the "Angle_regularization_2" and "Ordinate_regularization_2" classes.
CGAL/cgal-public-dev@29e5701007 Cleaned up the code in the "Grouping_segments_2", "Angles_regularization_2", "Ordinate_regularization_2", "Shape_regularization_2" classes.
CGAL/cgal-public-dev@54733ece6a Cleaned up the "Grouping_segments_2" class; Deleted the "Grouping_segments_ordinates_2" class.
CGAL/cgal-public-dev@1a8a01c73c Merged the 2 grouping classes.
CGAL/cgal-public-dev@4f5772ff7b Made the 2 grouping class as similar as possible.
CGAL/cgal-public-dev@82db2e2032 Cleaned up the code; Work in progress: refactoring of the Grouping class.
CGAL/cgal-public-dev@9e52867b74 Cleaned up the code
CGAL/cgal-public-dev@5e2eb9003d Fixed bugs in the "Ordinate_regularization_2" and "Grouping_segments_ordinates_2" classes.
CGAL/cgal-public-dev@3e631051fe Work in progress: Ordinate_regularization_2 : translate_collinear_segments
CGAL/cgal-public-dev@89ca77805c Finished the implementation of the "Grouping_segments_ordinates_2" class.
CGAL/cgal-public-dev@5e56ed0296 Work in progress (2): Grouping_segments_ordinates_2
CGAL/cgal-public-dev@fb6871fd9a Work in progress: grouping_segments_ordinates_2
CGAL/cgal-public-dev@71ba87ab5a Changes the "Delaunay_neighbor_query_2" class to work with the map of angles; Cleaned up the code.
CGAL/cgal-public-dev@de777e47f1 Completed working on building new orientations for ordinates.
CGAL/cgal-public-dev@8a951a49dc Work in progress: Ordinate_regularization; added the "transform_coordinates" function to the utils.h
CGAL/cgal-public-dev@ec9252425b Changed the "Delaunay_neighbor_query_2" class to work with ordinates; Changed the "get_bound" function to "bounds".  Added the "get_parallel_groups" function to the "Angle_regularization_2" class.
CGAL/cgal-public-dev@2ced0dd5a9 Renamed the "Rotated_segments_regularization" class to "Angle_regularization"; added a "get_bound()" function to the "Angle_regularization" class; deleted the "Tree" class.
CGAL/cgal-public-dev@cf0ce1c098 Fixed a bug; Cleaned up the code.
CGAL/cgal-public-dev@550322576f Added the "apply_new_orientations" functionality to the "Rotated_segments_regularization_2" class; Removed the usage of the "Tree" class from the algorithm.
CGAL/cgal-public-dev@9e281668b5 Finished the implementation of the "Grouping_segments_2" class.
CGAL/cgal-public-dev@568808fe88 Work in progress: refactoring the Tree class (Added the Grouping_segments_2 class)
CGAL/cgal-public-dev@bbed443dc3 Cleaned up the code a little bit.
CGAL/cgal-public-dev@5f5a727405 Finished refactoring the "OSQP_solver" class.
CGAL/cgal-public-dev@21d9d791e7 Currently still in the process of refactoring the "OSQP_solver" class; Known problem: the "solve()" function in the class crashes with the example of 216 segments.
CGAL/cgal-public-dev@5d4de0d95a Added a "build_OSQP_solver_data" function to the "Shape_regularization" class.
CGAL/cgal-public-dev@15057881e1 Cleaned up the code; changed loops in the "Delaunay_neighbor_query_2", "Shape_regularization" and "Rotated_segments_regularization_2: classes; removed the "get_t_ijs_map" and "get_r_ijs_map" functions from the "Rotated_segments_regularization_2" class; changed the std::vector m_t_ijs to an std::map.
CGAL/cgal-public-dev@adaea17275 Cleaned code; Added the usage of the "Segment_data_2" structure to the "Rotated_segments_regularization_2" class.
CGAL/cgal-public-dev@04e5b17149 Optimized the "operator()" function of the "Delaunay_neighbour_query_2" class.
CGAL/cgal-public-dev@a15b75f854 Did some code refactoring.
CGAL/cgal-public-dev@c5fa58295d Moved the "compute_direction" and "compute_orientation" functions to utils.h; Added the implementation of the "Segment_data_2" structure
CGAL/cgal-public-dev@5459417bcc Added the usage of property maps in the "Delaunay_neighbor_query_2" class; Moved the function for computing the middle point to utils.h; Changed "int" to "size_t" where it was appropriate.
CGAL/cgal-public-dev@e3987ae4ca Renamed Dense_QP_solver into OSQP_solver; Created an "internal" folder and "internal" namespace and moved the appropriate files into the folder.  Created a frame for the "Segment_data_2" structure.
CGAL/cgal-public-dev@8c6bf73039 cleaned some code
CGAL/cgal-public-dev@e499ddeba8 Finished implementing the QP solver.
CGAL/cgal-public-dev@61ae3ad552 QP_solver: work in progress (2)
CGAL/cgal-public-dev@62259b1d63 qp_solver: work in progress
CGAL/cgal-public-dev@8fe8e254d0 Implemented the "set_orientation" function for the "Tree" class.
CGAL/cgal-public-dev@22eb33f98a Implemented the Tree class except a "set_orientation" function.
CGAL/cgal-public-dev@e9008f7822 Added maps to t_ijs and r_ijs to the Rotated_segments_regularization_2 class; Cleaned the code by adding compute_direction() and compute_orientation() functions to the Rotated_segments_regularization_2 class.
CGAL/cgal-public-dev@b8926cf23d Added an implementation for the Shape_regularization class.
CGAL/cgal-public-dev@337fa015cf Added implementation for the operator() function in the Delaunay_neighbor_query_2 class; Created a dummy for the solve function in the Dense_QP_solver class.
CGAL/cgal-public-dev@ba37a73728 Completed the target_value() function implementation for the Rotated_segments_regularization_2 class
CGAL/cgal-public-dev@10678930fb Work in progress: Neighbor_query and Regularization_type
CGAL/cgal-public-dev@c64a83cf46 Fixed bugs
CGAL/cgal-public-dev@462bdbd8ce Made some changes so that the code would compile.
CGAL/cgal-public-dev@557c55902d Fixed formating
CGAL/cgal-public-dev@ca634c8c1b Corrected cmake list for examples
CGAL/cgal-public-dev@33885d8fd2 Created the package frame
CGAL/cgal-public-dev@a01e11242c Test commit. Just checking that everything is working.

**Comment by mushanf** [comment]
Hello, the quadratic program in CGAL shape regularization (3m+n constraints), and in the reference paper (2m+2n constraints） seem to be different.  Besides, what is the yk represents in the code program? 
![image](https://user-images.githubusercontent.com/89303384/180107309-c84061f3-e8a0-4171-9998-965d8edc75a5.png)

**Comment by soesau** [comment]
Hi, in the documentation of the [Shape Regularization package](https://doc.cgal.org/latest/Shape_regularization/index.html#QP_Regularization_Framework) it says that our implementation uses 2(n+m) constraints as the referenced paper. Can you point me to where it is written (3m+n constraints)?

The contribution of the y<sub>k</sub> term is the regularization of spatially close, almost collinear/coplanar or orthogonal elements.

**Comment by mushanf** [comment]
Thank you for your reply. The number of constraints (e) is listed in the function _set_qp_data()_  and _set_constraint_bounds_ in QP_regularization.h, which are in the screenshots below.
Is yk term equal to |θij−xi+xj| in value (infer from linear term q)? Then why does the bound of the first 2e constraints multiply 2*lambda (val_neg and val_pos)? It seems yk term is related to 2*lambda* |θij−xi+xj|. And the bound of the last e constraints are between neg_inf and pos_inf, can it be deleted?
![image](https://user-images.githubusercontent.com/89303384/180340062-3afbae12-97a7-4db6-b866-0f7d2966a5ce.png)
![image](https://user-images.githubusercontent.com/89303384/180340001-123632ab-b864-4b06-915a-b26bac56d208.png)
