### ISSUE TITLE
Obj file simplification process error

### ISSUE THREAD

**Issue by simonasdmd** [CGAL/cgal#4183]
_Please use the following template to help us solving your issue._

## Issue Details

I simplified the obj file according to the documentation. However, an abnormality was found in the process. I hope to be corrected.
The obj file has been successfully read. But there was a problem during the simplification process. Causes the program to be interrupted.

## Source Code

[main.txt](https://github.com/CGAL/cgal/files/3537277/main.txt)

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):win32
* Compiler: vs2017
* Release or debug mode: release
* Specific flags used (if any):
* CGAL version: 4.13.1
* Boost version: 1.70
* Other libraries versions if used (Eigen, TBB, etc.):

testdata: 
[test_obj.zip](https://github.com/CGAL/cgal/files/3537280/test_obj.zip)

I hope to be corrected. I thank you from the heart.

**Comment by afabri** [comment]
Hello, I loaded the mesh into the Polyhedron demo.  It is not really a 2-manifold as there are geometric edges with more than two incident patches.  The mesh simplification algorithm then simplifies individual patches that  is there is no guarantee that a shared geometric (and hence duplicated) edge gets the same treatment in the different patches. 
Note also that when you have objects with sharp features you probably should mark them as non-collapsible.

**Comment by simonasdmd** [comment]
How should I fix this problem? Is there a problem with my code?
Can you help me with the correction?

**Comment by afabri** [comment]
As your mesh is not a two-manifold, but several two-manifolds that share geometric edges, the CGAL mesh simplification algorithm is not powerful enough for what you want to achieve.

**Comment by simonasdmd** [comment]
Will this be supported later?

**Comment by sloriot** [comment]
Actually it should be working. In your code you should have:

```
namespace PMP = CGAL::Polygon_mesh_processing;		
if (!PMP::is_polygon_soup_a_polygon_mesh(faces))
  PMP::orient_polygon_soup(points, faces);
```

then calling simplify should work without pb, except that non-manifold edges are duplicated and might be collapsed independently.

I try running it on my computer and I could simplify it.

Note that the changes in https://github.com/CGAL/cgal/pull/4069 were needed (now integrated in master) to read the file.

**Comment by simonasdmd** [comment]
thanks~
