### ISSUE TITLE
Does Straight_skeleton_2 support Exact_predicates_exact_constructions_kernel?

### ISSUE THREAD

**Issue by drewish** [CGAL/cgal#42]
At the bottom of http://doc.cgal.org/latest/Straight_skeleton_2/index.html#title12 in the Advanced section it reads:
> Notice how some of the examples above use Exact_predicates_exact_constructions_kernel. In all cases, the straight skeleton is constructed using Exact_predicates_inexact_constructions_kernel.

But in fact none of the examples use exact constructions. 

Looking into the test cases I found https://github.com/CGAL/cgal/blob/master/Straight_skeleton_2/test/Straight_skeleton_2/include/CGAL/test_sls_types.h#L25-L46 which seems like someone tested it at one point... but it doesn't seem to work any more.

Here's my test case:
```c++
#include <iostream>
#include <CGAL/Exact_predicates_exact_constructions_kernel.h>
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/create_straight_skeleton_2.h>
#include <CGAL/Polygon_2.h>

typedef CGAL::Exact_predicates_exact_constructions_kernel K;
// typedef CGAL::Exact_predicates_inexact_constructions_kernel K;
typedef K::Point_2 Point ;
typedef CGAL::Straight_skeleton_2<K> Ss;
typedef boost::shared_ptr<Ss> SsPtr;

int main( int argc, const char* argv[] )
{
  CGAL::Polygon_2<K> poly;
  poly.push_back( Point( -1, -1 ) );
  poly.push_back( Point( 0, -12 ) );
  poly.push_back( Point( 1, -1 ) );
  poly.push_back( Point( 12, 0 ) );
  poly.push_back( Point( 1, 1 ) );
  poly.push_back( Point( 0, 12 ) );
  poly.push_back( Point( -1, 1 ) );
  poly.push_back( Point( -12, 0 ) );

  SsPtr ss = CGAL::create_interior_straight_skeleton_2(poly);
  
  std::cout << "Straight skeleton with " << ss->size_of_vertices()
            << " vertices, " << ss->size_of_halfedges()
            << " halfedges and " << ss->size_of_faces()
            << " faces" << std::endl ;
}
```

**Comment by lrineau** [comment]
Hi. I see that you bug has been unanswered for one month. That is a shame for CGAL. I will try to find someone to answer you in the CGAL developers. Sorry for that.

**Comment by drewish** [comment]
Thanks, it would be great if there's someone more familiar with it who could just tell me if it should work and I'm doing it wrong or if I shouldn't bother trying ;)

**Comment by drewish** [comment]
The compilation error I'm currently getting looks like:
```
/Users/amorton/projects/cgal/my_tests/skel/skel.cpp:25:9: error: no viable conversion from 'shared_ptr<Straight_skeleton_2<Exact_predicates_inexact_constructions_kernel>>' to
      'shared_ptr<Straight_skeleton_2<K>>'
  SsPtr ss = CGAL::create_interior_straight_skeleton_2(poly);
        ^    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/boost/smart_ptr/shared_ptr.hpp:323:25: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from
      'boost::shared_ptr<Straight_skeleton_2<Exact_predicates_inexact_constructions_kernel> >' to 'const boost::shared_ptr<CGAL::Straight_skeleton_2<CGAL::Epeck,
      CGAL::Straight_skeleton_items_2, std::__1::allocator<int> > > &' for 1st argument
template<class T> class shared_ptr
                        ^
/usr/local/include/boost/smart_ptr/shared_ptr.hpp:420:5: note: candidate template ignored: substitution failure [with Y = CGAL::Straight_skeleton_2<CGAL::Epick,
      CGAL::Straight_skeleton_items_2, std::__1::allocator<int> >]: no type named 'type' in 'boost::detail::sp_enable_if_convertible<CGAL::Straight_skeleton_2<CGAL::Epick,
      CGAL::Straight_skeleton_items_2, std::__1::allocator<int> >, CGAL::Straight_skeleton_2<CGAL::Epeck, CGAL::Straight_skeleton_items_2, std::__1::allocator<int> > >'
    shared_ptr( shared_ptr<Y> const & r, typename boost::detail::sp_enable_if_convertible<Y,T>::type = boost::detail::sp_empty() )
    ^                                                                                           ~~~~
/usr/local/include/boost/smart_ptr/detail/operator_bool.hpp:52:5: note: candidate function
    operator unspecified_bool_type() const BOOST_NOEXCEPT
    ^
In file included from /Users/amorton/projects/cgal/my_tests/skel/skel.cpp:4:
In file included from /Users/amorton/projects/cgal/Straight_skeleton_2/include/CGAL/create_straight_skeleton_2.h:23:
/Users/amorton/projects/cgal/Straight_skeleton_2/include/CGAL/Straight_skeleton_builder_2.h:793:91: error: no matching function for call to object of type 'const
      CGAL::Cartesian_converter<CGAL::Epeck, CGAL::Epick, CGAL::NT_converter<CGAL::Lazy_exact_nt<CGAL::Gmpq>, double> >'
      Vertex_handle lVertex = mSSkel->SSkel::Base::vertices_push_back( Vertex(mVertexID++,cvt(*lCurr)) ) ;
                                                                                          ^~~
/Users/amorton/projects/cgal/Straight_skeleton_2/include/CGAL/Straight_skeleton_builder_2.h:902:9: note: in instantiation of function template specialization
      'CGAL::Straight_skeleton_builder_2<CGAL::Straight_skeleton_builder_traits_2<CGAL::Epick>, CGAL::Straight_skeleton_2<CGAL::Epick, CGAL::Straight_skeleton_items_2,
      std::__1::allocator<int> >, CGAL::Dummy_straight_skeleton_builder_2_visitor<CGAL::Straight_skeleton_2<CGAL::Epick, CGAL::Straight_skeleton_items_2, std::__1::allocator<int>
      > > >::enter_valid_contour<std::__1::__wrap_iter<CGAL::Point_2<CGAL::Epick> *>, CGAL::Cartesian_converter<CGAL::Epeck, CGAL::Epick,
      CGAL::NT_converter<CGAL::Lazy_exact_nt<CGAL::Gmpq>, double> > >' requested here
        enter_valid_contour(lList.begin(),lList.end(),cvt);
        ^
/Users/amorton/projects/cgal/Straight_skeleton_2/include/CGAL/create_straight_skeleton_2.h:80:9: note: in instantiation of function template specialization
      'CGAL::Straight_skeleton_builder_2<CGAL::Straight_skeleton_builder_traits_2<CGAL::Epick>, CGAL::Straight_skeleton_2<CGAL::Epick, CGAL::Straight_skeleton_items_2,
      std::__1::allocator<int> >, CGAL::Dummy_straight_skeleton_builder_2_visitor<CGAL::Straight_skeleton_2<CGAL::Epick, CGAL::Straight_skeleton_items_2, std::__1::allocator<int>
      > > >::enter_contour<std::__1::__wrap_iter<CGAL::Point_2<CGAL::Epick> *>, CGAL::Cartesian_converter<CGAL::Epeck, CGAL::Epick,
      CGAL::NT_converter<CGAL::Lazy_exact_nt<CGAL::Gmpq>, double> > >' requested here
    ssb.enter_contour( CGAL_SS_i::vertices_begin(*hi), CGAL_SS_i::vertices_end(*hi), Point_converter ) ;
        ^
/Users/amorton/projects/cgal/Straight_skeleton_2/include/CGAL/create_straight_skeleton_2.h:111:10: note: in instantiation of function template specialization
      'CGAL::create_interior_straight_skeleton_2<std::__1::__wrap_iter<CGAL::Point_2<CGAL::Epeck> *>, std::__1::__wrap_iter<CGAL::Polygon_2<CGAL::Epick,
      std::__1::vector<CGAL::Point_2<CGAL::Epick>, std::__1::allocator<CGAL::Point_2<CGAL::Epick> > > > *>, CGAL::Epick>' requested here
  return create_interior_straight_skeleton_2(aOuterContour_VerticesBegin
         ^
/Users/amorton/projects/cgal/Straight_skeleton_2/include/CGAL/create_straight_skeleton_2.h:138:10: note: in instantiation of function template specialization
      'CGAL::create_interior_straight_skeleton_2<std::__1::__wrap_iter<CGAL::Point_2<CGAL::Epeck> *>, CGAL::Epick>' requested here
  return create_interior_straight_skeleton_2(CGAL_SS_i::vertices_begin(aOutContour)
         ^
/Users/amorton/projects/cgal/Straight_skeleton_2/include/CGAL/create_straight_skeleton_2.h:149:10: note: in instantiation of function template specialization
      'CGAL::create_interior_straight_skeleton_2<CGAL::Polygon_2<CGAL::Epeck, std::__1::vector<CGAL::Point_2<CGAL::Epeck>, std::__1::allocator<CGAL::Point_2<CGAL::Epeck> > > >,
      CGAL::Epick>' requested here
  return create_interior_straight_skeleton_2(aOutContour, Exact_predicates_inexact_constructions_kernel() );
         ^
/Users/amorton/projects/cgal/my_tests/skel/skel.cpp:25:20: note: in instantiation of function template specialization
      'CGAL::create_interior_straight_skeleton_2<CGAL::Polygon_2<CGAL::Epeck, std::__1::vector<CGAL::Point_2<CGAL::Epeck>, std::__1::allocator<CGAL::Point_2<CGAL::Epeck> > > > >'
      requested here
  SsPtr ss = CGAL::create_interior_straight_skeleton_2(poly);
                   ^
/Users/amorton/projects/cgal/Kernel_23/include/CGAL/Enum_converter.h:35:21: note: candidate function not viable: no known conversion from 'CGAL::Point_2<CGAL::Epick>' to 'bool'
      for 1st argument
  bool              operator()(bool b) const { return b; }
                    ^
```
It goes on to list all the other candidate functions.

**Comment by fcacciola** [comment]
Hello. I'm working on it. This used to work in the past but now it doesn't anymore, and I don't know why yet. FWIW I see the same error, so I should be able to fix it,

**Comment by fcacciola** [comment]
In the meantime, I've tested the "low-level construction", which is illustrated in the example file "Low_level.API", and it worked with exact constructions (*)

(*) In that example, I have to add:

typedef K::FT FT ;

then replace the ocurrences of 'double' by 'FT' so the change of kernel worked.

I'll keep looking for the problem in the simpler example.

**Comment by fcacciola** [comment]
Getting better.

This code is supposedly designed so you can input points on a "fast kernel", such as Simple_cartesian<double> and yet it constructs (and represents) the skeleton in a different kernel, such as Exact_predicates_exact_constructions.

Some of that mechanism is not working (and I'm looking into it), but in the meantime, for your example code, it suffices to simply add an instance of the kernel to the call to create_interior_straight_skeleton_2. That is:

  SsPtr ss = CGAL::create_interior_straight_skeleton_2(poly, K());

**Comment by drewish** [comment]
That definitely got me compiling and able to use Polygon_set_2 (which requires exact constructions) along with Straight_skeleton_2. I'm definitely noticing the difference in performance so I'll have to figure out the best way to structure my code to use the appropriate kernel for each and convert between them.

**Comment by strk** [comment]
We just switched to inexact kernel straight skeleton computation specifically for the performance issue, but then we hit robustness problems there: https://github.com/Oslandia/SFCGAL/issues/89 -- Is that expected @fcacciola or worth a ticket on this side ?

**Comment by lrineau** [comment]
@fcacciola Please also see the issue #123.

**Comment by fcacciola** [comment]
Hello. Please see my follow up on #123

**Comment by sgiraudot** [comment]
If I understand correctly, this issue can be closed. Please let me know if it's still a valid issue and should be opened again.

**Comment by alecjacobson** [comment]
I'm confused about whether the straight skeleton or polygon offsets can be computed using `CGAL::Exact_predicates_exact_constructions_kernel` (regardless of whether it's slow or currently working to switch the kernel).

First, am I correct that `CGAL::Exact_predicates_exact_constructions_kernel::FT` can represent rational numbers, but cannot represent irrational numbers like `sqrt(2)`?

If so, then the polygon offset of a rational polygon might not have rational vertices. Consider the one unit offset of the square with vertices (1,0), (0,1), (-1,0), (0,-1). This will have corners at (1+sqrt(2),0), ...

Seems at least `CGAL::Exact_predicates_exact_constructions_kernel_with_sqrt` would be needed.

> _BTW: the comment about the documentation in the original post is still true: "Notice how some of the examples above use...", but none of them do.

**Comment by fcacciola** [comment]
(sorry but since the issue was first closed I didn't noticed there was an additional question until now)

You are indeed correct and the computations use a sqrt(), so effectively, you need CGAL::Exact_predicates_exact_constructions_kernel_with_sqrt

What the current code does is use an extended precision SQRT approximation from the CORE package, if that is used by CGAL,  regardless of the type of predicates or constructions selected.
