### ISSUE TITLE
Potential bug for add_vertex or add_face in CGAL::Surface_mesh

### ISSUE THREAD

**Issue by jasjuang** [CGAL/cgal#4200]
## Issue Details

What happened was I have a particular obj file [test.zip](https://github.com/CGAL/cgal/files/3557895/test.zip), when I load it in with tinyobjloader into vertices and triangle indices, and then convert it into `CGAL::Surface_mesh` using `add_vertex` and `add_face`, and when I save it out as a `.off` file, the mesh actually changes. I think it's related to CGAL because if I write out the vertices and triangle indices directly into an obj file, the mesh does not change. Please see below minimal code to reproduce the problem. Note that the `tiny_obj_loader.h` can be directly copied from [here](https://github.com/syoyo/tinyobjloader/blob/master/tiny_obj_loader.h), it's a header only library. 

## Source Code

```
#include <tiny_obj_loader.h>

void ReadOBJ(const std::string &obj_file,
             std::vector<double> &vert_pos,
             std::vector<int> &tri_ind){
  tinyobj::attrib_t attrib;
  std::vector<tinyobj::shape_t> shapes;
  std::vector<tinyobj::material_t> materials;
  std::string warn;
  std::string err;

  tinyobj::LoadObj(&attrib, &shapes, &materials, &warn, &err, obj_file.c_str());

  for (float vertice : attrib.vertices){
    vert_pos.emplace_back(vertice);
  }

  for (auto &shape : shapes){
    for (auto &indice : shape.mesh.indices){
      tri_ind.emplace_back(indice.vertex_index);
    }
  }
}

void WriteOBJ(const std::vector<double> &vert_pos,
                      const std::vector<int> &tri_ind,
                      const std::string &obj_file){
   std::ofstream ostr_obj(obj_file);

  ostr_obj << std::fixed << std::setprecision(10);

  for (int i = 0; i < vert_pos.size(); i += 3){
    ostr_obj << "v " << vert_pos[i + 0] << " " << vert_pos[i + 1] << " "
             << vert_pos[i + 2] << std::endl;
  }

  // +1 because obj index starts with 1
  for (int i = 0; i < tri_ind.size(); i += 3){
    ostr_obj << "f " << tri_ind[i + 0] + 1 << " " << tri_ind[i + 1] + 1 << " "
             << tri_ind[i + 2] + 1 << std::endl;
  }
}

void STLtoCGAL(
    const std::vector<double> &vert_pos,
    const std::vector<int> &tri_ind,
    CGAL::Surface_mesh<CGAL::Simple_cartesian<double>::Point_3> &mesh_cgal){

  using Pt_3     = CGAL::Simple_cartesian<double>::Point_3;
  using Mesh   = CGAL::Surface_mesh<Pt_3>;

  std::vector<Mesh::Vertex_index> ind;

  const int num_vert = vert_pos.size() / 3;

  for (int i = 0; i < num_vert; i++){
    ind.emplace_back(mesh_cgal.add_vertex(
        Pt_3(vert_pos[i * 3 + 0], vert_pos[i * 3 + 1], vert_pos[i * 3 + 2])));
  }

  const int num_tri = tri_ind.size() / 3;

  for (int i = 0; i < num_tri; i++){
    mesh_cgal.add_face(ind[tri_ind[i * 3 + 0]],
                       ind[tri_ind[i * 3 + 1]],
                       ind[tri_ind[i * 3 + 2]]);
  }
}

int main(){
  std::vector<double> vert_pos;
  std::vector<int> tri_ind; 

  ReadOBJ("test.obj", vert_pos, tri_ind);
  
  using K    = CGAL::Simple_cartesian<double>;
  using Mesh = CGAL::Surface_mesh<K::Point_3>;

  Mesh m;

  STLtoCGAL(vert_pos, tri_ind, m);

  std::ofstream output("out_cgal.off"); // this is different than test.obj
  output << m;
  output.close();

  WriteOBJ(vert_pos, tri_ind, "out.obj") // this is normal
}
```

The STLtoCGAL is pretty straight forward and it has been working for the other meshes except for this one. My suspicion is there is bug somewhere in `add_vertex` and `add_face`. Here are the screenshots in meshlab showing the problem. 

This is the input test.obj
![test](https://user-images.githubusercontent.com/11759200/63987790-4dbe6180-ca8e-11e9-8231-df842c8c5b31.png)

This is the result of the problematic out_cgal.off
![out_cgal](https://user-images.githubusercontent.com/11759200/63987823-6595e580-ca8e-11e9-8045-1d34819d300f.png)

This is the result of out.obj
![out](https://user-images.githubusercontent.com/11759200/63987812-5a42ba00-ca8e-11e9-9f8b-3ad48944942e.png)

Please let me know if you can reproduce the problem.

## Environment

* Operating system: Ubuntu 18.04
* Compiler: GCC 7
* Release or debug mode: Release 
* CGAL version: Latest
* Boost version: 1.68

**Comment by maxGimeno** [comment]
It is not a problem in add_face but a problem in the way you are using it. You should always check for the result of add_face() as it will not always accept your input. If there is a manifoldness issue caused by the face you are trying to add, for example, it will not be added and null_face will be return instead. 
The right way to create a surface_mesh is to fill a polygon soup, and then orient it. See [this example](https://doc.cgal.org/latest/Polygon_mesh_processing/Polygon_mesh_processing_2repair_polygon_soup_example_8cpp-example.html#a3)

**Comment by jasjuang** [comment]
@maxGimeno thanks for the pointer, I can confirm that if I use polygon soup instead of `add_face` the problem is solved.
