### ISSUE TITLE
Compiler detection fails for MSVC version > 14.0

### ISSUE THREAD

**Issue by Teimpz** [CGAL/cgal#4206]
## Issue Details

When building using the included CMAKE scripts, the resulting library filenames contain an incorrect vc version number. 
f.e. CGAL_[Core|ImageIO]-**vc140**-[mt]-[gd]-1.14.dll where vc142 would be expected.

## Environment

* Operating system: Windows:
* Compiler: MSVC 14.1, MSVC 14.2
* Release or debug mode:
* Specific flags used (if any):
* CGAL version:
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by Teimpz** [comment]
Issue appears to be in cmake/modules/CGAL_GeneratorSpecificSettings.cmake. The if/else chain setting the CGAL_TOOLSET does not handle the newest MSVC compilers properly.

**Comment by lrineau** [comment]
You are right. Anyway, it should not be the job of CGAL CMake scripts to deal with that. Since CMake version 3.12, there is [`MSVC_TOOLSET_VERSION`][1] that can be used instead.

[1]: https://cmake.org/cmake/help/v3.12/variable/MSVC_TOOLSET_VERSION.html

**Comment by lrineau** [comment]
In the same file `cmake/modules/CGAL_GeneratorSpecificSettings.cmake`, our usage of `MSVC15` is wrong.

**Comment by Teimpz** [comment]
> You are right. Anyway, it should not be the job of CGAL CMake scripts to deal with that. Since CMake version 3.12, there is [`MSVC_TOOLSET_VERSION`](https://cmake.org/cmake/help/v3.12/variable/MSVC_TOOLSET_VERSION.html) that can be used instead.

Note that, according to https://cmake.org/cmake/help/latest/variable/MSVC_TOOLSET_VERSION.html, msvc 14.2 does not appear supported yet. Still would be an improvement though.

**Comment by lrineau** [comment]
[**@Teimpz**](https://github.com/Teimpz) commented on [Sep 2, 2019, 3:10 PM GMT+2](https://github.com/CGAL/cgal/issues/4206#issuecomment-527142892 "2019-09-02T13:10:14Z - Replied by Github Reply Comments"):
> > You are right. Anyway, it should not be the job of CGAL CMake scripts to deal with that. Since CMake version 3.12, there is [`MSVC_TOOLSET_VERSION`](https://cmake.org/cmake/help/v3.12/variable/MSVC_TOOLSET_VERSION.html) that can be used instead.
> 
> Note that, according to https://cmake.org/cmake/help/latest/variable/MSVC_TOOLSET_VERSION.html, msvc 14.2 does not appear supported yet. Still would be an improvement though.

The documentation is wrong. It has been added in CMake 3.14.2: https://gitlab.kitware.com/cmake/cmake/merge_requests/3186

**Comment by lrineau** [comment]
Will be fixed by https://github.com/CGAL/cgal/pull/4256.
