### ISSUE TITLE
Assertion error when rendering a simple custom polyhedron

### ISSUE THREAD

**Issue by mic-e** [CGAL/cgal#4210]
## Issue Details

I defined a custom polyhedron in OpenSCAD (a simple cube of size 1).
When rendering just the cube, it works fine.
But as soon as I add any other object, CGAL reports an assertion error.

CGAL error message:

```
Parsing design (AST generation)...
Compiling design (CSG Tree generation)...
Rendering Polygon Mesh using CGAL...
ERROR: CGAL error in CGAL_Nef_polyhedron3(): CGAL ERROR: assertion violation! Expr: e->incident_sface() != SFace_const_handle() File: /usr/include/CGAL/Nef_S2/SM_const_decorator.h Line: 330
```

## Source Code

Minimal example in OpenSCAD:

```
points = [
    [0, 0, 0], //  0
    [0, 0, 1], //  1
    [1, 0, 0], //  2
    [1, 0, 1], //  3
    [0, 1, 0], //  4
    [0, 1, 1], //  5
    [1, 1, 0], //  6
    [1, 1, 1], //  7
];

faces = [
    [0, 2, 3, 1],
    [6, 7, 5, 4],
    [0, 1, 5, 4],
    [2, 3, 7, 6],
    [0, 2, 6, 4],
    [1, 3, 7, 5],
];

union() {
    // if this cube is disabled, everything renders just fine.
    // it doesn't matter where I place the cube.
    translate([0, -1, 0]) cube([1, 1, 1]);
    polyhedron(points=points, faces=faces, convexity=10);
}
```

I assume that I defined one of the faces in the wrong point order and this is why it fails, but this should not cause the observed behavior (rendering fine if rendered alone, assertion if rendered together with an other shape).

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Linux mic 5.1.14-arch1-1-ARCH #1 SMP PREEMPT Sat Jun 22 16:28:48 UTC 2019 x86_64 GNU/Linux
* Official Arch Linux binaries from  `openscad 2019.05-1`

**Comment by sloriot** [comment]
Try this sequence for the faces.
0 2 3 1
4 5 7 6
0 1 5 4
6 7 3 2
4 6 2 0
1 3 7 5

**Comment by mic-e** [comment]
Thanks for the suggestion, but I think you misunderstood the intent of my bug report.

I didn't want you to fix my cube, there's easier ways of properly rendering a cube :)
My actual polyhedron is much more complex, and I just changed that to a bunch of linear extrusions after I encountered this bug.

I reported the bug because I think that CGAL should produce a proper user-facing error if presented with an invalid polyhedron of this type, instead of first rendering it properly but then throwing an internal assertion if any other object is added.

That way it took me quite some time to isolate this polyhedron as the cause of the error.

**Comment by sloriot** [comment]
CGAL is not doing any rendering, it is a library of algorithm and data structure. Please provide a minimal example showing your problem.  Your rendering issue is probably in Openscad.

**Comment by sloriot** [comment]
cc @kintel

**Comment by mic-e** [comment]
Ah, OK. I was assuming that the error output of OpenSCAD contained a CGAL internal failed assertion, it had to do with the CGAL library.
Or maybe I described my problem unclearly.

I already tried to make the example as minimal as possible, reducing my complex polyhedron to just a cube.

With your information, I assume that any polyhedron which has a face that is the wrong way around (points specified in the wrong order) will cause this failed assertion.

Should I report this bug in OpenSCAD instead?

**Comment by mic-e** [comment]
Ah, OK. I was assuming that the error output contained a CGAL internal failed assertion, it had to do with the CGAL library. Maybe I described my problem unclearly.

I already tried to make the example as minimal as possible, I don't think it can get much simpler than a cube.

With your information, I assume that any polyhedron which has a face that is the wrong way around (points specified in the wrong order) will cause this assertion error.

Should I report this bug in OpenSCAD instead? Maybe it would be OpenSCAD's job to detect the broken polyhedron before it passes it on to CGAL?

**Comment by sloriot** [comment]
You should indeed report to OpenSCAD,

**Comment by mic-e** [comment]
OK, thanks.
For proper reporting to the OpenSCAD team, is my following analysis correct:

- OpenSCAD accepts my polyhedron even though my polyhedron has inconsistent point ordering (clockwise/counterclockwise) in its faces
- OpenSCAD passes the invalid polyhedron to CGAL. This is an improper use of CGAL's API
- This causes CGAL to crash/throw an internal assertion error sometimes

**Comment by sloriot** [comment]
Yes, it seems correct.
