### ISSUE TITLE
OpenCV includes

### ISSUE THREAD

**Issue by JoelSjogren** [CGAL/cgal#4214]
## Issue Details

I am trying to build demos for the latest release branch 4.14.

    % make demos -j7
    ...
    [ 97%] Building CXX object demo/Polyhedron/Plugins/Classification/CMakeFiles/classification_plugin.dir/Surface_mesh_item_classification.cpp.o
    In file included from /home/joel/git/cgal/Polyhedron/demo/Polyhedron/Plugins/Classification/Item_classification_base.h:17,
                    from /home/joel/git/cgal/Polyhedron/demo/Polyhedron/Plugins/Classification/Point_set_item_classification.h:11,
                    from /home/joel/git/cgal/Polyhedron/demo/Polyhedron/Plugins/Classification/Point_set_item_classification.cpp:6:
    /home/joel/git/cgal/Classification/include/CGAL/Classification/OpenCV/Random_forest_classifier.h:29:10: fatal error: cv.h: No such file or directory
    29 | #include <cv.h>
        |          ^~~~~~
    compilation terminated.
    make[3]: *** [demo/Polyhedron/Plugins/Classification/CMakeFiles/classification_plugin.dir/build.make:101: demo/Polyhedron/Plugins/Classification/CMakeFiles/classification_plugin.dir/Point_set_item_classification.cpp.o] Error 1
    make[3]: *** Waiting for unfinished jobs....
    In file included from /home/joel/git/cgal/Polyhedron/demo/Polyhedron/Plugins/Classification/Item_classification_base.h:17,
                    from /home/joel/git/cgal/Polyhedron/demo/Polyhedron/Plugins/Classification/Cluster_classification.h:10,
                    from /home/joel/git/cgal/Polyhedron/demo/Polyhedron/Plugins/Classification/Cluster_classification.cpp:6:
    /home/joel/git/cgal/Classification/include/CGAL/Classification/OpenCV/Random_forest_classifier.h:29:10: fatal error: cv.h: No such file or directory
    29 | #include <cv.h>
        |          ^~~~~~
    compilation terminated.
    In file included from /home/joel/git/cgal/Polyhedron/demo/Polyhedron/Plugins/Classification/Item_classification_base.h:17,
                    from /home/joel/git/cgal/Polyhedron/demo/Polyhedron/Plugins/Classification/Classification_plugin.cpp:12:
    /home/joel/git/cgal/Classification/include/CGAL/Classification/OpenCV/Random_forest_classifier.h:29:10: fatal error: cv.h: No such file or directory
    29 | #include <cv.h>
        |          ^~~~~~
    compilation terminated.
    make[3]: *** [demo/Polyhedron/Plugins/Classification/CMakeFiles/classification_plugin.dir/build.make:114: demo/Polyhedron/Plugins/Classification/CMakeFiles/classification_plugin.dir/Cluster_classification.cpp.o] Error 1
    make[3]: *** [demo/Polyhedron/Plugins/Classification/CMakeFiles/classification_plugin.dir/build.make:88: demo/Polyhedron/Plugins/Classification/CMakeFiles/classification_plugin.dir/Classification_plugin.cpp.o] Error 1
    In file included from /home/joel/git/cgal/Polyhedron/demo/Polyhedron/Plugins/Classification/Item_classification_base.h:17,
                    from /home/joel/git/cgal/Polyhedron/demo/Polyhedron/Plugins/Classification/Surface_mesh_item_classification.h:11,
                    from /home/joel/git/cgal/Polyhedron/demo/Polyhedron/Plugins/Classification/Surface_mesh_item_classification.cpp:1:
    /home/joel/git/cgal/Classification/include/CGAL/Classification/OpenCV/Random_forest_classifier.h:29:10: fatal error: cv.h: No such file or directory
    29 | #include <cv.h>
        |          ^~~~~~
    compilation terminated.
    make[3]: *** [demo/Polyhedron/Plugins/Classification/CMakeFiles/classification_plugin.dir/build.make:127: demo/Polyhedron/Plugins/Classification/CMakeFiles/classification_plugin.dir/Surface_mesh_item_classification.cpp.o] Error 1
    make[2]: *** [CMakeFiles/Makefile2:4607: demo/Polyhedron/Plugins/Classification/CMakeFiles/classification_plugin.dir/all] Error 2
    make[1]: *** [CMakeFiles/Makefile2:331: Installation/CMakeFiles/demos.dir/rule] Error 2
    make: *** [Makefile:203: demos] Error 2

## Source Code

https://github.com/CGAL/cgal/blob/master/Classification/include/CGAL/Classification/OpenCV/Random_forest_classifier.h

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): arch linux
* Compiler: gcc 9.1.0
* Release or debug mode: release
* Specific flags used (if any): the one that enables demos
* CGAL version: 4.14
* Boost version: 1_69
* Other libraries versions if used (Eigen, TBB, etc.): opencv 4.1.1-1

## Diagnosis
I asked on #opencv @ freenode and someone told me:

    <Cracki> that's the c api so they shouldn't even be able to use c++ parts of opencv with just that include
    <Cracki> https://github.com/opencv/opencv/blob/3.4/include/opencv/cv.h#L61
    <Cracki> https://github.com/CGAL/cgal/commit/90698d93986ca08d77d149baf56946a83da3ec69#diff-4e591f4485b238012daae7d2a2e18128
    <Cracki> THAT is the commit that fucked it up
    <Cracki> they removed an include that would have been jsut fine, and should have added a similar one for the ml parts

**Comment by JoelSjogren** [comment]
<Cracki> yeah the 3.4 branch has an include/opencv dir still
    <Cracki> got axed in 4.x

**Comment by lrineau** [comment]
Fixed by https://github.com/CGAL/cgal/pull/4241.
