### ISSUE TITLE
How to configure CGAL to use laslib

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#4215]
There is nothing in the documention. I expected setting `LASLIB_DIR` to be working but it does not for now and anyway there is nothing in the installation manual.

**Comment by afabri** [comment]
Have a look at the [CMakeLists.txt](https://github.com/CGAL/cgal/blob/master/Point_set_processing_3/examples/Point_set_processing_3/CMakeLists.txt#L62) file of the Point Set Processing package.

**Comment by sloriot** [comment]
That's what I did. What I'm saying is that is should be documented like the other dependencies.

**Comment by sgiraudot** [comment]
What do you mean "documented like the other dependencies"? From what I see, [the LASlib paragraph in the doc](https://doc.cgal.org/latest/Manual/installation.html#thirdpartyLASlib) is pretty much the same as the other ones. Is there any place I missed where we document the CMake variables?

**Comment by sloriot** [comment]
https://doc.cgal.org/latest/Manual/installation.html#installation_summary

**Comment by sloriot** [comment]
I guess the same hold for OpenCV, TensorFlow (and upcoming OpenGR, libpointmatcher)

**Comment by lrineau** [comment]
[**@sloriot**](https://github.com/sloriot) commented on [Sep 23, 2019, 11:34 AM GMT+2](https://github.com/CGAL/cgal/issues/4215#issuecomment-534026312 "2019-09-23T09:34:57Z - Replied by Github Reply Comments"):
> https://doc.cgal.org/latest/Manual/installation.html#installation_summary

So you think those tables have a value? For the documentation of CGAL-5.0, we were considering removing all that.

**Comment by sloriot** [comment]
Well, if `LibFooBar_DIR` is not supported it is hard to guess what to use. Is the official way to configure a lib to look at the `FindLibFooBar.cmake`?
