### ISSUE TITLE
CGAL Library error in version (4.14_1)

### ISSUE THREAD

**Issue by indrajittah** [CGAL/cgal#4216]
_Please use the following template to help us solving your issue._

## Issue Details

_Describe your issue. Please be specific (compilation error, runtime error, unexpected behavior, wrong results, etc.)._

## Source Code
In new version of CGAL (4.14_1) I did not found the library<CGAL/Periodic_2_triangulation_filtered_traits_2.h> but it was available on version CGAL-4.9. I am always getting the fatal error: 'CGAL/Periodic_2_triangulation_filtered_traits_2.h' file not found. Could you please help me to resolve the above issue in newer version.

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): MAC-10.14.5
* Compiler:
* Release or debug mode:
* Specific flags used (if any):
* CGAL version:4.14_1
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by sloriot** [comment]
The filtering mechanism has been made automatic and you no longer need to include this header.
Simply include `CGAL/Periodic_2_triangulation_traits_2.h` and declare your triangulation as follow:

```
typedef CGAL::Exact_predicates_inexact_constructions_kernel K;
typedef CGAL::Periodic_2_Delaunay_triangulation_traits_2<K> PK;
typedef CGAL::Periodic_2_Delaunay_triangulation_2<PK>       P2DT2;
```
