### ISSUE TITLE
boost/container/flat_map.hpp wrongly included

### ISSUE THREAD

**Issue by dolfjaapklomp** [CGAL/cgal#4220]
_Please use the following template to help us solving your issue._

## Issue Details

I got a build error due to the inclusion of boost/container/flat_map.hpp while my boost version was 1.68, by the config.h file.
boost/container/flat_map.hpp should only be included for boost version 1.62. 

## Source Code

In the CGAL config.h file there is a type in the macro name

Excerpt from config.h:
133:  // workaround for the bug https://svn.boost.org/trac10/ticket/12534
134:  // That bug was introduced in Boost 1.62 and fixed in 1.63.
135:  #if BOOST_VERSION >= 106200 && BOOST**S**_VERSION < 106300
136:  #  include <boost/container/flat_map.hpp>
137:  #endif

## Solution

Remove the extra **S** in the next release.

**Comment by mglisse** [comment]
Sure, the typo should be fixed, but what kind of error are you getting? Unnecessarily including `flat_map.hpp` should be safe.

**Comment by lrineau** [comment]
Fixed by PR https://github.com/CGAL/cgal/pull/4292.
