### ISSUE TITLE
triangulate_refine_and_fair_hole never returns, possibly related to precision

### ISSUE THREAD

**Issue by jasjuang** [CGAL/cgal#4235]
## Issue Details

I have a particular mesh [here](https://github.com/CGAL/cgal/files/3637847/problem.zip) which causes `CGAL::Polygon_mesh_processing::triangulate_refine_and_fair_hole` to never return. Please see below minimal code:

```
  using K    = CGAL::Simple_cartesian<double>;
  using Mesh = CGAL::Surface_mesh<K::Point_3>;

  Mesh m;

  std::ifstream input("problem.off");
  input >> m;
  input.close();

  const double max_border_len =
      CGAL::Polygon_mesh_processing::longest_border(
          m, CGAL::Polygon_mesh_processing::parameters::vertex_point_map(
              get(CGAL::vertex_point, m))).second;

  for (Mesh::Halfedge_index it : m.halfedges()){
    const double border_len = CGAL::Polygon_mesh_processing::face_border_length(
        it, m, CGAL::Polygon_mesh_processing::parameters::vertex_point_map(
            get(CGAL::vertex_point, m)));

    if (m.is_border(it) && max_border_len - border_len > 10e-8){
      std::vector<Mesh::Face_index> patch_face;
      std::vector<Mesh::Vertex_index> patch_vert;

      CGAL::Polygon_mesh_processing::triangulate_refine_and_fair_hole(
          m, it, std::back_inserter(patch_face),
          std::back_inserter(patch_vert),
          CGAL::Polygon_mesh_processing::parameters::vertex_point_map(
              get(CGAL::vertex_point, m)));
    }
  }

  std::cout << "never reaches here" << std::endl;
```

The reason I think it is related to precision is initially when I was trying to create a minimal example, I inserted the below 

```
  std::ofstream output("problem.off");
  output << m;
  output.close();
```

after running all the operations before reaching `triangulate_refine_and_fair_hole` in my downstream project, but when I read this mesh in the minimal example, it didn't get stuck. However, if I inserted the below instead

```
  std::ofstream output("problem.off");
  output << std::setprecision(20) << m;
  output.close();
```

and then read this mesh in the minimal example it got stuck. Please let me know if you can reproduce the problem.

## Environment

* Operating system: Ubuntu 18.04
* Compiler: GCC 7
* Release or debug mode: Release
* CGAL version: Latest
* Boost version: 1.68

**Comment by sloriot** [comment]
Do you still have the problem if you replace `CGAL::Simple_cartesian<double>` with `CGAL::Exact_predicates_inexact_constructions_kernel`?

**Comment by jasjuang** [comment]
@sloriot You are right if I change it to `CGAL::Exact_predicates_inexact_constructions_kernel` it actually solves it. Thanks for the help.
