### ISSUE TITLE
FindTBB.cmake is still not working

### ISSUE THREAD

**Issue by zhfsu** [CGAL/cgal#4236]
_Please use the following template to help us solving your issue._

## Issue Details

I submitted a ticket 2 months ago (#4085) about FindTBB.cmake not working. A developer sent me a revised version of FindTBB.cmake and it worked. Now I reinstalled Windows and therefore need to reinstall CGAL. Since the version I am installing is still 4.14, it is not surprising that CMake GUI cannot find TBB. I then downloaded the most up-to-date FindTBB.cmake from cgal/Installation/cmake/modules/FindTBB.cmake and copied it to C:\dev\CGAL-4.14\cmake\modules, hoping that the issue has been solved forever. But, to my disappointment, I still got errors about finding TBB, and this time the problem seems more aggravated. Unlike 2 months ago, I now have almost no time troubleshooting the problem myself. So, please fix it and conduct test in actual environment to make sure it is indeed fixed.

I installed TBB by downloading the most recent version 2019 Update 8 from https://github.com/intel/tbb/releases, unzipping it and running `bin\tbbvars.bat` with proper arguments.
The CGAL I'm trying to install is 4.14 and the CMake version I am using is 3.15.3.
The error message I got is:

> CMake Error at cmake/modules/FindTBB.cmake:7:
>   Parse error.  Expected a command name, got unquoted argument with text
>   "<!DOCTYPE".
> Call Stack (most recent call first):
>   demo/Polyhedron/CMakeLists.txt:97 (find_package)
> 
> 
> CMake Warning at demo/Polyhedron/CMakeLists.txt:97 (find_package):
>   By not providing "FindTBB.cmake" in CMAKE_MODULE_PATH this project has
>   asked CMake to find a package configuration file provided by "TBB", but
>   CMake did not find one.
> 
>   Could not find a package configuration file provided by "TBB" with any of
>   the following names:
> 
>     TBBConfig.cmake
>     tbb-config.cmake
> 
>   Add the installation prefix of "TBB" to CMAKE_PREFIX_PATH or set "TBB_DIR"
>   to a directory containing one of the above files.  If "TBB" provides a
>   separate development package or SDK, be sure it has been installed.
> 
> 
> Configuring incomplete, errors occurred!
> See also "C:/dev/CGAL-4.14/build/CMakeFiles/CMakeOutput.log".
> See also "C:/dev/CGAL-4.14/build/CMakeFiles/CMakeError.log".
> 

The original FindTBB.cmake file and the revised one the developer sent me 2 months ago at least can ignore the error (which is "ERROR: Intel TBB NOT found! Please define the TBBROOT (or TBB_INSTALL_DIR) and/or TBB_ARCH_PLATFORM environment variables." though I have defined TBBROOT env var) and cmake can configure. But now even configure errors if I use the 199KB version.

## Source Code

It's right in the repo: https://github.com/CGAL/cgal/blob/master/Installation/cmake/modules/FindTBB.cmake

_If your issue arises by using CGAL in your own source code, please provide a minimalist example that we can compile easily to reproduce the bug. If your issue arises from using a CGAL program (demo, example, etc.), please let us know which one. Helping you solving an issue is much easier and efficient if we can reproduce it._

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows 10, version 1903, 64 bit
* Compiler: Not yet compiled
* Release or debug mode:
* Specific flags used (if any):
* CGAL version: 4.14
* Boost version: it has nothing to do with Boost
* Other libraries versions if used (Eigen, TBB, etc.): TBB version 2019 Update 8.

**Comment by lrineau** [comment]
The error message about `<!DOCTYPE"` shows that you have downloaded the web page https://github.com/CGAL/cgal/blob/master/Installation/cmake/modules/FindTBB.cmake and not the file itself! To get the file, you must click on the `Raw` button of the web page. Follow this link to get the file: https://raw.githubusercontent.com/CGAL/cgal/master/Installation/cmake/modules/FindTBB.cmake.
