### ISSUE TITLE
Can not build with ZLIB

### ISSUE THREAD

**Issue by zhfsu** [CGAL/cgal#4237]
_Please use the following template to help us solving your issue._

## Issue Details

I have added ZLIB_LIBRARY and ZLIB_INCLUDE_DIR as instructed in the error message, but CGAL CMake script just cannot find zlib. I believe I built up zlib correctly and specified the two cache vars in a way I think is correct. The error message is:

> Could NOT find ZLIB (missing: ZLIB_INCLUDE_DIR) 
> NOTICE: libCGAL_ImageIO needs ZLib to read compressed files. That feature will not be activated.

 We can see that ZLIB_LIBRARY is accepted but ZLIB_INCLUDE_DIR is not, hence the error I guess. I did not want to build with OIIO so I did not check WITH_CGAL_ImageIO.

The cmake GUI still configures, but I wanna build CGAL with ZLIB, so what do I do to have the CGAL configure accept the ZLIB_INCLUDE_DIR value I specified, to get rid of the above error, and to build with zlib? Thank you.

_Describe your issue. Please be specific (compilation error, runtime error, unexpected behavior, wrong results, etc.)._

## Source Code

_If your issue arises by using CGAL in your own source code, please provide a minimalist example that we can compile easily to reproduce the bug. If your issue arises from using a CGAL program (demo, example, etc.), please let us know which one. Helping you solving an issue is much easier and efficient if we can reproduce it._

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows 10, version 1903, 64bit
* Compiler: Not yet compiled
* Release or debug mode:
* Specific flags used (if any):
* CGAL version: 4.14
* Boost version: the issue has nothing to do with Boost
* Other libraries versions if used (Eigen, TBB, etc.): neither with Eigen or TBB.

**Comment by lrineau** [comment]
What are the values you set in `ZLIB_INCLUDE_DIR` and `ZLIB_LIBRARY`? `ZLIB_INCLUDE_DIR` has to be the path of the directory that contains `zlib.h`.

**Comment by zhfsu** [comment]
The value of ZLIB_INCLUDE_DIR is D:\3rd-parties\zlib-1.2.11\install\include
The value of ZLIB_LIBRARY is D:\3rd-parties\zlib-1.2.11\install\lib\zlib.lib

The error is Could NOT find ZLIB (missing: ZLIB_INCLUDE_DIR) 
NOTICE: libCGAL_ImageIO needs ZLib to read compressed files. That feature will not be activated.

**Comment by lrineau** [comment]
[**@zhfsu**](https://github.com/zhfsu) commented on [Sep 25, 2019, 11:16 PM GMT+2](https://github.com/CGAL/cgal/issues/4237#issuecomment-535224979 "2019-09-25T21:16:22Z - Replied by Github Reply Comments"):
> The value of ZLIB_INCLUDE_DIR is D:\3rd-parties\zlib-1.2.11\install\include
> The value of ZLIB_LIBRARY is D:\3rd-parties\zlib-1.2.11\install\lib\zlib.lib
> 
> The error is Could NOT find ZLIB (missing: ZLIB_INCLUDE_DIR) 
> NOTICE: libCGAL_ImageIO needs ZLib to read compressed files. That feature will not be activated.

That is indeed strange. Does the file `D:\3rd-parties\zlib-1.2.11\install\include\zlib.h` exist?

**Comment by zhfsu** [comment]
Yes, the zlib.h file exists and contains correct contents.
I can give you ID and passcode of TeamViewer so that you can conduct field debugging. The machine is usually available in the morning. I believe in you.

**Comment by lrineau** [comment]
[**@zhfsu**](https://github.com/zhfsu) commented on [Sep 28, 2019, 10:21 AM GMT+2](https://github.com/CGAL/cgal/issues/4237#issuecomment-536165404 "2019-09-28T08:21:46Z - Replied by Github Reply Comments"):
> Yes, the zlib.h file exists and contains correct contents.
> I can give you ID and passcode of TeamViewer so that you can conduct field debugging. The machine is usually available in the morning. I believe in you.

Be careful not to send and ID/password on Github. Send to my email address

    laurent.rineau \AT\ geometryfactory.com
