### ISSUE TITLE
Compilation of mesh simplification

### ISSUE THREAD

**Issue by simonasdmd** [CGAL/cgal#4239]
_Please use the following template to help us solving your issue._

## Issue Details
I have manually incorporated two updates of "4122" and "4069". But errors are displayed at compile time. Some LNK 2019 errors. Is there anything else that needs to be changed?

![image](https://user-images.githubusercontent.com/42527845/65408911-120e8180-de19-11e9-861f-44b1b3d314b3.png)

_Describe your issue. Please be specific (compilation error, runtime error, unexpected behavior, wrong results, etc.)._

## Source Code

The code is below. (Please remove ".txt" manually)

[jianhua.cpp.txt](https://github.com/CGAL/cgal/files/3641082/jianhua.cpp.txt)

_If your issue arises by using CGAL in your own source code, please provide a minimalist example that we can compile easily to reproduce the bug. If your issue arises from using a CGAL program (demo, example, etc.), please let us know which one. Helping you solving an issue is much easier and efficient if we can reproduce it._

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):win10 64
* Compiler: vs2017
* Release or debug mode:debug 64
* Specific flags used (if any):
* CGAL version:4.13
* Boost version:1.70
* Other libraries versions if used (Eigen, TBB, etc.):

Thank you all.

**Comment by simonasdmd** [comment]
@lrineau 
Hello. I added "libgmp" and had the same problem.
![image](https://user-images.githubusercontent.com/42527845/65410452-fad19300-de1c-11e9-992f-3c1b15641d0e.png)

**Comment by lrineau** [comment]
Your screenshot does not say anything about libgmp. It seems to show directories, including the one `auxiliary\lib\gmp` that probably contains libgmp. But that is not the screen that tells if libgmp is added to the project.

**Comment by simonasdmd** [comment]
hi~ 
My CGAL environment is downloaded from the "CGAL-4.13.1-Setup.exe" installation. There is only "gmp / lib" under "auxiliary" in the installation directory. Is there anything missing?
![image](https://user-images.githubusercontent.com/42527845/65475276-94e31b00-deb1-11e9-84d4-aa1aaec58c16.png)
![image](https://user-images.githubusercontent.com/42527845/65475290-9f9db000-deb1-11e9-8e9e-7011c0ba88d4.png)
![image](https://user-images.githubusercontent.com/42527845/65475299-a7f5eb00-deb1-11e9-94ea-8225bab22e9e.png)

**Comment by simonasdmd** [comment]
hi @lrineau 
If you can compile properly. Could you show me your catalog structure? Thank you.

**Comment by lrineau** [comment]
You are right. `CGAL4.13/auxiliary/gmp/lib` is the right path to the directory that contains the GMP and MPFR libraries. But you still need to instruct Visual Studio to link your project with them. I do not use Visual Studio myself, and I cannot tell where it is in the configuration dialogs.
