### ISSUE TITLE
Speeding up side of triangle mesh

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#4247]
I notice that the runtime of doing a Boolean operation of two disjoint and far apart meshes was actually larger than when they intersect. My guess is that it is coming from the need to build the AABB-tree to decide if one mesh is inside the other.

I think we should only build the tree if the bbox of the meshes (or even obb as soon as we integrate it) are not disjoint.
The same kind of trick can be apply to `Side_of_triangle_mesh`, that is use the bbox of the mesh before building the tree to answer a query.

@maxGimeno or @afabri. you might want to have a look.

**Comment by afabri** [comment]
For `Side_of_triangle_mesh` it does not really make sense.  You construct the AABB tree once for many queries. One might think about constructing the tree un a lazy manner, that is only the root bbox. If a query is outside fine, if inside one constructs the left and right child bbox.  Unfortunaltely the bboxes are constructed bottom up.

**Comment by sloriot** [comment]
The building of the tree can still be lazy + it will always be cheaper to do the size of with a bbox than a ray shooting in the tree even without intersections.
