### ISSUE TITLE
Demos:  Dialog with numbers are too short

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#4251]
## Issue Details

For example in the isotropic remeshing pop up window I first must remove the last digit, so that I can insert a 0 right after the comma.  

![image](https://user-images.githubusercontent.com/3263539/65679967-65214800-e056-11e9-972c-dcaaaff49e1a.png)

**Comment by maxGimeno** [comment]
We should make a custom class based on QLineEdit with a specific validator that only takes doubles. The current QDoubleSpinBox does not allow to have extra slots, it will automatically fill it with `0`s and therefore it will never be possible to add a digit. The LineEdit sdoes not have that problem.
