### ISSUE TITLE
header-only not quite the default

### ISSUE THREAD

**Issue by mglisse** [CGAL/cgal#4264]
## Issue Details

I downloaded the beta1 version of CGAL-5.0. In it, I ran `cmake . && make` (probably useless, I ran it just in case it might still create `compiler_config.h`). Now I am trying to use CGAL without cmake. `g++ -c file.cpp -I /path/to/include` produces
> fatal error: CGAL/compiler_config.h: No such file or directory

Apparently I need `-DCGAL_HEADER_ONLY`, which is strange for what is supposed to be the default. Shouldn't it be the other way around, people who do not want header-only need to define some macro?

## Source Code

```c++
#include <CGAL/config.h>
```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Linux
* Compiler: g++-9.2.1
* Release or debug mode: Release
* Specific flags used (if any):
* CGAL version: 5.0-beta1

**Comment by lrineau** [comment]
For the moment, CGAL does not officially support any setup that does not use CMake and our file `CGALConfig.cmake`. That might change for 5.1, but we will have to change our testsuite process.

I agree we could easily reverse the default behavior of `<CGAL/config.h>`, to help your use-case, even if that would not be officially supported nor tested.

**Comment by mglisse** [comment]
I think requiring CMake stretches the definition of "header-only" way too far: you could have CMake build the library on demand and it would remain just as header-only as it is now.
But it is not a regression, so it shouldn't block the release.

**Comment by mglisse** [comment]
> But given our history, we are doing our best.

Sure, and I won't be shocked if this waits until the next release, to reduce the risk of breaking the recommended cmake usage just before the release.

> I consider that anything that is not tested automatically is assumed broken.
 
That might get funny, using cmake/ctest to test that things work when you don't use cmake :grinning: 

> I have created #4265 to help you test case. Do you think that will fix your use case?

Probably, yes. (I only looked at `config.h`)

**Comment by lrineau** [comment]
Now it is the default.
