### ISSUE TITLE
Can CGAL's cmake script automatically detect MKL BLAS and use it?

### ISSUE THREAD

**Issue by zhfsu** [CGAL/cgal#4267]
_Please use the following template to help us solving your issue._

## Issue Details
I installed intel Parallel Studio 2019 Update 5 which contains BLAS APIs called MKL BLAS. The presence of MKL BLAS can be detected by some libraries which need BLAS functionality after running `psxevars.bat` with proper arguments. For example, Eigen3's cmake script can detect MKL BLAS automatically as follows:

> -- Looking for MKL BLAS: found
> -- A library with BLAS API found.
> -- BLAS_LIBRARIES C:/Program Files (x86)/IntelSWTools/parallel_studio_xe_2019.5.068/compilers_and_libraries_2019/windows/mkl/lib/intel64/mkl_intel_lp64_dll.lib;C:/Program Files (x86)/IntelSWTools/parallel_studio_xe_2019.5.068/compilers_and_libraries_2019/windows/mkl/lib/intel64/mkl_sequential_dll.lib;C:/Program Files (x86)/IntelSWTools/parallel_studio_xe_2019.5.068/compilers_and_libraries_2019/windows/mkl/lib/intel64/mkl_core_dll.lib
> -- Could NOT find CHOLMOD (missing: CHOLMOD_INCLUDES CHOLMOD_LIBRARIES)
> -- Could NOT find UMFPACK (missing: UMFPACK_INCLUDES UMFPACK_LIBRARIES)
> -- Could NOT find SUPERLU (missing: SUPERLU_INCLUDES SUPERLU_LIBRARIES SUPERLU_VERSION_OK)
> -- Found PkgConfig: D:/3rd-parties/pkg-config.exe (found version "0.28")
> -- Checking for one of the modules 'hwloc'
> -- Found BLAS: C:/Program Files (x86)/IntelSWTools/parallel_studio_xe_2019.5.068/compilers_and_libraries_2019/windows/mkl/lib/intel64/mkl_intel_lp64_dll.lib;C:/Program Files (x86)/IntelSWTools/parallel_studio_xe_2019.5.068/compilers_and_libraries_2019/windows/mkl/lib/intel64/mkl_sequential_dll.lib;C:/Program Files (x86)/IntelSWTools/parallel_studio_xe_2019.5.068/compilers_and_libraries_2019/windows/mkl/lib/intel64/mkl_core_dll.lib
> 

I expect that the same automatic detection can take place in CGAL's cmake script, but CGAL fails to do it after I checked `WITH_BLAS` option in cmake-gui (as well as running `psxevars.bat`):

> -- Preconfiguring library: BLAS ...
> -- A library with BLAS API not found. Please specify library location.
> 
So is it because I missed setting some variables, or CGAL's cmake script just can't detect MKL BLAS automatically at all? If the former, what variables do I need to set to use MKL BLAS in CGAL's installation? If the latter, I hope CGAL can learn from Eigen3 and automatically detect MKL BLAS which is contained in intel Parallel Studio 2019. Thank you.

Environment:
- Windows 10 version 1903, 64bit
- release/CGAL-4.14-branch source
- CMake 3.15.3
- intel Parallel Studio 2019 Update 5
- Eigen 3.3.7
- Visual Studio 2015 Update 3

## Source Code

_If your issue arises by using CGAL in your own source code, please provide a minimalist example that we can compile easily to reproduce the bug. If your issue arises from using a CGAL program (demo, example, etc.), please let us know which one. Helping you solving an issue is much easier and efficient if we can reproduce it._

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows 10 version 1903, 64bit
* Compiler: Not compiled yet
* Release or debug mode: Release
* Specific flags used (if any):
* CGAL version: 4.14 branch build
* Boost version: The issue has nothing to do with Boost
* Other libraries versions if used (Eigen, TBB, etc.): Eigen 3.3.7, TBB & MKL included in intel Parallel Studio 2019 Update 5.

**Comment by lrineau** [comment]
The support for BLAS/LAPACK in CGAL was not longer tested, after we have switched to using the Eigen3 API everywhere. In CGAL-5.0-beta1, we have even removed our CMake scripts about BLAS/LAPACK: https://github.com/CGAL/cgal/pull/3739

I think you should ask that sort of questions to the Eigen3 project, that now for CGAL the upstream provide for any matrix-release algorithms.

**Comment by zhfsu** [comment]
Thank you for the reply. Since BLAS/LAPACK has been removed from CGAL, maybe we could as well remove WITH_BLAS and WITH_LAPACK cache variable from cmake-gui's variable list.
