### ISSUE TITLE
Mpfz default constructor causes unreachable code warning is Visual Studio

### ISSUE THREAD

**Issue by jasjuang** [CGAL/cgal#4268]
## Issue Details

Please see the below minimal code to reproduce the problem:

CMakeLists.txt
```
cmake_minimum_required(VERSION 3.11)

set(CMAKE_TOOLCHAIN_FILE
    $ENV{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake
    CACHE STRING "")
set(VCPKG_TARGET_TRIPLET $ENV{VCPKG_DEFAULT_TRIPLET} CACHE STRING "")

project(Example)

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /WX /W4")

set(PROJECT_SRCS ${PROJECT_SOURCE_DIR}/main.cpp)

find_package(CGAL REQUIRED)

add_executable(${PROJECT_NAME} ${PROJECT_SRCS})

target_link_libraries(${PROJECT_NAME} CGAL::CGAL)
```

main.cpp
```
__pragma(warning(push,0))
#include "CGAL/Exact_predicates_inexact_constructions_kernel.h"
#include "CGAL/Polygon_mesh_processing/remesh.h"
#include "CGAL/Surface_mesh.h"
__pragma(warning(pop))

int main(){
  using Pt_3 = CGAL::Exact_predicates_inexact_constructions_kernel::Point_3;
  using Mesh = CGAL::Surface_mesh<Pt_3>;

  Mesh m;

  CGAL::Polygon_mesh_processing::isotropic_remeshing(m.faces(), 5, m);

  return 0;
}
```

Error message
```
1>main.cpp
1>c:\dev\vcpkg\installed\x64-windows\include\cgal\mpzf.h(273): error C2220: warning treated as error - no 'object' file generated
1>c:\dev\vcpkg\installed\x64-windows\include\cgal\mpzf.h(273): warning C4702: unreachable code
1>c:\dev\vcpkg\installed\x64-windows\include\cgal\mpzf.h(273): warning C4702: unreachable code
1>c:\dev\vcpkg\installed\x64-windows\include\cgal\mpzf.h(273): warning C4702: unreachable code
1>Done building project "Example.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 1 up-to-date, 0 skipped ==========
```

line 273 of mpzf.h is
```
inline mp_limb_t*& data() { return data_; }
```

If I comment out `isotropic_remeshing`, the error disappears. My guess is `isotropic_remeshing` indirectly uses something in mpzf.h that causes the warning to trigger, because if I include `CGAL/mpzf.h` directly without calling `isotropic_remeshing`, it actually compiles. The weird thing is this warning is not suppressed by the pragma warning push pop calls that surrounded the CGAL headers, so I don't even know how to temporarily work around this problem. Please help. 

## Environment

* Operating system: Windows 10
* Compiler: Visual Studio 2017
* Release or debug mode: Release
* CGAL version: 4.14 from `vcpkg install cgal[*]`
* Boost version: 1.71

**Comment by janetournois** [comment]
Hi @jasjuang 

I could reproduce the issue with the "non-vcpkg" CGAL-4.14.1 version, and the shortened following CMakeLists :
```
cmake_minimum_required(VERSION 3.11)
project(Example)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /WX /W4")
set(PROJECT_SRCS ${PROJECT_SOURCE_DIR}/issue4268.cpp)

find_package(CGAL REQUIRED)

add_executable(${PROJECT_NAME} ${PROJECT_SRCS})
target_link_libraries(${PROJECT_NAME} CGAL::CGAL)
```

**Comment by afabri** [comment]
A temporary workaround is not to use `/WX`.

**Comment by janetournois** [comment]
Note that the warning does not appear when you compile in Debug mode.

**Comment by lrineau** [comment]
Which piece of code is unreachable at line 273 of `<CGAL/Mpzf.h>`?

**Comment by janetournois** [comment]
The code is :
```   inline mp_limb_t*& data() { return data_; }
```
and the same happens with `master`

**Comment by janetournois** [comment]
Actually this minimal main also generates the warning :
```c++
#include "CGAL/Mpzf.h"

int main()
{
  CGAL::Mpzf x;
  return 0;
}
```

The default constructor of `Mpfz` calls the `init()` function :
```c++
  void init(unsigned mini=2){
#ifdef CGAL_MPZF_USE_CACHE
    if (mini <= cache_size) {
      cache[0] = cache_size;
      data() = cache + 1;
      return;
    }
#endif
    if(!pool::empty()){
      data() = pool::pop();
      if(data()[-1] >= mini) return; // TODO: when mini==2, no need to check
      delete[] (data() - (pool::extra+1)); // too small, useless
    }
    if(mini<2) mini=2;
    data() = (new mp_limb_t[mini+(pool::extra+1)]) + (pool::extra+1);
    data()[-1] = mini;
  }
```

`mini=2` and `cache_size=8`, so the compiler (in Release mode only) can figure out that everything outside the first `if()` block will not be reached.

**Comment by lrineau** [comment]
That looks like a compiler bug.

**Comment by afabri** [comment]
I was wondering how GCC does it and found [this](https://www.reddit.com/r/cpp/comments/695ye5/detect_unreachable_code_with_gcc/)

**Comment by afabri** [comment]
@jasjuang in case you stick to `/W4` and `/WX`, you might exempt this particular warning with  `/wd4702`, or do it in the Mpzf.h  header with a pragma.  A PR  is welcome.

**Comment by jasjuang** [comment]
Thank you all for the discussion and pointers. Please see #4272 for the PR that resolves this issue.
