### ISSUE TITLE
Mesh_3 and Skin_surface_3 deprecated

### ISSUE THREAD

**Issue by MoniqueTeillaud** [CGAL/cgal#427]
Regular_triangulation_filtered_traits_3 has been deprecated since CGAL 3.6. After 5 years, it is time to stop keeping the backwards compatibility...

However 2 packages seem to still be using it, at least that's what a grep in master says.
- Skin_surface_3
- Mesh_3
It might be old stuff, though (this is explicit in the name of the directory old_stuff in Mesh_3, but unclear for some others).

Can you please clean the above two packages so that Regular_triangulation_filtered_traits_3 can be safely removed?

**Comment by lrineau** [comment]
About Mesh_3
------------------

I think the following two directories should be removed from CGAL:

    Mesh_3/examples/Mesh_3/old_stuff
    Mesh_3/test/Mesh_3/old_stuff

I had not noticed that was still in CGAL. That corresponds to examples and tests that were in the `Mesh_3` package, when it was an "experimental package", before Stéphane Tayeb took over the maintenance of the package. All the functionality of those directories is already replaced by something in the official distribution.

For the following two files, I do not know exactly what should be in. @cjamin, can you comment?

    Mesh_3/benchmark/Mesh_3/StdAfx.h
    Mesh_3/demo/Mesh_3/StdAfx.h

The files in `Mesh_3/applications/` should be updated. They are outside of the distribution, and scarcely used, but they could still be useful.

**Comment by cjamin** [comment]
Any #include present in an StdAfx.h file can be removed safely. It's just used for precompiled headers, to make the compilation faster, it doesn't have to contain all headers. It would work even if it was empty.

**Comment by sloriot** [comment]
See #510
