### ISSUE TITLE
make - Nothing to be done for 'all'

### ISSUE THREAD

**Issue by kubaroth** [CGAL/cgal#4287]
Out of source build reports there is not targets to be built while running 'make' or 'make all'. Not sure I missed something obvious, perhaps all target should be updated accordingly. Reverting to 4.12 and building in the root directory (in-source) works as expected.

**Comment by sloriot** [comment]
Could you please give more details about what you tried and what error messages you got? Do not forget to tell us which version of CGAL you are using and the platform you are using.

**Comment by kubaroth** [comment]
Hi and thanks for fast response. I'm building from master, out of source tree by running `cmake .. -DCMAKE_BUILD_TYPE=Release`. Configuration completes but when running make in verbose mode make output:
`
make[1]: Entering directory '/home/kuba/SRC/cgal/build'
make[1]: Nothing to be done for 'all'.
`

I just tested releases/CGAL-4.14.1 the build works fine on that release. 
Please feel free to close it, I'm fine using that version instead of master.

**Comment by kubaroth** [comment]
Ok, all good I was expecting build step to do something but obviously with the header only switch nothing needs to be done. Perhaps the default choice to header only should be clearly communicated during the cmake configuration.
Please close the ticket and apologies for the noise.
