### ISSUE TITLE
CGAL_Core: floating point filters go wrong on divisions

### ISSUE THREAD

**Issue by weaselp** [CGAL/cgal#4296]
As mentioned in a [mailinglist posting last month](http://cgal-discuss.949826.n4.nabble.com/error-in-comparing-CORE-Expr-values-td4664487.html), there are sequences of operations that result in wrong answers to predicate queries.

Consider this code snippet:
```
std::cout << "v1: " << v1 << std::endl;
std::cout << "v2: " << v2 << std::endl;
std::cout << "v1 < v2: " << (v1 < v2 ? "yes" : "no") << std::endl;
```
from [cgal0_1.cpp](https://github.com/CGAL/cgal/files/3734046/cgal0_1.txt), which prints this after constructing v1 and v2:
```
weasel@orinoco:~$ clang++ cgal0_1.cpp -o cgal -lgmpxx -lgmp -lboost_thread -lCGAL_Core -lCGAL  
weasel@orinoco:~$ ./cgal 
v1: 0.49770
v2: 0.01047
v1 < v2: yes
```

Clearly that is wrong, as 0.49 is not less than 0.01.

Stefan Schirra had some insights he shared in the followup posts on-list.

**Comment by lrineau** [comment]
@CGAL/geometryfactory This bug is about Core. I do not know why I self-assigned myself to it. Obviously, I will not have time to investigate. Which of us should handle this bug? @afabri?
