### ISSUE TITLE
import_from_triangulation_3: Incident segments > number of darts defining infinite vertex

### ISSUE THREAD

**Issue by pranavkantgaur** [CGAL/cgal#43]
Hi,

I am using ```import_from_triangulation_3``` and trying to isolate infinite vertex from finite vertices. In [this code](https://gist.github.com/pranavkantgaur/43332452b5c52747dd80#file-experimentwithbeta-cpp) however I find than number of darts representing segments incident on infinite vertex are more than number of darts defining the infinite vertex itself.  
But, from what I understand from [figure 24.2](http://doc.cgal.org/latest/Combinatorial_map/index.html#fig__figexemple3Dmanifold) in the documentation, darts representing incident segments should always be less than or equal to number of darts defining the vertex.

I would like to know if it really is an issue or a bug in my implementation itself?

**Comment by gdamiand** [comment]
This is a bug in your code. You don't go through all the darts defining the vertex in your loop line 71.
Iterating through all the darts of a given vertex need a stack to store darts to visit (similarly than a breath first search algorithm for graph).

**Comment by pranavkantgaur** [comment]
@gdamiand Thanks! now it is working.
