### ISSUE TITLE
Add a function in PMP to remesh a FaceGraph with Mesh_3/Surface_mesher

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#4301]
The idea is to add a function in PMP that is a one-liner to remesh a polyhedral surface with options as named parameters.

This could include the sampling of connected components as option, sharp features as constrained edges,  etc...

**Comment by afabri** [comment]
As we had discussed it some days ago, the goal was more to have  a chapter with several remeshing algorithms (based on Mesh_3, isotropic_remeshing,..).

**Comment by sloriot** [comment]
This is a separate issue.

**Comment by lrineau** [comment]
That would introduce a dependency from PMP to Mesh_3. I think that function should be introduced in Mesh_3, even if it uses the "PMP style" for its API (with named parameters).

**Comment by sloriot** [comment]
Initialization part also relevant for #921
