### ISSUE TITLE
How can I find the points which have been simplified when using the halfedge-collapse algorithm?

### ISSUE THREAD

**Issue by KeepFaithMe** [CGAL/cgal#4305]
_Please use the following template to help us solving your issue._

## Issue Details

when I use the method 'edge_collapse' to simplify the mesh,I want to know which poins have been simplified,and I want to konw the index of theis points?so whether there are some method I can use to accomplish it? 

## Source Code
```
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/Surface_mesh.h>

#include <CGAL/Polygon_mesh_processing/remesh.h>
#include <CGAL/Polygon_mesh_processing/border.h>

#include <boost/function_output_iterator.hpp>
#include <fstream>
#include <vector>

#include <CGAL/Simple_cartesian.h>
#include <CGAL/Surface_mesh.h>
#include <CGAL/Surface_mesh_simplification/edge_collapse.h>
#include <CGAL/Surface_mesh_simplification/Policies/Edge_collapse/Count_ratio_stop_predicate.h>
#include<iomanip>
//Remesh
typedef CGAL::Exact_predicates_inexact_constructions_kernel K;
typedef CGAL::Surface_mesh<K::Point_3> Mesh;
typedef boost::graph_traits<Mesh>::halfedge_descriptor halfedge_descriptor;
typedef boost::graph_traits<Mesh>::edge_descriptor     edge_descriptor;
namespace PMP = CGAL::Polygon_mesh_processing;
struct halfedge2edge
{
	halfedge2edge(const Mesh& m, std::vector<edge_descriptor>& edges)
		: m_mesh(m), m_edges(edges)
	{}
	void operator()(const halfedge_descriptor& h) const
	{
		m_edges.push_back(edge(h, m_mesh));
	}
	const Mesh& m_mesh;
	std::vector<edge_descriptor>& m_edges;
};
namespace SMS = CGAL::Surface_mesh_simplification;

int main()
{
	std::string filename = "C:/Users/10712/Desktop/test/1021/Model.off";
	std::ifstream input(filename);

	Mesh mesh;

	if (!input || !(input >> mesh) || !CGAL::is_triangle_mesh(mesh)) {
		std::cerr << "Not a valid input file." << std::endl;
		return 1;
	}
	if (!CGAL::is_triangle_mesh(mesh))
	{
		std::cerr << "Input geometry is not triangulated" << std::endl;
		return EXIT_FAILURE;
	}
	// In this example, the simplification stops when the number of undirected edges drops below 10% of the initial count
	SMS::Count_ratio_stop_predicate<Mesh> stop(0.8);

	int r = SMS::edge_collapse(mesh, stop);
	std::cout << "\nFinished...\n" << r << " edges removed.\n"
		<< mesh.number_of_edges() << " final edges.\n";
	std::ofstream os("C:/Users/10712/Desktop/test/1021/Model_simp.off");
	os << std::setprecision(15) << mesh;
	return 0;
	
}
```

## Environment

* Operating system (Windows 64 bits):
* Compiler:
* Release or debug mode:
* Specific flags used (if any):
* CGAL version:
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by MaelRL** [comment]
You should use the edge collapse visitor, see the following example: https://doc.cgal.org/latest/Surface_mesh_simplification/Surface_mesh_simplification_2edge_collapse_visitor_surface_mesh_8cpp-example.html.

The visitor functions are detailed in the concept, here: https://doc.cgal.org/latest/Surface_mesh_simplification/classEdgeCollapseSimplificationVisitor.html. You'll care in particular about the functions `OnCollapsing ()` as you can obtain the vertices being removed via the profile (https://doc.cgal.org/latest/Surface_mesh_simplification/classEdgeProfile.html) and `OnCollapsed()`, which will you give you the vertex kept.

As for the index of your vertices, you could simply assign it as a property to your mesh, see this example if you are using a surface_mesh: https://doc.cgal.org/latest/Surface_mesh/Surface_mesh_2sm_properties_8cpp-example.html.

**Comment by KeepFaithMe** [comment]
&nbsp; &nbsp; &nbsp; Thank you for your reply.I have another question that I want you can give me some advice.
&nbsp; &nbsp; &nbsp; https://doc.cgal.org/latest/Surface_mesh_simplification/index.html&nbsp;
&nbsp; &nbsp; &nbsp;According to the document:'the halfedge-collapse operation pulls&nbsp;v&nbsp;into&nbsp;w, eliminating&nbsp;e&nbsp;and leaving&nbsp;w&nbsp;in place'.According to&nbsp; your advice,using the edge collapse visitor,I can find the point v which have been removed,at the same time,and I also want to konw the point w(including index of w).Because of the&nbsp;&nbsp;slightly less accuracy,I can't find the&nbsp; point w by comparing the coordinate of X-Y-Z directly.
&nbsp; &nbsp; &nbsp;This question puzzled me for a long time.So if you have some idea,please tell me,thank you very much!
&nbsp; &nbsp; &nbsp;Looking forward to&nbsp; your reply!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Mael"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月21日(星期一) 下午3:54
收件人:&nbsp;"CGAL/cgal"<cgal@noreply.github.com&gt;;
抄送:&nbsp;"张川"<1071244263@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [CGAL/cgal] How can I find the points which have been simplified when using the halfedge-collapse algorithm? (#4305)




You should use the edge collapse visitor, see the following example: https://doc.cgal.org/latest/Surface_mesh_simplification/Surface_mesh_simplification_2edge_collapse_visitor_surface_mesh_8cpp-example.html.
 
The visitor functions are detailed in the concept, here: https://doc.cgal.org/latest/Surface_mesh_simplification/classEdgeCollapseSimplificationVisitor.html. You'll care in particular about the functions OnCollapsing () as you can obtain the vertices being removed via the profile (https://doc.cgal.org/latest/Surface_mesh_simplification/classEdgeProfile.html) and OnCollapsed(), which will you give you the vertex kept.
 
As for the index of your vertices, you could simply assign it as a property to your mesh, see this example if you are using a surface_mesh: https://doc.cgal.org/latest/Surface_mesh/Surface_mesh_2sm_properties_8cpp-example.html.

**Comment by MaelRL** [comment]
The edge collapse does not necessarily collapse onto `w` : the vertex `w` is kept, but its position is changed according to the placement policy (see https://doc.cgal.org/latest/Surface_mesh_simplification/index.html#title2) that you have chosen, for example it might be moved to the midpoint of the edge.

If you use the visitor above, you get the information you desire: `v` and `w` are edge_profile.v0() and  edge_profile.v1(), and the vertex kept is a parameter of `OnCollapsed()`.

**Comment by KeepFaithMe** [comment]
Thank you for your reply! I have another question,in CGAL,which simplification algorithm is used,edge collapse or halfedge collapse? The user document show: ‘This package uses the halfedge-collapse operation, which is implemented by removing, additionally, 1 vertex (v) and 2 edges, one per adjacent triangle. It optionally moves the remaining vertex (w) into a new position, called placement, in which case the net effect is the same as in the edge-collapse operation.’.Reading this words aboved,I think the simplification algorithm is halfedge collapse,but the result we get is similar to the edge collapse.I don’t know if I understand that correctly! Sorry to bother you again, but I really need your help，thank you very much again! ------------------ 原始邮件 ------------------
发件人: "Mael"<notifications@github.com>
发送时间: 2019年10月21日(星期一) 下午5:52
收件人: "CGAL/cgal"<cgal@noreply.github.com>;
抄送: "KeepFaithMe"<1071244263@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [CGAL/cgal] How can I find the points which have been simplifiedwhen using the halfedge-collapse algorithm? (#4305)



The edge collapse does not necessarily collapse onto w : the vertex w is kept, but its position is changed according to the placement policy (see https://doc.cgal.org/latest/Surface_mesh_simplification/index.html#title2) that you have chosen, for example it might be moved to the midpoint of the edge.
 
If you use the visitor above, you get the information you desire: v and w are edge_profile.v0() and  edge_profile.v1(), and the vertex kept is a parameter of OnCollapsed().
 
&mdash;

**Comment by MaelRL** [comment]
It collapses edges, but the data structures are halfedge graphs.

**Comment by KeepFaithMe** [comment]
&nbsp; &nbsp;Thank for your reply!
&nbsp; &nbsp;Because of your help,I have some idea,but I also have some problem.According to you advice,through the function OnCollapsing(),we can get the two points which had been removed,and through the function OnCollapsed(),we can get the points which kept.So,based on the knowledeg aboved and the example of 'edge_collapse_surface_mesh.cpp',I made a small change,in the struct of My_visitor,I set a container std::vector<vertex_descriptoe&gt;removePoint,in the function OnCollapsing,I use this container 'removePoint' to record the points v0 and v1:'removePoint.push_back(profile.v0()),removePoint.push_back(profile.v1());',but when the function main is done,the size of container is 0.So I am quzzled.Maybe I have something wrong,but I don't konw what went wrong.If you know about this,please give me some advice.Thank you again!
&nbsp; &nbsp;Attached is my code:
&nbsp; &nbsp;void OnCollapsing(Profile const&amp; profile
		, boost::optional<Point&gt;&nbsp; placement
	)
	{
		
		removePoint.push_back(profile.v0());
		removePoint.push_back(profile.v1());
		if (!placement)
			++stats-&gt;placement_uncomputable;
	}
&nbsp; &nbsp; &nbsp; size_t size = vis.removePoint.size();
&nbsp; &nbsp; &nbsp; In the main function,the size is zero!
------------------ 原始邮件 ------------------
发件人:&nbsp;"Mael"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月21日(星期一) 晚上6:34
收件人:&nbsp;"CGAL/cgal"<cgal@noreply.github.com&gt;;
抄送:&nbsp;"张川"<1071244263@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [CGAL/cgal] How can I find the points which have been simplified when using the halfedge-collapse algorithm? (#4305)




It collapses edges, but the data structures are halfedge graphs.

**Comment by MaelRL** [comment]
Please provide the full code and data on a gist (https://gist.github.com/).

**Comment by KeepFaithMe** [comment]
&nbsp; &nbsp; &nbsp;Thank you for your reply!
&nbsp; &nbsp; &nbsp;The data and code have been upload to the gist,&nbsp;https://gist.github.com/KeepFaithMe/3c1f6e1c1797f00407e72b4b602b37cf
&nbsp; &nbsp; &nbsp;looking forward to your reply!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Mael"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月22日(星期二) 下午2:56
收件人:&nbsp;"CGAL/cgal"<cgal@noreply.github.com&gt;;
抄送:&nbsp;"张川"<1071244263@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [CGAL/cgal] How can I find the points which have been simplified when using the halfedge-collapse algorithm? (#4305)




Please provide the full code and data on a gist (https://gist.github.com/).

**Comment by KeepFaithMe** [comment]
&nbsp;I just edited my code.Now through the function 'OnCollapse()' ,I can get some points,but when I search the&nbsp; one point we got in the data file, there is no points in the data file that can match this point I got through the function 'OnCollapse'.I am so quezzled. At the same time,I have another question,How can I get the new point r,It's just like r point on the document:'edge-collapse&nbsp;while the other is known as&nbsp;halfedge-collapse. Given an edge&nbsp;e&nbsp;joining vertices&nbsp;w&nbsp;and&nbsp;v, the edge-collapse operation replaces&nbsp;e,w&nbsp;and&nbsp;v&nbsp;for a new vertex&nbsp;r'. I read this doucment&nbsp;https://doc.cgal.org/latest/Surface_mesh_simplification/classEdgeProfile.html#a3fee481d937c642db96cea4926a581ec&nbsp;.There is no content that tell me how can I get this 'r point'?
The data and code is upload to&nbsp;https://gist.github.com/KeepFaithMe/3c1f6e1c1797f00407e72b4b602b37cf
Looking forward to your reply.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Mael"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月22日(星期二) 下午2:56
收件人:&nbsp;"CGAL/cgal"<cgal@noreply.github.com&gt;;
抄送:&nbsp;"张川"<1071244263@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [CGAL/cgal] How can I find the points which have been simplified when using the halfedge-collapse algorithm? (#4305)




Please provide the full code and data on a gist (https://gist.github.com/).

**Comment by MaelRL** [comment]
The documentation says:
```
void | OnCollapsed (const Profile&, const Profile::vertex_descriptor vd)
> Called when an edge has been collapsed and replaced by the vertex vd
```
The point kept is `mesh.point(vd)`, not the `edge_profile.p0()` and `edge_profile.p1()`; these are the two points of your edge that has just been removed.

**Comment by KeepFaithMe** [comment]
&nbsp; &nbsp; Thank you for your reply!
&nbsp; &nbsp; After listening to your suggestions,I have&nbsp; understanding of the process of surface mesh simplification a liitle.But I still have a question.Through&nbsp;profile.p0()and&nbsp;profile.p1(),I can get the removed points,and through the 'void  OnCollapsed (const Profile&amp;, const Profile::vertex_descriptor vd)',the point kept is mesh.point(vd) which I can get.Is there a correspondence(relationship) here?
    For example, there are two points w and v,one edge.When the simplification process starts,first,the function OnCollpasing() has been called,and I can get the point w and v which have been removed,next when the function OnCollpasing() finished,the function OnCollpased() has been called,through this function I can get the new point r which is kept.So when I record the points w v r,I can find the w and v through the r according to the order of the records.I don't know if I understand that correctly?
    Looking forward to your reply!thak you again!
    Good Luck!


&nbsp; &nbsp; &nbsp;&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Mael"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月22日(星期二) 晚上6:36
收件人:&nbsp;"CGAL/cgal"<cgal@noreply.github.com&gt;;
抄送:&nbsp;"张川"<1071244263@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [CGAL/cgal] How can I find the points which have been simplified when using the halfedge-collapse algorithm? (#4305)




The documentation says:
 void | OnCollapsed (const Profile&amp;, const Profile::vertex_descriptor vd) &gt; Called when an edge has been collapsed and replaced by the vertex vd  
The point kept is mesh.point(vd), not the edge_profile.p0() and edge_profile.p1(); these are the two points of your edge that has just been removed.

**Comment by MaelRL** [comment]
I am not sure I understand your question.

Edge collapse uses internally the following function : https://doc.cgal.org/latest/BGL/group__PkgBGLEulerOperations.html#ga5d15eb83f797b8f91e23e8e9ceec78c9, which should give you some good information about what happens from a combinatorics point of view.

The vertices 'w' and 'v' are the source and target of the edge 'e'. With recent changes, we ensure that the vertex being kept is the target of the edge that was removed.

Does this help to clarify ?

**Comment by KeepFaithMe** [comment]
&nbsp; &nbsp; &nbsp;Thank you for your reply again!
&nbsp; &nbsp; &nbsp; According to the reference doucment you gave me,I know that through the function 'OnCollapsing()'，I can get the removed points v and w,and through the function 'OnCollapsed()',I can get the kept points r.
&nbsp; &nbsp; &nbsp;There is a question in my mind.Through the function 'OnCollapsing()' and the parameter 'Profile const&amp; profile',the vertex_descriptor of the removed points is profile.v0() and profile.v1() which I can get.Through the function 'OnCollpased()' and the parameter "const Profile::vertex_descriptor vd",the vertex_descriptor of the kept points r is&nbsp; vd which I can get.So I want to ask you is that whether through vd0 I can get the profile.v0()and profile.v1(),and the point vd0 happens to be produced by point profile.v0() and point profile.v1().Whether there is such a correspondence？About this question,you can see the accessory I uploaded.
&nbsp; &nbsp; Another question is the vertex_descriptor vd of the kept point r is new or is one of the&nbsp; points(v or w) removed?
&nbsp; &nbsp; Aboved question I asked is important for me,So please give me some advice! thank you again!
&nbsp; &nbsp; the codes you can see&nbsp;https://gist.github.com/KeepFaithMe/6209be67873d1ff5952b2d89e2f94162.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Mael"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月28日(星期一) 凌晨2:12
收件人:&nbsp;"CGAL/cgal"<cgal@noreply.github.com&gt;;
抄送:&nbsp;"张川"<1071244263@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [CGAL/cgal] How can I find the points which have been simplified when using the halfedge-collapse algorithm? (#4305)




I am not sure I understand your question.
 
Edge collapse uses internally the following function : https://doc.cgal.org/latest/BGL/group__PkgBGLEulerOperations.html#ga5d15eb83f797b8f91e23e8e9ceec78c9, which should give you some good information about what happens from a combinatorics point of view.
 
The vertices 'w' and 'v' are the source and target of the edge 'e'. With recent changes, we ensure that the vertex being kept is the target of the edge that was removed.
 
Does this help to clarify ?
