### ISSUE TITLE
Compilation gets stuck with Intel C++ compiler and flag -Wshadow

### ISSUE THREAD

**Issue by ca36xymo** [CGAL/cgal#4307]
## Issue Details

Programs that include certain CGAL headers can not be compiled with the Intel C++ compiler when using flag `-Wshadow`. The compilation stalls without showing any further error message.

## Source Code
The following code compiles with `icpc test.cpp -lCGAL -I/usr/local/include` but stalls during compilation with `icpc test.cpp -lCGAL -I/usr/local/include -Wshadow`.

```
#include <CGAL/Nef_polyhedron_3.h>

int main() {}
```

Other CGAL headers observed to stall compilation are e.g. `CGAL/Exact_predicates_exact_constructions_kernel.h` and `CGAL/convex_decomposition_3.h`.

## Environment

The issue has been observed on Ubuntu 18.04 with Intel C++ compiler versions 17,18 and 19. CGAL 4.13.1 and 4.14.1 were built manually (using above mentioned Intel compilers) and are both subject to this issue. Other versions of CGAL have not been tested.

The issue has not been observed with GCC and flag `-Wshadow`.

**Comment by mglisse** [comment]
Please report bugs in Intel's compiler to Intel. Note that this isn't one of the compilers that CGAL officially supports.

**Comment by ca36xymo** [comment]
Dear developers,
Thanks for the quick responses.

You are right, opposed to my initial thoughts, the issue is not related to the CGAL library. After some more debugging and problem reduction, I found it to occur when using certain functionality from `boost/operators`.

@afabri
I am one of the developers of the open source software framework [waLBerla](https://www.walberla.net). Since the framework's main focus is massivelly parallel computing, we want to ensure support for all major compilers found on modern supercomputers.

**Comment by afabri** [comment]
@ca36xymo where does CGAL come in at walBerla?  Did you write user code that you want to compile and run on the platform? Would be nice if we could put a link on such user code on the page [Projects Using CGAL ](https://www.cgal.org/projects.html)

**Comment by lrineau** [comment]
I have found the merge-request that introduces CGAL in waLBerla:
https://i10git.cs.fau.de/walberla/walberla/merge_requests/159.

**Comment by ca36xymo** [comment]
@afabri We are very grateful for CGAL and you can point to our project on your webpage, of course.

**Comment by afabri** [comment]
But do you tell somewhere on your pages what of CGAL you use to achieve what?

**Comment by lrineau** [comment]
@afabri The work is currently ongoing, in a merge-request: https://i10git.cs.fau.de/walberla/walberla/merge_requests/159.

**Comment by ca36xymo** [comment]
Indeed, the work is currently still ongoing and not officially available on our master branch.

Just for your information, I have meanwhile opened a [thread](https://software.intel.com/en-us/forums/intel-c-compiler/topic/831219) in the Intel C++ compiler forum regarding this issue.

Thanks again for your helpful feedback.
