### ISSUE TITLE
Wrong interval multiplication with NaN

### ISSUE THREAD

**Issue by mglisse** [CGAL/cgal#4312]
## Issue Details

The following program prints
> [nan;-nan]

instead of
> [-inf;inf]

This issue seems to have been present for many years, possibly since the introduction of intervals in CGAL. `[0,0]*[1,inf]` also has a NaN.

In master, the new SSE code is also affected by this issue, but the set of inputs that cause problems is a bit different (larger?) because of NaNs appearing in intermediate computations. In particular, `[1,INFINITY]*[0,1]` gives [1;inf]. This can only happen if 0 is an extremity of one interval and ±inf of the other. I think that only multiplication is affected, although I would need to double-check division.

It would have been super convenient for interval arithmetic if IEEE-754 had defined 0*inf as ±inf when the rounding mode is towards ±inf, but they defined it as NaN for all rounding modes, so we have to handle it somehow. (Intel's maxpd's handling of NaN is also a bit strange, but I don't think any behavior of max could fix what multiplications produce).

As an experiment, I created [a branch](https://github.com/mglisse/cgal/tree/Number_types-interval_NaN-glisse) where I check the floating point environment to know if any NaN appeared. For my favorite example, the simple_2 benchmark in Triangulation_3 with structural and static filters disabled, the running time in 4.14 was 1.6s, the current master is 0.87s, and the branch increases it to 0.93s (on a nice Xeon processor). Significant, but it does not kill the benefits of SSE. Note that the branch is not ready. Setting/clearing exception flags is not done cleanly, and the non-SSE path is still as broken as in 4.14. Also, this is only one approach, others are possible (I have some ideas I want to try).

The problem was reported to me by @MaelRL .

## Source Code

```c++
#include <CGAL/Interval_nt.h>
#include <iostream>
typedef CGAL::Interval_nt<> IA;
int main(){
  std::cout << IA(0) * IA::largest() << '\n';
}
```

**Comment by mglisse** [comment]
[Another branch](https://github.com/mglisse/cgal/tree/Number_types-interval_NaN2-glisse). This one is a bit slower (0.95) but simpler. Again, it only affects the SSE path.

**Comment by lrineau** [comment]
I do not think that issue should block the release. It seems the bug was already in CGAL for a long time, and the branch does not fix it fully (because of the non-SSE path).
