### ISSUE TITLE
Polyhedron demo: 2-color mode for point set & mesh

### ISSUE THREAD

**Issue by palliez** [CGAL/cgal#4320]
I suggest to add the following feature to the demo: a 2-material/color rendering mode for meshes or point sets, such that we can eg view each point as grey if front-facing, and green otherwise. Same for surface meshes. Colors can be combined with shading when using the ColorMaterial option: https://www.khronos.org/registry/OpenGL-Refpages/gl2.1/xhtml/glColorMaterial.xml

The goal is to ease the interactive orientation of point sets & meshes.

Pierre

**Comment by maxGimeno** [comment]
I fear that point-sets are always front-facing...
