### ISSUE TITLE
The OFF loader  loads directly in the mesh if able, but the OBJ loader always go through a soup, that is then oriented.

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#4332]
@sloriot It is because the OFF loader  loads directly in the mesh if able, but the OBJ loader always go through a soup, that is then oriented.

_Originally posted by @maxGimeno in https://github.com/CGAL/cgal/issues/4331#issuecomment-548250843_

**Comment by sloriot** [comment]
Is there any reason for that? if not I suggest we have the same logic than for OFF

**Comment by maxGimeno** [comment]
Yes, the reason is that I am quite sure there is no loader for OBJ that constructs directly a pmesh in master. There is one in my CGAL_IO branch though.

**Comment by sloriot** [comment]
Right  and since `is_polygon_soup_a_polygon_mesh()` returns `false` for a non-manifold vertex then orient is called. Shouldn't be the OBJ loaded as a soup then?

**Comment by sloriot** [comment]
Fine with me but it should be the case for everybody (STL, OFF, OBJ, PLY, ...) to be consistent which might be more work than your solution (which I agree is nicer).

**Comment by maxGimeno** [comment]
It's probably going to be copy pasting the solution for OBJ. IIRC they all act like OBJ does, except for OFF.

**Comment by sloriot** [comment]
Well instead of copy-pasting, you could have a function responsible for creating either a soup or a mesh that would be called by the loaders (which is probably what you already had in mind).
