### ISSUE TITLE
Linker-error with vcpkg and Gmp

### ISSUE THREAD

**Issue by McRaichu** [CGAL/cgal#4339]
## Issue Details

I'm trying to use CGAL (header only) from vcpkg and I get linker errors for Gmp.

```
- error LNK2019: unresolved external symbol __gmpq_clear referenced in function "public: __cdecl CGAL::Gmpq_rep::~Gmpq_rep(void)" 
- error LNK2019: unresolved external symbol __gmpq_cmp referenced in function "public: bool __cdecl CGAL::Gmpq::operator<(class CGAL::Gmpq const &)const " 
- error LNK2019: unresolved external symbol __gmpq_equal referenced in function "public: bool __cdecl CGAL::Gmpq::operator==(class CGAL::Gmpq const &)const " 
- error LNK2019: unresolved external symbol __gmpq_init referenced in function "public: __cdecl CGAL::Gmpq_rep::Gmpq_rep(void)"
- error LNK2019: unresolved external symbol __gmpq_set_d referenced in function "public: __cdecl CGAL::Gmpq::Gmpq(double)" 
- error LNK2019: unresolved external symbol __gmpn_add_n referenced in function __gmpn_add
- error LNK2019: unresolved external symbol __gmpn_mul referenced in function "struct CGAL::Mpzf __cdecl CGAL::operator*(struct CGAL::Mpzf const &,struct CGAL::Mpzf const &)" 
- error LNK2019: unresolved external symbol __gmpn_neg_n referenced in function "private: static struct CGAL::Mpzf __cdecl CGAL::Mpzf::aors(struct CGAL::Mpzf const &,struct CGAL::Mpzf const &,int)" 
- error LNK2019: unresolved external symbol __gmpn_sub_n referenced in function __gmpn_sub
- error LNK2019: unresolved external symbol __gmpn_copyi referenced in function "public: __cdecl CGAL::Mpzf::Mpzf(struct CGAL::Mpzf const &)"
```

It seems Gmp is not a dependency of the vcpkg (no lib-file found). I built CGAL separatly to get the libgmp-10.lib and added that one to my vs-project. This removed all but this linker error:
- error LNK2019: unresolved external symbol __gmpn_neg_n referenced in function "private: static struct CGAL::Mpzf __cdecl CGAL::Mpzf::aors(struct CGAL::Mpzf const &,struct CGAL::Mpzf const &,int)" 

Any help would be appreciated.

## Source Code

Include-list:
```
#define CGAL_HEADER_ONLY 1
#include <CGAL\Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL\Delaunay_triangulation_2.h>
#include <CGAL\Constrained_Delaunay_triangulation_2.h>
#include <CGAL\Triangulation_vertex_base_with_info_2.h>
#include <CGAL\Triangulation_face_base_with_info_2.h>
```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows 10 64bit
* Compiler: Visual Studio 2017 (Toolset v141)
* Release or debug mode: Debug
* Specific flags used (if any):
* CGAL version: 1.14.1
* Boost version: 1.68
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by lrineau** [comment]
(In `vcpkg` package dependencies,  GMP is replaced my MPIR, a fork of GMP, but I think that is off-topic for your case.)

I see that you have added libgmp-10.lib to your project. If you have linker errors, it might be because your are creating a x86_64 project (64 bits) where your GMP was for i686 (32 bits), or the reverse. You can please check?

**Comment by McRaichu** [comment]
The problem was my fault. I screwed up my project settings and it found the libs (another copy) in another folder.
Based on your comment I checked my ´vcpkg´ and found out the installation of mpir failed (still don't know why). That's why I tried to fix gmp in the first place. That is now fixed and CGAL links against mpir. Thank you.
