### ISSUE TITLE
Define VS_STARTUP_PROJECT

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#4342]
## Issue Details

Setting  [VS_STARTUP_PROJECT](https://cmake.org/cmake/help/v3.6/prop_dir/VS_STARTUP_PROJECT.html)  would be nice.

**Comment by lrineau** [comment]
That looks nice. But `ALL_BUILD` seems a nice default startup project. To which target would you set that property?

**Comment by afabri** [comment]
You cannot run it.

**Comment by lrineau** [comment]
`examples/Triangulation_2/` for example has 20 targets. Which one would you choose? At least `ALL_BUILD` builds all targets, even if it cannot be run.
