### ISSUE TITLE
Use Github actions to deploy our web site, instead of DeployHQ

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#4343]
## Issue Details

With the new repository https://github.com/CGAL/cgal-web, the automatic deployments of `upcoming` and `master` to `upcoming.cgal.org` and `www.cgal.org` are broken.

I think we should now use Github actions, for such a deployment. There are even predefined actions for that.

@maxGimeno Please prepare Github action steps that run jekyll on our branches `upcoming` and `master`, and then create artifacts. For the actuel deployment, we will setup it with ssh keys together.

Cc: @sloriot

**Comment by lrineau** [comment]
@maxGimeno This is actually urgent, because I do not know how to update the web site, now. If I want to publish 4.14.2 and 5.0, I need that.

**Comment by lrineau** [comment]
@maxGimeno That is a task for you: we should use Github Actions, instead of DeployHQ. In CGAL/cgal-web, for each push event to `upcoming` or `master`, Github Actions should run Jekyll, and then push to our web site.

**Comment by sloriot** [comment]
@maxGimeno any update on this?

**Comment by maxGimeno** [comment]
@sloriot nope

**Comment by lrineau** [comment]
## Status Report

The workflow is created: https://github.com/CGAL/cgal-web/pull/12

Now we are evaluating the possibility to deploy the web site directly using `ssh` and `rsync`.  See the experiment at https://github.com/SaillantNicolas/cgal-web/blob/deploy_ssh/.github/workflows/Receive_PR.yml.

**Comment by lrineau** [comment]
@MaelRL @afabri Do you still want to restore the behavior of the `upcoming` branch, with https://upcoming.cgal.org/?

As far as I know, that is the last missing feature.
