### ISSUE TITLE
How to download the latest document?

### ISSUE THREAD

**Issue by Micalson** [CGAL/cgal#4348]
Hello, thank you for your contribution.  I want to download the latest document of CGAL for easy reading, and how to get it? Thank you for your reply.

Regards,

**Comment by MaelRL** [comment]
Do you mean the documentation? If so, you can download it on the [Releases](https://github.com/CGAL/cgal/releases) page, within the "Assets" of your desired version. Documentation archives are called `...doc_html...` (e.g. `CGAL-4.14-doc_html.tar.xz`).

**Comment by Micalson** [comment]
Is there a PDF version? Or could you tell me how to convert it to PDF version? 
Thank you for your reply.

Regards,

**Comment by sloriot** [comment]
We are no longer shipping PDF versions of the documentation.

**Comment by lrineau** [comment]
[**@sloriot**](https://github.com/sloriot) commented on [Nov 8, 2019, 9:13 AM GMT+1](https://github.com/CGAL/cgal/issues/4348#issuecomment-551429392 "2019-11-08T08:13:25Z - Replied by Github Reply Comments"):
> We are no longer shipping PDF versions of the documentation.

Let me add that, at the time we stopped creating the PDF version of the manual, the size of it was about 3000 pages!
