### ISSUE TITLE
Boolean_set_operations_2/sequence.cpp example fails when EPICK

### ISSUE THREAD

**Issue by vanlankveldthijs** [CGAL/cgal#4349]
## Issue Details

Joining polygon Q in example Boolean_set_operations_2/sequence.cpp throws precondition failure when using EPICK instead of EPECK.
Note that this example only uses simple linear line-segment polygons, so EPICK seems appropriate.

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Ubuntu 18.04.3 LTS
* Compiler: gcc
* Release or debug mode: Debug
* Specific flags used (if any): -
* CGAL version: 4.11-2build1 (apt-get newest version)
* Boost version: 1.65.1.0ubuntu1
* Other libraries versions if used (Eigen, TBB, etc.): -

**Comment by sloriot** [comment]
Hi Thijs! you need exact constructions for doing Boolean operations so it is expected not to work with EPICK. Note that even the do-intersect for polygons that is based on arrangement requires exact constructions (at least for the moment).

**Comment by thijsvanlankveld** [comment]
Hey Sebastien, That's unfortunate, especially for the non-general
polygon sets. I guess I can put something together myself based on a CDT
then :-)

I didn't see the EPECK restriction mentioned in the manual. Did I miss it,
or is it not mentioned?

**Comment by efifogel** [comment]
The decision whether to use EPEC or EPEC solely has to do with whether
constructions of geometric objects occurs during the computation.
The union of two polygons may result with a polygon that has new points, so
surely you need EPEC.
Indeed, all the examples all use EPEC, and for a good reason.

Sebastien mentioned that the do-intersect() operation also needs EPEC, even
though the result (either true or false) has nothing to do with
constructions of geometric objects.
However, intermediate results (which are discarded) do include new
geometric objects, and I guess this should be explicitly indicated, until
the situation is reverted...

   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by vanlankveldthijs** [comment]
Thanks for the detailed explanation. I understand that there are good reasons for the restriction to EPEC. I originally hoped that these intersections could be constructed similar to the intersections created by Constrained_traingulation_2 with the Exact_predicates_tag intersection tag.

While you convinced me that EPEC is required, I feel like this should be mentioned in the user manual and/or reference manual.

Sorry for continuing this closed thread...
