### ISSUE TITLE
Boost error when including polygon_mesh_processing

### ISSUE THREAD

**Issue by taus** [CGAL/cgal#435]
I just updated from the 4.7 beta to 4.7 release. After updating i get the following error when including CGAL/polygon_mesh_processing.h : 

    C2664 'boost::type_traits::no_type boost::detail::has_member_function_finish_edge_detail_hcmf<BOOST_TTI_DETAIL_TP_T>::chkt<has_member_function_finish_edge_detail_hcmf<BOOST_TTI_DETAIL_TP_T>::cl_type<BOOST_TTI_DETAIL_TP_T>::type>(...)':
    cannot convert argument 1 from 'nullptr' to '...' CGALWrapper D:\Development\CORTIME\3rdParty\boost_1_59_0\boost\graph\depth_first_search.hpp

This happens even if have an entirely empty c++ project that does nothing but include polygon_mesh_processing.h.

As mentioned, this did not happen in the 4.7 beta. I am compiling using Visual studio 2015 and using boost 1.59

**Comment by sloriot** [comment]
This seems to indicate a problem with boost and Visual studio 2015. Could you try if including `<boost\graph\depth_first_search.hpp>` only produces the same error?

**Comment by taus** [comment]
It seems you are correct. Additionally i found that the error only occurs when using C++Cli and not when using unmanaged C++. 

a bit unrelated, orient_polygon_soup.h seems to miss an `#include <vector>`

**Comment by kapsl** [comment]
Did anybody find a solution for that till now?
