### ISSUE TITLE
Polygon mesh processing / corefinement mesh union and intersection demo not running on some meshes (infinite loop?)

### ISSUE THREAD

**Issue by Igiteverything** [CGAL/cgal#4360]
## Issue Details

Running the corefinement_mesh_union_and_intersection demo from the Polygon mesh Processing package runs in general, however,  on some meshes it does not provide ANY result and maybe is stuck in an infinite loop (in release version 4.14). No error message is generated, it just seems to be running forever.

can be reproduced running release version with
corefinement_mesh_union_and_intersection mesh_A.off mesh_B.off

with the attached meshes

-----

Also, running in debug mode, I get different error messages whether I run 
corefinement_mesh_union_and_intersection_cgal_debugv4_14 mesh_A.off mesh_B.off
or
corefinement_mesh_union_and_intersection_cgal_debugv4_14 mesh_B.off mesh_A.off

(note arguments inversed)

In debug mode, error messages are:

corefinement_mesh_union_and_intersection_cgal_debugv4_14 mesh_A.off mesh_B.off 
terminate called after throwing an instance of 'CGAL::Assertion_exception'
  what():  CGAL ERROR: assertion violation!
Expr: res!=boost::none
File: <...>/cgal/cgal-master/Kernel_23/include/CGAL/Kernel/function_objects.h
Line: 1696
Aborted (core dumped)

-------------

corefinement_mesh_union_and_intersection_cgal_debugv4_14 mesh_B.off mesh_A.off 
terminate called after throwing an instance of 'CGAL::Assertion_exception'
  what():  CGAL ERROR: assertion violation!
Expr: oxz_pqr != COLLINEAR
File: <...>/cgal/cgal-master/Cartesian_kernel/include/CGAL/predicates/kernel_ftC3.h
Line: 197
Aborted (core dumped)

## Environment

* Operating system Linux, x86_64, RHEL 
* Compiler: GNU 7.1.0
* Release or debug mode: Release and debug
* Specific flags used (if any): 
* CGAL version: 4.14
* Boost version: 1.53.0
* Other libraries versions if used (Eigen, TBB, etc.): eigen version 3.3.4

[cgal_bug_meshes.zip](https://github.com/CGAL/cgal/files/3842661/cgal_bug_meshes.zip)

**Comment by sloriot** [comment]
One of the Input mesh has some self-intersection, which breaks the [documented](https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__corefinement__grp.html#gad7e1741a7ce41a5846cf86494982ca8b) precondition.

If you set the named parameter `throw_on_self_intersection` to true, self-intersection will be check in the neighborhood of the intersection of the meshes and an exception will be thrown.
