### ISSUE TITLE
The method to export normals is missing.

### ISSUE THREAD

**Issue by simonasdmd** [CGAL/cgal#4361]
_Please use the following template to help us solving your issue._

## Issue Details

_Describe your issue. Please be specific (compilation error, runtime error, unexpected behavior, wrong results, etc.)._

The method to export normals is missing.
## Source Code
I read an obj file without normals. I want to compute normals and export obj files with normals.

But I used "compute_vertex_normals.". No normals were obtained. I don't know how to export normals.

I found that writer only supports exporting vertices and vertex indexes.

![image](https://user-images.githubusercontent.com/42527845/68834820-a4345700-06f1-11ea-8eda-451191b1484d.png)

I used "add property map". However, the properties added from the view line in the picture did not succeed.
![image](https://user-images.githubusercontent.com/42527845/68835645-80721080-06f3-11ea-80b5-768e8e0a08e1.png)

_If your issue arises by using CGAL in your own source code, please provide a minimalist example that we can compile easily to reproduce the bug. If your issue arises from using a CGAL program (demo, example, etc.), please let us know which one. Helping you solving an issue is much easier and efficient if we can reproduce it._

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):windows 64
* Compiler: vs2017
* Release or debug mode: release
* Specific flags used (if any):
* CGAL version: 4.14
* Boost version:1.70
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by maxGimeno** [comment]
Try calling your map "v:normal" instead of "vn_", that's the name the writer looks for when it is writing the OBJ.

**Comment by simonasdmd** [comment]
@maxGimeno 
I did. But it still hasn't been added.
![image](https://user-images.githubusercontent.com/42527845/70587527-1de23680-1c05-11ea-8ac7-a1e5a786140d.png)

**Comment by sloriot** [comment]
@maxGimeno AFAIS there is no writing of normal in OBJ using `v:normal`, so I think this is not implemented.

**Comment by simonasdmd** [comment]
@sloriot 
Hello. I want to know if CGAL currently supports calculating new normals and exporting them after simplifying the mesh?

**Comment by maxGimeno** [comment]
@sloriot [right here](https://github.com/CGAL/cgal/blob/master/Surface_mesh/include/CGAL/Surface_mesh/IO.h#L430)
