### ISSUE TITLE
Polyhedron demo: crash during saving

### ISSUE THREAD

**Issue by palliez** [CGAL/cgal#4365]
_Please use the following template to help us solving your issue._

## Issue Details

on windows 10, demo CGAL version 5-I-144, the demo crashes (and terminates) when I try to save a point set after applying an affine transform to it.

**Comment by maxGimeno** [comment]
What extension are you trying to use for saving ?

**Comment by palliez** [comment]
it crashes for both ply and xyz.
I just applied a scaling by 10 for z-coordinates, then cannot save anymore.

**Comment by maxGimeno** [comment]
I don't reproduce. Is it possible that you are trying to save the transformation item instead of the point_set item ? If so it should pop a warning and not crash though... How many points is there in your PS ?

**Comment by palliez** [comment]
nope - I just save the point set.
I have 125K points.
here is the file: https://filesender.renater.fr/?s=download&token=d771ce79-0a0e-1b98-5ddf-9f8ae41f5b62
try scaling it in z by a factor 10
then save it..

**Comment by maxGimeno** [comment]
I really don't reproduce...

**Comment by sloriot** [comment]
what version of the demo do you have?

**Comment by maxGimeno** [comment]
I have the latest master, but I don't remember anything about that kind of bug around September...

**Comment by sloriot** [comment]
I meant @palliez

**Comment by palliez** [comment]
hi all,

I am using the latest demo (downloaded from the doc page): 5.0-I-184.
I am running it on windows 10.

I made a small movie (animated gif) to illustrate the [bug:](https://filesender.renater.fr/?s=download&token=50f4058e-331d-3f20-9de8-b6ec262f4829)

I load a point set -> ok
I can compute something on it, eg convex hull
then I rescale it
when I compute the convex hull on it I get 0 vertices
when I save the point set I get a crash (exit).

in general the demo is always in a bad state after rescaling - I cannot do anything with the transformed point set.

Pierre

**Comment by maxGimeno** [comment]
Ok, i reproduce from your video. The key operation that you forgot to mention is that you delete the original item. 
@sgiraudot and I are looking into it.

**Comment by lrineau** [comment]
Fixed by #4437.
