### ISSUE TITLE
Warning C4244 with Point_set_3 and float kernel on MS Visual Studio

### ISSUE THREAD

**Issue by elombardi2** [CGAL/cgal#4367]
## Issue Details

Compiling a code using Point_set_3 with a float kernel triggers several "warning C4244:  conversion from 'const double' to 'const float' ..." warnings on MS Visual Studio.

The warnings come from [this line](https://github.com/CGAL/cgal/blob/55a05c5a23c1a5721f8cba3a7b5485b9a1f2f663/Point_set_3/include/CGAL/Point_set_3.h#L322) and [this line](https://github.com/CGAL/cgal/blob/55a05c5a23c1a5721f8cba3a7b5485b9a1f2f663/Point_set_3/include/CGAL/Point_set_3.h#L852). Changing the `0.` into `0.f` turns off the warning, but is not a global fix (works only with a float or a double kernel).

## Source Code
```
#include <CGAL/Cartesian.h>
#include <CGAL/Point_set_3.h>

using Kernel = CGAL::Cartesian< float >;
using Point = Kernel::Point_3;

int main(void)
{
	CGAL::Point_set_3< Point > ps;
	return 0;
}
```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows 10 64bits
* Compiler: MS Visual Studio 2015 & 2017
* Release or debug mode: both
* Specific flags used (if any):
* CGAL version: 4.14.1
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by gdamiand** [comment]
Maybe we need to replace all occurrences of Point (0., 0., 0.) by CGAL::Origin and Vector(0., 0., 0.) by CGAL::Null_vector ?

**Comment by sgiraudot** [comment]
One solution is to do something like `Point(FT(0),FT(0),FT(0))` but I find it quite heavy… I'll have a look into it, maybe `CGAL::Origin` is a good idea indeed.

**Comment by sloriot** [comment]
@sgiraudot would you have time to fix that?

**Comment by sgiraudot** [comment]
Sure, I'll look into it.
