### ISSUE TITLE
Improve autodetection of 3MF on Debian/Ubuntu

### ISSUE THREAD

**Issue by joachim-reichel** [CGAL/cgal#4369]
Autodetection of 3MF does not work on Debian/Ubuntu. This can be fixed by adding "PATHS /usr/include/lib3mf" after "NMR_DLLInterfaces.h" in Polyhedron/demo/Polyhedron/Plugins/IO/CMakeLists.txt.

**Comment by lrineau** [comment]
Fixed by #4370.
