### ISSUE TITLE
polygon mesh processing crash\access violation on example

### ISSUE THREAD

**Issue by amir90** [CGAL/cgal#4373]
Crash on example corefinement_mesh_union in polygon mesh processing. Mesh Input is fine, the crash occurs at somewhere in the boolean union function.

unfortunately, no exception or error message is thrown so I am not able to debug.

I followed the installation instructions and convex_hull_2 ch_timing example compiles and runs.

The example code:

```
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/Surface_mesh.h>
#include <CGAL/Polygon_mesh_processing/corefinement.h>
#include <fstream>

typedef CGAL::Exact_predicates_inexact_constructions_kernel K;
typedef CGAL::Surface_mesh<K::Point_3>             Mesh;

namespace PMP = CGAL::Polygon_mesh_processing;

int main(int argc, char* argv[])
{
  const char* filename1 = (argc > 1) ? argv[1] : "data/blobby.off";
  const char* filename2 = (argc > 2) ? argv[2] : "data/eight.off";
  std::ifstream input(filename1);

  Mesh mesh1, mesh2;
  if (!input || !(input >> mesh1))
  {
    std::cerr << "First mesh is not a valid off file." << std::endl;
    return 1;
  }
  input.close();
  input.open(filename2);
  if (!input || !(input >> mesh2))
  {
    std::cerr << "Second mesh is not a valid off file." << std::endl;
    return 1;
  }

  Mesh out;
  bool valid_union = PMP::corefine_and_compute_union(mesh1,mesh2, out); //crash here

  if (valid_union)
  {
    std::cout << "Union was successfully computed\n";
    std::ofstream output("union.off");
    output << out;
    return 0;
  }
  std::cout << "Union could not be computed\n";
  return 1;
}
```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows 64 bit
* Compiler: MSVC 2017 
* Release or debug mode: both
* Specific flags used (if any):
* CGAL version: 4.14.1
* Boost version: 1.71.0 
* Other libraries versions if used (Eigen, TBB, etc.): Eigen 3.3.7

**Comment by sloriot** [comment]
See my answer on [SO](https://stackoverflow.com/questions/58955179/cgal-polygon-mesh-processing-boolean-operations-crash).

**Comment by amir90** [comment]
I see, but the problem is that is crashes on the meshes given in the example, specifically in "blobby.off" and "eight.off", which should not have self intersections.

Additionally, I have tried installing cgal through vcpkg, but I get the same problem.

**Comment by sloriot** [comment]
I know there are some optimization issue with BOOST_FOREACH (internally used) with MSVC. Could you try using CGAL 5.0 instead?

**Comment by amir90** [comment]
Happy to say that it now works after cleaning some leftover system variables I defined when installing using the installer.

I have no idea what the problem was, but installing with vcpkg solved it.

Thank you for your time.
