### ISSUE TITLE
How to display the data of Point_set_3<Point_3>?

### ISSUE THREAD

**Issue by Micalson** [CGAL/cgal#4377]
Hello, thank you for your nice code. I have a problem:
I could use CGAL:draw() to display Surface_mesh data, and how could I display Point_set_3 data? 
Thank you for your reply.

Regards,

**Comment by sgiraudot** [comment]
You can draw `CGAL::Point_set_3` objects since CGAL 5.0, see https://doc.cgal.org/latest/Point_set_3/group__PkgDrawPointSet3D.html#ga3c245d15e8f7a2db7252fa450299e1bb.

**Comment by Micalson** [comment]
@sgiraudot I use CGAL 4.14.1,  and is this feature not supported in this release?

**Comment by gdamiand** [comment]
Draw for point sets was introduced in CGAL 5.0, thus does not exist in CGAL 4.14.1.

But I think the code should work (but I didn't tried thus there is no guarantee), thus you can try to copy the file draw_point_set_3.h and try it with your code 

( https://github.com/CGAL/cgal/blob/master/Point_set_3/include/CGAL/draw_point_set_3.h)

**Comment by Micalson** [comment]
I have tried it, and it doesn't work. 
In CGAL 5.0, could I draw the direction of normal like the following image?
![图片](https://user-images.githubusercontent.com/45941423/69767696-68e95c00-11b8-11ea-8762-0395e52cdbee.png)

Regards,

**Comment by Micalson** [comment]
@sgiraudot @gdamiand Any suggestions? Thank you

**Comment by gdamiand** [comment]
Copying the three following files

 GraphicsView/include/CGAL/Buffer_for_vao.h  GraphicsView/include/CGAL/Qt/Basic_viewer_qt.h  Point_set_3/include/CGAL/draw_point_set_3.h 

from master to CGAL 4.14.1 

works: I am able to use draw for point sets without problem.

**Comment by gdamiand** [comment]
The normal drawing is not (yet) included in the point set viewer; but this is probably easy to add (have a look into the file Point_set_3/include/CGAL/draw_point_set_3.h).

**Comment by Micalson** [comment]
@gdamiand Thank you for your reply. I will try it.
