### ISSUE TITLE
Polyhedron demo: ui_Polyhedron_demo_statistics_on_polyhedron_dialog.h not generated

### ISSUE THREAD

**Issue by sgiraudot** [CGAL/cgal#438]
When compiling the Polyhedron demo, I have the following error:

<code>Scene_polyhedron_item.h:20:64: fatal error: ui_Polyhedron_demo_statistics_on_polyhedron_dialog.h: Aucun fichier ou dossier de ce type</code>

But _Polyhedron_demo_statistics_on_polyhedron_dialog.ui_ does exist, so I guess maybe the H file is not generated soon enough by the CMakeLists?

**Comment by lrineau** [comment]
Fixed by #443
