### ISSUE TITLE
Build errors with CGAL/Aff_transformation_3.h in CGAL 4.14.2

### ISSUE THREAD

**Issue by hahnjo** [CGAL/cgal#4382]
## Issue Details

Build errors with CGAL 4.14.2 when including `CGAL/Aff_transformation_3.h`.

## Source Code

```c
#include <CGAL/Aff_transformation_3.h>
```

compiling with GCC 9.2.0:
```
In file included from test.cpp:1:
/usr/include/CGAL/Aff_transformation_3.h:86:6: error: ‘ostream’ in namespace ‘std’ does not name a type
   86 | std::ostream&
      |      ^~~~~~~
/usr/include/CGAL/Aff_transformation_3.h:30:1: note: ‘std::ostream’ is defined in header ‘<ostream>’; did you forget to ‘#include <ostream>’?
   29 | #include <CGAL/aff_transformation_tags.h>
  +++ |+#include <ostream>
   30 | 
/usr/include/CGAL/Aff_transformation_3.h:96:6: error: ‘istream’ in namespace ‘std’ does not name a type
   96 | std::istream&
      |      ^~~~~~~
/usr/include/CGAL/Aff_transformation_3.h:30:1: note: ‘std::istream’ is defined in header ‘<istream>’; did you forget to ‘#include <istream>’?
   29 | #include <CGAL/aff_transformation_tags.h>
  +++ |+#include <istream>
   30 |
```

## Environment

* Operating system: Arch Linux
* Compiler: GCC 9.2.0
* Release or debug mode: probably Release mode, using the prebuilt package https://www.archlinux.org/packages/community/x86_64/cgal/
* Specific flags used (if any): none
* CGAL version: 4.14.2
* Boost version: 1.71.0 (https://www.archlinux.org/packages/extra/x86_64/boost/)
* Other libraries versions if used (Eigen, TBB, etc.): none

## Further notes

The reason seems to be commit 856b7722f1038e333eb9a25e9f87a7b986d8f251 which fixes a typo in the macro name `BOOST_VERSION`. As a result, the header file `boost/container/flat_map.hpp` is not included anymore and doesn't pull in `std::istream` nor `std::ostream` anymore.
The correct solution is probably to include the headers mentioned by the compiler, or maybe `iosfwd` is enough.

**Comment by lrineau** [comment]
I am surprised that our CI checks have not caught that compilation error. ` <CGAL/Aff_transformation_3.h>` [is documented](https://doc.cgal.org/latest/Kernel_23/classCGAL_1_1Aff__transformation__3.html) and should have been checked.

**Comment by lrineau** [comment]
It was tested: https://travis-ci.org/CGAL/cgal/jobs/598003707#L6467

Strange.

**Comment by hahnjo** [comment]
It could be that this only happens with very recent versions of libstdc++ (from GCC 9): In the past releases they are reducing the number of transitively included headers, I've seen build failures in other projects as well.

**Comment by MaelRL** [comment]
@maxGimeno, this issue seems fixed (?).

**Comment by maxGimeno** [comment]
I have no idea. @lrineau removed the flag but did not close the issue, maybe it didn't work.

**Comment by sloriot** [comment]
I merged the PR and forgot to close the issue (I still don't understand what the text of the PR should contains so that it's done automatically after the merge).
