### ISSUE TITLE
some points convert to polyhedron_3?

### ISSUE THREAD

**Issue by KeepFaithMe** [CGAL/cgal#4386]
## Issue Details
Now I have some points,and I want to convert these points to the type of Polyhedron_3.These points are part of the mesh , and they can construct continuous faces.Yeap,I can convert these points to Surface_mesh,but using the same method,I can't convert these points to the type  of polyhedron_3.
So is there some doucment or example I can refer to.

**Comment by sloriot** [comment]
Sorry, but I don't understand what you want to do. Do you have some code showing what you  want do achieve?
