### ISSUE TITLE
Compilation error when using mpir instead of gmp

### ISSUE THREAD

**Issue by edisongustavo** [CGAL/cgal#439]
I'm trying to compile CGAL using Visual Studio 2010. I'm using MPIR version 2.6.0 and I get the following compilation error:

```
  f:\Miniconda64\conda-bld\work\cgal-releases-CGAL-4.7\Number_types\include\CGAL/GMP/Gmpzf_type.h(403): error C2664: '__gmpz_get_d_2exp' : cannot convert parameter 1 from 'CGAL::Gmpzf::Exponent *' to 'mpir_si *' [F:\Miniconda64\conda-bld\work\cgal-releases-CGAL-4.7\build\Installation\src\CGAL\CGAL.vcxproj]
  f:\Miniconda64\conda-bld\work\cgal-releases-CGAL-4.7\Number_types\include\CGAL/GMP/Gmpzf_type.h(414): error C2664: '__gmpz_get_d_2exp' : cannot convert parameter 1 from 'CGAL::Gmpzf::Exponent *' to 'mpir_si *' [F:\Miniconda64\conda-bld\work\cgal-releases-CGAL-4.7\build\Installation\src\CGAL\CGAL.vcxproj]
  f:\Miniconda64\conda-bld\work\cgal-releases-CGAL-4.7\Number_types\include\CGAL/GMP/Gmpzf_type.h(425): error C2664: '__gmpz_get_d_2exp' : cannot convert parameter 1 from 'long *' to 'mpir_si *' [F:\Miniconda64\conda-bld\work\cgal-releases-CGAL-4.7\build\Installation\src\CGAL\CGAL.vcxproj]
```

I found this e-mail on the cgal mailing list: http://cgal-discuss.949826.n4.nabble.com/compilation-error-in-CGAL-4-7-beta-1-in-VC2015-on-x64-Platform-td4661087.html.

Marc Glisse (@mglisse) in the e-mail states that:

>The problem is that MPIR broke compatibility with GMP (not necessarily for 
> bad reasons), it would work if you were using GMP. (Well, the original 
> problem is that Microsoft chose a weird LLP64 ABI instead of LP64 like 
> everyone else.) We will have to think of a workaround...

**Comment by lrineau** [comment]
The CGAL project does not support MPIR. We have never tried it.

Unless GeometryFactory has a request for MPIR from a customer, the support for MPIR will probably not added.

Why do you need MPIR? GMP cannot fit your needs?

**Comment by silentmissile** [comment]
GMP doesn't support windows, so we have to choose alternative solution which is MPIR now, but still troubles.

**Comment by lrineau** [comment]
Do you have issues on Windows using the GMP and MPFR precompiled libraires shipped with the CGAL Windows installer?

**Comment by silentmissile** [comment]
thank you, the precompiled binary file can help me to compile.

I'll continue to test the running of the files, if any issue, I'll apply a new issue.

**Comment by xantares** [comment]
a dirty hack is available here to use mpir:
https://github.com/conda-forge/cgal-feedstock/blob/master/recipe/cgal-mpir.patch

**Comment by mglisse** [comment]
@xantares Don't the VS builds of MPIR create a file gmp.h, in addition to mpir.h (for other builds, that requires `--enable-gmpcompat`)? Renaming all the includes seems wrong.

**Comment by xantares** [comment]
you're right, there's even a gmp library

**Comment by edisongustavo** [comment]
I wouldn't recommend this flag `--enable-gmpcompat`.

I had problems with it on the past, where you can't have both installed at the same time due to the `gmp.h` file.

**Comment by mglisse** [comment]
@edisongustavo Well, don't use it if you want to install GMP as well (in the same place), obviously. The name is pretty explicit that it is there for GMP compatibility, which is not as useful if you have the real GMP... My point was that for a client program that can use either GMP or MPIR, it makes sense to just include gmp.h and expect that to be available, either from the original GMP or through MPIR compatibility.

**Comment by edisongustavo** [comment]
@mglisse I understand that reasoning, however, as this issue here shows, the compatibility is not that great.
For example, I've worked together with @xantares to [patch the CGAL source](https://github.com/conda-forge/cgal-feedstock/blob/master/recipe/cgal-mpir.patch) so that MPIR compiles and works with CGAL.

My point is that MPIR is not 100% compatible, so I think the flag does more harm than good.

**Comment by lrineau** [comment]
@mglisse Do you think the CGAL project should try to support MPIR ? At least it seems easy to test it on Linux.

**Comment by mglisse** [comment]
> Do you think the CGAL project should try to support MPIR ?

Maybe... MPIR does seem popular with windows users, and I don't think it would be that much work. Using MPIR's GMP compatibility, the Gmpzf issue might be the only one that needs any source changes, and not even that if you get a snapshot from MPIR's github repository. On the other hand, I was scared when I saw some of the changes they made to gmpxx.h/mpirxx.h, and wouldn't want to sound like I am recommending it by officially supporting it.

> At least it seems easy to test it on Linux.

That would not be so useful. The main compatibility issue between GMP and MPIR is on win64, where for some interfaces GMP uses long and MPIR uses long long.
