### ISSUE TITLE
Update our script that pulls Eigen master branch

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#4393]
Eigen3 is moving out from Bitbucket.org. At the same time, they move from a Mercurial repo to a Git repository, hosted on Gitlab. See the [news on Eigen web site][1].

I think there are places where we update daily from Eigen `master` branch. There is at least the script `Maintenance/infrastructure/gauguin.geometryfactory.com/update_eigen.sh` and its copy on gauguin.

[1]: http://eigen.tuxfamily.org/index.php?title=News:Migration_to_GitLab.com_scheduled_on_the_December_4th

**Comment by maxGimeno** [comment]
I updated the remote repository on Gauguin and reset the branch to the new master.
