### ISSUE TITLE
Retrieving FPU rounding mode broken on mips

### ISSUE THREAD

**Issue by joachim-reichel** [CGAL/cgal#4399]
Retrieving the FPU rounding mode in FPU.h does not work on mips (Debian architecture names mipsel and mips64el).

The basic problems seems to be the discrepancy between the FPU control word as such and the rounding mode bits as part of the control word. CGAL_IA_GETFPCW defaults to fegetround(), i.e., returns only the rounding mode bits, whereas the specialized cases for the different platforms return the entire control word. However, other bits in the control word could be set, such that return value does not match one of the rounding mode constants.

When running the test Number_types/test/Number_types/rounding_modes.cpp I see that at least bits 2, 23, and 25-27 can be set on mips. And at the end of the program, the check at Number_types/include/CGAL/test_FPU_rounding_mode_impl.h:33 fails because these non-rounding mode bits have different values.

From the glibc headers for mips:
"MIPS FPU floating point control register bits.
31-25  -> floating point conditions code bits 7-1.  These bits are only available in MIPS IV.
23     -> Condition bit
2     -> flag inexact exception"

A similar problem might exist with the check in Checked_protect_FPU_rounding (but I have no repro case for this).

This can be fixed by removing the special case for __mips__ in FPU.h (and falling back to feset/getround()), or by masking the control word value with 0x3 (I hacked FPU_get_cw() to check that, but I don't know how do that in asm for CGAL_IA_GETFPCW).

I'm surprised that this general problem hasn't shown up on other architectures yet ...

**Comment by mglisse** [comment]
CGAL is not used that much on non-x86 platforms, I am not surprised that issues can happen. There is already some masking going on on some platforms:

`#define CGAL_IA_GETFPCW(CW)_controlfp_s (&CW, 0, 0 ); CW  &=  _MCW_RC`

`#define CGAL_IA_GETFPCW(CW) asm volatile ("VMRS %0, FPSCR" : "=r" (CW)); CW &= CGAL_FE_TOWARDZERO`

(as you see, the masking is not done in asm but in plain C(++))

In most cases, the extra bits don't really matter, in particular we do not use the exception flags, so we save a bit of time by handling the whole word. From your description, it looks like we read the control word at the beginning and store it in memory, some computation happens, we write from memory back to the control word, read the control word, and notice that it does not match the memory. Which would mean that reading/writing the control word are not symmetric operations... Or there are some operations after we last restore the control word that flip some bit (or at the beginning, actually).
Do you know which bits were set / not set before, and which after? With qemu for mips64el, the test fails much earlier (it doesn't seem to emulate non-default rounding modes for that platform?) and if I remove the failing parts, it succeeds without showing the flag discrepancy of this report.
Quite possibly the code works fine and the check is just too strict, or rounding_modes.cpp does something wrong. Is that test the only one that fails? I thought the checked happened for all programs...

I am tempted to comment out the mips special case until some motivated users appear...

**Comment by joachim-reichel** [comment]
The operations are symmetric. There are computations after the last restore that flip other bits. The sequence of events is:

1. CGAL reads the control word and stores it in memory.
2. CGAL does computations, changing, and finally correctly restoring the rounding mode.
3. Other computations take place which change bits in the control world (but not the rounding mode).
4. At the very end, the check in ~Check_FPU_rounding_mode_is_restored() fails because of the extra bits.

I don't know the exact bits that are set in step 3 for the mentioned test. (The initial post mentions the unions of bits set in steps 2 and 3 at certain checkpoints.) I could get the bits from that specific test in step 3, but I don't that's the right way. I think we need to assume that any bit with exception of the rounding-mode bits could be set after step 3.

I believe the test is correct, it is just the check in ~Check_FPU_rounding_mode_is_restored() that is too strict. I don't know about other tests. I haven't run all the tests on mips, it is just this one test that is also included in the Debian package since FPU rounding mode control was already a topic in the past for other architectures. But there is as least one reverse dependency (gudhi) that is affected by this problem as well.

**Comment by mglisse** [comment]
So the easiest is:
```diff
-#define CGAL_IA_GETFPCW(CW) asm volatile ("cfc1 %0,$31" : "=r" (CW))
+#define CGAL_IA_GETFPCW(CW) asm volatile ("cfc1 %0,$31" : "=r" (CW)); CW &= 3
```
which matches what some other archs are doing, and means we clear other bits when we set the rounding mode, which is likely ok.
More complicated would be to define a new CGAL_IA_STRIP_FPCW(CW) to CW by default, and `CW & 3` on mips, and in the checks, don't compare the cw directly, strip them both before comparing them. This just saves one *and* in normal CGAL_IA_GETFPCW, not worth the trouble.
Or obviously disable the special code for mips.

**Comment by joachim-reichel** [comment]
Adding "CW &= 3" sounds good to me.

(Resending since "Reply" in Thunderbird ignores the "Reply to" field for
mailing lists. Can be fixed via config option "mail.override_list_reply_to".)

**Comment by joachim-reichel** [comment]
I tested Marc's patch successfully. Can this be applied so that I don't have to carry this as a Debian-specific patch?

**Comment by lrineau** [comment]
Thanks Joachim. I like the idea of the "patch" label, for issues with a proposed patch. I have created it.

To which branch would you like that patch? 4.14.x, 5.0.x, only `master` (5.1)?

**Comment by joachim-reichel** [comment]
Just master is sufficient.

**Comment by lrineau** [comment]
Fixed by https://github.com/CGAL/cgal/commit/406b6faec0ae7f39dcf0964e8ef26e4650405e5e. I have committed and pushed directly to `master`, without any test, because our testsuite has no access to MIPS machines.
