### ISSUE TITLE
Issue with Polyhedron and CGAL::write_PLY() function

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#4411]
With CGAL 4.14 (the latest at conda-forge), the  CGAL::write_PLY() function did not work for me. I did have a valid mesh, and the .off file was written successfully, but when writing a ply file the indices of the faces were the largest 64 bit integer, which was odd. 

The following worked though:  https://piero.dev/2017/04/how-to-write-a-cgal-polyhedron-to-ply-or-any-other-format/

which makes me think that write_PLY() is buggy. I did not test this with GDAL 5. 

It would be great if a standalone example is shown for how to write PLY files. It is a widely used format.

_Originally posted by @oleg-alexandrov in https://github.com/CGAL/cgal/issues/3344#issuecomment-564745344_

**Comment by sgiraudot** [comment]
Do you have some code/data to share? I tested on a simple example and it seems to work well.

```c++
#include <CGAL/Simple_cartesian.h>
#include <CGAL/Surface_mesh.h>
#include <CGAL/IO/PLY_writer.h>

#include <fstream>

typedef CGAL::Simple_cartesian<double> Kernel;
typedef Kernel::Point_3 Point_3;
typedef CGAL::Surface_mesh<Point_3> Mesh;

int main (int argc, char** argv)
{
  Mesh mesh;
  std::ifstream (argv[1]) >> mesh;

  std::ofstream out ("out.ply");
  CGAL::write_PLY (out, mesh);
  
  return EXIT_SUCCESS;
}
```
For example, a cube in OFF:
```
OFF
8 12 0
-0.25 -0.25 -0.25
-0.25 0.25 -0.25
0.25 0.25 -0.25
0.25 -0.25 -0.25
-0.25 -0.25 0.25
-0.25 0.25 0.25
0.25 0.25 0.25
0.25 -0.25 0.25
3  0 1 3
3  3 1 2
3  0 4 1
3  1 4 5
3  3 2 7
3  7 2 6
3  4 0 3
3  7 4 3
3  6 4 7
3  6 5 4
3  1 5 6
3  2 1 6
```
is turned into this PLY:
```
ply
format ascii 1.0
comment Generated by the CGAL library
element vertex 8
property double x
property double y
property double z
element face 12
property list uchar int vertex_indices
end_header
-0.25 -0.25 -0.25
-0.25 0.25 -0.25
0.25 0.25 -0.25
0.25 -0.25 -0.25
-0.25 -0.25 0.25
-0.25 0.25 0.25
0.25 0.25 0.25
0.25 -0.25 0.25
3 3 0 1
3 2 3 1
3 1 0 4
3 5 1 4
3 7 3 2
3 6 7 2
3 3 4 0
3 3 7 4
3 7 6 4
3 4 6 5
3 6 1 5
3 6 2 1
```
which is correct and loads fine with PLY-reading softwares I know of.

> It would be great if a standalone example is shown for how to write PLY files. It is a widely used format.

If you are using `CGAL::Surface_mesh` as I did in my example, note that since CGAL 5.0 there are now documented functions for PLY IO: https://doc.cgal.org/latest/Surface_mesh/group__PkgSurface__mesh.html#ga77bbb79d449c981895eedb6c3c23bd14

**Comment by sloriot** [comment]
Read again the title :)

**Comment by sgiraudot** [comment]
`CGAL::write_PLY` is not directly usable with Polyhedron, which makes my need for a piece of code even stronger…

**Comment by oleg-alexandrov** [comment]
Thank you for your help! 

I think I know what I did wrong. I followed some documentation which says one must read the ply as a polygon soup, and then convert it to a polygon mesh. And another example was processing meshes as polyhedrons, and I mixed them up somehow. 

CGAL is just a large library and it takes time to understand all the pieces and gotchas. If a standalone example as you just provided for me could be part of the documentation (say in a section about exporting data), it would really help new users. I understand that the api is documented, as you say, but setting up a CGAL example from scratch is a pain, with some many typedefs, and kernels, and mesh vs polyhedron, that a simple full example will go a long way to making user's life easier.

**Comment by MaelRL** [comment]
We are working on improving the code and documentation of input and output in CGAL (https://github.com/CGAL/cgal/pull/4255) so hopefully things get clearer.

As a side tip, most code in CGAL is actually used by CGAL itself somewhere else, so if some functionality is not explained in an example (as it should be), a quick search in the source can show things are used in practice.
