### ISSUE TITLE
Intersecting a mesh with a box

### ISSUE THREAD

**Issue by oleg-alexandrov** [CGAL/cgal#4415]
# Issue Details

This is not a bug, but rather a feature request. It would be really great if CGAL would provide a simple function to intersect a mesh with a box. It looks like a basic kind of functionality.

I am aware of the undocumented internal function clip_to_bbox(), yet it is not clear why this function also takes a plane as an input, in addition to the desired box.

I am also aware of the CGAL::Polygon_mesh_processing::clip() function that intersects two meshes. I tried to make a cube mesh and intersect it with my mesh, but that resulted in some weird mesh that meshlab refused to load complaining about some eof thing.

I know that such geometric computation is a hard thing, but hey, you folks are experts. :) Ideally a function like this should be provided, and it should automatically clean up any degeneracy, such as when the cutting plane intersects a face within numerical precision when bad things can happen like tiny edges, degenerate triangles, etc, etc. 

I am so pleased with CGAL so far, and I hope it keeps on improving.

**Comment by afabri** [comment]
Please put a minimalistic cpp together with the data set on gist.github.com so that we can reproduce and fix if necessary.

**Comment by sloriot** [comment]
See #4416
