### ISSUE TITLE
Problem with alpha-shapes (3D) - Unexpected shape underlying

### ISSUE THREAD

**Issue by ismaelGomez87** [CGAL/cgal#4424]
Hi there,

## Issue Details

I am using unweighted alpha shapes from CGAL on 3D. My aim is to obtain a surface that resemble the space occupied by a molecule, considering only atom centers and the empty space trapped by them. All the void space calculation is already done, and some reference points are given, along with atom positions, for the alpha-shape to compute. 

My problem is as follows: I can manage to create the alpha-shape, but the results have unexpected behavior. I am interested only on the surface covering the whole object, thus I only extract the REGULAR simplices of dimension 2 (i.e. triangles). I would expect this to produce a genus-0 manifold, unless very exceptional cases of points being too distant among themselves. However, the alpha-shape code seems to introduce some triangles superposed to each other, avoiding the object to be a manifold. I suspect the problem being on the exact/inexact predicates, although I am not completely sure about it.

For instance, I try to generate a surface for a set of points, and I obtain something like the following:

![visit0001](https://user-images.githubusercontent.com/56299750/70931997-f8a45c80-2038-11ea-9f0e-541960bb8da8.png)

This looks reasonable. However, when I zoom in, I start seeing lines that is hard to believe that belong to a delaunay triangulation / alpha-shape. This is how it looks:

![visit0002](https://user-images.githubusercontent.com/56299750/70932051-15d92b00-2039-11ea-9384-5e7eb7bde1a2.png)

## Source Code

This is how I define all the links to the alpha-shape packages:

```
// CGAL Libraries

#include <CGAL/Simple_cartesian.h>
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
//#include <CGAL/Exact_predicates_exact_constructions_kernel.h>
#include <CGAL/Polyhedron_3.h>
#include <CGAL/Delaunay_triangulation_3.h>
#include <CGAL/Alpha_shape_3.h>
#include <CGAL/Regular_triangulation_euclidean_traits_3.h>
#include <CGAL/Regular_triangulation_3.h>

#include <CGAL/Dynamic_matrix.h>
#include <CGAL/Linear_algebraCd.h>

////// CGAL typedefs

typedef CGAL::Exact_predicates_inexact_constructions_kernel					CG_Kernel;

///// Types for unweighted alpha shapes		/////

typedef CGAL::Tag_true                                                    	Alpha_cmp_tag;
typedef CGAL::Alpha_shape_vertex_base_3<CG_Kernel>               			Vb;
typedef CGAL::Alpha_shape_cell_base_3<CG_Kernel>                 			Fb;
typedef CGAL::Triangulation_data_structure_3<Vb,Fb>      					Tds;
typedef CGAL::Delaunay_triangulation_3<CG_Kernel,Tds,CGAL::Fast_location>  	Delaunay_triangulation;
typedef CGAL::Alpha_shape_3<Delaunay_triangulation>							Alpha_shape_3;

// Alpha shape (general) types
typedef Alpha_shape_3::Alpha_iterator               						Alpha_iterator;
typedef Alpha_shape_3::NT                           						NT;

typedef Alpha_shape_3::Cell_handle 											Cell_handle;
typedef Alpha_shape_3::Edge 												CG_edge;
typedef Alpha_shape_3::Facet 												Facet;
typedef Alpha_shape_3::Vertex_handle										Vertex_handle;

typedef Alpha_shape_3::Classification_type									Classification_type;

typedef CGAL::Polyhedron_3<CG_Kernel> 										Polyhedron;
typedef Polyhedron::Halfedge_around_facet_circulator 						Halfedge_facet_circulator;
typedef Polyhedron::Facet_iterator 											Facet_iterator;

typedef CG_Kernel::Point_3                                  				CG_point;

// Type for cross product
typedef CGAL::Vector_3<CG_Kernel>											CG_vector_3;
```

I can't specify the whole code as it is a big project that liks to CGAL for some functions (mainly alpha-shapes). The definition of the alpha-shape is done as follows:

```
/////	GENERATE THE ALPHA SHAPE	-	Use both atoms and internal Voronoi nodes

	list<CG_point> UnweightedPList;

	// 	Insert atoms into DT object
	for (int i = 0; i < Molecule->GetChemical()->GetNPoints(); i++)
	{
		Point *PAux = Molecule->GetChemical()->GetPointList()[i];

		// Insert point into the unweighted point list (weighted alpha-shapes)
		UnweightedPList.push_back( CG_point(  PAux->GetCoordinate(0), PAux->GetCoordinate(1), PAux->GetCoordinate(2)) );

	}

	//	Insert internal Voronoi nodes into DT
	for (int i = 0; i < Molecule->GetVoronoiGraph()->GetNPoints(); i++)
	{
		Point *PAux = Molecule->GetVoronoiGraph()->GetPointList()[i];

		// Insert point into the unweighted point list (weighted alpha-shapes) - Only internal
		if (PAux->GetType() == internal_point)
		{
			UnweightedPList.push_back( CG_point(  PAux->GetCoordinate(0), PAux->GetCoordinate(1), PAux->GetCoordinate(2)) );
		}

	}


	//Alpha_shape_3 MoleculeAlphaShape(DT);
	Alpha_shape_3 MoleculeAlphaShape(UnweightedPList.begin(), UnweightedPList.end(), 0, Alpha_shape_3::GENERAL);
```

Later on, I extract the surface triangles by doing this:

```
list<Facet> FacetList;
	list<Facet>::const_iterator FacetIt;

	// Get the list of facets of the alpha shape
	MoleculeAlphaShape.get_alpha_shape_facets(back_inserter(FacetList), Alpha_shape_3::REGULAR, Alpha);

	for (FacetIt = FacetList.begin(); FacetIt != FacetList.end(); FacetIt++)
	{
		Facet FacetT = *FacetIt;

		int OppositeVertId = FacetT.second;

		int Indices[FACET_N_V] = { (FacetT.second + 1)%CELL_N_V, (FacetT.second + 2)%CELL_N_V, (FacetT.second + 3)%CELL_N_V};

		////	Simplex points
		double 	Point1[DIM_SMA] = {FacetT.first->vertex(Indices[0])->point().x(), FacetT.first->vertex(Indices[0])->point().y(), FacetT.first->vertex(Indices[0])->point().z()},
				Point2[DIM_SMA] = {FacetT.first->vertex(Indices[1])->point().x(), FacetT.first->vertex(Indices[1])->point().y(), FacetT.first->vertex(Indices[1])->point().z()},
				Point3[DIM_SMA] = {FacetT.first->vertex(Indices[2])->point().x(), FacetT.first->vertex(Indices[2])->point().y(), FacetT.first->vertex(Indices[2])->point().z()};

[Follows some more code ....]
```

I think the whole process is correct. 

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Mac OSX
* Compiler: g++
* Release or debug mode: Debug mode
* Specific flags used (if any): -Wall -ansi -pedantic -g -DNDEBUG -pipe
* CGAL version: 4.X (not sure about the X)
* Boost version: Not sure.
* Other libraries versions if used (Eigen, TBB, etc.): Eigen

Thanks!

**Comment by lrineau** [comment]
Those edges can be Delaunay, if they are on the convex hull for example. Please send us a minimal and reproducible cpp code, with the data set, so that we can try to reproduce your issue.

**Comment by MaelRL** [comment]
@ismaelGomez87 any update?

**Comment by ismaelGomez87** [comment]
Hi

**Comment by MaelRL** [comment]
Hi

**Comment by ismaelGomez87** [comment]
Sorry, I accidentally clicked on "comment". I edited my comment (see above).

**Comment by MaelRL** [comment]
Thanks for the update. No problem, leaving this open for now.

**Comment by MaelRL** [comment]
Feel free to re-open once you have some reproducible code.
