### ISSUE TITLE
polyhedron_3 demo crash 0xc000000142 win 10

### ISSUE THREAD

**Issue by pozegit** [CGAL/cgal#4427]
hi, 
i'm trying to check the polyhedron_3 demo, but after downloading the zip and the cgal-demoDLLs.zip and copying the dlls into the polyhedron folder i got this error trying to launch the Polyhedron_3.exe:
![image](https://user-images.githubusercontent.com/16197267/71118456-81a5ca00-21d8-11ea-97f9-b01bdfce13ff.png)

I ve already installed the qt5 on my system and is added into my windows PATH.
Maybe i miss something ?!

downloads links:
https://www.cgal.org/demo/5.0/CGAL-demoDLLs.zip
https://www.cgal.org/demo/5.0/polyhedron_3.zip

* Operating system (Windows10/64 bits)

**Comment by afabri** [comment]
Maybe run depends.exe to see if  it links with another dll than the ones downloaded.

**Comment by pozegit** [comment]
this is the depends profiler results:
![image](https://user-images.githubusercontent.com/16197267/71163675-e3ece200-224d-11ea-9bfa-b25d1d240e7b.png)


`Operating System: Microsoft Windows NT/2000/XP/2003/Vista based Professional (64-bit), version 6.02.9200
Program Executable: c:\windows\system32\CONHOST.EXE
Program Arguments: 0x4
Starting Directory: C:\WINDOWS\
Search Path: C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\CMake\bin;C:\Program Files\LLVM\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Git\cmd;C:\dev\CGAL-5.0\auxiliary\gmp\lib;C:\Qt\Qt5.9.1\Tools\QtCreator\bin;C:\Qt\Tools\mingw530_32\bin;C:\opencv\build\install\x86\mingw\bin;C:\Users\User\AppData\Local\Programs\Python\Python37\Scripts\;C:\Users\User\AppData\Local\Programs\Python\Python37\;C:\Users\User\AppData\Local\Microsoft\WindowsApps;;C:\Users\User\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\JetBrains\PyCharm Community Edition 2019.3\bin;

Options Selected:
     Log DllMain calls for process attach and process detach messages.
     Hook the process to gather more detailed dependency information.
     Log LoadLibrary function calls.
     Log GetProcAddress function calls.
     Log debug output messages.
     Log a time stamp with each line of log.
     Automatically open and profile child processes.
--------------------------------------------------------------------------------

00:00:00.000: Started "CONHOST.EXE" (process 0x2430) at address 0x00007FF6A4800000.  Successfully hooked module.
00:00:00.000: Loaded "NTDLL.DLL" at address 0x00007FF8B0600000.  Successfully hooked module.
00:00:00.062: Loaded "KERNEL32.DLL" at address 0x00007FF8AFF80000.  Successfully hooked module.
00:00:00.062: Loaded "KERNELBASE.DLL" at address 0x00007FF8AE2F0000.  Successfully hooked module.
00:00:00.062: DllMain(0x00007FF8AE2F0000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "KERNELBASE.DLL" called.
00:00:00.062: DllMain(0x00007FF8AE2F0000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "KERNELBASE.DLL" returned 1 (0x1).
00:00:00.062: DllMain(0x00007FF8AFF80000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "KERNEL32.DLL" called.
00:00:00.062: DllMain(0x00007FF8AFF80000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "KERNEL32.DLL" returned 1 (0x1).
00:00:00.062: Injected "DEPENDS.DLL" at address 0x000000005A610000.
00:00:00.062: DllMain(0x000000005A610000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "DEPENDS.DLL" called.
00:00:37.953: DllMain(0x000000005A610000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "DEPENDS.DLL" returned 1 (0x1).
00:00:38.031: Loaded "MSVCP_WIN.DLL" at address 0x00007FF8AD5E0000.  Successfully hooked module.
00:00:38.031: Loaded "UCRTBASE.DLL" at address 0x00007FF8AE1F0000.  Successfully hooked module.
00:00:38.219: Loaded "SHCORE.DLL" at address 0x00007FF8AE890000.  Successfully hooked module.
00:00:38.219: Loaded "MSVCRT.DLL" at address 0x00007FF8AE960000.  Successfully hooked module.
00:00:38.234: Loaded "RPCRT4.DLL" at address 0x00007FF8B0180000.  Successfully hooked module.
00:00:38.250: Loaded "COMBASE.DLL" at address 0x00007FF8AF3F0000.  Successfully hooked module.
00:00:38.265: Loaded "BCRYPTPRIMITIVES.DLL" at address 0x00007FF8AE5A0000.  Successfully hooked module.
00:00:38.281: Loaded "ADVAPI32.DLL" at address 0x00007FF8AF730000.  Successfully hooked module.
00:00:38.297: Loaded "SECHOST.DLL" at address 0x00007FF8AE720000.  Successfully hooked module.
00:00:38.312: Entrypoint reached. All implicit modules have been loaded.
00:00:38.328: DllMain(0x00007FF8AE1F0000, DLL_PROCESS_ATTACH, 0x00000001010CF7E0) in "UCRTBASE.DLL" called.
00:00:38.328: DllMain(0x00007FF8AE1F0000, DLL_PROCESS_ATTACH, 0x00000001010CF7E0) in "UCRTBASE.DLL" returned 1 (0x1).
00:00:38.328: DllMain(0x00007FF8AD5E0000, DLL_PROCESS_ATTACH, 0x00000001010CF7E0) in "MSVCP_WIN.DLL" called.
00:00:38.328: DllMain(0x00007FF8AD5E0000, DLL_PROCESS_ATTACH, 0x00000001010CF7E0) in "MSVCP_WIN.DLL" returned 1 (0x1).
00:00:38.328: DllMain(0x00007FF8AE960000, DLL_PROCESS_ATTACH, 0x00000001010CF7E0) in "MSVCRT.DLL" called.
00:00:38.328: DllMain(0x00007FF8AE960000, DLL_PROCESS_ATTACH, 0x00000001010CF7E0) in "MSVCRT.DLL" returned 1 (0x1).
00:00:38.328: DllMain(0x00007FF8B0180000, DLL_PROCESS_ATTACH, 0x00000001010CF7E0) in "RPCRT4.DLL" called.
00:00:38.344: DllMain(0x00007FF8B0180000, DLL_PROCESS_ATTACH, 0x00000001010CF7E0) in "RPCRT4.DLL" returned 2954757633 (0xB01E0601).
00:00:38.344: DllMain(0x00007FF8AE5A0000, DLL_PROCESS_ATTACH, 0x00000001010CF7E0) in "BCRYPTPRIMITIVES.DLL" called.
00:00:38.344: DllMain(0x00007FF8AE5A0000, DLL_PROCESS_ATTACH, 0x00000001010CF7E0) in "BCRYPTPRIMITIVES.DLL" returned 1 (0x1).
00:00:38.344: DllMain(0x00007FF8AF3F0000, DLL_PROCESS_ATTACH, 0x00000001010CF7E0) in "COMBASE.DLL" called.
00:00:38.344: DllMain(0x00007FF8AF3F0000, DLL_PROCESS_ATTACH, 0x00000001010CF7E0) in "COMBASE.DLL" returned 1 (0x1).
00:00:38.344: DllMain(0x00007FF8AE890000, DLL_PROCESS_ATTACH, 0x00000001010CF7E0) in "SHCORE.DLL" called.
00:00:38.344: DllMain(0x00007FF8AE890000, DLL_PROCESS_ATTACH, 0x00000001010CF7E0) in "SHCORE.DLL" returned 1 (0x1).
00:00:38.359: DllMain(0x00007FF8AE720000, DLL_PROCESS_ATTACH, 0x00000001010CF7E0) in "SECHOST.DLL" called.
00:00:38.359: DllMain(0x00007FF8AE720000, DLL_PROCESS_ATTACH, 0x00000001010CF7E0) in "SECHOST.DLL" returned 1 (0x1).
00:00:38.359: DllMain(0x00007FF8AF730000, DLL_PROCESS_ATTACH, 0x00000001010CF7E0) in "ADVAPI32.DLL" called.
00:00:38.359: DllMain(0x00007FF8AF730000, DLL_PROCESS_ATTACH, 0x00000001010CF7E0) in "ADVAPI32.DLL" returned 1 (0x1).
00:00:38.375: Loaded "USER32.DLL" at address 0x00007FF8AF250000.  Successfully hooked module.
00:00:38.375: Loaded "WIN32U.DLL" at address 0x00007FF8AD5B0000.  Successfully hooked module.
00:00:38.390: Loaded "GDI32.DLL" at address 0x00007FF8B0150000.  Successfully hooked module.
00:00:38.406: Loaded "GDI32FULL.DLL" at address 0x00007FF8AD730000.  Successfully hooked module.
00:00:38.969: DllMain(0x00007FF8AD730000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "GDI32FULL.DLL" called.
00:00:38.969: DllMain(0x00007FF8AD730000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "GDI32FULL.DLL" returned 1 (0x1).
00:00:38.969: DllMain(0x00007FF8B0150000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "GDI32.DLL" called.
00:00:38.969: DllMain(0x00007FF8B0150000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "GDI32.DLL" returned 1 (0x1).
00:00:38.969: DllMain(0x00007FF8AF250000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "USER32.DLL" called.
00:00:38.984: Loaded "IMM32.DLL" at address 0x00007FF8B03E0000.  Successfully hooked module.
00:00:38.984: DllMain(0x00007FF8B03E0000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "IMM32.DLL" called.
00:00:38.984: DllMain(0x00007FF8B03E0000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "IMM32.DLL" returned 1 (0x1).
00:00:38.984: DllMain(0x00007FF8AF250000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "USER32.DLL" returned 1 (0x1).
00:00:39.015: Loaded "SHELL32.DLL" at address 0x00007FF8AEA00000.  Successfully hooked module.
00:00:39.015: Loaded "CFGMGR32.DLL" at address 0x00007FF8AD8D0000.  Successfully hooked module.
00:00:39.031: Loaded "WINDOWS.STORAGE.DLL" at address 0x00007FF8ADA70000.  Successfully hooked module.
00:00:40.156: Loaded "PROFAPI.DLL" at address 0x00007FF8AD4E0000.  Successfully hooked module.
00:00:40.172: Loaded "POWRPROF.DLL" at address 0x00007FF8AD540000.  Successfully hooked module.
00:00:40.172: Loaded "UMPDC.DLL" at address 0x00007FF8AD4D0000.  Successfully hooked module.
00:00:40.187: Loaded "SHLWAPI.DLL" at address 0x00007FF8AFAA0000.  Successfully hooked module.
00:00:40.203: Loaded "KERNEL.APPCORE.DLL" at address 0x00007FF8AD520000.  Successfully hooked module.
00:00:40.312: Loaded "CRYPTSP.DLL" at address 0x00007FF8AD590000.  Successfully hooked module.
00:00:40.312: DllMain(0x00007FF8AD8D0000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "CFGMGR32.DLL" called.
00:00:40.312: DllMain(0x00007FF8AD8D0000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "CFGMGR32.DLL" returned 1 (0x1).
00:00:40.312: DllMain(0x00007FF8AD4E0000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "PROFAPI.DLL" called.
00:00:40.312: DllMain(0x00007FF8AD4E0000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "PROFAPI.DLL" returned 1 (0x1).
00:00:40.312: DllMain(0x00007FF8AD4D0000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "UMPDC.DLL" called.
00:00:40.328: DllMain(0x00007FF8AD4D0000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "UMPDC.DLL" returned 1 (0x1).
00:00:40.328: DllMain(0x00007FF8AD540000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "POWRPROF.DLL" called.
00:00:40.328: DllMain(0x00007FF8AD540000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "POWRPROF.DLL" returned 1 (0x1).
00:00:40.328: DllMain(0x00007FF8AFAA0000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "SHLWAPI.DLL" called.
00:00:40.328: DllMain(0x00007FF8AFAA0000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "SHLWAPI.DLL" returned 1 (0x1).
00:00:40.328: DllMain(0x00007FF8AD520000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "KERNEL.APPCORE.DLL" called.
00:00:40.328: DllMain(0x00007FF8AD520000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "KERNEL.APPCORE.DLL" returned 1579880705 (0x5E2B1101).
00:00:40.328: DllMain(0x00007FF8ADA70000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "WINDOWS.STORAGE.DLL" called.
00:00:40.344: DllMain(0x00007FF8ADA70000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "WINDOWS.STORAGE.DLL" returned 1 (0x1).
00:00:40.344: DllMain(0x00007FF8AD590000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "CRYPTSP.DLL" called.
00:00:40.344: DllMain(0x00007FF8AD590000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "CRYPTSP.DLL" returned 1 (0x1).
00:00:40.344: DllMain(0x00007FF8AEA00000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "SHELL32.DLL" called.
00:00:40.344: DllMain(0x00007FF8AEA00000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "SHELL32.DLL" returned 1 (0x1).
00:00:40.344: Loaded "UXTHEME.DLL" at address 0x00007FF8AB850000.  Successfully hooked module.
00:00:40.359: DllMain(0x00007FF8AB850000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "UXTHEME.DLL" called.
00:00:40.359: DllMain(0x00007FF8AB850000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "UXTHEME.DLL" returned 1 (0x1).
00:00:40.359: onecore\windows\core\console\open\src\interactivity\win32\systemconfigurationprovider.cpp(179)\conhost.exe!00007FF6A48056B5: (caller: 00007FF6A48060C3) LogHr(1) tid(26d4) 80004005 Unbekannter Fehler
00:00:40.406: onecore\windows\core\console\open\src\renderer\gdi\state.cpp(245)\conhost.exe!00007FF6A4815477: (caller: 00007FF6A4813FF7) LogHr(2) tid(3164) 80004005 Unbekannter Fehler
00:00:40.422: Loaded "MSCTF.DLL" at address 0x00007FF8B02A0000.  Successfully hooked module.
00:00:40.437: Loaded "OLEAUT32.DLL" at address 0x00007FF8AE7C0000.  Successfully hooked module.
00:00:40.437: DllMain(0x00007FF8AE7C0000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "OLEAUT32.DLL" called.
00:00:40.437: DllMain(0x00007FF8AE7C0000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "OLEAUT32.DLL" returned 1 (0x1).
00:00:40.437: DllMain(0x00007FF8B02A0000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "MSCTF.DLL" called.
00:00:40.453: DllMain(0x00007FF8B02A0000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "MSCTF.DLL" returned 1 (0x1).
00:00:40.469: Loaded "COMCTL32.DLL" at address 0x00007FF89E760000.  Successfully hooked module.
00:00:40.469: DllMain(0x00007FF89E760000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "COMCTL32.DLL" called.
00:00:40.484: DllMain(0x00007FF89E760000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "COMCTL32.DLL" returned 1 (0x1).
00:00:40.484: Loaded "DWMAPI.DLL" at address 0x00007FF8ABC70000.  Successfully hooked module.
00:00:40.484: DllMain(0x00007FF8ABC70000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "DWMAPI.DLL" called.
00:00:40.500: DllMain(0x00007FF8ABC70000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "DWMAPI.DLL" returned 1 (0x1).
00:00:40.500: Loaded "TEXTINPUTFRAMEWORK.DLL" at address 0x00007FF8A61B0000.  Successfully hooked module.
00:00:40.515: Loaded "COREUICOMPONENTS.DLL" at address 0x00007FF8A94F0000.  Successfully hooked module.
00:00:40.531: Loaded "COREMESSAGING.DLL" at address 0x00007FF8AB3A0000.  Successfully hooked module.
00:00:40.547: Loaded "NTMARTA.DLL" at address 0x00007FF8AC530000.  Successfully hooked module.
00:00:40.781: Loaded "WINTYPES.DLL" at address 0x00007FF8A9140000.  Successfully hooked module.
00:00:41.015: Loaded "WINTYPES.DLL" at address 0x0000018E76B90000.  Successfully hooked module.
00:00:41.015: Unloaded "WINTYPES.DLL" at address 0x0000018E76B90000.
00:00:41.031: Loaded "WINTYPES.DLL" at address 0x0000018E76CF0000.  Successfully hooked module.
00:00:41.031: Unloaded "WINTYPES.DLL" at address 0x0000018E76CF0000.
00:00:41.031: DllMain(0x00007FF8AC530000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "NTMARTA.DLL" called.
00:00:41.031: DllMain(0x00007FF8AC530000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "NTMARTA.DLL" returned 1 (0x1).
00:00:41.031: DllMain(0x00007FF8AB3A0000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "COREMESSAGING.DLL" called.
00:00:41.031: DllMain(0x00007FF8AB3A0000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "COREMESSAGING.DLL" returned 1 (0x1).
00:00:41.031: DllMain(0x00007FF8A9140000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "WINTYPES.DLL" called.
00:00:41.047: DllMain(0x00007FF8A9140000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "WINTYPES.DLL" returned 1 (0x1).
00:00:41.047: DllMain(0x00007FF8A94F0000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "COREUICOMPONENTS.DLL" called.
00:00:41.047: DllMain(0x00007FF8A94F0000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "COREUICOMPONENTS.DLL" returned 1 (0x1).
00:00:41.047: DllMain(0x00007FF8A61B0000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "TEXTINPUTFRAMEWORK.DLL" called.
00:00:41.047: DllMain(0x00007FF8A61B0000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "TEXTINPUTFRAMEWORK.DLL" returned 1 (0x1).
00:00:41.062: Loaded "IERTUTIL.DLL" at address 0x00007FF8A20C0000.  Successfully hooked module.
00:00:41.062: DllMain(0x00007FF8A20C0000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "IERTUTIL.DLL" called.
00:00:41.078: DllMain(0x00007FF8A20C0000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "IERTUTIL.DLL" returned 1 (0x1).
00:00:41.078: Loaded "CLBCATQ.DLL" at address 0x00007FF8B0040000.  Successfully hooked module.
00:00:41.297: DllMain(0x00007FF8B0040000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "CLBCATQ.DLL" called.
00:00:41.297: DllMain(0x00007FF8B0040000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "CLBCATQ.DLL" returned 1 (0x1).
00:00:48.781: onecore\windows\core\console\open\src\server\devicecomm.cpp(160)\conhost.exe!00007FF6A480F315: (caller: 00007FF8AFF97BD4) ReturnHr(1) tid(26d4) 800700E9 Kein Prozess ist am anderen Ende der Pipe.
00:00:48.781: Exited "CONHOST.EXE" (process 0x2430) with code 0 (0x0).
`

**Comment by MaelRL** [comment]
@pozegit any update?
