### ISSUE TITLE
CGAL Makefile

### ISSUE THREAD

**Issue by csverma610** [CGAL/cgal#4430]
Hello,

Is there a Makefile to include in a project involving CGAL?

Thanks

**Comment by oleg-alexandrov** [comment]
You can follow the example in https://github.com/CGAL/cgal/blob/master/INSTALL.md at the very bottom, which creates a CMakeLists.txt for you.

**Comment by lrineau** [comment]
There is no standard `Makefile`. The CGAL project supports `CMake`, that can generate various build systems, including makefiles.
