### ISSUE TITLE
merge_duplicate_points_in_polygon_soup error

### ISSUE THREAD

**Issue by tsukasa1989** [CGAL/cgal#4431]
## Issue Details

Loading an STL file via CGAL::read_STL and I there might be an invalid polygon_soup. Therefor I would like to reapir it first. It gives an error on merge_duplicate_points_in_polygon_soup. So I directly call this function to debug. But already gives an error. See error below:

My final goal is using repair_polygon_soup function.

The error is:

> error: no type named ‘Less_xyz_3’ in ‘Traits’ {aka ‘struct CGAL::internal_kernel_traits::Dummy_kernel<std::array<double, 3> >’}
>    typedef typename Traits::Less_xyz_3                                             Less_xyz_3;
> 

Full response:

> 
> /usr/local/include/CGAL/Polygon_mesh_processing/repair_polygon_soup.h: In instantiation of ‘std::size_t CGAL::Polygon_mesh_processing::merge_duplicate_points_in_polygon_soup(PointRange&, PolygonRange&, const NamedParameters&) [with PointRange = std::vector<std::array<double, 3> >; PolygonRange = std::vector<std::array<int, 3> >; NamedParameters = CGAL::Named_function_parameters<bool, CGAL::internal_np::all_default_t>; std::size_t = long unsigned int]’:
> /usr/local/include/CGAL/Polygon_mesh_processing/repair_polygon_soup.h:580:48:   required from ‘std::size_t CGAL::Polygon_mesh_processing::merge_duplicate_points_in_polygon_soup(PointRange&, PolygonRange&) [with PointRange = std::vector<std::array<double, 3> >; PolygonRange = std::vector<std::array<int, 3> >; std::size_t = long unsigned int]’
> /var/dev/mesh/project_name/test.cpp:36:89:   required from here
> /usr/local/include/CGAL/Polygon_mesh_processing/repair_polygon_soup.h:518:83: error: no type named ‘Less_xyz_3’ in ‘Traits’ {aka ‘struct CGAL::internal_kernel_traits::Dummy_kernel<std::array<double, 3> >’}
>    typedef typename Traits::Less_xyz_3                                             Less_xyz_3;
>                                                                                    ^~~~~~~~~~
> /usr/local/include/CGAL/Polygon_mesh_processing/repair_polygon_soup.h:523:83: error: no type named ‘Less_xyz_3’ in ‘CGAL::Polygon_mesh_processing::internal::GetPolygonGeomTraits<std::vector<std::array<double, 3> >, std::vector<std::array<int, 3> >, CGAL::Named_function_parameters<bool, CGAL::internal_np::all_default_t> >::type’ {aka ‘struct CGAL::internal_kernel_traits::Dummy_kernel<std::array<double, 3> >’}
>    typedef std::map<Point_3, std::size_t, Less_xyz_3>                              Unique_point_container;
>                                                                                    ^~~~~~~~~~~~~~~~~~~~~~
> /usr/local/include/CGAL/Polygon_mesh_processing/repair_polygon_soup.h:531:64: error: no type named ‘Less_xyz_3’ in ‘CGAL::Polygon_mesh_processing::internal::GetPolygonGeomTraits<std::vector<std::array<double, 3> >, std::vector<std::array<int, 3> >, CGAL::Named_function_parameters<bool, CGAL::internal_np::all_default_t> >::type’ {aka ‘struct CGAL::internal_kernel_traits::Dummy_kernel<std::array<double, 3> >’}
>      std::pair<typename Unique_point_container::iterator, bool> is_insert_successful =
>                                                                 ^~~~~~~~~~~~~~~~~~~~
> /usr/local/include/CGAL/Polygon_mesh_processing/repair_polygon_soup.h:531:64: error: no type named ‘Less_xyz_3’ in ‘CGAL::Polygon_mesh_processing::internal::GetPolygonGeomTraits<std::vector<std::array<double, 3> >, std::vector<std::array<int, 3> >, CGAL::Named_function_parameters<bool, CGAL::internal_np::all_default_t> >::type’ {aka ‘struct CGAL::internal_kernel_traits::Dummy_kernel<std::array<double, 3> >’}
> make[2]: *** [CMakeFiles/project_name.dir/build.make:63: CMakeFiles/project_name.dir/test.cpp.o] Error 1
> make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/project_name.dir/all] Error 2
> make: *** [Makefile:84: all] Error 2
> 

## Source Code
```

#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/Polyhedron_3.h>
#include <CGAL/Polygon_mesh_processing/triangulate_hole.h>
#include <iostream>
#include <fstream>
#include <vector>

#include <CGAL/IO/Polyhedron_builder_from_STL.h>
#include <CGAL/IO/STL_writer.h>
#include <CGAL/Polygon_mesh_processing/polygon_soup_to_polygon_mesh.h>

#include <CGAL/Polygon_mesh_processing/repair_polygon_soup.h>
#include <CGAL/Polygon_mesh_processing/orient_polygon_soup.h>

typedef CGAL::Exact_predicates_inexact_constructions_kernel Kernel;
typedef CGAL::Polyhedron_3<Kernel>     Polyhedron;
typedef Polyhedron::Halfedge_handle    Halfedge_handle;
typedef Polyhedron::Facet_handle       Facet_handle;
typedef Polyhedron::Vertex_handle      Vertex_handle;

int main(int argc, char* argv[])
{
	const char* filename = (argc > 1) ? argv[1] : "Z:/CGAL/bunnyhole.stl";
	std::ifstream input(filename, std::ios::in | std::ios::binary);

	std::vector<std::array<double, 3> > points;
	std::vector<std::array<int, 3> > triangles;

	if (!input || input.bad() || !CGAL::read_STL(input, points, triangles)) {
		std::cout << "Error: Invalid file" << std::endl;
		return 1;
	}

	Polyhedron poly;
	
	CGAL::Polygon_mesh_processing::merge_duplicate_points_in_polygon_soup(points, triangles); // ERROR HERE
//	CGAL::Polygon_mesh_processing::repair_polygon_soup(points, triangles);
        CGAL::Polygon_mesh_processing::orient_polygon_soup(points, triangles);

	if (CGAL::Polygon_mesh_processing::is_polygon_soup_a_polygon_mesh(triangles)) {
		CGAL::Polygon_mesh_processing::polygon_soup_to_polygon_mesh(points, triangles, poly);
        } else {
		 std::cout << "Error: Invalid polygon soup" << std::endl;
                return 1;
        }
	
	if (!poly.is_valid()) {
		std::cout << "Error: Invalid mesh" << std::endl;
		return 1;
	}


        if ( poly.is_empty()) {
                std::cout << "Error: Empty mesh" << std::endl;
                return 1;
        }

	return 0;
}

```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): CentOS 8
* Compiler: Linux version 4.18.0-80.11.2.el8_0.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 8.2.1 20180905 (Red Hat 8.2.1-3) (GCC)) #1 SMP Tue Sep 24 11:32:19 UTC 2019
* Release or debug mode: Release
* Specific flags used (if any):
* CGAL version: 5.0
* Boost version: 
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by MaelRL** [comment]
Firstly, the point type of your point range is not a natural kernel type (i.e. Kernel::Point_3). Consequently, you must provide a geometric traits adapted to your points, specifically, one that provides a `Less_xyz_3` predicate. You also need an `Equal_3` for another function of `PMP::repair_polygon_soup`.

See [documentation of the function](https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__repairing__grp.html#ga14042207f91907f139aff40b103824f4).

Secondly, some repair operation require the face type to be a container of mutable size, and thus `std::array` is not a good fit.

Once these two things are fixed, it works, see: https://gist.github.com/MaelRL/9440d918cca41411ec7547015cce2b2a.
