### ISSUE TITLE
How can I get the vertices through the face in Surface_mesh

### ISSUE THREAD

**Issue by KeepFaithMe** [CGAL/cgal#4434]
## Issue Details

How can I get the coordinates of the three vertices contained in the face through the face.for example,I have a Surface_mesh,there are many faces in the Surface_mesh,and I need **_through the face to get the vertices_** which contain in the face.So how can i do it? is there a document to refer?

**Comment by KeepFaithMe** [comment]
the version of cgal is 4.13.1

**Comment by MaelRL** [comment]
The documentation for the Surface_mesh class is available [here](https://doc.cgal.org/latest/Surface_mesh/index.html#Chapter_3D_Surface_mesh). Specifically, you want to look at Section 4, and [this example](https://doc.cgal.org/latest/Surface_mesh/Surface_mesh_2sm_circulators_8cpp-example.html).
