### ISSUE TITLE
CMake errors!

### ISSUE THREAD

**Issue by zengletian1491** [CGAL/cgal#4435]
The following operations are on ubuntu 16.04 LTS. 

Typing "cmake -DCGAL_HEADER_ONLY=OFF -DCMAKE_BUILD_TYPE=Release -Dboost_thread_FOUND=FALSE ..", we find that errors occur as follows:

-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using header-only CGAL
-- Targetting Unix Makefiles
-- Using /usr/bin/c++ compiler.
-- Found GMP: /usr/lib/x86_64-linux-gnu/libgmp.so  
-- Found MPFR: /usr/lib/x86_64-linux-gnu/libmpfr.so  
-- Found Boost 1.70.0 at /usr/local/lib/cmake/Boost-1.70.0
--   Requested configuration: QUIET REQUIRED
-- Found boost_headers 1.70.0 at /usr/local/lib/cmake/boost_headers-1.70.0
-- Found Boost: /usr/local/lib/cmake/Boost-1.70.0/BoostConfig.cmake (found suitable version "1.70.0", minimum required is "1.48")  
-- Boost include dirs: /usr/local/include
-- Boost libraries:    
-- Using gcc version 4 or later. Adding -frounding-math
== Generating build files for demos ==

-- Configuring demo in demo/AABB_tree
-- Using header-only CGAL

-- Configuring demo in demo/Alpha_shapes_2

-- Configuring demo in demo/Alpha_shapes_3

-- Configuring demo in demo/Apollonius_graph_2

-- Configuring demo in demo/Arrangement_on_surface_2
-- Using header-only CGAL
-- Found Boost 1.70.0 at /usr/local/lib/cmake/Boost-1.70.0
--   Requested configuration: QUIET REQUIRED COMPONENTS thread;system
**-- Found boost_thread 1.70.0 at /usr/local/lib/cmake/boost_thread-1.70.0**
**-- No suitable boost_thread variant has been identified!**
**--   libboost_thread.so.1.70.0 (shared, BUILD_SHARED_LIBS not ON, set Boost_USE_STATIC_LIBS=OFF to override)**
--   libboost_thread.a (static, Boost_USE_STATIC_LIBS=OFF)
**CMake Error at /usr/local/lib/cmake/Boost-1.70.0/BoostConfig.cmake:95 (find_package):**
  **Found package configuration file:**

    **/usr/local/lib/cmake/boost_thread-1.70.0/boost_thread-config.cmake**

  **but it set boost_thread_FOUND to FALSE so package "boost_thread" is**
  **considered to be NOT FOUND.  Reason given by package:**

  **No suitable build variant has been found.**

**Call Stack (most recent call first):
  /usr/local/lib/cmake/Boost-1.70.0/BoostConfig.cmake:124 (boost_find_dependency)
  /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:422 (find_package)
  /usr/local/lib/cmake/CGAL/CGAL_SetupCGAL_CoreDependencies.cmake:60 (find_package)
  /usr/local/lib/cmake/CGAL/CGALConfig.cmake:125 (include)
  Arrangement_on_surface_2/CMakeLists.txt:15 (find_package)**

**-- Configuring incomplete, errors occurred!
See also "/media/zeng/work/3DReconstruction/CGAL-5.0/demo/build/CMakeFiles/CMakeOutput.log".**

Could you please give some suggetions? Thank you!

**Comment by sloriot** [comment]
What happen if you don't set `boost_thread_FOUND=FALSE`? I think you are not supposed to set this variable by hand.

**Comment by zengletian1491** [comment]
> What happen if you don't set `boost_thread_FOUND=FALSE`? I think you are not supposed to set this variable by hand.

Typing "cmake -DCGAL_HEADER_ONLY=OFF -DCMAKE_BUILD_TYPE=Release ..", we find that errors occur are almost the same as the former one:

-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using header-only CGAL
-- Targetting Unix Makefiles
-- Using /usr/bin/c++ compiler.
-- Found GMP: /usr/lib/x86_64-linux-gnu/libgmp.so  
-- Found MPFR: /usr/lib/x86_64-linux-gnu/libmpfr.so  
-- Found Boost 1.70.0 at /usr/local/lib/cmake/Boost-1.70.0
--   Requested configuration: QUIET REQUIRED
-- Found boost_headers 1.70.0 at /usr/local/lib/cmake/boost_headers-1.70.0
-- Found Boost: /usr/local/lib/cmake/Boost-1.70.0/BoostConfig.cmake (found suitable version "1.70.0", minimum required is "1.48")  
-- Boost include dirs: /usr/local/include
-- Boost libraries:    
-- Using gcc version 4 or later. Adding -frounding-math
== Generating build files for demos ==

-- Configuring demo in demo/AABB_tree
-- Using header-only CGAL

-- Configuring demo in demo/Alpha_shapes_2

-- Configuring demo in demo/Alpha_shapes_3

-- Configuring demo in demo/Apollonius_graph_2

-- Configuring demo in demo/Arrangement_on_surface_2
-- Using header-only CGAL
**-- Found Boost 1.70.0 at /usr/local/lib/cmake/Boost-1.70.0**
**--   Requested configuration: QUIET REQUIRED COMPONENTS thread;system**
**-- Found boost_thread 1.70.0 at /usr/local/lib/cmake/boost_thread-1.70.0**
**-- No suitable boost_thread variant has been identified!**
**--   libboost_thread.so.1.70.0 (shared, BUILD_SHARED_LIBS not ON, set Boost_USE_STATIC_LIBS=OFF to override)**
**--   libboost_thread.a (static, Boost_USE_STATIC_LIBS=OFF)**
**CMake Error at /usr/local/lib/cmake/Boost-1.70.0/BoostConfig.cmake:95 (find_package):**
  **Found package configuration file:**

    **/usr/local/lib/cmake/boost_thread-1.70.0/boost_thread-config.cmake**

  **but it set boost_thread_FOUND to FALSE so package "boost_thread" is**
  **considered to be NOT FOUND.  Reason given by package:**

  **No suitable build variant has been found.**

Call Stack (most recent call first):
  /usr/local/lib/cmake/Boost-1.70.0/BoostConfig.cmake:124 (boost_find_dependency)
  /usr/local/share/cmake-3.15/Modules/FindBoost.cmake:422 (find_package)
  /usr/local/lib/cmake/CGAL/CGAL_SetupCGAL_CoreDependencies.cmake:60 (find_package)
  /usr/local/lib/cmake/CGAL/CGALConfig.cmake:125 (include)
  Arrangement_on_surface_2/CMakeLists.txt:15 (find_package)


-- Configuring incomplete, errors occurred!
See also "/media/zeng/work/3DReconstruction/CGAL-5.0/demo/build/CMakeFiles/CMakeOutput.log".

**Comment by lrineau** [comment]
Hi, can you please restart with `-DBoost_DEBUG=ON` to have better messages?

It seems to be an issue with the variant of Boost installed in `/usr/local/lib/`. Either the script wants a shared version but only a static version is available, or the reverse. I cannot tell because the messages are confusing.

You can also try with:
  -  `-DCGAL_Boost_USE_STATIC_LIBS=TRUE` or,
  -  `-DCGAL_Boost_USE_STATIC_LIBS=FALSE`.

I cannot say which one will work, because that depends on what is in your `/usr/local/lib/`.

**Comment by MaelRL** [comment]
@zengletian1491 any update?

**Comment by caohanghust** [comment]
> * -DCGAL_Boost_USE_STATIC_LIBS=FALSE


> Hi, can you please restart with `-DBoost_DEBUG=ON` to have better messages?
> 
> It seems to be an issue with the variant of Boost installed in `/usr/local/lib/`. Either the script wants a shared version but only a static version is available, or the reverse. I cannot tell because the messages are confusing.
> 
> You can also try with:
> 
> * `-DCGAL_Boost_USE_STATIC_LIBS=TRUE` or,
> * `-DCGAL_Boost_USE_STATIC_LIBS=FALSE`.
> 
> I cannot say which one will work, because that depends on what is in your `/usr/local/lib/`.

-DCGAL_Boost_USE_STATIC_LIBS=FALSE is useful
