### ISSUE TITLE
Link CGAL with Eigen library!

### ISSUE THREAD

**Issue by KeepFaithMe** [CGAL/cgal#4442]
_Please use the following template to help us solving your issue._

## Issue Details

when I use the parameterization algorithm,some problem "**_You must either provide 'SolverTraits_' or link CGAL with the Eigen library_**".But W hen I compile the CGAL ,I add the Eigen library to Cmake,and success.So how can I handle this problem.The Parameteriztion algroithm is from https://doc.cgal.org/latest/Surface_mesh_parameterization/Surface_mesh_parameterization_2simple_parameterization_8cpp-example.html

CGAL versioin 4.13.1
Operating system          Win10  x64

## Source Code

_If your issue arises by using CGAL in your own source code, please provide a minimalist example that we can compile easily to reproduce the bug. If your issue arises from using a CGAL program (demo, example, etc.), please let us know which one. Helping you solving an issue is much easier and efficient if we can reproduce it._

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):
* Compiler:
* Release or debug mode:
* Specific flags used (if any):
* CGAL version:
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by lrineau** [comment]
Your report is not really good, because you do not tell us how you have used CMake. Without that, I have to guess, and here is my advice: make sure you enable Eigen, in CMake, when you configure the example program, and not when you configure the CGAL libraries.

**Comment by KeepFaithMe** [comment]
I am so sorry&nbsp;I didn't make myself clear.I mean when I use Cmake 3.9.0 compile the CGAL library ,there is an option 'WITH_Eigen3',and I selected it,and I add the Eigen path into the 'EIGEN3_INCLUDE_DIR'. The Eigen version is 3.7.So when I use the example&nbsp;https://doc.cgal.org/latest/Surface_mesh_parameterization/Surface_mesh_parameterization_2discrete_authalic_8cpp-example.html, The Visual studio 2017 show: You must either provide 'SolverTraits_' or link CGAL with the Eigen library.I saw the source code:&nbsp;https://github.com/CGAL/releases/blob/master/include/CGAL/Surface_mesh_parameterization/Discrete_conformal_map_parameterizer_3.h&nbsp; and define the 'CGAL_EIGEN3_ENABLED',but it is still wrong.So how can it deal with it!
looking forward your reply!
good luck!




as following is my testing code:


#include <CGAL/Eigen_solver_traits.h&gt;
#include <CGAL/Simple_cartesian.h&gt;
#include <CGAL/Surface_mesh.h&gt;
#include <CGAL/Surface_mesh_parameterization/IO/File_off.h&gt;
#include <CGAL/Surface_mesh_parameterization/Circular_border_parameterizer_3.h&gt;
#include <CGAL/Surface_mesh_parameterization/Discrete_authalic_parameterizer_3.h&gt;
#include <CGAL/Surface_mesh_parameterization/Error_code.h&gt;
#include <CGAL/Surface_mesh_parameterization/parameterize.h&gt;
#include <CGAL/Polygon_mesh_processing/measure.h&gt;
#include <cstdlib&gt;
#include <iostream&gt;
#include <fstream&gt;
&nbsp;#include<Eigen/src/IterativeLinearSolvers/IncompleteLUT.h&gt;
&nbsp;#include<CGAL/Eigen_matrix.h&gt;
typedef CGAL::Simple_cartesian<double&gt;&nbsp; &nbsp; &nbsp; &nbsp;Kernel;
typedef Kernel::Point_2&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Point_2;
typedef Kernel::Point_3&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Point_3;
typedef CGAL::Surface_mesh<Kernel::Point_3&gt;&nbsp; SurfaceMesh;
typedef boost::graph_traits<SurfaceMesh&gt;::halfedge_descriptor&nbsp; halfedge_descriptor;
typedef boost::graph_traits<SurfaceMesh&gt;::vertex_descriptor&nbsp; &nbsp; vertex_descriptor;
typedef boost::graph_traits<SurfaceMesh&gt;::face_descriptor&nbsp; &nbsp; &nbsp; face_descriptor;
namespace SMP = CGAL::Surface_mesh_parameterization;


#define CGAL_EIGEN3_ENABLED CGAL::Eigen_solver_traits<Eigen::BiCGSTAB<Eigen_sparse_matrix<double&gt;::EigenType,Eigen::IncompleteLUT<double&gt; &gt; &gt; &gt; ::type &gt;
int main(int argc, char** argv)
{
	std::ifstream in((argc &gt; 1) ? argv[1] : "data/three_peaks.off");
	if (!in) {
		std::cerr << "Problem loading the input data" << std::endl;
		return EXIT_FAILURE;
	}
	SurfaceMesh sm;
	in &gt;&gt; sm;
	// A halfedge on the border
	halfedge_descriptor bhd = CGAL::Polygon_mesh_processing::longest_border(sm).first;
	// The 2D points of the uv parametrisation will be written into this map
	typedef SurfaceMesh::Property_map<vertex_descriptor, Point_2&gt;&nbsp; UV_pmap;
	UV_pmap uv_map = sm.add_property_map<vertex_descriptor, Point_2&gt;("v:uv").first;
	typedef SMP::Circular_border_arc_length_parameterizer_3<SurfaceMesh&gt;&nbsp; Border_parameterizer;
	typedef SMP::Discrete_authalic_parameterizer_3<SurfaceMesh, Border_parameterizer&gt; Parameterizer;
	SMP::Error_code err = SMP::parameterize(sm, Parameterizer(), bhd, uv_map);
	if (err != SMP::OK) {
		std::cerr << "Error: " << SMP::get_error_message(err) << std::endl;
		return EXIT_FAILURE;
	}
	std::ofstream out("result.off");
	SMP::IO::output_uvmap_to_off(sm, bhd, uv_map, out);
	return EXIT_SUCCESS;
}







------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Laurent Rineau"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月3日(星期五) 下午4:12
收件人:&nbsp;"CGAL/cgal"<cgal@noreply.github.com&gt;;
抄送:&nbsp;"张川"<1071244263@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [CGAL/cgal] Link CGAL with Eigen library! (#4442)




Your report is not really good, because you do not tell us how you have used CMake. Without that, I have to guess, and here is my advice: make sure you enable Eigen, in CMake, when you configure the example program, and not when you configure the CGAL libraries.

**Comment by lrineau** [comment]
That is still unclear. My guess is that you have used CMake, with `WITH_Eigen3`, to configure CGAL libraries. But then I do not understand how you have created the Visual Studio project that compiled `discrete_authalic.cpp`. If you had used CGAL CMake scripts, the Eigen libraries would have been configured correctly.

If you want to compile without our CMake script, and add `#define CGAL_EIGEN3_ENABLED` manually, then that macro definition must before you include CGAL headers, at the top of the .cpp file.

**Comment by KeepFaithMe** [comment]
Yeap! I used the CMAKE 3.9.0 with EIGEN_3 3.7 to configure CGAL libraries.By this method,I can get cgal lib,include and bin file,So when I create the project of parameterization surface mesh,I add the 'cgal include file path' into the Visual studio 2017 of property 'VC++ directory of include directory',add the 'cgal&nbsp; lib path ' into the Visual studio 2017 of property 'VC++ directory of library directory'.I used this method to configure my project.
But configured, I use this example&nbsp;https://doc.cgal.org/latest/Surface_mesh_parameterization/Surface_mesh_parameterization_2discrete_authalic_8cpp-example.html,the visual studio show:You must either provide 'SolverTraits_' or link CGAL with the Eigen library	.I am so confused,and don't kow how to deal with it.Is that clear?
looking forwarding to your reply!
good luck!






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Laurent Rineau"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月3日(星期五) 下午4:58
收件人:&nbsp;"CGAL/cgal"<cgal@noreply.github.com&gt;;
抄送:&nbsp;"张川"<1071244263@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [CGAL/cgal] Link CGAL with Eigen library! (#4442)




That is still unclear. My guess is that you have used CMake, with WITH_Eigen3, to configure CGAL libraries. But then I do not understand how you have created the Visual Studio project that compiled discrete_authalic.cpp. If you had used CGAL CMake scripts, the Eigen libraries would have been configured correctly.
 
If you want to compile without our CMake script, and add #define CGAL_EIGEN3_ENABLED manually, then that macro definition must before you include CGAL headers, at the top of the .cpp file.

**Comment by lrineau** [comment]
(@KeepFaithMe, this message is not for you.)

By the way, @MaelRL, there is an error in the logic you coded in 9eebcfbaacf7fb0076605c57de64f84d629a7d00. See for example:
https://github.com/CGAL/cgal/blob/76ff945bf47e9d6a123bf51670ba2f5fc88c32ea/Surface_mesh_parameterization/include/CGAL/Surface_mesh_parameterization/Barycentric_mapping_parameterizer_3.h#L75-L94

If `CGAL_EIGEN3_ENABLED` is not defined, then the `#pragma` directive will be issued by the preprocessor, and the compiler will interpret it even if the `SolverTraits_` template parameter is not `Default`.

It should be a static assertion, depending on the template parameter, like:
```c++
static_assert(!std::is_same<SolverTraits_, Default>::value, "You must ...");
````

**Comment by lrineau** [comment]
@KeepFaithMe Now I understand: as you have created the Visual studio project file yourself, without CMake, you must either:
  - add `#define CGAL_EIGEN3_ENABLED` as the **first line** of the .cpp file,
  - or add `CGAL_EIGEN3_ENABLED` in C++ preprocessor definitions (see https://stackoverflow.com/a/33470132/1728537 for explanations and a screenshot, in English).

@KeepFaithMe I let you close the issue, once you have found the solution.

**Comment by afabri** [comment]
Why does configuring Eigen not only shows up when a user selects WITH_EXAMPLES or WITH_DEMOS ?

**Comment by lrineau** [comment]
[**@afabri**](https://github.com/afabri) commented on [Jan 6, 2020, 9:57 AM GMT+1](https://github.com/CGAL/cgal/issues/4442#issuecomment-571058291 "2020-01-06T08:57:57Z - Replied by Github Reply Comments"):
> Why does configuring Eigen not only shows up when a user selects WITH_EXAMPLES or WITH_DEMOS ?

That is a left-over of the feature Eric named "preconfigured libraries". It is [documented in the installation manual of CGAL-4.14](https://doc.cgal.org/4.14/Manual/installation.html#secoptional3rdpartysoftware), and since CGAL-4.1.

That is something I hope we will clean in CGAL CMake scripts, soon or later.
