### ISSUE TITLE
Intersection_of_constraints_exception

### ISSUE THREAD

**Issue by KeepFaithMe** [CGAL/cgal#4447]
_Please use the following template to help us solving your issue._

## Issue Details

I want to clip the mesh using the '**clip()**'function,But my mesh has been processed by other algorithms,so there will be _self-intersecting cases_.Before using the clip() function,I using the function **PMP::remove_self_intersections(mesh)**;but after using this function,there is still a error:Intersection_of_constraints_exception,so there is some wrong but I don't kown.So How can I handle it.
## Environment

* Operating system (Windows 64 bits):
CGAL Version 4.13.1

**Comment by MaelRL** [comment]
Please provide your code and input data.
