### ISSUE TITLE
Polyhedron demo: segfault with transparency of a Surface_mesh 

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#4449]
## Issue Details

I took `master` (c97123f303e41fd145d4df9bf62d2939f6b62163), and made a fresh build of the polyhedron demo. Build only the `off_plugin` target. Then open `cube.off`, set an alpha value, and rotate the camera. Segfault.

Depending on when the bug was introduce, please base the fix on `master` or a release branch.

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Fedora 31 (64 bits)
* Compiler: c++ (GCC) 9.2.1 20190827 (Red Hat 9.2.1-1)

* Release or debug mode: none (`-- USING CXXFLAGS = ' -fvisibility=hidden '`)

* Specific flags used (if any):

**Comment by maxGimeno** [comment]
I'm quite sure #4394 fixes it.

**Comment by lrineau** [comment]
[**@maxGimeno**](https://github.com/maxGimeno) commented on [Jan 7, 2020, 3:36 PM GMT+1](https://github.com/CGAL/cgal/issues/4449#issuecomment-571612835 "2020-01-07T14:36:26Z - Replied by Github Reply Comments"):
> I'm quite sure #4394 fixes it. (fb25130)

I just tried (by merge #4394 in `master`), and #4394 does not fix the segfault.

**Comment by maxGimeno** [comment]
It was a local bug, related to the preferences. I added a commit to force the minimum value of the transparency passes to 4 as it should be, in case the preferences file is corrupted (or simply too old).
