### ISSUE TITLE
Intersection_of_constraints_exception when cliping the mesh

### ISSUE THREAD

**Issue by KeepFaithMe** [CGAL/cgal#4451]
## Issue Details
I have a mesh ,the data format is obj.Firstly I use the function  'read_OBJ' read the data.Next,I want to clip the mesh into 64 parts,finally,throw the error Intersection_of_constraints_exception.the codes as follows,the data is here: https://gist.github.com/KeepFaithMe/0ba6e0b71d014459042cd9a9dc531ddb

## Source Code
```c++
#include<iostream>
#include<fstream>
#include<CGAL/Polygon_mesh_processing/clip.h>
#include<CGAL/IO/OBJ_reader.h>
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/Polyhedron_3.h>
#include <CGAL/Polygon_mesh_processing/orient_polygon_soup.h>
#include <CGAL/Polygon_mesh_processing/polygon_soup_to_polygon_mesh.h>
#include <CGAL/Polygon_mesh_processing/orientation.h>

typedef CGAL::Exact_predicates_inexact_constructions_kernel Kernel;
typedef Kernel::Point_3 Point_3;
typedef CGAL::Polyhedron_3<Kernel> Polygon_3;

namespace PMP = CGAL::Polygon_mesh_processing;
namespace params = PMP::parameters;
using namespace std;
void CgalReadObj(Polygon_3& mesh, const std::string path)
{
	std::ifstream input(path);
	if (!input)
	{
		std::cerr << "Cannot open file" << std::endl;
		return;
	}
	std::vector<Kernel::Point_3>points;
	std::vector<std::vector<std::size_t>>polygons;
	if (!CGAL::read_OBJ(input, points, polygons))
	{
		std::cerr << "Error parsing the obj file " << std::endl;
		return;
	}
	CGAL::Polygon_mesh_processing::orient_polygon_soup(points, polygons);
	CGAL::Polygon_mesh_processing::polygon_soup_to_polygon_mesh(points, polygons, mesh);
}
void ClipMesh(Polygon_3& surface_mesh, std::queue<Polygon_3>& queue_meshes, int flag)
{
	std::queue<Polygon_3> mesh_queue_2;
	queue_meshes.push(surface_mesh);
	while (queue_meshes.size() != flag) {
		if (queue_meshes.size() != 0) {
			while (!queue_meshes.empty()) {
				Polygon_3 mesh = queue_meshes.front();
				queue_meshes.pop();
				if (PMP::does_self_intersect(mesh)) {
					PMP::remove_self_intersections(mesh);
				}
				Polygon_3 mesh_x(mesh);
				Polygon_3 mesh_xx(mesh);

				//clip
				//[1]get half of the mesh
				CGAL::Bbox_3 bb_3 = PMP::bbox(mesh_x);
				double x_d = (bb_3.xmin() + bb_3.xmax()) / 2;
				Kernel::Plane_3 plane_1(1, 0, 0, -x_d);//left side
				PMP::clip(mesh_x, plane_1, 
  params::clip_volume(false).throw_on_self_intersection(false));
				mesh_queue_2.push(mesh_x);
				//[2]get another half of the mesh
				Kernel::Plane_3 plane_2(-1, 0, 0, x_d);
				PMP::clip(mesh_xx, plane_2, params::clip_volume(false).throw_on_self_intersection(false));
				mesh_queue_2.push(mesh_xx);
			}
		}
		else if (mesh_queue_2.size() != 0) {
			while (!mesh_queue_2.empty()) {
				Polygon_3 mesh = mesh_queue_2.front();
				mesh_queue_2.pop();
				if (PMP::does_self_intersect(mesh)) {
					PMP::remove_self_intersections(mesh);
				}
				Polygon_3 mesh_y(mesh);
				Polygon_3 mesh_yy(mesh);
				//clip
				//[1]get half of the mesh
				/*CGAL::Bbox_3 bb_3 = GetModelBuondingBox(mesh_y);*/
				CGAL::Bbox_3 bb_3 = PMP::bbox(mesh_y);
				double y_d = (bb_3.ymin() + bb_3.ymax()) / 2;
				Kernel::Plane_3 plane_1(0, 1, 0, -y_d);
				PMP::clip(mesh_y, plane_1, params::clip_volume(false).throw_on_self_intersection(false));
				//PMP::remove_self_intersections(mesh_y);
				queue_meshes.push(mesh_y);
				//[2]get another half of the mesh
				Kernel::Plane_3 plane_2(0, -1, 0, y_d);
				PMP::clip(mesh_yy, plane_2, params::clip_volume(false).throw_on_self_intersection(false));
				//PMP::remove_self_intersections(mesh_yy);
				queue_meshes.push(mesh_yy);
			}
		}
	}
}
void main() {
	std::string path = "./Tile_1322333221331000333.obj";
	Polygon_3 mesh;
	std::queue<Polygon_3> queue_meshes;
	CgalReadObj(mesh, path);
	ClipMesh(mesh, queue_meshes, 16);
}
```
another question:why always Triggering a breakpoint under the Debug mode,when using the ofstream to write the data.
## Environment

* Operating system Windows 10   x64
*CGAL Version 4.13.1
*release mode

**Comment by KeepFaithMe** [comment]
Is there a method can handle this problem?or whether I have something wrong in my code?could you please give me some advice!

**Comment by KeepFaithMe** [comment]
Microsoft C++ exception: CGAL::Constrained_triangulation_2<CGAL::Triangulation_2_projection_traits_3<CGAL::Epeck,1>,CGAL::Triangulation_data_structure_2<CGAL::Triangulation_vertex_base_with_info_2<unsigned __int64,CGAL::Triangulation_2_projection_traits_3<CGAL::Epeck,1>,CGAL::Triangulation_vertex_base_2<CGAL::Triangulation_2_projection_traits_3<CGAL::Epeck,1>,CGAL::Triangulation_ds_vertex_base_2<void> > >,CGAL::Constrained_triangulation_face_base_2<CGAL::Triangulation_2_projection_traits_3<CGAL::Epeck,1>,CGAL::Triangulation_face_base_2<CGAL::Triangulation_2_projection_traits_3<CGAL::Epeck,1>,CGAL::Triangulation_ds_face_base_2<void> > > >,CGAL::Default>::Intersection_of_constraints_exception

**Comment by sloriot** [comment]
The exception is triggered because you have self-intersections in your input mesh (you would get a proper exception if you set [throw_on_self_intersection](https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__corefinement__grp.html#ga30082762ba2d947cba304e2884d96a99) to true when calling `clip()`.

**Comment by lrineau** [comment]
Suggestion: `clip()` should catch that exception (emitted by CDT_2), and throw a new one with a better name, so that CGAL users can understand the issue by themselves.

**Comment by KeepFaithMe** [comment]
I called the function 'PMP::remove_self_intersections(mesh)',but he didn't work

**Comment by KeepFaithMe** [comment]
hello:
     Is there a method can handle my peoblem?could you please give me some advice. I use the cgal version 4.14.2

**Comment by sloriot** [comment]
I have some experimental code that is doing the clipping on self-intersecting meshes (provided the clipper is free from self-intersections). You can send me an email if you want to discuss how we could setup an early access.

**Comment by KeepFaithMe** [comment]
> I have some experimental code that is doing the clipping on self-intersecting meshes (provided the clipper is free from self-intersections). You can send me an email if you want to discuss how we could setup an early access.

Thank you for your reply! my emailis: 1071244263@qq.com 
thank you again!

**Comment by KeepFaithMe** [comment]
> I have some experimental code that is doing the clipping on self-intersecting meshes (provided the clipper is free from self-intersections). You can send me an email if you want to discuss how we could setup an early access.

this is my Gmail: justdoitzc@gmail.com
