### ISSUE TITLE
CGAL install failed when building package mpfr

### ISSUE THREAD

**Issue by Timbersaw-wangzw** [CGAL/cgal#4452]
Hi Developer,
Recently I tried to install CGAL in vcpkg,but it installed failed when buiding package mpfr

## Issue Details
download mpfr successfully but build failed

## Source Code
Additional packages (*) will be modified to complete this operation.
Starting package 1/89: mpfr:x86-windows
Building package mpfr[core]:x86-windows...
-- Downloading http://www.mpfr.org/mpfr-4.0.2/mpfr-4.0.2.tar.xz...
-- Extracting source F:/PostgraduateStudy/Code/GitHub/vcpkg/downloads/mpfr-4.0.2.tar.xz
-- Using source at F:/PostgraduateStudy/Code/GitHub/vcpkg/buildtrees/mpfr/src/mpfr-4-e3d076d3ce
-- Configuring x86-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: ninja -v
    Working Directory: F:/PostgraduateStudy/Code/GitHub/vcpkg/buildtrees/mpfr/x86-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      F:\PostgraduateStudy\Code\GitHub\vcpkg\buildtrees\mpfr\config-x86-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:293 (vcpkg_execute_required_process)
  ports/mpfr/portfile.cmake:16 (vcpkg_configure_cmake)
  scripts/ports.cmake:94 (include)

Error: Building package mpfr:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: mpfr:x86-windows
  Vcpkg version: 2019.09.12-nohash

Additionally, attach any relevant sections from the log files above.
[
[config-x86-windows-out.log](https://github.com/CGAL/cgal/files/4033813/config-x86-windows-out.log)
](url)
## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):win10 64bit
* Compiler:Visual Studio 2017 (Toolset v141)
* Release or debug mode:
* Specific flags used (if any):
* CGAL version:
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by lrineau** [comment]
Hi @Timbersaw-wangzw,

You should do what is suggested by the error message:
> Error: Building package mpfr:x86-windows failed with: BUILD_FAILED
> Please ensure you're using the latest portfiles with .\vcpkg update, then
> submit an issue at Microsoft/vcpkg/issues including:
> Package: mpfr:x86-windows
> Vcpkg version: 2019.09.12-nohashHi @Timbersaw-wangzw,

Probably `vcpkg update` will solve your issue. You version of vcpkg
seem old (September 2019), and older than the release of CGAL-5.0,
anyway.

**Comment by lrineau** [comment]
Let us know if that worked, so that we can close this issue ticket.

**Comment by Timbersaw-wangzw** [comment]
Unfortunately,the output is No packages need updating.It doesn't seem to work

**Comment by Timbersaw-wangzw** [comment]
> Let us know if that worked, so that we can close this issue ticket.

Unfortunately,the output is No packages need updating.It doesn't seem to work

**Comment by lrineau** [comment]
You should know more about the issue, by reading the file `F:\PostgraduateStudy\Code\GitHub\vcpkg\buildtrees\mpfr\config-x86-windows-out.log`.

**Comment by Timbersaw-wangzw** [comment]
> You should know more about the issue, by reading the file `F:\PostgraduateStudy\Code\GitHub\vcpkg\buildtrees\mpfr\config-x86-windows-out.log`.

Coulde you help me to read this .log file?I'm new to this.thanks a lot[‪F:\PostgraduateStudy\Code\GitHub\vcpkg\buildtrees\mpfr\config-x86-windows-out.log](url)

**Comment by lrineau** [comment]
Actually, I did not see that the file was attached to this Github issue. I read:
```
cmd /c "cd .. && "F:/PostgraduateStudy/Code/GitHub/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/bin/cmake.exe" "F:/PostgraduateStudy/Code/GitHub/vcpkg/buildtrees/mpfr/src/mpfr-4-e3d076d3ce" "-DCMAKE_MAKE_PROGRAM=C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=F:/PostgraduateStudy/Code/GitHub/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x86-windows" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v141" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=F:/PostgraduateStudy/Code/GitHub/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_TARGET_ARCHITECTURE=x86" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=F:/PostgraduateStudy/Code/GitHub/vcpkg/packages/mpfr_x86-windows""
CMake Error at F:/PostgraduateStudy/Code/GitHub/vcpkg/scripts/buildsystems/vcpkg.cmake:3:
  Parse error.  Expected a command name, got unquoted argument with text
  "-DCMAKE_TOOLCHAIN_FILE=[vcpkg".
Call Stack (most recent call first):
  F:/PostgraduateStudy/Code/GitHub/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/share/cmake-3.14/Modules/CMakeDetermineSystem.cmake:93 (include)
  CMakeLists.txt:3 (project)
```

It seems the file `F:/PostgraduateStudy/Code/GitHub/vcpkg/scripts/buildsystems/vcpkg.cmake` is wrong. I suggest you reinstall `vcpkg`, or at least reset it:

```
cd  F:/PostgraduateStudy/Code/GitHub/vcpkg/
git checkout scripts/buildsystems/vcpkg.cmake
git pull
```

**Comment by Timbersaw-wangzw** [comment]
> Actually, I did not see that the file was attached to this Github issue. I read:
> 
> ```
> cmd /c "cd .. && "F:/PostgraduateStudy/Code/GitHub/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/bin/cmake.exe" "F:/PostgraduateStudy/Code/GitHub/vcpkg/buildtrees/mpfr/src/mpfr-4-e3d076d3ce" "-DCMAKE_MAKE_PROGRAM=C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=F:/PostgraduateStudy/Code/GitHub/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x86-windows" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v141" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=F:/PostgraduateStudy/Code/GitHub/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_TARGET_ARCHITECTURE=x86" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=F:/PostgraduateStudy/Code/GitHub/vcpkg/packages/mpfr_x86-windows""
> CMake Error at F:/PostgraduateStudy/Code/GitHub/vcpkg/scripts/buildsystems/vcpkg.cmake:3:
>   Parse error.  Expected a command name, got unquoted argument with text
>   "-DCMAKE_TOOLCHAIN_FILE=[vcpkg".
> Call Stack (most recent call first):
>   F:/PostgraduateStudy/Code/GitHub/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/share/cmake-3.14/Modules/CMakeDetermineSystem.cmake:93 (include)
>   CMakeLists.txt:3 (project)
> ```
> 
> It seems the file `F:/PostgraduateStudy/Code/GitHub/vcpkg/scripts/buildsystems/vcpkg.cmake` is wrong. I suggest you reinstall `vcpkg`, or at least reset it:
> 
> ```
> cd  F:/PostgraduateStudy/Code/GitHub/vcpkg/
> git checkout scripts/buildsystems/vcpkg.cmake
> git pull
> ```

thank you very much! it works!Thank you for patience

**Comment by lrineau** [comment]
Good! I am glad we managed to find the solution, even if that was not CGAL's fault by vcpkg's... I close the issue now.
