### ISSUE TITLE
PMP: warning about empty range in is_outward_oriented()

### ISSUE THREAD

**Issue by for-heart-peace** [CGAL/cgal#4456]
CGAL warning: check violation!
Expression : faces(pmesh).first != faces(pmesh).second
File       : C:\dev\CGAL-4.14.1\include\CGAL/Polygon_mesh_processing/orientation.h
Line       : 182
Explanation:
Refer to the bug-reporting instructions at https://www.cgal.org/bug_report.html

**Comment by afabri** [comment]
@sloriot why do we warn on this.  I can also apply  `std::sort()`  on an empty range.

**Comment by sloriot** [comment]
No idea, maybe somebody (you ? ;) ) complained that we should warn?

**Comment by sloriot** [comment]
```
commit 49818d56ce746b2b40900cd31b2c61c125a5d9ba
Author: Jane Tournois <jane.tournois@geometryfactory.com>
Date:   Tue Apr 18 10:26:23 2017 +0200

    add a runtime warning and return true for empty mesh
```

**Comment by sloriot** [comment]
@janetournois shall we remove this warning?

**Comment by janetournois** [comment]
I guess we can, since the code simply returns `true` when the mesh is empty.

I find such warnings handy for debug purposes, but then it could be protected by a `CGAL_PMP_DEBUG_CODE` macro - or just removed
