### ISSUE TITLE
How to use AABB Tree do_intersect() and first_intersection()

### ISSUE THREAD

**Issue by for-heart-peace** [CGAL/cgal#4457]
Have a example?

**Comment by MaelRL** [comment]
The document for the AABB tree is [here](https://doc.cgal.org/latest/AABB_tree/index.html) with some examples [there](https://doc.cgal.org/latest/AABB_tree/examples.html).

**Comment by for-heart-peace** [comment]
I am a rookie, The document for the AABB tree not have do_intersect() and first_intersection(). : )

**Comment by MaelRL** [comment]
They are:

Documentation for first intersection: https://doc.cgal.org/latest/AABB_tree/classCGAL_1_1AABB__tree.html#a8395a234825644b42619aee0829a3a13
Example for first intersection: https://doc.cgal.org/latest/AABB_tree/AABB_tree_2AABB_ray_shooting_example_8cpp-example.html
Doc for do_intersect: https://doc.cgal.org/latest/AABB_tree/index.html
Example with do_intersect: https://doc.cgal.org/latest/AABB_tree/AABB_tree_2AABB_polyhedron_facet_intersection_example_8cpp-example.html

**Comment by for-heart-peace** [comment]
Thank you very mush
