### ISSUE TITLE
Instantiate new geometry traits

### ISSUE THREAD

**Issue by chenming-wu** [CGAL/cgal#4458]
https://github.com/CGAL/cgal/blob/a9dc4c04440f5d540e1b955a9d7089e66f078c26/Mesh_2/include/CGAL/Delaunay_mesh_size_criteria_2.h#L114

Hi! I would like to ask why we don't use traits from the bad class here? I used `Triangulation_2_projection_traits_3` in my code but this trait doesn't have a default constructor to compile the `Delaunay_mesh_size_criteria`. Thanks!

**Comment by lrineau** [comment]
You are right. I have created the pul-request #4461 to fix that issue.
