### ISSUE TITLE
Shape_detection : interface with a Open3D Pointcloud

### ISSUE THREAD

**Issue by HndsmJohn** [CGAL/cgal#4462]
_Please use the following template to help us solving your issue._

## Issue Details

Hello, 
I am currently working on a project that uses Open3D pointclouds and I was interested in the Shape Detection algorithm implemented by the CGAL Library.  

Following this [example](https://cgal.geometryfactory.com/CGAL/doc/master/Shape_detection/Shape_detection_2efficient_RANSAC_with_parameters_8cpp-example.html), I tried to mimic the behaviour of the `CGAL::read_xyz_points` function, in order to use an already existing open3D pointcloud instead of reading a file. To test that, I used the cube.pwn data file provided in the example folder of the Shape Detection package. I then compared the result of the Efficient RANSAC shape extraction algorithm for a Point vector filled by the `read_xyz_points` function, and one filled by my method. The parameters for the Efficient RANSAC are exactly the same, the ones that are provided in the example.

Here are a visualization of the result, with one different colour for each detected shape :
![Screenshot from 2020-01-10 14-21-22](https://user-images.githubusercontent.com/26006858/72155923-82cfae80-33b4-11ea-8ef0-b045a4c5536c.png)
![Screenshot from 2020-01-10 14-18-09](https://user-images.githubusercontent.com/26006858/72155868-5e73d200-33b4-11ea-9e41-f234e2b98743.png)

_(Top one is as provided in the example, bottom one is filled by myself)_

Is there a concept that I didn't fully grasp ? Is the way of creating the associated property maps correct ? 

Thank you in advance for your answer.

## Source Code
```
using pcd = open3d::geometry::PointCloud;

typedef CGAL::Simple_cartesian<double>                       K;
typedef K::FT                                                FT;
typedef std::pair<K::Point_3, K::Vector_3>                   Point_with_normal;
typedef std::vector<Point_with_normal>                       Pwn_vector;
typedef CGAL::First_of_pair_property_map<Point_with_normal>  Point_map;
typedef CGAL::Second_of_pair_property_map<Point_with_normal> Normal_map;

typedef CGAL::Shape_detection::Efficient_RANSAC_traits
<K, Pwn_vector, Point_map, Normal_map>             Traits;
typedef CGAL::Shape_detection::Efficient_RANSAC<Traits> Efficient_ransac;
typedef CGAL::Shape_detection::Cone<Traits>             Cone;
typedef CGAL::Shape_detection::Cylinder<Traits>         Cylinder;
typedef CGAL::Shape_detection::Plane<Traits>            Plane;
typedef CGAL::Shape_detection::Sphere<Traits>           Sphere;
typedef CGAL::Shape_detection::Torus<Traits>            Torus;

  Pwn_vector points_ex;
  std::ifstream stream((argc > 1) ? argv[1] : tgt_xyzn);

  //This block is as provided as the example
  if (!stream ||
    !CGAL::read_xyz_points(
      stream,
      std::back_inserter(points_ex),
      CGAL::parameters::point_map(Point_map()).
      normal_map(Normal_map()))) {

    std::cerr << "Error: cannot read file cube.pwn!" << std::endl;
    return EXIT_FAILURE;
  }

  //I first need to convert Pwn_vector into open3d::geometry::Pointcloud to convert it back later
  //std::shared_ptr for visualization purposes
  auto trgt_pcd =  std::make_shared<pcd>();
  for (auto &pwn : points_ex) {
    Eigen::Vector3d pcl_point;
    Eigen::Vector3d pcl_normal;
    pcl_point << pwn.first.x(), pwn.first.y(), pwn.first.z();
    pcl_normal << pwn.second.x(), pwn.second.y(), pwn.second.z();
    trgt_pcd->points_.push_back(pcl_point);
    trgt_pcd->normals_.push_back(pcl_normal);
  }

  size_t pcl_size = trgt_pcd->points_.size();
  Pwn_vector points_self;
  Point_map p_pm;
  Normal_map n_pm;

  //Then I convert it back into a Pwn_vector
  for (uint32_t i =0 ; i < pcl_size; i++) {
    Eigen::Vector3d *p_p, *p_n;
    p_p = &(trgt_pcd->points_[i]);
    p_n = &(trgt_pcd->normals_[i]);

    p_n->normalize();
    K::Point_3  p ((K::FT)(*p_p)(0), (K::FT)(*p_p)(1), (K::FT)(*p_p)(2));
    K::Vector_3 n ((K::FT)(*p_n)(0), (K::FT)(*p_n)(1), (K::FT)(*p_n)(2));

    Point_with_normal pwn;
    put(p_pm, pwn, p);
    put(n_pm, pwn, n);
    points_self.push_back(pwn);
  }

  Efficient_ransac ransac;
  //Either points_ex or points_self
  ransac.set_input(points_ex);
  ransac.add_shape_factory<Plane>();
  ransac.add_shape_factory<Sphere>();
  ransac.add_shape_factory<Cylinder>();
  ransac.add_shape_factory<Cone>();
  ransac.add_shape_factory<Torus>();

  Efficient_ransac::Parameters parameters;
  parameters.probability = 0.05;
  parameters.min_points = 200;
  parameters.epsilon = 0.002;
  parameters.cluster_epsilon = 0.01;
  parameters.normal_threshold = 0.90;

  ransac.detect(parameters);

  //This next part is for visualization
  Efficient_ransac::Shape_range shapes = ransac.shapes();
  Efficient_ransac::Shape_range::iterator it = shapes.begin();
  std::vector<std::shared_ptr<const open3d::geometry::Geometry>> pcl_list;

  while (it != shapes.end()) {
    std::vector<std::size_t>::const_iterator
    index_it = (*it)->indices_of_assigned_points().begin();
    auto pcl = std::make_shared<pcd>();

    while (index_it != (*it)->indices_of_assigned_points().end()) {
      const Point_with_normal &p = *(points.begin() + (*index_it));
      Eigen::Vector3d v;
      v << (double) p.first.x(), (double) p.first.y(), (double) p.first.z();
      pcl->points_.push_back(v);
      index_it ++;
    }

    pcl->PaintUniformColor(Eigen::Vector3d::Random());
    pcl_list.push_back(pcl);

    // Proceed with the next detected shape.
    it++;
  }

  const auto pcl_v_cpy = pcl_list;
  open3d::visualization::DrawGeometries(pcl_v_cpy);


```

## Environment

* Operating system : Ubuntu 16.04
* Compiler: gcc (6.5.0)
* CGAL version: 5.0 (Release Version)
* Boost version: 1.58.0
* Other libraries versions if used :
   * [Open3D](http://www.open3d.org/docs/0.7.0/cpp_api/index.html) (0.7.0) ([git](https://github.com/intel-isl/Open3D)) with all its dependencies (notably Eigen 3.2.92)

**Comment by danston** [comment]
Hi. I have only quickly looked at your code, but noticed a few weird things:

- line 29: you read points_ex from a file, but then when converting to pcd, you go over points in points1, which is empty. Did I miss something?

- line 46: when filling up trgt_pcd, you push pcl_point both to points_ and normals_. What is a reason for that?

**Comment by HndsmJohn** [comment]
Hi, 
- At line 29, that is a typo I made when pasting my code here. It should be points_ex instead. I will edit the issue to correct that.
- At line 46, it should be pcl_normal. And as expected that is the error that gave this result. I can't believe I didn't see that before... With that fixed, the result I get is similar to the example.

Thank you for your time

**Comment by danston** [comment]
Great. Glad to help.
