### ISSUE TITLE
Can not run the Demo

### ISSUE THREAD

**Issue by Timbersaw-wangzw** [CGAL/cgal#4466]
I tried to run the demo.Unfortunatly,The VS project failed to run although CMake configure and generate it successfully.The error is cannot open souce file ...qrc_CGAL.cpp...qrc_Input.cpp...qrc_File.cpp qrc_triangulation_2.cpp. Those files don't exist at all.
## Issue Details
1. can not run the project.
2. CMake configure and generate  successfully.
3. the CGAL_Qt5_moc_and _resources project builds failed.
4. the error is can not find source file that mentioned above.
_Describe your issue. Please be specific (compilation error, runtime error, unexpected behavior, wrong results, etc.)._

## Source Code

_If your issue arises by using CGAL in your own source code, please provide a minimalist example that we can compile easily to reproduce the bug. If your issue arises from using a CGAL program (demo, example, etc.), please let us know which one. Helping you solving an issue is much easier and efficient if we can reproduce it._

## Environment

* Operating system windows x64
* Compiler:visual studio 2017
* Release or debug mode: debug
* Specific flags used (if any):
* CGAL version:5.0
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by sloriot** [comment]
What version of QT5 are you using? [QT 5.9](https://doc.cgal.org/latest/Manual/thirdparty.html#title7) or later should be used.

**Comment by Timbersaw-wangzw** [comment]
> What version of QT5 are you using? [QT 5.9](https://doc.cgal.org/latest/Manual/thirdparty.html#title7) or later should be used.

My QT version is 5.9.4

**Comment by lrineau** [comment]
Hi @Timbersaw-wangzw, we'll try to help you. Can you please rerun the CMake configuration, and copy-paste what is displayed by CMake, entirely. If that is long, I suggest you copy-paste it to a website like https://gist.github.com/ and then give us the link.

Files like `qrc_CGAL.cpp` are supposed to be generated during the compilation, by a tool named `qrc` and from input files named like `CGAL.qrc`. When all run as it should be, the solution generated by CMake has all the steeps to build those files, before they are needed.

**Comment by Timbersaw-wangzw** [comment]
> Hi @Timbersaw-wangzw, we'll try to help you. Can you please rerun the CMake configuration, and copy-paste what is displayed by CMake, entirely. If that is long, I suggest you copy-paste it to a website like https://gist.github.com/ and then give us the link.
> 
> Files like `qrc_CGAL.cpp` are supposed to be generated during the compilation, by a tool named `qrc` and from input files named like `CGAL.qrc`. When all run as it should be, the solution generated by CMake has all the steeps to build those files, before they are needed.

Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.18362.
The C compiler identification is MSVC 19.16.27034.0
The CXX compiler identification is MSVC 19.16.27034.0
Check for working C compiler: D:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
Check for working C compiler: D:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Detecting C compile features
Detecting C compile features - done
Check for working CXX compiler: D:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
Check for working CXX compiler: D:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
Visual Leak Detector (VLD) is not found.
Using header-only CGAL
Targetting Visual Studio 15 2017
Target build enviroment supports auto-linking
Using VC toolset 141.
Generator uses intermediate configuration directory: $(Configuration)
Found GMP: E:/vcpkg/installed/x64-windows/debug/lib/mpir.lib  
Found MPFR: E:/vcpkg/installed/x64-windows/debug/lib/mpfr.lib  
Boost version: 1.71.0
Boost include dirs: E:/vcpkg/installed/x64-windows/include
Boost libraries:    
Configuring done
Generating done

**Comment by lrineau** [comment]
I do not understand. What do you call "The Demo". The CMake log you send us seems too short. On which source directory did you run CMake?

**Comment by Timbersaw-wangzw** [comment]
> I do not understand. What do you call "The Demo". The CMake log you send us seems too short. On which source directory did you run CMake?

i run the one of the demo project [
![image](https://user-images.githubusercontent.com/57893826/72346731-7c716780-3711-11ea-8eec-3c0b559f7b2c.png)
](url)

**Comment by lrineau** [comment]
@maxGimeno Have you checked if one can compile Qt5 demos from the vcpkg installation of CGAL?

**Comment by maxGimeno** [comment]
@lrineau Yes.
@Timbersaw-wangzw  Did you install cgal or cgal[qt5] with vcpkg ?

**Comment by Timbersaw-wangzw** [comment]
> @lrineau Yes.
> @Timbersaw-wangzw Did you install cgal or cgal[qt5] with vcpkg ?

I installed cgal with vcpkg but Qt dose not. Qt installed by the .exe

**Comment by lrineau** [comment]
If you did not install `cgal[qt5]` then the CGAL installation is missing the Qt5 support, even if you install Qt5 separately.
