### ISSUE TITLE
Installation is still required?

### ISSUE THREAD

**Issue by jiapei100** [CGAL/cgal#4476]
Even if cgal is a header only project, why not still provide the installation, let's say: at least provide the version number, and pkgconfig info - cgal.pc automatically?

**Comment by lrineau** [comment]
It is already the case. With CGAL-5.0, the header-only mode is the default. From a checkout of the Git repository, or from the decompressed tarball, you can use it directly without any installation. However, the CGAL project only supports CMake, and not pkgconfig files.
