### ISSUE TITLE
Demo crash(es)

### ISSUE THREAD

**Issue by MaelRL** [CGAL/cgal#4498]
## Issue Details

Load polygon mesh, add a selection item, shuffle, orient --> crash

"Move point" is still crashing the demo randomly on vertex de-selection, but I don't know how to reproduce it consistently

**Comment by maxGimeno** [comment]
>  on vertex de-selection

When you use ctrl+Z ?

**Comment by MaelRL** [comment]
I think so, but I can't reproduce it intentionally so I do not know what if it's the de-selection or the movement (usually I am not trying to reproduce the crash, so the commands are about at the same time).

**Comment by maxGimeno** [comment]
My guess would be that when you "collapse" a face (make it degenerate while moving the point), a normal becomes null and the drawing crashes. I'll have to secure the normal computation some more at some point. I'd rather have a false lighting on an invisible face than a crash.

**Comment by MaelRL** [comment]
Odds of creating actually degenerate faces are pretty slim (and I am usually trying to move points away from degeneracies to understand the mess that is underneath).

**Comment by lrineau** [comment]
Fixed by the merge of #4481 in `master`.
