### ISSUE TITLE
Submit patch to Boost Parameters to remove a warning in Mesh_3

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#45]
The CGAL project has minor patches to Boost libraries, to remove warnings in Mesh_3. Those patches should be submitted upstream.

**Comment by sloriot** [comment]
Fixed in [boost repository](https://github.com/boostorg/parameter/commit/45eebd0b854d7f75c572db2dc96e6afe0b5d623f)

**Comment by lrineau** [comment]
Can you remind which patches were submitted and and accepted?

I have one patch in Bimap:
```patch
diff --git a/include/boost/bimap/detail/debug/static_error.hpp b/include/boost/bimap/detail/debug/static_error.hpp
index cbb1cad..4e5cb26 100644
--- a/include/boost/bimap/detail/debug/static_error.hpp
+++ b/include/boost/bimap/detail/debug/static_error.hpp
@@ -25,7 +25,6 @@
 // a static error.
 /*===========================================================================*/
 #define BOOST_BIMAP_STATIC_ERROR(MESSAGE,VARIABLES)                           \
-        struct BOOST_PP_CAT(BIMAP_STATIC_ERROR__,MESSAGE) {};                 \
         BOOST_MPL_ASSERT_MSG(false,                                           \
                              BOOST_PP_CAT(BIMAP_STATIC_ERROR__,MESSAGE),      \
                              VARIABLES)
```

And it seems the other one was the one you committed in boostorg/parameter@45eebd0b854d7f75c572db2dc96e6afe0b5d623f

**Comment by sloriot** [comment]
The patch integrated is already mentioned in my previous comment.

**Comment by lrineau** [comment]
I close this issue. Followup in #219 for the patch to be submitted in Boost.Bimap.
