### ISSUE TITLE
Can a CGAL's shared library (lib[name].so) be used on a computer without the CGAL library downloaded??

### ISSUE THREAD

**Issue by vitsensei** [CGAL/cgal#4507]
I managed to create a shared library that use CGAL 5.0.1 extensively. Now, my question is, would it be possible if I take this new shared library to other computer without CGAL already installed.

From CGAL's website:

> Since CGAL version 5.0, CGAL is header-only be default, which means that there is no need to compile CGAL or its libraries before it can be used.

The way I understand this is that since there is no need to compile CGAL, there is no need to have CGAL library download, if we already have the shared library .so file. Is this correct? Thanks.

**Comment by lrineau** [comment]
Yes, you can distribute your shared library without the source code of CGAL.

But note that your shared library probably depends on dependencies of the CGAL code you have used, like libgmp.so.* and libmpfr.so.* (but maybe others).

**Comment by vitsensei** [comment]
Hi @lrineau, thanks for the quick answer.
You are absolutely correct. I just tried my .so library on another computer without the source code and it turns out I'm missing another dependancy libCGAL_Core.so

So, is there a way (I'm sure there is) to include CGAL_Core in my shared library too? Here's my attempt at the CMakeLists:
```
project( skeleton )

cmake_minimum_required(VERSION 2.8.11)

# CGAL and its components
find_package(CGAL QUIET COMPONENTS Core )

if ( NOT CGAL_FOUND )

  message(STATUS "This project requires the CGAL library, and will not be compiled.")
  return()  

endif()

# include helper file
include( ${CGAL_USE_FILE} )


# Boost and its components
find_package( Boost REQUIRED )

if ( NOT Boost_FOUND )

  message(STATUS "This project requires the Boost library, and will not be compiled.")

  return()  

endif()

include( CGAL_CreateSingleSourceCGALProgram )
add_library(skel SHARED skeleton_generation.cpp)
```

Thank you for your support. I'm still learning slowly...

**Comment by lrineau** [comment]
If your `.so` library requires `libCGAL.so` or `libCGAL_Core.so` then it means you have not compiled it using CGAL in header-only. Let's try to find why, with a few questions...

1. What is the value of `CGAL_DIR` in the `CMakeCache.txt` file in the build directory you used to produce your `libskel.so`? That value is the name of a directory. If you want to use CGAL as header-only, then put the root of the CGAL sources directory in `CGAL_DIR`.
2. What CGAL version was compiled into that directory pointed by `CGAL_DIR`?

**Comment by vitsensei** [comment]
Incredible! Thank you @lrineau.
I take a look again and it turns out the version I got is 4.11, which kinda make sense. I was expecting 5.0.1. I check again and it turns out the version that we get from apt-get is 4.11, not 5.0.1.

Anyways, long story short. I re-downloaded CGAL source code and got it working now.

**Comment by lrineau** [comment]
4.11 is rather old. Which version of Debian or Ubuntu are you using?

**Comment by vitsensei** [comment]
> 4.11 is rather old. Which version of Debian or Ubuntu are you using?

I'm using Ubuntu 18.04. I'm pretty new to Linux too, so I might have messed up something...
