### ISSUE TITLE
How would someone go about "slice" a mesh using a curve surface 

### ISSUE THREAD

**Issue by vitsensei** [CGAL/cgal#4509]
Hi,

Let's say I have an arbitrary manifold polyhedron mesh, and a 3d curve surface (I have not figured out how to represent this 3d curve yet). How should I go about using CGAL to compute the intersecting polyline between this curve and the mesh?

For example, my mesh would be a 3d box, and my curve would represent an infinitely long hollow tube. 

I know my question is not quite well defined. If you guys could give me at least a direction to look for, that would be great. Thanks.

**Comment by sloriot** [comment]
It depends on how you define the curved surface. If you can generate a triangle mesh for your curve surface, you can use [`surface_intersection()`](https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__corefinement__grp.html#ga09e9c6524834aebd2b2dcd5c0031d1d4). But it might be overkill, especially if you only want to get the intersection with an axis aligned box, in which case you might work directly on the curve surface equation.

Without much more details it is hard to help you further. I'm closing the issue for now. Feel free to continue posting here.

**Comment by vitsensei** [comment]
Thank you @sloriot,
The function you suggested is what I was looking for. You are right about it being overkill for the example that I represented.

Anyways. What I am actually interested in is to find the intersecting surface between two meshes, and then use that intersecting surface as a slicing curvature plane to slice another mesh. Do you think that finding the intersecting surface of two meshes is a solvable problem with CGAL?

[Here](https://imgur.com/undefined)'s one example I have. My goal is to find the square surface that the upper half of number 3 intersect with the lower half of number 3.

Thank you.

**Comment by sloriot** [comment]
I think you can achieve what you want with the [`clip()`](https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__corefinement__grp.html#ga30082762ba2d947cba304e2884d96a99) function setting the option `clip_volume` to `false` and `use_compact_clipper` to `true`. You cannot use [`corefine_and_compute_intersection()`](https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__corefinement__grp.html#ga240e5df984c7d44741a7031e38203dc3) as it handle volume intersection.
