### ISSUE TITLE
Best way to extract the "top of the roof"/root of a straight skeleton?

### ISSUE THREAD

**Issue by vitsensei** [CGAL/cgal#4515]
Hi,
I have been thinking about this problem for a very long time now and until now, I have not figured out the correct answer. Hopefully someone smarter can give me a suggestion.

Anyways, let's say I have a 2D Straight Skeleton such as [this](https://imgur.com/UROQtHA) and would like to extract the rooftop as highlighted in red [here](https://imgur.com/kheaIba). 

My current method is as follow:
- Remove all contour edges.
- Now, remove all edges that makes of 1 degree vertex and another vertex with degree >=3. This helps me to remove (most) of the "leaf" edge. Continue doing so until there is no such vertex.

About half of the time, I achieve what I wanted. However sometimes, after step 2, there are a few more leaf branches ([example](https://imgur.com/AL0TcMF)).

Is there any other more effective methods for doing so?

Thank you.

edit: I made a mistake stating my method, it should be "and another vertex with degree >= **3**" rather than "and another vertex with degree >= **2**"

**Comment by sloriot** [comment]
I would work at the vertex level. I would flag vertices that are incident to 1 or 2 edges that are not contour edges (you can use `h->is_contour()` for that purpose). Those vertices are the one that are to be removed and so are all the edges incident to them. That way you have a non-recursive procedure that is deterministic and should be doing what you want.

I'm closing the issue, do not hesitate to re-open it in case I did not answer your question.
