### ISSUE TITLE
HOw to get skelton index given the vertex index

### ISSUE THREAD

**Issue by abuzaina** [CGAL/cgal#4518]
I would like to get the index for the skeleton point given the mesh point, it seems there isn't a way to do so.
In the example in [this link](https://doc.cgal.org/latest/Surface_mesh_skeletonization/Surface_mesh_skeletonization_2MCF_Skeleton_sm_example_8cpp-example.html), you can get the mesh point given the skeleton point.

``` 
 for(Skeleton_vertex v : CGAL::make_range(vertices(skeleton)))
    for(vertex_descriptor vd : skeleton[v].vertices)
      output << "2 " << skeleton[v].point << "  " << get(CGAL::vertex_point, tmesh, vd)  << "\n";
```

I want to do the opposite, which is find the skeleton point from a given mesh vertex, is there a quiq way to do so ? 

Thanks

**Comment by sloriot** [comment]
You can build that map yourself using the aforementioned loop. If your input mesh is a `Surface_mesh` then you can use an [internal property map](https://doc.cgal.org/latest/Surface_mesh/#title7).

**Comment by abuzaina** [comment]
@sloriot can you please provide an example? it is not a Surface_mesh, I have not been able to create that map.

**Comment by sloriot** [comment]
Something like that (did not check if it compiles)
```
std::map<vertex_descriptor, Skeleton_vertex> my_map;
for(Skeleton_vertex v : CGAL::make_range(vertices(skeleton)))
  for(vertex_descriptor vd : skeleton[v].vertices)
    my_map[vd]=v;
```
