### ISSUE TITLE
Infinite loop in PMP::corefine_and_compute_union since 4.14.2

### ISSUE THREAD

**Issue by gilesp1729** [CGAL/cgal#4522]
When corefining and unioning two closed, non-self-intersecting meshes, an infinite loop is occasionally seen. This is new with 4.14.2 and also in 5.x (it did not happen in 4.12). It only happens (apparently) when the output mesh is the same as one of the inputs.

OFF files and demo code are in
https://www.dropbox.com/sh/0q1i263zkjjjv3o/AAAz27BUXGYUBqRGZDnTi_v3a?dl=0
The demo code can be built in the PMP examples environment (it's a mod of an existing sample)

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows 10
* Compiler: Visual Studio 2019, 32-bit, tool set 1.42
* Release or debug mode: Debug
* Specific flags used (if any):
* CGAL version: 4.14.2 or later
* Boost version: 1.67.0
* Other libraries versions if used (Eigen, TBB, etc.): none

**Comment by sloriot** [comment]
Fixed by #4524

**Comment by sloriot** [comment]
In passing, in the last named parameter, the vertex point map should be the one from `mesh2` and not `mesh1` (since it is the output).

**Comment by lrineau** [comment]
Fixed by the merge of #4524 in 4.14.x.
