### ISSUE TITLE
Demo: cannot stop offset meshing

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#4525]
When trying to stop a offset meshing in the demo, I get a crash of the demo with the message in the terminal: "libgcc_s.so.1 must be installed for pthread_cancel to work". It is strange since I can cancel a `Mesh_3` run.

**Comment by lrineau** [comment]
In that plugin, the stop button calls [`QThread::terminate()`](https://doc.qt.io/qt-5/qthread.html#terminate), to "kill" the thread, whereas in the Mesh_3 plugin, the stop button just asks the Mesh_3 algorithm to stop (using an atomic Boolean variable).

The error message you get is strange. Why does not your machine have `libgcc_s.so.1`. Maybe the plugin should be linked with pthread:
```cmake
find_package(Threads)
target_link_libraries( offset_meshing_plugin PRIVATE Threads::Threads)
```

**Comment by maxGimeno** [comment]
Are you using a specific config, like not header only or something ?

**Comment by lrineau** [comment]
Actually, I do not think linking with pthread can solve that issue. I [googled the error message](https://www.google.com/search?q=%22libgcc_s.so.1+must+be+installed+for+pthread_cancel%22) and all the answers just explain how to install `libgcc_s.so.1`... On my Fedora machine, `libgcc_s.so.1` cannot even be removed, otherwise the whole system goes away with it. I am surprised that you do not have it installed on you machine. Which OS is that, @sloriot?

**Comment by lrineau** [comment]
Actually, on my Fedora again, linking with pthread triggers the linking with `-lgcc_s` as well. Maybe on your machine that is a static library `libgcc_s.a`.

**Comment by sloriot** [comment]
Building only `off_plugin` and `offset_meshing_plugin` does not trigger the error, but when building all plugins I got the error.

**Comment by lrineau** [comment]
@sloriot Please answer my question: which OS?

Which version of gcc? Which version of glibc?

**Comment by lrineau** [comment]
It might also be interesting to see the output log when you set `LD_DEBUG=libs` in the environment. The log will be huge, with the polyhedron demo, but the interesting part is only the one just after you click on the stop button (with all plugins).

pthread dlopen libgcc_s.so.1 at runtime, and it seems that the dlopen fails on your machine, for an unknown reason.

**Comment by sloriot** [comment]
I indicated in pm to @maxGimeno  that not linking with 3MF plugin removed the issue and the debug flags stays: `     22680:	/usr/lib/x86_64-linux-gnu/lib3MF.so.1: error: symbol lookup error: undefined symbol: zip_fclose (fatal)`

**Comment by sloriot** [comment]
g++ (Debian 8.3.0-2) 8.3.0 + libstdc++-8.3.0-2

**Comment by sloriot** [comment]
Linux haring 4.19.0-5-amd64 #1 SMP Debian 4.19.37-5 (2019-06-19) x86_64 GNU/Linux

**Comment by lrineau** [comment]
@sloriot @maxGimeno What is the conclusion of that discussion?

**Comment by maxGimeno** [comment]
I don't know. @sloriot did you try again with [my updates on lib3MF](https://github.com/CGAL/cgal/pull/4532) ?

**Comment by sloriot** [comment]
@maxGimeno  Your PR is not related to this issue but let's close it as it seems to be an issue with the way debian compiled lib3MF (not linked with zlib).

**Comment by lrineau** [comment]
Then why not link our 3mf plugin with libzip (not zlib) as well?

**Comment by sloriot** [comment]
Already try, it does not work
