### ISSUE TITLE
Is it possible to make write_ply_points() write ply in "float" rather than "double" , and how?

### ISSUE THREAD

**Issue by leelele-cug** [CGAL/cgal#4526]
## Issue Details

I first use `read_ply_points()` function to read a ply file whose data is "float", but when I use `write_ply_points()` function to write the result into a new ply file, the new file's data become "double". My question is : Is it possible to make write_ply_points() write ply in "float" rather than "double" ?

## Part of the Source Code

```
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/compute_average_spacing.h>
#include <CGAL/pca_estimate_normals.h>
#include <CGAL/mst_orient_normals.h>
#include <CGAL/property_map.h>
#include <CGAL/IO/read_ply_points.h>
#include <CGAL/IO/write_ply_points.h>
#include <utility> // defines std::pair
#include <list>
#include <fstream>

// Types
typedef CGAL::Exact_predicates_inexact_constructions_kernel Kernel;
typedef Kernel::Point_3 Point;
typedef Kernel::Vector_3 Vector;

// Point with normal vector stored in a std::pair.
typedef std::pair<Point, Vector> PointVectorPair;

int main(int argc, char*argv[])
{
    // Reads a .xyz point set file in points[].
    std::list<PointVectorPair> points;
    std::ifstream stream(input_filename);
    if (!stream ||
        !CGAL::read_ply_points(
			stream,std::back_inserter(points),
			CGAL::parameters::point_map(CGAL::First_of_pair_property_map<PointVectorPair>()).
			normal_map(CGAL::Second_of_pair_property_map<PointVectorPair>())))
    {
      std::cerr << "Error: cannot read file " << fname<< std::endl;
        return EXIT_FAILURE;
    }

	// Saves point set.
	std::ofstream out(output_filename);
	out.precision(6);
	if (!out ||
		!CGAL::write_ply_points(
			out, points,
			CGAL::parameters::point_map(CGAL::First_of_pair_property_map<PointVectorPair>()).
			normal_map(CGAL::Second_of_pair_property_map<PointVectorPair>())))
	{
		return EXIT_FAILURE;
	}
    return EXIT_SUCCESS;
}
```
## Input file header
```
ply
format ascii 1.0
comment VCGLIB generated
element vertex 25894
property float x
property float y
property float z
property float nx
property float ny
property float nz
end_header
```
## Output file header
```
ply
format ascii 1.0
comment Generated by the CGAL library
element vertex 25894
property double x
property double y
property double z
property double nx
property double ny
property double nz
end_header
```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows 10, 64bit
* Compiler: MSVC 15 (VS2017)
* Release or debug mode:
* Specific flags used (if any):
* CGAL version: 5.0.1
* Boost version: 1.71.0
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by sgiraudot** [comment]
The PLY IO in CGAL uses the floating type of the kernel to determine what floating type should be written: in your case, with `CGAL::Exact_predicates_inexact_constructions_kernel`, `double` is chosen. The only way to work directly with `floats` is to use `CGAL::Simple_cartesian<float>` as a Kernel.

Note that if you still want to use EPICK (or another non-float kernel) while still writing floats in your PLY output, it is possible, but it requires a bit more work (namely, you should write a property map that converts on the fly `EPICK::Point_3` to `Simple_cartesian<float>::Point_3` and pass it to `write_ply_points()`, same for normals).

**Comment by LeeXTZ** [comment]
Thank you for taking the trouble to help me. 

I changed `CGAL::Exact_predicates_inexact_constructions_kernel` into `CGAL::Simple_cartesian<float> `, then it works. 

Thanks a lot!
