### ISSUE TITLE
Documentation Bug - Homogenous Coordinates 

### ISSUE THREAD

**Issue by agnat** [CGAL/cgal#453]
The [section on homogenous coordinates](https://github.com/CGAL/cgal/blob/master/Documentation/doc/Documentation/Developer_manual/Chapter_kernels.txt#L46) in https://github.com/CGAL/cgal/blob/master/Documentation/doc/Documentation/Developer_manual/Chapter_kernels.txt states:

> Since CGAL uses homogeneous representation for affine geometry and not for projective geometry, the homogenizing coordinate is non zero.

I might be mistaken, but I believe this is trivially true and not really what you want to say. The homogenizing coordinate is _always_ non zero, since zero is mathematically boring and numerically catastrophic. What you want to say is that `w != 1`, no?

**Comment by sloriot** [comment]
I think the sentence is correct. We could add `always` in the sentence if you think this improves the reading.

**Comment by agnat** [comment]
No worries. Re-reading it, it makes more sense. The first part of the section says: We don't use point's at infinity. It puzzled me for a second, because in a numeric context that is kind of implied.

I do think the text is a little fuzzy, but couldn't point out how to improve it. If I come up with something I'll make a PR.
