### ISSUE TITLE
Incorrect computation of StraightSkeleton

### ISSUE THREAD

**Issue by vryashkov** [CGAL/cgal#4533]
## Issue Details

Wrong results when computing a StraightSkeleton for a star shaped polygon using the CGAL examples. The results (refer to the image below) contain one extra arc (the last two bisectors in the output) as well as rounding errors.

## Source Code

```
#include<boost/shared_ptr.hpp>

#include<CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include<CGAL/Polygon_2.h>
#include<CGAL/create_straight_skeleton_2.h>

#include "print.h"

typedef CGAL::Exact_predicates_inexact_constructions_kernel K ;

typedef K::Point_2                   Point ;
typedef CGAL::Polygon_2<K>           Polygon_2 ;
typedef CGAL::Straight_skeleton_2<K> Ss ;

typedef boost::shared_ptr<Ss> SsPtr ;

int main()
{
    Polygon_2 poly;

    poly.push_back( Point( 0, 0 ) );
    poly.push_back( Point( 2000, 8000 ) );
    poly.push_back( Point( 10000, 10000 ) );
    poly.push_back( Point( 2000, 12000 ) );
    poly.push_back( Point( 0, 20000 ) );
    poly.push_back( Point( -2000, 12000 ) );
    poly.push_back( Point( -10000, 10000 ) );
    poly.push_back( Point( -2000, 8000 ) );

    // You can pass the polygon via an iterator pair
    SsPtr iss = CGAL::create_interior_straight_skeleton_2(poly.vertices_begin(), poly.vertices_end());
  
    print_straight_skeleton(*iss);
  
    return 0;
}
```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows 10
* Platform Toolset: Visual Studio 2015 (v140)
* Compiler: Visual C++ 14.0
* Release or debug mode: debug
* CGAL version: 5.0.1

The setup follows the CGAL documentation:
[Using CGAL on Windows](https://doc.cgal.org/latest/Manual/windows.html)

## Results

![cgal_sk](https://user-images.githubusercontent.com/8861137/74750206-a61b3280-526b-11ea-8b0f-ed4b238d630b.PNG)

**Comment by afabri** [comment]
The PR #4905 fixes this problem.
