### ISSUE TITLE
Documentation warnings in overnight build

### ISSUE THREAD

**Issue by albert-github** [CGAL/cgal#4548]
In the overnight builds CGAL-5.0.3-I-207 and CGAL-5.1-Ic-86 I see for the Polygon_mesh_processing package:
> todo:8: warning: unexpected token TK_COMMAND_BS as the argument of _internalref
> todo:21: warning: unexpected token TK_COMMAND_BS as the argument of _internalref

Looking a bit into the problem I see that the come from:
- the file Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/repair.h line 1201
  > /// \todo use the area criteria? this means maybe continue exploration of larger cc
- the file Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/merge_border_vertices.h line 112:
  > /// \todo shall we try to be more conservative?

this is in the middle of the method and doxygen has no idea where to place it, changing `///` into `//` will solve the issue.

Note: there is some more "documentation" in repair.h that start with `///` (e.g. line 1371), this is a bit a strange block as it looks like it is intended as a comment block, but most lines just have `//`  or the `///` has not been changed into `//`. (Looks like incorrect merges after the "big" change of:

> Commit: 0417bb88d77c652fd301787eb0b110ea062dd6b8 [0417bb8]
> Parents: 5b22f7213e
> Author: Mael Rouxel-Labbé <mael.rouxel.labbe@geometryfactory.com>
> Date: Wednesday, July 25, 2018 10:51:53 AM
> Committer: Mael Rouxel-Labbé
> Commit Date: Wednesday, July 25, 2018 10:53:30 AM
> Hide "remove_degenerate_faces"

**Comment by MaelRL** [comment]
The issue of some leftovers "///" in `remove_degenerate_faces` will be fixed with https://github.com/CGAL/cgal/pull/4140.

**Comment by MaelRL** [comment]
Fixed other cases in the same PRs. Thanks for the investigation.

**Comment by lrineau** [comment]
Hi @MaelRL, the bug is reported against CGAL-5.0.3-I-207, but the PR #4140 will only fix the issue in `master` and CGAL-5.1-dev. The fix will have to be backported to a bug-fix PR for 5.0.x.

**Comment by lrineau** [comment]
(As for 4.14.x, that release branch already have tonnes of warnings with recent Doxygen. We do not try to fix them.)
