### ISSUE TITLE
Convex partition

### ISSUE THREAD

**Issue by abuzaina** [CGAL/cgal#4567]
## Issue Details

I have a list of points that look like this (I get it from slicing a mesh). I want to partition this shape to 2 parts at the "bottle neck" and approximate the length of each part individually.
what is the best way to do so ?
I have tried using the example here but it seems it throws an error
https://doc.cgal.org/4.9.1/Partition_2/Partition_2_2approx_convex_partition_2_8cpp-example.html

`terminate called after throwing an instance of 'CGAL::Precondition_exception'
  what():  CGAL ERROR: precondition violation!
Expr: is_simple_2(first, last, traits) 
Thanks
`
![image](https://user-images.githubusercontent.com/6253920/76269336-6d4cf880-622e-11ea-9de3-4f593bfba064.png)

**Comment by MaelRL** [comment]
As the precondition indicates, your input must be a simple polygon. This apparently isn't the case of your input.

As for your problem, you could try to do optimal convex partitioning and then merge parts while keeping the smallest interface, or just look for the closest pair of sufficiently-separated vertices of your polygon.
