### ISSUE TITLE
[Shape Detection - Region growing] issue with degenerate faces

### ISSUE THREAD

**Issue by amyxlalala** [CGAL/cgal#4570]
_Please use the following template to help us solving your issue._

## Issue Details

I encountered a problem, when I try to run the example code of region_growing_on_polygon_mesh.cpp
in the shape detection package for mesh segmentation. 

It was stopped at the algorithm running step, which is region_growing.detect(std::back_inserter(regions)).

Still, using the example dataset is fine, but I tried to input another test dataset myself, it turns to collapse. This time I just compared the .off format of the files, they have definitely the same. I have tried several different datasets, and had the same errors. So it seems to be bugs in the codes, isn’t it?

Please see the error information in the attachment. Thank you very much!
[mesh_section_YA.zip](https://github.com/CGAL/cgal/files/4313565/mesh_section_YA.zip)

## Source Code

region_growing_on_polygon_mesh.cpp

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows10
* Compiler: Visual Studio 2017
* Release or debug mode: Release
* Specific flags used (if any):
* CGAL version:5.0.1
* Boost version:1.71.0
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by sloriot** [comment]
@danston the error comes from a degenerate face in the input [here](https://github.com/CGAL/cgal/blob/master/Shape_detection/include/CGAL/Shape_detection/Region_growing/Region_growing_on_polygon_mesh/Least_squares_plane_fit_region.h#L362).

**Comment by danston** [comment]
Ok, I see. If you have a degenerated face, then the normal estimation fails. I will have a look at this case and try to find a solution for the problem as soon as possible. Thank you for the bug report!

**Comment by amyxlalala** [comment]
Hi Dmitry,

Thanks for your information. I manually removed the degenerate triangles
and tried again, however, it still stopped at the region_growing.detect(),
with errors of assertion violation. I attach the error  screenshot. Could
you please have a look for the reason?

Thanks in advance!
Jinwei

**Comment by danston** [comment]
Ok, this is weird. I will check the whole code with your data and come back to you.

**Comment by sloriot** [comment]
FYI it works for me after removing the degenerate faces using the function in the polyhedron demo.

**Comment by amyxlalala** [comment]
May I ask how you remove the degenerate faces? Manually or by implementing
specific functions in CGAL?

I just remove the degenerate faces manually in MeshLab, and then read in
the program. It still causes errors.

**Comment by sloriot** [comment]
Basically using [this](https://github.com/CGAL/cgal/blob/master/Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/repair.h#L2210) undocumented function.

**Comment by amyxlalala** [comment]
Ok. Thanks a lot!

**Comment by danston** [comment]
Hi @amyxlalala . The fix is here #4574. You can clone that PR and try it out. Please let me know if it works.

**Comment by amyxlalala** [comment]
Thanks a lot for your effort.

I just simply had a try, however, it still didn’t work due to other errors.
This time it stops at the same position, pointing to another head file. I
haven’t looked at it carefully yet, maybe next week.

Best regards,
Jinwei

**Comment by danston** [comment]
This is weird, because I tried your data and on my local system it passed multiple times both in Debug and Release modes without any errors. Though I use Mac OS, not a Windows. Once you have time, please let me know where the error comes from and maybe send me a snapshot of your other data where it fails. I will have a careful look at them. Thanks.

**Comment by amyxlalala** [comment]
Ok. Anyway, I will check it again next week.
