### ISSUE TITLE
C++ compilation flags from CGAL causes compilation problems for CUDA projects on Windows

### ISSUE THREAD

**Issue by jasjuang** [CGAL/cgal#4571]
## Environment

* Operating system: Windows 10
* Compiler: Visual Studio 2017
* Release or debug mode: Release
* CGAL version: Latest in vcpkg

## Source Code

Install CGAL via vcpkg first, `vcpkg install cgal`, and then please see below minimal code to reproduce the problem:

CMakeLists.txt
```
cmake_minimum_required(VERSION 3.15)

set(CMAKE_TOOLCHAIN_FILE
    $ENV{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake
    CACHE STRING "")
set(VCPKG_TARGET_TRIPLET $ENV{VCPKG_DEFAULT_TRIPLET} CACHE STRING "")

project(sample LANGUAGES CXX CUDA)
find_package(CUDA REQUIRED)
find_package(CGAL REQUIRED)

add_executable(${PROJECT_NAME} mycu.cu)

target_link_libraries(${PROJECT_NAME} CGAL::CGAL)
```

mycu.cu is as simple as
```
int main(){
return 0;
}
```

After clicking build, the below compilation error shows up
```
2>C:\Users\jasju\Desktop\test\build>"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin\nvcc.exe" -gencode=arch=compute_30,code=\"sm_30,compute_30\" --use-local-env -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64" -x cu  -I"C:\dev\vcpkg\installed\x64-windows\include" -I"C:\dev\vcpkg\installed\x64-windows\share\cgal\..\..\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\include"     --keep-dir x64\Release -maxrregcount=0  --machine 64 --compile -cudart static /fp:strict /fp:except- /wd4503 /bigobj -Xcompiler="/EHsc -Ob2"    -D_WINDOWS -DNDEBUG -D_SCL_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_WARNINGS -DBOOST_ALL_DYN_LINK=1 -D"CMAKE_INTDIR=\"Release\"" -D"CMAKE_INTDIR=\"Release\"" -D_MBCS -Xcompiler "/EHsc /W3 /nologo /O2 /Fdsample.dir\Release\vc141.pdb /FS /Zi  /MD /GR" -o sample.dir\Release\mycu.obj "C:\Users\jasju\Desktop\test\mycu.cu"
2>nvcc fatal   : A single input file is required for a non-link phase when an outputfile is specified
```

If I build it without linking to CGAL, it builds successfully,

```
2>C:\Users\jasju\Desktop\test\build>"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin\nvcc.exe" -gencode=arch=compute_30,code=\"sm_30,compute_30\" --use-local-env -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64" -x cu   -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\include"     --keep-dir x64\Release -maxrregcount=0  --machine 64 --compile -cudart static -Xcompiler="/EHsc -Ob2"    -D_WINDOWS -DNDEBUG -D"CMAKE_INTDIR=\"Release\"" -D"CMAKE_INTDIR=\"Release\"" -D_MBCS -Xcompiler "/EHsc /W3 /nologo /O2 /Fdsample.dir\Release\vc141.pdb /FS /Zi  /MD /GR" -o sample.dir\Release\mycu.obj "C:\Users\jasju\Desktop\test\mycu.cu"
2>mycu.cu
2>   Creating library C:/Users/jasju/Desktop/test/build/Release/sample.lib and object C:/Users/jasju/Desktop/test/build/Release/sample.exp
2>sample.vcxproj -> C:\Users\jasju\Desktop\test\build\Release\sample.exe
3>------ Build started: Project: ALL_BUILD, Configuration: Release x64 ------
========== Build: 3 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
```

After checking the difference between them, I figured out these 4 flags `/fp:strict /fp:except- /wd4503 /bigobj` added by CGAL breaks the compilation, because if I run the compilation command manually on a terminal without those 4 flags, it compiles successfully. My guess is those 4 flags are C++ specific but for some reason, it got propagated into nvcc. Can we figure out a way to fix this problem?

**Comment by lrineau** [comment]
As you use a version of CMake more recent than 3.11, I have created the PR #4572. Can you try with the patch of that pull-request?

**Comment by jasjuang** [comment]
@lrineau Unfortunately `COMPILE_LANGUAGE` doesn't work on Windows. Related issue on cmake [here](https://gitlab.kitware.com/cmake/cmake/issues/17656). Their [documentation](https://cmake.org/cmake/help/v3.17/manual/cmake-generator-expressions.7.html) also indicated that as well.

Is it possible to simply add a `PRIVATE` for the `target_compile_options` for those 4 flags? I don't know what those 4 flags mean, if the downstrean user links to CGAL and compile their application, 
would CGAL functions not produce the right result because of the absence of those 4 flags?

**Comment by lrineau** [comment]
> @lrineau Unfortunately `COMPILE_LANGUAGE` doesn't work on Windows. Related issue on cmake [here](https://gitlab.kitware.com/cmake/cmake/issues/17656). Their [documentation](https://cmake.org/cmake/help/v3.17/manual/cmake-generator-expressions.7.html) also indicated that as well.

I am surprised. I have seen in the [release notes of CMake-3.13](https://cmake.org/cmake/help/v3.14/release/3.11.html#id7) that `COMPILE_LANGUAGE` was with MSVC generators, since CMake-3.11.

And the documentation you quote only says that MSVC generator cannot distinguish between C and C++ code, but it gives an example with CUDA vs C++.

> Is it possible to simply add a `PRIVATE` for the `target_compile_options` for those 4 flags? I don't know what those 4 flags mean, if the downstrean user links to CGAL and compile their application,
> would CGAL functions not produce the right result because of the absence of those 4 flags?

Among those four flags (`/fp:strict /fp:except- /wd4503 /bigobj`), `/wd4503` is just a convenience, for MSVC 2015. And `/bigobj` is not always required: that depends on what is compiled. But `/fp:strict /fp:except-` is mandatory for the correct behavior of `<CGAL/Interval_nt.h>`.

**Comment by jasjuang** [comment]
@lrineau I just tried your PR and you right. It solves the problem. My information is outdated apparently. Thanks for the fix!
