### ISSUE TITLE
Polyhedron demo : C3t3 binary I/O do not deal with complex edges

### ISSUE THREAD

**Issue by janetournois** [CGAL/cgal#4583]
## Issue Details

I am facing the following issue : 
- generate a tetrahedral mesh with Mesh_3 in the demo, and save the mesh with the binary file format `*.binary.cgal`.
- load the file, and run the code below on the C3t3
- the output file is empty, complex edges have not been loaded (or not saved?)

@lrineau did you notice that already?
@maxGimeno can you please take a look while you are working on I/Os?

## Source Code
```
    template<typename C3T3>
    void dump_edges_in_complex(const C3T3& c3t3, const char* filename)
    {
      typename C3T3::Triangulation::Geom_traits::Construct_point_3 pt =
         c3t3.triangulation().geom_traits().construct_point_3_object();

      std::ofstream ofs(filename);
      ofs.precision(17);
      for (typename C3T3::Edges_in_complex_iterator eit = c3t3.edges_in_complex_begin();
        eit != c3t3.edges_in_complex_end(); ++eit)
      {
        const typename C3T3::Edge& e = *eit;
        ofs << "2 "
          << point(e.first->vertex(e.second)->point()) << " "
          << point(e.first->vertex(e.third)->point()) << "\n";
      }
      ofs.close();
    }
```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows 64 bits
* Compiler: msvc 2019
* Release or debug mode: both
* CGAL version: master

**Comment by maxGimeno** [comment]
I guess it is related to this PR : https://github.com/CGAL/cgal/pull/3850

**Comment by janetournois** [comment]
Right! Actually it is the same issue as #2359
I hope it is fixed soon :-)
