### ISSUE TITLE
PMP: close_volumes parameter does not exist 

### ISSUE THREAD

**Issue by abuzaina** [CGAL/cgal#4585]
_Please use the following template to help us solving your issue._

## Issue Details
I am trying to clip a mesh and close the volume, on the webpage here it suggests using
`CGAL::Polygon_mesh_processing::parameters::close_volumes`
but it does not exist.
https://doc.cgal.org/latest/Polygon_mesh_processing/index.html

How do I clip a mesh with a plane and have the mesh closed ?

* Operating system Ubuntu 16.04
* CGAL version: 4.13.2

**Comment by MaelRL** [comment]
The parameters that you can use with the functions are described in the [documentation of the function](https://doc.cgal.org/4.13.2/Polygon_mesh_processing/group__PMP__corefinement__grp.html#ga30082762ba2d947cba304e2884d96a99). In your case, you want to use `clip_volume`. 

It is true however, that the legend of the figure is a bit misleading.
