### ISSUE TITLE
mesh clip

### ISSUE THREAD

**Issue by KeepFaithMe** [CGAL/cgal#4593]
_Please use the following template to help us solving your issue._

## Issue Details

Dear CGAL developers:
        I have a confused need you to explain.When I use the function clip() to clip my mesh,I know that the process is two face intersected.By this process we can get two new point and three new triangles.So I just want to know  whether the new point must be on the cliped surface.
      It is very important to me,so please tell me the answer.looking forward to your reply!
      Thank you very much!

## Source Code

_If your issue arises by using CGAL in your own source code, please provide a minimalist example that we can compile easily to reproduce the bug. If your issue arises from using a CGAL program (demo, example, etc.), please let us know which one. Helping you solving an issue is much easier and efficient if we can reproduce it._

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):
* Compiler:
* Release or debug mode:
* Specific flags used (if any):
* CGAL version:
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by sloriot** [comment]
Sorry but I don't understand your question. Maybe you could make a 2D drawing ?

**Comment by KeepFaithMe** [comment]
![sketch map](https://user-images.githubusercontent.com/32037166/77293060-88cefd80-6d1c-11ea-8e0a-97b3b4126243.png)

Thank you for your reply.
As you can see in this picture,the triangle ABC is one of the face of my mesh,and the red line represents the plane which is used to clip the face ABC,and the point D,E is the new  points,and the triangle ABD,ADE,CDE is the new triangles.
My confused is that when using a plane to clip a mesh, there will be many new points,I just want to know that whether the new point must be on the cliped surface.
In the other words,whether the point D,E(the new point) must be on the face ABC.
Is that clear?

**Comment by sloriot** [comment]
The new points created by the `clip()` function are intersection points of edges from the input with the clipper. Note in the case a plane is used as clipper, a triangle mesh of a cube is generated and used as clipper internally. So there might be some intersection points that are intersection of the edges of the generated cube with the input mesh. In your picture, D and E will lie on the triangle ABC.

**Comment by KeepFaithMe** [comment]
You said: **So there might be some intersection points that are intersection of the edges of the generated cube with the input mesh**.Even if some intersection points that are intersection of the edges of the generated cube with the input mesh,can I understand it in this way,no matter how the points are generated,the new points always lie on the face of mesh. In other words,I can always find a surface that contains new points.

**Comment by sloriot** [comment]
Yes, new points will always be on the input mesh.

**Comment by KeepFaithMe** [comment]
Ok that is clear.But I still want to ask you a question.Is there a way to quickly get the relationship between the segmented plane and the new vertex.I mean can I quickly find out which surface of the input mesh the newly generated points are on.If there is no way,can you give me some advice about how do I determine which surface of the input mesh a newly generated surface is on.As the above picture shows,How can I judge whether plane ABD is on plane ABC.I konw this is not about CGAL,but I konw you are an expert in this field,so I hope to get your help!It is very import to me,Thank you very much!
Goog Luck!

**Comment by sloriot** [comment]
The only thing available in the current API is the `visitor` named parameter that will enable you to track the creation of new faces (as a subset of input one). Even if not direct, that should be enough to locate the new vertices.
