### ISSUE TITLE
add virtual destructor where relevant 

### ISSUE THREAD

**Issue by Mostafa-ashraf19** [CGAL/cgal#4596]
## Would you like to add "Virtual destructor"  Where relevant  ?

Virtual destructors are useful when you work on polymorphism concept.

**Comment by lrineau** [comment]
As an exercice, I let you find the use-cases of polymorphism in CGAL. Can you please point out where the virtual destructors are missing?

**Comment by gdamiand** [comment]
@lrineau By the way, when working on #4519, I noticed that class [Rep](https://github.com/CGAL/cgal/blob/0f0a0ed82d72db18822299e6000fd5499ffeb8b6/STL_Extension/include/CGAL/Handle.h#L26) has virtual destructor, and I am wondering if this is necessary ?

**Comment by lrineau** [comment]
`CGAL::Rep` is the base class for all representation types used by `CGAL::Handle`. That is actually one of the only places in CGAL where we use the dynamic polymorphism, and that destructor has to be virtual.
