### ISSUE TITLE
c3t3 item in demo/Polyhedron, plus I/O

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#46]
The [`Poyhedron demo`][demo code] has a way to visualize a c3t3, in the Mesh_3 plugin, but no I/O. That feature was developed in [another branch][Mesh_3-experimental-GF]. That functionality should be imported into `master`.

[demo code]: https://github.com/CGAL/cgal/tree/master/Polyhedron/demo/Polyhedron
[Mesh_3-experimental-GF]: https://github.com/CGAL/cgal-dev/tree/Mesh_3-experimental-GF

**Comment by sloriot** [comment]
@lrineau I think this issue can be closed.

**Comment by lrineau** [comment]
Will be closed by #480.
