### ISSUE TITLE
clip visitor problem

### ISSUE THREAD

**Issue by KeepFaithMe** [CGAL/cgal#4601]
_Please use the following template to help us solving your issue._

## Issue Details
dear CGAL developer:
        I used the function clip() to clip my mesh,and I have a need.
![sketch map](https://user-images.githubusercontent.com/32037166/77719195-ab645d80-701f-11ea-9c60-9a3c2acd1d57.png)
      As the image shows,when I used a plane(the rea line) to clip the mesh,there are three new faces generated,ABD,ADE,CDE.So if I use the API **visitor** ,can I get the relationship between the new face ABD and  old face ABC.In other words,by 
 the visitor can I record the new face ABD and the old face ABC(belonging to the input mesh),so that I can konw that which face the new face belong to quickly.
    If API visitor can do it ,please give me some advice!thank you! It is very import to me!

## Source Code

_If your issue arises by using CGAL in your own source code, please provide a minimalist example that we can compile easily to reproduce the bug. If your issue arises from using a CGAL program (demo, example, etc.), please let us know which one. Helping you solving an issue is much easier and efficient if we can reproduce it._

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):
* Compiler:
* Release or debug mode:
* Specific flags used (if any):
* CGAL version:
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by sloriot** [comment]
Does [this example](https://github.com/CGAL/cgal/blob/master/Polygon_mesh_processing/examples/Polygon_mesh_processing/corefinement_mesh_union_with_attributes.cpp) answer your question? It's for another function but the usage is similar.

**Comment by KeepFaithMe** [comment]
I have read this [https://github.com/CGAL/cgal/blob/master/Polygon_mesh_processing/examples/Polygon_mesh_processing/corefinement_mesh_union_with_attributes.cpp](url) you told me,and I also read the API Visitor https://doc.cgal.org/latest/Polygon_mesh_processing/classPMPCorefinementVisitor.html#a51a2222bdcadf27fecfd8c3862300d0b 
There are two functions  named 'before_subface_creations' and 'after_subface_created' I can overload .In the function 'before_subface_creations' ,there is a parameter 'face_descriptor f_split',whether this parameter is the id of face triangulated  in the input mesh,and in the function 'after_subface_created',there is also a parameter 'face_descriptor f_new',whether this parameter is the id of the new face in the out mesh.So by the parameters,I can find the faces triangulated in the input mesh  and the new faces in the output mesh.

**Comment by sloriot** [comment]
I see that the question is answered. I'm closing the issue.
