### ISSUE TITLE
test_constrained_triangulation_2 does not pass in Release

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#4609]
Since the merge of PR #4163 in `master`, the test `test_constrained_triangulation_2` does not pass with default CMake option in `Release`.

@maxGimeno and I detected that while trying to benchmark triangulations (see https://github.com/CGAL/cgal/pull/4496#issuecomment-607814445), because `ctest -L Triangulation_2` failed, in `master`, if cmake was configured with `-DCMAKE_BUILD_TYPE=Release`. We found strange that the test suite did not caught that error.

After use of git-bisect, I found that PR #4163 introduced the issue. But, that did not explain why the CGAL testsuite was fine with it. Eventually, I found that in `master` (23aca30a0493081478181a72a9572bc67f9d90b0):
  - `ctest -R test_constrained_triangulation_2` *passes* if one compiles with `-O3 -DCGAL_NDEBUG` (like in the testsuite)
  - `ctest -R test_constrained_triangulation_2` *does not* pass if one compiles with `-O3 -DNDEBUG` (like in the default CMake flags for Release).

**Comment by MaelRL** [comment]
Seems like the error is rather linked to the fact that some variables are assigned in assertions, such as:
```
  int ih;
  assert(T1_2.is_edge(vha,vhb, fh, ih));
```
which isn't code from that PR. Maybe the other lines I have added shifted memory around and it now explodes.

I think I have seen the same type of code in BGL tests, I will take care of it as well.
