### ISSUE TITLE
problem when do intersection of two 2d triangles

### ISSUE THREAD

**Issue by MulinYu** [CGAL/cgal#4613]
_Please use the following template to help us solving your issue._

## Issue Details
When I do intersection of two 2d triangles, met tihs problem.
CGAL error: assertion violation!
Expression : list.size-list_size <= 2
File       : C:\dev\CGAL-5.0.1\include\CGAL/Intersections_2/internal/Triangle_2_Triangle_2_intersection_impl.h
Line       : 123

## Source Code

double Shape_Detector::intersection_triangle_original(std::vector<Inexact_Triangle_3> target, std::vector<Inexact_Triangle_3> tr_3, const Inexact_Plane & PI) {
	std::vector<Inexact_Triangle_2> trianle_target;
	double area_target = 0;
	for (Inexact_Triangle_3 tr_3_one_1 : target) {
		Inexact_Triangle_2 tr_2_1(PI.to_2d(tr_3_one_1[0]), PI.to_2d(tr_3_one_1[1]), PI.to_2d(tr_3_one_1[2]));

		if (!tr_2_1.is_degenerate()&& CGAL::abs(tr_2_1.area())!=0) {
			trianle_target.push_back(tr_2_1);
			area_target += CGAL::abs(tr_2_1.area());
		}
		
	}

	std::vector<Inexact_Triangle_2> trianle_poly;
	double area_poly = 0;
	for (Inexact_Triangle_3 tr_3_one : tr_3) {
		Inexact_Triangle_2 tr_2(PI.to_2d(tr_3_one[0]), PI.to_2d(tr_3_one[1]), PI.to_2d(tr_3_one[2]));
		if (!tr_2.is_degenerate()&& CGAL::abs(tr_2.area())!=0) {
			trianle_poly.push_back(tr_2);
			area_poly += CGAL::abs(tr_2.area());
		}
		
	}
	if (area_poly == 0|| area_target==0) {

		return 0;
	}

	double area_inter = 0;
	for (size_t i = 0; i < trianle_target.size(); ++i) {
		const Inexact_Triangle_2 & tr_i = trianle_target[i];
		

		for (size_t j = 0; j < trianle_poly.size(); ++j) {
			const Inexact_Triangle_2 & tr_j = trianle_poly[j];

			CGAL::cpp11::result_of<CGAL::Exact_predicates_inexact_constructions_kernel::Intersect_2(Inexact_Triangle_2, Inexact_Triangle_2)>::type object = CGAL::intersection(tr_i, tr_j);
			if (object) {
				if (const Inexact_Triangle_2* ptr = boost::get<Inexact_Triangle_2>(&*object)) {
					area_inter += CGAL::abs(ptr->area());

				}
				else if (const std::vector<Inexact_Point_2>* ptr = boost::get<std::vector<Inexact_Point_2> >(&*object)) {

					std::vector<Inexact_Point_2> v = (*ptr);

					if (v.size()<3) { std::cout << "nononono................." << std::endl; }

					for (size_t k = 1; k < v.size() - 1; k++) {
						Inexact_Triangle_2 t_k(v[0], v[k], v[k + 1]);
						area_inter += CGAL::abs(t_k.area());

					}

				}
				//else if (const Inexact_Segment_2* ptr = boost::get<Inexact_Segment_2>(&*object)) {
				//std::cout << "segment................." << std::endl;
				//}
			}
		}
	}
	if (area_target == 0) {
		return 0;
	}
	else {
		return CGAL::to_double(area_inter / area_target);

	}
}

## Environment

* Operating system (Windows):
* Compiler:Vs2015
* Release or debug mode: both
* Specific flags used (if any):
* CGAL version:5.01
* Boost version:1_62_0
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by MulinYu** [comment]
Dear all,
I'm so sorry that I find that the problem just happened in debuge mode.

Thanks
BR

**Comment by sloriot** [comment]
Note that if you are doing constructions you have to use a Kernel with exact constructions like `CGAL::Exact_predicates_exact_constructions_kernel`. You can use [`CGAL::Cartesian_converter`](https://doc.cgal.org/latest/Kernel_23/classCGAL_1_1Cartesian__converter.html) for switching between kernels.
