### ISSUE TITLE
SDG2: Missing storage classes in documentation

### ISSUE THREAD

**Issue by MaelRL** [CGAL/cgal#4621]
The doc says:
```
CGAL::Segment_Delaunay_graph_2< Gt, DS >
```
but the actual code is:
```
template<class Gt,
         class ST = Segment_Delaunay_graph_storage_traits_2<Gt>,
         class D_S = Triangulation_data_structure_2 <
		                Segment_Delaunay_graph_vertex_base_2<ST>,
		                Segment_Delaunay_graph_face_base_2<Gt> >,
         class LTag = Tag_false >
class Segment_Delaunay_graph_2;
```

The template parameter corresponding to the second template parameter is missing, the class `Segment_Delaunay_graph_storage_traits_2` (and its concept?) are undocumented.

This seems to be the case across the whole package (maybe in SDG2_inf too?).

**Comment by demin-dmitriy** [comment]
`Segment_Delaunay_graph_face_base_2` is also undocumented.

Interestingly, it seems that extra data (compared to what is in `Triangulation_face_base_2`) stored in `Segment_Delaunay_graph_face_base_2` is not used at all, unless an undocumented macro `CGAL_SDG_NO_FACE_MAP` is defined.

So using `Triangulation_face_base_2` instead seems to compile just fine.

I see that macro `CGAL_SDG_NO_FACE_MAP` is defined in some of the benchmarks. I'm curious, if I should try to also define it in my user code and check if I get any performance gains.
