### ISSUE TITLE
Obsolete doxygen configuration settings

### ISSUE THREAD

**Issue by albert-github** [CGAL/cgal#4625]
## Issue Details

In the recent version of doxygen (1.8.16 and newer) the following configuration settings have been removed:
- PERL_PATH
- MSCGEN_PATH

in the current master also the configuration setting has been removed (due to the fact that the tcl support has been removed):
- TCL_SUBST 

## Source Code

As the file `./doc/resources/1.8.14/BaseDoxyfile.in` is for 1.8.14 I'm not sure to remove them from this file or that a new `BaseDoxyfile.in` should be created. I think it would be possible to do it in `./doc/resources/1.8.14/BaseDoxyfile.in` as the values are not used for CGAL.

**Comment by sloriot** [comment]
I just did what you suggested, that is removing the options. Thanks!
