### ISSUE TITLE
Bug intersection Line_2 Triangle_2

### ISSUE THREAD

**Issue by lvalque** [CGAL/cgal#4628]
## Issue Details

I'm calling CGAL::intersection() between a Line_2 and a Triangle_2, the program crashed with this:
```
terminate called after throwing an instance of 'CGAL::Assertion_exception'
  what():  CGAL ERROR: assertion violation!
Expr: false
File: /usr/local/include/CGAL/Intersections_2/Line_2_Triangle_2.h
Line: 133
Explanation: Internal CGAL error.
```
## Source Code

A minimal example that reproduces the bug
```c++
#include <CGAL/box_intersection_d.h>
#include <CGAL/Exact_predicates_exact_constructions_kernel.h>

typedef CGAL::Exact_predicates_exact_constructions_kernel Kernel;
typedef Kernel::Triangle_2 Triangle_2;
typedef Kernel::Line_2 Line_2;
typedef Kernel::Point_2 Point_2;
typedef CGAL::cpp11::result_of< Kernel::Intersect_2(Triangle_2, Line_2) >::type Intersect_Tri_Line_2;


int main(){
    Line_2 l(Point_2(1,-0.000457764),Point_2(2,-0.000457764));
    Triangle_2 tr(Point_2(-6.19597e+09,-0.000457764),Point_2(-5.26371e+09,-0.000457764),Point_2(-2.23825e+09,-0.000457764));
    
    Intersect_Tri_Line_2 result = CGAL::intersection( tr, l);
    return 0;
}
```
## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Ubuntu 18
* Compiler: gcc
* Release or debug mode: Release
* Specific flags used (if any):
* CGAL version: 5.0
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by lrineau** [comment]
You copy-pasted that error:
```
terminate called after throwing an instance of 'CGAL::Assertion_exception'
  what():  CGAL ERROR: assertion violation!
Expr: false
File: /usr/local/include/CGAL/Intersections_2/Line_2_Triangle_2.h
Line: 133
Explanation: Internal CGAL error.
```
but the line 133 of `include/CGAL/Intersections_2/Line_2_Triangle_2.h` does not correspond to that assertion, in CGAL-5.0. I should have been `124` instead of `133`. Do you use a modified version CGAL?

However, I can reproduce the bug with any of CGAL-4.14.x, CGAL-5.0.x, or `master`. The assertion is at line 124.

**Comment by lrineau** [comment]
Actually, the triangle is degenerated. That probably explains why the CGAL code crashes.

**Comment by lvalque** [comment]
The assertion is at line 133 on my version but I don't used a modified version of CGAL.

**Comment by sloriot** [comment]
Triangle being degenerate I flagged it as "not a bug" and closed the issue.

**Comment by lvalque** [comment]
Maybe add a CGAL precondition?

**Comment by sloriot** [comment]
See #4654
