### ISSUE TITLE
Squeeze/Expand space

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#4630]
I would like to have a feature that allows to squeeze/expand the space along a given axis.

Say I have a tetrahedron `{(0,0,0), (0,1,0), (1,0,0), (0,0,10e8) }` I'd like to be able to have an to option to display it as if it was fitting in the unit sphere.

On the user side, I think it might be sufficient to "normalize" all the axis at the same time.
Note that here I'm not talking about modifying a model (this can be done using affine transformation) but really scaling the whole scene on the fly.

**Comment by lrineau** [comment]
@maxGimeno Why is this issue in "Under review/testing" in your TODO-list.

**Comment by sloriot** [comment]
Indeed it is completed AFAIK
