### ISSUE TITLE
input >> polyhedron fails

### ISSUE THREAD

**Issue by nschloe** [CGAL/cgal#4632]
One of the pygalmesh users found an issue with CGAL's reading of OFF files. With [off.zip](https://github.com/CGAL/cgal/files/4451751/off.zip), the following has `!input.good()`:
```c++
  Polyhedron polyhedron;
  std::ifstream input(infile);
  input >> polyhedron;
  if (!input.good()) {
    std::stringstream msg;
    msg << "Cannot read input file \"" << infile << "\"" << std::endl;
    throw std::runtime_error(msg.str());
  }
  input.close();
```
Might that be because the input file as interior faces? Is it possible to retrieve a more detailed error message?
Slice view:

![in](https://user-images.githubusercontent.com/181628/78811611-6569ab00-79ca-11ea-8804-36623e50eab4.png)

https://github.com/nschloe/pygalmesh/issues/72

**Comment by afabri** [comment]
Hi Nico, The halfedge data structure can only represent 2-manifolds.  You should read a polygon soup and orient it, which will duplicate vertices if necessary. See the following [example](https://doc.cgal.org/latest/Polygon_mesh_processing/index.html#title40).

**Comment by sloriot** [comment]
More precisely, you should use the function [`is_polygon_soup_a_polygon_mesh()`](https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__repairing__grp.html#ga8b9d12d817b5cc76f5a42d74eac75bf3) to refuse those inputs. Calling orient is not a good idea as `Mesh_3` is not able to handle the input directly (a complex must be used). See also [this example](https://doc.cgal.org/latest/Polygon_mesh_processing/Polygon_mesh_processing_2orient_polygon_soup_example_8cpp-example.html) for how to use `read_OFF()`.

**Comment by nschloe** [comment]
Thanks for the explanations!
