### ISSUE TITLE
error in Delaunay3D report

### ISSUE THREAD

**Issue by whufor** [CGAL/cgal#4637]
_Please use the following template to help us solving your issue._

## Issue Details

I am using the Delaunay3D part of CGAL to generate FEM meshes.
During the computation process, the algorithm is generally robust. 
But sometimes I meet a error shown in the screen. The message is as below:
CGAL error: assertion violation!
Expression :
File       : C:\cudaWork\CGALinclude\CGAL\Small_unordered_map.h
Line       : 98
Explanation:
Refer to the bug-reporting instructions at https://www.cgal.org/bug_report.html

## Source Code

using namespace std;

	typedef CGAL::Exact_predicates_inexact_constructions_kernel         K;
	typedef CGAL::Triangulation_vertex_base_with_info_3<unsigned, K>    Vb;
	typedef CGAL::Delaunay_triangulation_cell_base_3<K>                 Cb;
	typedef CGAL::Triangulation_data_structure_3<Vb, Cb>                Tds;           //define 3d datastructure
	typedef CGAL::Delaunay_triangulation_3<K, Tds, CGAL::Fast_location> Delaunay;
	typedef Delaunay::Point                                             Point;

	vector< pair<Point, unsigned> > Points;

	
	for (int in = 0;in < node_cnt;in++)
	{
		Points.push_back(make_pair(Point(node_coor0[in], node_coor1[in], node_coor2[in]), in));
	}

	Delaunay DT3(Points.begin(), Points.end());//Triangulation

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):
Windows 64 bits
* Compiler:
Visual Studio 2019
* Release or debug mode:
Release
* Specific flags used (if any):
* CGAL version:
5.0.2
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by afabri** [comment]
Can you please provide a data set.

**Comment by whufor** [comment]
Dear Andreas,


Thanks for your rapid response.
As the whole computation is too large, I did not save all the data.
However, I will save and report a data set when the error occurs next time.


Best regards,


Wei Zhang
9 April 2020






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Andreas Fabri"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月9日(星期四) 晚上11:48
收件人:&nbsp;"CGAL/cgal"<cgal@noreply.github.com&gt;;
抄送:&nbsp;"天晴的雨/;f"<5297716@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [CGAL/cgal] error in Delaunay3D report (#4637)





 
Can you please provide a data set.

**Comment by MaelRL** [comment]
@whufor any update?
