### ISSUE TITLE
About normal computation?

### ISSUE THREAD

**Issue by ibrahimLearning** [CGAL/cgal#4653]
I would like to know about normal computation. For my data, I used pca_estimate_normal, but it takes so long time, around one night. 
When I used another library, where they use KDTreeSearch, it was faster.
What is the difference between pca_estimate_normals and KDTreeSearch based algorithms?
As for example KDTreeSearch (open3d): 

> pcd.estimate_normals( o3d.geometry.KDTreeSearchParamHybrid(radius=0.1, max_nn=30))

Is there any way to calculate normals using KDTreeSearch in CGAL?

My enivornment:
Windows 10
Visual studio 2017
CGAL 5.0.2

**Comment by sgiraudot** [comment]
The normal estimation algorithms in CGAL use kd tree structures internally, they shouldn't take that long. Are you sure you compiled your code in release mode (especially with the `-O3` flag)?

If not: how many points does your input contain? Do you have a source code to share?

**Comment by ibrahimLearning** [comment]
> The normal estimation algorithms in CGAL use kd tree structures internally, they shouldn't take that long. Are you sure you compiled your code in release mode (especially with the `-O3` flag)?
> 
> If not: how many points does your input contain? Do you have a source code to share?

Thanks for your comment. I installed cgal using vcpkg:
https://doc.cgal.org/latest/Manual/windows.html#title0
Also compile in debug mode using the instructions from above link.
The example program for normal estimation (normals_example.cpp) is ok for their own data (sphere_1k.xyz), but when I used my data, it takes so long time.

What does -03 flag mean? I did not use it, how can I use?
Number of points: 1372957 points

**Comment by afabri** [comment]
Dear @ibrahimLearning We can't spend time on explaining you the difference between release and debug compilation.

**Comment by ibrahimLearning** [comment]
It is solved by running in release mode!
