### ISSUE TITLE
Simple program to visualize my .ply in CGAL?

### ISSUE THREAD

**Issue by ibrahimLearning** [CGAL/cgal#4655]
I installed cgal successfully using vcpkg. Also compile and run some examples provided by cgal. 
I would like to display triangle mesh from my  .ply file in CGAL?

Is there any suggestion or code please?

Windows 10
cgal 5.0.2

**Comment by sgiraudot** [comment]
You can use the `CGAL::draw()` function applied to a Surface Mesh object, see [this example](https://doc.cgal.org/latest/Surface_mesh/Surface_mesh_2draw_surface_mesh_8cpp-example.html). The example reads an `OFF` file, but you can also read `PLY` files using [`CGAL::read_ply()`](https://doc.cgal.org/latest/Surface_mesh/group__PkgSurface__mesh.html#ga42f6ad486ddab74e13d3dc53f511c343).

**Comment by sloriot** [comment]
It is not acceptable to ping random people from the project, I consider this as spam. Please don't do that again.
