### ISSUE TITLE
Different behavior of the edge_aware_upsample_point_set?

### ISSUE THREAD

**Issue by ibrahimLearning** [CGAL/cgal#4662]
@afabri @sgiraudot 
I am trying to do up-sampling using edge_aware_upsample_point_set function. I used it from point_set_processing_3 example. It works for **before_upsample.xyz** data (which is available in the data folder); But when I used my own data it gives the following error:

> edge_aware_upsample_point_set_example.exe (process 17092) exited with code -1073741819.

```
//Algorithm parameters
  const double sharpness_angle = 30;   // control sharpness of the result.
  const double edge_sensitivity = 0.2;    // higher values will sample more points near the edges          
  const double neighbor_radius = 18;  // initial size of neighborhood.
```
Is there any hidden things with the dataset?
My data is look like this:
```
256075.14697445265 3935300.4999999995 -1.9903260605285873 -0.15059442500026382 -0.009264547714967571 -0.98855221779857272
256127.18092914129 3935279.9999999991 1.1806971722817656 0.36255488715508305 -0.28210066175799464 -0.88824161714911032
256124.96664647732 3935273.5000000005 0.018751732199395927 -0.14177362442736433 -0.13905823184364116 0.98008318400697436
256092.491746024 3935308.4999999995 -1.4489924924748039 -0.085803198655671153 0.024081843084161825 0.99602102183343766
256125.86596481747 3935280.5000000009 13.515503257111945 -0.13654115576027245 -0.24797889506659618 0.95909487559114781
256073.15088360262 3935255 -0.93490020406201102 0.59004993642832648 -0.095249131262525044 0.80172855475819382
256141.9517848785 3935322.2500000005 8.2318409757309219 -0.24795966835219574 -0.510449916403933 0.82338137318856486
256096.20889673862 3935319.7500000005 -0.21291360675685664 -0.099540727133083942 -0.024195625188008569 -0.9947392700419434
256107.09924066794 3935294.0000000005 -2.4377930441306859 -0.26315074779627329 -0.097325421959314151 0.95983303036241863
256130.16003200199 3935331.0002575037 14.609926967219579 -0.3588182051513355 -0.18823254749436522 0.9142308262773442
256116.12694613857 3935270.75 -2.0657511148141805 0.24053723579657579 0.070452458792483491 -0.9680796915778348
256089.84995883351 3935295.0000017555 -1.6188145313052476 0.0064104152035124699 0.04608216574353774 0.99891708393505008
256134.45646496481 3935324.2500000014 15.07897998471479 0.53174645878060467 -0.11064115355939698 -0.839645305300597
256095.27114842934 3935277.5 -2.8364161735055196 -0.074721280830373799 -0.096646577736570455 0.99251003481218136
256105.55928731122 3935323.0000000009 -1.1949637713004984 0.017197163654433804 0.097298114890588067 -0.99510669498349791
256130.41300641268 3935321.25 6.5035951636939613 -0.43255495210832851 0.15621449615365787 -0.88797142104800897
256137.72632800549 3935268.0000000005 5.7040995939553092 0.46653308381289188 -0.12300223968824016 -0.87590943067175042
256074.18452226146 3935306.9999999986 -1.7849232437298566 -0.32602824029779293 0.0081090078323643733 -0.94532525118093569
256117.4120398699 3935294.4999957578 -1.4283822200345702 -0.12123765837760146 -0.021571538178222535 0.99238908646344026
256093.04888751596 3935260.7500000005 -3.7532516406220982 -0.15371063599573145 0.38761148559555941 0.90891714507769694
256129.64393281593 3935324.75 12.980674692685975 -0.91363716556705743 0.026375393820841451 0.40567409123012632
256082.74928676969 3935279.5000000005 -2.3778079661987341 0.1486957529011404 0.017605361429175122 -0.98872626359276572
256067.26568958032 3935275.25 4.2080822055293892 -0.63171033161292922 0.23850790093484486 -0.73760154428060765
...
```

Environment:
Windows 10
cgal 5.0.2
Installed using vcpkg

**Comment by sgiraudot** [comment]
Can you do the following?
- add `#define CGAL_PSP3_VERBOSE` at the beginning of the program
- compile in debug mode
- copy-paste the full output of the program here

**Comment by ibrahimLearning** [comment]
> Can you do the following?
> 
> * add `#define CGAL_PSP3_VERBOSE` at the beginning of the program
> * compile in debug mode
> * copy-paste the full output of the program here

Error:
Debug Assertion Failed!
Program:
...ssing_3\build\Debug\edge_aware_upsample_point_set_example.exe
File: ....\2017\Commmunity\VC\Tools\MSVC\14.16.27023\include\vector
Line:1733

Expression: vector subscript out of range

**Comment by sgiraudot** [comment]
Is there any way you could share your full data set? I would very much like to reproduce this bug, but it seems hard to do without running the function on the same data set.

**Comment by ibrahimLearning** [comment]
> 
> 
> Is there any way you could share your full data set? I would very much like to reproduce this bug, but it seems hard to do without running the function on the same data set.

Woud you give your mail address please? it will be better for me!

**Comment by sgiraudot** [comment]
simon.giraudot@geometryfactory.com

Thanks!

**Comment by sgiraudot** [comment]
Thanks for sharing the data set privately with me, I managed to reproduce the bug and I made a fix: https://github.com/CGAL/cgal/pull/4677

You should be able to use the upsampling function using this bugfix. I tested on your data, it takes a while but it does not crash anymore.

Thanks a lot for this report!
