### ISSUE TITLE
Type issue with std::sqrt in compute_vertex_normal

### ISSUE THREAD

**Issue by taus** [CGAL/cgal#467]
When calling `CGAL::Polygon_mesh_processing::is_outward_oriented` i get Severity	"'sqrt': none of the 3 overloads could convert all the argument types" on both calls to `std::sqrt`. 

I am using the kernel `typedef CGAL::Exact_predicates_exact_constructions_kernel Kernel;` and calling `is_outward_oriented` with a `typedef CGAL::Polyhedron_3<Kernel> Polyhedron;` as input

std::sqrt is invoked on line 186 and 191 of compute_normal.h with the dot product of two `Kernel::Vector_3`. It would seem that the result of this dot product cannot be implicitly converted to a type compatible with `std::sqrt`.

**Comment by sloriot** [comment]
I think #444 should fix the issue.

**Comment by taus** [comment]
This just moves the problem to the `\` operator for which the result of the square root is used. Changing to `CGAL::sqrt` just gives me  "`binary '/': no operator found which takes a left-hand operand of type 'Vector' (or there is no acceptable conversion)`"

**Comment by sloriot** [comment]
See #468
