### ISSUE TITLE
What does Corefined means?

### ISSUE THREAD

**Issue by vitsensei** [CGAL/cgal#4679]
Hi,
I came across this term in [Polygon Mesh Processing](https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__corefinement__grp.html#ga30082762ba2d947cba304e2884d96a99). In particular, the clip() function: return true if the output surface mesh is manifold. If false is returned tm and clipper are only corefined. But after googling, it seems like the only hits are from CGAL related sites.

**Comment by sloriot** [comment]
https://doc.cgal.org/latest/Polygon_mesh_processing/index.html#coref_def_subsec

**Comment by afabri** [comment]
I may be wrong, but I think the term _corefinement_ comes from French _coraffinement_, a term which was coined in PhD thesis work such as [this](http://www.theses.fr/2006ENMP1443).
