### ISSUE TITLE
Mesh_2: Meshing is not deterministic

### ISSUE THREAD

**Issue by manuel-garnier** [CGAL/cgal#4681]
## Issue Details

We have non regression tests randomly diffing between executions. These tests rely on CGAL mesh2 refinement which is not deterministic. This is a problem for us, since we WANT reproducibility!

## Source Code

See https://gist.github.com/manuel-garnier/8214384716971459a8037814b2c5626d
CMakeLists.txt was generated from script provided in CGAL distrib. You could use setup.sh script but it's mainly 2 cmake calls :)
Provided sample test simply tries to do 20 meshing and fails when one is different from first one (in term of number of vertices). It may not seem enough if you integrate this in CGAL test suite though.
In source, you can uncomment output file write to visualize triangulation if needed.

## Environment

* Operating system: Windows/Linux
* Compiler: VS2015 / gcc48 / gcc73
* Release or debug mode: Both
* Specific flags used (if any): 5.0.2 built from scratch without modif
* CGAL version: 4.1.4 and 5.0.2
* Boost version: 1.63.0
* Other libraries versions if used (Eigen, TBB, etc.): gmp-5.0.1 and mpfr-3.0.0

**Comment by sloriot** [comment]
Fixed by  #4726
