### ISSUE TITLE
Extraneous trace in Heat Method : Instrincic Delaunay triangulation

### ISSUE THREAD

**Issue by seb-tourneux** [CGAL/cgal#4686]
Hello,
There is an extraneous trace in Heat Method's Intrinsic Delaunay triangulation :

In CGAL-5.0.2 (and probably some versions before)
include/CGAL/Heat_method_3/internal/Intrinsic_Delaunay_triangulation_3.h:
Line 345:
    std::cout<< a << " edges were flipped: " << std::endl;

Thank you

**Comment by MaelRL** [comment]
Done in https://github.com/CGAL/cgal/pull/4680.
