### ISSUE TITLE
How can i use CGAL on bussiness?

### ISSUE THREAD

**Issue by Haoqiantao** [CGAL/cgal#4689]
hello, if I want to use cgal on bussiness, how should i do?
I have already login in the website of CGAL but i do not find how to get the permission of using it on bussiness.

thanks.

**Comment by sloriot** [comment]
CGAL is an open source software library that is available under a dual license (GNU GPL v3+ and commercial). If your business usage is not compatible with the terms of the GNU GPL v3+, you can purchase a commercial license for the components you need from GeometryFactory by contacting @afabri at andreas.fabri@geometryfactory.com.
