### ISSUE TITLE
Unable to pretty print 3D Cartesian Transformation: Aff_transformationC3 has no member named 'print'

### ISSUE THREAD

**Issue by rgcv** [CGAL/cgal#4698]
## Issue Details

When attempting to output an `Aff_transformation_3` out to a stream (say `std::cout`) where its mode has been set to "pretty" (using `CGAL::set_pretty_mode`), an error message is spewed out during compilation. Expected result would be similar to that of outputting an instance of `Aff_transformation_2`.

## Source Code

```cpp
#include <iostream>

#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/IO/io.h>

using K = CGAL::Epick;
using T3 = K::Aff_transformation_3;

int main() {
  T3 t(CGAL::IDENTITY);
  CGAL::set_pretty_mode(std::cout);
  std::cout << t << std::endl;
  return 0;
}
```

Compilation output:

```
In file included from /usr/local/include/CGAL/Cartesian/Cartesian_base.h:55,
                 from /usr/local/include/CGAL/Simple_cartesian.h:20,
                 from /usr/local/include/CGAL/Exact_predicates_inexact_constructions_kernel.h:20,
                 from test.cpp:3:
/usr/local/include/CGAL/Cartesian/Aff_transformation_3.h: In instantiation of ‘std::ostream& CGAL::operator<<(std::ostream&, const CGAL::Aff_transformationC3<R>&) [with R = CGAL::Epick; std::ostream = std::basic_ostream<char>]’:
/usr/local/include/CGAL/Aff_transformation_3.h:87:13:   required from ‘std::ostream& CGAL::operator<<(std::ostream&, const CGAL::Aff_transformation_3<R>&) [with R = CGAL::Epick; std::ostream = std::basic_ostream<char>]’
test.cpp:12:16:   required from here
/usr/local/include/CGAL/Cartesian/Aff_transformation_3.h:196:7: error: ‘const class CGAL::Aff_transformationC3<CGAL::Epick>’ has no member named ‘print’
  196 |     t.print(os);
      |     ~~^~~~~
```

## Environment

* Operating system: Linux 5.6.8-arch1-1 x86_64
* Compiler: g++ version 9.3.0
* Release or debug mode: Release
* Specific flags used (if any): Just linker flags (`-lboost -lCGAL`)
* CGAL version: 5.0.2
* Boost version: 1.72.0
* Other libraries versions if used (Eigen, TBB, etc.): N/A

**Comment by rgcv** [comment]
This seems to have a terribly simple solution: implement the missing `print` method in `Aff_TransformationC3` just like the one for `Aff_TransformationC2`:

https://github.com/CGAL/cgal/blob/7a1ba12bab47123e5adc4536afef0359fb53ed97/Cartesian_kernel/include/CGAL/Cartesian/Aff_transformation_2.h#L197-L203

Little to almost no modification (despite obvious dimension differences) should be required. `Aff_transformation_rep_baseC3` already implements `print`:

https://github.com/CGAL/cgal/blob/7a1ba12bab47123e5adc4536afef0359fb53ed97/Cartesian_kernel/include/CGAL/Cartesian/Aff_transformation_rep_3.h#L183-L189

I'd be happy to submit a PR with a patch, though I'm new around these parts, never really contributed to the project. I'll be sure to get acquainted with contribution guidelines.

**Comment by MaelRL** [comment]
Hello,

There is indeed a problem and your solution seems correct. There is no particular contribution guideline, but if you could base your work and PR on the 4.14 branch (https://github.com/CGAL/cgal/tree/releases/CGAL-4.14-branch), it would be great.

Thank you.

**Comment by rgcv** [comment]
Created at #4705

**Comment by lrineau** [comment]
Fixed by https://github.com/CGAL/cgal/pull/4705.
