### ISSUE TITLE
reproducibility

### ISSUE THREAD

**Issue by nschloe** [CGAL/cgal#4699]
We're trying to get [pygalmesh](https://github.com/nschloe/pygalmesh) into conda and this turns out to require a number of test tolerance relaxations. This is because the results of the used methods -- `CGAL::make_mesh_3<C3t3>` and friends -- are not exactly reproducible across different machines.

Why is that? Are there `rand` calls in the code? If yes, is it possible to set the seed?

**Comment by lrineau** [comment]
If the code uses `CGAL::Parallel_tag` to run Mesh_3 using threads, then the result is non deterministic.

Otherwise you can see the seed using the usual API of `Random`:
```c++
CGAL::get_default_random() = CGAL::Random(0);
```

I am not completely sure we can ensure that the results are deterministic across machine architectures.

**Comment by nschloe** [comment]
Alright, thanks!
