### ISSUE TITLE
CGAL::Polygon_mesh_processing::triangulate_refine_and_fair_hole() generates wrong result 

### ISSUE THREAD

**Issue by dainamyki** [CGAL/cgal#4706]
_Please use the following template to help us solving your issue._

## Issue Details

I am trying to fill a hole on a mesh(fig 1). The hole filling and refinement worked(fig 2).  But with triangulate_refine_and_fair_hole(), the fairing result can't be right(fig 3)(fairing_continuity as default value). When setting fairing_continuity as 0, the result seems to be right. But if fairing_continuity is set to 2, the result would be insane. The mesh to be filled is attached. 

[mesh.zip](https://github.com/CGAL/cgal/files/4585388/mesh.zip)
![mesh_with_hole](https://user-images.githubusercontent.com/43584030/81149235-d2ca1680-8f4b-11ea-8e30-590a646d9c2d.PNG)
![triangulate_and_refine_hole](https://user-images.githubusercontent.com/43584030/81149244-d6f63400-8f4b-11ea-9650-5443bb59670b.png)
![triangulate_refine_and_fair_hole](https://user-images.githubusercontent.com/43584030/81149249-db225180-8f4b-11ea-8e78-91e684dc6436.png)

## Environment

* CGAL version: 4.14
* Other libraries versions if used (Eigen, TBB, etc.):  Eigen 3.3.5

**Comment by danston** [comment]
Hi @dainamyki I will have a look at your problem asap and let you know what could have gone wrong.

**Comment by danston** [comment]
Hey @dainamyki. I have proposed a fix for the issue with fairing. You can find it in PR #4711. The issue was related to the way internal weights are computed. You can already try this fix by getting that PR. The result for your file should look something like that: 

![fairing](https://user-images.githubusercontent.com/8123586/81330536-82180200-90a0-11ea-9cd8-7d19e22b8c55.png)

**Comment by dainamyki** [comment]
Cool. Thank you so much for your wonderful work!

**Comment by lrineau** [comment]
Fixed by https://github.com/CGAL/cgal/pull/4711.
