### ISSUE TITLE
Shape detection detects 0 shapes

### ISSUE THREAD

**Issue by MuxLi** [CGAL/cgal#4716]
## Issue Details

Wrong results: Shape detection with region growing detects 0 planar shape, tried with a set of different parameters. 
[data.zip](https://github.com/CGAL/cgal/files/4606214/data.zip)

## Source Code
CGAL Example tried on custom data: Point_set_shape_detection_3/shape_detection_with_callback.cpp

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Linux 64 bits
* Compiler: g++ 7
* Release or debug mode: Release
* Specific flags used (if any):
* CGAL version: 4.14
* Boost version: 1.65
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by sgiraudot** [comment]
What parameters did you try? My very first try using 2 * average spacing as epsilon and cluster epsilon and 10 min points (default for the rest) works well, around 1200 shapes returned.

**Comment by MaelRL** [comment]
bump @MuxLi

**Comment by MuxLi** [comment]
It works after I save the data in pwn format.. Thanks for providing your parameter try
