### ISSUE TITLE
How to Use CGAL::Polygon_mesh_processing::triangulate_faces()

### ISSUE THREAD

**Issue by Haoqiantao** [CGAL/cgal#4717]
Hello:
  I want to use the method CGAL::Polygon_mesh_processing::triangulate_faces(PolygonMesh& pmesh),  but I do not know how to construct the PolygonMesh.
   I have a point list and a face list like what i show below:

struct VFMesh {
	std::vector<CGALPoint> pointlist;//点;
	std::vector<std::vector<int>> facelist;//面，保存面的点的索引;
};

Can you show me the code of how to construct the type of PolygonMesh?

Thanks.

**Comment by sloriot** [comment]
You can use the function [`polygon_soup_to_polygon_mesh()`](https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__repairing__grp.html#gae4bb69cfd25240e8f929239b02d8c7f8). There are some examples using this function mentioned directly in the documentation of the function.

**Comment by Haoqiantao** [comment]
Thanks for your answer, And I have another question.
I want to know after I get a result of Polyhedron through Boolean Operation of  Polyhedron_3, how to merge the triangles in result to get the bound. So I can get all faces of the result.
Which method or concept should I learn?
The code just like this:

Polyhedron mesh,mesh2, meshout;
Nef_polyhedron nefmeshout = mesh + mesh2;
nefmeshout.convert_to_polyhedron(meshout);

I want to merge the triangles in meshout to get all faces.

Thanks

**Comment by sloriot** [comment]
You might want to use [`convert_nef_polyhedron_to_polygon_mesh()`](https://doc.cgal.org/latest/Nef_3/group__PkgNef3IOFunctions.html#ga2e47f1a21e5b35af36c7ef665c66e848) that will not triangulate the output mesh.

Note also that there are other Boolean operation retricted to triangle meshes available [here](https://doc.cgal.org/latest/Polygon_mesh_processing/index.html#title13).

**Comment by Haoqiantao** [comment]
I use the version of CGAL is 4.8, I do not find these methods in CGAL.
Are these methods only in the lastest version of CGAL?
If i use the version 4.8, how can I do about the problem above.

Thanks.

**Comment by sloriot** [comment]
It was introduced in  4.12

**Comment by Haoqiantao** [comment]
Hello, I use the method "convert_nef_polyhedron_to_polygon_mesh()" and I have already get the face of the result.But I have another question, if the result Polyhedron has a hole in one of its face, How can I get the hole in which face, or can I get two loops to represent a face, one is the loop of the hole and the other is the loop of the face border?
The result just like this:
![image](https://user-images.githubusercontent.com/56966783/81880221-7b691d80-95bf-11ea-886b-50aed3c02649.png)
I want get two loops to respresent this face;

**Comment by sloriot** [comment]
This face will be triangulated by the aforementioned function as it is the only way to represent it using a surface mesh.

**Comment by Haoqiantao** [comment]
![G8W6R4)PL 9VWN~}UFLTME2](https://user-images.githubusercontent.com/56966783/82001543-f6990500-968d-11ea-87d7-db1cf7cc20d5.png)
There are 6 faces in this box, I use 24 points and 6 faces to form the Polyhedron(there are some repeat points), When I change the polyhedron to Nef_Polyhedron, it make a mistake.
My codes are below

std::vector<Kernel::Point_3> points; // the 24 points
std::vector< std::vector<std::size_t> > polygons;// 6 faces
	int index = 0;
	for (int i = 0; i < loops->size(); i++)
	{
		LOOP* loop = loops->at(i);
		for (int j = 0; j < loop->size(); j++)
		{
			points.push_back(CGALPoint((*loop)[j].x, (*loop)[j].y, (*loop)[j].z));
		}
		std::vector<std::size_t> face;
		for (int j = 0; j < loop->size(); j++)
		{
			face.push_back(index + j);
		}
		index += loop->size();
		polygons.push_back(face);
	}
	Polyhedron mesh;
	CGAL::Polygon_mesh_processing::polygon_soup_to_polygon_mesh(points, polygons, mesh);
// I can get the polyhedron , but it can not transform to Nef_Polyhedron
Nef_polyhedron nef(mesh);

the error message is 
msg = 0x008bc1d0 "it is not possible to decide which one is a visible facet (if any)"

**Comment by Haoqiantao** [comment]
Sorry to trouble you again.
I Have already get a Polyhedron, and I want get the orthogonal_vector of one of this polyhedron's faces. But the x ,y, z I get is always 0.5. I do not know why. How can I get the normal vector of the face?

Polyhedron mesh;
	for (Facet_iterator i = mesh.facets_begin(); i != mesh.facets_end(); ++i)
	{
		double x = CGAL::to_double(i->plane().orthogonal_vector().x());
		double y = CGAL::to_double(i->plane().orthogonal_vector().y());
		double z = CGAL::to_double(i->plane().orthogonal_vector().z());
	}

**Comment by sloriot** [comment]
Except if you compute them explicitly the plane are not set. It is just a place holder. Check out [this example](https://doc.cgal.org/latest/Polyhedron/Polyhedron_2polyhedron_prog_planes_8cpp-example.html).
