### ISSUE TITLE
How should I get these values

### ISSUE THREAD

**Issue by simonasdmd** [CGAL/cgal#4718]
_Please use the following template to help us solving your issue._

## Issue Details
hi~

I simplified the triangulation. Want to get some data. But I don't know how to get the data.

Please tell me how to get the data. I'm a novice so the question may be too simple.

## Source Code

![1589278099](https://user-images.githubusercontent.com/42527845/81672049-2e306300-947c-11ea-92bc-e80aacb21d40.png)

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): windows10 64
* Compiler: vs2017
* Release or debug mode:release
* Specific flags used (if any):
* CGAL version: 5.0
* Boost version:1.71
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by sloriot** [comment]
It seems that you are pointing to internal data structures. What information are you interested in having access to?

**Comment by simonasdmd** [comment]
@sloriot 
Simplify mesh vertex and face index.
I don't know how to get them.

**Comment by sloriot** [comment]
You can use the functions return a range, see [here](https://doc.cgal.org/latest/Surface_mesh/classCGAL_1_1Surface__mesh.html#a64c3d4bfd5057d782f1e93f1f302bf5f).

Note that for `Surface_mesh`, `Vertex_index` and `Face_index` are wrappers around an index type.

In particular it means that you can do something like that:

```
typedef CGAL::Surface_mesh<K::Point_3> Mesh;
Mesh m;
for (Mesh::Vertex_index v : m.vertices())
{
  std::size_t vid = v;
}

for (Mesh::size_type vid=0;vid<m..num_vertices(); ++vid)
{
  if (!m.is_removed(Mesh::Vertex_id(vid)))
  {
    // this is a valid vertex index
  }
}
```
The index will be in the range `[0, m.num_vertices()[`. Be carefull that `num_vertices()` might be different from `number_of_vertices()` if some removal operations were done on the mesh.
See [this section](https://doc.cgal.org/latest/Surface_mesh/index.html#title12) for more details.
