### ISSUE TITLE
cmake find_package requires 4.14.1000 for an exact match on version 4.14 (4.14.0 expected)

### ISSUE THREAD

**Issue by yobeonline** [CGAL/cgal#4720]
## Issue Details

When trying to find the CGAL package version 4.14 (exact match) with cmake, I have to write: `find_package(CGAL 4.14.1000 EXACT REQUIRED)` instead of `find_package(CGAL 4.14 EXACT REQUIRED)` or even `find_package(CGAL 4.14.0 EXACT REQUIRED)`.

I don't know if it is intended, but I find it hard to figure out the 1000 value.

In case it is not intentional, I tracked down the reason for this and it seems that the following correction to [CGAL_Macros.cmake](https://github.com/CGAL/cgal/blob/master/Installation/cmake/modules/CGAL_Macros.cmake#L400)  should fix it:
```diff
 write_basic_package_version_file("${CMAKE_BINARY_DIR}/CGALConfigVersion.cmake"
-      VERSION "${CGAL_MAJOR_VERSION}.${CGAL_MINOR_VERSION}.${CGAL_BUILD_VERSION}"
+      VERSION "${CGAL_MAJOR_VERSION}.${CGAL_MINOR_VERSION}.${CGAL_BUGFIX_VERSION}"
       COMPATIBILITY SameMajorVersion)
```

## Environment
I reproduced it on both linux and windows

**Comment by lrineau** [comment]
Hi @yobeonline. You are right. I have fixed that bug in the pull-request #4697, that fixes other bugs related to `CGALConfigVersion.cmake`, and add a test-suite.
