### ISSUE TITLE
Const to non-const conversion error

### ISSUE THREAD

**Issue by kfckfckf** [CGAL/cgal#4724]
Const to non-const conversion error

## Issue Details

I tried to compile the example for incremental searching (file: Spatial_searching/distance_browsing.cpp) with a small modification (line 30):

`std::cout <<   (*it).first << "  at squared distance = " << (*it).second << std::endl;`

to

`std::cout <<   it->first << "  at squared distance = " << it->second << std::endl;`

Then, a compiler error occured:

`C:\lib\CGAL\include\CGAL\iterator.h(618,1): error C2440: 'return': cannot convert from 'const std::pair<CGAL::Point_2<Kernel_>,double> *' to 'std::pair<CGAL::Point_2<Kernel_>,double> *'`

It seams to be a bug on the member access operator (->) of the class iterator.

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows 10 18363.836, x64 bits
* Compiler: MSVC 19.25.28614 for x64
* Release or debug mode: Release
* Specific flags used (if any): CGAL_HEADER_ONLY
* CGAL version: 4.14
* Boost version: 1.70
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by sloriot** [comment]
Thanks for the report. Fixed in #4725

**Comment by lrineau** [comment]
Fixed by https://github.com/CGAL/cgal/pull/4725.
