### ISSUE TITLE
CGAL_target_use_XXX.cmake is not available in vcpkg installation

### ISSUE THREAD

**Issue by jingyangcarl** [CGAL/cgal#4736]
I found there is only "CGAL_target_use_TBB.cmake" available when performing vcpkg installation on Windows OS, where I run 

PATH_TO_VCPKG> ./vcpkg.exe install cgal[qt]:x64-windows

As provided in CGAL/cgal/Installation/cmake/modules, there should be CGAL_target_use_[Boost_IOStreams/Boost_Serialization/Eigen/GLPK/LASLIB/OpenCV/OpenGR/SCIP/TBB/TensorFlow/pointmatcher] available in vcpkg installation under share/cgal.

So If a compilation using Eigen, CMake will pop up a CMake Error indicating: Unknown CMake command "CGAL_target_use_Eigen".

**Comment by sloriot** [comment]
This modification was introduced in master recently so it will be available in vcpkg with the next release.

**Comment by lrineau** [comment]
@jingyangcarl I agree with Sébastien. Unless you used `./vcpkg.exe install --head cgal[qt]:x64-windows` (with the `--head` option), you should get CGAL-5.0.2, and not the content of the `master` branch.
