### ISSUE TITLE
issue with compile the examples

### ISSUE THREAD

**Issue by aiyouweiyxx** [CGAL/cgal#4739]
_Please use the following template to help us solving your issue._

## Issue Details
I try to compile the examples given in your website by
`cd $HOME/CGAL-5.1-dev/examples/Triangulation_2 # go to an example directory
cmake -DCMAKE_BUILD_TYPE=Release . # configure the examples
make`
and I got the following error
`In file included from /usr/local/include/CGAL/Exact_predicates_inexact_constructions_kernel.h:20:
In file included from /usr/local/include/CGAL/Simple_cartesian.h:20:
In file included from /usr/local/include/CGAL/Cartesian/Cartesian_base.h:20:
In file included from /usr/local/include/CGAL/basic.h:21:
In file included from /usr/local/include/CGAL/config.h:118:
In file included from /usr/local/include/boost/config.hpp:57:
In file included from /usr/local/include/boost/config/platform/macos.hpp:28:
In file included from /usr/local/include/boost/config/detail/posix_features.hpp:18:
In file included from /Users/yxx/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/unistd.h:72:
/Users/yxx/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/sys/unistd.h:189:72: error: 
      expected function body after function declarator
  ...const char *, void *, void *, size_t, uint32_t) __OSX_AVAILABLE(10.13) _...
                                                     ^
In file included from /Users/yxx/Downloads/CGAL-5.0.2 2/examples/Triangulation_2/regular.cpp:1:
In file included from /usr/local/include/CGAL/Exact_predicates_inexact_constructions_kernel.h:20:
In file included from /usr/local/include/CGAL/Simple_cartesian.h:20:
In file included from /usr/local/include/CGAL/Cartesian/Cartesian_base.h:20:
In file included from /usr/local/include/CGAL/basic.h:21:
In file included from /usr/local/include/CGAL/config.h:118:
In file included from /usr/local/include/boost/config.hpp:57:
In file included from /usr/local/include/boost/config/platform/macos.hpp:28:
In file included from /usr/local/include/boost/config/detail/posix_features.hpp:18:
/Users/yxx/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/unistd.h:440:59: error: 
      expected function body after function declarator
int      execl(const char * __path, const char * __arg0, ...) __WATCHOS_...
                                                              ^
/Users/yxx/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/unistd.h:441:60: error: 
      expected function body after function declarator
  ...execle(const char * __path, const char * __arg0, ...) __WATCHOS_PROHIBIT...
                                                           ^
/Users/yxx/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/unistd.h:442:60: error: 
      expected function body after function declarator
  ...execlp(const char * __file, const char * __arg0, ...) __WATCHOS_PROHIBIT...
                                                           ^
/Users/yxx/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/unistd.h:443:56: error: 
      expected function body after function declarator
int      execv(const char * __path, char * const * __argv) __WATCHOS_PRO...
                                                           ^
/Users/yxx/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/unistd.h:444:80: error: 
      expected function body after function declarator
  ...* __file, char * const * __argv, char * const * __envp) __WATCHOS_PROHIB...
                                                             ^
/Users/yxx/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/unistd.h:445:57: error: 
      expected function body after function declarator
int      execvp(const char * __file, char * const * __argv) __WATCHOS_PR...
                                                            ^
/Users/yxx/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/unistd.h:446:19: error: 
      expected function body after function declarator
pid_t    fork(void) __WATCHOS_PROHIBITED __TVOS_PROHIBITED;
                    ^
/Users/yxx/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/unistd.h:536:14: error: 
      unknown type name '__WATCHOS_PROHIBITED'
__deprecated __WATCHOS_PROHIBITED __TVOS_PROHIBITED
             ^
/Users/yxx/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/unistd.h:536:52: error: 
      expected ';' after top level declarator
__deprecated __WATCHOS_PROHIBITED __TVOS_PROHIBITED
                                                   ^
/Users/yxx/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/unistd.h:585:14: error: 
      unknown type name '__WATCHOS_PROHIBITED'
__deprecated __WATCHOS_PROHIBITED __TVOS_PROHIBITED
             ^
/Users/yxx/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/unistd.h:585:52: error: 
      expected ';' after top level declarator
__deprecated __WATCHOS_PROHIBITED __TVOS_PROHIBITED
                                                   ^
/Users/yxx/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/unistd.h:605:20: error: 
      expected function body after function declarator
pid_t    vfork(void) __WATCHOS_PROHIBITED __TVOS_PROHIBITED;
                     ^
/Users/yxx/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/unistd.h:648:62: error: 
      expected function body after function declarator
  ...add_profil(char *, size_t, unsigned long, unsigned int) __WATCHOS_PROHIB...
                                                             ^
/Users/yxx/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/unistd.h:650:85: error: 
      expected function body after function declarator
  ...* __file, const char * __searchpath, char * const * __argv)  __WATCHOS_P...
                                                                  ^
/Users/yxx/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/unistd.h:674:3: error: 
      expected function body after function declarator
                __OSX_AVAILABLE(10.12) __IOS_AVAILABLE(10.0)
                ^
/Users/yxx/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/unistd.h:680:3: error: 
      expected function body after function declarator
                __OSX_AVAILABLE(10.12) __IOS_AVAILABLE(10.0)
                ^
/Users/yxx/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/unistd.h:683:3: error: 
      expected function body after function declarator
                __OSX_AVAILABLE(10.12) __IOS_AVAILABLE(10.0)
                ^
/Users/yxx/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/unistd.h:687:3: error: 
      expected function body after function declarator
                __OSX_UNAVAILABLE __IOS_AVAILABLE(10.0)
                ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
`
How can I use the cgal correctly?

## Environment

* Mac 64 bits:
* Compiler: g++11
* Release or debug mode:
* Specific flags used (if any): no
* CGAL version: 5.0.2
* Boost version: 1.72
* Other libraries versions if used (Eigen, TBB, etc.): eigen opengl

**Comment by sloriot** [comment]
It seems that the error comes from a file not from CGAL. Did you try to compile a simple program not using CGAL with that compiler?

**Comment by aiyouweiyxx** [comment]
I use Xcode to compile the program without cgal, it works. Once I add `#include <CGAL/Cartesian.h>`, it gives 20 errors like 
<img width="1074" alt="截屏2020-05-23上午10 46 48" src="https://user-images.githubusercontent.com/9382081/82720259-5aea4300-9ce4-11ea-85fc-640af1ec4a93.png">
<img width="1056" alt="截屏2020-05-23上午10 47 03" src="https://user-images.githubusercontent.com/9382081/82720260-60478d80-9ce4-11ea-841b-bdc58d7ef34d.png">

**Comment by sloriot** [comment]
Is your program only:
```
#include <CGAL/Cartesian.h>
int main(){}
```
?

**Comment by MaelRL** [comment]
@aiyouweiyxx bump

**Comment by SUJEET7488** [comment]
I am not give time to do
I can do it before september end
