### ISSUE TITLE
Snap rounding issues for lines

### ISSUE THREAD

**Issue by WindingWinter** [CGAL/cgal#4741]
I think there is a bug with snap rounding if you feed it with a certain input of lines. Here's the code to reproduce the example:

```
struct Kernel : public CGAL::Exact_predicates_exact_constructions_kernel  {};
typedef Kernel::FT                                         Number_type;
typedef Kernel::Point_2                             Point_2;
typedef Kernel::Point_3                             Point_3;
typedef Kernel::Vector_3                           Vector_3;
typedef CGAL::Arr_segment_traits_2<Kernel>            Traits_2;
typedef Traits_2::X_monotone_curve_2                  Segment_2;
typedef CGAL::Snap_rounding_traits_2<Kernel>     Traits;

int main()
{
        std::list<Segment_2> seg_list;
	seg_list.push_back(Segment_2(Point_2(914502435, 618115125), Point_2(914502375, 618114975)));
	seg_list.push_back(Segment_2(Point_2(914502375, 618114975), Point_2(914502407.60869575, 618115033.69565225)));

	seg_list.push_back(Segment_2(Point_2(914502503.04878044, 618115205.48780489), Point_2(914502427.63157892, 618115069.73684216)));
	seg_list.push_back(Segment_2(Point_2(914502427.63157892, 618115069.73684216), Point_2(914502390.38461542, 618114967.30769229)));
	seg_list.push_back(Segment_2(Point_2(914502390.38461542, 618114967.30769229), Point_2(914502475, 618114925)));

	seg_list.push_back(Segment_2(Point_2(914502525, 618115425), Point_2(914502375, 618114975)));
	seg_list.push_back(Segment_2(Point_2(914502375, 618114975), Point_2(914502435, 618115125)));
        Polyline_list_2 output_list;
        CGAL::snap_rounding_2<Traits,list<Segment_2>::const_iterator,Polyline_list_2> (seg_list.begin(), seg_list.end(), output_list, 50, false, false, 1);
}
```

This is the `seg_list` when plotted

![beforesnapround](https://user-images.githubusercontent.com/13161574/82635304-7eed4c00-9c32-11ea-85a0-8de684051658.png)

However, when I plot the `output_list`, it becomes something like this

![after snapround](https://user-images.githubusercontent.com/13161574/82635323-8ad90e00-9c32-11ea-836b-e1388f756434.png)

The topology seems very different, and it appears the snap rounding is not correct?

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows 10
* Compiler: Visual Studio 2015
* Release or debug mode: RELEASE
* Specific flags used (if any):
* CGAL version: 4.11
* Boost version: 1.66

**Comment by sloriot** [comment]
What is `Kernel`? And why do you think the snap rounding is not correct? At first sight I don't see anything surprising.

**Comment by WindingWinter** [comment]
Guess you are right, there is nothing wrong with CGAL...
