### ISSUE TITLE
orient_polygon_soup  BUG

### ISSUE THREAD

**Issue by simonasdmd** [CGAL/cgal#4746]
_Please use the following template to help us solving your issue._

## Issue Details

When I simplify the triangulation
Entering this function does not exit
Caton

## Source Code

![image](https://user-images.githubusercontent.com/42527845/82785170-9e83af00-9e94-11ea-9096-5b3ad9669b13.png)

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):windows 10
* Compiler: vs2017
* Release or debug mode:release
* Specific flags used (if any):
* CGAL version:5.0
* Boost version:1.7
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by sloriot** [comment]
Could you please provide the points + the faces so that we can try to reproduce the issue?

Side note: you are passing the vector of points and faces by copy and not by reference (which means that they are copied when calling the function).

**Comment by simonasdmd** [comment]
hi~ @sloriot 
this is my data:
[Tile_0_22.zip](https://github.com/CGAL/cgal/files/4676686/Tile_0_22.zip)

**Comment by simonasdmd** [comment]
hello~ anybody here~
i need help
from <Resident Evil>

**Comment by sloriot** [comment]
We had troubles reading your file so it took some time. You can call the function [`repair_polygon_soup()`](https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__repairing__grp.html#ga4a8bf46e90d0cd94e1edf7ed90d42f2f) before calling orient and it should work.

**Comment by simonasdmd** [comment]
@sloriot 
thanks~ it‘s work
It helped me a lot
If you can. Can you tell me what caused it.

**Comment by sloriot** [comment]
The soup was not valid (degenerate elements IIRC).

**Comment by simonasdmd** [comment]
@sloriot
 hi ,I revised it as you said, but there are still problems. Zip contains the original data and the simplified data. Please help me see where I still need to change.
test data：
[Tile_1.zip](https://github.com/CGAL/cgal/files/4693101/Tile_1.zip)
screenshot：
![image](https://user-images.githubusercontent.com/42527845/83096635-c06d7380-a0d8-11ea-81a5-7b0c12b32994.png)

**Comment by simonasdmd** [comment]
hi~ @sloriot  @lrineau 
SMS::Count_ratio_stop_predicate<Surface_mesh> stop(0.3);
When I set it to 0.3, it will be like this。

I think we can judge the concept of "minimum" internally. For example, according to normal conditions. A model consists of 10000 triangles. He's reduced to 30% and should be able to maintain geometry. But some special models. For example, it's big or complicated. Geometry cannot be maintained below 6000. But users can't judge whether they should use 0.6 or 0.3. Can they add some judgments?

**Comment by sloriot** [comment]
It is impossible to understand what problem you have if you don't explain what problem you are having. This issue is about soup -> mesh and then you are talking about the simplification package. The best way to show a problem is to provide a **minimal** example that we can run and that show the problem.
