### ISSUE TITLE
remove_outliers no matching overloaded function

### ISSUE THREAD

**Issue by xieanne** [CGAL/cgal#4748]
_Please use the following template to help us solving your issue._

## Issue Details

While compiling the full code for surface reconstruction from point cloud, there is a compilation error saying no matching remove outliers overloaded function. 
![image](https://user-images.githubusercontent.com/44624612/82907702-f1ad3e80-9f34-11ea-8216-4ed574d32d9f.png)

## Source Code
surface reconstruction from point clouds

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows, 64 bit 
* Compiler: 
* Release or debug mode: debug
* Specific flags used (if any):
* CGAL version: 5.0.2
* Boost version: 1_73_0
* Other libraries versions if used (Eigen, TBB, etc.):  eigen 3.3.4

**Comment by sloriot** [comment]
You have to remove the first template parameter, there is no parallel version of this function. See the [doc](https://doc.cgal.org/latest/Point_set_processing_3/group__PkgPointSetProcessing3Algorithms.html#gafd0b5a21ec5042e4bca09cb43f1847f9).

**Comment by sgiraudot** [comment]
My guess is you were using a code example from Github which shows the master version of CGAL by default, while your local installation is CGAL 5.0.2: you should never do that, as these might not be compatible (in that case, the template parameter for `remove_outliers` was added very recently in master and is not in any release yet, which is what triggered your error).
