### ISSUE TITLE
scale space surface reconstruction holes

### ISSUE THREAD

**Issue by xieanne** [CGAL/cgal#4756]
_Please use the following template to help us solving your issue._

## Issue Details

I am using scale_space_increment to reconstruct the kitten.off point cloud, but the result it gave me has holes on it, I am wondering if that is a normal situation or I did something wrong in the process.
![kitten](https://user-images.githubusercontent.com/44624612/83415193-bacfa080-a3ec-11ea-8df7-a3687ea8b23e.PNG)
Thank you for your patience.

## Source Code

scale_space_increment.cpp

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows 64bits
* Compiler:
* Release or debug mode: debug
* Specific flags used (if any):
* CGAL version: 5.0.2
* Boost version: 1_73_0
* Other libraries versions if used (Eigen, TBB, etc.): 3.3.4

**Comment by sgiraudot** [comment]
Are you sure these are holes? From what I see, this looks like faces with inverted normals that appear black. If you use the example as is, it is expected that the algorithm using alpha shape returns 2  layers of faces (one internal, the other external). My guess is that Meshlab randomly displays the internal or external layer for each face.

I would strongly suggest using the advancing front mesher instead (see [this example](https://doc.cgal.org/latest/Scale_space_reconstruction_3/Scale_space_reconstruction_3_2scale_space_advancing_front_8cpp-example.html)) which is guaranteed to only create one layer and give overall better results.

**Comment by xieanne** [comment]
Thank you, but when I try to compile the scale space advancing front code, it gives me the error of number of sections exceeded object file format limit even after I added the /bigobj into the command line
