### ISSUE TITLE
 Surface_mesh_intersection.cpp gives the incomplete result of polylines

### ISSUE THREAD

**Issue by Nikolatesla-lj** [CGAL/cgal#4758]
_Please use the following template to help us solving your issue._

## Issue Details

_Describe your issue. Please be specific (compilation error, runtime error, unexpected behavior, wrong results, etc.)._

## Source Code

_If your issue arises by using CGAL in your own source code, please provide a minimalist example that we can compile easily to reproduce the bug. If your issue arises from using a CGAL program (demo, example, etc.), please let us know which one. Helping you solving an issue is much easier and efficient if we can reproduce it._

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):Linux
* Compiler:
* Release or debug mode:
* Specific flags used (if any):
* CGAL version:5.0.2
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

When I try to run the  surface_mesh_intersection.cpp demo with my own 2  **.off files which separately include a 3D polygon,  it gives the wrong result.  As showing in the picture, I think it should return two points of polylines, but it only gives me one point in intersection_polines.cgal.
I want to know is there any way to solve this problem?

![2](https://user-images.githubusercontent.com/34672324/83472726-875b4780-a4ba-11ea-94f6-5dff62ab244b.png)

![1](https://user-images.githubusercontent.com/34672324/83472638-5e3ab700-a4ba-11ea-9cd5-ba2021da4d2a.png)

**Comment by Nikolatesla-lj** [comment]
@Sebastien Loriot

**Comment by sloriot** [comment]
Can you share the input?

**Comment by Nikolatesla-lj** [comment]
Polygon1.off
OFF
4 1 0
-0.1000000014901161 -0.1000000014901161 0.0000000000000000
0.1000000014901161 -0.1000000014901161 0.0000000000000000
-0.1000000014901161 0.1000000014901161 0.0000000000000000
0.1000000014901161 0.1000000014901161 0.0000000000000000
4 0 1 3 2
_________________________________________________________________________
Polygon2.off
OFF
4 1 0
0.0200000032782555 0.0499999783933163 -0.1000000014901161
0.2199999988079071 0.0499999783933163 -0.1000000014901161
0.0200000032782555 0.0499999709427357 0.1000000014901161
0.2199999988079071 0.0499999709427357 0.1000000014901161
4 0 1 3 2

**Comment by Nikolatesla-lj** [comment]
It is just very simple @sloriot

**Comment by sloriot** [comment]
They are but they are not triangle meshes. Try calling [`triangulate_faces()`](https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__meshing__grp.html#gacaaff4d520500c530d9c3d5ebe2a0760) on the meshes before calling the intersection computation.

**Comment by Nikolatesla-lj** [comment]
Thank you very much!! It worked

**Comment by afabri** [comment]
> They are but they are not triangle meshes. Try calling [`triangulate_faces()`](https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__meshing__grp.html#gacaaff4d520500c530d9c3d5ebe2a0760) on the meshes before calling the intersection computation.

Just to add my ten cents.   You probably started from the example, but it is wise to also read the Reference Manual [page](https://cgal.geometryfactory.com/CGAL/doc/master/Polygon_mesh_processing/group__PMP__corefinement__grp.html#ga09e9c6524834aebd2b2dcd5c0031d1d4).    It states that the input meshes must be a `TriangleMesh`.  We maybe should add a precondition checking this, so that users get an error message when they run it in Debug mode.
