### ISSUE TITLE
Is there a parallel implementation for CGAL::solve_quadratic_program()?

### ISSUE THREAD

**Issue by lijinbio** [CGAL/cgal#4764]
# Issue Details

I am using CGAL::solve_quadratic_program() for quadratic programming. However, it becomes very slow for a large number of variables. For example, a QP of ~400 variables takes about 40 minutes. It becomes infeasible to solve large variables, say 1000 variables. I seek to find out a parallel implementation of CGAL::solve_quadratic_program() so that I can use my many CPU cores but no luck. Please help suggest if the parallelization is supported for the QP solver or not. Thank you.

**Comment by MaelRL** [comment]
There is unfortunately no parallel version for CGAL's QP solver at this time and there are no plans to have such feature in the foreseeable future.
