### ISSUE TITLE
CGAL::hierarchy_simplify_point_set's behavior mismatch with documentation

### ISSUE THREAD

**Issue by shauidu** [CGAL/cgal#4765]
## Issue Details

unexpected behavior
CGAL::hierarchy_simplify_point_set's documentation says it will "Recursively split the point set until the clusters have less than size elements or until their variation factor is below var_max"

But the real behavior is "Recursively split the point set until the clusters have less than size elements AND until their variation factor is below var_max"

So I wonder which is the expect result.

Thanks.

**Comment by sgiraudot** [comment]
You are correct, the mistake came from the fact that the recursion continues if one OR the other condition is still not fulfilled, which is confirmed by this comment+code:
```c++
        // Split the set if size OR variance of the cluster is too large
        if (current_cluster->first.size () > size || var > var_max)
```

But of course, in the end, that means both conditions are met, hence AND is the right word. I'll fix the documentation. Thanks for the report!
