### ISSUE TITLE
why do you have all files of CGAL

### ISSUE THREAD

**Issue by SY524044272-python** [CGAL/cgal#4767]
I download CGAL, Boost and CMake,but when I tested the examples,I don't have some important header file.why do you have all files of CGAL?

**Comment by sloriot** [comment]
Could you please provide a more complete description of what you are trying to achieve, what you did and what did not work? With the information provided for now, it is not possible to help you.

**Comment by lrineau** [comment]
Maybe you have mixed one version of CGAL with the example from a more recent version of CGAL.

**Comment by SY524044272-python** [comment]
Thank you for your reply。I think there are few tutorials,it‘s difficult for me to learn it.’














At 2020-06-09 15:59:46, "Laurent Rineau" <notifications@github.com> wrote:

Maybe you have mixed one version of CGAL with the example from a more recent version of CGAL.
