### ISSUE TITLE
Exact_rational

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#477]
The ref man page of [`Exact_rational`](http://doc.cgal.org/4.7/Number_types/group__nt__cgal.html#ga0849ff44771b19582218ebdfa5614f64)

does not say that it falls back to `Quotient<MP_float>`
if none of GMP or Leda is installed. I also do not see
why it mentions Core, as if one has Core, one has GMP.

As a side question to @efifogel : Could we replace

     #include "arr_rational_nt.h"

with

     #include <CGAL/Exact_rational.h>

in the examples of the [Arrangement User Manual](http://doc.cgal.org/4.7/Arrangement_on_surface_2/index.html#title31)

**Comment by efifogel** [comment]
On Thu, Nov 12, 2015 at 2:09 PM, Andreas Fabri <notifications@github.com>
wrote:

> The ref man page of Exact_rational
> <http://doc.cgal.org/4.7/Number_types/group__nt__cgal.html#ga0849ff44771b19582218ebdfa5614f64>
>
> does not say that it falls back to Quotient
> if none of GMP or Leda is installed. I also do not see
> why it mentions Core, as if one has Core, one has GMP.
>
> As a side question to @efifogel <https://github.com/efifogel> : Could we
> replace
> #include "arr_rational_nt.h"
>
> with
> #include
>
Yes it should.
Thanks for pointing it out.
I will fix it.

in the examples of the Arrangement User Manual

**Comment by sloriot** [comment]
Fixed in #478
