### ISSUE TITLE
Mesh_3 parallel - regression

### ISSUE THREAD

**Issue by janetournois** [CGAL/cgal#4796]
##  Issue Details

I am meshing an implicit domain with Mesh_3 parallel, and facing this assertion :
```CGAL error: assertion violation!
Expression : this->is_facet_on_surface(facet)
File       : C:\Users\Jane\Documents\CGAL\cgal-dev\Mesh_3\include\CGAL/Mesh_3/Refine_facets_3.h
```

Since this crash happens with CGAL-5.0.2 but not with CGAL-5.0.1, I bisected and found that commit 
85712ba28c63b708f106517a78229665d9a3ef23 seems to be responsible for that crash. (Indeed there is no assertion with the previous commit).

## Source Code

@maxGimeno @lrineau I am sending it to you directly (it's simple).

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows
* Compiler: vs2019
* Release or debug mode: both
* Specific flags used (if any): `CGAL_LINKED_WITH_TBB` `CGAL_CONCURRENT_MESH_3`
* CGAL version: 5.0.2
* Boost version: 1.67.0
* Other libraries versions if used (Eigen, TBB, etc.): Eigen 3.7.0, TBB 2019 Update 3

**Comment by janetournois** [comment]
@lrineau @sloriot I think this is a release blocker so I added the label. Feel free to remove it if you think it's not appropriate

**Comment by janetournois** [comment]
our experiments show that it only happens with VS 2019.
Not VS 2017, nor g++

I am using Microsoft Visual Studio Professional 2019
Version 16.6.2

**Comment by lrineau** [comment]
That could be interesting to bisect also on the changes of commit 85712ba28c63b708f106517a78229665d9a3ef23. At least it can split into two: one change about `std::atomic`, and another one about `std::mutex`.

**Comment by maxGimeno** [comment]
It seems to be [this change](https://github.com/CGAL/cgal/commit/85712ba28c63b708f106517a78229665d9a3ef23#diff-6e2ed621c0c914d6aed52a33baa3c300L190), for some reason, that leads to the assert.

**Comment by lrineau** [comment]
Fixed by https://github.com/CGAL/cgal/pull/4798.
