### ISSUE TITLE
create_interior_straight_skeleton_2 delivers wrong results

### ISSUE THREAD

**Issue by MatthiasThDs** [CGAL/cgal#4801]
When I use my own coordinates using your examples/Straight_skeleton_2/Show_straight_skeleton.cpp , it delivers wrong results
Example taken from here:  https://github.com/CGAL/cgal/releases/download/releases/CGAL-5.0.2/CGAL-5.0.2-examples.zip

```
#include<boost/shared_ptr.hpp>

#include<CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include<CGAL/Polygon_2.h>
#include<CGAL/create_straight_skeleton_2.h>

#include "print.h"

typedef CGAL::Exact_predicates_inexact_constructions_kernel K;

typedef K::Point_2                   Point;
typedef CGAL::Polygon_2<K>           Polygon_2;
typedef CGAL::Straight_skeleton_2<K> Ss;

typedef boost::shared_ptr<Ss> SsPtr;

int main()
{
	Polygon_2 poly;

	poly.push_back(Point(156.95414789335337, 86.43026643898338));
	poly.push_back(Point(169.13231613952667, 89.69391872733831));
	poly.push_back(Point(170.4993676925078, 84.59204484708607));
	poly.push_back(Point(171.96335960307624, 84.98716750182211));
	poly.push_back(Point(173.0072708039079, 81.08687948156148));
	poly.push_back(Point(171.75630641821772, 80.751907040365042));
	poly.push_back(Point(173.54693781817332, 74.06583078298718));
	poly.push_back(Point(161.154334134073, 70.75313899852335));

	// You can pass the polygon via an iterator pair
	SsPtr iss = CGAL::create_interior_straight_skeleton_2(poly.vertices_begin(), poly.vertices_end());

	// Or you can pass the polygon directly, as below.

	// To create an exterior straight skeleton you need to specify a maximum offset.
	double lMaxOffset = 5;
	SsPtr oss = CGAL::create_exterior_straight_skeleton_2(lMaxOffset, poly);

	print_straight_skeleton(*iss);
	print_straight_skeleton(*oss);

	return 0;
}
```

Result
Straight skeleton with 16 vertices, 36 halfedges and 8 faces
(161.154,70.7531)->(156.954,86.4303) contour
(156.954,86.4303)->(161.154,70.7531) contour
(156.954,86.4303)->(169.132,89.6939) contour
(169.132,89.6939)->(156.954,86.4303) contour
(169.132,89.6939)->(170.499,84.592) contour
(170.499,84.592)->(169.132,89.6939) contour
(170.499,84.592)->(171.963,84.9872) contour
(171.963,84.9872)->(170.499,84.592) contour
(171.963,84.9872)->(173.007,81.0869) contour
(173.007,81.0869)->(171.963,84.9872) contour
(173.007,81.0869)->(171.756,80.7519) contour
(171.756,80.7519)->(173.007,81.0869) contour
(171.756,80.7519)->(173.547,74.0658) contour
(173.547,74.0658)->(171.756,80.7519) contour
(173.547,74.0658)->(161.154,70.7531) contour
(161.154,70.7531)->(173.547,74.0658) contour
(156.954,86.4303)->(0,0) bisector
(0,0)->(156.954,86.4303) bisector
(169.132,89.6939)->(2272.85,3733.62) bisector  <--- Obviously completely out of boundary
(2272.85,3733.62)->(169.132,89.6939) bisector
(170.499,84.592)->(2272.85,3733.62) bisector    <--- Obviously completely out of boundary
(2272.85,3733.62)->(170.499,84.592) bisector    <--- Obviously completely out of boundary
(171.963,84.9872)->(0,0) bisector
(0,0)->(171.963,84.9872) bisector
(173.007,81.0869)->(10460,-5861.19) bisector   <--- Obviously completely out of boundary
(10460,-5861.19)->(173.007,81.0869) bisector
(171.756,80.7519)->(10460,-5861.19) bisector   <--- Obviously completely out of boundary
(10460,-5861.19)->(171.756,80.7519) bisector   <--- Obviously completely out of boundary
(173.547,74.0658)->(0,0) bisector
(0,0)->(173.547,74.0658) bisector
(161.154,70.7531)->(0,0) bisector
(0,0)->(161.154,70.7531) bisector
(2272.85,3733.62)->(0,0) bisector
(0,0)->(2272.85,3733.62) bisector
(10460,-5861.19)->(0,0) bisector
(0,0)->(10460,-5861.19) bisector
Straight skeleton with 20 vertices, 60 halfedges and 12 faces
(144.626,102.022)->(144.626,58.4247) contour
(144.626,58.4247)->(144.626,102.022) contour
(144.626,58.4247)->(185.875,58.4247) contour
(185.875,58.4247)->(144.626,58.4247) contour
(185.875,58.4247)->(185.875,102.022) contour
(185.875,102.022)->(185.875,58.4247) contour
(185.875,102.022)->(144.626,102.022) contour
(144.626,102.022)->(185.875,102.022) contour
(156.954,86.4303)->(161.154,70.7531) contour
(161.154,70.7531)->(156.954,86.4303) contour
(161.154,70.7531)->(173.547,74.0658) contour
(173.547,74.0658)->(161.154,70.7531) contour
(173.547,74.0658)->(171.756,80.7519) contour
(171.756,80.7519)->(173.547,74.0658) contour
(171.756,80.7519)->(173.007,81.0869) contour
(173.007,81.0869)->(171.756,80.7519) contour
(173.007,81.0869)->(171.963,84.9872) contour
(171.963,84.9872)->(173.007,81.0869) contour
(171.963,84.9872)->(170.499,84.592) contour
(170.499,84.592)->(171.963,84.9872) contour
(170.499,84.592)->(169.132,89.6939) contour
(169.132,89.6939)->(170.499,84.592) contour
(169.132,89.6939)->(156.954,86.4303) contour
(156.954,86.4303)->(169.132,89.6939) contour
(144.626,58.4247)->(165.251,79.0495) bisector
(165.251,79.0495)->(144.626,58.4247) bisector
(185.875,58.4247)->(165.251,79.0495) bisector
(165.251,79.0495)->(185.875,58.4247) bisector
(185.875,102.022)->(165.251,81.3975) bisector
(165.251,81.3975)->(185.875,102.022) bisector
(144.626,102.022)->(165.251,81.3975) bisector
(165.251,81.3975)->(144.626,102.022) bisector
(161.154,70.7531)->(165.613,78.4705) bisector
(165.613,78.4705)->(161.154,70.7531) bisector
(173.547,74.0658)->(166.845,77.9383) bisector
(166.845,77.9383)->(173.547,74.0658) bisector
(171.756,80.7519)->(169.288,82.1775) bisector
(169.288,82.1775)->(171.756,80.7519) bisector
(173.007,81.0869)->(170.538,82.5134) bisector
(170.538,82.5134)->(173.007,81.0869) bisector
(171.963,84.9872)->(170.538,82.5134) bisector
(170.538,82.5134)->(171.963,84.9872) bisector
(170.499,84.592)->(166.633,77.8813) bisector
(166.633,77.8813)->(170.499,84.592) bisector
(169.132,89.6939)->(164.675,81.9728) bisector
(164.675,81.9728)->(169.132,89.6939) bisector
(156.954,86.4303)->(164.675,81.9728) bisector
(164.675,81.9728)->(156.954,86.4303) bisector
(169.288,82.1775)->(166.845,77.9383) bisector
(166.845,77.9383)->(169.288,82.1775) bisector
(169.288,82.1775)->(170.538,82.5134) bisector
(170.538,82.5134)->(169.288,82.1775) bisector
(166.633,77.8813)->(166.845,77.9383) bisector
(166.845,77.9383)->(166.633,77.8813) bisector
(166.633,77.8813)->(165.613,78.4705) bisector
(165.613,78.4705)->(166.633,77.8813) bisector
(164.675,81.9728)->(165.613,78.4705) bisector
(165.613,78.4705)->(164.675,81.9728) bisector
(165.251,79.0495)->(165.251,81.3975) bisector
(165.251,81.3975)->(165.251,79.0495) bisector

## Environment

Operating system (Windows 64 bits):
Compiler: Visual Studio 2019 16.0.3
Release or debug mode: both
Specific flags used (if any):
CGAL version: 5.1beta
Boost version: 1.73.0
Other libraries versions if used (Eigen, TBB, etc.):

**Comment by MatthiasThDs** [comment]
I tested the example from above with the CGAL version "4.14.3" as well and it produces the same errors.
Though, I am not sure if he loads some 5.x DLLs at runtime (if there are any), because i have both versions installed now.

**Comment by MatthiasThDs** [comment]
Here is a screenshot, when using those coordinates with the "Show_straight_skeleton" example from vers 4.14.3, which creates an eps file autmatically (unlike the newer cgal versions, which only print numbers)

![image](https://user-images.githubusercontent.com/50454126/85210824-7d9f6400-b343-11ea-9e16-ae11be8a29a6.png)

**Comment by sloriot** [comment]
You polygon is not correctly oriented. Add
```
  if (poly.is_clockwise_oriented())
    poly.reverse_orientation();
```
and you will get what you expect.

**Comment by MatthiasThDs** [comment]
thanks a lot for clarification!!
