### ISSUE TITLE
What is the best way to cite CGAL's delaunay triangulation algorithm?

### ISSUE THREAD

**Issue by SBCV** [CGAL/cgal#4802]
I would like to cite CGAL's delaunay triangulation algorithm, however neither the [corresponding documentation (Triangulation_3)](https://doc.cgal.org/latest/Triangulation_3/classCGAL_1_1Regular__triangulation__3.html) nor the [corresponding source code (Delaunay_triangulation_3.h)](https://github.com/CGAL/cgal/blob/master/Triangulation_3/include/CGAL/Delaunay_triangulation_3.h) contains any information about the method.
Thus, I'm wondering, if CGAL has it's own delaunay triangulation algorithm, or if it is following some existing paper. 
Would be nice if someone could me help out here.

**Comment by MaelRL** [comment]
The proper way to cite the package is indicated on this page : https://doc.cgal.org/latest/Manual/how_to_cite_cgal.html.

The 3D triangulations of CGAL use the standard Bowyer-Watson algorithm; the data structures and important parts are presented in the documentation of the package (https://doc.cgal.org/latest/Triangulation_3/index.html). Low-level implementation details do not have any documentation or publication.

**Comment by SBCV** [comment]
Thank you for clarifying this!
