### ISSUE TITLE
unexpected results when intersecting two segments when one of the segments has 0-length

### ISSUE THREAD

**Issue by bitonic** [CGAL/cgal#4805]
## Issue Details

I ran into an issue whereby I get spurious intersections when testing a 0-length segment against a segment which has length. Even if the segments do not intersect, `CGAL::intersection` erroneusly reports that they do. Not sure if 0-length intersections are considered invalid input to `CGAL::intersection`.

Intersecting the corresponding `Point_3` with the `Segment_3` with length yields no intersection as expected.

## Source Code

This is a C++ repro:

```
using namespace std;
using EK = CGAL::Exact_predicates_exact_constructions_kernel;
using Segment_3 = typename EK::Segment_3;

Segment_3 test_segment_1; 
istringstream("15.5444 1.53163 0.311164 15.5444 1.53163 0.311164") >> test_segment_1; 
Segment_3 test_segment_2; 
istringstream("15.568 1.79418 0.0550635 15.399 1.5103 -0.0616675") >> test_segment_2; 
const auto test_intersection = CGAL::intersection(test_segment_1, test_segment_2); 
if (test_intersection) {
  throw runtime_error("Spurious intersection"); 
}
```

And this is .ply file that you can load in MeshLab to verify that the two segments do not intersect:

```
ply
format ascii 1.0
element vertex 3
property float x
property float y
property float z
element edge 1
property int vertex1
property int vertex2
end_header
15.5444 1.53163 0.311164
15.568 1.79418 0.0550635
15.399 1.5103 -0.0616675
1 2
```

This is what it looks like:

![2020-06-22-220125_1544x1297_scrot](https://user-images.githubusercontent.com/556090/85332852-f4219a80-b4d8-11ea-9ad2-41c68b164908.png)

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Debian 10
* Compiler: g++ (GCC) 9.2.0
* Release or debug mode: debug
* Specific flags used (if any):
* CGAL version: 5.0.2
* Boost version: 1.66.0
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by sloriot** [comment]
The function expects the input to be non-degenerate. If you know that you might have some degenerate segments, then you should write a small wrapper function checking for degeneracies and forward the call to `intersection(point,segment)` or `intersection (point, point)`. I started #4654 that adds preconditions to make it clearer.

**Comment by bitonic** [comment]
@sloriot thanks -- I expected as much. It would be good to mention this in the docs.
