### ISSUE TITLE
Tetrahedral remeshing failed to deal with complex inputs

### ISSUE THREAD

**Issue by WinnieLaugh** [CGAL/cgal#4808]
## Issue Details
runtime error
Hi, I tried to use the new package **Tetrahedral_remeshing** and found that it fails to deal with some complex meshes. A minimal example that can fail the program is provided at:
https://drive.google.com/file/d/1r6NqV2RVhNfZkXLPvcFlAwf4aSoUJQ3C/view?usp=sharing

The error is like folllowing:
![image](https://user-images.githubusercontent.com/10320523/85433255-bb57f300-b5b6-11ea-8687-006ea750785a.png)

## Environment

* Operating system: Windows, 64 bits
* Compiler: Visual Studio 2015
* Release or debug mode: Debug
* Specific flags used (if any):
* CGAL version: 5.1
* Boost version: 1.73.0
* Other libraries versions if used (Eigen, TBB, etc.): None

Thanks!

**Comment by janetournois** [comment]
Hi @WinnieLaugh 
thank you for your report.
I could reproduce your issue with `target_edge_length=5.0` (guessed from your log)
I will take a look at it

**Comment by WinnieLaugh** [comment]
Hi, @janetournois 
Thanks for your work!

**Comment by janetournois** [comment]
Hi @WinnieLaugh 
The bug is fixed by the PR #4812
Thanks again for the report!

**Comment by WinnieLaugh** [comment]
Hi, @janetournois 
Thanks for your quick reply and wonderful work!
