### ISSUE TITLE
Polyhedron demo : add a triangulation_3_item

### ISSUE THREAD

**Issue by janetournois** [CGAL/cgal#4819]
## Issue Details

I think it would make sense to create a `triangulation_3_item` to be able to display a `Triangulation_3` in the demo, and perform operations on it.
It would be useful for `tetrahedral_isotropic_remeshing()`, because its only input in the API in a Triangulation_3. 

## Source Code

To be really useful for tetrahedral remeshing, I would need the exact type to be `CGAL::Triangulation_3<C3T3::Triangulation::Geom_traits, C3T3::Triangulation::Triangulation_data_structure>` (`C3T3` is defined in `C3t3_type.h`

Then we would need a `triangulation_3_io_plugin` which could be part of the current effort on CGAL I/Os.

@maxGimeno do you think you can have a look at that please?
@lrineau @MaelRL

**Comment by maxGimeno** [comment]
>Then we would need a triangulation_3_io_plugin which could be part of the current effort on CGAL I/Os.
I can (and probably will) base the branch on the I/O  branch, but I don't think we should start developing new things in that branch. It's really heavy enough like that :/

**Comment by janetournois** [comment]
A new branch definitely is a better option
