### ISSUE TITLE
Add an automatic testsuite for our CMake use-cases

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#4826]
# Add an automatic testsuite for our CMake use-cases

That is the first step before we can modernize the CMake scripts of CGAL (see issue #4815).

The goal is to test automatically the CMake scenarios that we support, either in our CI tests or in the daily testsuite.

## What do we want to support
See also https://github.com/CGAL/cgal/issues/4815#issuecomment-650180229.

In all cases, we want to test the scenario:
  - from a Git repository,
  - from a tarball layout.

The tests from the tarball layout could be easily done from the CGAL testsuite, and the test from the Git layout can be easily done from the CI.

Here are the cases we want to support:
- usage from the source code, without configuring CGAL at all, with `CGAL_DIR` pointing to the directory containing:
  - `Git/CGALConfig.cmake` (for the Git layout only),
  - `CGAL-5.x*/CGALConfig.cmake` (from a tarball),
  - `Git/Installation/lib/cmake/CGAL/CGALConfig.cmake` (Git) or `CGAL-5.x*/lib/cmake/CGAL/CGALConfig.cmake` (tarball)
- configure all CGAL with `-DWITH_examples=ON -DWITH_demos=ON -DWITH_tests=ON`, and then launch CTest on a few labels.
- configure CGAL (as header-only), then use its build-directory as `CGAL_DIR` (we might want to support that use-case to be compatible with our usage with non-header-only, for CGAL-4.14),
- CGAL installed in the default prefix, with or without the CGAL_Qt5 header-files,
- CGAL installed in a non-default prefix, with or without the CGAL_Qt5 header-files.
- others...?

All the test-cases should verify that the user-defined project (can be one of our examples or tests directory) configures, compiles, and runs fine.

## What we do not want to support
  - in-source builds,
  - `CGAL_NOT_HEADER_ONLY` (see https://github.com/CGAL/cgal/issues/4815#issuecomment-652313461).

## What do we test for the moment

- In Travis, we test two different scenario:
  1. The CGAL libraries are configured (from the Git layout) with `cmake -DWITH_examples=ON -DWITH_demos=ON -DWITH_tests=ON ..`, and then `make install`'ed to the default prefix `/usr/local:
    https://github.com/CGAL/cgal/blob/9cfb0401a489b0f35f43a1416c96677e0d411c6c/.travis.yml#L66-L70
    then for each examples or tests directory, the directory is configured out-of-source:
    https://github.com/CGAL/cgal/blob/9cfb0401a489b0f35f43a1416c96677e0d411c6c/.travis/build_package.sh#L12-L15
  2. In the `CHECK` job of the Travis tests, we also test an installation in a non-default prefix, 
    and then a user-defined project is configured, with the corresponding `CGAL_DIR`. But we do not test if it builds and runs correctly. 
    https://github.com/CGAL/cgal/blob/9cfb0401a489b0f35f43a1416c96677e0d411c6c/.travis/build_package.sh#L95-L115

**Comment by lrineau** [comment]
@maxGimeno I have created this issue to give details about what is to be done. We can discuss that in Telegram once you are ready.

@CGAL/geometryfactory Please comment, on the scenarii we want to support. In particular, I have removed all tests of non-header-only CGAL.

**Comment by maxGimeno** [comment]
>configure CGAL (as header-only), then use its build-directory as CGAL_DIR (we might want to support that use-case to be compatible with our usage with non-header-only, for CGAL-4.14),

I thought we wanted to drop the support fr that case

**Comment by maxGimeno** [comment]
Note: 
- FIXTURES appeared in cmake 3.7
