### ISSUE TITLE
CGAL::remove_outliers error C2672 error C2770

### ISSUE THREAD

**Issue by YRstronger** [CGAL/cgal#4830]
_Please use the following template to help us solving your issue._

## Issue Details

I am learning exmaple of Surface Reconstruction in Manual of CGAL 5.1. I copied all those example code but the two error occurs. I am a starter of CGAL and also don't find any useful solution online. 

error C2672: "CGAL::remove_outliers": No matching overloaded function found
error C2770: The explicit template parameter for "PointRange::iterator CGAL::remove_outliers(PointRange &,unsigned int,const NamedParameters &)" is invalid

## Source Code

	CGAL::remove_outliers<CGAL::Sequential_tag>
		(points,
			24, // Number of neighbors considered for evaluation
			points.parameters().threshold_percent(5.0)); // Percentage of points to remove

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows 
* Compiler: 2017 msvc
* Release or debug mode: release
* Specific flags used (if any):
* CGAL version: 5.1
* Boost version: 1.72
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by sgiraudot** [comment]
Did you use the exact same example code or did you just copy bits of it? If so, can you post the full code you compiled?
Can you please also post the output of `cmake`?

**Comment by YRstronger** [comment]
I copied all those example code into my new project which has correct dir including CGAL, Boost and gmp lib. 

But I ignored the version. I used 5.0.1 so that error occurs and I thought this function has no difference in those two version. But I am wrong after reading renive_outliers.h file of two version.

other errors are present when I use the right version!

** cgal-5.1-beta1\include\cgal\poisson_surface_reconstruction.h(104): error C2672: “CGAL::Poisson_reconstruction_function<Kernel>::compute_implicit_function”: No matching overloaded function found**

**cgal-5.1-beta1\include\cgal\poisson_surface_reconstruction.h(104): error C2780: “bool CGAL::Poisson_reconstruction_function<Kernel>::compute_implicit_function(SparseLinearAlgebraTraits_d,bool)”: 2 parameters should be entered, but 0 are provided**

**cgal-5.1-beta1\include\cgal\poisson_surface_reconstruction.h(104): error C2780: “bool CGAL::Poisson_reconstruction_function<Kernel>::compute_implicit_function(SparseLinearAlgebraTraits_d,Visitor,double,double)”: 4 parameters should be entered, but 0 are provided**


Code is same as example provided here: https://cgal.geometryfactory.com/CGAL/doc/master/Manual/tuto_reconstruction.html#TutorialsReconstruction_recap

The only difference now I think is that the gmp lib I used is still 5.0.1 because when I download the 5.1, there is no gmp lib file and I use older one. 

Finally, I do not use cmake because I use the prebuilt version. I just add a new project in Visual Studio, add Dir, paste the example code. 

Thanks for your reply!

**Comment by sgiraudot** [comment]
You need to use the Eigen library if you want to use Poisson (see [the manual section about it](https://doc.cgal.org/latest/Manual/thirdparty.html#title8)).

I'm not a Windows user so I can't help much on this matter, but I am pretty sure you should still use CMake files to configure your project (especially if you need 3rd party libraries like Eigen, which in this case, you do).

**Comment by YRstronger** [comment]
Thanks for your help! I can solve those problems by my own.
If it's ok, can i close this issue?

**Comment by sgiraudot** [comment]
You're welcome, I'm happy to help!

I'll close the issue.
