### ISSUE TITLE
Add an interface for statistical helpers

### ISSUE THREAD

**Issue by jjerphan** [CGAL/cgal#4843]
## Issue Details

Having mesh statistics is convenient to perform subsequent processing on a mesh. 
Some [CGAL internals](https://github.com/CGAL/cgal/blob/master/Polyhedron/demo/Polyhedron/include/CGAL/statistics_helpers.h) exist to compute mesh statistics, but they aren't exposed.

Could it be possible to add an interface for them?

I can work on this if appropriate. :slightly_smiling_face:

**Comment by afabri** [comment]
Hello Julien,   Feel free to join thee effort.   
In  the  Polygon Mesh Processing package we regrouped several functions under the title [Measure](https://cgal.geometryfactory.com/CGAL/doc/master/Polygon_mesh_processing/group__measure__grp.html).  That could be a starting point.    If we see that it grows out of this it could become something bigger. 
We could start collecting in this issue the statistics functions you have in mind.   
Note that in the Polyhedron demo we also have color coding faces based on the smallest angle, etc.   This could be linked to histograms.

**Comment by jjerphan** [comment]
Hi Andreas,

Thanks for your answer. I am basically interested in getting the statistics and boolean information which are:
 - the number of vertices, edges, faces
 - the minimum altitude
 - the number of degenerated faces and edges (i.e null length edges) 
 - the minimum, maximum, mean and median of:
   - edge lengths, angles, areas and aspect-ratio
 - the minimum, maximum, mean and median angles
 - the minimum, maximum, mean and median areas
 - the minimum, maximum
 - the area
 - the volume and genus when relevant
 - whether the mesh self intersect 
 - whether the mesh is a triangle mesh
 - whether the mesh is closed
 - whether the mesh has non manifold vertices
 - the number of connected components and borders

The functions present in [`Polyhedron/demo/Polyhedron/include/CGAL/statistics_helpers.h`](https://github.com/CGAL/cgal/blob/master/Polyhedron/demo/Polyhedron/include/CGAL/statistics_helpers.h) allow to get those informations, there are solely not accessible in this package if I am not wrong.

**Comment by jjerphan** [comment]
Hi @afabri,

How do you think of integrating those in CGAL? :)

**Comment by afabri** [comment]
One problem is that the functions are not all in the same package, and with doxygen we can only have them once in a reference manual page.   For example the test whether a mesh has holes or not  is in the chapter  [CGAL and the Boost Graph Library](https://cgal.geometryfactory.com/CGAL/doc/master/BGL/group__PkgBGLHelperFct.html#gae04c8044cf1eee6a84baa5b79ab99fef).  

What are our options. We could write a section on statistics in the User Manual of the  Polygon Processing Package.   This would more or less have the above list with links to the various functions.   We could  have a namespace with more or less wrappers for the functions. This would have the benefit that they had a Reference Manual, but at the price of redundancy, and drift.

**Comment by jjerphan** [comment]
Sorry, I think that I should have been clearer: the functions present in `Polyhedron/demo/Polyhedron/include/CGAL/statistics_helpers.h` are not linkable if I am not mistaken.

To be more explicit, the linker will fail when using:

```cpp
#include <CGAL/statistic_helpers.h>
```
or
```cpp
#include <CGAL/Polygon/statistic_helpers.h>
```

More generally, all the header files in the demo folder `Polyhedron/demo/` aren't linkable.
This makes sense for a demo, but maybe having the features of `statistics_helpers.h` accessible would be convenient?

Though integrating the remaining functions of `statistics_helpers.h` in `Measure` definitely will introduce some redundancy, this might be an simple solution to have them accessible, leaving the demo unchanged and self-contained.

I hope this message is clearer, let me know if this is not the case.
