### ISSUE TITLE
cmake: CGAL_VERSION not set in subsequent calls to find_package(CGAL)

### ISSUE THREAD

**Issue by almightykiwi** [CGAL/cgal#4850]
## Issue Details

If different subdirectories use `find_package(CGAL)` in a project, only the first one will set the variable `CGAL_VERSION`.

## Source Code

* [cgal-cmake-repro.zip](https://github.com/CGAL/cgal/files/4949362/cgal-cmake-repro.zip):

```
$ tree
.
├── a
│   └── CMakeLists.txt
├── b
│   └── CMakeLists.txt
└── CMakeLists.txt

$ cat CMakeLists.txt 
project(blah)
add_subdirectory(a)
add_subdirectory(b)

$ cat a/CMakeLists.txt 
find_package(CGAL)
message("CGAL_VERSION: ${CGAL_VERSION}")

$ cat b/CMakeLists.txt 
find_package(CGAL)
message("CGAL_VERSION: ${CGAL_VERSION}")
```

* cmake output (emphasis mine):

<pre>
$ mkdir build     
$ cd build
$ cmake -DCGAL_DO_NOT_WARN_ABOUT_CMAKE_BUILD_TYPE=ON -Wno-dev ..
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/lib/ccache/cc
-- Check for working C compiler: /usr/lib/ccache/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/lib/ccache/c++
-- Check for working CXX compiler: /usr/lib/ccache/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using header-only CGAL
-- Targetting Unix Makefiles
-- Using /usr/lib/ccache/c++ compiler.
-- Found GMP: /usr/lib/x86_64-linux-gnu/libgmp.so  
-- Found MPFR: /usr/lib/x86_64-linux-gnu/libmpfr.so  
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found suitable version "1.71.0", minimum required is "1.48")  
-- Boost include dirs: /usr/include
-- Boost libraries:    
-- Using gcc version 4 or later. Adding -frounding-math
<b>CGAL_VERSION: 5.00.2.100
CGAL_VERSION: </b>
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/cgaltest/build
</pre>

## Environment

* Operating system: Ubuntu 20.04
* Compiler:
* Release or debug mode:
* Specific flags used (if any):
* CGAL version: 5.0.2-3 (package `libcgal-dev`)
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

## Ideas

I think `CGALConfig.cmake` returns before setting `CGAL_VERSION` here: https://github.com/CGAL/cgal/blob/aea6ac3e064106785112c30b21757b8d48a0db06/Installation/lib/cmake/CGAL/CGALConfig.cmake#L109-L111

**Comment by lrineau** [comment]
That is a know bug, that is already solved in Git branches by the merge of PR https://github.com/CGAL/cgal/pull/4697. I hope to publish new releases of CGAL soon.

**Comment by almightykiwi** [comment]
Quick note for the sake of completeness: I tried with master, and CGAL_VERSION is indeed set each time, but with different values:

<pre>
$ cmake -DCGAL_DIR=../../cgal -DCGAL_DO_NOT_WARN_ABOUT_CMAKE_BUILD_TYPE=ON -Wno-dev ..
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using header-only CGAL
-- Targetting Unix Makefiles
-- Using /usr/bin/c++ compiler.
-- Found GMP: /usr/lib/x86_64-linux-gnu/libgmp.so  
-- Found MPFR: /usr/lib/x86_64-linux-gnu/libmpfr.so  
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found suitable version "1.71.0", minimum required is "1.48")  
-- Boost include dirs: /usr/include
-- Boost libraries:    
-- Using gcc version 4 or later. Adding -frounding-math
<b>CGAL_VERSION: 5.1.0.000
CGAL_VERSION: 5.1</b>
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/cgal-cmake-repro/build
</pre>

This bit of code looks redondant with CGALConfigVersion.cmake: https://github.com/CGAL/cgal/blob/52dabb89ada393b7b88917187f7be70e8c61e85f/Installation/lib/cmake/CGAL/CGALConfig.cmake#L164-L171

**Comment by lrineau** [comment]
I reopen the issue. Thanks to your repro zip, I can easily reproduce the same issue with `master`.
