### ISSUE TITLE
How to merge two triangular mesh surfaces?

### ISSUE THREAD

**Issue by Micalson** [CGAL/cgal#4867]
Hello, thank you for this nice lib. It helps me a lot.
I have a question, and maybe someone could answer me. I have two triangular mesh surfaces with overlapping regions, and is there  a ready-made function which could merge the two mesh surfaces in CGAL? Thank you.

regards,

**Comment by sloriot** [comment]
What do you mean by merge?

If  you have two triangle meshes bounding two volume and you would like to have only one surface bounding the union of the volume, you can use [`corefine_and_compute_union()`](https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__corefinement__grp.html#gad7e1741a7ce41a5846cf86494982ca8b). If you only want to make a raw merge you can use [`copy_face_graph`](https://doc.cgal.org/latest/BGL/group__PkgBGLHelperFct.html#ga2d3eb044bfe42eab566779ce32216c11).

**Comment by Micalson** [comment]
@sloriot What I mean by that is that the two mesh surfaces(not necessarily a closed surface) can be automatically optimized as a whole where they overlap,.

**Comment by sloriot** [comment]
I see you somehow want to blend surfaces (maybe reconstructions from different view points). There is nothing doing that out of the box.

**Comment by Micalson** [comment]
Thanks. @sloriot
