### ISSUE TITLE
clip mesh error

### ISSUE THREAD

**Issue by KeepFaithMe** [CGAL/cgal#4868]
_Please use the following template to help us solving your issue._

## Issue Details
I have a mesh, and I want to bisect it along the X-axis.Therefore, I first calculate the mesh bounding box, using (xmin + xmax) / 2 getting the offset distance d, and then constructing a flat plane (1,0,0, -d), using this way to mesh segmentation, but for my mesh,I can't use this way to clip mesh, the CGAL version is 4.14.1, but previously I used the CGAL version 4.13.1, using the way of the above can be normal cliping the mesh,Since I need to use some of the functions in 4.14.1, I have to replace the version.I am confused.Could you tell me what's the problem?

The is data: https://gist.github.com/KeepFaithMe/9b8bcd2eaf94ed12d76f2c6bb08a613b
## Source Code
```c++
#include<CGAL/Polygon_mesh_processing/bbox.h>
#include <iostream>
#include<fstream>
#include<CGAL/Polygon_mesh_processing/clip.h>
#include<CGAL/Surface_mesh.h>
namespace zc
{
	typedef CGAL::Simple_cartesian<double> Kernel;
	typedef CGAL::Surface_mesh<Kernel::Point_3> Surface_mesh;
	typedef typename boost::graph_traits<Surface_mesh>::face_descriptor    face_descriptor;
	typedef Surface_mesh::Vertex_iterator Vertex_iterator;
	typedef Surface_mesh::Face_iterator Face_iterator;
	typedef Surface_mesh::Halfedge_index halfedge_index;
	typedef Surface_mesh::Face_index face_index;
	typedef Surface_mesh::Vertex_index vertex_index;
	namespace PMP = CGAL::Polygon_mesh_processing;
	namespace params = PMP::parameters;
}
int main() {
	zc::Surface_mesh mesh;
	ifstream open("21.off");
	open >> mesh;
	open.close();
	CGAL::Bbox_3 bb_3 = zc::PMP::bbox(mesh);
	double x_d_left = (bb_3.xmin() + bb_3.xmax()) / 2;
	Kernel::Plane_3 plane_1(1, 0, 0, -x_d_left);
	zc::PMP::clip(mesh, plane_1, zc::params::clip_volume(false).throw_on_self_intersection(false));
	std::ofstream out("xx.off");
	out << mesh;
	out.close();
	return 0;
}
```
## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):
* Compiler:
* Release or debug mode:
* Specific flags used (if any):
* CGAL version:
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by sloriot** [comment]
You are being tricked by isolated vertices that creates a bbox larger than what you expected.
Add `zc::PMP::remove_isolated_vertices(mesh);` just before the call to `bbox()` and you'll get what you expect.

Side note: replace `CGAL::Simple_cartesian<double>` by `CGAL::Exact_predicates_inexact_constructions_kernel`, details [here](https://www.cgal.org/FAQ.html#inexact_NT).
