### ISSUE TITLE
Deprecate Polyhedral_mesh_domain_with_features_3(std::string) constructor

### ISSUE THREAD

**Issue by gdamiand** [CGAL/cgal#488]
When using a Polyhedral_mesh_domain_with_features_3 constructor taking an off filename as parameter, there is no way to test if there was an error during the constructor (for example if the given file does not exist, or it there is an error during the reading...).

One solution could be to add exceptions in order to detect and catch the possible errors.

**Update:**

Andreas proposed that the constructor is deprecated.

**Comment by afabri** [comment]
I would deprecate the constructor with the string.

**Comment by sgiraudot** [comment]
What can we do to close this issue? Is deprecating the constructor with string the right solution? Who can take care of it?

**Comment by lrineau** [comment]
#827 has removed the usage. We still have to deprecate the constructor, in the code and in the documentation.

**Comment by afabri** [comment]
In fact, just deprecating is not really a solution. We then need a constructor with  a `std::istream&` as parameter. And in this case as well, the constructor might fail, even if we can check before that the stream is valid. Here are some options:
- A valid stream is good enough.
- The class may get a function that it is valid, which may be tested after the construction.
- The constructor might throw an exception. 
- The construction could be done by a free function.
I would go for the first option. 

_Question:_ Do we have more constructors which take an istream as parameter?

**Comment by lrineau** [comment]
Fixed by #1640.
