### ISSUE TITLE
How to use visitor parameter for clip function

### ISSUE THREAD

**Issue by LaporteThomas** [CGAL/cgal#4886]
## Issue Details

I'm working with the clip function to split a Polyhedron in half according to a plane, and I'd like to retrieve the new faces created in this clip, and apply a remesh to them.
I've seen that the visitor parameter can help with this, but I don't really understand how to use it.
Hope someone can help me.

**Comment by MaelRL** [comment]
The visitor is a class that you provide and whose functions are being called at certain precise points while the algorithm is running (e.g. face creation). The visitor API is fixed and your visitor class must provide these functions. These requirements are described in the concept: https://doc.cgal.org/latest/Polygon_mesh_processing/classPMPCorefinementVisitor.html.

There is no precise example of `clip()` and this visitor, but there is the example [corefinement_mesh_union_with_attributes.cpp](https://github.com/CGAL/cgal/blob/master/Polygon_mesh_processing/examples/Polygon_mesh_processing/corefinement_mesh_union_with_attributes.cpp), which illustrates usage of this precise visitor for a very similar function (both that function and `clip()` use the same core functions).
