### ISSUE TITLE
Polyhedron and surface_mesh Basic viewers appear blank (White Screen only appears with axes) 

### ISSUE THREAD

**Issue by rezanajianasl** [CGAL/cgal#4887]
## Issue Details

I have been runnign CGAL examples that use basic viewer functionality to visualize some 2D and 3D geometries, namely draw_surface_mesh.cpp and draw_polyhedron.cpp. 
Executables get generated without any error, however when I execute them, blank screen (White Screen only appears with axes) appear as follows 

![image](https://user-images.githubusercontent.com/62375973/88691231-e3c69600-d0fc-11ea-9092-764e2b5dbadc.png)

I do not know if this is a bug or and issue of my linux env and compilers, Can anyone comment on it ?

Also I tried draw_polygon.cpp, draw_polygon_with_holes.cpp and draw_triangulation_3.cpp. They are all fine. 

## Source Code
examples/Surface_mesh/draw_surface_mesh.cpp and examples/Polyhedron/draw_polyhedron.cpp.

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):Linux 64
* Compiler: GNU 7.3.1
* Release or debug mode: Release 
* Specific flags used (if any):
* CGAL version: 5.0.2
* Boost version: 1.73.0
* Other libraries versions if used (Eigen, TBB, etc.): Qt 5.11.2

**Comment by sloriot** [comment]
Both examples are reading an off file (default being "data/cross.off") taken as parameters. Did you pass a mesh or is the default path valid from where the exe are run?

**Comment by rezanajianasl** [comment]
@sloriot Thanks for your post. Actually I tried both. First I tried to visualize locally created surface meshes and I got blank white screen. Then I simply compiled and ran Surface_mesh, Polyhedron, Triangulation_3 and Polygon examples. 
I observed similar behaviour in draw_surface_mesh and draw_polyhedron, however draw_polygon, draw_polygon_with_holes and draw_triangulation_3 display their respective geometries. 

Any idea what the issue is ?! Hwy only happens for Surface_mesh and Polyhedron objects ?!

Thanks again.

**Comment by sloriot** [comment]
Sorry but I'm not sure to understand your answer.

did you run:
`> draw_polyhedron mymesh.off`
and got a blank screen
and also run:
`> draw_polyhedron`
and got a blank screen while
`> ls data/cross.off`
display the file?

**Comment by rezanajianasl** [comment]
@sloriot You are right. My stupid mistake since first I tried draw_Triangilation_3 which does not require off file. Also I overlooked implementations in *.cpp files. Indeed, when I give the off files, I get the shape.

Thanks a lot for the support.

Cheers,
