### ISSUE TITLE
CGAL-5.0.3 was published

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#4894]
I have published CGAL-5.0.3.

- [x] Re-upload the pre-compiled demos @lrineau 
- [x] update PR for brew package @maxGimeno (done: https://github.com/Homebrew/homebrew-core/pull/59068)
- [x] update PR for vcpkg @maxGimeno (done: https://github.com/microsoft/vcpkg/pull/12711)
- [x] update RPM for Fedora ([done](https://bodhi.fedoraproject.org/updates/FEDORA-2020-84ff78773d))

**Comment by lrineau** [comment]
@maxGimeno Please post the links to PRs for brew and vcpkg

**Comment by maxGimeno** [comment]
- vcpkg : https://github.com/microsoft/vcpkg/pull/12711
