### ISSUE TITLE
Compile CGAL_Qt5 and libtorch together: librsvg-2.so.2: undefined reference to `cairo_tag_end'

### ISSUE THREAD

**Issue by jingma-git** [CGAL/cgal#4896]
## Issue Details

I want to use LibTorch in CGAL, and I use CMake to configure and build the project. When I link CGAL_Qt5 and LibTorch libraries together by `target_link_libraries(draw_surface_mesh PUBLIC CGAL::CGAL_Qt5  ${TORCH_LIBRARIES})`, it gives me following errors:
`[build] /usr/bin/ld: /lib/x86_64-linux-gnu/librsvg-2.so.2: undefined reference to 'cairo_tag_end'`
`[build] /usr/bin/ld: /lib/x86_64-linux-gnu/librsvg-2.so.2: undefined reference to 'cairo_tag_begin'`

I doubt it is because there is some conflicts between CGAL_Qt5 library and LibTorch library, and I do not know how to resolve it.

## Source Code

Here is the CMakeLists.txt
```cmake
cmake_minimum_required(VERSION 3.1...3.15)
project(MyCGAL)

set(CMAKE_PREFIX_PATH "path to LibTorch")
set(CGAL_DIR "path to CGAL")
set(CMAKE_BUILD_TYPE RELEASE)

find_package(CGAL REQUIRED OPTIONAL_COMPONENTS Qt5)

if(CGAL_Qt5_FOUND)
  #required to use basic_viewer
  add_definitions(-DCGAL_USE_BASIC_VIEWER -DQT_NO_KEYWORDS)
endif()

find_package(Torch REQUIRED)

find_package(CGAL QUIET)

if ( CGAL_FOUND )
if (MSVC)
    # Allow Windows 32bit applications to use up to 3GB of RAM
    SET (CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} /LARGEADDRESSAWARE")
    message( STATUS "USING DEBUG CXXFLAGS   = '${CMAKE_CXX_FLAGS} ${CMAKE_CXX_FLAGS_DEBUG}'" )
    message( STATUS "USING DEBUG EXEFLAGS   = '${CMAKE_EXE_LINKER_FLAGS} ${CMAKE_EXE_LINKER_FLAGS_DEBUG}'" )
    message( STATUS "USING RELEASE CXXFLAGS = '${CMAKE_CXX_FLAGS} ${CMAKE_CXX_FLAGS_RELEASE}'" )
    message( STATUS "USING RELEASE EXEFLAGS = '${CMAKE_EXE_LINKER_FLAGS} ${CMAKE_EXE_LINKER_FLAGS_RELEASE}'" )
endif()

find_package(Eigen3 3.1.0)
include(CGAL_Eigen_support)
if (TARGET CGAL::Eigen_support)
    create_single_source_cgal_program( "draw_surface_mesh.cpp" )
    target_link_libraries(draw_surface_mesh PUBLIC CGAL::CGAL_Qt5 CGAL::Eigen_support ${TORCH_LIBRARIES})
else()
    message(STATUS "NOTICE: The examples need Eigen 3.1 (or greater) will not be compiled.")
endif()
else()
    message(STATUS "NOTICE: This program requires the CGAL library, and will not be compiled.")
endif()
```

## Environment

* Operating system (Ubuntu 20.04 LTS, 64 bits):
* Compiler: gcc 7.5.0
* Release or debug mode: Release
* Specific flags used (if any):
* CGAL version: CGAL-5.1-beta2
* Other libraries versions : **I compile pytorch from source to make it adapt to my OS with OpenCV option set as ON, and I use the Latest pytorch (which released in July 2020 and can be downloaded from https://github.com/pytorch/pytorch#from-source **

**Comment by lrineau** [comment]
It seems your code not only depend on Torch, but also on `librsvg`. I do not see how that library got linked with your binary.

**Comment by MaelRL** [comment]
Bump @jingma-git
