### ISSUE TITLE
C++11 std::pair causes order-of-instantiation issues in CRTP

### ISSUE THREAD

**Issue by mglisse** [CGAL/cgal#49]
See http://stackoverflow.com/q/27748442/1918193

**Comment by lrineau** [comment]
Why do you fill a CGAL issue. Do you think that is a bug of CGAL? I thought it was a bug in libc++?

**Comment by mglisse** [comment]
Please read the comments below the question (ignore the answer, it is useless).

**Comment by mglisse** [comment]
Copying some of it, in case it disappears:
- it fails with clang, not with gcc, independently of libstdc++ vs libc++
- http://llvm.org/bugs/show_bug.cgi?id=22085

**Comment by lrineau** [comment]
You should also modify your initial post to give directly the pertinent link to the useful comment. Is that http://stackoverflow.com/questions/27748442/is-clangs-c11-support-reliable#comment44298738_27748442 ?

I suggest you compile somewhere (either here or in SO) a convincing explanation why the code in CGAL is wrong.

**Comment by lrineau** [comment]
[The comment c4 of the LLVM seems][c4] to be the right answer.

[c4]: https://llvm.org/bugs/show_bug.cgi?id=22085#c4

**Comment by lrineau** [comment]
Actually, even [the comment c4 of the LLVM bug][c4] is not sufficient. Is libc++ allowed to implement `std::pair` that way? Is CGAL allowed to use `std::pair` that way?

[c4]: https://llvm.org/bugs/show_bug.cgi?id=22085#c4

**Comment by mglisse** [comment]
As I already said, the same problem appears with libstdc++, which makes a bug in libc++ unlikely. This is a complicated issue, I filed a bug so it doesn't get lost, I don't pretend that I understand it fully or have a fix ready.

**Comment by lrineau** [comment]
You are right. That is strange. By the way, should the CGAL testsuite test clang on Linux with libstdc++ and C++11? Does it make sense?

I wonder why the bug can be seen in the C++11 implementation of libstdc++, but not in its c++98 version.

**Comment by mglisse** [comment]
clang-c++11-libstdc++: I don't think you can test all the combinations of {gcc,clang}-{c++03,c++11,c++14}-{libstdc++,libc++} with all the possible versions of each and the different compilation flags, but sure, more testing is always better (should there be a random generator that selects what to test each night?). Note that it is quite possible the issue wouldn't be visible, it depends in subtle ways on the order of the includes, typedefs, functions, etc.
C++11 vs C++98: the test for is_constructible in the constructor of std::pair is new in C++11 (there is a #if to enable it only in C++11), and it is (part of) the cause of this issue.

**Comment by sgiraudot** [comment]
This issue can be closed (fixed by https://github.com/CGAL/cgal/issues/561).
