### ISSUE TITLE
Best practices for serializing exact construction data?

### ISSUE THREAD

**Issue by alecjacobson** [CGAL/cgal#490]
I have a set of 3d points represented in the exact construction kernel (`CGAL::Exact_predicates_exact_constructions_kernel`, aka `CGAL::Epeck`). I'd like to save these points to a (binary) file and then be able to load them back in (losslessly) later. Is there already some functionality in CGAL to do this?
Or do you have recommendations for doing this?

**Comment by alecjacobson** [comment]
Seems that there are methods for writing `gmp` types to file: http://stackoverflow.com/a/18069234/148668

but CGAL might not be using gmp depending on the flags/installation?

**Comment by sloriot** [comment]
For each points,  call `CGAL::exact()` and then use the stream operator.

**Comment by alecjacobson** [comment]
Will this work between different CGAL installations/flags? Suppose on Machine A, `CGAL_USE_GMP` is defined and I write a file `foo.bin` then I send that file to Machine B where `CGAL_USE_GMP` is not defined, will Machine B understand how to read in `foo.bin`?

**Comment by sloriot** [comment]
It should be working if you do not use an esoteric number type I guess.
About the binary format, in that case you'll be in trouble I think if you change the underlying NT.
See [set_binary_mode](http://doc.cgal.org/latest/Stream_support/index.html)
