### ISSUE TITLE
Automatic run of Doxygen on pull-requests

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#4900]
Github has announced yesterday a change in Github actions:
https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/

I think that would allows us, now, to run the Doxygen compilation automatically on pull-requests, using Github actions.

@maxGimeno I think you can add that in your todo-list.

**Comment by maxGimeno** [comment]
Done in https://github.com/CGAL/cgal-testsuite-dockerfiles/pull/109
