### ISSUE TITLE
Adding polygons with holes to polygon set changes its arrangement

### ISSUE THREAD

**Issue by HollowSun0** [CGAL/cgal#4903]
## Issue Details

Hello! I am trying to add multiple polygons inside one single polygon set, but there seems to be an arrangement update. I'm adding the polygons like shown in the first schema:

![Example_input](https://user-images.githubusercontent.com/43864651/89450910-57822780-d729-11ea-873d-0dd2fb303445.png)

by going from the biggest to the smallest. Ordering of the polygons is represented by the 3D arrow glyphs. The code used to add these polygons is described between lines 146 to 165 shown here: https://github.com/ShapeShift3D/cgal-community-plugins/blob/feature/2Dboolean/Plugins/CGAL/vtkCGAL/vtkCGALPolyLineSetToPolygonSet.cxx#L146

The resulting answer gives an output where arrow directions are reversed:

![Example_output](https://user-images.githubusercontent.com/43864651/89449886-b8a8fb80-d727-11ea-942e-abf531dcc8aa.png)

For a more clear observation of the issue, a print of both structures have been made:

![test_print](https://user-images.githubusercontent.com/43864651/89451637-7fbe5600-d72a-11ea-99c7-98a66b5de7d0.png)

Polygons are appended following the descending order of the text.

## Source Code

It's hard to reproduce without VTK. If there's any need to reproduce, I can export polygons into sets of points.

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows 10 Version 1909
* Compiler: Microsoft Visual C++ 2019
* Release or debug mode: RelWithDebInfo
* Specific flags used (if any): **NOMINMAX**
* CGAL version: 4.14.3 (SHA 23beca416cdd3ae04852a8a4736bca72bdac27bb)
* Boost version: 1.69
* Other libraries versions if used (Eigen, TBB, etc.): Eigen

**Comment by sloriot** [comment]
AFAIU, what you are trying to represent cannot be represented by a polygon with holes. A polygon with holes bound a connected region of the plane. In you case you have 4 connected components, each being representable as a polygon with holes. Maybe using `General_polygon_with_holes_2` with `Polygon_with_holes_2` you can achieve what you want. There are other options too but it depends on what you want to do with it.

**Comment by efifogel** [comment]
1. What do you mean by "arrangement update"? If you add a polygon why would
you expect the underlying arrangement not to change?
2. Why have you provided 2 images?
3. The textual data resembles the 2nd image. There are 3 polygons with one
hole in each and another polygon without holes. What is the problem?
   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by HollowSun0** [comment]
> AFAIU, what you are trying to represent cannot be represented by a polygon with holes. A polygon with holes bounds a connected region of the plane. In your case you have 4 connected components, each being representable as a polygon with holes. Maybe using `General_polygon_with_holes_2` with `Polygon_with_holes_2` you can achieve what you want. There are other options too but it depends on your usage.

I'll try and see if General_polygon_with_holes_2 helps in keeping the arrangement.

> 1. What do you mean by "arrangement update"? If you add a polygon why would you expect the underlying arrangement not to change? 2. Why have you provided 2 images? 3. The textual data resembles the 2nd image. There are 3 polygons with one hole in each and another polygon without holes. What is the problem? ____ _ ____ _ /_____/_) o /__________ __ // (____ ( ( ( (_/ (_/-(-'_(/ _/

1. There is probably a reason it changes but I don't understand why.

2. The first image is the set of polygons that have been fed to the Polygon_Set_2 object. The second image is a visual representation of the Polygon_Set_2 object.

3. So the reason why I'm doing a Polygon_Set_2 (Filter 1) -> VTK PolyLines -> Polygon_Set_2 (Filter 2) conversion is to be able to chain filters in ParaView and being able to visualize all the different blocks independently. One definitive fix would be to remove all these conversions and pass the Polygon_Sets_2 directly, but there is some value to being able to use these filters by themselves.

Maybe it is just the way I set these polygons. Indeed, I can just set 4 polygons with holes but instead, I set 7 of them (1 for each closed loop): 4 polygons without holes and 3 holes without outer boundaries. I should maybe keep track of that information in Filter 1 and give it to Filter 2 so it constructs its Polygon_Set_2 correctly.

**Comment by HollowSun0** [comment]
Ok well even though I don't understand the logic behind the polygon automatic reordering, appending them in my set with only 4 polygons with holes worked! Thanks for the help!
