### ISSUE TITLE
AABB_tree: What is this underscore about 

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#4907]
## Issue Details

[Here ](https://doc.cgal.org/latest/AABB_tree/classCGAL_1_1AABB__face__graph__triangle__primitive.html#ae8e0ac62f0e7a1a209d157a5f8cc222a) we write `VertexPointPMap`  and later  `VertexPointPMap_`.

## Environment
* CGAL version: master

**Comment by sloriot** [comment]
It's a typo, it should be _ (because of `Default`).

**Comment by afabri** [comment]
I would prefer if it was without  _    Can that not be achieved?

**Comment by MaelRL** [comment]
Can be done using the `DOXYGEN_RUNNING` macro, it's actually how it's done in some other parts of the AABB tree package (e.g. https://github.com/CGAL/cgal/blob/master/AABB_tree/include/CGAL/AABB_face_graph_triangle_primitive.h#L101).

**Comment by lrineau** [comment]
Fixed by #5229.
