### ISSUE TITLE
Polyhedron demo - snapshot of C3T3 does not shoot the edges

### ISSUE THREAD

**Issue by janetournois** [CGAL/cgal#4927]
## Issue Details

In the demo, generate a mesh with Mesh_3, and use "save snapshot". The snapshot shoots the facets with their proper patch-id-color, but the edges are not drawn. The png image saved is similar to "flat" mode of the demo.

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows
* Compiler: msvc 2019
* Release or debug mode: Release
* CGAL version: master

**Comment by janetournois** [comment]
@maxGimeno can you please have a look?

**Comment by maxGimeno** [comment]
The problem comes from a call to viewer->makeCurrent() in the intersection item. It is already fixed in #4811, it caused other problems too.

**Comment by janetournois** [comment]
ok thank you!

**Comment by lrineau** [comment]
Closed by the merge of #4949.
