### ISSUE TITLE
Travis: Link error in master

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#4929]
Travis: Link error in master

https://travis-ci.com/github/CGAL/cgal/jobs/372634815#L3778

**Comment by sloriot** [comment]
This one is probably related too:
https://travis-ci.com/github/CGAL/cgal/jobs/363252180#L2909

**Comment by maxGimeno** [comment]
My guess is that the boost build from he new ppa is not performed with the option --with-zlib, so the boost_iostreams.so is not complete and once again we are screwed by the IO of classification.
