### ISSUE TITLE
Expr: m_face_range.size() > 0

### ISSUE THREAD

**Issue by XGL96** [CGAL/cgal#4934]
## Issue Details

I tried to run the demo *region_growing_on_polygon_mesh.cpp*, but it caused an error that
```cpp
* polygon mesh with 0 faces is loaded
terminate called after throwing an instance of 'CGAL::Precondition_exception'
  what():  CGAL ERROR: precondition violation!
Expr: m_face_range.size() > 0
File: /usr/local/include/CGAL/Shape_detection/Region_growing/Region_growing_on_polygon_mesh/One_ring_neighbor_query.h
Line: 87
Aborted (core dumped)
```
It looks like it did not read in my face data. I suspect that my off file was in the wrong format, but my mesh gets imported correctly in both cloudcompare and meshlab.

The following is what my data looks like.
```tex
OFF
116776 233520 0
23.4571 17.4015 -0.155859 
23.639 24.2195 -0.155859 
23.7811 13.3576 -0.155859 
24.4917 24.0049 -0.155859 
23.4968 17.3453 -0.155859 
...
3 83 81 3 
3 3 14 83 
3 84 83 14 
3 14 24 84 
3 29 83 86 
...
```
And the download link for the data I used is
https://drive.google.com/file/d/16VcG30PqdZqqVxCWWf5vPXTrfWXwc85e/view?usp=sharing

## Source Code

The demo was *Shape_detection/region_growing_on_polygon_mesh.cpp* on https://doc.cgal.org/latest/Shape_detection/index.html#Chapter_Shape_Detection. And my parameters are the default ones in the example.

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):    Linux
* Compiler:    g++ (Ubuntu 8.4.0-1ubuntu1~18.04) 8.4.0
* Release or debug mode:    debug?
* Specific flags used (if any):    -lgmp -lmpfr
* CGAL version:    5.0.3
* Boost version:    1.65
* Other libraries versions if used (Eigen, TBB, etc.):    Eigen 3.3.4

**Comment by danston** [comment]
Hi. Your file is not a valid surface mesh that is its facets are not correctly oriented. What you try to load is a polygon soup that does not have connectivity among its facets and hence this particular example fails. The example works only for polygon meshes, not for soups. 

You can:
- fix your facets orientation though I have tried a quick test and it seems that your polygon soup is not directly orientable;
- transform your mesh into a point cloud and run RG on the point cloud (this is what I think you have already tried);
- create your own model of the region growing that handles polygon soups in some way (more [here](https://doc.cgal.org/latest/Shape_detection/index.html#Shape_detection_RegionGrowingFramework)).

**Comment by XGL96** [comment]
Thanks for the reply, by **quick test** do you mean the example *Polygon_mesh_processing / orient_polygon_soup_example.cpp*?

> Hi. Your file is not a valid surface mesh that is its facets are not correctly oriented. What you try to load is a polygon soup that does not have connectivity among its facets and hence this particular example fails. The example works only for polygon meshes, not for soups.
> 
> You can:
> 
> * fix your facets orientation though I have tried a quick test and it seems that your polygon soup is not directly orientable;
> * transform your mesh into a point cloud and run RG on the point cloud (this is what I think you have already tried);
> * create your own model of the region growing that handles polygon soups in some way (more [here](https://doc.cgal.org/latest/Shape_detection/index.html#Shape_detection_RegionGrowingFramework)).

**Comment by XGL96** [comment]
To be honest I don't really understand the difference between soup and mesh (it seems to be Orientation and connectivity?). CGAL is really an awesome library.

**Comment by XGL96** [comment]
By the way, can I ask which example content you recommend to use for computing mesh based on point cloud? I have seem a lot of the examples in Mesh Generation, but their inputs are images or meshes (the inputs are off files, but the examples check if they are triangle meshes directly using *CGAL::is_triangle_mesh*).

**Comment by danston** [comment]
> Thanks for the reply, by **quick test** do you mean the example _Polygon_mesh_processing / orient_polygon_soup_example.cpp_?

Sort of. I actually use the CGAL demo from the `Polyhedron` package that enables to apply various CGAL algorithms.

**Comment by danston** [comment]
> To be honest I don't really understand the difference between soup and mesh (it seems to be Orientation and connectivity?). I just tried the example _Polygon_mesh_processing / orient_polygon_soup_example.cpp_, and it worked. CGAL is really an awesome library.

Soup is an ungrouped set of disjoint triangles/polygons. Even when triangles are close to each other and seem to be connected visually, in fact, no triangle knows its neighbors. Mesh is when each triangle knows its neighbors so you can walk from one triangle to another. Great that you managed to orient your data set. It seemed to be quite complex.

**Comment by danston** [comment]
> By the way, can I ask which example content you recommend to use for computing mesh based on point cloud? I have seem a lot of the examples in Mesh Generation, but their inputs are images or meshes (the inputs are off files, but the examples check if they are triangle meshes directly using _CGAL::is_triangle_mesh_).

Do you want to get a mesh from a point cloud? - If so, you should address the Shape Reconstruction set of packages [here](https://doc.cgal.org/latest/Manual/packages.html#PartReconstruction). Otherwise, please explain in more detail what is your task so that I could guide you better.

**Comment by XGL96** [comment]
Thank you very much for your answers, I think these are what I'm wondering about.

Just one more question, I see that the mesh file is quite similar to soup, with faces as "3 point_index point_index point_index" after the points, how does it know the neighbors for each one?

**Comment by danston** [comment]
It is either created by someone and then provided in the [off file format](https://en.wikipedia.org/wiki/OFF_(file_format)) (or any other similar file format) or there are special algorithms that create connectivity. You can find them in the second chapter of [this book](http://www.pmp-book.org/). You can also read [here](https://doc.cgal.org/latest/HalfedgeDS/index.html#Chapter_Halfedge_Data_Structures).

**Comment by afabri** [comment]
Well, the off format does not encode neighborhoods.   So algorithmically for a face with index `f` with the index triple `i, j, k`   one typically puts `(i, j),f`  and `(j,k),f`and `(k,i),f`  in a `std::map<std::pair<int,int>,int>`   and checks if it stores  a face for `j,i` and so on.  And if there is another face with `i,j`  then we have the situation of incoherent orientation, or more than 2 faces sharing an edge (called non-manifold).

**Comment by danston** [comment]
Yep, my bad, @afabri is right, the off does not encode neighbors! I was a bit sloppy here.

**Comment by XGL96** [comment]
Thanks for the answers, I see there is 116776 vertices, 233520 faces and 0 edges in soup and 116785 vertices, 233520 faces and 0 edges in mesh. So the conversion between it might be redistributing some of the edges shared by more than 3 faces through the extra 9 points?

**Comment by danston** [comment]
If your count is right, during the conversion several vertices could be duplicated.

**Comment by XGL96** [comment]
True, they appeared twice. Thank you both for your answers.
