### ISSUE TITLE
Polyhedron demo - Mesh global optimizers loose their patch IDs

### ISSUE THREAD

**Issue by janetournois** [CGAL/cgal#4935]
## Issue Details

In the demo :
- open a polyhedron with sharp edges (e.g. data/star.off)
- run Mesh_3 (default parameters are OK) : the surface has one color per patch ID
![image](https://user-images.githubusercontent.com/11311305/90521423-c8cecb00-e16a-11ea-868e-cf26ff8c84da.png)

- run `lloyd_optimize_mesh_3()` : the surface has lost (almost all) its patch colors/IDs
![image](https://user-images.githubusercontent.com/11311305/90521510-e7cd5d00-e16a-11ea-8452-665b0503293b.png)

Note that :
- `odt_optimize_mesh_3()` has the same issue, but `perturb_mesh_3()` and `exude_mesh_3()` don't.
- I have tried in a standalone cpp file (I can send it if it helps) and the patch IDs are valid.

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows
* Compiler: MSVC 2019
* Release or debug mode: Release
* CGAL version: master
* Boost version: 1.67.0

**Comment by janetournois** [comment]
@maxGimeno can you please have a look?

**Comment by maxGimeno** [comment]
When you call optimizations in the demo, you re-create a new domain based on the original item used in mesh_3. The difference is that in mesh_3, in the default parameters, you detect charp edges. In the new domain, everything is default, so no feature is detected, and that is why there is no surface_patch_id after an optimization. 

That also means that all the bounderies are lost during optimization. I wonder if it is a problem.
