### ISSUE TITLE
error while building an appplication

### ISSUE THREAD

**Issue by AlexandreMagnolc** [CGAL/cgal#4946]
_Please use the following template to help us solving your issue._

## Trying to install an application tha uses CGAL but i can't make it.
Everytime time I try to "make~my application I got this error.

I reinstalled Qt5, CGAL and many other dependencies, but I still got this error. Any ideas on what to do next?  

CMake Error at /usr/lib/x86_64-linux-gnu/cmake/CGAL/CGALConfig.cmake:137 (message):
  ERROR: The CGAL_Qt5 library was not configured.  CGAL was configured with
  WITH_CGAL_Qt5=ON, **but one of the dependencies of CGAL_Qt5 was not
  configured properly.**
Call Stack (most recent call first):
  /usr/lib/x86_64-linux-gnu/cmake/CGAL/CGALConfig.cmake:147 (check_cgal_component)
  ../CMake/find_packages.cmake:7 (find_package)
  CMakeLists.txt:37 (INCLUDE)

## Source Code

_If your issue arises by using CGAL in your own source code, please provide a minimalist example that we can compile easily to reproduce the bug. If your issue arises from using a CGAL program (demo, example, etc.), please let us know which one. Helping you solving an issue is much easier and efficient if we can reproduce it._

## Environment

* UBUNTU Windows subsystem

**Comment by lrineau** [comment]
Qt5 has several components. Probably you did not install what was necessary.

```shell
sudo apt install libqt5opengl5-dev
```

The simplest way to install CGAL on Ubuntu is via the package manager:
```shell
sudo apt install libcgal-qt5-dev
```

If the packages are well done, it should install everything that is required.

**Comment by AlexandreMagnolc** [comment]
@lrineau 
The libqt5opengl5-dev was missing, I'm a newbie using Linux, thanks for your reply
