### ISSUE TITLE
STL_reader.h can not read binary file ,but other soft can open it.

### ISSUE THREAD

**Issue by for-heart-peace** [CGAL/cgal#4954]
_Please use the following template to help us solving your issue._

## Issue Details

_Describe your issue. Please be specific (compilation error, runtime error, unexpected behavior, wrong results, etc.)._

## Source Code

_If your issue arises by using CGAL in your own source code, please provide a minimalist example that we can compile easily to reproduce the bug. If your issue arises from using a CGAL program (demo, example, etc.), please let us know which one. Helping you solving an issue is much easier and efficient if we can reproduce it._

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):
* Compiler:
* Release or debug mode:
* Specific flags used (if any):
* CGAL version:
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by MaelRL** [comment]
Please provide the problematic STL file.

**Comment by for-heart-peace** [comment]
> Please provide the problematic STL file.

can I send it to you?

Error is Error while reading vertex coordinates (premature end of file)

thank you

**Comment by MaelRL** [comment]
If it is not confidential, you can host it on https://gist.github.com/ for example.

If it is, you can send it to me at mael.rouxel.labbe@geometryfactory.com and it will not be shared.

**Comment by for-heart-peace** [comment]
> If it is not confidential, you can host it on https://gist.github.com/ for example.
> 
> If it is, you can send it to me at [mael.rouxel.labbe@geometryfactory.com](mailto:mael.rouxel.labbe@geometryfactory.com) and it will not be shared.

send to your mail, thank you for you raply.

**Comment by MaelRL** [comment]
What version of CGAL are you using? I had no problem opening it with our master branch.

**Comment by for-heart-peace** [comment]
4.14

**Comment by MaelRL** [comment]
Don't have any issue with 4.14 either. Please fill the information that you skipped in the original post (source code and environment).

**Comment by for-heart-peace** [comment]
windows10+vs2017


#include <iostream>
#include <algorithm>
#include <queue>
#include <set>
#include <fstream>
#include <list>
#include <CGAL/Simple_cartesian.h>
#include <CGAL/AABB_tree.h>
#include <CGAL/AABB_traits.h>
#include <CGAL/Polyhedron_3.h>
#include <CGAL/AABB_face_graph_triangle_primitive.h>
#include <CGAL/IO/Polyhedron_VRML_1_ostream.h>
#include <CGAL/IO/STL_reader.h>
#include <CGAL/IO/Polyhedron_builder_from_STL.h>

typedef CGAL::Simple_cartesian<double> K;
typedef K::Point_3 Point;

int main()
{
	vector<Point> points1;
        vector<vector<int>> facets1;
	std::ifstream input(filename);
	cout << CGAL::read_STL(input, points1, facets1,true) << endl;//read 
	input.close();
}



Error:
Parsing binary file...
header: COLOR= MATERIAL=  
29160 facets to read
Error while reading normal coordinates (premature end of file)
Parsing ASCII file...
Error while parsing ASCII file

**Comment by for-heart-peace** [comment]
windows10+vs2017

#include <iostream>
#include <algorithm>
#include <queue>
#include <set>
#include <fstream>
#include <list>
#include <CGAL/Simple_cartesian.h>
#include <CGAL/AABB_tree.h>
#include <CGAL/AABB_traits.h>
#include <CGAL/Polyhedron_3.h>
#include <CGAL/AABB_face_graph_triangle_primitive.h>
#include <CGAL/IO/Polyhedron_VRML_1_ostream.h>
#include <CGAL/IO/STL_reader.h>
#include <CGAL/IO/Polyhedron_builder_from_STL.h>

typedef CGAL::Simple_cartesian K;
typedef K::Point_3 Point;

int main()
{
vector points1;
vector<vector> facets1;
std::ifstream input(filename);
cout << CGAL::read_STL(input, points1, facets1,true) << endl;//read
input.close();
}

Error:
Parsing binary file...
header: COLOR=��� MATERIAL=��� ��� ���
29160 facets to read
Error while reading normal coordinates (premature end of file)
Parsing ASCII file...
Error while parsing ASCII file

**Comment by for-heart-peace** [comment]
I am sorry ,I do not know why some include can not show in github

**Comment by for-heart-peace** [comment]
I am so sorry and thank you for you help, I use std::ifstream input(filename); rather than std::ifstream input(filename,ios::binary);
sorry, sorry.
Best wishes!
