### ISSUE TITLE
Iterating over Polyhedron facets and planes returns random numbers

### ISSUE THREAD

**Issue by cebe** [CGAL/cgal#496]
Here is a script for reproducing the issue: https://gist.github.com/cebe/7c6323fe09a5cab3dc8d

compile it with

    g++ -o bug bug.cpp -lCGAL

Run it as `./bug > out.off` to get the mesh written as an OFF file to view it.

The essential part is this one:

```cpp
// create a mesh containing 2 triangles
Polyhedron mesh;
Point_3 p = Point_3(0, 0, 0);
Point_3 q = Point_3(1, 0, 0);
Point_3 r = Point_3(0, 1, 0);
mesh.make_triangle( p, q, r);
Point_3 t = Point_3(0, 0, 1);
Point_3 u = Point_3(1, 0, 1);
Point_3 v = Point_3(0, 1, 1);
mesh.make_triangle( t, u, v);

// iterate over all faces
for (  Facet_iterator f = mesh.facets_begin(); f != mesh.facets_end(); ++f) {

    // extract the plane in space form the facet
    Plane_3 plane = f->plane();
    std::cerr << "plane: " << plane.a() << "; " << plane.b() << "; " << plane.c() << "; " << plane.d() << std::endl;
}
```

The printed plane parameters are random float numbers and it looks like they come from unused memory or something:

```
mesh stats:
6 vertices
2 facets
plane: 2.0796e-317; 6.95274e-310; 6.95274e-310; 6.95274e-310
plane: 2.0796e-317; 6.95274e-310; 6.95274e-310; 6.95274e-310
```

Here is how the mesh looks like so the plane parameters should be quite easy to compute and not in the range I see them here.

![bildschirmfoto von 2015-11-21 17 31 23](https://cloud.githubusercontent.com/assets/189796/11319397/d7d80350-9075-11e5-99ec-b13be69290db.png)

I am using [version 4.5-2 that ships with debian jessie](https://packages.debian.org/jessie/libcgal10).

**Comment by cebe** [comment]
Btw, `plane.is_degenerate()` is not `true` even when I see these numbers...

**Comment by sloriot** [comment]
Planes are not automatically computed nor maintained.
See http://doc.cgal.org/latest/Convex_hull_3/Convex_hull_3_2quickhull_3_8cpp-example.html for example for how to set them.

**Comment by cebe** [comment]
thanks for the link. Consider this as a documentation issue then. Docs for `plane()` method on the facet should point out that they have to be calculated beforehand and link to that example.
