### ISSUE TITLE
How to get the order of node number of input file

### ISSUE THREAD

**Issue by badminton-imde** [CGAL/cgal#4971]
## Issue Details
Delaunay triangulation was used to triangulation. But the order of vertices is different from the input one.
For example, 
Input nodes: 
node 1 (1 2)
node 2 (2 3) 
node 3 (3 2)
node 4 (4 2)
The order of vertex:
vertex 1(2,3)
vertex 2(3,2)
vertex 3(1,2)
vertex 4(4,2)
1. How to get the original node number of vertex?
2. How to get the node number of element(not only the  coordinates)?

**Comment by mglisse** [comment]
https://doc.cgal.org/latest/Triangulation_3/index.html#title14 (Setting Information While Inserting a Range of Points) You can store that number in the vertex.

**Comment by badminton-imde** [comment]
> https://doc.cgal.org/latest/Triangulation_3/index.html#title14 (Setting Information While Inserting a Range of Points) You can store that number in the vertex.
Hi, mglisse. Thank you very much. Could you give me a simple example?

**Comment by sloriot** [comment]
Everything is included in the example provided by Marc. Note that input points are first put inside a vector ` std::vector< std::pair<Point,unsigned> > points` where the unsigned correspond to the id of the corresponding point. Then the pairs of points and id are inserted in the triangulation and you can access the id from a vertex `v` by using `v->info()`.
