### ISSUE TITLE
triangulate_refine_and_fair_hole function infinite loop

### ISSUE THREAD

**Issue by Diramorius** [CGAL/cgal#4977]
_Please use the following template to help us solving your issue._

## Issue Details

For a specific mesh configuration case, the algorithm went into an infinite loop. The off file is attached and the specific region that causes the problem is highlighted in the powerpoint slide. 

The problem area is a valid border loop, just that it forms into another loop from another portion of the mesh. 
The problem is in detecting such loops, which if i can detect this type of loop, i can delete it and the code will run just fine. 

## Source Code

Polygon_mesh_processing/hole_filling_example.cpp 

This is the source code that comes with the latest CGAL version 5.0.3

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): windows 10 64 bits
* Compiler: Visual Studio 14 2015
* Release or debug mode: Release
* Specific flags used (if any):
* CGAL version: 5.0.3
* Boost version: 1.68
* Other libraries versions if used (Eigen, TBB, etc.):

[issue.zip](https://github.com/CGAL/cgal/files/5173193/issue.zip)

**Comment by sloriot** [comment]
Without a main it is hard to know what you tried. Did you try to fill only the small holes or all boundary, including the very large one?

If you are trying to fill the very large hole, it might take time if the Delaunay version failed as the fallback is `O(n^3)`.

The corresponding polyhedron demo camera position for the highlighted location in the pptx is `23.2528 18.1159 19.7402 0.201861 -0.470626 0.34949 -0.784615`.

**Comment by lrineau** [comment]
I think @Diramorius indicated that the main was the file `examples/Polygon_mesh_processing/hole_filling_example.cpp` from CGAL-5.0.3.

**Comment by sloriot** [comment]
In such a case, I confirm that the Delaunay version is failing and that it uses the expensive fallback on a very large hole. I have it running in background we'll see if I get a result.

**Comment by Diramorius** [comment]
Hi @sloriot , thanks for the response. 

The issue I am trying to resolve is how to ensure that algorithm does not fallback on the expensive path. 
Is there a general rule of how the border should be in order for the algorithm to proceed normally? For example, minimum angle, etc? 

thanks!

**Comment by sloriot** [comment]
Sorry for the late reply. There is no way to ensure that. As the hole is pretty large, it would probably need another method.

**Comment by danston** [comment]
Should not be this one closed now?
