### ISSUE TITLE
Dangerous conversions in converters

### ISSUE THREAD

**Issue by MaelRL** [CGAL/cgal#4982]
## Issue Details

When using a converter, one can get surprising results when passing types that are not explicitly supported but have unintuitive conversions to other types:

For example, let's assume a `Cartesian_converter<Simple_cartesian<Core>, Epick>` called `conv`. Calling
`conv(2.5)` will return... `Epick::FT(1)`! This is because Core does not have an implicit construction from a double, so it converts the `double` to a `bool` and use the converter's `bool operator()(bool)` from the base `Enum_converter` and then constructs a `Epick::FT` from `true` (thus, `1`).

I first thought that I would simply disable everything not explicitly matching with
```c++
template <typename T>
T operator()(const T&) = delete;
```
but it breaks quite a bit of stuff: for example, the converters are required before type equality (e.g. `CGAL::Point_2<K>`/`K::Point_2`) is added in the kernels. If the proper operators were to be added, it should work and then be completely safe.

Another solution is to be a little softer, and just disable the `operator()` for fundamental types:
```c++
    template <typename T>
    T operator()(T,
                 typename std::enable_if<std::is_fundamental<T>::value>::type* = nullptr,
                 typename std::enable_if<!std::is_convertible<T, typename K1::FT>::value>::type* = nullptr)
    {
      CGAL_static_assertion_msg(!std::is_fundamental<T>::value,
                                "Kernel type converters should not be called on fundamental types");
    }
```
On paper there might be other weird conversions opened for non-fundamental types, but probably not in practice.

Any opinion, suggestion?

**Comment by lrineau** [comment]
It seems the solution with two `std::enable_if` is a good solution.

As for the first proposition, what are the "proper operators" that are needed?

**Comment by mglisse** [comment]
Another possibility (I am not claiming it is better or worse) would be to make the bool overload only accept exactly bool. C++20 concepts would make it easy, but even in older C++ one can make the type of the argument a template and sfinae if not is_same<T,bool>.

**Comment by lrineau** [comment]
Would the following patch fix the issue?
```patch
diff --git a/Number_types/include/CGAL/NT_converter.h b/Number_types/include/CGAL/NT_converter.h
index 1d7c4a8d639..ff58be55766 100644
--- a/Number_types/include/CGAL/NT_converter.h
+++ b/Number_types/include/CGAL/NT_converter.h
@@ -30,7 +30,7 @@ struct NT_converter
     NT2
     operator()(const NT1 &a) const
     {
-        return NT2(a);
+        return NT2{a};
     }
 };
 

```

As far as I understand, that should avoid narrowing conversions of `a` to any parameter type of the constructor of `NT2`.

**Comment by mglisse** [comment]
What if I **want** to convert from double to float, is that the wrong tool?

**Comment by lrineau** [comment]
> What if I **want** to convert from double to float, is that the wrong tool?

Might be. There should be a non-narrowing converter by default, and another one for users wanting to narrow their number types.

**Comment by MaelRL** [comment]
> Would the following patch fix the issue?

I would think not : the problem is that when it has to find which `operator()` of the converter is called, it will use `operator()(bool)` because `double` is implicitely convertible to `bool`, and it will not enter the `operator()(NT1)` that you modify at all, because `NT1(double)` is an explicit construction. The bad conversion is in the creation of NT1, and is completely independent from your choice of NT2.

> As for the first proposition, what are the "proper operators" that are needed?

Potentially just adding overloads of `K::Object` on top of `Object<K>` since converters are used before type equality shenanigans. It's a bit difficult to see ahead of time here; I think I will just have to try to implement it, and see what works or not.
