### ISSUE TITLE
CMake not creating a solution with projects for building shared libraries with CGAL 5.1

### ISSUE THREAD

**Issue by oracle3001** [CGAL/cgal#4985]
## Issue Details

For some reason, when I create the the VS solution using Cmake (v3.18) for CGAL 5.1, with shared libraries flag set to on (and header only off) and the "with_CGAL_CORE" etc flags on, the resultant VS solution doesn't contain the projects such as Core from which dlls are created. This is different behaviour to 5.0 (and below), where the solution with contain projects Cgal, Cgal_core, cgal_imageIO etc, from which the dll are built.

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows 10
* Compiler: VS2019
* Release or debug mode: Both
* Specific flags used (if any): With_CGAL_CORE, 
* CGAL version: 5.1
* Boost version: 1.74
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by lrineau** [comment]
CGAL is header-only since CGAL-5.0. If with CGAL-5.0 you produced DLLs, then that must be because you configured it that way, setting the CMake cache variable `CGAL_HEADER_ONLY` to `FALSE`. You can still do that with CGAL-5.1, but we plan to drop the non-header-only possibility in CGAL-5.2.

**Comment by oracle3001** [comment]
I am sorry, I have found my issue, I hadn't refreshed the project after changing the flag to turn off header only.

**Comment by lrineau** [comment]
@oracle3001 Notice that with CGAL-5.2 we plan to remove that non-only-header mode. Can you explain why you compile the DLLs of CGAL-5.0 or CGAL-5.1? There might be a use-case we do not see.
