### ISSUE TITLE
CGAL-5.1 precompiled demos do not work

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#4986]
I have tried https://www.cgal.org/demo/5.1/polyhedron_3.zip with https://www.cgal.org/demo/5.1/CGAL-demoDLLs.zip with `wine` on my Linux machine, and it does not work:

```
0024:err:module:import_dll Library Qt5WebSockets.dll (which is needed by L"Z:\\home\\lrineau\\CGAL\\Releases\\tmp\\demo_framework.dll") not found
0024:err:module:import_dll Library demo_framework.dll (which is needed by L"Z:\\home\\lrineau\\CGAL\\Releases\\tmp\\polyhedron_demo.dll") not found
0024:err:module:import_dll Library polyhedron_demo.dll (which is needed by L"Z:\\home\\lrineau\\CGAL\\Releases\\tmp\\Polyhedron_3.exe") not found
0024:err:module:LdrInitializeThunk Importing dlls for L"Z:\\home\\lrineau\\CGAL\\Releases\\tmp\\Polyhedron_3.exe" failed, status c0000135
```

It seems `Qt5WebSockets.dll` is now a requirement for `demo_framework.dll`. It should be added to `CGAL-demoDLLs.zip`.

**Comment by maxGimeno** [comment]
Mmmh I guess the Qt5WebSocket is found during compile time, but indeed it
is not added to the list of dlls in the zip.

Le mar. 8 sept. 2020 à 18:20, Laurent Rineau <notifications@github.com> a
écrit :

**Comment by lrineau** [comment]
@maxGimeno Do you have access to gauguin, so that we can fix that quickly?

**Comment by maxGimeno** [comment]
Not from home, no

**Comment by lrineau** [comment]
I have a ssh access to it. I am working now on the issue...

**Comment by lrineau** [comment]
I think I have fixed the issue. At list it works now with the Wine emulation on my Linux machine.
 https://github.com/CGAL/cgal-web/commit/2412fe370ace3606a00639665534afbd4f473ff5

**Comment by maxGimeno** [comment]
I think it was simply adding the Qt5WebSocket dll to the zip and upload the new zip

**Comment by lrineau** [comment]
Actually `Qt5Network.dll` was required as well, as a dependency of `Qt5WebSocket.dll`. I have updated the zip file.

**Comment by afabri** [comment]
Maybe you should add to the release-checklist that this gets tested during the beta.
