### ISSUE TITLE
Scale-Space Surface Reconstruction memory leak

### ISSUE THREAD

**Issue by Tigertron** [CGAL/cgal#4988]
Scale_space_surface_reconstruction_3 with Alpha_shape_mesher has a huge memory leak on reconstruct function. More than that it has no methods or destructor for clear memory manualy. By Valgrind I see, that the most problem in Alpha_shape_mesher.h
```
Shape* _shape;
```
or, may be deeper in Triangulation_3.
This is especially critical for big Points Sets, because after reconstruction we didn't have memory for operate with the result and cannot clear it.

## Source Code

```
typedef CGAL::Exact_predicates_inexact_constructions_kernel  kernel;
typedef kernel::Point_3                                      Point3D;
typedef CGAL::Scale_space_surface_reconstruction_3<kernel>   SurfaceReconstruction;

void surface_reconstruction(std::vector<Point3D> &points, std::vector<Triangle_Indexes> &out_triangles)
{
	SurfaceReconstruction reconstructedMesh(points.begin(), points.end());
	reconstructedMesh.increase_scale (1, CGAL::Scale_space_reconstruction_3::Jet_smoother<kernel, CGAL::Parallel_tag>());
	reconstructedMesh.reconstruct_surface (SurfaceReconstruction::Alpha_shape_mesher(2.0));  
	
	/* this is not influence on memory leak
	for(auto fit = reconstructedMesh.facets_begin(); fit != reconstructedMesh.facets_end(); ++fit)
	{
		out_triangles.push_back(Triangle_Indexes(fit->at(0), fit->at(1), fit->at(2)));
	}  */
}
```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Ubuntu 18.04
* Compiler: gcc 7.5
* Release or debug mode: both Release and debug
* Specific flags used (if any): -frounding-math
* CGAL version: 5.03 and 5.1
* Boost version: 1.65.1
* Other libraries versions if used (Eigen, TBB, etc.): Eigen 3. TBB

**Comment by afabri** [comment]
Thank you for your bug report.  
Just looking at the code I think that adding a destructor  `~Alpha_shape_mesher(){  clear_surface();}` should fix the problem as   [`clear_surface()`](https://github.com/CGAL/cgal/blob/master/Scale_space_reconstruction_3/include/CGAL/Scale_space_reconstruction_3/Alpha_shape_mesher.h#L332)  deletes the `shape`. 
We will have a closer look.

**Comment by danston** [comment]
Hi @Tigertron, I am working on the patch for this issue. I will let you know when it is finished so that you could test this patch on your data.

**Comment by danston** [comment]
I have created the PR that addresses this bug. Please let me know if you encounter any other issues.
