### ISSUE TITLE
Add a testsuite which uses the AdressSanitizer

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#4991]
## Issue Details

Although we cannot add the address sanitizer in the complete testsuite, we should do it one day a week, or for one platform, or for selected tests.  It could also be a VC testsuite (see [blog entry](https://devblogs.microsoft.com/cppblog/addresssanitizer-asan-for-windows-with-msvc/))  .

**Comment by sloriot** [comment]
20 | Fedora-Release | bonnard (GF) | 158 | 40 | 75 | 6 | 4 | 3.22.2 | 1.76.0 | 4.1.0 | 6.2.1 | 5.15.5 | - | -Wall -frounding-math -msse3 -fsanitize=address -msse3 -O3 -DCGAL_NDEBUG -fsanitize=address
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
