### ISSUE TITLE
no type named Point_3 in CGAL::Epick

### ISSUE THREAD

**Issue by rockydut** [CGAL/cgal#4997]
_Please use the following template to help us solving your issue._

## Issue Details

when I compile the example in "3D Mesh Generation" by mingw in qtcreator, it shows the no type named errors;
"typedef K::FT FT" shows "no type named 'FT' in 'CGAL::Epick'
"typedef K::Point_3 Point" shows "no type named 'Point_3' in 'CGAL::Epick'"
and K::Sphere_3(CGAL::ORIGIN, 2.) shows "no member named Sphere_3" in 'CGAL::Epick'"
The source code copy from the example from user manual.

## Source Code

#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/Mesh_triangulation_3.h>
#include <CGAL/Mesh_complex_3_in_triangulation_3.h>
#include <CGAL/Mesh_criteria_3.h>
#include <CGAL/Labeled_mesh_domain_3.h>
#include <CGAL/make_mesh_3.h>
// Domain
typedef CGAL::Exact_predicates_inexact_constructions_kernel K;
typedef K::FT FT;
typedef K::Point_3 Point;
typedef FT (Function)(const Point&);
typedef CGAL::Labeled_mesh_domain_3<K> Mesh_domain;
#ifdef CGAL_CONCURRENT_MESH_3
typedef CGAL::Parallel_tag Concurrency_tag;
#else
typedef CGAL::Sequential_tag Concurrency_tag;
#endif
// Triangulation
typedef CGAL::Mesh_triangulation_3<Mesh_domain,CGAL::Default,Concurrency_tag>::type Tr;
typedef CGAL::Mesh_complex_3_in_triangulation_3<Tr> C3t3;
// Criteria
typedef CGAL::Mesh_criteria_3<Tr> Mesh_criteria;
// To avoid verbose function and named parameters call
using namespace CGAL::parameters;
// Function
FT sphere_function (const Point& p)
{ return CGAL::squared_distance(p, Point(CGAL::ORIGIN))-1; }
int main()
{
  Mesh_domain domain =
    Mesh_domain::create_implicit_mesh_domain(sphere_function,
                                             K::Sphere_3(CGAL::ORIGIN, 2.));
  // Mesh criteria
  Mesh_criteria criteria(facet_angle=30, facet_size=0.1, facet_distance=0.025,
                         cell_radius_edge_ratio=2, cell_size=0.1);
  // Mesh generation
  C3t3 c3t3 = CGAL::make_mesh_3<C3t3>(domain, criteria);
  // Output
  std::ofstream medit_file("out.mesh");
  c3t3.output_to_medit(medit_file);
  return 0;
}

## Environment

* Operating system Window:
* Compiler: gcc newest version
* Release or debug mode:
* Specific flags used (if any):
* CGAL version: 5.0.2
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):
The qt creator setting:
TEMPLATE = app
CONFIG += console c++14
CONFIG -= app_bundle
CONFIG -= qt

LIBS += -lmpfr -lgmp

SOURCES += \
        main.cpp

**Comment by lrineau** [comment]
That is really strange. What were the compilation flags? Maybe you should post the full error log. You can post big files on https://gist.github.com/ and then post the link here.

**Comment by rockydut** [comment]
The complete errors show blow:

F:\Packages\cgal\CGALtest\main.cpp:64: error: no type named 'FT' in 'CGAL::Epick'
F:\Packages\cgal\CGALtest\main.cpp:65: error: no type named 'Point_3' in 'CGAL::Epick'
F:\Packages\cgal\CGALtest\main.cpp:82: error: cannot convert 'const CGAL::Origin' to 'Point' (aka 'int') without a conversion operator
F:\Packages\cgal\CGALtest\main.cpp:87: error: no member named 'Sphere_3' in 'CGAL::Epick'

By the way, the compiler is mingw64 in windows. And use the qtcreator for the IDE.

**Comment by lrineau** [comment]
That is not the full error log. Please post the log with the compilation command lines.

**Comment by lrineau** [comment]
In qtcreator, it should be in the windows `Compile Output` Please post its full content.

**Comment by rockydut** [comment]
Following is the detail compile information in qtcreator.

21:21:32: Running steps for project cgaltest...
21:21:32: Configuration unchanged, skipping qmake step.
21:21:32: Starting: "D:\Msys2\mingw64\bin\mingw32-make.exe" -j8
D:/Msys2/mingw64/bin/mingw32-make.exe -f Makefile.Debug
mingw32-make[1]: Entering directory 'G:/test/cgaltest/x64'
g++ -c -fno-keep-inline-dllexport -g -std=gnu++1y -Wall -Wextra -Wextra -fexceptions -mthreads -DUNICODE -D_UNICODE -DWIN32 -DMINGW_HAS_SECURE_API=1 -DQT_QML_DEBUG -I../../cgaltest -I. -IF:/Packages/cgal/libcgal/include -ID:/Msys2/mingw64/share/qt5/mkspecs/win32-g++  -o debug/main.o ../main.cpp
In file included from D:/Msys2/mingw64/include/boost/math/tools/cxx03_warn.hpp:9,
                 from D:/Msys2/mingw64/include/boost/math/constants/constants.hpp:11,
                 from D:/Msys2/mingw64/include/boost/math/special_functions/asinh.hpp:25,
                 from D:/Msys2/mingw64/include/boost/multiprecision/gmp.hpp:21,
                 from F:/Packages/cgal/libcgal/include/CGAL/boost_mp.h:43,
                 from F:/Packages/cgal/libcgal/include/CGAL/internal/Exact_type_selector.h:27,
                 from F:/Packages/cgal/libcgal/include/CGAL/Exact_kernel_selector.h:26,
                 from F:/Packages/cgal/libcgal/include/CGAL/Filtered_kernel.h:22,
                 from F:/Packages/cgal/libcgal/include/CGAL/Exact_predicates_inexact_constructions_kernel.h:21,
                 from ../main.cpp:1:
D:/Msys2/mingw64/include/boost/bind.hpp:36:1: note: '#pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.'
   36 | BOOST_PRAGMA_MESSAGE(
      | ^~~~~~~~~~~~~~~~~~~~
../main.cpp:12:9: error: invalid use of template-name 'CGAL::Labeled_mesh_domain_3' without an argument list
   12 | typedef CGAL::Labeled_mesh_domain_3 Mesh_domain;
      |         ^~~~
../main.cpp:12:9: note: class template argument deduction is only available with '-std=c++17' or '-std=gnu++17'
In file included from ../main.cpp:5:
F:/Packages/cgal/libcgal/include/CGAL/Labeled_mesh_domain_3.h:257:7: note: 'template<class BGT, class Subdomain_index_, class Surface_patch_index_> class CGAL::Labeled_mesh_domain_3' declared here
  257 | class Labeled_mesh_domain_3 :
      |       ^~~~~~~~~~~~~~~~~~~~~
../main.cpp:19:36: error: 'Mesh_domain' was not declared in this scope
   19 | typedef CGAL::Mesh_triangulation_3<Mesh_domain,CGAL::Default,Concurrency_tag>::type Tr;
      |                                    ^~~~~~~~~~~
../main.cpp:19:77: error: template argument 1 is invalid
   19 | typedef CGAL::Mesh_triangulation_3<Mesh_domain,CGAL::Default,Concurrency_tag>::type Tr;
      |                                                                             ^
../main.cpp:19:85: error: expected initializer before 'Tr'
   19 | typedef CGAL::Mesh_triangulation_3<Mesh_domain,CGAL::Default,Concurrency_tag>::type Tr;
      |                                                                                     ^~
../main.cpp:20:9: error: invalid use of template-name 'CGAL::Mesh_complex_3_in_triangulation_3' without an argument list
   20 | typedef CGAL::Mesh_complex_3_in_triangulation_3 C3t3;
      |         ^~~~
../main.cpp:20:9: note: class template argument deduction is only available with '-std=c++17' or '-std=gnu++17'
In file included from F:/Packages/cgal/libcgal/include/CGAL/Mesh_complex_3_in_triangulation_3.h:23,
                 from ../main.cpp:3:
F:/Packages/cgal/libcgal/include/CGAL/Mesh_3/Mesh_complex_3_in_triangulation_3_fwd.h:23:7: note: 'template<class Tr, class CornerIndex, class CurveIndex> class CGAL::Mesh_complex_3_in_triangulation_3' declared here
   23 | class Mesh_complex_3_in_triangulation_3;
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../main.cpp:22:9: error: invalid use of template-name 'CGAL::Mesh_criteria_3' without an argument list
   22 | typedef CGAL::Mesh_criteria_3 Mesh_criteria;
      |         ^~~~
../main.cpp:22:9: note: class template argument deduction is only available with '-std=c++17' or '-std=gnu++17'
In file included from ../main.cpp:4:
F:/Packages/cgal/libcgal/include/CGAL/Mesh_criteria_3.h:159:7: note: 'template<class Tr, class EdgeCriteria, class FacetCriteria, class CellCriteria> class CGAL::Mesh_criteria_3' declared here
  159 | class Mesh_criteria_3
      |       ^~~~~~~~~~~~~~~
../main.cpp: In function 'int main()':
../main.cpp:30:1: error: 'Mesh_domain' was not declared in this scope
   30 | Mesh_domain domain =
      | ^~~~~~~~~~~
../main.cpp:34:1: error: 'Mesh_criteria' was not declared in this scope
   34 | Mesh_criteria criteria(facet_angle=30, facet_size=0.1, facet_distance=0.025,
      | ^~~~~~~~~~~~~
../main.cpp:37:1: error: 'C3t3' was not declared in this scope
   37 | C3t3 c3t3 = CGAL::make_mesh_3(domain, criteria);
      | ^~~~
../main.cpp:40:1: error: 'c3t3' was not declared in this scope; did you mean 'CGAL::parameters::tag::c3t3'?
   40 | c3t3.output_to_medit(medit_file);
      | ^~~~
      | CGAL::parameters::tag::c3t3
In file included from F:/Packages/cgal/libcgal/include/CGAL/boost/parameter.h:26,
                 from F:/Packages/cgal/libcgal/include/CGAL/Mesh_criteria_3.h:28,
                 from ../main.cpp:4:
F:/Packages/cgal/libcgal/include/CGAL/boost/parameter.h:76:23: note: 'CGAL::parameters::tag::c3t3' declared here
   76 | BOOST_PARAMETER_NAME( c3t3 )
      |                       ^~~~
mingw32-make[1]: *** [Makefile.Debug:582: debug/main.o] Error 1
mingw32-make[1]: Leaving directory 'G:/test/cgaltest/x64'
mingw32-make: *** [Makefile:45: debug] Error 2
21:21:52: The process "D:\Msys2\mingw64\bin\mingw32-make.exe" exited with code 2.
Error while building/deploying project cgaltest (kit: Desktop Qt  MinGW-w64 64bit (MSYS2))
When executing step "Make"
21:21:52: Elapsed time: 00:20.

**Comment by lrineau** [comment]
Now it seems your compilation errors are different from what you first reported. Your .cpp program is wrong, because of a bad copy-paste. Line 12:
```c++
typedef CGAL::Labeled_mesh_domain_3 Mesh_domain;
```
It should be:
```c++
typedef CGAL::Labeled_mesh_domain_3<K> Mesh_domain;
```
