### ISSUE TITLE
Wrong classification of point on plane

### ISSUE THREAD

**Issue by thomasp85** [CGAL/cgal#4999]
## Issue Details

I'm building a BSP tree and I'm having issues with how points are classified according to the plane. The input data is a mesh structure where shared vertices are encoded once, so that the same underlying data is used for adjacent triangles. Now, when build my BSP Tree I observe that triangles are getting cut by planes defined by neighbouring triangles, something that should not be possible since two of the points lie (or should lie) on the supporting plane of the adjacent triangle (after all, they are used in defining the plane). Is this behaviour somehow expected or possible when using the exact_predicates_exact_construction_kernel? If so, what kind of measure can be taken to prevent it?

## Source Code

My first question is mostly theoretical (can this happen). If it shouldn't happen and it thus indicates a bug in either my own or CGAL's code I'll work towards creating a minimal example.

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): 
* Compiler:
* Release or debug mode:
* Specific flags used (if any):
* CGAL version:
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by sloriot** [comment]
If I get you right, you have a triangle mesh and you define the supporting planes of triangle faces using EPECK. Then you observe that the supporting plane of a triangle might intersect a neighbor triangle in the mesh in its interior. If this is what you have, then yes it should not happen.

**Comment by thomasp85** [comment]
Yes - that is correctly observed. OK, I'll work on creating a minimal example for debugging. My full BSP tree is obviously not that minimal🙂

**Comment by sloriot** [comment]
I guess you already check that you don't have coplanar adjacent faces?

PS: Are you aware of the CGAL [AABB-tree package](https://doc.cgal.org/latest/AABB_tree/)?

**Comment by thomasp85** [comment]
If they are coplanar I should detect it and simply lump the triangles together in the same BSP node.

I looked at the AABB tree but I really need a face-aligned structure for what I'm doing so I decided to attempt to roll my own

**Comment by thomasp85** [comment]
OK, so I had mischaracterised the problem a bit. The issue seems to be nearly-adjacent triangles with a mesh made of triangulated quads. In the image below of a sphere the supporting plane of the blue(ish) triangle intersects with the red one.

![image](https://user-images.githubusercontent.com/1775316/93379172-c476fa00-f85d-11ea-8684-7722a642b725.png)

I've manually run through the numbers and it appears that rounding errors means that the original quad is not actually occupying a plane, so CGAL is doing nothing wrong.

Is there any good strategy for working with meshes where prior rounding may have introduced such discrepancies in the data?

**Comment by sloriot** [comment]
Hard to tell without having more details, I guess it depends on what you are trying to achieve.

**Comment by thomasp85** [comment]
yeah - I can't see how this can be achieved myself. For this particular shape (a sphere), we know that it should be concave and that triangles that triangles sharing their longest edge should be on the same plane, but that is not true for all shapes so there's probably no way to clean up shapes consistently... anyway, that's a "me" problem — thanks for taking your time 🙂
