### ISSUE TITLE
Sqrt_extension(double)

### ISSUE THREAD

**Issue by mglisse** [CGAL/cgal#50]
`Sqrt_extension<NT,...>` has implicit constructors taking `int` or NT. When NT is not a builtin type, trying to implicitly construct `Sqrt_extension` from `double` picks the `int` constructor. `-Wconversion` gives a warning with gcc/clang, Visual Studio seems to warn as well.

**Comment by sloriot** [comment]
Due to some internal usage in the arrangement package the constructor from `int` cannot be made `explicit`. I documented the constructor from any `NTX` in #505. Specifying the template parameter should enable to remove the warning.
