### ISSUE TITLE
Reading medit files

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#5005]
In the demo (and I think also in the function `read_MEDIT()`), an infinite cell is created for each face on the boundary of the domain. If there are some non-manifold edges on the boundary of the domain, then the demo fails to load the file (a facet will be shared by more than 2 cells).

Are we planning to support all possible cases or shall we be restrictive? For the latter case, an error message/code might be interesting for the user.

I don't know if non-manifold edges are the only issues we could have, maybe cavities, several connected components, non-manifold vertices could also be problematic (or not).

**Comment by janetournois** [comment]
You are right about non-manifold edges. 

Note that the function called internally that builds the triangulation from a tet soup is also used inside tetrahedral remeshing, and I met the same issue.

My opinion is that we should make this code more generic, and it is linked to the more general issue of having a non-convex triangulation.

About the cases you list, here is how they behave in the current code :
- cavities are considered as being on the hull, i.e. connected to the infinite vertex. If there is no non-manifold edges, it should not be an issue.
- several connected components : all "surface" facets are connected to the infinite vertex. It should be fine too.
- non-manifold vertices : connectivity is built based on pairs of equivalent facets (same facets, without checking orientation) so non manifold vertices should not be an issue either.

There may be other problematic cases though.

**Comment by MaelRL** [comment]
Non-manifoldness support was added with https://github.com/CGAL/cgal/pull/5693.
