### ISSUE TITLE
Arrangement of segments complexity issue

### ISSUE THREAD

**Issue by gdamiand** [CGAL/cgal#5015]
_Please use the following template to help us solving your issue._

## Issue Details

Computing arrangement of segments could be very long; there is probably some strange code implying an huge complexity overhead.

## Source Code

I load the set of segment (txt files given here) in a vector of segments
[FRA_adm3.txt](https://github.com/CGAL/cgal/files/5269893/FRA_adm3.txt)
[FRA_adm3.txt-noise-0.001000.txt](https://github.com/CGAL/cgal/files/5269894/FRA_adm3.txt-noise-0.001000.txt)

And I compute the arrangement using the CGAL::insert method.

typedef CGAL::Exact_predicates_exact_constructions_kernel EPECK;
typedef EPECK                     MyKernel;
typedef CGAL::Arr_segment_traits_2<EPECK> Traits_2;
typedef CGAL::Arrangement_2<Traits_2>  Arrangement_2;
typedef MyKernel::Segment_2       TSegment;
std::vector<TSegment> all_segments;
Arrangement_2 arr;
CGAL::insert(arr, all_segments.begin(), all_segments.end());
 
For the first file, computation time is very long: 75.628 seconds.
The second file is obtained from the first one, adding a very low noise to each point. Computation time is now very fast: 2.27472 seconds.

This huge difference is suspect.

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Linux
* Compiler: g++ 9.3.0
* Release or debug mode: Release
* Specific flags used (if any):
* CGAL version: master (but same behaviour with previous releases)
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by sloriot** [comment]
Thanks for the report @sgiraudot will have a look when he's back. Maybe it is already fixed in his PRs.

**Comment by sgiraudot** [comment]
I can confirm that https://github.com/CGAL/cgal/pull/4875 solves the issue. I can reproduce the problem, the computation takes 63s on my computer using `master`, and 2.6s using https://github.com/CGAL/cgal/pull/4875.

**Comment by gdamiand** [comment]
> I can confirm that #4875 solves the issue. I can reproduce the problem, the computation takes 63s on my computer using `master`, and 2.6s using #4875.

Very good news; thanks @sgiraudot !

**Comment by lrineau** [comment]
This issue will only be fixed once #5166 is merged.

**Comment by gdamiand** [comment]
Remember there exists a parallel version of arrangement of segments if someone need a very fast method ;) (for now outside cgal code)
