### ISSUE TITLE
CGAL_CFG_MATCHING_BUG is not needed by MSVC >= 2015

### ISSUE THREAD

**Issue by janetournois** [CGAL/cgal#5021]
## Issue Details

I commented all the `#define` of `Installation\include\CGAL\MSVC_compiler_config.h` and compiled the tests and examples of Mesh_3. It turns out that the macros defined to avoid the "matching bug" are not needed anymore with MSVC 2019 (version 16).
I tried a few examples with the compilers of MSVC 2015, 2017 and 2019 and they behave similarly (no error).

Should we start thinking of removing them?

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows
* Compiler: MSVC >= 2015
* Release or debug mode: both
* CGAL version:  releases/CGAL-5.0-branch

**Comment by sloriot** [comment]
If this is something tested in the testsuite then go for it :)
