### ISSUE TITLE
meaning of cell_size in 2D mesh generation

### ISSUE THREAD

**Issue by nschloe** [CGAL/cgal#5061]
Given a target edge size, I would like to create a mesh of the unit disk with CGAL's 2D mesh generator. I create a regular polygon with the appropriate number of faces and set cell size to the corresponding area of the cell. I set the max ratio of the cell circumradius to edge size to something large to not be constrained by that.  This, still, gives much over-refined mesh. Perhaps `cell_size` is not the area of the triangle?
```python
import numpy
import pygalmesh


def disk(h):
    n = int(2 * numpy.pi / h)
    points = numpy.array(
        [
            [numpy.cos(alpha), numpy.sin(alpha)]
            for alpha in numpy.linspace(0.0, 2 * numpy.pi, n + 1, endpoint=False)
        ]
    )
    constraints = [[k, k + 1] for k in range(n)] + [[n, 0]]
    cell_size = numpy.sqrt(3) / 4 * h ** 2
    # cell_size = h  # ?
    mesh = pygalmesh.generate_2d(
        points,
        constraints,
        B=100000,
        cell_size=cell_size,
        num_lloyd_steps=0
    )
    mesh.write("cgal2d.vtk")
    return mesh.points, mesh.get_cells_type("triangle")


if __name__ == "__main__":
    disk(0.1)
```
![disk](https://user-images.githubusercontent.com/181628/95439001-52bf3700-0957-11eb-8ada-fa1bfe5ebb89.png)

**Comment by janetournois** [comment]
Hi @nschloe,
the "default" size criterion for a triangle in the 2D mesh generator refers to its edges lengths. In the output mesh, all segments of all triangles must be shorter than the given bound.

**Comment by nschloe** [comment]
Ah. In 3D, you have `edge_size`, `cell_size`, and `facet_size`, and they all mean something different. When encountering `cell_size` in 2D, one would expect it to be equivalent to `cell_size` in 3D, but if it really is `edge_size`, perhaps the variable should be renamed?

**Comment by lrineau** [comment]
>  When encountering `cell_size` in 2D, one would expect it to be equivalent to `cell_size` in 3D, but if it really is `edge_size`, perhaps the variable should be renamed?

There is no mention of `cell_size` in the 2D Mesh Generation package. You invented it in your Python API. We cannot be responsible for that confusion. :smile: 

> [The documentation](https://doc.cgal.org/latest/Mesh_2/classCGAL_1_1Delaunay__mesh__size__criteria__2.html#a58b0186eae407ba76b8f4a3d0aa85a1a) correctly says:
> 
> > all segments of all triangles must be shorter than a bound S.

What is not clear? Please propose a new wording. Maybe we call `S` a "length", instead of a "bound"?

**Comment by nschloe** [comment]
> There is no mention of cell_size in the 2D Mesh Generation package. You invented it in your Python API. We cannot be responsible for that confusion. :smile: 

Oh geez, you're right! I must have gotten it mixed up with some other package (probably my own). All good now.
