### ISSUE TITLE
2D mesh generation produces degenerate cells

### ISSUE THREAD

**Issue by nschloe** [CGAL/cgal#5068]
Simple example of a mesh of the unit disk:
```python
import numpy
import pygalmesh
import meshplex

h = 0.1
n = int(2 * numpy.pi / h)
points = numpy.array(
    [
        [numpy.cos(alpha), numpy.sin(alpha)]
        for alpha in numpy.linspace(0.0, 2 * numpy.pi, n + 1, endpoint=False)
    ]
)
constraints = [[k, k + 1] for k in range(n)] + [[n, 0]]
mesh = pygalmesh.generate_2d(
    points,
    constraints,
    edge_size=h,
    num_lloyd_steps=0
)

mesh = meshplex.MeshTri(mesh.points, mesh.get_cells_type("triangle"))
print(numpy.sum(mesh.cell_volumes < 1.0e-13))
```
```python
7  # cells with volume 0
```

**Comment by lrineau** [comment]
Hi @nschloe. That is very difficult for use to understand what is the issue, with such a bug report. We are not Python developers, and we do not use, or know, the API of `pygalmesh`.

Can you please explain, either in C++, or in words, what is the issue?

**Comment by nschloe** [comment]
> Hi @nschloe. That is very difficult for use to understand what is the issue, with such a bug report. We are not Python developers, and we do not use, or know, the API of pygalmesh.

Sure thing, but creating a C++ MWE is too time-consuming for me. I though with such an easy example, you'd be able to reproduce it from one of your C++ example files.

> Can you please explain, either in C++, or in words, what is the issue?

Yes. I'm trying to create a mesh of the unit disk with CGAL's 2D mesh generator. To this end, I create appropriate constraints on the unit circle and generate the mesh. Unfortunately, the mesh often contains degenerate cells (cells of volume 0). In the above case (max edge length 0.1), there are 7 degenerate cells.

**Comment by lrineau** [comment]
I had a look at the code pygalmesh: https://github.com/nschloe/pygalmesh/blob/d8bf3b5405e6cb3a75619f24342e4994a1b70ee4/src/generate_2d.cpp#L24-L88

If you look at lines L78-L85, we see that you export all the triangles of the triangulation, even those for which `fit->is_in_domain()` is `false`. That is the bug. I am surprised that the bug can occur with a domain that is convex (like a disk), but certainly that code L78-L85 is wrong. It should be (I type code without testing):
```c++
  auto nb_faces = 0u;
  for(auto fit: finite_face_handles()) {
    if(fit->is_in_domain()) ++nb_faces;
  }
  std::vector<std::array<int, 3>> out_cells(nb_faces);
  k = 0;
  for (auto fit: finite_face_handles()) {
    if(!fit->is_in_domain()) continue;
    out_cells[k][0] = vertex_index[fit->vertex(0)];
    out_cells[k][1] = vertex_index[fit->vertex(1)];
    out_cells[k][2] = vertex_index[fit->vertex(2)];
    k++;
  }
```

I hope that C++ code makes sense for you, and fixes the issue.

**Comment by nschloe** [comment]
Thaks @lrineau for taking the time and looking into it. Your suggestion indeed fixes the issue. I can safely say I would _never_ have thought of that. Thanks very much again.
