### ISSUE TITLE
boost::variant causes maybe-unitialized compiler warnings with gcc in c++14 mode with O3

### ISSUE THREAD

**Issue by theartful** [CGAL/cgal#5086]
## Issue Details

I tracked the compiler warnings with the demo, and I simplified it until I got this:
```C++
#include <vector>
#include <boost/variant.hpp>
#include <stdlib.h>

struct Y
{
  Y() {}
  Y(const Y &) {}
};

class Z {
public:
  Z() : a{}, b{}, c(false), d(false), e(false) {}

protected:
  Y a;
  Y b;
  bool c;
  bool d;
  bool e;
};

int main() {
  std::vector<boost::variant<int, Z>> vec;
  auto oi = std::back_inserter(vec);
  *oi++ = boost::variant<int, Z>(rand());
}
```
Compiling this with almost any gcc version and any boost version raises  the warning
```
In constructor ‘Z::Z(Z&&)’,
    inlined from ‘typename Visitor::result_type boost::detail::variant::visitation_impl(int, int, Visitor&, VoidPtrCV, mpl_::false_, NoBackupFlag, Which*, step0*) [with Which = mpl_::int_<0>; step0 = boost::detail::variant::visitation_impl_step<boost::mpl::l_iter<boost::mpl::l_item<mpl_::long_<2>, int, boost::mpl::l_item<mpl_::long_<1>, Z, boost::mpl::l_end> > >, boost::mpl::l_iter<boost::mpl::l_end> >; Visitor = boost::detail::variant::move_into; VoidPtrCV = void*; NoBackupFlag = boost::variant<int, Z>::has_fallback_type_]’ at /usr/include/boost/variant/variant.hpp:495:9,
    inlined from ‘typename Visitor::result_type boost::variant<T0, TN>::internal_apply_visitor(Visitor&) [with Visitor = boost::detail::variant::move_into; T0_ = int; TN = {Z}]’ at /usr/include/boost/variant/variant.hpp:2334:48,
    inlined from ‘boost::variant<T0, TN>::variant(boost::variant<T0, TN>&&) [with T0_ = int; TN = {Z}]’ at /usr/include/boost/variant/variant.hpp:1771:39,
    inlined from ‘void std::vector<_Tp, _Alloc>::emplace_back(_Args&& ...) [with _Args = {boost::variant<int, Z>}; _Tp = boost::variant<int, Z>; _Alloc = std::allocator<boost::variant<int, Z> >]’ at /usr/gcc-trunk/include/c++/11/ext/new_allocator.h:156:4,
    inlined from ‘int main()’ at /usr/gcc-trunk/include/c++/11/bits/stl_vector.h:1204:21:
overlay.cpp:11:7: warning: ‘*((void*)(&<anonymous>)+4).Z::e’ may be used uninitialized [-Wmaybe-uninitialized]
   11 | class Z {
      |       ^
overlay.cpp: In function ‘int main()’:
overlay.cpp:26:40: note: ‘<anonymous>’ declared here
   26 |   *oi++ = boost::variant<int, Z>(rand());
      |                                        ^
```
This is essentially the same what happens here:
https://github.com/CGAL/cgal/blob/b4a536047d098d586a89982146fd094dd97b41aa/Arrangement_on_surface_2/include/CGAL/Arr_curve_data_traits_2.h#L234-L237
where all the warnings originate.
Editing it to use the copy constructor removes the warnings
```C++
 Intersection_result ip = *boost::get<Intersection_point>(&item); 
 *oi++ = ip; 
```
but it seems to me as a brittle solution, as this pattern is used in many other locations, and I see no reason it wouldn't raise the warning except for the optimizer optimized it differently + this is slightly more inefficient.

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Linux 64/32 bit
* Compiler: gcc 10, 11
* Specific flags used (if any): -O3, -Wall -std=gnu++14
* Boost version: 1.69, 1.70, 1.71, 1.72, 1.73, 1.74

**Comment by theartful** [comment]
The warnings can be reproduced by running `overlay.cpp` example using `Arrangement_with_history_2` instead of `Arrangement_2` https://github.com/CGAL/cgal/blob/master/Arrangement_on_surface_2/examples/Arrangement_on_surface_2/overlay.cpp

**Comment by Vishal19111999** [comment]
Ran the simplified code that you reached to, in my machine
Does not give any warning
Here's a screenshot
![Screenshot from 2020-10-20 02-13-08](https://user-images.githubusercontent.com/29145212/96509651-fa066d00-1279-11eb-9e21-af025da7bc36.png)

<b>OS</b> - Ubuntu 20.04 (Pop_OS!)
<b>Boost version</b> - 1.71
<b>Compiler</b>- gcc 9

(Correct me if I am doing a mistake, I'm just a beginner)

**Comment by theartful** [comment]
@Vishal19111999  You're doing nothing wrong, this is a mistake on my part this example generates warnings with "gcc 10" and "gcc 11", my mistake on the report (warnings happen in test suite in gcc 10).
https://godbolt.org/z/8n711f

**Comment by lrineau** [comment]
That is a long-standing bug of gcc, that dates from gcc-6, actually: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=80635

That bug has been discussed a lot by gcc experts. I do not know what we can do from winthin CGAL.

**Comment by theartful** [comment]
I see, thanks for clearing this up. I will close this issue then.
