### ISSUE TITLE
How to remove linear degenerated face.

### ISSUE THREAD

**Issue by bianyunzhi95** [CGAL/cgal#5121]
I have got a question regarding polygon mesh processing.

![image](https://user-images.githubusercontent.com/42105279/97224824-a90fef00-180c-11eb-9b1d-54d027734019.png)

I am trying to make not self-intersecting mesh from this kind of topology. Here, [124, 236], [145,236], [465,236] pairs are intersecting. Sometimes, [246,246] pair is considered to be self-intersecting too.

What can I do to remove this kind of oddness of mesh using CGAL?
Thank you.

**Comment by MaelRL** [comment]
You can use the (currently undocumented) function [`remove_degenerate_faces()`](https://github.com/CGAL/cgal/blob/master/Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/repair_degeneracies.h#L1555).

**Comment by bianyunzhi95** [comment]
Thanks. That worked. Btw, is there any one function method that will prepare mesh(it is originally ready but it happens to distorted while compressing/decompressing using draco) for sequential boolean operations?

**Comment by MaelRL** [comment]
There is not a single function yet, but you can find many mesh repairing/cleaning functions in the [Polygon Mesh Processing package](https://doc.cgal.org/latest/Polygon_mesh_processing/index.html#Chapter_PolygonMeshProcessing).
