### ISSUE TITLE
Question: performance of displacement in Delaunay triangulations

### ISSUE THREAD

**Issue by krober10nd** [CGAL/cgal#5137]
## Issue Details

This is not an issue per se just a question searching for more information regarding a method.

 I would like to know the factors that affect the performance of the incremental move operations in Delaunay3 triangulations besides the amount of points. In some of my experience using the displacement ("move") operations in Delaunay3, it is sometimes faster to re-triangulate than to use the move operation; even for small point sets relative to the size of a large triangulation. 

I find this performance somewhat paradoxical and would like to know more about why this may occur. 

Perhaps this has to do with the distance the point has to move? 

I'm using CGAL 5.0.0 on Mac Catalina compiled with gcc 8.3.0. 

Thank you for any information you can provide!

**Comment by afabri** [comment]
Moving  is a removal and an insertion, if it is not just a very small displacement.
Removal and insertion have costs of the size of the conflict zone. In an extreme case (all points being co-spherical) all points may be concerned.
Can you retry with a more recent release (even just 5.0.3) as #4397 addressed performance of insertion.

**Comment by krober10nd** [comment]
Sure I can try with a more recent release. Thanks I’ll let you know. 

Just some context: I use moves in a sliver removal algorithm very similar to this 

https://imr.sandia.gov/papers/imr18/Tournois.pdf

by perturbing slivers so there circumsphere grows the fastest. Sometimes the sliver perturbation creates large point displacements and very slow performance hence the question.

**Comment by krober10nd** [comment]
So updating to 5.0.3 did not seem to help with the slow performance.

 I'm attaching the 3d triangulation (points and cells) and the indexes of the points and their new locations I would like to move.  On my Mac Book with Catalina using CGAL 5.0.3 this operation takes 78-84 seconds while a full retriangulation takes about 8 seconds. 

The mesh  has around 3.5 million cells

https://drive.google.com/file/d/14yzYNRFma49ZR7fwlE3HwVdk4-nvQLrV/view?usp=sharing

**Comment by afabri** [comment]
Can you please put a self-contained code on gist.github.com so that we can see how you use the triangulation.

**Comment by krober10nd** [comment]
Ah well I think I resolved the problem myself. I found there was indeed a lot of cospherical points due to a method I was using. I since altered the method and the performance improved significantly.
