### ISSUE TITLE
Unnecessary allocations in ID_support_handler

### ISSUE THREAD

**Issue by GilesBathgate** [CGAL/cgal#5143]
## Issue Details

Recently I have been investigating the performance of binary operations on Nef Polyhedra. The performance analysis I made revealed that ID_support_handler is making lots of allocations, due to a default bucket size of 512 here
https://github.com/CGAL/cgal/blob/16fc8d1fe27ff2ea79340d5c7a892083acbb24fe/Hash_map/include/CGAL/Tools/chained_map.h#L276-L277

While this isn't unreasonable for a hash map, (anything smaller and there isn't much advantage to using hashes) in ID_support_handler this is used to make a hash map, of hash maps:

https://github.com/CGAL/cgal/blob/16fc8d1fe27ff2ea79340d5c7a892083acbb24fe/Nef_3/include/CGAL/Nef_3/ID_support_handler.h#L41-L42

Consequently, there are 262144 buckets allocated. Since this is used to store Halffacet_const_handle f1, and Halffacet_const_handle f2, i.e a pair of half facets, these are usually pairwise, so each of the sub hash tables seems to always contain only 1 entry, (wasting the other 512 buckets!)

## Proposed fix

I have a proposed fix, details of which I will publish below.

## Source Code

I have created the following benchmark source code:

https://gist.github.com/GilesBathgate/78f9df7b149ccfd021d63a1d84842c24

Which has the output as follows:

```
Total allocations 772
Total bytes 14333952
And now lets populate...
table_size: 512
number of entries: 168
fraction of entries in first position: 0.184524
fraction of empty lists: 0.0605469
table_size: 512
number of entries: 1
fraction of entries in first position: 1
fraction of empty lists: 0.00195312
table_size: 512
number of entries: 1
fraction of entries in first position: 1
fraction of empty lists: 0.00195312
... repeated 512 times ...
```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):
Linux
* Compiler:
clang
* Release or debug mode:
Release
* Specific flags used (if any):
None
* CGAL version:
5.0.2
* Boost version:
1.71.0
* Other libraries versions if used (Eigen, TBB, etc.):
None

**Comment by GilesBathgate** [comment]
The proposed fix is instead of using a hash map of hash maps, to instead use a single hashmap of HalfFacet pairs, this is achieved using a struct, and a new hashing function which uses both hashes of the structs items to generate a combines hash.

The proposed implementation of this is given in #5144

Here are the results from the benchmark:

```
Total allocations 1
Total bytes 18432
And now lets populate...
table_size: 512
number of entries: 168
fraction of entries in first position: 0.190476
fraction of empty lists: 0.0625
```

In terms of stability, I have tried these changes in place in my own project for a while now and have noticed no difference in behaviour.

**Comment by afabri** [comment]
Is it "only"  a memory usage issue, or does it impact performance?  In the latter case do you have a cpp and data where one can see the difference?

**Comment by GilesBathgate** [comment]
The goal was to increase performance. I found the issue using qtcreator [profiling tools](https://doc.qt.io/qtcreator/creator-cpu-usage-analyzer.html) The flame graphs before and after showed fewer samples in `init_table` after the change. The removal of duplicated hash lookups are probably helping to facilitate a performance boost:

https://github.com/CGAL/cgal/pull/5144/files#diff-72f4c27e9b8013ec61e1d982fc52c76c2630b9efd1364c22e47ac6041d368285L80

However, I will put a benchmark together using google's [libbenchmark](https://github.com/google/benchmark) as I have since learned how to use this tool.

**Comment by GilesBathgate** [comment]
Firstly let me share the flame graph results I mentioned earlier:
In the baseline executable, during the symmetric_difference operation, 4.1% of the CPU samples are within the `Association A;` initialisation (Association is a typedef of ID_support_handler) 
![baseline](https://user-images.githubusercontent.com/444143/98576056-e61abd80-22b1-11eb-9e66-dfce183af8be.png)
In the contender executable, the aforementioned initialisation no longer appears in the flame graph. I've highlighted an unrelated operation which has 0.6% of the samples, meaning the contender is spending less than 0.6% of the CPU time for the improved code.
![contender](https://user-images.githubusercontent.com/444143/98576751-e5cef200-22b2-11eb-971d-edb6ac12b06c.png)

**Comment by GilesBathgate** [comment]
I have created a performance benchmark here:

https://gist.github.com/GilesBathgate/94a153553019c04b6090352f232c5a5b

In summary, there seems to be a performance increase in both the initialisation of the ID_support_handler, (initialisation_test ) and inserting of elements (hash_facet_pair_test).

**Comment by afabri** [comment]
I did the intersection of two medium sized Nef polyhedra  with the extract predicates/constructions kernel, and I don't see a difference with a timer.

**Comment by GilesBathgate** [comment]
Yes, I guess it's possible with different (larger) datasets the significance of this improvement is diminished. I am just trying to find a number of small performance tweaks that could add up to something more significant, and this was the first of which I decided to share.

**Comment by GilesBathgate** [comment]
I think there is a "sweet spot" where the improvement becomes more noticeable. I use the following [sphere.off](https://gist.github.com/GilesBathgate/513bda7135dd610f24a89c1a3a177b2a) and then do a symmetric_difference with itself to produce an empty set. Then the ID_support_handler initialisation is a very small percentage  (around 1.3%) of the whole boolean operation.
