### ISSUE TITLE
Surface meshes do not behave well with multi-threading

### ISSUE THREAD

**Issue by aseverino** [CGAL/cgal#5148]
## Issue Details

I'm trying to create a "divide to conquer" Mesh Boolean where I combine multiple cylinders into one single shape (forming a "fence" like shape). I'm trying to do it in parallel. The code is unstable and causes several crashes related to invalid memory access when trying to destroy objects. Most common is in Handle.h:

    ~Handle()
    {
        if ( PTR && (--PTR->count == 0))
            delete PTR;
    }

The only way I was able to get it to work, was to dynamically allocate and delete all the meshes.

## Source Code

       #include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
       #include <CGAL/Exact_predicates_exact_constructions_kernel.h>
       #include <CGAL/Surface_mesh.h>

       #include <CGAL/Polygon_mesh_processing/corefinement.h>

       #include <numeric>
       #include <execution>

        typedef CGAL::Exact_predicates_inexact_constructions_kernel     Kernel;
        typedef Kernel::Point_3											Point_3;
        typedef CGAL::Surface_mesh<Point_3>								Triangle_mesh;

        typedef CGAL::Exact_predicates_exact_constructions_kernel       Kernel_exact;
        typedef Kernel_exact::Point_3                                   Point_3_ex;
        typedef CGAL::Surface_mesh<Point_3_ex>                          Triangle_mesh_exact;
        typedef Kernel_exact::FT										FT_ex;

        namespace PMP = CGAL::Polygon_mesh_processing;

	class Combiner
	{
	public:
		Combiner(std::vector<Triangle_mesh_exact> toCombine);
		~Combiner() {};

		Triangle_mesh combineMeshes();

	private:
		std::vector<Triangle_mesh_exact> m_toCombine;
	};

	Combiner::Combiner(std::vector<Triangle_mesh_exact> toCombine)
	{
		m_toCombine = toCombine;
	}

	Triangle_mesh_exact combine(Triangle_mesh_exact a, Triangle_mesh_exact b)
	{
		auto c = Triangle_mesh_exact();

		bool success = false;

		try
		{
			success = CGAL::Polygon_mesh_processing::corefine_and_compute_union(a, b, c);
		}
		catch (const std::exception&)
		{
			return a;
		}

		return success ? c : a;
	}

	Triangle_mesh Combiner::combineMeshes()
	{
		Triangle_mesh_exact exact = std::reduce(std::execution::par_unseq,
			m_toCombine.begin(), m_toCombine.end(),
			m_toCombine.front(), combine);

		Triangle_mesh ret;
		ret.clear();
		CGAL::copy_face_graph(exact, ret);
		return ret;
	}

	int main(int argc, const char** argv)
	{
		std::ifstream in("V:/cylinder.off");
		Triangle_mesh cylinder;
		in >> cylinder;

		for (int j = 0; j < 100; ++j) {
			std::vector<Triangle_mesh_exact> clones;
			for (int i = 0; i < 10; ++i) {
				Triangle_mesh clone;
				CGAL::copy_face_graph(cylinder, clone);

				Kernel::Vector_3 vec = Kernel::Vector_3(i, 0, 0);
				CGAL::Aff_transformation_3<Kernel> aff(CGAL::Translation(), vec);

				for (auto& p : clone.points()) {
					p = p.transform(aff);
				}

				Triangle_mesh_exact exact; exact.clear();
				CGAL::copy_face_graph(clone, exact);
				clones.push_back(exact);
			}

			Combiner combiner(clones);
			auto ret = combiner.combineMeshes();

			std::ofstream out("V:/sweep.off");
			out << ret;
		}
	}

Just download the cylinder.txt and rename to cylinder.off
[cylinder.txt](https://github.com/CGAL/cgal/files/5530661/cylinder.txt)

## Environment

* Operating system: Windows 10
* Compiler: MSVC 2017
* Release or debug mode: RelWithDebInfo (x64)
* Specific flags used (if any): /bigobj
* CGAL version: 5.1
* Boost version: 1.67

**Comment by aseverino** [comment]
Anyone?

**Comment by afabri** [comment]
In cgal-discuss @sloriot wrote 

 Could you please open an issue on github with a minimal example showing a crash?

Then we can have a look.

**Comment by sloriot** [comment]
Just to mentioned that I wrote in the past a code doing union of a set of meshes in parallel and it was working fine. Unfortunately, I could not find it yet.

**Comment by aseverino** [comment]
> In cgal-discuss @sloriot wrote
> 
> Could you please open an issue on github with a minimal example showing a crash?
> 
> A minimal example is a cpp and a data set, that allow us to hopefully reproduce and fix.

Done. The source code now is self-contained, and I'm including cylinder.txt.

**Comment by afabri** [comment]
The problem comes from the fact that you clone the cylinder and that the points are reference counted objects. The reference counting mechanism is not multithreading safe.  Note that the affine transformation does not really change that, as the rotated points internally have a pointer to the input point.   Can you do the affine transformation inexact?

**Comment by aseverino** [comment]
That seems to solve the race condition, but if I ever change anything from exact, I end up having self-intersecting meshes. Is there a way to run `edge_collapse` on exact meshes?

**Comment by sloriot** [comment]
You have self-intersections after doing only a translation?

**Comment by aseverino** [comment]
No. After the first union.

**Comment by aseverino** [comment]
And I still have read access violations by following afabri's advice, albeit much more rare.

**Comment by aseverino** [comment]
I edited the code on the original post with afabri's suggestion. Still having problems at the same place.

**Comment by sloriot** [comment]
Here is a version that is working:
```
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/Polygon_mesh_processing/transform.h>
#include <CGAL/Surface_mesh.h>

#include <CGAL/Polygon_mesh_processing/corefinement.h>
#include <CGAL/Polygon_mesh_processing/repair.h>

#include <numeric>
#include <execution>

typedef CGAL::Exact_predicates_inexact_constructions_kernel     Kernel;
typedef Kernel::Point_3											Point_3;
typedef CGAL::Surface_mesh<Point_3>								Triangle_mesh;

namespace PMP = CGAL::Polygon_mesh_processing;

class Combiner
{
public:
	Combiner(std::vector<Triangle_mesh> toCombine);
	~Combiner() {};

	Triangle_mesh combineMeshes();

private:
	std::vector<Triangle_mesh> m_toCombine;
};


Combiner::Combiner(std::vector<Triangle_mesh> toCombine)
{
	m_toCombine = toCombine;
}

Triangle_mesh combine(Triangle_mesh a, Triangle_mesh b)
{
	bool success = false;
  Triangle_mesh c;

	try
	{
		success = PMP::corefine_and_compute_union(a, b, c, CGAL::parameters::throw_on_self_intersection(true));
	}
	catch (const PMP::Corefinement::Self_intersection_exception &)
	{
    PMP::experimental::remove_self_intersections(a);
    PMP::experimental::remove_self_intersections(b);
    
    try {
      success = PMP::corefine_and_compute_union(a, b, c, CGAL::parameters::throw_on_self_intersection(true));
    }
    catch (const PMP::Corefinement::Self_intersection_exception &)
    {}
	}

	return success ? c : a;
}

Triangle_mesh Combiner::combineMeshes()
{
	Triangle_mesh ret = std::reduce(std::execution::par_unseq,
		m_toCombine.begin(), m_toCombine.end(),
		m_toCombine.front(), combine);

  PMP::experimental::remove_self_intersections(ret);

	return ret;
}

int main()
{
	std::ifstream in("cylinder.off");
	Triangle_mesh cylinder;
	in >> cylinder;

	for (int j = 0; j < 100; ++j) {
		std::vector<Triangle_mesh> clones;
		for (int i = 0; i < 10; ++i) {
			Triangle_mesh clone;
			CGAL::copy_face_graph(cylinder, clone);

			CGAL::Aff_transformation_3<Kernel> aff(CGAL::Translation(),  Kernel::Vector_3(i, 0, 0));      
      PMP::transform(aff, clone);
      
      std::ofstream("cylinder_"+std::to_string(i)+".off") << std::setprecision(17) << clone;

			clones.push_back(clone);
		}

		Combiner combiner(clones);
		auto ret = combiner.combineMeshes();

		std::ofstream out("sweep.off");
		out << std::setprecision(17) << ret;
	}
}
```
It makes used of the experimental function `remove_self_intersections()`. Note that you should avoid copying the meshes if you want better performances. Use for example indices of the meshes in the `clones` instead of the mesh themselves in `reduce`.

**Comment by aseverino** [comment]
I'm glad the ticket was reopened, because the suggested solution doesn't solve the problem. The mesh is still riddled with self-intersections.

**Comment by sloriot** [comment]
Well it's not when I run it so I'm surprised. Did you run the same exact code or a modified version.

**Comment by MaelRL** [comment]
bump @aseverino
