### ISSUE TITLE
Is htere a 3D constrained triangulation methods in this package?

### ISSUE THREAD

**Issue by tub-sgg** [CGAL/cgal#5149]
_Please use the following template to help us solving your issue._

## Issue Details
I have to polylines( each polyline contains arbitrary 3D points), I want to triangulate these vertices but better to remain the polyline geometry constrains, however, if I simply use the function  Delaunay_triangulation_2,it   could not get a better result
![1](https://user-images.githubusercontent.com/44619635/98456227-4c50f480-217b-11eb-8056-2758e3e7c782.png)
the border is  discreted in some part. Is there a function or idea to solve it??

_Describe your issue. Please be specific (compilation error, runtime error, unexpected behavior, wrong results, etc.)._

## Source Code

_If your issue arises by using CGAL in your own source code, please provide a minimalist example that we can compile easily to reproduce the bug. If your issue arises from using a CGAL program (demo, example, etc.), please let us know which one. Helping you solving an issue is much easier and efficient if we can reproduce it._

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):
* Compiler:
* Release or debug mode:
* Specific flags used (if any):
* CGAL version:
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by sloriot** [comment]
Does this function solve your issue?

https://doc.cgal.org/latest/Polygon_mesh_processing/group__hole__filling__grp.html#ga8508fd49a2482ec7dcb3e1799234696a

**Comment by tub-sgg** [comment]
it seems it does not work very well  the result is like this
![Screenshot from 2020-11-09 14-30-32](https://user-images.githubusercontent.com/44619635/98547252-2ec57d00-2298-11eb-8930-f1371116261b.png)

**Comment by sloriot** [comment]
Could you please share the input polyline?

**Comment by tub-sgg** [comment]
Hi Loriot,
here I want to stitch two mesh models, these two mesh models overlaps on the joint.However if I simply use copy_face _graph(), there will be lots of self-intersecting triangulars(I could not find an usefull way to repair the self-intersecting issue). Therefore, I use clip() to cut both models and use slicer() to get the polylines
[polyline.txt](https://github.com/CGAL/cgal/files/5514540/polyline.txt). So is it possible to triangulate there area between these two polylines?(by the way,  the .txt file contains two polylines).

**Comment by sloriot** [comment]
It is not clear you will achieve what you want by using this method but here are some advises:
- You have 2 polylines that you want to join. Join them using the endpoints or the closest point to one endpoint. If one is longer than the other the result will be better
- Do not forget to pass `third_points` to [triangulate_hole_polylines](https://doc.cgal.org/latest/Polygon_mesh_processing/group__hole__filling__grp.html#ga8508fd49a2482ec7dcb3e1799234696a), the read point on the picture below. Use midpoint if there is no incident triangle.

I'm closing the issue as there is not much more we can do.

![ex](https://user-images.githubusercontent.com/1224632/98651721-e743fd00-233a-11eb-8675-98df90feff0e.png)

**Comment by tub-sgg** [comment]
I  want to fill the gap .using a mesh surface. And the border of new mesh surface should exactly match each other.
By the way, what is a proper way to combine  two surface mesh model( they are not a close model and overlap in some part. Because I see the function: [corefine_and_compute_union()](https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__corefinement__grp.html#gad7e1741a7ce41a5846cf86494982ca8b) requires a  bound volume model and the function [copy_face_graph()](https://doc.cgal.org/latest/BGL/group__PkgBGLHelperFct.html#ga2d3eb044bfe42eab566779ce32216c11) can not be sure the combined area is a non-selfintersecting area.

**Comment by sloriot** [comment]
I understood what you said and what you need is not a union but a fusion of meshes that overlap. We did some experiments in the past but nothing was included in CGAL. You should try what I suggest above after having clipped your surfaces. Your surfaces seem to be shaggy so you might not get good results.
