### ISSUE TITLE
Failure while joining many 2D polygons

### ISSUE THREAD

**Issue by striajan** [CGAL/cgal#5163]
## Issue Details

I'd like to project a 3D mesh onto a horizontal plane to obtain its accurate 2D footprint. The input mesh can be pretty complex, therefore, the footprint can consist of several polygons with holes in general. My code crashes even while projecting a simple [torus](https://en.wikipedia.org/wiki/Torus), which should result in an [annulus](https://en.wikipedia.org/wiki/Annulus_(mathematics)) footprint. It crashes specifically while joining the 2D triangles into a set of polygons with holes.

This is the input OBJ file that is used for testing: [torus.zip](https://github.com/CGAL/cgal/files/5547221/torus.zip)

This is a stack trace:
```
    @     0x7fd66cc3a602  (unknown)  raise
    @     0x5566c4feb496        976  FailureSignalHandler()
    @     0x7fd66cdb89a0  360306928  (unknown)
    @     0x5566c2bbf7e9         16  boost::detail::variant::forced_return_no_return()
    @     0x5566c2bd24e9         16  boost::detail::variant::forced_return<>()
    @     0x5566c2bd24c7         16  boost::detail::variant::visitation_impl<>()
    @     0x5566c2bd1888        256  CGAL::Arr_segment_traits_2<>::Intersect_2::operator()<>()
    @     0x5566c2bcea5e        624  CGAL::Arr_overlay_traits_2<>::Intersect_2::operator()<>()
    @     0x5566c2bce23f        384  CGAL::Surface_sweep_2::Surface_sweep_2<>::_intersect()
    @     0x5566c2bcd6c0        192  CGAL::Surface_sweep_2::Surface_sweep_2<>::_handle_overlaps_in_right_curves()
    @     0x5566c2bc81d9        144  CGAL::Surface_sweep_2::Surface_sweep_2<>::_handle_left_curves()
    @     0x5566c2bc2888        144  CGAL::Surface_sweep_2::No_intersection_surface_sweep_2<>::indexed_sweep<>()
    @     0x5566c2bc1dd6       2448  CGAL::overlay<>()
    @     0x5566c2bbbf31         64  CGAL::Gps_on_surface_base_2<>::_join()
    @     0x5566c2bbaf76        304  CGAL::Gps_on_surface_base_2<>::_join<>()
    @     0x5566c2bac4fb        208  ProjectMeshOntoHorizontalPlane()
    @     0x5566c2bacac4        368  main
```

Please note that if I generate the 2D triangles to be joined randomly using the function `GenerateRandomTriangles`, the algorithm seems to works even for 100s triangles. I would be grateful for any advice! Thank you!

## Source Code

```cpp
#include <algorithm>
#include <array>
#include <cassert>
#include <cstddef>
#include <iostream>
#include <random>
#include <string>
#include <vector>

#include "CGAL/Polygon_set_2.h"
#include "CGAL/Exact_predicates_inexact_constructions_kernel.h"
#include "CGAL/Polygon_with_holes_2.h"
#include "CGAL/IO/OBJ_reader.h"
#include "CGAL/Surface_mesh/Surface_mesh.h"

using K = CGAL::Exact_predicates_inexact_constructions_kernel;
using Mesh = CGAL::Surface_mesh<K::Point_3>;
using Polyline_2 = std::vector<K::Point_2>;
using Polygon_2 = CGAL::Polygon_2<K>;
using Polygon_with_holes_2 = CGAL::Polygon_with_holes_2<K>;
using Polygon_set_2 = CGAL::Polygon_set_2<K>;

std::vector<Polygon_2> GenerateRandomTriangles(int num_triangles) {
  std::vector<Polygon_2> triangles;
  triangles.reserve(num_triangles);

  std::random_device rd;
  std::mt19937 gen(rd());
  std::uniform_real_distribution<double> dis(-1, 1);

  for (int t = 0; t < num_triangles; ++t) {
    std::array<K::Point_2, 3> triangle;
    for (int v = 0; v < 3; ++v) {
      triangle[v] = K::Point_2(dis(gen), dis(gen));
    }

    triangles.emplace_back(triangle.begin(), triangle.end());
  }

  return triangles;
}

Mesh ReadMesh(const std::string& filename) {
  std::ifstream istream(filename);
  std::vector<K::Point_3> points;
  std::vector<std::vector<size_t>> faces;
  CGAL::read_OBJ(istream, points, faces);

  CGAL::Surface_mesh<K::Point_3> mesh;
  for (const auto& p : points) {
    mesh.add_vertex(p);
  }
  for (const auto& f : faces) {
    assert(f.size() == 3);
    mesh.add_face(Mesh::Vertex_index(f[0]),
                  Mesh::Vertex_index(f[1]),
                  Mesh::Vertex_index(f[2]));
  }

  return mesh;
}

Polygon_set_2 ProjectMeshOntoHorizontalPlane(const Mesh& mesh) {
  std::vector<Polygon_2> polygons;
  for (const auto& face_idx : mesh.faces()) {
    std::vector<K::Point_2> face_points;
    const auto& vertex_indices = mesh.vertices_around_face(mesh.halfedge(face_idx));

    for (const auto& vertex_idx : vertex_indices) {
      const auto& p = mesh.point(vertex_idx);
      face_points.emplace_back(p.x(), p.y());
    }

    polygons.emplace_back(face_points.begin(), face_points.end());
  }

  Polygon_set_2 polyset;
  for (const auto& polygon : polygons) {
    polyset.join(polygon);
  }

  return polyset;
}

int main(int argc, char* argv[]) {
  const CGAL::Surface_mesh<K::Point_3> mesh = ReadMesh("torus_z.obj");
  Polygon_set_2 polyset = ProjectMeshOntoHorizontalPlane(mesh);
  return 0;
}
```

## Environment

* Operating system: Linux 64-bit
* Compiler: gcc
* Release or debug mode: release
* CGAL version: CGAL-5.2-beta1 ([1d9bebc](https://github.com/CGAL/cgal/commit/1d9bebc6739e4380061d2ed0afe5f0c87a363490))
* Boost version: 1.67

**Comment by afabri** [comment]
The 2D Boolean operations need the `Exact_predicates_exact_constructions_kernel`

**Comment by striajan** [comment]
Thanks for a quick response! But using `Exact_predicates_exact_constructions_kernel` instead of `Exact_predicates_inexact_constructions_kernel` didn't help. The stack trace is exactly the same.

**Comment by sloriot** [comment]
Input polygons must be counterclockwise, as far as I see you are not checking that.

https://doc.cgal.org/latest/Polygon/classCGAL_1_1Polygon__2.html#a50f72a61b1a3eac123e10a8b6d928635
https://doc.cgal.org/latest/Polygon/classCGAL_1_1Polygon__2.html#ac9bca34769a460a300acdc1415be7ca9

**Comment by striajan** [comment]
I'm sorry. It turned out that I was not using `Exact_predicates_exact_constructions_kernel`, even though I thought so.

You're right that I was not checking whether the polygons are oriented counter-clockwise. But it doesn't work even for correctly oriented triangles.

This is a new minimum example with just 8 triangles:

```cpp
#include <cassert>
#include <vector>

#include "third_party/cgal/Boolean_set_operations_2/include/CGAL/Polygon_set_2.h"
#include "third_party/cgal/Kernel_23/include/CGAL/Exact_predicates_exact_constructions_kernel.h"
#include "third_party/cgal/Polygon/include/CGAL/Polygon_with_holes_2.h"

using K = CGAL::Exact_predicates_exact_constructions_kernel;
using Polygon_2 = CGAL::Polygon_2<K>;
using Polygon_set_2 = CGAL::Polygon_set_2<K>;

int main(int argc, char* argv[]) {
  std::vector<K::Point_2> points {
    {-0.323524,1.20741},{0,1.17678},{0,1.25},
    {-0.304572,1.13668},{0,1},{0,1.17678},
    {-0.258819,0.965926},{0,0.823223},{0,1},
    {-0.213066,0.795173},{0,0.75},{0,0.823223},
    {-0.194114,0.724444},{0,0.75},{0,0.823223},
    {0,0.823223},{0,1},{-0.258819,0.965926},
    {0,1},{0,1.17678},{-0.304572,1.13668},
    {0,1.17678},{0,1.25},{-0.323524,1.20741},
  };

  std::vector<Polygon_2> polygons;
  for (int i = 0; i < points.size(); i += 3) {
    polygons.emplace_back(points.begin() + i, points.begin() + i + 3);
    assert(polygons.back().is_counterclockwise_oriented());
  }

  Polygon_set_2 polyset;
  for (const Polygon_2& polygon : polygons) {
    polyset.join(polygon);
  }

  return 0;
}
```

I'm getting the following error this time: `terminating with uncaught exception of type CGAL::Uncertain_conversion_exception: Undecidable conversion of CGAL::Uncertain<T>`

**Comment by sloriot** [comment]
It works for me. If you are not using cmake, maybe you did not pass `-frounding-math` option to the compiler.
![Screenshot from 2020-11-17 09-41-16](https://user-images.githubusercontent.com/1224632/99366846-71e7a780-28b9-11eb-889d-1ecd965e447b.png)
![Screenshot from 2020-11-17 09-41-20](https://user-images.githubusercontent.com/1224632/99366848-72803e00-28b9-11eb-8877-281beeb132a3.png)

**Comment by sloriot** [comment]
My code with the print as polyline for the 3D demo is [here](https://gist.github.com/sloriot/6b872a1c5ad9b4d192fa35e3ad654540).

**Comment by striajan** [comment]
It turned out that we have exception handling turned off by default and therefore any exception, even if handled inside CGAL correctly, causes the binary to crash. So building my binary with `-fexceptions` solved the problem.

Thanks for all your help and for creating such a great library!
