### ISSUE TITLE
How to remove and add faces in mesh model

### ISSUE THREAD

**Issue by tub-sgg** [CGAL/cgal#5165]
_Please use the following template to help us solving your issue._
If I try to use the function [remove_face](https://doc.cgal.org/latest/Surface_mesh/classCGAL_1_1Surface__mesh.html#af2311658bf6d730b276b23b5c304f90e), it will definitely produce some bugs. you can see the test code below. I want to remove some special face in a mesh model but save the vertices around the deleted face. There is a bug which the first one is always invalid.
So I would like to ask you how I can add or remove faces in a mesh model correctly?any ideas?
## Issue Details

_Describe your issue. Please be specific (compilation error, runtime error, unexpected behavior, wrong results, etc.)._

## Source Code
```c++
#include <CGAL/Surface_mesh.h>
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>

#include <CGAL/Polygon_mesh_processing/repair.h>
#include<CGAL/Timer.h>
#include <CGAL/Polygon_mesh_processing/polygon_mesh_to_polygon_soup.h>
#include <CGAL/Polygon_mesh_processing/repair.h>

#include <CGAL/Polygon_mesh_processing/measure.h>
#include <CGAL/boost/graph/copy_face_graph.h>
#include<iostream>
#include<vector>

typedef CGAL::Exact_predicates_inexact_constructions_kernel       K;
typedef CGAL::Surface_mesh<K::Point_3>                            SMesh;
typedef SMesh::Vertex_index                                       Vertex_index;
typedef SMesh::Face_index                                         Face_index;
typedef SMesh::Halfedge_index                                     Halfedge_index;


int main(int argc, char **argv){


    const char* in_file = (argc > 1) ? argv[1] : "../data/cube.off";
    SMesh pmesh;
    std::ifstream in(in_file);
    if(in.fail()) {
        std::cerr << "Could not open input file " << in_file << std::endl;
        return 1;
    }
    in >> pmesh;
    CGAL::Timer t;
    t.start();

    std::vector<Face_index > faces_index(faces(pmesh).begin(), faces(pmesh).end());
    std::vector<std::vector<Vertex_index>> deletetris;

    for(auto fidx:faces_index){
        pmesh.remove_face(fidx);
        //save the triangulars
        std::vector<Vertex_index> tmp;
        auto tp = CGAL::vertices_around_face(pmesh.halfedge(fidx), pmesh);
        for (auto vd:tp) {
            std::cout<<"vertex_index="<<vd<<std::endl;
            tmp.push_back(vd);
        }
        deletetris.push_back(tmp);
        std::cout<<"===================="<<std::endl;
    }
//    pmesh.collect_garbage();
    for(auto del:deletetris) {

        std::cout<<"del="<<del[0]<<","<<del[1]<<","<<del[2]<<std::endl;
    }
    std::cerr << "Done (" << t.time() << " s)" << std::endl;



    return 0;
}
```

_If your issue arises by using CGAL in your own source code, please provide a minimalist example that we can compile easily to reproduce the bug. If your issue arises from using a CGAL program (demo, example, etc.), please let us know which one. Helping you solving an issue is much easier and efficient if we can reproduce it._

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):UBUNTU 18.04
* Compiler:GCC
* Release or debug mode:
* Specific flags used (if any):
* CGAL version: 5.1
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by afabri** [comment]
As the documentation states 

> **Warning**
    Functions in this group do not adjust any of connected elements and usually leave the surface mesh in an invalid state. 

You can find the high level operation [`CGAL::Euler::remove_face()`](https://doc.cgal.org/latest/BGL/group__PkgBGLEulerOperations.html#gacfae7ff8e782da55b941e4487e86c738)  in the package [CGAL and the Boost Graph Library](https://doc.cgal.org/latest/BGL/group__PkgBGLEulerOperations.html).

**Comment by tub-sgg** [comment]
thanks for your reply, 
However this function CGAL::Euler::remove_face()  can no t remove border halfedge, But for me , in some situation I have to remove the border face,, which one should I use?

**Comment by sloriot** [comment]
Why can't it remove border face? Did you give it a try and go an problem?

**Comment by tub-sgg** [comment]
[CGAL::Euler::remove_face()](https://doc.cgal.org/latest/BGL/group__PkgBGLEulerOperations.html#gacfae7ff8e782da55b941e4487e86c738), its recondition is not a border halfedge. And I got such error:
 terminate called after throwing an instance of 'CGAL::Precondition_exception'
  what():  CGAL ERROR: precondition violation!
Expr: ! is_border(h,g)
File: /usr/local/include/CGAL/boost/graph/Euler_operations.h
Line: 509

**Comment by MaelRL** [comment]
You have to give `remove_face()` a halfedge that is incident to the face you want to remove; such halfedge can be obtained for example with `halfedge(f, g)`. 

A border halfedge is "outside" and is not incident to any face, thus the precondition.

**Comment by tub-sgg** [comment]
yes, I input a halfedge, my code is like this:
void deal_with_two_triangles(Halfedge_index &&h,
                             SMesh& mesh){
    typedef K::Point_3 Point;
    //make sure the face is a triangle
    if(!CGAL::is_triangle(h,mesh)){
        std::cerr<<"invalid data, the face should be a  triangle"<<std::endl;
        return;
    }
    //find the longest edge
    //get three halfedge for this triangle
    Halfedge_index longestEdge;
    double len=0.f;
    for(auto hf:CGAL::halfedges_around_face(h,mesh)){
        double tp=CGAL::Polygon_mesh_processing::edge_length(hf,mesh);
        if(tp>len){
            len=tp;
            longestEdge=hf;
        }
    }

    // find the mid-point
    auto tar=target(longestEdge,mesh);
    auto src=source(longestEdge,mesh);
    auto points=mesh.points().data();
    Point midPt=Point(0.5*(points[tar.idx()].x()+points[src.idx()].x()),
                      0.5*(points[tar.idx()].y()+points[src.idx()].y()),
                      0.5*(points[tar.idx()].z()+points[src.idx()].z()));
    //add mid point
    Vertex_index midVertex=CGAL::add_vertex(midPt,mesh);
    //find the correspond vertex for the longestEdge
    auto correspondVertex=target(next(longestEdge,mesh),mesh);

    //chech the halfedge is a border or not
    bool test=CGAL::is_border(longestEdge,mesh);
    if(test){
        //remove the face ,find the next edge which is not a boder edge
        Halfedge_index nt=next(longestEdge,mesh);
        if(!CGAL::is_border(nt,mesh))
        {
            CGAL::Euler::remove_face(nt,mesh);
        }
        else{
            CGAL::Euler::remove_face(prev(longestEdge,mesh),mesh);
        }

        CGAL::Euler::remove_face(longestEdge,mesh);
        // create new faces


        std::vector<Vertex_index> first_index{correspondVertex,src,midVertex},
                                    second_index{midVertex,tar,correspondVertex};
        CGAL::Euler::add_face(first_index,mesh);
        CGAL::Euler::add_face(second_index,mesh);

    }else{
        //Find the opposite halfedge
        Halfedge_index oppoEdge=opposite(longestEdge,mesh);
        //find the corre vertex index
        Vertex_index corr_opposite=target(next(oppoEdge,mesh),mesh);
        //Point p=points[corr_opposite.idx()];
        //remove both faces
        //make sure oppoEdge is not a border edge
        std::cerr<<"border halfedge="<<CGAL::is_border(oppoEdge,mesh)<<std::endl;
        CGAL::Euler::remove_face(oppoEdge,mesh);
        //add faces
        //1st
        std::vector<Vertex_index> first_index{correspondVertex,src,midVertex},
                second_index{midVertex,tar,correspondVertex};
        CGAL::Euler::add_face(first_index,mesh);
        CGAL::Euler::add_face(second_index,mesh);
        //2nd
        std::vector<Vertex_index> third_index{midVertex,target(oppoEdge,mesh),corr_opposite},
                fourth_index{corr_opposite,source(oppoEdge,mesh),midVertex};
        //corr_opposite=mesh.add_vertex(p);
        CGAL::Euler::add_face(third_index,mesh);
        CGAL::Euler::add_face(fourth_index,mesh);

    }


}

**Comment by tub-sgg** [comment]
that is the code I try to add and remove faces, however got some error

**Comment by MaelRL** [comment]
```
        Halfedge_index nt=next(longestEdge,mesh);
        if(!CGAL::is_border(nt,mesh))
        {
            CGAL::Euler::remove_face(nt,mesh);
        }
        else{
            CGAL::Euler::remove_face(prev(longestEdge,mesh),mesh);
        }
```
If `nt = next(longestEdge, mesh)` is a border halfedge, so is `longestEdge` and so is `prev(longestEdge, mesh)`. `next()` and `prev()` enable you to walk on the border of the face. When on a border, you are walking along the border. You can use `opposite(h,g)` to get the halfedge opposite of a halfedge.

**Comment by tub-sgg** [comment]
Halfedge_index nt=next(longestEdge,mesh);
        if(!CGAL::is_border(nt,mesh))
        {
            CGAL::Euler::remove_face(nt,mesh);
        }
        else{
            CGAL::Euler::remove_face(prev(longestEdge,mesh),mesh);
        }

this part ,I just want to delete this face .To be honest I dont understand very well how to delete border halfedge, if I use opposite(f,g), I think I get its neighbor face(maybe the neighbor does not exist).

So the function CGAL::Euler::remove_face(h,g), if h is included in a face, and one edge of this face is a border edge, so this function does not work any more. So in general How could I remove this face

**Comment by sloriot** [comment]
Why not `CGAL::Euler::remove_face(opposite(n, mesh),mesh);` in the else?

**Comment by tub-sgg** [comment]
Oh Sorry, maybe I made some mistakes,This function will delete the isolated vertex and it resulted some error
