### ISSUE TITLE
How to compile CGAL5.1.1 including OpenGR+PointMatcher ?

### ISSUE THREAD

**Issue by Micalson** [CGAL/cgal#5167]
Hello, I found the new feature of CGAL 5.1.1 about point cloud registration. But I could not compile it successfully in Visual Studio 2017. Is there any docs about this? Thank you for your reply.

Regards,

**Comment by sgiraudot** [comment]
You need to first compile OpenGR and/or PointMatcher depending on which function you want to use (see https://doc.cgal.org/latest/Manual/thirdparty.html#title9 ).

Then, when configuring CMake on the Point Set Processing examples (which I assume you are trying to do, if not please let me know), you need to fill the `OpenGR_DIR` and `libpointmatcher_DIR` fields if they are not found.

You can copy-paste your configuration and error messages if you need more help.

**Comment by Micalson** [comment]
I compile the example "registration_with_OpenGR", and the following is the errors:
> 1>c:\program files\pcl 1.8.1\3rdparty\eigen\eigen3\eigen\src\core\product.h(29): error C3646: “Scalar”: Unknown overwrite specifier
1>c:\program files\pcl 1.8.1\3rdparty\eigen\eigen3\eigen\src\core\product.h(29): error C4430: Missing type specifier
1>c:\program files\pcl 1.8.1\3rdparty\eigen\eigen3\eigen\src\core\densecoeffsbase.h(38): error C2039: “Scalar”: not member of “Eigen::internal::traits<Derived>”的成员

**Comment by Micalson** [comment]
I compiled OpenGR successfully separately, but cannot compile the registration_with_OpenGR example successfully.

**Comment by sgiraudot** [comment]
Can you share your configuration (output of cmake)? The errors seems to come from Eigen, which in your case seems to be the version shipped from PCL, I'd like to know which version is used.

**Comment by sgiraudot** [comment]
I see you closed the issue: did you manage to compile the example? Did you figure out what was going wrong?

**Comment by Micalson** [comment]
Sorry, I did not find the cause.  I compile the OpenGR independently and use it with CGAL instead of CGAL build-in OenGR.
