### ISSUE TITLE
Object to variant missing?

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#5174]
In the doc of the concept [ConstrainedTriangulationTraits_2](https://doc.cgal.org/latest/Triangulation_2/classConstrainedTriangulationTraits__2.html#a686a7db5dd5eeae155213d354f94bdb1) it says that `Intersect_2` should return a `Object`. However, we can also see that any CGAL Kernel is model of  `ConstrainedTriangulationTraits_2` but CGAL Kernel `Intersect_2` returns `boost::optional<boost::variant<...> >`. Shall we update the concept? Currently the projection traits `Intersect_2` functors return `Object` while Kernel's return variant and the conversion to Object has an extra cost.

**Comment by lrineau** [comment]
Should not we move away from `Object`, in CDT_2, in favor of the newest intersection value types?

**Comment by sloriot** [comment]
That's what I suggest by updating the concept. Since you are the maintainer I would say it's up to you to decide :)

**Comment by afabri** [comment]
@sloriot I am wondering how to write the result type for the Intersect in the `Projection_traits` class.
