### ISSUE TITLE
Boundary edges or split issue

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#5176]
I do:
"Detect boundaries", select the polyline item and then "Split Graph Into Polylines", then "split selected polyline" and got 2 polylines instead of one. There might be some duplicated edges that makes parallel edges to be inserted in a `boost::adajcency_list`.

![Screenshot from 2020-11-20 14-08-36](https://user-images.githubusercontent.com/1224632/99803657-22fc7500-2b3a-11eb-90d8-c16404402607.png)
[hex.off.gz](https://github.com/CGAL/cgal/files/5573647/hex.off.gz)

**Comment by tub-sgg** [comment]
by the way, what kind of tools that you ues for the visiualization?

**Comment by sloriot** [comment]
@tub-sgg The CGAL polyhedron demo that you can compile in the directory `demo/Polyhedron` from a CGAL release.
