### ISSUE TITLE
FuzzyQueryItem concept nested types

### ISSUE THREAD

**Issue by mglisse** [CGAL/cgal#5178]
## Issue Details

The concept FuzzyQueryItem documents that a model must provide nested public types Point_d, FT and D. The first thing to notice is that Fuzzy_sphere does not provide D. Second, nothing uses any of those types in Kd_tree. It looks like they are present because the rest of the concept has a function that takes a Point_d and another one that takes a `Kd_tree_rectangle<FT,D>`, and because Kd_tree::search needs a way to say that the argument of contains() matches the type SearchTraits::Point_d.

Should there be a mention that those types are for "exposition only"? Or just remove them? Rename D to Dimension or vice versa?

## Environment

* CGAL version: 5.1

**Comment by sloriot** [comment]
If they are not needed, we should remove them.

**Comment by lrineau** [comment]
The fix from https://github.com/CGAL/cgal/pull/5231 will be in CGAL-5.3, planned June 2021.
