### ISSUE TITLE
How to set Qt for CGAL

### ISSUE THREAD

**Issue by tub-sgg** [CGAL/cgal#5179]
_Please use the following template to help us solving your issue._

## Issue Details

I want to use Qt to visualize the result. However  there is something wrong with the configuration about Qt and CGAL.
Qt is succussfully installed and I use CMake to do the configuration
The options is as follows:
![qt_cgal](https://user-images.githubusercontent.com/44619635/99902864-20785780-2cc1-11eb-97bb-5008d5722ac3.png)
and then, I have installed CGAL in a default location (sudo make install)
![2](https://user-images.githubusercontent.com/44619635/99903057-320e2f00-2cc2-11eb-8132-18df1da5eeb4.png)

And I have already set the Qt path:   export PATH=$PATH:...../bin
I think I set all env correctly, however,when want to use it, CGAL_Qt5 could not found yet and the error is always :+1:  Impossible to draw, CGAL_USE_BASIC_VIEWER is not defined.
how could I solver this problem? any idea
## Source Code

_If your issue arises by using CGAL in your own source code, please provide a minimalist example that we can compile easily to reproduce the bug. If your issue arises from using a CGAL program (demo, example, etc.), please let us know which one. Helping you solving an issue is much easier and efficient if we can reproduce it._

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):UBuntu 18.04
* Compiler:
* Release or debug mode:Debug
* Specific flags used (if any):
* CGAL version:5.1
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by gdamiand** [comment]
did you defined CGAL_USE_BASIC_VIEWER ? (cf for example [this CMakelist](https://github.com/CGAL/cgal/blob/master/Polyhedron/examples/Polyhedron/CMakeLists.txt)).

**Comment by tub-sgg** [comment]
I think the problem located here:
find_package(CGAL COMPONENTS Qt5 REQUIRED)
 if(CGAL_Qt5_FOUND)## always false, so it could not find CGAL_Qt5

**Comment by gdamiand** [comment]
> I think the problem located here:
> find_package(CGAL COMPONENTS Qt5 REQUIRED)
> if(CGAL_Qt5_FOUND)## always false, so it could not find CGAL_Qt5

If CGAL_Qt5 is not found; you should have an error when running cmake.
Could you show me your log of cmake please?

**Comment by tub-sgg** [comment]
yes There is no error.But I add
 if(CGAL_Qt5_FOUND)
  message(STATUS "Found CGAL_Qt5 library.")

  add_definitions(-DCGAL_USE_BASIC_VIEWER -DQT_NO_KEYWORDS)

endif()
It should output Found CGAL_Qt5, but there is not, So I think it could not find CGAL_Qt5
The CMakeOutput.log is 
[CMakeOutput.log](https://github.com/CGAL/cgal/files/5582304/CMakeOutput.log

**Comment by gdamiand** [comment]
Could you also provide the output of cmake (if possible both when you configure CGAL and when you configure your program).

**Comment by tub-sgg** [comment]
this is output for installation:
[build.zip](https://github.com/CGAL/cgal/files/5588423/build.zip)

this is the example for draw polyhedron 
[cmake-build-debug.zip](https://github.com/CGAL/cgal/files/5588440/cmake-build-debug.zip)

**Comment by lrineau** [comment]
### Diagnotic
@tub-sgg:
> this is output for installation:
> [build.zip](https://github.com/CGAL/cgal/files/5588423/build.zip)

Here the `CMakeCache.txt` shows that Qt5 was found in `/home/alxlee/Documents/Qt/5.12.8/gcc_64/`.

> this is the example for draw polyhedron
> [cmake-build-debug.zip](https://github.com/CGAL/cgal/files/5588440/cmake-build-debug.zip)

But then, if the example, the `CMakeCache.txt` shows that Qt5 was found in the system (in `/usr/lib/x86_64-linux-gnu/`,) but the *required* component `Qt5Svg` is missing.

### Solution
During the configuration of the example, you should:
  - remove all the CMake cache variables about Qt5,
  - add `/home/alxlee/Documents/Qt/5.12.8/gcc_64/` to `CMAKE_PREFIX_PATH`, so that Qt5 can be found there.
