### ISSUE TITLE
Uninitialized members - static analysis.

### ISSUE THREAD

**Issue by GilesBathgate** [CGAL/cgal#5181]
## Issue Details

CWE-456: I use static analysis on my project provided by Synopsis Coverity Scan. Amongst other issues, there are approx 23 instances of class constructors not initialising all pointer, and scalar member variables. This is a trivial issue but one for which I have been able to create patches. I will submit these as pull requests.

## Source Code

Before applying patches my project has the following analysis results:

![coverity-defects](https://user-images.githubusercontent.com/444143/100069259-728bbb00-2e30-11eb-9952-3bf500a35b52.png)
 
After applying the patches the results are as follows:

![coverity-defects-partially-resolved](https://user-images.githubusercontent.com/444143/100070813-44a77600-2e32-11eb-9783-6794458d2c1f.png)

## Environment

* Operating system (Linux, 64 bits):
* Compiler: gcc
* Release or debug mode: release
* CGAL version: 5.0.2
* Boost version: 1.71.0
* Other libraries versions if used (Eigen, TBB, etc.): Qt 5.12.8

**Comment by GilesBathgate** [comment]
The two `High` issues are fixed by #5169 and #5168

**Comment by GilesBathgate** [comment]
One of the `Low` issues (Copying large values is inefficient, consider passing by reference; size thresholds for detection can be adjusted.) was fixed by #5143

**Comment by lrineau** [comment]
https://github.com/CGAL/cgal/pull/5189 is only a partial fix.
