### ISSUE TITLE
CGAL error: assertion violation in bipartite_nary_union_sorted_combined.h

### ISSUE THREAD

**Issue by keleisi2001** [CGAL/cgal#5206]
## Issue Details

I try to use CGAL to deal with OFF model and then I find this strange error:

```
WARNING: Geometry is not solid, will make it fat. ->
CGAL error: assertion violation!
Expression : !GM0.empty() && !GM1.empty()
File : C:\dev\CGAL-4.13\include\CGAL/Minkowski_sum_3/bipartite_nary_union_sorted_combined.h
Line : 211
Explanation: one operand must be full-dimensional
Refer to the bug-reporting instructions at https://www.cgal.org/bug_report.html
```

I tried 10 different models, and 6 of them gave the same error message. So I want to consult experienced developers how to solve this problem.

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):WIN 10 64bits
* Compiler:visual studio
* Release or debug mode: Just use it in CMD
* Specific flags used (if any):
* CGAL version: 4.13
* Boost version: 1.56
* Other libraries versions if used (Eigen, TBB, etc.): OpenCASCADE6.7.0 IFCOPENSHELL 0.4.0

**Comment by sloriot** [comment]
Would you mind providing one such model? I think it is because you are using a function to decompose a solid onto something that is not a solid (model with boundary edges).

**Comment by MaelRL** [comment]
bump @keleisi2001
