### ISSUE TITLE
Possible issue with C++14 vs. C++17 in cgal-5.1

### ISSUE THREAD

**Issue by waebbl** [CGAL/cgal#5211]
_Please use the following template to help us solving your issue._

## Issue Details

We encountered an issue building the openscad package when building against cgal-5.1, cf. https://bugs.gentoo.org/755842. After talking to the openscad folks (https://github.com/openscad/openscad/issues/3497) it looks like this might be related to using a C++17 feature (is_swappable) while the manual states compatibility to C++14. Please see the attached build log at the openscad issue for a complete log.

## Source Code

I'm the maintainer of the package for Gentoo, but not involved in the openscad code itself, so I'm sorry to not be able to provide a simple minimalistic example to show the issue.

## Environment

* Operating system (Linux, 64 bits):
* Compiler: gcc-10.2.0
* Release or debug mode: probably debug, -DDEBUG is defined although it should be a release build
* Specific flags used (if any): -std=c++11 -std=gnu++11
* CGAL version: 5.1
* Boost version: 1.74.0
* Other libraries versions if used (Eigen, TBB, etc.): eigen-3.3.8, qt5-5.15.1, opengl (Nvidia-455.38), glu-9.0.1 , libX11-1.6.12, mpfr-4.1.0, gmp-6.2.1

**Comment by lrineau** [comment]
The issue is with the use of `-std=gnu++11`, that CGAL>=5.0 does not support.

See in the upstream bug at https://github.com/openscad/openscad/issues/3497#issuecomment-734751342 for a detailed explanation.
