### ISSUE TITLE
Surface_mesh: How will the indices of face, edge, halfedege, and vertex change after I remove some face or edge?

### ISSUE THREAD

**Issue by tub-sgg** [CGAL/cgal#5217]
_Please use the following template to help us solving your issue._

## Issue Details
I would like to know is there document that explain how the index change once some features have been modified.

For example, if one face of a model has been removed, the lower index faces will remain the same and the greater ones will be index -1? and the edges, vertices or halfegde will obey the identical rules?
if one new face has been added successfully, the index will be the last index+1?

Do I understand correctly? I only read some source code but not sure I got the idea correctly.

_Describe your issue. Please be specific (compilation error, runtime error, unexpected behavior, wrong results, etc.)._

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):
* Compiler:
* Release or debug mode:
* Specific flags used (if any):
* CGAL version:
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by lrineau** [comment]
Just to be sure, which CGAL class are you asking about? My guess is it is `CGAL::Surface_mesh<Point>`. Am i right?

**Comment by tub-sgg** [comment]
Yes I am doing on surface_mesh, however some functions are not only from the surface_mesh<Point> class. Some functions are from BGL,
for example, CGAL::Euler::remove_face() to be used instead of the mesh.remove_face(), add_vertex() is from CGAL::Surface_mesh<Point>

**Comment by tub-sgg** [comment]
Now I want to add one a middle point of one edge in one triangle and then split the triangle into two triangles. So I want to do as follows:
1) CGAL::add_vertex(Point,mesh);// middle point of one edge
2)CGAL::Euler::remove_face(Halfedge& h,mesh)
3)CGAL::Euler::add_face(VertexRange,mesh)
But step 2,some isolated vertex will be removed as well, so if I use the previous halfedge to search the vertex_index, maybe the halfedge has beed changed once I removed faces. So I would know more details how the indices of vertex,haifedge change

**Comment by MaelRL** [comment]
Have you considered using [CGAL::Euler::spit_edge()](https://doc.cgal.org/latest/BGL/group__PkgBGLEulerOperations.html#ga8a7629a2a0659ca059081eae8cedca3d) instead?

**Comment by tub-sgg** [comment]
yes,I have ever considered this function(CGAL::Euler::split_edge()), this function will split a vertex of the triangle essencially and insert an indentical vertex.But I need a new vertex which is the middle point of one edge

**Comment by MaelRL** [comment]
The new point is positioned at a vertex just as a place-holder, the user is expected to change it afterwards; something like:
```
        halfedge_descriptor hnew = Euler::split_edge(hedge, mesh);
        vertex_descriptor vnew = target(hnew, mesh);
        put(vpm, vnew, mid_point);
```

**Comment by tub-sgg** [comment]
thanks for your advice.So next step is to use CGAL::Euler:split_face() to split the triangle into small triangles?

**Comment by MaelRL** [comment]
Yes, possibly on both sides of the edge if the faces on both sides of the edge are real faces; something like:
```
        halfedge_descriptor hnew = Euler::split_edge(hedge, mesh);
        vertex_descriptor vnew = target(hnew, mesh);
        put(vpm, vnew, mid_point);
		if(!is_border(hnew, mesh))
          Euler::split_face(hnew, next(next(hnew, mesh), mesh), mesh);
        halfedge_descriptor opp_hnew = opposite(hnew, mesh);
		if(!is_border(opp_hnew, mesh))
          Euler::split_face(prev(opp_hnew, mesh), next(opp_hnew, mesh), mesh);
```

**Comment by tub-sgg** [comment]
thanks a lot.By the way, after I split the edge and move the new vertex to the middle location,  there are a lot of polygons(with 4 vertices),is this function [CGAL::Polygon_mesh_processing::triangulate_faces( mesh)](https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__meshing__grp.html#ga70d65044f8c7309c24ade88fa280124a) proper to get the same result? I would like to make it as fast as possilbe because  my mesh model contains more than 1 million faces

**Comment by MaelRL** [comment]
After `Euler::split_edge()`, the `Euler::split_face()` will be faster because you already known which faces need triangulating and how to triangulate them.

**Comment by tub-sgg** [comment]
By the way, the figure for [split_edge()](https://doc.cgal.org/latest/BGL/group__PkgBGLEulerOperations.html#gaa60aecdf1aa48b7b3609abddd3b4d38b)  seems somehow not correct? The res should be the opposite halfedge I think

**Comment by tub-sgg** [comment]
I mean the [split_vertex()](https://doc.cgal.org/latest/BGL/group__PkgBGLEulerOperations.html#gaa60aecdf1aa48b7b3609abddd3b4d38b)
