### ISSUE TITLE
Polygon_mesh_processing::parameters::choose_parameter has not been declared

### ISSUE THREAD

**Issue by copyme** [CGAL/cgal#5224]
## Issue Details

While trying to use `polygon_mesh_to_polygon_soup` I am getting the following errors:

```
/usr/include/CGAL/Polygon_mesh_processing/polygon_mesh_to_polygon_soup.h:80:21: error: ‘CGAL::Polygon_mesh_processing::parameters::choose_parameter’ has not been declared
   using parameters::choose_parameter;
                     ^~~~~~~~~~~~~~~~
/usr/include/CGAL/Polygon_mesh_processing/polygon_mesh_to_polygon_soup.h:81:21: error: ‘CGAL::Polygon_mesh_processing::parameters::get_parameter’ has not been declared
   using parameters::get_parameter;
```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Linux 64bits
* Compiler:
* Release or debug mode: (I only tried to compile in Debug)
* Specific flags used (if any): none
* CGAL version: 5.1.1
* Boost version: 1.66
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by MaelRL** [comment]
Thanks for the bug report. Can you please give it a try with #5228?

**Comment by lrineau** [comment]
Fixed by https://github.com/CGAL/cgal/pull/5228. Will be in CGAL-5.1.2 and CGAL-5.2.
