### ISSUE TITLE
Converting objects (ex: Polyhedron_3<>) from one kernel to the other.

### ISSUE THREAD

**Issue by ethiy** [CGAL/cgal#5243]
I am trying to convert a polyhedron using one kernel to another. The idea is to use exact kernels only if necessary. In the following example, I want to compute a minkowski sum which must be done with the `CGAL::Epeck` kernel. I do not want to make other computations with this kernel as it will be more slow.

## Issue Details

Is it possible to develop such a feature? If theoretically impossible, could you explain why?

## Example

```c++
CGAL::Polyhedron_3<EPECK> exact_shape(shape);
CGAL::Nef_polyhedron_3<EPECK> nef_shape(exact_shape);
auto offset_cube = make_cube(offset);
CGAL::Polyhedron_3<EPECK> exact_cube(offset_cube);
CGAL::Nef_polyhedron_3<EPECK> nef_cube_offset(exact_cube);
auto nef_result = CGAL::minkowski_sum_3(nef_shape, nef_cube_offset);
nef_result.convert_to_polyhedron(exact_shape);
CGAL::Polyhedron_3<Simple_Cartesian> shape_(exact_shape);
shape = shape_;
return shape;
```

The same works without the attempted conversion. The error message is: `no matching function for call to ‘CGAL::Polyhedron_3<CGAL::Epeck>::Polyhedron_3(CGAL::Polyhedron_3<Simple_Cartesian>&)’`

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): wsl2-ubuntu 20.04
* Compiler: gcc-9
* Release or debug mode: Debug
* Specific flags used (if any): "C++17"
* CGAL version: 5.0.2
* Boost version: 1.72 (from `conan`)
* Other libraries versions if used (Eigen, TBB, etc.): Catch2 (for tests)

**Comment by GilesBathgate** [comment]
http://www.cgal.org/Manual/latest/doc_html/cgal_manual/Kernel_23_ref/Class_Cartesian_converter.html
or
https://github.com/GilesBathgate/RapCAD/blob/MEPP-integration/contrib/Copy_polyhedron_to.h

**Comment by lrineau** [comment]
Giles' answer is a good one. That is nice to see users answering to users. :smiley:

You can also use [`CGAL::copy_face_graph`](https://doc.cgal.org/latest/BGL/group__PkgBGLHelperFct.html#ga2d3eb044bfe42eab566779ce32216c11). It converted point types from one kernel to another. See [that example](https://doc.cgal.org/latest/BGL/BGL_polyhedron_3_2copy_polyhedron_8cpp-example.html#a5), where it also converts from a face graph type to another.

**Comment by ethiy** [comment]
> 
> 
> Giles' answer is a good one. That is nice to see users answering to users. 😃
> 
> You can also use [`CGAL::copy_face_graph`](https://doc.cgal.org/latest/BGL/group__PkgBGLHelperFct.html#ga2d3eb044bfe42eab566779ce32216c11). It converted point types from one kernel to another. See [that example](https://doc.cgal.org/latest/BGL/BGL_polyhedron_3_2copy_polyhedron_8cpp-example.html#a5), where it also converts from a face graph type to another.

@lrineau this works very well, thanks!
