### ISSUE TITLE
How to open *.cgal type files？

### ISSUE THREAD

**Issue by SY524044272-python** [CGAL/cgal#5249]
I use `Surface_mesh_skeletonization/simple_mcfskel_sm_example.cpp` as example。 But I found that I cannot output the code in bold font normally。Cannot output normally from the sixth line。 can someone help me ? 

       Skeleton skeleton;
	CGAL::extract_mean_curvature_flow_skeleton(tmesh, skeleton);
	std::cout << "Number of vertices of the skeleton: " << boost::num_vertices(skeleton) << "\n";
	std::cout << "Number of edges of the skeleton: " << boost::num_edges(skeleton) << "\n";
	**// Output all the edges of the skeleton.
	std::ofstream output("skel-sm.cgal");
	for (Skeleton_edge e : CGAL::make_range(edges(skeleton)))
	{
		const Point& s = skeleton[source(e, skeleton)].point;
		const Point& t = skeleton[target(e, skeleton)].point;
		output << "2 " << s << " " << t << "\n";
	}
	output.close();
	// Output skeleton points and the corresponding surface points
	output.open("correspondance-sm.cgal");
	for (Skeleton_vertex v : CGAL::make_range(vertices(skeleton)))
		for (vertex_descriptor vd : skeleton[v].vertices)
			output << "2 " << skeleton[v].point << "  " << get(CGAL::vertex_point, tmesh, vd) << "\n";

**Comment by sloriot** [comment]
The CGAL polyhedron contained in the `demo/Polyhedron` shipped with a CGAL release can open those files. A precompiled version for windows is available [here](https://www.cgal.org/demo/5.1.1/polyhedron_3.zip) and requires some extra [dlls](https://www.cgal.org/demo/5.1.1/CGAL-demoDLLs.zip).

**Comment by SY524044272-python** [comment]
hello，Sebastien Loriot.When I run the program,the *. cgal file will be generated successfully under the current directory folder. I think the *. cgal file is an intermediate file and will not affect the program operation.
But the following lines of code are not working properly：
`for (Skeleton_edge e : CGAL::make_range(edges(skeleton)))
{
	const Point& s = skeleton[source(e, skeleton)].point;
	const Point& t = skeleton[target(e, skeleton)].point;
	output << "2 " << s << " " << t << "\n";
}`
I don't  understand why

**Comment by sloriot** [comment]
I don't understand your question. What did not work? The generation of the file or opening it in the demo? Did you generation program ended correctly?

**Comment by SY524044272-python** [comment]
Sorry, let me describe my problem again. First，the program can run normally, and output the results of the following two lines of code

```
std::cout << "Number of vertices of the skeleton: " << boost::num_vertices(skeleton) << "\n";
std::cout << "Number of edges of the skeleton: " << boost::num_edges(skeleton) << "\n";
```

**Comment by sloriot** [comment]
What is your question?

**Comment by SY524044272-python** [comment]
hello，Sebastien Loriot. I think I was a little confused just now. Now the program can run normally, and two cgal type files are generated.  

you know,I want to extract the skeleton from the model
![image](https://user-images.githubusercontent.com/58041339/101630425-d1227d00-3a5d-11eb-9958-8d3430153769.png)

**Comment by sloriot** [comment]
Use `polylines_io_plugin`  or change the extension of the file from `.cgal` to `.polylines.txt`

**Comment by SY524044272-python** [comment]
thank you, sloriot ! I think I have solved this question. By the way, I have another question. if I have a 3D model `Point（x,y,z）` but it is so thin that almost a two-dimensional shape. Can I use  `CGAL::extract_mean_curvature_flow_skeleton()` to extract the skeleton to instead 2D skeleton of this 3D model?

**Comment by sloriot** [comment]
I never tried but you should try and see what it does.
