### ISSUE TITLE
A question about the annotation in surface mesh simplification

### ISSUE THREAD

**Issue by KuribohG** [CGAL/cgal#5253]
In file Surface_mesh_simplification/internal/Edge_collapse.h, there are the following annotations:
```
  // (C) Insert ignored edges
  //
  // I think that this should be done for edges eliminated because of the geometric criteria
  // and not the topological one.However maintaining such a set might be more expensive
  // and hard to be safe ...
```

Imagine we have a 4-vertex mesh, name these vertices as A/B/C/D. D is in the triangle ABC geometrically, and the faces are ABD, BCD, ACD. For now we cannot collapse edge AB, because C is adjacent to both A and B, but ABC is not a facet. However, when we collapse CD first, AB no longer violates the link condition. So even the edges eliminated by topological criteria may need reinserting.

I want to know if these edges eliminated by topological criteria really need reinserting or I misunderstood the annotations.

**Comment by sloriot** [comment]
Basically, an edge is marked as collapsible if the edge verifies the link condition (see [this function](https://doc.cgal.org/latest/BGL/group__PkgBGLEulerOperations.html#ga8af4fd79178c66fef7091614c0bc4a01)). The link condition guarantees that at most 2 triangles will disappear when collapsing an edge, and at the same time that the topology of the mesh will not change. But it does not mean that if we were collapsing an edge not verifying the link condition (+updating correctly disappearing faces), the topology of the mesh would change. In the example below, collapsing the red edge would not change the topology of the mesh and it does not verify the link condition.
![ex](https://user-images.githubusercontent.com/1224632/101459560-b1456900-3938-11eb-965c-6dbfb8c6f0e3.png)

HTH

**Comment by KuribohG** [comment]
Thanks for your reply!

Sorry I didn't get your idea completely. I can't figure out why collapse the red edge will leave the topology unchanged. After collapsing, there will be a new edge which have three adjacent triangles, and make this mesh not a manifold anymore.

In these annotations, it seems we should split the reinsert pool into a geometrical one and a topological one. And we can simply ignore the topological one, not reinserting them. However I don't think use only the geometrical reason is enough for reinserting.

My opinion is that the link condition for an edge will change in the process of simplification (after several edge collapse). It may change from true to false, or false to true. I have no doubt about the code, but just the annotation. Because the link condition is dynamic, the reinsert pool must consider not only for geometrical reason but also topological one. Here in annotations, it says we could only consider the geometrical reason, which I can't figure out why it is correct.

**Comment by sloriot** [comment]
What I meant is that if you consider the point both connected to the endpoints of the red edge, it will gives you two triangle, one not being in the mesh as a face. But if you look at the union of faces making that triangles, you can see that it has the topology of a disk. So removing all those faces (what I called disappearing faces) you would have a manifold mesh with the same topology.
Anyway this was just an example illustrating the link condition is only a sufficient condition of non topology change and it can evolve for an edge after collapses.

For the algorithmic part, an edge will be checked for collapsibilility when at the top of the priority queue, and if it is not in the priority queue (discarded earlier due geometric or link condition) if a neighbor edge was collapsed.
