### ISSUE TITLE
CMake error when linking with Boost libraries

### ISSUE THREAD

**Issue by maximecharriere** [CGAL/cgal#5257]
## Issue Details

When I try to generate a Visual Studio project using CMake for the [examples of **Point_set_processing_3** package](https://github.com/CGAL/cgal/tree/master/Point_set_processing_3/examples/Point_set_processing_3), I got the following error:
```
CMake Error at CMakeLists.txt:97 (add_executable):
  Target "registration_with_pointmatcher" links to target "Boost::thread" but
  the target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
```
I got this error for 24 different `Boost::<library>` on examples :
- registration_with_pointmatcher
- registration_with_opengr_pointmatcher_pipeline

The project is still generated, so I launched it and compiled it with Visual Studio, but I got a lot of errors.

Does anyone know where the error may come from?

## Environment

* Operating system: **Windows 10, 64 bits**
* Compiler: **MSVC 14.2**
* Release or debug mode: **Release** 
* CGAL version: **5.1.1**
* Boost version: **1.74.0**
* Eigen version: **3.3.9**

**Comment by sloriot** [comment]
pointmatcher is using boost thread (amongst other boost libraries). @maxGimeno , I don't see openGR nor pointmatcher in the testsuite on a windows platform. Did I miss them?

**Comment by maxGimeno** [comment]
No, you didn't. No windows platform hase one of those.

**Comment by maximecharriere** [comment]
I just noticed that when I configure the Point_set_processing_3 project, the Cmake output tells me `Boost libraries:` without the path. So I set `Boost_LIBRARIES` to `C:\dev\boost_1_74_0\build\lib` but it doesn't change anything.

## Cmake output
```
Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.19041.
The C compiler identification is MSVC 19.28.29333.0
The CXX compiler identification is MSVC 19.28.29333.0
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe - skipped
Detecting C compile features
Detecting C compile features - done
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe - skipped
Detecting CXX compile features
Detecting CXX compile features - done
Visual Leak Detector (VLD) is not found.
Using header-only CGAL
Targetting Visual Studio 16 2019
Target build enviroment supports auto-linking
Using VC toolset 142.
Generator uses intermediate configuration directory: $(Configuration)
Boost include dirs: C:/dev/boost_1_74_0/build/include/boost-1_74
Boost libraries:    
USING DEBUG CXXFLAGS   = '/DWIN32 /D_WINDOWS /GR /EHsc /Zi /Ob0 /Od /RTC1'
USING DEBUG EXEFLAGS   = '/machine:x64 /debug /INCREMENTAL'
USING RELEASE CXXFLAGS = '/DWIN32 /D_WINDOWS /GR /EHsc /O2 /Ob2 /DNDEBUG'
USING RELEASE EXEFLAGS = '/machine:x64 /INCREMENTAL:NO'
Configuring done
```

**Comment by maxGimeno** [comment]
I don't think BOOST_LIBRARIES is really used, it is necessary to specify each lib one by one

**Comment by lrineau** [comment]
The `libpointmatcherConfig.cmake` shipped with `libpointmatcher` is not right: if `Boost::thread` is a dependency, then `libpointmatcherConfig.cmake` should search for it.

**Comment by maximecharriere** [comment]
Okay it was indeed `libpointmatcher` and `boost` that were problematic.
I thought that boost was header only, so I didn't build it. But [a few libraries need to be built](https://www.boost.org/doc/libs/1_74_0/more/getting_started/windows.html#header-only-libraries). Building boost solves the previous problems.

Now I still have many problems with `libpointmatcher` (this library is not really compatible with Windows) and `OpenGR`.
I oppened a [new issue](https://github.com/CGAL/cgal/issues/5262) for OpenGr. Sorry for the inconvenience.

**Comment by afabri** [comment]
Could we make pointmatcher independent of  `boost::thread`?
