### ISSUE TITLE
How to configure the CGAL environment manually instead of using CMake?

### ISSUE THREAD

**Issue by SY524044272-python** [CGAL/cgal#5259]
## Issue Details

I creat a CGAL project and add additional dependencies , library directories and include directories in VS2017 with my hands. Similarly, I  copy the  `dll` file to the project file.I am able to run most CGAL programs except for those examples that require Qt5 support.The following problems always occur
![image](https://user-images.githubusercontent.com/58041339/101728257-13e16500-3af1-11eb-84d2-94905d3fefe1.png)

At first I thought that Qt5 was not configured properly，but when I try to use CMake to compile `CGAL-5.0.2\examples`,expecially those require Qt5 support, It can run perfectly! It make me so confused. How can I fix it or use CMake ?

## Source Code

**Below are my configuration options**
**Additional Dependencies**
```
CGAL_Core-vc141-mt-gd-5.0.2.lib
CGAL_ImageIO-vc141-mt-gd-5.0.2.lib
CGAL-vc141-mt-gd-5.0.2.lib
libgmp-10.lib
libmpfr-4.lib
kernel32.lib
user32.lib
```
**Additional Library Directories**
```
D:\Library\CGAL-5.0.2\auxiliary\gmp\lib
D:\Library\CGAL-5.0.2\build\lib
D:\Library\boost_1_71_0\libs
```
 **Additional Include Directories**
```
D:\Library\boost_1_71_0
D:\Library\CGAL-5.0.2\include
D:\Library\CGAL-5.0.2\build\include
D:\Library\CGAL-5.0.2\auxiliary\gmp\include
```
DLLS

![image](https://user-images.githubusercontent.com/58041339/101734284-ff09cf00-3afa-11eb-81b1-839752a8ce5c.png)
![image](https://user-images.githubusercontent.com/58041339/101734354-1a74da00-3afb-11eb-941b-0d1d8fa38633.png)
The DLLS in second picture was given to me from Sebastien Loriot.
## Environment

* Operating system (Windows 64 bits):
* debug mode:
* CMake：cmake-3.15.7-win64-x64
* CGAL version: CGAL-5.0.2
* Boost version: boost_1_71_0-msvc-14.1-64
* Other libraries versions if used (Eigenc,it can work correctly):

**Comment by SY524044272-python** [comment]
this is my CMake,they are found correctly.
![image](https://user-images.githubusercontent.com/58041339/101736008-b3a4f000-3afd-11eb-9bee-719453a5519f.png)

**Comment by sloriot** [comment]
It is because `CGAL_USE_BASIC_VIEWER` is not defined.

At the cmake level you can do:
```
find_package(CGAL REQUIRED OPTIONAL_COMPONENTS Qt5)

if(CGAL_Qt5_FOUND)
  add_definitions(-DCGAL_USE_BASIC_VIEWER -DQT_NO_KEYWORDS)
  target_link_libraries(my_program PUBLIC CGAL::CGAL_Qt5)
endif()
```

**Comment by SY524044272-python** [comment]
> 这是因为`CGAL_USE_BASIC_VIEWER`未定义。
> 
> 在cmake级别，您可以执行以下操作：
> 
> ```
> find_package(CGAL REQUIRED OPTIONAL_COMPONENTS Qt5)
> 
> if(CGAL_Qt5_FOUND)
>   add_definitions(-DCGAL_USE_BASIC_VIEWER -DQT_NO_KEYWORDS)
>   target_link_libraries(my_program PUBLIC CGAL::CGAL_Qt5)
> endif()
> ```

thank you Sebastien Loriot.I think you must be the creater of CGAL .
