### ISSUE TITLE
Exception using corefine_and_compute_union

### ISSUE THREAD

**Issue by benlaurie** [CGAL/cgal#5264]
## Issue Details

I was trying to make a reproducer for an assertion failure:

CGAL error: assertion violation!
Expression : it_poly_hedge!=edge_to_hedge.end()
File       : //home/ben/local/include/CGAL/Polygon_mesh_processing/internal/Corefinement/Visitor.h
Line       : 1024

But I guess the process of dumping the objects to STL changed something and instead I get an exception here:

-> 932    throw Intersection_of_constraints_exception();

in Constrained_triangulation_2.h.

## Source Code

https://gist.github.com/benlaurie/bbc1b2602881ba000ff97f6b3ab30557

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): FreeBSD
* Compiler: clang
* Release or debug mode: release
* Specific flags used (if any):
* CGAL version: 5.0.3
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by sloriot** [comment]
bug2_2.stl has some self-intersections. As you can see on the attached screenshot it feature 2 connected components and some internal boundaries. This is due to point being very closed but not equal. Using the named parameter `throw_on_self_intersection(true)` for the corefine function would have indicated you the issue.
![image](https://user-images.githubusercontent.com/1224632/101877674-ae43b600-3b8e-11eb-8988-80dd0887d489.png)

There are several functions in CGAL to fix your input but they are not documented.
The easier is probably in `CGAL/Polygon_mesh_processing/internal/repair_extra.h`

```
std::vector< std::pair<halfedge_descriptor, halfedge_descriptor> > halfedges_to_stitch;
PMP::collect_close_stitchable_boundary_edges(sm, epsilon,
                                                  get(boost::vertex_point, sm),
                                                 halfedges_to_stitch);
PMP::stitch_borders(sm, halfedges_to_stitch);
```

epsilon being the distance threshold between two points to be considered as equal.

**Comment by benlaurie** [comment]
Thanks - not sure how that's happened, I generate that shape myself - will look into it.

What tool did you use to get that screenshot?

**Comment by sloriot** [comment]
The CGAL polyhedron demo available in demo/Polyhedron (precompiled version are also available on windows).

**Comment by benlaurie** [comment]
I'm a bit mystified by this - the shape generated uses the same points for the end caps as it does for the side walls (at least, it is *supposed* to) - it doesn't use the same vertex_descriptors, though - could that cause a problem?

**Comment by sloriot** [comment]
It's not a vertex descriptor issue. You are using STL so points with the same coordinates are associated to the same vertex by our reader.

**Comment by benlaurie** [comment]
I meant in the original shape which was used to generate the STL (which is a dump of a shape constructed using the same kernel as the example uses).

**Comment by benlaurie** [comment]
It turns out the answer to this is "yes", which I find a bit surprising.

That is, if I make a shape that shares identical Points but associating them to different vertices, I get errors, but if I make the same shape sharing vertices, it works fine.

I will try to make an example to illustrate this.

**Comment by Hearain323** [comment]
> bug2_2.stl has some self-intersections. As you can see on the attached screenshot it feature 2 connected components and some internal boundaries. This is due to points being very closed but not equal. Using the named parameter `throw_on_self_intersection(true)` for the corefine function would have indicated you the issue. ![image](https://user-images.githubusercontent.com/1224632/101877674-ae43b600-3b8e-11eb-8988-80dd0887d489.png)
> 
> There are several functions in CGAL to fix your input but they are not documented. The easiest is probably in `CGAL/Polygon_mesh_processing/internal/repair_extra.h`
> 
> ```
> std::vector< std::pair<halfedge_descriptor, halfedge_descriptor> > halfedges_to_stitch;
> PMP::collect_close_stitchable_boundary_edges(sm, epsilon,
>                                                   get(boost::vertex_point, sm),
>                                                  halfedges_to_stitch);
> PMP::stitch_borders(sm, halfedges_to_stitch);
> ```
> 
> epsilon being the distance threshold between two points to be considered as equal.

Hi sloriot

I am also stuck at self-intersection for quite a while. I tried to use the code you attached to remove the self-intersection by "combining" points with very small distance.  My issue is I dont know how to get the correct threshold which is "epsilon" in the function. I have tried different numbers but failed:

        Mesh3 mesh1;

        //read in mesh1 using _read_polygon_mesh_

	_std::vector< std::pair<halfedge_descriptor, halfedge_descriptor> > halfedges_to_stitch;
	PMP::collect_close_stitchable_boundary_edges(mesh1, 0.01,
		get(boost::vertex_point, mesh1),
		halfedges_to_stitch);

	std::cout << "stitchable boundary edge size: " << halfedges_to_stitch.size() << endl;

	PMP::stitch_borders(mesh1, halfedges_to_stitch);_

It always print out 0 for the size of halfedges_to_stitch

Could you please advise on this? Thank you very much!!!
[28transformed.zip](https://github.com/CGAL/cgal/files/7806657/28transformed.zip)

**Comment by loryhndol** [comment]
maybe the parameter is chosen empirically depending on your dataset?
