### ISSUE TITLE
Could I set 'd' as dense matrix?

### ISSUE THREAD

**Issue by zed654** [CGAL/cgal#5265]
when write d as `set_d()`, now it work only diagonal shape.

How can i reform this shape like
```
d = 
[
    1.0037   -0.9975    0.0014    0.0005    0
   -0.9975    2.0018   -0.9989    0.0004    0
    0.0014   -0.9989    2.0007   -0.9997    0
    0.0005    0.0004   -0.9997    2.0001   -1.0000
         0         0         0   -1.0000    1.0000
]
```
I want solve this equation, `0.5 X' d X + cX + c0`

and, why this method is not working?
```
qp.set_d(0,0,1); qp.set_d(0,1,1); qp.set_d(0,2,0);
qp.set_d(1,0,1); qp.set_d(1,1,1); qp.set_d(1,2,0);
qp.set_d(2,0,1); qp.set_d(2,1,1); qp.set_d(2,2,1);
```

**Comment by sloriot** [comment]
Could you please add more context?

**Comment by zed654** [comment]
The equation what I want to solve is like that
0.5 X' [ 1 1 0; 1 1 0; 1 1 1] X + cX + c0.
I want to know how to do this as c language.

**Comment by MaelRL** [comment]
What do you mean by "it doesn't not work"?

`set_d(i, j)` should also only be used with `j <= i`, see [its documentation](https://doc.cgal.org/latest/QP_solver/classCGAL_1_1Quadratic__program.html#a2b598d11d1d6daff9d20e43dc586257d).

**Comment by zed654** [comment]
> I add more context, please save me--!



> What do you mean by "it doesn't not work"?
> 
> `set_d(i, j)` should also only be used with `j <= i`, see [its documentation](https://doc.cgal.org/latest/QP_solver/classCGAL_1_1Quadratic__program.html#a2b598d11d1d6daff9d20e43dc586257d).

Thanks you!

If i wanna do this, should I use other library...?

**Comment by MaelRL** [comment]
What I meant was that `D` can be a dense matrix, but since it is symmetrical, calling it with `j > i` is pointless.

What is your error?

**Comment by zed654** [comment]
> What I meant was that `D` can be a dense matrix, but since it is symmetrical, calling it with `j > i` is pointless.
> 
> What is your error?

My 'd'  is like that

d = 
[
    1.0037   -0.9975    0.0014    0.0005    0
   -0.9975    2.0018   -0.9989    0.0004    0
    0.0014   -0.9989    2.0007   -0.9997    0
    0.0005    0.0004   -0.9997    2.0001   -1.0000
         0         0         0   -1.0000    1.0000
]

It's not symmetrical.

How can i operate the solver by using this 'd'?

( And, the error what i saw is ' j > i' )

**Comment by MaelRL** [comment]
The matrix you gave _is_ symmetric.

Just fill the coefficients `(i,j)`, with `j <= i` and the other ones will be set up automatically.

Important: `set_d()` actually sets the coefficients of the matrix `2 * D` with `D` in the formulation at the top of [the doc](https://doc.cgal.org/latest/QP_solver/index.html).

**Comment by zed654** [comment]
> The matrix you gave _is_ symmetric.
> 
> Just fill the coefficients `(i,j)`, with `j <= i` and the other ones will be set up automatically.
> 
> Important: `set_d()` actually sets the coefficients of the matrix `2 * D` with `D` in the formulation at the top of [the doc](https://doc.cgal.org/latest/QP_solver/index.html).

Oh.. Thanks..
But, the result is not equal to MATLAB quadpog.

My d, c, c0, a, b is like that

d = 
[
    1.0020   -0.9986    0.0009    0.0003         0
   -0.9986    2.0012   -0.9993    0.0003         0
    0.0009   -0.9993    2.0005   -0.9998         0
    0.0003    0.0003   -0.9998    2.0001   -1.0000
         0         0         0   -1.0000    1.0000
]

c
=
[
    0.0726
    0.0482
    0.0270
    0.0102
         0
]

c0 = 0

a_trans
=
[
1.0000         0         0         0         0
         0    1.0000         0         0         0
         0         0    1.0000         0         0
         0         0         0    1.0000         0
         0         0         0         0    1.0000
   -1.0000         0         0         0         0
         0   -1.0000         0         0         0
         0         0   -1.0000         0         0
         0         0         0   -1.0000         0
         0         0         0         0   -1.0000
         0         0         0         0         0
         0         0         0         0         0
    0.0102         0         0         0         0
    0.0061         0         0         0         0
    0.0168    0.0102         0         0         0
    0.0103    0.0061         0         0         0
    0.0213    0.0168    0.0102         0         0
    0.0130    0.0103    0.0061         0         0
    0.0244    0.0213    0.0168    0.0102         0
    0.0149    0.0130    0.0103    0.0061         0
         0         0         0         0         0
         0         0         0         0         0
   -0.0102         0         0         0         0
   -0.0061         0         0         0         0
   -0.0168   -0.0102         0         0         0
   -0.0103   -0.0061         0         0         0
   -0.0213   -0.0168   -0.0102         0         0
   -0.0130   -0.0103   -0.0061         0         0
   -0.0244   -0.0213   -0.0168   -0.0102         0
   -0.0149   -0.0130   -0.0103   -0.0061         0
]

b
=
[
0.5236
    0.5236
    0.5236
    0.5236
    0.5236
    0.5236
    0.5236
    0.5236
    0.5236
    0.5236
   99.0000
  100.0000
   99.0000
  100.0000
   99.0000
  100.0000
   99.0000
  100.0000
   99.0000
  100.0000
  101.0000
  100.0000
  101.0000
  100.0000
  101.0000
  100.0000
  101.0000
  100.0000
  101.0000
  100.0000
]


As a result of MATLAB quadprog, the output should be 
[
   -0.5236
   -0.5236
   -0.5236
   -0.5236
   -0.5236
]
.

But, when I operate it on CGAL, the output is like that

**Comment by MaelRL** [comment]
The matrix `A` is an `m x n` matrix, with `m` the number of constraints and `n` the number of variables. With your `set_a`, the matrix is an `n x m` matrix. 

Note that the function [`set_a()`](https://doc.cgal.org/latest/QP_solver/classCGAL_1_1Quadratic__program.html#a32c7376751bea8eceeeb2276ebc93225) have signature `set_a(j; i)` to write the coefficient `A(i, j)`.
