### ISSUE TITLE
NOTICE: The example draw_triangulation_2 requires Qt and will not be compiled.

### ISSUE THREAD

**Issue by jamesben6688** [CGAL/cgal#5267]
## Issue Details
Cmake cannot find qt5.

_Describe your issue. Please be specific (compilation error, runtime error, unexpected behavior, wrong results, etc.)._

I installed qt5, cgal with vcpkg and specified the qt5_dir in cmake:
![QQ截图20201211170706](https://user-images.githubusercontent.com/11385453/101959511-7743c380-3bd3-11eb-8cdb-01f26436f55e.png)

It seems that cmake find the qt related path, but CGAL_Qt5_FOUND still returns false.

## Environment

* Operating system (Windows 10/64 bits):
* Compiler: visual studio 2019
* Specific flags used (if any):
* CGAL version: 5.1
* Boost version: 1.72.0

**Comment by jamesben6688** [comment]
It seems that CGAL/QT/GraphicsItem.h does not exist. How to fix it?

**Comment by jamesben6688** [comment]
I finally solved it by reinstalling cgal using `vcpkg install cgal[qt]:x64-windows --recurse` instead of `vcpkg install cgal:x64-windows`

**Comment by SenyangJiang** [comment]
thank you! I reinstalled the cgal library and it solved the CGAL_Qt5_FOUND problem for me as well.
