### ISSUE TITLE
Remove workarounds for old gcc

### ISSUE THREAD

**Issue by mglisse** [CGAL/cgal#5273]
## Issue Details

cgal only supports gcc 6.3 or later, but the code still contain many tests like
```c++
#if (__GNUC__>4) || (__GNUC__ == 4 && __GNUC_MINOR__ >=6)
#if defined(BOOST_GCC) && (__GNUC__ <= 4) && (__GNUC_MINOR__ < 4)
(__GNUC__ * 100 + __GNUC_MINOR__) >= 408
#if ((__GNUC__ < 3) || ((__GNUC__ == 3) && (__GNUC_MINOR__ <= 2)))
defined(__GNUC__) && (__GNUC__ == 3 ) && (__GNUC_MINOR__ == 4)
```
etc.
This looks like a nice and simple clean-up. One slight thing to be aware of is that clang still identifies itself as gcc-4.2, but most likely if it gets caught in some of those tests it is by accident and shouldn't be, or if it needs to be then `__llvm__` looks like a better test.

**Comment by GilesBathgate** [comment]
A nice commandline to do this:
`grep __GNUC__ * -Rl | xargs unifdef -D__GNUC__=6 -D__GNUC_MINOR__=3 -m`

**Comment by lrineau** [comment]
@sloriot You have done a bit of cleanup, in a recent pull-request. Do you think this issue is solved, now?

**Comment by sloriot** [comment]
No but just did. Only two files were affected.
