### ISSUE TITLE
Point to tetrahedron distance

### ISSUE THREAD

**Issue by jjcasmar** [CGAL/cgal#5291]
CGAL doesn't contain a squared_distance for tetrahedron and point. I needed this and I implemented by checking if the point is inside the tetrahedron and by computing the distance to the 4 triangles that define the boundary. 

Would you be interested in adding this into CGAL? Right now is in my own codebase, but I could clean it and add it to CGAL.

**Comment by sloriot** [comment]
Is it a distance to the surface or to the volume (i.e. 0 inside?). This addition would fit well into the lib so a contribution would be welcome. Note that since it is an addition to the Kernel package, a CLA will be probably needed.

**Comment by MaelRL** [comment]
Bump @jjcasmar

**Comment by jjcasmar** [comment]
AFAIK, a patch with a solution for this was already merged
