### ISSUE TITLE
Fix frequent Boost warnings about bind.hpp and function_output_iterator.hpp

### ISSUE THREAD

**Issue by joachim-reichel** [CGAL/cgal#5303]
Compiling the demos/examples with Boost 1.74.0 creates a huge number of new warnings (the number at the start of each line denotes the count):

```
    274 /usr/include/boost/bind.hpp:36:1: note: ‘#pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.’
    210 /usr/include/boost/function_output_iterator.hpp:14:1: note: ‘#pragma message: This header is deprecated. Use <boost/iterator/function_output_iterator.hpp> instead.’
```
While at it, getting rid of this (older) warning might be nice too:

```
      4 /usr/include/boost/timer.hpp:21:1: note: ‘#pragma message: This header is deprecated. Use the facilities in <boost/timer/timer.hpp> instead.’
```

Not sure when the replacement headers got introduced. Fixing this might require bumping the minimum supported Boost version.

* Operating system (Windows/Mac/Linux, 32/64 bits): Linux, x86_64
* Compiler: GCC 10.2.1
* Release or debug mode: Release
* CGAL version: 5.2
* Boost version: 1.74.0

**Comment by afabri** [comment]
`function_output_iterator` moved starting from [66_0](https://www.boost.org/doc/libs/1_66_0/boost/function_output_iterator.hpp)

**Comment by afabri** [comment]
@sloriot what shall we do for `boost::bind`?  Doing what the warning says, or replacing it with `std::bind`  or with lambdas?
It can for example be found in the [`ch_bykat_impl.h`](https://github.com/CGAL/cgal/blob/master/Convex_hull_2/include/CGAL/Convex_hull_2/ch_bykat_impl.h#L80)

**Comment by afabri** [comment]
As for the boost timer, it is not in headers but in the `Minkowski_sum_2` examples and test cpps
