### ISSUE TITLE
Can I manually create and initialize an object of class named "Efficient_ransac::Plane_range" ?

### ISSUE THREAD

**Issue by leelele-cug** [CGAL/cgal#5305]
## Issue Details(Help wanted)

In [this shape detection example](https://doc.cgal.org/latest/Point_set_processing_3/Point_set_processing_3_2structuring_example_8cpp-example.html) of CGAL's doc, 
one of `CGAL::structure_point_set()`'s input parameters is `Efficient_ransac::Plane_range planes`  , which is a result of `ransac.planes()` .

### My Problem is : 
If I already have the points and normals of required planes(stored in STL vector), can I manually create and initialize this input parameter of  `CGAL::structure_point_set()` rather than get it from `ransac.planes()`?

I have try to find its constructor function in CGAL's source code, but failed. I also have read the doc, Google about it, still cannot find solution. That's would be GREAT if anyone can help!

THANKS!

## Source Code

Here is the relative part of CGAL's example code:
```
  // Shape detection
  Efficient_ransac ransac;
  ransac.set_input(points);
  ransac.add_shape_factory<Plane>();
  ransac.detect();
  Efficient_ransac::Plane_range planes = ransac.planes();
  Pwn_vector structured_pts;
  CGAL::structure_point_set (points,
                             planes,
                             std::back_inserter (structured_pts),
                             0.015, // epsilon for structuring points
                             CGAL::parameters::point_map (Point_map()).
                             normal_map (Normal_map()).
                             plane_map (CGAL::Shape_detection::Plane_map<Traits>()).
                             plane_index_map (CGAL::Shape_detection::Point_to_shape_index_map<Traits>(points, planes)));
```

**Comment by sgiraudot** [comment]
Indeed, you don't have to use RANSAC if you don't want to: as state in [the documentation of `CGAL::structure_point_set()`](https://doc.cgal.org/latest/Point_set_processing_3/group__PkgPointSetProcessing3Algorithms.html#gaebbc04909dfd575a94f932c8d3bacdce), the _planes_ parameter is just required to be a range of planes: you can, for example, pass a `std::vector<Kernel::Plane_3>` as a parameter (in which case you can also remove the `plane_map()` named parameter, as the default - identity map to `Plane_3` - will work well).

**Comment by leelele-cug** [comment]
> Indeed, you don't have to use RANSAC if you don't want to: as state in [the documentation of `CGAL::structure_point_set()`](https://doc.cgal.org/latest/Point_set_processing_3/group__PkgPointSetProcessing3Algorithms.html#gaebbc04909dfd575a94f932c8d3bacdce), the _planes_ parameter is just required to be a range of planes: you can, for example, pass a `std::vector<Kernel::Plane_3>` as a parameter (in which case you can also remove the `plane_map()` named parameter, as the default - identity map to `Plane_3` - will work well).

Thank you for your patience. That is very helpful !
