### ISSUE TITLE
Problem reading some .off files

### ISSUE THREAD

**Issue by pauljurczak** [CGAL/cgal#5306]
## Issue Details

Problem reading some `.off` files, which are readable by MeshLab and Open3D. Sample file
[dresser_0228.zip](https://github.com/CGAL/cgal/files/5744871/dresser_0228.zip) from ModelNet10 is attached.

## Source Code

This code snippet reads most, but fails on some ModelNet10 files:
```
  for (recursive_directory_iterator i("/home/paul/data/ModelNet10/dresser/test"), end; i != end; i++)
    if (!is_directory(i->path())) {
      Mesh     mesh;
      ifstream file(i->path().native());
      print("{} -- ", file.good());
      file >> mesh;
      print("{} vertices in {} -- {}\n", mesh.num_vertices(), i->path().filename(), file.good());
    }
```
producing:
```
...
true -- 0 vertices in "dresser_0228.off" -- false
true -- 1452 vertices in "dresser_0260.off" -- true
true -- 1096 vertices in "dresser_0215.off" -- true
...
```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Ubuntu 18.04.5 64-bit
* Compiler: gcc-10.1.0, clang-11.0.1
* Release or debug mode: release
* Specific flags used (if any):
* CGAL version: 5.2
* Boost version: 1.65, 1.75
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by maxGimeno** [comment]
The faces are not oriented correctly, so it cannot be read in a polygon mesh. This model should first be loaded in a polygon soup, then oriented with [PMP:::Orient_polygon_soup](https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__orientation__grp.html#gaadc5bac3072b11d2313e40043c729d0a)
You can see [this example](https://doc.cgal.org/latest/Polygon_mesh_processing/Polygon_mesh_processing_2orient_polygon_soup_example_8cpp-example.html#a2)
