### ISSUE TITLE
CMAKE_CXX_STANDARD in our CMakeLists

### ISSUE THREAD

**Issue by maxGimeno** [CGAL/cgal#5311]
## Issue Details
In some of our CMakeLists, we use 
`set(CMAKE_CXX_STANDARD 14)` or `set(CMAKE_CXX_STANDARD 11)`

It seems to me like an error. Instead we should test if the required features are present and disable the configuration if not. 
A more concrete side-effect is the warning D9025 that appears when using a flag like /std:c++latest:

`Command line warning D9025 : overriding '/std:c++latest' with '/std:c++14'`

It seems to me that we should remove these cmake commands, especially since we require c++14 since 5.0 (IIRC), 
but as we are currently ignoring those warning in our testsuite, I fear there were a reason to keep them.
@CGAL/geometryfactory any opinion ?

**Comment by sgiraudot** [comment]
For the C++11 in `Shape_detection`, I'm pretty sure this goes back to CGAL 4, before we generalize C++14, so I think it can be safely removed now that CGAL enforces C++14 (@danston can you confirm? You're the one who introduced the line, probably during the Region Growing feature submission).

**Comment by danston** [comment]
True. For `Shape_detection`, they are not anymore necessary. In general, I think the idea of testing if all the required features are present and disabling otherwise is a cleaner solution.

**Comment by lrineau** [comment]
I agree those CMake commands should be removed.
