### ISSUE TITLE
Nef_2:  misleading-indentation

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#5312]
## Issue Details

In [this testsuite](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.2.1-I-65/Nef_2/TestReport_lrineau_Ubuntu-GCC_master_CXX20-Release.gz)  we get a warning about misleading indentation for [this line](https://github.com/CGAL/cgal/blob/master/Nef_2/include/CGAL/Nef_2/debug.h#L55).   We don't need a `flush`  after an `endl`, and I can't imagine that we need it if we are not in the `if`.  So something is wrong here.

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Linux
* Compiler: gcc

**Comment by lrineau** [comment]
And `flush` is useless on `std::cerr`, because it is flushed at every operation on it: https://en.cppreference.com/w/cpp/io/cerr.

I suggest we remove the two lines with `std::flush`.
