### ISSUE TITLE
compile openGR and  pointmatch wrapper

### ISSUE THREAD

**Issue by 821736960** [CGAL/cgal#5315]
Sorry to bother you.
## Issue Details
I have installed CGAL 5.1.1 through **vcpkg**  and compiled the example: CGAL-5.0.2-examples-Surface_mesh with Cmake and run it successfully.

My aim is to use **OpenGR** and Pointmacher wrapper in CGAl to register point clouds gbobally. So I try to compile the example: Point_set_processing_3.
But a compilation error raises.

Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.18363.
Visual Leak Detector (VLD) is not found.
Using header-only CGAL
Targetting Visual Studio 15 2017
Target build enviroment supports auto-linking
Using VC toolset 141.
Generator uses intermediate configuration directory: $(Configuration)
Boost include dirs: E:/vcpkg/installed/x64-windows/include
Boost libraries:    
USING DEBUG CXXFLAGS   = '/DWIN32 /D_WINDOWS /GR /EHsc /Zi /Ob0 /Od /RTC1'
USING DEBUG EXEFLAGS   = '/machine:x64 /debug /INCREMENTAL'
USING RELEASE CXXFLAGS = '/DWIN32 /D_WINDOWS /GR /EHsc /O2 /Ob2 /DNDEBUG'
USING RELEASE EXEFLAGS = '/machine:x64 /INCREMENTAL:NO'
NOTICE : the LAS reader test requires LASlib and will not be compiled.
CMake Deprecation Warning at E:/vcpkg/installed/x64-windows/share/cgal/UseEigen3.cmake:11 (message):
  This file UseEigen.cmake is deprecated, and the imported target
  `CGAL::Eigen_support` from CGAL_Eigen_support.cmake should be used instead.
Call Stack (most recent call first):
  CMakeLists.txt:76 (include)

Configuring done

I know this is because OpenGR and Eign are **Optional Third Party Libraries** so they are not installed when I install CGAL.

The problem is, I dont quite understand the instructions on the web :
**In order to use Eigen in CGAL programs, the executables should be linked with the CMake imported target CGAL::Eigen_support provided in CGAL_Eigen_support.cmake.**
 **In order to use OpenGR in CGAL programs, the executables should be linked with the CMake imported target CGAL::OpenGR_support provided in CGAL_OpenGR_support.cmake.**

What does it mean? What should I do when compile the example in Cmake?

## Source Code

 error when compile the example: Point_set_processing_3.

## Environment

* Operating system (Windows/64 bits):
* Compiler: VS 2017, Cmake
* CGAL version: 5.1.1

Thanks

**Comment by sgiraudot** [comment]
You shouldn't mix versions of CGAL: the OpenGR wrapper is not available on CGAL 5.0, only in CGAL 5.1 (so the related example won't be in CGAL 5.0 either).

Once you use 5.1, you should install first OpenGR and libpointmatcher (see their respective `README` for instructions).

What we mean by "linking the program with", is that in the case where you create a `CMakeLists.txt` yourself, when adding an executable for which you want to use CGAL with OpenGR (or Eigen, or whatever), you need to do `target_link_library(your_executable CGAL::Eigen_support)`. Of course, if you just want to compile the provided examples, then the `CMakeLists.txt` provided is already filled with these, and you don't need to edit anything, just run `cmake`.

**Comment by 821736960** [comment]
Thanks for you apply.
Now I  installed CGAL 5.1.1 through vcpkg and use the example: CGAL-5.1.2 examples as you said. I try to compile the example: Point_set_processing_3 again. The following error appears: 
##
NOTICE : the LAS reader test requires LASlib and will not be compiled.
NOTICE : the registration_with_pointmatcher test requires libpointmatcher and will not be compiled.
NOTICE : registration_with_OpenGR requires OpenGR, and will not be compiled.
NOTICE : registration_with_opengr_pointmatcher_pipeline requires libpointmatcher and OpenGR, and will not be compiled.
## and OpenGR_DIR-NOTFOUND in Cmake gui.
Does it means if I want to use openGr-Super4pcs in CGAl-5.1, I must install the OpenGr respectivly following its github page  before compile Point_set_processing_3?
Besides, Does CGAl-5.2 have OpenGR module so that I dont need to install OpenGR respectivly? 
Thanks again.

**Comment by sgiraudot** [comment]
Yes, you do need to install OpenGR, CGAL does not include OpenGR, it just provides wrappers for it.

**Comment by 821736960** [comment]
> Yes, you do need to install OpenGR, CGAL does not include OpenGR, it just provides wrappers for it.

It seems that I have compile and install OpenGR on my computer.

Now I got three OpenGRConfig.cmake files, which are
E:\OpenGR\build\OpenGRConfig.cmake,
E:\OpenGR\build\generated\OpenGRConfig.cmake
E:\OpenGR\build\install\lib\cmake\opengr\OpenGRConfig.cmake

So which one should I link to OpenGR_DIR(at cmake-gui) when compile CGAL-5.1.2\examples\Point_set_processing_3?

I tried all of them. Two of them can compile successfully. But when I open the project: registration_with_OpenGR in VS2019 and build it. It says

Error: cannot read file E:/CGAL-5.1.2-examples/CGAL-5.1.2/examples/Point_set_processing_3/data/hippo1.ply

While other projects which dont need OpenGR can run well.

**Comment by sgiraudot** [comment]
Thanks for the report, it seems the `std::ios::binary` tag required by Windows to open binary files was missing. I just submitted a fix: https://github.com/CGAL/cgal/pull/5323

You should be able to make it work by using this fix (you can simply add the `std::ios::binary` tag at the 2 lines were a `std::ifstream` is opened in the example).

**Comment by 821736960** [comment]
> Thanks for the report, it seems the `std::ios::binary` tag required by Windows to open binary files was missing. I just submitted a fix: #5323
> 
> You should be able to make it work by using this fix (you can simply add the `std::ios::binary` tag at the 2 lines were a `std::ifstream` is opened in the example).

Thanks, what about the structuring_example in CGAL-5.1.2-examples-Point_set_processing_3 , It also says : Error: cannot read file cube.pwn
