### ISSUE TITLE
benchmark/Triangulation/Td_vs_T2_and_T3.cpp doesn't compile

### ISSUE THREAD

**Issue by mglisse** [CGAL/cgal#5316]
## Issue Details

> Td_vs_T2_and_T3.cpp:9:10: fatal error: CGAL/Regular_triangulation_euclidean_traits_2.h: No such file or directory

It looks like this file wasn't updated. Are benchmarks excluded from the testsuite?

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): linux x86_64
* Compiler: gcc-10
* CGAL version: master

**Comment by sloriot** [comment]
Benchmarks are indeed excluded from the testsuite.
