### ISSUE TITLE
Documentation scripts should use Python 3

### ISSUE THREAD

**Issue by sgiraudot** [CGAL/cgal#5320]
## Issue Details

Some scripts used to generate documentation (and maybe others, I haven't checked) still use Python 2 (for example [html_output_post_processing.py](https://github.com/CGAL/cgal/blob/master/Documentation/doc/scripts/html_output_post_processing.py)). The support for Python 2 ended last year and some recent OS (like the latest versions of Ubuntu and Linux Mint) stopped providing `pip` for Python 2, which makes compiling the doc tedious on such OS. This will become a common problem in the medium term.

I have no idea how hard it would be to translate these scripts to Python 3, but we'll have to do it in a near future.

**Comment by sloriot** [comment]
Scripts are working with python3. Python is detected by cmake so if you have both on your machine, python2 will be favored. You can update that so that v3 is favored.
