### ISSUE TITLE
Compilation issues with custom kernels

### ISSUE THREAD

**Issue by dpellegr** [CGAL/cgal#5322]
I am on CGAL v5.2 and I would like to experiment with custom kernels. However I am having issues compiling this toy program:

    #include <fstream>

    #include <CGAL/Surface_mesh.h>
    #include <CGAL/Polygon_mesh_processing/corefinement.h>

    #ifdef NO_CORE
      #include <CGAL/Exact_predicates_exact_constructions_kernel.h>
      using K = CGAL::Exact_predicates_exact_constructions_kernel;
    #else
      #include <CGAL/CORE_Expr.h>
      #include <CGAL/Cartesian.h>
      using K = CGAL::Cartesian<CORE::Expr>;
    #endif

    using Mesh = CGAL::Surface_mesh<K::Point_3>;

    #include "aux.h"

    int main() {
      Mesh m1 = Cube({1,1,1});
      Mesh m2 = Translate({0.5,0.5,0.5}) * Cube({1,1,1});
      Mesh m3;
      CGAL::Polygon_mesh_processing::corefine_and_compute_union(m1, m2, m3);
      std::ofstream f("cubes.off");
      f << m3;
      return 0;
    }

The functions used in the main are defined in `aux.h`:

    #include <vector>

    Mesh Polyhedron(const std::vector<K::Point_3> & vs, const std::vector<std::vector<size_t>> & fs) {
      Mesh res;
      std::vector<Mesh::vertex_index> vertices{};
      for ( const auto & v: vs) {
        vertices.push_back(res.add_vertex(v));
      }

      for (const auto & f: fs) {
        std::vector<Mesh::vertex_index> face{};
        for (const auto & i: f) {
          face.push_back(vertices[i]);
        }
        res.add_face(face);
      }
      return res;
    }

    Mesh Cube(const K::Point_3 & p) {
      return Polyhedron( 
        {
          {    0,      0,  p.z()},
          {p.x(),      0,  p.z()},
          {p.x(),  p.y(),  p.z()},
          {    0,  p.y(),  p.z()},
          {    0,      0,      0},
          {p.x(),      0,      0},
          {p.x(),  p.y(),      0},
          {    0,  p.y(),      0}
        },
        {
          {0,1,2}, {0,2,3},
          {7,6,5}, {7,5,4},
          {0,4,5}, {0,5,1},
          {1,5,6}, {1,6,2},
          {2,6,7}, {2,7,3},
          {3,7,4}, {3,4,0}
        }
      );
    }

    struct Transformation: K::Aff_transformation_3 {
      using K::Aff_transformation_3::Aff_transformation_3;

      Mesh& operator()(Mesh& m) const {
        for (const auto & v: m.vertices()) {
          m.point(v) = transform(m.point(v));
        }
        return m;
      }
      Mesh operator()(Mesh&& m) const {
        return this->operator()(m);
      }
    };
    Mesh operator*(const Transformation & t, Mesh m) { return t(m); }

    Transformation Translate( const K::Vector_3 & v) { return Transformation(CGAL::Translation(), v); }

The program can be compiled with:

    g++ -DNO_CORE test.cpp -lCGAL -lgmp -lmpfr

and will work fine, but omitting `-DNO_CORE` so that it will use `Cartesian<CORE_Expr>` instead of `Epeck` I am getting multiple compiler errors.

The first seems to be related to a faulty selection of a template specialization in `CGAL/Polygon_mesh_processing/internal/Corefinement/intersection_impl.h:365:25`

Then there is a whole class of errors associated with `CGAL/Lazy.h`

Am I doing it wrong?

**Comment by sloriot** [comment]
It was a mistake fixed in #5330. Note that I won't recommend using this Kernel if you want to get reasonable runtime. Are you an openSCAD developer?

**Comment by dpellegr** [comment]
> It was a mistake fixed in #5330. 
Great thanks!

> Are you an openSCAD developer?
A pretty advanced user, but not really a developer. Having encountered its limitations so many times I got curious about trying some different approaches.

**Comment by pentacular** [comment]
Just from curiosity -- what will make the biggest performance impact on corefinement with the cartesian kernel?

Is it due to laziness or something else?

**Comment by sloriot** [comment]
If you use a plain Cartesian kernel, you will require an exact number type so that predicates and constructions are exact. If you use EPECK, you will have a kernel that has both exact predicates and exact constructions + you will benefit from the filtering of the evaluation of predicates and of constructions (the laziness). If you want to stick to double, you can even use EPICK as this particular function will handle constructions internally with EPECK to be robust.

**Comment by lrineau** [comment]
Fixed by https://github.com/CGAL/cgal/pull/5330.
