### ISSUE TITLE
Does CGAL provide conforming tetrahedralization?

### ISSUE THREAD

**Issue by Yixin-Hu** [CGAL/cgal#5327]
Hi,

I wonder if CGAL provides conforming tetrahedralization that takes as input triangles and preserve the triangles exactly in the output. If so, could you please point me to the documentation?

Thanks!

**Comment by lrineau** [comment]
Hi @Yixin-Hu, CGAL does not have that functionality for the moment. There has been work in the past, but that gave experimental code that was not fully functional at the moment. That is still something the CGAL project is willing to work on, though.
