### ISSUE TITLE
I can't run the example of the method “Triangulated Surface Mesh Shortest Paths”

### ISSUE THREAD

**Issue by flagwind11** [CGAL/cgal#5328]
I have installed CGAL 5.1.2 as the "Getting Started" page has said. It is OK to run the CGAL "Hello, world!" example. Unfortunately, I got a lot of error reports when I copy and run the first "Triangulated Surface Mesh Shortest Paths" example program as it is in this page(https://doc.cgal.org/5.1.2/Surface_mesh_shortest_path/index.html#Chapter_Surface_mesh_shortest_path). 
Those errors are variable and it's impossible to paste all of them here. Here are several of them. 

E0519	type "CGAL::Surface_mesh_shortest_path" 不能包含模板参数列表	CGAL_functions C:\dev\boost_1_71_0\boost\graph\properties.hpp	12		
E0135	class "boost::graph_traits<Triangle_mesh>" 没有成员 "face_iterator"	CGAL_functions C:\dev\boost_1_71_0\boost\graph\properties.hpp	16		
E0070	不允许使用不完整的类型	CGAL_functions	H:\WYLearningfile\PROGRAM\VS\CGAL_functions\CGAL_functions.cpp	18		
E0065	应输入“;”	CGAL_functions	C:\dev\CGAL-5.1.2\include\CGAL\boost\graph\internal\initialized_index_maps_helpers.h	215	
E0349	没有与这些操作数匹配的 ">>" 运算符	CGAL_functions	C:\dev\boost_1_71_0\boost\graph\properties.hpp	23		
	
etc.

Actually, I doubt it that the problem is because of the version of this example code. Is it programed in an older version of VC++?If it is, how can I use this method properly? If it isn't, please point out the problem that causes this mess. Thanks! 

## Source Code
```
#include <cstdlib>
#include <iostream>
#include <fstream>
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/Random.h>
#include <CGAL/Surface_mesh.h>
#include <CGAL/Surface_mesh_shortest_path.h>
#include <boost/lexical_cast.hpp>
typedef CGAL::Exact_predicates_inexact_constructions_kernel Kernel;
typedef CGAL::Surface_mesh<Kernel::Point_3> Triangle_mesh;
typedef CGAL::Surface_mesh_shortest_path_traits<Kernel, Triangle_mesh> Traits;
typedef CGAL::Surface_mesh_shortest_path<Traits> Surface_mesh_shortest_path;
typedef boost::graph_traits<Triangle_mesh> Graph_traits;
typedef Graph_traits::vertex_iterator vertex_iterator;
typedef Graph_traits::face_iterator face_iterator;
int main(int argc, char** argv)
{
  Triangle_mesh tmesh;
  std::ifstream input((argc>1)?argv[1]:"data/elephant.off");
  input >> tmesh;
  input.close();
  // pick up a random face
  const unsigned int randSeed = argc > 2 ? boost::lexical_cast<unsigned int>(argv[2]) : 7915421;
  CGAL::Random rand(randSeed);
  const int target_face_index = rand.get_int(0, static_cast<int>(num_faces(tmesh)));
  face_iterator face_it = faces(tmesh).first;
  std::advance(face_it,target_face_index);
  // ... and define a barycentric coordinates inside the face
  Traits::Barycentric_coordinates face_location = {{0.25, 0.5, 0.25}};
  // construct a shortest path query object and add a source point
  Surface_mesh_shortest_path shortest_paths(tmesh);
  shortest_paths.add_source_point(*face_it, face_location);
  // For all vertices in the tmesh, compute the points of
  // the shortest path to the source point and write them
  // into a file readable using the CGAL Polyhedron demo
  std::ofstream output("shortest_paths_with_id.cgal");
  vertex_iterator vit, vit_end;
  for ( boost::tie(vit, vit_end) = vertices(tmesh);
        vit != vit_end; ++vit)
  {
    std::vector<Traits::Point_3> points;
    shortest_paths.shortest_path_points_to_source_points(*vit, std::back_inserter(points));
    // print the points
    output << points.size() << " ";
    for (std::size_t i = 0; i < points.size(); ++i)
      output << " " << points[i];
    output << std::endl;
  }
  return 0;
}
```
## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):Windows 10
* Compiler:VS 2019
* Release or debug mode:
* Specific flags used (if any):
* CGAL version:5.1.2
* Boost version:1.71
* Other libraries versions if used (Eigen, TBB, etc.):None

**Comment by sloriot** [comment]
Could you try adding after `#include <CGAL/Surface_mesh.h>` `#include <boost/graph/properties_Surface_mesh.h>`?

I can't reproduce the issue on my GNU/Linux with g++.

**Comment by flagwind11** [comment]
> Could you try adding after `#include <CGAL/Surface_mesh.h>` `#include <boost/graph/properties_Surface_mesh.h>`?
> 
> I can't reproduce the issue on my GNU/Linux with g++.

I tried but it's not useful. Thanks for your opinion!

**Comment by sloriot** [comment]
CGAL 5.1.2 is not longer supported, feel free to reopen in case you are still having the issue with a more recent release.
