### ISSUE TITLE
-Wrange-loop-analysis

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#5332]
## Issue Details

The [clang testsuite](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-Ic-34/Optimal_bounding_box/TestReport_monet_x86_64-apple_bigsur_clang1200-release-64bits.gz) warns for

`for(const  auto gnu : gnats){....} `

This seems a reasonable warning as the variable `gnu`  will get re-assigned values in the loop.
The warning suggests to write `const auto &`.     We can also drop the `const`, if it  is a small object.    

This should be fixed in the whole column of the testsuite.

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):
* Compiler: clang
* Specific flags used (if any):   probably due to the `-wextra`, but maybe also with `-wall`
* CGAL version: master

**Comment by lrineau** [comment]
I do not understand the compiler warning:
> /Users/monet/Documents/test-suite/clang-default/CGAL-5.3-Ic-34/test/Optimal_bounding_box/test_optimization_algorithms.cpp:94:18: warning: loop variable `v` of type `const CGAL::internal::In_place_list_iterator<CGAL::HalfedgeDS_in_place_list_vertex<CGAL::I_Polyhedron_vertex<CGAL::HalfedgeDS_vertex_base<CGAL::HalfedgeDS_list_types<CGAL::Epick, CGAL::I_Polyhedron_derived_items_3<CGAL::Polyhedron_items_3>, std::__1::allocator<int> >, CGAL::Boolean_tag<true>, CGAL::Point_3<CGAL::Epick> > > >, std::__1::allocator<CGAL::HalfedgeDS_in_place_list_vertex<CGAL::I_Polyhedron_vertex<CGAL::HalfedgeDS_vertex_base<CGAL::HalfedgeDS_list_types<CGAL::Epick, CGAL::I_Polyhedron_derived_items_3<CGAL::Polyhedron_items_3>, std::__1::allocator<int> >, CGAL::Boolean_tag<true>, CGAL::Point_3<CGAL::Epick> > > > > >` creates a copy from type `const CGAL::internal::In_place_list_iterator<CGAL::HalfedgeDS_in_place_list_vertex<CGAL::I_Polyhedron_vertex<CGAL::HalfedgeDS_vertex_base<CGAL::HalfedgeDS_list_types<CGAL::Epick, CGAL::I_Polyhedron_derived_items_3<CGAL::Polyhedron_items_3>, std::__1::allocator<int> >, CGAL::Boolean_tag<true>, CGAL::Point_3<CGAL::Epick> > > >, std::__1::allocator<CGAL::HalfedgeDS_in_place_list_vertex<CGAL::I_Polyhedron_vertex<CGAL::HalfedgeDS_vertex_base<CGAL::HalfedgeDS_list_types<CGAL::Epick, CGAL::I_Polyhedron_derived_items_3<CGAL::Polyhedron_items_3>, std::__1::allocator<int> >, CGAL::Boolean_tag<true>, CGAL::Point_3<CGAL::Epick> > > > > >` [-Wrange-loop-analysis]
```
  for(const auto v : vertices(mesh))
                 ^
```
> /Users/monet/Documents/test-suite/clang-default/CGAL-5.3-Ic-34/test/Optimal_bounding_box/test_optimization_algorithms.cpp:94:7: note: use reference type `const CGAL::internal::In_place_list_iterator<CGAL::HalfedgeDS_in_place_list_vertex<CGAL::I_Polyhedron_vertex<CGAL::HalfedgeDS_vertex_base<CGAL::HalfedgeDS_list_types<CGAL::Epick, CGAL::I_Polyhedron_derived_items_3<CGAL::Polyhedron_items_3>, std::__1::allocator<int> >, CGAL::Boolean_tag<true>, CGAL::Point_3<CGAL::Epick> > > >, std::__1::allocator<CGAL::HalfedgeDS_in_place_list_vertex<CGAL::I_Polyhedron_vertex<CGAL::HalfedgeDS_vertex_base<CGAL::HalfedgeDS_list_types<CGAL::Epick, CGAL::I_Polyhedron_derived_items_3<CGAL::Polyhedron_items_3>, std::__1::allocator<int> >, CGAL::Boolean_tag<true>, CGAL::Point_3<CGAL::Epick> > > > > > &` to prevent copying
```
  for(const auto v : vertices(mesh))
      ^~~~~~~~~~~~~~
                 &
```

Is not `CGAL::internal::In_place_list_iterator<...>` a type that is almost trivial to copy?

**Comment by afabri** [comment]
So maybe just the `-wextra`  is a bad idea.  Or we just put a `const&`  to make the compiler happy.

**Comment by lrineau** [comment]
I agree `const auto&` cannot harm, and will probably make the compiler happy. That is the easiest solution.

**Comment by danston** [comment]
Yes, this should be `const auto&`. When using `-wall` this is a common issue. I will fix that.

**Comment by lrineau** [comment]
> I agree `const auto&` cannot harm, and will probably make the compiler happy. That is the easiest solution.

Actually, the code generated by the compiler could slightly less efficient with `const auto&`. For a container of iterators, if iterators are implemented as a single pointer (a 64bits word), then it is more efficient to copy such an iterator than having a reference (an indirection, similar to a pointer) to such an iterator.

But I doubt we can detect the performance difference in a real code involving computations with CGAL.
