### ISSUE TITLE
Segmentation fault with invalid Aff_transformation_3

### ISSUE THREAD

**Issue by GilesBathgate** [CGAL/cgal#5338]
## Issue Details

When constructing an Aff_transformstion_3 with hw value of 0 there is, as expected, a divide by zero assertion thrown. However the assertion exception is not catchable, because the program crashes before it can be caught.

## Source Code

```c++
#include <CGAL/Exact_predicates_exact_constructions_kernel.h>
#include <CGAL/Aff_transformation_3.h>
#include <iostream>

using K = CGAL::Exact_predicates_exact_constructions_kernel;
using Aff = CGAL::Aff_transformation_3<K>;
using FT = K::FT;

Aff test()
{
    FT O(0.0),I(1.0);

    return Aff(I,O,O,O,
               O,I,O,O,
               O,O,I,O,
                     O);
}

int main()
{
    try
    {
        Aff t = test();
    } catch (...)
    {
    }
    std::cout << "Successful exit" << std::endl;
}
```
clang++ crash.cpp -DCGAL_DO_NOT_USE_BOOST_MP -lgmp -lmpfr

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Linux 64bit
* Compiler: clang++
* Release or debug mode: Release
* Specific flags used (if any): CGAL_NO_ASSERTIONS = false, CGAL_DO_NOT_USE_BOOST_MP
* CGAL version: 5.0.2
* Boost version: 1.71.0
* Other libraries versions if used (Eigen, TBB, etc.): Qt 5.12.8

**Comment by mglisse** [comment]
The assertion would be catchable, but the program crashes earlier. Handle_for_virtual is created with a null pointer, and the destructor dereferences it. In normal operations, the null pointer would be replaced by something else before the destructor, but because of the exception, this does not have a chance to happen.

**Comment by GilesBathgate** [comment]
@mglisse As far as a fix, the only thing that makes sense to me would be to check for nullptr in the destructor. Is there any other way?

**Comment by mglisse** [comment]
As long as Handle_for_virtual uses the mechanism "constructor then initialize_with", yes, the destructor should be able to handle the case where initialize_with did not complete, which means testing for a null pointer.
A more invasive change would be to merge initialize_with and the constructor, so we avoid this zombie state of an object that has been constructed but isn't valid yet.
Handle_for_virtual is not used much in CGAL, so it probably isn't worth spending a lot of time on it, the nullptr check looks good enough to me.
