### ISSUE TITLE
How to use custom point cloud data type for surface reconstruction?

### ISSUE THREAD

**Issue by Micalson** [CGAL/cgal#5339]
Hello, in my work, I want to use custom point cloud data type for surface reconstruction(Such as **poisson_surface_reconstruction_delaunay**), But I cannot find the right way. Could anyone help?
Thank you for the reply.

Regards,

**Comment by sloriot** [comment]
There is the `PointMap` parameter that should allow you to read any type of points and feed the CGAL algorithm with CGAL points constructed on the fly for example.

There is an example [here](https://doc.cgal.org/latest/Property_map/Property_map_2custom_property_map_8cpp-example.html) where "points" are actually indices referring to double values in arrays (`Custom_point_map`).

**Comment by Micalson** [comment]
Perfect! Thank you for your help.

**Comment by afabri** [comment]
@sgiraudot I think it would make sense to add examples to packages such as surface reconstruction.

**Comment by Micalson** [comment]
When I use the another method(`advancing_front_surface_reconstruction()`) for surface reconstrction, how could I use custom data type as the input? Thanks for your reply.

Regards,

**Comment by sgiraudot** [comment]
The easiest to do is to use Boost Transform Iterator on whatever range you have as input. You just need to provide a functor that converts your own data to the CGAL `Point_3` type. For example:

```c++
std::vector<My_point> my_points;

auto converter = [](const My_point& p) -> Kernel::Point_3
                 { return Kernel::Point_3( /* however you access the coordinates */); };

CGAL::advancing_front_surface_reconstruction
  (boost::make_transform_iterator (my_points.begin(), converter),
   boost::make_transform_iterator (my_points.end(), converter),
   /* ... the rest of the parameters ... */);
   ```

**Comment by Micalson** [comment]
Is there a more efficient way? For example: use the shared data.

**Comment by sgiraudot** [comment]
What do you mean by more efficient? Using the transform iterator, objects are converted on-the-fly, there is no memory overhead. And the time cost for the construction of `Point_3` objects should be quite insignificant compared to the rest of the algorithm.

**Comment by Micalson** [comment]
I think there are assignment operations in the transformation, so I thought there might be a more efficient way.
