### ISSUE TITLE
New warnings in testsuite

### ISSUE THREAD

**Issue by maxGimeno** [CGAL/cgal#5342]
## Issue Details
- [ ] ['this' pointer null](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.2.1-I-66/Interpolation_Demo/TestReport_lrineau_Ubuntu-GCC_master_CXX20-Release.gz)
- [ ] [arithmetic between floating-point type 'double' and enumeration type deprecated](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.2.1-I-66/Triangulation_3_Geomview_demos_Demo/TestReport_lrineau_Ubuntu-GCC_master_CXX20-Release.gz)

**Comment by afabri** [comment]
The second one is addressed by PR #5317

**Comment by afabri** [comment]
And isn't the first one just now discussed with @GilesBathgate ?

**Comment by GilesBathgate** [comment]
@afabri @maxGimeno Yes this may be fixed by #5341
