### ISSUE TITLE
Include order Delaunay_2 and Epick

### ISSUE THREAD

**Issue by HoffmannMichael** [CGAL/cgal#536]
It seems there are still issues with the include order of these two files

`#include <CGAL/Delaunay_triangulation_2.h>`
`#include <CGAL/Exact_predicates_inexact_constructions_kernel.`

(cf. discussion on cgal-develop from Jan 2015)

**Comment by sloriot** [comment]
What is the first file?

**Comment by HoffmannMichael** [comment]
#include <CGAL/Delaunay_triangulation_2.h>

**Comment by HoffmannMichael** [comment]
Delaunay_triangulation_2.h
(I don't know why it disappeared again... I typed it...)

**Comment by afabri** [comment]
I just implemented what  Laurent suggested in his mail from 22.1.15
and you can find it  at 4d324c704fe7c9bd05a6dfaccc58e6f767a20384
Question: what about  the .._kernel_with... ??

**Comment by lrineau** [comment]
See also PR #579 .
