### ISSUE TITLE
Polyhedron Vertex ID

### ISSUE THREAD

**Issue by petrasvestartas** [CGAL/cgal#5362]
How can I get Polyhedron vertex id?
I would like to iterate over faces and get vertex id of those face vertices.
In code below I am iterating over faces, but I do not know how to get index of a vertex.

     ```
       for ( auto it = output_mesh.facets_begin (); it != output_mesh.facets_end (); ++it ) {
                auto j = it->facet_begin ();
                CGAL_assertion (CGAL::circulator_size (j) >= 3);

               
                do {
                    //j->vertex()->point(). //How can I get an index ?
                    //std::cout << ' ' << std::distance (P.vertices_begin (), j->vertex ());
                } while ( ++j != it->facet_begin () );

            }
```

**Comment by raphaelsulzer** [comment]
See here: http://cgal-discuss.949826.n4.nabble.com/Convert-Polyhedron-3-Vertex-handles-to-integers-tp4664108p4664110.html

So for the first solution use CGAL::Polyhedron_items_with_id_3.
Loop over your mesh vertices and set vertex->id() = i++, which you can then access with j->vertex()->id() in your while loop.

**Comment by petrasvestartas** [comment]
Can I use this method for poisson surface reconstruction?
Considering output_mesh.

```

#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/Polyhedron_3.h>
#include <CGAL/poisson_surface_reconstruction.h>
#include <CGAL/IO/read_xyz_points.h>
#include <vector>
#include <fstream>
// Types
typedef CGAL::Exact_predicates_inexact_constructions_kernel Kernel;
typedef Kernel::Point_3 Point;
typedef Kernel::Vector_3 Vector;
typedef std::pair<Point, Vector> Pwn;
typedef CGAL::Polyhedron_3<Kernel> Polyhedron;
int main(void)
{
  std::vector<Pwn> points;
  std::ifstream stream("data/kitten.xyz");
  if (!stream ||
      !CGAL::read_xyz_points(
           stream,
           std::back_inserter(points),
           CGAL::parameters::point_map(CGAL::First_of_pair_property_map<Pwn>()).
           normal_map(CGAL::Second_of_pair_property_map<Pwn>())))
    {
      std::cerr << "Error: cannot read file data/kitten.xyz" << std::endl;
      return EXIT_FAILURE;
    }
  Polyhedron output_mesh;
  double average_spacing = CGAL::compute_average_spacing<CGAL::Sequential_tag>
    (points, 6, CGAL::parameters::point_map(CGAL::First_of_pair_property_map<Pwn>()));
  if (CGAL::poisson_surface_reconstruction_delaunay
      (points.begin(), points.end(),
       CGAL::First_of_pair_property_map<Pwn>(),
       CGAL::Second_of_pair_property_map<Pwn>(),
       output_mesh, average_spacing))
    {
        std::ofstream out("kitten_poisson-20-30-0.375.off");
        out << output_mesh;
    }
  else
    return EXIT_FAILURE;
  return EXIT_SUCCESS;
}
```

**Comment by petrasvestartas** [comment]
@raphaelsulzer  the reason for asking this is because I would like to get face vertex id.

I did this:
           int counter = 0;
           for ( Polyhedron3::Vertex_iterator it = output_mesh.vertices_begin (); it < output_mesh.vertices_end (); ++it ) {
               it->id () = counter;
               counter++;
           }

Then I want to fill integer array:
```
            int b = 0;
            for ( auto it = output_mesh.facets_begin (); it != output_mesh.facets_end (); ++it ) {
                auto j = it->facet_begin ();

                do {
                    n_o[b++] = j->vertex()->id ();
                } while ( ++j != it->facet_begin () );

            }
   
```

but this outputs strange information:
```
18446744073709551615
4
18446744073709551615
18446744073709551615
18446744073709551615
18446744073709551615
18446744073709551615
18446744073709551615
18446744073709551615
18446744073709551615
18446744073709551615
18446744073709551615
18446744073709551615
18446744073709551615
18446744073709551615
18446744073709551615
18446744073709551615
18446744073709551615
18446744073709551615
18446744073709551615
18446744073709551615
18446744073709551615
18446744073709551615
18446744073709551615
18446744073709551615
18446744073709551615
18446744073709551615
18446744073709551615
```

**Comment by sloriot** [comment]
Try
```
for (Polyhedron3::Facet_handle fh : output_mesh.facet_handles())
{
  Polyhedron3::Halfedge_handle start = fh->halfedge(), h = start;
  do{
    std::cout << h->vertex()->id() << "\n";
    h = h->next();
  }while(h!=start);
}
```

**Comment by sloriot** [comment]
The issue in your code was
`it < output_mesh.vertices_end ()` you should use `!=`.

**Comment by afabri** [comment]
Note also that it might make sense to use `Surface_mesh`  instead of `Polyhedron` and the BGL API.  While the former gives you the index for free, as a vertex is identified by an index, and the latter gives you more elegant loops.
```
for(boost::graph_traits<Poyhedron3>::face_descriptor fd : faces(output_mesh)){
  for(boost::graph_traits<Poyhedron3>::vertex_descriptor vd :  vertices_around_face(halfedge(fd, output_mesh), output_mesh){
    int id  = vd; 
  }
}
````

**Comment by afabri** [comment]
The function `facet_handles()`  got introduced in  `5.2`, so you must either upgrade, or use the `_begin()/_end()`  or switch to the BGL API.

**Comment by petrasvestartas** [comment]
Thank you @afabri  I did not know that it is possible to use Surface mesh as well. I will try to use it.
And it seems I am using CGAL 5.1.1

Is there any possibility to prevent code from crashing?
If I input less than 150 points or if point are lying on a plane like the screenshot attach, it crashes.

I tried to use  try/catch statement but it does not prevent from crash. 
Is there any way to prevent this? 
 ```
try { 
        double average_spacing = CGAL::compute_average_spacing<CGAL::Sequential_tag>     (points, 6, CGAL::parameters::point_map (CGAL::First_of_pair_property_map<PointVectorPair> ()));
        if ( CGAL::poisson_surface_reconstruction_delaunay  (points.begin (), points.end (), CGAL::First_of_pair_property_map<PointVectorPair> (),   CGAL::Second_of_pair_property_map<PointVectorPair> (),  output_mesh, average_spacing) ) {
...
   }

    } catch ( const std::exception& e ) {

        std::ofstream myfile2;
        myfile2.open ("C:\\libs\\Cockroach\\CockroachPInvoke\\Cockroach_CSHARP_DLL\\bin\\x64\\PoissonDebug.txt");
        myfile2<<e.what();
        myfile2.close();
    }



```

![Poisson](https://user-images.githubusercontent.com/18013985/104907484-772ea480-5985-11eb-9c34-872ff79319ad.png)

**Comment by afabri** [comment]
We should work on this.  
And let me make a remark for full code examples. You better put them on gist.github.com so that they are really full,  that is with `#include`  and `typedef`.  As a bonus this gets versioned.

**Comment by petrasvestartas** [comment]
These are two examples files inlcuding header and cpp:

https://gist.github.com/petrasvestartas/7d84b73170fafa38c51b23ad699af5d4
https://gist.github.com/petrasvestartas/10c521c7b2a82ed65536cfe1ebfec200

I know it is PInvoke but at least you can see code better.


I assume, the issue of crashing when input is not good, cannot be solved at a current stage?

**Comment by afabri** [comment]
You have to check if all points are coplanar.  In this case Poisson does not really make sense.

**Comment by petrasvestartas** [comment]
It is not only about planarity.
For instance if input pointset is downsampled to really small number of points i.e. 100 it crashes as well.

I am wondering if there is any way to track if inputs are totally irrational like this to avoid running Poisson:
![q](https://user-images.githubusercontent.com/18013985/104923193-021a9980-599c-11eb-9e21-4ef51b135c49.png)

**Comment by afabri** [comment]
Can you just send me a small point  set  with normals for which Poisson crashes so that I do not have to invent it myself.

**Comment by petrasvestartas** [comment]
These are two pointclouds that crashes.
If you need other than .ply format let me know.

[Clouds.zip](https://github.com/CGAL/cgal/files/5836030/Clouds.zip)

**Comment by petrasvestartas** [comment]
With normals
[CloudsWithNormals.zip](https://github.com/CGAL/cgal/files/5836102/CloudsWithNormals.zip)

**Comment by petrasvestartas** [comment]
Dear @afabri  maybe there was a chance to check the pointclouds?

**Comment by afabri** [comment]
Sorry @petrasvestartas   for coming back to you so late. Do you have a .cpp with your call that leads to a crash, so that I see the parameters etc.

**Comment by petrasvestartas** [comment]
Hi,

The Poisson Surface Reconstruction starts at line 786:
https://gist.github.com/petrasvestartas/c37b9d8089c2c0532cd4a5ac358505df

It is a PInvoke method. I believe it would be straight forward to understand.

**Comment by afabri** [comment]
I just created the self contained [`poisson.cpp` ](https://gist.github.com/afabri/a8c248195c6fe11d50258e951d2163ee )and it works for `Cloud1.ply`

**Comment by petrasvestartas** [comment]
Thank you @afabri  for the example file. I am really grateful that CGAL is such an active and responsive library.

I am trying to compare the example I took before and yours.
To make your method works do I need to install the recent CGAL version due?
It seems on older version I cannot call average spacing with two variables and for poisson reconstruction point_map does not exist.

![CGAL](https://user-images.githubusercontent.com/18013985/107271682-df384e00-6a4c-11eb-9218-4852b98c2247.png)

**Comment by afabri** [comment]
Ideally you cloned what I've put on gist.github.com, so that we have the same code base and can eventually reproduce.   It would also be good if for that you  used the latest public release (or even the master branch).

**Comment by petrasvestartas** [comment]
Hi,

I installed CGAL 5.2, seems that the method you are using working on my pc as well.
Since I am using PInvoke, I would to ask few question due inputs and outputs.
They are simple, but I strictly would like to follow your example using the same data-structures.

1) In your example you are reading a file, in my case I need to add points and vectors to the point set.
Previously I was pushing  PointVectorPair , can I somehow add points and vectors to the points object of your example?

```
    CGAL::Point_set_3<Kernel2::Point_3, Kernel2::Vector_3> points;

    for ( int i = 0; i < p_c; i++ ) {

        //points.push_back (PointVectorPair (
        //    Kernel2::Point_3 (p[3 * i + 0], p[3 * i + 1], p[3 * i + 2]),
        //    Kernel2::Vector_3 (n[3 * i + 0], n[3 * i + 1], n[3 * i + 2])
        //));
    }

```

2)  This question about reading vertices / faces from Polyhedron.
The commented line before worked now there not index. How can I iterate through vertices/faces and get each of their id?

```
Polyhedron2 output_mesh;

            for ( auto it = output_mesh.vertices_begin (); it != output_mesh.vertices_end (); ++it ) {
               // it->id () = counter++;
            }

```

**Comment by petrasvestartas** [comment]
Dear @afabri ,

Would it be possible to get a reply for this issue?

**Comment by sloriot** [comment]
1. There is the [`insert`](https://doc.cgal.org/latest/Point_set_3/classCGAL_1_1Point__set__3.html#acd87a6f1e03fdb0d1bec9111272043ae) method.
2. You need to use [`Polyhedron_items_with_id_3`](https://doc.cgal.org/latest/BGL/classCGAL_1_1Polyhedron__items__with__id__3.html) as template parameter.

**Comment by afabri** [comment]
The class  `Point_set_3`  has a method to [`insert()` ](https://doc.cgal.org/latest/Point_set_3/classCGAL_1_1Point__set__3.html#acd87a6f1e03fdb0d1bec9111272043ae) taking a point and a normal as arguments.   As the documentation of the method says, you must [add ](https://doc.cgal.org/latest/Point_set_3/classCGAL_1_1Point__set__3.html#aa04001c48e69953bba0f5eef989ba7fc )the normal property map once before.

**Comment by petrasvestartas** [comment]
Works perfectly, thank you @afabri  and @sloriot (I consider this issue closed).

Can you also explain me why mesh properties are normally not indexed? Is it faster to have it that way?
Before I was using OpenMesh as part of EPFL courses I was taking and they were not indexed either. Since my tutors did not answer this question, maybe you could?

Here is a working version from Rhino:
![image](https://user-images.githubusercontent.com/18013985/108122781-1b029180-70a5-11eb-9b65-3fd6bc4a7149.png)

**Comment by sloriot** [comment]
If by index property you mean a property that can be accessed in constant time (using an index), then obviously it requires an index on the considered item. Point_set_3 properties is considering points as indices to properties associated to points (like coordinates) are in a vector. The same hold for Surface_mesh and OpenMesh. For Polyhedron, if you use the item with id mentioned above, only [dynamic properties](https://doc.cgal.org/latest/BGL/index.html#title25) will be indexed.
