### ISSUE TITLE
CGAL::Polygon_mesh_processing::corefine_and_compute_intersection throw 'CGAL::Assertion_exception'

### ISSUE THREAD

**Issue by xiaowen64** [CGAL/cgal#5364]
[error.zip](https://github.com/CGAL/cgal/files/5825995/error.zip)

## Issue Details

As the title says. Source code and ply files of the two polygons are attached, both ascii and binary.

Error message:

```
terminate called after throwing an instance of 'CGAL::Assertion_exception'
  what():  CGAL ERROR: assertion violation!
Expr: (size_ == 2 && (v == first || v == second) ) || v==first
File: C:/msys64/mingw64/include/CGAL/Polygon_mesh_processing/internal/Corefinement/intersection_impl.h
Line: 130
```

## Source Code

```
#include <CGAL/Polygon_mesh_processing/corefinement.h>
#include <CGAL/Simple_cartesian.h>
#include <CGAL/Surface_mesh.h>

typedef CGAL::Simple_cartesian<double> Kernel;
typedef CGAL::Surface_mesh<Kernel::Point_3> Mesh;

namespace PMP = CGAL::Polygon_mesh_processing;

main()
{
    Mesh cube, sub;

    std::ifstream is("cube-b.ply");
    CGAL::read_ply(is, cube);
    is.close();

    is.open("sub-b.ply");
    CGAL::read_ply(is, sub);
    is.close();

    return PMP::corefine_and_compute_intersection(cube, sub, cube) ? 0 : 1;
}
```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): MSYS2 on Windows 10
* Compiler: gcc 10.2
* Release or debug mode: `g++ -Wall -O3 error.cpp -lmpfr -lgmp`
* Specific flags used (if any):
* CGAL version: 5.1.1
* Boost version: 1.75.0
* Other libraries versions if used (Eigen, TBB, etc.): `mpfr 4.1.0, gmp 6.2.1`

**Comment by sloriot** [comment]
-  replace `CGAL::Simple_cartesian<double>` by `CGAL::Exact_predicates_inexact_constructions_kernel`. See [FAQ](https://www.cgal.org/FAQ.html#inexact_NT)
-  add `-frounding-math` to gcc options.
