### ISSUE TITLE
where can I find setup.exe file for 5.2?

### ISSUE THREAD

**Issue by fredkimu** [CGAL/cgal#5365]
will the setup.exe file be uploaded for 5.2 release? Thank you!

**Comment by GilesBathgate** [comment]
@fredkimu I think now that cgal is headerless the setup.exe is no longer distributed. But installation is quite simple:

```powershell
Invoke-WebRequest https://github.com/CGAL/cgal/releases/download/v5.2/CGAL-5.2.zip -OutFile CGAL-release.zip
7z x -oC:\ CGAL-release.zip
Invoke-WebRequest https://github.com/CGAL/cgal/releases/download/v5.2/CGAL-5.2-win64-auxiliary-libraries-gmp-mpfr.zip -OutFile CGAL-gmp-mpfr.zip
7z x -o"$env:CGAL_DIR" CGAL-gmp-mpfr.zip -aoa
```

**Comment by fredkimu** [comment]
> @fredkimu I think now that cgal is headerless the setup.exe is no longer distributed. But installation is quite simple:
> 
> ```powershell
> Invoke-WebRequest https://github.com/CGAL/cgal/releases/download/v5.2/CGAL-5.2.zip -OutFile CGAL-release.zip
> 7z x -oC:\ CGAL-release.zip
> Invoke-WebRequest https://github.com/CGAL/cgal/releases/download/v5.2/CGAL-5.2-win64-auxiliary-libraries-gmp-mpfr.zip -OutFile CGAL-gmp-mpfr.zip
> 7z x -o"$env:CGAL_DIR" CGAL-gmp-mpfr.zip -aoa
> ```

thank you!

**Comment by lrineau** [comment]
Hi @fredkimu

I am the release manager of CGAL: I am the person who publish the assets for each CGAL releases. For CGAL-5.2, we intentionally did not publish the Windows installer, because we fell it is not needed, and we wanted to know if any user would ask for it. So far your are the first one asking.

Do you need the Windows installer or are the zip files sufficient? Please let us know.

**Comment by fredkimu** [comment]
> Hi @fredkimu
> 
> I am the release manager of CGAL: I am the person who publish the assets for each CGAL releases. For CGAL-5.2, we intentionally did not publish the Windows installer, because we fell it is not needed, and we wanted to know if any user would ask for it. So far your are the first one asking.
> 
> Do you need the Windows installer or are the zip files sufficient? Please let us know.

Dear @lrineau,

That would be great! I actually don't have much programming experience (almost no experience) and having hard to make something work with CGAL. Tried to follow the instructions but still having hard to "build(?)" and couldn't find much video tutorials and etc.. It would be still nice to have to windows installer as it is easier to install but i haven't been successful with previous windows installers yet. still trying to make it work. Do you happen to know if there any tutorials or previous threads for someone who would like to use CGAL but have no coding experience? Thank you!

**Comment by afabri** [comment]
I may be wrong, but I have a hard time to imagine what you want to do with CGAL if you have almost no programming experience. Then the "better" installer will hardly help you.  This is not meant as an offense, so please explain and maybe I later I understand that there is  indeed a justified need.

**Comment by maximecharriere** [comment]
I was also looking for the installer to update from 5.1 to 5.2, but I understand very well that it is no longer necessary. 
I simply advise to change the download instructions on the [website](https://www.cgal.org/download/windows.html) and explain what to do with GMP and MPFR.

**Comment by petrasvestartas** [comment]
I think I need installation tutorial for dummies.

I downloaded these two files (not sure if I need to download anything else ?)

What should I do next? 
Compile projects as before or do I need build CGAL?
![Question](https://user-images.githubusercontent.com/18013985/107580048-4e04db00-6bf6-11eb-888d-335e2435f7a1.png)

**Comment by maximecharriere** [comment]
I'm currently writing a tutorial on how to install CGAL and its third party libraries libraries for Windows. 
See my [gist](https://gist.github.com/maximecharriere/5b071d5d07581af58b7333fe72a3e1f7)
