### ISSUE TITLE
problems with Point_set_3 property maps

### ISSUE THREAD

**Issue by raphaelsulzer** [CGAL/cgal#5368]
## Issue Details

I'm trying to use the Point_set_3 property maps but run into many issues as described in the last three lines in the code below.
What am I doing wrong?

## Source Code

```
    #include <CGAL/Point_set_3.h>
    typedef CGAL::Point_set_3<Point> Point_set;
    typedef std::array<unsigned char, 3> Color;
    typedef Point_set::Property_map<Color> Color_map;

    data.point_set.reserve(data.smesh.number_of_vertices());
    Color white = {{ 255, 255, 255 }};
    Color_map color;
    bool created;
    boost::tie(color, created) = data.point_set.add_property_map<Color>("color", white);
    cout << "color point map for point set created: " << created << endl;  // outputs true

    /// add some points to the point_set ///

   int j = 0;
    for(Point_set::const_iterator pit = data.point_set.begin(); pit !=data.point_set.end(); pit++){
        int c = get(index_map, j++);
        if(c == -1)
            continue; // leave unassigned points white
        color[*pit][0]=(unsigned char)color_palette[c%7].r();
        color[*pit][1]=(unsigned char)color_palette[c%7].g();
        color[*pit][2]=(unsigned char)color_palette[c%7].b();
    }

//// This works fine
//    Point_set::iterator it = data.point_set.begin();
//    while (it != data.point_set.end())
//      {
//        cout << (int)color[*it][0] <<  " " << (int)color[*it][1] << " " << (int)color[*it][2] << endl;
//        it++;
//      }

//// Here nothing works
    write_ply_point_set(outstream,data.point_set); // writes the points but doesn't write colors
    Color_map color = data.point_set.property_map("color").first; // no matching function error
    auto nt = data.point_set.properties_and_types(); // no matching function error in stl_pair.h
```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Ubuntu 18.04
* Compiler: gcc 7.5.0
* Release or debug mode: Release
* CGAL version: 5.1.1
* Boost version: 1.6.5

**Comment by sgiraudot** [comment]
- `write_ply_point_set()` will only write properties with simple types (as [stated in the documention](https://doc.cgal.org/latest/Point_set_3/group__PkgPointSet3IO.html#ga4dafa5ad1b9a33b84ad3467510791875)): in your case, the color is an object, not a simple type. If you want to use this function to output your colors, I suggest using 3 property maps of type `unsigned char` (in which case, you will also benefit from the fact that their names will be propagated to the PLY output, which can be handy as many softwares will recognize `red`, `green` and `blue` properties and interpret them correctly)

- The `Point_set_3::property_map` function is template, you need to specify the type `data.point_set.property_map<Color>("color")`

- I can indeed reproduce the last bug about the error in `stl_pair`. Thanks for the report, I'll investigate

**Comment by sgiraudot** [comment]
The issue with `stl_pair` is fixed by https://github.com/CGAL/cgal/pull/5369.

**Comment by raphaelsulzer** [comment]
Thanks a lot for the quick reply, everything working as expected now!
