### ISSUE TITLE
Errors in 5.3-I-42

### ISSUE THREAD

**Issue by maxGimeno** [CGAL/cgal#5374]
- **Compilation errors** :
  - LEDA erorrs:
    - [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/Algebraic_kernel_d/TestReport_lrineau_Fedora-with-LEDA.gz
    - [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/Arrangement_on_surface_2/TestReport_lrineau_Fedora-with-LEDA.gz
    - [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/Distance_2/TestReport_lrineau_Fedora-with-LEDA.gz
    - [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/Number_types/TestReport_lrineau_Fedora-with-LEDA.gz
    - [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/Polyhedron_Demo/TestReport_lrineau_Fedora-with-LEDA.gz

  - CXX20
    - result_type
      - [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/Bounding_volumes/TestReport_Blake_Windows_MSVCPreview-Release-64bits.gz
      - [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/Bounding_volumes_Demo/TestReport_Blake_Windows_MSVCPreview-Release-64bits.gz
      - [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/Convex_hull_3/TestReport_Blake_Windows_MSVCPreview-Release-64bits.gz
      - [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/Convex_hull_3_Examples/TestReport_Blake_Windows_MSVCPreview-Release-64bits.gz
      - [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/Generator/TestReport_Blake_Windows_MSVCPreview-Release-64bits.gz
      - [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/Generator_Examples/TestReport_Blake_Windows_MSVCPreview-Release-64bits.gz
      - [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/Inscribed_areas/TestReport_Blake_Windows_MSVCPreview-Release-64bits.gz
      - [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/Inscribed_areas_Examples/TestReport_Blake_Windows_MSVCPreview-Release-64bits.gz
      - [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/Kernel_d/TestReport_Blake_Windows_MSVCPreview-Release-64bits.gz
      - [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/Matrix_search/TestReport_Blake_Windows_MSVCPreview-Release-64bits.gz
      - [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/Matrix_search_Examples/TestReport_Blake_Windows_MSVCPreview-Release-64bits.gz
      - [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/Min_annulus_d_Examples/TestReport_Blake_Windows_MSVCPreview-Release-64bits.gz
      - [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/Min_quadrilateral_2_Examples/TestReport_Blake_Windows_MSVCPreview-Release-64bits.gz
      - [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/Optimal_bounding_box/TestReport_Blake_Windows_MSVCPreview-Release-64bits.gz
      - [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/Optimal_bounding_box_Examples/TestReport_Blake_Windows_MSVCPreview-Release-64bits.gz
      - [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/Point_set_processing_3/TestReport_Blake_Windows_MSVCPreview-Release-64bits.gz
      - [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/Polytope_distance_d/TestReport_Blake_Windows_MSVCPreview-Release-64bits.gz
      - [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/Polytope_distance_d_Examples/TestReport_Blake_Windows_MSVCPreview-Release-64bits.gz
      - [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/QP_solver/TestReport_Blake_Windows_MSVCPreview-Release-64bits.gz
      - [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/QP_solver_Examples/TestReport_Blake_Windows_MSVCPreview-Release-64bits.gz
      - [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/Rectangular_p_center_2_Examples/TestReport_Blake_Windows_MSVCPreview-Release-64bits.gz
      - [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/STL_Extension/TestReport_Blake_Windows_MSVCPreview-Release-64bits.gz
      - [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/STL_Extension_Examples/TestReport_Blake_Windows_MSVCPreview-Release-64bits.gz

    - error C2039: 'random_shuffle' is not a member of 'std':
      - [x] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/Segment_Delaunay_graph_2_Demo/TestReport_Blake_Windows_MSVCPreview-Release-64bits.gz
      - [x] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/Segment_Delaunay_graph_Linf_2_Demo/TestReport_Blake_Windows_MSVCPreview-Release-64bits.gz

    - ICE
      - [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/Arrangement_on_surface_2/TestReport_Blake_Windows_MSVCPreview-Release-64bits.gz

  - VS2017 ICE:
      - [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/Polygon_Demo/TestReport_afabri_x64_Cygwin-Windows10_MSVC2017-Release-64bits.gz
      - [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/Arrangement_on_surface_2_Demo/TestReport_afabri_x64_Cygwin-Windows10_MSVC2017-Release-64bits.gz
      - [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/Straight_skeleton_2/TestReport_afabri_x64_Cygwin-Windows10_MSVC2017-Release-64bits.gz
      - [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/Straight_skeleton_2_Examples/TestReport_afabri_x64_Cygwin-Windows10_MSVC2017-Release-64bits.gz

  - boost multiprecision error :
    - [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/Number_types/TestReport_lrineau_ArchLinux-CXX14.gz

- **Runtime errors**:
  - [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/Algebraic_kernel_d/TestReport_lrineau_ArchLinux-clang.gz:
  - [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/Arrangement_on_surface_2/TestReport_Blake_Windows_MSVC-2019-Community-Release-64bits.gz
  - [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/Bounding_volumes/TestReport_lrineau_Fedora-with-LEDA.gz
  - [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/CGAL_ImageIO/TestReport_lrineau_Fedora-32-Release.gz
  - [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/Classification/TestReport_Blake_Windows_MSVC-2019-Community-Release-64bits.gz
  - [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/Classification_Examples/TestReport_Blake_Windows_MSVC-2019-Community-Release-64bits.gz
  - [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/Envelope_3/TestReport_lrineau_Fedora-with-LEDA.gz
  - [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/Jet_fitting_3_Examples/TestReport_Blake_Windows_MSVC-2019-Community-Release-64bits.gz
  - [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/Mesh_3_Examples/TestReport_lrineau_ArchLinux.gz
  - [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/NewKernel_d/TestReport_lrineau_Fedora-with-LEDA.gz
  - [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/Polynomial/TestReport_afabri_x64_Cygwin-Windows10_MSVC2017-Release-64bits.gz
  - [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/Polynomial/TestReport_lrineau_Fedora-32-Release.gz
  - [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/Polynomial/TestReport_Blake_Windows_MSVC-2019-Community-Release-64bits.gz
  - [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/Polynomial/TestReport_Blake_Windows_MSVCPreview-Release-64bits.gz
  - [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/QP_solver/TestReport_lrineau_Fedora-with-LEDA.gz
  - [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/Ridges_3_Examples/TestReport_Blake_Windows_MSVC-2019-Community-Release-64bits.gz
  - [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/Surface_mesh_approximation/TestReport_lrineau_Fedora-32.gz
  - [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/Surface_mesh_shortest_path/TestReport_lrineau_Fedora-32-Release.gz
  - [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/Surface_mesh_shortest_path/TestReport_Blake_Windows_MSVC-2019-Community-Release-64bits.gz

- **CMake Error**
  - [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/Hyperbolic_triangulation_2_Demo/TestReport_lrineau_Fedora-with-LEDA.gz
  - [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/Mesh_3_Examples/TestReport_lrineau_Ubuntu-GCC_master_CXX20-Release.gz
  - [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/Mesh_3_Examples/TestReport_lrineau_Fedora-32.gz
  - [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/Point_set_processing_3_Examples/TestReport_lrineau_Fedora-32.gz
  - [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/Polyhedron_Demo/TestReport_lrineau_Fedora-32.gz
  - [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/Tetrahedral_remeshing_Examples/TestReport_lrineau_Ubuntu-GCC_master_CXX20-Release.gz
  - [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/Tetrahedral_remeshing_Examples/TestReport_lrineau_Fedora-32.gz
  - [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/Triangulation_3_Demo/TestReport_lrineau_Fedora-32.gz
  - [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/Point_set_processing_3_Examples/TestReport_Blake_Windows_MSVCPreview-Release-64bits.gz

- **Timeout Errors**
  - [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/Mesh_3_Examples/TestReport_Blake_Windows_MSVCPreview-Release-64bits.gz
  - [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/Periodic_3_mesh_3/TestReport_afabri_x64_Cygwin-Windows10_MSVC2015-Debug-64bits.gz
  - [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/Periodic_3_triangulation_3/TestReport_afabri_x64_Cygwin-Windows10_MSVC2015-Debug-64bits.gz
  - [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/Polygon_mesh_processing/TestReport_lrineau_Ubuntu-latest-GCC6-Release.gz
  - [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/Polygon_mesh_processing/TestReport_lrineau_Ubuntu-GCC_master_CXX20-Release.gz
  - [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/Polyhedron_Demo/TestReport_lrineau_ArchLinux-clang-CXX17-Release.gz
  - [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/Polyhedron_Demo/TestReport_lrineau_ArchLinux-clang-Release.gz
  - [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/Polyhedron_Demo/TestReport_lrineau_ArchLinux-clang.gz
  - [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/Triangulation_3/TestReport_afabri_x64_Cygwin-Windows10_MSVC2017-Release-64bits.gz
  - [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/Triangulation_3_Examples/TestReport_afabri_x64_Cygwin-Windows10_MSVC2017-Release-64bits.gz
  - [ ] https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-42/Visibility_2/TestReport_lrineau_Fedora-with-LEDA.gz

**Comment by afabri** [comment]
For the runtime errors with msvc community release the fix is probably that you install boost program options.

**Comment by maxGimeno** [comment]
It is already installed. All the "missing shared libs" are installed. The problem may be a bug in the BoostConfig.cmake.

**Comment by maxGimeno** [comment]
I removed /external  /external:I C:/3rdPartyLibs/boost_1_69_0 from the flags of the platform, maybe it was confusing things.
