### ISSUE TITLE
Mesh_3 compiles but crashes if compiled then run with `Parallel_tag` but without `CGAL_LINKED_WITH_TBB`

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#5375]
## Issue Details

See the result of examples/Mesh_3/ is that test results:
https://cgal.geometryfactory.com/CGAL/testsuite/results-5.3-I-42.shtml#Mesh_3_Examples

There are a lot of platforms were the example `mesh_implicit_domains.cpp` fails at runtime.

The reason is that, the tag `CGAL::Parallel_tag` was used for the concurrency tag of the triangulation **but** `CGAL_LINKED_WITH_TBB` was not defined. That did compile, but the code logic with wrong with that setting: the function `Refine_cells_3::remove_element_from_refinement_queue(Cell_handle, Parallel_tag)` is then implemented as a no-op, even if `CGAL_LINKED_WITH_TBB` is not defined.

In my opinion that is completely wrong: a usage of `CGAL::Parallel_tag` when `CGAL_LINKED_WITH_TBB` should lead to a compilation error.

That was already discussed in the small feature [`Patch_to_concurrency_in_CGAL`](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Patch_to_concurrency_in_CGAL) in 2016 and 2019, but I think the authors and reviewers focused on `Parallel_if_available_tag` and forgot to discuss about `Parallel_tag`, or made the wrong decision.

**Comment by lrineau** [comment]
@afabri What was your opinion about the following?

```c++
struct Sequential_tag {};
struct Parallel_tag : public Sequential_tag {};
```

The implicit cast of `Parallel_tag` into `Sequential` is an error, in my opinion. I think you saw that during the review, at https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Patch_to_concurrency_in_CGAL#Discussion_3 but the feature moved forward anyway.

**Comment by afabri** [comment]
@MaelRL and @sloriot I would like to discuss this next Monday.

**Comment by MaelRL** [comment]
> @afabri What was your opinion about the following?
> 
> ```c++
> struct Sequential_tag {};
> struct Parallel_tag : public Sequential_tag {};
> ```
> 
> The implicit cast of `Parallel_tag` into `Sequential` is an error, in my opinion. I think you saw that during the review, at https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Patch_to_concurrency_in_CGAL#Discussion_3 but the feature moved forward anyway.

`struct Parallel_tag : public Sequential_tag {};`  
predates that particular small feature. Seems to be coming from parallel Mesh_3, so might have to check why it was done there.

**Comment by lrineau** [comment]
> > @afabri What was your opinion about the following?
> > ```c++
> > struct Sequential_tag {};
> > struct Parallel_tag : public Sequential_tag {};
> > ```
> > 
> > 
> > The implicit cast of `Parallel_tag` into `Sequential` is an error, in my opinion. I think you saw that during the review, at [cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Patch_to_concurrency_in_CGAL#Discussion_3](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Patch_to_concurrency_in_CGAL#Discussion_3) but the feature moved forward anyway.
> 
> `struct Parallel_tag : public Sequential_tag {};`
> predates that particular small feature. Seems to be coming from parallel Mesh_3, so might have to check why it was done there.

At the time `Parallel_tag` was created, it was chosen that the `Parallel_tag` degrades implicitly to `Sequential_tag`, using that derivation. That was by design, at that time.

If you have a look at the [rational section of the small feature](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Patch_to_concurrency_in_CGAL#Rationale), from 2014, it was created to removed that derivation, and create a compilation error if the user asked for `Parallel_tag` whereas TBB was not used. The small feature was pre-approved in 2016 by Clément Jamin, but never implemented. Then Andreas and Mael tooks over the small feature, and decided to refocus it on a new name `Parallel_if_available_tag`. But the need for a compilation error was dropped. Andreas re-questionned the derivation [in the discussion section of the third round] (https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Patch_to_concurrency_in_CGAL#Discussion_3), but the feature was approved anyway.
