### ISSUE TITLE
~70% Performance speedup for polygon_mesh_to_nef_3

### ISSUE THREAD

**Issue by GilesBathgate** [CGAL/cgal#5379]
## Issue Details

I have been investigating the performance of nef polyhedron construction, and have noticed the calculation of normals using normal_newell_3, while this approach is suitable for convex/concave facets with an arbitrary number of vertices, I think it is suboptimal for triangular facets. The function CGAL::orthogonal_vector is much better for this task, and we can easily switch between these two methods based on the number of edges/vertices.

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Linux 64bit
* Compiler: clang++ 
* Release or debug mode: Release
* Specific flags used (if any): clang++ polyhedron_3_to_nef_3_benchmark.cpp -DCGAL_DO_NOT_USE_BOOST_MP -lgmp -lmpfr -lbenchmark
* CGAL version: 5.0.2
* Boost version: 1.71.0
* Other libraries versions if used (Eigen, TBB, etc.): Qt 5.12.8

**Comment by GilesBathgate** [comment]
One approach to improving the performance might be to add the following function to `normal_vector_newell_3.h` to be used as a drop-in replacement in `polygon_mesh_to_nef_3.h`

```c++
template <class IC, class Vector, class VertexPointMap>
void facet_normal_3( IC first, IC last, VertexPointMap vpm, Vector& n )
{
    const typename IC::size_type triangle_points = 3;
    if(CGAL::circulator_size(first) == triangle_points) {
        n = CGAL::orthogonal_vector(get(vpm,*(first)),get(vpm,*(++first)),get(vpm,*(++first)));
    } else {
        normal_vector_newell_3(first, last, vpm, n);
    }
}
```

**Comment by GilesBathgate** [comment]
Here is another simple benchmark:

```c++
#include <CGAL/Exact_predicates_exact_constructions_kernel.h>
#include <CGAL/Polyhedron_3.h>
#include <CGAL/Nef_polyhedron_3.h>
#include <fstream>

using K = CGAL::Exact_predicates_exact_constructions_kernel;
using Polyhedron = CGAL::Polyhedron_3<K>;
using NefPolyhedron = CGAL::Nef_polyhedron_3<K>;

int main()
{

    std::ifstream file("Surface_mesh_segmentation/benchmark/Surface_mesh_segmentation/data/refined_elephant.off");
    Polyhedron P;
    file >> P;
    NefPolyhedron N(P);
}
```

time ./baseline
real	0m50.498s
user	0m49.719s
sys	0m0.768s

time ./contender 
real	0m33.058s
user	0m32.689s
sys	0m0.368s

**Comment by mglisse** [comment]
Out of curiosity, are all the computations in newell_single_step_3 performed on Lazy_exact_nt (including many multiplications by hw=1)?

**Comment by GilesBathgate** [comment]
@mglisse Yes? https://github.com/CGAL/cgal/blob/74af3e7d33e7354e4090a1b17941a3f0c372ca8d/Nef_3/include/CGAL/normal_vector_newell_3.h#L33

**Comment by mglisse** [comment]
Well, that's not a good idea from an efficiency PoV...

**Comment by GilesBathgate** [comment]
@mglisse If `newell_single_step_3` can be optimised that would be better than trying to switch between two methods, but how to do such an optimisation didn't occur to me.

**Comment by mglisse** [comment]
1. If the kernel is Cartesian (not homogeneous), don't multiply by hw (which is 1).
2. Make newell_single_step_3 a construction functor at the kernel level (taking 2 points and a vector and returning a vector), so that it creates a single lazy node instead of one for each arithmetic operation.

Note that I am not familiar with Nef_3, so take what I say with a truckload of salt. Maybe there is a hidden homogeneous point somewhere, and maybe moving things to the kernel gives a crappy interface.

**Comment by GilesBathgate** [comment]
@mglisse I'd like to give those ideas a try but 
1) I don't know how to create a template specialisation for non-homgeneous kernel. I'll see if I can figure it out
2) I get the gist of what you are saying but not quite sure how to implement that.
3) I can certainly give this a try.

**Comment by GilesBathgate** [comment]
@mglisse This is looking hopeful:

```c++
void newell_single_step_3( const Handle& p, const Handle& q, Vector& n )
{
  const auto& phw = p.hw();
  const auto& qhw = q.hw();
  const auto& nhw = n.hw();
  const auto& sq = phw * phw * qhw * qhw;
  const auto& phyqhw = p.hy() * qhw;
  const auto& qhyphw = q.hy() * phw;
  const auto& phxqhw = p.hx() * qhw;
  const auto& qhxphw = q.hx() * phw;
  const auto& phzqhw = p.hz() * qhw;
  const auto& qhzphw = q.hz() * phw;

  n = Vector(
    n.hx()
        * sq
      + nhw
        * ( phyqhw - qhyphw )
        * ( phzqhw + qhzphw ),
    n.hy()
        * sq
      + nhw
        * ( phzqhw - qhzphw )
        * ( phxqhw + qhxphw ),
    n.hz()
        * sq
      + nhw
        * ( phxqhw - qhxphw )
        * ( phyqhw + qhyphw ),
    n.hw()
        * sq
    );
}
```

time ./contender2

real	0m42.888s
user	0m42.490s
sys	0m0.388s

**Comment by GilesBathgate** [comment]
@mglisse Here is a non-homogeneous version which passes the test (I've no reason to believe there are hidden homogenous points in Nef3) But I don't know how to make this a template specialisation.

```c++
void newell_single_step_3( const Handle& p, const Handle& q, Vector& n )
{
  const auto& phy = p.hy();
  const auto& qhy = q.hy();
  const auto& phx = p.hx();
  const auto& qhx = q.hx();
  const auto& phz = p.hz();
  const auto& qhz = q.hz();

  n = Vector(
    n.hx()
        + ( phy - qhy )
        * ( phz + qhz ),
    n.hy()
        + ( phz - qhz )
        * ( phx + qhx ),
    n.hz()
        + ( phx - qhx )
        * ( phy + qhy )
    );
}
```

time ./contender3

real	0m38.731s
user	0m38.420s
sys	0m0.312s

**Comment by GilesBathgate** [comment]
@mglisse How would I do the template specialisation, something like:

```c++
std::enable_if_t<std::is_class<Kernel_traits<Vector>::Kernel,Homogeneous<Kernel_traits<Vector>::Kernel::RT> = true>
```
🤷‍♂️

**Comment by GilesBathgate** [comment]
```c++
typedef typename Kernel_traits<Vector>::Kernel R;

internal_nef::newell_single_step_3( get(vpm,*prev), get(vpm,*first), n, R::Kernel_tag());

void newell_single_step_3( const Handle& p, const Handle& q, Vector& n, const Homogeneous_tag&);
 void newell_single_step_3( const Handle& p, const Handle& q, Vector& n, const Cartesian_tag&);
 
 ```

**Comment by mglisse** [comment]
3 quick comments (review will need to be by someone who knows Nef_3): `x*x` should be `CGAL::square(x)`, Cartesian coordinates should be x, y and z, not hx, hy and hz, and `Kernel_traits` should be avoided as much as possible, although Nef_3 specifically requires its traits class to be one of the official kernels (with Type_equality_wrapper), so it seems ok for that package.

**Comment by GilesBathgate** [comment]
@mglisse Applied the suggested changes: https://github.com/GilesBathgate/cgal/commit/87b2c5e2876ff7929cfa049cb3015585858f1734

**Comment by GilesBathgate** [comment]
@mglisse @sloriot I have another question regarding code in `polygon_mesh_to_nef_3`. According to performance analysis the assertion:

https://github.com/CGAL/cgal/blob/74af3e7d33e7354e4090a1b17941a3f0c372ca8d/Nef_3/include/CGAL/Nef_3/polygon_mesh_to_nef_3.h#L255-L256

takes 54.8% of the time to compute. Would this be a candidate for `CGAL_expensive_assertion`? and under what circumstances would this assertion fail?

**Comment by GilesBathgate** [comment]
> takes 54.8% of the time to compute.

I think this is due to running the profiler with a Lazy kernel, if I use `Cartesian<Gmpq>` the assertions only take 6.8% of the computation time, and `normal_vector_newell_3` takes 45.2% of the time.

**Comment by GilesBathgate** [comment]
I've been looking further into the steps performed in `polygon_mesh_to_nef_3` and noticed `check_integrity_and_topological_planarity` was a minor hotspot. The code behind the method:

https://github.com/CGAL/cgal/blob/0a46621dc6d9db1a8dfef7885e196c6a6bbeaca0/Nef_S2/include/CGAL/Nef_S2/SM_const_decorator.h#L286-L291

Constructs and populates 3 hash maps as part of the `Object_index` class, but 2 of the maps are only used in the case where `CGAL_assertion_msg` fails. (The third `FI` isn't even used) I changed the code to only calculate the indexes when needed:

```c++
    if ( is_isolated(v) ) {
       if ( faces )
         CGAL_assertion_msg(v->incident_sface() != SFace_const_handle(), get_svertex_index(v).c_str());
       ++iso_vert_num;
     } else {
      CGAL_assertion_msg(first_out_edge(v) != SHalfedge_const_handle(), get_svertex_index(v).c_str());
      CGAL_NEF_TRACEN(v->point()<<" "<<get_shalfedge_index(first_out_edge(v)));
      CGAL_assertion_msg(first_out_edge(v)->source() == v, get_svertex_index(v).c_str());
```

This creates an additional speedup when compared with the baseline which has the previous optimisations included:

```
time ../baseline && time ../contender 

real	0m33.526s
user	0m33.132s
sys	0m0.385s

real	0m31.284s
user	0m30.920s
sys	0m0.364s
```

**Comment by GilesBathgate** [comment]
@mglisse  The following changes provide a further speedup if `robin_hood::unordered_flat_map` is used as suggested in #4049. I don't know how to implement wrapping `std::list` in `std:queue` but I'd like to try that out too.:
```
time ../contender

real	0m30.125s
user	0m29.880s
sys	0m0.240s
```

```diff
@@ -381,12 +381,13 @@ SM_const_decorator<SM_>::
 number_of_sface_cycles() const
 {
   unsigned int fc_num=0;
-  CGAL::Unique_hash_map<SHalfedge_const_handle,bool> visited;
+  robin_hood::unordered_flat_set<SHalfedge_const_handle,Handle_hash_function> visited;
+  visited.reserve(number_of_shalfedges());
   SHalfedge_const_iterator e;
   CGAL_forall_shalfedges(e,*this) {
-    if (visited[e]) continue;
+    if (visited.contains(e)) continue;
     SHalfedge_around_sface_const_circulator hfc(e), hend(hfc);
-    CGAL_For_all(hfc,hend) visited[hfc]=true;
+    CGAL_For_all(hfc,hend) visited.insert(hfc);
     ++fc_num;
   }
   if ( has_shalfloop() ) fc_num += 2;
@@ -399,12 +400,13 @@ SM_const_decorator<SM_>::
 number_of_connected_components() const
 {
   int comp_num=0;
-  CGAL::Unique_hash_map<SVertex_const_iterator,bool> visited(false);
+  robin_hood::unordered_flat_set<SVertex_const_iterator,Handle_hash_function> visited;
+  visited.reserve(number_of_svertices());
   SVertex_const_iterator v;
   CGAL_forall_svertices(v,*this) {
-    if (visited[v]) continue;
+    if (visited.contains(v)) continue;
     std::list<SVertex_const_iterator> L;
-    L.push_back(v); visited[v]=true;
+    L.push_back(v); visited.insert(v);
     /* we keep the invariant that all nodes which have been stacked
        are marked visited */
     while (!L.empty()) {
@@ -413,8 +415,8 @@ number_of_connected_components() const
       SHalfedge_around_svertex_const_circulator
         havc(first_out_edge(vc)), hend(havc);
       CGAL_For_all(havc,hend) {
-        if (!visited[havc->target()]) {
-          L.push_back(havc->target()); visited[havc->target()]=true;
+        if (!visited.contains(havc->target())) {
+          L.push_back(havc->target()); visited.insert(havc->target());
         }
       }
     }
```

**Comment by mglisse** [comment]
The comment above said that `visited.contains(v)` should be directly `!visited.insert(v).second`, removing the later insert, so that only one hash+search is done.

**Comment by mglisse** [comment]
> I don't know how to implement wrapping `std::list` in `std:queue`

Just replace list with queue, and adapt the names of the functions (push instead of push_back, etc).

**Comment by GilesBathgate** [comment]
@mglisse Updated code and numbers above. The performance gain is now ~40% :)

**Comment by GilesBathgate** [comment]
I've done some further investigation regarding the assertions:

```
CGAL_assertion(ss_circle.has_on(sp));
CGAL_assertion(ss_circle.has_on(sv_prev->point()));
```

These are showing up as quite expensive in the profiler. If I understand correctly these assertions are being made while walking around the edges of the facet, checking that the current and previous points of the facet are on the plane defined by the facet normal. This is necessary to make sure the points on the facet are co-planar as discovered here: http://forum.openscad.org/Anybody-know-what-ss-circle-has-on-sp-means-td22662.html . However when we are walking the edges of a triangular facet, we know that the 3 points of the facet will always be on a plane defined by the facet normal, (since 3 points define a plane, and this is why a table with 3 legs doesn't wobble ;) ) so the check is redundant.

I have implemented a bypass of this assertion for triangular facets, which provides another performance boost:

```
time ../contender 

real	0m25.154s
user	0m24.933s
sys	0m0.212s
```

I will submit another PR with additional changes.

**Comment by GilesBathgate** [comment]
Further investigation suggests that in the constructor of `Nef_polyhedron_3` the call to `simplify()` is made twice, once explicitly:

https://github.com/CGAL/cgal/blob/0dcff365d063bac5e159b53346566d1c22209b55/Nef_3/include/CGAL/Nef_polyhedron_3.h#L594-L609

and then again through the Mark_bounded_volumes delegate:

https://github.com/CGAL/cgal/blob/0dcff365d063bac5e159b53346566d1c22209b55/Nef_3/include/CGAL/Nef_polyhedron_3.h#L1058-L1076

I believe this to be unintentional since the old versions of the constructor in the git history did not call simplify twice.

Removing the duplicated call offers further performance improvements. (I have compiled both baseline and contender with -O2 and run both tests again)

```
time ../baseline && time ../contender 

real	0m20.849s
user	0m20.035s
sys	0m0.812s

real	0m6.126s
user	0m5.930s
sys	0m0.196s
```

((20.035-5.930)/20.035)*100 = 70%

**Comment by GilesBathgate** [comment]
@lrineau Can you reopen this one too.

**Comment by afabri** [comment]
Hi @GilesBathgate,  I just made the pull request #5522 that should accelerate Boolean operations.   I am a little bit puzzled by the fact that you focus on the initial construction.  When I generate the Nef polyhedron of two spheres,  and intersect them I spend 80% in the Boolean operation and only 20% in the initial construction.

**Comment by GilesBathgate** [comment]
@afabri This is because I don't understand the code in the boolean operation. I did understand that Normals calculations and coplanarity checks could be improved so I addressed these first. But I am beginning to understand some of the other code now, such as the K3 tree point locator.

**Comment by GilesBathgate** [comment]
@afabri I did find a small optimisation here:

https://github.com/CGAL/cgal/blob/74af3e7d33e7354e4090a1b17941a3f0c372ca8d/Nef_2/include/CGAL/Nef_2/Segment_overlay_traits.h#L547-L570

This can be rewritten to avoid duplication call (when assertions are on) to `K.orientation(s1,p)` (which is expensive in the profiler):

```c++
CGAL::Comparison_result
    operator()(const ISegment& is1, const ISegment& is2) const
    {
      if ( is2 == s_top || is1 == s_bottom ) return CGAL::SMALLER;
      if ( is1 == s_top || is2 == s_bottom ) return CGAL::LARGER;
      if ( is1 == is2 ) return CGAL::EQUAL;
      // Precondition: p is contained in s1 or s2.
      const Segment_2& s1 = is1->first;
      const Segment_2& s2 = is2->first;

      int s = -K.orientation(s1,p);
      if ( s == 0 )
        s = K.orientation(s2,p);
      else
        CGAL_assertion_msg( K.orientation(s2,p) == 0, "compare error in sweep.");

      if( s || K.is_degenerate(s2) || K.is_degenerate(s1))
        return o2c(s);

      return o2c(K.orientation(s2,K.target(s1)));
    }
```

**Comment by GilesBathgate** [comment]
@afabri For the history books, this is where I first discovered the normals optimisation in my own code :joy: https://github.com/GilesBathgate/RapCAD/commit/80dd54681aea5283a552a65edf8d059eb7e7accd#diff-069c246b7fdb3ccf197676886aa2a2c5ac842276ea4df9d5eff9c62faf34da28R78

**Comment by afabri** [comment]
It is not a misunderstanding. After all the error handlers are configurable. I only took assertions as something to verify my assumptions in the middle of my code.  Ideally we had preconditions which checked the input.  From then on assertions should
only trigger in case there is a bug in our code.

**Comment by GilesBathgate** [comment]
@afabri Ah yes ok. It might be appropriate for our projects to disable Assertions/Warnings, but keep Preconditions and Postconditions. I am just unsure whether the co-planarity check in #5455 is meant to be a precondition or just to verify an assumption of the code :confused:
