### ISSUE TITLE
Removal of connected components invalidates the mesh

### ISSUE THREAD

**Issue by oleg-alexandrov** [CGAL/cgal#5383]
## Issue Details

I tried to use the example at 

cgal/Polygon_mesh_processing/examples/Polygon_mesh_processing/connected_components_example.cpp

to remove connected components. I am getting as a result an invalid mesh as the functions invoked there do not clean up the mesh after they are done with it. 

What helped is to invoke on the mesh the function collect_garbage() I found somewhere else.

I am not a very experienced user of CGAL, so this may need to be verified, but if that is the case, I will suggest this function call be added in this example as well as to any other examples which leave the mesh in an indeterminate state.

## Environment

* Operating system Linux 64 bit
* Compiler: gcc
* CGAL version: 5
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by sloriot** [comment]
Could you please provide the input you used as well as what tells you that the mesh is invalid?

**Comment by oleg-alexandrov** [comment]
The input is a large file. A very fast way of testing this, should you desire to, is to create a .ply mesh with two connected components, with the first being smaller than the second. Then invoke that code in a way in which the first smaller connected component will be wiped, and then save the result as a .ply while. Then you can diff the old file with the new file.

In my experience, if the vertex indices say were 0, 1, 2 in the first connected component, and 3, 4, 5, 6, 7 in the second component, then after the mesh is cleaned and saved to disk, the first three vertices are not written, but a triangle which say had vertices 3, 4, 7 stays the same, instead of now those indices being renamed to 0, 1, 4. So the bookkeeping is wrong.

**Comment by sloriot** [comment]
Is it an issue only with the ply format?

**Comment by oleg-alexandrov** [comment]
I did not test with other formats. My suspicion is, as before, that the functions which remove connected components mark them for deletion but don't actually delete them, so maybe it has a flag to mark valid vertices, or something. 

If some subsequent functions can handle correctly such a mesh with invalidated vertices, I guess it is fine. If not, a bad mesh will be written. 

If you can't reproduce this with a simple mesh with two connected components, let me know and I can dig deeper. It should be simple for you though, one just has to follow that code.

**Comment by sloriot** [comment]
I don't have any issue with the following code (or I don't get what your issue is):

https://gist.github.com/sloriot/0fa684b015215ea414b779fdf4ab3f7a

**Comment by oleg-alexandrov** [comment]
Thank you for verifying this. Using your code I am getting the following invalid mesh:

ly
format ascii 1.0
comment Generated by the CGAL library
element vertex 8
property double x
property double y
property double z
element face 6
property list uchar int vertex_indices
end_header
-1 -1 -1
1 -1 -1
1 1 -1
-1 1 -1
-1 1 1
-1 -1 1
1 -1 1
1 1 1
4 8 9 10 7
4 6 5 4 3
4 5 10 9 4
4 4 9 8 3
4 3 8 7 6
4 6 7 10 5

This is a bad mesh, because some triangles have the index 10, which is not a valid vertex given that many vertices got removed by the cleanup.

If you don't get the same result, it means something changed since my CGAL version. I have CGAL 5.x, with commit b8f90e1a753118609aecc65b635e2776590fdeeb from GitHub.

Thank you for your attention again.

**Comment by sloriot** [comment]
I can reproduce the issue with the hash given but not with 5.1 nor 5.2. Could you please update and try again?

**Comment by oleg-alexandrov** [comment]
I trust you then that the issue is fixed. I very much appreciate your attention. Next time I should do a more thorough job and first check the latest version. Thank you again.
