### ISSUE TITLE
IS there a function to output .obj file

### ISSUE THREAD

**Issue by tub-sgg** [CGAL/cgal#5385]
in the library there is a function( read_OBJ) , however I have not found a function write_OBJ  for Surface_mesh

**Comment by MaelRL** [comment]
Before CGAL 5.3, there is no explicit `write_OBJ()` function, you have to use the writer `CGAL::File_writer_wavefront` as done [here](https://github.com/CGAL/cgal/blob/5.2.x-branch/Polyhedron/demo/Polyhedron/Scene_surface_mesh_item.cpp#L1533).

In upcoming CGAL 5.3 and already integrated in the master branch, there is now a `write_OBJ()`, see [doc](https://cgal.geometryfactory.com/CGAL/doc/master/BGL/group__PkgBGLIoFuncsOBJ.html#ga4d13f5fd5466959b2836e3dd26f85bd9) / [code](https://github.com/CGAL/cgal/blob/master/BGL/include/CGAL/boost/graph/IO/OBJ.h).
