### ISSUE TITLE
Talos Security Advisory for Linux Kernel (TALOS-2021-1243)

### ISSUE THREAD

**Issue by CiscoTalos** [CGAL/cgal#5404]
Hello,
The Cisco Talos team found a security vulnerability affecting Linux Kernel v5.4.66 and v5.4.54. As this is a sensitive security issue, this message is to request an email contact/maintainer handling and PGP key for further communication. If there's an option to mark this issue as private, we can place the details here.

For further information about the Cisco Vendor Vulnerability Reporting and Disclosure Policy please refer to this document which also links to our public PGP key. https://tools.cisco.com/security/center/resources/vendor_vulnerability_policy.html

Please CC vulndev@cisco.com on all correspondence related to this issue.

###Tested Versions
Linux Kernel v5.4.54 
Linux Kernel v5.4.66

**Comment by lrineau** [comment]
I let you inform the Linux kernel team.
