### ISSUE TITLE
METIS partition graph type conversion error

### ISSUE THREAD

**Issue by maximecharriere** [CGAL/cgal#5410]
# Issue Details
In [partition_graph()](https://doc.cgal.org/latest/BGL/group__PkgBGLPartition.html#gae7e37b6101e63f4c5959f1ae6c6fe7d2) function that we can found in `CGAL-5.1.1/include/CGAL/boost/graph/METIS/partition_graph.h` the `nparts` parameter is an `int`.
Inside partition_graph(), the METIS_PartMeshNodal() function (from `metis.h`) is called, and it take `nparts` as parameter.

The problem is that in METIS_PartMeshNodal(), `nparts` is of type `idx_t*` and not `int*`.
`idx_t` is a typedef for `long long` so it doesn't seem to me that conversion should be a problem, but VisualStudio throw me this error: 

```
'int METIS_PartMeshNodal(idx_t *,idx_t *,idx_t *,idx_t *,idx_t *,idx_t *,idx_t *,real_t *,idx_t *,idx_t *,idx_t *,idx_t *)': cannot convert argument 7 from 'int *' to 'idx_t *'
```

Somebody know why he don't want to convert an `int*` to an `long long *` ?

# Environment
Operating system: Windows 10, 64 bits
Compiler: MSVC 14.2
Release or debug mode: Release
CGAL version: 5.1.1
Boost version: 1.74.0
Eigen version: 3.3.9
Metis version: 5.1.0

**Comment by MaelRL** [comment]
Could you please provide some code with the issue?

**Comment by maximecharriere** [comment]
This error occurred while compiling the [polyhedron_partition.cpp](https://github.com/CGAL/cgal/blob/master/BGL/examples/BGL_polyhedron_3/polyhedron_partition.cpp) (see line 50) example.

The definition of `partition_graph()` is:
```c++
template<typename TriangleMesh, typename METIS_options, typename NamedParameters>
void partition_graph(const TriangleMesh& tm,
                     int nparts,
                     METIS_options options, // pointer to the options array
                     const NamedParameters& np)
```
and inside of it, this function is called:
```c++
METIS_PartMeshNodal(&ne, &nn, eptr, eind,
                              nullptr /* nodes weights */, nullptr /* nodes sizes */,
                              &nparts,
                              nullptr /* partitions weights */,
                              *options,
                              &objval, epart, npart);
```
Definition of `METIS_PartMeshNodal()`:
```c++
typedef long long     int64_t;
typedef int64_t       idx_t;
METIS_API(int) METIS_PartMeshNodal(idx_t *ne, idx_t *nn, idx_t *eptr, idx_t *eind,
                  idx_t *vwgt, idx_t *vsize, idx_t *nparts, real_t *tpwgts, 
                  idx_t *options, idx_t *objval, idx_t *epart, idx_t *npart);
```
So `METIS_PartMeshNodal()` is waiting a `long long*` as 7th argument but `&nparts` is a `int*`.

**Comment by maximecharriere** [comment]
By manually casting nparts before taking his adress, it worked. But it's durty
```c++
METIS_PartMeshNodal(&ne, &nn, eptr, eind,
                              nullptr /* nodes weights */, nullptr /* nodes sizes */,
                              &(idx_t)nparts,
                              nullptr /* partitions weights */,
                              *options,
                              &objval, epart, npart);
```

**Comment by sloriot** [comment]
@MaelRL is there an easy fix or shall we postpone the issue?
