### ISSUE TITLE
! K().collinear_3_object()(p,q,r)

### ISSUE THREAD

**Issue by benlaurie** [CGAL/cgal#5422]
_Please use the following template to help us solving your issue._

## Issue Details

Sorry this is a bit elaborate, but its the shortest I know to cause the problem. Run this and you get the following error:

CGAL error: precondition violation!
Expression : ! K().collinear_3_object()(p,q,r)
File       : /usr/local/include/CGAL/Kernel/function_objects.h
Line       : 1780

## Source Code

https://gist.github.com/benlaurie/2ce3742ed454242ab2ef8dc21d82ee8c

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): FreeBSD
* Compiler: FreeBSD clang version 8.0.1 (tags/RELEASE_801/final 366581) (based on LLVM 8.0.1)
* Release or debug mode: Debug
* Specific flags used (if any):
* CGAL version: 5.2
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by sloriot** [comment]
Adding:
```
  Vector n;
  if (collinear(p0,p1,p2))
    std::cerr << "Points are collinear!\n";
  else
    n = CGAL::normal(p0, p1, p2);
```
it works and you will see that you have 8 degenerate faces.

**Comment by sloriot** [comment]
As you can see with the following code, the [PMP function](https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__normal__grp.html#gaa76c6d307b9d3e48cafacd7b77b2c043) handles degenerate faces, you better use that function if you can have degenerate faces.

```
  Vector n = CGAL::Polygon_mesh_processing::compute_face_normal(f, surf);
  if (collinear(p0,p1,p2))
  {
    std::cerr << "Points are collinear!\n";
    assert(n==CGAL::NULL_VECTOR);
  }
```

**Comment by benlaurie** [comment]
But surely the presence of degenerate faces is a bug, since all I did was combine meshes with no degeneracy?

In other words: how do I avoid having degenerate faces in the first place?

**Comment by benlaurie** [comment]
Also, if I incorporate your suggested workaround, unsurprisingly the next subtraction operation gives me this error:

```
CGAL error: assertion violation!
Expression : oxz_pqr != COLLINEAR
File       : /usr/local/include/CGAL/predicates/kernel_ftC3.h
Line       : 188
```

**Comment by sloriot** [comment]
1) replace Cartesian with:
```
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
typedef CGAL::Exact_predicates_inexact_constructions_kernel Kernel;
```
See [FAQ](https://www.cgal.org/FAQ.html#inexact_NT)

2) If in addition you don't want to use a kernel with exact constructions (to get better runtime performances) then you have to deal with rounding issues.

You can use the following code:

```
void Subtract(Mesh *dest, Mesh *src)
{
  try{
    CGAL::Polygon_mesh_processing::corefine_and_compute_difference(*dest,
                   *src,
                   *dest, CGAL::parameters::throw_on_self_intersection(true));
  }
  catch(CGAL::Corefinement::Self_intersection_exception&)
  {
    // only on dest as src is generated and should be fine
    CGAL::Polygon_mesh_processing::experimental::remove_self_intersections(*dest);
    CGAL::Polygon_mesh_processing::corefine_and_compute_difference(*dest,
             *src,
             *dest, CGAL::parameters::throw_on_self_intersection(true));
  }
}
```
Note that the experimental function is experimental and might not be able to fix all issues (you can check the return type of the function).

Also since the repair is only done during before the differnce, you need an extra call
```
CGAL::Polygon_mesh_processing::experimental::remove_self_intersections(stock);
```
before the final write to STL (or any use of a mesh that should be self-intersection free.

**Comment by benlaurie** [comment]
Cool, thanks, but wouldn't it make sense to deal with these issues in the difference function?

**Comment by sloriot** [comment]
If you want a clean solution, you will need 3D snap rounding which unfortunately as of today does not have any usable implementation AFAIK.

**Comment by benlaurie** [comment]
Sorry, it took a while to be able to test this. I do need performance, so if I do as you suggest, I get this error:

CGAL error: precondition violation!
Expression : orientation(p0, p1, p2, p3) == POSITIVE
File       : /home/ben/local/include/CGAL/Delaunay_triangulation_3.h

This happens when `tool4` gets subtracted.

**Comment by benlaurie** [comment]
This is built in Debug mode, of course.

**Comment by benlaurie** [comment]
Incidentally, your other suggestion doesn't work either - I have to use `Exact_predicates_exact_constructions_kernel` - and that's very slow, of course.

**Comment by sloriot** [comment]
You got an issue with Epick? Could you post the program I should run to reproduce the issue?

**Comment by benlaurie** [comment]
Problem with Cartesian<double>: https://gist.github.com/benlaurie/99be0e2ec6d6d3fca843978ec38a1b4a - dies at tool4 in debug mode, hangs in release mode.

I was wrong about ``Exact_predicates_inexact_constructions_kernel`` - that one is just a warning - however, it seems to be a warning related to hole-filling - but there shouldn't be holes? Code is here: https://gist.github.com/benlaurie/c0f8f1bea0d6d9daa3f5a07bc3d0e3ca

**Comment by sloriot** [comment]
You should not use `Cartesian<double>` as Kernel pour doing Boolean operations, you at least need exact predicates.

About the warning, it is gone in https://github.com/CGAL/cgal/pull/5424

**Comment by benlaurie** [comment]
That's a shame, it is really very slow using exact predicates.

Thanks for the !warning.

**Comment by sloriot** [comment]
using Exact_predicates_inexact_constructions_kernel?

**Comment by benlaurie** [comment]
By operation 14 it is taking over a minute per subtraction.

**Comment by benlaurie** [comment]
BTW, were you expecting to have to remove self intersections with that kernel?
