### ISSUE TITLE
Intersection of Bbox_3 or Iso_cuboid_3 with axis aligned planes fails

### ISSUE THREAD

**Issue by raphaelsulzer** [CGAL/cgal#5428]
## Issue Details

Intersection of Bbox_3 or Iso_cuboid_3 with axis aligned planes fails with inexact as well as exact construction kernel, with the following runtime error:

```
/usr/include/boost/optional/optional.hpp:1107: boost::optional<T>::reference_type boost::optional<T>::get() [with T = boost::variant<CGAL::Line_3<CGAL::Epick>, CGAL::Plane_3<CGAL::Epick> >; boost::optional<T>::reference_type = boost::variant<CGAL::Line_3<CGAL::Epick>, CGAL::Plane_3<CGAL::Epick> >&]: Assertion `this->is_initialized()' failed.
```

## Source Code

```
    IK_to_EK to_exact;

    EPICK::Plane_3 pl(Point(0,0,0),Point(1,0,0),Point(0,1,0));
    EPECK::Plane_3 epl = to_exact(pl);

    vector<Point> pts;
    pts.push_back(Point(-10,-10,-10));
    pts.push_back(Point(10,10,10));
    Bbox cub = CGAL::bbox_3(pts.begin(), pts.end());
    EPECK::Iso_cuboid_3 ecub = to_exact(cub);

    auto result = intersection(cub,pl);    
    auto result = intersection(ecub,epl);
```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Ubuntu 18.04
* Compiler: gcc 7.5.0
* Release or debug mode: Release
* CGAL version: 5.1.1
* Boost version: 1.7.5

**Comment by afabri** [comment]
I confirm that there is a bug. I have a PR in draft state.  As I wrote I have  to take another look at the code, as I think it may not compute the right thing even in simple cases when using a kernel with inexact constructions.

**Comment by lrineau** [comment]
Fixed by https://github.com/CGAL/cgal/pull/5435.
