### ISSUE TITLE
How to use CGAL::Euler::remove_center_vertex() ?

### ISSUE THREAD

**Issue by raphaelsulzer** [CGAL/cgal#5437]
## Issue Details

My goal is to simplify a surface mesh with the following steps:
1) Detect ransac planes using the mesh vertex points.
2) Snap mesh vertices to their closest ransac planes
3) Successfully fix resulting self intersections with PMP::experimental::remove_self_intersections() and check that the mesh is closed
4) Collect fans for which the center vertices only have adjacent vertices snapped to the same plane
5) Now I would like to remove the vertices collected in 4) with CGAL::Euler::remove_center_vertex()

If I am not mistaken, in theory, this should not produce new self-intersections or lead to any other problems. However, in practice it does, and I am not sure why. Is it because of inexact constructions of new faces? How could I achieve what I want to do?

The code below where I try to remove the vertices goes in some endless loop.
If I stop at the last successful removal it outputs:
```
Halfedge connectivity Face removed in 1603
Halfedge connectivity hprev removed in 1603
```
If I try to check the mesh validity after each removal I get:
```
#faces: iterated: 87159 vs number_of_faces(): 87158
```

Any help would be greatly appreciated.

## Source Code
```
# collect vertices to remove

  set<SurfaceMesh::Halfedge_index> removals;
  bool remove;
  auto vh = data.smesh.vertices().begin();
  while(vh != data.smesh.vertices().end()){

      if(vstatus[*vh] != PLANE){
          vh++;
          continue;
      }

      auto first_hedge = data.smesh.halfedge(*vh);
      const auto target = data.smesh.target(first_hedge);
      auto next_hedge = first_hedge;
      remove = true;
      while(remove){
          const auto source = data.smesh.source(next_hedge);
          if(vplane[source] != vplane[target])
              remove = false;
          next_hedge = data.smesh.next_around_target(next_hedge);
          if(next_hedge == first_hedge)
              break;
      }
      if(remove){
          removals.insert(first_hedge);
          vcolor[*vh] = CGAL::green();
      }
      vh++;
  }

# try to remove the vertices

    vector<SurfaceMesh::Halfedge_index> rev;
    for(auto r : removals)
        rev.push_back(r);
    for(int i = 0; i < rev.size(); i++){
        cout << "try edge " << i << "/" << rc;
        if(new_mesh.is_valid(rev[i])){
            cout << ": removed" << endl;
            CGAL::Euler::remove_center_vertex(rev[i],new_mesh);
        }
    }

```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Ubuntu 18.04
* Compiler: gcc 7.5.0
* Release or debug mode: Release
* CGAL version: 5.1.1
* Boost version: 1.7.5

**Comment by sloriot** [comment]
not that if you call `remove_center_vertex` you will no longer have a triangle mesh in general  so you cannot call `remove_self_intersections for example.

**Comment by raphaelsulzer** [comment]
Yes, I understand that. I call `remove_self_intersection` before and I do not care about not having a triangle mesh after calling `remove_center_vertex`. What I do not understand is why CGAL goes in an endless loop when calling `remove_center_vertex` on many coplanar fans of my mesh.

**Comment by pentacular** [comment]
Have you checked that the preconditions of remove_center_vertex are maintained?

**Comment by sloriot** [comment]
Without a minimal example showing the problem, it is hard to tell you what can go wrong. You can try to call [`is_valid_polygon_mesh()`](https://doc.cgal.org/latest/BGL/group__PkgBGLHelperFct.html#gafa3bc673513c8750321bf062afd5e6b7) before calling the Euler function.

**Comment by pentacular** [comment]
Be careful to ensure that you've met the pre-conditions for remove_center_vertex (and the other euler operations).

I've found that it's easy to miss some by accident and have things go strangely wrong later on.

I was also trying to simplify coplanar faces using euler operations, but am now extracting the edges and reconstructing via arrangement and stitching.

**Comment by sloriot** [comment]
@pentacular if you are interested in simplifying coplanar patches of faces, I do have some code doing that if you are interested.

**Comment by pentacular** [comment]
> @pentacular if you are interested in simplifying coplanar patches of faces, I do have some code doing that if you are interested.

Yes, I am very interested in this. :)

Particularly if it works on Surface_mesh.

**Comment by sloriot** [comment]
Check #5461, and call `CGAL::Polygon_mesh_processing::decimate(sm);` Feedback in the PR is welcome.

**Comment by pentacular** [comment]
> Check #5461, and call `CGAL::Polygon_mesh_processing::decimate(sm);` Feedback in the PR is welcome.

That looks very cool -- particularly the support for constrained edges.
But I'm really looking to reduce a polyhedron to an outline -- like a set of 3d polygons with holes.

**Comment by sloriot** [comment]
Have a look at `tag_corners_and_constrained_edges()` then. It will mark vertices to be kept and tag faces per coplanar patch.
