### ISSUE TITLE
Mesh Boolean attach face information 

### ISSUE THREAD

**Issue by petrasvestartas** [CGAL/cgal#5440]
I am trying to follow this example file @sloriot :
https://github.com/CGAL/cgal/blob/master/Polygon_mesh_processing/examples/Polygon_mesh_processing/corefinement_mesh_union_with_attributes.cpp

The goal is to track original mesh id after boolean methods.

The method crashes in line 50 when I run mesh boolean with visitor. Without visitor it works.
Can someone help me debug where I am making the mistake?
The goal is to run multiple meshes with visitor, that is why I am using vector.

https://gist.github.com/petrasvestartas/606b9e2809c907922eee35791745180e

`

    /////////////////////////////////////////////////////////////////
    //Create Mesh List
    /////////////////////////////////////////////////////////////////
    std::vector< Mesh > meshList;
    std::vector<Mesh::Property_map<Mesh::Face_index, int>> meshList_id;
    
    Mesh   out;
    Mesh::Property_map<Mesh::Face_index, int>  out_id = out.add_property_map<Mesh::Face_index, int> ("f:id", -1).first;

    int numOfValidMeshes = 0;

    for ( size_t i = 0; i < n_mesh; i++ ) {

        CGAL::Surface_mesh<CGAL::Exact_predicates_inexact_constructions_kernel::Point_3>  tempMesh;
        
        for ( int j = n_coord_meshArray[i]; j < n_coord_meshArray[i + 1]; j++ ) {
            tempMesh.add_vertex (CGAL::Epick::Point_3 (coord_mesh[3 * j + 0], coord_mesh[3 * j + 1], coord_mesh[3 * j + 2]));
        }

        for ( int j = n_faces_meshArray[i]; j < n_faces_meshArray[i + 1]; j++ ) {
            tempMesh.add_face (CGAL::SM_Vertex_index (faces_mesh[3 * j + 0]), CGAL::SM_Vertex_index (faces_mesh[3 * j + 1]), CGAL::SM_Vertex_index (faces_mesh[3 * j + 2]));
        }

        if ( tempMesh.is_valid (false) ) {
             meshList.push_back (tempMesh);
             numOfValidMeshes++;
        }
    }

    /////////////////////////////////////////////////////////////////
    //Add Visitor
    /////////////////////////////////////////////////////////////////
    Visitor visitor;
    for ( int i = 0; i < meshList.size (); i++ ) {
        Mesh::Property_map<Mesh::Face_index, int>  mesh_id = meshList[i].add_property_map<Mesh::Face_index, int> ("f:id", -1).first;

        for ( Mesh::Face_index f : faces (meshList[i]) )
                mesh_id[f] = (i+1);

        meshList_id.push_back (mesh_id);
        visitor.properties[&meshList[i]] = meshList_id[i];// mesh_id;
    }
    visitor.properties[&out] = out_id;

     //////////////////////////////////////////////////////////////////
     //// Perform CGAL Boolean
     //////////////////////////////////////////////////////////////////
     CGAL::Surface_mesh<CGAL::Exact_predicates_inexact_constructions_kernel::Point_3>  mesh0 = meshList[0];
     CGAL::Surface_mesh<CGAL::Exact_predicates_inexact_constructions_kernel::Point_3>  mesh1 = meshList[1];
     bool valid_union = CGAL::Polygon_mesh_processing::corefine_and_compute_union (mesh0, mesh1, out, CGAL::Polygon_mesh_processing::parameters::visitor (visitor));

`

**Comment by sloriot** [comment]
I think the issues comes from the fact that mesh0 and mesh1 are copies of `meshList[0]` and `meshList[1]` and properties in the visitor are not resized upon modification of meshes. Try taking references or update the visitor to use mesh0 and mesh1.

```
 CGAL::Surface_mesh<CGAL::Exact_predicates_inexact_constructions_kernel::Point_3>&  mesh0 = meshList[0];
 CGAL::Surface_mesh<CGAL::Exact_predicates_inexact_constructions_kernel::Point_3>& mesh1 = meshList[1];
```

**Comment by petrasvestartas** [comment]
Dear @sloriot ,

It works. Thank you.
But I have a similar issue what I want to perform Boolean Mesh with visitor for more than meshes.

This code normally works with multiple meshes, but using visitor I have the same problem when running 3 or more meshes:


    CGAL::Surface_mesh<CGAL::Exact_predicates_inexact_constructions_kernel::Point_3>& lastMesh = meshList[0];
    for ( int i = 1; i < meshList.size (); i++ ) {//meshList.size ()

        bool valid_union = false;
        const bool throw_on_self_intersection = true;

        try {
            if ( Difference_Union_Intersection == 1 ) {
                valid_union = CGAL::Polygon_mesh_processing::corefine_and_compute_union (lastMesh, meshList[i], out, CGAL::Polygon_mesh_processing::parameters::visitor (visitor), CGAL::Polygon_mesh_processing::parameters::throw_on_self_intersection (true));//, , CGAL::Polygon_mesh_processing::parameters::throw_on_self_intersection (true) , CGAL::Polygon_mesh_processing::parameters::visitor (visitor)
            } else if ( Difference_Union_Intersection == 2 ) {
                valid_union = CGAL::Polygon_mesh_processing::corefine_and_compute_intersection (lastMesh, meshList[i], out, CGAL::Polygon_mesh_processing::parameters::visitor (visitor), CGAL::Polygon_mesh_processing::parameters::throw_on_self_intersection (true)); //, CGAL::Polygon_mesh_processing::parameters::visitor (visitor)
            } else {
                valid_union = CGAL::Polygon_mesh_processing::corefine_and_compute_difference (lastMesh, meshList[i], out, CGAL::Polygon_mesh_processing::parameters::visitor (visitor), CGAL::Polygon_mesh_processing::parameters::throw_on_self_intersection (true));//, CGAL::Polygon_mesh_processing::parameters::visitor (visitor)
            }
            if ( valid_union ) {
                //myfile << "\n Valid Boolean";
                lastMesh = out;
            } else {
                //myfile << "\n Not Valid Boolean";
                lastMesh = meshList[i];
            }
        } catch ( const std::exception& e ) {
            lastMesh = meshList[i];
        }
        out.clear ();
    }
    out = lastMesh;

    std::ofstream myfile3;
    myfile3.open ("C:\\libs\\PInvokeCPPCSHARP\\PInvoke\\x64\\Release\\TrackFaceIDEnd.txt");

    for ( Mesh::Face_index f : faces (out) ) {
        myfile3 << f << " ID" << out_id[f] << " \n";
    }

    myfile3.close ();

**Comment by sloriot** [comment]
Try to create the visitor in the scoop of the loop that way it will be associated to the current meshes

**Comment by petrasvestartas** [comment]
Dear @sloriot ,

I am trying to get around this problem for several hours. I print values to .txt files myfile3, application crashes:

 ```
   CGAL::Surface_mesh<CGAL::Exact_predicates_inexact_constructions_kernel::Point_3>& lastMesh = meshList[0];
    Mesh::Property_map<Mesh::Face_index, int>  lastMesh_id = lastMesh.add_property_map<Mesh::Face_index, int> ("f:id", -1).first;
    for ( Mesh::Face_index f : faces (lastMesh) )
      lastMesh_id[f] = 1;


    for ( int i = 1; i < meshList.size (); i++ ) {//meshList.size ()

        Visitor visitor;

        //Properties last mesh
        visitor.properties[&lastMesh] = lastMesh_id;//From previous iteration must or must not contain property map?

        ////Properties current mesh
        Mesh::Property_map<Mesh::Face_index, int>  mesh_id = meshList[i].add_property_map<Mesh::Face_index, int> ("f:id", -1).first;
        for ( Mesh::Face_index f : faces (meshList[i]) )
            mesh_id[f] = (i + 1);
        visitor.properties[&meshList[i]] = mesh_id;

        ////Properties Out
        Mesh   out;
        Mesh::Property_map<Mesh::Face_index, int>  out_id = out.add_property_map<Mesh::Face_index, int> ("f:id", -1).first;
        visitor.properties[&out] = out_id;

        bool valid_union = false;
        const bool throw_on_self_intersection = true;

        try {

            if ( Difference_Union_Intersection == 1 ) {
                valid_union = CGAL::Polygon_mesh_processing::corefine_and_compute_union (lastMesh, meshList[i], out,  CGAL::Polygon_mesh_processing::parameters::throw_on_self_intersection (true), CGAL::Polygon_mesh_processing::parameters::visitor (visitor));//, , CGAL::Polygon_mesh_processing::parameters::throw_on_self_intersection (true) , CGAL::Polygon_mesh_processing::parameters::visitor (visitor)
            } else if ( Difference_Union_Intersection == 2 ) {
                valid_union = CGAL::Polygon_mesh_processing::corefine_and_compute_intersection (lastMesh, meshList[i], out,  CGAL::Polygon_mesh_processing::parameters::throw_on_self_intersection (true), CGAL::Polygon_mesh_processing::parameters::visitor (visitor)); //, CGAL::Polygon_mesh_processing::parameters::visitor (visitor)
            } else {
                valid_union = CGAL::Polygon_mesh_processing::corefine_and_compute_difference (lastMesh, meshList[i], out, CGAL::Polygon_mesh_processing::parameters::throw_on_self_intersection (true), CGAL::Polygon_mesh_processing::parameters::visitor (visitor));//, CGAL::Polygon_mesh_processing::parameters::visitor (visitor)
            }

            lastMesh = valid_union ? out : meshList[i];

        } catch ( const std::exception& e ) {
            lastMesh = meshList[i];
        }

    }


    std::ofstream myfile3;
    myfile3.open ("C:\\libs\\PInvokeCPPCSHARP\\PInvoke\\x64\\Release\\TrackFaceIDEnd.txt");
    for ( Mesh::Face_index f : faces (lastMesh) ) 
        myfile3 << f << " ID" << lastMesh_id[f] << " \n";
    myfile3.close ();
```

**Comment by petrasvestartas** [comment]
This worked, I do not why:)

![Preview00](https://user-images.githubusercontent.com/18013985/107244867-cc168580-6a2e-11eb-9b25-8291c9517b90.png)
```


    CGAL::Surface_mesh<CGAL::Exact_predicates_inexact_constructions_kernel::Point_3>& lastMesh = meshList[0];
    Mesh::Property_map<Mesh::Face_index, int>  lastMesh_id = lastMesh.add_property_map<Mesh::Face_index, int> ("f:id", -1).first;
    for ( Mesh::Face_index f : faces (lastMesh) )
        lastMesh_id[f] = 1;


    for ( int i = 1; i < meshList.size (); i++ ) {//meshList.size ()

        Visitor visitor;

        //Properties last mesh
        //Mesh::Property_map<Mesh::Face_index, int>  lastMesh_id = lastMesh.add_property_map<Mesh::Face_index, int> ("f:id", -1).first;
        //for ( Mesh::Face_index f : faces (lastMesh) )
        //    lastMesh_id[f] = 1;
        visitor.properties[&lastMesh] = lastMesh_id;//From previous iteration must or must not contain property map?

        ////Properties current mesh
        Mesh::Property_map<Mesh::Face_index, int>  mesh_id = meshList[i].add_property_map<Mesh::Face_index, int> ("f:id", -1).first;
        for ( Mesh::Face_index f : faces (meshList[i]) )
            mesh_id[f] = (i + 1);
        visitor.properties[&meshList[i]] = mesh_id;

        ////Properties Out
        Mesh   out;
        Mesh::Property_map<Mesh::Face_index, int>  out_id = out.add_property_map<Mesh::Face_index, int> ("f:id", -1).first;
        visitor.properties[&out] = out_id;

        bool valid_union = false;
        const bool throw_on_self_intersection = true;

        try {

            if ( Difference_Union_Intersection == 1 ) {
                valid_union = CGAL::Polygon_mesh_processing::corefine_and_compute_union (lastMesh, meshList[i], out, CGAL::Polygon_mesh_processing::parameters::visitor (visitor), CGAL::Polygon_mesh_processing::parameters::throw_on_self_intersection (true));//, , CGAL::Polygon_mesh_processing::parameters::throw_on_self_intersection (true) , CGAL::Polygon_mesh_processing::parameters::visitor (visitor)
            } else if ( Difference_Union_Intersection == 2 ) {
                valid_union = CGAL::Polygon_mesh_processing::corefine_and_compute_intersection (lastMesh, meshList[i], out, CGAL::Polygon_mesh_processing::parameters::visitor (visitor), CGAL::Polygon_mesh_processing::parameters::throw_on_self_intersection (true)); //, CGAL::Polygon_mesh_processing::parameters::visitor (visitor)
            } else {
                valid_union = CGAL::Polygon_mesh_processing::corefine_and_compute_difference (lastMesh, meshList[i], out, CGAL::Polygon_mesh_processing::parameters::visitor (visitor), CGAL::Polygon_mesh_processing::parameters::throw_on_self_intersection (true));//, CGAL::Polygon_mesh_processing::parameters::visitor (visitor)
            }

            std::ofstream myfile3;
            myfile3.open ("C:\\libs\\PInvokeCPPCSHARP\\PInvoke\\x64\\Release\\TrackFaceIDEnd.txt");
            for ( Mesh::Face_index f : faces (out) )
                myfile3 << f << " ID" << out_id[f] << " \n";
            myfile3.close ();

            lastMesh = valid_union ? out : meshList[i];
            
            //for ( Mesh::Face_index f : faces (out) )
            //    lastMesh_id[f] = out_id[f];

            lastMesh_id = lastMesh.add_property_map<Mesh::Face_index, int> ("f:id", -1).first;
            for ( Mesh::Face_index f : faces (out) ){
                auto faceID = out_id[f];
                lastMesh_id[f] = faceID;
            }
         


        } catch ( const std::exception& e ) {
            lastMesh = meshList[i];
        }

    }

```

**Comment by sloriot** [comment]
In the code not working you were using a property of one mesh (lastMesh) with the face descriptors of another mesh (out).

```
            lastMesh_id = lastMesh.add_property_map<Mesh::Face_index, int> ("f:id", -1).first;
            for ( Mesh::Face_index f : faces (out) ){
                auto faceID = out_id[f];
                lastMesh_id[f] = faceID;
            }
```
