### ISSUE TITLE
out_degree() documentation missing?

### ISSUE THREAD

**Issue by pentacular** [CGAL/cgal#5443]
## Issue Details

out_degree is mentioned in a precondition
https://doc.cgal.org/latest/BGL/group__PkgBGLEulerOperations.html#gac0e8aebb3072d5dd67487ce40205f318

The function appears to exist and work, but I cannot find the documentation for out_degree in the web site.

Searching for out_degree gives "no matches"

Just opening an issue for future reference, before I forget about it.

**Comment by afabri** [comment]
You are right that it is missing in the documentation.   It comes from the boost graph library and is documented [here](https://www.boost.org/doc/libs/1_57_0/libs/graph/doc/graph_concepts.html).
