### ISSUE TITLE
URL in CMakeLists.txt pointing to a NSFW website

### ISSUE THREAD

**Issue by thomassiju** [CGAL/cgal#5448]
_Please use the following template to help us solving your issue._

## Issue Details

In the CMakeLists.txt file (CGAL-5.2), there is a URL on line 412 that points to a NSFW website. Probably, the domain expired and it was reassigned. 

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Linux
* Compiler:
* Release or debug mode:
* Specific flags used (if any):
* CGAL version: 5.2
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by afabri** [comment]
Can you add a link please,  There is no line 412   in[ this file](https://github.com/CGAL/cgal/blob/5.2.x-branch/CMakeLists.txt).

**Comment by MaelRL** [comment]
https://github.com/CGAL/cgal/blob/5.2.x-branch/Installation/CMakeLists.txt#L412.

Seemingly been dead for a while, since issues like https://github.com/Imagick/imagick/issues/210 pop up.

**Comment by afabri** [comment]
@joachim-reichel is that something you consider important to keep?

**Comment by lrineau** [comment]
> [https://github.com/CGAL/cgal/blob/5.2.x-branch/Installation/CMakeLists.txt#L412](https://github.com/CGAL/cgal/blob/5.2.x-branch/Installation/CMakeLists.txt?rgh-link-date=2021-02-10T16%3A22%3A46Z#L412).
> 
> Seemingly been dead for a while, since issues like [Imagick/imagick#210](https://github.com/Imagick/imagick/issues/210) pop up.
> 
> Replacement? [abi-laboratory.pro/?view=timeline&l=cgal](https://abi-laboratory.pro/?view=timeline&l=cgal) (comes from what you get on [http://upstream.rosalinux.ru](http://upstream.rosalinux.ru/) + CGAL). Not really up-to-date though...

That is meaningless anyway, and can be removed, now that we have decided to drop non-header-only mode for CGAL-5.3.

**Comment by joachim-reichel** [comment]
No, not needed anymore IMHO.
