### ISSUE TITLE
Useless x=x

### ISSUE THREAD

**Issue by mglisse** [CGAL/cgal#5466]
https://github.com/CGAL/cgal/blob/0dcff365d063bac5e159b53346566d1c22209b55/Kernel_23/include/CGAL/rational_rotation.h#L141

The definition above is `NT & den = denom;` so this is really doing denom=denom, not very useful. Same for the 2 lines above.
(ok, this showed a bug in some code I was writing, so not 100% useless...)

**Comment by afabri** [comment]
Why not removing `NT & den = denom`  and the occurrences of `den` with `denom` in the function.

**Comment by afabri** [comment]
@mglisse do you agree with what I propose, namely to just remove the local vaiables,, so that I can just do it for both functions?   Shall I at the same time drop in some `CGAL::square()` ?

**Comment by mglisse** [comment]
Assuming the function is otherwise fine, sure, removing the alias and using directly the true name seems good.
`square`: if you want. I have no idea what types this function is typically used with, but it can't hurt.
