### ISSUE TITLE
Lazy Intersect_point_3

### ISSUE THREAD

**Issue by mglisse** [CGAL/cgal#5471]
## Issue Details

I noticed some new code in Lazy.h, introduced in #5090, which looks suspicious. Why is it ok to use a global LazyPointRep for the returned object? See the testcase below for an issue this causes. I didn't see any kind of documentation or comment, so maybe there are restrictions on how this functor may be used? The code has a generic-looking name (Lazy_construction_optional) but actually hardcodes that it can only be used for Intersect_point_3, so I wouldn't be that surprised to discover other restrictions.

## Source Code

```c++
#include <CGAL/Exact_predicates_exact_constructions_kernel.h>
typedef CGAL::Epeck K;
int main(){
  K::Plane_3 a(rand(),rand(),rand(),rand());
  K::Plane_3 b(rand(),rand(),rand(),rand());
  K::Plane_3 c(rand(),rand(),rand(),rand());
  K::Plane_3 d(rand(),rand(),rand(),rand());
  K::Intersect_point_3 inter;
  auto i1 = inter(a,b,c);
  auto i2 = inter(a,b,d);
}
```
> free(): invalid pointer

or phrased differently
> attempting free on address which was not malloc()-ed

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): linux 64
* Compiler: gcc-10
* CGAL version: master

**Comment by afabri** [comment]
It is an implementation detail for the envelope code. There we know that at any point in time we only have to do with a single point.

**Comment by mglisse** [comment]
It would be nice to add a comment about it in the code, so it is a bit less confusing.

**Comment by sloriot** [comment]
@afabri please add a comment.

**Comment by lrineau** [comment]
> It is an implementation detail for the envelope code. There we know that at any point in time we only have to do with a single point.

The naming of that functor should indicate that it is an internal implementation detail. No need for a comment if the naming is right.

**Comment by afabri** [comment]
@mglisse   did you run into this because you need an intersection that does not produce a variant?
@lrineau suggested to rename  the functor `Intersect_point_3`  to `Intersect_point_3_for_polygonal_envelope`.    
  
Remains the issue of dispatching to lazy functors in `Lazy_kernel.h` just based on the result type being `boost::optional`.  For now only the `Intersect_point_3` functor is concerned, but in case someone adds a functor that does not return a singleton in the optional, it has to be split.

**Comment by mglisse** [comment]
> @mglisse did you run into this because you need an intersection that does not produce a variant?

No, I ran into the code trying to merge master into the branch mt-glisse, so I had to modify this code to match that branch, and the first step was understanding what it does to avoid breaking it. The testcase was just a way to clarify what seemed strange to me.
