### ISSUE TITLE
SOR CGAL  PointSet

### ISSUE THREAD

**Issue by petrasvestartas** [CGAL/cgal#5477]
Hi,

I am trying to follow SOR outlier removal tutorial from here:
https://doc.cgal.org/latest/Point_set_processing_3/Point_set_processing_3_2remove_outliers_example_8cpp-example.html

But it works with Point vector.
Is there any possibility to use a PointSet with color also?
If yes is it possible to show a code example?

When I try to use pointset instead of point vector I get following error:
![image](https://user-images.githubusercontent.com/18013985/108521547-208df080-72cc-11eb-9a6f-6ae12e3c18de.png)

**Comment by sgiraudot** [comment]
It does work with Point Set, but you need to change all structures that depend on the point range type (see [documentation](https://doc.cgal.org/latest/Point_set_processing_3/group__PkgPointSetProcessing3Algorithms.html#ga1ab1dcee59caadde50572c5a504cc41a)). In your case:
- the return type is not `std::vector<Point_3>::iterator` anymore but `Point_set::iterator`
- the default point map not longer works, you need to use the [point map of the point set](https://doc.cgal.org/latest/Point_set_3/classCGAL_1_1Point__set__3.html#aa738f987bd96ad8e86e558d3cd9278e9), either by doing `CGAL::parameters::point_map(points.point_map()).threshold_percent(100.). /* etc */`, or by using directly [the named parameters base provided by Point set](https://doc.cgal.org/latest/Point_set_3/classCGAL_1_1Point__set__3.html#a02ef886d19ffa53faf527625c633c81c) `point_set.parameters().threshold_percent(100.). /* etc */`

Something like this should work:
```c++
Point_set::iterator first_to_remove
   = CGAL::remove_outliers<CGAL::Parallel_if_available_tag>(points, nb_neighbors,
     points.parameters().threshold_percent(100).threshold_distance(2 * average_spacing));
```
