### ISSUE TITLE
CGAL_TEST_SUITE with CTest

### ISSUE THREAD

**Issue by mglisse** [CGAL/cgal#5479]
## Issue Details

I followed the instructions from https://github.com/CGAL/cgal/wiki/Testing to run the testsuite with CTest:
```sh
mkdir build
cd build
cmake -DBUILD_TESTING=ON -DWITH_examples=ON -DWITH_tests=ON ..
nice ctest -j16
```
and I had to kill test_validity_sampled_data after 5h (it was using 30G of memory). This is a non-optimized build, so I expect programs to run slow, but the main issue is that the macro CGAL_TEST_SUITE was not defined, so it went for the expensive test. I don't know if it should be defined by default, or if the documentation should mention that we need to define this macro in CXXFLAGS, but the current behavior when following the documentation is not good.

(there are other expensive tests, but not the same order of magnitude, test_triply_periodic_minimal_surfaces 1800s, Triangle_coordinates_speed_test 1100s)

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): linux 64
* Compiler: gcc-10
* Release or debug mode: not optimized
* Specific flags used (if any):
* CGAL version: master

**Comment by sloriot** [comment]
I'm using that often without `CGAL_TEST_SUITE` and don't have any problem. Were you using master or your branch? (with `CMAKE_BUILD_TYPE=Debug`)

**Comment by mglisse** [comment]
It was my branch, but it doesn't touch any cmake stuff. CMAKE_BUILD_TYPE was empty. How long does test_validity_sampled_data take for you without CGAL_TEST_SUITE on a debug build?

**Comment by sloriot** [comment]
I'm running it...

**Comment by lrineau** [comment]
> I'm running it...

Then, three days after, what was the outcome?

**Comment by sloriot** [comment]
I had to kill it because I had a meeting and it was taking too much memory. I restarted it this morning and it keeps filling my memory (22GB for now). It is in Shape_detection btw.

**Comment by sloriot** [comment]
It is strange cause I never noticed it in the past. I wonder if it has always been like that of it is due to an update of the package. Maybe @sgiraudot @danston know more.

**Comment by sloriot** [comment]
I only realize know that there is 
```
#ifndef CGAL_TEST_SUITE // Disable tests too large for testsuite
  test_copied_point_cloud (points, 20);
  test_copied_point_cloud (points, 50);
#endif
```
in the test file and which is probably why you mentioned `CGAL_TEST_SUITE`...

I'm killing the test as my memory is almost filled now.

**Comment by mglisse** [comment]
Yes, sorry if I wasn't clear enough. Running the testsuite "old-style" defines CGAL_TEST_SUITE (I think, otherwise you would have noticed), but not with ctest, and that has an impact on some tests. Some other tests also check for an environment variable at runtime, which I think is defined even with ctest.

**Comment by lrineau** [comment]
> Yes, sorry if I wasn't clear enough. Running the testsuite "old-style" defines CGAL_TEST_SUITE (I think, otherwise you would have noticed), but not with ctest, and that has an impact on some tests.

Actually CTest cannot control the CMake configuration. I am open to suggestions. In my opinion, there should not be any test dependending on `CGAL_TEST_SUITE`. If a package author wants a more complex testsuite, then it should depend on something else, like `CGAL_SHAPE_DETECTION_EXPENSIVE_TESTSUITE`.

> Some other tests also check for an environment variable at runtime, which I think is defined even with ctest.

That is for the Qt5 basic_viewer: an example from `examples/Triangulation_2/` might try to popup a Qt5 drawing widget, because of a call to [`CGAL::draw`](https://doc.cgal.org/latest/Triangulation_2/group__PkgDrawTriangulation2.html#ga5b2aa57d37e1b52c7f4a3a879fd40dfc). We wanted the testsuite to compile that call but avoid the blocking widget at runtime.

**Comment by mglisse** [comment]
> I am open to suggestions.

Document in the wiki page on Testing that people may wish to add this to CXXFLAGS?

> it should depend on something else

I'll let you discuss that with the maintainers of that package.

> We wanted the testsuite to compile that call but avoid the blocking widget at runtime.

It would be possible to do that here as well, compile the expensive calls, but disable them at runtime based on the environment.

I don't really care which way you go as long as the next person following the wiki instructions is less likely to hit this issue.

**Comment by lrineau** [comment]
Fixed by https://github.com/CGAL/cgal/pull/5487.
