### ISSUE TITLE
Rounding exact scalars to integers

### ISSUE THREAD

**Issue by alecjacobson** [CGAL/cgal#548]
I'd like to round an arbitrary precision number (e.g. `CGAL::Epeck::FT e`) to the nearest integer:

so if e is an arbitrary precision input number and i <= e < i where i is an integer then I assume the following (usual) rounding rule:

    if e < i+0.5  --> i
    otherwise     --> i+1

Can I trust that `std::round(CGAL::to_double(e))` will give the correct rounding result? I guess I'm asking if it's possible that `e<0.5` but `CGAL::to_double(e) >= 0.5` (or `e>=0.5` but `CGAL::to_double(e)<0.5`). I suppose there could also be issues with very large doubles?

**Comment by sloriot** [comment]
Use `to_interval` to get a safe bounds.

**Comment by alecjacobson** [comment]
K, thanks for the solution. In answer to the original question: Will `std::round(CGAL::to_double(e))` ever give the _wrong_ result? (That is, different from using `to_interval` and finding the closest integer?)

**Comment by sloriot** [comment]
`to_double` gives the <i>middle</i> of the interval, but since the interval might contains several integers there is no guarantee you'll get the nearest integer.
