### ISSUE TITLE
Compute distances between a mesh and pointset

### ISSUE THREAD

**Issue by petrasvestartas** [CGAL/cgal#5481]
Is it possible to find all distances between points in a pointset and a mesh?

In the documentation I see only max distance:

https://doc.cgal.org/latest/Polygon_mesh_processing/Polygon_mesh_processing_2hausdorff_distance_remeshing_example_8cpp-example.html#a4

**Comment by sloriot** [comment]
You'll have to use the AABB-tree by yourself and call [squared_distance()](https://doc.cgal.org/latest/AABB_tree/classCGAL_1_1AABB__tree.html#a24efb545081b6796d8843861a4bf49e6).

An example of how build a tree is available [here](https://doc.cgal.org/latest/AABB_tree/AABB_tree_2AABB_face_graph_triangle_example_8cpp-example.html). You can of course replace `Polyhedron` by `Surface_mesh` if you need to.

**Comment by sloriot** [comment]
Note that you can make the calls in parallel if you want.
