### ISSUE TITLE
stl hash missing for CGAL::internal::OMesh_edge

### ISSUE THREAD

**Issue by unclejimbo** [CGAL/cgal#5493]
## Issue Details

For `OMesh_edge` defined here
https://github.com/CGAL/cgal/blob/1a040c8552c6f68c3ed57f918634d30e3416517e/STL_Extension/include/CGAL/hash_openmesh.h#L18-L22

partial specialization of `hash` is missing in the stl namespace

`hash_value` here only works for boost
https://github.com/CGAL/cgal/blob/1a040c8552c6f68c3ed57f918634d30e3416517e/STL_Extension/include/CGAL/hash_openmesh.h#L70-L74

## Source Code

The following code won't compile when `Mesh` is OpenMesh type
```
template<typename Mesh>
std::unordered_set<typename boost::graph_traits<Mesh>::edge_descriptor> eset;
```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Linux 64
* Compiler: g++/clang++
* Release or debug mode: 
* Specific flags used (if any):
* CGAL version: 5.1.2
* Boost version: 1.75.0
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by afabri** [comment]
I confirm and work on it.
