### ISSUE TITLE
Finding closed (watertight) volumes in polygon soup

### ISSUE THREAD

**Issue by Rockambole** [CGAL/cgal#550]
Polygon connectivity data is known, i.e. element incidences + edge connections

Does CGAL deal with this problem?

**Comment by sloriot** [comment]
Could you be more precise?

**Comment by Rockambole** [comment]
I've studied the problem and think I've solved it using iteration. Between iterations I remove any polygons which are confirmed being part of 1 or 2 compartments (found by studying connection info on boundary edges) thereby successively reducing the problem until all polygons have been confirmed. Very fast, very stable😊
