### ISSUE TITLE
Cartesian_kernel: Warning in Circle_3

### ISSUE THREAD

**Issue by maxGimeno** [CGAL/cgal#5506]
## Issue Details

There is a warning in a test of Kernel_23 : https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-Ic-73/Kernel_23/TestReport_lrineau_ArchLinux-CXX17-Release.gz
The problem lies here: 
```cpp
 struct Rep
  {
    Sphere_3 first;
    Plane_3 second;
    Rep () : first(), second() { }
    Rep (const Sphere_3& s, const Plane_3& p) : first(s), second(p) { }
  };
  ```
Replacing the `Rep` by an std::pair fixes the warning, but is there a reason why `Rep` is a struct in the first place ? 

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): archlinux cxx14 and 17
* Compiler:c++ (GCC) 10.2.0
* Release or debug mode:Release
* Specific flags used (if any):-Wall -O3 -msse4.1 -std=gnu++17 -DCGAL_NDEBUG -O3
* CGAL version:5.1, 5.2, 5.3

**Comment by lrineau** [comment]
> is there a reason why `Rep` is a struct in the first place ?

e9505dc8405f... @sgiraudot?

Simon has not given context in his commit message, but I think it might be because of the bug https://bugs.llvm.org/show_bug.cgi?id=22085 from libc++ or clang.

**Comment by MaelRL** [comment]
The explanation is in https://github.com/CGAL/cgal/pull/561.

(Just to advertise the Github search to find PRs given a commit hash, because it's pretty convenient. Here: https://github.com/CGAL/cgal/search?q=e9505dc8405f55326606ef87fe1fb7c761bb093e+is%3Apr&type=issues)

**Comment by sgiraudot** [comment]
Yes, this is exactly the PR given by Mael. I don't know if using a pair still creates problem now, but it's probably worth verifying before reverting to  `std::pair`.

**Comment by afabri** [comment]
Or `std::tuple`?

**Comment by maxGimeno** [comment]
tuple doesn't have a `first` and `second` members, so it will require far more changes than `pair`.

**Comment by maxGimeno** [comment]
It still doesn't work with pair on AppleClang with an `std::pair`, but `boost::tuple` works fine.

**Comment by lrineau** [comment]
Fixed by https://github.com/CGAL/cgal/pull/5561
