### ISSUE TITLE
unpredictable error in CGAL::intersection(Line_3,Line_3)

### ISSUE THREAD

**Issue by Mzzzzzzzzz** [CGAL/cgal#5511]
## Issue Details

i try to use the function CGAL::intersection() to compute the intersect point of two Line_3,but when the data contains a lot of decimals , it returns false AND i am sure those two lines are in the same plane. During my debugging process，i found the function Orientation_3() which is in the Coplanar_3.h always returns false when the data contains a lot of decimals. for example like 2.123131313131

## Source Code
```
Point_3 face1_a = Point_3(-2.06965 3.12872 -0.0454252);
Point_3 face1_b = Point_3(10.8649 -2.46452 -0.0454252);
Point_3 face1_c = Point_3(16.4714 10.5006 -0.0484785);
Point_3 face1_d = Point_3(3.53679 16.0938 -0.0484785);

Point_3 face2_a = Point_3(4.90314 10.0936 4.63226);
Point_3 face2_b = Point_3(11.1826 7.47561 4.63226);
Point_3 face2_c = Point_3(11.2751 7.69749 -0.26809);
Point_3 face2_d = Point_3(4.99564 10.3155 -0.26809);

Plane3 cgal_plane1 = Plane_3(face1_a,face1_b,face1_c);
Plane3 cgal_plane2 = Plane_3(face2_a,face2_b,face2_c);

CGAL::cpp11::result_of<K::Intersect_3(Plane_3, Plane_3)>::type result = CGAL::intersection(cgal_plane1, cgal_plane2);
    Line_3* s;
    if (result) {
        s = boost::get<Line_3>(&*result);
    }
    else {
        return false;
    }

Line_3 s_projection = Line_3(cgal_plane1.projection(s->point(1)),cgal_plane1.projection(s->point(5)));
Line_3 face1_diagonal_a_c = Line_3(face1_a,face1_c);

Point_3 * p ;
CGAL::cpp11::result_of<K::Intersect_3(Line_3, Line_3)>::type cross_s_face1_diagonal_a_c = CGAL::intersection(face1_diagonal_a_c, s_projection);
if(cross_s_face1_diagonal_a_c){
    p = boost::get<Point_3>(&*cross_s_face1_diagonal_a_c);
}
```
## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):Windows 64bits
* Compiler:QT creator
* Release or debug mode:debug
* Specific flags used (if any):None
* CGAL version:5.1.1
* Boost version:1.74.0
* Other libraries versions if used (Eigen, TBB, etc.):None

**Comment by sloriot** [comment]
What Kernel are you using? Note that you need a kernel with exact constructions.

**Comment by Mzzzzzzzzz** [comment]
i typedef the CGAL::Exact_predicates_inexact_constructions_kernel k

**Comment by sloriot** [comment]
You need `CGAL::Exact_predicates_exact_constructions_kernel`. Could you try with this kernel?

**Comment by Mzzzzzzzzz** [comment]
i tryed CGAL::Exact_predicates_exact_constructions_kernel，and i get the same result. so i tryed the function CGAL::coplanar()
it returns false as well.

**Comment by sloriot** [comment]
I don't know what you are trying to do but the  program below prints:

```
intersection is a line
intersection is a point
```

which is what I expected.

```
#include <CGAL/Exact_predicates_exact_constructions_kernel.h>

#include <iostream>

typedef CGAL::Exact_predicates_exact_constructions_kernel K;
typedef K::Point_3 Point_3;
typedef K::Line_3 Line_3;
typedef K::Plane_3 Plane_3;

int main()
{
  Point_3 face1_a = Point_3(-2.06965, 3.12872,-0.0454252);
  Point_3 face1_b = Point_3(10.8649, -2.46452, -0.0454252);
  Point_3 face1_c = Point_3(16.4714, 10.5006 ,-0.0484785);
  Point_3 face1_d = Point_3(3.53679, 16.0938, -0.0484785);

  Point_3 face2_a = Point_3(4.90314, 10.0936, 4.63226);
  Point_3 face2_b = Point_3(11.1826, 7.47561, 4.63226);
  Point_3 face2_c = Point_3(11.2751 ,7.69749, -0.26809);
  Point_3 face2_d = Point_3(4.99564, 10.3155, -0.26809);

  Plane_3 cgal_plane1 = Plane_3(face1_a,face1_b,face1_c);
  Plane_3 cgal_plane2 = Plane_3(face2_a,face2_b,face2_c);

  CGAL::cpp11::result_of<K::Intersect_3(Plane_3, Plane_3)>::type result = CGAL::intersection(cgal_plane1, cgal_plane2);
      Line_3* s;
      if (result) {
          s = boost::get<Line_3>(&*result);
          if (s == nullptr)
          {
            std::cout << "intersection is not a line\n";
            return 1;
          }
          else
            std::cout << "intersection is a line\n";
      }
      else {
        std::cout << "no plane intersection\n";
          return 1;
      }

  Line_3 s_projection = Line_3(cgal_plane1.projection(s->point(1)),cgal_plane1.projection(s->point(5)));
  Line_3 face1_diagonal_a_c = Line_3(face1_a,face1_c);

  Point_3 * p ;
  CGAL::cpp11::result_of<K::Intersect_3(Line_3, Line_3)>::type cross_s_face1_diagonal_a_c = CGAL::intersection(face1_diagonal_a_c, s_projection);
  if(cross_s_face1_diagonal_a_c){
      p = boost::get<Point_3>(&*cross_s_face1_diagonal_a_c);
    if (p==nullptr)
      std::cout << "intersection is not a point\n";
    else
      std::cout << "intersection is a point\n";
    }
  else
    std::cout << "no line intersection\n";
  return 0;
}
```

**Comment by Mzzzzzzzzz** [comment]
> I don't know what you are trying to do but the program below prints:
> 
> ```
> intersection is a line
> intersection is a point
> ```
> 
> which is what I expected.
> 
> ```
> #include <CGAL/Exact_predicates_exact_constructions_kernel.h>
> 
> #include <iostream>
> 
> typedef CGAL::Exact_predicates_exact_constructions_kernel K;
> typedef K::Point_3 Point_3;
> typedef K::Line_3 Line_3;
> typedef K::Plane_3 Plane_3;
> 
> int main()
> {
>   Point_3 face1_a = Point_3(-2.06965, 3.12872,-0.0454252);
>   Point_3 face1_b = Point_3(10.8649, -2.46452, -0.0454252);
>   Point_3 face1_c = Point_3(16.4714, 10.5006 ,-0.0484785);
>   Point_3 face1_d = Point_3(3.53679, 16.0938, -0.0484785);
> 
>   Point_3 face2_a = Point_3(4.90314, 10.0936, 4.63226);
>   Point_3 face2_b = Point_3(11.1826, 7.47561, 4.63226);
>   Point_3 face2_c = Point_3(11.2751 ,7.69749, -0.26809);
>   Point_3 face2_d = Point_3(4.99564, 10.3155, -0.26809);
> 
>   Plane_3 cgal_plane1 = Plane_3(face1_a,face1_b,face1_c);
>   Plane_3 cgal_plane2 = Plane_3(face2_a,face2_b,face2_c);
> 
>   CGAL::cpp11::result_of<K::Intersect_3(Plane_3, Plane_3)>::type result = CGAL::intersection(cgal_plane1, cgal_plane2);
>       Line_3* s;
>       if (result) {
>           s = boost::get<Line_3>(&*result);
>           if (s == nullptr)
>           {
>             std::cout << "intersection is not a line\n";
>             return 1;
>           }
>           else
>             std::cout << "intersection is a line\n";
>       }
>       else {
>         std::cout << "no plane intersection\n";
>           return 1;
>       }
> 
>   Line_3 s_projection = Line_3(cgal_plane1.projection(s->point(1)),cgal_plane1.projection(s->point(5)));
>   Line_3 face1_diagonal_a_c = Line_3(face1_a,face1_c);
> 
>   Point_3 * p ;
>   CGAL::cpp11::result_of<K::Intersect_3(Line_3, Line_3)>::type cross_s_face1_diagonal_a_c = CGAL::intersection(face1_diagonal_a_c, s_projection);
>   if(cross_s_face1_diagonal_a_c){
>       p = boost::get<Point_3>(&*cross_s_face1_diagonal_a_c);
>     if (p==nullptr)
>       std::cout << "intersection is not a point\n";
>     else
>       std::cout << "intersection is a point\n";
>     }
>   else
>     std::cout << "no line intersection\n";
>   return 0;
> }
> ```

the function CGAL::intersection(Plane_3,Plane_3) doesn't work in my function ,but it works in the main function.i haven't figured it out ,so i changed it into 2d and get the right answer. 
But in any case, thanks a lot for giveing me an example
