### ISSUE TITLE
Isosurface from 3D Delaunay triangulation with vertex scalars

### ISSUE THREAD

**Issue by raphaelsulzer** [CGAL/cgal#5521]
## Issue Details

Is there a way to use the function below to extract an isosurface as a triangle mesh from an existing 3D Delaunay triangulation with a scalar value in [0, 1] for each vertex in the 3DT? If not, what would be an efficient way to keep track of vertices and triangle indices during construction of such a triangle mesh?

## Source Code

```
template <class SurfaceMeshC2T3,
          class Surface,
          class FacetsCriteria,
          class Tag >
void make_surface_mesh(SurfaceMeshC2T3& c2t3,
                       Surface surface,
                       FacetsCriteria criteria,
                       Tag);
```

**Comment by sloriot** [comment]
I don't think there is anything available out of the box. It makes me think to a marching tetrahedra algorithm. There might be a non-documented implementation somewhere in CGAL.

**Comment by MaelRL** [comment]
There is an internal marching tets [here](https://github.com/CGAL/cgal/blob/74af3e7d33e7354e4090a1b17941a3f0c372ca8d/Polyhedron/demo/Polyhedron/Plugins/Point_set/Surface_reconstruction_poisson_impl.cpp#L32).
