### ISSUE TITLE
jet_smooth_point_set.h(202): error C2338: Error: no SVD traits.

### ISSUE THREAD

**Issue by SunYueM** [CGAL/cgal#5523]
_Please use the following template to help us solving your issue._

## Issue Details

d:\vcpkg\installed\x86-windows\include\cgal\jet_smooth_point_set.h(202): error C2338: Error: no SVD traits

## Source Code

CGAL::jet_smooth_point_set<CGAL::Sequential_tag>(points,24);
This code from the CGAL manual in CGAL official website,  https://doc.cgal.org/5.1.2/Manual/tuto_reconstruction.html

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):windows 10 64bits
* Compiler:  vs2017
* Release or debug mode: x86 debug
* Specific flags used (if any):
* CGAL version: 5.1
* Boost version:1.73
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by sgiraudot** [comment]
You need the Eigen library to compile this example (you should have got a configuration error if you used the provided `CMakeLists.txt`).

**Comment by SunYueM** [comment]
> You need the Eigen library to compile this example (you should have got a configuration error if you used the provided `CMakeLists.txt`).

thank you so much! This problem had been solved，but the new one has arisen！
d:\vcpkg\installed\x86-windows\include\cgal\poisson_surface_reconstruction.h(104): error C2672: 'CGAL::Poisson_reconstruction_function<Kernel>::compute_implicit_function': no matching overloaded function found.

Code:
CGAL::poisson_surface_reconstruction_delaunay(points.begin(), points.end(),oints.point_map(), 
                                                                               points.normal_map(),output_mesh, spacing);

**Comment by ToHold** [comment]
Hi,

Can you tell me how did you solve your problem ? Because I've also tried to install Eigen3, it didnt change anything for me.
And the error still the same.

Regards,
Théo.

**Comment by sgiraudot** [comment]
What is the output you get from `cmake`? Was Eigen correctly found?

**Comment by ToHold** [comment]
Thanks for your fast answer.

`
vcpkg list

_other dependencies_
eigen3:x64-windows                                 3.3.7#7          C++ template library for linear algebra: matrice...
_other dependencies_
`

**Comment by ToHold** [comment]
Could you tell me where can I find the great cmake file. Sorry I'm begginer in CPP.

**Comment by sgiraudot** [comment]
The file `CMakeLists.txt` is provided with the example.

There is [a section about using CGAL on Windows in the manual](https://doc.cgal.org/latest/Manual/windows.html) that should help you.

**Comment by SunYueM** [comment]
My&nbsp;mistake&nbsp;is&nbsp;the&nbsp;included&nbsp;directory.it's&nbsp;result&nbsp;from&nbsp;my&nbsp;installed&nbsp;method&nbsp;of&nbsp;eigen3&nbsp;which&nbsp;simply&nbsp;installed&nbsp;by&nbsp;vcpkg.&nbsp;When&nbsp;using&nbsp;eigen,I&nbsp;must&nbsp;be&nbsp;#include<eigen3/Eigen/&hellip;&gt;，but&nbsp;#include<Eigen/&hellip;&gt;.
&nbsp;&nbsp;it's&nbsp;as&nbsp;simple&nbsp;as&nbsp;that.&nbsp;
&nbsp;&nbsp;Maybe，it&nbsp;couldn't&nbsp;help&nbsp;you,but&nbsp;it's&nbsp;just&nbsp;my&nbsp;experience.&nbsp;And&nbsp;I'm&nbsp;not&nbsp;good&nbsp;at&nbsp;English，Hope&nbsp;you&nbsp;can&nbsp;understand&nbsp;it.&nbsp;😂


---Original---
From: ***@***.***&gt;
Date: Wed, Mar 17, 2021 21:32 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [CGAL/cgal] jet_smooth_point_set.h(202): error C2338: Error: no SVD traits. (#5523)




 
Hi,
 
Can you tell me how did you solve your problem ? Because I've also tried to install Eigen3, it didnt change anything for me.
 And the error still the same.
 
Regards,
 Théo.
 
&mdash;

**Comment by SunYueM** [comment]
Yeah, just not found the eigen correctly. Thank you!



---Original---
From: "Simon ***@***.***&gt;
Date: Wed, Mar 17, 2021 21:34 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [CGAL/cgal] jet_smooth_point_set.h(202): error C2338: Error: no SVD traits. (#5523)




 
What is the output you get from cmake? Was Eigen correctly found?

**Comment by SunYueM** [comment]
To be frank, I'm not good at Cmake at all. sorry.&nbsp;I almost only use Vishal Studio programming, and rarely use Linux and GCC.&nbsp;



---Original---
From: ***@***.***&gt;
Date: Wed, Mar 17, 2021 21:45 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [CGAL/cgal] jet_smooth_point_set.h(202): error C2338: Error: no SVD traits. (#5523)




 
Could you tell me where can I find the great cmake file. Sorry I'm begginer in CPP.

**Comment by ToHold** [comment]
I've found a solution :

I'm using Visual Studio 2019. So I've installed vcpkg and used : 

vcpkg install cgal:x64-windows
vcpkg install boost:x64-windows
vcpkg install LAStools:x64-windows
 vcpkg install tbb:x64-windows
vcpkg install cgal[qt]:x64-windows
vcpkg.exe install qt5:x64-windows
vcpkg integrate install
cmake -DCMAKE_TOOLCHAIN_FILE=C:/Users/Admin/vcpkg-2020.11/scripts/buildsystems/vcpkg.cmake

And I've installed Eigen 3.3.9 from NuGet : In VS2019 => Tools/NuGet Package Manager => search for Eigen3 and install

**Comment by ToHold** [comment]
So I can create mesh from example file named : "kitten.xyz"

But I can't use ".las" file. I've tried to change Point_set to PointWithColors but I cant use this type for the rest of code.

Any idea ?

**Comment by SunYueM** [comment]
Nice! Man.&nbsp;



---Original---
From: ***@***.***&gt;
Date: Thu, Mar 18, 2021 19:19 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [CGAL/cgal] jet_smooth_point_set.h(202): error C2338: Error: no SVD traits. (#5523)




 
I've found a solution :
 
I'm using Visual Studio 2019. So I've installed vcpkg and used :
 
vcpkg install cgal:x64-windows
 vcpkg install boost:x64-windows
 vcpkg install LAStools:x64-windows
 vcpkg install tbb:x64-windows
 vcpkg install cgal[qt]:x64-windows
 vcpkg.exe install qt5:x64-windows
 vcpkg integrate install
 cmake -DCMAKE_TOOLCHAIN_FILE=C:/Users/Admin/vcpkg-2020.11/scripts/buildsystems/vcpkg.cmake
 
And I've installed Eigen 3.3.9 from NuGet : In VS2019 =&gt; Tools/NuGet Package Manager =&gt; search for Eigen3 and install

**Comment by SunYueM** [comment]
Sorry!
Due to personal ability and time, I don't have more energy to study CGAL carefully.&nbsp; I consider writing some relatively simple and easy-to-understand programs by myself so that I can publish papers and graduate more quickly.

So,maybe I couldn't help you much more.

---Original---
From: ***@***.***&gt;
Date: Thu, Mar 18, 2021 19:22 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [CGAL/cgal] jet_smooth_point_set.h(202): error C2338: Error: no SVD traits. (#5523)




 
So I can create mesh from example file named : "kitten.xyz"
 
But I can't use ".las" file. I've tried to change Point_set to PointWithColors but I cant use this type for the rest of code.
 
Any idea ?

**Comment by ToHold** [comment]
Thanks a lot 😉 !
