### ISSUE TITLE
cgal\poisson_surface_reconstruction.h(104): error C2672. Could you help me? thanks!

### ISSUE THREAD

**Issue by SunYueM** [CGAL/cgal#5524]
_Please use the following template to help us solving your issue._

## Issue Details
1>d:\vcpkg\installed\x86-windows\include\cgal\poisson_surface_reconstruction.h(104): error C2672: 'CGAL::Poisson_reconstruction_function<Kernel>::compute_implicit_function': no matching overloaded function found

## Source Code

Source code is from CGAL user manual .address:  https://doc.cgal.org/5.1.2/Manual/tuto_reconstruction.html

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):windows 64
* Compiler: vs2017
* Release or debug mode:debug
* Specific flags used (if any): 
* CGAL version: 5.1
* Boost version:1.73
* Other libraries versions if used (Eigen, TBB, etc.): eigen 3.3.7#7

**Comment by lrineau** [comment]
Check in `d:\vcpkg\installed\x86-windows\include\cgal\version.h` which CGAL version you have installed with vcpkg. Maybe that is not version 5.1.

**Comment by sloriot** [comment]
If you did not pass the linear solver as parameter and expect to use Eigen,   `CGAL_EIGEN3_ENABLED` must be defined and eigen should be in the include path. This should be added automatically by cmake.

**Comment by SunYueM** [comment]
> Check in `d:\vcpkg\installed\x86-windows\include\cgal\version.h` which CGAL version you have installed with vcpkg. Maybe that is not version 5.1.

#define CGAL_VERSION 5.1-I-900

**Comment by SunYueM** [comment]
> If you did not pass the linear solver as parameter and expect to use Eigen, `CGAL_EIGEN3_ENABLED` must be defined and eigen should be in the include path. This should be added automatically by cmake.

I don't good at using cmake. how to do if I don't use cmake?  Could u teach me how to define 'GAL_EIGEN3_ENABLED'?

**Comment by sloriot** [comment]
It is automatically done by   this command:
`target_link_libraries(poisson_reconstruction_example  PUBLIC CGAL::Eigen3_support)` where `poisson_reconstruction_example` is the name of your exe/target.

Note that you can simply add `#define CGAL_EIGEN3_ENABLED` before including the Poisson CGAL header (if Eigen is already in the include path)

**Comment by SunYueM** [comment]
> It is automatically done by this command:
> `target_link_libraries(poisson_reconstruction_example PUBLIC CGAL::Eigen3_support)` where `poisson_reconstruction_example` is the name of your exe/target.
> 
> Note that you can simply add `#define CGAL_EIGEN3_ENABLED` before including the Poisson CGAL header (if Eigen is already in the include path)

Thank  you very much ! I think i finded the problem: All of the third party dependencies were installed by vcpkg,but the included directory in this code can't achieve some third party dependencies direcctly.
