### ISSUE TITLE
Issue in Point Set Processing documentation

### ISSUE THREAD

**Issue by maximecharriere** [CGAL/cgal#5531]
## Issue Details

Is it normal that the documentation on the CGAL website for the `read_ply_points_with_properties()` function is on the [`CGAL Namespace Reference` ](https://doc.cgal.org/latest/Point_set_processing_3/namespaceCGAL.html#a483fe42bbefcafce8a5d6194573a2715) page and not with the others [IO PLY functions](https://doc.cgal.org/latest/Point_set_processing_3/group__PkgPointSetProcessing3IOPly.html) ?

## Concerned package
**- Point_set_processing_3**

**Comment by lrineau** [comment]
Fixed by https://github.com/CGAL/cgal/pull/5536.
