### ISSUE TITLE
an issue about 2D arrangement

### ISSUE THREAD

**Issue by Mzzzzzzzzz** [CGAL/cgal#5543]
## Issue Details
Given a set of segments, I would like to compute the set of closed polygons inside the convex hull of the set of the end of those segments. The vertices of the polygons are the intersections of the segments. 
for example :
given the segments set
[(-1,1),(0,0)]  [(0,0),(1,1)]  [(-2,1),(2,1)] 
returns the polygon with vertex(0,0),(1,1),(-1,1)
so i follow the example of Arrangement_on_surface_2/global_insertion.cpp
but i got the result 
-0 -0
-1 1
-1.5 1
-1 1
1 1
1.5 1
1 1
-0 -0
1 -1
-0 -0
-1 -1
how could i solve that,please help me ,thanks!
## Source Code

#include <CGAL/Cartesian.h>
#include <CGAL/Quotient.h>
#include <CGAL/MP_Float.h>
#include <CGAL/Arr_segment_traits_2.h>
#include <CGAL/Arrangement_2.h>
#include <CGAL/Arr_naive_point_location.h>
#include "arr_print.h"
typedef CGAL::Quotient<CGAL::MP_Float>                Number_type;
typedef CGAL::Cartesian<Number_type>                  Kernel;
typedef CGAL::Arr_segment_traits_2<Kernel>            Traits_2;
typedef Traits_2::Point_2                             Point_2;
typedef Traits_2::X_monotone_curve_2                  Segment_2;
typedef CGAL::Arrangement_2<Traits_2>                 Arrangement_2;
typedef CGAL::Arr_naive_point_location<Arrangement_2> Naive_pl;

int main ()
{

  Arrangement_2     arr;
  Segment_2         S1 [3];
  S1[0] = Segment_2 (Point_2 (-1,1), Point_2 (0,0));
  S1[1] = Segment_2 (Point_2 (1,1), Point_2 (0,0));
  S1[2] = Segment_2 (Point_2 (-2,1), Point_2 (2,1));

  insert(arr, S1, S1 + 3);

  Arrangement_2::Face_const_iterator fit;
  Arrangement_2::Hole_const_iterator hi;

 for (fit = arr.faces_begin(); fit != arr.faces_end(); ++fit) {
        int index = 1;
        for (hi = fit->holes_begin(); hi != fit->holes_end(); ++hi, ++index) {
            Arrangement_2::Ccb_halfedge_const_circulator curr = *hi;
            do {
                temp.plane_seg_id = cuf->plane_seg_id;
                std::cout << curr->target()->point() << std::endl;
            } while (++curr != *hi);
            return_result.push_back(temp);
        }
    }
  std::cout << "The arrangement size:" << std::endl
            << "   V = " << arr.number_of_vertices()
            << ",  E = " << arr.number_of_edges()
            << ",  F = " << arr.number_of_faces() << std::endl;

  return 0;
}

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):Windows
* Compiler:vs code
* CGAL version:4.1.1

**Comment by efifogel** [comment]
I don't understand what you are trying to do.
Before you start with code, formally define your problem.
This is not an issue. cgal-discuss is more appropriate.
   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/
