### ISSUE TITLE
Is there is any feature of cutting the mesh by giving exact size of cut for boundary cutting using cgal library?

### ISSUE THREAD

**Issue by mikelars16** [CGAL/cgal#5553]
Respected All,
I have a set of 3D data mesh file which look uniform plane. I want to cut the boundary of this mesh by 0.09 cm using coding. I was researching and found the cgal library. I am very excited to work with this library. I tried the same using Meshlab software. But, I am unable to do cut the boundary mesh using cgal. I need mesh cutting for the boundary of 0.09 since I want to work on further processes using simulation, based on this mesh.
I have attached the link to the ".ply" file. I would like to know how to work with cgal to get such a kind of mesh result.
[Ply file link](https://drive.google.com/file/d/1BwXaB8pYTVOPXeCChL2gK7acjcEVKFpQ/view?usp=sharing)
Any leads will be appreciated.
Thanks in advance

**Comment by sloriot** [comment]
What does cut mean? You want to move the center of  a ball of 0.09 of radius on boundary edges and remove any part of the mesh that is inside the ball?

**Comment by nikhilpatil99** [comment]
> What does cut mean? You want to move the center of a ball of 0.09 of radius on boundary edges and remove any part of the mesh that is inside the ball?

I want to cut only the boundary of the mesh by 0.09 cm inside.i.e  cut the boundary of 3D mesh object
