### ISSUE TITLE
Not able to find file for Finalization of Reconstruction from Parallel Slices in code base 

### ISSUE THREAD

**Issue by anishsingh935** [CGAL/cgal#5558]
_Please use the following template to help us solving your issue._

## Issue Details

_Describe your issue. Please be specific (compilation error, runtime error, unexpected behavior, wrong results, etc.)._

## Source Code

_If your issue arises by using CGAL in your own source code, please provide a minimalist example that we can compile easily to reproduce the bug. If your issue arises from using a CGAL program (demo, example, etc.), please let us know which one. Helping you solving an issue is much easier and efficient if we can reproduce it._

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):
* Compiler:
* Release or debug mode:
* Specific flags used (if any):
* CGAL version:
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by anishsingh935** [comment]
Please help me

**Comment by sloriot** [comment]
Please read the instructions on the [project page](https://github.com/CGAL/cgal/wiki/Project-Ideas) and follow them.

**Comment by anishsingh935** [comment]
Ok Now I got it 
Thanks a lot for helping
