### ISSUE TITLE
The program can't start because gmp.dll is missing from your computer. Try reinstalling the program to fix this problem.

### ISSUE THREAD

**Issue by ZiniuLu** [CGAL/cgal#5567]
## Issue Details
I downloaded cgal:x64-windows via vcpkg and successfully generated the project with cmake-gui.

However, when I run the code "simple_mcfskel_sm_example.cpp" in "Debug" modus (VS2019), I got the error message: "The program can't start because gmp.dll is missing from your computer. Try reinstalling the program to fix this problem." When I switch to "Realease" modus, everything is fine.

I checked the file under the directory "_<project_dir>/build/Debug_". Thers is no "_gmp.dll_" but only a "_gmpd.dll_". Actually the "_gmp.dll_" is under "_<project_dir>/build/Realease_".

What should I do to copy "_gmp.dll_" automaticlly in DEBUG modus?

## Source Code
I am using the example code : "_simple_mcfskel_sm_example.cpp_" .

## Environment

* Operating system (Windows 10, 64 bit):
* Compiler: cmake-gui
* Release or debug mode: DEBUG
* Specific flags used (if any): all packages are up to date
* CGAL version:5.2.1
* Boost version: 1.75.0
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by GilesBathgate** [comment]
Did you download the accompanying [gmp and mpfr](https://github.com/CGAL/cgal/releases/download/v5.2.1/CGAL-5.2.1-win64-auxiliary-libraries-gmp-mpfr.zip) from the releases page?

**Comment by lrineau** [comment]
That is surprising. What has copied `gmpd.dll` in your build directory?

**Comment by ZiniuLu** [comment]
@GilesBathgate 
no. I just followed the official guide [(here)](https://doc.cgal.org/latest/Manual/windows.html) and installed cgal with vcpkg. I think all dependencies have been automaticlly installed.

**Comment by ZiniuLu** [comment]
@lrineau 
That is also my question. I didn't change anything in `CMakeList`.
What I did:
- `cmake-gui ..` --> generated `.sln` in _./build_
- opened the solution in VS 2019
- chose _Debug_ Modus
- Click _Build_ _Solution_ --> then I found `gmpd.dll` and `mpfr-6.dll` in the directory `./build/Debug`.

**Comment by lrineau** [comment]
That must be the [`vcpkg integrate` feature](https://github.com/microsoft/vcpkg/blob/master/docs/users/integration.md#integrate):
> This will implicitly add Include Directories, Link Directories, and Link Libraries for all packages installed with Vcpkg to all VS2015, VS2017 and VS2019 MSBuild projects. **We also add a post-build action for executable projects that will analyze and copy any DLLs you need to the output folder, enabling a seamless F5 experience.**

**Comment by ZiniuLu** [comment]
@lrineau 
Thanks for this Information! This is really helpful.

Accroding to this page [vcpkg integrate feature](https://github.com/microsoft/vcpkg/blob/master/docs/users/integration.md#integrate):
- **Release `.dll` files are installed to `installed\x64-windows\bin`**
- **Debug `.dll` files are installed to `installed\x64-windows\debug\bin`**

I found that there is really no `gmp.dll` under `vcpkg\installed\x64-windows\debug\bin`! 

After I copied the `gmp.dll` file into this directory and rebuild the solution, there are no missing libraries any more when I run 'simple_mcfskel_sm_example.cpp' in Debug Modus.

**Comment by lrineau** [comment]
@maxGimeno We should probably modify our `FindGMP.cmake` to deal with that situation. It seems that the GMP library can be named `gmpd.lib`/`gmpd.dll` in Debug. An improved version of `FindGMP.cmake` would search for gmp and gmpd separately.

[As far as I can see from Google](https://www.google.com/search?q=findgmp.cmake+%22gmpd%22), there is currently no `FindGMP.cmake` on the web that deal with gmpd. We will have to write our own.

**Comment by afabri** [comment]
Is there really  a need for a debug version of GMP when debugging a program that uses CGAL?

**Comment by lrineau** [comment]
> Is there really a need for a debug version of GMP when debugging a program that uses CGAL?

No, not really, but it seems the vcpkg integration does not copy `gmp.dll` in `Debug` directories. If the user program was linked with `gmpd.lib` instead of `gmp.lib`, then it would run automatically.

**Comment by lrineau** [comment]
Fixed by https://github.com/CGAL/cgal/pull/5578.
