### ISSUE TITLE
cannot open file mpir.lib, while mpir has conflicts with gmp

### ISSUE THREAD

**Issue by cuirq3** [CGAL/cgal#5574]
## Issue Details

Hi, I updated my cgal:x64-windows via vcpkg to run _obb_example.cpp_. And I generated the project using cmake successfully. 

I got a link error while debugging it with VS2019. It says that cannot open file **mpir.lib**, so I tried to install mpir via vcpkg.

However, I found an issue under vcpkg that there are conflicts between **gmp** and **mpir**. Here are links: 

https://github.com/microsoft/vcpkg/pull/12664#issue-459939778
https://github.com/microsoft/vcpkg/issues/11756#issuecomment-639320633

I wonder that is there any chance to use _oriented_bounding_box()_ without mpir or any other way to fix this problem.

Thanks!

## Environment

* Operating system (Windows 10, 64 bits):
* Compiler: cmake-gui
* Release or debug mode: debug
* Specific flags used (if any):
* CGAL version:5.2#2
* Boost version:1.75.0
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by maxGimeno** [comment]
At first we used mpir as dependency for cgal in vcpkg, but they changed it for gmp for linux compatibility. This must be the reason for your problem.
My advice would be to `vcpkg remove cgal mpir gmp`, and then to do:
```
vcpkg install yasm-tool:x86-windows
vcpkg install cgal
```
This should solve your problem.
