### ISSUE TITLE
LCC : uninitialized variable

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#5576]
## Issue Details

The [warning ](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-Ic-96/Linear_cell_complex_Examples/TestReport_lrineau_ArchLinux-CXX17-Release.gz) of the compiler that the variable `index`  may be uninitialized is correct, namely when the input file is not valid.
We could fix it by changing the return value from `void` to `bool` in `File_scanner_OFF.h`  `scan_facet_vertex_index()`and then do the right thing when the result is `false`.
This would not be a complete fix of dealing with invalid input but improve the situation a little bit.  

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):
* Compiler:
* Release or debug mode:
* Specific flags used (if any):
* CGAL version:
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by gdamiand** [comment]
I checked how it is done for Polyhedron, after a call to scan_facet_vertex_index, the ifstream is tested, when it is not valid the function exit.
I can do the same here if you want.
Note that this code is not robust to errors in off (there are many Todo); but this is a very low priority in my todo list.

**Comment by afabri** [comment]
I agree with what you propose.
