### ISSUE TITLE
Feature request: adaptive envelope

### ISSUE THREAD

**Issue by rjanvier** [CGAL/cgal#5581]
## Issue Details

I saw the nice addition of "Polyhedral Envelope Containment Check" for Polygon meshes and triangle soups in the 5.3 version. Do you think it would it be possible to add the ability of using it with a "per face eps. value" (that could be passed via a property map) ?
thanks.

**Comment by sloriot** [comment]
Yes it is possible and not hard to do I think.

**Comment by afabri** [comment]
This should not be that difficult.  What is your use case?

**Comment by rjanvier** [comment]
Thanks! I'm using it in the context of an advancing front method guided by an implicit function like this [paper](https://www.researchgate.net/profile/Marco-Centin/publication/323975958_Advancing_mesh_completion_for_digital_modeling_and_manufacturing/links/5abb3b47aca2722b0b7bde35/Advancing-mesh-completion-for-digital-modeling-and-manufacturing.pdf) I use it for interference checking with existing borders (my epsilon is local and function both of the local curvature + a sigma determined by some a priori knowledge on uncertainty of the data collection). I think, It can also be useful for adaptive mesh simplification.

**Comment by sloriot** [comment]
You can try #5583 (disclaimer: not tested)

**Comment by rjanvier** [comment]
thank you! It seems ok.
I used
`Envelope env_border(border_triangles, base_mesh, 0.0, CGAL::Polygon_mesh_processing::parameters::face_epsilon_map(f_epsilon));` then I fixed two different envelope sizes in my pmap and I used the CGAL_ENVELOPE_DEBUG define to output a off file with the prisms. 
![cgal_env01](https://user-images.githubusercontent.com/1537100/113491818-d5264f00-94d3-11eb-8ca4-815984bdc3e2.png)
