### ISSUE TITLE
Add a named parameter

### ISSUE THREAD

**Issue by maximecharriere** [CGAL/cgal#5591]
## Issue Details

I'm adding a function in my code based on the CGAL structure, and  I'm using named parameters.
I need to add a named parameter but I don't know how.

The declaration of my function look like this :
```c++
template <class PointRange1, class PointRange2, class NamedParameters1, class NamedParameters2>
bool transpose_properties(const PointRange1 &point_set_1, const PointRange2 &point_set_2, 
                          const NamedParameters1 &np1, const NamedParameters2 &np2);
```

It should be called this way :
```c++
CGAL::pointmatcher::transpose_properties(
		refHdMesh.vertices(), 
		scanHdMesh.vertices(),
		CGAL::parameters::point_map(refMesh.points())
		.CGAL::parameters::property_map(refColorPm)
		.matcher(matcher),
		CGAL::parameters::point_map(scanMesh.points())
		.CGAL::parameters::property_map(scanColorPm));
```
But `CGAL::parameters::property_map` is not know because it's a new named parameter.  

## Tried solution

I have added the following line in [parameters_interface.h](https://github.com/CGAL/cgal/blob/master/BGL/include/CGAL/boost/graph/parameters_interface.h) :

```c++
CGAL_add_named_parameter(property_map_t, property_map, property_map)
```

but this is not enough.  

----

**Can you help me find a solution?**

**Comment by sloriot** [comment]
`CGAL::parameters::` namespace if only needed for the first parameter of the pack (the following are member function calls)

`CGAL::parameters::point_map(refMesh.points()).property_map(refColorPm).matcher(matcher))`

**Comment by maximecharriere** [comment]
Thank you ! It was the problem
