### ISSUE TITLE
include Could not find requested files: CGAL_Eigen3_support

### ISSUE THREAD

**Issue by ZiniuLu** [CGAL/cgal#5603]
## Issue Details

Today I used `git pull`, `vcpkg update` and `vcpkg upgrade` to update all packages in vcpkg (including cgal). After that, I tried to complie the example code under the directory `Surface_mesh_skeletonization`. Then I got this Error Information in cmake-gui: 

> Found Eigen3: E:/Code/vcpkg/installed/x64-windows/include/eigen3 (found suitable version "3.3.9", minimum required is "3.2.0") 
CMake Error at CMakeLists.txt:10 (include):
  include could not find requested file:

>    CGAL_Eigen3_support

> These programs require the Eigen library (3.2 or greater), and will not be compiled.
Configuring incomplete, errors occurred!
See also "C:/Users/luzin/Downloads/CGAL-5.2.1-examples/examples/Surface_mesh_skeletonization/build/CMakeFiles/CMakeOutput.log".

The error in line 10 is `include(CGAL_Eigen3_support)`, which means the file `CGAL_Eigen3_support.cmake` is needed.

But I can only find a `CGAL_Eigen_support.cmake` under `./vcpkg/installed/x64-windows/share/cgal`

File: 
[CMakeOutput.log](https://github.com/CGAL/cgal/files/6288668/CMakeOutput.log)

## Source Code

all cgal example codes under the directory `Surface_mesh_skeletonization`
- MCF_Skeleton_example.cpp
- MCF_Skeleton_LCC_example.cpp
- MCF_Skeleton_sm_example.cpp
- segmentation_example.cpp
- simple_mcfskel_example.cpp
- simple_mcfskel_LCC_example.cpp
- simple_mcfskel_sm_example.cpp
- CMakeList.txt
- ./data/...

## Environment

* Operating system: Windows 10, x64
* Compiler: vcpkg, VS2019
* Release or debug mode: tried to use cmake-gui to generate .sln
* Specific flags used (if any):
* CGAL version: `cgal[core]:x64-windows -> 5.2#2`
* Boost version: 1.75.0
* Other libraries versions if used (Eigen, TBB, etc.): `eigen3[core]:x64-windows -> 3.3.9`

**Comment by sloriot** [comment]
My guess is that you are using the release of CGAL 5.2 with examples from CGAL 5.2.1 (where the cmake macro was renamed but the old one was kept for compatibility).
You can replace in the CMakeLists.txt `Eigen3_support` by `Eigen_support`
