### ISSUE TITLE
Demo Improvements for display of tetmeshes

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#5612]
Some features that are missing and that would be nice to have:

- add a way to filter what we see. For example, in the case of a complex, we might want to look at only one subdomain. There could be a menu with subdomain to display or even better it could directly be in the item list below `Intersection tetrahedra` (shouldn't it be `Intersected`? btw)
- Display tetra that are below some criteria. The most obvious case would be to see where are the slivers (with a bound on the dihedral angle provided by the user).
- show tetrahedra (there is an entry in the context menu but it is only for intersected tetrahedra AFAIS)

**Comment by afabri** [comment]
It might make sense that @sloriot @janetournois and @maxGimeno discuss  this first.
