### ISSUE TITLE
Dereference after null check in K3_tree.h

### ISSUE THREAD

**Issue by GilesBathgate** [CGAL/cgal#5613]
In the transform funcion of the following code, root is checked for null `if(root != 0)` implying that it can be null, however the code then falls through to `visit_k3tree` in which current is dereferenced in the check `if(current->left() != 0)`  

https://github.com/CGAL/cgal/blob/a8e87526348d2d1faa2ea893747314853ee6868d/Nef_3/include/CGAL/Nef_3/K3_tree.h#L971-L992

I think the code should be either `if(current !=0 && current->left() != 0 && current->right() != 0)` or simply `if(!current) return;`  since the call is recursive. The check should bypass all of the code in visit_k3tree since `V.post_visit` also dereferences `n`

**Comment by afabri** [comment]
What about to check only in the [transform ](https://github.com/CGAL/cgal/blob/master/Nef_3/include/CGAL/Nef_3/K3_tree.h#L986) method of the tree itself and just return?

**Comment by GilesBathgate** [comment]
I assumed `current->left()` can also be null so this pattern is more generalised. But it could also leave early in `transform`, since there is already a check there.

**Comment by afabri** [comment]
When `current->left()`  is null we do not go in the recursion.   If you don't mind I put the return in the transform in PR #5595.

**Comment by GilesBathgate** [comment]
Yes, it's just simpler to check `if(current == nullptr) return;` and let the recursion go down one extra level, then `if(current->left() != 0)` can be removed. This way you also know that `current->right()` cannot be null and also if the method is called from anywhere else it is pessimistic.

For sure though  `if(root == nullptr) return;`  will fix the SA warning.

**Comment by GilesBathgate** [comment]
#5595

**Comment by lrineau** [comment]
I reopen the issue. It will be closed automatically once https://github.com/CGAL/cgal/pull/5595 is merged.
