### ISSUE TITLE
Ambiguity between a halfedge dcel_circulator and a face_iterator

### ISSUE THREAD

**Issue by faretzemir** [CGAL/cgal#5641]
## Issue Details

The issue occurs during compilation. The issue in question prevents compilation and presents the user with the error "'operator !=' is ambiguous" with error code C2593 in Visual Studio 2015. The code can be compiled in CGAL version 4.11 with Boost version 1.66 as it is part of a larger program that was written and built in Windows 8 on Visual Studio 2015. 

[Edited]: Added a small sample code that reproduces the error in question. The issue is that the comparison between Arr:Ccb_halfedge_const_circulator and Arr:Ccb_halfedge_circulator has worked previously, but with the update to CGAL version 5.2.1, it no longer works as it did. I am looking for suggestions on how to proceed to rectify this issue.

## Source Code / Error Sample Code

```
#include <iostream>
#include <CGAL/Simple_cartesian.h>
#include <CGAL/Cartesian.h>
#include <CGAL/Polygon_2.h>
#include <boost/lexical_cast.hpp>
#include <CGAL/Arr_extended_dcel.h>
#include <CGAL/Arrangement_with_history_2.h>
#include <CGAL/Arr_segment_traits_2.h>
#include <windows.h>

using namespace std;

struct FaceStruct
{
    int first, second;
    bool bounded;
    string name;
};

struct FaceStructs
{
    int input_index;
    vector<string> mesh_marks;
    vector<pair<int, int>> mesh_face_index;
    bool bounded;
};

typedef CGAL::Quotient<CGAL::MP_Float > Number_type;
typedef CGAL::Cartesian<Number_type> Kernel;
typedef CGAL::Arr_segment_traits_2<Kernel> Traits_2;
typedef CGAL::Arr_face_extended_dcel <Traits_2, FaceStructs>  DCelB;
typedef CGAL::Arrangement_with_history_2<Traits_2, DCelB> ArrangementBH_2;
ArrangementBH_2::Face_const_iterator face_iterator;
ArrangementBH_2::Ccb_halfedge_const_circulator dcel_circulator;
ArrangementBH_2::Originating_curve_iterator ocurve_iterator;
ArrangementBH_2 current;
map<int, int> edge_map;

int main()
{
    
    for (face_iterator = current.faces_begin();
        face_iterator != current.faces_end();
        ++face_iterator)
    {

        if (face_iterator->is_unbounded())
        {
            FaceStructs meta;
            meta.bounded = false;
            face_iterator->set_data(meta);
            continue;
        }



        dcel_circulator = face_iterator->outer_ccb();
        map<int, int> index_count;  //key=>polygonIndex, value=> number of referenced edge
        set<int> edgePolygonSet;  //for edge facing infinity or hole (ie: edge that has only one and not two halfedge)



        do
        {
            int originalCurveCountt = 0;
            int input_index;
            for (ocurve_iterator = current.originating_curves_begin(dcel_circulator);
                ocurve_iterator != current.originating_curves_end(dcel_circulator);
                ++ocurve_iterator)
            {
                int id = ocurve_iterator->source().id();
                input_index = edge_map[id];  //polygonindex

                if (index_count.count(input_index) == 0)
                    index_count[input_index] = 1;
                else
                    index_count[input_index]++;
                originalCurveCountt++;
            }
            if (originalCurveCountt == 1)
            {
                edgePolygonSet.insert(input_index);
            }

            dcel_circulator++;
        } while (dcel_circulator != face_iterator->outer_ccb());
        // Error Here

    }
}
```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows 64-bit
* Compiler: Visual Studio 2015, toolset version v140
* Release or debug mode: Debug Mode
* Specific flags used (if any): -
* CGAL version: 5.2.1
* Boost version: 1.72.0
* Other libraries versions if used (Eigen, TBB, etc.): -

## Output Error

`1>GetFaces.cpp(210): error C2593: 'operator !=' is ambiguous
1>  C:\dev\vcpkg\installed\x64-windows\include\CGAL/HalfedgeDS_iterator.h(266): note: could be 'bool CGAL::_HalfedgeDS_facet_const_circ<CGAL::Arrangement_on_surface_2<CGAL::Arr_consolidated_curve_data_traits_2<GeomTraits_,CGAL::Arr_segment_2<Kernel_> *>,CGAL::Arr_bounded_planar_topology_traits_2<T,D>>::Halfedge,CGAL::I_Filtered_const_iterator<CGAL::internal::In_place_list_const_iterator<CGAL::Arr_halfedge<V,H,F>,Alloc>,CGAL::Arrangement_on_surface_2<CGAL::Arr_consolidated_curve_data_traits_2<GeomTraits_,CGAL::Arr_segment_2<Kernel_> *>,CGAL::Arr_bounded_planar_topology_traits_2<T,D>>::_Is_valid_halfedge,CGAL::internal::In_place_list_iterator<CGAL::Arr_halfedge<V,H,F>,Alloc>,CGAL::Arrangement_on_surface_2<CGAL::Arr_consolidated_curve_data_traits_2<GeomTraits_,CGAL::Arr_segment_2<Kernel_> *>,CGAL::Arr_bounded_planar_topology_traits_2<T,D>>::Halfedge,__int64,std::bidirectional_iterator_tag>,CGAL::Bidirectional_circulator_tag>::operator !=(const It &) const'
1>          with
1>          [
1>              GeomTraits_=Traits_2,
1>              Kernel_=Kernel,
1>              T=CGAL::Arr_consolidated_curve_data_traits_2<Traits_2,CGAL::Arr_segment_2<Kernel> *>,
1>              D=CGAL::Arr_face_extended_dcel<CGAL::Arr_consolidated_curve_data_traits_2<Traits_2,CGAL::Arr_segment_2<Kernel> *>,FaceStructs,CGAL::Arr_vertex_base<CGAL::Point_2<CGAL::Epeck>>,CGAL::Arr_halfedge_base<CGAL::_Curve_data_ex<CGAL::Arr_segment_2<Kernel>,CGAL::_Unique_list<CGAL::Arr_segment_2<Kernel> *>>>,CGAL::Arr_face_base>,
1>              V=CGAL::Arr_vertex_base<CGAL::Point_2<CGAL::Epeck>>,
1>              H=CGAL::Arr_halfedge_base<CGAL::_Curve_data_ex<CGAL::Arr_segment_2<Kernel>,CGAL::_Unique_list<CGAL::Arr_segment_2<Kernel> *>>>,
1>              F=CGAL::Arr_extended_face<CGAL::Arr_face_base,FaceStructs>,
1>              Alloc=std::allocator<CGAL::Arr_halfedge<CGAL::Arr_vertex_base<CGAL::Point_2<CGAL::Epeck>>,CGAL::Arr_halfedge_base<CGAL::_Curve_data_ex<CGAL::Arr_segment_2<Kernel>,CGAL::_Unique_list<CGAL::Arr_segment_2<Kernel> *>>>,CGAL::Arr_extended_face<CGAL::Arr_face_base,FaceStructs>>>,
1>              It=CGAL::I_Filtered_const_iterator<CGAL::internal::In_place_list_const_iterator<CGAL::Arr_halfedge<CGAL::Arr_vertex_base<CGAL::Point_2<CGAL::Epeck>>,CGAL::Arr_halfedge_base<CGAL::_Curve_data_ex<CGAL::Arr_segment_2<Kernel>,CGAL::_Unique_list<CGAL::Arr_segment_2<Kernel> *>>>,CGAL::Arr_extended_face<CGAL::Arr_face_base,FaceStructs>>,std::allocator<CGAL::Arr_halfedge<CGAL::Arr_vertex_base<CGAL::Point_2<CGAL::Epeck>>,CGAL::Arr_halfedge_base<CGAL::_Curve_data_ex<CGAL::Arr_segment_2<Kernel>,CGAL::_Unique_list<CGAL::Arr_segment_2<Kernel> *>>>,CGAL::Arr_extended_face<CGAL::Arr_face_base,FaceStructs>>>>,CGAL::Arrangement_on_surface_2<CGAL::Arr_consolidated_curve_data_traits_2<Traits_2,CGAL::Arr_segment_2<Kernel> *>,CGAL::Arr_bounded_planar_topology_traits_2<CGAL::Arr_consolidated_curve_data_traits_2<Traits_2,CGAL::Arr_segment_2<Kernel> *>,CGAL::Arr_face_extended_dcel<CGAL::Arr_consolidated_curve_data_traits_2<Traits_2,CGAL::Arr_segment_2<Kernel> *>,FaceStructs,CGAL::Arr_vertex_base<CGAL::Point_2<CGAL::Epeck>>,CGAL::Arr_halfedge_base<CGAL::_Curve_data_ex<CGAL::Arr_segment_2<Kernel>,CGAL::_Unique_list<CGAL::Arr_segment_2<Kernel> *>>>,CGAL::Arr_face_base>>>::_Is_valid_halfedge,CGAL::internal::In_place_list_iterator<CGAL::Arr_halfedge<CGAL::Arr_vertex_base<CGAL::Point_2<CGAL::Epeck>>,CGAL::Arr_halfedge_base<CGAL::_Curve_data_ex<CGAL::Arr_segment_2<Kernel>,CGAL::_Unique_list<CGAL::Arr_segment_2<Kernel> *>>>,CGAL::Arr_extended_face<CGAL::Arr_face_base,FaceStructs>>,std::allocator<CGAL::Arr_halfedge<CGAL::Arr_vertex_base<CGAL::Point_2<CGAL::Epeck>>,CGAL::Arr_halfedge_base<CGAL::_Curve_data_ex<CGAL::Arr_segment_2<Kernel>,CGAL::_Unique_list<CGAL::Arr_segment_2<Kernel> *>>>,CGAL::Arr_extended_face<CGAL::Arr_face_base,FaceStructs>>>>,CGAL::Arrangement_on_surface_2<CGAL::Arr_consolidated_curve_data_traits_2<Traits_2,CGAL::Arr_segment_2<Kernel> *>,CGAL::Arr_bounded_planar_topology_traits_2<CGAL::Arr_consolidated_curve_data_traits_2<Traits_2,CGAL::Arr_segment_2<Kernel> *>,CGAL::Arr_face_extended_dcel<CGAL::Arr_consolidated_curve_data_traits_2<Traits_2,CGAL::Arr_segment_2<Kernel> *>,FaceStructs,CGAL::Arr_vertex_base<CGAL::Point_2<CGAL::Epeck>>,CGAL::Arr_halfedge_base<CGAL::_Curve_data_ex<CGAL::Arr_segment_2<Kernel>,CGAL::_Unique_list<CGAL::Arr_segment_2<Kernel> *>>>,CGAL::Arr_face_base>>>::Halfedge,__int64,std::bidirectional_iterator_tag>
1>          ]
1>  C:\dev\vcpkg\installed\x64-windows\include\CGAL/HalfedgeDS_iterator.h(264): note: or       'bool CGAL::_HalfedgeDS_facet_const_circ<CGAL::Arrangement_on_surface_2<CGAL::Arr_consolidated_curve_data_traits_2<GeomTraits_,CGAL::Arr_segment_2<Kernel_> *>,CGAL::Arr_bounded_planar_topology_traits_2<T,D>>::Halfedge,CGAL::I_Filtered_const_iterator<CGAL::internal::In_place_list_const_iterator<CGAL::Arr_halfedge<V,H,F>,Alloc>,CGAL::Arrangement_on_surface_2<CGAL::Arr_consolidated_curve_data_traits_2<GeomTraits_,CGAL::Arr_segment_2<Kernel_> *>,CGAL::Arr_bounded_planar_topology_traits_2<T,D>>::_Is_valid_halfedge,CGAL::internal::In_place_list_iterator<CGAL::Arr_halfedge<V,H,F>,Alloc>,CGAL::Arrangement_on_surface_2<CGAL::Arr_consolidated_curve_data_traits_2<GeomTraits_,CGAL::Arr_segment_2<Kernel_> *>,CGAL::Arr_bounded_planar_topology_traits_2<T,D>>::Halfedge,__int64,std::bidirectional_iterator_tag>,CGAL::Bidirectional_circulator_tag>::operator !=(const CGAL::_HalfedgeDS_facet_const_circ<CGAL::Arrangement_on_surface_2<CGAL::Arr_consolidated_curve_data_traits_2<GeomTraits_,CGAL::Arr_segment_2<Kernel_> *>,CGAL::Arr_bounded_planar_topology_traits_2<T,D>>::Halfedge,CGAL::I_Filtered_const_iterator<CGAL::internal::In_place_list_const_iterator<CGAL::Arr_halfedge<V,H,F>,Alloc>,CGAL::Arrangement_on_surface_2<CGAL::Arr_consolidated_curve_data_traits_2<GeomTraits_,CGAL::Arr_segment_2<Kernel_> *>,CGAL::Arr_bounded_planar_topology_traits_2<T,D>>::_Is_valid_halfedge,CGAL::internal::In_place_list_iterator<CGAL::Arr_halfedge<V,H,F>,Alloc>,CGAL::Arrangement_on_surface_2<CGAL::Arr_consolidated_curve_data_traits_2<GeomTraits_,CGAL::Arr_segment_2<Kernel_> *>,CGAL::Arr_bounded_planar_topology_traits_2<T,D>>::Halfedge,__int64,std::bidirectional_iterator_tag>,CGAL::Bidirectional_circulator_tag> &) const'
1>          with
1>          [
1>              GeomTraits_=Traits_2,
1>              Kernel_=Kernel,
1>              T=CGAL::Arr_consolidated_curve_data_traits_2<Traits_2,CGAL::Arr_segment_2<Kernel> *>,
1>              D=CGAL::Arr_face_extended_dcel<CGAL::Arr_consolidated_curve_data_traits_2<Traits_2,CGAL::Arr_segment_2<Kernel> *>,FaceStructs,CGAL::Arr_vertex_base<CGAL::Point_2<CGAL::Epeck>>,CGAL::Arr_halfedge_base<CGAL::_Curve_data_ex<CGAL::Arr_segment_2<Kernel>,CGAL::_Unique_list<CGAL::Arr_segment_2<Kernel> *>>>,CGAL::Arr_face_base>,
1>              V=CGAL::Arr_vertex_base<CGAL::Point_2<CGAL::Epeck>>,
1>              H=CGAL::Arr_halfedge_base<CGAL::_Curve_data_ex<CGAL::Arr_segment_2<Kernel>,CGAL::_Unique_list<CGAL::Arr_segment_2<Kernel> *>>>,
1>              F=CGAL::Arr_extended_face<CGAL::Arr_face_base,FaceStructs>,
1>              Alloc=std::allocator<CGAL::Arr_halfedge<CGAL::Arr_vertex_base<CGAL::Point_2<CGAL::Epeck>>,CGAL::Arr_halfedge_base<CGAL::_Curve_data_ex<CGAL::Arr_segment_2<Kernel>,CGAL::_Unique_list<CGAL::Arr_segment_2<Kernel> *>>>,CGAL::Arr_extended_face<CGAL::Arr_face_base,FaceStructs>>>
1>          ]
1>  C:\dev\vcpkg\installed\x64-windows\include\CGAL/HalfedgeDS_iterator.h(262): note: or       'bool CGAL::_HalfedgeDS_facet_const_circ<CGAL::Arrangement_on_surface_2<CGAL::Arr_consolidated_curve_data_traits_2<GeomTraits_,CGAL::Arr_segment_2<Kernel_> *>,CGAL::Arr_bounded_planar_topology_traits_2<T,D>>::Halfedge,CGAL::I_Filtered_const_iterator<CGAL::internal::In_place_list_const_iterator<CGAL::Arr_halfedge<V,H,F>,Alloc>,CGAL::Arrangement_on_surface_2<CGAL::Arr_consolidated_curve_data_traits_2<GeomTraits_,CGAL::Arr_segment_2<Kernel_> *>,CGAL::Arr_bounded_planar_topology_traits_2<T,D>>::_Is_valid_halfedge,CGAL::internal::In_place_list_iterator<CGAL::Arr_halfedge<V,H,F>,Alloc>,CGAL::Arrangement_on_surface_2<CGAL::Arr_consolidated_curve_data_traits_2<GeomTraits_,CGAL::Arr_segment_2<Kernel_> *>,CGAL::Arr_bounded_planar_topology_traits_2<T,D>>::Halfedge,__int64,std::bidirectional_iterator_tag>,CGAL::Bidirectional_circulator_tag>::operator !=(std::nullptr_t) const'
1>          with
1>          [
1>              GeomTraits_=Traits_2,
1>              Kernel_=Kernel,
1>              T=CGAL::Arr_consolidated_curve_data_traits_2<Traits_2,CGAL::Arr_segment_2<Kernel> *>,
1>              D=CGAL::Arr_face_extended_dcel<CGAL::Arr_consolidated_curve_data_traits_2<Traits_2,CGAL::Arr_segment_2<Kernel> *>,FaceStructs,CGAL::Arr_vertex_base<CGAL::Point_2<CGAL::Epeck>>,CGAL::Arr_halfedge_base<CGAL::_Curve_data_ex<CGAL::Arr_segment_2<Kernel>,CGAL::_Unique_list<CGAL::Arr_segment_2<Kernel> *>>>,CGAL::Arr_face_base>,
1>              V=CGAL::Arr_vertex_base<CGAL::Point_2<CGAL::Epeck>>,
1>              H=CGAL::Arr_halfedge_base<CGAL::_Curve_data_ex<CGAL::Arr_segment_2<Kernel>,CGAL::_Unique_list<CGAL::Arr_segment_2<Kernel> *>>>,
1>              F=CGAL::Arr_extended_face<CGAL::Arr_face_base,FaceStructs>,
1>              Alloc=std::allocator<CGAL::Arr_halfedge<CGAL::Arr_vertex_base<CGAL::Point_2<CGAL::Epeck>>,CGAL::Arr_halfedge_base<CGAL::_Curve_data_ex<CGAL::Arr_segment_2<Kernel>,CGAL::_Unique_list<CGAL::Arr_segment_2<Kernel> *>>>,CGAL::Arr_extended_face<CGAL::Arr_face_base,FaceStructs>>>
1>          ]
1>  C:\Program Files (x86)\Windows Kits\8.1\Include\shared\guiddef.h(197): note: or       'bool operator !=(const GUID &,const GUID &)'
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\thread(219): note: or       'bool std::operator !=(std::thread::id,std::thread::id) noexcept'
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\system_error(419): note: or       'bool std::operator !=(const std::error_condition &,const std::error_condition &) noexcept'
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\system_error(412): note: or       'bool std::operator !=(const std::error_condition &,const std::error_code &) noexcept'
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\system_error(405): note: or       'bool std::operator !=(const std::error_code &,const std::error_condition &) noexcept'
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\system_error(398): note: or       'bool std::operator !=(const std::error_code &,const std::error_code &) noexcept'
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\exception(354): note: or       'bool std::operator !=(const std::exception_ptr &,std::nullptr_t) throw()'
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\exception(349): note: or       'bool std::operator !=(std::nullptr_t,const std::exception_ptr &) throw()'
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\exception(344): note: or       'bool std::operator !=(const std::exception_ptr &,const std::exception_ptr &) throw()'
1>  C:\dev\vcpkg\installed\x64-windows\include\CGAL/Interval_nt.h(329): note: or       'CGAL::Uncertain<bool> CGAL::Interval_nt<true>::operator !=(const CGAL::Interval_nt<true> &,const CGAL::Interval_nt<true> &)' [found using argument-dependent lookup]
1>  C:\dev\vcpkg\installed\x64-windows\include\CGAL/Interval_nt.h(374): note: or       'CGAL::Uncertain<bool> CGAL::Interval_nt<true>::operator !=(double,const CGAL::Interval_nt<true> &)' [found using argument-dependent lookup]
1>  C:\dev\vcpkg\installed\x64-windows\include\CGAL/Interval_nt.h(414): note: or       'CGAL::Uncertain<bool> CGAL::Interval_nt<true>::operator !=(const CGAL::Interval_nt<true> &,double)' [found using argument-dependent lookup]
1>  C:\dev\vcpkg\installed\x64-windows\include\CGAL/Interval_nt.h(329): note: or       'CGAL::Uncertain<bool> CGAL::Interval_nt<false>::operator !=(const CGAL::Interval_nt<false> &,const CGAL::Interval_nt<false> &)' [found using argument-dependent lookup]
1>  C:\dev\vcpkg\installed\x64-windows\include\CGAL/Interval_nt.h(374): note: or       'CGAL::Uncertain<bool> CGAL::Interval_nt<false>::operator !=(double,const CGAL::Interval_nt<false> &)' [found using argument-dependent lookup]
1>  C:\dev\vcpkg\installed\x64-windows\include\CGAL/Interval_nt.h(414): note: or       'CGAL::Uncertain<bool> CGAL::Interval_nt<false>::operator !=(const CGAL::Interval_nt<false> &,double)' [found using argument-dependent lookup]
1>  C:\dev\vcpkg\installed\x64-windows\include\CGAL/Mpzf.h(578): note: or       'bool CGAL::operator !=(const CGAL::Mpzf &,const CGAL::Mpzf &)' [found using argument-dependent lookup]
1>  GetFaces.cpp(210): note: while trying to match the argument list '(CGAL::_HalfedgeDS_facet_const_circ<CGAL::Arrangement_on_surface_2<CGAL::Arr_consolidated_curve_data_traits_2<GeomTraits_,CGAL::Arr_segment_2<Kernel_> *>,CGAL::Arr_bounded_planar_topology_traits_2<T,D>>::Halfedge,CGAL::I_Filtered_const_iterator<CGAL::internal::In_place_list_const_iterator<CGAL::Arr_halfedge<V,H,F>,Alloc>,CGAL::Arrangement_on_surface_2<CGAL::Arr_consolidated_curve_data_traits_2<GeomTraits_,CGAL::Arr_segment_2<Kernel_> *>,CGAL::Arr_bounded_planar_topology_traits_2<T,D>>::_Is_valid_halfedge,CGAL::internal::In_place_list_iterator<CGAL::Arr_halfedge<V,H,F>,Alloc>,CGAL::Arrangement_on_surface_2<CGAL::Arr_consolidated_curve_data_traits_2<GeomTraits_,CGAL::Arr_segment_2<Kernel_> *>,CGAL::Arr_bounded_planar_topology_traits_2<T,D>>::Halfedge,__int64,std::bidirectional_iterator_tag>,CGAL::Bidirectional_circulator_tag>, CGAL::_HalfedgeDS_facet_circ<CGAL::Arrangement_on_surface_2<CGAL::Arr_consolidated_curve_data_traits_2<GeomTraits_,CGAL::Arr_segment_2<Kernel_> *>,CGAL::Arr_bounded_planar_topology_traits_2<T,D>>::Halfedge,CGAL::I_Filtered_iterator<CGAL::internal::In_place_list_iterator<CGAL::Arr_halfedge<V,H,F>,Alloc>,CGAL::Arrangement_on_surface_2<CGAL::Arr_consolidated_curve_data_traits_2<GeomTraits_,CGAL::Arr_segment_2<Kernel_> *>,CGAL::Arr_bounded_planar_topology_traits_2<T,D>>::_Is_valid_halfedge,CGAL::Arrangement_on_surface_2<CGAL::Arr_consolidated_curve_data_traits_2<GeomTraits_,CGAL::Arr_segment_2<Kernel_> *>,CGAL::Arr_bounded_planar_topology_traits_2<T,D>>::Halfedge,__int64,std::bidirectional_iterator_tag>,CGAL::Bidirectional_circulator_tag>)'
1>          with
1>          [
1>              GeomTraits_=Traits_2,
1>              Kernel_=Kernel,
1>              T=CGAL::Arr_consolidated_curve_data_traits_2<Traits_2,CGAL::Arr_segment_2<Kernel> *>,
1>              D=CGAL::Arr_face_extended_dcel<CGAL::Arr_consolidated_curve_data_traits_2<Traits_2,CGAL::Arr_segment_2<Kernel> *>,FaceStructs,CGAL::Arr_vertex_base<CGAL::Point_2<CGAL::Epeck>>,CGAL::Arr_halfedge_base<CGAL::_Curve_data_ex<CGAL::Arr_segment_2<Kernel>,CGAL::_Unique_list<CGAL::Arr_segment_2<Kernel> *>>>,CGAL::Arr_face_base>,
1>              V=CGAL::Arr_vertex_base<CGAL::Point_2<CGAL::Epeck>>,
1>              H=CGAL::Arr_halfedge_base<CGAL::_Curve_data_ex<CGAL::Arr_segment_2<Kernel>,CGAL::_Unique_list<CGAL::Arr_segment_2<Kernel> *>>>,
1>              F=CGAL::Arr_extended_face<CGAL::Arr_face_base,FaceStructs>,
1>              Alloc=std::allocator<CGAL::Arr_halfedge<CGAL::Arr_vertex_base<CGAL::Point_2<CGAL::Epeck>>,CGAL::Arr_halfedge_base<CGAL::_Curve_data_ex<CGAL::Arr_segment_2<Kernel>,CGAL::_Unique_list<CGAL::Arr_segment_2<Kernel> *>>>,CGAL::Arr_extended_face<CGAL::Arr_face_base,FaceStructs>>>
1>          ]`

**Comment by efifogel** [comment]
You are comparing Arr::Ccb_halfedge_const_circulator and
Arr::Ccb_halfedge_circulator which are different types.
   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by faretzemir** [comment]
The problem is that this code has worked in the past, using CGAL 4.11 and Boost version 1.66. I updated my CGAL and Boost versions, and was met with this error. The code I originally included is part of a larger repository, but I have managed to include a smaller sample that isolates the error in question (I edited the issue to attach the sample below the issue). Do you have any suggestions on how to proceed in order to rectify this issue?

**Comment by efifogel** [comment]
I think that it has never worked (since the beginning of time....:)
The fix is simple, either change face_iterator to face_const_iterator, or
convert Ccb_halfedge_const_circulator to its non-const counterpart
(Ccb_halfedge_circulator) just before the comparison.
   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by afabri** [comment]
@faretzemir did what Efi proposed work out for you, or do you have so many places where you would have  to change?
