### ISSUE TITLE
Missing functionality in CGAL to libpointmatcher interface

### ISSUE THREAD

**Issue by maximecharriere** [CGAL/cgal#5648]
## Issue Details

The libpointmatcher librairy give you the opportunity to do a point set registration by manually giving a weight to each point.
To do it, you have to set a `GenericDescriptorOutlierFilter` in the ICP algorithm.  

>#### GenericDescriptorOutlierFilter description :
>This filter weights matched points based on a 1D descriptor of either a single point cloud (either the reference or the reading). The descriptor values must be larger than zero.
>- source (default: reference) - Point cloud from which the descriptor will be used: reference or reading
>- descName (default: none) - Descriptor name used to weight paired points
>- useSoftThreshold (default: 0) - If set to 1 (true), uses the value of the descriptor as a weight. If set to 0 (false), uses the parameter 'threshold' to set binary weights. - min: 0 - max: 1
>- useLargerThan (default: 1) - If set to 1 (true), values over the 'threshold' will have a weight of one.  If set to 0 (false), values under the 'threshold' will have a weight of one. All other values will have a weight of zero. - min: 0 - max: 1
>- threshold (default: 0.1) - Value used to determine the binary weights - min: 0.0000001 - max: inf

The construction of the ICP algorithm works all fine with the CGAL to libpointmatcher interface (see function to construct the ICP [here](https://github.com/CGAL/cgal/blob/master/Point_set_processing_3/include/CGAL/pointmatcher/compute_registration_transformation.h#L70)).  

The problem occurs when running the ICP algorithm. libpointmatcher search for the `descName` descriptor in the `source` point cloud, but it can't find it because the CGAL interface doesn't transfer this information. We can see in the [`construct_PM_cloud`](https://github.com/CGAL/cgal/blob/master/Point_set_processing_3/include/CGAL/pointmatcher/compute_registration_transformation.h#L294) function that the position of each point and its normal is transferred to the libpointmatcher point cloud but not other informations like the weight of the point that interests us here.  

The interface should be improved so that it is possible to provide to the `compute_registration_transformation` function an additional optional PropertyMap containing the weight of each point, and that the CGAL interface adds the descriptor with the name provided during the ICP configuration to the pointmatcher point cloud.  

Would it be possible to see how to make the GenericDescriptorOutlierFilter work with CGAL? I am not experienced enough to provide you with a good PullRequest adding this feature. 
Maybe @pomerlef can help us on this one ?

**Comment by danston** [comment]
Hi @maximecharriere. Thanks for the detailed explanation. I will see these days what can be done in this regard and keep you updated.

**Comment by danston** [comment]
I have created a pull request #5655 with the feature you asked for. Please let me know if it does what you need and if anything else is still missing. In the example `registration_with_pointmatcher`, I have added the `GenericDescriptorOutlierFilter` and a weight map with default weights to illustrate how it works.
