### ISSUE TITLE
classifier.save_configuration(fconfig) Error : 'save_configuration': is not a member of 'CGAL::Classification::ETHZ::Random_forest_classifier'

### ISSUE THREAD

**Issue by AnasFX** [CGAL/cgal#5670]
## Issue Details

I got this error when I try to compile the example code ( ETHZ Random Forest ) in this page ( https://doc.cgal.org/latest/Classification/index.html ) :

Error	C2039	'save_configuration': is not a member of 'CGAL::Classification::ETHZ::Random_forest_classifier'	
 although I checked in the ( Random_forest_classifier.h ) and it is there.

## Environment

* Operating system (Windows, 64 bits):
* Compiler:
* Release or debug mode: both
* CGAL version: 5.2.1

**Comment by sgiraudot** [comment]
Are you sure you are using CGAL 5.2.1? For a short period of time, there was a false dependency to Boost IO Streams / Serialization that deactivated `save/load_configuration()` functions if these Boost libraries were not present, but this false dependency was fixed and integrated in 5.2.1 (see https://github.com/CGAL/cgal/commit/fba2e1fc45e6137249fc6cfc04bc5cb8a9bf1b51).

**Comment by AnasFX** [comment]
I rechecked, and indeed I was using the 5.2 version. Thanks a lot.
