### ISSUE TITLE
PMP::iso_remeshing issue(s)

### ISSUE THREAD

**Issue by MaelRL** [CGAL/cgal#5675]
## Issue Details

An issue and a maybe-issue:

* An assertion pops up in [this code](https://gist.github.com/MaelRL/107447b9467df2ea3b5d1038295d87e7). I am not actually running code that constrains everything, I just noticed this border case trying to reproduce the next point.

* I was quite surprised by the behavior of the algorithm in [this code](https://gist.github.com/MaelRL/9548957d11fa0290d1764939a1fb7bf6) with [this input](https://gist.github.com/MaelRL/6ede329a5aacebab328e3a7f882f402a). I give it a face range, but all the faces of the mesh end up being refined. If this were necessary to create isotropic triangles on the boundary of my face selection, I could understand; however, this produces anisotropic triangles. ![Illustration](https://user-images.githubusercontent.com/5074170/117108501-95c57980-ad83-11eb-9cb4-6a5e2edca1eb.png)

## Environment

* Release or debug mode: debug
* CGAL version: master

**Comment by sloriot** [comment]
@maxGimeno could you please try to see if the problem occurs with CGAL 5.2? I'm worried this was introduced by a recent fix in master.

**Comment by MaelRL** [comment]
Note that for the second point, this results from the edges that are not part of the face selection being constrained (but not protected) and if you remove the ecm, you'll get what you expect. Still, I would expect it to stop refining once it is not handling faces within the input range anymore.

**Comment by maxGimeno** [comment]
@sloriot I confirm the assertion also occurs in 5.2

**Comment by janetournois** [comment]
I am looking at this issue

**Comment by janetournois** [comment]
The 1st issue is related to my PR #5616, I'm sorry
I'm working on it

**Comment by lrineau** [comment]
Fixed by https://github.com/CGAL/cgal/pull/5689.
