### ISSUE TITLE
Illegal division in Quotient.h

### ISSUE THREAD

**Issue by MaelRL** [CGAL/cgal#5688]
## Issue Details

`Quotient::to_double()` divides a NT by another ([here](https://github.com/CGAL/cgal/blame/master/Number_types/include/CGAL/Quotient.h#L674)). 

But this operator is not necessarily available since the requirement is: `NT must be at least model of concept IntegralDomainWithoutDivision and a model of concept RealEmbeddable.` Thus, something like `Quotient<Mpzf>` (with the macro removing the division) will not compile.

**Comment by MaelRL** [comment]
Also isn't:
```
double nd = CGAL_NTS to_double( x.num );
double dd = CGAL_NTS to_double( x.den );
if ( CGAL_NTS is_finite( x.den ) && CGAL_NTS is_finite( x.num ) )
return nd/dd;
```
a little strange? The value `NT(x.den)` is not allowed to be zero, but what prevents a division by `to_double(x.den) =: dd = 0.`?

**Comment by mglisse** [comment]
Duplicate of #1053 ?

**Comment by mglisse** [comment]
#1815 (and possibly others) also mentions that this function is ... questionable.

**Comment by MaelRL** [comment]
Indeed, both PR are the same issues as the comments above, thanks.
