### ISSUE TITLE
Qt viever is just empty in every example.

### ISSUE THREAD

**Issue by DzikiCzosnek99** [CGAL/cgal#5691]
Hello everyone. I am realy new to cgal na c++and I have some problems. When I am trying to run an example wich requires qt, basic viewer is just empty. There is no errors and I checked, that the file was correctly loaded by print all points.  

My Source Code:

```c++
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/Polyhedron_3.h>
#include <CGAL/IO/Polyhedron_iostream.h>
#include <CGAL/draw_polyhedron.h>
#include  <fstream>
#include  <ios>

typedef CGAL::Exact_predicates_inexact_constructions_kernel  Kernel;
typedef CGAL::Polyhedron_3<Kernel>                       Polyhedron;

int main(int argc, char* argv[])
{
  Polyhedron P;
  std::ifstream in1((argc>1)?argv[1]:"C:/Praca/wczytanie_belki/dane/belka.off");
  in1 >> P;
  std::cout << P;
  CGAL::draw(P);


  return EXIT_SUCCESS;
}
```
Screenshot:
![image](https://user-images.githubusercontent.com/83810161/117421136-8af31c00-af1e-11eb-8d4a-fc71f6a7383f.png)

Environment

* Win 10 64 bit
* Compiler: MSVC 19.28.29914.0
* CGAL version: 5.2.1
* Boost version:1.75.0

**Comment by maxGimeno** [comment]
Maybe for some reason edges and faces are hidden. Try to push E and W in the Basic Viewer. Or try to zoom out to see if it is just the camera that is not centered. I tried your file on a 5.2.1 version built with MSVC 2019 and everything showed up.

**Comment by afabri** [comment]
@DzikiCzosnek99 did it finally work out or did you give up?

**Comment by MaelRL** [comment]
Bump @DzikiCzosnek99
