### ISSUE TITLE
concept-model differences in Mesh_3

### ISSUE THREAD

**Issue by MaelRL** [CGAL/cgal#570]
According to the documentation,  [Mesh_complex_3_in_triangulation_3](http://doc.cgal.org/latest/Mesh_3/classCGAL_1_1Mesh__complex__3__in__triangulation__3.html) is a model of [MeshComplexWithFeatures_3InTriangulation_3](http://doc.cgal.org/latest/Mesh_3/classMeshComplexWithFeatures__3InTriangulation__3.html). However, a few functions differ from the concept to the model: for example `number_of_corners()` is called `number_of_vertices_in_complex()` in the model; additionally, overloads with a subdomain index are also missing.

The documentation uses the terminology `corners`, `curve segments` but `vertices_in_complex` is simpler so I am not sure which one should be kept.

**Comment by janetournois** [comment]
You are right, there are some inconsistencies!

Imho, the option that should the kept is the one which we can find in the model, so that no code is broken by the documentation change.

 What do you think @lrineau ?

**Comment by lrineau** [comment]
The reviewers of Mesh_3 with features would probably disagree but I agree with Jane.

**Comment by MaelRL** [comment]
Ran into that again while on P3M3 and thought I'd fix it along the way.

Consensus is still to break the concept ?
