### ISSUE TITLE
CDT Seg Faults

### ISSUE THREAD

**Issue by qnzhou** [CGAL/cgal#572]
I noticed a seg fault deep down inside CGAL CDT.  Here is a minimal example to reproduce the issue:

https://gist.github.com/qnzhou/e997f6a04be5dfd169f9

Testing environment:
OS: OS X 10.10.5 and Linux
CGAL version: 4.7 (installed through mac port) and 4.5
Compiler: Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn) and gcc4.9.2

~~Update: I made a mistake in the minimal example which causes the crash.  I am working on an updated one.  Sorry.~~
Update2: The minimal example should now reproduce the seg fault.

Here is the visualization of the constraints for the CDT:
![image](https://cloud.githubusercontent.com/assets/3606672/11980639/5a06a752-a96a-11e5-80d1-0c826f530b68.png)

**Comment by alecjacobson** [comment]
For what it's worth, subdividing all the segments at their mutual intersections as a preprocess fixes/hides this issue.

**Comment by sloriot** [comment]
The code is working fine with 4.5 but not with 4.6. This comes from the work done for introducing polyline support in `Constrained_triangulation_plus_2`.
@afabri could you have a look?

**Comment by afabri** [comment]
Hello @qnzhou ,
can you give this fix a try, and report back.
