### ISSUE TITLE
slow dynamic_cast in Lazy_kernel::Construct_point_3

### ISSUE THREAD

**Issue by mglisse** [CGAL/cgal#5724]
With libstdc++ (and possibly even worse with visual studio), test_p3rt3_as_p3t3.cpp spends a lot of time in the dynamic_cast of Lazy_kernel used to recognize if a weighted point was constructed from a point and a weight, and thus if we can extract those without building a new lazy object. This was noticed in #5402.

Rewriting the test as
```c++
      auto&& t = typeid(*p.ptr());
      if(t == typeid(LR)){
        LR * lr = static_cast<LR*>(p.ptr());
        return std::get<1>(lr->l);
      }else{
        if(t == typeid(LRint)){
          LRint* lrint = static_cast<LRint*>(p.ptr());
          return std::get<1>(lrint->l);
        }
      }
```
without the dynamic_cast seems to speed things up nicely here (we could add `final` on Lazy_rep_n to confirm that this is equivalent). (it is possible that I got the test wrong, this needs checking)
Further replacing `t == typeid(X)` with `t.name() == typeid(X).name()` gives another nice gain on top of that (I think that's how libc++ implements it, but libstdc++ further checks `strcmp` if that comparison is false). It is supposedly unsafe when parts of the program are loaded with `dlopen` or similar, but since this is just an optimization and wrongly saying false still uses valid code, maybe that would be acceptable.
I don't know if getting rid of LRint (casting the `int` to FT and creating LR instead) would help or hurt more.
Another option may be adding a virtual function in Lazy_rep to detect these cases.

**Comment by lrineau** [comment]
Maybe we should implement our own RTTI, or use dedicated virtual functions.

**Comment by afabri** [comment]
You mean something like a `char`  in a lazy object encoding the type?

**Comment by lrineau** [comment]
> You mean something like a `char` in a lazy object encoding the type?

Something like that. Given the number of functors in our kernel, a `char` will not be enough, but an `int` will.

**Comment by afabri** [comment]
Given that the dynamic cast is only done for the `Construct_point_2/3` functor I would go for what Marc proposes.

**Comment by mglisse** [comment]
One of my propositions is a virtual function, so it intersects with Laurent's propositions. It it just a bit inconvenient to transmit the right information through those templates to the one that needs to define the function. The typeid comparison on the other hand is a trivial change and already gets a large part of the potential gain (possibly all of it on some platforms).

**Comment by afabri** [comment]
At one point I was thinking about `Construct_source_3`  of  a segment finding out if the segment has two children which just happen to be lazy points.  So there could be more cases, but as we all have limited resources ....

**Comment by lrineau** [comment]
Actually, @mglisse, what is so costly with the dynamic cast, compared to using `typeid`? Both use the RTTI. I do not understand how a dynamic cast can be slower than following a few pointers to get the dynamic type of the object.

**Comment by mglisse** [comment]
dynamic_cast doesn't just check if the types are the same, it checks if one type derives from the other, that's much more work.
(and then typeid::operator== is slow ***if*** it cannot just compare 2 pointers but has to compare 2 strings instead)

**Comment by mglisse** [comment]
https://github.com/mglisse/cgal/commit/f4ec282c01f4f330a5c3bab7a7dc59ec53c07595
vs
https://github.com/mglisse/cgal/commit/21dfcb1b5752034393f8405acb627dee54c6e3f4
Performance seems close enough (I think they both become negligible in the test I did).
