### ISSUE TITLE
Point cloud classification train example code throws CGAL::Assertion_exception exception

### ISSUE THREAD

**Issue by MorcilloSanz** [CGAL/cgal#5727]
## Issue Details
Hi, I'm trying to run the example code of Training for Point cloud classification, but I'm getting the following error:
**Unhandled exception at 0x00007FFCE7D04B89 in CloudClassifier.exe: Microsoft C++ exception: CGAL::Assertion_exception at memory location 0x00000010728F77A0.**

It happens when calling this function:
**classifier.train<CGAL::Parallel_if_available_tag>(pts.range(label_map), 800);**

The rest of the code is the same as the code example.

Thanks in advance

## Source Code
The code I'm trying to run is:
https://doc.cgal.org/latest/Classification/Classification_2example_generation_and_training_8cpp-example.html

## Environment

* Operating system: Windows 10
* Compiler: Visual C++
* Release or debug mode: Both, x64
* Specific flags used (if any):
* CGAL version: 5.2.1
* Boost version: 1.74
* Other libraries versions if used (Eigen, TBB, etc.): Qt5

**Comment by MorcilloSanz** [comment]
Hi, I didn't change anything of the code actually but I'm using my own point cloud. Sorry for not expressing myself correctly before.
The code compiles successfuly but the only thing that happens is that exception is thrown when calling **classifier.train()**.
I tried to debug and it looks like everything is working until calling that function.

Thanks in advance again.

**Comment by danston** [comment]
Could you please provide your data or at least a part that fails? I am running this example successfully with our data so to reproduce your error, I would need your data. Thanks.

**Comment by MorcilloSanz** [comment]
Hi, sorry for waiting. 
I found out why it was crashing, it was because of my point cloud didn't have the "property int label" defined inside the .ply file.
When I use your assets it works correctly.
How can I use the train() function in my own .ply file?

Thanks for helping

**Comment by danston** [comment]
I am glad that you have resolved your problem. Indeed, the `property int label` is required for this example. This is a property map that is used to actually train the classifier. If you want to train on your own data, you need to provide a data file with the predefined labels, the one similar to the `data/b9_training.ply`. You can also read about it [here](https://doc.cgal.org/latest/Classification/index.html#Classification_sowf_training) and [here](https://doc.cgal.org/latest/Classification/classCGAL_1_1Classification_1_1Sum__of__weighted__features__classifier.html#a11bcf5a1416f0fd2c4855af9c73797cc).

**Comment by MorcilloSanz** [comment]
Thanks for helping, I did it finally!
