### ISSUE TITLE
Problem with link in Triangulation_on_sphere_ package

### ISSUE THREAD

**Issue by albert-github** [CGAL/cgal#5750]
## Issue Details
In the file `Triangulation_on_sphere_2/doc/Triangulation_on_sphere_2/PackageDescription.txt` we have the definition:
```
\cgalPkgDemo{Delaunay Triangulation, delaunay_Triangulation_on_sphere_2.zip}
```
resulting in the link:
```
https://www.cgal.org/demo/5.3/%20delaunay_Triangulation_on_sphere_2.zip
```
there are a number of problems:
- the space after the comma should not be present
- the zip file does not (yet, looks to me that it is a new package for the 5.3. version)

This shows up on the "page":
```
Manual/packages.html#PkgTriangulationOnSphere2
```

## Environment
* CGAL version: master

**Comment by MaelRL** [comment]
Could you please clarify the last part of the issue (about `Manual/packages.html#PkgTriangulationOnSphere2`)?

**Comment by albert-github** [comment]
I saw this in my local build
Here I have between:
> 2D Triangulation Data Structure

and
> 2D Periodic Triangulations

The item:
> 2D Triangulations on Sphere

in the later part the problem occurs.

The version I used was the, up to date, master version.
Did you, by accident, look at the:
- 5.2.2 version: https://cgal.geometryfactory.com/CGAL/Manual_doxygen_test/CGAL-5.2.2-I-87/master/Manual/packages.html
- 5.1.5 version: https://cgal.geometryfactory.com/CGAL/Manual_doxygen_test/CGAL-5.1.5-I-281/master/Manual/packages.html

As far as I know the mentioned package is a new package for the 5.3 version.
You can see the problem as well on https://cgal.geometryfactory.com/CGAL/Manual_doxygen_test/CGAL-5.3-Ic-141/master/Manual/packages.html#PkgTriangulationOnSphere2
