### ISSUE TITLE
Hard to reach link (behind login) in documentation

### ISSUE THREAD

**Issue by albert-github** [CGAL/cgal#5752]
## Issue Details

In the file `Documentation/doc/Documentation/Developer_manual/Chapter_code_format.txt` there is the link to:
```
https://sympa.inria.fr/sympa/arc/cgal-develop/2010-10/msg00118.html
```
this is behind a login and it looks like one can get access through a login process though it is not 100% clear what the restrictions / necessities are.
This is a bit user unfriendly (in my opinion) and would also be time consuming.

Might be better to include the mentioned file verbatim into the documentation.

**Comment by sloriot** [comment]
@mglisse do you agree to inline your message to cgal-develop in the manual?

**Comment by mglisse** [comment]
No problem if you want to copy it, but isn't it outdated? I thought C++11 reconciled sfinae with access control.

**Comment by lrineau** [comment]
> No problem if you want to copy it, but isn't it outdated? I thought C++11 reconciled sfinae with access control.

You are right. The following code is rejected by clang with `-std=c++03` but accepted by it with `-std=c++11`.

```c++
class A {
    typedef int Ploum;
};

void f(A,int){}
template <class T> void f(T, typename T::Ploum){}

void g(){ f(A(),0); } // which f is called?
```

It is also accepted in both cases by gcc, and MSVC (tested with MSVC 2015). I tested using compiler explorer: https://godbolt.org/z/WKdbqTz9z
