### ISSUE TITLE
Broken hyperlink in Number_types

### ISSUE THREAD

**Issue by albert-github** [CGAL/cgal#5753]
## Issue Details

In the package Number_types (file Documentation/doc/biblio/geom.bib) there is a broken link to:
```
https://cs.nyu.edu/exact/core/
```

**Comment by afabri** [comment]
https://cs.nyu.edu/exact/core_pages/intro.html

**Comment by albert-github** [comment]
Not sure whether it is the correct reference, it goes to a general description though the bibtex entry lists an number of authors indicating a bit a higher level documentation (to me), but it might be the right entry point.

**Comment by afabri** [comment]
@albert-github indeed a better choice.

**Comment by lrineau** [comment]
Fixed by #5787.

**Comment by edcjones00** [comment]
As of Feb 27, 2022, The nyu page is partly broken and partly behind a password.  I suggest that CGAL needs to fully document CORE like it does gmp.

**Comment by lrineau** [comment]
> As of Feb 27, 2022, The nyu page is partly broken and partly behind a password. I suggest that CGAL needs to fully document CORE like it does gmp.

The link https://cs.nyu.edu/exact/doc/core.pdf still work. Which page were you referring to?

**Comment by edcjones00** [comment]
https://cs.nyu.edu/exact/core_pages/index.html
