### ISSUE TITLE
Broken hyperlink in Stream_support

### ISSUE THREAD

**Issue by albert-github** [CGAL/cgal#5754]
## Issue Details

In the package Stream_support (file Stream_support/doc/Stream_support/File_formats/Supported_file_formats.txt) there is a broken link to:
```
http://www.fabbers.com/tech/STL_Format
```

**Comment by afabri** [comment]
I don't see it to be broken.  It is also the external link given on the wikipedia

**Comment by albert-github** [comment]
The last few days (May 26, May31 and June 3) I got that it is not accessible and (by head also this morning I got that, but now I can access it as well.
