### ISSUE TITLE
Security risk regarding link to uni-bielefeld in package Surface_mesh

### ISSUE THREAD

**Issue by albert-github** [CGAL/cgal#5755]
## Issue Details

Not 100% a CGAL problem, but the link to:
```
https://graphics.uni-bielefeld.de/publications/imr11/
```
in the package Surface_mesh (file: Surface_mesh/doc/Surface_mesh/Surface_mesh.txt) gives a security risk:
```
Warning: Potential Security Risk Ahead
```
this is not that good and might be best to contact uni-bielefeld about this issue (better from an institute than from a private person).

**Comment by afabri** [comment]
We should just remove the link. The authors changed the university, the original implementation is no longer distributed.
