### ISSUE TITLE
Tetrahedral remeshing problem

### ISSUE THREAD

**Issue by sachaichbiah** [CGAL/cgal#5789]
## Issue Details

Dear Mr, Mrs, 
 
I contact you about your package : [https://doc.cgal.org/latest/Tetrahedral_remeshing/index.html]
I have tried to use it in the following way : 
First, I take a labelled voxel inr picture called liver.inr given in [https://doc.cgal.org/latest/Mesh_3/index.html#Mesh_3DomainsFromSegmented3DImages] , to obtain a mesh called liver_triangulation.inr
 
Then I want to refine this mesh using a function (enclosed) called tetrahedral_remeshing_medit, and obtain the following error : (see image bellow). 
Do you have any idea why this happens ? It looks like an overflow as it happens for no reason, but this is weird because my tetrahedral mesh is not very big compared to the ones studied in the paper. 
Thank you very much for your help !

## Source Code
```c++
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/Tetrahedral_remeshing/Remeshing_triangulation_3.h>
#include <CGAL/tetrahedral_remeshing.h>

#include <CGAL/IO/File_medit.h>

#include <fstream>

typedef CGAL::Exact_predicates_inexact_constructions_kernel K;

typedef CGAL::Tetrahedral_remeshing::Remeshing_triangulation_3<K> Tr;

int main(int argc, char* argv[])
{
  const char* filename = (argc > 1) ? argv[1] : "data/sphere.mesh";
  const char* filename_out = (argc > 2) ? argv[2] : "data/sphere_out.mesh";
  const double target_edge_length = (argc > 3) ? atof(argv[3]) : 0.1;
  
  Tr tr;

  std::ifstream is(filename, std::ios_base::in);
  CGAL::read_MEDIT(is, tr);

  CGAL::tetrahedral_isotropic_remeshing(tr, target_edge_length);

  std::ofstream os(filename_out);
  CGAL::write_MEDIT(os, tr);

  return EXIT_SUCCESS;
}
```

## Error picture 

<img width="941" alt="Error_tetrahedral_remeshing" src="https://user-images.githubusercontent.com/32900766/122790234-67aae300-d2b8-11eb-8ab0-f350ef46e86f.png">

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Mac OS Catalina
* Compiler:
* Release or debug mode: Release
* CGAL version: 5.2.2
* Boost version: 1.76.0
* Eigen : 3.3.9

**Comment by janetournois** [comment]
Dear @sachaichbiah ,
your source code looks correct. Can you please send the code you used to generate `liver_triangulation.mesh`, or the file itself?

**Comment by sachaichbiah** [comment]
`

`

**Comment by sachaichbiah** [comment]
Here is the code for generating the medit mesh. It is just a reformulation of the code given in the example from CGAL documentation. 

`
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>

#include <CGAL/Mesh_triangulation_3.h>
#include <CGAL/Mesh_complex_3_in_triangulation_3.h>
#include <CGAL/Mesh_criteria_3.h>

#include <CGAL/Labeled_mesh_domain_3.h>
#include <CGAL/make_mesh_3.h>
#include <CGAL/Image_3.h>

#include <CGAL/IO/File_medit.h>
#include <iostream>

// Domain
typedef CGAL::Exact_predicates_inexact_constructions_kernel K;
typedef CGAL::Labeled_mesh_domain_3<K> Mesh_domain;

#ifdef CGAL_CONCURRENT_MESH_3
typedef CGAL::Parallel_tag Concurrency_tag;
#else
typedef CGAL::Sequential_tag Concurrency_tag;
#endif

// Triangulation
typedef CGAL::Mesh_triangulation_3<Mesh_domain,CGAL::Default,Concurrency_tag>::type Tr;

typedef CGAL::Mesh_complex_3_in_triangulation_3<Tr> C3t3;

// Criteria
typedef CGAL::Mesh_criteria_3<Tr> Mesh_criteria;

// To avoid verbose function and named parameters call
using namespace CGAL::parameters;

int main(int argc, char* argv[])
{
  /// [Loads image]
  const char* fname = (argc>1)?argv[1]:"";
  const char* outname = (argc>2)?argv[2]:"out.mesh";
  double facet_angle = (argc > 3) ? atof(argv[3]) : 30;
  double facet_size = (argc > 4) ? atof(argv[4]) : 6;
  double facet_distance = (argc > 5) ? atof(argv[5]) : 4;
  double cell_radius_edge_ratio = (argc > 6) ? atof(argv[6]) : 3;
  double cell_size = (argc > 7) ? atof(argv[7]) : 8;


  CGAL::Image_3 image;
  if(!image.read(fname)){
    std::cerr << "Error: Cannot read file " <<  fname << std::endl;
    return EXIT_FAILURE;
  }
  
  /// [Loads image]

  /// [Domain creation]
  Mesh_domain domain = Mesh_domain::create_labeled_image_mesh_domain(image);
  /// [Domain creation]

  // Mesh criteria
  Mesh_criteria criteria(facet_angle=facet_angle, facet_size=facet_size, facet_distance=facet_distance,
                         cell_radius_edge_ratio=cell_radius_edge_ratio, cell_size=cell_size);

  /// [Meshing]
  C3t3 c3t3 = CGAL::make_mesh_3<C3t3>(domain, criteria);

  // Output
  std::ofstream medit_file(outname);
  CGAL::output_to_medit(medit_file,c3t3);
  return 0;
}
`

[Uploading liver_triangulation.mesh.zip…]()

**Comment by janetournois** [comment]
It turns out this issue actually is an I/O problem. I'll have a look at it.

As a temporary solution, you can run `CGAL::tetrahedral_isotropic_remeshing();` right away after `CGAL::make_mesh_3()` (see [this example](https://doc.cgal.org/latest/Tetrahedral_remeshing/Tetrahedral_remeshing_2mesh_and_remesh_polyhedral_domain_with_features_8cpp-example.html) )

**Comment by janetournois** [comment]
Hello @sachaichbiah ,

the pull-request #5693 will solve the issue you met.

Note that, using this branch, you need to save and load the `C3t3`, you have to use the functions : 
- [`CGAL::IO::write_MEDIT()`](https://cgal.github.io/5693/v3/MDS_3/group__PkgMDS3IOFunctions.html#gaa1f5784e19af4e399734724523d77163) (this doc is not final), will the `all_cells` parameter set to `true`,
- [`CGAL::IO::read_MEDIT()`](https://cgal.github.io/5693/v3/MDS_3/group__PkgMDS3IOFunctions.html#gae568272186821b0b236257819dbf55db)

I tested your examples and they work nicely with those

**Comment by sachaichbiah** [comment]
Thank you very much ! It works as expected
