### ISSUE TITLE
Confusing documentation of function is_ascii in StreamSupportpackage

### ISSUE THREAD

**Issue by albert-github** [CGAL/cgal#5795]
In the documentation file : Stream_support/group__PkgStreamSupportRef.html#ga0b83393fdb06a880a8f9c8778b6fb13e we see for the function `is_ascii`:

![image](https://user-images.githubusercontent.com/5223533/122929450-3dfec400-d36b-11eb-9301-401d662a4ddd.png)

i.e. in the "blue bar" there is an argument `i` but in the text this is referred to as `s`.

The problem comes from the source file: Stream_support/include/CGAL/IO/io.h where we read:
```
/*!
\ingroup PkgStreamSupportRef

checks if the %IO stream `s` is in `ASCII` mode.

\link PkgStreamSupportEnumRef `CGAL::IO::Mode`\endlink
\sa `CGAL::IO::set_mode()`
\sa `CGAL::IO::set_ascii_mode()`
\sa `CGAL::IO::set_binary_mode()`
\sa `CGAL::IO::set_pretty_mode()`
\sa `CGAL::IO::get_mode()`
\sa `CGAL::IO::is_binary()`
\sa `CGAL::IO::is_pretty()`
*/
inline bool is_ascii(std::ios& i) { return i.iword(Static::get_mode()) == ASCII; }
```

This problem is also with a number of other functions in this file (`is_...`, `set_...` functions).

Unfortunately no PR as I'm not sure whether the documentation or the code should be adjusted (what is preferred):
- documentation
   from:
   ```
   checks if the %IO stream `s` is in `ASCII` mode.
   ```
  to:
  ```
  checks if the %IO stream `i` is in `ASCII` mode.
  ```
- code
   from:
   ```
  inline bool is_ascii(std::ios& i) { return i.iword(Static::get_mode()) == ASCII; }
   ```
  to:
  ```
  inline bool is_ascii(std::ios& s) { return s.iword(Static::get_mode()) == ASCII; }
  ```

(note: code cannot be tested by me, so a code PR from me would be a PR into the dark ...)

**Comment by lrineau** [comment]
In my opinion, `s` is a better name for an "IO stream".
