### ISSUE TITLE
Windows Polyhedron demo from available zip files does not start

### ISSUE THREAD

**Issue by cjamin** [CGAL/cgal#5819]
I downloaded the Polyhedron demo (5.2.2 and 5.3-beta1) and the associated DLL files from the online documentation.

When I start it, I get the following message: "This application failed to start because it could not find or load the Qt platform plugin "windows" in "". Reinstalling the application may fix this problem."

Version 5.0 works fine, so I don't think this is related to my computer.

**Comment by maxGimeno** [comment]
https://github.com/CGAL/cgal/pull/5430 should have fixed that, but by the look of what we find in the doc, it has not been used. @lrineau what happens to the results sent from Gauguin, those are not the ones that one can download from the doc. Something remains to be done but I don't know what.

**Comment by janetournois** [comment]
Hello @cjamin ,

thanks for the report.

Can you please tell me
- if you have a version of Qt installed on your computer (and if so, which version number),
- if you have put everything from the two zip archives downloadable from the doc at the same place,
- if you have the environment variable `QT_QPA_PLATFORM_PLUGIN_PATH` set on your computer?

**Comment by janetournois** [comment]
Two more questions :
- do you have the `QT_PLUGIN_PATH` set in your environment?
- do you have MikteX installed on your computer? (from what I found it may be responsible for changes in your `PATH` that mislead the dlls finding process)

**Comment by cjamin** [comment]
Hi Jane,

Sorry for the late reply!

- Qt: yes, version 5.12.6
- Yes, I did put everything from the two zip archives downloadable from the doc at the same place
- No, I don't have `QT_QPA_PLATFORM_PLUGIN_PATH` set.
- No, I don't have `QT_PLUGIN_PATH ` set.
- No, I don't have MikteX.

Hope this helps!

**Comment by cjamin** [comment]
Just realized that the problem is solved in version 5.3 already.
In the versions that were available when I open this issue, the zip files were missing the file `platforms/qwindows.dll`.
