### ISSUE TITLE
Cannot find MKL on Ubuntu 20.04

### ISSUE THREAD

**Issue by vmartinlac** [CGAL/cgal#5829]
## Issue Details

FindMKL.cmake provided with CGAL 5.2.2 fails to detect MKL on Ubuntu 20.04.
The issue seems to be that libmkl_solver library was deprecated and is no longer shipped.

## Source Code

find_package(MKL REQUIRED)

## Environment

* Linux 64 Bit / Ubuntu 20.04
* CGAL version: 5.2.2
* MKL: 2020.0.166 (from Ubuntu repositories)

**Comment by lrineau** [comment]
Please retry with CGAL-5.2.3, published today. I think that was solved by the pull-requests https://github.com/CGAL/cgal/pull/5687 and  https://github.com/CGAL/cgal/pull/5732.
