### ISSUE TITLE
simplify_polygon.exe: Microsoft C++ exception: CGAL::Assertion_exception at memory location 0x0000000915F4EDD0.

### ISSUE THREAD

**Issue by lore1013** [CGAL/cgal#5832]
_Please use the following template to help us solving your issue._

## Issue Details

hi guys, i am new with this library and kinda new in c++ programming. i am trying to compile the example "simplify_polygon.cpp" but i get this error about assertion exeception

## Source Code
#include <boost/config.hpp>
#include <boost/version.hpp>
#if BOOST_VERSION >= 105600 && (! defined(BOOST_GCC) || BOOST_GCC >= 40500)
#include <iostream>
#include <fstream>
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/Polygon_with_holes_2.h>
#include <CGAL/Polyline_simplification_2/simplify.h>
#include <CGAL/IO/WKT.h>

namespace PS = CGAL::Polyline_simplification_2;

typedef CGAL::Exact_predicates_inexact_constructions_kernel K;
typedef CGAL::Polygon_2<K>                   Polygon_2;
typedef CGAL::Polygon_with_holes_2<K>        Polygon_with_holes_2;
typedef PS::Stop_below_count_ratio_threshold Stop;
typedef PS::Squared_distance_cost            Cost;

int main(int argc, char* argv[])
{
  std::ifstream ifs( (argc==1)?"data/polygon.wkt":argv[1]);
  Polygon_with_holes_2 polygon;
  CGAL::read_polygon_WKT(ifs, polygon);
  Cost cost;
  polygon = PS::simplify(polygon, cost, Stop(0.5));

  std::cout.precision(12);
  CGAL::write_polygon_WKT(std::cout, polygon) << std::endl;

  return 0;
}
#else
int main()
{
  return 0;
}
#endif

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows 10-64 bits
* Compiler: MSVC
* Release or debug mode: debug
* Specific flags used (if any):
* CGAL version:5.22
* Boost version:1_75
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by sloriot** [comment]
Does it happen with any input file or with a particular one?

**Comment by lore1013** [comment]
there is no input file, i am using what is provided from the example

**Comment by sloriot** [comment]
Just to be sure, `data/polygon.wkt` is a valid path from where you run the exe?

**Comment by lore1013** [comment]
no it was not, i've changed the path and it worked!
thanks for your help.
sry that i ask such a dumb question.
thanks!
