### ISSUE TITLE
Incorrerct conversion of Nef_polyhedron_3 to Surface_mesh

### ISSUE THREAD

**Issue by dpapavas** [CGAL/cgal#5833]
There seems to be a problem with the conversion from `Nef_polyhedron_3` to `Surface_mesh`, as carried out with `CGAL::convert_nef_polyhedron_to_polygon_mesh`.  The [attached](https://github.com/CGAL/cgal/files/6769221/neftomesh.zip) test program illustrates the problem with the simplest geometry I could find.  When inspecting the `mesh.off` output file via Geomview for instance,  spurious faces can be seen.

The problem seems to be specific to that particular conversion process, as it is not present when converting to a `Polyhedron_3` instead, or when converting to a `Surface_mesh` via `Polyhedron_3`  (as the test code shows).

**Comment by sloriot** [comment]
The output is valid, it is only an issue with the software not being able to display non triangular faces.
Here is what I see with the CGAL Polyhedron demo:
![Screenshot from 2021-07-06 13-22-01](https://user-images.githubusercontent.com/1224632/124592032-4c65d900-de5d-11eb-9a68-28b784e829d6.png)
Note that [`convert_nef_polyhedron_to_polygon_mesh()`](https://doc.cgal.org/latest/Nef_3/group__PkgNef3IOFunctions.html#ga2e47f1a21e5b35af36c7ef665c66e848) has a parameter to triangulate or not faces.

**Comment by dpapavas** [comment]
Ah, indeed.  The conversion to `Polyhedron_3` just leads to triangulated output.  I had suspected Geomview being the culprit, but Meshlab failed in exactly the same way.  Thanks for the speedy explanation (and also for the heads up on the `triangulate_all_faces` parameter, which I had missed).
