### ISSUE TITLE
 Clip mesh with texture coordinates 

### ISSUE THREAD

**Issue by ligaofeng0901** [CGAL/cgal#5835]
## Issue Details

Dear developer

I use the clip function to clip a surface mesh by a cube, and I add a property map named v:uv to surface mesh as the texture coordinates. After clipping, some new vertices are generated, but the  corresponding value of the property v:uv is zero. As I know, a new vertex is always on the edge of original mesh, so I can get a new value of texture coordinates by linear interpolation. But I don’t know how to implement it, can you give me some advices？thank you very much.

## Source Code

_If your issue arises by using CGAL in your own source code, please provide a minimalist example that we can compile easily to reproduce the bug. If your issue arises from using a CGAL program (demo, example, etc.), please let us know which one. Helping you solving an issue is much easier and efficient if we can reproduce it._

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):
* Compiler:
* Release or debug mode:
* Specific flags used (if any):
* CGAL version:
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by sloriot** [comment]
There is no direct way to track the creation of new vertices. I would have to extend the following concept:
https://doc.cgal.org/latest/Polygon_mesh_processing/classPMPCorefinementVisitor.html to add vertex management (in addition to face and edges).

There is one solution if you are using `Surface_mesh` as input mesh type. Since the mesh will be first refined before being  clipped, you first call `collect_garbage()` before clip, save the number of vertices and then do the clip. All vertices with an id larger or equal to the saved number of vertices is a new vertex.

**Comment by ligaofeng0901** [comment]
> There is no direct way to track the creation of new vertices. I would have to extend the following concept:
> https://doc.cgal.org/latest/Polygon_mesh_processing/classPMPCorefinementVisitor.html to add vertex management (in addition to face and edges).
> 
> There is one solution if you are using `Surface_mesh` as input mesh type. Since the mesh will be first refined before being clipped, you first call `collect_garbage()` before clip, save the number of vertices and then do the clip. All vertices with an id larger or equal to the saved number of vertices is a new vertex.

@sloriot Thanks for your reply. According to your suggestion, I can get all new vertices, and I should determine the triangle that a new vertex is in one by one, then get the new  value of texture coordinate by linear interpolation. It's just kind of complicated. Is there some other ways to  track the creation of new vertices when clipping? If I can visit a new vertex and an original face that the new vertex is in, I can modify the value of texture coordinate directly. My input mesh does't have to be surface mesh, It's just some vertices and triangulated faces. Is there a better input mesh type for my data?
