### ISSUE TITLE
Processing 3D model data with PMP

### ISSUE THREAD

**Issue by ligaofeng0901** [CGAL/cgal#5836]
## Issue Details

Dear developer

Ｉam using cgal library to process some 3D data. I read some models from file, and then invoke the PMP functions like clip, edge_collapse, etc. the problem is that the 3D models are not always strict surface mesh, there may have some self-intersections or coplanar issues, and cause a failure of processing. Is there a way to ignore these issues. My model data has been triangulated, can you help me? Thanks a lot!

## Source Code

_If your issue arises by using CGAL in your own source code, please provide a minimalist example that we can compile easily to reproduce the bug. If your issue arises from using a CGAL program (demo, example, etc.), please let us know which one. Helping you solving an issue is much easier and efficient if we can reproduce it._

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):
* Compiler:
* Release or debug mode:
* Specific flags used (if any):
* CGAL version:
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by sloriot** [comment]
You can call some internal heal functions (undocumented for now).

`CGAL/Polygon_mesh_processing/repair_degeneracies.h` provides `remove_degenerate_faces()`
`CGAL/Polygon_mesh_processing/repair_self_intersections.h` provides `remove_self_intersections()`
