### ISSUE TITLE
Bad Access in CGAL::Handle for CGAL::Epeck

### ISSUE THREAD

**Issue by alecjacobson** [CGAL/cgal#584]
Here's a little program that causes a memory violation.

```cpp
#include <CGAL/Exact_predicates_exact_constructions_kernel.h>
int main()
{
  CGAL::Epeck::FT v = 0;
  for(int i = 0;i<30825; i++)
  {
    v += 0;
  }
}
```

I'm using Apple LLVM version 7.0.2 (clang-700.1.81) on Mac OS X. If I change `30825` to `30824`, it runs OK. The problem seems to be related to the number of times `+=` is called.

If I switch to gcc 5.2 then the magic number is `43668`.

**Comment by afabri** [comment]
The Exact_predicates_exact_constructions_kernel stores a directed acyclic graph of the operations, where each node stores an approximation (interval of doubles) the operation, and handles of the child nodes.  The error happens in the destructor, when it calls the destructor of the child of the destructror of the grand child ...   and the error is a stackoverflow. 

We could derecursify this (and we then better at the same time derecursified the function `exact()`), but I am wondering if your usage of this lazy kernel is appropriate. When we present CGAL, we state that this lazy approach is not well suited for  iterative algorithms, and  I guess that is what your real application is about (thank you for having boiled it  down).

**Comment by alecjacobson** [comment]
Thanks for the clarification. I guess another option would be to throw an assertion if the graph gets too big, but then I suppose "too big" is machine/compilation dependent.

**Comment by afabri** [comment]
One way to go is to keep track of the depth of the dag,
and to evaluate the dag when a threshold is reached.
You would then loose performance wise as this means
that all the operations in the DAG that were done only
with interval arithmetic will now be done with Gmpq.

But again, what is your application like that this
problem occurs?

**Comment by alecjacobson** [comment]
Say, summing the areas of a triangle mesh where each area is computed exactly and there are more than 38,000 triangles.

**Comment by afabri** [comment]
Split in two and sum recursively

andreas

**Comment by sloriot** [comment]
Note that if you really want the exact value at the end (and not an approximation), then you can directly sum the exact value (using `CGAL::to_exact()`) of the area. That way you'll not increase the size of the DAG.
On the other hand if you want a controlled approximation, you can sum up the interval (`CGAL::to_interval()`).

**Comment by alecjacobson** [comment]
Is a sum of the floating-point intervals around A and B guaranteed to be an
interval of the sum of the exact numbers A and B?

**Comment by afabri** [comment]
that's the whole point of using interval arithmetic.

**Comment by alecjacobson** [comment]
I guess I'm not super familiar with the details, but don't you need to
round A_upper + B_upper up and A_lower+B_lower down?  I.e. you can't just
use floating-point summation of the lower and upper bounds? (Or maybe
Sebastien meant to use some special interval addition function?)

**Comment by afabri** [comment]
Interval_nt is a full fledged number type, and provides operator *, + , etc which take care of  error propagation.

**Comment by alecjacobson** [comment]
Oh, then I misunderstood. I thought Sebastien was recommending to use the [CGAL::to_interval](http://doc.cgal.org/latest/Algebraic_foundations/group__PkgAlgebraicFoundations.html#gac30124cb713e69f02816e2b91c655fa6) that returns a `std::pair<double,double>` and then just simple sum the double intervals using usual double addition.

**Comment by afabri** [comment]
You are right that we were not precise enough.
The number type (Lazy_exact_nt) has a function [approx()](http://doc.cgal.org/latest/Number_types/classCGAL_1_1Lazy__exact__nt.html#a64d3fed7afc36f054e3472c1af98452e) that gives you the interval.
