### ISSUE TITLE
Let Doxygen 1.8.4 have a peaceful retirement. Prepare 1.9.1

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#5840]
> I agree it would be nice let Doxygen 1.8.4 have a peaceful retirement. That column helped us transition from 1.8.4 to 1.8.13, but it would be a good time to start the transition from 1.8.13 to... 1.9.1?

We could shift the columns:
  - move 1.8.13 to the first one,
  - have 1.9.1 as the second one,
  - and keep doxygen-master in the last one.
  
@maxGimeno Would it be easy to implement?

_Originally posted by @lrineau in https://github.com/CGAL/cgal/issues/5800#issuecomment-876351121_

**Comment by lrineau** [comment]
@sloriot Do we still need to compile Doxygen with a patch, to support... something specific to CGAL that I do not remember?

**Comment by maxGimeno** [comment]
I'll look into it

**Comment by sloriot** [comment]
Yes, cf https://github.com/CGAL/cgal/issues/1799

**Comment by albert-github** [comment]
See https://github.com/CGAL/cgal/issues/1799#issuecomment-876596085
