### ISSUE TITLE
building project "reconstruction_structured.vcxproj" -- FAILED.

### ISSUE THREAD

**Issue by LeoYang-Chuese** [CGAL/cgal#5844]
_Please use the following template to help us solving your issue._

###### Compile output:

1>------ Build started: Project: reconstruction_structured, Configuration: Debug x64 ------
1>reconstruction_structured.cpp
1>D:\dev\CGAL-5.3\include\CGAL/Shape_detection/Efficient_RANSAC/Octree.h(1,1): warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss
1>D:\dev\CGAL-5.3\include\CGAL/Shape_detection/Efficient_RANSAC/Octree.h(46,1): error C2947: expecting '>' to terminate template-argument-list, found '<'
1>D:\dev\CGAL-5.3\include\CGAL/Shape_detection/Efficient_RANSAC/Octree.h(46,66): error C2365: 'Gt': redefinition; previous definition was 'template parameter'
1>D:\dev\CGAL-5.3\include\CGAL/Shape_detection/Efficient_RANSAC/Octree.h(45): message : see declaration of 'Gt'
1>D:\dev\CGAL-5.3\include\CGAL/Shape_detection/Efficient_RANSAC/Octree.h(46,68): error C2988: unrecognizable template declaration/definition
1>D:\dev\CGAL-5.3\include\CGAL/Shape_detection/Efficient_RANSAC/Octree.h(46,68): error C2059: syntax error: ','
1>D:\dev\CGAL-5.3\include\CGAL/Shape_detection/Efficient_RANSAC/Octree.h(47,1): error C2143: syntax error: missing ';' before '{'
1>D:\dev\CGAL-5.3\include\CGAL/Shape_detection/Efficient_RANSAC/Octree.h(47,1): error C2447: '{': missing function header (old-style formal list?)
1>D:\dev\CGAL-5.3\include\CGAL/boost/graph/Euler_operations.h(1,1): warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss
1>D:\dev\CGAL-5.3\include\CGAL/boost/graph/Euler_operations.h(1,1): warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss
1>Done building project "reconstruction_structured.vcxproj" -- FAILED.

###### Error List:

- Severity	Code	Description	Project	File	Line	Suppression State
  Error	C2947	expecting '>' to terminate template-argument-list, found '<'	reconstruction_structured	D:\dev\CGAL-5.3\include\CGAL\Shape_detection\Efficient_RANSAC\Octree.h	46	
- Severity	Code	Description	Project	File	Line	Suppression State
  Error	C2365	'Gt': redefinition; previous definition was 'template parameter'	reconstruction_structured	D:\dev\CGAL-5.3\include\CGAL\Shape_detection\Efficient_RANSAC\Octree.h	46	
- Severity	Code	Description	Project	File	Line	Suppression State
  Error	C2988	unrecognizable template declaration/definition	reconstruction_structured	D:\dev\CGAL-5.3\include\CGAL\Shape_detection\Efficient_RANSAC\Octree.h	46	
- Severity	Code	Description	Project	File	Line	Suppression State
  Error	C2059	syntax error: ','	reconstruction_structured	D:\dev\CGAL-5.3\include\CGAL\Shape_detection\Efficient_RANSAC\Octree.h	46		
- Severity	Code	Description	Project	File	Line	Suppression State
  Error	C2143	syntax error: missing ';' before '{'	reconstruction_structured	D:\dev\CGAL-5.3\include\CGAL\Shape_detection\Efficient_RANSAC\Octree.h	47	
- Severity	Code	Description	Project	File	Line	Suppression State
  Error	C2447	'{': missing function header (old-style formal list?)	reconstruction_structured	D:\dev\CGAL-5.3\include\CGAL\Shape_detection\Efficient_RANSAC\Octree.h	47		

## Source Code

CGAL-5.3\examples\Advancing_front_surface_reconstruction\reconstruction_structured.cpp

## Environment

* Operating system (Windows 19042, 64 bits):
* Compiler:Visual Studio 2019 (v142)
* Release or debug mode:Debug and Release
* Specific flags used (if any):
* CGAL version:V5.3
* Boost version:V1.71.0
* Other libraries versions if used (Eigen V3.2.1):

**Comment by sloriot** [comment]
Could you give some details about what you did? Was `reconstruction_structured.vcxproj` generated using cmake?

**Comment by LeoYang-Chuese** [comment]
Installing from the Source Archive,using the default configuration for projects generated by cmake.

**Comment by LeoYang-Chuese** [comment]
The Triangulation_2 example and the Advancing_front_surface_reconstruction/reconstruction_class.cpp example can be compiled successfully.

**Comment by LeoYang-Chuese** [comment]
Example project built with cmake.

[Advancing_front_surface_reconstruction.zip](https://github.com/CGAL/cgal/files/6790200/Advancing_front_surface_reconstruction.zip)

**Comment by maxGimeno** [comment]
Isn't there a line number for the first error ? It seems to indicate that a `>` is not recognized, it would be helpful to know which one.

**Comment by sloriot** [comment]
Maxime forgot to mentioned that he tried to reproduce the issue on a computer with a similar config but did not have any error. You can also attached the full log if it is easier (but usually the first error is the one that matters)

**Comment by LeoYang-Chuese** [comment]
Updated the error log. I tried to find a similarly configured computer to reproduce the problem, thanks for the reply.

**Comment by sloriot** [comment]
Seems to be an encoding issue of the file but I don't see any problem (`file` says that it's UTF-8 Unicode text). Maybe it comes from the configuration of you MS compiler. Never saw that before.

**Comment by LeoYang-Chuese** [comment]
> Seems to be an encoding issue of the file but I don't see any problem (`file` says that it's UTF-8 Unicode text). Maybe it comes from the configuration of you MS compiler. Never saw that before.

You are absolutely right, the compilation was successful after modifying the coding, thanks a lot.
