### ISSUE TITLE
cmake install failed for CGAL-5.3-library.tar.xz

### ISSUE THREAD

**Issue by unclejimbo** [CGAL/cgal#5852]
The demo resources get installed even if `WITH_demos=OFF`
```
CMake Error at cmake_install.cmake:50 (file):
  file INSTALL cannot find
  "/home/unclejimbo/Software/cgal-headers/src/CGAL-5.3/demo/resources": No
  such file or directory.
```

**Comment by lrineau** [comment]
I can reproduce, and that is a reason to publish a bug-fx version CGAL-5.3.1 as soon as we can. We'll work on this issue...

**Comment by lrineau** [comment]
Fixed by https://github.com/CGAL/cgal/pull/5853.

**Comment by lrineau** [comment]
Actually, the fix was not completely right. I modified it with https://github.com/CGAL/cgal/pull/6023.
