### ISSUE TITLE
CGal Polyline

### ISSUE THREAD

**Issue by petrasvestartas** [CGAL/cgal#5856]
Hi,

Is there any example how could I use polygons in 3d?
I just want to use a data structure of polyline with xyz coordinates instead of xy.

**Comment by GilesBathgate** [comment]
It depends what you want to do with the polyline. It could just be a list of `Point_3` or it could be a list of `Segment_3` with the target vertex equal to the next segments source vertex...

**Comment by petrasvestartas** [comment]
Is it possible to have both I sometimes need to work with point array and sometimes work with line segments?

Is there any example for a polyline with a Point_3 property?

**Comment by GilesBathgate** [comment]
You are probably better off looking at functions that take a polyline, e.g: https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__predicates__grp.html#ga2cb4019111658999234b3e377e3eabcd

https://doc.cgal.org/latest/Nef_3/Nef_3_2polyline_construction_8cpp-example.html

There is no standard class to encapsulate a so-called `Polyline_3` though.

**Comment by sloriot** [comment]
There is no data structure to represent points in CGAL. There are also only a few functions in PMP that deal with polylines. All of them are expecting a range of points as polyline.

**Comment by petrasvestartas** [comment]
Thank you, if I understand correctly there is no curve like data structure, that help to get i.e. frames on polylines, polyline derivatives like in curves,  and similar geometry properties. Do you know any c++ library that has 3d polyline data type with extensive functions for working with them?

**Comment by sloriot** [comment]
Sorry I don't.
