### ISSUE TITLE
constexpr floating point and CGAL

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#5862]
If I'm not mistaken CGAL redefines the operators for C++ data types like `float` and `double` so that the following code no longer compiles when linking against CGAL:

``` cpp
constexpr float deg_to_rad = M_PI / 180.0f;
```

GCC 9.3.0 using the `--std=c++17` flag produces the following error:

``` text
error: ‘(3.1415926535897931e+0 / 1.8e+2)’ is not a constant expression
```

This code compiles fine without linking CGAL.

So I would argue this is more of an issue to be fixed than a new feature.

_Originally posted by @sotpapathe in https://github.com/CGAL/cgal/issues/5123#issuecomment-884208324_

**Comment by lrineau** [comment]
CGAL does interfere with operators for native types. The issue is that gcc, in older versions, does not allow `constexpr` floating point expressions with the compiler flag `-frounding-math` is used. And CGAL needs it, and enforces it.

**Comment by mglisse** [comment]
#3180

**Comment by sotpapathe** [comment]
Thanks for the clarification! It compiles fine with clang so that's another possible workaround for now. Feel free to close the issue.
