### ISSUE TITLE
FPU Warning on ARM machines

### ISSUE THREAD

**Issue by maxGimeno** [CGAL/cgal#5864]
## Issue Details

When running tests on our arm mac machine, I get those warnings :
```
/Users/magritte/cgal/Number_types/include/CGAL/FPU.h:480:21: warning: value size does not match register size specified by the constraint and modifier [-Wasm-operand-widths]
    CGAL_IA_GETFPCW(cw);
                    ^
/Users/magritte/cgal/Number_types/include/CGAL/FPU.h:480:5: note: use constraint modifier "w"
    CGAL_IA_GETFPCW(cw);
    ^
/Users/magritte/cgal/Number_types/include/CGAL/FPU.h:452:48: note: expanded from macro 'CGAL_IA_GETFPCW'
#define CGAL_IA_GETFPCW(CW) asm volatile ("MRS %0, FPCR" : "=r" (CW))
                                               ^
/Users/magritte/cgal/Number_types/include/CGAL/FPU.h:490:19: warning: value size does not match register size specified by the constraint and modifier [-Wasm-operand-widths]
  CGAL_IA_SETFPCW(cw);
                  ^
/Users/magritte/cgal/Number_types/include/CGAL/FPU.h:490:3: note: use constraint modifier "w"
  CGAL_IA_SETFPCW(cw);
  ^
/Users/magritte/cgal/Number_types/include/CGAL/FPU.h:451:54: note: expanded from macro 'CGAL_IA_SETFPCW'
#define CGAL_IA_SETFPCW(CW) asm volatile ("MSR FPCR, %0" : :"r" (CW))
                                                     ^
```
This appears when CMAKE_NO_SYSTEM_FROM_IMPORTED is ON. 

@mglisse, do you have any idea what is wrong here ?
## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Mac
* Compiler:Apple clang version 12.0.0 (clang-1200.0.32.29)
* Release or debug mode:Debug
* Specific flags used (if any):CMAKE_NO_SYSTEM_FROM_IMPORTED=TRUE
* CGAL version:all

**Comment by mglisse** [comment]
This reminds me of
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=63359
"r" is for 64 bits unless you use a "w" modifier like "mrs %w0,fpcr".

**Comment by maxGimeno** [comment]
> "r" is for 64 bits unless you use a "w" modifier like "mrs %w0,fpcr".

I'm not sure I understand. The platform is arm64 bits, so "r" looks like the right choice.

**Comment by lrineau** [comment]
The variable is of type `unsigned int`, probably 32 bits on that platform.

@mglisse So, the fix would be to turn `%0` into `%w0`, that way?
```
# elif defined __VFP_FP__ && !defined __SOFTFP__
#define CGAL_IA_SETFPCW(CW) asm volatile ("VMSR FPSCR, %w0" : :"r" (CW))
#define CGAL_IA_GETFPCW(CW) asm volatile ("VMRS %w0, FPSCR" : "=r" (CW)); CW &= CGAL_FE_TOWARDZERO
typedef unsigned int FPU_CW_t;
```

**Comment by mglisse** [comment]
Hmm, right, the doc says MRS expects a 64-bit register... :confused:

**Comment by lrineau** [comment]
They the fix is a change of the typedef, right?
```c++
typedef unsigned long FPU_CW_t;
```

**Comment by mglisse** [comment]
Apparently MRS really wants a 64-bit register, so `%w0` would not work. If we pass a 32-bit integer, compilers just use the 64-bit name of that register, and everything works fine, the warning is harmless. Passing a 64-bit integer should also be fine.
With glibc, there is a file `<fpu_control.h>` that provides _FPU_GETCW (as builtin or inline asm), I don't know if macosx has something similar.

**Comment by maxGimeno** [comment]
> Apparently MRS really wants a 64-bit register, so %w0 would not work. 

Indeed, the compiler fails to build when I add it.
> Passing a 64-bit integer should also be fine.

That's the impression I get, it removes the warning. Let's test it in a testsuite and we'll probably keep that, the warning may be harmless but it adds a lot of yellow to the testsuite results :/.

**Comment by lrineau** [comment]
> With glibc, there is a file `<fpu_control.h>` that provides _FPU_GETCW (as builtin or inline asm), I don't know if macosx has something similar.

Well, on my machine, `_FPU_GETCW` uses the old FPU x87 control word:
```c++
/* [...]
   Note that the use of these macros is not sufficient anymore with
   recent hardware nor on x86-64.  Some floating point operations are
   executed in the SSE/SSE2 engines which have their own control and
   status register.  */
#define _FPU_GETCW(cw) __asm__ __volatile__ ("fnstcw %0" : "=m" (*&cw))
#define _FPU_SETCW(cw) __asm__ __volatile__ ("fldcw %0" : : "m" (*&cw))
```
so, that is a bad example to follow blindly.

**Comment by lrineau** [comment]
Fixed by https://github.com/CGAL/cgal/pull/5866.
