### ISSUE TITLE
read_LAS() could not be used??

### ISSUE THREAD

**Issue by tub-sgg** [CGAL/cgal#5869]
## Issue Details

I installed CGAL by make install, and the LAS.h has already existed in the folder /usr/local/include/CGAL/Point_set_3/IO
but there is an error :error: ‘read_LAS’ is not a member of ‘CGAL::IO’

## Source Code

```
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/Point_set_3.h>
#include <CGAL/Point_set_3/IO.h>
#include <CGAL/Point_set_3/IO/LAS.h>
#include <CGAL/remove_outliers.h>
#include <CGAL/grid_simplify_point_set.h>
#include <CGAL/jet_smooth_point_set.h>
#include <CGAL/jet_estimate_normals.h>
#include <CGAL/mst_orient_normals.h>
#include <CGAL/poisson_surface_reconstruction.h>
#include <CGAL/Advancing_front_surface_reconstruction.h>
#include <CGAL/Scale_space_surface_reconstruction_3.h>
#include <CGAL/Scale_space_reconstruction_3/Jet_smoother.h>
#include <CGAL/Scale_space_reconstruction_3/Advancing_front_mesher.h>
#include <CGAL/Surface_mesh.h>
#include <CGAL/Polygon_mesh_processing/polygon_soup_to_polygon_mesh.h>
#include <cstdlib>
#include <vector>
#include <fstream>
// #include <CGAL/IO/read_las_points.h>
#include <CGAL/Point_set_3/IO/LAS.h>

// types
typedef CGAL::Exact_predicates_inexact_constructions_kernel Kernel;
typedef Kernel::FT FT;
typedef Kernel::Point_3 Point_3;
typedef Kernel::Vector_3 Vector_3;
typedef Kernel::Sphere_3 Sphere_3;
typedef CGAL::Point_set_3<Point_3, Vector_3> Point_set;
int main(int argc, char*argv[])
{
  Point_set points;
  
  CGAL::IO::read_LAS("building_block_a_las.las",points);
return EXIT_SUCCESS;
}
```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):Linux 18.04
* Compiler:g++
* Release or debug mode:release
* Specific flags used (if any):
* CGAL version:5.3
* Boost version:1.72
* Other libraries versions if used (Eigen, TBB, etc.):Eigen3 3.3

**Comment by maxGimeno** [comment]
Did you link your progam with LASLIB ?

**Comment by lrineau** [comment]
`CGAL::IO::read_LAS` is declared in `<CGAL/Point_set_3/IO/LAS.h>`, but only if the preprocessor macro `CGAL_LINKED_WITH_LASLIB` is defined. That macro is defined by CGAL CMake script, when LAS is correctly found by LAS. If you use another build system, then you have to define the macro yourself.

@CGAL/geometryfactory I wonder if that macro `CGAL_LINKED_WITH_LASLIB` is documented. It does not seem so.

**Comment by sloriot** [comment]
```
230:\subsection thirdpartyLASlib LASlib
233:the LAS format (or the compressed LAZ format).
238:imported target `CGAL::LASLIB_support` provided in
239:`CGAL_LASLIB_support.cmake`.
```
is the official doc.

**Comment by lrineau** [comment]
> [https://doc.cgal.org/latest/Manual/thirdparty.html#thirdpartyLASlibAL_LASLIB_support.cmake`](https://doc.cgal.org/latest/Manual/thirdparty.html#thirdpartyLASlibAL_LASLIB_support.cmake%60). is the official doc, that is only the cmake macro is documented.

That is right: since recent releases (maybe only in CGAL-5.3), we document the CMake API. Maybe for CGAL-5.4 we should document how to use CGAL without CMake at all.

**Comment by sloriot** [comment]
What about adding an extra macro like CGAL_DO_NOT_USE_CMAKE that if defined defines all third-party lib macros. That way people get include errors and know that they will have to fix a dependency issue. That way we only document one macro.

**Comment by tub-sgg** [comment]
yes , when I and  macro CGAL_LINKED_WITH_LASLIB using add_definitions(-DCGAL_LINKED_WITH_LASLIB)  now the error is: /usr/local/include/CGAL/IO/read_las_points.h:48:10: fatal error: lasreader_las.hpp: No such file or directory
   48 | #include <lasreader_las.hpp>
      |          ^~~~~~~~~~~~~~~~~~~

indeed there is no such file in this folder. So do i NEED to install LASlib or this function depends on LASlib??

**Comment by tub-sgg** [comment]
thanks, this function depends on LASlib, when I install LASlib and modify the CMakeLists.txt
add_definitions(-DCGAL_LINKED_WITH_LASLIB)
find_package( LASlib REQUIRED )
.....
target_link_libraries(xxxx 
                      LASlib)
gnerate and configure it again and it works now.
Hoep this can also help someone who encounters a similar problem

**Comment by maxGimeno** [comment]
LASlib is listed in CGAL's dependencies list. Have a look at https://doc.cgal.org/latest/Manual/thirdparty.html#thirdpartyLASlib. You won't get any LAS IO CGAL function without LAS.
