### ISSUE TITLE
Geomview_stream_impl.h error

### ISSUE THREAD

**Issue by acgetchell** [CGAL/cgal#5873]
## Issue Details

Using CGAL 5.3 and the setting `-DCGAL_USE_GEOMVIEW` produces the following error:

```
In file included from /Users/adam/projects/CDT-plusplus/src/cdt-gv.cpp:19:
In file included from /Users/adam/projects/CDT-plusplus/vcpkg_installed/x64-osx/include/CGAL/IO/Geomview_stream.h:600:
/Users/adam/projects/CDT-plusplus/vcpkg_installed/x64-osx/include/CGAL/IO/Geomview_stream_impl.h:200:24: error: non-const lvalue reference to type 'std::ios' (aka 'basic_ios<char>') cannot bind to a value of unrelated type 'bool'
    IO::set_ascii_mode(bin_bak);
                       ^~~~~~~
/Users/adam/projects/CDT-plusplus/vcpkg_installed/x64-osx/include/CGAL/IO/io.h:473:38: note: passing argument to parameter 'i' here
inline Mode set_ascii_mode(std::ios& i)
                                     ^
1 error generated.
```

Examples:

https://travis-ci.com/github/acgetchell/CDT-plusplus/jobs/527301421#L4089

https://github.com/acgetchell/CDT-plusplus/runs/3177622399?check_suite_focus=true#step:6:111

## Source Code

The relevant line is simply:

```
#include <CGAL/IO/Geomview_stream.h>
```

https://github.com/acgetchell/CDT-plusplus/blob/develop/src/cdt-gv.cpp#L19

## Environment

* Operating system: macOS 11.5.1, Ubuntu 20.04
* Compiler: Apple clang version 12.0.5 (clang-1205.0.22.11), gcc-10, clang-10
* Release or debug mode: Both
* Specific flags used (if any): -DCGAL_USE_GEOMVIEW
* CGAL version: 5.3
* Boost version: 1.76
* Other libraries versions if used (Eigen, TBB, etc.): eigen 3.3.9, tbb 2020_U3

Full list here:

https://travis-ci.com/github/acgetchell/CDT-plusplus/jobs/527301421#L1127

**Comment by lrineau** [comment]
That is strange. Try a local fix in `include/CGAL/IO/Geomview_stream_impl.h`, line. Call
```c++
    this->set_ascii_mode(bin_bak);
```
instead of
```c++
    set_ascii_mode(bin_bak);
```
I do not understand the lookup, here.

**Comment by acgetchell** [comment]
After making that local change I still get:

```
[18/27] Building CXX object src/CMakeFiles/cdt-gv.dir/cdt-gv.cpp.o
FAILED: src/CMakeFiles/cdt-gv.dir/cdt-gv.cpp.o 
/usr/local/bin/ccache /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DCGAL_TRIANGULATION_NO_ASSERTIONS -DCGAL_TRIANGULATION_NO_POSTCONDITIONS -DCGAL_USE_GEOMVIEW -DCGAL_USE_GMPXX=1 -DFMT_HEADER_ONLY=1 -I../include -isystem ../vcpkg_installed/x64-osx/include/docopt -isystem ../vcpkg_installed/x64-osx/include -isystem /usr/local/include -isystem ../vcpkg_installed/x64-osx/share/cgal/../../include -O2 -g -DNDEBUG -flto=thin -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk -Wall -Wextra -Wshadow -Wnon-virtual-dtor -Wold-style-cast -Wcast-align -Wunused -Woverloaded-virtual -Wpedantic -Wconversion -Wsign-conversion -Wnull-dereference -Wdouble-promotion -Wformat=2 -std=c++17 -MD -MT src/CMakeFiles/cdt-gv.dir/cdt-gv.cpp.o -MF src/CMakeFiles/cdt-gv.dir/cdt-gv.cpp.o.d -o src/CMakeFiles/cdt-gv.dir/cdt-gv.cpp.o -c ../src/cdt-gv.cpp
In file included from ../src/cdt-gv.cpp:19:
In file included from ../vcpkg_installed/x64-osx/include/CGAL/IO/Geomview_stream.h:600:
../vcpkg_installed/x64-osx/include/CGAL/IO/Geomview_stream_impl.h:200:24: error: non-const lvalue reference to type 'std::ios' (aka 'basic_ios<char>') cannot bind to a value of unrelated type 'bool'
    IO::set_ascii_mode(bin_bak);
                       ^~~~~~~
../vcpkg_installed/x64-osx/include/CGAL/IO/io.h:473:38: note: passing argument to parameter 'i' here
inline Mode set_ascii_mode(std::ios& i)
                                     ^
1 error generated.
```

**Comment by lrineau** [comment]
Adam, what are you using `CGAL::Geomview_stream` for? Geomview as a software is an abandonware, as far as I know, and its support in CGAL is abandoned as well (we do not test it, and indeed it no longer compiles). Is there a way you could stop using it in your own software?

**Comment by acgetchell** [comment]
I am trying to output and display graphical models of my Delaunay triangulations without necessarily having to install Qt (which last time I tried was complex).

I can certainly try something else, what is recommended?

The Visualization section lists:

- Geomview
- Qt5
- IPE

IPE only does 2D figures, so that leaves Geomview and Qt5.

If Geomview is deprecated the documentation should probably reflect that:

https://doc.cgal.org/latest/Geomview/index.html

I'll work my way through the Qt documentation.

Thank you.

**Comment by gdamiand** [comment]
I think the recommended is Qt.

Do you have any suggestion of any other tool that you would like to be available in cgal?

**Comment by acgetchell** [comment]
As long as it can be saved in *.OFF I will probably just import it into Mathematica.

**Comment by gdamiand** [comment]
Off format cannot be used for 3D objects but only for surfacic ones.

**Comment by acgetchell** [comment]
https://reference.wolfram.com/language/ref/format/OFF.html

**Comment by gdamiand** [comment]
There is nothing in this link about VOLUMIC object. 3D is not volumic.

OFF is not clearly defined: it is not clear if it allows non manifold edge (i.e. an edge incident to more than 2 faces). I think many tools (like meshlab) does not support off files with non manifold edges (and thus volumic objects). And I think this is also the case of many cgal methods.
