### ISSUE TITLE
When building a polyhedron redundant vertices cause a segmentation fault

### ISSUE THREAD

**Issue by efifogel** [CGAL/cgal#5886]
## Issue Details

When using the polyhedron builder to build a polyhedron and redundant vertices are provided during the first phase, iterating over the vertices range causes a segmentation fault. 
One may argue that redundant vertices should not be provided. I claim that it should not cause a segmentation fault. As a matter of fact, it would be useful to add a function that removed redundant vertices.
In the code below a tetrahedron is built, but 8 vertices are added. This is actually a convenient way to create a perfect regular tetrahedron.

## Source Code

```
#include <CGAL/Simple_cartesian.h>
#include <CGAL/Polyhedron_incremental_builder_3.h>
#include <CGAL/Polyhedron_3.h>
// #include <CGAL/draw_polyhedron.h>
template <class HDS>
class Build : public CGAL::Modifier_base<HDS> {
public:
  Build() {}
  void operator()(HDS& hds) {
    CGAL::Polyhedron_incremental_builder_3<HDS> B(hds, true);
    B.begin_surface(8, 4, 6);
    typedef typename HDS::Vertex   Vertex;
    typedef typename Vertex::Point Point;
    B.add_vertex(Point(-1 ,-1, -1));
    B.add_vertex(Point(-1, -1,  1));
    B.add_vertex(Point(-1,  1, -1));
    B.add_vertex(Point(-1,  1,  1));
    B.add_vertex(Point( 1, -1, -1));
    B.add_vertex(Point( 1, -1,  1));
    B.add_vertex(Point( 1,  1, -1));
    B.add_vertex(Point( 1,  1,  1));
    B.begin_facet();
    B.add_vertex_to_facet(4);
    B.add_vertex_to_facet(1);
    B.add_vertex_to_facet(2);
    B.end_facet();
    B.begin_facet();
    B.add_vertex_to_facet(1);
    B.add_vertex_to_facet(4);
    B.add_vertex_to_facet(7);
    B.end_facet();
    B.begin_facet();
    B.add_vertex_to_facet(7);
    B.add_vertex_to_facet(2);
    B.add_vertex_to_facet(1);
    B.end_facet();
    B.begin_facet();
    B.add_vertex_to_facet(2);
    B.add_vertex_to_facet(7);
    B.add_vertex_to_facet(4);
    B.end_facet();
    B.end_surface();
  }
};
typedef CGAL::Simple_cartesian<double>     Kernel;
typedef CGAL::Polyhedron_3<Kernel>         Polyhedron;
typedef Polyhedron::HalfedgeDS             HalfedgeDS;
int main() {
  Polyhedron P;
  Build<HalfedgeDS> polyhedron;
  P.delegate(polyhedron);
  // CGAL::draw(P);
  std::cout << P.size_of_vertices() << std::endl;
  auto range = P.vertex_handles();
  for (auto hv : range) std::cout << hv->degree() << std::endl;
  return 0;
}

```

## Environment

* Operating system: Ubuntu 20.04
* Compiler: g++ 9.3.0
* Release or debug mode: either
* Specific flags used (if any): none
* CGAL version: latest
* Boost version: 1.73
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by sloriot** [comment]
It has nothing to do with iteration over isolated vertices but with the usage of the member function `degree()` of Polyhedron that is not handling isolated vertices. If you use the BGL function `degree(hv, P)`, it works correctly. I'll fix the Polyhedron function.

**Comment by sloriot** [comment]
Actually, it is not a bug. This function is not documented. The documented one is `vertex_degree()` which is working correctly on your input.

**Comment by efifogel** [comment]
No, it also fails with vertex_degree().
Sometimes it fails with point() as well.
When it fails, it fails on the redundant vertex. (So it makes little sense that degree() is the cause.)

**Comment by sloriot** [comment]
I don't reproduce the issue then.

**Comment by efifogel** [comment]
Now that you mention it, I think that it didn't happen before I upgraded to Ubuntu 20.04, which came with a recent g++ compiler.

**Comment by sloriot** [comment]
I have `g++ (Debian 10.2.1-6) 10.2.1 20210110`

**Comment by efifogel** [comment]
I looked at the code. It's a simple bug:

```
    std::size_t vertex_degree() const {
        return this->halfedge()->vertex_degree();
    }
```
The halfedge is empty. 
Should be something like:
```
    std::size_t vertex_degree() const {
        return (this->halfedge() == Halfedge_handle()) ? 0 : this->halfedge()->vertex_degree();
    }
```

**Comment by sloriot** [comment]
I agree, that how the BGL degree function is implemented.
