### ISSUE TITLE
Bug in user manuel for Color 

### ISSUE THREAD

**Issue by gdamiand** [CGAL/cgal#5887]
## Issue Details

https://cgal.geometryfactory.com/CGAL/doc/master/Stream_support/#title9

"There are a 11 predefined Color constants available: BLACK, WHITE, GRAY, RED, GREEN, DEEPBLUE, BLUE, PURPLE, VIOLET, ORANGE, and YELLOW."

but it seems these constants were removed.

**Comment by lrineau** [comment]
Indeed. The change was e3e0efb4f8bf22f2e6f65f680025a2104316df5a, from PR #3636. The change to the color API was sneaked into an unrelated PR.

**Comment by afabri** [comment]
Well, it is not really fixed.  It is a breaking change if I have to replace  `RED` with ``red()`

**Comment by sloriot** [comment]
The breaking change is in 5.0 so I don't see the need to do more than what I did.
