### ISSUE TITLE
MOC generation fails: ImageInterface.ui not found

### ISSUE THREAD

**Issue by copyme** [CGAL/cgal#5899]
## Issue Details

 I get the following error during MOC object generation.

```Scanning dependencies of target QEM-Tester_autogen
[  5%] Automatic MOC and UIC for target QEM-Tester
[  5%] Built target QEM-Tester_autogen
Scanning dependencies of target CGAL_Qt5_moc_and_resources_autogen
[ 11%] Automatic MOC and UIC for target CGAL_Qt5_moc_and_resources

AutoUic error

-------------
"/usr/local/include/CGAL/Qt/image_interface.h"
includes the uic file "ui_ImageInterface.h",
but the user interface file "ImageInterface.ui"
could not be found in the following directories
  "/usr/local/include/CGAL/Qt"

make[2]: *** [CMakeFiles/CGAL_Qt5_moc_and_resources_autogen.dir/build.make:77: CMakeFiles/CGAL_Qt5_moc_and_resources_autogen] Error 1
make[1]: *** [CMakeFiles/Makefile2:180: CMakeFiles/CGAL_Qt5_moc_and_resources_autogen.dir/all] Error 2
make: *** [Makefile:103: all] Error 2
```

## Source Code
[example-bug-cgal.zip](https://github.com/CGAL/cgal/files/6969019/example-bug-cgal.zip)

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Fedora 33
* Compiler: gcc (GCC) 10.3.1 20210422 (Red Hat 10.3.1-1)
* Release or debug mode: any
* Specific flags used (if any): 
* CGAL version: current master 
* Boost version: 1.73
* Other libraries versions if used (Eigen, TBB, etc.): Qt 5.15.2

**Comment by sloriot** [comment]
Works without `set(CMAKE_AUTOUIC ON)` in `CMakeLists.txt`

**Comment by sloriot** [comment]
No idea

**Comment by djangoliv** [comment]
@maxGimeno @sloriot 

Before CGAL 5, the file ImageInterface.ui was in "<CGAL_DIR>/include/CGAL/Qt/". Now this file is located in "<CGAL_DIR>/include/CGAL/Qt/resources/". Why this change ?

If we put the file back in its original folder everything works very well.

The commit:
https://github.com/CGAL/cgal/commit/37c52e6bbcc5a42f9fda9b1a2720472a4a060e6f#diff-6d46f253b14afe1a92f45779feae6ef637f9145420300860bf6fe98c78173611

Regards
