### ISSUE TITLE
TBB and the OneAPI

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#5911]
## Issue Details

Do we have to make fixes due to API changes, for example in the Spatial Searching package. In its [testsuite](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.4-Ic-30/Spatial_searching_Examples/TestReport_Sosno_MSVC-2022-Preview-Release.gz)

```
(C:\dev\OneAPI\tbb\2021.3.0\include\tbb\../oneapi/tbb/concurrent_hash_map.h(1610,86): error C2955: 'tbb::detail::d2::concurrent_hash_map': use of class template requires template argument list 
```

@lrineau I assigned you as if I remember right you had to adapt the nurbs meshing code concerning TBB.

**Comment by lrineau** [comment]
I had to provide explicitly a third template argument (`HashCompare`) to `tbb::concurrent_hash_map`. See my patch, for example: https://github.com/CGAL/cgal/pull/5850/files#diff-0af1458d8254c21cb674344db2e63895a39b92fba0b934f545fc1bbcf561c14b

Be careful: `HashCompare` is a strange "hash" functor: it must at the same time provide a `hash` and a `equal` member functions (or static member functions). See the TBB developers guide: [`concurrent_hash_map`](https://software.intel.com/content/www/us/en/develop/documentation/tbb-documentation/top/intel-threading-building-blocks-developer-guide/containers/concurrenthashmap.html).

**Comment by lrineau** [comment]
There might be other ways to do. I found out that solution is compatible with both TBB 2019/2020 and oneAPI-TBB 2021.

**Comment by MaelRL** [comment]
Seems fixed from https://cgal.geometryfactory.com/CGAL/testsuite/results-5.4-Ic-68.shtml.
