### ISSUE TITLE
CGAL::oriented_bounding_box calculation sometimes leads to different results for the same set of inputs

### ISSUE THREAD

**Issue by abibas** [CGAL/cgal#5912]
## Issue Details

CGAL::oriented_bounding_box calculation sometimes leads to different results for the same set of inputs.
Bounding box is not always optimal.
And more critical different output for the same input data.

Is there any wat to restrict outputs to be the same for the same inputs?

## Source Code
```
#include <iostream>

#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/optimal_bounding_box.h>
#include <CGAL/Polygon_mesh_processing/IO/polygon_mesh_io.h>
#include <CGAL/Surface_mesh.h>

int main(int argc, char *argv[])
{
    for(auto x = 0; x < 10; ++x){
        Surface_mesh sm;
        if(!CGAL::Polygon_mesh_processing::IO::read_polygon_mesh("../../resources/tests/ruf__rt_12_spoiler.stl", sm) || sm.is_empty())
        {
          std::cerr << "Invalid input file." << std::endl;
          return EXIT_FAILURE;
        }

        std::array<Point, 8> obb_points;
        CGAL::oriented_bounding_box(sm, obb_points);

        /*Considering the fact that
        * - 0 - obb_points[0]
        * - X - obb_points[1]
        * - Y - obb_points[3]
        * - Z - obb_points[5]
        */

        std::array<std::pair<Point, float>, 3> xyz{std::make_pair(obb_points[1], CGAL::squared_distance(obb_points[0], obb_points[1])),
                                                   std::make_pair(obb_points[3], CGAL::squared_distance(obb_points[0], obb_points[3])),
                                                   std::make_pair(obb_points[5], CGAL::squared_distance(obb_points[0], obb_points[5]))};

        for(auto point: obb_points){
            std::cout << point << " ";
        }
        std::cout << std::endl;

        for(auto dot: xyz){
            std::cout << "Squared Distance - " << dot.second << std::endl;
            std::cout << dot.first << "  " << std::endl;
        }
        std::cout << "###############################" << std::endl;
    }

    return 0;
}
```
Outputs:
125.032 611.568 273.632 -214.043 611.568 273.632 -214.043 514.963 327.369 125.032 514.963 327.369 125.032 570.224 426.715 125.032 666.83 372.978 -214.043 666.83 372.978 -214.043 570.224 426.715 
Squared Distance - 114972
-214.043 611.568 273.632  
Squared Distance - 12220.4
125.032 514.963 327.369  
Squared Distance - 12923.5
125.032 666.83 372.978  
###############################
125.032 613.311 275.108 -214.043 613.311 275.108 -214.043 509.158 292.949 125.032 509.158 292.949 125.032 529.194 409.914 125.032 633.347 392.073 -214.043 633.347 392.073 -214.043 529.194 409.914 
Squared Distance - 114972
-214.043 613.311 275.108  
Squared Distance - 11166.2
125.032 509.158 292.949  
Squared Distance - 14082.2
125.032 633.347 392.073  
**###############################**
**125.032 611.568 273.632 -214.043 611.568 273.632 -214.043 514.963 327.369 125.032 514.963 327.369 125.032 570.224 426.715 125.032 666.83 372.978 -214.043 666.83 372.978 -214.043 570.224 426.715** 
**Squared Distance - 114972
-214.043 611.568 273.632  
Squared Distance - 12220.4
125.032 514.963 327.369  
Squared Distance - 12923.5
125.032 666.83 372.978**  
###############################
125.032 613.311 275.108 -214.043 613.311 275.108 -214.043 509.158 292.949 125.032 509.158 292.949 125.032 529.194 409.914 125.032 633.347 392.073 -214.043 633.347 392.073 -214.043 529.194 409.914 
Squared Distance - 114972
-214.043 613.311 275.108  
Squared Distance - 11166.2
125.032 509.158 292.949  
Squared Distance - 14082.2
125.032 633.347 392.073  
###############################
125.032 613.311 275.108 -214.043 613.311 275.108 -214.043 509.158 292.949 125.032 509.158 292.949 125.032 529.194 409.914 125.032 633.347 392.073 -214.043 633.347 392.073 -214.043 529.194 409.914 
Squared Distance - 114972
-214.043 613.311 275.108  
Squared Distance - 11166.2
125.032 509.158 292.949  
Squared Distance - 14082.2
125.032 633.347 392.073  
###############################
125.032 613.311 275.108 -214.043 613.311 275.108 -214.043 509.158 292.949 125.032 509.158 292.949 125.032 529.194 409.914 125.032 633.347 392.073 -214.043 633.347 392.073 -214.043 529.194 409.914 
Squared Distance - 114972
-214.043 613.311 275.108  
Squared Distance - 11166.2
125.032 509.158 292.949  
Squared Distance - 14082.2
125.032 633.347 392.073  
###############################
125.032 613.311 275.108 -214.043 613.311 275.108 -214.043 509.158 292.949 125.032 509.158 292.949 125.032 529.194 409.914 125.032 633.347 392.073 -214.043 633.347 392.073 -214.043 529.194 409.914 
Squared Distance - 114972
-214.043 613.311 275.108  
Squared Distance - 11166.2
125.032 509.158 292.949  
Squared Distance - 14082.2
125.032 633.347 392.073  
###############################
125.032 613.311 275.108 -214.043 613.311 275.108 -214.043 509.158 292.949 125.032 509.158 292.949 125.032 529.194 409.914 125.032 633.347 392.073 -214.043 633.347 392.073 -214.043 529.194 409.914 
Squared Distance - 114972
-214.043 613.311 275.108  
Squared Distance - 11166.2
125.032 509.158 292.949  
Squared Distance - 14082.2
125.032 633.347 392.073  
###############################
125.032 666.83 372.978 -214.043 666.83 372.978 -214.043 611.568 273.632 125.032 611.568 273.632 125.032 514.963 327.369 125.032 570.224 426.715 -214.043 570.224 426.715 -214.043 514.963 327.369 
Squared Distance - 114972
-214.043 666.83 372.978  
Squared Distance - 12923.5
125.032 611.568 273.632  
Squared Distance - 12220.4
125.032 570.224 426.715  
###############################
125.032 613.311 275.108 -214.043 613.311 275.108 -214.043 509.158 292.949 125.032 509.158 292.949 125.032 529.194 409.914 125.032 633.347 392.073 -214.043 633.347 392.073 -214.043 529.194 409.914 
Squared Distance - 114972
-214.043 613.311 275.108  
Squared Distance - 11166.2
125.032 509.158 292.949  
Squared Distance - 14082.2
125.032 633.347 392.073  
###############################

Squared volumes for 2 different OBB:
// 114972 * 11166,2 * 14082,2 = 18078733238074,08
// 114972 * 12923,5 * 12220,4 = 18157566981496,8

## Environment

* Operating system: Windows 10 64 bits 1809
* Compiler: MSVC2019 64bit
* Release or debug mode: Release mode
* Specific flags used (if any): Same problem appears even if _CGAL::parameters::use_convex_hull(false)_
* CGAL version: CGAL-5.3
* Boost version: boost_1_76_0
* Other libraries versions if used (Eigen, TBB, etc.):  Eigen 3.3.9
* Input for tests: [porsche-ruf20210724-13031-1u9b6tr.zip](https://github.com/CGAL/cgal/files/7001327/porsche-ruf20210724-13031-1u9b6tr.zip)

**Comment by abibas** [comment]
[porsche-ruf20210724-13031-1u9b6tr.zip](https://github.com/CGAL/cgal/files/7001298/porsche-ruf20210724-13031-1u9b6tr.zip

GitHub attachments doesn't support .stl attachments. That's why full zip with 3 models attached.

**Comment by MaelRL** [comment]
> CGAL::oriented_bounding_box calculation sometimes leads to different results for the same set of inputs.

The computation of the oriented bounding box is based on a random-mutation algorithm, so that is normal. See also https://doc.cgal.org/latest/Optimal_bounding_box/index.html#title1.

> Bounding box is not always optimal.

That's expected, it is an iteration-based optimization algorithm. Each iteration improves the potential boxes and re-adds brand new candidates to expand the possibilities. Hence, with enough iterations it will find the optimal box with as much precision as you want. However, in the current code, the number of iterations (as well as other important parameters) are hardcoded based on some empirical balance between runtime and quality of the result.

> And more critical different output for the same input data.
> Is there any wat to restrict outputs to be the same for the same inputs?

You can specify the random seed that governs the generator as such:
```
CGAL::oriented_bounding_box(sm, obb_points, CGAL::parameters::random_seed(*SEED_ID*));
```
which will make the program deterministic.
