### ISSUE TITLE
problem compiling - BOOST_PARAMETER_MAX_ARITY 

### ISSUE THREAD

**Issue by afhuertass** [CGAL/cgal#593]
Hi !

i just installed the cgal from sources and trying to compile a programm but i get this strange error an i have no idea what is it. 

 from /home/andresh/tesis/experimentos/code-lbp/src/main.cpp:8:
/usr/local/include/CGAL/Mesh_3/global_parameters.h:33:6: error: #error "BOOST_PARAMETER_MAX_ARITY must be at least 12 for CGAL::Mesh_3"
 #    error "BOOST_PARAMETER_MAX_ARITY must be at least 12 for CGAL::Mesh_3"

i installed boost version 1.60 ( the last one find in the boost.org )  and when i compiled the cgal everthing seem to work well , but trying to include Mesh_criteria_3 give me this error. 

Any help? thanks  ( by the way i dont know if this is the place to post this question but i'm kind of desperate  :(  )

**Comment by sloriot** [comment]
Could you share the program you are trying to compile?

**Comment by afhuertass** [comment]
The programm is quite large... i have it in a old disk and it used to compile well. but the problem seems to be include in the file CGAL/Mesh_criteria_3 

but i have no clue what is happening.... y try to recompile everything ( cgal, boost ) but still is not working.  the compiler points to an error in the main.cpp , in the line where the include is ( <CGAL/Mesh_criteria_3.h> )   any hint?

**Comment by lrineau** [comment]
Add:
```C++
#define BOOST_PARAMETER_MAX_ARITY 12
```
at the *beginning* of the .cpp file that uses CGAL/Mesh_3. That should fix the compilation issue.

**Comment by afhuertass** [comment]
That did the trick !

thanks! :D
