### ISSUE TITLE
CMake minimal version since CGAL 5.3

### ISSUE THREAD

**Issue by VincentRouvreau** [CGAL/cgal#5956]
## Issue Details

[Installation manual](https://doc.cgal.org/latest/Manual/thirdparty.html) and [CGAL 5.3 release note](https://github.com/CGAL/cgal/releases/tag/v5.3) mention that cmake minimal version is 3.14, whereas `Installation/CMakeLists.txt` says `cmake_minimum_required(VERSION 3.12...3.20)`.

This leads to the following error with cmake 3.10:

```
CMake Error at CMakeLists.txt:7 (cmake_minimum_required):
  CMake 3.12...3.20 or higher is required.  You are running version 3.10.2
```

It is a bit confusing that cmake minimal version is not 3.14 here.

## Source Code

N/A
just cmake.

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Ubuntu 18.04
* Compiler: g++ 7.5.0
* Release or debug mode: N/A
* Specific flags used (if any): 
* CGAL version: 5.3
* Boost version: N/A
* Other libraries versions if used (Eigen, TBB, etc.): N/A

**Comment by lrineau** [comment]
CMake 3.14 is the minimal version of CMake CGAL-5.3 was tested with. But, technically, we think it could also work well with CMake-3.12 and CMake-3.13. That is why:
  - we document in the manual what we are sure of,
  - we hardcode in the CMake scripts what we technically require.

Does that answer your question? ... and is the answer acceptable?

**Comment by VincentRouvreau** [comment]
Thanks for your quick answer ! I was just wondering to know if it was not any documentation error.

But, yes, the answer is acceptable. I close the issue
