### ISSUE TITLE
Removed anchors in cgal doc

### ISSUE THREAD

**Issue by gdamiand** [CGAL/cgal#5957]
_Please use the following template to help us solving your issue._

## Issue Details

In previous cgal documentation, anchors like https://www.cgal.org/Pkg/Polyhedron exist (for each package).

I used these links since they are short. In CGAL 5.3, these anchors no more exist.
Is it possible to resurrect them? (many links in papers and websites become invalid otherwise)

**Comment by afabri** [comment]
But are this not redirects on the http server?

**Comment by afabri** [comment]
I fully agree that they are more than helpful

**Comment by gdamiand** [comment]
http://www.cgal.org/Pkg/Polyhedron redirects to https://doc.cgal.org/latest/Manual/packages.html#PkgPolyhedronSummary which does not exist => we arrive to the top of the cgal doc.

**Comment by lrineau** [comment]
The anchor `PkgPolyhedronSummary` has disappeared and now it is named `PkgPolyhedron`. I wonder how that file `packages.html` is generated. It is probably from `Documentation/doc/Documentation/packages.txt`, but I cannot see where is defined the macro `\package_listing`.

**Comment by lrineau** [comment]
That bug appeared at CGAL-4.14:
  - https://doc.cgal.org/4.13.2/Manual/packages.html#PkgPolyhedronSummary works, but
  - https://doc.cgal.org/4.14.3/Manual/packages.html#PkgPolyhedronSummary does not.

**Comment by gdamiand** [comment]
Maybe it is enough to modify the redirect so that http://www.cgal.org/Pkg/Polyhedron redirects to https://doc.cgal.org/latest/Manual/packages.html#PkgPolyhedron ?

**Comment by gdamiand** [comment]
Thanks @lrineau  !!
