### ISSUE TITLE
Vector_3 Cannot be transformed

### ISSUE THREAD

**Issue by petrasvestartas** [CGAL/cgal#5965]
## Issue Details

Vector_3 does cannot be transformed. Why?
And are there any casting methods from point to vector?

## Source Code

```

using CGAL_Kernel = CGAL::Exact_predicates_inexact_constructions_kernel;
using CGAL_Point = CGAL_Kernel::Point_3;
using CGAL_Vector = CGAL_Kernel::Vector_3;
using CGAL_Transformation = CGAL::Aff_transformation_3<CGAL_Kernel>;

CGAL_Transformation T0(CGAL::TRANSLATION, CGAL_Vector(0, 0, 100));
CGAL_Vector p(0,0,1);
p=p.transform(T0);

//Only point works:
CGAL_Transformation T0(CGAL::TRANSLATION, CGAL_Vector(0, 0, 100));
CGAL_Point p(0,0,1);
p=p.transform(T0);
```

## Environment

Last CGAL version on Windows.

**Comment by lrineau** [comment]
You can write the code using `Aff_transformation_3::transform`:
```c++
CGAL_Transformation T0(CGAL::TRANSLATION, CGAL_Vector(0, 0, 100));
CGAL_Vector v(0,0,1);
v=T0.transform(v);
```

**Comment by petrasvestartas** [comment]
Deae @lrineau ,

What do you mean by this:
Aff_transformation_3::transform

**Comment by lrineau** [comment]
Instead of calling `p=p.transform(T0);`, call `p=T0.transform(p);`. That will work for both points and vectors.

**Comment by petrasvestartas** [comment]
Will vectors be unitized/normalized after this transformation?
Or I have to do it myself? I have hard time finding any normalization method in documentation.

**Comment by lrineau** [comment]
Well, that depends on the characteristics of the transformation: if it is an isometry (rotation, reflection, that preserves lengths and distance), then any normalized vector will be transformed into a normalized vector (but the precision errors during the computation can slightly transform the length of the vector). If the transformation is not an isometry, then no.

You can easily normalize a vector. Given `v` a vector, then `v*v` is the squared length of it, so you can write a function template like that one:
```c++
template <typename Vector>
Vector normalize(Vector v) {
  auto length = CGAL::sqrt(v*v);
  if(length != 0) { // a null vector cannot be normalized
    v = v / length;
  }
  return v;
};
```

**Comment by petrasvestartas** [comment]
Thank you
