### ISSUE TITLE
Suggestions for Point_set_processing_3/remove_outliers_example.cpp

### ISSUE THREAD

**Issue by copyme** [CGAL/cgal#5977]
In the example there is `std::vector<Point>(points).swap(points);` but would not be better to use `std::vector<T,Allocator>::shrink_to_fit`?

Also, why the example is not saving the final set? From a user point of view it would make a lot of sense to check what we will get with the default example's set of parameters.

**Comment by lrineau** [comment]
That question is discussed in StackOverflow, here: https://stackoverflow.com/q/43667175/1728537

The issue with `shrink_to_fit` is that it is not guaranteed to do anything. A compiler implementation can choose not to implement it.

**Comment by copyme** [comment]
@lrineau Thanks for the link!

**Comment by afabri** [comment]
Hi Kacper,  
as you observed some examples write the result to a files others don't.  The examples are more to illustrate the API than utility functions to really DO point set processing.  For utilities we would have to add program options, and if it was only for that the users can choose the output format.   If we did that the example would first have many lines for parsing,  and it would be hard for the reader of the User Manual  to  just see  the main function.   
It might make sense to have command line utilities.
