### ISSUE TITLE
Line Plane Intersection, How to know when resulted point is on a line?

### ISSUE THREAD

**Issue by petrasvestartas** [CGAL/cgal#5980]
## Issue Details

How to know if intersection between plane and line is result of a point on a line, not on infinite line?

## Source Code
```
               

            CGAL_Line line(polyline[i], polyline[i + 1]);            
            auto result = CGAL::intersection(line, plane);
            CGAL_Point pt = *boost::get<CGAL_Point>(&*result);
```

![image](https://user-images.githubusercontent.com/18013985/132893795-a1c0d802-0bc1-49cf-90b9-9c34d0922af5.png)

## Environment

Windows, Latest CGAL

**Comment by MaelRL** [comment]
Is https://doc.cgal.org/latest/Kernel_23/Kernel_23_2intersection_get_8cpp-example.html what you mean?

**Comment by petrasvestartas** [comment]
I tried to check the result, but it still output a point on infinite line.
In my case, it is not segment but a line and and a plane:

            auto result = CGAL::intersection(line, plane);
            if (result) {
                CGAL_Point pt = *boost::get<CGAL_Point>(&*result);
                CGAL_Debug(pt, true);
            }

**Comment by MaelRL** [comment]
`if (result)` checks if there is an actual intersection; otherwise the objects do not intersect.

Then you try to cast the result into the different types:
```
  if (result) {
    if (const Line_3* l = boost::get<Line_3>(&*result)) {
      std::cout << *l << std::endl;
    } else {
      const Point_3* p = boost::get<Point_3>(&*result);
      std::cout << *p << std::endl;
    }
  }
  else
  {
    std::cout << "no inter" << std::endl;
  }
```

**Comment by petrasvestartas** [comment]
I still get the same result for this situation: 

![image](https://user-images.githubusercontent.com/18013985/132897935-2864cc8b-8395-48dd-a10c-967420f1e825.png)

```
58579.694258, 1737261.188586, -54.875143  
-31.162684, -34.404537, -54.875143        
-31.162683, -34.404500, -54.875143        
216797.104876, 6427013.643330, -54.875143 
-28.740901, 37.380011, -54.875143
```

**Comment by petrasvestartas** [comment]
Dear @MaelRL ,

Do I need to use a different type of intersection such segment and plane instead of line and plane?

**Comment by petrasvestartas** [comment]
Segment_3 and Plane_3 intersection worked
![20210913_090633](https://user-images.githubusercontent.com/18013985/133038855-e6bc07cd-a2a4-4e7d-9759-0c008106ef84.jpg)
