### ISSUE TITLE
Modify Transformation matrix by row and column

### ISSUE THREAD

**Issue by petrasvestartas** [CGAL/cgal#6001]
## Issue Details

How can I modify a transformation matrix by row and column?
There is no operator to modify matrix like this:

```
        CGAL_Transformation m_xform;
        m_xform.cartesian[0][0] = 0;

```
and obviously cartesian only return output but you cannot modify it:
```
        CGAL_Transformation m_xform;
        m_xform.cartesian(0,0) = 0;
```
The `CGAL_Transformation` type is `using CGAL_Transformation = CGAL::Aff_transformation_3<CGAL_Kernel>;`

Probably I am missing something simple but I cannot find a way how to modify matrix values by row and column.

**Comment by mglisse** [comment]
CGAL kernel objects are not usually mutable. Similarly, you cannot just modify one coordinate of a point. What you can do is create a new object with the values you want (and possibly copy it over the old object).

**Comment by petrasvestartas** [comment]
Thanks
