### ISSUE TITLE
Cmake fails for example files

### ISSUE THREAD

**Issue by Sumilsood** [CGAL/cgal#6008]
## Issue Details

1.  I followed the instructions to install CGAL-5.3 into my Windows 10 computer with Visual studio 2019. After installing the CGAL-5.3 I tried to configure the example as given in the documentation but got this error in Cmake. I have made sure to add environment variable "CGAL_DIR" to locate the CGAL directory as 'C:\dev\CGAL-5.3'. I am not sure how to solve this.
"""
Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19043.
CMake Error at CMakeLists.txt:16 (find_package):
  By not providing "FindCGAL.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "CGAL", but
  CMake did not find one.

  Could not find a package configuration file provided by "CGAL" with any of
  the following names:

    CGALConfig.cmake
    cgal-config.cmake

  Add the installation prefix of "CGAL" to CMAKE_PREFIX_PATH or set
  "CGAL_DIR" to a directory containing one of the above files.  If "CGAL"
  provides a separate development package or SDK, be sure it has been
  installed.

Configuring incomplete, errors occurred!
See also "C:/dev/CGAL-5.3/examples/Triangulation_2/build/CMakeFiles/CMakeOutput.log".
"""

2. When I try to run the example (https://github.com/CGAL/cgal/blob/master/Polygon_mesh_processing/examples/Polygon_mesh_processing/corefinement_difference_remeshed.cpp)
It doesn't build and gives this compilation error:
"""
Build started...
1>------ Build started: Project: cgal2, Configuration: Debug Win32 ------
1>cgal2.cpp
1>C:\dev\CGAL-5.3\include\CGAL\Mpzf.h(69,9): warning C4163: '_BitScanForward64': not available as an intrinsic function
1>C:\dev\CGAL-5.3\include\CGAL\Mpzf.h(70,9): warning C4163: '_BitScanReverse64': not available as an intrinsic function
1>C:\dev\CGAL-5.3\include\CGAL\Mpzf.h(202,3): error C3861: '_BitScanForward64': identifier not found
1>C:\dev\CGAL-5.3\include\CGAL\Mpzf.h(214,3): error C3861: '_BitScanReverse64': identifier not found
1>Done building project "cgal2.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
"""

I am not sure how to solve this. Please help me solve these issues. 
Thank you

## Environment

* Operating system (Windows 10- 64 bits):
* Compiler: Visual studio 2019, x86
* Release or debug mode: Win 32
* Specific flags used (if any):
* CGAL version: 5.3
* Boost version:1_71_0
* Other libraries versions if used (Eigen, TBB, etc.): QT5 5.11

**Comment by sloriot** [comment]
Does the path provided in `${CGAL_DIR}` contain the file `CGALConfig.cmake`? If not then the CGAL_DIR is not set correctly.

**Comment by lrineau** [comment]
For 1.,
  - verify that `C:\dev\CGAL-5.3\CGALConfig.cmake` exists
  - add `CGAL_DIR` as a CMake variable:
    - if you use the CMake graphical interface, add a new entry `CGAL_DIR`, or type `PATH`, and set it to `C:\dev\CGAL-5.3`,
    - if you use the CMake command line, add `-DCGAL_DIR=C:\dev\CGAL-5.3` to the command options.

For 2., I am surprised that you can compile at all, because in 1. your said you cannot configure CGAL examples using CMake.
  - What is in that file `cgal2.cpp`?
  - How have your generated the Visual Studio project `cgal2.vcxproj`?
  - The compilation errors show that you are trying to compile a CGAL example in 32 bits on Windows. That is no longer tested, and not supported by the CGAL project. The GMP version you install is for 64 bits.

**Comment by Sumilsood** [comment]
Hi,

Thank you for the help regarding the Cmake the solution to add new entry helped in resolving the error.
Actually I work at Mathworks and right now my team is looking at different Libraries that can help in doing Boolean mesh operations like union, difference, intersection etc. We have a Delaunay Triangulation class in Matlab that creates mesh for data points. We are looking for a library that can take in this data and allow us to do Boolean operations on it. We are looking for a library that is Rubust, fast and can save the material property of the mesh components. 
I know that CGAL can do Boolean operation but I am not sure whether it can preserve the material property of different objects. Can you tell me if that's possible. I know that Polygon mesh processing is one of the component with Boolean operations capability. Is there anything better that I can use for this purpose?
Example of an application will be to have two cubes and we want to compute union of those two.

Secondly, I tried running the examples in Visual studio 2019 but it keeps giving me this error.
'''
The code execution cannot be completed because libgmp-10.dll was not found. Reinstalling the program may fix the issue.
'''
I have made sure to add the folder path to the additional libraries directory of this project. The path I added is "C:\dev\CGAL-5.3\auxiliary\gmp\lib" and I can see that it contains the file libgmp-10.dll.

I am not sure why this error is coming even after I added the path to additional libraries directory in Project properties.

**Comment by sloriot** [comment]
IIUC what you are looking for, this example should do what you want:

https://github.com/CGAL/cgal/blob/master/Polygon_mesh_processing/examples/Polygon_mesh_processing/corefinement_mesh_union_with_attributes.cpp

About the gmp error,  the path to the gmp dll should be in your PATH env variable.

**Comment by lrineau** [comment]
> Secondly, I tried running the examples in Visual studio 2019 but it keeps giving me this error.
> '''
> The code execution cannot be completed because libgmp-10.dll was not found. Reinstalling the program may fix the issue.
> '''
> I have made sure to add the folder path to the additional libraries directory of this project. The path I added is "C:\dev\CGAL-5.3\auxiliary\gmp\lib" and I can see that it contains the file libgmp-10.dll.
> 
> I am not sure why this error is coming even after I added the path to additional libraries directory in Project properties.

In Visual Studio, "Additional Library Directories" is a configuration for the linker: it specifies where the linker should search for `.lib` files if it receive instruction to link with a library without its full path. That corresponds the [`/LIBPATH` linker option](https://docs.microsoft.com/en-us/cpp/build/reference/libpath-additional-libpath?view=msvc-160).

The error `The code execution cannot be completed because libgmp-10.dll was not found. Reinstalling the program may fix the issue.` is a runtime issue. It is triggered when you try to run the program. There are several ways to allow the Windows runtime to find a DLL, and the easiest ones are:
  - copy the DLL in the same directory as the `.exe` file your want to run,
  - or add `C:\dev\CGAL-5.3\auxiliary\gmp\lib` in the `PATH` environment variable.

**Comment by Sumilsood** [comment]
Hi,
Thank you for the help. I am able to run all the example and change them for my data. I see that in this example:
[https://github.com/CGAL/cgal/blob/master/Polygon_mesh_processing/examples/Polygon_mesh_processing/corefinement_mesh_union_with_attributes.cpp]

You are adding a mesh ID to each of the input meshes. What I want to do is when I do a union on these two input meshes. I want the output to have this ID attached to it which tells me that this part of the output is coming from mesh 1 and the other part is coming from mesh 2. Right now the output OFF file that comes just contains the result data and no mesh id is attached to it. I want to know when I perform Union or intersection do the function allow it to preserve the mesh ID and tell which data point is coming from which mesh?

**Comment by Sumilsood** [comment]
I also tried running the example with my data. The code I am using is the example code mentioned here
[https://github.com/CGAL/cgal/blob/master/Polygon_mesh_processing/examples/Polygon_mesh_processing/corefinement_mesh_union_with_attributes.cpp]

and I am just changing the input files to my own data points.
`int main(int argc, char* argv[])
{
  const char* filename1 = (argc > 1) ? argv[1] : "data/cube1.off";
  const char* filename2 = (argc > 2) ? argv[2] : "data/cube2.off";
  Mesh mesh1, mesh2;
  if(!PMP::IO::read_polygon_mesh(filename1, mesh1) || !PMP::IO::read_polygon_mesh(filename2, mesh2))
  {
    std::cerr << "Invalid input." << std::endl;
    return 1;
  }

  Mesh out;
`
and I get this error
"""
1
CGAL error: precondition violation!
Expression : is_triangle_mesh(tm1)
File       : C:\dev\CGAL-5.3\include\CGAL/Polygon_mesh_processing/internal/Corefinement/intersection_impl.h
Line       : 1546
Explanation:
Refer to the bug-reporting instructions at https://www.cgal.org/bug_report.html
"""

The difference between my data and the one in example is that it has 4 face point for the mesh connectivity. Does the CGAL algorithm not take that type of data?
The data files are attached in the ZIP forder:
[Data.zip](https://github.com/CGAL/cgal/files/7228404/Data.zip)

**Comment by sloriot** [comment]
The input is indeed expected to be triangulated. You will have to call the function [`CGAL::Polygon_mesh_processing::triangulate_faces()`](https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__meshing__grp.html#ga1e9c8778755b2d1741f47736ba6e4b45) as a pre-processing step.

However, after looking at your data, it seems that you put a volume mesh (3D meshes) into 3d surface meshes. Here is what I see if I clip `cube1.off` to see the inside:
![Screenshot from 2021-09-27 15-12-26](https://user-images.githubusercontent.com/1224632/134915347-48b6bb95-9e52-4dd7-9984-46d26a32d271.png)

About your previous question, I'm adding ids to input faces and those ids get ported in the output whenever an input face is used in the output (so I could get several colors on both meshes and get the color correctly ported on the output mesh).

**Comment by Sumilsood** [comment]
Hi, Thank you for the help. Tis solves the problem that I was facing. Yes the input that I had was a Volume mesh and I think the the function "corefine_and_compute_union" does not handle volume meshes. Is there a function in CGAL that can handle volume meshes for Boolean operations?

**Comment by sloriot** [comment]
There is no such package in CGAL. Everything we have will operate on the boundary surfaces of the solids. Out of curiosity, do you have tetmeshes, hexmeshes? What is the expected output?

**Comment by Sumilsood** [comment]
The surface mesh operations works for our application right now and I was able to do the Boolean operations on meshes generated in MATLAB. I was asking about volume meshes for a future application but I think that should be ok for now. Thank you for all the help.
