### ISSUE TITLE
Commit #50ae0ae modified WLOP behavior

### ISSUE THREAD

**Issue by cjamin** [CGAL/cgal#6009]
Since commit [#50ae0aeb](https://github.com/CGAL/cgal/commit/50ae0aeba4b9eae5bda72088d9e11ac381a05895#diff-e2458387eeb0ee3c1b322311a8113fc6be6a8e8866f5ae8df0af37629cf1a737), `compute_update_sample_point` is now called with the non-squared radius (`radius`) as parameter, instead of the squared radius (`radius2`) as before.
Is it intended?

Note that the variable names are a bit confusing in the code, since the squared radius is sometimes stored in a variable named `radius`.

**Comment by lrineau** [comment]
Its seems to be intended, because `compute_update_sample_point` squares the `radius` parameter variable.

The code is indeed quite confusing. It comes from a GSoC'13 intern. The documentation was reviewed, but not the code.

**Comment by cjamin** [comment]
Yes, you are right. I was not sure if this was intended because the commit did not mention the bug fix.
Actually, I was mentoring this student with Pierre, but I was quite busy at this time and I admit the code could be better. Sorry!
