### ISSUE TITLE
Unable to compile surface reconstruction demo - Surface Reconstruction from Point Clouds

### ISSUE THREAD

**Issue by pscholle** [CGAL/cgal#6026]
Hey everyone, I am trying to compile the surface reconstruction [demo](https://doc.cgal.org/latest/Manual/tuto_reconstruction.html) in the manual and am getting a few weird errors. 

`lib/CGAL/jet_smooth_point_set.h:202:29: error: static assertion failed: Error: no SVD traits
  202 |   CGAL_static_assertion_msg(!(boost::is_same<SvdTraits,
      |                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~
  203 |                               typename GetSvdTraits<NamedParameters>::NoTraits>::value),
`  

and then further along

`/usr/include/c++/9/bits/std_function.h:667:7: error: ‘std::function<_Res(_ArgTypes ...)>::function(_Functor) [with _Functor = CGAL::jet_smooth_point_set(PointRange&, unsigned int, const NamedParameters&) [with ConcurrencyTag = CGAL::Sequential_tag; PointRange = CGAL::Point_set_3<CGAL::Point_3<CGAL::Epick>, CGAL::Vector_3<CGAL::Epick> >; NamedParameters = CGAL::Named_function_parameters<CGAL::Epick, CGAL::internal_np::geom_traits_t, CGAL::Named_function_parameters<CGAL::Point_set_3<CGAL::Point_3<CGAL::Epick>, CGAL::Vector_3<CGAL::Epick> >::Property_map<CGAL::Vector_3<CGAL::Epick> >, CGAL::internal_np::normal_t, CGAL::Named_function_parameters<CGAL::Point_set_3<CGAL::Point_3<CGAL::Epick>, CGAL::Vector_3<CGAL::Epick> >::Property_map<CGAL::Point_3<CGAL::Epick> >, CGAL::internal_np::point_t, CGAL::internal_np::No_property> > >]::<lambda(const reference&)>; <template-parameter-2-2> = void; <template-parameter-2-3> = void; _Res = bool; _ArgTypes = {boost::tuples::cons<CGAL::Point_set_3<CGAL::Point_3<CGAL::Epick>, CGAL::Vector_3<CGAL::Epick> >::Index&, boost::tuples::cons<CGAL::Point_3<CGAL::Epick>&, boost::tuples::null_type> >}]’, declared using local type ‘CGAL::jet_smooth_point_set(PointRange&, unsigned int, const NamedParameters&) [with ConcurrencyTag = CGAL::Sequential_tag; PointRange = CGAL::Point_set_3<CGAL::Point_3<CGAL::Epick>, CGAL::Vector_3<CGAL::Epick> >; NamedParameters = CGAL::Named_function_parameters<CGAL::Epick, CGAL::internal_np::geom_traits_t, CGAL::Named_function_parameters<CGAL::Point_set_3<CGAL::Point_3<CGAL::Epick>, CGAL::Vector_3<CGAL::Epick> >::Property_map<CGAL::Vector_3<CGAL::Epick> >, CGAL::internal_np::normal_t, CGAL::Named_function_parameters<CGAL::Point_set_3<CGAL::Point_3<CGAL::Epick>, CGAL::Vector_3<CGAL::Epick> >::Property_map<CGAL::Point_3<CGAL::Epick> >, CGAL::internal_np::point_t, CGAL::internal_np::No_property> > >]::<lambda(const reference&)>’, is used but never defined [-fpermissive]
  667 |       function<_Res(_ArgTypes...)>::
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
`

I have included the headers for  CGAL5.3  and boost_1.61 

--lib
  -CGAL
  -boost

I try to compile with the following command. 

`g++ test.cpp -I lib`

Other examples have worked fine. So I am a bit stumped!

## Environment
* Operating system: Linux Ubuntu 20.04
* Compiler: g++ 9.3.0
* CGAL version: 5.3
* Boost version: 1.61

**Comment by sloriot** [comment]
You are missing Eigen. It is done by the cmake machinery but if you do it manually, it should be activated with `-DCGAL_EIGEN3_ENABLED` (and -I eigen include path if not already in the include path).

Note that you are also missing the flag `-frounding-math`.

**Comment by pscholle** [comment]
ahhh jee wiz, many thanks!

So my lib folder structure is as follows:  
--lib
  --CGAL
  --Eigen
  --Boost

with the command `g++ cgal_test.cpp -I lib -frounding-math -lmpfr  -lgmp` it worked.
