### ISSUE TITLE
Polyhedron demo: Scene_polyhedron_item, display of feature edges

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#603]
In the `Scene_polyhedron_item`, the feature edges should be displayed in red.

- Open the `cross.off`, for example,
- then use the action "Detect sharp features".

The feature edges should be displayed in red. With the current `master` the feature edges are displayed in the same color as the other ones (black).

CC @maxGimeno

**Comment by sloriot** [comment]
Fixed by #632
