### ISSUE TITLE
corefine_and_compute_intersection not working in windows (unexpected behavior)

### ISSUE THREAD

**Issue by otrouser** [CGAL/cgal#6032]
## Issue Details
Unexpected behavior: corefine_and_compute_intersection returns no error but gives and empty output mesh when compiled for windows. When compiled for Linux it works without any issues.

## Source Code
```
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/IO/Polyhedron_builder_from_STL.h>
#include <CGAL/Polyhedron_3.h>
#include <CGAL/Polyhedron_items_with_id_3.h>
#include <CGAL/Polygon_mesh_processing/polygon_soup_to_polygon_mesh.h>
#include <CGAL/Polygon_mesh_processing/corefinement.h>

#include <vector>
#include <string>
#include <fstream>
#include <iostream>
#include <sstream>

typedef CGAL::Exact_predicates_inexact_constructions_kernel Kernel;
typedef Kernel::Point_3 Point_3;
typedef CGAL::Polyhedron_3<Kernel, CGAL::Polyhedron_items_with_id_3> PolygonMesh;

struct myShell {
	std::vector<Point_3> points;
	std::vector<std::vector<std::size_t>> polygons;
};

int main(int argc, char *argv[]) {
	myShell cutter, object;

	std::string cuterFile = "cutter.stl";
	char* stlFileCharA = new char[cuterFile.size() + 1];
	strcpy(stlFileCharA, cuterFile.c_str());
	std::ifstream stl_fileA(cuterFile, std::ifstream::in);
	CGAL::read_STL(stl_fileA, cutter.points, cutter.polygons);
	//cuterFile.close();
	
	std::string objectFile = "object.stl";
	char* stlFileCharB = new char[objectFile.size() + 1];
	strcpy(stlFileCharB, objectFile.c_str());
	std::ifstream stl_fileB(objectFile, std::ifstream::in);
	CGAL::read_STL(stl_fileB, object.points, object.polygons);
	//objectFile.close();
	
	PolygonMesh cutter_shell;
	CGAL::Polygon_mesh_processing::polygon_soup_to_polygon_mesh(cutter.points, cutter.polygons, cutter_shell);
	
	PolygonMesh object_shell;
	CGAL::Polygon_mesh_processing::polygon_soup_to_polygon_mesh(object.points, object.polygons, object_shell);
	
	PolygonMesh output;
	if( CGAL::Polygon_mesh_processing::corefine_and_compute_intersection(object_shell, cutter_shell, output) == false)
		std::cout << "\n  WARNING: corefine_and_compute_intersection output may have only been corefined!" << std::endl;
	
	std::ofstream("output.off") << std::setprecision(17) << output;
	
	return EXIT_SUCCESS;
}
```

Note: See attachment for required input files and CMakeList file used to compile.

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows 10 64 bits
* Compiler: gcc 10.3 (MSYS2 MinGW 64-bit)
* Release or debug mode: Release
* Specific flags used (if any): See cmakefile in attached .zip
* CGAL version: 5.2.3
* Boost version: 1.71
* Other libraries versions if used (Eigen, TBB, etc.) Eigen 3.3.9

[corefine_test.zip](https://github.com/CGAL/cgal/files/7287562/corefine_test.zip)

**Comment by sloriot** [comment]
Why aren't you simply doing `std::ifstream stl_fileA("cutter.stl");` and similar for B?

**Comment by otrouser** [comment]
> 
> 
> Why aren't you simply doing `std::ifstream stl_fileA("cutter.stl");` and similar for B?

Oversight on my part, there is no reason. I just missed simplifying that bit when i copied the problematic section form my larger code ...

**Comment by sloriot** [comment]
So replacing that code does not fix the issue on windows?

**Comment by otrouser** [comment]
No, the issue remains.

**Comment by otrouser** [comment]
I do use cmake, you will find the cmakefile I use in atached zip. I also did try to compile in DEBUG mode but get "Fatal error: file too big".

**Comment by otrouser** [comment]
Specifying std::ios::binary has also solved the issue on my side to. Thank you very much! 
Do you know the exact reason why this is required when compiling for Windows use but not when compiling for Linux use?
