### ISSUE TITLE
CGAL::make_icosahedron creates mesh of wrong scale

### ISSUE THREAD

**Issue by dpapavas** [CGAL/cgal#6064]
According to the documentation, the function `CGAL::make_icosahedron`, takes the circumradius of the icosahedron, but as it is now, the argument is used as half the edge length, rather than radius.  To make it the radius, the mesh would have to be scaled by `sqrt(φ + 2)`, but this would make all components of the vertices approximate.  Perhaps simply changing the documentation would be simpler.

**Comment by dpapavas** [comment]
Well, as far as I can see, if you compare the coordinates given for example [here](https://en.wikipedia.org/wiki/Regular_icosahedron#Cartesian_coordinates), for an icosahedron of edge length 2, centered at the origin, with those of [the implementation](https://github.com/CGAL/cgal/blob/a8e87526348d2d1faa2ea893747314853ee6868d/BGL/include/CGAL/boost/graph/generators.h#L657-L670), you'll see that they match, for `radius` equal to 1 and `center` equal to the origin.

So "radius" is in fact equal to half the edge length (seen another way, consecutive pairs of vertices are evidently placed `2 * radius` apart).  Furthermore, since, as the article mentions, the circumradius of the existing icosahedron is, in fact, `sqrt(φ + 2)`, we can get a unit radius icosahedron by scaling the existing coordinates by `1 / sqrt(φ + 2)`.  The only downside I can see, if that is a downside, is that then none of the coordinates would be integral and exact.  I'm not sure if that is of importance.

**Comment by afabri** [comment]
I agree that we better change the documentation.   I was wondering if we want to change the hard-coded `(1.0 + CGAL::approximate_sqrt(5.0)) / 2.0`.   After  all with `Exact_predicates_exact_construction_kernel_with_sqrt` we could deal with `sqrt(5)`  in a symbolic way. But as this is anyways only an approximation of the golden ratio we can as well approximate it just with `double`.

**Comment by lrineau** [comment]
Fixed by https://github.com/CGAL/cgal/pull/6373
