### ISSUE TITLE
Line Line Intersection

### ISSUE THREAD

**Issue by petrasvestartas** [CGAL/cgal#6089]
Line line intersection does no produce a valid result

## Issue Details

I assume that within a very small tolerance lines are not completely on the same plane (0.00001 tolerance).
But I would like still to compute an approximate intersection between infinite lines.
How can I do it, because the following code does not produce a result.
I tried to switch to inexact kernel, but it is the same problem sometimes you get a result sometimes not.

## Source Code

 ```
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/Exact_predicates_exact_constructions_kernel.h>
#include <CGAL/Intersections.h>

using IK = CGAL::Exact_predicates_inexact_constructions_kernel;
using EK = CGAL::Exact_predicates_exact_constructions_kernel;
typedef CGAL::Cartesian_converter<IK, EK> IK_to_EK;
typedef CGAL::Cartesian_converter<EK, IK> EK_to_IK;

void test(){
     IK::Line_3 l0_(IK::Point_3(-1242.9339929999999, -680.04568599999982, 711.26441699999987), IK::Point_3(-1740.1076069999997, -680.04568599999982, 711.26441699999987));
     IK::Line_3 l1_(IK::Point_3(-1242.933992, -680.04568600000005, 711.26441699999998), IK::Point_3(-1242.933992, -196.286, 535.190291));
                  
      
     IK_to_EK ie; EK_to_IK ei;
     auto result0 = CGAL::intersection(ie(l0_), ie(l1_));

     if (result0) {
         auto p0 = ei(*boost::get<EK::Point_3>(&*result0));
         printf("Good\n");
     }   else {
         printf("Bad\n"); //prints bad result
     }

}
```

Here is how those two lines look like:
![image](https://user-images.githubusercontent.com/18013985/139361165-2bfc9f4c-2a21-4bf1-a1cc-60fbf0b7520c.png)

**Comment by petrasvestartas** [comment]
@lrineau Thank you for a suggestion, I was wondering if there some sort partial intersection method, that finds closest distance between two lines and output point on these lines. Are there anything similar in CGAL?

@sloriot  I went this route as you suggest. For now my code works nice. And I can insert timber joints in a shell.
But after reading your post, you mention special cases. What are those cases where this would fail?

![image](https://user-images.githubusercontent.com/18013985/139481996-8e118798-4be8-4d85-99c2-e9e78b08b723.png)

**Comment by sloriot** [comment]
Here is the code for polyline intersection I mentioned during the zoom meeting:
https://gist.github.com/sloriot/0943fec878401e04930b7bcbd73baf91

It is using `do_intersect()` but you can replace it with distance computation if needed. You will also need to increase the bbox.

**Comment by petrasvestartas** [comment]
Thank you very much:)
You are really kind people !

**Comment by petrasvestartas** [comment]
Dear @sloriot,

Where is the Orientation type defined in which header or namespace?
Line 178 https://github.com/CGAL/cgal/pull/2883/files#diff-f91fc85e05962dc2dc6eaf3f58703ef3948b4adf361b6ba259de6ffbedd7e3d6R372
![image](https://user-images.githubusercontent.com/18013985/148986034-ae59d00e-4aba-464a-99a6-d071bc289d8c.png)

**Comment by sloriot** [comment]
The free function is in the CGAL:: namespace. If you want to use the kernel, you need to construct the orientation object and then use it.

**Comment by petrasvestartas** [comment]
Do you mean like this:

```
                EK::Orientation_2 source_sc = orientation(sc.source(), sc.target(), seg2.source());
                EK::Orientation_2 source_scc = orientation(scc.source(), scc.target(), seg2.source());
                EK::Orientation_2 target_sc = orientation(sc.source(), sc.target(), seg2.target());
                EK::Orientation_2 target_scc = orientation(scc.source(), scc.target(), seg2.target());
```

**Comment by afabri** [comment]
The type `CGAL::Orientation` is documented [here](https://doc.cgal.org/latest/Kernel_23/classKernel.html#ac3987564bd4891820ba667615d59090b)

**Comment by petrasvestartas** [comment]
@sloriot and @afabri  thank you for confirmation.

**Comment by petrasvestartas** [comment]
Works nicely, does the tolerance has something to do with the distance between the segments, or it means something else?


![image](https://user-images.githubusercontent.com/18013985/148998432-191c3855-490c-4e71-b7a6-1f64a241c4e8.png)

**Comment by sloriot** [comment]
If you are using something like the following, then yes.
```
        if (CGAL::squared_distance (s1, s2) > tolerance * tolerance)
           return;
```

**Comment by petrasvestartas** [comment]
I would like to ask if there is a better way to do the search between groups of boxes than described below.
I have a data-set like image below, where two dark black lines are closest to each other. You can see that during the search the are more collisions between other segments as well.

To solve this issue I use a` std::map` within the callback in  `CGAL::box_self_intersection_d(boxes.begin(), boxes.end(), callback);`
In the callback I add collisions to the map or replace the previous ones if the distance is lower. To get a unique id from two polylines indexes I construct a long number that is the key. Is there a better way to do this than the code below?

```
         /////////////////////////////////////////////////////////////////////
        //do_interesect call_back
        /////////////////////////////////////////////////////////////////////
        double max_distance = 10;
        std::map<uint64_t, std::tuple<double, int, int, int, int>> pair_collisions;

        auto callback = [&segment, &max_distance, &pair_collisions](const Box& b1, const Box& b2) {


            if (b1.info().first != b2.info().first) {

                double distance = CGAL::squared_distance(segment(b1.info().first, b1.info().second), segment(b2.info().first, b2.info().second));
                if (distance < max_distance * max_distance) {

                    size_t first_0, first_1;
                    bool flipped = false;
                    uint64_t id = cgal_math_util::unique_from_two_size_t(b1.info().first, b2.info().first, flipped);

                    auto dist_and_segment_ids = flipped ?  std::make_tuple(distance, b1.info().first, b1.info().second, b2.info().first, b2.info().second) : std::make_tuple(distance, b2.info().first, b2.info().second, b1.info().first, b1.info().second);

                    //Add elements to std::map
                    if (pair_collisions.find(id) == pair_collisions.end()) {
                        //not found
                        pair_collisions.insert(  std::make_pair (id, dist_and_segment_ids)   );

                    } else if( distance < std::get<0>(pair_collisions[id]) ) {
                        // found and distance is smaller that before found
                        pair_collisions[id] = dist_and_segment_ids;
                    }
                    
                }//check if lines closer than the given distance

            }//check if boxes do not belong to the same group b.info().first

        };

        /////////////////////////////////////////////////////////////////////
        //self intersection
        /////////////////////////////////////////////////////////////////////
        CGAL::box_self_intersection_d(boxes.begin(), boxes.end(), callback);
```

![image](https://user-images.githubusercontent.com/18013985/149138717-2d508421-2dcc-4e5a-b08c-49f14c4a6025.png)

**Comment by afabri** [comment]
There will be collisions between neighbors on the polyline.

**Comment by petrasvestartas** [comment]
Yes, these collisions exists and ignored after this check:
`if (b1.info().first != b2.info().first) `

then the are multiple collisions between I try to use the std::map in the code above.
Is this a correct way of doing this by using the std::map?

![image](https://user-images.githubusercontent.com/18013985/149142390-72c70710-639c-45a5-9ba6-dc566a931eba.png)

**Comment by petrasvestartas** [comment]
It is a bit trickier than I thought. There are 2 problems:
1) Polylines whose corners are close to each other by ends, not middle parts, sometimes are not detected. I tried to extend the segment lengths but then the points are not on the polyline anymore as image below.
2) The second problem is that the Line to Line snapping method becomes slow:
 2.1) Just box search takes in this example 2 ms, 2.2) While the snapping / relative intersection methods adds up 170 ms.

Would it changing anything if I use inexact kernel?

![image](https://user-images.githubusercontent.com/18013985/149186577-5ce4fd13-fb4e-493f-a1be-1077890b210b.png)

**Comment by petrasvestartas** [comment]
Dear @sloriot 

Today I started directly using your code, instead of copying parts of it.

I write these lines:
```
    std::vector<std::tuple<size_t, size_t, size_t, size_t, IK::FT, IK::FT>> output;
    CGAL::Polygon_mesh_processing::polyline_snapping(polylines, 1000, output, IK());
```

And during the build I have two following errors, any idea what I am doing wrong? :
![image](https://user-images.githubusercontent.com/18013985/149306587-7ccd8e18-d7a0-4801-ba99-82b01c8153a5.png)

**Comment by sloriot** [comment]
Disclamer: I did not write the code of the PR and never really looked at it. I'm not sure I understand what did not work with the code that you wrote. All pairs of segments that are closed with different polyline ids are reported. Then what are you missing?

**Comment by petrasvestartas** [comment]
It seems that when closest segment distance i.e. points on segment are not lying on segments then the returned value would be false. This is not handled, but I extended lines in such cases. I believe the issue is solved or what I believe is sufficient workaround.
The source code is here in case somebody will need it:
https://github.com/ibois-epfl/compas_wood/blob/main/src/cgal_box_search.h
