### ISSUE TITLE
Running Efficinet RANSAC and calculate normals only using Point_set

### ISSUE THREAD

**Issue by shayannikoohemat** [CGAL/cgal#6111]
## Issue Details
I want to know how to run the `CGAL::pca_estimate_normals` on a Point_set NOT a PointVectorPair. 
I need this for the planar segmentation of point clouds of many rooms with Efficient Ransac. I prefer to use point_set so I can carry my `named_properties` such as labels through the whole process even if points are shuffled or erased. Currently, I solve the issue by running the `pca_estimate_normals` on `PointVectorPair` and then transferring the normals to the `Point_set`. But this requires two times going through the point_set. 
Is there a better way to do it? And what is the best method to calculate normals for planar objects, such as walls, floor ceilings?
Any suggestion to improve the code is appreciated.

I am using part of this example: https://doc.cgal.org/latest/Point_set_3/index.html#title4

## Source Code

```
typedef CGAL::Exact_predicates_inexact_constructions_kernel  Kernel;
typedef Kernel::FT FT;
typedef Kernel::Point_3 Point;
typedef CGAL::Point_set_3<Point> Point_set;
typedef std::array<unsigned char, 3> Color;
typedef Point_set::Property_map<Color> Color_map;
typedef Point_set::Property_map<FT> FT_map; //  FT is FieldNumberType
typedef CGAL::Shape_detection::Efficient_RANSAC_traits
        <Kernel, Point_set, Point_set::Point_map, Point_set::Vector_map> Traits;
typedef CGAL::Shape_detection::Efficient_RANSAC<Traits> Efficient_ransac;
typedef CGAL::Shape_detection::Plane<Traits>            CGAL_Plane;

// Point with normal vector stored in a std::pair.
typedef Kernel::Vector_3 Vector;
typedef std::pair<Point, Vector> PointVectorPair;

// Concurrency
#ifdef CGAL_LINKED_WITH_TBB
typedef CGAL::Parallel_tag Concurrency_tag;
#else
typedef CGAL::Sequential_tag Concurrency_tag;
#endif

int planar_ransac(const string &ascii_filename, Efficient_ransac::Parameters ransac_parameters,
                  Point_set &point_set, int nb_neighbors){
    // read points with labels and color (customized function)
    if(read_color_label_ascii(ascii_filename, point_set, 1)){
        std::cout << " num of read points:" << point_set.size() << std::endl;
    } else {
        std::cout << "error in reading the file!" << std::endl;
        return EXIT_FAILURE;
    }
    // add segment_num as another property map (each segment num is a plane shape from ransac)
    bool success = false;
    FT_map segment;
    boost::tie (segment, success) = point_set.add_property_map<FT> ("segment", -1);
    assert (success);
    /// populate PointVectorMap with the point_set and empty normals
    point_set.add_normal_map();
    std::list<PointVectorPair> points;
    Point_set::iterator ps_it = point_set.begin();
    for (ps_it = point_set.begin(); ps_it != point_set.end(); ps_it++){
        Kernel::Point_3 point3(point_set.point(*ps_it));
        Kernel::Vector_3 normal3;
        PointVectorPair pwn; // point with normal
        pwn = std::make_pair(point3, normal3);
        points.push_back(pwn);
    }
    CGAL::pca_estimate_normals<Concurrency_tag>
            (points, nb_neighbors, 
               CGAL::parameters::point_map(CGAL::First_of_pair_property_map<PointVectorPair>())
                             .normal_map(CGAL::Second_of_pair_property_map<PointVectorPair>()));
    /// populate pointset with normals of PointVectorPair
    /// order of the points is the same
    Point_set::iterator pset_it = point_set.begin();
    for (auto &p : points){
        point_set.normal(*pset_it) = Vector(p.second.x(), p.second.y(), p.second.z());
        pset_it++;
    }
    // write point with normals for double check
    string out_ascii_normal="points_normal_label.txt";
    save_point_set(point_set, out_ascii_normal); // customized function
    // Efficient_ransac
    Efficient_ransac ransac;
    ransac.set_input(point_set,
                     point_set.point_map(), // Call built-in property map
                     point_set.normal_map()); // Call built-in property map
    ransac.add_shape_factory<CGAL_Plane>();
     // Detect shapes.
     ransac.detect(ransac_parameters);
     // access points and assign shape id to points
     Efficient_ransac::Shape_range shapes = ransac.shapes();
     Efficient_ransac::Shape_range::iterator it = shapes.begin();
     int shape_counter=0;
     Point_set::const_iterator pointset_it = point_set.begin();
     while (it != shapes.end()) {
       boost::shared_ptr<Efficient_ransac::Shape> shape = *it;
       /// Iterate through point indices assigned to each detected shape.
       std::vector<std::size_t>::const_iterator
       index_it = (*it)->indices_of_assigned_points().begin();
       while (index_it != (*it)->indices_of_assigned_points().end()) {
         /// Retrieve point.
          pointset_it = point_set.begin() + (*index_it);
         int inx = pointset_it - point_set.begin();
         Point p = point_set.point(inx);
         /// set the segment number to the pointset
         segment[*pointset_it] = it - shapes.begin();
         index_it++;
       } // end points iteration per shape
        it++;
     }//end shape iteration
     
    cout << "shape count: " << it - shapes.begin() << endl;
     return EXIT_SUCCESS;
}
```

## Environment

* Operating system (Linux, 64 bits, ubuntu 18.04):
* Compiler: g++, gcc
* CGAL version: 5.3
* Boost version: 1.65

**Comment by danston** [comment]
Hi. What you need to do is:
1. Create a [Point_set_3](https://doc.cgal.org/latest/Point_set_3/classCGAL_1_1Point__set__3.html) object. E.g. let it call `point_set`;
2. Then you need to [add a normal map](https://doc.cgal.org/latest/Point_set_3/classCGAL_1_1Point__set__3.html#aa04001c48e69953bba0f5eef989ba7fc) to it by doing: `point_set.add_normal_map()`.
3. Once it is there, you need to call [pca_estimate_normals](https://doc.cgal.org/latest/Point_set_processing_3/group__PkgPointSetProcessing3Algorithms.html#ga8c642da96a025ab32445aeb6cc219b0b) like this: `pca_estimate_normals(point_set, k, CGAL::parameters::point_map(point_set.point_map()).normal_map(point_set.normal_map())`. See [here](https://doc.cgal.org/latest/Point_set_3/classCGAL_1_1Point__set__3.html#a41a0ac0eecc100a02efca2039a1c35c5) for normal map of the point set object. The estimated normals will be put right inside the normal map of the `point_set` and can be then used in Ransac.

I think if your objects are nearly planar then PCA normal estimation should be good but be careful of choosing the right number of nearest neighbors `k`. If your points make a surface and are more or less uniformly sampled, 6 or 12 should be a good fit.

**Comment by shayannikoohemat** [comment]
@danston thanks I tried this and it worked. Great help.

**Comment by shayannikoohemat** [comment]
Do you know if I add [plane regularization](https://doc.cgal.org/latest/Shape_detection/group__PkgShapeDetectionRef.html#gadaa392158d3ca1857dbb426953d1f9d8) to the same code how I can transfer points to the new planes? In the documentation, it says "Planes are directly modified. Points are left unaltered, as well as their relationships to planes (no transfer of point from a primitive plane to another)." This means for example if two nearly co-planar planes are altered with one plane still their points are not. One thing I can do is go through new planes and add inlier points to them but then this can create segments of points far from each other but on the same plane.

**Comment by danston** [comment]
@shayannikoohemat I am glad that it works now. About transferring points, why do you need that? The plane regularization returns planes, which are regularized and their inliers are untouched. If you want to reshuffle your points between new planes you will need some kind of measure that says that the old inlier must now go to the new plane, but I do not see any real application of that... The common idea is to find planar shapes first and then work with them keeping in mind original points, that form these shapes.

**Comment by shayannikoohemat** [comment]
@danston I need to use the inliers of planes for my further process which means after regularization new planes are generated and their inliers are also required to be regenerated but from plane regularization documentation I understood this is not happening.

**Comment by danston** [comment]
Ok, then you need to reassign your points to the new planes yourself because the plane regularization algorithm only regularizes planes.

**Comment by danston** [comment]
@shayannikoohemat Do you need any extra clarifications on the point set processing algorithms? If not, I would like to close this issue. Thanks.
