### ISSUE TITLE
`#define CGAL_NO_UNIQUE_ADDRESS [[msvc::no_unique_address]]` when _MSC_VER >= 1929

### ISSUE THREAD

**Issue by mglisse** [CGAL/cgal#6115]
As described in https://devblogs.microsoft.com/cppblog/msvc-cpp20-and-the-std-cpp20-switch/

**Comment by mglisse** [comment]
I don't have windows, can't do something I cannot test...

**Comment by lrineau** [comment]
@janetournois Let's discuss that next time we meet at the office...

**Comment by mglisse** [comment]
This seems to have been done a while ago. Strangely, it was decided to also check `_MSVC_LANG >= 202002L` in order to quiet a warning (https://github.com/CGAL/cgal/pull/6950#discussion_r1169748544) instead of disabling that warning :disappointed: 

Another related thing that could be useful is a macro for [`__declspec(empty_bases)`](https://learn.microsoft.com/en-us/cpp/cpp/empty-bases).
