### ISSUE TITLE
CGAL::poisson_surface_reconstruction_delaunay

### ISSUE THREAD

**Issue by DaReCo12** [CGAL/cgal#6125]
## Issue Details

i want to write a programm in c++ which use CGAL. I want to use the "CGAL::poisson_surface_reconstruction_delaunay" but there is still a problem that the follwoing Error occurs

"'CGAL::Poisson_reconstruction_function<Kernel>::compute_implicit_function': no matching overloaded function found"
"CGAL::Poisson_reconstruction_function<Kernel>::compute_implicit_function(SparseLinearAlgebraTraits_d,Visitor,double,double)': expects 4 arguments - 0 provided"

I used the example: https://doc.cgal.org/latest/Poisson_surface_reconstruction_3/Poisson_surface_reconstruction_3_2poisson_reconstruction_function_8cpp-example.html

## Source Code

```
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/Polyhedron_3.h>
#include <CGAL/poisson_surface_reconstruction.h>
#include <CGAL/IO/read_points.h>
#include <vector>
#include <fstream>
// Types
typedef CGAL::Exact_predicates_inexact_constructions_kernel Kernel;
typedef Kernel::Point_3 Point;
typedef Kernel::Vector_3 Vector;
typedef std::pair<Point, Vector> Pwn;
typedef CGAL::Polyhedron_3<Kernel> Polyhedron;

int main(void)
{
    std::vector<Pwn> points;
    if (!CGAL::IO::read_points("data/kitten.xyz", std::back_inserter(points),
        CGAL::parameters::point_map(CGAL::First_of_pair_property_map<Pwn>())
        .normal_map(CGAL::Second_of_pair_property_map<Pwn>())))
    {
        std::cerr << "Error: cannot read input file!" << std::endl;
        return EXIT_FAILURE;
    }
    Polyhedron output_mesh;
    double average_spacing = CGAL::compute_average_spacing<CGAL::Sequential_tag>
        (points, 6, CGAL::parameters::point_map(CGAL::First_of_pair_property_map<Pwn>()));
    if (CGAL::poisson_surface_reconstruction_delaunay
    (points.begin(), points.end(),
        CGAL::First_of_pair_property_map<Pwn>(),
        CGAL::Second_of_pair_property_map<Pwn>(),
        output_mesh, average_spacing))
    {
        std::ofstream out("kitten_poisson-20-30-0.375.off");
        out << output_mesh;
    }
    else
        return EXIT_FAILURE;
    return EXIT_SUCCESS;
}
```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows 64 Bit
* Compiler: VS 2019
* Release or debug mode: debug
* Specific flags used (if any):
* CGAL version: 5.3
* Boost version: 1.77.0
* Other libraries versions if used (Eigen, TBB, etc.): qt5 5.15.2

**Comment by sloriot** [comment]
Do you have the Eigen library install and was it correctly detected by cmake?

**Comment by lrineau** [comment]
@DaReCo12 If you do not use CMake to configure the Visual Studio project, then add:
```c++
#define CGAL_EIGEN3_ENABLED 1
```
as the first line of your .cpp file. Then you will probably have errors about Visual Studio that cannot find headers files like `Eigen/Sparse`. You will have to add the directory to those header files in the include path.

**Comment by lrineau** [comment]
@DaReCo12 Now that the compilation error is fixed, you have now a linker error. In the solution, you need to add `libgmp-10.lib` in the list of libraries linked with the target. You will also have to add `libmpfr-4.lib`. If your solution was produced by the CMake build system shipped with CGAL, it would be automatic.

Then, at runtime, make sure the path to the DLLs `libgmp-10.dll` and `libmpfr-4.dll` is in the `PATH` environment variable, or copy this DLLs alongside the executable.

Note that, if you installed CGAL using vcpkg, the names of the libraries and DLLs for GMP and MPFR might be slightly different.

**Comment by DaReCo12** [comment]
Ok thanks alot. The Programm works, i doesn't understand that the "poisson_surface_reconstruction_delaunay" needs a lot of time, or something is wrong, I have a bunny with 35000 Points but it woriks for 2h and it's still work. Is it normal that it needs so much time?

**Comment by lrineau** [comment]
@DaReCo12 I am glad you eventually managed to compile and run that code. A Poisson reconstruction should only take a few seconds.

From what I can see in the code, the input file is expected to contain normals. And it seems that the behavior of the code, when the normals are absent, is that infinite loop. In my opinion that is not correct:
  - the function `CGAL::IO::read_points` shoudl return an error, if a normal map is passed to it but the file has no normals,
  - and then Poisson Reconstruction algorithm should complain and return an error, instead of looping forever.

**Comment by DaReCo12** [comment]
@lrineau Thank you! Is there any way to create normals in CGAL only with a pointcloud? I looked in my file and there are no nomals and now i want to create them to run the poisson algorithm.

**Comment by lrineau** [comment]
Yes. Everything is explained in the user manual. See https://doc.cgal.org/latest/Poisson_surface_reconstruction_3/index.html#title1

**Comment by MaelRL** [comment]
> the function CGAL::IO::read_points should return an error, if a normal map is passed to it but the file has no normals

I had a look and this is a "feature" due to the way `Point_set_3`'s IO was written: when trying to read into a `Point_set_3`, a `normal_map` property is automatically added to the `Point_set_3`, and the generic functions for point sets are called (with the normal map passed through named parameters); if in the output there is a point with a null normal, then the normal map property is removed from the `Point_set_3`. For OFF (NOFF), this could be detected easily through the header, but this is not the case for all formats (`.xyz` for example).

**Comment by lrineau** [comment]
> > the function CGAL::IO::read_points should return an error, if a normal map is passed to it but the file has no normals
> 
> I had a look and this is a "feature" due to the way `Point_set_3`'s IO was written: when trying to read into a `Point_set_3`, a `normal_map` property is automatically added to the `Point_set_3`, and the generic functions for point sets are called (with the normal map passed through named parameters); if in the output there is a point with a null normal, then the normal map property is removed from the `Point_set_3`. For OFF (NOFF), this could be detected easily through the header, but this is not the case for all formats (`.xyz` for example).

Then maybe the Poisson reconstruction algorithm should check as a precondition that the normals are not all null.
