### ISSUE TITLE
#include "CGAL/Surface_mesh.h" warning in Visual Studio

### ISSUE THREAD

**Issue by jasjuang** [CGAL/cgal#6127]
## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows 10
* Compiler: Visual Studio 2019
* Release or debug mode: Debug
* CGAL version: 5.3
* Boost version: 1.77
* 
## Steps to reproduce

```
vcpkg install cgal
```

CMakeLists.txt
```
set(CMAKE_TOOLCHAIN_FILE $ENV{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake)

cmake_minimum_required(VERSION 3.20)

project(example)

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /W4 /WX")

find_package(CGAL REQUIRED)

add_executable(${PROJECT_NAME} main.cpp)

target_link_libraries(${PROJECT_NAME} PUBLIC CGAL::CGAL)
```

main.cpp
```
__pragma(warning(push,0))
#include "CGAL/Surface_mesh.h"
__pragma(warning(pop))

int main() { return 0; }
```

This results in compilation error:

```
1>C:\vcpkg\installed\x64-windows\include\CGAL/IO/helpers.h(56): message : see reference to function template instantiation '_OutIt std::transform<std::_String_iterator<std::_String_val<std::_Simple_types<_Elem>>>,std::_String_iterator<std::_String_val<std::_Simple_types<_Elem>>>,int(__cdecl *)(int)>(const _InIt,const _InIt,_OutIt,_Fn)' being compiled
1>        with
1>        [
1>            _OutIt=std::_String_iterator<std::_String_val<std::_Simple_types<char>>>,
1>            _Elem=char,
1>            _InIt=std::_String_iterator<std::_String_val<std::_Simple_types<char>>>,
1>            _Fn=int (__cdecl *)(int)
1>        ]
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\include\algorithm(2216,24): warning C4244: '=': conversion from 'int' to 'char', possible loss of data
1>Done building project "example.vcxproj" -- FAILED.
```

After looking into https://github.com/CGAL/cgal/blob/4610cf3c666b512816fd643df6082f5720111a8b/Stream_support/include/CGAL/IO/helpers.h#L57 according to the hint from Visual Studio, I was able to get it to compile by changing 

```
std::transform(ext.begin(), ext.end(), ext.begin(), ::tolower);
```
to
```
std::transform(ext.begin(), ext.end(), ext.begin(), [](char c) { return static_cast<char>(std::tolower(c)); });
```

It would be nice to get this fix or some other better equivalent fix into 5.4 especially when for some reason I can't disable this warning despite having `__pragma(warning(push,0))` and `__pragma(warning(pop))` sandwiching the CGAL headers.

**Comment by lrineau** [comment]
See also https://en.cppreference.com/w/cpp/string/byte/tolower#Notes: the correct implementation of the lambda expression is:
```c++
[](char c) { 
  return static_cast<char>(std::tolower(static_cast<unsigned char>(ch)));
}
```

**Comment by afabri** [comment]
In the link you @lrineau gave  is written `[](unsigned char c){ return std::tolower(c); } // correct`   so why do you see need for the two `static_cast`?

**Comment by lrineau** [comment]
> In the link you @lrineau gave is written `[](unsigned char c){ return std::tolower(c); } // correct` so why do you see need for the two `static_cast`?

That's because in our case the data type of `std::string` is `char`, and not `unsigned char`. With `/W4` and `/WX`, you need to quiet all the warnings. That is why I added the the two `static_cast`.
