### ISSUE TITLE
Bug for anchors in cgal doc, for packages HeatMethod and SurfaceMeshTopology.

### ISSUE THREAD

**Issue by gdamiand** [CGAL/cgal#6136]
_Please use the following template to help us solving your issue._

## Issue Details

One small bug in the documentation, for packages HeatMethod and SurfaceMeshTopology.

In https://doc.cgal.org/latest/Manual/packages.html, each package has an anchor named "PkgXXX", XXX being the name of the package.

For the 2 packages HeatMethod and SurfaceMeshTopology, the anchor is named "PkgXXXSummary", implying error when these anchors are used as redirect.

**Comment by sloriot** [comment]
Heat method was fixed in e64089d6904ef0ebcf551f64cad5b60306ad8bd8 and I just fixed SMT in fb4c8484e9f
