### ISSUE TITLE
Triangulating 3D surfaces

### ISSUE THREAD

**Issue by ReeNine** [CGAL/cgal#6142]
Hi. I need some help. Can I do something similar using this library? In this example, an image is fed to the input of a function, but I want to feed in an array of points and get a triangulated surface. 3D triangulation is not quite suitable for this because it makes the object closed. Can anyone help - I'm looking for something like triangulating a 3d surface.
![image](https://user-images.githubusercontent.com/94655126/142734869-baa0d640-98a7-4ac2-a820-82bc80d60f70.png)

**Comment by petrasvestartas** [comment]
If you have point cloud input then perform poisson surface reconstruction:
https://doc.cgal.org/latest/Poisson_surface_reconstruction_3/index.html

or if it is 2d, then alpha-share or similar delaunay triangulation

**Comment by sloriot** [comment]
More generally, you can have a look at that tutorial: https://doc.cgal.org/latest/Manual/tuto_reconstruction.html
