### ISSUE TITLE
linear_least_squares_fitting_3 may return NAN

### ISSUE THREAD

**Issue by bizerfr** [CGAL/cgal#6146]
## Issue Details

I use the cgal function "linear_least_squares_fitting_3" to fit a plane, I found the return value may be "NAN";

My code is like this:
```
Plane plane;
FT conf = linear_least_squares_fitting_3(points.begin(), points.end(), plane, CGAL::Dimension_tag<0>());
```
the value "conf" can be "NaN" or "2", whereas it should be within `[0,1]`.

Please take a look at the source code:

https://github.com/CGAL/cgal/blob/4321e776d0eb2ac6b2581ff06445aebca6e06a81/Principal_component_analysis/include/CGAL/PCA_util.h#L712-L727

If the `eigen_values[0]`, `eigen_values[1]`  and `eigen_values[2]` are all `0`, it will return zero; otherwise it will return `1 - eigen_values[0] / eigen_values[1]`. But there is a case, `eigen_values[1]` is `0`, while one of the others are not; in this case, the function can return "nan'. 

and also, `eigen_values[0] / eigen_values[1]` could `-1`, thus the return value will be `2`.

I think some degenerate cases are not taken into consideration, such as we fitting a plane for just two points.

Please fix it

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): linux
* Compiler: gcc
* Release or debug mode: release
* Specific flags used (if any): 
* CGAL version: 5.3

**Comment by afabri** [comment]
See [nan.cpp](https://gist.github.com/afabri/e74d6bbf503c802066a23f194700f4f9)

**Comment by oesi82** [comment]
> and also, eigen_values[0] / eigen_values[1] could -1, thus the return value will be 2.

A covariance matrix is positive semi-definite, so all eigenvalues are >= 0.

**Comment by lrineau** [comment]
Fixed by https://github.com/CGAL/cgal/pull/6510
