### ISSUE TITLE
CGAL Mesh Boolean Difference depreciated on C++17

### ISSUE THREAD

**Issue by petrasvestartas** [CGAL/cgal#6148]
## Issue Details

CGAL 5.3 Trying to compile previous code from CGAL 5.2 but warnings do not let to compile because method is depreciated.
What changed in the new version of CGAL regarding mesh boolean operations?

The compilation works for C++14 but not for C++17.

![image](https://user-images.githubusercontent.com/18013985/143263496-11ad078d-511a-4988-97b0-133d0c8205e9.png)

## Source Code
```
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/Surface_mesh.h>
#include <CGAL/Polygon_mesh_processing/corefinement.h>
....
bool valid_union = CGAL::Polygon_mesh_processing::corefine_and_compute_difference(mesh1, mesh2, out);

```

Full SourceCode:
https://github.com/ibois-epfl/Raccoon_Litter_Box/blob/main/joinery_solver/joinery_solver_rhino7/command_mesh_difference.cpp

## Environment
* Operating system (Windows 64 bits):
* CGAL version: 5.3

**Comment by sloriot** [comment]
AFAIS, the depreciation warnings come from the usage of some std functions, not from CGAL directly. I'm a bit surprised you do not have those warnings with 5.2. Could you try an [internal release](https://cgal.geometryfactory.com/CGAL/Releases/CGAL-5.4-I-99.tar.gz) targeting CGAL-5.4? Also I did not see this error in the testsuite on the platform using the latest version of c++.

**Comment by petrasvestartas** [comment]
I think this is caused by Rhino software that I am linking CGAL with.
I will check 5.4 as well.

**Comment by sloriot** [comment]
@petrasvestartas do you still have the issue with 5.4?

**Comment by petrasvestartas** [comment]
I think this was related to my workflow. I close this issue.
