### ISSUE TITLE
surface_mesh is too strict

### ISSUE THREAD

**Issue by ligaofeng0901** [CGAL/cgal#6150]
surface mesh will check many preconditions before operations,  like clipping, simplification, etc. What if I only want to clip a triangulated mesh by bounding box, even if the mesh is so messy.  Many different kinds of error messages will show up.
`
is_valid_polygon_mesh(m_tm) && CGAL::is_triangle_mesh(m_tm)
`
and the operation will fail.

I wonder if there is another way to do it. Maybe it does't have to be surface mesh.

**Comment by MaelRL** [comment]
Could you please provide the mesh, to clarify which kind of "messy" you mean?

If your set of faces cannot be represented via a polygon mesh, you could just clip each face independently.
