### ISSUE TITLE
Broken greater-than operator for Nef_polyhedron_3

### ISSUE THREAD

**Issue by firerain42** [CGAL/cgal#6151]
## Issue Details

For two disjoint Nef polyhedra `poly1` and `poly2`, `poly1 > poly2` returns `true`.  The other comparison operators don't seem to be affected. Most likely this is caused by a missing `N1` in [this line](https://github.com/CGAL/cgal/blob/cce94c21c5aad8a55ca5bc272229628e70bb3049/Nef_3/include/CGAL/Nef_polyhedron_3.h#L1559), i.e. it should be `return N1.difference(*this).is_empty() && !difference(N1).is_empty();`.

## Source Code

```c++
#include <CGAL/Exact_integer.h>
#include <CGAL/Extended_homogeneous.h>
#include <CGAL/Nef_polyhedron_3.h>

typedef CGAL::Exact_integer  NT;
typedef CGAL::Extended_homogeneous<NT>  Kernel;
typedef CGAL::Nef_polyhedron_3<Kernel>  Nef_polyhedron;
typedef Kernel::Plane_3 Plane_3;
int main() {

  Nef_polyhedron N1(Plane_3(2,5,7,11), Nef_polyhedron::INCLUDED);
  Nef_polyhedron N2(Plane_3(-2,-5,-7,-10), Nef_polyhedron::INCLUDED);

  CGAL_assertion(!(N1 >= N2));
  CGAL_assertion(!(N2 <= N1));
  CGAL_assertion(N1 != N2);
  CGAL_assertion(!(N2 < N1));
  CGAL_assertion(!(N1 > N2));  // fails

  return 0;
}
```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Linux x64
* Compiler: GCC
* Release or debug mode: Debug
* Specific flags used (if any): /
* CGAL version: master
* Boost version: Boost-1.71.0  
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by afabri** [comment]
Hello @firerain42, thank you for pointing it out.

**Comment by lrineau** [comment]
Fixed by https://github.com/CGAL/cgal/pull/6154. Will be in 5.2.4.
