### ISSUE TITLE
CDT - 2D triangulation crash when holes are intersecting.

### ISSUE THREAD

**Issue by petrasvestartas** [CGAL/cgal#6153]
I would like to ask how I can prevent application from crashing when using CDT when inner polygons intersecting with outer. In those cases I do not need any output, but empty result.

To explain the problem I attach the code, video and images.

## Issue Details

This is the current issue:
![image](https://user-images.githubusercontent.com/18013985/144075157-80a4c8e6-025c-4aeb-a452-f8b738be5186.png)

![Triangulation](https://user-images.githubusercontent.com/18013985/144075514-eb57ba0f-d2be-4a29-9c7f-1415fd000183.png)

I use it for meshing following polylines:
https://vimeo.com/650968401

## Source Code

Just a little bit adapted from this official CGAL example:
https://doc.cgal.org/latest/Triangulation_2/Triangulation_2_2polygon_triangulation_8cpp-example.html

```

#pragma once
#include "stdafx.h"
#include "compas.h"



namespace CGAL_MeshUtil{

    inline void
        mark_domains(CDT& ct,
            Face_handle start,
            int index,
            std::list<CDT::Edge>& border) {
        if (start->info().nesting_level != -1) {
            return;
        }
        std::list<Face_handle> queue;
        queue.push_back(start);
        while (!queue.empty()) {
            Face_handle fh = queue.front();
            queue.pop_front();
            if (fh->info().nesting_level == -1) {
                fh->info().nesting_level = index;
                for (int i = 0; i < 3; i++) {
                    CDT::Edge e(fh, i);
                    Face_handle n = fh->neighbor(i);
                    if (n->info().nesting_level == -1) {
                        if (ct.is_constrained(e)) border.push_back(e);
                        else queue.push_back(n);
                    }
                }
            }
        }
    }
    //explore set of facets connected with non constrained edges,
    //and attribute to each such set a nesting level.
    //We start from facets incident to the infinite vertex, with a nesting
    //level of 0. Then we recursively consider the non-explored facets incident
    //to constrained edges bounding the former set and increase the nesting level by 1.
    //Facets in the domain are those with an odd nesting level.
    inline void
        mark_domains(CDT& cdt) {
        for (CDT::Face_handle f : cdt.all_face_handles()) {
            f->info().nesting_level = -1;
        }
        std::list<CDT::Edge> border;
        mark_domains(cdt, cdt.infinite_face(), 0, border);
        while (!border.empty()) {
            CDT::Edge e = border.front();
            border.pop_front();
            Face_handle n = e.first->neighbor(e.second);
            if (n->info().nesting_level == -1) {
                mark_domains(cdt, n, e.first->info().nesting_level + 1, border);
            }
        }
    }

    inline CGAL::Aff_transformation_3<IK> plane_to_XY_mesh(
        IK::Point_3 O0, IK::Plane_3 plane
    ) {
        auto X0 = plane.base1();
        auto Y0 = plane.base2();
        auto Z0 = plane.orthogonal_vector();
        CGAL_VectorUtil::Unitize(X0);
        CGAL_VectorUtil::Unitize(Y0);
        CGAL_VectorUtil::Unitize(Z0);

        // transformation maps P0 to P1, P0+X0 to P1+X1, ...

        //Move to origin -> T0 translates point P0 to (0,0,0)
        CGAL::Aff_transformation_3<IK> T0(CGAL::TRANSLATION, IK::Vector_3(0 - O0.x(), 0 - O0.y(), 0 - O0.z()));


        //Rotate ->
        CGAL::Aff_transformation_3<IK> F0(
            X0.x(), X0.y(), X0.z(),
            Y0.x(), Y0.y(), Y0.z(),
            Z0.x(), Z0.y(), Z0.z()
        );


        return  F0 * T0;

    }



    inline void mesh_from_polylines(std::vector<CGAL_Polyline>& polylines_with_holes, IK::Plane_3& base_plane, std::vector<int>& top_face_vertices) {
   
        //////////////////////////////////////////////////////////////////////////////
        //Create Transformation | Orient to 2D 
        //////////////////////////////////////////////////////////////////////////////
        CGAL::Aff_transformation_3<IK> xform_toXY = plane_to_XY_mesh(polylines_with_holes[0][0], base_plane);
        CGAL::Aff_transformation_3<IK> xform_toXY_Inv = xform_toXY.inverse();

        CDT cdt;
        for (int i = 0; i < polylines_with_holes.size(); i +=2 ) {

            Polygon_2 polygon_2d;
            for (int j = 0; j < polylines_with_holes[i].size()-1; j++) {
                IK::Point_3 p = polylines_with_holes[i][j].transform(xform_toXY);
                polygon_2d.push_back(Point(p.hx(), p.hy()));
                //myfile << polylines_with_holes[i][j][0] << " " << polylines_with_holes[i][j][1] << " " << polylines_with_holes[i][j][2] << "\n";
            }
     
            //////////////////////////////////////////////////////////////////////////////
            //Insert the polygons into a constrained triangulation
            //////////////////////////////////////////////////////////////////////////////
            cdt.insert_constraint(polygon_2d.vertices_begin(), polygon_2d.vertices_end(), true);
        }

        //////////////////////////////////////////////////////////////////////////////
        //Mark facets that are inside the domain bounded by the polygon
        //////////////////////////////////////////////////////////////////////////////
        mark_domains(cdt);
      
        int count = 0;
        for (Face_handle f : cdt.finite_face_handles()) {
            if (f->info().in_domain()) {
           
                ++count;

            }
        }
       

         std::map<CDT::Vertex_handle, int> vertex_index;
        int k = 0;
        for (auto it = cdt.vertices_begin(); it != cdt.vertices_end(); ++it) {
            auto p = it->point();
            vertex_index[it] = k;
            k++;
            //myfile << p[0] << " " << p[1] << "\n";
        }

     
        int number_of_faces = 0;
        for (Face_handle f : cdt.finite_face_handles()) {
            if (f->info().in_domain()) {
                number_of_faces+=3;
            }
        }

        top_face_vertices.reserve(number_of_faces);
        for (Face_handle f : cdt.finite_face_handles()) {
            if (f->info().in_domain()) {
                  top_face_vertices.emplace_back(vertex_index[f->vertex(0)]);
                top_face_vertices.emplace_back(vertex_index[f->vertex(1)]);
                top_face_vertices.emplace_back(vertex_index[f->vertex(2)]);
  
            }
        }
   
    }
	


}
```
## Environment

* Operating system (Windows 64 bits):
* CGAL version 5.3:

**Comment by afabri** [comment]
What is your typedef for CDT ?

**Comment by petrasvestartas** [comment]
using IK = CGAL::Exact_predicates_inexact_constructions_kernel;
using EK = CGAL::Exact_predicates_exact_constructions_kernel;
typedef CGAL::Cartesian_converter<IK, EK> IK_to_EK;
typedef CGAL::Cartesian_converter<EK, IK> EK_to_IK;
using CGAL_Polyline = std::vector<IK::Point_3>;
using CGAL_Polylines = std::list<CGAL_Polyline>;

typedef CGAL::Triangulation_vertex_base_2<IK>                      Vb;
typedef CGAL::Triangulation_face_base_with_info_2<FaceInfo2, IK>    Fbb;
typedef CGAL::Constrained_triangulation_face_base_2<IK, Fbb>        Fb;
typedef CGAL::Triangulation_data_structure_2<Vb, Fb>               TDS;
typedef CGAL::Exact_predicates_tag                                Itag;
typedef CGAL::Constrained_Delaunay_triangulation_2<IK, TDS, Itag>  CDT;
typedef CDT::Point                                                Point;
typedef CGAL::Polygon_2<IK>                                        Polygon_2;
typedef CDT::Face_handle                                          Face_handle;

**Comment by lrineau** [comment]
Hi Petras, thanks for the video. That is interesting to see what users may do with CGAL code. The template parameter `Itag` already allows intersections between constraints. So, the issue is probably somewhere else.

I am surprised that the crash can be on data as simple as two overlapping rectangles. That would help us if you could dump (with precision 17) the coordinates of all the polylines (in `polygon_2d`) that are inserted in the CDT.

**Comment by afabri** [comment]
> Regarding the code. I will try to debug more, if this is not an issue of CDT, then something is crashing after in my own code.

Hello @petrasvestartas , did you get a chance to see if the bug is on our side or on your side?  Best, Andreas

**Comment by petrasvestartas** [comment]
@afabri  thanks for the reminder, I ll check my code since and let you know ASAP.

**Comment by petrasvestartas** [comment]
@afabri ,

Can you help me to spot the problem, where can I have a bug?
The application does not crash but my code produces more faces than vertices in problematic inputs. With good input it works fine. The failing case is this:

![image](https://user-images.githubusercontent.com/18013985/148258899-35c8b679-67c0-4cd8-b0cf-22a648b8274c.png)

```
Polyline
Point(-250.000, -161.482, -7.500)
Point(-250.000, -156.153, -7.500)
Point(-194.444, -154.323, -7.500)
Point(-194.198, -161.819, -7.500)
Point(-138.642, -159.989, -7.500)
Point(-138.889, -152.493, -7.500)
Point(-83.333, -150.662, -7.500)
Point(-27.778, -152.493, -7.500)
Point(-28.025, -159.989, -7.500)
Point(27.531, -161.819, -7.500)
Point(27.778, -154.323, -7.500)
Point(83.333, -156.153, -7.500)
Point(83.333, -157.929, -7.500)
Point(75.833, -157.929, -7.500)
Point(75.833, -159.705, -7.500)
Point(83.333, -159.705, -7.500)
Point(83.333, -161.482, -7.500)
Point(-250.000, -161.482, -7.500)

Polyline
Point(-250.000, -161.482, 7.500)
Point(-250.000, -156.153, 7.500)
Point(-194.444, -154.323, 7.500)
Point(-194.198, -161.819, 7.500)
Point(-138.642, -159.989, 7.500)
Point(-138.889, -152.493, 7.500)
Point(-83.333, -150.662, 7.500)
Point(-27.778, -152.493, 7.500)
Point(-28.025, -159.989, 7.500)
Point(27.531, -161.819, 7.500)
Point(27.778, -154.323, 7.500)
Point(83.333, -156.153, 7.500)
Point(83.333, -157.929, 7.500)
Point(75.833, -157.929, 7.500)
Point(75.833, -159.705, 7.500)
Point(83.333, -159.705, 7.500)
Point(83.333, -161.482, 7.500)
Point(-250.000, -161.482, 7.500)
```

The source code is here:
https://github.com/petrasvestartas/compas_wood/blob/main/src/cgal_mesh_util.h

In the function called:
` inline void mesh_from_polylines(std::vector<CGAL_Polyline>& polylines_with_holes, IK::Plane_3& base_plane, std::vector<int>& top_outline_face_vertex_indices)`

face vertex (goes until 37) indices that there are vertices (34):
```
V
[-249.999985 -161.481766   -7.5     ]
[-249.999985 -156.152866   -7.5     ]
[-194.4444431  -154.32273967   -7.5       ]
[-194.19750993 -161.8186735    -7.5       ]
[-138.64196802 -159.98854717   -7.5       ]
[-138.88890119 -152.49261334   -7.5       ]
[ -83.333359 -150.662487   -7.5     ]
[ -27.77779675 -152.49261333   -7.5       ]
[ -28.02472983 -159.98854717   -7.5       ]
[  27.53083242 -161.8186735    -7.5       ]
[  27.7777655  -154.32273966   -7.5       ]
[  83.333328 -156.152866   -7.5     ]
[  83.333328 -157.929166   -7.5     ]
[  75.833328 -157.929166   -7.5     ]
[  75.833328 -159.705466   -7.5     ]
[  83.333328 -159.705466   -7.5     ]
[  83.333328 -161.481766   -7.5     ]
[-249.999985 -161.481766    7.5     ]
[-249.999985 -156.152866    7.5     ]
[-194.4444431  -154.32273967    7.5       ]
[-194.19750993 -161.8186735     7.5       ]
[-138.64196802 -159.98854717    7.5       ]
[-138.88890119 -152.49261334    7.5       ]
[ -83.333359 -150.662487    7.5     ]
[ -27.77779675 -152.49261333    7.5       ]
[ -28.02472983 -159.98854717    7.5       ]
[  27.53083242 -161.8186735     7.5       ]
[  27.7777655  -154.32273966    7.5       ]
[  83.333328 -156.152866    7.5     ]
[  83.333328 -157.929166    7.5     ]
[  75.833328 -157.929166    7.5     ]
[  75.833328 -159.705466    7.5     ]
[  83.333328 -159.705466    7.5     ]
[  83.333328 -161.481766    7.5     ]
F
[0 1 2]
[20  0  2]
[ 8 18 19]
[6 4 5]
[7 8 6]
[8 4 6]
[17  9 18]
[11 12 13]
[13 14 17]
[11 13 10]
[15 16 14]
[10 13 17]
[ 8 19  4]
[19  3 20]
[16 17 14]
[19 18 17]
[19 17 37]
[36 35 25]
[22 21 23]
[23 25 24]
[23 21 25]
[35 26 34]
[30 29 28]
[34 31 30]
[27 30 28]
[31 33 32]
[34 30 27]
[21 36 25]
[37 20 36]
[31 34 33]
[17 18  1]
[17  1  0]
[18 19  2]
[18  2  1]
[19 20  3]
[19  3  2]
[20 21  4]
[20  4  3]
[21 22  5]
[21  5  4]
[22 23  6]
[22  6  5]
[23 24  7]
[23  7  6]
[24 25  8]
[24  8  7]
[25 26  9]
[25  9  8]
[26 27 10]
[26 10  9]
[27 28 11]
[27 11 10]
[28 29 12]
[28 12 11]
[29 30 13]
[29 13 12]
[30 31 14]
[30 14 13]
[31 32 15]
[31 15 14]
[32 33 16]
[32 16 15]
[33 17  0]
[33  0 16]
```

It normally produces good results as images below:
![closed_mesh_from_polylines_ss_24](https://user-images.githubusercontent.com/18013985/148258418-025c6993-a500-4686-88b2-dd95fcc776ef.jpg)
![closed_mesh_from_polylines_c_0](https://user-images.githubusercontent.com/18013985/148258420-659ef6bc-818e-4722-8b51-744502963d24.jpg)
![closed_mesh_from_polylines_c_10](https://user-images.githubusercontent.com/18013985/148258426-efe16428-44ea-43ab-b193-a23bd80e126e.jpg)
![closed_mesh_from_polylines_c_13](https://user-images.githubusercontent.com/18013985/148258427-4f19ad8e-8b73-4d37-a2a6-3e89326af81a.jpg)
![closed_mesh_from_polylines_c_14](https://user-images.githubusercontent.com/18013985/148258430-003c3c02-0cbc-4cd0-8103-09c2a1684125.jpg)
![closed_mesh_from_polylines_c_15](https://user-images.githubusercontent.com/18013985/148258433-3134d3db-f0ed-470f-a5e3-ad08b5083df6.jpg)
![closed_mesh_from_polylines_c_16](https://user-images.githubusercontent.com/18013985/148258435-dad67c37-6bb1-4500-87c4-d2c5607ed965.jpg)
![closed_mesh_from_polylines_ss_0](https://user-images.githubusercontent.com/18013985/148258437-86f2f311-3cca-470f-8402-1c1a87958eb0.jpg)
![closed_mesh_from_polylines_ss_7](https://user-images.githubusercontent.com/18013985/148258438-c8b46fae-79ca-4246-abba-ef58151dd970.jpg)
![closed_mesh_from_polylines_ss_10](https://user-images.githubusercontent.com/18013985/148258439-67966349-2da6-4ee9-a769-7a92f0eea54c.jpg)
![closed_mesh_from_polylines_ss_14](https://user-images.githubusercontent.com/18013985/148258441-008e377a-2a67-4094-9f59-f08b402f454b.jpg)
![closed_mesh_from_polylines_ss_17](https://user-images.githubusercontent.com/18013985/148258444-53c85673-d3b7-4e9e-ba9e-54ad51380b00.jpg)

**Comment by afabri** [comment]
Hello @petrasvestartas.   I  just created a standalone [cdt.cpp](https://gist.github.com/afabri/827106024fd6b89fbacd6b2bbb7b3f94) on gist.github,com.   I would be glad to have a google meet with you the next days as I am not really sure to understand the problem you want to solve.

**Comment by petrasvestartas** [comment]
Thank you. What I am doing here is:
1. Orient a polyline from 3d to 2d and mesh it using cdt
2. Use the the same triangulation for the other group of polylines
3. Add side mesh faces

I worked today on this little problem, and came out to conclusion that I should not have output if polylines are intersecting. I simply do not continue to make mesh and output empty array. Just it would be good to have confirmation, from you, that the cdt mesh vertex order is always the same as polygon input.

I have few other questions, since I relying on CGAL in my work.

I would like to ask how to set up bounding box search package, since I struggle to read documentation properly:

https://doc.cgal.org/latest/Box_intersection_d/index.html#Chapter_Intersecting_Sequences_of_dD_Iso-oriented_Boxes

If you are available tomorrow or next week, it would a great help for me.

**Comment by petrasvestartas** [comment]
@afabri Thank you very much for the help during the Zoom talk.

I managed to test the simple set and the application return without crash.
Here is the set:
![image](https://user-images.githubusercontent.com/18013985/148822242-09b01713-a4ed-4967-a7a6-44c255af0140.png)
2nd from is caught during try and catch statement: CDT::Intersection_of_constraints_exception 

```
            try {
               cdt.insert_constraint(polygon_2d.vertices_begin(), polygon_2d.vertices_end(), true);
            } catch (const CDT::Intersection_of_constraints_exception&){
                printf("CDT::Intersection_of_constraints_exception \n");

                return;
            }
```

and the rest of the cases are returned after is_simple test:
```
            if (!polygon_2d.is_simple()) {
                printf("CPP Not simple \n");
                return;
            }
```

The locate method currently is not recognized probably because the input is send from another programming language (rounding errors). But I will test a simple case with hard-coded coordinates.

 ```
               CDT::Locate_type l_t;
                int l_i;
                cdt.locate(pt_2d, l_t, l_i);

                if (l_t == CDT::VERTEX) {
                    printf("CDT::VERTEX \n");

                    return;
                }
```

I consider this issue closed and once again thank you very much for helping me.
