### ISSUE TITLE
[Question] Where do I find ARCAVOID?

### ISSUE THREAD

**Issue by s5bug** [CGAL/cgal#6158]
## Issue Details

The [ARCAVOID paper](https://people.mpi-inf.mpg.de/~akobel/publications/Kobel11-complex-root-finding.pdf) mentions an implementation of ARCAVOID for CGAL. Yet I'm unable to find it.

## Environment

Trying to implement a complex roots finder that plays nice with Scala's Spire's `Real` type, based off of CReal/Exact Real Arithmetic. I've opened a [Math SE Question](https://math.stackexchange.com/questions/4325885/computing-complexcreal-roots-of-a-polynomial) related to what I'm trying to do, but I figure it'd be helpful to ask about ARCAVOID here as well.

**Comment by sloriot** [comment]
I think it has never been integrated. The branch seems to be: https://github.com/CGAL/cgal-public-dev/tree/Arcavoid-akobel

cc @akobel
