### ISSUE TITLE
Windows installation issue: Empty solution

### ISSUE THREAD

**Issue by kyamant** [CGAL/cgal#6163]
Using CGAL-5.3 on Windows 10:
After building, I have a CGAL.sln file in the main installation directory, but it is empty. I have to go to individual `demo` and `example` folders and build them one-by-one.
What is the use of this CGAL.sln, then?
![image](https://user-images.githubusercontent.com/16941640/145355833-0aeba09e-4507-46b0-bf36-32ca941015a5.png)

**Comment by janetournois** [comment]
Hello @kyamant 
you actually don't need to build CGAL, which is header-only.
However you can build your "user code", aka the CGAL provided examples, or your own cpp files.
It is documented [here](https://doc.cgal.org/latest/Manual/windows.html)

**Comment by kyamant** [comment]
@janetournois What is the point of this CGAL.sln solution then?

**Comment by janetournois** [comment]
you don't need CGAL.sln unless you want it to compile the examples and demos.
You can directly compile your chosen package examples, with `CGAL_DIR=/your/cgal/root/directory` in CMake

**Comment by kyamant** [comment]
That is exactly what I what I wan to do, build all the demos and examples and see them from a central place.
How do I do that exactly

**Comment by janetournois** [comment]
then in visual studio, you can build the "examples" and "demos" targets

**Comment by lrineau** [comment]
> That is exactly what I what I wan to do, build all the demos and examples and see them from a central place. How do I do that exactly

In the CMake configuration of the CGAL project, set the variables `WITH_demos` and `WITH_examples` to `ON`.

**Comment by kyamant** [comment]
In the CmakeLists.txt file I see `# Variables used when WITH_{demos|examples|tests} are TRUE`, is this where I set them to true.

**Comment by lrineau** [comment]
> @lrineau In the CmakeLists.txt file I see `# Variables used when WITH_{demos|examples|tests} are TRUE`, is this where I set them to true?

No. Do not modify the `CMakeLists.txt` files from CGAL. The CMake configuration parameters can be modified in the CMake-GUI graphical application, or in the file `CMakeCache.txt` of your build directory. You should read introduction to usage of CMake. For example, start with that page: https://cmake.org/runningcmake/
