### ISSUE TITLE
CGAL::join fail

### ISSUE THREAD

**Issue by huangdade** [CGAL/cgal#6164]
## Issue Details

Runtime error:

CGAL error: precondition violation!
Expression : (m_traits.compare_y_at_x_2_object()(p, cv) == EQUAL) && compare_xy(cv.left(), p) == SMALLER && compare_xy(cv.right(), p) == LARGER
File       : E:\bfbrmt\third-libs\vcpkg\installed\x64-windows\include\CGAL\Arr_segment_traits_2.h
Line       : 610
Explanation:
Refer to the bug-reporting instructions at https://www.cgal.org/bug_report.html

## Source Code

```cpp
#include <CGAL/Simple_cartesian.h>
#include <CGAL/Polygon_2.h>
#include <CGAL/Polygon_with_holes_2.h>
#include <CGAL/Boolean_set_operations_2.h>
typedef CGAL::Simple_cartesian<double> K;
int main()
{
    double scale = 100;
    CGAL::Polygon_2<K> area1;
    area1.push_back(K::Point_2(0 * scale, 0 * scale));
    area1.push_back(K::Point_2(1 * scale, 0 * scale));
    area1.push_back(K::Point_2(1 * scale, 1 * scale));
    area1.push_back(K::Point_2(0 * scale, 1 * scale));
    CGAL::Polygon_2<K> area2;
    area2.push_back(K::Point_2(0.9 * scale, 0.1 * scale));
    area2.push_back(K::Point_2(2 * scale, 0.1 * scale));
    area2.push_back(K::Point_2(2 * scale, 0.8 * scale));
    area2.push_back(K::Point_2(0.9 * scale, 0.9 * scale));
    CGAL::Polygon_with_holes_2<K> area3;
    CGAL::join(area1, area2, area3);
    return 0;
}
```

## Environment

* Windows 10 64
* Visual Studio 2019
* Debug Mode
* CGAL version: 5.3
* Boost version: 1.76.0

**Comment by sloriot** [comment]
You should use a kernel with exact constructions, like `CGAL::Exact_predicates_exact_constructions_kernel`. More details [here](https://www.cgal.org/FAQ.html#inexact_NT)
