### ISSUE TITLE
Convex_decomposition: puzzled about a warning

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#6165]
## Issue Details

In [this testsuite](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.4-I-107/Convex_decomposition_3/TestReport_gimeno_ArchLinux-clang-CXX17-Release.gz) the compiler warns that `M`  is not used. I later see `M *= D;`  so why do we get the warning?  Can it be that the `gcd()`function is called somewhere with a constant as argument and the compiler then knows that there is an early `return`? 

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): archlinux
* Compiler: clang
* Release or debug mode:
* Specific flags used (if any):
* CGAL version:  CGAL-5.4-I-107
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by sloriot** [comment]
M is used in `CGAL_NEF_TRACEV` only so there should be something equivalent to `CGAL_assertion_code()`.

**Comment by lrineau** [comment]
The warning wording is:
> warning: variable 'M' set but not used [-Wunused-but-set-variable]

That variable is set (initialized, and then modified), but its value is never used, hence the warning.

**Comment by afabri** [comment]
In line 94 we have   `if (!first) M*=D;`

**Comment by sloriot** [comment]
I saw it too but the value of the variable is still unused
