### ISSUE TITLE
How could I read PLY point(with color property) and face together?

### ISSUE THREAD

**Issue by xvzezi** [CGAL/cgal#6167]
## Issue Details

I want to read a ply file. First I use read_PLY() function, but it seems that only position and face are read. Then I try read_PLY_with_properties(), but it seems the info of faces is missing. How could I mix these two method? Or I have to read twice to get the vertex info and face info?

## Source Code

int SFS::ReadPLYFile(string filename) {
    // use CGAL to read ply file with color
    std::ifstream ifs(filename);
    std::vector<PC> points;
    if (!ifs) {
        std::cerr<<"Fail to open: "<<filename<<"\n";
        return -1;
    }
    Mesh mesh;
    string comments;
    if (!CGAL::IO::read_PLY(ifs, mesh, comments)) {
        std::cerr<<"Invalid ply file:"<<filename<<"\n";
        return -1;
    }
    ifs.close();
    std::cout<<comments;
    std::cout<<"vertex size:"<<mesh.number_of_vertices()<<"\nface size:"<<mesh.number_of_faces()<<"\n";
    if (mesh.number_of_vertices() > 0) {
        std::cout<<*(mesh.vertices().begin())<<std::endl;
        std::cout<<*(mesh.points().begin())<<std::endl;
    }
    CGAL::draw(mesh);

    return 0;
}

## Environment

* Operating system : Linux x64:
* Compiler:
* Release:
* Specific flags used (if any):
* CGAL 5.3:
* Boost 1.75:
* Eigen 3.7

## my ply file
ply
format ascii 1.0
element vertex 629342
property float x
property float y
property float z
property uchar red
property uchar green
property uchar blue
element face 1256812
property list int int vertex_indices
end_header
-42.1733 13.5629 508.214 249 246 239

**Comment by afabri** [comment]
CGAL 5.4 will offer the function[ `CGAL::IOr::read_PLY()`](https://cgal.geometryfactory.com/CGAL/doc/master/Surface_mesh/group__PkgSurfaceMeshIOFuncPLY.html) for a ply file with properties associated to vertices and faces.  It is already in the master branch. @MaelRL correct me if I am wrong.

**Comment by sloriot** [comment]
It is already in 5.3 (and older versions under a different name).
