### ISSUE TITLE
Parallel Mesh_3 algorithms incompatible with TBB 2021.x versions

### ISSUE THREAD

**Issue by lahwaacz** [CGAL/cgal#6168]
## Issue Details

I'm trying to compile the [mesh_implicit_sphere.cpp](https://doc.cgal.org/latest/Mesh_3/Mesh_3_2mesh_implicit_sphere_8cpp-example.html) example from the [Mesh_3](https://doc.cgal.org/latest/Mesh_3/index.html) package on Arch Linux, which has [TBB 2021.4.0](https://archlinux.org/packages/extra/x86_64/tbb/) where the [parallel_do.h](https://github.com/oneapi-src/oneTBB/issues/416) header was removed. This leads to the following error:

```
$ g++ -std=c++17 mesh_implicit_sphere.cpp -lgmp -lmpfr -DCGAL_CONCURRENT_MESH_3 -DCGAL_LINKED_WITH_TBB -ltbb
In file included from /usr/include/CGAL/Mesh_3/Mesher_3.h:41,
                 from /usr/include/CGAL/refine_mesh_3.h:28,
                 from /usr/include/CGAL/make_mesh_3.h:26,
                 from mesh_implicit_sphere.cpp:6:
/usr/include/CGAL/Mesh_3/Refine_facets_3.h:29:12: fatal error: tbb/parallel_do.h: No such file or directory
   29 |   #include <tbb/parallel_do.h>
      |            ^~~~~~~~~~~~~~~~~~~
compilation terminated.
```

## Environment

* Operating system: Arch Linux (x64)
* Compiler: g++ 11.1.0
* Release or debug mode:
* Specific flags used (if any):
* CGAL version: 5.3
* Boost version: 1.76.0
* Other libraries versions if used (Eigen, TBB, etc.): TBB 2021.4.0

**Comment by mglisse** [comment]
Hello, could you try the master branch on github? I think this was fixed a while ago (#5850), and the fix should be in 5.3.1 and 5.4 when they arrive.

**Comment by lahwaacz** [comment]
Thanks, that seems to work. I'm only getting a deprecation warning that will probably go away in the final release.

**Comment by lrineau** [comment]
> Thanks, that seems to work. I'm only getting a deprecation warning that will probably go away in the final release.

Thanks Jakub. Can you please tell us more about that deprecation warning? I would like to make sure we already have dealt with it.

For the moment, we only test OneAPI TBB (version 2021.4.0 like yours) on Windows, with Visual Studio C++ 2019 and 2022. We have not yet tested on Linux or MacOS.

**Comment by lahwaacz** [comment]
The warning I get when compiling this example is
```
cgal_install/include/CGAL/Default_diagonalize_traits.h:65:59: warning: ‘static bool CGAL::Diagonalize_traits<FT, dim>::diagonalize_selfadjoint_covariance_matrix(const Covariance_matrix&, CGAL::Diagonalize_traits<FT, dim>::Vector&, CGAL::Diagonalize_traits<FT, dim>::Matrix&) [with FT = double; unsigned int dim = 3; CGAL::Diagonalize_traits<FT, dim>::Covariance_matrix = std::array<double, 6>; CGAL::Diagonalize_traits<FT, dim>::Vector = std::array<double, 3>; CGAL::Diagonalize_traits<FT, dim>::Matrix = std::array<double, 9>]’ is deprecated: CGAL::Diagonalize_traits is a deprecated class that can lead to precision issues, please use CGAL::Eigen_diagonalize_traits [-Wdeprecated-declarations]
   65 |     return Base::diagonalize_selfadjoint_covariance_matrix(cov, eigenvalues, eigenvectors);
      |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from cgal_install/include/CGAL/Default_diagonalize_traits.h:17,
                 from cgal_install/include/CGAL/linear_least_squares_fitting_3.h:27,
                 from cgal_install/include/CGAL/Mesh_3/C3T3_helpers.h:27,
                 from cgal_install/include/CGAL/Mesh_3/vertex_perturbation.h:25,
                 from cgal_install/include/CGAL/Mesh_3/Sliver_perturber.h:39,
                 from cgal_install/include/CGAL/perturb_mesh_3.h:26,
                 from cgal_install/include/CGAL/optimize_mesh_3.h:22,
                 from cgal_install/include/CGAL/refine_mesh_3.h:30,
                 from cgal_install/include/CGAL/make_mesh_3.h:26,
                 from mesh_implicit_sphere.cpp:6:
cgal_install/include/CGAL/Diagonalize_traits.h:88:15: note: declared here
   88 |   static bool diagonalize_selfadjoint_covariance_matrix(const Covariance_matrix& mat,
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by sloriot** [comment]
The warning indicates that the Eigen3 dependency is missing (or that `CGAL_EIGEN3_ENABLED` is not defined).

For cmake handling see [here](https://doc.cgal.org/latest/Manual/thirdparty.html#title8)

**Comment by lrineau** [comment]
The warning message says:
> `CGAL::Diagonalize_traits` is a deprecated class that can lead to precision issues, please use `CGAL::Eigen_diagonalize_traits`.

The issue is that your are compiling `mesh_implicit_sphere.cpp` "by hand", with your own compilation command line, instead of using the build system provided by our CMake scripts. [Eigen](https://eigen.tuxfamily.org/) is a mandatory dependency of most of the functions from Mesh_3, because it is needed in the Lloyd mesh optimizer. See [the documentation](https://doc.cgal.org/latest/Mesh_3/group__PkgMesh3Functions.html#gaa3a279f64022f2bc51935f946dd8a50e).

Once [`eigen` from the ArchLinux `Extra` repository](https://archlinux.org/packages/extra/any/eigen/) is installed on your ArchLinux, add `-I /usr/include/eigen3 -DCGAL_EIGEN3_ENABLED` to your compilation command line, and the warning will disappear.

**Comment by lahwaacz** [comment]
Right, thanks. I've gone with the "by hand" approach just to reproduce the original problem, but I'm using CMake in the real project.
