### ISSUE TITLE
Polyhedron demo - bug in "Show cells not in complex" of a C3t3

### ISSUE THREAD

**Issue by janetournois** [CGAL/cgal#6187]
## Issue Details

- Load a C3T3 in the demo, 
- choose "Show cells not in complex"
- hide the C3T3 by clicking the "view" option (red cross vs green check)

The "cells not in complex" remain in the view, though the C3T3 gets hidden as requested.

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): windows
* Compiler: msvc 2022
* CGAL version: master

**Comment by Jay8181** [comment]
I would like to take this issue and  fix this bug : )

**Comment by janetournois** [comment]
@ange-clement can you please have a look at that issue ?
