### ISSUE TITLE
faces_around_face return invalid face_descriptor

### ISSUE THREAD

**Issue by sukamay** [CGAL/cgal#6189]
## Issue Details

unexpected behavior, wrong results,
CGAL::faces_around_face return invalid face_descriptor. I want to iterate the neighbor face of a selected face, so I use faces_around_face. I get the error 
```
"terminate called after throwing an instance of 'CGAL::Assertion_exception'
  what():  CGAL ERROR: assertion violation!
Expr: _idx < data_.size()
File: /home/wim/softwares/CGAL-5.3/include/CGAL/Surface_mesh/Properties.h
Line: 193"
```
I run the program in debug mode and found that the neighbor face_descriptor return by faces_around_face is 4294967295, which is an invalid index. Commonly a face has 3 neighbor face, and each face return the wrong index in 2rd face, 1st and 3nd neighbor face index is correct. Is that my fault in programming or it's a bug?

## Source Code
```
    for (FaceDesc &fd : m_mesh.faces()) {
        size_t count = 0;
        float temp_gradient = 0.0f;
        (std::vector<float>(3, 0.0f)).swap(temp_chroma);
        for (FaceDesc neighbor_fd : CGAL::faces_around_face(m_mesh.halfedge(fd), m_mesh)) {
            temp_gradient += (m_fIntensities[neighbor_fd] - m_fIntensities[fd]);
            temp_chroma[count] = RobustKernel(m_fIntensities[fd] - m_fIntensities[neighbor_fd]);
            count++;
        }
        put(m_fChroma, fd, Vector(temp_chroma[0], temp_chroma[1], temp_chroma[2]));
        m_fGradientIntensities[fd] = temp_gradient / count;
        // m_fGradientIntensities[fd] = temp_gradient;
    }
```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Linux 64 bits
* Compiler:gcc
* Release or debug mode:debug
* Specific flags used (if any):
* CGAL version:5.3
* Boost version:1.7
* Other libraries versions if used (Eigen, TBB, etc.):
* Eigen:3.3

**Comment by sukamay** [comment]
PS: my mesh may be a little big, with millions of faces.
It's one of my ply files header:
ply
format binary_little_endian 1.0
element vertex 632561
property float x
property float y
property float z
property uchar red
property uchar green
property uchar blue
element face 1264470
property list int int vertex_indices
end_header

**Comment by MaelRL** [comment]
You need to check if the face is not `boost::graph_traits<Mesh>::null_face()` before using it : if your face has boundary edges, its `faces_around_face` neighbors will include the null face.

**Comment by Aadit-Nagori** [comment]
Hi, could anyone give a code example of this working as i am trying to get the faces around a face and the iterator is not working. I tried MaeIRL's suggestion and added an if statement to check if the face found is null but apparently every face found by the iterator is null. This is my code.
``
 Face_index start = cave_faces[0];
    for(auto f: CGAL::faces_around_face(sm.halfedge(start), sm)){
        std::cout<<"test"<<std::endl;
        if(f==Mesh::null_face()){
            std::cout<<"invalid"<<std::endl;
            //put(surfacecm, f, CGAL::IO::gray());
        }
        else{
            std::cout<<"valid"<<std::endl;
            put(surfacecm, f, CGAL::IO::blue());
       
``
