### ISSUE TITLE
trailing ;

### ISSUE THREAD

**Issue by ffteja** [CGAL/cgal#6194]
Compiling with GCC 10 and -pedantic option raises an issue here about a trailing ";"

CGAL-5.2.2/include/CGAL/Mesh_triangulation_3.h:157:3: error: extra ';' [-Werror=pedantic]
  157 |   ;

https://github.com/CGAL/cgal/blob/f10214dadd553fe511f0b3853edd7d0ed5e1ea5b/Mesh_3/include/CGAL/Mesh_triangulation_3.h#L157

Seems easy to remove :-)

**Comment by unnumsykar** [comment]
wanted to contribute ! made one PR 
https://github.com/CGAL/cgal/pull/6197

**Comment by lrineau** [comment]
Fixed by https://github.com/CGAL/cgal/pull/6196.
