### ISSUE TITLE
Warning about `\dot` in overnight 5.3.2 build with doxygen master

### ISSUE THREAD

**Issue by albert-github** [CGAL/cgal#6200]
The overnight 5.3.2 build gives the warning for the master build:
```
/home/cgal-testsuite/cgal_doc_build/CGAL-5.3.2-I-189/doc/BGL/PackageDescription.txt:32: warning: ignoring \dot command because HAVE_DOT is not set
```
It looks like the (CGAL) 5.3 overnight build uses the `Documentation/doc/resources/1.8.20/BaseDoxyfile.in` where the `HAVE_DOT` is set to `NO` with the doxygen master build.
(For the overnight (CGAL) `master` build the file `Documentation/doc/resources/1.9.3/BaseDoxyfile.in` where the `HAVE_DOT` is set to `YES` is used.)

**Comment by lrineau** [comment]
Fixed by #6204.
