### ISSUE TITLE
Warnings about settings in CGAL 5.3 build with doxygen master

### ISSUE THREAD

**Issue by albert-github** [CGAL/cgal#6202]
When building the documentation in the CGAL 5.3 branch with the doxygen master version we get for each package the messages:
```
warning: Tag 'LATEX_SOURCE_CODE' at line 1969 of file '.../doc_dxy/BaseDoxyfile' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: Tag 'RTF_SOURCE_CODE' at line 2059 of file '.../doc_dxy/BaseDoxyfile' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: Tag 'DOCBOOK_PROGRAMLISTING' at line 2164 of file '.../doc_dxy/BaseDoxyfile' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: Tag 'CLASS_DIAGRAMS' at line 2351 of file '.../doc_dxy/BaseDoxyfile' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
```

the messages are clear and due to the fact that in the used 1.8.20 `BaseDoxyfile.in` they are still present they are given. Problem can be solved by either creating a 1.9.3 version (like already is done in CGAL master) or to remove the entries and set the new entry `CLASS_GRAPH` to `TEXT`.

The question is
- fix 1.8.20 `BaseDoxyfile.in` 

or

- create new 1.9.3 directory

(Note: #6200 is more or less related as here also a setting has to be changed).

**Comment by lrineau** [comment]
Fixed by #6204.
