### ISSUE TITLE
Mesh reconstruction compilations errors

### ISSUE THREAD

**Issue by CharlesFarhat** [CGAL/cgal#6216]
## Issue Details

When triying to compile the Surface Reconstruction from Point Clouds Example code I have the following errors :+1: 

> FAILED: CMakeFiles/meshBuilder.dir/src/main.cpp.o 
/usr/bin/c++  -I/home/ares/Projects/meshBuilder/ThirdParties/CGAL/include -Wall -O3 -DNDEBUG -std=c++17 -MD -MT CMakeFiles/meshBuilder.dir/src/main.cpp.o -MF CMakeFiles/meshBuilder.dir/src/main.cpp.o.d -o CMakeFiles/meshBuilder.dir/src/main.cpp.o -c /home/ares/Projects/meshBuilder/src/main.cpp
/home/ares/Projects/meshBuilder/src/main.cpp: In function ‘int main(int, char**)’:
/home/ares/Projects/meshBuilder/src/main.cpp:29:39: error: ‘data_file_path’ is not a member of ‘CGAL’
   29 |     std::string fname = argc==1?CGAL::data_file_path("points_3/kitten.xyz") : argv[1];
      |                                       ^~~~~~~~~~~~~~
In file included from /home/ares/Projects/meshBuilder/src/main.cpp:9:
/home/ares/Projects/meshBuilder/ThirdParties/CGAL/include/CGAL/poisson_surface_reconstruction.h: In instantiation of ‘bool CGAL::poisson_surface_reconstruction_delaunay(PointInputIterator, PointInputIterator, PointMap, NormalMap, PolygonMesh&, double, double, double, double, Tag) [with PointInputIterator = __gnu_cxx::__normal_iterator<CGAL::Point_set_3<CGAL::Point_3<CGAL::Epick>, CGAL::Vector_3<CGAL::Epick> >::Index*, std::vector<CGAL::Point_set_3<CGAL::Point_3<CGAL::Epick>, CGAL::Vector_3<CGAL::Epick> >::Index, std::allocator<CGAL::Point_set_3<CGAL::Point_3<CGAL::Epick>, CGAL::Vector_3<CGAL::Epick> >::Index> > >; PointMap = CGAL::Point_set_3<CGAL::Point_3<CGAL::Epick>, CGAL::Vector_3<CGAL::Epick> >::Property_map<CGAL::Point_3<CGAL::Epick> >; NormalMap = CGAL::Point_set_3<CGAL::Point_3<CGAL::Epick>, CGAL::Vector_3<CGAL::Epick> >::Property_map<CGAL::Vector_3<CGAL::Epick> >; PolygonMesh = CGAL::Surface_mesh<CGAL::Point_3<CGAL::Epick> >; Tag = CGAL::Manifold_with_boundary_tag]’:
/home/ares/Projects/meshBuilder/src/main.cpp:79:38:   required from here
/home/ares/Projects/meshBuilder/ThirdParties/CGAL/include/CGAL/poisson_surface_reconstruction.h:105:46: error: no matching function for call to ‘CGAL::Poisson_reconstruction_function<CGAL::Epick>::compute_implicit_function()’
  105 |     if ( ! function.compute_implicit_function() )
      |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
In file included from /home/ares/Projects/meshBuilder/ThirdParties/CGAL/include/CGAL/poisson_surface_reconstruction.h:21,
                 from /home/ares/Projects/meshBuilder/src/main.cpp:9:
/home/ares/Projects/meshBuilder/ThirdParties/CGAL/include/CGAL/Poisson_reconstruction_function.h:417:8: note: candidate: ‘template<class SparseLinearAlgebraTraits_d, class Visitor> bool CGAL::Poisson_reconstruction_function<Gt>::compute_implicit_function(SparseLinearAlgebraTraits_d, Visitor, double, double) [with SparseLinearAlgebraTraits_d = SparseLinearAlgebraTraits_d; Visitor = Visitor; Gt = CGAL::Epick]’
  417 |   bool compute_implicit_function(
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/ares/Projects/meshBuilder/ThirdParties/CGAL/include/CGAL/Poisson_reconstruction_function.h:417:8: note:   template argument deduction/substitution failed:
In file included from /home/ares/Projects/meshBuilder/src/main.cpp:9:
/home/ares/Projects/meshBuilder/ThirdParties/CGAL/include/CGAL/poisson_surface_reconstruction.h:105:46: note:   candidate expects 4 arguments, 0 provided
  105 |     if ( ! function.compute_implicit_function() )
      |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
In file included from /home/ares/Projects/meshBuilder/ThirdParties/CGAL/include/CGAL/poisson_surface_reconstruction.h:21,
                 from /home/ares/Projects/meshBuilder/src/main.cpp:9:
/home/ares/Projects/meshBuilder/ThirdParties/CGAL/include/CGAL/Poisson_reconstruction_function.h:571:8: note: candidate: ‘template<class SparseLinearAlgebraTraits_d> bool CGAL::Poisson_reconstruction_function<Gt>::compute_implicit_function(SparseLinearAlgebraTraits_d, bool) [with SparseLinearAlgebraTraits_d = SparseLinearAlgebraTraits_d; Gt = CGAL::Epick]’
  571 |   bool compute_implicit_function(SparseLinearAlgebraTraits_d solver, bool smoother_hole_filling = false)
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/ares/Projects/meshBuilder/ThirdParties/CGAL/include/CGAL/Poisson_reconstruction_function.h:571:8: note:   template argument deduction/substitution failed:
In file included from /home/ares/Projects/meshBuilder/src/main.cpp:9:
/home/ares/Projects/meshBuilder/ThirdParties/CGAL/include/CGAL/poisson_surface_reconstruction.h:105:46: note:   candidate expects 2 arguments, 0 provided
  105 |     if ( ! function.compute_implicit_function() )
      |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
In file included from /home/ares/Projects/meshBuilder/ThirdParties/CGAL/include/CGAL/jet_smooth_point_set.h:23,
                 from /home/ares/Projects/meshBuilder/src/main.cpp:6:
/home/ares/Projects/meshBuilder/ThirdParties/CGAL/include/CGAL/Monge_via_jet_fitting.h: In instantiation of ‘CGAL::Monge_via_jet_fitting<DataKernel, LocalKernel, SvdTraits>::Monge_form CGAL::Monge_via_jet_fitting<DataKernel, LocalKernel, SvdTraits>::operator()(InputIterator, InputIterator, size_t, size_t) [with InputIterator = __gnu_cxx::__normal_iterator<CGAL::Point_3<CGAL::Epick>*, std::vector<CGAL::Point_3<CGAL::Epick>, std::allocator<CGAL::Point_3<CGAL::Epick> > > >; DataKernel = CGAL::Epick; LocalKernel = CGAL::Simple_cartesian<double>; SvdTraits = CGAL::GetSvdTraits<CGAL::Named_function_parameters<CGAL::Epick, CGAL::internal_np::geom_traits_t, CGAL::Named_function_parameters<CGAL::Point_set_3<CGAL::Point_3<CGAL::Epick>, CGAL::Vector_3<CGAL::Epick> >::Property_map<CGAL::Vector_3<CGAL::Epick> >, CGAL::internal_np::normal_t, CGAL::Named_function_parameters<CGAL::Point_set_3<CGAL::Point_3<CGAL::Epick>, CGAL::Vector_3<CGAL::Epick> >::Property_map<CGAL::Point_3<CGAL::Epick> >, CGAL::internal_np::point_t, CGAL::internal_np::No_property> > > >::DummySvdTraits; size_t = long unsigned int]’:
/home/ares/Projects/meshBuilder/ThirdParties/CGAL/include/CGAL/jet_smooth_point_set.h:85:36:   required from ‘typename NeighborQuery::Kernel::Point_3 CGAL::internal::jet_smooth_point(const typename NeighborQuery::Kernel::Point_3&, NeighborQuery&, unsigned int, typename NeighborQuery::Kernel::FT, unsigned int, unsigned int) [with SvdTraits = CGAL::GetSvdTraits<CGAL::Named_function_parameters<CGAL::Epick, CGAL::internal_np::geom_traits_t, CGAL::Named_function_parameters<CGAL::Point_set_3<CGAL::Point_3<CGAL::Epick>, CGAL::Vector_3<CGAL::Epick> >::Property_map<CGAL::Vector_3<CGAL::Epick> >, CGAL::internal_np::normal_t, CGAL::Named_function_parameters<CGAL::Point_set_3<CGAL::Point_3<CGAL::Epick>, CGAL::Vector_3<CGAL::Epick> >::Property_map<CGAL::Point_3<CGAL::Epick> >, CGAL::internal_np::point_t, CGAL::internal_np::No_property> > > >::DummySvdTraits; NeighborQuery = CGAL::Point_set_processing_3::internal::Neighbor_query<CGAL::Epick, CGAL::Point_set_3<CGAL::Point_3<CGAL::Epick>, CGAL::Vector_3<CGAL::Epick> >&, CGAL::Point_set_3<CGAL::Point_3<CGAL::Epick>, CGAL::Vector_3<CGAL::Epick> >::Property_map<CGAL::Point_3<CGAL::Epick> > >; typename NeighborQuery::Kernel::Point_3 = CGAL::Point_3<CGAL::Epick>; typename NeighborQuery::Kernel::FT = double]’
/home/ares/Projects/meshBuilder/ThirdParties/CGAL/include/CGAL/jet_smooth_point_set.h:251:10:   required from ‘void CGAL::jet_smooth_point_set(PointRange&, unsigned int, const NamedParameters&) [with ConcurrencyTag = CGAL::Sequential_tag; PointRange = CGAL::Point_set_3<CGAL::Point_3<CGAL::Epick>, CGAL::Vector_3<CGAL::Epick> >; NamedParameters = CGAL::Named_function_parameters<CGAL::Epick, CGAL::internal_np::geom_traits_t, CGAL::Named_function_parameters<CGAL::Point_set_3<CGAL::Point_3<CGAL::Epick>, CGAL::Vector_3<CGAL::Epick> >::Property_map<CGAL::Vector_3<CGAL::Epick> >, CGAL::internal_np::normal_t, CGAL::Named_function_parameters<CGAL::Point_set_3<CGAL::Point_3<CGAL::Epick>, CGAL::Vector_3<CGAL::Epick> >::Property_map<CGAL::Point_3<CGAL::Epick> >, CGAL::internal_np::point_t, CGAL::internal_np::No_property> > >]’
/home/ares/Projects/meshBuilder/ThirdParties/CGAL/include/CGAL/jet_smooth_point_set.h:285:5:   required from ‘void CGAL::jet_smooth_point_set(PointRange&, unsigned int) [with ConcurrencyTag = CGAL::Sequential_tag; PointRange = CGAL::Point_set_3<CGAL::Point_3<CGAL::Epick>, CGAL::Vector_3<CGAL::Epick> >]’
/home/ares/Projects/meshBuilder/src/main.cpp:64:65:   required from here
/home/ares/Projects/meshBuilder/ThirdParties/CGAL/include/CGAL/Monge_via_jet_fitting.h:303:12: error: expression list treated as compound expression in initializer [-fpermissive]
  303 |   LAMatrix M(nb_input_pts, nb_d_jet_coeff);
      |            ^
/home/ares/Projects/meshBuilder/ThirdParties/CGAL/include/CGAL/Monge_via_jet_fitting.h:303:14: warning: left operand of comma operator has no effect [-Wunused-value]
  303 |   LAMatrix M(nb_input_pts, nb_d_jet_coeff);
      |              ^~~~~~~~~~~~
/home/ares/Projects/meshBuilder/ThirdParties/CGAL/include/CGAL/Monge_via_jet_fitting.h:309:25: error: request for member ‘vector’ in ‘Z’, which is of non-class type ‘CGAL::Monge_via_jet_fitting<CGAL::Epick, CGAL::Simple_cartesian<double>, CGAL::GetSvdTraits<CGAL::Named_function_parameters<CGAL::Epick, CGAL::internal_np::geom_traits_t, CGAL::Named_function_parameters<CGAL::Point_set_3<CGAL::Point_3<CGAL::Epick>, CGAL::Vector_3<CGAL::Epick> >::Property_map<CGAL::Vector_3<CGAL::Epick> >, CGAL::internal_np::normal_t, CGAL::Named_function_parameters<CGAL::Point_set_3<CGAL::Point_3<CGAL::Epick>, CGAL::Vector_3<CGAL::Epick> >::Property_map<CGAL::Point_3<CGAL::Epick> >, CGAL::internal_np::point_t, CGAL::internal_np::No_property> > > >::DummySvdTraits>::LAVector’ {aka ‘int’}
  309 |   compute_Monge_basis(Z.vector(), monge_form);
      |                       ~~^~~~~~
/home/ares/Projects/meshBuilder/ThirdParties/CGAL/include/CGAL/Monge_via_jet_fitting.h:310:50: error: request for member ‘vector’ in ‘Z’, which is of non-class type ‘CGAL::Monge_via_jet_fitting<CGAL::Epick, CGAL::Simple_cartesian<double>, CGAL::GetSvdTraits<CGAL::Named_function_parameters<CGAL::Epick, CGAL::internal_np::geom_traits_t, CGAL::Named_function_parameters<CGAL::Point_set_3<CGAL::Point_3<CGAL::Epick>, CGAL::Vector_3<CGAL::Epick> >::Property_map<CGAL::Vector_3<CGAL::Epick> >, CGAL::internal_np::normal_t, CGAL::Named_function_parameters<CGAL::Point_set_3<CGAL::Point_3<CGAL::Epick>, CGAL::Vector_3<CGAL::Epick> >::Property_map<CGAL::Point_3<CGAL::Epick> >, CGAL::internal_np::point_t, CGAL::internal_np::No_property> > > >::DummySvdTraits>::LAVector’ {aka ‘int’}
  310 |   if ( dprime >= 3) compute_Monge_coefficients(Z.vector(), dprime, monge_form);
      |                                                ~~^~~~~~
/home/ares/Projects/meshBuilder/ThirdParties/CGAL/include/CGAL/Monge_via_jet_fitting.h: In instantiation of ‘CGAL::Monge_via_jet_fitting<DataKernel, LocalKernel, SvdTraits>::Monge_form CGAL::Monge_via_jet_fitting<DataKernel, LocalKernel, SvdTraits>::operator()(InputIterator, InputIterator, size_t, size_t) [with InputIterator = __gnu_cxx::__normal_iterator<CGAL::Point_3<CGAL::Epick>*, std::vector<CGAL::Point_3<CGAL::Epick>, std::allocator<CGAL::Point_3<CGAL::Epick> > > >; DataKernel = CGAL::Epick; LocalKernel = CGAL::Simple_cartesian<double>; SvdTraits = CGAL::GetSvdTraits<CGAL::Named_function_parameters<unsigned int, CGAL::internal_np::degree_monge_t, CGAL::Named_function_parameters<unsigned int, CGAL::internal_np::degree_fitting_t, CGAL::internal_np::No_property> > >::DummySvdTraits; size_t = long unsigned int]’:
/home/ares/Projects/meshBuilder/ThirdParties/CGAL/include/CGAL/jet_smooth_point_set.h:85:36:   required from ‘typename NeighborQuery::Kernel::Point_3 CGAL::internal::jet_smooth_point(const typename NeighborQuery::Kernel::Point_3&, NeighborQuery&, unsigned int, typename NeighborQuery::Kernel::FT, unsigned int, unsigned int) [with SvdTraits = CGAL::GetSvdTraits<CGAL::Named_function_parameters<unsigned int, CGAL::internal_np::degree_monge_t, CGAL::Named_function_parameters<unsigned int, CGAL::internal_np::degree_fitting_t, CGAL::internal_np::No_property> > >::DummySvdTraits; NeighborQuery = CGAL::Point_set_processing_3::internal::Neighbor_query<CGAL::Epick, CGAL::Iterator_range<__gnu_cxx::__normal_iterator<CGAL::Point_3<CGAL::Epick>*, std::vector<CGAL::Point_3<CGAL::Epick>, std::allocator<CGAL::Point_3<CGAL::Epick> > > > >&, CGAL::Identity_property_map<CGAL::Point_3<CGAL::Epick> > >; typename NeighborQuery::Kernel::Point_3 = CGAL::Point_3<CGAL::Epick>; typename NeighborQuery::Kernel::FT = double]’
/home/ares/Projects/meshBuilder/ThirdParties/CGAL/include/CGAL/jet_smooth_point_set.h:251:10:   required from ‘void CGAL::jet_smooth_point_set(PointRange&, unsigned int, const NamedParameters&) [with ConcurrencyTag = CGAL::Sequential_tag; PointRange = CGAL::Iterator_range<__gnu_cxx::__normal_iterator<CGAL::Point_3<CGAL::Epick>*, std::vector<CGAL::Point_3<CGAL::Epick>, std::allocator<CGAL::Point_3<CGAL::Epick> > > > >; NamedParameters = CGAL::Named_function_parameters<unsigned int, CGAL::internal_np::degree_monge_t, CGAL::Named_function_parameters<unsigned int, CGAL::internal_np::degree_fitting_t, CGAL::internal_np::No_property> >]’
/home/ares/Projects/meshBuilder/ThirdParties/CGAL/include/CGAL/Scale_space_reconstruction_3/Jet_smoother.h:83:5:   required from ‘void CGAL::Scale_space_reconstruction_3::Jet_smoother<Geom_traits, ConcurrencyTag>::operator()(InputIterator, InputIterator) [with InputIterator = __gnu_cxx::__normal_iterator<CGAL::Point_3<CGAL::Epick>*, std::vector<CGAL::Point_3<CGAL::Epick>, std::allocator<CGAL::Point_3<CGAL::Epick> > > >; Geom_traits = CGAL::Epick; ConcurrencyTag = CGAL::Sequential_tag]’
/home/ares/Projects/meshBuilder/ThirdParties/CGAL/include/CGAL/Scale_space_surface_reconstruction_3.h:180:39:   required from ‘void CGAL::Scale_space_surface_reconstruction_3<Geom_traits>::increase_scale(std::size_t, const Smoother&) [with Smoother = CGAL::Scale_space_reconstruction_3::Jet_smoother<CGAL::Epick>; Geom_traits = CGAL::Epick; std::size_t = long unsigned int]’
/home/ares/Projects/meshBuilder/src/main.cpp:110:98:   required from here
/home/ares/Projects/meshBuilder/ThirdParties/CGAL/include/CGAL/Monge_via_jet_fitting.h:303:12: error: expression list treated as compound expression in initializer [-fpermissive]
  303 |   LAMatrix M(nb_input_pts, nb_d_jet_coeff);
      |            ^
/home/ares/Projects/meshBuilder/ThirdParties/CGAL/include/CGAL/Monge_via_jet_fitting.h:303:14: warning: left operand of comma operator has no effect [-Wunused-value]
  303 |   LAMatrix M(nb_input_pts, nb_d_jet_coeff);
      |              ^~~~~~~~~~~~
/home/ares/Projects/meshBuilder/ThirdParties/CGAL/include/CGAL/Monge_via_jet_fitting.h:309:25: error: request for member ‘vector’ in ‘Z’, which is of non-class type ‘CGAL::Monge_via_jet_fitting<CGAL::Epick, CGAL::Simple_cartesian<double>, CGAL::GetSvdTraits<CGAL::Named_function_parameters<unsigned int, CGAL::internal_np::degree_monge_t, CGAL::Named_function_parameters<unsigned int, CGAL::internal_np::degree_fitting_t, CGAL::internal_np::No_property> > >::DummySvdTraits>::LAVector’ {aka ‘int’}
  309 |   compute_Monge_basis(Z.vector(), monge_form);
      |                       ~~^~~~~~
/home/ares/Projects/meshBuilder/ThirdParties/CGAL/include/CGAL/Monge_via_jet_fitting.h:310:50: error: request for member ‘vector’ in ‘Z’, which is of non-class type ‘CGAL::Monge_via_jet_fitting<CGAL::Epick, CGAL::Simple_cartesian<double>, CGAL::GetSvdTraits<CGAL::Named_function_parameters<unsigned int, CGAL::internal_np::degree_monge_t, CGAL::Named_function_parameters<unsigned int, CGAL::internal_np::degree_fitting_t, CGAL::internal_np::No_property> > >::DummySvdTraits>::LAVector’ {aka ‘int’}
  310 |   if ( dprime >= 3) compute_Monge_coefficients(Z.vector(), dprime, monge_form);
      |                                                ~~^~~~~~
ninja: build stopped: subcommand failed.

## Environment

* Operating system (Linux, 64 bits):
* Compiler: G++ 10.3
* Release or debug mode: Released
* Specific flags used (if any): 
* CGAL version: 5.3
* Boost version: 1.74
* Other libraries versions if used (Eigen, TBB, etc.): Eigen, GMP and MPFR

**Comment by sloriot** [comment]
The first error is that you are using an example from CGAL 5.4 with an earlier release as `CGAL::data_file_path()` has been introduced with that release. Then I suspect you do no use the cmake macro to activate Eigen as defaut solver
```
find_package(Eigen3 3.1.0)
include(CGAL_Eigen3_support)
if(TARGET CGAL::Eigen3_support)
  # Executables that require Eigen 3
  create_single_source_cgal_program("poisson_reconstruction_example.cpp")
  target_link_libraries(poisson_reconstruction_example
                        PUBLIC CGAL::Eigen3_support)
endif()
```
You can also simply add `#define CGAL_EIGEN3_ENABLED` before including any CGAL header.
. script asking for

**Comment by CharlesFarhat** [comment]
Sorry for the late reply, thanks for the answer !
I was very keen to use CGAL as header only lib and without any OS specific lib linking. So I found that the following config is working properly : 

`SET(CGAL_DIR "${PROJECT_SOURCE_DIR}/ThirdParties/CGAL")

#flags
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED OFF)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_CXX_FLAGS "-Wall")
#set(CMAKE_CXX_FLAGS " -march=native -Wno-duplicate-decl-specifier -Wno-ignored-qualifiers -Wno-reorder -pthread -frounding-math")

# Versions
set(VERSION_MAJOR 0)
set(VERSION_MINOR 1)
set(VERSION_PATCH 1)

#Packages used :
# CGAL
#find_package(CGAL REQUIRED)
#include(${CGAL_USE_FILE})

FIND_PACKAGE(Eigen3 REQUIRED)
if (EIGEN3_FOUND)
    include( ${EIGEN3_USE_FILE} )
endif()
find_package(GMP REQUIRED)
FIND_PACKAGE(MPFR REQUIRED)
FIND_PACKAGE(Boost REQUIRED)


INCLUDE_DIRECTORIES(
        ${Boost_INCLUDE_DIRS}
        ${PROJECT_SOURCE_DIR}/ThirdParties/CGAL/include
)

LIST(APPEND LINK_LIBS_EXTERNAL
        ${Boost_LIBRARIES}
        ${GMP_LIBRARIES}
        ${MPFR_LIBRARIES}
        )

add_executable(meshBuilder src/main.cpp)
TARGET_LINK_LIBRARIES(meshBuilder ${LINK_LIBS_EXTERNAL})`
