### ISSUE TITLE
Arrangement_2：report “The two halfedges must share the same incident face.” when use insert_at_vertices

### ISSUE THREAD

**Issue by DoMoCo** [CGAL/cgal#6226]
What wrong with me? Anyone help.

source code:
```
end_vit = getArrowPoint(growth_lines_[id].related_hits.back(), growth_lines_[id].origin);
insert_s = Segment_2(end_vit->point(), collision_vit->point());
h = arr_.insert_at_vertices(insert_s, collision_vit, end_vit);
```

Both endpoints already exist and the insert operation will connects two disconnected components.

![Capture](https://user-images.githubusercontent.com/22541710/148581273-c6aac000-8567-4fc6-88dc-63eebb5660ec.JPG)
This happens again when I connect red vertex and blue vertex.

**Comment by efifogel** [comment]
Make sure that the new segment does not intersect an existing one.
   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by DoMoCo** [comment]
Thank you for your help.

But it does not intersect any existing edge here，see the image. And I know if this happen，I will get “The inserted curve should not intersect the existing arrangement.”，that's not this case

**Comment by efifogel** [comment]
What image?
   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by efifogel** [comment]
oh, the email doesn't include it, but I can see ii in the issues.
ok, please upload a complete program and the data that can be used to
reproduce the problem.
   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by DoMoCo** [comment]
I solved my problem when prepare source code，it is a stupid mistake.

Anyway, thank you very very much, this problem has been bothering me many weeks while there is little related information online.

____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by afabri** [comment]
What "related information" could potentially have helped. Did you oversee something in the documentation? Is it not well documented?
