### ISSUE TITLE
CMAKE Error during configuration of provided Examples

### ISSUE THREAD

**Issue by daihengming** [CGAL/cgal#6229]
## Issue Details

I've installed CGAL 5.3 by using vcpkg follow the instructions of 
[https://doc.cgal.org/latest/Manual/windows.html](url)

and trying to compiling the example of Polygonal_surface_reconstruction
[https://github.com/CGAL/cgal/releases/tag/v5.3.1](url) 

Additional dependencies  has been set correctly,  but during the configuration process i got

``

CMake Warning (dev) at C:/dev/vcpkg-master/installed/x64-windows/share/cgal/CGAL_add_test.cmake:288 (if):
  Policy CMP0064 is not set: Support new TEST if() operator.  Run "cmake
  --help-policy CMP0064" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  TEST will be interpreted as an operator when the policy is set to NEW.
  Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
  C:/dev/vcpkg-master/installed/x64-windows/share/cgal/CGAL_CreateSingleSourceCGALProgram.cmake:63 (cgal_add_test)
  CMakeLists.txt:57 (create_single_source_cgal_program)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at C:/dev/vcpkg-master/installed/x64-windows/share/cgal/CGAL_add_test.cmake:288 (if):
  if given arguments:

    "cgal_add_test_NO_EXECUTION" "OR" "TEST" "execution___of__polyfit_example_without_input_planes"

  Unknown arguments specified
Call Stack (most recent call first):
  C:/dev/vcpkg-master/installed/x64-windows/share/cgal/CGAL_CreateSingleSourceCGALProgram.cmake:63 (cgal_add_test)
  CMakeLists.txt:57 (create_single_source_cgal_program)

``

 

## Environment

* Operating system (Windows 64 bits)
* CGAL version: 5.3
* Boost version: 1.77.0 
* Other libraries versions if used (Eigen 3.4,  SCIP 8.0)
* CMAKE: 3.20

## Corretated Issue
[https://github.com/CGAL/cgal/issues/5857](url)
i've found a similar issue, and tried to explicitly set the cmake policy to NEW with 
`cmake_policy(SET CMP0064 NEW)` in the CMakeLists.txt in the example.
But the error is till coming out.

**Comment by lrineau** [comment]
Please update `cgal` using vcpkg. The port `cgal` from vcpkg has been updated to version 5.3.1, by https://github.com/microsoft/vcpkg/pull/22235, merged December 31th 2021. CGAL version 5.3.1 includes the fix from PR https://github.com/CGAL/cgal/pull/5859.
