### ISSUE TITLE
Costa surface: another failure of the Poisson reconstruction

### ISSUE THREAD

**Issue by stla** [CGAL/cgal#6231]
Hello,

  Here is the Costa surface:

![CostaNice](https://user-images.githubusercontent.com/4466543/148784391-4b81e78b-1eaa-4ff5-9838-99dd4109df82.gif)

Here is a points cloud of this surface:

![CostaCloud](https://user-images.githubusercontent.com/4466543/148784514-72547712-3f65-4576-977e-6b660f4db715.png)

And here is what I get when I run the Poisson reconstruction:

![CostaMesh](https://user-images.githubusercontent.com/4466543/148784643-f6ec21c7-e388-41a8-86c3-74cddc003871.png)

If you want to try:

[CostaSurfaceWithNormals.txt](https://github.com/CGAL/cgal/files/7839603/CostaSurfaceWithNormals.txt)

**Comment by afabri** [comment]
Poisson surface reconstruction is not made for surfaces with boundaries.

**Comment by stla** [comment]
Ok, thanks. You mean it is made for "volumes"? (closed surfaces)

**Comment by afabri** [comment]
yes,

**Comment by afabri** [comment]
The thing is that it has to separate an inside from an outside.
