### ISSUE TITLE
NewKernel_d  in VC testsuite

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#6245]
## Issue Details

We get a [compilation error](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.4-Ic-141/NewKernel_d/TestReport_Sosno_MSVC-2022-Preview-Release.gz) for eigen-3.3.7 with VC++ and `/std::c++latest`.    If we keep _latest_ we have to upgrade to Eigen 3.3.9  on _sosno_

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): 
* Compiler: VC 2022   but  I guess it is more the language option which reveals a problem in Eigen.
* Release or debug mode:
* Specific flags used (if any):  `/std::c++latest`
* CGAL version:  master

**Comment by janetournois** [comment]
All windows testsuites have been migrated to Christo, that uses Eigen 3.4, so we can close this issue
