### ISSUE TITLE
Correct argument for Mesh_criteria

### ISSUE THREAD

**Issue by Franzsardoma** [CGAL/cgal#6249]
Hi, I would like to ask about Mesh_Criteria for to input for make_mesh_3. According to given example: 

https://github.com/CGAL/cgal/blob/ad08f020b671295e95807ccc7cfc787236beb03b/Mesh_3/examples/Mesh_3/mesh_polyhedral_domain_with_features.cpp

```
  Mesh_criteria criteria(edge_size = 0.025,
                         facet_angle = 25, facet_size = 0.05, facet_distance = 0.005,
                         cell_radius_edge_ratio = 3, cell_size = 0.05);
```

Is there a way for those parameters to adjust according to size of the polyhedron body? It is like making the size of triangles dynamically based on the size of whole geometry

Thanks

**Comment by sloriot** [comment]
What do you mean by size of the body? Something related to the length of the diagonal of the bbox for example?

**Comment by Franzsardoma** [comment]
> What do you mean by size of the body? Something related to the length of the diagonal of the bbox for example?

Yes, if it is possible that the size of mesh faces is not hard coded. So for larger geometry, the mesh is most likely to be larger too

**Comment by MaelRL** [comment]
You could define a value based on your domain and then pass it like
```
CGAL::Bbox_3 bb = Polygon_mesh_processing::bbox(input_mesh);
double my_distance_threshold = ... // compute the min distance of the bbox or something else
double my_size_threshold = ... // compute the min distance of the bbox or something else

  Mesh_criteria criteria(edge_size = 0.025,
			                         facet_angle = 30, 
    								 facet_size = my_size_threshold,
                                     facet_distance = my_distance_threshold,
			                         cell_radius_edge_ratio = 3,
                                     cell_size = my_size_threshold);
```

You can also use a function instead of a fixed value for these parameters, see [this example](https://github.com/CGAL/cgal/blob/master/Mesh_3/examples/Mesh_3/mesh_implicit_sphere_variable_size.cpp).
