### ISSUE TITLE
Report a bug to boost (warning) and to gcc (ICE)

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#6262]
## Issue Details

In the [Mesh_3 testsuite](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.5-Ic-3/Mesh_3/TestReport_lrineau_Ubuntu-GCC_master_CXX20-Release.gz) with the boost master and the latest gcc we produce an ICE following a unused parameter warning concerning a boost header file.

We could check if it passes when we locally fix the unused parameter and report this back to boost.org.
We could check if other compilers have the same problem with the HEAD of boost (low prabability as it is an ICE).
In case it is the HEAD of gcc and not a release we could file a bug report to the gcc developers (@mglisse ?) .

**Comment by mglisse** [comment]
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=104184
