### ISSUE TITLE
Windows 10: Setting the rounding mode influences output of double 

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#6272]
## Issue Details

In the Polynomial [testsuite ](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.5-Ic-5/Polynomial/TestReport_Sosno_MSVC-2019-Community-Release.gz )for some versions of `VC++` we get an assertion that `3 != 3.0000000000001`

I boiled that down to this [gist](https://gist.github.com/afabri/db27a95b2818f63889e6a928d30f6c2e)

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):  Windows
* Compiler:  VC 2017 and 2019 
* CGAL version:  afabri/Polynomial-precision-GF  because otherwise we get another assert earlier

**Comment by sloriot** [comment]
I don't observe that behavior on my GNU linux with both gcc and clang. Could it come from the extended precision?

**Comment by lrineau** [comment]
I think that is a known bug Jane and I worked on. Jane, do you still have the reference?
(@janetournois)

**Comment by janetournois** [comment]
Yes. According to the developer community of Visual Studio, it has been fixed. See [here](https://developercommunity2.visualstudio.com/t/Under-FE_UPWARD-printf%E2%80%9C1fn%E2%80%9D-00-pr/1508709?entry=problem&ref=native&refTime=1629984606777&refUserId=42a6ec12-4108-4941-bec4-64403a039c72&viewtype=all)

I am looking for the issue

**Comment by afabri** [comment]
It may sound that I want to work around a compiler bug, but does anybody in @CGAL/developers know where the `Modular_arithmetic` test needs a wrong rounding mode?   And if so must that be [set at top level](https://github.com/CGAL/cgal/blob/master/Polynomial/test/Polynomial/Polynomial_using_core.cpp#L8)?  And do all test cases of Polynomial test modular arithmetic?

**Comment by afabri** [comment]
The following works
```

**Comment by sloriot** [comment]
Successfully tested in CGAL-5.5-Ic-10 (Error is gone)
