### ISSUE TITLE
Triangulation_2:  move triangulation_print_off.h into official IO headers

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#6278]
## Issue Details

Do we still need the file [`triangulation_print_OFF.h`](https://github.com/CGAL/cgal/blob/master/Triangulation_2/examples/Triangulation_2/triangulation_print_OFF.h) in an example directory?

**Comment by lrineau** [comment]
Yes, it is used in `Triangulation_2/examples/Triangulation_2/terr_trian.cpp`
https://github.com/CGAL/cgal/blob/a5a5a432050a0d676e56fe14c638f51881c4273c/Triangulation_2/examples/Triangulation_2/terr_trian.cpp#L18-L18

Shall we close the issue or do you want to move that header file somewhere else?

**Comment by afabri** [comment]
My question was in fact not very clear. I was wondering if the code is redundant with something in Stream Support and assigned it to Mael because he had worked on IO recently.    If not redundant the next question is if the example code should not become official code.

**Comment by sloriot** [comment]
In theory, it could be considered as a FaceGraph so updating the example and testing it is the way to go.
