### ISSUE TITLE
Assertion error in Voronoi diagram manipulation

### ISSUE THREAD

**Issue by r-barnes** [CGAL/cgal#6307]
## Issue Details

I generate a Voronoi diagram from a multipolygon and then attempt to see if vertices from the diagram are enclosed in the multipolygon. The following assertion failure results. There's no explanatory message here, so I'm not sure what I've done wrong, if anything.
```
CGAL error: assertion violation!
Expression : cv1.is_vertical() ? m_traits.is_in_y_range_2_object()(cv1, *ip) : m_traits.is_in_x_range_2_object()(cv1, *ip)
File       : /usr/include/CGAL/Arr_segment_traits_2.h
Line       : 730
Explanation: 
Refer to the bug-reporting instructions at https://www.cgal.org/bug_report.html
terminate called after throwing an instance of 'CGAL::Assertion_exception'
  what():  CGAL ERROR: assertion violation!
Expr: cv1.is_vertical() ? m_traits.is_in_y_range_2_object()(cv1, *ip) : m_traits.is_in_x_range_2_object()(cv1, *ip)
File: /usr/include/CGAL/Arr_segment_traits_2.h
Line: 730
Aborted (core dumped)
```
The full backtrace is available [here](https://gist.github.com/r-barnes/6650a542bc6922545cb2b87d36d28497).

The assertion seems to be ultimately triggered by Line 105:
```
return inside(CGAL::oriented_side(vh->point(), poly));
```

## Source Code

The assertion can be triggered with the code and compilation string provided [here](https://gist.github.com/r-barnes/002406efb164888b8e112824490c028f).

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Linux
* Compiler: Assertion triggers for clang 12.0.0 and gcc 10.3.0
* Release or debug mode: ??
* Specific flags used (if any): `-DBOOST_ALL_NO_LIB -DCGAL_USE_GMPXX=1 -g -Wall -Wextra -pedantic -march=native -frounding-math -lgmpxx -lmpfr -lgmp`
* CGAL version: Present on 5.2, 5.3, 5.4, and 5.5-dev
* Boost version: 1.74
* Other libraries versions if used (Eigen, TBB, etc.): N/A, I think

**Comment by sloriot** [comment]
What Kernel are you using? If it is not already the case, try with `CGAL::Exact_predicates_exact_constructions_kernel`.

**Comment by r-barnes** [comment]
@sloriot : That did indeed fix the situation, thanks! My apologies for missing such an easy and, retrospectively, obvious fix.

I believe I'd tried exact constructions previously and found it painfully slow, but I guess that's just what needs to happen here.
