### ISSUE TITLE
source codes about progressive mesh compression

### ISSUE THREAD

**Issue by Seven377** [CGAL/cgal#631]
I am studying the progressive mesh compression algorithms. But , I can't find corresponding source codes, can you help me?
I have read the paper- progressive compression for lossless transmission of triangle meshes, I want to compare my algorithms with this algorithm, however, I can't find corresponding source. What should I do?

**Comment by sloriot** [comment]
You should contact the author of the paper you're referring to. There is no CGAL package dedicated to that.
