### ISSUE TITLE
cgal failed to run tests with MSVC on windows

### ISSUE THREAD

**Issue by YangYang129** [CGAL/cgal#6320]
cgal failed to run tests with MSVC on windows. It can reproduces on version https://github.com/CGAL/cgal/commit/5118f5f0234d132d96d3fa1c726fd8d1458ccea9. Could you please help look at this issue? Thank you very much
**Environment:**
Compiler version: VS2019 (16.11.10)
Operating system: Windows server 2019

**Steps to reproduce:**
1. open VS2019 x64 tools command
2. git clone https://github.com/CGAL/cgal F:\gitP\CGAL/cgal
3. cd F:\gitP\microsoft\vcpkg
4. bootstrap-vcpkg.bat
5. vcpkg.exe install --recurse yasm-tool  GMP MPFR Eigen3 --triplet x64-windows --clean-after-build
6. cd F:\gitP\CGAL/cgal & mkdir build_amd64 & cd build_amd64
7. set PATH=F:\tools\qt5\qt\5_15_2\msvc2019_64\bin;%PATH%
8. cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=ON  -DCMAKE_TOOLCHAIN_FILE="F:\gitP\microsoft\vcpkg\scripts\buildsystems\vcpkg.cmake" -DVCPKG_TARGET_TRIPLET=x64-windows -DWITH_demos=ON -DWITH_examples=ON -DBOOST_LIBRARYDIR="F:\tools\boost_1_67_0\x64\lib64-msvc-14.1" -DBOOST_INCLUDEDIR="F:\tools\boost_1_67_0\x64" ..
9. msbuild /m /p:Platform=x64 /p:Configuration=Release CGAL.sln /t:Rebuild
10. ctest --build-config Release --output-on-failure

**Test log:**
[ctest.log](https://github.com/CGAL/cgal/files/8065424/ctest.log)

**Error info:**
The following tests FAILED:
	286 - execution___of__example_classification (Exit code 0xc0000135
)
	289 - execution___of__example_ethz_random_forest (Exit code 0xc0000135
)
	290 - execution___of__example_feature (Exit code 0xc0000135
)
	291 - execution___of__example_generation_and_training (Exit code 0xc0000135
)
	292 - execution___of__example_mesh_classification (Exit code 0xc0000135
)
	293 - execution___of__example_cluster_classification (Exit code 0xc0000135
)
	294 - execution___of__gis_tutorial_example (Exit code 0xc0000135
)
	295 - execution___of__example_deprecated_conversion (Exit code 0xc0000135
)

**Comment by lrineau** [comment]
> The following tests FAILED:
> 286 - execution___of__example_classification (Exit code 0xc0000135)
> 289 - execution___of__example_ethz_random_forest (Exit code 0xc0000135)
> 290 - execution___of__example_feature (Exit code 0xc0000135)
> 291 - execution___of__example_generation_and_training (Exit code 0xc0000135)
> 292 - execution___of__example_mesh_classification (Exit code 0xc0000135)
> 293 - execution___of__example_cluster_classification (Exit code 0xc0000135)
> 294 - execution___of__gis_tutorial_example (Exit code 0xc0000135)
> 295 - execution___of__example_deprecated_conversion (Exit code 0xc0000135)

The exit code `0xc0000135` is the one the Windows runtime library uses when a DLL is not found at runtime. The set of examples that do not run are all from the directory `Classification/examples/Classification/` in CGAL. They all depend on Boost iostreams and Boost serialization libraries. You should add the directory containing the Boost DLLs (probably `F:\tools\boost_1_67_0\x64\lib64-msvc-14.1`) to your `PATH`.
