### ISSUE TITLE
cgal failed to run tests "error MSB4126: The specified solution configuration "Release|x86" is invalid" on Windows with MSVC of win32

### ISSUE THREAD

**Issue by YangYang129** [CGAL/cgal#6328]
cgal failed to run tests with MSVC on windows. It can reproduces on version https://github.com/CGAL/cgal/commit/5118f5f0234d132d96d3fa1c726fd8d1458ccea9. Could you please help look at this issue? Thank you very much

**Environment:**
Compiler version: VS2019 (16.11.10)
Operating system: Windows server 2019

**Steps to reproduce:**
1. open VS2019 x86 tools command
2. git clone https://github.com/CGAL/cgal F:\gitP\CGAL/cgal
3. cd F:\gitP\microsoft\vcpkg
4. bootstrap-vcpkg.bat
5. vcpkg.exe install --recurse yasm-tool GMP MPFR Eigen3 --triplet x64-windows --clean-after-build
6. cd F:\gitP\CGAL/cgal & mkdir buildx86aa & cd buildx86aa
7. set PATH=F:\tools\qt5\qt\5_15_2\msvc2019_86\bin;%PATH%
8. cmake -G "Visual Studio 16 2019" -A Win32 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=ON  -DCMAKE_TOOLCHAIN_FILE="F:\gitP\microsoft\vcpkg\scripts\buildsystems\vcpkg.cmake" -DVCPKG_TARGET_TRIPLET=x86-windows -DWITH_demos=ON -DWITH_examples=ON -DBOOST_LIBRARYDIR="F:\tools\boost_1_67_0\x86\lib32-msvc-14.1" -DBOOST_INCLUDEDIR="F:\tools\boost_1_67_0\x86" ..
9. msbuild /m /p:Platform=Win32 /p:Configuration=Release CGAL.sln /t:Rebuild
10. ctest --build-config Release --output-on-failure

**Test log:**
[ctestx86.log](https://github.com/CGAL/cgal/files/8077332/ctestx86.log)

**Error info:**
   3/1256 Test    #1: compilation_of__AABB_tree_Examples ...................................***Failed    0.31 sec
Microsoft (R) Build Engine version 16.11.2+f32259642 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 2/15/2022 9:38:08 PM.
     1>Project "F:\gitP\CGAL\cgal\buildx86aa\examples\AABB_tree\AABB_tree_Examples.sln" on node 1 (Build target(s)).
     1>F:\gitP\CGAL\cgal\buildx86aa\examples\AABB_tree\AABB_tree_Examples.sln.metaproj : error MSB4126: The specified solution configuration "Release|x86" is invalid. Please specify a valid solution configuration using the Configuration and Platform properties (e.g. MSBuild.exe Solution.sln /p:Configuration=Debug /p:Platform="Any CPU") or leave those properties blank to use the default solution configuration. [F:\gitP\CGAL\cgal\buildx86aa\examples\AABB_tree\AABB_tree_Examples.sln]
     1>Done Building Project "F:\gitP\CGAL\cgal\buildx86aa\examples\AABB_tree\AABB_tree_Examples.sln" (Build target(s)) -- FAILED.

Build FAILED.

       "F:\gitP\CGAL\cgal\buildx86aa\examples\AABB_tree\AABB_tree_Examples.sln" (Build target) (1) ->
       (ValidateSolutionConfiguration target) -> 
         F:\gitP\CGAL\cgal\buildx86aa\examples\AABB_tree\AABB_tree_Examples.sln.metaproj : error MSB4126: The specified solution configuration "Release|x86" is invalid. Please specify a valid solution configuration using the Configuration and Platform properties (e.g. MSBuild.exe Solution.sln /p:Configuration=Debug /p:Platform="Any CPU") or leave those properties blank to use the default solution configuration. [F:\gitP\CGAL\cgal\buildx86aa\examples\AABB_tree\AABB_tree_Examples.sln]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.14

**Comment by lrineau** [comment]
I am not sure. In the step 5, the `vcpkg.exe install ...`, should not you use `--triplet x86-windows` instead of `--triplet x64-windows`?
