### ISSUE TITLE
Solver_interface:  Soon deprecated Eigen API

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#6330]
## Issue Details

In the Surface Mesh Deformation [testsuite ](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.5-Ic-22/Surface_mesh_deformation/TestReport_lrineau_Ubuntu-GCC_master_CXX20-Release.gz)using the master branch of Eigen we get an error.

The error does not show up in the _Solver_interface_ testsuite, which means that it is not complete.

[This commit](https://gitlab.com/libeigen/eigen/-/commit/766087329ea34acaa2fa2a560cb79a981d6d265d#9ddf5069764a8b20d61431166bcae12ce74fb66e_601_607) on the Eigen gitlab gives a hint what we have to change. 

## Environment

* Other libraries versions if used (Eigen, TBB, etc.):  Eigen master branch

**Comment by lrineau** [comment]
See also the corresponding PR https://gitlab.com/libeigen/eigen/-/merge_requests/857 and the discussions in it.

**Comment by lrineau** [comment]
@soesau This issue is exactly the same as in https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.5-I-69/Surface_mesh_deformation/TestReport_lrineau_Ubuntu-GCC_master_CXX20-Release.gz

**Comment by MaelRL** [comment]
Fixed by https://github.com/CGAL/cgal/pull/6562.
