### ISSUE TITLE
issues with PMP::smooth_mesh and PMP::refine

### ISSUE THREAD

**Issue by easterngarden** [CGAL/cgal#6332]
## Issue Details

Using attached mesh_input, PMP::smooth_mesh creates spike mesh elemnts as shown in smooth_output and PMP::refine created many intersections in result mesh refine_output.
![image](https://user-images.githubusercontent.com/36804327/154596098-8fd0f284-258c-4926-9c8a-574599019ccb.png)
![image](https://user-images.githubusercontent.com/36804327/154596146-8e46fc02-b834-421d-93a0-7bd9ae710f39.png)

## Source Code

	namespace PMP = CGAL::Polygon_mesh_processing;
	PMP::smooth_mesh(mesh, PMP::parameters::do_project(true)
		.number_of_iterations(2));

	std::vector<face_descriptor>  new_facets;
	std::vector<vertex_descriptor> new_vertices;
        float densityFactor = sqrt(2);
	PMP::refine(mesh, faces(mesh),
				std::back_inserter(new_facets), 
				std::back_inserter(new_vertices),
				CGAL::parameters::density_control_factor(densityFactor));

## Environment

* Operating system (Windows 64 bits):
* Compiler: Visual Studio 2022
* Release or debug mode: both
* Specific flags used (if any):
* CGAL version: 5.2.1
* Boost version: 1_69
* Other libraries versions if used (Eigen, TBB, etc.):
[cgal_mesh_issues.zip](https://github.com/CGAL/cgal/files/8093183/cgal_mesh_issues.zip)

**Comment by MaelRL** [comment]
With more iterations, mesh smoothing should give you something nicer, but the geometry will not be honored nicely.  You might want to use [PMP::isotropic_remeshing](https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__meshing__grp.html#gad3d03890515ae8103bd32a30a3486412) instead.
