### ISSUE TITLE
Model to Nef_polyhedron occur error

### ISSUE THREAD

**Issue by Cool-key** [CGAL/cgal#6347]
Can you help me? Two cuboids are next to each other.
  Nef_polyhedron  nef1(mesh1);//Error
  Nef_polyhedron  nef1(polyhedron1);//Error

```c++
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/Nef_polyhedron_3.h>
#include <CGAL/Surface_mesh.h>
#include <CGAL/Polyhedron_items_with_id_3.h>
#include <CGAL/Polygon_mesh_processing/repair_polygon_soup.h>
#include <CGAL/Polygon_mesh_processing/orient_polygon_soup.h>
#include <CGAL/Polygon_mesh_processing/polygon_soup_to_polygon_mesh.h>
#include <CGAL/Polygon_mesh_processing/triangulate_faces.h>

using Kernel = CGAL::Exact_predicates_inexact_constructions_kernel;
using Point_3 = Kernel::Point_3;
using Mesh = CGAL::Surface_mesh<Point_3>;
using Polyhedron = CGAL::Polyhedron_3<Kernel, CGAL::Polyhedron_items_with_id_3, CGAL::HalfedgeDS_default>;
using Nef_polyhedron = CGAL::Nef_polyhedron_3<Kernel>;

namespace PMP=CGAL::Polygon_mesh_processing;

int main(int argc, char** argv)
{
        std::vector<std::vector<double>> triangles;
        std::vector<Kernel::Point_3> points;
   

	points.push_back(Point_3(-0.02, 0.02, -0.03));
	points.push_back(Point_3(-0.02, -0.02, -0.03));
	points.push_back(Point_3(-0.02, 0.02, -0.02));
	points.push_back(Point_3(-0.02, -0.02, -0.02));
        points.push_back(Point_3(0.02, 0.02, -0.03));
        points.push_back(Point_3(0.02, 0.02, -0.02));
        points.push_back(Point_3(0.02, -0.02, -0.03));
        points.push_back(Point_3(0.02, -0.02, -0.02));
        points.push_back(Point_3(-0.02, 0.02, 0.02));
        points.push_back(Point_3(-0.02, -0.02, 0.02));
        points.push_back(Point_3(0.02, 0.02, 0.02));
        points.push_back(Point_3(0.02, -0.02, 0.02));

	triangles.push_back({0,1,2});
	triangles.push_back({2,1,3});
	triangles.push_back({4,0,5});
	triangles.push_back({5,0,2});
	triangles.push_back({6,4,7});
	triangles.push_back({7,4,5});
	triangles.push_back({1,6,3});
	triangles.push_back({3,6,7});
	triangles.push_back({4,6,0});
	triangles.push_back({0,6,1});
	triangles.push_back({7,5,3});
	triangles.push_back({3,5,2});
	triangles.push_back({8,2,9});
	triangles.push_back({9,2,3});
	triangles.push_back({10,8,11});
	triangles.push_back({11,8,9});
	triangles.push_back({5,10,7});
	triangles.push_back({7,10,11});
	triangles.push_back({2,5,3});
	triangles.push_back({3,5,7});
	triangles.push_back({10,5,8});
	triangles.push_back({8,5,2});
	triangles.push_back({7,11,3});
	triangles.push_back({3,11,9});


        Polyhedron polyhedron1;
        Mesh mesh1;
        PMP::repair_polygon_soup(points, triangles);
	PMP::orient_polygon_soup(points, triangles);
        PMP::polygon_soup_to_polygon_mesh(points, triangles, mesh1);
        PMP::triangulate_faces(mesh1);
        //mesh1→polyhedron1
  
        std::ofstream("mesh1.off") << mesh1;
  
        Nef_polyhedron  nef1(mesh1);//Error
        Nef_polyhedron  nef2(polyhedron1);//Error
	
	return 0;
}

```

**Comment by afabri** [comment]
Did you use the exact_constructions kernel for the Nef_polyhedron ?

**Comment by Cool-key** [comment]
>Did you use the exact_constructions kernel for the Nef_polyhedron ?

I am a beginner，I'm not sure if I used it.
Kernel = CGAL::Exact_predicates_inexact_constructions_kernel;
Nef_polyhedron = CGAL::Nef_polyhedron_3<Kernel>;

**Comment by Cool-key** [comment]
> Did you use the exact_constructions kernel for the Nef_polyhedron ?

I am a beginner，I'm not sure if I used it.
Kernel = CGAL::Exact_predicates_inexact_constructions_kernel;
Nef_polyhedron = CGAL::Nef_polyhedron_3;

**Comment by Cool-key** [comment]
I am a beginner，I'm not sure if I used it.
Kernel = CGAL::Exact_predicates_inexact_constructions_kernel;
Nef_polyhedron = CGAL::Nef_polyhedron_3<Kernel>;
Is this correct?

**Comment by Cool-key** [comment]
> Did you use the exact_constructions kernel for the Nef_polyhedron ?
I am a beginner, and I am not sure whether I have used him or not.
using Kernel = CGAL::Exact_predicates_inexact_constructions_kernel;
using Nef_polyhedron = CGAL::Nef_polyhedron_3<Kernel>;
Is this correct?

**Comment by Cool-key** [comment]
> Did you use the exact_constructions kernel for the Nef_polyhedron ?

I am a beginner, and I am not sure whether I have used him or not.
using Kernel = CGAL::Exact_predicates_inexact_constructions_kernel;
using Nef_polyhedron = CGAL::Nef_polyhedron_3;
Is this correct?

**Comment by sloriot** [comment]
When you submit an issue, please make sure that the example you provide is complete and compile. I edit it to a version that I could compile and run.

Your example does not work because the input mesh is non-manifold. Indeed, as can be seen on the image below, you have 3 triangles incident to the red edges:

![Screenshot from 2022-02-24 09-11-57](https://user-images.githubusercontent.com/1224632/155484796-417abee1-c089-4889-bdef-931b079a53b2.png)

About Andreas comment, you should replace the first line by `using Kernel = CGAL::Exact_predicates_exact_constructions_kernel;` but that will not solve the non-manifoldness issue.

**Comment by Cool-key** [comment]
Thank you.
