### ISSUE TITLE
Error: Unhandled exception at 0x00007FFB27D5286E (ucrtbase.dll)

### ISSUE THREAD

**Issue by FuzhangHe** [CGAL/cgal#6349]
## Issue Details
Hi, Dear CGAL-Developer:

Maybe this is not a bug, but i still need some help, so i write here:
I tried to run the example "draw_triangulation_2" and got an error in plot:

> Unhandled exception at 0x00007FFB27D5286E (ucrtbase.dll) in draw_triangulation_2.exe: Fatal program exit requested.

I have checked, that the ucrtbase.dll is in the both folder "C:\Windows\SysWOW64" and "C:\Windows\System32"

Following is the entire output of the project:

> 'draw_triangulation_2.exe' (Win32): Loaded 'D:\PTW\CGAL-5.4-examples\CGAL-5.4\examples\Triangulation_2\build\Debug\draw_triangulation_2.exe'. Symbols loaded.
> 'draw_triangulation_2.exe' (Win32): Loaded 'C:\Windows\System32\ntdll.dll'. Symbols loaded.
> 'draw_triangulation_2.exe' (Win32): Loaded 'C:\Windows\System32\kernel32.dll'. Symbols loaded.
> 'draw_triangulation_2.exe' (Win32): Loaded 'C:\Windows\System32\KernelBase.dll'. Symbols loaded.
> 'draw_triangulation_2.exe' (Win32): Loaded 'D:\PTW\dev\vcpkg\installed\x64-windows\bin\gmp.dll'. Symbols loaded.
> 'draw_triangulation_2.exe' (Win32): Loaded 'C:\Windows\System32\ucrtbase.dll'. Symbols loaded.
> 'draw_triangulation_2.exe' (Win32): Loaded 'C:\ProgramData\Anaconda3\Library\bin\Qt5OpenGL.dll'. Module was built without symbols.
> 'draw_triangulation_2.exe' (Win32): Loaded 'C:\ProgramData\Anaconda3\Library\bin\Qt5Svg.dll'. Module was built without symbols.
> 'draw_triangulation_2.exe' (Win32): Loaded 'C:\ProgramData\Anaconda3\Library\bin\Qt5Widgets.dll'. Module was built without symbols.
> 'draw_triangulation_2.exe' (Win32): Loaded 'C:\Windows\System32\gdi32.dll'. Symbols loaded.
> 'draw_triangulation_2.exe' (Win32): Loaded 'C:\Windows\System32\win32u.dll'. Symbols loaded.
> 'draw_triangulation_2.exe' (Win32): Loaded 'C:\Windows\System32\gdi32full.dll'. Symbols loaded.
> 'draw_triangulation_2.exe' (Win32): Loaded 'C:\Windows\System32\msvcp_win.dll'. Symbols loaded.
> 'draw_triangulation_2.exe' (Win32): Loaded 'C:\Windows\System32\user32.dll'. Symbols loaded.
> 'draw_triangulation_2.exe' (Win32): Loaded 'C:\Windows\System32\shell32.dll'. Symbols loaded.
> 'draw_triangulation_2.exe' (Win32): Loaded 'C:\ProgramData\Anaconda3\Library\bin\Qt5Gui.dll'. Module was built without symbols.
> 'draw_triangulation_2.exe' (Win32): Loaded 'C:\Windows\System32\ole32.dll'. Symbols loaded.
> 'draw_triangulation_2.exe' (Win32): Loaded 'C:\Windows\System32\rpcrt4.dll'. Symbols loaded.
> 'draw_triangulation_2.exe' (Win32): Loaded 'C:\Windows\System32\combase.dll'. Symbols loaded.
> 'draw_triangulation_2.exe' (Win32): Loaded 'C:\ProgramData\Anaconda3\Library\bin\Qt5Core.dll'. Module was built without symbols.
> 'draw_triangulation_2.exe' (Win32): Loaded 'C:\Windows\System32\ws2_32.dll'. Symbols loaded.
> 'draw_triangulation_2.exe' (Win32): Loaded 'C:\Windows\System32\advapi32.dll'. Symbols loaded.
> 'draw_triangulation_2.exe' (Win32): Loaded 'C:\Windows\System32\msvcrt.dll'. Symbols loaded.
> 'draw_triangulation_2.exe' (Win32): Loaded 'C:\Windows\System32\sechost.dll'. Symbols loaded.
> 'draw_triangulation_2.exe' (Win32): Loaded 'C:\Windows\System32\msvcp140d.dll'. Symbols loaded.
> 'draw_triangulation_2.exe' (Win32): Loaded 'C:\Windows\System32\vcruntime140d.dll'. Symbols loaded.
> 'draw_triangulation_2.exe' (Win32): Loaded 'C:\Windows\System32\vcruntime140_1d.dll'. Symbols loaded.
> 'draw_triangulation_2.exe' (Win32): Loaded 'C:\Windows\System32\ucrtbased.dll'. Symbols loaded.
> 'draw_triangulation_2.exe' (Win32): Loaded 'C:\Windows\System32\vcruntime140.dll'. Symbols loaded.
> 'draw_triangulation_2.exe' (Win32): Loaded 'C:\ProgramData\Anaconda3\Library\bin\zlib.dll'. Module was built without symbols.
> 'draw_triangulation_2.exe' (Win32): Loaded 'C:\Windows\System32\uxtheme.dll'. Symbols loaded.
> 'draw_triangulation_2.exe' (Win32): Loaded 'C:\Windows\System32\dwmapi.dll'. Symbols loaded.
> 'draw_triangulation_2.exe' (Win32): Loaded 'C:\Windows\System32\msvcp140.dll'. Symbols loaded.
> 'draw_triangulation_2.exe' (Win32): Loaded 'C:\ProgramData\Anaconda3\Library\bin\libpng16.dll'. Module was built without symbols.
> 'draw_triangulation_2.exe' (Win32): Loaded 'C:\Windows\System32\mpr.dll'. Symbols loaded.
> 'draw_triangulation_2.exe' (Win32): Loaded 'C:\Windows\System32\version.dll'. Symbols loaded.
> 'draw_triangulation_2.exe' (Win32): Loaded 'C:\Windows\System32\winmm.dll'. Symbols loaded.
> 'draw_triangulation_2.exe' (Win32): Loaded 'C:\ProgramData\Anaconda3\Library\bin\icuin58.dll'. Module was built without symbols.
> 'draw_triangulation_2.exe' (Win32): Loaded 'C:\ProgramData\Anaconda3\Library\bin\icuuc58.dll'. Module was built without symbols.
> 'draw_triangulation_2.exe' (Win32): Loaded 'C:\Windows\System32\vcruntime140_1.dll'. Symbols loaded.
> 'draw_triangulation_2.exe' (Win32): Loaded 'C:\ProgramData\Anaconda3\Library\bin\icudt58.dll'. Module was built without symbols.
> 'draw_triangulation_2.exe' (Win32): Unloaded 'C:\ProgramData\Anaconda3\Library\bin\icudt58.dll'
> 'draw_triangulation_2.exe' (Win32): Loaded 'C:\ProgramData\Anaconda3\Library\bin\icudt58.dll'. Module was built without symbols.
> 'draw_triangulation_2.exe' (Win32): Loaded 'C:\Windows\System32\imm32.dll'. Symbols loaded.
> The thread 0x3618 has exited with code 0 (0x0).
> 'draw_triangulation_2.exe' (Win32): Loaded 'C:\Windows\System32\cryptbase.dll'. Symbols loaded.
> 'draw_triangulation_2.exe' (Win32): Loaded 'C:\Windows\System32\bcryptprimitives.dll'. Symbols loaded.
> 'draw_triangulation_2.exe' (Win32): Loaded 'C:\Windows\System32\windows.storage.dll'. Symbols loaded.
> 'draw_triangulation_2.exe' (Win32): Loaded 'C:\Windows\System32\wldp.dll'. Symbols loaded.
> 'draw_triangulation_2.exe' (Win32): Loaded 'C:\Windows\System32\SHCore.dll'. Symbols loaded.
> 'draw_triangulation_2.exe' (Win32): Loaded 'C:\Windows\System32\shlwapi.dll'. Symbols loaded.
> 'draw_triangulation_2.exe' (Win32): Loaded 'C:\Windows\System32\profapi.dll'. Symbols loaded.
> Unhandled exception at 0x00007FFB27D5286E (ucrtbase.dll) in draw_triangulation_2.exe: Fatal program exit requested.
> 
> The program '[31912] draw_triangulation_2.exe' has exited with code 0 (0x0).

## Source Code

CGAL Example:
...\CGAL-5.4-examples\CGAL-5.4\examples\Triangulation_2\draw_triangulation_2.cpp

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows 64
* Compiler: CMake
* Release or debug mode: Debug
* Specific flags used (if any):
* CGAL version: 5.4
* Boost version: 1.78.0
* Visual Studio: Community 2019, Version 16.11.10.
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by sloriot** [comment]
Is this issue also solved by the reinstall?

**Comment by FuzhangHe** [comment]
> 

unfortunately the issue still exists after reinstallation.

**Comment by FuzhangHe** [comment]
Finally, i find out the problem.

See this picture, the cmake linked the qt library from Anaconda, not from the qt5 of vcpkg.
![Capture](https://user-images.githubusercontent.com/32159074/156049721-371235ce-23c2-40b6-8c37-6c3ead94cf10.PNG)

Just change these pathes to the "vcpkg\installed\x64-windows\include\qt5\..." .
Than it works.

**Comment by lrineau** [comment]
Thanks @FuzhangHe for letting us know you found the issue, and what it was. It might permit us to help other users having similar symptoms.
