### ISSUE TITLE
high precision kernel support for Polygon_mesh_processing

### ISSUE THREAD

**Issue by wucm1994** [CGAL/cgal#635]
Hi! Today, I was trying to use Exact_predicates_exact_constructions_kernel kernel (CGAL::Lazy_exact_nt<CGAL::Gmpq> as default) to refine my polyhedron with holes, my compiler said **C2440 Cannot convert from "CGAL::Lazy_exact_nt<CGAL::Gmpq>" to "double"** and stopped it.

So what I want to ask for is if there has any possibility to use high precision kernels in package Polygon_mesh_processing? Thanks.

p.s.: I have tried to use **triangulate_and_refine_hole** function and **triangulate_hole** function, neither can pass the compiling.

**Comment by sloriot** [comment]
Indeed the expected number type for the point type must be convertible to double. A solution is to provide a point proeperty map where it is the case.

**Comment by afabri** [comment]
@wucm1994 : What is your motivation to perform these operations with an exact number type?

**Comment by janetournois** [comment]
@wucm1994 we have made the `Polygon_mesh_processing` package compatible with the `Exact_predicates_exact_constructions_kernel`, and it's tested daily, so you should be able to use it with the `master` branch now.

**Comment by wucm1994** [comment]
Thanks for you effort.
