### ISSUE TITLE
Model to Nef_polyhedron occur error 0x000007FEFD1BBE0D

### ISSUE THREAD

**Issue by Cool-key** [CGAL/cgal#6355]
Run the following code.

```
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/Nef_polyhedron_3.h>
#include <CGAL/Surface_mesh.h>
#include <CGAL/Polyhedron_items_with_id_3.h>
#include <CGAL/Polygon_mesh_processing/repair_polygon_soup.h>
#include <CGAL/Polygon_mesh_processing/orient_polygon_soup.h>
#include <CGAL/Polygon_mesh_processing/polygon_soup_to_polygon_mesh.h>
#include <CGAL/Polygon_mesh_processing/triangulate_faces.h>

using Kernel = CGAL::Exact_predicates_exact_constructions_kernel;
using Point_3 = Kernel::Point_3;
using Mesh = CGAL::Surface_mesh<Point_3>;
using Polyhedron = CGAL::Polyhedron_3<Kernel, CGAL::Polyhedron_items_with_id_3, CGAL::HalfedgeDS_default>;
using Nef_polyhedron = CGAL::Nef_polyhedron_3<Kernel>;
std::string OFF_str = "OFF\n8 12 0\n0.03 -0.02 0.02\n0.03 0.02 0.02\n0.02 -0.02 0.02\n0.02 0.02 0.02\n0.03 -0.02 -0.02\n0.02 -0.02 -0.02\n0.03 0.02 -0.02\n0.02 0.02 -0.02\n3  0 1 2\n3  2 1 3\n3  4 0 5\n3  5 0 2\n3  6 4 7\n3  7 4 5\n3  1 6 3\n3  3 6 7\n3  4 6 0\n3  0 6 1\n3  7 5 3\n3  3 5 2\n/B/OFF\n8 12 0\n-0.02 0.02 0.02\n-0.02 0.02 -0.02\n-0.02 -0.02 0.02\n-0.02 -0.02 -0.02\n0.02 0.02 0.02\n0.02 -0.02 0.02\n0.02 0.02 -0.02\n0.02 -0.02 -0.02\n3  0 1 2\n3  2 1 3\n3  4 0 5\n3  5 0 2\n3  6 4 7\n3  7 4 5\n3  1 6 3\n3  3 6 7\n3  4 6 0\n3  0 6 1\n3  7 5 3\n3  3 5 2\n/B/";
void OFFString_To_PolyhedronS(std::string OFF_str, std::vector<Polyhedron>& polyhedrons)
	{

		std::vector<string>  OFF_strS = StringLogic::split(OFF_str, "/B/");

		for (size_t i = 0; i < OFF_strS.size(); i++)
		{
			Polyhedron polyhedron1;
			std::stringstream ss;
			ss << OFF_strS[i];
			ss >> polyhedron1;
			polyhedrons.push_back(polyhedron1);
			//Nef_polyhedron  nef1(polyhedron1); // not Error
			//Mesh mesh;
			//CGAL::convert_nef_polyhedron_to_polygon_mesh(nef1, mesh);
			//CGAL::draw(mesh);
		}
	

	}
int main(int argc, char* argv[])
	{

		std::vector<Polyhedron> polyhedrons;

		Model_IO::OFFString_To_PolyhedronS(OFF_str, polyhedrons);

		int Num = polyhedrons.size();

		while (Num > 1)
		{
			Polyhedron polyhedron0 = polyhedrons[polyhedrons.size() - 1];
			Polyhedron polyhedron1 = polyhedrons[polyhedrons.size() - 2];
			Polyhedron polyhedron2;
			Nef_polyhedron  nef0(polyhedron0);//Error: 0x000007 There is an unhandled exception at fefd1be0d (located in ZHITU_Algorithms_Library.exe): Microsoft C++ exception: CGAL::Assertion_exception, located at memory location 0x000000000028D600.

			Nef_polyhedron  nef1(polyhedron1);//Error: 0x000007 There is an unhandled exception at fefd1be0d (located in ZHITU_Algorithms_Library.exe): Microsoft C++ exception: CGAL::Assertion_exception, located at memory location 0x000000000028D600.
			Nef_polyhedron  nef = nef0 + nef1;//Error: 0x000007 There is an unhandled exception at fefd1be0d (located in ZHITU_Algorithms_Library.exe): Microsoft C++ exception: CGAL::Assertion_exception, located at memory location 0x000000000028D600.

			nef.convert_to_Polyhedron(polyhedron2);

			polyhedrons.pop_back();
			polyhedrons.pop_back();
			polyhedrons.push_back(polyhedron2);

			Num = polyhedrons.size();
		};

		Nef_polyhedron  nef0(polyhedrons[0]);

		CGAL::draw(polyhedrons[0]);

		return EXIT_SUCCESS;

	}
```

**Comment by sloriot** [comment]
I don't have any error with the following code:
```
#include <CGAL/Exact_predicates_exact_constructions_kernel.h>
#include <CGAL/Nef_polyhedron_3.h>
#include <CGAL/Surface_mesh.h>
#include <CGAL/Polyhedron_items_with_id_3.h>
#include <CGAL/Polygon_mesh_processing/repair_polygon_soup.h>
#include <CGAL/Polygon_mesh_processing/orient_polygon_soup.h>
#include <CGAL/Polygon_mesh_processing/polygon_soup_to_polygon_mesh.h>
#include <CGAL/Polygon_mesh_processing/triangulate_faces.h>

using Kernel = CGAL::Exact_predicates_exact_constructions_kernel;
using Point_3 = Kernel::Point_3;
using Mesh = CGAL::Surface_mesh<Point_3>;
using Polyhedron = CGAL::Polyhedron_3<Kernel, CGAL::Polyhedron_items_with_id_3, CGAL::HalfedgeDS_default>;
using Nef_polyhedron = CGAL::Nef_polyhedron_3<Kernel>;
std::string OFF_str1 = "OFF\n8 12 0\n0.03 -0.02 0.02\n0.03 0.02 0.02\n0.02 -0.02 0.02\n0.02 0.02 0.02\n0.03 -0.02 -0.02\n0.02 -0.02 -0.02\n0.03 0.02 -0.02\n0.02 0.02 -0.02\n3  0 1 2\n3  2 1 3\n3  4 0 5\n3  5 0 2\n3  6 4 7\n3  7 4 5\n3  1 6 3\n3  3 6 7\n3  4 6 0\n3  0 6 1\n3  7 5 3\n3  3 5 2\n";
std::string OFF_str2 = "OFF\n8 12 0\n-0.02 0.02 0.02\n-0.02 0.02 -0.02\n-0.02 -0.02 0.02\n-0.02 -0.02 -0.02\n0.02 0.02 0.02\n0.02 -0.02 0.02\n0.02 0.02 -0.02\n0.02 -0.02 -0.02\n3  0 1 2\n3  2 1 3\n3  4 0 5\n3  5 0 2\n3  6 4 7\n3  7 4 5\n3  1 6 3\n3  3 6 7\n3  4 6 0\n3  0 6 1\n3  7 5 3\n3  3 5 2\n";
void OFFString_To_PolyhedronS(std::vector<Polyhedron>& polyhedrons)
	{

    {
			Polyhedron polyhedron1;
			std::stringstream ss;
			ss << OFF_str1;
			ss >> polyhedron1;
      std::ofstream("out1.off") << polyhedron1;
			polyhedrons.push_back(polyhedron1);
		}
    {
			Polyhedron polyhedron1;
			std::stringstream ss;
			ss << OFF_str2;
			ss >> polyhedron1;
      std::ofstream("out2.off") << polyhedron1;
			polyhedrons.push_back(polyhedron1);
		}
	

	}
int main(int argc, char* argv[])
	{

		std::vector<Polyhedron> polyhedrons;

		OFFString_To_PolyhedronS(polyhedrons);

		int Num = polyhedrons.size();

		while (Num > 1)
		{
			Polyhedron polyhedron0 = polyhedrons[polyhedrons.size() - 1];
			Polyhedron polyhedron1 = polyhedrons[polyhedrons.size() - 2];
			Polyhedron polyhedron2;
			Nef_polyhedron  nef0(polyhedron0);//Error: 0x000007 There is an unhandled exception at fefd1be0d (located in ZHITU_Algorithms_Library.exe): Microsoft C++ exception: CGAL::Assertion_exception, located at memory location 0x000000000028D600.

			Nef_polyhedron  nef1(polyhedron1);//Error: 0x000007 There is an unhandled exception at fefd1be0d (located in ZHITU_Algorithms_Library.exe): Microsoft C++ exception: CGAL::Assertion_exception, located at memory location 0x000000000028D600.
			Nef_polyhedron  nef = nef0 + nef1;//Error: 0x000007 There is an unhandled exception at fefd1be0d (located in ZHITU_Algorithms_Library.exe): Microsoft C++ exception: CGAL::Assertion_exception, located at memory location 0x000000000028D600.

			nef.convert_to_Polyhedron(polyhedron2);

			polyhedrons.pop_back();
			polyhedrons.pop_back();
			polyhedrons.push_back(polyhedron2);

			Num = polyhedrons.size();
		};

		Nef_polyhedron  nef0(polyhedrons[0]);

		// CGAL::draw(polyhedrons[0]);

		return EXIT_SUCCESS;

	}
```

which I just updated so that it could be compiled

**Comment by Cool-key** [comment]
> I don't have any error with the following code:
> 
> ```
> #include <CGAL/Exact_predicates_exact_constructions_kernel.h>
> #include <CGAL/Nef_polyhedron_3.h>
> #include <CGAL/Surface_mesh.h>
> #include <CGAL/Polyhedron_items_with_id_3.h>
> #include <CGAL/Polygon_mesh_processing/repair_polygon_soup.h>
> #include <CGAL/Polygon_mesh_processing/orient_polygon_soup.h>
> #include <CGAL/Polygon_mesh_processing/polygon_soup_to_polygon_mesh.h>
> #include <CGAL/Polygon_mesh_processing/triangulate_faces.h>
> 
> using Kernel = CGAL::Exact_predicates_exact_constructions_kernel;
> using Point_3 = Kernel::Point_3;
> using Mesh = CGAL::Surface_mesh<Point_3>;
> using Polyhedron = CGAL::Polyhedron_3<Kernel, CGAL::Polyhedron_items_with_id_3, CGAL::HalfedgeDS_default>;
> using Nef_polyhedron = CGAL::Nef_polyhedron_3<Kernel>;
> std::string OFF_str1 = "OFF\n8 12 0\n0.03 -0.02 0.02\n0.03 0.02 0.02\n0.02 -0.02 0.02\n0.02 0.02 0.02\n0.03 -0.02 -0.02\n0.02 -0.02 -0.02\n0.03 0.02 -0.02\n0.02 0.02 -0.02\n3  0 1 2\n3  2 1 3\n3  4 0 5\n3  5 0 2\n3  6 4 7\n3  7 4 5\n3  1 6 3\n3  3 6 7\n3  4 6 0\n3  0 6 1\n3  7 5 3\n3  3 5 2\n";
> std::string OFF_str2 = "OFF\n8 12 0\n-0.02 0.02 0.02\n-0.02 0.02 -0.02\n-0.02 -0.02 0.02\n-0.02 -0.02 -0.02\n0.02 0.02 0.02\n0.02 -0.02 0.02\n0.02 0.02 -0.02\n0.02 -0.02 -0.02\n3  0 1 2\n3  2 1 3\n3  4 0 5\n3  5 0 2\n3  6 4 7\n3  7 4 5\n3  1 6 3\n3  3 6 7\n3  4 6 0\n3  0 6 1\n3  7 5 3\n3  3 5 2\n";
> void OFFString_To_PolyhedronS(std::vector<Polyhedron>& polyhedrons)
> 	{
> 
>     {
> 			Polyhedron polyhedron1;
> 			std::stringstream ss;
> 			ss << OFF_str1;
> 			ss >> polyhedron1;
>       std::ofstream("out1.off") << polyhedron1;
> 			polyhedrons.push_back(polyhedron1);
> 		}
>     {
> 			Polyhedron polyhedron1;
> 			std::stringstream ss;
> 			ss << OFF_str2;
> 			ss >> polyhedron1;
>       std::ofstream("out2.off") << polyhedron1;
> 			polyhedrons.push_back(polyhedron1);
> 		}
> 	
> 
> 	}
> int main(int argc, char* argv[])
> 	{
> 
> 		std::vector<Polyhedron> polyhedrons;
> 
> 		OFFString_To_PolyhedronS(polyhedrons);
> 
> 		int Num = polyhedrons.size();
> 
> 		while (Num > 1)
> 		{
> 			Polyhedron polyhedron0 = polyhedrons[polyhedrons.size() - 1];
> 			Polyhedron polyhedron1 = polyhedrons[polyhedrons.size() - 2];
> 			Polyhedron polyhedron2;
> 			Nef_polyhedron  nef0(polyhedron0);//Error: 0x000007 There is an unhandled exception at fefd1be0d (located in ZHITU_Algorithms_Library.exe): Microsoft C++ exception: CGAL::Assertion_exception, located at memory location 0x000000000028D600.
> 
> 			Nef_polyhedron  nef1(polyhedron1);//Error: 0x000007 There is an unhandled exception at fefd1be0d (located in ZHITU_Algorithms_Library.exe): Microsoft C++ exception: CGAL::Assertion_exception, located at memory location 0x000000000028D600.
> 			Nef_polyhedron  nef = nef0 + nef1;//Error: 0x000007 There is an unhandled exception at fefd1be0d (located in ZHITU_Algorithms_Library.exe): Microsoft C++ exception: CGAL::Assertion_exception, located at memory location 0x000000000028D600.
> 
> 			nef.convert_to_Polyhedron(polyhedron2);
> 
> 			polyhedrons.pop_back();
> 			polyhedrons.pop_back();
> 			polyhedrons.push_back(polyhedron2);
> 
> 			Num = polyhedrons.size();
> 		};
> 
> 		Nef_polyhedron  nef0(polyhedrons[0]);
> 
> 		// CGAL::draw(polyhedrons[0]);
> 
> 		return EXIT_SUCCESS;
> 
> 	}
> ```
> 
> which I just updated so that it could be compiled

I tried a new method.
std::string OFF_str1 = "OFF\n8 12 0\n0.03 -0.02 0.02\n0.03 0.02 0.02\n0.02 -0.02 0.02\n0.02 0.02 0.02\n0.03 -0.02 -0.02\n0.02 -0.02 -0.02\n0.03 0.02 -0.02\n0.02 0.02 -0.02\n3  0 1 2\n3  2 1 3\n3  4 0 5\n3  5 0 2\n3  6 4 7\n3  7 4 5\n3  1 6 3\n3  3 6 7\n3  4 6 0\n3  0 6 1\n3  7 5 3\n3  3 5 2\n";
std::string OFF_str2 = "OFF\n8 12 0\n-0.02 0.02 0.02\n-0.02 0.02 -0.02\n-0.02 -0.02 0.02\n-0.02 -0.02 -0.02\n0.02 0.02 0.02\n0.02 -0.02 0.02\n0.02 0.02 -0.02\n0.02 -0.02 -0.02\n3  0 1 2\n3  2 1 3\n3  4 0 5\n3  5 0 2\n3  6 4 7\n3  7 4 5\n3  1 6 3\n3  3 6 7\n3  4 6 0\n3  0 6 1\n3  7 5 3\n3  3 5 2\n";
Eject error：Not loaded ucrtbased.pdb  , version 10.0.19041.1（WinBuild.160101.0800）

**Comment by Cool-key** [comment]
Error still reported after update.
Nef_polyhedron  nef0(polyhedron0);//Error: 0x000007fefd1be0d (located in ZHITU_Algorithms_Library.exe): Microsoft C++ exception: CGAL::Assertion_exception, located at memory location 0x000000000028D600.

**Comment by Cool-key** [comment]
To solve
CGAL::Exact_predicates_inexact_constructions_kernel (×)
CGAL::Exact_predicates_exact_constructions_kernel（√）
