### ISSUE TITLE
error: keyword 'template' not allowed in declarator-id [-Werror=pedantic]

### ISSUE THREAD

**Issue by ffteja** [CGAL/cgal#6358]
## Issue Details

I'm compiling with GCC 10.3 with std=c++14 and pedantic checks
I could fix other pedantic errors but this one is tougher.
Maybe you'll find a solution. Otherwise it's not critical.

## Source Code

I face this issue at compilation:
```
/CGAL-5.4/include/CGAL/AABB_tree.h:967:53: error: keyword 'template' not allowed in declarator-id [-Werror=pedantic]
967 | boost::optional< typename AABB_tree<Tr>::template Intersection_and_primitive_id<Query>::Type >
```

This refers to this line : https://github.com/CGAL/releases/blob/72836689d03dbd6ebfcfbb2d646e60ef5a7a18c7/include/CGAL/AABB_tree.h#L967

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Linux
* Compiler: GCC10.3
* CGAL version: 5.4 and 5.2.2

**Comment by sloriot** [comment]
It should be `boost::optional< typename AABB_tree<Tr>::Intersection_and_primitive_id<Query>::Type >`. Would you mind add it in your other PR and check that the error is gone?

**Comment by ffteja** [comment]
Intersection_and_primitive_id<Query> is the declarator-id? Thus won't accept Query in it?

**Comment by ffteja** [comment]
If that could help:
https://timsong-cpp.github.io/cppwp/n4659/temp.names#4

**Comment by sloriot** [comment]
I don't reproduce the issue and I don't see any problem but the extra template I already mentioned. @lrineau @mglisse any idea?

**Comment by lrineau** [comment]
I do not know who to reproduce the error. Please @ffteja give us a self-contained .cpp file that can reproduce the error, and tell us about the compiler flags you used.

**Comment by lrineau** [comment]
@ffteja I was not able to reproduce the pedantic error with my version of gcc, but I have created PR https://github.com/CGAL/cgal/pull/6571 anyway to remove that `template` keyword.
