### ISSUE TITLE
The webpage can't be opened.

### ISSUE THREAD

**Issue by Cool-key** [CGAL/cgal#6362]
CGAL error: assertion violation
Experssion :h.has_on<p>
file             : ....\include\CGAL/Nef_3/SNC_intersection.h
line  :317
Explanation:
Refer to the bug-reporting instructions at https://www.cgal.ory/bug_report.html

**Comment by Cool-key** [comment]
Source of problem
Nef_polyhedron nef0(polyhedron0)

https://github.com/CGAL/cgal/issues/6355

**Comment by Cool-key** [comment]
Source of problem
Nef_polyhedron nef0(polyhedron0)

https://github.com/CGAL/cgal/issues/6355

**Comment by sloriot** [comment]
it is `.org` not `.ory`. You seems to have strange issues happening. Could it be related to the configuration of your locale in MSVC?
