### ISSUE TITLE
CGAL image_3 cant load analyze format correctly 

### ISSUE THREAD

**Issue by blacksino** [CGAL/cgal#6371]
Hi, I have got some trouble with loading volumetric data in CGAL.
[t2_mask.hdr.gz](https://github.com/CGAL/cgal/files/8167913/t2_mask.hdr.gz)
BTW: Is there any easy way to load .nii file in CGAL?

**Comment by sloriot** [comment]
Without any guarantee, maybe you can adapt [that example](https://doc.cgal.org/latest/Mesh_3/Mesh_3_2mesh_3D_gray_vtk_image_8cpp-example.html) using [`vtkHDRReader`](https://vtk.org/doc/nightly/html/classvtkHDRReader.html) instead of `vtkDICOMImageReader`.

**Comment by lrineau** [comment]
I think [`vtkNIFTIImageReader`](https://vtk.org/doc/nightly/html/classvtkNIFTIImageReader.html) is the right class to open NIFTI files using the VTK API.

**Comment by blacksino** [comment]
Thanks, guys. I have written a python script to convert the .nii file to .inr file, here  is some example code, enjoy it.

**Comment by blacksino** [comment]
Thanks, guys, I have written a simple python script for converting the nifty file to Inria image, I hope it would help those people who met the same problems.


```
from os import path
import gzip
from io import StringIO
import cv2
import numpy as np
import matplotlib.pyplot as plt
import SimpleITK as sitk


def nii2inr(nii_path,target_path):
    itk_image = sitk.ReadImage(nii_path)
    x,y,z = itk_image.GetSize()
    x_spacing,y_spacing,z_spacing = itk_image.GetSpacing()
    itk_array = sitk.GetArrayFromImage(itk_image)
    type = itk_image.GetPixelIDTypeAsString()
    assert type== "8-bit unsigned integer"

    # Change the type if you need.

    info_prefix = f"#INRIMAGE-4#{{\nXDIM={x}\nYDIM={y}\nZDIM={z}\nVDIM=1\nTYPE=unsigned fixed\nPIXSIZE=8 bits\nSCALE=2**0\nCPU=decm\nVX={x_spacing}\nVY={y_spacing}\nVZ={z_spacing}"
    header_suffix = "##}}\n"
    num_of_EOL = 257 - len(info_prefix) - len(header_suffix)
    header = f"#INRIMAGE-4#{{\nXDIM={x}\nYDIM={y}\nZDIM={z}\nVDIM=1\nTYPE=unsigned fixed\nPIXSIZE=8 bits\nSCALE=2**0\nCPU=decm\nVX={x_spacing}\nVY={y_spacing}\nVZ={z_spacing}"+\
             "\n"*num_of_EOL+"##}\n"

    with open(target_path,"wb") as f:
        f.write(header.encode("utf-8"))
        f.write(itk_array.flatten())

    return 1
```
