### ISSUE TITLE
read_STL can not parse binary stl files with all space head.

### ISSUE THREAD

**Issue by huangdade** [CGAL/cgal#6374]
## Issue Details

I have a binary .STL file, with a head consisting of 80 space char. read_STL treats it as an ascii STL file.

## Environment

CGAL_VERSION 5.3-I-900

STL file head:
![image](https://user-images.githubusercontent.com/4537048/156507094-5bd4e302-5c9a-404b-af9a-be6ba86e35cf.png)
Stream_support/include/CGAL/IO/STL.h
![image](https://user-images.githubusercontent.com/4537048/156507153-b956a5a1-c6dd-4ce8-8b53-3c3a625fc82b.png)

**Comment by afabri** [comment]
Did you open the stream  in `std::ios::binary` mode?    If that does not help maybe share the file with us to have a look.

**Comment by huangdade** [comment]
I load the STL file like this:
PMP::IO::read_polygon_mesh(filepath, mesh, CGAL::parameters::verbose(true));

[10du(1)-origin.zip](https://github.com/CGAL/cgal/files/8175716/10du.1.-origin.zip)

**Comment by lrineau** [comment]
Fixed by https://github.com/CGAL/cgal/pull/6376
