### ISSUE TITLE
 CGAL::draw(Nef_3): Holes are filled incorrectly

### ISSUE THREAD

**Issue by Cool-key** [CGAL/cgal#6375]
[ceshi.txt](https://github.com/CGAL/cgal/files/8175972/ceshi.txt)
![kk_image](https://user-images.githubusercontent.com/34527183/156522033-aa846bb8-0691-4871-92e4-a7c03aff19ee.jpg)
![kk_image2](https://user-images.githubusercontent.com/34527183/156522040-8a9bcd8a-1b83-49ce-a25e-6d4f16ad1f1b.jpg)

**Comment by Cool-key** [comment]
What is the reason for this?

**Comment by sloriot** [comment]
We need more details. display is different between what and what?

**Comment by Cool-key** [comment]
The hole of the red arrow was filled. in CGAL::draw(nef_3).
But there are holes in the example.  in Polyhedron Demo window
See attachment for model.


> We need more details. display is different between what and what?

**Comment by Cool-key** [comment]
[ceshi.txt](https://github.com/CGAL/cgal/files/8175972/ceshi.txt)

**Comment by lrineau** [comment]
Thanks @Cool-key. So the bug seems in the function template [`CGAL::draw(Nef_3)`](https://doc.cgal.org/5.4/Nef_3/group__PkgDrawNef3.html). Can you please tell which version of CGAL you are using?

**Comment by lrineau** [comment]
That function `CGAL::draw(Nef_3)` was developed during GSoC'19, and implemented in the PR https://github.com/CGAL/cgal/pull/4224. Guillaume (@gdamiand) you were the mentor of the internship, do you remember any discussion about holes and Nef_3?

**Comment by Cool-key** [comment]
> 在函

5.4

**Comment by gdamiand** [comment]
> That function `CGAL::draw(Nef_3)` was developed during GSoC'19, and implemented in the PR #4224. Guillaume (@gdamiand) you were the mentor of the internship, do you remember any discussion about holes and Nef_3?

Nothing special about holes.
In the code, faces are drawn by:
<code>
      CGAL_forall_shells_of(it, c)
      {
        nef.visit_shell_objects(SFace_const_handle(it), V);
      }
</code>
Any idea how to iterate only on faces and not holes ?

**Comment by Cool-key** [comment]
> That function `CGAL::draw(Nef_3)` was developed during GSoC'19, and implemented in the PR #4224. Guillaume (@gdamiand) you were the mentor of the internship, do you remember any discussion about holes and Nef_3?



> Thanks @Cool-key. So the bug seems in the function template [`CGAL::draw(Nef_3)`](https://doc.cgal.org/5.4/Nef_3/group__PkgDrawNef3.html). Can you please tell which version of CGAL you are using?

cgal 5.4

**Comment by sloriot** [comment]
Actually the drawing code requires a CDT to triangulate the polygon with holes like it is done in the demo for example.

**Comment by gdamiand** [comment]
The CDT is automatically computed in the basic viewer. For a face with hole, it is enough to add points of the external boundary, then points of the internal boundaries to draw it correctly (like done in draw_polygon_with_holes_2.h).

**Comment by GilesBathgate** [comment]
Maybe a test can be written, and then `git bisect run` to find out which commit broke it :worried:

**Comment by Cool-key** [comment]
Thank you, showing success.
