### ISSUE TITLE
Variadic templates in Lazy.h

### ISSUE THREAD

**Issue by GilesBathgate** [CGAL/cgal#6382]
## Issue Details

In Lazy.h the code seems to predate variadic templates.

## Source Code

https://github.com/CGAL/cgal/blob/cb5cb46b5faf88b999bce9f1e1e527f62fa4bf21/Filtered_kernel/include/CGAL/Lazy.h#L2104-L2123

I think this can be re-written without the BOOST preprocessor macros, unless I have misunderstood the intention of using BOOST_PP_REPEAT

```c++
  template <class ...L>
  decltype(auto)
  operator()(L const &... l) const {
    typedef Lazy < AT, ET, E2A > Handle;
    CGAL_BRANCH_PROFILER(std::string(" failures/calls to   : ") + std::string(CGAL_PRETTY_FUNCTION), tmp);
    {
      Protect_FPU_rounding<Protection> P;
      try {
        return result_type(Handle(new Lazy_rep_n< AT, ET, AC, EC, E2A, noprune, L...>(ac, ec, l...)));
      } catch (Uncertain_conversion_exception&) {}
    }
    CGAL_BRANCH_PROFILER_BRANCH(tmp);
    Protect_FPU_rounding<!Protection> P2(CGAL_FE_TONEAREST);
    CGAL_expensive_assertion(FPU_get_cw() == CGAL_FE_TONEAREST);
    return result_type(Handle(new Lazy_rep_0< AT, ET, E2A >(ec(CGAL::exact(l)...))));
  }
```
It compiles with C++14. It would make reading the code much easier as well as improve debugging.

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Linux
* Compiler: C++14
* Release or debug mode: Release
* CGAL version: 5.4

**Comment by mglisse** [comment]
It may even be possible to add some perfect forwarding in there, because the actual moving in Lazy_rep_n takes place after the possibly throwing operations, although that would require adding some comments.

**Comment by GilesBathgate** [comment]
@mglisse I presume for that I have to change:

 ```c++
 operator()(L const &... l) const {
 ```
to
```c++
operator()(L const &&... l) const {
```

I don't know how to get that to compile.

**Comment by GilesBathgate** [comment]
@mglisse Can the same type of approach be used in Static_filtered_kernel:

https://github.com/CGAL/cgal/blob/6e4483a7d02497d87a53916aa92630ae194c3313/Filtered_kernel/include/CGAL/Static_filtered_predicate.h#L274-L319

Or is this too complicated for the ellipsis syntax...

**Comment by mglisse** [comment]
At least in C++14, I think it is too complicated to be worth the trouble, the result would likely not be very readable, and may have a runtime cost. Of course, if someone comes up with a nice formulation that contradicts my expectation, that's great.

**Comment by GilesBathgate** [comment]
> It may even be possible to add some perfect forwarding in there, because the actual moving in Lazy_rep_n takes place after the possibly throwing operations, although that would require adding some comments.

@mglisse Yes it is possible, but changes are needed to the mutable tuple in Lazy_rep_n. Here is a minimal example to demonstrate the issue:

```c++
template<class T> struct Lazy_reset_member_1 {
  void operator()(T& t)const{ t = T(); }  // compiler error here: cannot assign to variable 't' with const-qualified type 'const double &'
};
template<class T>void lazy_reset_member(T&t) {
  Lazy_reset_member_1<T>()(t);
}
template<class...T, std::size_t...i>void lazy_reset_member_tuple(std::tuple<T...>&t, std::index_sequence<i...>) {
  auto ignore = [](auto&&...){};
  ignore ( (lazy_reset_member(std::get<i>(t)), 0) ... );
}
template<class...T>void lazy_reset_member(std::tuple<T...>&t) {
  lazy_reset_member_tuple(t, std::make_index_sequence<sizeof...(T)>());
}

struct Lazy_rep {
  virtual void update_exact() const {}
};

template <typename... L>
class Lazy_rep_n : public Lazy_rep
{
  mutable std::tuple<L...> l;
  
  //potential fix:
  //mutable std::tuple<std::remove_cv_t<std::remove_reference_t<L>>...> l; 

public:
  Lazy_rep_n(L&&... ll) : l(std::forward<L>(ll)...) {}

  void update_exact() const {
    lazy_reset_member(l);
  }
};

struct Lazy_construction
{
  template <typename... L>
  Lazy_rep operator()(L&&... t) {
    return Lazy_rep_n<L...>(std::forward<L>(t)...);
  }
};

int main(int argc,char* argv[]) {

  const double x=1;
  Lazy_rep r = Lazy_construction()(x);
  r.update_exact();
}
```

The fix seems to be to make sure that the mutable tuple only contains copies:
```mutable std::tuple<std::remove_cv_t<std::remove_reference_t<L>>...> l; ```

**Comment by mglisse** [comment]
IIUC, I'd rather use `Lazy_rep_n<std::remove_cvref_t<L>...>`

**Comment by GilesBathgate** [comment]
> IIUC, I'd rather use `Lazy_rep_n<std::remove_cvref_t<L>...>`

Yeah you can do that, so in the example, it would give a `Lazy_rep_n<double...>` , instead of a `Lazy_rep<const double&...>` I figured if that was the only mutable member, then only the tuple should hold copies. But either way works.

As a side note apparently `std::remove_cvref_t<L>` is C++20
