### ISSUE TITLE
The bug of CGAL::intersection(Triangle_3, Triangle_3)

### ISSUE THREAD

**Issue by 147451753** [CGAL/cgal#6384]
Hi
 i use the fuction for intersection of two triangle CGAL version is 5.4 i use `CGAL::Exact_predicates_inexact_constructions_kernel` as `K` like this: `typedef CGAL::Exact_predicates_inexact_constructions_kernel K;`

The triangle data is below:
```
t1:
-1.2251099999999999,-5.8899699999999999,-7.987949999999999
0.40490799999999999,-6.0014500000000002,-3.314319999999999
-1.2251099999999999,-5.8899699999999999,-3.314319999999999
t2:
-0.21243100000000001,-5.7414293000000001,-4.50379500000000
-0.15238699999999999,-6.0416264999999996,-4.51681199999999
-0.56714299999999995,-5.9451375000000004,-4.37800200000000
```

CGAL::intersection(t1, t2) returns null

i follow the code,and find in function line:194  of `kernel_ftC3.h` when i use `CGAL::intersection(t1, t2)` exists a bug because of tol, the code in function `coplanar_orientationC3`
```
Ori oxy_pqr = orientationC2(px, py, qx, qy, rx, ry);
if (oxy_pqr != COLLINEAR)
  return oxy_pqr;
```
lead to an incorrect result.

When i change the `coplanar_orientationC3` as below, the result is ok

```
	template < class FT >
	CGAL_KERNEL_MEDIUM_INLINE
		typename Same_uncertainty_nt<Orientation, FT>::type
		coplanar_orientationC3(const FT& px, const FT& py, const FT& pz,
			const FT& qx, const FT& qy, const FT& qz,
			const FT& rx, const FT& ry, const FT& rz)
	{
		typedef typename Same_uncertainty_nt<Orientation, FT>::type  Ori;
                //the new code
		FT num[3] =
		{
			determinant(qx - px, qy - py, rx - px, ry - py),
			determinant(qy - py, qz - pz, ry - py, rz - pz),
			determinant(qx - px, qz - pz, rx - px, rz - pz)
		};

		FT fnum[3];
		for (int i = 0; i < 3; ++i)
		{
			fnum[i] = num[i] > 0 ? num[i] : -num[i];
		}
		int inx = fnum[1] > fnum[0] ? 1 : 0;

		inx = fnum[inx] > fnum[2] ? inx : 2;


		return enum_cast<Sign>(CGAL_NTS compare(num[inx], 0));
		/*the old code
	            Ori oxy_pqr = orientationC2(px, py, qx, qy, rx, ry);
			if (oxy_pqr != COLLINEAR)
				return oxy_pqr;

			Ori oyz_pqr = orientationC2(py, pz, qy, qz, ry, rz);
			if (oyz_pqr != COLLINEAR)
				return oyz_pqr;

			return orientationC2(px, pz, qx, qz, rx, rz);*/
	}
```

**Comment by MaelRL** [comment]
You're using an inexact construction kernel and so nothing is guaranteed. Your configuration is a degenerate configuration for the coplanar orientation test, and the kernel makes a mistake. You can use an exact construction kernel, or detect that there is an inconsistency between `CGAL::do_intersect(t1, t2)` and `CGAL::intersection(t1, t2)` and use an exact kernel only when that happens.

`coplanar_orientationC3` must have a global consistency, see [the concept](https://doc.cgal.org/latest/Kernel_23/classKernel_1_1CoplanarOrientation__3.html). This would be lost with your change.
