### ISSUE TITLE
PMP: Navtree and Reference Manual Index are not in sync

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#6385]
## Issue Details

If you look at "Combinatorial Repairing Functions" you can see that the entry page of the Reference Manual is not complete. 

![image](https://user-images.githubusercontent.com/3263539/156888972-af55cad5-8b26-433d-874e-ddedbcd9320c.png)

**Comment by sloriot** [comment]
One is manually generated (classified refman) and the other is automatically generated. I don't think it is meaningful to replicate it. Maybe we can add a link to the group at the end ?

**Comment by afabri** [comment]
In my opinion the content should be the same, but with potentially another order.  When you are on the index page the navtree node is **not** open. I was looking for a function for finding non-manifold vertices.  I saw only `is_non_manifold_vertex()` and was puzzled that we do not have a function for finding all vertices.  We should at least add a _See also_
