### ISSUE TITLE
CGAL Function to create polyhedron from polygon

### ISSUE THREAD

**Issue by TankTheSerker** [CGAL/cgal#6387]
Hi, I just want to ask if there's a function that can turn a polygon into a polyhedron. Just like the extrusion but all sides of the polygon, so it is expanding the polygon to create a mesh body

**Comment by sloriot** [comment]
Did you already see these overloads: [`extrude_mesh()`](https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__meshing__grp.html#ga102e1ba5d709c5e53e013160792e4d08)?

Polygon -> Mesh, you can use: [`add_face()`](https://doc.cgal.org/latest/BGL/group__PkgBGLEulerOperations.html#gaa386d0cdef3b5d6ef43d6b503392dbcd).

**Comment by TankTheSerker** [comment]
I was thinking of like when we put noodles into the water, it is enlarging. Not sure if extrusion is correct term but I want to apply isotropic_remeshing on a polygon. I got this error:
```
CGAL error: assertion violation!
Expression : !get(ecmap_, edge(hf, mesh_))
File       : C:\dev\vcpkg\installed\x86-windows\include\CGAL/Polygon_mesh_processing/internal/Isotropic_remeshing/remesh_impl.h
Line       : 1753
Explanation:
Refer to the bug-reporting instructions at https://www.cgal.org/bug_report.html
```

I used the degtri_sliding.off file from the samples. That is just flat face, so giving it some more weight is just an idea in able to use Istropic_remeshing but still not sure if it will work since I'm just studying CGAL functions

**Comment by sloriot** [comment]
This file contains degenerate triangles and the crash happens in a part dealing with degenerate triangles. You should open a dedicated issue for this one. cc @janetournois

**Comment by sloriot** [comment]
Especially, the calling code would be interesting as I see that you passed some constrained edges.

**Comment by janetournois** [comment]
Hello @TankTheSerker 
can you please send the code that generates this crash, so that we can reproduce the issue?
