### ISSUE TITLE
Visualisation of Skeleton and mesh segmentation result [question]

### ISSUE THREAD

**Issue by alshef** [CGAL/cgal#6394]
Hello,

I am trying to extract skeleton from my own mesh and visualyze it. I use the code from this example (https://github.com/CGAL/cgal/blob/master/Surface_mesh_skeletonization/examples/Surface_mesh_skeletonization/segmentation_example.cpp) and it works. 

But I can't find any code example or other information to get the pictures like these in docs
<img width="987" alt="Screenshot 2022-03-09 at 13 41 39" src="https://user-images.githubusercontent.com/26190621/157425963-1f3d1296-323e-41d0-b54d-1ca5d831ff59.png">
: 

Could you, please, help me with that?

**Comment by afabri** [comment]
You get that with the Polyhedron demo.

**Comment by alshef** [comment]
@afabri Thank you for the answer. I downloaded a precompiled binary of the demo for Windows OS. But I faced with a problem. The code from the example works but the same functionality (mean curvature skeleton) in demo is failed because of mesh is not closed. How could it be?
Could you, please, point out what I should do to get the skeleton with Polyhedron demo? 

I use 5.3 version of Polyhedron demo.

**Comment by sloriot** [comment]
What do you mean by "How could it be?" ? If you are using a mesh which is not closed, the skeleton algorithm will not work.

**Comment by zahrakheyrollahi** [comment]
what are the defualt setting polyhedron.demo for input display and input type?
@afabri 
@alshef 
@MaelRL
