### ISSUE TITLE
Arrangement_on_surface_2: obsolete documentation file?

### ISSUE THREAD

**Issue by albert-github** [CGAL/cgal#6419]
In the directory `Arrangement_on_surface_2/doc/Arrangement_on_surface_2/Concepts` of the current master there is a file `ArrangementClosedIdentifiedVerticalTraits_2.h`.

On the one hand in the documentation there it refers to `ArrangementClosedIdentifiedVerticalTraits_2` but in the class definition that folllows the class name is called `ArrangementVerticalSideTraits_2` whilst there is on the same directory a file `ArrangementVerticalSideTraits_2.h` with again a class `ArrangementVerticalSideTraits_2` but now refering to `ArrangementVerticalSideTraits_2`.

In the source code sections there is no evidence of a `ArrangementClosedIdentifiedVerticalTraits_2` class.

Note: `ArrangementClosedIdentifiedVerticalTraits_2` is also mentioned in `doc/Arrangement_on_surface_2/PackageDescription.txt`

**Comment by efifogel** [comment]
This indeed was erroneous. 
This is fixed now as part of PR #6408
