### ISSUE TITLE
Fast Boolean Operation of Polyhedra

### ISSUE THREAD

**Issue by FuzhangHe** [CGAL/cgal#6425]
## Fast Boolean Operation of Polyhedra in CGAL

For a Wood Drilling Simulation, i need to do about 5 000 to 10 000 times boolean operation between the drill bit and the tool.
Right row it takes about 2 hours for just 300 steps drilling interations. It will get longer and longer to calculate, because the wood polyhedra mesh will get more and more complicate und has more vertices and faces.

I have read in stackoverflow, that there maybe a fast boolean operation method in cgal. but i cannot find it.

https://stackoverflow.com/questions/18513484/cgal-is-there-a-fast-way-to-produce-the-intersection-of-two-polyhedra

can you please tell me, which function it is and how to use it ?

**Comment by sloriot** [comment]
I updated the post and add the link to the doc [here](https://doc.cgal.org/latest/Polygon_mesh_processing/index.html#title16).
