### ISSUE TITLE
Mesh_3: reference to unknown site

### ISSUE THREAD

**Issue by albert-github** [CGAL/cgal#6436]
In the Mesh_3 package there are a number of references to http://inrimage.gforge.inria.fr/, more precise:
```
Mesh_3/doc/Mesh_3/CGAL/Image_3.h:href="http://inrimage.gforge.inria.fr/">InrImage library</a>. It holds a
Mesh_3/doc/Mesh_3/Mesh_3.txt:`http://inrimage.gforge.inria.fr/`.
```
though this site cannot be found.

**Comment by lrineau** [comment]
It seems the new location, since the disparition of gforge.inria.fr, is now https://www-pequan.lip6.fr/~bereziat/inrimage/.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #6442
