### ISSUE TITLE
Manual: Link to unknown site 

### ISSUE THREAD

**Issue by albert-github** [CGAL/cgal#6437]
In the Manual, there are references to https://mpfi.gforge.inria.fr/ ,more precise:
```
Documentation/doc/Documentation/Third_party.txt:\mpfi can be downloaded from <A HREF="https://mpfi.gforge.inria.fr/">`https://mpfi.gforge.inria.fr/`</A>.
Documentation/doc/Documentation/Third_party.txt:<A HREF="https://mpfi.gforge.inria.fr/">`https://mpfi.gforge.inria.fr/`</A>.
```

though the site https://mpfi.gforge.inria.fr/ cannot be found.

**Comment by lrineau** [comment]
Now at https://gitlab.inria.fr/mpfi/mpfi

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request https://github.com/CGAL/cgal/pull/6443
