### ISSUE TITLE
Precondition violation in GPS::join() 

### ISSUE THREAD

**Issue by petersadro** [CGAL/cgal#644]
Hello,

When individually adding the second PolygonWithHoles to a GPS, I hit a precondition violation.
Expr: Base::number_of_outer_ccbs() == 1

CGAL version is from git ( to build debug version ).
SHA 1df32a4bd2a2678ea500fb98359e068da3b347c9 (Fri Jan 15 15:25:21 2016)

Kernel is EPEC.  The two PolygonWithHoles objects are the result of previous clipping operations. 
Looks like the winding is correct.

gist containing test program and data to reproduce this issue is at:
https://gist.github.com/petersadro/c622d95768f5e6e505c1

Pete

**Comment by sloriot** [comment]
There is a bug introduced with an optimization that was targeting 4.8. I'm trying to find a fix.

**Comment by sloriot** [comment]
Could you try with the following [patched file](https://github.com/sloriot/cgal/raw/434fb62b887463f3309d2e034e5cf51318cc49d8/Boolean_set_operations_2/include/CGAL/Boolean_set_operations_2/Gps_on_surface_base_2.h)?

**Comment by petersadro** [comment]
I'll give it a try tomorrow morning. Thank you.

**Comment by petersadro** [comment]
That patch fixed my GPS issue.  We can close this.

I came across this because I was building the debug version to track down another issue I am having with the 4.7 release.

Refine mesh (in  triangulation package )
I''ll create a test app and data for that issue this weekend.

Pete
