### ISSUE TITLE
Periodic_2_triangulation_2: Strange documentation.

### ISSUE THREAD

**Issue by albert-github** [CGAL/cgal#6440]
In the file Periodic_2_triangulation_2/classCGAL_1_1Periodic__2__triangulation__2.html we see:

![image](https://user-images.githubusercontent.com/5223533/159162342-e5a9b23e-6567-4f36-b7f6-f64ef41b13c8.png)

This is due to the description:
```
  \name Handles, Iterators and Circulators

  The vertices and faces of the triangulations are accessed through
  `handles`, `iterators` and `circulators`. The handles are \cgalModels of
  the concept `Handle` which basically offers the two dereference
```
in Periodic_2_triangulation_2/doc/Periodic_2_triangulation_2/CGAL/Periodic_2_triangulation_2.h
It looks like a mis-use of the ALIASES command `cgalModels`.

A better formulation would probably be:
```
  \name Handles, Iterators and Circulators

  The vertices and faces of the triangulations are accessed through
  `handles`, `iterators` and `circulators`. The handles are %CGAL \ref models "models" of
  the concept `Handle` which basically offers the two dereference
```
resulting in:

![image](https://user-images.githubusercontent.com/5223533/159162438-ac273c8b-d5cd-4b80-9e29-43c5bd384fed.png)

**Comment by albert-github** [comment]
any progress?

**Comment by sloriot** [comment]
You are perfectly right. Shall I create a PR or do you have it ready already?

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #6522
