### ISSUE TITLE
Polyhedron demo: shortest path plugin is in AABB_tree directory

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#646]
cc @maxGimeno

**Comment by maxGimeno** [comment]
Where should it be instead?

**Comment by sloriot** [comment]
`Shortest_path` for example

**Comment by maxGimeno** [comment]
Wouldn't it be better in Surface_mesh, as the CGAL packae is called
Surface_mesh_shortest_path ?

2016-01-18 21:07 GMT+01:00 Sebastien Loriot <notifications@github.com>:

**Comment by sloriot** [comment]
OK
