### ISSUE TITLE
Compatibility of CGAL parameters and Boost Parameter Library

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#6468]
### Boost Parameter
With parameters from the Boost Parameter Library, a parameter is:
  - a tag class, let's call it `Tag`,
  - and a keyword object of type `boost::parameter::keyword<Tag>`.

So, for example, the name `CGAL::parameters::max_iteration_number` is a reference to const of type:
```c++
const boost::parameter::keyword<CGAL::parameters::tag::max_iteration_number_>&
```

### CGAL named parameters, copied and adapted from BGL
With the CGAL named parameters inherited from the BGL, a parameter is:
  - a tag class `Tag`,
  - a function template with one argument of type `K`, returning a `CGAL::parameters::Named_function_parameters<K, Tag>`,
  - and a member function of that template class `CGAL::parameters::Named_function_parameters`, that allows the chaining of parameters using a `.`.

For example, `CGAL::parameters::do_not_use_cubic_algorithm<bool>`, is a function of type:
```c++
CGAL::Named_function_parameters<bool, Tag, CGAL::internal_np::No_property>(const bool&)
```
where `Tag` is `CGAL::internal_np::do_not_use_cubic_algorithm_t`.

### How to make those two compatible?

Maybe we could derive (or copy-paste) our own template class `CGAL::parameters::keyword<tag>` from `boost::parameter::keyword<Tag>`, to add a `template <typename T> operator()(const T&)` to it, returning a `CGAL::parameters::Named_function_parameters<K, Tag>`. That would allow to use the named parameters defined by the Boost Parameter Library in the framework of the CGAL parameters. So, example, `CGAL::parameters::do_not_use_cubic_algorithm` would no longer be a function template, but a function object with a template function member `operator()`.

## Part 2: compatibility of parameter packs

I have not really looked at that part.

In CGAL parameters, the parameter pack is the class template `CGAL::Named_function_parameters<Type, Tag, Base` itself, where `Base` is the tail of a recursive tuple-like implementation.

In Boost Parameter, [`ArgumentPack`] is a concept, and its concrete implementation is very complex. Its particularity is its `operator,` that allows to gather several arguments in a pack.

[`ArgumentPack`]: https://www.boost.org/doc/libs/1_78_0/libs/parameter/doc/html/reference.html#argumentpack

_Originally posted by @lrineau in https://github.com/CGAL/cgal/issues/6412#issuecomment-1085834357_

**Comment by sloriot** [comment]
What is the problem you are trying to solve?

**Comment by lrineau** [comment]
> What is the problem you are trying to solve?

One concrete example: [`CGAL::lloyd_optimize_mesh_2`](https://doc.cgal.org/5.4/Mesh_2/group__PkgMesh2Functions.html#ga5903d196ab84ecf1c1596c8892f7a6d4), in CGAL-5.4, uses named parameters from the Boost Parameter Library. Andreas would like to:
  - deprecated that function template,
  - add a new one with the same name, using the BGL-like named parameters.

The problem is the names of the named parameters, if we want to keep the same names and namespaces. For example, `CGAL::parameters::max_iteration_number` cannot be easily turned into something compatible with both the Boost Parameter Library and the CGAL BGL-like named parameters. That is the purpose of my ["Part 1"](https://github.com/CGAL/cgal/issues/6468#issue-1189724760) above.
