### ISSUE TITLE
Cannot run CMake for CGAL_ipelets demo: CGAL_Eigen3_support not found

### ISSUE THREAD

**Issue by jlvermeulen** [CGAL/cgal#6484]
## Issue Details

I'm trying to add the CGAL ipelets to ipe. When I download the source of the latest CGAL release (5.4) and run `cmake .` in the demo/CGAL_ipelets directory, I get the following error:

```
CMake Error at CMakeLists.txt:26 (include):
  include could not find requested file:

    CGAL_Eigen3_support
```

I tried to replace the line in question with `include(CGAL_Eigen_support)` as per issue #5603, but to no avail.

On a side-note, it would be great if someone could maintain a compiled version of these ipelets. I've tried to compile and integrate them myself on Windows before with no success whatsoever.

## Environment

* Operating system: Fedora 35
* Compiler: CMake 3.22.2
* CGAL version: 5.4
* Other libraries versions if used: eigen 3.3.9

**Comment by sloriot** [comment]
You should make sure you don't have an old CGAL installed on your system. Check CGAL_DIR in CMakeCache.txt if it is already generated.

**Comment by jlvermeulen** [comment]
@sloriot indeed it seemed like there were some remnants of an old CGAL version lingering about, even though I did not have any of the CGAL packages installed. The ipelets compiled fine once I deleted the /usr/local/lib64/cmake/CGAL directory. Thanks for the quick help!
