### ISSUE TITLE
Function CGAL::Polygon_mesh_processing::corefine_and_compute_intersection cannot be called more than once

### ISSUE THREAD

**Issue by GreenAvocado92** [CGAL/cgal#6490]
when I want to call function _CGAL::Polygon_mesh_processing::corefine_and_compute_intersection_ more than once， when runing , it  report error：

Explanation: COPLANAR_TRIANGLES: this point should never be reached!

how to use it：

   for (int i = 0; i < 2; i++) {
       CGAL::Polygon_mesh_processing::corefine_and_compute_intersection（mesh0, mesh1, out）;
   }

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows
* Compiler: VS2019
* Release or debug mode: Release
* Specific flags used (if any):
* CGAL version: 5.4

**Comment by janetournois** [comment]
It seems that this issue has been fixed. I just gave it a try with CGAL-5.6 and it does not report any error.
