### ISSUE TITLE
STL_Extension: Documentation boost unordered_set and unordered_map

### ISSUE THREAD

**Issue by albert-github** [CGAL/cgal#6511]
It looks like that boost has changed its documentation structure regarding the unordered functionality slightly.
Till the boost version 1.78.0 it looks like that the following links worked:
- https://www.boost.org/doc/libs/release/doc/html/boost/unordered_set.html
- https://www.boost.org/doc/libs/release/doc/html/boost/unordered_map.html

and automatically redirected to:
- https://www.boost.org/doc/libs/1_78_0/doc/html/boost/unordered_set.html
- https://www.boost.org/doc/libs/1_78_0/doc/html/boost/unordered_map.html

but with the 1.79.0 these generic links don't work anymore. It looks like they have to be replaced with
- https://www.boost.org/libs/unordered/doc/html/unordered.html#unordered_set
- https://www.boost.org/libs/unordered/doc/html/unordered.html#unordered_map

that redirect to:
- https://www.boost.org/doc/libs/1_79_0/libs/unordered/doc/html/unordered.html#unordered_set
- https://www.boost.org/doc/libs/1_79_0/libs/unordered/doc/html/unordered.html#unordered_map

The relevant places in the source code look like to be:
- STL_Extension/doc/STL_Extension/Concepts/Hashable.h:``\sa <A HREF="https://www.boost.org/doc/libs/release/doc/html/boost/unordered_set.html">`boost::unordered_set`</a>``
- STL_Extension/doc/STL_Extension/Concepts/Hashable.h:``\sa <A HREF="https://www.boost.org/doc/libs/release/doc/html/boost/unordered_map.html">`boost::unordered_map`</a>``

**Comment by afabri** [comment]
Wouldn't it make sense to tell the maintainers of boost to add a redirect?   I guess their `.htaccess` file is not under version control to make a PR.

**Comment by albert-github** [comment]
Probably yes, but it might be that they did the change on purpose (the page contents of set and map were joined).
You could try to contact the Boost maintainers and see what there reaction is (and how long it will take them to fix it).

**Comment by albert-github** [comment]
I just did a bit of searching and found their website repository at: https://github.com/boostorg/website/
It looks like the `.htaccess` is there as well.

**Comment by afabri** [comment]
Thanks for having investigated.  I just wrote an issue.

**Comment by albert-github** [comment]
Similar problems occur for:
- https://www.boost.org/doc/libs/release/libs/utility/utility.htm#results_of

that redirects to:
- https://www.boost.org/doc/libs/1_79_0/libs/utility/doc/html/index.html

instead of:
- https://www.boost.org/doc/libs/1_79_0/libs/utility/doc/html/utility/utilities/result_of.html

**Comment by afabri** [comment]
Reading this issue again, as boost.org does not redirect, we just have to change the URL as proposed by @albert-github.

**Comment by afabri** [comment]
Concerning `boost::result_of`  the link seems to be only [here ](https://doc.cgal.org/latest/Manual/preliminaries.html#title3).  @lrineau is it not somehow outdated to refer to the boost documentation?  If so can you give me a better URL please.

**Comment by afabri** [comment]
I would tend to link to  https://en.cppreference.com/w/cpp/types/result_of

**Comment by MaelRL** [comment]
> Concerning `boost::result_of` the link seems to be only [here ](https://doc.cgal.org/latest/Manual/preliminaries.html#title3). @lrineau is it not somehow outdated to refer to the boost documentation? If so can you give me a better URL please.

https://github.com/CGAL/cgal/blob/master/Documentation/doc/Documentation/Developer_manual/Chapter_code_format.txt#L261= also

**Comment by lrineau** [comment]
> Concerning `boost::result_of` the link seems to be only [here ](https://doc.cgal.org/latest/Manual/preliminaries.html#title3). @lrineau is it not somehow outdated to refer to the boost documentation? If so can you give me a better URL please.

The new URL is https://www.boost.org/doc/libs/release/libs/utility/doc/html/utility/utilities/result_of.html.

But I think all paragraphs or sections about `result_of` should be removed from the CGAL documentation. `result_of` was already old-style when C++11 was published. It cames from TR1.

**Comment by afabri** [comment]
**> If so can you give me a better URL please.**

**Comment by afabri** [comment]
I've just put the link I had proposed earlier:  https://en.cppreference.com/w/cpp/types/result_of

**Comment by lrineau** [comment]
> **> If so can you give me a better URL please.**

I have solved the issue: https://github.com/CGAL/cgal/pull/6659/commits/d9245b9cd63d024d401522fe32afd5d0126460b1
