### ISSUE TITLE
Guidelines need an overhaul

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#6513]
## Issue Details

In the guidelines we write things like ["Under no circumstance Jenny merges master into her feature branch."](https://github.com/CGAL/cgal/wiki/Developing-Features-with-Git#synchronizing-the-feature-branch).    This seems no longer to hold, and it would be good if @lrineau @sloriot and @MaelRL made a pass over the Guidelines in order to make update where necessary.

**Comment by lrineau** [comment]
Replace by #6527.
