### ISSUE TITLE
Solver_interface: Non reachable link to https://osqp.org/docs/interfaces/cc++

### ISSUE THREAD

**Issue by albert-github** [CGAL/cgal#6515]
In the file Solver_interface/include/CGAL/OSQP_quadratic_program_traits.h there is the reference to https://osqp.org/docs/interfaces/cc++#data-types though the page https://osqp.org/docs/interfaces/cc++ does not exist anymore, resulting in a 404 message from page doc_output/Solver_interface/classCGAL_1_1OSQP__quadratic__program__traits.html

On the page https://osqp.org/docs/interfaces/ there is tough:
![image](https://user-images.githubusercontent.com/5223533/165100490-7bb3c081-8c5e-4d60-ae4a-0be97182ec85.png)

though it is unclear which one to use.

**Comment by sloriot** [comment]
It should be 
https://osqp.org/docs/interfaces/C.html#c-interface
(I used webarchive to be sure)

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #6523

I used the link https://osqp.org/docs/interfaces/C.html#data-types as this directly points to the `c_float`. In case a link to the more general https://osqp.org/docs/interfaces/C.html#c-interface the text should be adjusted as well (feel free to discard this PR in favor of a more general formulation and link).
