### ISSUE TITLE
Arrangement_2：edges missed when use overlay

### ISSUE THREAD

**Issue by DoMoCo** [CGAL/cgal#6528]
![Capture](https://user-images.githubusercontent.com/22541710/165490544-dbf09687-b268-452d-8b2a-35123c8efa2b.JPG)

I get a bug which the result arrangement lost some edges when I use a arrangement overlay a grid arrangement, here is a triangle arrangement, see the picture. 

I have tested many cases, sometimes this problem occurs and sometimes not. 

My related code is shown below:
```
// both test_arr and overlay_arr are valid
overlay(test_arr, grid_arr_, overlay_arr, overlay_traits);
// get result
vertices.clear();
segments.clear();
if (overlay_arr.is_valid()) {
	for (auto vit = overlay_arr.vertices_begin(); vit != overlay_arr.vertices_end(); ++vit) {
		vertices.push_back(Point_3(vit->point().x(), vit->point().y(), 0));
	}

	// Print the arrangement edges.
	for (auto eit = overlay_arr.edges_begin(); eit != overlay_arr.edges_end(); ++eit) {
		auto source = eit->source()->point();
		auto target = eit->target()->point();
		segments.push_back(Segment_3(Point_3(source.x(), source.y(), 0), Point_3(target.x(), target.y(), 0)));
	}
}
```

**Comment by afabri** [comment]
Ideally you put a self contained cpp  on gist.github. com  so that we see what kernel you use, etc.

**Comment by DoMoCo** [comment]
Fine!
[GridMap_2.zip](https://github.com/CGAL/cgal/files/8571036/GridMap_2.zip)

**Comment by DoMoCo** [comment]
![Capture](https://user-images.githubusercontent.com/22541710/165659907-ac4a6ed1-7636-4b59-89ba-ae96c28f9cbd.JPG)
![Capture1](https://user-images.githubusercontent.com/22541710/165659916-910c8b83-7bba-414b-a3a4-5b3a4d6fd80e.JPG)
![Capture2](https://user-images.githubusercontent.com/22541710/165659920-999608ef-3985-4016-8e2e-50f403e0315a.JPG)

Sometimes I get the right result, sometimes I don't, I don't have any idea now.

**Comment by efifogel** [comment]
GridMap.h ?
Would be nice if you reduce the code to a minimal program...
   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by DoMoCo** [comment]
[overlay.zip](https://github.com/CGAL/cgal/files/8588216/overlay.zip)
I've struggled to build a minimal program without the visualization part.
During process，I got a hint of the problem through the debug mode, but I don't know what it means.
`CGAL error: precondition violation!
Expression : (m_traits.compare_y_at_x_2_object()(p, cv) == EQUAL) && compare_xy(cv.left(), p) == SMALLER && compare_xy(cv.right(), p) == LARGER`

CGAL version is 5.3.1.

**Comment by DoMoCo** [comment]
Sorry for my mistake.
Mybe it will be helpful which I reorganized the code with cmake.
By the way, what does the above error mean, there is very little relevant information.
[overlay.zip](https://github.com/CGAL/cgal/files/8595421/overlay.zip)

**Comment by efifogel** [comment]
First, to answer your question, the assertion implies that the program has
reached an invalid state.
Secondly, you are using an inexact kernel.
It seems to work fine when switching to a kernel of type
'Exact_predicates_exact_constructions_kernel'.
   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by DoMoCo** [comment]
Thank you, your answer is very useful.
