### ISSUE TITLE
Mesh3: unreachable page of ircad

### ISSUE THREAD

**Issue by albert-github** [CGAL/cgal#6539]
On the page: Mesh_3/index.html we see the link to https://www.ircad.fr/softwares/3Dircadb/3Dircadb1/index.phpthough this give a specific ircad 404 page not found message. Ircad has restructured its internet pages and the most likely page is now https://www.ircad.fr/research/software/ or one of its subpages.

The source file:
- Mesh_3/doc/Mesh_3/Mesh_3.txt

**Comment by afabri** [comment]
It should be this page : https://www.ircad.fr/research/data-sets/liver-segmentation-3d-ircadb-01/

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #6540
