### ISSUE TITLE
ch_quickhull_face_graph in convex_hull_3 bug

### ISSUE THREAD

**Issue by sukamay** [CGAL/cgal#6543]
_Please use the following template to help us solving your issue._

## Issue Details

I got EXC_BAD_ACCESS error when I run function extreme_points_3, follow the step I found that the error is thrown at CGAL/convex_hull_3.h
I found 3 points that may cause EXC_BAD_ACCESS
1) convex_hull_3.h line 849
in ch_quickhull_face_graph(std::list<typename Traits::Point_3>& points,
                        InputIterator point1_it, InputIterator point2_it, InputIterator point3_it,
                        PolygonMesh& P,
                        const Traits& traits)
...

    points.erase(point1_it);
    points.erase(point2_it);
    points.erase(point3_it);
    points.erase(max_it);
when max_it == point1_it or max_it == point2_it or max_it == point3_it
2) convex_hull_3.h line 682
in ch_quickhull_3_scan(TDS_2& tds,
                    std::list<typename TDS_2::Face_handle>& pending_facets,
                    const Traits& traits)
...
     typename Border_edges::iterator it = border.begin();
     Edge e = it->second;
    e.first->info() = 0;
    edges.push_back(e);
    border.erase(it);
when border is empty, border.erase(it) may cause EXC_BAD_ACCESS
3) convex_hull_3.h line 705
Vertex_handle vh = tds.star_hole(edges.begin(), edges.end(), visible_set.begin(), visible_set.end());
when edges is empty or visible_set is empty

I wanna to know if is the problem of my input points or it's the bug in convex_hull_3

## Source Code

      CGAL::extreme_points_3(CGAL::make_range(region.begin(), region.end()),
                        std::back_inserter(outline),
                        CGAL::make_extreme_points_traits_adapter(proj_point_map));
ps: my region is the indices array of property map proj_point_map and its indices is not continuous, does it matter?
region may looks like `region = [1,2,6,7,140,157]`

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Mac
* Compiler: gcc
* Release or debug mode: debug
* Specific flags used (if any):
* CGAL version: 5.4
* Boost version: 1.48
* Other libraries versions if used (Eigen, TBB, etc.): eigen3, jsoncpp

**Comment by afabri** [comment]
Can you please put a self contained cpp  on gist.github.com together with a data set so that we can try to reproduce and fix.
