### ISSUE TITLE
Comment error in Arr_segment_traits_2.h

### ISSUE THREAD

**Issue by 1833183060** [CGAL/cgal#6544]
## Issue Details
![image](https://user-images.githubusercontent.com/13117202/166230538-5769e458-dd61-4ffa-9af3-6d736254cae3.png)
in G:\lib\cgal-v5.3\Arrangement_on_surface_2\include\CGAL\Arr_segment_traits_2.h

Should it be "right"?Since it is in class Compare_y_at_x_right_2.

## Source Code
```
      // Compare the slopes of the two segments to determine their relative
      // position immediately to the left of q.
      // Notice we use the supporting lines in order to compare the slopes.
      return (kernel.compare_slope_2_object()(cv1.line(), cv2.line()));
```
## Environment

* Operating system (Windows,64 bits):
* Compiler:msvc
* CGAL version:5.3

**Comment by afabri** [comment]
Thank you.
