### ISSUE TITLE
CGAL/Polygon_mesh_processing/IO/ not found when installing cgal using .deb package

### ISSUE THREAD

**Issue by alpha027** [CGAL/cgal#6555]
_Please use the following template to help us solving your issue._

## Issue Details

I get this when I try to compile my program (same as example 3.4: https://doc.cgal.org/latest/Surface_mesh_segmentation/index.html)
I would like to mention that the installation of CGAL was done using the deb package (sudo apt-get install libcgal-dev)
 No such file or directory
    4 | #include <CGAL/Polygon_mesh_processing/IO/polygon_mesh_io.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
I went to the following directory: `usr/include/CGAL/Polygon_mesh_processing` I found no IO folder with `polygon_mesh_io.h` file in it. I also went to the parent directory and searched for the file `polygon_mesh_io.h` but could not find it.

Does the .deb package have less functionalities that the github repo code ?

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Ubuntu 20.04
* Compiler: g++ 9.4.0
* Release or debug mode: Release 
* CGAL version: (5.4)

**Comment by sloriot** [comment]
You should check the version of CGAL, but most probably it is not 5.4. Open `/usr/include/CGAL/version.h`.

**Comment by alpha027** [comment]
Got it ! I actually did install using the .tar library and it worked, I just wanted to know what was wrong with my program when CGAL was installed using .deb. Thanks a lot for your quick replies !
