### ISSUE TITLE
Remove duplicate vertices and invalid triangles from CgalMesh while preserving the attributes

### ISSUE THREAD

**Issue by soodsumil** [CGAL/cgal#6566]
Hi,
Currently I am using CGAL's 3d Boolean operations to perform Union. difference and intersect. I am also attaching a attribute ID to each face of the mesh following this example:
https://github.com/CGAL/cgal/blob/master/Polygon_mesh_processing/examples/Polygon_mesh_processing/corefinement_mesh_union_with_attributes.cpp

However this Boolean operation fails many times because of duplicate vertices or invalid triangles that needs to be removed before performing the operation. Currently I convert the cgalmesh to polygon soup perform the `merge_duplicate_points_in_polygon_soup` and `merge_duplicate_polygons_in_polygon_soup` operation to the soup and then convert it back. However with this method my attribute ID is not conserved for the polygons or faces and I lose that data.

Is there a way to remove duplicate and invalid data directly on the cgalmesh that can also preserve my attribute data?

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows 64 bit
* Compiler: Visual Studio 2019
* Release or debug mode: Release
* Specific flags used (if any):
* CGAL version: 5.3
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by sloriot** [comment]
Did you try calling [`CGAL::Polygon_mesh_processing::stitch_borders()`](https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__repairing__grp.html#ga8ae4352e67d2b099994ac8990c13bd41) ?

**Comment by MaelRL** [comment]
bump @soodsumil
