### ISSUE TITLE
Cgal constrained 2d triangulation of a polygon does not consider holes

### ISSUE THREAD

**Issue by Sumilsood** [CGAL/cgal#6567]
_Please use the following template to help us solving your issue._

Hi,
I am following the example given here to triangulate a 2d polygon.
https://doc.cgal.org/latest/Triangulation_2/Triangulation_2_2polygon_triangulation_8cpp-example.html

However, when I try to input a polygon with holes it does not work. If I give two polygons as inputs it does not consider the second polygon as a hole and gives different result.
Does CGAL support triangulating polygons with holes. If yes then is there an example that can help me implement it.

Thank you

_Describe your issue. Please be specific (compilation error, runtime error, unexpected behavior, wrong results, etc.)._

## Source Code

_If your issue arises by using CGAL in your own source code, please provide a minimalist example that we can compile easily to reproduce the bug. If your issue arises from using a CGAL program (demo, example, etc.), please let us know which one. Helping you solving an issue is much easier and efficient if we can reproduce it._

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows 64bit
* Compiler: VS 2019
* Release or debug mode: Release
* Specific flags used (if any):
* CGAL version: 5.3
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by afabri** [comment]
You might have a look at the pull request #6412

**Comment by afabri** [comment]
> You might have a look at the pull request #6412

@Sumilsood did you give this a try?   Can we close the issue?
