### ISSUE TITLE
Linear_cell_complex:  Failure in a testsuite

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#6579]
## Issue Details
In this [VC2015 testuite ](https://cgal.geometryfactory.com/CGAL/testsuite/results-5.5-Ic-83.shtml#Linear_cell_complex) we get an assertion.  
```
------------------------------------------------------------------
- Linear_cell_complex/ProgramOutput.execution___of__Linear_cell_complex_copy_test
------------------------------------------------------------------

CGAL::Random()::get_seed() = 1652389513
Linear cell complex copy test (v1).Assertion failed: false, file C:\CGAL_ROOT\CGAL-5.5-Ic-83\test\Linear_cell_complex\Linear_cell_complex_copy_test.cpp, line 83
```
I could not reproduce it locally (in the master branch), also not by inserting 
```
CGAL::get_default_random() = CGAL::Random(1652389513);
```
as first line in `main()`.    This is maybe not enough as at the same time the function `rand()` is used. 

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows 64bit
* Compiler:  VC2015
* Release or debug mode: Debug
* Specific flags used (if any):
* CGAL version:
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by sloriot** [comment]
Also [here](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.5-Ic-22/Linear_cell_complex/TestReport_Sosno_MSVC-2022-Community-Release.gz) and [there](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.5-Ic-32/Linear_cell_complex/TestReport_Sosno_MSVC-2022-Community-Release.gz).

**Comment by gdamiand** [comment]
Thanks. I will look.

**Comment by afabri** [comment]
The first step might be to replace the call of `rand()`   and wait for the next failure,
