### ISSUE TITLE
AABB_tree: Incorrect documentation

### ISSUE THREAD

**Issue by albert-github** [CGAL/cgal#6582]
Doing some extra tests on the CGAL documentation (setting `GENERATE_XML=YES`), the following warning appeared:
```
.../AABB_tree/include/CGAL/AABB_tree.h:565: warning: argument 'last' of command @param is not found in the argument list of CGAL::AABB_tree< AABBTraits >::expand(Node &node, ConstPrimitiveIterator first, ConstPrimitiveIterator beyond, const std::size_t range, const ComputeBbox &compute_bbox, const SplitPrimitives &split_primitives, const AABBTraits &)
.../AABB_tree/include/CGAL/AABB_tree.h:565: warning: The following parameters of CGAL::AABB_tree::expand(Node &node, ConstPrimitiveIterator first, ConstPrimitiveIterator beyond, const std::size_t range, const ComputeBbox &compute_bbox, const SplitPrimitives &split_primitives, const AABBTraits &) are not documented:
  parameter 'node'
  parameter 'beyond'
  parameter 'compute_bbox'
  parameter 'split_primitives'
```

Even though the function is not part of the official documentation the documentation of the function should be correct.

**Comment by albert-github** [comment]
To be honest I wouldn't as I think **all* functions should be documented properly to show their intention for future maintainers.
The documentation in the code is not just for the outside world but also for maintainers / people who want to extend code.

**Comment by afabri** [comment]
I added the parameters in PR #6629, but just state that it are two functors.  While it is true that documenting also all private functions would be great this is currently not a realistic option.

**Comment by MaelRL** [comment]
Fixed by https://github.com/CGAL/cgal/pull/6629.
