### ISSUE TITLE
Combinatorial_map is not thread-safe

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#659]
In `<CGAL/Combinatorial_map.h`, there is a non-static variable:
```C++
    static Null_handle_type null_handle;
```
That variable makes the code non-thread-safe.

@gdamiand, what is its purpose? What is the difference with `null_dart_handle`, that was made non-static in recent releases of CGAL?

**Comment by gdamiand** [comment]
null_handle equals to NULL. The purpose of this variable is to allow to change the type of handle, and thus replace null_handle by something else (for example 0 if we use index instead of handle).

Since this variable is undocumented and used only internally; we can perhaps simply make it non static.

**Comment by gdamiand** [comment]
@lrineau is this commit https://github.com/gdamiand/cgal/commit/60d44ab38bd390e7f836b6545ea2059fc21391f6 solves the problem ? (In fact it is a bug that this null_handle variable is non const).

**Comment by lrineau** [comment]
Probably having that variable `static const` solves the issue: the variable content is initialized before the execution of threads, and there cannot be any race-conditions.

I think there is also a `null_handle` in the file `Combinatorial_map/include/CGAL/Combinatorial_map_storages.h`.

**Comment by gdamiand** [comment]
I agree.

And even if the variable is initialized by several threads, I think it cannot be a problem because it will be initialized with the same value.

I don't understand your remark about the null_handle variable in the file Combinatorial_map_storages.h: this is the place where I modified it ?

**Comment by lrineau** [comment]
* For the thread-safety of the initialization by several threads, you are wrong: the variable is not atomic. If it is initialized by several threads, then there is a race-condition.

* As for `<CGAL/Combinatorial_map.h>`/`<CGAL/Combinatorial_map_storages.h>`:
For the moment in `master`, there are two static member variables named `null_handle`:
```
/home/lrineau/Git/cgal/Combinatorial_map/include/CGAL/Combinatorial_map.h
103:    static Null_handle_type null_handle;

/home/lrineau/Git/cgal/Combinatorial_map/include/CGAL/Combinatorial_map_storages.h
62:    static Null_handle_type null_handle;
```

**Comment by gdamiand** [comment]
Who developed this code ?? ;)
(corrected now in this commit https://github.com/CGAL/cgal-dev/commit/7810d3b6309e3467b18493a808a8805c9d47c3d1 : thanks @lrineau).

**Comment by gdamiand** [comment]
@lrineau This issue can be closed (by PR https://github.com/CGAL/cgal/pull/701).
