### ISSUE TITLE
`CGAL::do_intersect` on `Segment_3` is Ambiguous in v5.4

### ISSUE THREAD

**Issue by KermMartian** [CGAL/cgal#6600]
## Issue Details

Up to v5.3.1, calling `CGAL::do_intersect()` on two `Segment_3`s works as expected (the following program prints `3D segments do intersect`). In v5.4, the following minimum (non-)working example does not compile; CGAL's internal call to `do_intersect` is ambiguous. The two possible candidates between which the compiler cannot distinguish are https://github.com/CGAL/cgal/blob/c58ac97e93c838ebfb1e8adaf23ff4fd185dc8e4/Intersections_3/include/CGAL/Intersections_3/internal/Line_3_Line_3_do_intersect.h#L20-L24 and https://github.com/CGAL/cgal/blob/c58ac97e93c838ebfb1e8adaf23ff4fd185dc8e4/Boolean_set_operations_2/include/CGAL/Boolean_set_operations_2/do_intersect.h#L237-L240 .

## Source Code

```
#include <CGAL/Exact_predicates_exact_constructions_kernel.h>

using CGAL_Kernel = CGAL::Exact_predicates_exact_constructions_kernel;
using Point_3 = CGAL::Point_3<CGAL_Kernel>;
using Segment_3 = CGAL_Kernel::Segment_3;

int main(int argc, char* argv[]) {
        Segment_3 seg1(Point_3(1., 1.5, 1.), Point_3(1., 1.5, 10.5));           // Vertical in the Z axis
        Segment_3 seg2(Point_3(-3.5, 1.5, 2.2), Point_3(42., 1.5, 2.2));        // Horizontal in X axis, intersecting
        const bool intersects = CGAL::do_intersect(seg1, seg2);
        printf("3D segments do%s intersect\n", intersects ? "" : " not");
        return 0;
}
```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Ubuntu 20.04 LTS
* Compiler: clang version 12.0.0-3ubuntu1~20.04.5
* Release or debug mode: Release
* Specific flags used (if any): `-O3 -DNDEBUG`
* CGAL version: v5.4
* Boost version: 1.78
* Other libraries versions if used (Eigen, TBB, etc.): n/a

**Comment by sloriot** [comment]
I can't reproduce it with 5.4 and master with clang 11.0.1-2. I'll try to get the same compiler to give it a try.

**Comment by sloriot** [comment]
Still no luck with clang version 12.0.1

**Comment by sloriot** [comment]
@KermMartian could it be that you have several CGAL version installed that could end up in the include path? Could you share the whole error stack?

**Comment by KermMartian** [comment]
I'll take a look on a fresh Ubuntu VM and provide the stack if I can reproduce it again.

**Comment by pentacular** [comment]
I just got hit by this as well. :)

Fortunately it seems that we can resolve the ambiguity by a little qualification.

@KermMartian could you confirm this solves your issue as well?

**Comment by lrineau** [comment]
> I just got hit by this as well. :)
> 
> Fortunately it seems that we can resolve the ambiguity by a little qualification.
> 
> @KermMartian could you confirm this solves your issue as well?

Can you please post a way to reproduce the issue? So far we cannot.

**Comment by pentacular** [comment]
This does the trick for me.

```
#include <CGAL/Boolean_set_operations_2.h>
#include <CGAL/Polygon_mesh_processing/corefinement.h>
#include <CGAL/Surface_mesh.h>

void minimal() {
  typedef CGAL::Exact_predicates_exact_constructions_kernel Kernel;
  typedef Kernel::Point_3 Point;
  typedef CGAL::Surface_mesh<Point> Surface_mesh;
  Surface_mesh mesh;
  CGAL::Polygon_mesh_processing::experimental::
      autorefine_and_remove_self_intersections(mesh);
}
```

**Comment by afabri** [comment]
I can reproduce it with clang on Windows.    VC++ does not have the problem.  I first thought that it is maybe because no header for a kernel is included but  that is not the problem.

**Comment by afabri** [comment]
And I can confirm that it  goes away when I apply what @pentacular suggests.

**Comment by afabri** [comment]
We might have other combinations of header files that have the same problem as there are plenty of  `do_intersect()`  when I see the list of candidates in the  Search Box in the online documentation.

**Comment by lrineau** [comment]
> This does the trick for me.
> 
> ```c++
> #include <CGAL/Boolean_set_operations_2.h>
> #include <CGAL/Polygon_mesh_processing/corefinement.h>
> #include <CGAL/Surface_mesh.h>
> 
> void minimal() {
>   typedef CGAL::Exact_predicates_exact_constructions_kernel Kernel;
>   typedef Kernel::Point_3 Point;
>   typedef CGAL::Surface_mesh<Point> Surface_mesh;
>   Surface_mesh mesh;
>   CGAL::Polygon_mesh_processing::experimental::
>       autorefine_and_remove_self_intersections(mesh);
> }
> ```

Me too I can reproduce on Linux with clang-14. The error is:
```
/home/lrineau/Git/cgal-master/Intersections_3/include/CGAL/Intersections_3/internal/Segment_3_Segment_3_do_intersect.h:33:12: error: 
      call to 'do_intersect' is ambiguous
  bool b = do_intersect(s1.supporting_line(), s2.supporting_line(), k);
           ^~~~~~~~~~~~
/home/lrineau/Git/cgal-master/Kernel_23/include/CGAL/Kernel/function_objects.h:3036:39: note: in
      instantiation of function template specialization
      'CGAL::Intersections::internal::do_intersect<CGAL::Simple_cartesian<CGAL::Interval_nt<false>>>'
      requested here
    { return Intersections::internal::do_intersect(t1, t2, K()); }
                                      ^
[...]
/home/lrineau/Git/cgal-master/Intersections_3/include/CGAL/Intersections_3/internal/Line_3_Line_3_do_intersect.h:22:1: note: 
      candidate function [with K = CGAL::Simple_cartesian<CGAL::Interval_nt<false>>]
do_intersect(const typename K::Line_3& l1,
^
/home/lrineau/Git/cgal-master/Boolean_set_operations_2/include/CGAL/Boolean_set_operations_2/do_intersect.h:239:13: note: 
      candidate function [with InputIterator =
      CGAL::Line_3<CGAL::Simple_cartesian<CGAL::Interval_nt<false>>>, Traits = const
      CGAL::Simple_cartesian<CGAL::Interval_nt<false>>]
inline bool do_intersect(InputIterator begin, InputIterator end, Traits& traits,
            ^
```

So the ambiguity is between the right `do_intersect` function from the kernel, and:
```c++
template<typename InputIterator , typename Traits > 
bool do_intersect(InputIterator begin, InputIterator end, Traits& traits);
```
from `Boolean_set_operations_2/include/CGAL/Boolean_set_operations_2/do_intersect.h`, [documented here](https://doc.cgal.org/latest/Boolean_set_operations_2/group__boolean__do__intersect.html#gaa7cd339cba1f0c8eb0d337fe9f98790b).

**Comment by HolenWu** [comment]
I've also been stuck with this problem recently. This problem keeps appearing, even with the latest version of CGAL. On Ubuntu 22.04 LTS 64bit with clang-14.

**Comment by HolenWu** [comment]
> > This does the trick for me.
> > ```c++
> > #include <CGAL/Boolean_set_operations_2.h>
> > #include <CGAL/Polygon_mesh_processing/corefinement.h>
> > #include <CGAL/Surface_mesh.h>
> > 
> > void minimal() {
> >   typedef CGAL::Exact_predicates_exact_constructions_kernel Kernel;
> >   typedef Kernel::Point_3 Point;
> >   typedef CGAL::Surface_mesh<Point> Surface_mesh;
> >   Surface_mesh mesh;
> >   CGAL::Polygon_mesh_processing::experimental::
> >       autorefine_and_remove_self_intersections(mesh);
> > }
> > ```
> 
> Me too I can reproduce on Linux with clang-14. The error is:
> 
> ```
> /home/lrineau/Git/cgal-master/Intersections_3/include/CGAL/Intersections_3/internal/Segment_3_Segment_3_do_intersect.h:33:12: error: 
>       call to 'do_intersect' is ambiguous
>   bool b = do_intersect(s1.supporting_line(), s2.supporting_line(), k);
>            ^~~~~~~~~~~~
> /home/lrineau/Git/cgal-master/Kernel_23/include/CGAL/Kernel/function_objects.h:3036:39: note: in
>       instantiation of function template specialization
>       'CGAL::Intersections::internal::do_intersect<CGAL::Simple_cartesian<CGAL::Interval_nt<false>>>'
>       requested here
>     { return Intersections::internal::do_intersect(t1, t2, K()); }
>                                       ^
> [...]
> /home/lrineau/Git/cgal-master/Intersections_3/include/CGAL/Intersections_3/internal/Line_3_Line_3_do_intersect.h:22:1: note: 
>       candidate function [with K = CGAL::Simple_cartesian<CGAL::Interval_nt<false>>]
> do_intersect(const typename K::Line_3& l1,
> ^
> /home/lrineau/Git/cgal-master/Boolean_set_operations_2/include/CGAL/Boolean_set_operations_2/do_intersect.h:239:13: note: 
>       candidate function [with InputIterator =
>       CGAL::Line_3<CGAL::Simple_cartesian<CGAL::Interval_nt<false>>>, Traits = const
>       CGAL::Simple_cartesian<CGAL::Interval_nt<false>>]
> inline bool do_intersect(InputIterator begin, InputIterator end, Traits& traits,
>             ^
> ```
> 
> So the ambiguity is between the right `do_intersect` function from the kernel, and:
> 
> ```c++
> template<typename InputIterator , typename Traits > 
> bool do_intersect(InputIterator begin, InputIterator end, Traits& traits);
> ```
> 
> from `Boolean_set_operations_2/include/CGAL/Boolean_set_operations_2/do_intersect.h`, [documented here](https://doc.cgal.org/latest/Boolean_set_operations_2/group__boolean__do__intersect.html#gaa7cd339cba1f0c8eb0d337fe9f98790b).

I've also been stuck with this problem recently. This problem keeps appearing, even with the latest version of CGAL. On Ubuntu 22.04 LTS 64bit with clang-14.

**Comment by lrineau** [comment]
> We might have other combinations of header files that have the same problem as there are plenty of `do_intersect()` when I see the list of candidates in the Search Box in the online documentation.

Maybe we would create a super-header including everything, and test it in the testsuite.

**Comment by HolenWu** [comment]
> > We might have other combinations of header files that have the same problem as there are plenty of `do_intersect()` when I see the list of candidates in the Search Box in the online documentation.
> 
> Maybe we would create a super-header including everything, and test it in the testsuite.

What confuses me is that everything works fine when using GCC.

**Comment by pentacular** [comment]
There are many disagreements between clang and gcc regarding what they consider to be ambiguous template invocations.

The problem is probably that this template accepts any three arguments of any type.

```
template<typename InputIterator , typename Traits > 
bool do_intersect(InputIterator begin, InputIterator end, Traits& traits);
```

If this could be restricted to some base class for InputIterator, etc, then I expect the problem would go away.

**Comment by afabri** [comment]
Some `enable_if`-magic to test for being an iterator??

**Comment by pentacular** [comment]
I think that would make sense, but I'm not really sure what is expected of that do_intersect function -- which is why I opted to constrain the other end in my fix.

**Comment by afabri** [comment]
> Some `enable_if`-magic to test for being an iterator??

@lrineau is that not easy to implement following recipes on [stackoverflow](https://stackoverflow.com/questions/4335962/how-to-check-if-a-template-parameter-is-an-iterator-type-or-not)?

**Comment by afabri** [comment]
@MaelRL just pointed out that we have  [CGAL/is_iterator.h](https://github.com/CGAL/cgal/blob/master/STL_Extension/include/CGAL/is_iterator.h)

**Comment by afabri** [comment]
And that is also the way it is done for [`intersection()`](https://github.com/CGAL/cgal/blob/master/Boolean_set_operations_2/include/CGAL/Boolean_set_operations_2/intersection.h#L292)
