### ISSUE TITLE
Nef_polyhedron_3 build error as following.

### ISSUE THREAD

**Issue by houlewei** [CGAL/cgal#6614]
_Please use the following template to help us solving your issue._

## Issue Details
Error		'class CGAL::HalfedgeDS_in_place_list_face<CGAL::I_Polyhedron_facet<CGAL::HalfedgeDS_face_base<CGAL::HalfedgeDS_list_types<CGAL::Epeck, CGAL::I_Polyhedron_derived_items_3<CGAL::Polyhedron_items_3>, std::allocator<int> >, CGAL::Boolean_tag<true>, CGAL::Plane_3<CGAL::Epeck> > > >' has no member named 'id'	linux-debug	/usr/include/CGAL/boost/graph/properties.h

## Source Code
Why I get these errors, do I missing some headers when I use Nef_polyhedron_3 to calc boolean opearations?

## Environment

* Operating system (Ubuntu 64 bits):
* Compiler: /usr/bin/c++   -g -std=gnu++20 -MD -MT 
* Release or debug mode: Debug
* Specific flags used (if any):
* CGAL version: 5.4
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by afabri** [comment]
Hello @houw, can you please put a self-contained cpp on gist.github,com so that we can try to reproduce.

**Comment by MaelRL** [comment]
bump @houw
