### ISSUE TITLE
get the error : undefined reference to `__gmpz_init'

### ISSUE THREAD

**Issue by houw** [CGAL/cgal#6621]
_Please use the following template to help us solving your issue._

## Issue Details

1>Linking objects
1>/usr/bin/ld : error : /root/projects/TestCGAL/obj/x64/Debug/CGALExmaple.o: in function `boost::multiprecision::backends::gmp_int::gmp_int()':
1>/usr/include/boost/multiprecision/gmp.hpp(1130): error : undefined reference to `__gmpz_init'
1>/usr/bin/ld : error : /root/projects/TestCGAL/obj/x64/Debug/CGALExmaple.o: in function `boost::multiprecision::backends::gmp_int::gmp_int(boost::multiprecision::backends::gmp_int const&)':
1>/usr/include/boost/multiprecision/gmp.hpp(1135): error : undefined reference to `__gmpz_init_set'
1>/usr/bin/ld : error : /usr/include/boost/multiprecision/gmp.hpp:1137: undefined reference to `__gmpz_init'
1>/usr/bin/ld : error : /root/projects/TestCGAL/obj/x64/Debug/CGALExmaple.o: in function `boost::multiprecision::backends::gmp_int::operator=(boost::multiprecision::backends::gmp_int&&)':
1>/usr/include/boost/multiprecision/gmp.hpp(1177): error : undefined reference to `__gmpz_swap'
1>/usr/bin/ld : error : /root/projects/TestCGAL/obj/x64/Debug/CGALExmaple.o: in function `boost::multiprecision::backends::gmp_int::operator=(long)':
1>/usr/include/boost/multiprecision/gmp.hpp(1232): error : undefined reference to `__gmpz_init'
1>/usr/bin/ld : error : /usr/include/boost/multiprecision/gmp.hpp:1233: undefined reference to `__gmpz_set_si'
1>/usr/bin/ld : error : /root/projects/TestCGAL/obj/x64/Debug/CGALExmaple.o: in function `boost::multiprecision::backends::gmp_int::~gmp_int()':
1>/usr/include/boost/multiprecision/gmp.hpp(1395): error : undefined reference to `__gmpz_clear'
1>/usr/bin/ld : error : /root/projects/TestCGAL/obj/x64/Debug/CGALExmaple.o: in function `boost::multiprecision::backends::gmp_int::compare(boost::multiprecision::backends::gmp_int const&) const':
1>/usr/include/boost/multiprecision/gmp.hpp(1405): error : undefined reference to `__gmpz_cmp'
1>/usr/bin/ld : error : /root/projects/TestCGAL/obj/x64/Debug/CGALExmaple.o: in function `boost::multiprecision::backends::gmp_int::compare(long) const':
1>/usr/include/boost/multiprecision/gmp.hpp(1410): error : undefined reference to `__gmpz_cmp_si'
1>/usr/bin/ld : error : /root/projects/TestCGAL/obj/x64/Debug/CGALExmaple.o: in function `boost::multiprecision::backends::eval_multiply(boost::multiprecision::backends::gmp_int&, boost::multiprecision::backends::gmp_int const&, boost::multiprecision::backends::gmp_int const&)':
1>/usr/include/boost/multiprecision/gmp.hpp(1611): error : undefined reference to `__gmpz_mul'
1>/usr/bin/ld : error : /root/projects/TestCGAL/obj/x64/Debug/CGALExmaple.o: in function `boost::multiprecision::backends::eval_divide(boost::multiprecision::backends::gmp_int&, boost::multiprecision::backends::gmp_int const&, boost::multiprecision::backends::gmp_int const&)':
1>/usr/include/boost/multiprecision/gmp.hpp(1617): error : undefined reference to `__gmpz_tdiv_q'
1>/usr/bin/ld : error : /root/projects/TestCGAL/obj/x64/Debug/CGALExmaple.o: in function `boost::multiprecision::backends::eval_abs(boost::multiprecision::backends::gmp_int&, boost::multiprecision::backends::gmp_int const&)':
1>/usr/include/boost/multiprecision/gmp.hpp(1727): error : undefined reference to `__gmpz_abs'
1>/usr/bin/ld : error : /root/projects/TestCGAL/obj/x64/Debug/CGALExmaple.o: in function `boost::multiprecision::backends::eval_gcd(boost::multiprecision::backends::gmp_int&, boost::multiprecision::backends::gmp_int const&, boost::multiprecision::backends::gmp_int const&)':
1>/usr/include/boost/multiprecision/gmp.hpp(1732): error : undefined reference to `__gmpz_gcd'
1>/usr/bin/ld : error : /root/projects/TestCGAL/obj/x64/Debug/CGALExmaple.o: in function `boost::multiprecision::backends::gmp_rational::gmp_rational()':
1>/usr/include/boost/multiprecision/gmp.hpp(1897): error : undefined reference to `__gmpq_init'
1>/usr/bin/ld : error : /root/projects/TestCGAL/obj/x64/Debug/CGALExmaple.o: in function `boost::multiprecision::backends::gmp_rational::gmp_rational(boost::multiprecision::backends::gmp_rational const&)':
1>/usr/include/boost/multiprecision/gmp.hpp(1901): error : undefined reference to `__gmpq_init'
1>/usr/bin/ld : error : /usr/include/boost/multiprecision/gmp.hpp:1903: undefined reference to `__gmpq_set'
1>/usr/bin/ld : error : /root/projects/TestCGAL/obj/x64/Debug/CGALExmaple.o: in function `boost::multiprecision::backends::gmp_rational::operator=(boost::multiprecision::backends::gmp_rational const&)':
1>/usr/include/boost/multiprecision/gmp.hpp(1931): error : undefined reference to `__gmpq_init'
1>/usr/bin/ld : error : /usr/include/boost/multiprecision/gmp.hpp:1932: undefined reference to `__gmpq_set'
1>/usr/bin/ld : error : /root/projects/TestCGAL/obj/x64/Debug/CGALExmaple.o: in function `boost::multiprecision::backends::gmp_rational::operator=(boost::multiprecision::backends::gmp_rational&&)':
1>/usr/include/boost/multiprecision/gmp.hpp(1938): error : undefined reference to `__gmpq_swap'
1>/usr/bin/ld : error : /root/projects/TestCGAL/obj/x64/Debug/CGALExmaple.o: in function `boost::multiprecision::backends::gmp_rational::operator=(long)':
1>/usr/include/boost/multiprecision/gmp.hpp(1981): error : undefined reference to `__gmpq_init'
1>/usr/bin/ld : error : /usr/include/boost/multiprecision/gmp.hpp:1982: undefined reference to `__gmpq_set_si'
1>/usr/bin/ld : error : /root/projects/TestCGAL/obj/x64/Debug/CGALExmaple.o: in function `boost::multiprecision::backends::gmp_rational::operator=(double)':
1>/usr/include/boost/multiprecision/gmp.hpp(1988): error : undefined reference to `__gmpq_init'
1>/usr/bin/ld : error : /usr/include/boost/multiprecision/gmp.hpp:1989: undefined reference to `__gmpq_set_d'
1>/usr/bin/ld : error : /root/projects/TestCGAL/obj/x64/Debug/CGALExmaple.o: in function `boost::multiprecision::backends::gmp_rational::swap(boost::multiprecision::backends::gmp_rational&)':
1>/usr/include/boost/multiprecision/gmp.hpp(2076): error : undefined reference to `__gmpq_swap'
1>/usr/bin/ld : error : /root/projects/TestCGAL/obj/x64/Debug/CGALExmaple.o: in function `boost::multiprecision::backends::gmp_rational::~gmp_rational()':
1>/usr/include/boost/multiprecision/gmp.hpp(2094): error : undefined reference to `__gmpq_clear'
1>/usr/bin/ld : error : /root/projects/TestCGAL/obj/x64/Debug/CGALExmaple.o: in function `boost::multiprecision::backends::gmp_rational::negate()':
1>/usr/include/boost/multiprecision/gmp.hpp(2099): error : undefined reference to `__gmpq_neg'
1>/usr/bin/ld : error : /root/projects/TestCGAL/obj/x64/Debug/CGALExmaple.o: in function `boost::multiprecision::backends::gmp_rational::compare(boost::multiprecision::backends::gmp_rational const&) const':
1>/usr/include/boost/multiprecision/gmp.hpp(2104): error : undefined reference to `__gmpq_cmp'
1>/usr/bin/ld : error : /root/projects/TestCGAL/obj/x64/Debug/CGALExmaple.o: in function `boost::multiprecision::backends::eval_add(boost::multiprecision::backends::gmp_rational&, boost::multiprecision::backends::gmp_rational const&)':
1>/usr/include/boost/multiprecision/gmp.hpp(2160): error : undefined reference to `__gmpq_add'
1>/usr/bin/ld : error : /root/projects/TestCGAL/obj/x64/Debug/CGALExmaple.o: in function `boost::multiprecision::backends::eval_subtract(boost::multiprecision::backends::gmp_rational&, boost::multiprecision::backends::gmp_rational const&)':
1>/usr/include/boost/multiprecision/gmp.hpp(2164): error : undefined reference to `__gmpq_sub'
1>/usr/bin/ld : error : /root/projects/TestCGAL/obj/x64/Debug/CGALExmaple.o: in function `boost::multiprecision::backends::eval_multiply(boost::multiprecision::backends::gmp_rational&, boost::multiprecision::backends::gmp_rational const&)':
1>/usr/include/boost/multiprecision/gmp.hpp(2168): error : undefined reference to `__gmpq_mul'
1>/usr/bin/ld : error : /root/projects/TestCGAL/obj/x64/Debug/CGALExmaple.o: in function `boost::multiprecision::backends::eval_add(boost::multiprecision::backends::gmp_rational&, boost::multiprecision::backends::gmp_rational const&, boost::multiprecision::backends::gmp_rational const&)':
1>/usr/include/boost/multiprecision/gmp.hpp(2178): error : undefined reference to `__gmpq_add'
1>/usr/bin/ld : error : /root/projects/TestCGAL/obj/x64/Debug/CGALExmaple.o: in function `boost::multiprecision::backends::eval_subtract(boost::multiprecision::backends::gmp_rational&, boost::multiprecision::backends::gmp_rational const&, boost::multiprecision::backends::gmp_rational const&)':
1>/usr/include/boost/multiprecision/gmp.hpp(2182): error : undefined reference to `__gmpq_sub'
1>/usr/bin/ld : error : /root/projects/TestCGAL/obj/x64/Debug/CGALExmaple.o: in function `boost::multiprecision::backends::eval_multiply(boost::multiprecision::backends::gmp_rational&, boost::multiprecision::backends::gmp_rational const&, boost::multiprecision::backends::gmp_rational const&)':
1>/usr/include/boost/multiprecision/gmp.hpp(2186): error : undefined reference to `__gmpq_mul'
1>/usr/bin/ld : error : /root/projects/TestCGAL/obj/x64/Debug/CGALExmaple.o: in function `boost::multiprecision::backends::eval_divide(boost::multiprecision::backends::gmp_rational&, boost::multiprecision::backends::gmp_rational const&, boost::multiprecision::backends::gmp_rational const&)':
1>/usr/include/boost/multiprecision/gmp.hpp(2192): error : undefined reference to `__gmpq_div'
1>/usr/bin/ld : error : /root/projects/TestCGAL/obj/x64/Debug/CGALExmaple.o: in function `boost::multiprecision::backends::eval_abs(boost::multiprecision::backends::gmp_rational&, boost::multiprecision::backends::gmp_rational const&)':
1>/usr/include/boost/multiprecision/gmp.hpp(2246): error : undefined reference to `__gmpq_abs'
1>/usr/bin/ld : error : /root/projects/TestCGAL/obj/x64/Debug/CGALExmaple.o: in function `boost::multiprecision::backends::assign_components(boost::multiprecision::backends::gmp_rational&, boost::multiprecision::backends::gmp_int const&, boost::multiprecision::backends::gmp_int const&)':
1>/usr/include/boost/multiprecision/gmp.hpp(2261): error : undefined reference to `__gmpz_set'
1>/usr/bin/ld : error : /usr/include/boost/multiprecision/gmp.hpp:2262: undefined reference to `__gmpz_set'
1>/usr/bin/ld : error : /usr/include/boost/multiprecision/gmp.hpp:2263: undefined reference to `__gmpq_canonicalize'
1>/usr/bin/ld : error : /root/projects/TestCGAL/obj/x64/Debug/CGALExmaple.o: in function `CGAL::RET_boost_mp<boost::multiprecision::number<boost::multiprecision::backends::gmp_int, (boost::multiprecision::expression_template_option)1>, mpl_::int_<0> >::To_interval::operator()(boost::multiprecision::number<boost::multiprecision::backends::gmp_int, (boost::multiprecision::expression_template_option)1> const&) const':
1>/usr/include/CGAL/boost_mp.h(240): error : undefined reference to `mpfr_set_z'
1>/usr/bin/ld : error : /usr/include/CGAL/boost_mp.h:241: undefined reference to `mpfr_get_d'
1>/usr/bin/ld : error : /root/projects/TestCGAL/obj/x64/Debug/CGALExmaple.o: in function `CGAL::RET_boost_mp<boost::multiprecision::number<boost::multiprecision::backends::gmp_rational, (boost::multiprecision::expression_template_option)1>, mpl_::int_<2> >::To_interval::operator()(boost::multiprecision::number<boost::multiprecision::backends::gmp_rational, (boost::multiprecision::expression_template_option)1> const&) const':
1>/usr/include/CGAL/boost_mp.h(274): error : undefined reference to `mpfr_get_emin'
1>/usr/bin/ld : error : /usr/include/CGAL/boost_mp.h:275: undefined reference to `mpfr_set_emin'
1>/usr/bin/ld : error : /usr/include/CGAL/boost_mp.h:277: undefined reference to `mpfr_set_q'
1>/usr/bin/ld : error : /usr/include/CGAL/boost_mp.h:278: undefined reference to `mpfr_subnormalize'
1>/usr/bin/ld : error : /usr/include/CGAL/boost_mp.h:279: undefined reference to `mpfr_get_d'
1>/usr/bin/ld : error : /usr/include/CGAL/boost_mp.h:280: undefined reference to `mpfr_set_emin'
1>/usr/bin/ld : error : /root/projects/TestCGAL/obj/x64/Debug/CGALExmaple.o: in function `CGAL::Mpzf::Mpzf(CGAL::Mpzf const&)':
1>/usr/include/CGAL/Mpzf.h(338): error : undefined reference to `__gmpn_copyi'
1>/usr/bin/ld : error : /root/projects/TestCGAL/obj/x64/Debug/CGALExmaple.o: in function `CGAL::Mpzf::aors(CGAL::Mpzf const&, CGAL::Mpzf const&, int)':
1>/usr/include/CGAL/Mpzf.h(592): error : undefined reference to `__gmpn_copyi'
1>/usr/bin/ld : error : /usr/include/CGAL/Mpzf.h:601: undefined reference to `__gmpn_copyi'
1>/usr/bin/ld : error : /usr/include/CGAL/Mpzf.h:620: undefined reference to `__gmpn_copyi'
1>/usr/bin/ld : error : /usr/include/CGAL/Mpzf.h:623: undefined reference to `__gmpn_copyi'
1>/usr/bin/ld : error : /root/projects/TestCGAL/obj/x64/Debug/CGALExmaple.o:/usr/include/CGAL/Mpzf.h:628: more undefined references to `__gmpn_copyi' follow
1>/usr/bin/ld : error : /root/projects/TestCGAL/obj/x64/Debug/CGALExmaple.o: in function `CGAL::Mpzf::aors(CGAL::Mpzf const&, CGAL::Mpzf const&, int)':
1>/usr/include/CGAL/Mpzf.h(653): error : undefined reference to `__gmpn_add'
1>/usr/bin/ld : error : /usr/include/CGAL/Mpzf.h:660: undefined reference to `__gmpn_add'
1>/usr/bin/ld : error : /usr/include/CGAL/Mpzf.h:692: undefined reference to `__gmpn_copyi'
1>/usr/bin/ld : error : /usr/include/CGAL/Mpzf.h:700: undefined reference to `__gmpn_neg'
1>/usr/bin/ld : error : /usr/include/CGAL/Mpzf.h:703: undefined reference to `__gmpn_sub_1'
1>/usr/bin/ld : error : /usr/include/CGAL/Mpzf.h:709: undefined reference to `__gmpn_neg'
1>/usr/bin/ld : error : /usr/include/CGAL/Mpzf.h:718: undefined reference to `__gmpn_sub'
1>/usr/bin/ld : error : /usr/include/CGAL/Mpzf.h:721: undefined reference to `__gmpn_sub_1'
1>/usr/bin/ld : error : /root/projects/TestCGAL/obj/x64/Debug/CGALExmaple.o: in function `CGAL::operator*(CGAL::Mpzf const&, CGAL::Mpzf const&)':
1>/usr/include/CGAL/Mpzf.h(749): error : undefined reference to `__gmpn_mul'
1>/usr/bin/ld : error : /usr/include/CGAL/Mpzf.h:751: undefined reference to `__gmpn_mul'
1>/usr/bin/ld : error : /root/projects/TestCGAL/obj/x64/Debug/CGALExmaple.o: in function `boost::multiprecision::number<boost::multiprecision::backends::gmp_int, (boost::multiprecision::expression_template_option)1> boost::multiprecision::numerator<(boost::multiprecision::expression_template_option)1>(boost::multiprecision::number<boost::multiprecision::backends::gmp_rational, (boost::multiprecision::expression_template_option)1> const&)':
1>/usr/include/boost/multiprecision/gmp.hpp(2390): error : undefined reference to `__gmpz_set'
1>/usr/bin/ld : error : /root/projects/TestCGAL/obj/x64/Debug/CGALExmaple.o: in function `boost::multiprecision::number<boost::multiprecision::backends::gmp_int, (boost::multiprecision::expression_template_option)1> boost::multiprecision::denominator<(boost::multiprecision::expression_template_option)1>(boost::multiprecision::number<boost::multiprecision::backends::gmp_rational, (boost::multiprecision::expression_template_option)1> const&)':
1>/usr/include/boost/multiprecision/gmp.hpp(2397): error : undefined reference to `__gmpz_set'
1>collect2 : error : ld returned 1 exit status

## Source Code
I use the sample codes as following:

#include <iostream>
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/convex_hull_2.h>
typedef [CGAL::Exact_predicates_inexact_constructions_kernel](https://doc.cgal.org/latest/Kernel_23/classCGAL_1_1Exact__predicates__inexact__constructions__kernel.html) K;
typedef K::Point_2 Point_2;
int main()
{
  Point_2 points[5] = { Point_2(0,0), Point_2(10,0), Point_2(10,10), Point_2(6,5), Point_2(4,1) };
  Point_2 result[5];
  Point_2 *ptr = [CGAL::convex_hull_2](https://doc.cgal.org/latest/Convex_hull_2/group__PkgConvexHull2Functions.html#ga8241d43969ff61cb9be46811c2e9e176)( points, points+5, result );
  std::cout <<  ptr - result << " points on the convex hull:" << std::endl;
  for(int i = 0; i < ptr - result; i++){
    std::cout << result[i] << std::endl;
  }
  return 0;
}

_If your issue arises by using CGAL in your own source code, please provide a minimalist example that we can compile easily to reproduce the bug. If your issue arises from using a CGAL program (demo, example, etc.), please let us know which one. Helping you solving an issue is much easier and efficient if we can reproduce it._

## Environment

* Operating system (Ubuntu 64 bits):
* Compiler: Build using visual studio 2022 WSL (remote ubuntu system)
* Release or debug mode:
* Specific flags used (if any):
* CGAL version: 5.4
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.): Eigen

**Comment by houw** [comment]
The library gmp provides the extended arithmetic for the number types integer and rational.

The following files should be available:

gmp.h: the header files for the declarations exported from the library,

libgmp.[a,so,dyl]: the library compiled either statically or dynamically.

where can I find the libgmp.[a,so,dyl], I don;t find it on my ubuntu os?

**Comment by houw** [comment]
foreach(target BnCgal)
  target_link_libraries(${target} PUBLIC CGAL::Eigen3_support)
endforeach()

Can I know what libs linked about CGAL::Eigen3_support?

**Comment by sloriot** [comment]
Eigen is a header only library. More details here: https://eigen.tuxfamily.org/index.php?title=Main_Page

At CGAL's level, you will need to define `CGAL_EIGEN3_ENABLED` (which is done automatically by cmake with the macro `Eigen3_support`) so that default parameters for solver traits are available.

**Comment by houw** [comment]
It is works for me. thanks.

-Ryan
