### ISSUE TITLE
Solution link for disabling CGAL::Uncertain_conversion_exception in FAQ page is not working

### ISSUE THREAD

**Issue by ShenCiao** [CGAL/cgal#6624]
## Issue Details
The link about disabling CGAL::Uncertain_conversion_exception in [FAQ page](https://www.cgal.org/FAQ.html#uncertain_exception) is not viable. Here is the link:

http://www.helixoft.com/blog/archives/24

**Comment by sloriot** [comment]
Just fixed it. It should be:
https://www.helixoft.com/blog/how-to-disable-a-first-chance-exception-of-type-messages-in-vs-2005.html
