### ISSUE TITLE
Nef_Polyhedron boolean operation always exception

### ISSUE THREAD

**Issue by breakerrorchen** [CGAL/cgal#6654]
@sloriot @afabri   @lrineau L @marv take the liberty to disturb you，but i need your help.

I'm using Nef_Polyhedron for boolean operations because he doesn't seem to need to triangulate ahead of time.
My code looks like this

```cpp
using K_T_                   = CGAL::Exact_predicates_inexact_constructions_kernel;
using POINT2_T_              = K_T_::Point_2;
using POINT3_T_              = K_T_::Point_3;
using VECTOR3_T_             = K_T_::Vector_3;
using Mesh_T_                = CGAL::Surface_mesh<POINT3_T_>;
using Polyhedron_            = CGAL::Polyhedron_3<K_T_>;
using Nef_Polyhedron_        = CGAL::Nef_polyhedron_3<K_T_>;

// step 1:
Mesh_T_ m0;
CGAL::Polygon_mesh_processing::IO::read_polygon_mesh("0.obj",  m0);
Nef_Polyhedron_ nefPoly_0(m0);

// step 2: 
Mesh_T_ m1;
CGAL::Polygon_mesh_processing::IO::read_polygon_mesh("spot.obj", m1);
Nef_Polyhedron_ nefPoly_1(m1);

// step: 3
auto s = nefPoly_0 + nefPoly_1;
```

At the second step I get an exception.

```cpp
CGAL error: assertion violation!
Expression : c.has_on(p1)&&c.has_on(p2)
File       : 3rd/cgal/Nef_S2/include/CGAL/Nef_S2/Sphere_segment.h
Line       : 56
Explanation: 
Refer to the bug-reporting instructions at https://www.cgal.org/bug_report.html
libc++abi: terminating with uncaught exception of type CGAL::Assertion_exception: CGAL ERROR: assertion violation!
Expr: c.has_on(p1)&&c.has_on(p2)
File: 3rd/cgal/Nef_S2/include/CGAL/Nef_S2/Sphere_segment.h
Line: 56
```
I suspect it is the problem of calculation precision, so I replace kernel with `CGAL::Exact_predicates_exact_constructions_kernel`
The exception in the second step disappears

But when I use another model `monkey.obj` to replace `spot.obj`, there is an exception during the boolean operation

```cpp
CGAL error: assertion violation!
Expression : ss_circle.has_on(sp)
File       : 3rd/cgal/Nef_3/include/CGAL/Nef_3/polygon_mesh_to_nef_3.h
Line       : 253
Explanation: 
Refer to the bug-reporting instructions at https://www.cgal.org/bug_report.html
libc++abi: terminating with uncaught exception of type CGAL::Assertion_exception: CGAL ERROR: assertion violation!
Expr: ss_circle.has_on(sp)
File: 3rd/cgal/Nef_3/include/CGAL/Nef_3/polygon_mesh_to_nef_3.h
Line: 253
```

So where am I using it wrong? I put all three models in the attachment.

[data.zip](https://github.com/CGAL/cgal/files/8861203/data.zip)

**Comment by afabri** [comment]
You must first triangulate the quad mesh.

**Comment by breakerrorchen** [comment]
> 

But I need to support clipping of polyheons (which can be more than 3 edges) and don't want to break the topology of uncovered faces，Can CGAL fulfill this requirement?

**Comment by afabri** [comment]
Sorry, but I do not understand.   I had suggested to call [`triangulate_faces()`](https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__meshing__grp.html#ga1e9c8778755b2d1741f47736ba6e4b45).

**Comment by sloriot** [comment]
You can also try [`OFF_to_nef_3()`](https://doc.cgal.org/latest/Nef_3/group__PkgNef3IOFunctions.html#gaeb31b20d2824c500c4a12e284667dfce) when you input is not clean, like the monkey that is self-intersecting.
