### ISSUE TITLE
CGAL::create_interior_straight_skeleton_2 does not provide the vertices for StraightSkeletonFace_2

### ISSUE THREAD

**Issue by Sumilsood** [CGAL/cgal#6661]
_Please use the following template to help us solving your issue._

I am using straight skeleton to build a Roof type structure from a polygon. I want to triangulate the faces that are given as output from the straight skeleton but the StraightSkeletonFace_2 class does not give access to the vertices. I tried to go around it using the Halfedges given by the straight skeleton. I used the Face Id attached to each half edges to see sort on which d=face a halfedge belongs to but this gives a unsorted set of point which needs to be sorted in counter clockwise order(Which is also difficult as polygons can be highly irregular) before they can be triangulated. Is there a simple way to get the vertices for each of the face in straight skeleton so that they can be triangulated?

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows
* Compiler: VS 2019
* Release or debug mode: Release
* Specific flags used (if any):
* CGAL version: 5.4
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by sloriot** [comment]
https://gist.github.com/sloriot/d01439c7abab31a9fa0e2a3af84eca41

**Comment by for-heart-peace** [comment]
I also encountered this problem, because there is a random scattering process, so my bone generation is occasionally successful, uncertain failure.
