### ISSUE TITLE
"Unknown error -1" in CGAL::difference for Polygon_with_holes_2, exact constructions

### ISSUE THREAD

**Issue by johnnybigert** [CGAL/cgal#6675]
## Issue Details

I run the below program and it crashes with "Unknown error -1" on the `CGAL::difference` line (verified by printouts). If all the input points are integers, I don't get the error. Please advice, thanks!

```
$ ./problem_exact
terminate called after throwing an instance of 'std::system_error'
  what():  Unknown error -1
Aborted
```

## Source Code

```
#include <CGAL/Exact_predicates_exact_constructions_kernel.h>
#include <CGAL/Boolean_set_operations_2.h>
#include <vector>

typedef CGAL::Exact_predicates_exact_constructions_kernel Kernel;

typedef Kernel::Point_2 Point_2;
typedef CGAL::Polygon_2<Kernel> Polygon_2;
typedef std::vector<Polygon_2> Polygons;

typedef CGAL::Polygon_with_holes_2<Kernel> Polygon_with_holes_2;
typedef std::vector<Polygon_with_holes_2> Pwh_vector;


int main()
{
    Polygon_2 outP;
    outP.push_back(Point_2(-45, -30));
    outP.push_back(Point_2(-44.935363788124477, -30.821280941461211));
    outP.push_back(Point_2(-40.606601717798213, -40.606601717798213));
    outP.push_back(Point_2(-31.525236034142253, -44.879961320802593));
    outP.push_back(Point_2(-30, -45));
    outP.push_back(Point_2(30, -45));
    outP.push_back(Point_2(30.821280941461211, -44.935363788124477));
    outP.push_back(Point_2(40.606601717798213, -40.606601717798213));
    outP.push_back(Point_2(44.935363788124477, -30.821280941461211));
    outP.push_back(Point_2(45, -30));
    outP.push_back(Point_2(45, 30));
    outP.push_back(Point_2(44.935363788124477, 30.821280941461211));
    outP.push_back(Point_2(40.606601717798213, 40.606601717798213));
    outP.push_back(Point_2(31.525236034142253, 44.879961320802593));
    outP.push_back(Point_2(30, 45));
    outP.push_back(Point_2(-30, 45));
    outP.push_back(Point_2(-30.821280941461211, 44.935363788124477));
    outP.push_back(Point_2(-40.606601717798213, 40.606601717798213));
    outP.push_back(Point_2(-44.879961320802593, 31.525236034142253));
    outP.push_back(Point_2(-45, 30));
    Polygon_with_holes_2 P(outP);

    Polygon_2 outQ;
    outQ.push_back(Point_2(-45, -30));
    outQ.push_back(Point_2(-44.889195065356247, -31.407910185362077));
    outQ.push_back(Point_2(-40.606601717798213, -40.606601717798213));
    outQ.push_back(Point_2(-30.938606790241387, -44.926130043570822));
    outQ.push_back(Point_2(-30, -45));
    outQ.push_back(Point_2(30, -45));
    outQ.push_back(Point_2(31.407910185362077, -44.889195065356233));
    outQ.push_back(Point_2(40.606601717798213, -40.606601717798213));
    outQ.push_back(Point_2(44.889195065356247, -31.407910185362077));
    outQ.push_back(Point_2(45, -30));
    outQ.push_back(Point_2(45, 30));
    outQ.push_back(Point_2(44.889195065356247, 31.407910185362077));
    outQ.push_back(Point_2(40.606601717798213, 40.606601717798213));
    outQ.push_back(Point_2(30.938606790241387, 44.926130043570822));
    outQ.push_back(Point_2(30, 45));
    outQ.push_back(Point_2(-30, 45));
    outQ.push_back(Point_2(-31.407910185362077, 44.889195065356247));
    outQ.push_back(Point_2(-40.606601717798213, 40.606601717798213));
    outQ.push_back(Point_2(-44.926130043570822, 30.938606790241387));
    outQ.push_back(Point_2(-45, 30));
    Polygon_with_holes_2 Q(outQ);

    Pwh_vector diff;
    CGAL::difference(P, Q, std::back_inserter(diff));

    return 0;
}
```

## Environment

* Operating system:
```
$ uname -a
Linux docker-desktop 5.10.76-linuxkit #1 SMP PREEMPT Mon Nov 8 11:22:26 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
```
* Compiler:
```
$ c++ --version
Ubuntu clang version 12.0.0-3ubuntu1~20.04.5
Target: aarch64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```
* Release or debug mode: `debug mode`
* Specific flags used (if any):
`c++ problem_exact.cpp -std=c++17 -I. -I/opt/vcpkg/installed/arm64-linux/include /opt/vcpkg/installed/arm64-linux/lib/{libmpfr.a,libgmp.a,libgmpxx.a,libboost_math_c99.a} -o problem_exact`
* CGAL version: `v5.4.1`
* Boost version: `1.79.0`
* Other libraries versions if used (Eigen, TBB, etc.): None to my best knowledge

**Comment by johnnybigert** [comment]
This may or may not be related to my other bug report on inexact constructions for the same program: https://github.com/CGAL/cgal/issues/6676

**Comment by johnnybigert** [comment]
Hi, and thank you for the quick answer.

- `-frounding-math` gives me: `warning: overriding currently unsupported rounding mode on this target [-Wunsupported-floating-point-opt]`, so it doesn't seem to be supported on my platform
- I've now added `#define CGAL_NO_GMP 1` and `#define CGAL_NO_MPFR 1` to the top of my program and removed all libs from the command line, so compilation is now `c++ problem_exact.cpp -I/opt/vcpkg/installed/arm64-linux/include -o problem_exact` and I still get the same error "Unknown error -1"!

Any ideas what I could try next? Thanks.

**Comment by mglisse** [comment]
> terminate called after throwing an instance of 'std::system_error'

That's usually a sign of missing `-pthread`. This is required since we made Epeck thread-safe, unless you pass `-DCGAL_HAS_NO_THREADS`.

**Comment by johnnybigert** [comment]
Wow, `-lpthread` solved my problem, huge thanks!!! And thanks for the tip going forward.

**Comment by mglisse** [comment]
> `-lpthread` solved my problem

Note that it is preferable to use `-pthread` which depending on the system may do more than just `-lpthread`, or may even do something completely different.

> I guess it was the mutex.cpp that lead you to suspect threading?

I hit this `system_error` many, many times while writing this code, so now it immediately rings a bell when I see it :wink: But yes, `mutex` and `call_once` are hints.

**Comment by johnnybigert** [comment]
Ok, I'll read up on it. Again, many thanks!
