### ISSUE TITLE
CGAL_NO_THREADS typo

### ISSUE THREAD

**Issue by mglisse** [CGAL/cgal#6679]
https://github.com/CGAL/cgal/blob/03508a96f4f6114fd305e1c436e3a529d9fdaa9b/Installation/include/CGAL/atomic.h#L36

This is the sole occurrence of CGAL_NO_THREADS. Maybe CGAL_HAS_NO_THREADS was intended?

**Comment by lrineau** [comment]
Will be fixed by #6682 too, commit 429c7646bd6a2f9e80adf1deaba86e139f044434.
