### ISSUE TITLE
Pre-C++11 ref to boost

### ISSUE THREAD

**Issue by mglisse** [CGAL/cgal#6680]
https://github.com/CGAL/cgal/blob/03508a96f4f6114fd305e1c436e3a529d9fdaa9b/Documentation/doc/Documentation/Developer_manual/Chapter_multithreading.txt#L18

The boost case doesn't seem to exist anymore.

**Comment by lrineau** [comment]
Thanks. It will be fixed by https://github.com/CGAL/cgal/pull/6682.

**Comment by lrineau** [comment]
Fixed by https://github.com/CGAL/cgal/pull/6682.
