### ISSUE TITLE
Example project Bezier_curves assertion violation ! do_ovlp

### ISSUE THREAD

**Issue by tkdejong** [CGAL/cgal#669]
Hello,

I'm having trouble with the Arrangement package when using Bezier curves; it seems to crash for some inputs when inserting curves, so I decided to record the curves in one of these cases.

Using CGAL 4.7, 64-bit Windows version installed as per the manual.
Using Visual Studio 2013.
Using the provided example solution Arrangement_on_surface_2 - project Bezier_curves, to hopefully rule out errors in my own code or project setup.

Running the produced Bezier_curves.exe with as argument a file with my 6 recorded Bezier curves gives the assertion violation (Expression: ! do_ovlp).

For detailed info, please take a look at this gist. And please do tell me if any information is missing! Any help would be greatly appreciated.
https://gist.github.com/tkdejong/9bdde0f94591dc5f161c

PS: I have more .dat files with Bezier curves that crashs (in apparently different ways) when fed to the example project, but I thought it would be prudent to hold on to those in case the underlying problem turns out to be the same.

**Comment by sloriot** [comment]
See #802

**Comment by lrineau** [comment]
Is this fixed, now that #802 has been merged?

**Comment by efifogel** [comment]
I believe so.

   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by lrineau** [comment]
Fixed by #802.
