### ISSUE TITLE
Problems using `std::array` as the value type of a `PolygonRange` in polygon soup related functionality

### ISSUE THREAD

**Issue by ton** [CGAL/cgal#6693]
The documentation of CGAL 5.4.1 contains the following note for `PMP::polygon_mesh_to_polygon_soup()`:

> PolygonRange can also be a model of the concepts [RandomAccessContainer](https://doc.cgal.org/latest/Manual/classRandomAccessContainer.html) and [BackInsertionSequence](https://doc.cgal.org/latest/Manual/classBackInsertionSequence.html) whose value type is an array, but it is the user's responsability to ensure that all faces have the same number of vertices, and that this number is equal to the size of the array.

This is true and works as expected for `PMP::polygon_mesh_to_polygon_soup()`. However, this useful property in practice is not very useful, since other functions that operate on a polygon soup have stricter requirements on the value type of a `PolygonRange`. For example, `PMP::repair_polygon_soup()` requires that it is possible to construct a container with a pair of iterators, which `std::array` as an almost-but-not-quite-`SequenceContainer` does not support:

https://github.com/CGAL/cgal/blob/7ba81ca1d5d519d8f3691eeb9051f93933dd969d/Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/repair_polygon_soup.h#L275

I am wondering whether it would be possible for the functions that operate on a polygon soup to loosen their restrictions on the `PolygonRange` type such that `std::array` can be used consistently as a value type of a `PolygonRange` within this domain?

**Comment by MaelRL** [comment]
For `PMP::repair_polygon_soup()`, a few functions are meant to modify polygonal faces for which an array is not a compatible container, such as the "pinched face splitting" function that you quote.

There could be some overload of "repair_polygon_soup()" for fixed-size faces that does not include those functions.

**Comment by ton** [comment]
Yes, that makes sense. In my case, I am dealing with triangle soups, so splitting pinched polygons is not needed. I can take the functions that are called from `repair_polygon_soup()` and just not include the one that is quoted above.

In theory I think it would be possible to detect at compile time that the value type in a `PolygonRange` is a container of some fixed size, and then prevent `split_pinched_polygons_in_polygon_soup()` from being called for a container with a fixed size equal to 3 (maybe also 4?).

**Comment by ton** [comment]
No I have not, but I must say I did not do any extensive testing.

**Comment by MaelRL** [comment]
See #6704.

**Comment by ton** [comment]
Thanks a lot for the quick response! Is it possible for these kinds of changes to be backported to CGAL 4, or is that only done for critical bug fixes?

**Comment by sloriot** [comment]
Do you mean 5.4?

**Comment by lrineau** [comment]
Fixed by the merge of https://github.com/CGAL/cgal/pull/6704.
