### ISSUE TITLE
PolygonWithHolesConvexDecomposition_2 how to include file 

### ISSUE THREAD

**Issue by qiangsun89** [CGAL/cgal#6697]
## Issue Details

I want to use PolygonWithHolesConvexDecomposition_2 and include file, 
#include <Concepts/PolygonWithHolesConvexDecomposition_2.h>
but it doesn't work.
![屏幕截图 2022-06-23 103325](https://user-images.githubusercontent.com/46945831/175194877-e46d03c6-2b7d-46e1-be29-61442d91ded1.png)

**Comment by lrineau** [comment]
`PolygonWithHolesConvexDecomposition_2` is a concept, and not a class or class template.
Have a look at:
  - [`CGAL::Polygon_vertical_decomposition_2`](https://doc.cgal.org/latest/Minkowski_sum_2/classCGAL_1_1Polygon__vertical__decomposition__2.html), and
  - [`CGAL::Polygon_triangulation_decomposition_2`](https://doc.cgal.org/latest/Minkowski_sum_2/classCGAL_1_1Polygon__triangulation__decomposition__2.html),

that are both class templates models of that concept.
