### ISSUE TITLE
Wrong distance computation of the camera caused by Basic_viewer_qt::draw()

### ISSUE THREAD

**Issue by efifogel** [CGAL/cgal#6722]
## Issue Details

The problem is in the `draw()` function of the `Basic_viewer_qt`.
When using the `Basic_viewer_qt` construct to draw a 2D data structure, an orthogonal camera should be used.
The type of the camera is set in lines 1007 (orthogonal) and 1023 (perspective) as part of the `draw()` function.
However, this happens too late in the game, because the call `showEntireScene()` in line 1391 from the init() function of `Basic_viewer_qt` has already been occurred. This call triggers the call `camera->showEntireScene()` on line 3574 of `gqlviwer.h`, which in turn triggers the call `fitSphere(sceneCenter(), sceneRadius())` on line 907 (in `Camera.h`), which computes the distance based on the camera type. As the default type is perspective, the wrong distance is obtained (line 951).

The net effect is that the interesting area of the window is smaller than it should be. You can think of it has having too large margins.

The solution is simple, but I believe that the entire handling of the camera (the compound statement that starts with `if (is_two_dimensional())` in line 1005 of `Basic_viewer_qt.h`)  should not be part of the `draw()` function, because it should not be executed for every frame.

While at it, it will be nice to add a function to `Basic_viewer_qt` that the user can be used to obtain the width and height of the near plane. The rational for this request follows:

Consider rendering non-linear curves in the plane.
I need to approximate a given curve by a polyline in order to render it.
The approximation depends on two things, namely
(i) the window width and height in pixels, and
(ii) the near plane width and height.
I can obtain the former, no problem, with the `resizeGL()` callback.
Naturally, I can compute the bounding box of my scene.
What I'm missing is the margin of the bounding box used to define the camera.
Observe that I do not have the final camera parameters at hand when I generate the polyline approximation (well, these are based on the resulting approximated polylines...).

## Source Code

Polygon/examples/Polygon/draw_polygon.cpp

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): irrelevant
* Compiler: irrelevant
* Release or debug mode: both
* Specific flags used (if any): irrelevant
* CGAL version: latest (5.5)
* Boost version: irrelevant
* Other libraries versions if used (Eigen, TBB, etc.): irrelevant

**Comment by lrineau** [comment]
Fixed by https://github.com/CGAL/cgal/pull/6729
