### ISSUE TITLE
Assertion failure in Nef polyhedron join: itl != it->second.end()

### ISSUE THREAD

**Issue by dpapavas** [CGAL/cgal#6738]
I get the following assertion failure while joining two Nef polyhedra:

```
terminate called after throwing an instance of 'CGAL::Assertion_exception'
  what():  CGAL ERROR: assertion violation!
Expr: itl != it->second.end()
File: /home/dimitris/source/gc/cgal/Nef_3/include/CGAL/Nef_3/SNC_external_structure.h
Line: 1144
Aborted
```

[Here](https://github.com/CGAL/cgal/files/9041091/test.zip) is  a small test program, including the geometry in question.  As you can see one of the joined polyhedra is not manifold, but the result should be.  In fact the same join works fine using corefinement.

I'm currently using the `5.4.x-branch` branch, at commit ce87699ed3f8ee75758a2c25ebd031aa8e1a4840.

**Comment by sloriot** [comment]
I don't know if it's a bug of github but your small test points to an example only using 2D convex hull.

**Comment by dpapavas** [comment]
No, sorry, this was a mistake on my part.  [Here](https://github.com/CGAL/cgal/files/9061462/test.zip) is the correct test case.

**Comment by sloriot** [comment]
How was B produced? `Nef_polyhedron::is_valid()` says it is not valid.

**Comment by Dwight98** [comment]
I have met the same condition, but the method which I used is "Nef polyhedron difference". Now I still can't correctly run my code. What can i do?
