### ISSUE TITLE
CGAL 5.4.1 is supported for VS 2022, or not?

### ISSUE THREAD

**Issue by WindingWinter** [CGAL/cgal#6741]
Here it [says ](https://doc.cgal.org/latest/Manual/windows.html)

> CGAL 5.4.1 is supported for the following MS Visual C++ compilers: 14.0, 15.9, 16.0 (Visual Studio 2015, 2017, and 2019).

Notice that VS 2022 is excluded.

However, [at the other part](https://doc.cgal.org/latest/Manual/thirdparty.html), it lists VS 2022 as is a supported compiler. 

So, is CGAL 5.4.1 supported for VS 2022, or not? It seems like there must be a bug in the documentation.

**Comment by sloriot** [comment]
Fixed by #6749: it is supported
