### ISSUE TITLE
How to write stl file

### ISSUE THREAD

**Issue by lacrymose** [CGAL/cgal#6763]
_Please use the following template to help us solving your issue._

## Issue Details

Could you give me an example code of how to write stl file?

## Source Code

_If your issue arises by using CGAL in your own source code, please provide a minimalist example that we can compile easily to reproduce the bug. If your issue arises from using a CGAL program (demo, example, etc.), please let us know which one. Helping you solving an issue is much easier and efficient if we can reproduce it._

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): windows 64
* Compiler: vc2017
* Release or debug mode: release and debug
* Specific flags used (if any):
* CGAL version: 5.4.1
* Boost version: 1.79.0
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by sloriot** [comment]
Replacing `.off` by `.stl` in [this example](https://doc.cgal.org/latest/BGL/BGL_surface_mesh_2surface_mesh_partition_8cpp-example.html#a7) for example.

See also [here](https://doc.cgal.org/latest/BGL/group__PkgBGLIOFct.html)

**Comment by lacrymose** [comment]
@sloriot Thanks for your quick reply! I tried the example code. It works. Are there any example codes to show the usage of the function write_STL in CGAL\include\CGAL\IO\STL.h which seems not relying on BOOST ?

**Comment by sloriot** [comment]
This one is for polygon soup not triangle meshes. The aforementioned function does not rely on boost, only on extended boost concepts.

**Comment by lacrymose** [comment]
@sloriot Thanks! Could you tell me how to deal with my case where mesh data are coordinates of all vertices and indices of the three vertices in each triangular facet. I guess I have to create a Graph object and transfer the data into it. But I donot know how to accomplish this. Many thanks in advance.
