### ISSUE TITLE
How to use CGAL::root_of?

### ISSUE THREAD

**Issue by ShenCiao** [CGAL/cgal#6768]
## Issue Details
In the [document](https://doc.cgal.org/latest/Algebraic_foundations/group__PkgAlgebraicFoundationsRef.html#ga975ad8b8b91cd67463c6c2be863d16a2), the `root_of` has signature:
`NT CGAL::root_of	(int k, InputIterator begin, InputIterator end)`

But in actual code the return type comes to `typename Algebraic_structure_traits<typename std::iterator_traits<Input_iterator>::value_type >::Root_of::result_type`:
```
template< class Input_iterator >
inline
typename Algebraic_structure_traits< typename std::iterator_traits<Input_iterator>::value_type >::Root_of::result_type
root_of( int k, Input_iterator begin, Input_iterator end )
```

Have I forgot about including or installing something or this function has already been deprecated?

## Environment

* Operating system (Windows 64 bits):
* Compiler: MSVC
* CGAL version: lastest with vcpkg (5.4.1)
* Boost version: lastest with vcpkg

**Comment by MaelRL** [comment]
But this `result_type` will resolve to `NT`, see for example https://github.com/CGAL/cgal/blob/master/Number_types/include/CGAL/Lazy_exact_nt.h#L842. Are you getting some compilation error?
