### ISSUE TITLE
Incorrect camera sizes in GraphicsView/include/CGAL/Qt/Basic_viewer_qt.h

### ISSUE THREAD

**Issue by albert-github** [CGAL/cgal#6769]
Looking at the code of GraphicsView/include/CGAL/Qt/Basic_viewer_qt.h I saw at line 209:
```
resize(CGAL_BASIC_VIEWER_INIT_SIZE_X, CGAL_BASIC_VIEWER_INIT_SIZE_X);
```
whilst in the past this was:
```
    resize(500, 450);
```
there are now 2 new defines:
```
#define CGAL_BASIC_VIEWER_INIT_SIZE_X 500
#define CGAL_BASIC_VIEWER_INIT_SIZE_Y 450
```

so should the line not read:
```
resize(CGAL_BASIC_VIEWER_INIT_SIZE_X, CGAL_BASIC_VIEWER_INIT_SIZE_Y);
```

The changes are from #6729 (@gdamiand)

**Comment by gdamiand** [comment]
Right @albert-github ; feel free to open a PR.

**Comment by sloriot** [comment]
I don't get what you mean here. I can do the PR but I don't see what needs to be fixed.

**Comment by sloriot** [comment]
Got it sorry.
