### ISSUE TITLE
lack queue.pop_front()

### ISSUE THREAD

**Issue by luobo67** [CGAL/cgal#6771]
## Issue Details

Code in **[Nef_nary_intersection_3.h](https://github.com/CGAL/cgal/blob/master/Nef_3/include/CGAL/Nef_nary_intersection_3.h)** and  **[Nef_nary_union_3.h](https://github.com/CGAL/cgal/blob/master/Nef_3/include/CGAL/Nef_nary_union_3.h)** after **get_intersection()** or **get_union()** `inserted = 0`, but `std::list<Polyhedron> queue` still has one item. I think (it lack `queue.pop_front();` back to `inserted = 0` )or( inserted should be 1).

## Source Code
```
  Polyhedron get_intersection() {
    if (queue.empty())
      return empty;
    while(queue.size() > 1)
      intersect();
    inserted = 0;
    return queue.front();
  }
  Polyhedron get_union() {
    if (queue.empty())
      return empty;
    while(queue.size() > 1)
      unite();
    inserted = 0;
    return queue.front();
  }
};
```

**Comment by afabri** [comment]
Helllo @luobo67, You are right. I think the better choice is to leave the result in the object, as one then may add other objects later.
