### ISSUE TITLE
Adding axis at the origin in the Polyhedron demo

### ISSUE THREAD

**Issue by maximecharriere** [CGAL/cgal#6775]
Would it be possible to add to the Polyhedron demo the XYZ axes at the origin?  

There are the little arrows at the top right, but it is often useful to know where the origin is and not only the direction.  
For now I generate 3 Polyline with the Polyline Generator, but it would be nice to be able to simply activate the axes.  
![image](https://user-images.githubusercontent.com/51918753/181814295-692be40c-ae41-4b94-9c5e-a36c4f6685eb.png)  

It look like this in MeshLab :   
![image](https://user-images.githubusercontent.com/51918753/181814170-2b6e0e3b-84ac-41a6-a756-0d9a550472ce.png)

**Comment by MaelRL** [comment]
You can get a a Z-grid and two axis by pressing 'G'.

It looks like this:
![tmp](https://user-images.githubusercontent.com/5074170/181824892-6b691122-39f9-44f5-ae60-2057f4284bd3.png)
