### ISSUE TITLE
Performance degrade with `Compare_distance_3` (seen in Mesh_3)

### ISSUE THREAD

**Issue by janetournois** [CGAL/cgal#6792]
## Issue Details

There is a performance degrade in `CGAL::Mesh_3::internal::init_c3t3_with_features()` since CGAL-5.0 (about a factor 5).

This is due to a change of `Compare_distance_3` and the commit responsible for that degrade is ba2f2c1c20bd4812c128ac08e082b70f55ef6f18

I am trying to isolate the degrade out of Mesh_3

## Source Code

The Mesh_3 example `mesh_polyhedral_domain_with_features.cpp` meshing part has its computation time doubled.

## Environment

* Release or debug mode: Release

**Comment by sloriot** [comment]
The commit you are pointing changes the exact NT to basically be mpq instead of mpz. The reason for that is that some overloads (with triangles IIRC) are using a division and mpz alone cannot be used. I don't know what is the best solution but I see two options:
- split the functor
- update the implementation of the `operator()` that requires `/` to not use it

**Comment by janetournois** [comment]
Thank you, I'll give it a try

**Comment by afabri** [comment]
Which operator do you use @janetournois ?

**Comment by janetournois** [comment]
I think it is `Compare_distance_3()(point, point, segment)` that is the bottleneck

**Comment by lrineau** [comment]
@mglisse

In PR https://github.com/CGAL/cgal/pull/6796 we have removed the calls to predicates causing the filter failures. But the original issue (see https://github.com/CGAL/cgal/issues/6792#issuecomment-1209411342) is still there: given a kernel predicate having multiple overloads of `operator()`, some needing only `RT` and other needing `FT` (with division), could it be possible for `Filtered_predicate` to wrap those different `operator()` differently.

I have several ideas:
  - split the class into two: `Compare_distance_3_RT` and `Compare_distance_3_FT`, and have `Compare_distance_3` inherit from both sets of `operator()`. Then with a special `Filtered_predicate` wrap all accordingly.
  - have a special return type like `CGAL::Needs_FT<typename Kernel::Boolean>` for overloads using `FT`, and have a simple meta-programming in `Filtered_predicate` to wrap differently. `CGAL::Need_FT<Boolean>` would be have the trivial `operator Boolean()`.

What do you think of that? Maybe another idea?

**Comment by sloriot** [comment]
First option seems the best to me.

**Comment by mglisse** [comment]
* I like the idea of layers of functors, where the low layers don't use overloading. Your first suggestion goes a bit in this direction. I don't know what the nicest way is to implement Compare_distance_3 in terms of the other 2 so it works with all kernels.
* I'd probably keep FT as default and have Only_needs_RT to specify when that's safe. Unless we keep the RT case as now and this is a way to have an exception? Or we could reinvent something like we used to have for result_of.

I don't have a clear answer, you will have to experiment to see what works and is not too ugly...

**Comment by lrineau** [comment]
Fixed by  https://github.com/CGAL/cgal/pull/6796.

See also https://github.com/CGAL/cgal/pull/6866 for the kernel issue.
