### ISSUE TITLE
Since 5.4 version there is a significant performance degrade in CGAL::Polygon_mesh_processing::fair() 

### ISSUE THREAD

**Issue by likona1993** [CGAL/cgal#6794]
## Issue Details

After upgrading to 5.4 version CGAL::Polygon_mesh_processing::fair() slowed down significantly (from 0.077 sec to 144.236 sec for 916 vertices). Can you please suggest what could be the reason for this performance degrade?

## Environment

* Operating system Windows 64 bits
* Compiler: mingw64
* Release or debug mode: release
* Specific flags used (if any):
* CGAL version: 5.5
* Boost version: 1.79.0-4
* Other libraries versions if used (Eigen, TBB, etc.): eigen 3.4

**Comment by sloriot** [comment]
What example did you run?

**Comment by likona1993** [comment]
I made smaller mesh than in my first comment. The difference for one hole in this example: 124 vertices - CGAL 5.3.1 - 0.012 sec vs CGAL 5.5 - 1.1418 sec 

[pyramide.zip](https://github.com/CGAL/cgal/files/9314896/pyramide.zip)

**Comment by MaelRL** [comment]
With master and some code to triangulate, refine, and fair the holes of your mesh, I get runtime of a few ms per hole (except for the very large hole).

Can you please provide the code that you have benched?

**Comment by likona1993** [comment]
I took it partially from example:    

    unsigned int nb_holes = 0;
    std::vector<halfedge_descriptor> border_cycles;
    CGAL::Polygon_mesh_processing::extract_boundary_cycles(mesh, std::back_inserter(border_cycles));
    for (halfedge_descriptor h : border_cycles)
    {
        if (max_hole_diam > 0 && max_num_hole_edges > 0 &&
            !is_small_hole(h, mesh, max_hole_diam, max_num_hole_edges))
        {
            continue;
        }
        std::vector<face_descriptor>  patch_facets;
        std::vector<vertex_descriptor> patch_vertices;

        std::vector<face_descriptor>  refined_patch_facets;
        CGAL::Polygon_mesh_processing::triangulate_hole(
            mesh,
            h,
            std::back_inserter(patch_facets));
        CGAL::Polygon_mesh_processing::refine(mesh, patch_facets,
                                              std::back_inserter(refined_patch_facets),
                                              std::back_inserter(patch_vertices));

        CGAL::Polygon_mesh_processing::fair(mesh, patch_vertices);

        ++nb_holes;
    }

**Comment by MaelRL** [comment]
Below is the log I get with [this program](https://gist.github.com/MaelRL/2cad06ecb4508fd19d4ffa39995ed627)

```
[mrouxell@braque build-release]$ ./refine_fair_example ~/DATA/Debug/Github/6794/pyramide.off 
Input, 101420 vertices.
Fairing patch of 30
Fairing patch of 29
Fairing patch of 36
Fairing patch of 40
Fairing patch of 23
Fairing patch of 29
Fairing patch of 27
Fairing patch of 29
Fairing patch of 25
Fairing patch of 27
Fairing patch of 28
Fairing patch of 19
Fairing patch of 22
Fairing patch of 26
Fairing patch of 15
Fairing patch of 14
Fairing patch of 25
Fairing patch of 15
0.032836 s
```

How does it differ from the rest of your code?

**Comment by likona1993** [comment]
My output:
Input, 101420 vertices.
Fairing patch of 30 facets
Fairing patch of 29 facets
Fairing patch of 36 facets
Fairing patch of 40 facets
Fairing patch of 23 facets
Fairing patch of 29 facets
Fairing patch of 27 facets
Fairing patch of 29 facets
Fairing patch of 25 facets
Fairing patch of 27 facets
Fairing patch of 28 facets
Fairing patch of 19 facets
Fairing patch of 22 facets
Fairing patch of 26 facets
Fairing patch of 15 facets
Fairing patch of 14 facets
Fairing patch of 25 facets
Fairing patch of 15 facets
14.421 s

And also I had an issue in compiling,  I got error "no type named "Point_3" in CGAL::Epick", so I changed to CGAL::Filtered_kernel<CGAL::Simple_cartesian<double>>, was it correct? I'm using QtСreator to comple with mingw

**Comment by likona1993** [comment]
And without Qt, when I'm using just mingw, I've got the following output:
Input, 101420 vertices.
Fairing patch of 30 facets
Fairing patch of 29 facets
Fairing patch of 36 facets
Fairing patch of 40 facets
Fairing patch of 23 facets
Fairing patch of 29 facets
Fairing patch of 27 facets
Fairing patch of 29 facets
Fairing patch of 25 facets
Fairing patch of 27 facets
Fairing patch of 28 facets
Fairing patch of 19 facets
Fairing patch of 22 facets
Fairing patch of 26 facets
Fairing patch of 15 facets
Fairing patch of 14 facets
Fairing patch of 25 facets
Fairing patch of 15 facets
0.0410001 s

**Comment by MaelRL** [comment]
Did you check if your initial previous build setup was not using the "Debug" mode accidentally?

**Comment by likona1993** [comment]
It helped, thank you! I used cmake instead qmake in QtCreator and set CMAKE_BUILD_TYPE to Release and now it works!
