### ISSUE TITLE
problem about building igl_copyleft_cgal.lib in libigl example

### ISSUE THREAD

**Issue by echo-hi** [CGAL/cgal#6797]
I want to run the tutorial 609 in libigl project ,but I failed to build igl_copyleft_cgal.lib after running the cmake of libigl.
here is the error to build the igl_copyleft_cgal.lib:
![image](https://user-images.githubusercontent.com/55911430/184393725-5e2121f5-6002-48fb-8c31-3b7e9507f99e.png)

it could build the lib after i comment the code :
auto* pet = new typename Lazy_exact_nt_rep<ET>::Indirect(cste); this->keep_at(pet); this->set_ptr(pet);
but the lib would occur error when i test the tutorial 609

**Comment by afabri** [comment]
You should file an issue in the libigl project that they should upgrade to a more recent header only CGAL.
