### ISSUE TITLE
Problems with read_OBJ()

### ISSUE THREAD

**Issue by cuirq3** [CGAL/cgal#6798]
## Issue Details
I'm trying IO functions in CGAL and I met the error below.

**Compilation error:** 
![image](https://user-images.githubusercontent.com/50020459/184681604-b6116e07-5698-4d1b-a913-90b7230fdd0c.png)

I'm using this function and I saw it will call its override function with std::istream as the first parameter.

bool CGAL::IO::read_OBJ | ( | const std::string & | fname,
  |   | PointRange & | points,
  |   | PolygonRange & | polygons,
  |   | const NamedParameters & | np = parameters::default_values()
  | )

 The error pops up in that std::istream one.

## Source Code

**test.h:**
```
#include <CGAL/IO/OBJ.h>
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
typedef CGAL::Exact_predicates_inexact_constructions_kernel Kernel;
typedef Kernel::Point_3 Point;
typedef CGAL::Point_set_3<Point> Point_set;

void read_obj_CGAL(std::string, Point_set&,
		std::vector<std::vector<std::size_t>>&);
```

**test.cpp:**
```
void read_obj_CGAL(std::string file_path, Point_set& vertices,
	std::vector<std::vector<std::size_t>>& faces_ref) {
	CGAL::IO::read_OBJ(file_path, vertices, faces_ref);
	return;
}
```

**Btw, the function can't read vertex normals from the .obj file now, right? I didn't see a parameter for that :o**

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows 64
* Compiler: VS 2019
* Release or debug mode: debug
* Specific flags used (if any):
* CGAL version: 5.5
* Boost version: 1.79.0
* Other libraries versions if used (Eigen, TBB, etc.):

Thanks for any help!

**Comment by MaelRL** [comment]
`CGAL::Point_set_3` is not a range of points, it is a range of indices, so you cannot use it for the range of points parameter.

Normals are indeed not supported at this time.

**Comment by sloriot** [comment]
Well, you should be able to use it passing the right point map in the named parameters. The default should even be good. Might be broken for this function.

**Comment by cuirq3** [comment]
Thanks for the quick reply! It solved my problem :)

I tried to use some kind of point maps in the named parameters, such as

CGAL::IO::read_OBJ(file_path, vertices, faces_ref
		, CGAL::parameters::point_map(CGAL::First_of_pair_property_map<PointVectorPair>())
		.normal_map(CGAL::Second_of_pair_property_map<PointVectorPair>()));

But if I want to make it work, I need to change the type of vertices to vector<PointVectorPair>, it doesn't fit the input parameters.

(If I understand correctly, I can only use those listed named parameters. Then there is only one named parameter called verbose listed in read_OBJ())
