### ISSUE TITLE
do_intersect(Triangle_3,Bbox_3) is incorrect

### ISSUE THREAD

**Issue by geomtri** [CGAL/cgal#6808]
## Issue Details

do_intersect(Triangle_3,Bbox_3) is incorrect

## Source Code

```c++
#include <CGAL/Exact_predicates_exact_constructions_kernel.h>
#include <iostream>

typedef CGAL::Exact_predicates_exact_constructions_kernel K;
typedef K::Point_3 Point_3;
typedef K::Triangle_3 Triangle_3;
typedef CGAL::Bbox_3 Bbox_3;

int main()
{
  Point_3 p0(-34.1128,-4.00842,39.5061);
  Point_3 p1(-36.0938,-3.6615,36.87);
  Point_3 p2(-34.5781,-3.61804,39.9716);
  Triangle_3 cgt(p0,p1,p2);
  Bbox_3 triBox(cgt.bbox());
  
  Bbox_3 otherBox(-52.3586,-14.3376,25.3037,-38.021,0,39.6414);
  
  if(do_intersect(cgt,otherBox)) std::cout<<"cgt and otherBox intersect"<< std::endl;
  else std::cout<<"cgt and otherBox do not intersect" << std::endl;
  if(do_intersect(triBox,otherBox)) std::cout<<"triBox and otherBox intersect"<<std::endl;
  else std::cout<<"triBox and otherBox do not intersect"<<std::endl;
  return 0;
}

```

The above code outputs:

```
cgt and otherBox intersect
triBox and otherBox do not intersect
```

In the below image otherBox is green, triBox is gray and cgt is red:

![a](https://user-images.githubusercontent.com/111967692/186377258-0ab7b391-941e-4058-a24f-003a6cfe56c3.png)

## Environment

OS: Ubuntu 22.04
g++ (Ubuntu 11.2.0-19ubuntu1) 11.2.0
Release
CGAL 5.5
Boost 1.66

**Comment by lrineau** [comment]
I confirm the bug. The bug seems to be in static filters, because the behavior is right with
```c++
#define CGAL_NO_STATIC_FILTERS 1
```

**Comment by lrineau** [comment]
More info: the bug was first introduced in CGAL-5.4 (correct behavior with CGAL-5.3), probably by PR #5767.

**Comment by lrineau** [comment]
> More info: the bug was first introduced in CGAL-5.4 (correct behavior with CGAL-5.3), probably by PR #5767.

I confirm the bug was introduced in CGAL by the merge of PR #5767 (commit 50f30df08362e79d986a4e1e69eb3bd12f877dce).

**Comment by lrineau** [comment]
Fixed by the merge of https://github.com/CGAL/cgal/pull/6809.
