### ISSUE TITLE
Runtime error for polygon intersection

### ISSUE THREAD

**Issue by Alison-97** [CGAL/cgal#6829]
## Issue Details

This is a continuation from the [discussion here](https://github.com/CGAL/cgal/discussions/6822), about polygon intersection involving duplicated vertex. Please feel free to close this issue if the problem is the same as in that discussion. 

I'm aware that degenerated segment could not be constructed, but in the following scenarios, there's no degenerated segment involved. And yet I'm still getting runtime error when the polygon is in a specific position. 

I'm trying to check if the two polygons (pol1 & pol2) intersect with each other. In CGAL 5.5, the runtime error occurs when the pol1 (orange) is in position A, but not when it is moved to position B. However, previously on CGAL 4.11, both scenarios compute the result just fine. 

![temp](https://user-images.githubusercontent.com/97237245/188354852-727dc70d-850e-4b14-b78a-7ac0223c864d.png)

## Source Code
```
#include <CGAL/Exact_predicates_exact_constructions_kernel.h>
#include <CGAL/box_intersection_d.h>
#include <vector>
#include <CGAL/Polygon_2.h>
#include <CGAL/Boolean_set_operations_2/do_intersect.h>

typedef CGAL::Exact_predicates_exact_constructions_kernel K;
typedef CGAL::Polygon_2<K>                                  Polygon_2;
typedef CGAL::Point_2<K>                                    Point_2;
typedef std::map<int, Polygon_2>                            PolygonIndex;
typedef PolygonIndex::iterator                              Iterator;
typedef CGAL::Box_intersection_d::Box_with_handle_d<double, 2, Iterator>    Box;


struct KeyValuePair
{
    int key;
    int value;
    KeyValuePair(int ee1, int ee2) {
        key = ee1;
        value = ee2;
    };
};

std::list<KeyValuePair> intersectedPairList;

void CollectAllIntersectPairs(const Box& a, const Box& b)
{
    Iterator ait = a.handle();
    Iterator bit = b.handle();

    Polygon_2 pol1 = (*ait).second;
    Polygon_2 pol2 = (*bit).second;
    bool isIntersect = CGAL::do_intersect(pol1, pol2);

    if (isIntersect)
    {
        KeyValuePair kyPair = KeyValuePair((*ait).first, (*bit).first);
        intersectedPairList.push_back(kyPair);
    }
}

auto callback (const Box& a, const Box& b) { CollectAllIntersectPairs(a, b); };


int main(int argc, char* argv[])
{
    Polygon_2 pol1;
    // Position A
    pol1.push_back(Point_2(0, 0));
    pol1.push_back(Point_2(4, 0));
    pol1.push_back(Point_2(0, 4));

    // Position B
    //pol1.push_back(Point_2(12, 0));
    //pol1.push_back(Point_2(16, 0));
    //pol1.push_back(Point_2(12, 4));


    Polygon_2 pol2;
    pol2.push_back(Point_2(0, 10));
    pol2.push_back(Point_2(10, 10));
    pol2.push_back(Point_2(5, 5));
    pol2.push_back(Point_2(10, 0));
    pol2.push_back(Point_2(0, 0));      
    pol2.push_back(Point_2(5, 5));      

    std::vector<Polygon_2> polies;
    polies.push_back(pol1);
    polies.push_back(pol2);

    PolygonIndex   faces;
    for (unsigned int i = 0; i < polies.size(); i++)
    {
        faces.insert(std::pair<int, Polygon_2>(i, polies[i]));
    }

    // Create the corresponding vector of bounding boxes
    std::vector<Box> boxes;
    for (Iterator i = faces.begin(); i != faces.end(); ++i) {
        Polygon_2 poly = i->second;
        boxes.push_back(Box(poly.bbox(), i));
    }

    CGAL::box_self_intersection_d(boxes.begin(), boxes.end(), callback);

    return 0;
}   
```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows 11 version 21H2, 64 bits
* Compiler: Visual Studio 2022
* Release or debug mode: Debug
* CGAL version: 5.5
* Boost version: 1_65_1

**Comment by efifogel** [comment]
Please close it; the code works as advertised.
   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by lrineau** [comment]
@Alison-97 Alison, the situation you described was never allowed, even in CGAL 4.11. Polygons must be *simple*. See the definitions at https://doc.cgal.org/latest/Boolean_set_operations_2/index.html#title1. You can check that the definitions and conditions were exactly the same in CGAL-4.11: https://doc.cgal.org/4.11.3/Boolean_set_operations_2/index.html#title1

**Comment by Alison-97** [comment]
@lrineau Thanks for sharing the links. The definitions and conditions were indeed the same for both versions (CGAL 4.11 and 5.5) in the documentation. So if we try to run the code on CGAL 5.5, we'll see that the code fails to run because of the precondition check, which is reasonable because the polygon is _relatively simple_ and not just _simple_ as you said. 

But the strange thing is that we _did_ and can still get the equivalent code to work on CGAL 4.11 without any precondition assert checking error message. Here’s a full compilable code. Note that all the code is the same, except that one include header is changed due to the file being moved in between versions.

We managed to get this code compiled and run ( without runtime exception) in Release x64 mode. Debug x64 mode, however, fails to compile due to LNK 1120 linker errors.

By inspecting the CGAL internal code it does seem that in both CGAL 4.11 and 5.5, the precondition check is invoked at General_polygon_set_on_surface_2.h ([PreconditionValidationPolicy.is_valid method](https://github.com/CGAL/cgal/blob/master/Boolean_set_operations_2/include/CGAL/General_polygon_set_on_surface_2.h#L28)), so we have no idea why 4.11 still passes. If only we could get Debug x64 mode compilation to work, we could trace through the statement and check why the precondition is not invoked. Alas we couldn’t. 

Therefore we would appreciate it if you could lend us a helping hand here by telling exactly why CGAL 4.11 doesn't throw a precondition check error, which it should, judging from the documentation. Thank you so much!

```
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/box_intersection_d.h>
#include <vector>
#include <CGAL/Polygon_2.h>
#include <CGAL/Boolean_set_operations_2.h>

typedef CGAL::Exact_predicates_inexact_constructions_kernel K;
typedef CGAL::Polygon_2<K>                                  Polygon_2;
typedef CGAL::Point_2<K>                                    Point_2;
typedef std::map<int, Polygon_2>                            PolygonIndex;
typedef PolygonIndex::iterator                              Iterator;
typedef CGAL::Box_intersection_d::Box_with_handle_d<double, 2, Iterator>    Box;


struct KeyValuePair
{
    int key;
    int value;
    KeyValuePair(int ee1, int ee2) {
        key = ee1;
        value = ee2;
    };
};

std::list<KeyValuePair> intersectedPairList;

void CollectAllIntersectPairs(const Box& a, const Box& b)
{
    Iterator ait = a.handle();
    Iterator bit = b.handle();

    Polygon_2 pol1 = (*ait).second;
    Polygon_2 pol2 = (*bit).second;
    bool isIntersect = CGAL::do_intersect(pol1, pol2);

    if (isIntersect)
    {
        KeyValuePair kyPair = KeyValuePair((*ait).first, (*bit).first);
        intersectedPairList.push_back(kyPair);
    }
}

auto callback(const Box& a, const Box& b) { CollectAllIntersectPairs(a, b); };


int main(int argc, char* argv[])
{
    Polygon_2 pol1;
    pol1.push_back(Point_2(0, 0));
    pol1.push_back(Point_2(4, 0));
    pol1.push_back(Point_2(0, 4));
    //no runtime error when pol1 is farther apart at (12,0) (16,0), (12,4)

    Polygon_2 pol2;
    pol2.push_back(Point_2(0, 10));
    pol2.push_back(Point_2(10, 10));
    pol2.push_back(Point_2(5, 5));
    pol2.push_back(Point_2(10, 0));
    pol2.push_back(Point_2(0, 0));
    pol2.push_back(Point_2(5, 5));
    // pol2 is a polygon with duplicated points (5,5)


    std::vector<Polygon_2> polies;
    polies.push_back(pol1);
    polies.push_back(pol2);

    PolygonIndex   faces;
    for (unsigned int i = 0; i < polies.size(); i++)
    {
        faces.insert(std::pair<int, Polygon_2>(i, polies[i]));
    }

    // Create the corresponding vector of bounding boxes
    std::vector<Box> boxes;
    for (Iterator i = faces.begin(); i != faces.end(); ++i) {
        Polygon_2 poly = i->second;
        boxes.push_back(Box(poly.bbox(), i));
    }

    CGAL::box_self_intersection_d(boxes.begin(), boxes.end(), callback);

    return 0;
}
```
