### ISSUE TITLE
Workaround for `Triangulation_ds_cell_base_3.circumcenter()`

### ISSUE THREAD

**Issue by qiancao** [CGAL/cgal#6839]
## Issue Details

In CGAL version 4.8.2, `Triangulation_ds_cell_base_3.h` has the method `circumcenter()` (https://github.com/CGAL/cgal/blob/releases/CGAL-4.8.2/TDS_3/include/CGAL/Triangulation_ds_cell_base_3.h, lines 207-218).

```
  // This is here in the *ds*_cell_base to ease its use as default
  // template parameter, so that the .dual() functions of Delaunay_3
  // still work.
  template < typename Traits >
  typename Traits::Point_3
  circumcenter(const Traits& gt) const
  {
    return gt.construct_circumcenter_3_object()(this->vertex(0)->point(),
                                                this->vertex(1)->point(),
                                                this->vertex(2)->point(),
                                                this->vertex(3)->point());
  }
```

This has been removed in the current master branch. I'm using a library that performs delunay triangulation with `Triangulation_cell_base_with_info_3` which relies on this `circumcenter` in its `.dual()` function, as stated in the comments. The pseudo code for this is:

```
typedef CGAL::Exact_predicates_inexact_constructions_kernel K;
typedef CGAL::Triangulation_vertex_base_with_info_3<VertexInfo, K> Vb;
typedef CGAL::Triangulation_cell_base_with_info_3<CellInfo, K> Cb;
typedef CGAL::Triangulation_data_structure_3<Vb, Cb> Tds;

triangulation = CGAL::Delaunay_triangulation_3<K, Tds>...
triangulation.dual(Cell_handle c) # where cell_handle is for Triangulation_cell_base_with_info_3. This relies on circumcenter() somewhere in the inheritance chain of Triangulation_cell_base_with_info_3
```

With this `circumcenter` removed, what is the suggested way of doing the same thing? Do I now need to subclass `Triangulation_cell_base_with_info_3`?

Thanks,
Q

**Comment by MaelRL** [comment]
The `circumcenter()` function has been moved to the cell class [Delaunay_triangulation_cell_base_3](https://doc.cgal.org/latest/Triangulation_3/classCGAL_1_1Delaunay__triangulation__cell__base__3.html) to better reflect the fact that the triangulation data structure does not handle geometry. So your stack should be:

```
typedef CGAL::Exact_predicates_inexact_constructions_kernel K;
typedef CGAL::Triangulation_vertex_base_with_info_3<VertexInfo, K> Vb;
typedef CGAL::Triangulation_cell_base_with_info_3<CellInfo, K> Cbb;
typedef CGAL::Delaunay_triangulation_cell_base_3<K, Cb> Cb;
typedef CGAL::Triangulation_data_structure_3<Vb, Cb> Tds;
```

Note that you can also use [Delaunay_triangulation_cell_base_with_circumcenter_3](https://doc.cgal.org/latest/Triangulation_3/classCGAL_1_1Delaunay__triangulation__cell__base__with__circumcenter__3.html), which provides a caching mechanism for the circumcenter, if you need to re-use it multiple times.
