### ISSUE TITLE
IntersectsRobustness test fails since CGAL 5.4

### ISSUE THREAD

**Issue by lbartoletti** [CGAL/cgal#6843]
## Issue Details

One of the (old) CGAL test fails on (at least) macOs and OpenSuse: 

The original issue was on SFCGAL: https://gitlab.com/Oslandia/SFCGAL/-/issues/257

## Source Code

```cpp
#include <iostream>

#include <boost/test/unit_test.hpp>

#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>

#include <CGAL/Point_2.h>
#include <CGAL/Point_3.h>
#include <CGAL/Plane_3.h>

#include <cmath>

typedef CGAL::Exact_predicates_inexact_constructions_kernel Kernel ;
typedef Kernel::Vector_2          Vector_2 ;
typedef Kernel::Vector_3          Vector_3 ;
typedef Kernel::Point_2           Point_2 ;
typedef Kernel::Point_3           Point_3 ;
typedef Kernel::Segment_2         Segment_2 ;
typedef Kernel::Segment_3         Segment_3 ;

// always after CGAL
using namespace boost::unit_test ;

BOOST_AUTO_TEST_SUITE( CGAL_KernelTest )

BOOST_AUTO_TEST_CASE( testIntersectsRobutness )
{
    Segment_2 ab( Point_2( 0.0,0.0 ) , Point_2( 1.0,3.0 ) );
    Segment_2 cd( Point_2( 0.0,1.0 ) , Point_2( 1.0,1.0 ) );
    Segment_2 ef( Point_2( -1.0,3.0 ), Point_2( 1.0,0.0 ) );

    CGAL::Object abIcd_ = CGAL::intersection( ab, cd );
    const Point_2* abIcd = CGAL::object_cast<Point_2>( &abIcd_ ) ;
    BOOST_REQUIRE( abIcd != NULL );

    CGAL::Object abIef_ = CGAL::intersection( ab, ef );
    const Point_2* abIef = CGAL::object_cast<Point_2>( &abIef_ ) ;
    BOOST_REQUIRE( abIef != NULL );

//	std::cout << (*abIcd) << std::endl;
//	std::cout << (*abIef) << std::endl;
    BOOST_CHECK( ( *abIcd ) == ( *abIef ) ) ;
}



BOOST_AUTO_TEST_SUITE_END()

```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Mac, Linux
* Compiler: clang
* Release or debug mode: release
* Specific flags used (if any):
* CGAL version: > 5.4.x
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by sloriot** [comment]
Are you using `Exact_predicates_inexact_constructions` on purpose in the test? It should be `Exact_predicates_exact_constructions` if you want to have some guarantees.

**Comment by lbartoletti** [comment]
> Are you using `Exact_predicates_inexact_constructions` on purpose in the test? It should be `Exact_predicates_exact_constructions` if you want to have some guarantees.

The tests were here before me (7 years old!) :)

I didn't pay attention to them before this CI problem with CGAL >= 5.4
