### ISSUE TITLE
CGAL demo compilation problem

### ISSUE THREAD

**Issue by alvi1995** [CGAL/cgal#6847]
## Issue Details

I want to use CGAL  for learning CFD meshing from the basics. So like any learning that involves programming, the environment setup is pretty important. To test my setup, I tried to compile the AABB_tree demo and I was able to link all the necessary libraries properly. But I found some source file missing in the given demo- 

1. Scene_moc.cpp 
2. Viewer_moc.cpp
3. MainWindow_moc.cpp
4. ui_ImageInterface.h

I am not very good with Cmake so I have tried- 

1. created a QtWidget project in QtCreator in **D:\CC++\Qt\demo** with qmake.  
2. deleted the default generated files(mainwindow.h, mainwindow.ui, etc....)
3. Added the given demo files in my project and copied the Resources folder to **demo** directory.
4. copied the necessary third party libraries to **demo** directory.
5. After that my demo directory looks like 
![Screenshot 2022-09-15 053914](https://user-images.githubusercontent.com/57279626/190281236-d0c89054-1d34-4748-958d-1253fed082ce.jpg)

which generates the error 
![Screenshot 2022-09-15 054231](https://user-images.githubusercontent.com/57279626/190281549-c8c2539f-93d8-4769-ac48-09412338ff35.jpg)

I could not find the above mentioned files in anywhere in demo. So my question is that- 

> Is it on the users to generate those files and then compile?

`
## Source Code

my pro file `demo.pro`

```
QT       += core gui opengl svg

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

CONFIG += c++14

# You can make your code fail to compile if it uses deprecated APIs.
# In order to do so, uncomment the following line.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

INCLUDEPATH += boost_1_80_0 \
               gmp_x64-windows-static\include \
               mpfr_x64-windows-static\include \
               CGAL-5.5\include


SOURCES += \
    MainWindow.cpp \
    Scene.cpp \
    Viewer.cpp \
    benchmarks.cpp \
    main.cpp

LIBS += -LD:\CC++\Qt\demo\gmp_x64-windows-static\lib -lgmp \
        -LD:\CC++\Qt\demo\mpfr_x64-windows-static\lib -lmpfr

HEADERS += \
    Color_ramp.h \
    MainWindow.h \
    Refiner.h \
    Scene.h \
    Viewer.h \
    types.h

FORMS += \
    MainWindow.ui

# Default rules for deployment.
qnx: target.path = /tmp/$${TARGET}/bin
else: unix:!android: target.path = /opt/$${TARGET}/bin
!isEmpty(target.path): INSTALLS += target

RESOURCES += \
    AABB_demo.qrc

```
## Environment

* Operating system (Windows 11):
* Compiler: msvc-142
* Release or debug mode:  both
* Specific flags used (if any): none
* CGAL version: 5.5
* Boost version: 1.80
* Other libraries versions if used (Eigen, TBB, etc.): gmp & mpfr(latest version); Qt5.15.2

**Comment by lrineau** [comment]
Hi, thanks for your detailed message in that issue. Unfortunately, my answer will probably disappoint you.

The AABB_demo from CGAL is already shipped with a way to build it: its `CMakeLists.txt`, to be used by CMake to produce a build system (for example a Visual Studio solution, on Windows). That is the tool you should (must) use to configure and build the application.

`qmake` is a different build system generator, and it uses different conventions. The code of the AABB demo is not ready for the usage of `qmake`. In particular, a file `.cpp` files include file named `ui_*.h` whereas the build system produced by `qmake` probably produces one `.cpp` per Ui file.
