### ISSUE TITLE
Isotropic_remeshing: Collapse Short Edges

### ISSUE THREAD

**Issue by FuzhangHePTW** [CGAL/cgal#6851]
## Issue Details

As this picture shown, the inside surface of this hole is meshed badly;
So I want to remesh it, but only the inside surface.
The outside surface is simple, but enough, so i wan't change it.
Are there any functions that can collapse these short mesh edges ?
(Some thing like "collapse_short_edges" in Pymesh: https://pymesh.readthedocs.io/en/latest/mesh_processing.html)

![Remesh](https://user-images.githubusercontent.com/62293522/190635688-cfd5792d-f78a-4280-8906-0a6266f85f29.jpg)

## Source Code

My source Code is the same as the example: 
Polygon_mesh_processing/isotropic_remeshing_example.cpp

Only the input file is different, see the zip-file in Attachment.
[Core_NewWS7.zip](https://github.com/CGAL/cgal/files/9583924/Core_NewWS7.zip)
(off file type is not supported, so i compressed it in zip.)

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows
* Compiler: Visual Studio 2022
* Release or debug mode: 
* Specific flags used (if any):
* CGAL version: 5.4
* Boost version: 
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by janetournois** [comment]
[CGAL::Polygon_mesh_processing::isotropic_remeshing](https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__meshing__grp.html#gaa5cc92275df27f0baab2472ecbc4ea3f) comes with a large set of options to activate/deactivate the different remeshing steps.
You can use `parameters::do_split(false).do_collapse(true).do_flip(false).number_of_relaxation_steps(0).do_project(false)` to have only the collapse step

**Comment by FuzhangHePTW** [comment]
Thank You, Jane, It works; 
(I know it, that CGAL can do this !!!)

**Comment by FuzhangHePTW** [comment]
Hallo, @janetournois 

After many times of trying the different remesh steps, i still can't get a perfect remeshed geometry.
For the simple mesh, it works ok. (But there are still short edges)
![image](https://user-images.githubusercontent.com/62293522/191023334-1fd76d52-eb50-48d2-81fa-dd20352eae06.png)

For complicate case (like this [Mesh_Datei](https://gist.github.com/FuzhangHePTW/c118e6b83eee9aac312417a96ec3bd9e)), the remeshing with `parameters::do_split(false).do_collapse(true).do_flip(false).number_of_relaxation_steps(0).do_project(false) ` almost doesnot work. 
(target_edge_length = 1; nb_iter = 3)
![image](https://user-images.githubusercontent.com/62293522/191025702-ede529bc-ecc7-417c-8b4c-e2986a8cb972.png)

Is there some way to solve this ?

Ps. I know the roughly diameter of the insider surface, which needed to be remeshed. For example, is there some way to pick up this surface...

**Comment by janetournois** [comment]
It is possible to remesh only a set of faces of the input surface, if you know how to select them

**Comment by FuzhangHePTW** [comment]
that is exact the problem.
Is it the way like this example: [corefinement_difference_remeshed](https://doc.cgal.org/latest/Polygon_mesh_processing/Polygon_mesh_processing_2corefinement_difference_remeshed_8cpp-example.html)  ?
I try about one hour to understand it, but failed...
Can you tell me, in which direction should i look for ?
