### ISSUE TITLE
Boolean Operation error by remeshed geometry

### ISSUE THREAD

**Issue by FuzhangHePTW** [CGAL/cgal#6853]
## Issue Details

As the issue #6481 mentioned, the geometry becomes more and more complicate by doing boolean operation. So i remesded one part before the further boolean operation. But then i get the following error by doing boolean operation with the remeshed part.

> CGAL error: assertion violation!
> Expression : it_poly_hedge!=edge_to_hedge.end()
> File       : C:\dev\vcpkg\installed\x64-windows\include\CGAL/Polygon_mesh_processing/internal/Corefinement/Visitor.h
> Line       : 1278
> Explanation:
> Refer to the bug-reporting instructions at https://www.cgal.org/bug_report.html

## Source Code

https://gist.github.com/FuzhangHePTW/f195809db8bdea49152f974a9149e584

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows 11
* Compiler: Visual Studio 2022
* Release or debug mode: debug
* Specific flags used (if any):
* CGAL version: 5.4
* Boost version: 1.78.0
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by sloriot** [comment]
Did you check that the remeshing does not introduce self-intersections?

**Comment by FuzhangHePTW** [comment]
Yes, there are self-intersections in the remeshed geometry.

> Using parallel mode? 0
> There are self-intersections.
> Elapsed time (does self intersect): 0.00199986
> 127 pairs of triangles intersect.
> Elapsed time (self intersections): 1.573

I think that i need to repair it.

**Comment by FuzhangHePTW** [comment]
# Issue Details
By trying to repair the remeshed geometry i get another error.
The repair function is  "PMP::experimental::autorefine_and_remove_self_intersections(mesh);"
@sloriot can you help me by this ?

> Split border...done.
> Start remeshing of C:/dev/data//output/Core_NewWS7.off (4282 faces)...
> Remeshing done.
> CGAL error: assertion violation!
> Expression : oxz_pqr != COLLINEAR
> File       : C:\dev\vcpkg\installed\x64-windows\include\CGAL/predicates/kernel_ftC3.h
> Line       : 190
> Explanation:
> Refer to the bug-reporting instructions at https://www.cgal.org/bug_report.html

# Source Code
https://gist.github.com/FuzhangHePTW/5b556061702ebb1de11518fd4cba264e
