### ISSUE TITLE
[RFE] CGAL testsuite: add a platform with clang main branch 

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#6857]
## Feature Request

[Clang 15.0 was publish early September 2022](https://releases.llvm.org/). It seems that the new libc++ STL shipped with it has removed some of the deprecated functions, and that [broke at least Boost ContainerHash](https://github.com/boostorg/container_hash/issues/24) (that we do not use as far as I know).

Anyway, in my opinion the CGAL project should test the `main` branch of LLVM and clang (and libc++), the same way we test the `trunk` of gcc, and the preview versions of MSVC.

*Note: I plan to assign that issue to an apprentice of GeometryFactory, as the first task of the apprenticeship.*

### Intermediate Steps

1. On one own machine, try and compile LLVM and clang and libc++ from Git. See that page: https://clang.llvm.org/get_started.html
2. Check if the newly built compiler can correctly compile a few examples from CGAL `master` branch.
3. Create a new Docker image (with its `Dockerfile`) with "clang from git" (or using the [nightly builds packages for Debian](https://apt.llvm.org/)), and most of CGAL dependencies, and *without gcc*.
4. Check that CGAL examples can be built using that new Docker image.
5. Create a pull-request on https://github.com/CGAL/cgal-testsuite-dockerfiles to add that new `Dockerfile` and Docker image.

**Comment by mglisse** [comment]
(just passing by) https://apt.llvm.org/ may be easier than building from source, if you intend to test it on linux.

**Comment by lrineau** [comment]
> (just passing by) [apt.llvm.org](https://apt.llvm.org/) may be easier than building from source, if you intend to test it on linux.

Yes, that's great! Of course that `apt` repository is the right tool to use for the task. Thanks for pointing it out. 🙏

**Comment by lrineau** [comment]
Fixed by the merge of https://github.com/CGAL/cgal-testsuite-dockerfiles/pull/126.
