### ISSUE TITLE
Reading Hyperbolic Delaunay Triangulations

### ISSUE THREAD

**Issue by maxkatzmann** [CGAL/cgal#6869]
## Issue Details

Hi everyone, thanks for taking the time to look into my issue. I'm trying to use CGAL to compute hyperbolic Delaunay triangulations and am under the impression that I'm doing something wrong as it seems like one edge of the triangulation is not returned.

Here's the [instance](https://github.com/CGAL/cgal/files/9623294/Poincare.Disk.pdf) that I'm interested in. Points A-J are the sites and the remaining points are intersections that I added when drawing the relevant parts of the Voronoi diagram.

To me it looks like E and H are in neighboring Voronoi cells and should therefore be connected by an edge in the Delaunay triangulation. However, the following code yields the edges of the triangulation that I would expect, except for E-H. I tried to follow the CGAL example code for computing hyperbolic Delaunay triangulations in [ht2_example.cpp](https://github.com/CGAL/cgal/blob/master/Hyperbolic_triangulation_2/examples/Hyperbolic_triangulation_2/ht2_example.cpp) and wonder whether I'm missing something when reading the edges of the triangulation.

## Source Code

[Source Code](https://gist.github.com/maxkatzmann/3d0e6d25f8eab4785d799d274e112f7a)
[CMake File](https://gist.github.com/maxkatzmann/2b18f96159693a6429e03d365b188acd)

Here's the [output](https://gist.github.com/maxkatzmann/462579ce21bf77a54ddd6b0a32828e7b) of
```
cmake -DCMAKE_BUILD_TYPE=Release .
make
./cgal_util
```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): macOS Big Sur Version 11.6.4 (64 bits)
* Compiler: AppleClang 13.0.0.13000029
* Release or debug mode: Release
* Specific flags used (if any):
* CGAL version: stable 5.5 (installed via homebrew)
* Boost version: stable 1.79.0 (installed via homebrew)
* Other libraries versions if used (Eigen, TBB, etc.):

I hope that the report lists what is expected. If more information is needed, I'm happy to provide it. Thanks again for taking the time!

**Comment by MaelRL** [comment]
Thanks for the bug report, it'll be fixed in https://github.com/CGAL/cgal/pull/6883.

![Screenshot from 2022-09-26 16-49-01](https://user-images.githubusercontent.com/5074170/192308464-2ac5b4ac-969c-4946-8353-83f8c1b3647c.png)

**Comment by maxkatzmann** [comment]
Thank you very much for the quick response! I'm looking forward to working with the updated code!

**Comment by lrineau** [comment]
> Thank you very much for the quick response! I'm looking forward to working with the updated code!

Thanks @maxkatzmann for your bug report. It is now fixed, in the `master` branch of CGAL. It will not be backported to any CGAL version 5.5.x, because the fix requires a breaking change of the API (see commit 8a1e8b16ce023f53d33174f94a78f050373bd14f). CGAL-5.6 is planned for June 2023. Meanwhile, you should use CGAL from its `master` branch.
