### ISSUE TITLE
Arrangement_on_surface_2 missing link

### ISSUE THREAD

**Issue by albert-github** [CGAL/cgal#6881]
In the file Arrangement_on_surface_2/classArrTraits_1_1CompareYOnBoundary__2.html  I see(made links red so they are better visible):

![image](https://user-images.githubusercontent.com/5223533/192282878-d3642fc5-63b1-40d7-936c-beed298d57e3.png)

Is this correct / intended or an omission in the relevant include file.

See file Arrangement_on_surface_2/doc/Arrangement_on_surface_2/Concepts/ArrangementOpenBoundaryTraits_2.h

**Comment by albert-github** [comment]
Sorry, I don't see a patch, when send as attachment to an email I think (when I remember correctly) attachments won't come through.

**Comment by efifogel** [comment]
You are correct of course.
Anyhow, just remove the line:
* \cgalHasModel ArrangementOpenBoundaryTraits_2::Compare_y_on_boundary_2
Thanks

   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #6890

**Comment by efifogel** [comment]
Thank you
   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/
