### ISSUE TITLE
Generator: missing link

### ISSUE THREAD

**Issue by albert-github** [CGAL/cgal#6885]
In the file Generator/classCGAL_1_1Points__on__segment__2.html I see(made links red so they are better visible):

![image](https://user-images.githubusercontent.com/5223533/192336307-382ae159-7d55-4533-ae63-b14ffa0b7d6a.png)

Is this correct / intended or an omission in the relevant include file?

See file: Generator/doc/Generator/CGAL/point_generators_2.h

**Comment by afabri** [comment]
It must be `points_on_segment_2`.

**Comment by afabri** [comment]
And [here](https://doc.cgal.org/latest/Generator/classCombinationElement.html)   the `CGAL::`   namespace prefix is missing for the See Also item.

Is there a new warning feature in a doxygen version that allows you to spot errors?

**Comment by afabri** [comment]
There are also occurences of `std::random_shuffle`. First there should be `()`.   Then we maybe should write `CGAL::cpp98::random_shuffle()` so that it links [here](https://doc.cgal.org/latest/STL_Extension/group__STLAlgos.html#ga03da480625f380d4d06ea64de211add4).

**Comment by albert-github** [comment]
No there is no warning for this, I'm doing a quick browse ( :-( )through a number of files based on the fact that I was missing some `"` and that some documentation was garbled.

Where should the `CGAL::points_on_segment_2` point to ?

Do you make the relevant PRs?

**Comment by albert-github** [comment]
Note in Generator/classCGAL_1_1Random__points__on__segment__2.html the See Also section mentions `CGAL::Points_on_segment_2<Point_2>`

**Comment by afabri** [comment]
Adding the `_2` suffix makes that it links automatically to [here](https://doc.cgal.org/latest/Generator/group__PkgGeneratorsRef.html#ga58b8faf4c090fc9b367f51d9004cde4c).    And there is the class with capital P and the function with lower case p.

**Comment by afabri** [comment]
I can make the PR.  Please confirm so that we do not double work.

**Comment by albert-github** [comment]
@afabri please make the PR for the mentioned cases
