### ISSUE TITLE
Documentation missing versions in drop down menu

### ISSUE THREAD

**Issue by albert-github** [CGAL/cgal#6886]
In the local generated version of the documentation of the master version we see:

![image](https://user-images.githubusercontent.com/5223533/192337448-33582e56-41e4-40f4-9b91-7ffd2fddc363.png)

Here references to the versions like 5.5, 5.4.2 and 5.3.2 are missing.

Is this intentionally or ...

**Comment by lrineau** [comment]
I cannot reproduce. What I see, at the page https://cgal.geometryfactory.com/CGAL/doc/master/Generator/annotated.html is:
![Screenshot_20220927_151312](https://user-images.githubusercontent.com/5746675/192536077-5d3720a4-ab8c-4d52-8cf5-8f17ca12a467.png)

**Comment by lrineau** [comment]
Maybe a cache issue? What if you force the refresh of the page with <kbd>shift+F5</kbd>?

**Comment by albert-github** [comment]
The problem is that your link points to a build using the doxygen version 1.8.13 and probably the Documentation/doc/resources/1.8.13 directory, I'm talking about a doxygen master build using the Documentation/doc/resources/1.9.3 directory.

**Comment by lrineau** [comment]
You are right. I forgot to update that file. Now we have five copies of it!

I fixed that directly by a push in `master`, commit https://github.com/CGAL/cgal/commit/b8e342d84525a3ce713e9111ba6d105b6de82c80,

**Comment by albert-github** [comment]
Maybe to think again of obsoleting some builds ...  😉
