### ISSUE TITLE
Kernel_23: inconsistent documentation

### ISSUE THREAD

**Issue by albert-github** [CGAL/cgal#6891]
In the file Kernel_23/classCGAL_1_1Sphere__3.html we see:

![image](https://user-images.githubusercontent.com/5223533/192515313-c87b96fa-aded-4fbf-9753-1b457e1c58d8.png)

and

![image](https://user-images.githubusercontent.com/5223533/192515462-e78e5155-3b1a-4e89-945b-eb77be34deae.png)

So in one case a mathematical symbol and in the other case a description.
(Happens on more places)

In my opinion both should either be with a mathematical symbol or as a description.

**Comment by albert-github** [comment]
Which version should it be:
- mathematical symbol (I think best also seen the use of the greater equal)
- the descriptive version

**Comment by sloriot** [comment]
I prefer the c++ version as it does not required mathjax

**Comment by albert-github** [comment]
@sloriot, neither version uses MathJax one is just text and the other is just `=`. The MathJax version is used necessary for things like unequal and greater equal (or do you want to have here `!=` and `>=` as text.

**Comment by albert-github** [comment]
Made a small test:
```
- in backticks `==` and plain text ==
- in backticks `!=` and plain text !=
- in backticks `>=` and plain text >=
- in backticks `<=` and plain text <=
- `\f$ == \f$` result \f$ == \f$
- `\f$ != \f$` result \f$ != \f$
- `\f$ >= \f$` result \f$ >= \f$
- `\f$ <= \f$` result \f$ <= \f$
- HTML symbol `&Equal;&Equal;` result &Equal;&Equal;
- HTML symbol `&ne;` result &ne;
- HTML symbol `&le;` result &le;
- HTML symbol `&ge;` result &ge;
```
result:

![image](https://user-images.githubusercontent.com/5223533/192569560-6d07d27f-5879-46c5-b1c6-6ba4a327ca9e.png)

**Comment by afabri** [comment]
In a mathematical formula I prefer mathematical symbols, but  to test if a point equals the origin I prefer `==`.   And I would not  even consider `x == 0` a formula.

**Comment by albert-github** [comment]
And what about `1 <= x <= 100` formula or test so:And how about ranges:

![image](https://user-images.githubusercontent.com/5223533/192572255-42ea950d-4c48-4b96-b724-f845159d53ea.png)

**Comment by afabri** [comment]
Why not just backticks  `1 <= x <= 100`

**Comment by albert-github** [comment]
Might be the best readable in the code.

@sloriot what do you think

**Comment by sloriot** [comment]
That's indeed what I meant. In a precondition I prefer seeing the C++ code.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #6916
