### ISSUE TITLE
Polyhedron demo - Point set normal estimation crashes

### ISSUE THREAD

**Issue by soesau** [CGAL/cgal#6893]
## Issue Details

The demo crashes after loading a point cloud (with or without normals) and launching the normal estimation (any of the three methods). Before the crash a dialog with a progress bar appears and after the bar finishes the dialog disappears and then the demo crashes.

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows 10 64
* Compiler: MSVC2022
* Release or debug mode: both
* Specific flags used (if any):
* CGAL version: master
* Boost version: 1.78
* Other libraries versions if used (Eigen, TBB, etc.): Eigen 3.4.0

**Comment by afabri** [comment]
@soesau I cannot reproduce this.  Also I do not see a progress bar.

**Comment by afabri** [comment]
@soesau can we have a look at this on Thursday.

**Comment by soesau** [comment]
I rebuild from current HEAD. I may have changed some libraries (at least Boost 1.80) and it does not crash anymore. I still see a dialog box with progress bar, though.
