### ISSUE TITLE
Periodic_2_triangulation_2: Strange documentation

### ISSUE THREAD

**Issue by albert-github** [CGAL/cgal#6896]
https://github.com/CGAL/cgal/blob/b8e342d84525a3ce713e9111ba6d105b6de82c80/Periodic_2_triangulation_2/doc/Periodic_2_triangulation_2/CGAL/Periodic_2_triangulation_2.h#L103-L107

results in:

![image](https://user-images.githubusercontent.com/5223533/192574239-079e1dd8-1fbb-4f25-9d0d-cd9496173fd2.png)

but it is completely unclear what the meaning of the `@` is here (at least to me).

**Comment by afabri** [comment]
Well, it is a comment for what follows, so it should be `Locate_type`, shouldn't it?

**Comment by albert-github** [comment]
I think so too, shall I make a PR for it?

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #6897
