### ISSUE TITLE
Polytope_distance_d: Mentioning of `get_.()` functions

### ISSUE THREAD

**Issue by albert-github** [CGAL/cgal#6905]
In the file Polytope_distance_d/classWidthTraits__3.html we see:

![image](https://user-images.githubusercontent.com/5223533/192771426-ff62d636-f374-4a11-9698-1f8c6d3bc907.png)

based on the code:
https://github.com/CGAL/cgal/blob/b8e342d84525a3ce713e9111ba6d105b6de82c80/Polytope_distance_d/doc/Polytope_distance_d/Concepts/WidthTraits_3.h#L28-L41

The question is is the `get_.()` pointing just to `get_a()`, `get_b()`, `get_c()` and `get_d()` respectively `get_hx()`, `get_hy()`, `get_hz()` and `get_hw()` or to the complete set of get functions:
![image](https://user-images.githubusercontent.com/5223533/192771855-18d5e97d-3b99-4860-b8dc-bf6eceb48cd1.png)

In the first case I think it would be better to mention the functions explicitly in the later case I thing the reference should be `get_...()`.

**Comment by MaelRL** [comment]
I understand it as matching both `get_a/b/c/d` and `get_place_coefficients` (and similarly for the point). It could be changed to `get_...` or `get_XXX` indeed.
