### ISSUE TITLE
Surface_mesh_deformation: Videos not accessible

### ISSUE THREAD

**Issue by albert-github** [CGAL/cgal#6911]
In the file: [Surface_mesh_deformation/index.html#title12](https://doc.cgal.org/5.5.1/Surface_mesh_deformation/index.html#title12) we see:

![image](https://user-images.githubusercontent.com/5223533/192998132-ff244b3d-81db-4654-9f9b-88ca6334fdfc.png)

So the videos are not accessible.
- How can de user access these videos?

In general:
- it it not a good idea to have this type of information (as it is specific to CGAL) on an external site as
  - the information might not be persistent
  - an Internet access is necessary to view it even when one has the documentation locally available.

**Comment by sloriot** [comment]
Fixed

**Comment by albert-github** [comment]
I can now see the videos (though they are still hosted externally, so an Internet access is required even when one has the documentation locally available)

**Comment by sloriot** [comment]
With the current layout of the doc, I don't see an easy way not to have them in the code repo, inducing a increase of size. So I prefer keeping them hosted externally.

**Comment by albert-github** [comment]
I agree that the package size would probably increase dramatically (no idea how big the videos are).
Also far from ideal but maybe analogous to the examples, so separate download package (will be a one time action of the person installing the documentation), but gives also better opportunities to make videos version dependent.
