### ISSUE TITLE
Exported target for libCGAL.so in CGALExports.cmake is versioned, breaking CMake RPATH handling

### ISSUE THREAD

**Issue by kynan** [CGAL/cgal#692]
Due to a [CMake bug](https://cmake.org/Bug/view.php?id=15938), RPATHs are missing from the link line for the versioned .so. CGAL exports.

As a workaround, until that CMake bug is fixed, could there be an option to disable .so versioning for exported targets?

**Comment by sloriot** [comment]
Could #645 be related to the bug you point out?

**Comment by lrineau** [comment]
Can you be more specific? In the file `CGALExports.cmake` generated during the configuration of CGAL libraries, the path of the binaries is a full path.

Then, if you use that file, CMake, at least on my platform (Linux Fedora 23) does generate a RPATH. For example, for the link of `demo/Polyhedron/Polyhedron_3.cpp` into the `Polyhedron_3` target, the command line is:
> /usr/lib64/ccache/c++    -frounding-math -std=c++1y -fvisibility=hidden -Wall -Wextra -Wno-maybe-uninitialized -g -Og  -z defs CMakeFiles/Polyhedron_3.dir/Polyhedron_3.cpp.o CMakeFiles/Polyhedron_3.dir/Polyhedron_3_automoc.cpp.o  -o Polyhedron_3  -L/home/lrineau/Git/Polyhedron-clipping_snapping-lrineau/build/lib -rdynamic -lmpfr -lgmp -lGLU -lGL -lGLU -lGL -lz libpolyhedron_demo.so /usr/lib64/libQt5ScriptTools.so.5.5.1 libdemo_framework.so -lGLU -lGL -lGLU -lGL -lz -ltbb -ltbbmalloc -pthread -lQGLViewer-qt5 -lGL -lGLU libgl_splat.so libpoint_dialog.so ../../lib/libCGAL_Qt5.so.11.0.1 /usr/lib64/libQt5Svg.so.5.5.1 ../../lib/libCGAL_ImageIO.so.11.0.1 ../../lib/libCGAL.so.11.0.1 -lmpfr -lgmp -lz /usr/lib64/libQt5OpenGL.so.5.5.1 /usr/lib64/libQt5Xml.so.5.5.1 /usr/lib64/libQt5Widgets.so.5.5.1 /usr/lib64/libQt5Gui.so.5.5.1 /usr/lib64/libQt5Script.so.5.5.1 /usr/lib64/libQt5Core.so.5.5.1 -lGLU -lGL **-Wl,-rpath,/home/lrineau/Git/Polyhedron-clipping_snapping-lrineau/build/lib:/home/lrineau/Git/Polyhedron-clipping_snapping-lrineau/build/demo/Polyhedron**

The RPATH option is the last one. @kynan, can you tell us more about your platform, the content of the file `CGALExports.cmake`, and the linker command line that exposes the issue?

**Comment by kynan** [comment]
@lrineau This is with the CGAL 4.7 release, CentOS 7.1 x64, CMake 2.8.11 (also tested with 3.4.3), gcc 4.8.3

I've used the simplest possible test case:
```
cmake_minimum_required( VERSION 2.8.11 FATAL_ERROR )
project( cmake-link-test )
find_package( CGAL REQUIRED )
add_executable( main main.c )
target_link_libraries( main ${CGAL_LIBRARY} )
```

The link line is:
```
/usr/bin/gcc      CMakeFiles/main.dir/main.c.o  -o main -rdynamic /usr/local/apps/cgal/4.7.0/GNU/4.8.3/lib/libCGAL.so.11.0.1
```
As you can see this links against the *versioned* .so, since that is what we get as `${CGAL_LIBRARY}` and CMake will not add the RPATH to the link line.

[CGALExports-release.cmake](https://github.com/CGAL/cgal/files/110468/CGALExports-release.cmake.txt) is attached.

**Comment by lrineau** [comment]
Cc @bo0ts

**Comment by lrineau** [comment]
@kynan I had a look at your minimal example.

It is incorrect. The CMake API of CGAL is not documented, but you cannot use it that way.
Add either `include(${CGAL_USE_FILE})`:
```cmake
cmake_minimum_required( VERSION 2.8.11 FATAL_ERROR )
project( cmake-link-test )
find_package( CGAL REQUIRED )
include(${CGAL_USE_FILE})
add_executable( main main.c )
target_link_libraries( main ${CGAL_LIBRARY})
```
or link `main` with the imported target `CGAL::CGAL`:
```cmake
cmake_minimum_required( VERSION 2.8.11 FATAL_ERROR )
project( cmake-link-test )
find_package( CGAL REQUIRED )
add_executable( main main.c )
target_link_libraries( main CGAL::CGAL)
```

Both will work.

**Comment by kynan** [comment]
@lrineau I know I can use it in this way. However I want to point our that you're violating the "principle of least surprise" because most CMake users will (try to) use it the way I showed in my minimal example.

What if I want to make the CGAL dependency optional?

**Comment by lrineau** [comment]
@kynan Your minimal example cannot work. The `${CGAL_LIBRARY}` is a `.so` file, on Linux, that has dependencies, at least: `libgmp.so`, `libmpfr.so`, `libboost_thread-mt.so`. Your minimal example cannot produce a binary that will work.

For the moment, the CMake API of CGAL is not documented, but do not tell me that we break any principle with the two working API I showed you in 
https://github.com/CGAL/cgal/issues/692#issuecomment-196761730:
  - the first one is the API that was used by most `FindFooBar` CMake modules at the time of CMake-2.6,
  - the second is the newest API that is allowed since CMake-2.8.11.

Our long-term plan is to document the CMake API of CGAL, to something that would be similar to the documentation provided by Qt5: http://doc.qt.io/qt-5/cmake-manual.html

**Comment by kynan** [comment]
@lrineau I think you misunderstood my comment: it was merely trying to highlight that you may find other users making the same mistake I made since (as you say) the CGAL CMake API is not documented.

Thanks for your 2 example use cases. I figured out the 2nd way myself by looking the exported targets file. Most users not familiar with the inner workings of CMake however will be totally lost I suspect.

Not meaning to criticise, just trying to be helpful!
