### ISSUE TITLE
Different Infinite Vertex in Debug and Release Build

### ISSUE THREAD

**Issue by Alison-97** [CGAL/cgal#6928]
## Issue Details

The evaluation of `cdt.infinite_vertex()->point()` produces different output in Debug and Release Build. The infinite vertex is evaluated into a huge value `(-6.27744e+66, -6.27744e+66)` in Debug mode but in Release mode, the value is `(0, 0)`. Also, if I switch the Runtime library of Release mode from **Multi-threaded DLL (/MD)** to **Multi-threaded Debug DLL (/MDd)**, I’m getting the huge value as in the Debug Build. Nevertheless, I think the Debug version is more appropriate as infinite vertex is meant to be a huge infinite value, rather than a `(0, 0)`.

## Source Code

```
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/Constrained_Delaunay_triangulation_2.h>
#include <CGAL/Delaunay_mesher_2.h>
#include <CGAL/Delaunay_mesh_face_base_2.h>
#include <CGAL/Delaunay_mesh_size_criteria_2.h>
#include <iostream>

typedef CGAL::Exact_predicates_inexact_constructions_kernel K;
typedef CGAL::Triangulation_vertex_base_2<K> Vb;
typedef CGAL::Delaunay_mesh_face_base_2<K> Fb;
typedef CGAL::Triangulation_data_structure_2<Vb, Fb> Tds;
typedef CGAL::Constrained_Delaunay_triangulation_2<K, Tds> CDT;
typedef CGAL::Delaunay_mesh_size_criteria_2<CDT> Criteria;

typedef CDT::Vertex_handle Vertex_handle;
typedef CDT::Point Point;

int main()
{
  CDT cdt;

  Point result = cdt.infinite_vertex()->point();
  std::cout << result.x() << std::endl;	
  std::cout << result.y() << std::endl;
}
```
The output is as follow:

- Output in Debug mode (MDd):
  // -6.27744e+66
  // -6.27744e+66

- Output in Release mode (MD):
  // 0
  // 0

- Output in Release mode (MDd):
  // -6.27744e+66
  // -6.27744e+66

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows 11 version 21H2, 64 bits
* Compiler: Visual Studio 2022
* Release or debug mode: Both
* CGAL version: 5.5
* Boost version: 1_80_0

**Comment by mglisse** [comment]
This isn't specifically a large value or 0, this is just uninitialized memory, and you are getting arbitrary values based on multiple reasons. You should not rely on this meaningless value. Using clang's `-fsanitize=memory`, it tells me
```
Uninitialized bytes in MemcmpInterceptorCommon at offset 112 inside [0x7fff3f7cca90, 256)
==16162==WARNING: MemorySanitizer: use-of-uninitialized-value
[...]
    #6 0x7f4347f318ff in std::ostream& std::ostream::_M_insert<double>(double) /build/gcc-12-tHYXim/gcc-12-12.2.0/build/x86_64-linux-gnu/libstdc++-v3/include/bits/ostream.tcc:73:40
    #7 0x55c37ee0235c in main /tmp/a.cc:23:13
```
Valgrind can also print
```
==16185== Conditional jump or move depends on uninitialised value(s)
[...]
==16185==    by 0x4A4B84D: std::ostream& std::ostream::_M_insert<double>(double) (ostream.tcc:73)
==16185==    by 0x10C860: main (a.cc:23)
```
I am not familiar enough with windows to suggest corresponding tools there.

There was a discussion at some point about initializing this value to NaN for number types that support such a value. It would prevent the sanitizer and valgrind from detecting the user error, but the value would be recognizable. Whether that helps a user debug their program depends on the way they debug and the tools they use...
