### ISSUE TITLE
Problem with the provided cgal example: Alpha_wrap_3/point_set_wrap.cpp

### ISSUE THREAD

**Issue by doeby1978** [CGAL/cgal#6936]
## Issue Details
I could not compile in msys2-environment: 
_boost/container/flat_map.hpp:72:38: error: inlining failed in call to 'always_inline' 'D boost::container::dtl::force_copy(const S&) [with D = std::less<long long unsigned int>; S = std::less<long long unsigned int>]':_
With: _"CXXFLAGS+=-DBOOST_CONTAINER_DISABLE_FORCEINLINE"_ it works but I am not sure if this has any side effects. 

Running then point_set_wrap example (with: _-DBOOST_CONTAINER_DISABLE_FORCEINLINE_) crashes:
**CGAL warning: check violation!
Expression : false
File       : C:/msys64/mingw64/include/CGAL/Alpha_wrap_3/internal/Alpha_wrap_3.h
Line       : 796
Explanation: Could NOT extract mesh...
Refer to the bug-reporting instructions at https://www.cgal.org/bug_report.html**

## Environment

* Win 11, msys2 (mingw64) 
* Compiler: g++.exe (Rev1, Built by MSYS2 project) 12.2.0
* CGAL version: 5.5-2
* Boost version: 1.80.0-1

Thanks!

**Comment by MaelRL** [comment]
Can you try replacing the flat_map in [orient_polygon_soup.h](https://github.com/CGAL/cgal/blob/master/Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/orient_polygon_soup.h#L74) (I assume this is where you are getting a compiler error) with a simple map?

What is the input data and arguments to Alpha_wrap_3?

**Comment by doeby1978** [comment]
Hi @MaelRL,
in **orient_polygon_soup.h**,  switching line 74 with content:
_typedef boost::container::flat_map< V_ID, boost::container::flat_set<P_ID> >  Internal_map_type;_  
to: 
 _typedef std::map< V_ID, boost::container::flat_set<P_ID> >  Internal_map_type;_
solved the issue!

Thank you very much for the hint and also for the huge effort you guys punt into cgal!

    Döby
