### ISSUE TITLE
edges_example   error?

### ISSUE THREAD

**Issue by cq0907** [CGAL/cgal#6944]
_Please use the following template to help us solving your issue._

## Issue Details
When I execute the code edges_example.cpp there is an error? Is that why? thanks

## Environment
* Operating system: Windows
* Compiler: cmake3.24
* Release or debug mode: 
* Specific flags used (if any): 
* CGAL version: 5.5
* Boost version: 1.71.0
* Eigen: 3.4
![Snipaste_2022-10-07_17-59-50](https://user-images.githubusercontent.com/39946114/194528442-008808dc-dfb5-40b4-831d-11c8a0c424df.png)

**Comment by sloriot** [comment]
What does the error message say (in English)? Maybe that's a link issue or a pb with finding libraries at runtime.

**Comment by cq0907** [comment]
> What does the error message say (in English)? Maybe that's a link issue or a pb with finding libraries at runtime.

The code is executed here and the error is reported.
![image](https://user-images.githubusercontent.com/39946114/194551025-26aebf28-b171-4452-a84e-3f03d07575e4.png)

**Comment by cq0907** [comment]
> What does the error message say (in English)? Maybe that's a link issue or a pb with finding libraries at runtime.

The error is as follows：
Exception thrown at 0x000000006AD20FA0 (libgmp-10.dll) (in edges_example.exe): 0xC0000005: Access violation executing at location 0x000000006AD20FA0.

**Comment by sloriot** [comment]
Just to be sure, `libgmp-10.dll` is the dll that correspond to the GMP version used to compile the example? (you can use [that tool](www.dependencywalker.com) to check it).

**Comment by cq0907** [comment]
> libgmp-10.dll

I downloaded the 5.5 version of CGAL and its corresponding win64-auxiliary-libraries-gmp-mpfr, and then copied the gmp directly, is this ok?
![image](https://user-images.githubusercontent.com/39946114/194554965-9ee39b09-3ed3-45ce-b7ac-2288df4f3dc9.png)

**Comment by sloriot** [comment]
My question is whether that is this dll that is used at runtime by the example (requires to update you PATH env variable so that the libgmp-10.dll is found). It might that you have another software providing this dll and that's this one that is used (we already have this issue and with Blender if I remember correctly). Using the tool I mentioned above on the edge_example exe will tell you what dll is used.

**Comment by cq0907** [comment]
> My question is whether that is this dll that is used at runtime by the example (requires to update you PATH env variable so that the libgmp-10.dll is found). It might that you have another software providing this dll and that's this one that is used (we already have this issue and with Blender if I remember correctly). Using the tool I mentioned above on the edge_example exe will tell you what dll is used.

According to your method, I checked edge_example.exe. According to the check result, as shown in the figure, is it because the file is not found and an error is reported?

![image](https://user-images.githubusercontent.com/39946114/194558465-32c52247-8c62-4e07-b53d-a070fa208819.png)

**Comment by sloriot** [comment]
Did you pick x64 as target for compiling the example?

**Comment by sloriot** [comment]
Could you try leaving GMPXX_INCLUDE_DIR empty?

**Comment by cq0907** [comment]
> Could you try leaving GMPXX_INCLUDE_DIR empty?

According to your suggestion, I tried your method, but the same error still occurs.

**Comment by sloriot** [comment]
if `D:/dev/CGAL-5.5/auxiliary/gmp/lib` is in your PATH environment variable then I don't really have anything else to suggest (I'm not a windows user).

**Comment by cq0907** [comment]
> if `D:/dev/CGAL-5.5/auxiliary/gmp/lib` is in your PATH environment variable then I don't really have anything else to suggest (I'm not a windows user).

Thank you very much for your enthusiastic answer.
