### ISSUE TITLE
Memory leak in Orthtree

### ISSUE THREAD

**Issue by DanielZint** [CGAL/cgal#6951]
## Issue Details

The Node in the Orthtree package has a member variable called m_data that is initialized in the constructor with _new_. However, there is no destructor that frees the memory. There is a member function called _free_ that does the job but when the member function _unsplit_ is called, there is no call to _free()_.

I recommend replacing the c-style pointer with a shared pointer.

## Environment

* CGAL version: 5.5

**Comment by lrineau** [comment]
Maybe a `unique_ptr` instead of a shared pointer. Is there any indication that the data is shared?

**Comment by DanielZint** [comment]
The Node is written with the intention that it can be copied. A unique_ptr would destroy that behavior.

**Comment by lrineau** [comment]
Fixed by merge of https://github.com/CGAL/cgal/pull/7028.
