### ISSUE TITLE
can not traverse over all facet equation of a polyhendron

### ISSUE THREAD

**Issue by wxh158849067wxh** [CGAL/cgal#6974]
_Please use the following template to help us solving your issue._

## Issue Details

As you can see below, P is a polyhenron by creating with a OFF file,
this a context of the file:
OFF 
8 6 0 
-5.00000 -5.00000 5.00000 
5.00000 -5.00000 5.00000 
-5.00000 5.00000 5.00000 
5.00000 5.00000 5.00000 
-5.00000 5.00000 -5.00000 
5.00000 5.00000 -5.00000 
-5.00000 -5.00000 -5.00000 
5.00000 -5.00000 -5.00000 
4 0 1 3 2 
4 2 3 5 4 
4 4 5 7 6 
4 6 7 1 0 
4 1 7 5 3 
4 6 0 2 4
when i use below code to get plane equation, there is following result:
0.5 0.5 0.5 0.5
0.5 0.5 0.5 0.5
0.5 0.5 0.5 0.5
0.5 0.5 0.5 0.5
0.5 0.5 0.5 0.5
0.5 0.5 0.5 0.5
six same coefficients, how possibly  get this result, sorry for taking up your time, hope you can help me out this, thank you every much! 
## Source Code
```c++
for (Facet_iterator it = P.facets_begin(); it != P.facets_end(); ++it)
	{
		
		
		Plane pl = (*it).plane();
		cout << pl.a() << " " << pl.b() << " " << pl.c() << " " << pl.d() << endl;

	}
```
## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):
* Compiler:
* Release or debug mode:
* Specific flags used (if any):
* CGAL version:
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by sloriot** [comment]
You need to compute plane equations before using them. See how to do this in [this example](https://doc.cgal.org/latest/Polyhedron/Polyhedron_2polyhedron_prog_planes_8cpp-example.html).

**Comment by afabri** [comment]
@wxh158849067wxh can you confirm that this solves your problem and close the issue.

**Comment by wxh158849067wxh** [comment]
thank you

**Comment by wxh158849067wxh** [comment]
i
