### ISSUE TITLE
PMP::triangulate_refine_and_fair_hole() creates pairs of intersecting triangles.

### ISSUE THREAD

**Issue by AlekseyMuraviev** [CGAL/cgal#6982]
## Issue Details

PMP::triangulate_refine_and_fair_hole() creates pairs of intersecting triangles. As a consequence, boolean operations on meshes do not work.

The following parameters were used:
```
use_delaunay_triangulation = true
use_2d_constrained_delaunay_triangulation = true
threshold_distance = 0.25
fairing_continuity = 0
density_control_factor = root_two
```

The [original](https://github.com/CGAL/cgal/files/9854619/original.zip) and [resulting](https://github.com/CGAL/cgal/files/9854625/after_hole_filling.zip) meshes are attached.

After hole filling (invalid pairs of triangles highlighted):
![1666347767](https://user-images.githubusercontent.com/14346009/197607854-72c93584-8eb8-4f14-b532-aacafc7399a6.png)

Before hole filling + invalid pairs of triangles:
![1666348013](https://user-images.githubusercontent.com/14346009/197608186-695cfa62-6a10-48f4-93a0-fe33a9ff993a.png)

Two pairs of intersecting triangles:
![1666362113](https://user-images.githubusercontent.com/14346009/197608236-32eebdfa-3917-4789-8cef-9a11a07c77e7.png)
[33468-9376.zip](https://github.com/CGAL/cgal/files/9854662/33468-9376.zip)

![1666362172](https://user-images.githubusercontent.com/14346009/197608282-042b7f36-1079-4941-a9ea-92f8b9b5fbf5.png)
[33468-9381.zip](https://github.com/CGAL/cgal/files/9854666/33468-9381.zip)

These triangle pairs are found by the [PMP::self_intersections()](https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__intersection__grp.html#ga5c8f1c1aba66b32be12d88f852f87fb0) function.

In addition to these triangles, the hole filling function adds another [triangle](https://github.com/CGAL/cgal/files/9854703/non_manifold.zip) (the triangle is shown after the removal of intersecting pairs of triangles):
![1666600580](https://user-images.githubusercontent.com/14346009/197608658-3a0bb66c-17c0-46ae-8ec2-604ecfbb3ccb.png)

## Source Code

A slightly modified [Polygon_mesh_processing/hole_filling_example_SM.cpp](https://doc.cgal.org/latest/Polygon_mesh_processing/Polygon_mesh_processing_2hole_filling_example_SM_8cpp-example.html) for working with arbitrary meshes.

## Environment

* Operating system: Windows, 64 bits
* Compiler: Microsoft (R) C/C++ Optimizing Compiler Version 19.33.31629 for x64
* Release or debug mode: Release
* Specific flags used (if any):
* CGAL version: 5.5
* Boost version: 1.71.0

**Comment by sloriot** [comment]
I had a quick look because I thought that maybe https://github.com/CGAL/cgal/pull/6977 was fixing the issue but it turns out that even without fairing there is a self-intersection. There is a folding happening that is very suspicious. I wonder if it could not be due to an invalid refinement point computed on a cap triangle. @MaelRL what do you think?

@AlekseyMuraviev in the meantime, you can use `PMP::experimental::remove_self_intersections()` from `CGAL/Polygon_mesh_processing/repair_self_intersections.h`.

**Comment by AlekseyMuraviev** [comment]
Thanks for the advice!
