### ISSUE TITLE
Surface_mesh_approximation: is not manifold

### ISSUE THREAD

**Issue by Sssss7** [CGAL/cgal#6983]
## Issue Details

I want to use [CGAL::Surface_mesh_approximation::approximate_triangle_mesh] to simplify the surface mesh of mechanical parts. The output mesh must be 2-manifold and oriented if you want to output a simplified .off file at the end. But when I run it, I can't guarantee these points. So new simplified .off file can not be generated. How can I solve it?
<img width="706" alt="截屏2022-10-24 23 25 58" src="https://user-images.githubusercontent.com/104279321/197633191-3f2a2f87-c909-4b16-9d5a-7ceeaa8c5f11.png">

## Source Code
My source Code is the same as the example:
Surface_mesh_approximation/vsa_approximation_2_example.cpp
This is my input file:
[Core_NewWS7.off.zip](https://github.com/CGAL/cgal/files/9855416/Core_NewWS7.off.zip)

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):
* Compiler:
* Release or debug mode:
* Specific flags used (if any):
* CGAL version: 5.5
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by afabri** [comment]
My guess is that these > 90 degree sharp edges make trouble.
![image](https://user-images.githubusercontent.com/3263539/197706093-66756cc9-a3c1-48ac-b153-3d349d256c01.png)
