### ISSUE TITLE
Assertion failure with read_MEDIT

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#6997]
Original comment from stackoverflow:

*I have tested with the new function and the issue remains. The output is giving the error "Error in add_facet_to_incident_cells_map" before giving a segmentation fault. The .mesh file I am trying to load was generated by CGAL itself. I have made the mesh file available this [link](https://wetransfer.com/downloads/f095b06e268879212cc60c78bfdf5ea820221029064830/48c963)*

**Comment by MaelRL** [comment]
Data re-uploaded to https://gist.githubusercontent.com/Another-Anonymous-User/7b628cf1f010dfcd143449bc4ef09ae3/raw/69e2d9f15d5bf6bae30f91815b1a29090a84bb71/test_medit.mesh
