### ISSUE TITLE
Document when CGAL_ImageIO must be linked

### ISSUE THREAD

**Issue by cesare-corrado** [CGAL/cgal#70]
I'm trying to compile my own code and linking it with CGAL 4.6
During the linking, i had the following error:
```
CMakeFiles/test.dir/main.cpp.o:main.cpp:function main: error: undefined reference to '_readImage(char const*)'
CMakeFiles/test.dir/main.cpp.o:main.cpp:function main: error: undefined reference to 'CGAL::Image_3::private_read(point_image*)'
```
I followed step-by-step the instructions reported in: http://doc.cgal.org/latest/Manual/installation.html (compiling a own non-shipped program).
Googling the error, I found this report:

http://cgal-discuss.949826.n4.nabble.com/CGAL-3-6-first-post-installation-steps-td2065667.html

The error referred to version 3.6 (i.e. one major version older than the one I use) and the solution proposed (the only one) was to manually edit `CMakeLists.txt`, and `CGALConfig.cmake`.
Is there another simpler solution to solve this problem (i.e. avoiding a manual edit)? Will be fixed the problem in the future?

Thanks

**Comment by sloriot** [comment]
Did you link with CGAL_imageIO?

**Comment by cesare-corrado** [comment]
I don't think I linked with CGAL_imageIO. The output I had during yhe link (enabling verbosity) was:

Linking CXX executable test
/usr/bin/cmake -E cmake_link_script CMakeFiles/test.dir/link.txt --verbose=1
/usr/bin/c++    -frounding-math -O3 -DNDEBUG    CMakeFiles/test.dir/main.cpp.o  -o test -rdynamic -L/home/common/CGAL-4.6/lib -lmpfr -lgmp /home/common/CGAL-4.6/lib/libCGAL.so -lboost_thread-mt -lpthread -lboost_system-mt /home/common/CGAL-4.6/lib/libCGAL.so -lboost_thread-mt -lpthread -lboost_system-mt -Wl,-rpath,/home/common/CGAL-4.6/lib 
CMakeFiles/test.dir/main.cpp.o:main.cpp:function main: error: undefined reference to '_readImage(char const*)'
CMakeFiles/test.dir/main.cpp.o:main.cpp:function main: error: undefined reference to 'CGAL::Image_3::private_read(point_image*)'
collect2: ld returned 1 exit status
make[2]: *** [test] Error 1
make[2]: Leaving directory `/home/cc14/cgalTests'
make[1]: *** [CMakeFiles/test.dir/all] Error 2
make[1]: Leaving directory `/home/cc14/cgalTests'
make: *** [all] Error 2

**Comment by cesare-corrado** [comment]
A short update: File CGALConfig.cmake is ok in version 4.6
For imageIO one has to modify by hand file CMakeLists.txt as follows:
from:
find_package( CGAL QUIET COMPONENTS )
to:
find_package( CGAL QUIET COMPONENTS ImageIO)

This is a solution, even though not the best one

**Comment by lrineau** [comment]
Which `CMakeLists.txt` needs to be modified? One in CGAL or the one of your application?

**Comment by cesare-corrado** [comment]
The one in my application (which was generated by cgal_create_CMakeLists script I think)

**Comment by lrineau** [comment]
Then the bug is in the documentation of Mesh_3. It should be clear when `CGAL_ImageIO` has to be linked. I have renamed the bug.

Meanwhile, you know that, if you use our CMake scripts to configure your application, ImageIO must be specified as a component.

**Comment by sloriot** [comment]
See #506 (It is already documented for `Surface_mesher`

**Comment by Shitao389** [comment]
Hi,I have the same problem when  I am trying to run the 3D mesh generation example based on segmented images with CGAL 4.13. The errors are reported as follow:

-  ccPHBFbg.o: In function `CGAL::Image_3::read(char const*)':

-mesh_3D_image.cpp(.text._ZN4CGAL7Image_34readEPKc[_ZN4CGAL7Image_34readEPKc]+0x18): undefined reference to `_readImage(char const*)'

-mesh_3D_image.cpp(.text._ZN4CGAL7Image_34readEPKc[_ZN4CGAL7Image_34readEPKc]+0x2a): undefined reference to `CGAL::Image_3::private_read(point_image)

Can you please help me solve this problem.
Thank you very much.

**Comment by lrineau** [comment]
You must link with libCGAL_ImageIO.so.
