### ISSUE TITLE
What are the Qt 6 migration plans?

### ISSUE THREAD

**Issue by fxcoudert** [CGAL/cgal#7004]
## Issue Details

CGAL currently requires Qt 5, currently in LTS. After 26 May 2023, there will not be any further support or updates for open source, and only customers with commercial licenses will be able to access Qt 5 LTS (until May 2025). https://www.qt.io/blog/qt-5.15-extended-support-for-subscription-license-holders

What are the current plans for CGAL?

**Comment by lrineau** [comment]
Hi FX,

the current plan is: ... that is on the TODO-list, but the priority is quite low.

Your issue just reminds us that we should really think about it. I have a plan to assign that task to an apprentice, later in the year.

Is there any impact on the Homebrew project? Each time I encounter you on Github, that is about Homebrew, so I imagine that is yet again the case. Is there a plan for a migration to Qt6 on Homebrew?

cc @SaillantNicolas

**Comment by fxcoudert** [comment]
We ship both Qt 5 and Qt 6 in Homebrew, and will continue as long as Qt 5 is supported. After that, we would ship CGAL without Qt (if that is possible), or remove CGAL altogether if it becomes the only option.

This comment was triggered by the fact that Qt 5 is currently not building on macOS Ventura, and because CGAL depends on it, I wondered if we could migrate CGAL to Qt 6. But there is no immediate need for action. Just thought, because it wasn't discussed in any issue that I could find, you would appreciate the heads-up.

**Comment by sloriot** [comment]
Note that Qt5 is optional and only a really small part of the library related to visualization depends on it. Since CGAL is header only and the detection of Qt5 happens at configuration time (cmake), I think Qt5 could be marked as an optional dependency (if that notion exists in brew).
