### ISSUE TITLE
Polyhedron3 Demo cannot detect most of the plugins

### ISSUE THREAD

**Issue by abdoulayediak** [CGAL/cgal#7008]
## Issue Details
I compiled the Polyhedron3 Demo and it goes without any error. However, when I open the UI, most of the plugins are not detected. See in image below when I open the _Preferences_ tab.

<img src="https://user-images.githubusercontent.com/7335122/199881827-fab6818f-7a6f-47e6-b787-c6a96109ca6b.png" width="500">

All the plugins in Red are not detected. When I pick any of them and check the details, it says, something like: 
**_Status: Cannot load library_** C:\path_to_plugin\plugin_name.dll: **_The specified module could not be found._** 

![image](https://user-images.githubusercontent.com/7335122/199882019-500e000a-ee6e-4fb7-8c31-478c6e7ca846.png)

However, when I follow the path, the corresponding dlls are all there. 

![image](https://user-images.githubusercontent.com/7335122/199885790-d2c5fa2b-1ef5-4731-ad00-70d8b7653d34.png)

Note in the image above the polylines_io_plugin.dll which is well detected in the UI. I tried the **File->Load Plugin** option, without success. 
 
Any idea of what could be the reason?

## Environment

* Operating system: **Windows 10 64bits**
* Compiler: **MSVC 2022**
* Release or debug mode: **Release**
* Specific flags used (if any):
* CGAL version: **5.5**
* Boost version: **1.80.0**
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by sloriot** [comment]
are gmp and mpfr dll in the PATH environment variable? Alternatively try to put them at the root of the demo.

**Comment by abdoulayediak** [comment]
Adding those dlls to the PATH environment worked like a charm! 
Thanks a lot for the quick help.
