### ISSUE TITLE
Difficulty importing headers that use Eigen3

### ISSUE THREAD

**Issue by thchang** [CGAL/cgal#7016]
## Issue Details

All occurrences of ``<include Eigen/...>`` need to change to --> ``<include eigen3/Eigen/...>`` (at least for my set up).  All of my packages are as updated as they can be using ``apt``.  Although I originally encountered this issue using a clone of your github main branch, I think I get the same issue when using the version that installs from ``apt``

## Source Code

``<include Eigen/Core>`` --> ``<include eigen3/Eigen/Core>``

## Environment

* Ubuntu 20.04 LTS
* Compiler:  g++ 9.4.0
* CGAL version:  GH-main latest (as of Nov. 6, 2022)
* Boost version:  1.71.0.0ubuntu2
* Other libraries:  Eigen 3.3.7-2

**Comment by mglisse** [comment]
You are supposed to compile with `-I /usr/include/eigen3` (CMake should add it for you if you use that), or complain to debian/ubuntu that they should install things directly in /usr/include and not /usr/include/eigen3 (which made sense at the time there were both eigen2 and eigen3, but not so much now). Including `Eigen/Core` is what the Eigen developers document as the right way.
