### ISSUE TITLE
bug PMP::experimental::remove_self_intersections (and CGAL::is_valid_polygon_mesh)

### ISSUE THREAD

**Issue by stla** [CGAL/cgal#7019]
[CopyOfHEART_OBS5.ply.txt](https://github.com/CGAL/cgal/files/9951094/CopyOfHEART_OBS5.ply.txt)

## Issue Details

The mesh in the attached PLY file self-intersects. When I apply `PMP::experimental::remove_self_intersections`, it does not self-intersect anymore. Moreover it is valid according to `CGAL::is_valid_polygon_mesh`. However it is not valid: there are some faces involving vertex 2510, while this vertex does not exist, there are 2510 vertices (so the last index is 2509).

## Source Code

I'm preparing the source code, I will edit.

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Linux Mint
* CGAL version: 5.4.1

**Comment by afabri** [comment]
Did you garbage collect?

**Comment by stla** [comment]
> Did you garbage collect ([Surface_mesh::collect_garbage()](https://doc.cgal.org/latest/Surface_mesh/classCGAL_1_1Surface__mesh.html#aea69dbef8122b1acf050c19063f935f2)) ?

Aaahhh no! Let me try.

**Comment by stla** [comment]
Yes, it works! Thanks.
