### ISSUE TITLE
Calculate the distance between two triangulated surfaces by CGAL

### ISSUE THREAD

**Issue by flaminyu** [CGAL/cgal#7026]
We need a tool to compute the distance between two triangulated surface. And we are only allowed to use the CGAL to solve the problem.

I only found the API computing the distance from a point to a surface in `AABB tree` package, and some relevant APIs in `Surface_mesh_shortest_path` package. But I still can't fix my problem. Is there any tool in CGAL could fix my problem? Thanks!

**Comment by sloriot** [comment]
Duplicate of  #7024
