### ISSUE TITLE
Weighted_Minkowski_distance constructor behavior different from documentation

### ISSUE THREAD

**Issue by xjiangan** [CGAL/cgal#7029]
## Issue Details

The [document](https://doc.cgal.org/latest/Spatial_searching/classCGAL_1_1Weighted__Minkowski__distance.html#a0fa557548ccefcdeb03fdb416389b33e) shows $power \leq 0$  denotes the $l_\infty$(weights) metric. 
But actually only $power = 0$ will get $l_\infty$(weights) metric. 

## Source Code

```cpp
#include <iostream>

#include <CGAL/Simple_cartesian.h>
#include <CGAL/Search_traits_2.h>
#include <CGAL/Weighted_Minkowski_distance.h>

typedef CGAL::Simple_cartesian<double> K;
typedef K::Point_2 P;
typedef CGAL::Search_traits_2<K> TreeTraits;
typedef CGAL::Weighted_Minkowski_distance<TreeTraits> Dist;


int main(){
    std::array<int,2> hw{2,3};
    Dist dist_0(0, 2, hw.begin(), hw.end());
    std::cout<<dist_0.transformed_distance(P(0,0),P(2,3))<<'\n';
    Dist dist_n(-1, 2, hw.begin(), hw.end());
    std::cout<<dist_n.transformed_distance(P(0,0),P(2,3))<<'\n';

}
```
Will out put
```
9
2
```

## Environment

* Operating system : Windows and Linux, 64 bits
* Compiler:  Microsoft (R) C/C++ compiler 19.33.31630 and GNU C++ compiler V8.4.1, using C++14
* Release or debug mode: Release
* Specific flags used (if any):
* CGAL version: 5.5.1 and 5.2.3
* Boost version: 1.80 and 1.77
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by afabri** [comment]
Thank you for pointing this out.   Would be interesting to hear for what you use this class.

**Comment by xjiangan** [comment]
Thank you for fixing the doc.   
I am a student taking an [Algorithms Lab](https://cadmo.ethz.ch/education/lectures/HS22/algolab/index.html) Course which teaches CGAL, and I use this class to solve one of the problems.
