### ISSUE TITLE
Arrangement polyline bug

### ISSUE THREAD

**Issue by ShenCiao** [CGAL/cgal#7033]
## Issue Details

I was playing with the example code of 2D arrangement, all examples work perfectly correct. But I think I've found a case with polyline wrongly calculated. Here is the code:

```
#include <vector>
#include <list>
#include "arr_polylines.h"
#include "arr_print.h"
int main() {
	Traits traits;
	Arrangement arr(&traits);
	auto polyline_construct = traits.construct_curve_2_object();

	// A square, diagonal lay on xy axis. 
	Point points1[5];
	points1[0] = Point(0, 1);
	points1[1] = Point(1, 0);
	points1[2] = Point(0, -1);
	points1[3] = Point(-1, 0);
	points1[4] = Point(0, 1);
	auto pi1 = polyline_construct(&points1[0], &points1[5]);
	
	insert(arr, pi1);
	
	print_arrangement(arr);          // print the arrangement size
	return 0;
}
```
As the code above shows, it arranges on a square with diagonals laid on axes. It suppose to get four vertices and four edges. But the results are wrongly calculated:
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/24319509/200855129-6cc31c29-80e7-41fe-8f4d-b446888bb657.png">

The other test cases I tried all work correctly except for this one. Am I touching on a wired dark corn case?

## Environment

* Operating system (Windows 11, 64 bits):
* Compiler: MSVC
* CGAL version: vcpkg installed last week

**Comment by efifogel** [comment]
There is nothing wrong here.
You get an arrangement that has 3 vertices and 3 edges.
Each edge maps to a polyline.
One of the polylines has 3 extreme points.
Only the 2 endpoints map to arrangement vertices.
Please close.
   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by ShenCiao** [comment]
The computational geometry I've learned from school was not broken. Please reopen this issue and review my statement more carefully.

**Comment by ShenCiao** [comment]
There is the plot in the code above. There is no chance that we got three vertices or edges.
<img width="596" alt="image" src="https://user-images.githubusercontent.com/24319509/201265263-76cb9d60-08aa-4105-ac05-9928712c1d44.png">

**Comment by efifogel** [comment]
Please read my message carefully. I restate:
There are 3 edges.
Each edge maps to a polyline.
The bottom polyline consists of 2 segments.

   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by ShenCiao** [comment]
> Please read my message carefully. I restate: There are 3 edges. Each edge maps to a polyline. The bottom polyline consists of 2 segments.

Yeah this is what the arrangement output gives me but I don't think it supposes to be the result of the shape drawn above from my personal understanding of the arrangement algorithm and polyline.

Am I coding it wrongly?

**Comment by efifogel** [comment]
You are doing the right thing, and the results are correct.
Notice that you construct an arrangement induced by polylines.
Do not confuse between interior extreme points of a polyline and
arrangement vertices.
   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by ShenCiao** [comment]
Thanks for your guidence! I get the point. It must be I've missed something inside the arrangement manual.

**Comment by lrineau** [comment]
@ShenCiao The input polyline is defined by:
```c++
	Point points1[5];
	points1[0] = Point(0, 1);
	points1[1] = Point(1, 0);
	points1[2] = Point(0, -1);
	points1[3] = Point(-1, 0);
	points1[4] = Point(0, 1);
```
Note that its first and end point is (0, 1). As it is not x-monotone, the algorithm *splits* it into x-monotone sub-curves, and that gives:
  - a first polyline composed of one segment [ (0, 1), (1, 0) ],
  - a second polyline composed of **two** segments (three input vertices): [ (1, 0), (0, -1), (-1. 0) ], and
  - a third polyline composed of one segment: [ (-1, 0), (0, 1) ].

So, once decomposed into x-monotone sub-curves, there are three curves, and only **three** vertices:
  - (0, 1),
  - (1, 0), and
  - (-1, 0).

The input vertex (0, -1) is not a vertex of the decomposition into x-monotone sub-curves, because it is only an internal vertex of a x-monotone polyline/sub-curve.


Note that if the start and endpoint of the input polyline had been (-1, 0), or (1, 0), the decomposition would have been with two sub-curves, and two vertices.
