### ISSUE TITLE
Documentation: strange namespace documentation in Manual directory

### ISSUE THREAD

**Issue by albert-github** [CGAL/cgal#7037]
In the documentation I found the file doc_output/Manual/namespaceCGAL.html which is not directly referenced.
The content is:

![image](https://user-images.githubusercontent.com/5223533/201517396-08906e51-a393-4c26-9cc7-2009b1ee74cf.png)

- The text is coming from: Documentation/doc/Documentation/CGAL/config.h
   The question is here should this function be here or be part of one of the packages?
- the first example link comes from: Documentation/doc/Documentation/Tutorials/Tutorial_GIS.txt 
  ```
  namespace CGAL {
  /*!
  \example Classification/gis_tutorial_example.cpp
  */
  
  /*!
  
  \page tuto_gis GIS (Geographic Information System)
  \cgalAutoToc
  ```
  I don't think it is intended for the global CGAL namespace and certainly not for the data_file_path function
- The second  example link comes from: Documentation/doc/Documentation/Tutorials/Tutorial_reconstruction.txt
   Same construct as for the first example link

**Comment by sloriot** [comment]
I don't understand what the issue is. To me it is correct. The aforementioned function is used in tests/examples and is not part of any specific package. What matters is that it is found by users/devs looking at examples/tests. Or maybe I don't get your point.

**Comment by albert-github** [comment]
It was not clear to me that the `data_file_path` function was  only used in `test`s and `examples`  ( though not completely correct as it is also used in `benchmark`s of `AAABB_tree`, `Surface_mesh_segmentation` and `Surface_mesh_skeletonization`, though these fall in the same category as `test`s and `examples`). 

So indeed yes I think now also that this is all OK.
