### ISSUE TITLE
Surface_mesh_segmentation: Non reachable link

### ISSUE THREAD

**Issue by albert-github** [CGAL/cgal#7039]
In the package Surface_mesh_segmentation we get the non reachable links
```
Processing      file:///.../doc_output/Surface_mesh_segmentation/index.html


List of broken links and other issues:
http://pub.ist.ac.at/~vnk/software.html
  Line: 679
  Code: 500 Can't connect to pub.ist.ac.at:80 (Connection timed out)
 To do: This is a server side problem. Check the URI.
```
which result from the file Surface_mesh_segmentation/doc/Surface_mesh_segmentation/Surface_Mesh_Segmentation.txt i.e.:
```
Runtime in milliseconds of `segmentation_from_sdf_values()` (using `%Simple_cartesian<double>` or `EPICK` gives the same results),
the graph-cut part is using the library <a href="http://pub.ist.ac.at/~vnk/software.html">MaxFlow</a> v2.21:
```

**Comment by afabri** [comment]
A link to `~vnk`  with a  timeout is also at the bottom of the page https://www.ist.ac.at/en/research/kolmogorov-group/

**Comment by MaelRL** [comment]
The software is now at https://xip.uclb.com/product/maxflow_computervision under some proprietary (apparently closed source) licenses.

Although the links mentioned above are dead, they can still be reached through `archive.org`, for example: https://web.archive.org/web/20220902231920/https://pub.ist.ac.at/~vnk/software/maxflow-v3.04.src.zip

For this reason, I would tend to leave dead links if they cannot be updated to something better.

**Comment by afabri** [comment]
I've sent a mail to Vladimir Kolmogorov

**Comment by afabri** [comment]
The reply:  "The IT is trying to restore them, so hopefully my webpage will be live again in the coming weeks."  So there is nothing to do.

**Comment by albert-github** [comment]
I think it would be better to wait till the link is restored before closing this issue, link (http://pub.ist.ac.at/~vnk/software.html) is not yet accessible.
