### ISSUE TITLE
Distance analysis between two surface meshes

### ISSUE THREAD

**Issue by Sunny-bot1** [CGAL/cgal#7048]
## Issue Details

I am wondering if there is a function to compute the shortest distance between two surface meshes. I have paid attention to the previous issues related to distance analysis, and the Hausdorff distance mentioned before is not helpful to me. Would you give me some advice, please?

**Comment by MaelRL** [comment]
The discussion (https://github.com/CGAL/cgal/discussions/7024) is still open; there is no point opening yet another issue.
