### ISSUE TITLE
Some polygons with touching vertices not colored when drawing `Polygon_set_2`

### ISSUE THREAD

**Issue by Underrout** [CGAL/cgal#7054]
## Issue Details

The draw function for `Polygon_set_2` seems to not color some polygons for me if they are touching at corner points, here is an example (corresponding source code below):

![2022-11-16_23-31](https://user-images.githubusercontent.com/8695490/202309117-58243ecc-9b00-467c-8502-bf546affa08c.png)

Would appreciate if someone could tell me if they can reproduce this or if if something's just wrong with my setup/system.

EDIT: This may also happen with touching edges, I did not test that specifically. It also appears that whenever I have multiple polygons touching at corners, only one of them gets colored, the others stay blank, if that's any help.

## Source Code

This should produce exactly the image from above, just (clumsily) adapted this from the example code for drawing `Polygon_set_2`:
```c++
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/Polygon_2.h>
#include <CGAL/Polygon_with_holes_2.h>
#include <CGAL/Polygon_set_2.h>
#include <CGAL/draw_polygon_set_2.h>

typedef CGAL::Exact_predicates_exact_constructions_kernel K;
typedef CGAL::Polygon_2<K>                                Polygon_2;
typedef CGAL::Polygon_with_holes_2<K>                     Polygon_with_holes_2;
typedef CGAL::Polygon_set_2<K>                            Polygon_set_2;
typedef CGAL::Point_2<K>                                  Point_2;

int main()
{
  Polygon_2 A;

  A.push_back(Point_2(0, 0));
  A.push_back(Point_2(5, 0));
  A.push_back(Point_2(5, 5));
  A.push_back(Point_2(0, 5));

  Polygon_2 B;

  B.push_back(Point_2(5, 5));
  B.push_back(Point_2(6, 5));
  B.push_back(Point_2(6, 6));
  B.push_back(Point_2(5, 6));

  Polygon_with_holes_2 AH(A), BH(B);

  Polygon_set_2 S;
  S.insert(AH);
  S.insert(BH);

  CGAL::draw(S);

  return 0;
}
```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Ubuntu 20.04.5 LTS, 64-bit
* Compiler: gcc version 9.4.0
* Release or debug mode: Release
* Specific flags used (if any): 
* CGAL version: 5.5.1
* Boost version: 1.71
* Other libraries versions if used (Eigen, TBB, etc.): Qt 5.12.8, libcgal-qt5-dev 5.0.2-3

**Comment by gdamiand** [comment]
This comes from the definition of Polygon_set_2. You can read in the manual "A central component in the Boolean set-operations package is the Polygon_set_2 class-template. An instance of this class represents a point set formed by the collection of several disconnected polygons with holes.".

Your polygons must be disconnected, otherwise this is not a "valid" polygon set.

See https://doc.cgal.org/latest/Boolean_set_operations_2/index.html#bso_ssecmain_component

**Comment by Underrout** [comment]
Ah, I see. I must have missed that part, my bad. Thanks for the explanation.
