### ISSUE TITLE
Aggregate boolean set operations for Polygon_set_2

### ISSUE THREAD

**Issue by thomasp85** [CGAL/cgal#7059]
I'm working with a vector of polygon_set_2 that I wish to join together. It seems the aggregate join and intersect functions only have methods for the different flavours of polygons and not for polygon sets. Is this because there are no benefit to the aggregate operations when the polygons are already converted to polygon sets or is it a missing feature?

**Comment by efifogel** [comment]
You are not missing a thing. There are no aggregate functions on objects of
type Polygon_set_2 (or General_polygon_set_2).
These data structures are represented by objects the type of which are
instances of the Arrangement_2<> class template.
Applying the Boolean operations translates to applying the overlay()
function on the underlying arrangements.
An aggregate overlay function is not supported.
   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by thomasp85** [comment]
Thanks for the clarification🙂
