### ISSUE TITLE
how to calculate inverse matrix?

### ISSUE THREAD

**Issue by MengHao666** [CGAL/cgal#7066]
_Please use the following template to help us solving your issue._

## Issue Details
I am a freshman in CGAL. I could not find any example code to compute inverse matrix after spending hours reading documentation.
Could anyone give me a help?
_Describe your issue. Please be specific (compilation error, runtime error, unexpected behavior, wrong results, etc.)._

## Source Code
#include <CGAL/Linear_algebraHd.h>
#include <CGAL/Linear_algebraCd.h>
#include <iostream>

using namespace std;
using namespace CGAL::Linear_Algebra;

typedef CGAL::Linear_algebraCd<double> LA;
typedef LA::Matrix Matrix;
typedef LA::Vector Vector;

template <typename Type>
Matrix BuildMatrix(int rowCount, int colCount, Type* values)
{
	std::vector<Vector> elements;
	for (int i = 0; i < rowCount; ++i) {
		std::vector<Type> tmp;
		for (int j = 0; j < colCount; ++j) {
			tmp.push_back(values[i * colCount + j]);
		}
		elements.push_back(Vector(tmp.begin(), tmp.end()));
	}
	Matrix M(elements.begin(), elements.end());
	return M;
}

int main()
{
	CGAL::set_mode(cout, CGAL::IO::PRETTY);

	double values0[16] = { 1, 1, 2, 3, // column vector
						  0, 1, 0, 3,
						  0, 2, 5, 1,
						  0, 0, 10, 9 };
	auto A = BuildMatrix(4, 4, values0);

	
	cout << A << endl;
	
	//HOW TO compute the inverse matrix of A !!!!!!!!!!!!!!????????????????????????????

	return 0;
}
_If your issue arises by using CGAL in your own source code, please provide a minimalist example that we can compile easily to reproduce the bug. If your issue arises from using a CGAL program (demo, example, etc.), please let us know which one. Helping you solving an issue is much easier and efficient if we can reproduce it._

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): win10 64bit
* Compiler: visual studio 
* Release or debug mode: debug
* Specific flags used (if any):
* CGAL version: latest
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by mglisse** [comment]
https://doc.cgal.org/latest/Kernel_d/classLinearAlgebraTraits__d.html#a63b5d706ce9c2a617dd56847d142b768
There are 2 functions called `inverse` there.
If possible, we try to use Eigen instead of those matrices, and we try to avoid computing the inverse of a matrix if we would just use that inverse to solve linear systems.

(it seems you didn't properly quote the code block so it appears mangled on github)

**Comment by MengHao666** [comment]
> https://doc.cgal.org/latest/Kernel_d/classLinearAlgebraTraits__d.html#a63b5d706ce9c2a617dd56847d142b768 There are 2 functions called `inverse` there. If possible, we try to use Eigen instead of those matrices, and we try to avoid computing the inverse of a matrix if we would just use that inverse to solve linear systems.
> 
> (it seems you didn't properly quote the code block so it appears mangled on github)

Thanks for reply.
I found the function you refer to before. But I search in the documentation, Google and github, but fail to find any one exmaple code to tell me how to use the function.

The original code is like following:
```
  #include <CGAL/Linear_algebraHd.h>
  #include <CGAL/Linear_algebraCd.h>
  #include <iostream>
  
  using namespace std;
  using namespace CGAL::Linear_Algebra;
  
  typedef CGAL::Linear_algebraCd<double> LA;
  typedef LA::Matrix Matrix;
  typedef LA::Vector Vector;
  
  template <typename Type>
  Matrix BuildMatrix(int rowCount, int colCount, Type* values)
  {
	  std::vector<Vector> elements;
	  for (int i = 0; i < rowCount; ++i) {
		  std::vector<Type> tmp;
		  for (int j = 0; j < colCount; ++j) {
			  tmp.push_back(values[i * colCount + j]);
		  }
		  elements.push_back(Vector(tmp.begin(), tmp.end()));
	  }
	  Matrix M(elements.begin(), elements.end());
	  return M;
  }
  
  int main()
  {
	  CGAL::set_mode(cout, CGAL::IO::PRETTY);
	  double values0[16] = { 1, 1, 2, 3, // column vector
						    0, 1, 0, 3,
						    0, 2, 5, 1,
						    0, 0, 10, 9 };
	  auto A = BuildMatrix(4, 4, values0);
	  // how to calculate the inverse matrix of A ?
	  return 0;
  }
```

**Comment by pentacular** [comment]
auto B = A.inverse() should do what you want, I think.

**Comment by MengHao666** [comment]
> `auto B = A.inverse()` should do what you want, I think.

Thanks, I would try it.
