### ISSUE TITLE
CGAL QT_widget.h 

### ISSUE THREAD

**Issue by BobThome** [CGAL/cgal#707]
I am using QT5.5.0 and CGAL 4-7. 

When in QT creator, attempting to use #include CGAL/IO/Qt_widget.h will result in ~18 errors. 
When you search into QT_widget.h, the <qprinter.h> header file is not being recognized. 
I tried #include QtPrintSupport/qprinter.h but it did not work. 

Here is the error listing ... 

![cgal](https://cloud.githubusercontent.com/assets/15759202/12733962/cba44868-c90b-11e5-96a5-4050f8e24fbe.PNG)

I read other bug reports as of the last few months, where qt support was cleaned up, header files perhaps were not fully addressed. I built CGAL from November, if patches have been made since then, should I rebuild?

Thanks

**Comment by sloriot** [comment]
This header file is meant to be used with Qt3. I has been removed from the development branch now and the next release will not provide it.

**Comment by maxGimeno** [comment]
With Qt5, just include <QWidget>, it should be sufficient.

**Comment by lrineau** [comment]
That file, and all the files of the old Qt3 support, has been removed from the [`master`](https://github.com/CGAL/cgal/master) branch of CGAL, that will be used to publish CGAL-4.8-beta1 in about a week. So the "bug" is already fixed in Git.
