### ISSUE TITLE
corefine_and_compute_union intersection_nodes check_no_duplicates failed

### ISSUE THREAD

**Issue by TLCZhaoxi** [CGAL/cgal#7071]
## Issue Details
I tried to calculate the boolen operation Union of two meshes with default parameters. 
In Debug Mode, CGAL::Assertion_exception was throwed, which indicated that some nodes are duplicated. As follow:
`terminate called after throwing an instance of 'CGAL::Assertion_exception'
  what():  CGAL ERROR: assertion violation!
Expr: enodes.size() == std::set<typename Exact_kernel::Point_3>(enodes.begin(), enodes.end()).size()
File: /opt/install/CProjX/Hemodynamics_Library/include/CGAL/Polygon_mesh_processing/internal/Corefinement/intersection_nodes.h
Line: 316`
In Release Mode, The function of 'corefine_and_compute_union' return false;

Meshes are uploaded here: 
[Meshes.zip](https://github.com/CGAL/cgal/files/10072357/Meshes.zip)

## Source Code

`	SurfaceMesh::Property_map<edge_descriptor, bool> is_constrained_map =
		unionMesh.add_property_map<edge_descriptor, bool>("e:is_constrained", false).first;
	bool isValid = PMP::corefine_and_compute_union(msh1, msh2, unionMesh,
		CGAL::parameters::default_values(), CGAL::parameters::default_values(),
		CGAL::parameters::edge_is_constrained_map(is_constrained_map));
	if (!isValid)
	{
		std::cerr << "Mesh Union Failed" << std::endl;
		return false;
	}`

## Environment

* Operating system (Linux 64 bits):
* Compiler: g++
* Release or debug mode: Both
* Specific flags used (if any):
* CGAL version:
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by TLCZhaoxi** [comment]
I tried to use VTK to calculate the BooleanOperationUnion of the two meshes and got a result. But the results has a lot of errors.
The error result is here: 
[union.zip](https://github.com/CGAL/cgal/files/10073815/union.zip)

**Comment by sloriot** [comment]
Your meshes have some self-intersections and boundary edges:
![Screenshot from 2022-11-23 09-27-24](https://user-images.githubusercontent.com/1224632/203502124-f2e761d4-3235-4ef3-ad1d-18379de33e09.png)
![Screenshot from 2022-11-23 09-32-56](https://user-images.githubusercontent.com/1224632/203502125-c34ce42c-9ab6-4937-8ca3-90b2cc47280b.png)

A simple call to [`stitch_borders()`](https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__repairing__grp.html#ga740c417af0ef24a16faebb23727d089c) on each mesh before the operations is enough to fix those issues. Most likely it is a problem in the generation algorithm.

Out of curiosity, what are those meshes? Trajectories?

**Comment by TLCZhaoxi** [comment]
These two meshes was generated based on VTK TubeFilter, which is two wires of an expanded flow diverter. The flow diverter is an device implant into the neuro-aneurysm's parent artery to stop the blood flow flushing onto the wall of aneurysm.

Anyway, I will check the mesh again, and do as what you said.
Thanks.

**Comment by TLCZhaoxi** [comment]
@sloriot I check the two meshes again, but I didnot found any border edges.
Here is my meshes in both off and stl format.
[Desktop.zip](https://github.com/CGAL/cgal/files/10073962/Desktop.zip)
Could you help to check them again? And I will check the borders and call stitch_boarders() before the boolean union. I will submit the result soon.

**Comment by TLCZhaoxi** [comment]
@sloriot Thanks a lot, I checked my meshes with code. They do have some border edges. And the stitch_borders() do solve the problem. Although the results seems not so good, but that is another problem. Thanks a lot!
![snapshot00](https://user-images.githubusercontent.com/117611517/203510346-3f3ca543-120c-4bf9-968b-1aab70aa5586.png)

**Comment by sloriot** [comment]
I guess you called some remeshing after the boolop
![Screenshot from 2022-11-23 10-25-58](https://user-images.githubusercontent.com/1224632/203511539-cd41a22f-9d23-4cd5-9e14-7c7841c72496.png)

**Comment by sloriot** [comment]
You need to also protect sharp features. You can do it locally but globally (more expensive though) should be fine too.
https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__detect__features__grp.html#gadd3d18c0a9773463cd57902f85d0b23d

**Comment by TLCZhaoxi** [comment]
@sloriot I am trying to optimize the triangles after boolean operation like this:
`typedef boost::property_map<SurfaceMesh, CGAL::edge_is_feature_t>::type EIFMap;`
`EIFMap eif = get(CGAL::edge_is_feature, unionMesh);`
`PMP::detect_sharp_edges(unionMesh, 10.0, eif);`
`PMP::isotropic_remeshing(unionMesh.faces(), constrainedRemeshSize, unionMesh,`
`CGAL::parameters::edge_is_constrained_map(eif).protect_constraints(true));`
This code really do something, but maybe too much edges are protected. That lead the optimization is not enough.
![image](https://user-images.githubusercontent.com/117611517/203544447-4ba1b100-75c8-4c3d-ac44-d6d4ffb2ad89.png)
There are a lot of sharp angles still.

**Comment by afabri** [comment]
Can you try to add the named property `relax_constraints`.

**Comment by TLCZhaoxi** [comment]
I did just like what you said, It is better. But maybe still not perfect.
![image](https://user-images.githubusercontent.com/117611517/203562162-18bf042e-f156-41f8-9e89-81dfb9421efe.png)

**Comment by sloriot** [comment]
Try adding more iterations?

**Comment by TLCZhaoxi** [comment]
I make the remesh after boolen union locally with a smaller size. The sharp edges was set to be constrained(collapse false, relax true). The iteration number was set to be 20. It seems better.
![image](https://user-images.githubusercontent.com/117611517/203697721-08850788-888c-42db-8c99-183f7c145f68.png)
Maybe it can be better?

**Comment by TLCZhaoxi** [comment]
And I do find some edges collapse, as shown below
![image](https://user-images.githubusercontent.com/117611517/203698274-64a6c0b5-ddbc-4068-b2ab-1bf87a4d994e.png)
Even the collapse was set to be false.

**Comment by TLCZhaoxi** [comment]
The collapse edge is because of I did not expand the local selected faces, after I did that, Everythind seems much better now!
![image](https://user-images.githubusercontent.com/117611517/203701753-c3a0f5c1-bdf9-4fdf-9851-f588e8647d07.png)

**Comment by TLCZhaoxi** [comment]
Everything is good, but the mesh data is quite large right now....

**Comment by TLCZhaoxi** [comment]
And the generation time is also quite long.

**Comment by sloriot** [comment]
You can try to reduce the number of iterations now that you've set up options according to your needs. Also sharp edge detection could be reduced to the selection and target edge could be adapted.
