### ISSUE TITLE
Orthtree test error

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#7080]
I can reproduce [this error](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.6-Ic-119/Orthtree/TestReport_lrineau_Debian-stable-Release.gz) [test_octree_grade.cpp, seed = 1669157241] with master.

**Comment by afabri** [comment]
I think [this assertion](https://github.com/CGAL/cgal/blob/master/Orthtree/test/Orthtree/test_octree_grade.cpp#L59) makes no sense.   We create an octree for a random point set and refine the tree.   Depending on the input it may just happen that there is nothing to do for the `grade()` function.  It is like an assert that a random sequence of numbers was not sorted before you call `std::sort()`.     @palliez @JacksonCampolattaro can you confirm.

**Comment by JacksonCampolattaro** [comment]
> I think [this assertion](https://github.com/CGAL/cgal/blob/master/Orthtree/test/Orthtree/test_octree_grade.cpp#L59) makes no sense. We create an octree for a random point set and refine the tree. Depending on the input it may just happen that there is nothing to do for the `grade()` function. It is like an assert that a random sequence of numbers was not sorted before you call `std::sort()`. @palliez @JacksonCampolattaro can you confirm.

That can probably be removed. I think my logic at the time was that if the random point set happens to produce a tree with no jumps, then that unit test wouldn't actually confirm that `grade()` was functioning correctly. In practice that likely never happens.

**Comment by afabri** [comment]
It even then confirms that `grade()` does the right thing, namely just nothing.
