### ISSUE TITLE
Create a Docker installation of our internal wiki

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#7085]
The current installation can be seen at https://cgal.geometryfactory.com/CGAL/Members/wiki/Special:Version (restricted to CGAL members).

The goal is to get a Docker installation of Mediawiki, with a recent version, and with the same set of Mediawiki extensions.

The Mediawiki web site quotes several ways to do that: https://www.mediawiki.org/wiki/Docker

My personal choice would be to follow https://www.mediawiki.org/wiki/Docker/Hub, but I do not know if that would be easy to install the Mediawiki extensions we need.

Our installation needs a MariaBD server, so that we can import a dump of our current Mediawiki installation.

**Comment by SaillantNicolas** [comment]
Here is all you need to install media-wiki with the extensions and the database. This directory contains a file "mediawikiCGAL.md" which explains all the steps to follow
[installCGALmediawiki.tar.gz](https://github.com/CGAL/cgal/files/10500561/installCGALmediawiki.tar.gz)

**Comment by SaillantNicolas** [comment]
> Here is all you need to install media-wiki with the extensions and the database. This directory contains a file "mediawikiCGAL.md" which explains all the steps to follow [installCGALmediawiki.tar.gz](https://github.com/CGAL/cgal/files/10500561/installCGALmediawiki.tar.gz)

The MediaWiki version used in this work is no longer relevant, I will work on it again.

**Comment by lrineau** [comment]
Replaced by #8353.
