### ISSUE TITLE
Repair Boost installations of Windows platforms on Christo

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#7088]
See for example

- https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.6-Ic-120/Classification_Examples/TestReport_Christo_MSVC-2022-Preview-Release.gz

- https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.6-Ic-120/Classification_Examples/TestReport_Christo_MSVC-2022-Preview-Release.gz

**Comment by lrineau** [comment]
Note that the platform `Christo_MSVC2015-Release-64bits` is broken since yesterday:

https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.6-Ic-121/Installation/TestReport_Christo_MSVC2015-Release-64bits.gz

**Comment by janetournois** [comment]
It seems that everything is fixed. If you confirm, I will push the new setup to the corresponding repository
