### ISSUE TITLE
Polygonal Surface Reconstruction (polyfit) : result faces orientation ?

### ISSUE THREAD

**Issue by esgn** [CGAL/cgal#7096]
## Issue Details

I've slightly adapted the polygonal surface reconstruction without planes [example](https://doc.cgal.org/latest/Polygonal_surface_reconstruction/Polygonal_surface_reconstruction_2polyfit_example_without_input_planes_8cpp-example.html) to pass ransac and polyfit parameters. The code used is [here](https://gist.github.com/esgn/671a691d74eccd67578664b27f2e8c26).

I've been using the following ply files containing points with normals [dsm_as_point_cloud_with_walls.zip](https://github.com/CGAL/cgal/files/10114093/dsm_as_point_cloud_with_walls.zip) as input. (This file is produced by combining digital surface model and building footprint that's why the roof goes inside the building :wink:)

The result I'm getting has incorrectly oriented faces.

![image](https://user-images.githubusercontent.com/5435148/204568142-a0610ff6-8804-4d6e-92af-758e0857d141.png)

I managed to fix the faces orientation errors by using the following snippet (I'm not an expert in CGAL so this might not be the optimal solution to do so)

```c++
    // Cleanup and fix obtained mesh (holes, orientation, ...)
    std::vector<Point> _points;
    std::vector<std::vector<std::size_t>> _polygons;
    // mesh will be the correctly oriented model
    Surface_mesh mesh;
    // model is the result of Polygonal Surface Reconstruction
    PMP::polygon_mesh_to_polygon_soup(model, _points, _polygons);
    PMP::repair_polygon_soup(_points, _polygons);
    PMP::orient_polygon_soup(_points, _polygons);
    PMP::polygon_soup_to_polygon_mesh(_points, _polygons, mesh);
    PMP::triangulate_faces(mesh);
    if (CGAL::is_closed(mesh))
    {
        std::cout << "The obtained mesh is closed" << std::endl;
        PMP::orient_to_bound_a_volume(mesh);
    }
```

The full source code with the face orientation fix is available [here](https://gist.github.com/esgn/81906b0fb197ab86e9c536c2434a1439). Here is the mesh obtained whose faces are now correctly oriented.

![image](https://user-images.githubusercontent.com/5435148/204570302-73ede399-4b3e-491a-bdf7-074bdd0a791d.png)

## My questions

* Is there something wrong in my dataset or in my understanding of polyfit + ransac ?
* If not, should a fix be introduced in polygonal surface reconstruction so that the result models are correctly oriented ?

Thanks in advance for any help

## Environment

* Ubuntu 20.04
* Compiler: g++ 9.4.0
* Release or debug mode: Release
* Specific flags used (if any): built with scip (SCIP_INCLUDE_DIR, SCIP_DIR)
* CGAL version: 5.5.1
* Boost version: 1.80.0
* Other libraries versions if used (Eigen, TBB, etc.):
  * cmake: 3.24.2
  * gmp: 6.2.1
  * mpfr: 4.1.1
  * eigen: 3.4.0
  * glpk: 5.0
  * ipopt: 3.14.10
  * hmetis: 1.5
  * criterion: 2.4.1
  * scip: 8.0.2

**Comment by yywd6** [comment]
Hello, excuse me, I have now come across a running rebuild aspect, can you try to give me some solution #7433

**Comment by esgn** [comment]
> Hello, excuse me, I have now come across a running rebuild aspect, can you try to give me some solution #7433

Your issue doesn't seem to be related to the issue I described here.

**Comment by yywd6** [comment]
> > Hello, excuse me, I have now come across a running rebuild aspect, can you try to give me some solution #7433
> 
> Your issue doesn't seem to be related to the issue I described here.

Yes very sorry to bother you, I tried a lot of methods and still didn't solve this problem
