### ISSUE TITLE
convert polyhedron to nef_polyhedron_3

### ISSUE THREAD

**Issue by JLYang123** [CGAL/cgal#7097]
## Issue Details
When i convert an unclosed mesh to Nef_polyhedron_3,  the mesh seems to have the wrong orientation and become not simple(see below),  which causes problems in my subsequent operations.  I tried to use Surface_mesh instead, but got the empty result.  I also tried to convert the result back to surface_mesh and repair the mesh orentation, but the mesh information will be lost immediately after conversion. Is this a bug or other subsequent operations are required? 
![image](https://user-images.githubusercontent.com/106522728/204733172-dc9cef29-a42e-463b-840e-c63db2358e90.png)

![image](https://user-images.githubusercontent.com/106522728/204732932-45b91a1f-2709-4856-a72e-b0391a4958db.png)

mesh is here:
[mesh.zip](https://github.com/CGAL/cgal/files/10120742/mesh.zip)

## Source Code

````
#include <CGAL/Exact_predicates_exact_constructions_kernel.h>
#include <CGAL/Nef_polyhedron_3.h>
#include <CGAL/Polyhedron_3.h>
#include <CGAL/IO/Nef_polyhedron_iostream_3.h>
#include <CGAL/draw_nef_3.h>
#include <CGAL/draw_polyhedron.h>
#include <CGAL/Surface_mesh.h>
#include <iostream>

typedef CGAL::Exact_predicates_exact_constructions_kernel Kernel;
typedef CGAL::Polyhedron_3<Kernel>                          Polyhedron;
typedef CGAL::Nef_polyhedron_3<Kernel> Nef_polyhedron;
typedef CGAL::Surface_mesh<Kernel::Point_3> Surface_mesh;

int main(int argc, char *argv[]) {
  Polyhedron P1;
  std::ifstream ifs1(argv[1]);
  ifs1 >> P1;
  Nef_polyhedron N1(P1);

  CGAL::draw(N1);
  //CGAL::draw(P1);
  return EXIT_SUCCESS;
}
````

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): linux
* Compiler: gcc 8,3.0
* Release or debug mode: Release
* Specific flags used (if any):
* CGAL version: CGAL 5.5
* Boost version: 1.67
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by sloriot** [comment]
I guess that an issue with the triangles passes to the shader. Orientation is correct in the Polyhedron demo.

**Comment by JLYang123** [comment]
> I guess that is an issue with the triangles passes to the shader. Orientation is correct in the Polyhedron demo.

Orientation is correct in the Polyhedron demo, but I'm not sure whether it is correct in the Nef_Polyhedron demo(At least it is wrong from the second figure). I tried check it by using the operator "<<" to output the nef_polyhedron, but i am not familiar with data structure. In most unclosed mesh examples, i can continue to use the nef_polyhedron, but an error occured in this example, so may be this is not just a rendering error?

**Comment by sloriot** [comment]
As I said, I think it is a shader issue, not an issue with Nef.
