### ISSUE TITLE
convert relatively simple polygon to simple polygons

### ISSUE THREAD

**Issue by Supranaturaler** [CGAL/cgal#7111]
## Issue Details

I have a rectangle shape and a triangle shape as follows:
![image](https://user-images.githubusercontent.com/40469886/206193647-18f5c123-a76c-4d74-a4af-e474039f074f.png)
![image](https://user-images.githubusercontent.com/40469886/206193748-4bfc484e-9792-4b0e-be64-07f0b812443e.png)

I use Polygon_set_2 to do difference boolean operation. The result is one relatively simple polygon. But I want to get two simple polygons. Is there any interface to implement this?
![image](https://user-images.githubusercontent.com/40469886/206195642-bb76ab58-6f64-4006-87c7-a88ee720905f.png)

## Source Code

```c++
#include "CGAL/Exact_predicates_exact_constructions_kernel.h"
typedef CGAL::Exact_predicates_exact_constructions_kernel Kernel;
typedef Kernel::Point_2 Point_2;

#include "CGAL/Polygon_2.h"
#include "CGAL/Polygon_with_holes_2.h"
typedef CGAL::Polygon_2<Kernel> Polygon_2;
typedef CGAL::Polygon_with_holes_2<Kernel> Polygon_with_holes;

#include "CGAL/Polygon_set_2.h"
typedef CGAL::Polygon_set_2<Kernel> Polygon_set_2;

#include "CGAL/draw_polygon_2.h"
#include "CGAL/draw_polygon_with_holes_2.h"

int main(int argc, char* argv[])
{
    Polygon_2 rectangle;
    rectangle.push_back(Point_2(0, 0));
    rectangle.push_back(Point_2(2, 0));
    rectangle.push_back(Point_2(2, 2));
    rectangle.push_back(Point_2(0, 2));
    CGAL::draw(rectangle);

    Polygon_2 triangle;
    triangle.push_back(Point_2(0, 0));
    triangle.push_back(Point_2(2, 0));
    triangle.push_back(Point_2(1, 2));
    CGAL::draw(triangle);

    Polygon_set_2 rectanglePolygonSet(rectangle);
    Polygon_set_2 trianglePolygonSet(triangle);
    rectanglePolygonSet.difference(triangle);

    std::vector<Polygon_with_holes> differencePolygons;
    rectanglePolygonSet.polygons_with_holes(std::back_inserter(differencePolygons));
    std::cout << "number of polygon_with_holes" << differencePolygons.size();
    CGAL::draw(differencePolygons.front());

    return EXIT_SUCCESS;
}
```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows 11 home basic 64 bits
* Compiler: MSVC-2019-Community
* Release or debug mode: debug
* Specific flags used (if any):
* CGAL version: CGAL-5.4
* Boost version: boost_1_78_0
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by efifogel** [comment]
The drawing function is wrong.
The computation is correct.
The result is one polygon with holes that has 6 vertices. This polygon is
not simple.
Actually the drawing is not completely wrong.
The drawn boundary is correct; only the interior (the blue area) is missing
the right triangle.
   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by Supranaturaler** [comment]
> The drawing function is wrong. The computation is correct. The result is one polygon with holes that has 6 vertices. This polygon is not simple. Actually the drawing is not completely wrong. The drawn boundary is correct; only the interior (the blue area) is missing the right triangle. ____ _ ____ _ /_____/_) o /__________ __ // (____ ( ( ( (_/ (_/-(-'_(/ _/

@efifogel 

According to CGAL manual, the result polygon is relatively simple.
![image](https://user-images.githubusercontent.com/40469886/206398503-cbd59969-6cb4-4951-bed2-50b9adb9fc8d.png)

I print the polygon, there has no holes.
```c++
    std::vector<Polygon_with_holes> differencePolygons;
    rectanglePolygonSet.polygons_with_holes(std::back_inserter(differencePolygons));
    std::cout << "number of polygon_with_holes: " << differencePolygons.size() << std::endl;
    const Polygon_with_holes& resultPolygon = differencePolygons.front();
    if (!resultPolygon.has_holes())
    {
        std::cout << "the polygon has no holes" << std::endl;
    }
    const std::vector<Point_2>& vecPoints = resultPolygon.outer_boundary().container();
    std::cout << vecPoints.size() << std::endl;
    for (const Point_2& point : vecPoints)
    {
        std::cout << point.x() << "," << point.y() << std::endl;
    }
```
![image](https://user-images.githubusercontent.com/40469886/206401478-b9e8fcf0-0e2b-42f5-8494-57396775040b.png)

What I want is to get **two simple polygons** not this relatively simple polygon. Any suggestions?

**Comment by efifogel** [comment]
Hi Supranaturaler,

I don't think that there is a function that splits the boundary of a
polygon with holes into simple polygons, but you can do something like that:

Construct a Polygon_set_2 object.
Polygon_set_2 ps;
Update it; that is, apply Boolean operations.
Extract the underlying arrangement:
const auto& arrangement = ps.arrangement();
Traverse the arrangement faces; discard faces that are not part of the
result; something like the following:
for (auto fh : arrangement.faces_handles()) {
  if (! fh->contained() continue;
  auto ccb = fh->outer_ccb();
  typename Arrangement::Halfedge_const_handle he = ccb;
  do std::cout << he->target()->point() << " ";
  while (++he != ccb);
  std::cout << std::endl;
  // Traverse the outer ccb of the face
}

Efi

   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/
