### ISSUE TITLE
convex_hull_2 doesn't include collinear points.

### ISSUE THREAD

**Issue by AlexHCC** [CGAL/cgal#7113]
## Issue Details

Hi, I am new to CGAL, so this may be either a documentation problem, or a missing feature. 
I am using `Exact_predicates_exact_constructions_kernel` and the `convex_hull_2` function to create a convex hull from a set of points, but the output doesn't include points that are on top of the convex hull edges (collinear with 2 other points on the convex hull). 
It would be optimal in terms of speed and ease of use if there was a way to tell CGAL to include those points, instead of adding them after manually. So my question is, is there a way to do that?
I've seen there is Traits::Left_turn_2, I am not sure if this is relevant to the question, or how to modify it to be true for collinear points too.

## Example

```
#include <CGAL/Exact_predicates_exact_constructions_kernel.h>
#include <CGAL/convex_hull_2.h>

typedef CGAL::Exact_predicates_inexact_constructions_kernel K;
typedef K::Point_2 Point;
typedef std::vector<Point> Points;
```
Then I have the set of points: (0,0), (1,1), (2,2), (0,2)
But the convex hull is: (0,0), (2,2), (0,2), but I want it to include (1,1).

```
  Points set;
  Points convex_hull;
  CGAL::convex_hull_2(set.begin(), set.end(), std::back_inserter(convex_hull_v));
```

## Environment

* Operating system: Linux 64bits
* Compiler: GCC
* Release or debug mode: Release
* CGAL version: 5.5

**Comment by afabri** [comment]
The easiest way to achieve what you want is using a 2D triangulation as it keeps collinear vertices on the convex hull.

**Comment by AlexHCC** [comment]
Yes, this solves my issue, thank you.
