### ISSUE TITLE
CGAL overrides BUILD_TESTING for parent project when consumed as a third-party library

### ISSUE THREAD

**Issue by puneetmatharu** [CGAL/cgal#7121]
## Issue Details

I'm working on a project that consumes CGAL as a third-party library via FetchContent. After installing my project as well as CGAL, my `<project-name>Config.cmake` file locates CGAL using `find_dependency(...)`. When CGAL is found this way, it inevitably reads the file `<INSTALL_DIR>/lib/cmake/CGAL/CGAL_add_test.cmake` which hardcodes the value of `BUILD_TESTING` as a cache variable. When I build my tests as a separate project, this disables testing for them and I have to explicitly pass `-DBUILD_TESTING=ON` at CMake configure time to reenable them. 

According to Scott Craig's book ["Professional CMake: A Practical Guide"](https://crascit.com/professional-cmake/), it is best to avoid explicitly setting `BUILD_TESTING` in case the project is being consumed as a subproject:

```txt
31.2. Don’t Assume A Top Level Build

...

Another common problem is modifying variables that have the potential to affect the whole build,
not just the project. A classic example is forcing the value of cache variables like BUILD_SHARED_LIBS,
BUILD_TESTING, CMAKE_BUILD_TYPE, CMAKE_MODULE_PATH or CMAKE_RUNTIME_OUTPUT_DIRECTORY. Using the FORCE
or INTERNAL keywords with the set() command on these variables prevents a parent project from
overriding that choice. Quite often, these variables shouldn’t be defined by the project as cache
variables at all, and maybe shouldn’t even be set by the project to begin with. For variables like
CMAKE_MODULE_PATH, append to existing values rather than replace them.
```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): not relevant
* Compiler: not relevant
* Release or debug mode: not relevant
* Specific flags used (if any): not relevant
* CGAL version: 5.5.1
* Boost version: 1.80.0
* Other libraries versions if used (Eigen, TBB, etc.): none

## Solution

I think you can get around this by renaming `BUILD_TESTING`. For example, to make it project-specific you may wish to use `CGAL_BUILD_TESTING`. I have attached a patch file (see below) that contains the required changes applied to CGAL release version 5.5.1.

[patch.zip](https://github.com/CGAL/cgal/files/10222532/patch.zip)

**Comment by lrineau** [comment]
Hi, I am glad you are using CGAL for your project. :tada:

**Comment by puneetmatharu** [comment]
Hi, this was logged (with a patch provided) nearly a year ago but keeps being moved to a later milestone. Do you have any estimates on when it is likely to be merged in? Thank you.

**Comment by lrineau** [comment]
Hi @puneetmatharu, it seems that one-year old issue was left forgotten. Can you please create a pull-request corresponding to the patch? That will help us find time to review and integrate the patch.
