### ISSUE TITLE
Is function_output_iterator.hpp include needed in copy_face_graph.h ?

### ISSUE THREAD

**Issue by cedricpradalier** [CGAL/cgal#7123]
_Please use the following template to help us solving your issue._

## Issue Details

_Describe your issue. Please be specific (compilation error, runtime error, unexpected behavior, wrong results, etc.)._

I use the latest CGAL (bullseye) on ubuntu 18.04 (old hardware that needs 18.04 for now) and 20.04. 
$ dpkg -l libcgal-dev
ii  libcgal-dev:amd64                                              5.4-1~deb11u1                        amd64                                C++ library for computational geometry (development files)

I've noticed that compilation fails on /usr/include/CGAL/boost/graph/copy_face_graph.h with the following missing include file:
 #include <boost/iterator/function_output_iterator.hpp>
On ubuntu 18, there is a file located at /usr/include/boost/function_output_iterator.hpp (no iterator sub directory).

Anyway, for my use case, I am just commenting this include out and everything compiles. Is this include really needed ? Should it be removed ?

## Source Code

_If your issue arises by using CGAL in your own source code, please provide a minimalist example that we can compile easily to reproduce the bug. If your issue arises from using a CGAL program (demo, example, etc.), please let us know which one. Helping you solving an issue is much easier and efficient if we can reproduce it._

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Ubuntu 18.04/20.04
* Compiler: gcc/g++
* Release or debug mode:
* Specific flags used (if any):
* CGAL version: 5.4-1~deb11u1
* Boost version: 1.65 on 18.04, 1.71 on 20.04.
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by sloriot** [comment]
Note that CGAL requires boost 1.66. This header is not in boost 1.65.

**Comment by afabri** [comment]
Seems no longer to be in the master branch. See [here](https://github.com/CGAL/cgal/blob/master/BGL/include/CGAL/boost/graph/copy_face_graph.h)

**Comment by MaelRL** [comment]
It was moved to internal helper headers (57439c0235e0fa37de62a4779134f52ac043b535), and it is used in copy_face_graph.h in the `impl::make_functor(...)` calls.

**Comment by afabri** [comment]
> Note that CGAL requires boost 1.66. This header is not in boost 1.65.

@sloriot : Shall we nevertheless add the `#include` to the old location of the header?  We require 1.66 but in practice many packages work with older versions.

**Comment by sloriot** [comment]
I would not do the change since we no longer support it.
