### ISSUE TITLE
Optimal Transport: memory leak

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#7132]
## Issue Details

Reported by the address sanitizer in this [testsuite](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.6-Ic-139/Optimal_transportation_reconstruction_2_Examples/TestReport_lrineau_Fedora-Release.gz).

I can reproduce the "Premature ending"  by adding `CGAL::get_default_random() = CGAL::Random(1671586136);` in `main()`.

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):
* Compiler:
* Release or debug mode:
* Specific flags used (if any):
* CGAL version:
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by sloriot** [comment]
Duplicate of #7119

**Comment by afabri** [comment]
Reading the code it is also a bad idea to give local variable names the `m_` prefix, usually used for data members.

**Comment by afabri** [comment]
[Here ](https://github.com/CGAL/cgal/blob/master/Optimal_transportation_reconstruction_2/include/CGAL/Optimal_transportation_reconstruction_2.h#L540) the last argument `true` makes that in the vertex the pointer to the sample is set to `nullptr`. In case the function returns in line 555 the collected samples are not assigned again, and that is the leak.
