### ISSUE TITLE
CGAL::create_interior_straight_skeleton_2 with none strictly simple polygon

### ISSUE THREAD

**Issue by Supranaturaler** [CGAL/cgal#7138]
## Issue Details

If I use CGAL::create_interior_straight_skeleton_2 with non strictly simple polygon, the null pointer is returned.
How can I fix this?
![image](https://user-images.githubusercontent.com/40469886/209073723-0b1727cd-3a26-4cbd-a557-d3862cb13768.png)

## Source Code

```c++
#include "CGAL/Exact_predicates_exact_constructions_kernel.h"
typedef CGAL::Exact_predicates_exact_constructions_kernel Kernel;
typedef Kernel::Point_2 Point_2;

#include "CGAL/Polygon_2.h"
#include "CGAL/Polygon_with_holes_2.h"
typedef CGAL::Polygon_2<Kernel> Polygon_2;
typedef CGAL::Polygon_with_holes_2<Kernel> Polygon_with_holes;

#include "CGAL/Polygon_set_2.h"
typedef CGAL::Polygon_set_2<Kernel> Polygon_set_2;

#include "CGAL/draw_polygon_2.h"
#include "CGAL/draw_polygon_with_holes_2.h"

#include "CGAL/create_straight_skeleton_from_polygon_with_holes_2.h"

int main(int argc, char* argv[])
{
    Polygon_2 rectangle;
    rectangle.push_back(Point_2(0, 0));
    rectangle.push_back(Point_2(2, 0));
    rectangle.push_back(Point_2(2, 2));
    rectangle.push_back(Point_2(0, 2));

    Polygon_2 triangle;
    triangle.push_back(Point_2(0.5, 0.5));
    triangle.push_back(Point_2(1.5, 0.5));
    triangle.push_back(Point_2(1, 2));

    Polygon_set_2 rectanglePolygonSet(rectangle);
    Polygon_set_2 trianglePolygonSet(triangle);
    rectanglePolygonSet.difference(trianglePolygonSet);

    std::vector<Polygon_with_holes> differencePolygons;
    rectanglePolygonSet.polygons_with_holes(std::back_inserter(differencePolygons));
    std::cout << "number of polygon_with_holes: " << differencePolygons.size() << std::endl;
    const Polygon_with_holes& resultPolygon = differencePolygons.front();
    CGAL::draw(resultPolygon);

    typedef boost::shared_ptr<Straight_skeleton> Straight_skeleton_ptr;
    Straight_skeleton_ptr pSkeleton = CGAL::create_interior_straight_skeleton_2(resultPolygon, Kernel());
    if (pSkeleton)
    {
        std::cout << "[Info] CGAL::create_interior_straight_skeleton_2 success!" << std::endl;
        return true;
    }
    else
    {
        std::cout << "[Error] CGAL::create_interior_straight_skeleton_2 failed!" << std::endl;
        return false;
    }
}
```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows 11 home basic 64 bits
* Compiler: MSVC-2019-Community
* Release or debug mode: debug 
* Specific flags used (if any):
* CGAL version: CGAL5.5.1
* Boost version: boost_1_78_0
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by MaelRL** [comment]
The hole(s) should not intersect the outer boundary. You should use a single outer boundary, which will form a strictly simple polygon

```
  Polygon_2 rectangle_m_triangle;
  rectangle_m_triangle.push_back(Point_2(0, 0));
  rectangle_m_triangle.push_back(Point_2(2, 0));
  rectangle_m_triangle.push_back(Point_2(2, 2));
  rectangle_m_triangle.push_back(Point_2(1, 2));
  rectangle_m_triangle.push_back(Point_2(1.5, 0.5));
  rectangle_m_triangle.push_back(Point_2(0.5, 0.5));
  rectangle_m_triangle.push_back(Point_2(1, 2));
  rectangle_m_triangle.push_back(Point_2(0, 2));
  ...
  Straight_skeleton_ptr pSkeleton = CGAL::create_interior_straight_skeleton_2(rectangle_m_triangle, Kernel());
```

![image](https://user-images.githubusercontent.com/5074170/210238541-03f74105-ed44-4224-b1ee-bba1b93bde18.png)

**Comment by Supranaturaler** [comment]
> The hole(s) should not intersect the outer boundary. You should use a single Polygon_2, which will form a strictly simple polygon:
> 
> ```
>   Polygon_2 rectangle_m_triangle;
>   rectangle_m_triangle.push_back(Point_2(0, 0));
>   rectangle_m_triangle.push_back(Point_2(2, 0));
>   rectangle_m_triangle.push_back(Point_2(2, 2));
>   rectangle_m_triangle.push_back(Point_2(1, 2));
>   rectangle_m_triangle.push_back(Point_2(1.5, 0.5));
>   rectangle_m_triangle.push_back(Point_2(0.5, 0.5));
>   rectangle_m_triangle.push_back(Point_2(1, 2));
>   rectangle_m_triangle.push_back(Point_2(0, 2));
>   ...
>   Straight_skeleton_ptr pSkeleton = CGAL::create_interior_straight_skeleton_2(rectangle_m_triangle, Kernel());
> ```
> 
> ![image](https://user-images.githubusercontent.com/5074170/210238541-03f74105-ed44-4224-b1ee-bba1b93bde18.png)

The polygon is generated by polygonset boolean operation. This operation can't guarantee that the generated polygon is strictly simple. If so, how can I convert this non-strictly simple polygon to strictly simple polygon.
