### ISSUE TITLE
Tutorial 3D Mesh Generation -- 4.3.1 3D Polyhedral Domains

### ISSUE THREAD

**Issue by citystrawman** [CGAL/cgal#7162]
_Please use the following template to help us solving your issue._

## Issue Details

I am a new user of CGAL and I just started the tutorial of 3D Mesh Generation from this [link](https://doc.cgal.org/latest/Mesh_3/index.html#Mesh_3InputDomain). In 4.3.1 3D Polyhedral Domains, the source code produces out1.mesh and out2.mesh and has its picture. However when I compiled the code, my out1.mesh is much more coarse than the picture. Here's my out1.mesh:  
![企业微信截图_16728233352169](https://user-images.githubusercontent.com/9004748/210681585-08a6993a-ce75-4589-8210-de31e5b2d45a.png)
then I adjusted the facet_size to 0.1 and the elephant looks similar to the tutorial picture. 
I dont know if this is correct 

## Source Code

_If your issue arises by using CGAL in your own source code, please provide a minimalist example that we can compile easily to reproduce the bug. If your issue arises from using a CGAL program (demo, example, etc.), please let us know which one. Helping you solving an issue is much easier and efficient if we can reproduce it._

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):
* Compiler:
* Release or debug mode:
* Specific flags used (if any):
* CGAL version:
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by janetournois** [comment]
Hello,
are you using the exact same example as `mesh_polyhedral_domain.cpp`, and with what version of CGAL?
Can you please fill the "environment" section in your issue, so that we can check if we reproduce it?

**Comment by citystrawman** [comment]
> Hello, are you using the exact same example as `mesh_polyhedral_domain.cpp`, and with what version of CGAL? Can you please fill the "environment" section in your issue, so that we can check if we reproduce it?

I use the latest 5.5.1 version. My OS is windows 10, I use cmake plus vcpkg to generate the visual studio 2019 project. 

BTW the strange thing is,  I changed the parameters of facet_size to see its effect, then when I changed the parameter back to 0.15, the mesh got correct shape. I swear I did not change anything.

**Comment by afabri** [comment]
I close the issue. In case you can reproduce it, just reopen it.
