### ISSUE TITLE
compilation errors for CGAL with NVCC

### ISSUE THREAD

**Issue by ZaswinsZ** [CGAL/cgal#7174]
# Issue Details
When contents of Create_offset_polygons_2.cpp is added to .cu file and compiled with nvcc, it results in the following error:

`/usr/include/c++/9/array(110): error: incomplete type is not allowed
          detected during:
            instantiation of class "std::array<_Tp, _Nm> [with _Tp=CGAL::Point_2<CGAL::Epick>, _Nm=2UL]" 
/tmp/cgal/include/CGAL/Cartesian/Ray_2.h(36): here
            instantiation of class "CGAL::RayC2<R_> [with R_=CGAL::Epick]" 
/tmp/cgal/include/CGAL/Ray_2.h(31): here
            instantiation of class "CGAL::Ray_2<R_> [with R_=CGAL::Epick]" 
/usr/include/c++/9/type_traits(884): here
            instantiation of class "std::is_constructible<_Tp, _Args...> [with _Tp=CGAL::Vector_2<CGAL::Epick>, _Args=<CGAL::Vector_2<CGAL::Epick> &&>]" 
/usr/include/c++/9/type_traits(920): here
            instantiation of class "std::__is_move_constructible_impl<_Tp, true> [with _Tp=CGAL::Vector_2<CGAL::Epick>]" 
/usr/include/c++/9/type_traits(926): here
            [ 3 instantiation contexts not shown ]
            instantiation of class "std::__is_nothrow_swappable_impl<_Tp> [with _Tp=CGAL::Vector_2<CGAL::Epick>]" 
/usr/include/c++/9/type_traits(2556): here
            instantiation of class "std::is_nothrow_swappable<_Tp> [with _Tp=CGAL::Vector_2<CGAL::Epick>]" 
/usr/include/c++/9/type_traits(2568): here
            instantiation of "const bool std::is_nothrow_swappable_v [with _Tp=CGAL::Vector_2<CGAL::Epick>]" 
/tmp/cgal/include/CGAL/Cartesian/Point_2.h(55): here
            instantiation of class "CGAL::PointC2<R_> [with R_=CGAL::Epick]" 
/tmp/cgal/include/CGAL/Point_2.h(31): here
            instantiation of class "CGAL::Point_2<R_> [with R_=CGAL::Epick]" 
saxpy_with_cgal.cu(36): here`

# Environment
OS: ubuntu 18.04
GCC: 9.4/9.5
CUDA: 11.x and 12.x
CGAL: 5.5.1

 # Code
`
#include <stdio.h>
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>

#include <CGAL/Point_2.h>
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/Cartesian/Ray_2.h>
#include <CGAL/Vector_2.h>
#include <CGAL/Polygon_2.h>
#include <CGAL/Cartesian/Point_2.h>
#include <CGAL/create_offset_polygons_2.h>
#include "print.h"

#include <boost/shared_ptr.hpp>

#include <vector>
#include <cassert>

typedef CGAL::Exact_predicates_inexact_constructions_kernel K ;

typedef K::Point_2                   Point ;
typedef CGAL::Polygon_2<K>           Polygon_2 ;
typedef CGAL::Straight_skeleton_2<K> Ss ;

typedef boost::shared_ptr<Polygon_2> PolygonPtr ;
typedef boost::shared_ptr<Ss> SsPtr ;

typedef std::vector<PolygonPtr> PolygonPtrVector ;

__global__
void saxpy(int n, float a, float *x, float *y)
{
  int i = blockIdx.x*blockDim.x + threadIdx.x;
  if (i < n) y[i] = a*x[i] + y[i];
}

int main(void)
{

  Polygon_2 poly ;
  poly.push_back( Point(-1,-1) ) ;
  poly.push_back( Point(0,-12) ) ;
  poly.push_back( Point(1,-1) ) ;
  poly.push_back( Point(12,0) ) ;
  poly.push_back( Point(1,1) ) ;
  poly.push_back( Point(0,12) ) ;
  poly.push_back( Point(-1,1) ) ;
  poly.push_back( Point(-12,0) ) ;
  assert(poly.is_counterclockwise_oriented());

SsPtr ss = CGAL::create_interior_straight_skeleton_2(poly);

  double lOffset = 1 ;
  PolygonPtrVector offset_polygons = CGAL::create_offset_polygons_2<Polygon_2>(lOffset,*ss);
  print_polygons(offset_polygons);

  int N = 1<<20;
  float *x, *y, *d_x, *d_y;
  x = (float*)malloc(N*sizeof(float));
  y = (float*)malloc(N*sizeof(float));

  cudaMalloc(&d_x, N*sizeof(float));
  cudaMalloc(&d_y, N*sizeof(float));

  for (int i = 0; i < N; i++) {
    x[i] = 1.0f;
    y[i] = 3.0f;
  }

  cudaMemcpy(d_x, x, N*sizeof(float), cudaMemcpyHostToDevice);
  cudaMemcpy(d_y, y, N*sizeof(float), cudaMemcpyHostToDevice);

  // Perform SAXPY on 1M elements
  saxpy<<<(N+255)/256, 256>>>(N, 2.0f, d_x, d_y);

  cudaMemcpy(y, d_y, N*sizeof(float), cudaMemcpyDeviceToHost);

  float maxError = 0.0f;
  for (int i = 0; i < N; i++)
    maxError = max(maxError, abs(y[i]-4.0f));
  printf("Max error: %f\n", maxError);

  cudaFree(d_x);
  cudaFree(d_y);
  free(x);
  free(y);
}
`

# NVCC command line
`/usr/local/cuda/bin/nvcc -DCGAL_DIR=/tmp/cgal/lib/cmake/CGAL -DCGAL_USE_CORE=1 -DCGAL_USE_GMPXX=1 -isystem=/tmp/gmp/include -isystem=/tmp/cgal/auxiliary/mpfr/include -isystem=/tmp/cgal/include -isystem=/usr/local/boost/include -isystem=/usr/local/cuda/include -std=c++17 -rdc=true saxpy_with_cgal.cu -o saxpy_with_cgal`

**Comment by mglisse** [comment]
Please post a correctly formatted, minimal, self-contained example, there is nothing we can do with this.

It seems that nvcc may benefit from the same workaround as Intel's compiler in CGAL/Point_2.h (look for `__INTEL_COMPILER`). Note that I don't think CGAL officially supports this compiler.

**Comment by ZaswinsZ** [comment]
Using that #define did not help either. I will keep CGAL away from the nvcc compiler. Thanks!
