### ISSUE TITLE
Is there a good way to make domain divisions/regions by random surfaces?

### ISSUE THREAD

**Issue by citystrawman** [CGAL/cgal#7175]
_Please use the following template to help us solving your issue._

## Issue Details

I am trying to use CGAL to simulate earth regions divided by stratums(which is modeled by surfaces). My original model is : 1. the rock mass off model which composed 1 whole rock mass; 2. the stratums off model which composed of several surfaces. They are shown in the following pictures:

![image](https://user-images.githubusercontent.com/9004748/211730921-6415120d-aa48-4b06-b1a6-c2b1dcab90ee.png)
![image](https://user-images.githubusercontent.com/9004748/211730993-2263ea72-70cf-46c9-a40a-5e60e3d6ed07.png)

Then my goal is to divide the rock mass into 4 meshed layers by the 3 stratums as shown here:
![企业微信截图_16733349555736](https://user-images.githubusercontent.com/9004748/211731250-e3baf123-480c-442f-93a5-06a684000703.png)

In CGAL's 3D Mesh Generation there's a similar [code example](https://doc.cgal.org/latest/Mesh_3/index.html#Mesh_3_section_io) which is section 4.3.2 Remeshing a Polyhedral Domain with Surfaces, in which a domain and 2 surfaces generates a meshing domain whose tetrahedras vertex exactly coincide with the surface points. I tried to make the domain smaller so that all surfaces cut cross it, however the domain could not differentiate the regions: 
![image](https://user-images.githubusercontent.com/9004748/211732389-8155dab8-6a42-4cc8-ace1-3903369926f3.png)
In the output file, all tetrahedras are referenced as a same number. 

So is it possible in CGAL that I can divide the generated mesh by different regions?

## Source Code

_If your issue arises by using CGAL in your own source code, please provide a minimalist example that we can compile easily to reproduce the bug. If your issue arises from using a CGAL program (demo, example, etc.), please let us know which one. Helping you solving an issue is much easier and efficient if we can reproduce it._

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): WIndows 10
* Compiler: Visual Studion 2019
* Release or debug mode:
* Specific flags used (if any):
* CGAL version:
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by sloriot** [comment]
You can compute intersection polylines of each stratum with the cube using [`PMP::surface_intersection()`](https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__corefinement__grp.html#ga6e6c4a724ce19e7a207de56f3a7408ab). Then insert those polylines as feature to protect in the domain.

**Comment by citystrawman** [comment]
> You can compute intersection polylines of each stratum with the cube using [`PMP::surface_intersection()`](https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__corefinement__grp.html#ga6e6c4a724ce19e7a207de56f3a7408ab). Then insert those polylines as feature to protect in the domain.
Thanks sloriot. I think your suggestion is to solve the inconsistency where the surface intersects with the slope domain. This is also an issue that I need to solve. However,  my big issue is to find a way to automatically divide the domain into regions which are separated by the surfaces. Do you have a solution for that?

**Comment by citystrawman** [comment]
> You can compute intersection polylines of each stratum with the cube using [`PMP::surface_intersection()`](https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__corefinement__grp.html#ga6e6c4a724ce19e7a207de56f3a7408ab). Then insert those polylines as feature to protect in the domain.

Thanks sloriot. I think your suggestion is to solve the inconsistency where the surface intersects with the slope domain. This is also an issue that I need to solve. However, my big issue is to find a way to automatically divide the domain into regions which are separated by the surfaces. Do you have a solution for that?

**Comment by sloriot** [comment]
If you mean the location of the domain, you can put the meshes in a AABB-tree, shot a ray with `all_intersected_primitive()` collect the intersected faces and then you'll get where you are in the arrangement of meshes (note that if you hit an edge/vertex it is simpler to shot another ray than handling particular cases.

**Comment by citystrawman** [comment]
> @citystrawman Have you solve the issue yourself meanwhile, following Sébastien's suggestions? Your need would probably require creating a specific domain class.

Not yet. Are there any examples in CGAL's tutorial?

**Comment by citystrawman** [comment]
I've tested the cgal official example,  by [surface_intersection()](https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__corefinement__grp.html#ga6e6c4a724ce19e7a207de56f3a7408ab) I got polylines and by add the polylines to features I got a very nice mesh generation along the intersected lines. However when I applied these to my model it took too long time.

**Comment by afabri** [comment]
Maybe you can share the data and a self contained code. If it was small enough we might add it to the manual. We could also have a look at the performance problem you mention.
