### ISSUE TITLE
Writing and reading PLY file with colors does not work

### ISSUE THREAD

**Issue by stla** [CGAL/cgal#7176]
## Issue Details

I have a mesh with face colors (all blue). When I write it to a PLY file with `CGAL::IO::write_PLY`, here is what I get in the file for a face:

```
....
3 0 2 8 0 0 255 255 0 0 255 255 
....
```
The color is there but it is duplicated, I don't know whether this is normal.

Now, I read this file with `CGAL::IO::read_PLY`. And all the color components I get are `0`, even the third one which should be `255`.

I also tried with `write/read_OFF`, and this works fine.

**Comment by afabri** [comment]
I've created this [gist](https://gist.github.com/afabri/150da258c9f9da6e78aa23821ec47dd7), and I think everything is fine.  You do not give enough detail but just report us symptoms.  The next time please give us a minimal example as I did.

**Comment by stla** [comment]
I think I understand: my mesh has *two* property maps `"f:color"`. The other one has value type `std::string` and provides the colors as hex codes. It seems that `read_PLY` combines the two property maps, and automatically converts the hes codes to RGB. I'll confirm later.

**Comment by stla** [comment]
I confirm. But there's no hex code in my map, only the word "blue".
