### ISSUE TITLE
Weighted_Minkowski_Distance in Spatial searching not working with exact kernels

### ISSUE THREAD

**Issue by thomasp85** [CGAL/cgal#7194]
## Issue Details

When trying to compile a spatial search with an exact kernel using weighted Minkowski distance we get a compiler error due to FT being passed in directly to `std::pow()` in the source code for Weighted_Minkowksi_Distance:

https://github.com/CGAL/cgal/blob/5f205d35068b5fb951f8e5d95654c99827f65a7e/Spatial_searching/include/CGAL/Weighted_Minkowski_distance.h#L360

## Source Code

Modified from the Minkowski example in the spatial searching docs

```c++
#include <CGAL/Exact_predicates_exact_constructions_kernel.h>
#include <CGAL/Orthogonal_k_neighbor_search.h>
#include <CGAL/Weighted_Minkowski_distance.h>
#include <CGAL/Search_traits_2.h>
#include <CGAL/point_generators_2.h>
typedef CGAL::Exact_predicates_exact_constructions_kernel K;
typedef K::Point_2 Point_d;
typedef CGAL::Random_points_in_square_2<Point_d> Random_points_iterator;
typedef CGAL::Counting_iterator<Random_points_iterator> N_Random_points_iterator;
typedef CGAL::Search_traits_2<K> TreeTraits;
typedef CGAL::Weighted_Minkowski_distance<TreeTraits> Distance;
typedef CGAL::Orthogonal_k_neighbor_search<TreeTraits, Distance> K_neighbor_search;
typedef K_neighbor_search::Tree Tree;

[[cpp11::register]]
int main()
{
  const int D = 2;
  const int N = 1000;
  const unsigned int K = 5;
  Random_points_iterator rpit( 1.0);
  Tree tree(N_Random_points_iterator(rpit,0),
            N_Random_points_iterator(N));
  Point_d query(0,0);
  double w[2] = { 1.0, 2.0};
  Distance tr_dist(3.14,D,w, w+D);
  K_neighbor_search search(tree, query, K, 0.0, true, tr_dist);
  for (K_neighbor_search::iterator it = search.begin(); it!=search.end(); ++it)
    std::cout << "Point " << (*it).first << " at distance = " << (*it).second << std::endl;
  return 0;
}
```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Mac M1
* Compiler: clang
* Release or debug mode: release
* Specific flags used (if any): =-DCGAL_DO_NOT_USE_BOOST_MP -DCGAL_USE_GMPXX -DBOOST_NO_AUTO_PTR
* CGAL version: 5.5.1
* Boost version: 1.81.0
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by mglisse** [comment]
What behavior do you expect? Epeck is based on rational numbers, q^3.14 is bound to be problematic.

**Comment by thomasp85** [comment]
I would expect either a precondition in the docs stating the requirements of the kernel, or (and I think this is better), casting FT to double and note the lack of exactness in the docs. Latter would (I think) be in line with the intent of Spatial Searching which already support approximate computations

**Comment by afabri** [comment]
I get your point and will have a look., but are you sure that you want to construct a kd-tree which computes medians on coordinates of the Epeck number type. 
I also never used weighted Minkowski distance, so I have a question what value of power people use. For example is it most often just 2?

**Comment by thomasp85** [comment]
TBH, i don't have a great answer as I'm mainly just creating a wrapper library for using CGAL from R. I'm happy to take "not supported" as an answer and move on

**Comment by lrineau** [comment]
Fixed by https://github.com/CGAL/cgal/pull/7219
