### ISSUE TITLE
Missing doxygen link 

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#7195]
## Issue Details

There is a link for ` CGAL::Orientation`   [here](https://doc.cgal.org/latest/Kernel_23/group__PkgKernel23Ref.html), but not [here](https://doc.cgal.org/latest/Polygon/group__PkgPolygon2Functions.html#gad1cb4044f1c59db27c1a06cb47957acb). How can we fix that? Is this a doxygen problem?

**Comment by albert-github** [comment]
I just looked in the overnight documentation build and see for the 1.8.13 version in https://cgal.geometryfactory.com/CGAL/Manual_doxygen_test/CGAL-5.6-Ic-158/output2/Polygon/group__PkgPolygon2Functions.html#gad1cb4044f1c59db27c1a06cb47957acb
that the link is missing but for the current master version in https://cgal.geometryfactory.com/CGAL/Manual_doxygen_test/CGAL-5.6-Ic-158/master/Polygon/group__PkgPolygon2Functions.html#gad1cb4044f1c59db27c1a06cb47957acb that the link is present, so it is probably a quirk of the 1.8.13 version (version is from December 29, 2016)

On the question "How can we fix that?" in my personal opinion abandon the 1.8.13 version in favor of the current 1.9.6 version.

**Comment by afabri** [comment]
This is no longer an issue in the online doumentation of the master branch.
