### ISSUE TITLE
getting started: failure to build examples

### ISSUE THREAD

**Issue by skramm** [CGAL/cgal#7196]
I wanted to give a try on CGAL, but was unable to make the demo build succeed.
I followed the steps described here: https://doc.cgal.org/latest/Manual/usage.html

I *think* I have all the requirements (but maybe I'm wrong?)
```
libmpfr-dev: 4.0.2-1
libeigen3-dev: 3.3.7-2
libboost-dev: 1.71.0.0ubuntu2
libgmp-dev: 2:6.2.0+dfsg-4ubuntu0.1
```

## Issue Details

Steps:

1. `$ sudo apt install libcgal-dev`
2. `$ sudo apt install libcgal-qt5-dev`
3. `$ mkdir $HOME/cgal_examples`
4. `$ cd $HOME/cgal_examples`
5. `$ wget https://github.com/CGAL/cgal/releases/download/v5.5.1/CGAL-5.5.1-examples.tar.xz`
6. `$ tar -xf CGAL-5.5.1-examples.tar.xz`
7. `$ cd CGAL-5.5.1/examples/Triangulation_2/`
8. `$ cmake -DCMAKE_BUILD_TYPE=Release .`

(please note that step 2 above isn't mentioned on this page https://doc.cgal.org/latest/Manual/usage.html
but seems to be required as I had another failure before I installed it.
Could be useful to add that package to the manual.)

Output (of step 8, all the others are fine):
```
-- Using header-only CGAL
-- Targetting Unix Makefiles
-- Using /usr/bin/c++ compiler.
-- Boost include dirs: /usr/include
-- Boost libraries:    
-- Using gcc version 4 or later. Adding -frounding-math
-- Configuring done
CMake Error at /usr/lib/x86_64-linux-gnu/cmake/CGAL/CGAL_CreateSingleSourceCGALProgram.cmake:49 (add_executable):
  Target "draw_triangulation_2" links to target "CGAL::CGAL_Basic_viewer" but
  the target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:15 (create_single_source_cgal_program)

CMake Error at /usr/lib/x86_64-linux-gnu/cmake/CGAL/CGAL_CreateSingleSourceCGALProgram.cmake:49 (add_executable):
  Target "star_conflict_zone" links to target "CGAL::CGAL_Basic_viewer" but
  the target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:15 (create_single_source_cgal_program)

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
```
And, of course, `make` fails.

Is this a version glitch, between repo package and official releases? I did not try the GH releases archives.

Thanks for your help!

## Environment

* Operating system: Ubuntu 20.04.5 LTS
* Boost version: (see above)
* Other libraries versions if used (Eigen, TBB, etc.):  (see above)

**Comment by sloriot** [comment]
Try downloading CGAL-5.5.1, extract the archive in `/where/you/want`:
```
rm CMakeCache.txt
CGAL_DIR=/where/you/want/CGAL-5.5.1 cmake -DCMAKE_BUILD_TYPE=Release .
make
```

Since `CGAL_DIR` was not set, cmake takes the CGAL version from your system (install with `apt`) which probably too old compared to the examples you are trying to compile.

**Comment by skramm** [comment]
Thanks Sebastien ;-)
ok, did that, uninstalled the package manager version and got the 5.5.1 archive, uncompressed it, and checked `INSTALL.md`. But this file does not give the install informations (maybe add a link in there? The info is actually here: https://doc.cgal.org/latest/Manual/usage.html#title4)

so I did:
```
$ cmake .
$ sudo make install
```
Went fine, and headers are indeed copied in `/usr/local/include/`.
Then, back to my "examples" folder, and cmake and make wen uneventfull.

Thanks again, closing issue!
