### ISSUE TITLE
batch remove edges in arrangement

### ISSUE THREAD

**Issue by thomasp85** [CGAL/cgal#7216]
## Issue Details

I have made an overlay of two arrangements and now wish to remove edges in the result that does not have the expected `data()` value. However, simply iterating over the edges in the arrangement, removing them as they are encountered, is not possible as removing the edge invalidates the iterator and crashes the program.

What is the correct strategy for removing multiple edges from an arrangement?

## Source Code

_If your issue arises by using CGAL in your own source code, please provide a minimalist example that we can compile easily to reproduce the bug. If your issue arises from using a CGAL program (demo, example, etc.), please let us know which one. Helping you solving an issue is much easier and efficient if we can reproduce it._

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Mac Arm
* Compiler: llvm
* Release or debug mode: release
* Specific flags used (if any):
* CGAL version: 5.5.1
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by thomasp85** [comment]
This (iterating and removing as encountered) was working in a previous build - perhaps the current failure is due to this change 5da848dbd3e4f9db3a1bc361bf22a9782a56cb80

But I'm only guessing

**Comment by thomasp85** [comment]
My pragmatic fix to this is to increment the iterator within the loop body before removing the edge

**Comment by afabri** [comment]
> My pragmatic fix to this is to increment the iterator within the loop body before removing the edge

This is not only pragmatic but also the only correct fix.  It "accidentally" worked while the underlying container was array like and hence the iterator was roughly a pointer and one could advance although the pointee was marked as deleted.
