### ISSUE TITLE
trying to use mingw32-make but got errors

### ISSUE THREAD

**Issue by citystrawman** [CGAL/cgal#7220]
_Please use the following template to help us solving your issue._

## Issue Details

I configured CGAL 5.5 example: AABB_tree by setting the generator as "cmake -G MingW-Makefiles", it configured successfully:

![image](https://user-images.githubusercontent.com/9004748/215154472-f73f728c-87fb-410b-ae77-74ede88ff61a.png)

Then I execute mingw32-make in the build directory but got errors:
.......
c:\progra~2\mingw-~1\winlib~1.0-r\mingw64\include\c++\12.2.0\bits\std_thread.h:286:26: error: no match for 'operator==' (operand types are 'std::thread::native_handle_type' and 'std::thread::native_handle_type')
  286 |     return __x._M_thread == __y._M_thread;
      |            ~~~~~~~~~~~~~ ^~ ~~~~~~~~~~~~~
      |                |                |
      |                |                std::thread::native_handle_type
      |                std::thread::native_handle_type
In file included from c:\progra~2\mingw-~1\winlib~1.0-r\mingw64\include\c++\12.2.0\bits\stl_algobase.h:64,
                 from c:\progra~2\mingw-~1\winlib~1.0-r\mingw64\include\c++\12.2.0\algorithm:60,
                 from D:/software/vcpkg/installed/x64-windows/include/CGAL/config.h:282:
.......

The screenshot is : 
![image](https://user-images.githubusercontent.com/9004748/215155641-4d4d23c5-02a3-4f5e-ac04-1eaceaef73b5.png)

I searched this issue and got this : https://github.com/jtv/libpqxx/issues/441 
But I am not sure how to solve this issue.

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Win10
* Compiler: 
* Release or debug mode:
* Specific flags used (if any):
* CGAL version: 5.5
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by citystrawman** [comment]
Just fixed this issue by commenting the codes. However when I ran the exe it gave me wrong output for invalid output:
![image](https://user-images.githubusercontent.com/9004748/215239939-8e5f44dd-2301-4657-9fc9-670961ee252e.png)
(**Actually I use Mingw as the generator because I want to run the code using VSCode rather than visual studio, but I am not clear how to make it correctly.**.. )

**Comment by lrineau** [comment]
Hi @citystrawman. The compilation error you got seems to be a bug from `<thread>` in MinGW version 12.2.0. It seems you are far from being the only one bitten by that bug. See for example https://github.com/jtv/libpqxx/issues/424 (and all other the issues, from different projects,  linking to that one).

If your program is not multi-threaded (or at least does not use CGAL code in parallel), then a possible workaround could be to use CGAL **without thread-support**. You can add **`-DCGAL_HAS_NO_THREADS`** to the compilation flags in the CMake cache variable `CMAKE_CXX_FLAGS`. Or add the command `add_definitions(-DCGAL_HAS_NO_THREADS)` in your `CMakeLists.txt`.
