### ISSUE TITLE
The icosahedron `(center, radius)` is not inscribed in the sphere `(center, radius)`.

### ISSUE THREAD

**Issue by stla** [CGAL/cgal#7224]
Hello, 

It took me at least two hours to figure out what happened :-(

`CGAL::make_icosahedron(g, center, radius)` indeed returns an icosahedron centered at `center`, but not of radius `radius`:

```cpp
void test() {
  Mesh3 mesh;
  Point3 O(0.0, 0.0, 0.0);
  CGAL::make_icosahedron<Mesh3, Point3>(mesh, O, 1.0);
  Rcpp::Rcout << mesh;
}
```

*Output:*
```
OFF
12 20 0

-1 1.61803 0
1 1.61803 0
-1 -1.61803 0
1 -1.61803 0
0 -1 1.61803
0 1 1.61803
0 -1 -1.61803
0 1 -1.61803
1.61803 0 -1
1.61803 0 1
-1.61803 0 -1
-1.61803 0 1
3  5 0 11
......
```

There's the golden number there.

**Comment by stla** [comment]
Very weird. I tried to divide the radius by `sqrt(phi²+1)` and this doesn't give the expected radius. Either I need to sleep or this function is totally bugged :-/

**Comment by stla** [comment]
Get it. One has to divide by `sqrt((phi²+1)/2)`.

**Comment by MaelRL** [comment]
This was fixed in https://github.com/CGAL/cgal/pull/6373.

```
OFF
12 20 0

0 0.525731 0.850651
0 0.525731 -0.850651
0 -0.525731 0.850651
0 -0.525731 -0.850651
0.525731 0.850651 0
0.525731 -0.850651 0
-0.525731 0.850651 0
-0.525731 -0.850651 0
0.850651 0 0.525731
0.850651 0 -0.525731
-0.850651 0 0.525731
-0.850651 0 -0.525731
...
```
