### ISSUE TITLE
Polygon_2::erase(circulator) failure

### ISSUE THREAD

**Issue by efifogel** [CGAL/cgal#7228]
## Issue Details

Calling the erase() member of Polygon_2 fails to return the correct value when the input is a circulator that points at the last element of the underlying sequence.

## Source Code

```
  CGAL::Polygon_2<Kernel, Container> p;
  auto circ = p.vertices_circulator();
  // advance circ to point at the last element
#if 1
  circ = p.erase(circ);
#else
    tmp = circ;
    ++tmp;
    p.erase(circ);
  circ = tmp
#endif
```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): all
* Compiler: all
* Release or debug mode: both
* Specific flags used (if any): none
* CGAL version: 5.5
* Boost version: irrelevant
* Other libraries versions if used (Eigen, TBB, etc.): irrelevant

**Comment by afabri** [comment]
Thank you Efi for pointing out.  I will fix it.

**Comment by lrineau** [comment]
Fixed by https://github.com/CGAL/cgal/pull/7230.
