### ISSUE TITLE
Improvement of layout of refines relations.

### ISSUE THREAD

**Issue by albert-github** [CGAL/cgal#7231]
An idea for improvement ?

In e.g Kernel_23/doc/Kernel_23/Concepts/FunctionObjectConcepts.h we have the line:
```
/*!
  \ingroup PkgKernel23ConceptsFunctionObjects
  \cgalConcept

  A type representing an iterator to the Cartesian coordinates of a point
  in two dimensions.

  \cgalRefines CopyConstructible
  \cgalRefines Assignable
  \cgalRefines DefaultConstructible

  \sa `Kernel::ConstructCartesianConstIterator_2`

*/
class CartesianConstIterator_2 {
public:

}; /* end Kernel::CartesianConstIterator_2 */

/*!
  \ingroup PkgKernel23ConceptsFunctionObjects
  \cgalConcept

  A type representing an iterator to the Cartesian coordinates of a point
  in three dimensions.

  \cgalRefines CopyConstructible
  \cgalRefines Assignable
  \cgalRefines DefaultConstructible

  \sa `Kernel::ConstructCartesianConstIterator_3`

*/
class CartesianConstIterator_3 {
public:

}; /* end Kernel::CartesianConstIterator_3 */

```
this leads to:

![image](https://user-images.githubusercontent.com/5223533/215779318-16eb6ed8-414f-4bae-9fa5-dd5d7d2c1900.png)

and (in Kernel_23/classKernel_1_1CartesianConstIterator__2.html)

![image](https://user-images.githubusercontent.com/5223533/215779449-d3920199-2b2a-40fb-9cbb-3a3afe97c9e6.png)

so this takes quite a bit of place on the output pages.

When we would change the code to:
```
/*!
  \ingroup PkgKernel23ConceptsFunctionObjects
  \cgalConcept

  A type representing an iterator to the Cartesian coordinates of a point
  in two dimensions.

  \cgalRefines CopyConstructible, Assignable and DefaultConstructible

  \sa `Kernel::ConstructCartesianConstIterator_2`

*/
class CartesianConstIterator_2 {
public:

}; /* end Kernel::CartesianConstIterator_2 */

/*!
  \ingroup PkgKernel23ConceptsFunctionObjects
  \cgalConcept

  A type representing an iterator to the Cartesian coordinates of a point
  in three dimensions.

  \cgalRefines CopyConstructible, Assignable and DefaultConstructible

  \sa `Kernel::ConstructCartesianConstIterator_3`

*/
class CartesianConstIterator_3 {
public:

}; /* end Kernel::CartesianConstIterator_3 */

```

We would get:

![image](https://user-images.githubusercontent.com/5223533/215779912-f6e20048-31ae-4417-a894-ce6fcadc067f.png)

and

![image](https://user-images.githubusercontent.com/5223533/215780040-03515df4-6489-4349-b127-2019a3de6318.png)

This looks, in my opinion, much better without loosing any information.

This might not only be valid for `\cgalRefines` but maybe also for `\cgalModels`, `\cgalGeneralizes` and `\cgalHasModel`

(triggered by the remark https://github.com/CGAL/cgal/pull/6950#issuecomment-1359951223 and subsequent discussion)

**Comment by afabri** [comment]
I agree that it looks better

**Comment by albert-github** [comment]
Another improvement might be to use the `\qualifier` command (but this doxygen command only works with the current master (1.9.7 (f40290be22990ddc164736c5a43352cb82cb5e29)) and newer). When we would modify the code to:
```
/*!
  \ingroup PkgKernel23ConceptsFunctionObjects
  \cgalConcept

  A type representing an iterator to the Cartesian coordinates of a point
  in two dimensions.

  \cgalRefines CopyConstructible Assignable and  DefaultConstructible
  \qualifier CopyConstructible
  \qualifier Assignable
  \qualifier DefaultConstructible

  \sa `Kernel::ConstructCartesianConstIterator_2`

*/
class CartesianConstIterator_2 {
public:

}; /* end Kernel::CartesianConstIterator_2 */
```

this would look on the Kernel_23/refines.html page the same but the page Kernel_23/classKernel_1_1CartesianConstIterator__2.html would look like:

![image](https://user-images.githubusercontent.com/5223533/215787981-7a59caf5-38ab-4b2f-b5d8-c4fb9d0fd26d.png)

compared to the situation without the `\qualifier` command:

![image](https://user-images.githubusercontent.com/5223533/215788209-ce24a387-1011-4307-af5f-1a07ec7bfac0.png)


Note the changes in the top gray bar.

It would be possible to combine this all into a new `ALIASES` like (untested):
```
cgalNewRefines{3}="\qualifier \1 ^^ \qualifier \2 ^^ \qualifier \3 ^^ \cgalRefines \1, \2 and \3"
```

(analogous for 1,2,4, ....)

**Comment by sloriot** [comment]
Related question: Why do we even have the page `refines.html` ? it is useless to me. We could change the macro 
`cgalrefines` to simply define a section in the concept page and that's it. No need of `xrefitem` IMO.

**Comment by afabri** [comment]
always with backticks

**Comment by albert-github** [comment]
I agree with @sloriot (https://github.com/CGAL/cgal/issues/7231#issuecomment-1410510464) but I think that the other points mentioned (e.g `\qualifier` and the proper use with or without backticks) should also me taken into account.

When the change regarding the backticks is agreed upon as proposed by @afabri, and I think this the better way too as it refers to "code", this has to be done at around 184 places (i.e. about 69 files).

**Comment by sloriot** [comment]
Reading qualify doc I don't see why it is what should be used. Anyway hiding all that stuff within a macro is the way to go. Implementing the macro is somehow an independent question.

**Comment by sloriot** [comment]
Thus I would not put backticks at the macro call but in the macro definition so that it is not forgotten.

**Comment by albert-github** [comment]
@sloiriot 
- I think you meant `qualifier` where you wrote `quality` or did I miss that point?
- Hiding the things in the macro is indeed the way to go

@afabri, @sloriot
- regarding the backticks we have to know whether or not the `\qualifier` command will be used or not as in case it is used the backticks have to be added in the `ALIASES` as otherwise the `\qualfier` command will show them literally as well (the argument of `\qualifier` is a string (see update  of my original `ALIASES`)).

**Comment by albert-github** [comment]
> We should start by modifying one page, look at the output and agree on that change before applying it globally.

I've just pushed a proposed patch, pull request #7236
