### ISSUE TITLE
Compilation error in examples of Algebraic_foundation

### ISSUE THREAD

**Issue by PritK99** [CGAL/cgal#7240]
## Issue Details

Compilation error in fraction_traits.cpp and implicit_interoperable_dispatch.cpp in Algebraic_foundations/examples/Algebraic_foundations.

The error arises because of use of CGAL::IO namespace with set_pretty_mode() function.

Error : 
```
[ 20%] Built target algebraic_structure_dispatch
[ 30%] Building CXX object CMakeFiles/fraction_traits.dir/fraction_traits.cpp.o
/home/prit/Desktop/cgal/Algebraic_foundations/examples/Algebraic_foundations/fraction_traits.cpp: In function ‘int main()’:
/home/prit/Desktop/cgal/Algebraic_foundations/examples/Algebraic_foundations/fraction_traits.cpp:20:15: error: ‘set_pretty_mode’ is not a member of ‘CGAL::IO’; did you mean ‘CGAL::set_pretty_mode’?
   20 |     CGAL::IO::set_pretty_mode(std::cout);
      |               ^~~~~~~~~~~~~~~
In file included from /usr/include/CGAL/IO/io.h:612,
                 from /home/prit/Desktop/cgal/Algebraic_foundations/examples/Algebraic_foundations/fraction_traits.cpp:2:
/usr/include/CGAL/IO/io_impl.h:58:1: note: ‘CGAL::set_pretty_mode’ declared here
   58 | set_pretty_mode(std::ios& i)
      | ^~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/fraction_traits.dir/build.make:76: CMakeFiles/fraction_traits.dir/fraction_traits.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:171: CMakeFiles/fraction_traits.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```
If we replace the namespace from ```CGAL::IO::set_pretty_mode(std::cout)``` to ```CGAL::set_pretty_mode(std::cout)```, the error gets resolved.

## Source Code

The issue arises in examples (fraction_traits.cpp and implicit_interoperable_dispatch.cpp) of Algebraic_foundation
Path : Algebraic_foundations/examples/Algebraic_foundations

## Environment

* Operating system : ubuntu 20.04
* Compiler: GCC 9.4.0
* CGAL version: 5.5.1
* Boost version: 1.71.0

**Comment by GilesBathgate** [comment]
Is the version of cgal in: `/home/prit/Desktop/cgal/Algebraic_foundations/examples/Algebraic_foundations/fraction_traits.cpp` the same version as in `/usr/include/CGAL/IO/io_impl.h`

**Comment by lrineau** [comment]
Never mix two versions of CGAL! Here you have one version in `/home/prit/Desktop/cgal`, probably CGAL-5.5.1 as you say, but you also have another version in `/usr/include/`, probably [version 5.0.2 from Ubuntu 20.04](https://packages.ubuntu.com/focal/libcgal-dev).

Your CMake setup is probably wrong. If you want further help, please share your file(s) `CMakeLists.txt`.
