### ISSUE TITLE
Some typos in the doc

### ISSUE THREAD

**Issue by stla** [CGAL/cgal#7242]
- [Here](https://doc.cgal.org/latest/Scale_space_reconstruction_3/classCGAL_1_1Scale__space__surface__reconstruction__3.html), `Facet_iterator` and `Facet_const_iterator`: "iterator over the points" is written => *over the facets*.

- Somewhere, I don't find where I saw that, I saw "decompisition" instead of "decomposition", two times.

And more, but do not rememeber. Now I'll note here the typos I found, so that I will not lost them. And I'll do a PR.

**Comment by albert-github** [comment]
I don't see the word `decompisition` anywhere in the current master do you have any idea about the version you saw the problem and / or the package though I think I found in Minkowski_sum_2/test/Minkowski_sum_2/test_minkowski_sum.cpp:
```
"Greene decomosition",
"Vertical decomosition"
```
so are these the ones you saw?


Note that with #7041 quite a few spelling corrections were made (and with " Spelling corrections" #7244 I created a proposed pull request with some spelling corrections)

**Comment by stla** [comment]
That's possible since I recently dealt with `Minkowski_sum_2`.

**Comment by stla** [comment]
[interiro](https://doc.cgal.org/latest/Boolean_set_operations_2/group__boolean__do__intersect.html) instead of "interior", multiple times.
