### ISSUE TITLE
`PMP::orient_to_bound_a_volume(emptyMesh)` crashes the session

### ISSUE THREAD

**Issue by stla** [CGAL/cgal#7263]
Hello,

When a mesh is empty, `CGAL::is_closed(themesh)` and `CGAL::is_triangle_mesh(themesh)` both return `true`, but `PMP::orient_to_bound_a_volume(themesh)` crashes the session.

**Comment by afabri** [comment]
So you suggest that we add the precondition  `! is_empty()` to `PMP::orient_to_bound_a_volume(themesh)` ?
Or you would prefer that we return the empty mesh.  
To be closed means not to have border edges, which is the case for an empty mesh.
Concerning the triangle mesh test, it is unfortunately true that predicates on empty sets are  often true.  There is no face that is not a triangle.

**Comment by stla** [comment]
I agree that existential predicates on a empty mesh must be true. I don't know what to suggest, but something which does not crash the session. `PMP::orient_to_bound_a_volume` is `void`, I don't think that makes sense to return something.

**Comment by stla** [comment]
> I agree that existential predicates on a empty mesh must be true. 

Sorry, `false` for existential, `true` for universal.

**Comment by afabri** [comment]
With "return the empty mesh" I mean that it just does nothing.

**Comment by stla** [comment]
Yes sorry, I finally understood later. Indeed that would be a nice option.

**Comment by afabri** [comment]
We could write test cases for all functions called with empty meshes, but I somehow would expect that you test for  empty meshes higher up in your application code as it will in most cases need extra treatment.

**Comment by stla** [comment]
This is what I do. Even if you change something I can't benefit of it, because I use the **RcppCGAL** package for R, which includes version 5.4 of CGAL (I suggested to the author to upgrade in summer, when CGAL will no longer depend on the **mpfr** library).

**Comment by afabri** [comment]
And I forgot to say thank you for the bug report.   It's appreciated.

**Comment by afabri** [comment]
Giving it another thought, I would tend to change the definition of being closed by adding that it must not be empty. Because closed somehow means separating two volumes (not thinking about self-intersections).  @sloriot do you agree?
