### ISSUE TITLE
Nef_3: e_below != SHalfedge_handle() assertion error.

### ISSUE THREAD

**Issue by GilesBathgate** [CGAL/cgal#7266]
## Issue Details

Following on the investigation in #7205  I find an example with a different exception. This time the polyhedron example is:

```c++
Polyhedron polyhedron = {{{0,0,0},{0,0,10},{0,10,10},{0,10,0},{10,10,0},{10,0,0},{10,0,10},{10,10,10},{0,0,0}},{{0,1,2,3},{1,4,5,2},{0,3,6,7},{3,2,5,6},{7,4,1,0},{6,5,4,7}}};
```

Which passes the coplanar test, but then fails with:

```
CGAL error: assertion violation!
Expression : e_below != SHalfedge_handle()
File       : /usr/include/CGAL/Nef_3/SNC_FM_decorator.h
Line       : 418
Explanation: 
Refer to the bug-reporting instructions at https://www.cgal.org/bug_report.html
terminate called after throwing an instance of 'CGAL::Assertion_exception'
  what():  CGAL ERROR: assertion violation!
Expr: e_below != SHalfedge_handle()
File: /usr/include/CGAL/Nef_3/SNC_FM_decorator.h
Line: 418
```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Linux 64bit
* Compiler: clang++ version 14.0.0
* Release or debug mode: debug
* Specific flags used (if any):
* CGAL version: master
* Boost version:  1.74.0
* Other libraries versions if used (Eigen, TBB, etc.): None

**Comment by GilesBathgate** [comment]
Also reported in #2899 and #5711

**Comment by GilesBathgate** [comment]
This additional exception is caused by self-intersecting facets which the following minimal example quad demonstrates:

```c++
Polyhedron polyhedron = {{{0,0,0},{10,0,0},{10,10,0},{0,10,0}},{{0,1,3,2}}};
```

Note the reversed indices 3 and 2.

A test for this can be written as:

```c++
bool all_facets_non_self_intersecting(const HalfedgeDS& hds) {
	for(auto h=hds.faces_begin(); h!=hds.faces_end(); ++h) {
		if(h->facet_degree()<=3) continue;
		auto b=h->facet_begin(),e(b),o(b);
		CGAL_For_all(b,e) {
			CGAL_For_all(o,e) {
				if(b==o||b->next()==o||o->next()==b||b->prev()==o||o->prev()==b) continue;
				CGAL::Segment_3<K> sb(b->vertex()->point(),b->opposite()->vertex()->point());
				CGAL::Segment_3<K> so(o->vertex()->point(),o->opposite()->vertex()->point());
				if(CGAL::do_intersect(sb,so)) return false;
			}
		}
	}
	return true;
}
```

**Comment by sloriot** [comment]
Note that the vertex (0,0,0) is duplicated and leads to an isolated vertex.

**Comment by sloriot** [comment]
Also since the mesh is self-intersecting, you should use `OFF_to_nef_3()` and not the regular constructor.

**Comment by GilesBathgate** [comment]
@sloriot Yes, I updated the code in #7205 after this and added `builder.remove_unconnected_vertices();` The self intersecting faces test does seem to be a more general solution though.

**Comment by GilesBathgate** [comment]
> Also since the mesh is self-intersecting, you should use `OFF_to_nef_3()` and not the regular constructor.

Yes as I wrote in https://github.com/CGAL/cgal/issues/7205#issuecomment-1416808374 However I want to be able to detect when to use the union of facet cycles  (OFF_to_nef_3) methodology. See the discussion https://github.com/CGAL/cgal/discussions/7268
