### ISSUE TITLE
natural_neighbor_coordinates_2 runs very slowly under linux operating system

### ISSUE THREAD

**Issue by Peng-Amos** [CGAL/cgal#7282]
Why this part of c++ code runs very slowly under linux operation system but very fast in windows? How can I do to improve the performance?
same number points 370 * 580, in linux, it takes about 22 seconds, however it takes just about 300ms in windows. I compile code both in release mode

```c++
for (int i = 0; i < numQuery; ++i) {
    K::Point_2 p(xyGrid[i * 2], xyGrid[i * 2 + 1]);
    coords.clear();
    fh = dt.locate(p, fh);
        CGAL::Triple<std::back_insert_iterator<Point_coordinate_vector>, K::FT, bool> result =
            CGAL::natural_neighbor_coordinates_2(dt, p, std::back_inserter(coords), fh);
        if (!result.third) { 
            gridZ[i] = meanVal;
        }
        else {
            norm = result.second;
            interpVal = CGAL::linear_interpolation(coords.begin(), coords.end(),
                    norm, CGAL::Data_access<Point_value_map>(values));
            gridZ[i] = interpVal;
        }
    }
```

* Operating system (Windows/Mac/Linux, 32/64 bits):  linux windows 64bits
* Compiler: gcc 5.4 and msvc2017
* Release or debug mode: release
* Specific flags used (if any): -std=c++14
* CGAL version:5.0
* Boost version:1.76

**Comment by afabri** [comment]
Did you try to compile on the Windows machine with clang as Platform Toolset?

**Comment by afabri** [comment]
And do you observe the same slowdown for other CGAL packages?
