### ISSUE TITLE
triangulate_refine_and_fair_hole not working

### ISSUE THREAD

**Issue by 9and3** [CGAL/cgal#7283]
## Issue Details

Hello CGAL community!

I am trying to fill some holes in several meshes with the wonderful `CGAL::Polygon_mesh_processing::triangulate_refine_and_fair_hole()`. **_Unfortunately for all the meshes I am trying to patch it does not close not even one hole._**

I've seen a [similar issue](https://github.com/CGAL/cgal/issues/5681) reporting the bad quality of the mesh as the source of the inefficiency of the hole filler function. This is way I cleaned out the mesh via converting the mesh back to a polygon soup ([polygon_mesh_to_polygon_soup](https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__repairing__grp.html#ga76648a509409ff3c3ad3f71eff8ce9d9)), cleaning the soup ([repair_polygon_soup](https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__repairing__grp.html#ga4a8bf46e90d0cd94e1edf7ed90d42f2f)), before converting back to a polygon mesh ([orient_polygon_soup](https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__orientation__grp.html#gaadc5bac3072b11d2313e40043c729d0a) + [polygon_soup_to_polygon_mesh](https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__repairing__grp.html#ga0dec58e8a0112791f72ebbe77bac074b)). But still no hole filling.

Please find attached 3 examples of mesh objects I am trying to patch, as well few images down below.
↓↓↓[CGAL_mesh_fill_holes_data.zip](https://github.com/CGAL/cgal/files/10808106/CGAL_mesh_fill_holes_data.zip)↓↓↓

Many thanks in advance for any help or hint you can provide! 🙌

![Screenshot from 2023-02-22 16-39-55](https://user-images.githubusercontent.com/50238678/220752812-157f56a3-632a-41ae-bcf6-e189e092fff3.png)
![Screenshot from 2023-02-22 16-39-57](https://user-images.githubusercontent.com/50238678/220752913-81c373c7-2cc4-4fcf-a1c9-8f0fbc99c105.png)
![Screenshot from 2023-02-22 16-40-14](https://user-images.githubusercontent.com/50238678/220752823-9bb81633-feb7-4ec1-8173-324a30d9c50a.png)

## Source Code
```cpp
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/Surface_mesh.h>

#include <CGAL/Polygon_mesh_processing/triangulate_hole.h>
#include <CGAL/Polygon_mesh_processing/border.h>
#include <CGAL/Polygon_mesh_processing/IO/polygon_mesh_io.h>

#include <boost/lexical_cast.hpp>

#include <CGAL/Polyhedron_3.h>
#include <CGAL/Polyhedron_items_with_id_3.h>
#include <CGAL/Polygon_mesh_processing/orient_polygon_soup.h>
#include <CGAL/Polygon_mesh_processing/polygon_soup_to_polygon_mesh.h>
#include <CGAL/Polygon_mesh_processing/polygon_mesh_to_polygon_soup.h>
#include <CGAL/Polygon_mesh_processing/repair_polygon_soup.h>

#include <CGAL/Polygon_mesh_processing/orientation.h>
#include <CGAL/IO/polygon_soup_io.h>

#include <iostream>
#include <fstream>
#include <iterator>
#include <string>
#include <tuple>
#include <vector>

typedef CGAL::Exact_predicates_inexact_constructions_kernel  K;
typedef K::Point_3                                                                                Point_3;
typedef CGAL::Surface_mesh<Point_3>                                           Mesh_srf;
typedef boost::graph_traits<Mesh_srf>::vertex_descriptor          vertex_descriptor;
typedef boost::graph_traits<Mesh_srf>::halfedge_descriptor     halfedge_descriptor;
typedef boost::graph_traits<Mesh_srf>::face_descriptor              face_descriptor;

namespace PMP = CGAL::Polygon_mesh_processing;

void fillHoles(Mesh_srf &cgalMesh)
{
  // cleaning
  std::vector<Point_3> points;
  std::vector<std::vector<std::size_t> > polygons;
  PMP::polygon_mesh_to_polygon_soup(cgalMesh, points, polygons);
  size_t nbrRmvPoints = 0;
  nbrRmvPoints = PMP::merge_duplicate_points_in_polygon_soup(points, polygons);
  PMP::repair_polygon_soup(points, polygons);
  PMP::orient_polygon_soup(points, polygons);
  Mesh_srf meshOut;
  PMP::polygon_soup_to_polygon_mesh(points, polygons, meshOut);
  cgalMesh = meshOut;

  // hole filler
  double max_hole_diam   = -1.0;
  int max_num_hole_edges = -1;
  unsigned int nb_holes = 0;
  std::vector<halfedge_descriptor> border_cycles;
  PMP::extract_boundary_cycles(cgalMesh, std::back_inserter(border_cycles));
  for(halfedge_descriptor h : border_cycles)
  {
      std::vector<face_descriptor>  patch_facets;
      std::vector<vertex_descriptor> patch_vertices;
      bool success = std::get<0>(PMP::triangulate_refine_and_fair_hole(cgalMesh,
                                                                      h,
                                                                      std::back_inserter(patch_facets),
                                                                      std::back_inserter(patch_vertices)));
      ++nb_holes;
  }
};
```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Ubuntu 22.04 LTS
* Compiler: gcc
* Release or debug mode: release
* Specific flags used (if any): /
* CGAL version: 5.5.1
* Boost version: 1.74.0.3ubuntu7
* Other libraries versions if used (Eigen, TBB, etc.): /

**Comment by stla** [comment]
Hello,

For me this feature works fine.

I tried your mesh ***piece_1.off*** and according to CGAL it has no border, hence no hole to fill.

**Comment by stla** [comment]
Also tried with VCG, same conclusion: no border.

**Comment by sloriot** [comment]
It indeed seems that all your faces are duplicated.

**Comment by stla** [comment]
I checked with VCG. @sloriot is right: all faces are duplicated. After removing the duplicates, five boundary cycles are found.

**Comment by stla** [comment]
You can read the file as a polygon soup and convert it to a polygon mesh after cleaning, then there's no duplicate face.

```cpp
std::vector<Point_3> points;
std::vector<std::vector<size_t>> faces;
std::ifstream infile;
infile.open(filename);
bool ok = CGAL::IO::read_OFF(infile, points, faces);
infile.close()
......
```

**Comment by 9and3** [comment]
Hello! Thank you so much for you feedback! :) Then it's a cleaning problem. I was wondering if the cleaning block in the code I posted shouldn't already take care of converting the mesh in polygon soup, cleaning it and re-converting it into a mesh? I mean what if we wanted to do this cleaning in memory without saving and reimporting the file with `CGAL::IO::read_OFF()`? Btw thanks a lot again for the hint!

**Comment by 9and3** [comment]
By creating the polygon soup from the start without going through mesh -> polygon soup -> cleaning -> cvt2mesh it works. Thanks for your time!
