### ISSUE TITLE
3D Mesh Generation: Is it possible to retain the domain's surface points?

### ISSUE THREAD

**Issue by citystrawman** [CGAL/cgal#7286]
_Please use the following template to help us solving your issue._

## Issue Details

I am using a surface mesh as input domain bounding and trying to generate 3D Mesh from the domain. 

The input domain bounding is an off file that has a good triangulated shape:
![image](https://user-images.githubusercontent.com/9004748/221528717-09eab1e3-4416-4cd1-a4bd-0b707a4bf91e.png)
(Actually this off file was generated from PMP::isotropic_remeshing with mesh size of 30 and constrained map)

However,  using CGAL::make_mesh_3 method resulted a mesh that looks not so perfect(the triangles are not so uniform compared to the input domain) as follows:
![image](https://user-images.githubusercontent.com/9004748/221530847-e22c63be-c467-4e20-8ed7-68ef37d637e4.png)

Is it possible to make the surface points of the 3D mesh as much close as the input domain?

## Source Code

```
#define CGAL_MESH_3_VERBOSE 1

#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/Surface_mesh.h>

#include <CGAL/Polygon_mesh_processing/intersection.h>
#include <CGAL/Polygon_mesh_processing/IO/polygon_mesh_io.h>
#include <CGAL/Polygon_mesh_processing/clip.h>

#include <CGAL/Mesh_triangulation_3.h>
#include <CGAL/Mesh_complex_3_in_triangulation_3.h>
#include <CGAL/Mesh_criteria_3.h>

#include <CGAL/Polyhedron_3.h>
#include <CGAL/Polyhedral_mesh_domain_with_features_3.h>
#include <CGAL/make_mesh_3.h>
#include <CGAL/Timer.h>

// Domain
typedef CGAL::Exact_predicates_inexact_constructions_kernel K;

typedef CGAL::Mesh_polyhedron_3<K>::type Polyhedron;

typedef CGAL::Polyhedral_mesh_domain_with_features_3<K> Mesh_domain;

typedef K::Point_3 Point;

typedef CGAL::Surface_mesh<Point> Mesh;

// Triangulation
typedef CGAL::Mesh_triangulation_3<Mesh_domain, CGAL::Default, CGAL::Sequential_tag>::type Tr;

typedef CGAL::Mesh_complex_3_in_triangulation_3<
    Tr, Mesh_domain::Corner_index, Mesh_domain::Curve_index> C3t3;

// Criteria
typedef CGAL::Mesh_criteria_3<Tr> Mesh_criteria;

// To avoid verbose function and named parameters call
using namespace CGAL::parameters;
namespace PMP = CGAL::Polygon_mesh_processing;

int main(int argc, char* argv[])
{
    std::cout.precision(17);
    std::cerr.precision(17);
    const std::string fname = (argc > 1) ? argv[1] : CGAL::data_file_path("RM-Surf.off");
    std::ifstream input(fname);
    const std::string fname2 = (argc > 2) ? argv[2] : CGAL::data_file_path("RM-Rock-SurfaceMesh.off");
    std::ifstream input2(fname2);
    Polyhedron sm, smbounding;
    input >> sm;
    input2 >> smbounding;
    if (input.fail()) {
        std::cerr << "Error: Cannot read file " << fname << std::endl;
        return EXIT_FAILURE;
    }

    PMP::clip(sm, smbounding);

    CGAL::Timer t;
    t.start();
    // Create domain
    Mesh_domain domain(sm, smbounding);

    // Get sharp features
    domain.detect_features();

    // Mesh criteria
    Mesh_criteria criteria(edge_size = 30,
        facet_angle = 25, facet_size = 30, facet_distance = 3,
        cell_radius_edge_ratio = 3, cell_size = 50);
         // Mesh generation
    C3t3 c3t3 = CGAL::make_mesh_3<C3t3>(domain, criteria,
        no_perturb(), no_exude());

    std::cerr << t.time() << " sec." << std::endl;
    // Output
    dump_c3t3(c3t3, "RM_Test_Result");

}
```
The input files and the result mesh are attached:
[TestFiles.zip](https://github.com/CGAL/cgal/files/10838377/TestFiles.zip)

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):
* Compiler:
* Release or debug mode:
* Specific flags used (if any):
* CGAL version:
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by janetournois** [comment]
Hello @citystrawman 

- in `make_mesh_3()`, the facet criterion `facet_size` is a guaranteed upper bound on surface facets sizes (resp. for `edge_size` and `cell_size),`
- in `isotropic_remeshing()`, the target edge length parameter only is a target, with no upper/lower bound guarantees, though all edge lengths empirically converge to close values
  
Moreover, the criteria `facet_distance` and `facet_shape` also cause surface facets refinement, to be satisfied (see
 [Mesh_facet_criteria_3](https://doc.cgal.org/latest/Mesh_3/classCGAL_1_1Mesh__facet__criteria__3.html) for more details).
`facet_distance` may cause stronger refinements in some regions like high-curvature regions for example.

You can change your facet criteria to try getting a more isotropic mesh, but with no guarantee.
Note that `facet_size` and `facet_distance` can be either scalar constant values or scalar fiels, such that you can for example have a very goof approximation error in flat regions and a coarser one in curved regions.

**Comment by citystrawman** [comment]
> Hello @citystrawman
> 
> * in `make_mesh_3()`, the facet criterion `facet_size` is a guaranteed upper bound on surface facets sizes (resp. for `edge_size` and `cell_size),`
> * in `isotropic_remeshing()`, the target edge length parameter only is a target, with no upper/lower bound guarantees, though all edge lengths empirically converge to close values
> 
> Moreover, the criteria `facet_distance` and `facet_shape` also cause surface facets refinement, to be satisfied (see [Mesh_facet_criteria_3](https://doc.cgal.org/latest/Mesh_3/classCGAL_1_1Mesh__facet__criteria__3.html) for more details). `facet_distance` may cause stronger refinements in some regions like high-curvature regions for example.
> 
> You can change your facet criteria to try getting a more isotropic mesh, but with no guarantee. Note that `facet_size` and `facet_distance` can be either scalar constant values or scalar fiels, such that you can for example have a very goof approximation error in flat regions and a coarser one in curved regions.

Thank you! BTW when you mention facet_shape, do you mean by Mesh_facet_topology? I did not see parameter facet_shape in [Mesh_facet_criteria_3](https://doc.cgal.org/latest/Mesh_3/classCGAL_1_1Mesh__facet__criteria__3.html)

**Comment by janetournois** [comment]
Sorry it's `facet_angle`!

**Comment by citystrawman** [comment]
> Sorry it's `facet_angle`!

Thanks! I just set facet_distance from 3 to 30 and the surface looks much more uniform. From your post can I assume that make_mesh_3() could not make the points coordinates on surface of the 3D mesh exactly the same as the input surface mesh points, but only close to it?
