### ISSUE TITLE
Potential race-condition in Triangulation_3

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#7295]
Reopened issue: see https://github.com/CGAL/cgal/issues/7295#issuecomment-1573284097.

---

This PR reveals the following error: https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.6-Ic-184/Triangulation_3/TestReport_gimeno_ArchLinux-clang.gz and it seems related to the parallel insertion with a pb with a ref counted object. I cannot reproduce it locally. @mglisse does that ring a bell?

_Originally posted by @sloriot in https://github.com/CGAL/cgal/issues/7115#issuecomment-1442913374_

**Comment by lrineau** [comment]
See also @mglisse comment https://github.com/CGAL/cgal/pull/7115#issuecomment-1443638336:
> I can reproduce, maybe once every 5 runs, with the branch, with both gcc-12 and clang-15, on debian testing x86_64. It does seem related to threading. `-fsanitize=thread` reports many issues, but if you ignore the ones in TBB, some seem to come from CGAL trying to read and write in the same place in different threads. It happens to be detected in the ref-counting code because that's one of the few places with an assertion, but most likely there is a race condition in the triangulation code (of course I can't 100% rule out a bug in the ref-counting, but that wouldn't be my first guess for a culprit).

**Comment by lrineau** [comment]
Other fact: the first occurrence of the bug was in CGAL-5.6-Ic-135. I think that is related to the PR #7115 that improves the test suite for 3D triangulations. The bug was already there but it was not detected.

I have a fix, and I am preparing the PR for `5.4.x-branch`... Stay tuned.

**Comment by lrineau** [comment]
This issue is a release blocker, but it can wait for 5.6 final version. We can publish 5.6-beta1 without the fix.

**Comment by lrineau** [comment]
Fixed by https://github.com/CGAL/cgal/pull/7448

**Comment by lrineau** [comment]
I reopen the issue.


> @lrineau I saw this error today: https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.6-Ic-261/Triangulation_3/TestReport_lrineau_Ubuntu-Latest.gz
> Looks very much to the original issue reported

_Originally posted by @sloriot in https://github.com/CGAL/cgal/issues/7448#issuecomment-1568773546_


I am a bit stuck with that issue. I can reproduce, but very rarely: about one 1 over 100 times. And I have issue with TBB, that catches the assertion to rethrow it in the main thread. That scrambles the backtrace.

**Comment by MaelRL** [comment]
Fixed with https://github.com/CGAL/cgal/pull/7496?

**Comment by lrineau** [comment]
> Fixed with #7496?

That is right. Let's close this issue.

A race-condition is still possible (see the new issue https://github.com/CGAL/cgal/issues/4660) but all those occurrences we have seen so far are most likely fixed by #7496.
