### ISSUE TITLE
Surface_mesh_deformation

### ISSUE THREAD

**Issue by xiaodongdong101** [CGAL/cgal#7302]
CGAL warning: check violation!
Expression : last_preprocess_successful
File       : D:\vcpkg\installed\x64-windows\include\CGAL\Surface_mesh_deformation.h
Line       : 1215
Explanation:
Refer to the bug-reporting instructions at https://www.cgal.org/bug_report.html
Error in preprocessing, check documentation of preprocess()

**Comment by MaelRL** [comment]
Please use the template provided for issues: the information described in there is required to be able to understand and fix the problem. With your current report, it is impossible to do anything.
