### ISSUE TITLE
CGAL::Surface_mesh<P>::join is not documented

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#7317]
In latest CGAL-5.5.2, in the documentation of the class `CGAL::Surface_mesh`, the method [`join`](https://doc.cgal.org/latest/Surface_mesh/classCGAL_1_1Surface__mesh.html#a60816a7febffcddc9c0043977379e1d7) is mentioned but without a documentation.

**Comment by albert-github** [comment]
Note: same accounts for the function `resize` as well (just above the `join`), `collect_garbage (a bit down), the `operator=` ...
