### ISSUE TITLE
why slender triangle occurs?

### ISSUE THREAD

**Issue by StromanStroman** [CGAL/cgal#7318]
why slender triangle occurs?

I use 
```
PMP::extract_boundary_cycles
```
to get holes in my mesh.
I use
```
bool success = std::get<0>(PMP::triangulate_refine_and_fair_hole(resultMesh,
			border_cycles.at(index),
			std::back_inserter(patch_facets),
			std::back_inserter(patch_vertices),
			CGAL::parameters::density_control_factor(1)));
```
to fill the hole.
I got a slender triangle finally.
The hole as you see below
![屏幕截图 2023-03-10 095529](https://user-images.githubusercontent.com/13552268/224234898-5de21618-f65b-4368-ac5a-f64bf53cd754.png)

The patch as you see below
![屏幕截图 2023-03-10 095554](https://user-images.githubusercontent.com/13552268/224234907-783eb9b8-fb07-46aa-abae-adcf97c91d3f.png)

How to get a normal patch?

Language:C++
Compiler:VS2022 community
Operation System:Windows 11

**Comment by afabri** [comment]
Might be a similar problem to #7181.   Can you put the mesh somewhere please.

**Comment by lrineau** [comment]
@StromanStroman You never answered Andreas'question (https://github.com/CGAL/cgal/issues/7318#issuecomment-1463383833). I close the issue. If eventually you reply, we will reopen the issue.
