### ISSUE TITLE
How could CGAL::Polygon_with_holes_2 have not accessible holes?

### ISSUE THREAD

**Issue by mptangtang** [CGAL/cgal#7326]
How could CGAL::Polygon_with_holes_2 have not accessible holes?

## Issue Details

When I was using Polygon with holes offered by CGAL. Some error happens during the program is running. When I use debug mode with QtCreator 9. I found a strong error. I looked into the variables that might be related to. I noticed that the member variable m_holes in Polygon_with_holes_2. It is in a status "not accessible". Since m_holes is not defined as a pointer. I can not understand in which circumstances would this variable be not accessible? It is difficult for me to figure out the error.  The error happens in the following figure.  

![image](https://user-images.githubusercontent.com/42928638/224671877-4e3889b9-c225-45b5-8e88-0420bd0077ae.png)

## Source Code
I tried to rebuild the error with a simple one. But since this error happens randomly. I haven't figure out the way to find the data that trigger the error. I am also not sure that I have locate the exact error position in my program.

## Environment

* Operating system (Ubuntu 22.04, 64 bits):
* Compiler: g++ 11.3.0
* Release or debug mode: Debug
* Specific flags used (if any):
* CGAL version: 5.5.2
* Boost version: 1.76.0
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by MaelRL** [comment]
It could be that you are trying to inspect the polygon at a time where the member is not yet initialized (or some issue with qt creator).

Could you please post the code as well as the error you get, instead?
