### ISSUE TITLE
CDT_2 bug

### ISSUE THREAD

**Issue by soesau** [CGAL/cgal#7328]
## Issue Details

I get an exception without message in Lazy.h:452 when adding a specific constraint to a copy of a CDTPlus_2 with a few points and a few constraints.
Inserting the constraint into the original instance works. The constraint can either be inserted with the already used vertex_handles or as new points. When using handles instead of Point_2 an assertion fails (Polyline_constraint_hierarchy_2.h:428) instead of a raised exception.

When the same code is applied to a CDT_2 instead of a CDTPlus_2 it works, but in debug mode the following message is given:

Refer to the bug-reporting instructions at https://www.cgal.org/bug_report.html
CGAL warning: check violation!
Expression : false
File       : C:\dev\cgal\Triangulation_2\include\CGAL/Constrained_triangulation_2.h
Line       : 1100
Explanation: You are using an exact number type,
using a Constrained_triangulation_plus_2 class
would avoid cascading intersection computation
 and be much more efficient
This message is shown only if CGAL_NO_CDT_2_WARNING is not defined.

## Source Code

https://gist.github.com/soesau/e982d54f3059a0544b6dfce6aef3ebd3

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows 10
* Compiler: MSVC 2022
* Release or debug mode: both
* Specific flags used (if any):
* CGAL version: master
* Boost version: 1.80
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by afabri** [comment]
You cannot call insert with vertex handles as they live in the first triangulation.

**Comment by soesau** [comment]
That makes sense. The problem remains, for the first insert.
