### ISSUE TITLE
Plane to plane intersection looks wrong

### ISSUE THREAD

**Issue by maquemo** [CGAL/cgal#7333]
When trying to calculate a plane to plane intersection with the below input, the origin point for the resulting line looks wrong:

Input: plane1: (origin=(0, 0, -6), normal vector=(1, 4, -1)), plane2:(origin(0, 0, 4), normal vector(1, -2, 1))

The point p=(5, 0, -1) is a known point that it is on the resulted intersecting line of the two planes so the next assert should be true:
   ```c++
    gte::Vector3<double> vA{ 1.0, 4.0, -1.0 };
    gte::Normalize(vA);
    gte::Vector3<double> vB{ 1.0, -2.0, 1.0 };
    gte::Normalize(vB);

    gte::Plane3<double> A{ vA, 6.0 };
    gte::Plane3<double> B{ vB, 4.0 };

    gte::FIQuery<double, gte::Plane3<double>, gte::Plane3<double>> query;

    const auto result = query(A, B);

    assert(gte::Length(gte::Cross((gte::Vector3<double>{ 5, 0, -1 } - result.line.origin), result.line.direction)) < 0.0000001);
```
but it fails. The direction of the intersection line is ok, it is only the origin line.

![image](https://user-images.githubusercontent.com/64633912/225386617-cef88efd-4e5b-4c69-8113-3361253d2ffa.png)

In the image the point B is the returned origin point for the intersection.

**Comment by sloriot** [comment]
Seems that the code posted use GTE and not CGAL. Did you post that code to show something or is it a post in the wrong github repo?

**Comment by maquemo** [comment]
Yes, I have just realized of that. I am very sorry.
