### ISSUE TITLE
issues with typedef in CGAL

### ISSUE THREAD

**Issue by Resacd** [CGAL/cgal#7340]
I am using CGAL 5.5.2 in my project. I download the zip file and extracted it. Then I included the path of include folder into the visual studio project. As far as this version is only header files. I'm not including anything else in C++ or linker part in visual studio. The headers are included correctly but when defining typedef CGAL::Exact_predicates_inexact_constructions_kernel Kernel I get the error saying there is no member Exact_predicates_inexact_constructions_kernel  in CGAL. for the next typedef CGAL::Polyhedron_3<Kernel> Polyhedron_3 the error is qualified name is not allowed. the next typedef Polyhedron_3::Vertex_handle Vertex_handle giving the error named followed by:: must be class or name space. 

```c++
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/Polyhedron_3.h>

typedef CGAL::Exact_predicates_inexact_constructions_kernel Kernel;
typedef CGAL::Polyhedron_3<Kernel> Polyhedron_3;
typedef Polyhedron_3::Vertex_handle Vertex_handle;
typedef Polyhedron_3::Facet_iterator Facet_iterator;

int main() {
    // Create a polyhedron
    Polyhedron_3 polyhedron;

    // ...
    return 0;
}
```
Thanks for your help in advance.

**Comment by Resacd** [comment]
Yes, I did.

**Comment by sloriot** [comment]
So you get CGAL working with vcpkg but not with a zip you download yourself? If the include directives do not produce any error but only the typedef then it means that either you are already in CGAL namespace or that the include macros are already defined but I don't see why it would produce such an error. You should try to ask visual studio/code to open the header file directly from the example you are trying to compile and see if you can find `Exact_predicates_inexact_constructions_kernel` in the header.
