### ISSUE TITLE
CGAL's FindTBB.cmake creates target TBB::tbb

### ISSUE THREAD

**Issue by mglisse** [CGAL/cgal#7349]
## Issue Details

In another program that uses CGAL we have the issue that in cmake, `if(TARGET TBB::tbb)` returns true even though TBB is not present on this system, causing the build to fail. That seems wrong.

We can work around it by `find_package(TBB CONFIG)` (we don't mind not supporting old TBB versions). Is that considered safe with respect to CGAL's use of TBB?

## Source Code
CMakeLists.txt
```cmake
cmake_minimum_required(VERSION 3.8)
project(Plouf)
find_package(TBB)
if (TARGET TBB::tbb)
  message("yes")
else()
  message("no")
endif()
```
```sh
cmake . -DCMAKE_MODULE_PATH=/usr/local/lib64/cmake/CGAL
```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): linux 64
* Compiler: gcc
* CGAL version: 5.4.1
* Other libraries versions if used (Eigen, TBB, etc.): CMake 3.16.2, no TBB

**Comment by lrineau** [comment]
We should ship a more recent version of `FindTBB`, like that one: https://github.com/NVIDIA/thrust/blob/9f1cddc62b1bebbaeb8d07d4476c285be5aa0adc/thrust/cmake/FindTBB.cmake#L110-L122

**Comment by mglisse** [comment]
There is still a suspicious `add_library(TBB::${TARGET_NAME} UNKNOWN IMPORTED)`, I don't know if it would fix this issue.
