### ISSUE TITLE
CGAL Hole Filling does not work on specific mesh

### ISSUE THREAD

**Issue by Maksimo007** [CGAL/cgal#7354]
## Issue Details

Currently I am trying to fill holes (undersides of objects) on various meshes (reconstruction of real objects). This has worked well so far, but now I have a reconstruction on which this does not work, although boundary edges have been recognised. In the following picture the boundary edges are marked in green.

![mesh_hole](https://user-images.githubusercontent.com/16197626/228542885-63c9b1b3-595c-43cd-b707-bee110a90152.PNG)

This is the mesh:
[mesh.zip](https://github.com/CGAL/cgal/files/11101068/mesh.zip)

I would appreciate any help since I don't know if I am doing something wrong or it is a bug.

## Source Code

```
int main(int argc, char* argv[])
{
    CGAL::Surface_mesh<CGAL::Simple_cartesian<double>::Point_3> CGAL_mesh;

    CGAL::IO::read_OBJ("mesh.obj", CGAL_mesh);
    unsigned int nb_holes = 0;
    std::vector<halfedge_descriptor> border_cycles;
    CGAL::Polygon_mesh_processing::extract_boundary_cycles(CGAL_mesh, std::back_inserter(border_cycles));
    for (halfedge_descriptor h : border_cycles)
    {
        std::vector<face_descriptor>  patch_facets;
        std::vector<vertex_descriptor> patch_vertices;
        CGAL::Polygon_mesh_processing::triangulate_and_refine_hole(CGAL_mesh,
            h,
            std::back_inserter(patch_facets),
            std::back_inserter(patch_vertices));
        std::cout << "* Number of facets in constructed patch: " << patch_facets.size() << std::endl;
        std::cout << "  Number of vertices in constructed patch: " << patch_vertices.size() << std::endl;
        ++nb_holes;
    }
    std::cout << std::endl;
    std::cout << nb_holes << " holes have been filled" << std::endl;
    CGAL::IO::write_OBJ("filled.obj", CGAL_mesh);
}
```

This is the output of the code above:
`* Number of facets in constructed patch: 0
  Number of vertices in constructed patch: 0

1 holes have been filled`

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows 64 bits
* Compiler: MSVC
* Release or debug mode: Release
* Specific flags used (if any): -
* CGAL version: 5.5.1
* Boost version: 1.81.0
* Other libraries versions if used (Eigen, TBB, etc.): Eigen, PCL with VTK

**Comment by sloriot** [comment]
You have degenerate elements on the boundary. Calling `CGAL::PMP::remove_degenerate_faces()` before doing the hole filling worked for me.

**Comment by Maksimo007** [comment]
Oh yes, you're right. Thank you so much!
