### ISSUE TITLE
Union operation on Nef_polyhedron failing

### ISSUE THREAD

**Issue by juergenboehm** [CGAL/cgal#736]
For a certain computation with CGAL (4.7), package Nef_polyhedron (Kernel EPEC), I form the union of a large number of Nef_polyhedron_3 objects N1,...,Nk. Every Nj is a (not necessarily convex) polyhedron with 14 faces, and Nj is created from a Polyhedron_3 Pj with varying vertices, but fixed topology. All Nj are simple (Nj.is_simple() is always true). Now I often get errors on doing the union (operator+ on Nef_polyhedron_3)

```
Nef_polyhedron_3 Ntotal, Ni
....    
Ntotal = Ntotal + Ni

```
A typical error is for example

```
terminate called after throwing an instance of 'CGAL::Assertion_exception'
  what():  CGAL ERROR: assertion violation!
Expr: G.mark(v1,0)==G.mark(v2,0)&& G.mark(v1,1)==G.mark(v2,1)
File: /usr/local/include/CGAL/Nef_S2/SM_overlayer.h
Line: 300

```
There are other errors too, but the core of the problem is the failing of the boolean + operation on certain Nef polyhedra N1 + N2 where N2 is simple and N1 is the union of simple Nef polyhedra.

Unfortunately I could not produce a short example for this error, so I attach a file renderstl.tar.zip
[renderstl.tar.zip](https://github.com/CGAL/cgal/files/117416/renderstl.tar.zip)
.
It must be unpacked, then, in the unpacked directory renderstl, compiled as a qmake application and executed by ./renderstl (no arguments).

The program reads the attached file model.scad and tries to produce model.stl (but fails).

**Comment by juergenboehm** [comment]
I investigated the problem a bit more on my own, because I suspected that the problem is on my side, because openjscad also produced render errors for the model.scad included in the above .zip file.

The main point is the following: Every elementary polyhedron Ni, that is united to a big Nef_polyhedron is of the following form: Take A, B, C, three vertices of a triangle in space. Consider directed line segments lA, lB, lC of length h which have A, B, C respectively as their midpoints. Call A', B', C' the respective points at the beginnings of lA, lB, lC and A'', B'', C'' the respective points at the ends of lA, lB, lC. It is clear, that for certain choices of lA, lB, lC the points A', B', C' or A'', B'', C'' can lie "irregular" with respect to A, B, C. Especially triangle t(A', B', C') can have a different orientation as triangle t(A,B,C). It might even happen, that A', B', C' are collinear.

Now the polyhedron I consider is formed of the vertices A',B',C', A, B, C, A'', B'', C''. It has "upper" and "lower" bounding triangle t(A'',B'',C'') and t(A',B',C') and additionally 12 faces grouped in 3 classes corresponding to the midpoints P,Q,R of AB, BC, CA and formed of A'PA'', A'PB', B'PB'', A''PB'' and similarly for Q and R. (Three pyramids "open at the base" with four triangles as boundary). Now I noticed that errors occur, when A', B', C' or A'', B'', C'' lie "badly" with respect to A,B,C which can happen, when lA, lB, lC are chosen "badly". Although errors also occur for triangles that seem "innocent" by the tests I have added, I suspect, that more thorough tests would reveal anomalies for them too. So it seems the problem is - at least in a great part of the cases - on my side.

**Comment by sloriot** [comment]
OK, let us know if we can close the ticket. Your test is running right now on my machine (no error for now).
You should probably use `is_valid()` each calls and catch the first test failing. Then export the Nef polyhedra into files.

**Comment by juergenboehm** [comment]
The test does not halt on errors, as I used try{}catch(...){} blocks in openscad.cpp around the critical calls to CGAL. Nevertheless the errors occur (at least for me).

**Comment by sloriot** [comment]
It generates a empty file.

**Comment by lrineau** [comment]
This issue can probably be closed. It has been stalled for a while.

**Comment by Shen001** [comment]
i get the same problem with CGAL（4.7），A is simple and B is simple ；but A+B is not simple ；how to convert those nef_polyhedron to polygon（maybe open~）?

**Comment by sloriot** [comment]
@Shen001 you better open a new issue and possibly link the current one to avoid your question to be forgotten.
I think you can use the function [convert_nef_polyhedron_to_polygon_soup()](https://doc.cgal.org/latest/Nef_3/group__PkgNef3IOFunctions.html#ga28a9eb4da0cd6153f0c16f7f9eaf6665). Then you can use [is_polygon_soup_a_polygon_mesh()](https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__repairing__grp.html#ga8b9d12d817b5cc76f5a42d74eac75bf3) and all polygon soup funtions to safely get something out of the soup.

**Comment by Shen001** [comment]
@sloriot thanks a lot for your reply，i will try new version~
