### ISSUE TITLE
Examples: Missed files "meshes/cross_quad.off" and "meshes/beam.off"

### ISSUE THREAD

**Issue by alekseYY** [CGAL/cgal#7362]
## Issue Details

The user manual for the package "3D Boolean Operations on Nef Polyhedra" contains an example "draw_nef_3.cpp" (in the Chapter 5.7). It compiles OK, however it can't run because there are **no data files** "meshes/cross_quad.off" and "meshes/beam.off" anywhere in the directory hierarchy.

## Source Code (from the CGAL documentation)

    #include <CGAL/Exact_predicates_exact_constructions_kernel.h>
    #include <CGAL/Nef_polyhedron_3.h>
    #include <CGAL/Polyhedron_3.h>
    #include <CGAL/draw_nef_3.h>
    #include <fstream>
    #include <iostream>
    typedef CGAL::Exact_predicates_exact_constructions_kernel   Kernel;
    typedef CGAL::Polyhedron_3<Kernel>                          Polyhedron;
    typedef CGAL::Nef_polyhedron_3<Kernel>                      Nef_polyhedron;
    int main(int argc, char *argv[])
    {
      // read OFF file into a polyhedron
      Polyhedron P1, P2;
      std::ifstream ifs1((argc > 1) ? argv[1] : CGAL::data_file_path("meshes/cross_quad.off"));
      ifs1 >> P1;
      std::ifstream ifs2((argc > 1) ? argv[1] : CGAL::data_file_path("meshes/beam.off"));
      ifs2 >> P2;
      // initialize nef from polyhedron
      Nef_polyhedron N1(P1);
      Nef_polyhedron N2(P2);
      // draw Nef Polyhedron
      CGAL::draw(N1-N2);
      return EXIT_SUCCESS;
    }

## Environment

* Operating system: Ubuntu 20.04.6 LTS
* Compiler: g++ 10.3.0
* Release or debug mode: Debug
* Specific flags used (if any):
* CGAL version: 5.5
* Boost version: 1.71.0
* Other libraries versions if used (Eigen, TBB, etc.): Qt 5.12.8

**Comment by albert-github** [comment]
I saw the files in the repository as:
- Data/data/meshes/cross_quad.off
- Data/data/meshes/beam.off

and in the code the data_file_path is set based in the environment variable `CGAL_DATA_DIR`

- did you set the environment variable `CGAL_DATA_DIR`?
- do you see the files as indicated?

**Comment by alekseYY** [comment]
@albert-github - thank you, I've found these files in the tar-file, it was my fault, incomplete installation of examples/demos.
