### ISSUE TITLE
clang warning in Rotation_tree_2.h

### ISSUE THREAD

**Issue by stla** [CGAL/cgal#7372]
Hello,

I submitted a R package to CRAN and they found the following warning with clang 16:

```
CGAL/Partition_2/Rotation_tree_2.h:81:7: warning: ignoring return value of function declared with 'nodiscard' attribute [-Wunused-result]
      std::unique(this->begin(), this->end(),equal);
```

They don't accept this warning (there are other ones, screens and screens with clang USBAN).

CGAL version 5.4.

[Here is a temporary link](https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-fedora-clang/cgalPolygons-00install.html) to the full report.

**Comment by lrineau** [comment]
That warning was a legit bug. It has been fixed by #6935, see https://github.com/CGAL/cgal/pull/6935/files#diff-ed12eb157ca70d0afcf381017b577366ee957b51f9bc852129e1bcef1584dfdf.

The patch first appeared in CGAL-5.4.4 and CGAL-5.5.2. Please update the version of CGAL.
