### ISSUE TITLE
Segmentation fault during drawing a 3D Nef polyhedron

### ISSUE THREAD

**Issue by alekseYY** [CGAL/cgal#7377]
## Issue Details

I've tried to draw a 3D Nef polyhedron from the Section 5.6 of the User Manual for the "3D Boolean Operations on Nef Polyhedra" and got the segmentation fault. The problem is in the "draw_nef_3.h" header, function is "compute_elements". Are there any limitations on the input data for drawing?  

## Source Code

    #include <fstream>
    #include <iostream>

    #define CGAL_USE_BASIC_VIEWER

    #include <CGAL/Exact_integer.h>
    #include <CGAL/Extended_homogeneous.h>
    #include <CGAL/Nef_polyhedron_3.h>
    #include <CGAL/IO/Nef_polyhedron_iostream_3.h>
    #include <CGAL/draw_nef_3.h>

    using Kernel = CGAL::Extended_homogeneous<CGAL::Exact_integer>;
    using Nef_polyhedron = CGAL::Nef_polyhedron_3<Kernel>;

    int main()
    {
      Nef_polyhedron N;
      // ------ the input data correspond to the 'Nef_3/extended_kernel.cpp'
      // ------ example from the Section 5.6 of the User Manual   
      std::ifstream fs("data/extended_kernel.cin");
      if (fs >> N)
      {
        std::cout << "File loaded" << std::endl;
        CGAL::draw(N);
      }
      else
      {
         std::cout << "ERROR!!!" << std::endl;
      }
    }

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Linux 64-bit
* Compiler: G++ 10.3.0
* Release or debug mode: Debug
* Specific flags used (if any): -no-pie -ggdb -O0
* CGAL version: 5.5.2
* Boost version: 1.71.0
* Other libraries versions if used (Eigen, TBB, etc.): Qt 5.12.8

**Comment by gdamiand** [comment]
The pach above seems to solve the bug; but maybe with this code, the object is not drawn correctly.

**Comment by alekseYY** [comment]
In the CGAL 6.0 there are no segmentation fault during drawing. However the picture, corresponding to the file "extended_kernel.cin", looks weird (please see below). It seems to me that `Extended_homogeneous` is still a problem for the `draw` function.

![Screenshot_2024-10-19_23-36-56](https://github.com/user-attachments/assets/0d188d97-ccfe-454c-bcd8-7b4de7a5a23d)

**Comment by alekseYY** [comment]
@lrineau - I still see the picture, which I posted here on October 19, 2024, **in the 6.0.1 version.** May be, it makes sense to reopen this issue and rework the 3D Nef drawing code?

Please see also the #9010 issue, which also about this type of drawing.

Thanks!
