### ISSUE TITLE
Generate a coplanar 3D mesh element

### ISSUE THREAD

**Issue by citystrawman** [CGAL/cgal#7389]
_Please use the following template to help us solving your issue._

## Issue Details

This is a continuation for issue  #7387.

I generated a 3D mesh successfully, but when I imported the mesh into FLAC3D, and tried to solve it, I got an error saying:
![image](https://user-images.githubusercontent.com/9004748/232447105-319f837b-ba7b-416b-b20e-19c0889968dc.png)
Thus I checked element(in this example, tetrahedra) No.159465, and found it is a coplanar tetrahedra:
![image](https://user-images.githubusercontent.com/9004748/232447588-17546f90-fa22-4f94-be97-a6e37380cf0f.png)

I am not sure if there're any solution to this.

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):
* Compiler:
* Release or debug mode:
* Specific flags used (if any):
* CGAL version:
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by afabri** [comment]
Did you do any optimization, e.g. sliver exudation to get rid of almost flat cells?

**Comment by citystrawman** [comment]
@afabri using exude() works.
