### ISSUE TITLE
Improvement of layout of model relations.

### ISSUE THREAD

**Issue by albert-github** [CGAL/cgal#7395]
After successful implementation of the adjusted documentation approach for refines (see #7236 and #7231), it would also be good to have a look at other possible candidates, especially the `\cgalHasModel` and `\cgalModel`. like in Algebraic_foundations/classFieldNumberType.html:

![image](https://user-images.githubusercontent.com/5223533/232797555-9edb6c91-4d5d-4afd-a646-c2920126a700.png)

and in the "treeview" the part:
![image](https://user-images.githubusercontent.com/5223533/232798752-c20a9246-8f36-4db6-b6ae-11b10dc786f5.png)

The questions that arise:
1. would this be useful, in my opinion YES
2. in general types in "Has Model" should appear in "code" format (so between backticks) should "simple" types like "float" and "double" also appear here in "code" format
3. should `Has Model Relationships` appear in the "treeview"
4. should `Is Model Relationships` appear in the "treeview"

**Comment by albert-github** [comment]
Any comments?

**Comment by sloriot** [comment]
I 100% agree to do the same thing, it is useless in my opinion to have such pages and even more in the treeview.

**Comment by albert-github** [comment]
As a start I've just pushed a proposed patch, pull request #7576 for the `AABB_tree` so the results can be checked on "problems" before implementing it with the other packages.
