### ISSUE TITLE
[Barycentric_coordinates_2] unreachable link

### ISSUE THREAD

**Issue by albert-github** [CGAL/cgal#7404]
In the html output Barycentric_coordinates_2/index.html there is a link to:

https://www.anisimovdmitry.com/assets/files/phd_thesis_anisimov.pdf

though this link is not reachable / the side cannot be found.
- is there an alternative link?
- maybe the phd thesis should be on a CGAL server as well.

**Comment by albert-github** [comment]
Thanks.

Good to have that link, question remain should this link be used or will the phd theses be located at a CGAL server as well

**Comment by afabri** [comment]
I think the institute is a good place.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #7408
