### ISSUE TITLE
Conflict of definitions between x11 and Boost (Complex)

### ISSUE THREAD

**Issue by Maximus0079** [CGAL/cgal#7425]
First of all your work is huge ! thanks to everybody !!! I'm a fan !

But here is an issue :

I'm trying to use CGAL scale_space_reconstruction with my project that uses Vulkan (so x11). It's a single source draft program with the simplest structure.
When I tried to implement directly in my source the Scale_space_reconstruction_3/scale_space_advancing_front.cpp example, a conflict arose between the x11's Complex definition and Boost's Complex.
Using undef wasn't conclusive at all, so I tried to isolate the reconstruction into a static library, included and linked CGAL only there.
The conflict of names disappeared but showed up a
    CGAL ERROR: precondition violation!
    Expr: points.begin() != points.end()
from reconstruction.increase_scale<Smoother>()
When I comment that line to pass directly to reconstruct.reconstruct_surface(Mesher()) "not 3D" error appeared and no facets computed at all.
It's been days of searching in vain. Hoping it has something to do with static library, and even if the context of the issue [Failure when compiling with static libs #7192](https://github.com/CGAL/cgal/issues/7192) is not quite the same, I tried what Lrineau suggested in it, but still the same errors.

So if a Samaritin resolved this Complex issue with x11 & boost, or know how to build a working static library with CGAL I'd be grateful to read it.

Thanks in advance

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): ubuntu64
* Compiler: gcc 11.3.0
* Release or debug mode: debug
* Specific flags used (if any): -O2 -Wall -funsigned-char -fPIC
* CGAL version: 5.4.1
* Boost version: 1.74
* Other libraries versions if used (Eigen, TBB, etc.): Eigen_3.4.0-2

**Comment by sloriot** [comment]
What is the error message you are having with boost and x11? about the precondition, it is because the point set provided is empty. Maybe the path to the file is wrong?

**Comment by Maximus0079** [comment]
Here is the x11/Boost conflict

`[build] FAILED: CMakeFiles/vulkanRPLidar.dir/vulkanRPLidar.cpp.o 
[build] /usr/bin/g++ -DBOOST_ALL_NO_LIB -DCGAL_USE_GMPXX=1 -I/home/max/Dev/vulkanRPLidar-CMake-old/dependencies/include -I/home/max/Dev/vulkanRPLidar-CMake-old/dependencies/src -O2 -Wall -funsigned-char -fPIC -g -frounding-math -MD -MT CMakeFiles/vulkanRPLidar.dir/vulkanRPLidar.cpp.o -MF CMakeFiles/vulkanRPLidar.dir/vulkanRPLidar.cpp.o.d -o CMakeFiles/vulkanRPLidar.dir/vulkanRPLidar.cpp.o -c /home/max/Dev/vulkanRPLidar-CMake-old/vulkanRPLidar.cpp
[build] In file included from /usr/include/X11/Xlib.h:44,
[build]                  from /home/max/Dev/vulkanRPLidar-CMake-old/vulkanRPLidar.h:27,
[build]                  from /home/max/Dev/vulkanRPLidar-CMake-old/vulkanRPLidar.cpp:1:
[build] /usr/include/boost/math/tools/roots.hpp:793:16: error: expected identifier before numeric constant
[build]   793 | template<class Complex, class F>
[build]       |                ^~~~~~~
[build] /usr/include/boost/math/tools/roots.hpp:793:16: error: expected ‘>’ before numeric constant
[build] /usr/include/boost/math/tools/roots.hpp:794:1: error: expected unqualified-id before numeric constant
[build]   794 | Complex complex_newton(F g, Complex guess, int max_iterations = std::numeric_limits<typename Complex::value_type>::digits)
[build]       | ^~~~~~~`
And that is when all the inclusions are in the same source.

Otherwise yes, the points set have been verified. I even thought it was because of my points coming from the lidar, so I tried with the file kitten.off exactly as in the example, and still that "not 3D"

**Comment by sloriot** [comment]
`boost/math/tools/roots.hpp` is not included by CGAL itself so the issue does not seem related to CGAL. Maybe you can try to isolate the include directives in different compilation unit, only exposing a high level API.

About the assertion, you did not give the corresponding file. I checked all CGAL files and in all cases it means that the input point set is empty. Could you provided the stack of call in gdb, it might be that it is a function call from another CGAL function.

**Comment by afabri** [comment]
Ideally YOU provide a minimal program that we can compile locally in order to reproduce.

**Comment by mglisse** [comment]
> I'm trying to use CGAL scale_space_reconstruction with my project that uses Vulkan (so x11).

AFAIK, for X11, Vulkan can use either Xlib (and its X.h header that defines a gazillion macros) or the more modern XCB.

**Comment by afabri** [comment]
To come back to the minimal example. Please put on gist.github.com (1)  scale.cpp  with the reconstruction code and put that in a static library, and (2) main.cpp that calls the library function, plus (3) the CMakeLists.txt to build everything.  When we can reproduce, we can think about a fix.

**Comment by Maximus0079** [comment]
Shame on me ... wanted to do too much...

**Comment by Maximus0079** [comment]
Those kind of mistakes that makes me hide somewhere deep ...

Really sorry for everybody's time !!!!

:-(

**Comment by pentacular** [comment]
The simplest mistakes are often the hardest to see.

**Comment by afabri** [comment]
Don't worry. But at least you now you understand my "request".

**Comment by Maximus0079** [comment]
So true, and so sweat giving when those are found @pentacular 
^.^'
@afabri , this little excursion teach me great lessons about minimalism, indeed ^.^

I should close this issue. Big thx !
