### ISSUE TITLE
Method and origin of "oriented_side" for point in polygon?

### ISSUE THREAD

**Issue by j2kun** [CGAL/cgal#7428]
Hi there, I am doing some research for a book, and I'm interested to know the method that CGAL uses for computing whether a point is contained in a (possibly non-simple) polygon.

I am finding the source code quite difficult to navigate, so I am wondering if someone reading this could point me to the right place.  I believe the method is `oriented_side`, and from there eventually found `Arrangement_on_surface_2/include/CGAL/Arr_point_location/Arr_simple_point_location_impl.h`, but from reading that I suspect (but am not 100% confident) that the overall method is based on a winding number approach as in https://en.wikipedia.org/wiki/Point_in_polygon#Winding_number_algorithm

Could someone with expertise here confirm or refute this? If it is not this algorithm, could you provide a quick overview of the method and where it originated? Thanks!

**Comment by afabri** [comment]
The inside test for a `Polygon_2`  uses the odd/even rule as explained [here](https://doc.cgal.org/latest/Polygon/group__PkgPolygon2Functions.html#ga0cbb36e051264c152189a057ea385578).   And the precondition is that the polygon is simple.

**Comment by afabri** [comment]
Can you close the issue, in case that was the answer.
