### ISSUE TITLE
Alpha Wrap Example - Compilation issues on Windows

### ISSUE THREAD

**Issue by mariuszhermansdorfer** [CGAL/cgal#7432]
## Issue Details

I'm trying to compile Cgal examples on Windows and even though the process completes without errors, the resulting executables don't run. 

Specifically, the [Alpha Wrap 3](https://github.com/CGAL/cgal/tree/master/Alpha_wrap_3/examples/Alpha_wrap_3) examples return the following error message:
![image](https://user-images.githubusercontent.com/49192999/236801630-3af570a2-0ef3-46c7-92fc-2c3696e46809.png)

Calling Alpha Wrap in the following line causes the issue:
https://github.com/CGAL/cgal/blob/4798b1da0d53d629f4e7f2e00aec405130048c3c/Alpha_wrap_3/examples/Alpha_wrap_3/triangle_mesh_wrap.cpp#L55

Below you can find the log from cmake:

```
Selecting Windows SDK version 10.0.22000.0 to target Windows 10.0.19045.
The C compiler identification is MSVC 19.34.31937.0
The CXX compiler identification is MSVC 19.34.31937.0
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.34.31933/bin/Hostx64/x64/cl.exe - skipped
Detecting C compile features
Detecting C compile features - done
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.34.31933/bin/Hostx64/x64/cl.exe - skipped
Detecting CXX compile features
Detecting CXX compile features - done
Visual Leak Detector (VLD) is not found.
Using header-only CGAL
Targetting Visual Studio 17 2022
Target build environment supports auto-linking
Using VC toolset 143.
Generator uses intermediate configuration directory: $(Configuration)
Boost include dirs: C:/devl/boost_1_82_0
Boost libraries:    
Configuring done
Generating done
```

## Environment

* Operating system (Windows 64 bits):
* Compiler: MSVC
* Release or debug mode: any
* Specific flags used (if any):
* CGAL version: 5.5.2
* Boost version: 1.82.0
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by lrineau** [comment]
`0xc000007b` means missing DLLs. Most probably the DLLs exist on your machine but the dynamic loader of Microsoft Windows does not know where. Make sure the GMP and MPFR DLLs are in a directory pointed by the `PATH` environment variable. Or copy them in the same directory as your executable `triangle_mesh_wrap.exe`.

**Comment by mariuszhermansdorfer** [comment]
Thanks @lrineau!
Copying `libgmp-10.dll` & `libmpfr-4.dll` to the same directory as the executable file solved the issue.

Appreciate your prompt response!
