### ISSUE TITLE
The Polygonal Surface Reconstruction algorithm run failed

### ISSUE THREAD

**Issue by yywd6** [CGAL/cgal#7433]
_Please use the following template to help us solving your issue._

## Issue Details
I'm using the the example of Reconstruction with User-Provided Planes  from CGAL's"Polygonal_surface_reconstruction/polyfit_example_user_provided_planes.cpp", I have split point cloud planes, each plane with different color information（PCD format）.Then I converted it to the  ply format according to the source code, The properties of the converted ply file are given below, but the program will report an exception when running, please how can I solve this problem?

##Ply file
My converted ply file is here ： [ply.zip](https://github.com/CGAL/cgal/files/11431216/ply.zip)

![V@I$(SR13AFBOZ~WA`HDEU1](https://user-images.githubusercontent.com/101700971/237053368-33942b1b-91a4-4572-8872-40f734eabb15.png)

The place circled in the image below will be abnormal
![6D1~OU9UJR8_TPMX_N50D5M](https://user-images.githubusercontent.com/101700971/237053407-186dea2c-dec0-4981-9f61-3f003733a1f5.png)
![8 O CNK{EKN8X(@YZ4J8A0G](https://user-images.githubusercontent.com/101700971/236838087-e1588f57-0c36-46ce-8282-409b12bad4b3.png)
![60_1JVKGMFRRZ{7R_)2L%1P](https://user-images.githubusercontent.com/101700971/237052290-b3548bd3-5958-4621-bae0-c565ac4ebe57.png)

## Source Code

```c++
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/IO/read_points.h>
#include <CGAL/property_map.h>
#include <CGAL/Surface_mesh.h>
#include <CGAL/Polygonal_surface_reconstruction.h>
//#define CGAL_USE_SCIP  // defined (or not) by CMake scripts, do not define by hand
/*#include <CGAL/SCIP_mixed_integer_program_traits.h>
typedef CGAL::SCIP_mixed_integer_program_traits<double>*/                        //MIP_Solver;
#define CGAL_USE_GLPK  // defined (or not) by CMake scripts, do not define by hand
#include <CGAL/GLPK_mixed_integer_program_traits.h>
typedef CGAL::GLPK_mixed_integer_program_traits<double>                        MIP_Solver;


#include <CGAL/Timer.h>
#include <fstream>
typedef CGAL::Exact_predicates_inexact_constructions_kernel                Kernel;
typedef Kernel::Point_3                                                                                        Point;
typedef Kernel::Vector_3                                                                                Vector;
typedef        CGAL::Polygonal_surface_reconstruction<Kernel>                        Polygonal_surface_reconstruction;
typedef CGAL::Surface_mesh<Point>                                                                Surface_mesh;
// Point with normal, and plane index
typedef boost::tuple<Point, Vector, int>                                                PNI;
typedef CGAL::Nth_of_tuple_property_map<0, PNI>                                        Point_map;
typedef CGAL::Nth_of_tuple_property_map<1, PNI>                                        Normal_map;
typedef CGAL::Nth_of_tuple_property_map<2, PNI>                                        Plane_index_map;
/*
* The following example shows the reconstruction using user-provided
* planar segments stored in PLY format. In the PLY format, a property
* named "segment_index" stores the plane index for each point (-1 if
* the point is not assigned to a plane).
*/
int main(int argc, char* argv[])
{
    const std::string input_file = ("output.ply");
    std::ifstream input_stream(input_file.c_str());
    std::vector<PNI> points; // store points
    std::cout << "Loading point cloud: " << input_file << "...";
    CGAL::Timer t;
    t.start();
    if (!CGAL::IO::read_PLY_with_properties(input_stream,
        std::back_inserter(points),
        CGAL::make_ply_point_reader(Point_map()),
        CGAL::make_ply_normal_reader(Normal_map()),
        std::make_pair(Plane_index_map(), CGAL::PLY_property<int>("segment_index"))))
    {
        std::cerr << "Error: cannot read file " << input_file << std::endl;
        return EXIT_FAILURE;
    }
    else
        std::cout << " Done. " << points.size() << " points. Time: " << t.time() << " sec." << std::endl;
    std::cout << "Generating candidate faces...";
    t.reset();
    Polygonal_surface_reconstruction algo(
        points,
        Point_map(),
        Normal_map(),
        Plane_index_map()
    );
    std::cout << " Done. Time: " << t.time() << " sec." << std::endl;
    Surface_mesh model;
    std::cout << "Reconstructing...";
    t.reset();
    if (!algo.reconstruct<MIP_Solver>(model)) {
        std::cerr << " Failed: " << algo.error_message() << std::endl;
        return EXIT_FAILURE;
    }
    // Saves the mesh model
    const std::string& output_file("user_provided_planes_result.off");
    if (CGAL::IO::write_OFF(output_file, model))
        std::cout << " Done. Saved to " << output_file << ". Time: " << t.time() << " sec." << std::endl;
    else {
        std::cerr << " Failed saving file." << std::endl;
        return EXIT_FAILURE;
    }
    return EXIT_SUCCESS;
}

```

## Environment

* Operating system (Windows 64 bits):
* Compiler: VS2019
* debug mode
* CGAL version: 5.5.2 
* Boost version: 1.82.0#1

**Comment by esgn** [comment]
You should share the ply file you used (not a screenshot) for other people to reproduce the error and eventually help you solve your issue.

**Comment by yywd6** [comment]
> You should share the ply file you used (not a screenshot) for other people to reproduce the error and eventually help you solve your issue.

Thank you very much for your reply, I have added the file in，
[ply.zip](https://github.com/CGAL/cgal/files/11431231/ply.zip)

**Comment by soesau** [comment]
The segment_index in your ply file is starting from 1. However, the method expects the first plane to be at index 0. Points that do not belong to a plane should have an index -1.

So if you just decrement the segment_index for all your points in your file by 1, it should work.

**Comment by afabri** [comment]
@yywd6 does that solve your issue?
