### ISSUE TITLE
Polyhedron_3 with is_closed() false but no border edges

### ISSUE THREAD

**Issue by pss959** [CGAL/cgal#7442]
## Issue Details

According to the doc, `Polyhedron_3::is_closed()` "returns true if there are no border edges." Therefore, I have to assume that if `is_closed()` returns false, there must be border edges. I have a case where this is not true.

I.e., this code:
```
        std::cerr << "Polyhedron_3:\n";
        std::cerr << " is_valid:              " << poly.is_valid() << "\n";
        std::cerr << " is_closed:             " << poly.is_closed() << "\n";
        std::cerr << " vertex count:          " << poly.size_of_vertices()  << "\n";
        std::cerr << " halfedge count:        " << poly.size_of_halfedges() << "\n";
        std::cerr << " facet count:           " << poly.size_of_facets() << "\n";
        std::cerr << " border edge count:     " << poly.size_of_border_edges() << "\n";
        std::cerr << " border halfedge count: " << poly.size_of_border_halfedges() << "\n";
```
produces:

```
Polyhedron_3:
 is_valid:              1
 is_closed:             0
 vertex count:          45
 halfedge count:        256
 facet count:           84
 border edge count:     0
 border halfedge count: 0
```

Is this a bug or is there some missing/incorrect info in the doc? I can provide more specifics, but I thought I'd ask the general question first.

Follow-up: if this is not a bug, is there any way I can find out what is causing my polyhedron to be considered not closed?

Thanks!

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Linux 64-bit 6.2.0-20-generic
* Compiler: g++
* Release or debug mode: release
* CGAL version: 5.5.1-2
* Boost version: 1.74.0-18.1ubuntu3

**Comment by afabri** [comment]
Can you pleaade share the data set and a minimal example program to reproduce and fix.

**Comment by sloriot** [comment]
You have to call [`normalize_border()`](https://doc.cgal.org/latest/Polyhedron/classCGAL_1_1Polyhedron__3.html#a6ca5eddcfe19c5b69a500f39a0bfdbe5) so that edges are reordered and put at the end of the range. That is in the doc of [`size_of_border_edges()`](https://doc.cgal.org/latest/Polyhedron/classCGAL_1_1Polyhedron__3.html#a1a1dbed72ce1b001446dd3ce25155d30).
