### ISSUE TITLE
Library issue with matlab.

### ISSUE THREAD

**Issue by iPsych** [CGAL/cgal#7452]
_Please use the following template to help us solving your issue._

## Issue Details

When set up matlab library path in .bashrc, calling compiled cgal library have an issue.

`ImportError: /home/ipsych/SimNIBS-4.0/simnibs_env/lib/python3.9/site-packages/simnibs/mesh_tools/cgal/create_mesh_surf.cpython-39-x86_64-linux-gnu.so: undefined symbol: __gmpq_add
`

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Ubuntu 18.04 LTS

**Comment by afabri** [comment]
Is this related to the [SimNIBS Project](https://github.com/simnibs/simnibs)? Then you should maybe file your issue there.   It looks as if GMP (libGMP.so maybe) was not found on your machine.
