### ISSUE TITLE
Consistency of BigO notations

### ISSUE THREAD

**Issue by albert-github** [CGAL/cgal#7454]
In the proposed pull request #7453 the BigO notation has been made consistent in the Barycentric_coordinates_2 package.

A quick search reveals that there are in other packages also usages of the BigO notation that are not properly shown, a quick search gave: [big_O.txt](https://github.com/CGAL/cgal/files/11506873/big_O.txt) (this file might contain a number of false positives as they are in non doxygen comment blocks)

- should all the BigO notations in doxygen comments be shown as formulas like `\f$O(n)\f$` ?

As a side note / question a number of comment blocks are starting like `/*{\Mimplementation`, do they have a deeper meaning?

**Comment by albert-github** [comment]
Any comments ?

**Comment by sloriot** [comment]
I think it should even be a macro. About the comment, I guess it is probably for an old system that is not used anymore.

**Comment by sloriot** [comment]
maybe @afabri knows more about the pattern `/*{\M`

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #7571

**Comment by albert-github** [comment]
Code of #7571 has been integrated in master on GitHub, closing issue
