### ISSUE TITLE
Polygon Soup Not Closing to Form a Bounded Volume Due to Low Accuracy

### ISSUE THREAD

**Issue by FuzhangHe** [CGAL/cgal#7458]
## Issue Details

I'm having an issue with a vector of triangles represented as a polygon soup. This polygon soup is saved in a float accuracy format and I am attempting to calculate its bounded volume. However, the polygon soup does not close as expected, and this seems to be primarily caused by the low accuracy of the points.

The triangles are saved as an .off file.[resultIntersect.off](https://gist.github.com/FuzhangHe/e9eb840a5bd16f4a339883b5028dc066#file-resultintersect-off)

### Steps to reproduce:

1. Convert the triangles into cgal polygon soup;
2. Cleaned the polygon soup using the ([repair_polygon_soup](https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__repairing__grp.html#ga4a8bf46e90d0cd94e1edf7ed90d42f2f));
3. Converting it to a polygon mesh ([orient_polygon_soup](https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__orientation__grp.html#gaadc5bac3072b11d2313e40043c729d0a) + [polygon_soup_to_polygon_mesh](https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__repairing__grp.html#ga0dec58e8a0112791f72ebbe77bac074b)); 
4. Do the hole filling with [triangulate_refine_and_fair_hole()
](https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__hole__filling__grp.html#ga16473e4861b13d1241edee68f596b153), by using code in the example [hole_filling_example_SM](https://doc.cgal.org/latest/Polygon_mesh_processing/Polygon_mesh_processing_2hole_filling_example_SM_8cpp-example.html).

Despite following the mentioned steps, the resulting surface mesh is not closed.

## Source Code

The example [hole_filling_example_SM](https://doc.cgal.org/latest/Polygon_mesh_processing/Polygon_mesh_processing_2hole_filling_example_SM_8cpp-example.html) 

```
// Convert the triangles to cgal polygon soup
        std::vector<Custom_point> points;
        std::vector<CGAL_Polygon> polygons;

        std::map<pos3, std::size_t> index_map;
        std::size_t next_index = 0;

        for (const triangle3& t : newTris)
        {
            std::array<pos3, 3> vertices = { t.v0, t.v1, t.v2 };
            polygons.push_back({});
            for (const pos3& v : vertices)
            {
                auto it = index_map.find(v);
                if (it == index_map.end())
                {
                    // New point, add it to the points vector and the index map
                    points.push_back(v.to_custom_point());
                    index_map[v] = next_index++;
                }
                polygons.back().push_back(index_map[v]);
            }
        }
        std::cout << "Before reparation, the soup has " << points.size() << " vertices and " << polygons.size() << " faces" << std::endl;

// Now, repair and orient the polygon soup, and convert it to a mesh
        PMP::repair_polygon_soup(points, polygons, CGAL::parameters::geom_traits(Array_traits()));
        Mesh mesh;
        PMP::orient_polygon_soup(points, polygons);
        PMP::polygon_soup_to_polygon_mesh(points, polygons, mesh);

        std::cout << "Mesh has " << num_vertices(mesh) << " vertices and " << num_faces(mesh) << " faces" << std::endl;

// Hole filling
        unsigned int nb_holes = 0;
        std::vector<halfedge_descriptor> border_cycles;
        // collect one halfedge per boundary cycle
        PMP::extract_boundary_cycles(mesh, std::back_inserter(border_cycles));
        for (halfedge_descriptor h : border_cycles)
        {
            std::vector<face_descriptor>  patch_facets;
            std::vector<vertex_descriptor> patch_vertices;
            bool success = std::get<0>(PMP::triangulate_refine_and_fair_hole(mesh,
                h,
                std::back_inserter(patch_facets),
                std::back_inserter(patch_vertices)));
            std::cout << "* Number of facets in constructed patch: " << patch_facets.size() << std::endl;
            std::cout << "  Number of vertices in constructed patch: " << patch_vertices.size() << std::endl;
            std::cout << "  Is fairing successful: " << success << std::endl;
            ++nb_holes;
        }

// Check if mesh closed
        bool doesMeshClose2 = CGAL::is_closed(mesh);
        if (doesMeshClose2) {
            std::cout << "Mesh is closed" << std::endl;
        }
        else {
            std::cout << "Oh Nein!" << std::endl;
        }

```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):Windows
* Compiler: Visual Studio
* Release or debug mode: debug 
* Specific flags used (if any): no
* CGAL version: 5.2.1
* Boost version: 1.80.0
* Other libraries versions if used (Eigen, TBB, etc.): eigen3:x64-windows                                3.4.0#2

**Comment by MaelRL** [comment]
If the issue is mostly due to float accuracy, I would suggest snapping together points with a very small distance bound and then using [PMP::stitch_borders()](https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__repairing__grp.html#ga693b0922fe6c518f36c23f3eec15c15d).

Hole filling can only fill a hole made of a single border, not bridge a gap between different connected components.

**Comment by FuzhangHe** [comment]
Thanks for the answer.
I implied the function _PMP::stitch_borders(mesh)_, but the mesh is still not closed.

**Comment by MaelRL** [comment]
Did you perform any snapping beforehands?

**Comment by FuzhangHe** [comment]
I'm not certain if any snapping procedure has been implemented beforehand.

Perhaps a bit more background information would be helpful. The resultant polygon soup is derived from a plan-based boolean operation, not from the CGAL corefinement boolean operation, but rather from a different algorithm. This particular algorithm conducts the boolean operation by breaking down the mesh into a polygon soup and employing homogeneous integer coordinates. The outcome of this boolean operation is a polygon soup set with float accuracy. In physical terms, this polygon soup should form a closed volume.

What I am trying to do, is to connect the polygon soup and calculate the bounded volume.

**Comment by pentacular** [comment]
The point is that the vertices may have drifted slightly apart due to floating point error.

To fix this you can have nearby vertices agree on a precise location.

If you can do this correctly, then the polygon soup should become coherent.

**Comment by FuzhangHe** [comment]
I tried to snap the vertices together with following code:

**Data Structure:**
```
struct pos3 {
    float x, y, z;

    Eigen::Vector3f to_vector3f() const {
        return Eigen::Vector3f(x, y, z);
    }
};

struct idx_triangle {
    int i0, i1, i2;
};
```

**Merge Vertices and Update index_triangle:**

      std::vector<pos3> newVertices;
      std::map<int, int> oldToNewIndex;
      std::vector<idx_triangle> newIndices;
      for (int i = 0; i < vertsA.size(); ++i) {
          const pos3& vertex = vertsA[i];
          bool isCloseToExisting = false;

          // Check if this vertex is close to any vertex in the new vector
          for (int j = 0; j < newVertices.size(); ++j) {
              if (distance(vertex, newVertices[j]) < 0.005) {
                  isCloseToExisting = true;
                  oldToNewIndex[i] = j;
                  break;
              }
          }

          // If it's not close to any, add it to the new vector
          if (!isCloseToExisting) {
              newVertices.push_back(vertex);
              oldToNewIndex[i] = newVertices.size() - 1;
          }
      }

      // Create the new indices
      
      for (const idx_triangle& triangle : trisA) {
          idx_triangle newTriangle;
          newTriangle.i0 = oldToNewIndex[triangle.i0];
          newTriangle.i1 = oldToNewIndex[triangle.i1];
          newTriangle.i2 = oldToNewIndex[triangle.i2];
          newIndices.push_back(newTriangle);
      }


After this step, I cannot convert the triangles (polygon soup) to polyhedron_3 mesh and get the following message
 "Input soup needs to define a valid polygon mesh! See is_polygon_soup_a_polygon_mesh() for further information."

Do you have any idea how to do this correctly?

**Comment by FuzhangHe** [comment]
Hallo @MaelRL 

The function alpha_warp_3 works, but it takes about 4 seconds to get the desired accuracy.

Also I found the [snap_vertices.h](Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Snapping/snap_vertices.h), can I use it to snap the vertices?
Does the "snap_all_vertices" help, can you please explain how I can use it?
Especially how can I define the ToleranceMap, can I just give a value like 0.001?
