### ISSUE TITLE
erroneous claim in 1st example of spherical triangulation

### ISSUE THREAD

**Issue by stla** [CGAL/cgal#7475]
Hello,

 In [this example](https://doc.cgal.org/latest/Triangulation_on_sphere_2/Triangulation_on_sphere_2_2triang_on_sphere_proj_8cpp-example.html), the line 
```cpp
std::cout << dtos.number_of_faces() << " solid faces\n";
```
prints ***6 solid faces***.

This example is also in the [user manual](https://doc.cgal.org/latest/Triangulation_on_sphere_2/index.html#Section_2D_ToS_Ex_Project).

This is not true, [number_of_faces()](https://doc.cgal.org/latest/Triangulation_on_sphere_2/classCGAL_1_1Triangulation__on__sphere__2.html#af858392dd142c5f7b024f4b4f1c6bb11) includes the ghost faces (this is written in the doc and I checked).

**Comment by lrineau** [comment]
Fixed by the merge of PR #7477.
