### ISSUE TITLE
Error with Periodic 3d triangulation (DIVE code)

### ISSUE THREAD

**Issue by elenaferg** [CGAL/cgal#7479]
While using the public code DIVE (published in github), which uses the library https://github.com/CGAL/cgal/blob/master/Periodic_3_triangulation_3/include/CGAL/Periodic_3_triangulation_3.h, I get the following error:

terminate called after throwing an instance of 'CGAL::Assertion_exception'
what():  CGAL ERROR: assertion violation! 
Expr: (domain().ymin() <= p.y()) && (p.y() < domain().ymax()) 
File: /usr/local/include/CGAL/Periodic_3_triangulation_3.h 
Line: 2855 

I've already checked the range of the y coordinates and they are between the domain. What could be the problem?

**Comment by MaelRL** [comment]
Please provide more data: code, or at least the periodic domain and the points you are inserting.

**Comment by elenaferg** [comment]
I can't upload the catalogue I'm trying to use because it's 1.7 GiB. It consists of 24 million points in the range 0-2000. The code is this one: https://github.com/cheng-zhao/DIVE I use as -u flag 2000 (the upper limit of x,y,z ranges).

**Comment by MaelRL** [comment]
Can you dump the coordinates of the point that is problematic? Note this is a strict upper bound for the domain's max: if your point has `y = 2000`, it'll trigger the assertion.

**Comment by elenaferg** [comment]
I don't know which is the problematic point, honestly. I wrote a code in order to find the minimum and maximum values of my (x,y,z) points and all of them are between (0,2000).

**Comment by MaelRL** [comment]
You can get the position of the point by running the program within a debugger and printing the values once the assertion has halted the program.

**Comment by elenaferg** [comment]
I'm running the code on a ssh server and I'm not an expert, so I'm not sure how to debug in ssh

**Comment by elenaferg** [comment]
I've tried with more files and still get the same error. With each file I get the error with different dimensions, I mean with some files I get the error:

(domain().xmin() <= p.x()) && (p.x() < domain().xmax())

And with other files I get the error:

(domain().zmin() <= p.z()) && (p.z() < domain().zmax())


I only get this error in the ssh server, but I've never gotten this type of error in my pc. Any clue of what could be happening?

**Comment by elenaferg** [comment]
As I've already said, the code I use is DIVE: https://github.com/cheng-zhao/DIVE.  I've just upload one of the .txt in which i get errors in my drive, here's the link: https://drive.google.com/file/d/1OkXDNiN7tOxhi5r8_0z4WkoLtNw_HvYK/view?usp=sharing

In addition, I've checked the coordinates of my catalogue and each coordinate is between the domaing [0,2000], so that can't be the problem.

**Comment by MaelRL** [comment]
> In addition, I've checked the coordinates of my catalogue and each coordinate is between the domaing [0,2000], so that can't be the problem.

Again, the canonical domain is open in its upper part, so you need coordinates in `[0; 2000[`, not `[0; 2000]`.

If I grep your file, I find many occurrences of `2.000000000000000000e+03`, hence your assertion failure.

This probably needs to be more user-friendly, I'll open a separate issue.
