### ISSUE TITLE
Geometrical segmentation (vertical & horizontal) on 3D mesh

### ISSUE THREAD

**Issue by HripsimeS** [CGAL/cgal#7482]
@benlaurie @marv @chgans @drewish @bo0ts 

Hello. I would appreciate if you inform me if there is a way with CGAL to do a segmentation of horizontal and vertical mesh. To get horizontal mesh one color and other color for vertical mesh. I look forward to hearing from you and thanks in advance!

**Comment by afabri** [comment]
for all triangles of the mesh compute the normal.   If  the x and y component are 0 it is a horizontal triangle.

**Comment by HripsimeS** [comment]
@afabri thank you for your quick reply. If possible, can you please send a python scrip for that computation?

**Comment by afabri** [comment]
ask chatgpt.   just kidding.   But you expect a little bit too much.
