### ISSUE TITLE
`Precondition_exception` during computation of delaunay triangulation

### ISSUE THREAD

**Issue by jsangmeister** [CGAL/cgal#7483]
## Issue Details

I'm generating random delaunay triangulations for my masters thesis and sometimes the triangulation fails with the following `CGAL::Precondition_exception`:
```
terminate called after throwing an instance of 'CGAL::Precondition_exception'
  what():  CGAL ERROR: precondition violation!
Expr: orientation(f->vertex(i)->point(), f->vertex(cw(i))->point(), mirror_vertex(f,i)->point()) == RIGHT_TURN && orientation(f->vertex(i)->point(), f->vertex(ccw(i))->point(), mirror_vertex(f,i)->point()) == LEFT_TURN
File: /usr/include/CGAL/Triangulation_2.h
Line: 1171
```
I tried to find pattern for the error, but could not really come up with one. Some observations:
- The error only happens when the points have large enough coordinates. For coordinates less than ~250, I did not observe the error.
- If the error occurs, it occurs during the first few points (~10).

And example which generates the error above is the following instance:
```
{{12, 85}, {99, 268}, {214, 74}, {69, 35}, {282, 44}}
```
Adding these points in that order one after another to the triangulation triggers the error upon trying to add the last point.

I then went ahead and tried to find a pattern behind it all and scanned a large area for the last point to see if the error would occur or not. The result is the following (very interesting) distribution:
![delaunay](https://github.com/CGAL/cgal/assets/33004050/39e393d2-cb93-4b02-a96b-244a4d531372)

Blue is the current triangulation of the first four points, red are all points which result in the error. All white (non-marked) points give the correct result, as far as I tested it.

## Source Code
```
#include <CGAL/Cartesian.h>
#include <CGAL/Delaunay_triangulation_2.h>

typedef CGAL::Cartesian<int> K;
typedef CGAL::Delaunay_triangulation_2<K> Delaunay;
typedef K::Point_2 Point;

int main() {
    Delaunay dt;
    for (auto p : std::vector<Point> {{12, 85}, {99, 268}, {214, 74}, {69, 35}, {282, 44}}) {
        dt.insert(p);
    }
    return 0;
}
```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Arch Linux 64bit
* Compiler: c++
* Release or debug mode: Debug
* Specific flags used (if any): -
* CGAL version: 5.5.2-1
* Boost version: 1.81.0-3
* Other libraries versions if used (Eigen, TBB, etc.): -

**Comment by afabri** [comment]
Use `CGAL::Exact_predicates_inexact_constructions_kernel`

**Comment by MaelRL** [comment]
The construction of Delaunay triangulations is based on a numbers of predicates (orientation / in-circle tests), and if you use a kernel like `Cartesian` that does not provide exact versions of these predicates, there is no guarantee on whether it will produce a correct result (or even finish).
