### ISSUE TITLE
CGAL::Polyhedron_incremental_builder_3<HDS>:: lookup_halfedge(): input error: facet 2 shares a halfedge from vertex 2 to vertex 1 with facet 1.

### ISSUE THREAD

**Issue by wujingweb** [CGAL/cgal#7495]
_Please use the following template to help us solving your issue._
I met this bug, is there someone know how to fix it?
## Issue Details
CGAL::Polyhedron_incremental_builder_3<HDS>::
lookup_halfedge(): input error: facet 2 shares a halfedge from vertex 2 to vertex 1 with facet 1.
_Describe your issue. Please be specific (compilation error, runtime error, unexpected behavior, wrong results, etc.)._

## Source Code
	STL2OFF2("tmp.off", centerline_input_surface);
	// 提取骨骼
	std::ifstream input("tmp.off");
	Polyhedron tmesh;
	input >> tmesh;
_If your issue arises by using CGAL in your own source code, please provide a minimalist example that we can compile easily to reproduce the bug. If your issue arises from using a CGAL program (demo, example, etc.), please let us know which one. Helping you solving an issue is much easier and efficient if we can reproduce it._

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):
* Compiler:
* Release or debug mode:
* Specific flags used (if any):
* CGAL version:5.5.2
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by sloriot** [comment]
You input mesh is most probably invalid. Using the function [`CGAL::IO::read_polygon_mesh()`](https://doc.cgal.org/latest/BGL/group__PkgBGLIOFct.html#ga49f5b5e6fbfcbfaaac7604c88e10915c), you should get `false` returned. You can try the function [`CGAL::Polygon_mesh_processing::IO::read_polygon_mesh()`](https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__IO__grp.html) that will in addition try to apply some combinatorial repair operations.

**Comment by wujingweb** [comment]
> You input mesh is most probably invalid. Using the function [`CGAL::IO::read_polygon_mesh()`](https://doc.cgal.org/latest/BGL/group__PkgBGLIOFct.html#ga49f5b5e6fbfcbfaaac7604c88e10915c), you should get `false` returned. You can try the function [`CGAL::Polygon_mesh_processing::IO::read_polygon_mesh()`](https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__IO__grp.html) that will in addition try to apply some combinatorial repair operations.

Okay, I'll give it a try now

**Comment by wujingweb** [comment]
> You input mesh is most probably invalid. Using the function [`CGAL::IO::read_polygon_mesh()`](https://doc.cgal.org/latest/BGL/group__PkgBGLIOFct.html#ga49f5b5e6fbfcbfaaac7604c88e10915c), you should get `false` returned. You can try the function [`CGAL::Polygon_mesh_processing::IO::read_polygon_mesh()`](https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__IO__grp.html) that will in addition try to apply some combinatorial repair operations.

use [CGAL::Polygon_mesh_processing::IO::read_polygon_mesh()](https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__IO__grp.html) and duplicate_non_manifold_vertices(), 
the output is like this:
0 non-manifold occurrence(s)
0 vertices have been added to fix mesh manifoldness
but the bug 
CGAL::Polyhedron_incremental_builder_3<HDS>::
lookup_halfedge(): input error: facet 2 shares a halfedge from vertex 2 to vertex 1 with facet 1.
also exist。

**Comment by sloriot** [comment]
Please share the input and a minimal example I can compile and run so that I can reproduce the issue.

**Comment by wujingweb** [comment]
> Please share the input and a minimal example I can compile and run so that I can reproduce the issue.

	std::ifstream input("tmp.off");
	Polyhedron tmesh;
	input >> tmesh;
	//if (!CGAL::is_triangle_mesh(tmesh)) {
	//	std::cout << "Input geometry is not triangulated." << std::endl;
	//	return ;
	//}

	//std::cout << "Input mesh is triangulated." << std::endl;

	std::cout << "Number of vertices: " << tmesh.size_of_vertices() << std::endl;
	std::cout << "Number of edges: " << tmesh.size_of_halfedges() / 2 << std::endl;
the file tmp.off in https://github.com/wujingweb/cgal_bug

**Comment by sloriot** [comment]
There is no usage of `PMP::IO::read_polygon_mesh()` in your example.

**Comment by wujingweb** [comment]
> There is no usage of `PMP::IO::read_polygon_mesh()` in your example.

i used to create a demo with my tmp.off ,code from 
https://doc.cgal.org/latest/Polygon_mesh_processing/Polygon_mesh_processing_2manifoldness_repair_example_8cpp-example.html#a6
then output:
0 non-manifold occurrence(s)
0 vertices have been added to fix mesh manifoldness

**Comment by sloriot** [comment]
I'm puzzled. If that example worked then there is no bug and you can use the PMP read function instead of operator>> (that requires the input mesh to be manifold, which is not the case of your input, leading to an assertion). Am I missing something?

**Comment by wujingweb** [comment]
> I'm puzzled. If that example worked then there is no bug and you can use the PMP read function instead of operator>> (that requires the input mesh to be manifold, which is not the case of your input, leading to an assertion). Am I missing something?

you are right, i use PMP::IO::read_polygon_mesh("tmp.off", tmesh) instead input >> ,and it's works.
