### ISSUE TITLE
Useless #include in the iterative authalic parameterizer example

### ISSUE THREAD

**Issue by stla** [CGAL/cgal#7507]
Hello, 

In [this example](https://doc.cgal.org/latest/Surface_mesh_parameterization/Surface_mesh_parameterization_2iterative_authalic_parameterizer_8cpp-example.html), there's a useless `#include`:

```cpp
#include <CGAL/Surface_mesh_parameterization/Square_border_parameterizer_3.h>
```

Moreover there's a comment in the code which is not very understandable:

```cpp
Border_parameterizer border_parameterizer; // the border parameterizer will automatically compute the corner vertices
```

What are the corner vertices? The UV-space is a disk. Maybe the author intended to use the useless `#include`?

**Comment by lrineau** [comment]
Fix by the merge of PR https://github.com/CGAL/cgal/pull/7531 in `5.5.x-branch`.
