### ISSUE TITLE
Iterative authalic parameterizer automatically writes an OFF file

### ISSUE THREAD

**Issue by stla** [CGAL/cgal#7509]
Hello,

I've just run an iterative authalic parameterization, with a code similar to the one of [the example](https://doc.cgal.org/latest/Surface_mesh_parameterization/Surface_mesh_parameterization_2iterative_authalic_parameterizer_8cpp-example.html), and then an OFF file `last_solve.off` has been written in the current directory. This file contains the UV coordinates with a zero third coordinate:

```
OFF
4901 9700 0
0.5 0.5 0
0.507106 0.499547 0
0.507064 0.499102 0
......
```

I looked at the doc and didn't see anything about this automatic file. That's why I think this is not normal.

**Comment by afabri** [comment]
Thank you for pointing out.  It was already fixed by [this commit](https://github.com/CGAL/cgal/commit/001f9b8c43236f904672091b1739986c15b4ddce)
