### ISSUE TITLE
polyhedron can not read a .off file

### ISSUE THREAD

**Issue by wxh158849067wxh** [CGAL/cgal#7514]
_Please use the following template to help us solving your issue._

## Issue Details

i use fstream to read a file construct a polyhedron ,the file is  i used meshlab (a open source software) import a .obj file and export the .off file, but  CGAL said that facet 7477 has fewer than 3 vertices. besides that it also said that at vertex 3893 a closed surface already exists and facet 7476 is nonetheless adjacent.
             The closed cycle of facets is: 7445 7430 7441 7444.
at last, i read the file and construct nefpolyhedron CAGL said "check violation!"
but meshlab can read it and display it ,could you please explain this for me?

## Source Code

        Polyhedron p;
	Nef_polyhedron N3;
	std::fstream file("C:\\Users\\CSU\\Desktop\\tmp.off");
	file >> N3;

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):
* Compiler:
* Release or debug mode:
* Specific flags used (if any):
* CGAL version:
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by wxh158849067wxh** [comment]
thank u very much ,i have read file with CGAL::OFF_to_nef_3,but there is a mistake in CGAL_assertion, below is souce code where failure happened,   header file is Sphere_segment.h
Sphere_segment_rep(const Point& p1, const Point& p2, const Circle& c) :
  ps_(p1), pt_(p2), c_(c)
{ CGAL_assertion(c.has_on(p1)&&c.has_on(p2)); }
are there some mistakes in my .off file? 
besides that ,why i can not read file (like file>>polyhedron) construct a polyhedron either, below is feedback:
CGAL::Polyhedron_incremental_builder_3<HDS>::
add_vertex_to_facet(): input error: disconnected facet complexes at vertex 1528:
           involved facets are: 3067 2968 2931 3015 3066 (closed cycle) and.

Polyhedron_scan_OFF<Traits>::
operator()(): input error: facet 3068 has fewer than 3 vertices.

 thank you very much

**Comment by wxh158849067wxh** [comment]
> thank u very much ,i have read file with CGAL::OFF_to_nef_3,but there is a mistake in CGAL_assertion, below is souce code where failure happened, header file is Sphere_segment.h
Sphere_segment_rep(const Point& p1, const Point& p2, const Circle& c) :
ps_(p1), pt_(p2), c_(c)
{ CGAL_assertion(c.has_on(p1)&&c.has_on(p2)); }
are there some mistakes in my .off file?
besides that ,why i can not read file (like file>>polyhedron) construct a polyhedron either, below is feedback:
CGAL::Polyhedron_incremental_builder_3::
add_vertex_to_facet(): input error: disconnected facet complexes at vertex 1528:
involved facets are: 3067 2968 2931 3015 3066 (closed cycle) and.

Polyhedron_scan_OFF::
operator()(): input error: facet 3068 has fewer than 3 vertices.

thank you very much

**Comment by sloriot** [comment]
If you want a precise answer, please provide a complete minimal example that we can compile, run and that shows the issue you encounter.

**Comment by wxh158849067wxh** [comment]
> ok, there is source code:
Polyhedron p;
std::fstream file("C:\\Users\\CSU\\Desktop\\tmp2.off");
file >> p;
std::cout << p;

feedback is:
CGAL::Polyhedron_incremental_builder_3<HDS>::
add_vertex_to_facet(): input error: disconnected facet complexes at vertex 1528:
           involved facets are: 3067 2968 2931 3015 3066 (closed cycle) and.

Polyhedron_scan_OFF<Traits>::
operator()(): input error: facet 3068 has fewer than 3 vertices.
OFF
0 0 0
[tmp2.txt](https://github.com/CGAL/cgal/files/11742725/tmp2.txt)

thank u a lot

**Comment by sloriot** [comment]
Implementing what I said in my previous comment:
```
#include <CGAL/Exact_predicates_exact_constructions_kernel.h>
#include <CGAL/OFF_to_nef_3.h>
#include <fstream>
#include <iostream>

#include <CGAL/Polygon_mesh_processing/IO/polygon_mesh_io.h>
#include <CGAL/Polyhedron_3.h>

int main(int argc, char** argv)
{
  typedef CGAL::Exact_predicates_exact_constructions_kernel Kernel;
  typedef CGAL::Nef_polyhedron_3<Kernel> Nef_3;

  {
  std::cout << "option 1\n";
  Nef_3 N;
  std::ifstream in(argv[1]);
  std::size_t discarded = CGAL::OFF_to_nef_3 (in, N);

  std::cout << "Nef vertices: "
           << N.number_of_vertices() << std::endl;
  std::cout << "Nef edges: "
           << N.number_of_edges() << std::endl;
  std::cout << "Nef facets: "
           << N.number_of_facets() << std::endl;
  std::cout << "Nef volumes: "
           << N.number_of_volumes() << std::endl;
  std::cout << "number of discarded facets: "
           << discarded << std::endl;
  }


  {
  std::cout << "option 2 (does not work because of a non-manifold edge)\n";
  typedef CGAL::Polyhedron_3<Kernel> Polyhedron;
  Polyhedron P;
  std::ifstream(argv[1]) >> P;
  Nef_3 N(P);
  std::cout << "Nef vertices: "
           << N.number_of_vertices() << std::endl;
  std::cout << "Nef edges: "
           << N.number_of_edges() << std::endl;
  std::cout << "Nef facets: "
           << N.number_of_facets() << std::endl;
  std::cout << "Nef volumes: "
           << N.number_of_volumes() << std::endl;
  }

   return 0;
}
```

**Comment by sloriot** [comment]
Option 1 is the only that can work because the input have one non-manifold edge, shown in red below
![Screenshot from 2023-06-14 10-06-09](https://github.com/CGAL/cgal/assets/1224632/8f6cc3e7-fefc-49b8-b4d4-14a410af9afc)

**Comment by sloriot** [comment]
![Screenshot from 2023-06-14 10-28-07](https://github.com/CGAL/cgal/assets/1224632/47e8a415-0300-4d60-9b50-3c111dd494c7)
(easier to see from the top)

**Comment by wxh158849067wxh** [comment]
> ![Screenshot from 2023-06-14 10-28-07](https://user-images.githubusercontent.com/1224632/245727782-47e8a415-0300-4d60-9b50-3c111dd494c7.png) (easier to see from the top)

thank y very much
