### ISSUE TITLE
Add redirections for renamed packages

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#752]
`Surface_point_reconstructions` --> `Point_surface_reconstruction` (#319)
`Surface_modeling` --> `Surface_mesh_deformation` (#751)

**Comment by sloriot** [comment]
@lrineau 4.8 was released and 
http://doc.cgal.org/latest/Surface_modeling/index.html and http://doc.cgal.org/latest/Surface_reconstruction_points_3/index.html are broken

**Comment by lrineau** [comment]
Fixed.
```
RedirectPermanent /latest/Surface_modeling/ /latest/Surface_mesh_deformation/
RedirectPermanent /latest/Surface_reconstruction_points_3/ /latest/Poisson_surface_reconstruction_3/

```
