### ISSUE TITLE
Issue with drawing of feature edges

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#753]
@maxGimeno 

Open the `cube.off` in the polyhedron demo. Then "Operation->Detect sharp features", and accept the bound of 60°. The the sharp edges of the cube are drawn in read, and the other edges (the diagonals) in black.

# First bug
In the context menu of the item, the open "Show feature edges" is unchecked. It should be checked. Probably the action "Detect sharp features" should ensure that "Show feature edges" is checked in the polyhedron item it acts on. The function `Scene_polyhedron_item::contextMenu()` should call:
```C++
  action = menu->findChild<QAction*>("actionShowOnlyFeatureEdges");
  if(action) action->setChecked(show_feature_edges_m);
```
and same for `"actionShowFeatureEdges"`.

Please also fix the indentation of the function `Scene_polyhedron_item::contextMenu()`, and only that function, at the same time.

# Second bug
Check the option "Show feature edges", nothing happens. Then uncheck it. The bug is that the sharp edges are no longer drawn, and the diagonals are drawn in black.

The correct behavior is:
  - when "Show feature edges" is unchecked, then draw **all** edges in black,
  - when "Show feature edges" is checked, then draw the normal edges in black (unless "Show only feature edges" is checked), and draw the feature edges in red.

Cc: @sloriot 

That impacts our work in the clipping-snapping branch. High priority.

**Comment by maxGimeno** [comment]
See #755 for a fix.
