### ISSUE TITLE
write_stl_file.h

### ISSUE THREAD

**Issue by OmshreeV-MTechCN-UVCE** [CGAL/cgal#7558]
_Please use the following template to help us solving your issue._

## Issue Details
write_stl_file.h
write_stl.h
_Describe your issue. Please be specific (compilation error, runtime error, unexpected behavior, wrong results, etc.)._
i cant write stl file so include write_stl.h
## Source Code

_If your issue arises by using CGAL in your own source code, please provide a minimalist example that we can compile easily to reproduce the bug. If your issue arises from using a CGAL program (demo, example, etc.), please let us know which one. Helping you solving an issue is much easier and efficient if we can reproduce it._

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):
* Compiler:
* Release or debug mode:
* Specific flags used (if any):
* CGAL version:
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by lrineau** [comment]
@OmshreeV-MTechCN-UVCE You need to improve the content you submit to issue reports.

Here the issue message you submitted has 20 lines, mostly unmodified from the initial issue template, but you contribution is only:
> write_stl_file.h
> write_stl.h

> i cant write stl file so include write_stl.h

That can be understood. Please rephrase.
