### ISSUE TITLE
Memory leaks in Three

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#756]
- In the [function `QGLContext* createOpenGLContext()` from `<CGAL/Qt/CreateOpenGLContext.h>`][1] there is a `new QOpenGLContext()` that is never deleted. I suggest that the function `createOpenGLContext()` has a parameter `QObject* parent`, that is passed to the constructor of the `QOpenGLContext`. That way, the object owning the context will destroy it itself.

- In the [function `Scene_item::~Scene_item`][2], the VAOs are "destroyed" but the `QOpenGLVertexArrayObject` objects themselves are not deleted. You should call delete directly, because it is documented that the destructor of `QOpenGLVertexArrayObject` calls `destroy()`.

[1]: https://github.com/CGAL/cgal/commit/c29b3cb70065311d2f35f195871bd3b239aec203#diff-a6248780195497cd3ed9772798a6efdfR28
[2]: https://github.com/CGAL/cgal/commit/49b45a753d6fefc2b7a7e78bfddb5f6314ac21bd#diff-3713fcfe5df492b2195a6d66e0d2cae1R17

**Comment by lrineau** [comment]
@maxGimeno That issue does not have a high priority, but it would be nice to have if fixed before March 2016, for the release CGAL-4.8.

**Comment by sloriot** [comment]
@maxGimeno did you fix this issue already?

**Comment by maxGimeno** [comment]
No.

**Comment by maxGimeno** [comment]
I suspected that there were no actual memory leak, by observing the behavior of the contexts when trying to delete them. If I understand correctly [this patch report](https://codereview.qt-project.org/#/c/90090/), I was right and the QGLContext created by `fromQOpenGLContext()` will delete the QOpenGLContext it is created from when it is destroyed.

**Comment by lrineau** [comment]
Let's close this issue. It seems fixed in Qt-5.3, according to https://github.com/CGAL/cgal/issues/756#issuecomment-241754433.
