### ISSUE TITLE
Draw Polyhedron: throw exception

### ISSUE THREAD

**Issue by wxh158849067wxh** [CGAL/cgal#7564]
_Please use the following template to help us solving your issue._

## Issue Details

read .obj to create Polyhedron and draw it .when CGAL::draw, throw a exception,
i found because a pointer _ptr of Lazy_rep<AT_, ET, E2A, 1> is null;

## Source Code
```cpp
int main(int argc, char *argv[])
{

  Polyhedron P1;
  Nef_polyhedron N2;
  bool mark=CGAL::Polygon_mesh_processing::IO::read_polygon_mesh("C:\\Users\\CSU\\Desktop\\work\\8.5.obj", P1);
  if (!mark)
  {
	  std::cout << "fail！" << std::endl;
  }
  if (P1.is_closed())
  {
	  N2 = Nef_polyhedron(P1);
  }
  CGAL::draw(P1);
  CGAL::draw(N2);
  return EXIT_SUCCESS;
}
```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): windows 64
* Compiler: MSVC
* Release or debug mode: debug
* Specific flags used (if any):
* CGAL version: 5.4.2
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):
* there is .obj file
[8.5.txt](https://github.com/CGAL/cgal/files/11924049/8.5.txt)

**Comment by sloriot** [comment]
Your mesh is self-intersecting, you need to use something like the function `OFF_to_nef_3` in `CGAL/OFF_to_nef_3.h`. The function is meant to be used with OFF and not an OBJ file, so unfortunately you'll need to convert the file first before.
Even after resolving self-intersection, Nef cannot handle the mesh as I guess the internal structure (floors and walls) makes in impossible to decide which faces are the visible ones. 
![Screenshot from 2023-07-03 08-35-00](https://github.com/CGAL/cgal/assets/1224632/69099b04-8d42-4dc5-b293-ed886492c4b8)

**Comment by wxh158849067wxh** [comment]
> Your mesh is self-intersecting,

OK,got it,thank you very much.

**Comment by Dwight98** [comment]
> Your mesh is self-intersecting, you need to use something like the function `OFF_to_nef_3` in `CGAL/OFF_to_nef_3.h`. The function is meant to be used with OFF and not an OBJ file, so unfortunately you'll need to convert the file first before. Even after resolving self-intersection, Nef cannot handle the mesh as I guess the internal structure (floors and walls) makes in impossible to decide which faces are the visible ones. ![Screenshot from 2023-07-03 08-35-00](https://user-images.githubusercontent.com/1224632/250477346-69099b04-8d42-4dc5-b293-ed886492c4b8.png)

Can I ask one ask about the self-intersecting? I really want know which Class in the CGAL can be used to deal the self-intersecting models. About 3 days ago, I used the polygon_soup to change the models' format, and then I used the repair_polygon_soup trying to solve this issue. Unfortunately, I didn't get an ideal result, and the models still self-intersecting. Please help me !
