### ISSUE TITLE
CGAL error: assertion violation! When using example from “Surface Reconstruction from Point Clouds”

### ISSUE THREAD

**Issue by Dwight98** [CGAL/cgal#7565]
_Please use the following template to help us solving your issue._

## Issue Details
I loaded my own point cloud file (.xyz) which contains 3288 points, many more then the example provided. The code compiles fine, but when I run it after a few minutes I get an error like this:

CGAL error: assertion violation!
Expression : parray_ != nullptr
File       : D:\Programs\dev\CGAL-5.5.1\include\CGAL\Surface_mesh\Properties.h
Line       : 614
Explanation:
Refer to the bug-reporting instructions at https://www.cgal.org/bug_report.html

I debug the code by myself, and the location of the normal error is this sentence：“CGAL::jet_estimate_normals<CGAL::Sequential_tag>(points, 24); // Use 24 neighbors”，I swear I'm completely copying the source code of the case on the official website，but once I get here, I can't execute it successfully.

## Source Code
My source code is from“https://doc.cgal.org/latest/Manual/tuto_reconstruction.html#title8” ，and I only used Poisson reconstruction.

head file:
```
#include <iostream>
#include <fstream>
#include <string>
#include <vector>
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/IO/read_las_points.h>
#include <CGAL/property_map.h>
#include <CGAL/Point_set_3.h>
#include <CGAL/Point_set_3/IO.h>
#include <CGAL/Point_set_3/IO/LAS.h>
#include <CGAL/IO/read_points.h>
//#include <CGAL/IO/write_points.h>         
#include <CGAL/IO/write_las_points.h>         
#include <CGAL/jet_estimate_normals.h>   
#include <CGAL/mst_orient_normals.h>      
#include <CGAL/compute_average_spacing.h> 
#include <CGAL/pca_estimate_normals.h>
#include <CGAL/remove_outliers.h>
#include <CGAL/grid_simplify_point_set.h>
#include <CGAL/jet_smooth_point_set.h>
#include <CGAL/poisson_surface_reconstruction.h>
#include <CGAL/Advancing_front_surface_reconstruction.h>
#include <CGAL/Scale_space_surface_reconstruction_3.h>
#include <CGAL/Scale_space_reconstruction_3/Jet_smoother.h>
#include <CGAL/Scale_space_reconstruction_3/Advancing_front_mesher.h>
#include <CGAL/Surface_mesh.h>
#include <CGAL/Polygon_mesh_processing/polygon_soup_to_polygon_mesh.h>
#include <cstdlib>

typedef:
typedef CGAL::Exact_predicates_inexact_constructions_kernel Kernel;
typedef Kernel::FT FT;
typedef Kernel::Point_3 Point_3;
typedef Kernel::Vector_3 Vector_3;
typedef Kernel::Sphere_3 Sphere_3;
typedef CGAL::Point_set_3<Point_3, Vector_3> Point_set;

code:
        const char* output_filename = "E:/point/output/1.obj";
	
	char v2[] = "D:/Programs/dev/CGAL-5.5.1/data/points_3/blobby.xyz";
	Point_set points;
	std::string fname = argc == 1 ? CGAL::data_file_path(v2) : argv[1];
	if (argc < 2)
	{
		std::cerr << "Usage: " << argv[0] << " [input.xyz/off/ply/las]" << std::endl;
		std::cerr << "Running " << argv[0] << " data/kitten.xyz -1\n";
	}
	std::ifstream stream(fname, std::ios_base::binary);
	if (!stream)
	{
		std::cerr << "Error: cannot read file " << fname << std::endl;
		return EXIT_FAILURE;
	}
	stream >> points;
	std::cout << "Read " << points.size() << " point(s)" << std::endl;
	if (points.empty())
		return EXIT_FAILURE;
	typename Point_set::iterator rout_it = CGAL::remove_outliers<CGAL::Sequential_tag>
		(points,
			24, // Number of neighbors considered for evaluation
			points.parameters().threshold_percent(5.0)); // Percentage of points to remove
	points.remove(rout_it, points.end());
	std::cout << points.number_of_removed_points()
		<< " point(s) are outliers." << std::endl;
	points.collect_garbage();
	double spacing = CGAL::compute_average_spacing<CGAL::Sequential_tag>(points, 6);
	// Simplify using a grid of size 2 * average spacing
	typename Point_set::iterator gsim_it = CGAL::grid_simplify_point_set(points, 2. * spacing);
	points.remove(gsim_it, points.end());
	std::cout << points.number_of_removed_points()
		<< " point(s) removed after simplification." << std::endl;
	points.collect_garbage();
	CGAL::jet_smooth_point_set<CGAL::Sequential_tag>(points, 24);
	CGAL::jet_estimate_normals<CGAL::Sequential_tag>(points, 24); // Use 24 neighbors
	  // Orientation of normals, returns iterator to first unoriented point
	typename Point_set::iterator unoriented_points_begin =
		CGAL::mst_orient_normals(points, 24); // Use 24 neighbors
	points.remove(unoriented_points_begin, points.end());

	CGAL::Surface_mesh<Point_3> output_mesh;
	CGAL::poisson_surface_reconstruction_delaunay
	(points.begin(), points.end(),
		points.point_map(), points.normal_map(),
		output_mesh, spacing);


	std::ofstream f(output_filename, std::ios_base::binary);
	CGAL::IO::set_binary_mode(f);
	CGAL::IO::write_OBJ(f, output_mesh);
	f.close();
```

## Environment

* Operating system (Windows 64 bits):
* Compiler:Visual Studio 2019
* Release or debug mode: debug
* Specific flags used (if any):
* CGAL version: 5.5.1 
* Boost version: 1.71.0
* Other libraries versions if used (Eigen, TBB, etc.): Eigen 3

**Comment by soesau** [comment]
The normal estimation methods require a normal map property in the point set.
You can add "points.add_normal_map();" before the normal estimation and the method will work.

Notice, however, that the poisson reconstruction is a surface reconstruction, but the point cloud "blobby.xyz" is volumetric. Meaning, the method expects the points to be sampled from the surface, but the provided point cloud also has many points on the inside of the object. You can try kitten.xyz, e.g., for better results.

**Comment by Dwight98** [comment]
> The normal estimation methods require a normal map property in the point set. You can add "points.add_normal_map();" before the normal estimation and the method will work.
> 
> Notice, however, that the poisson reconstruction is a surface reconstruction, but the point cloud "blobby.xyz" is volumetric. Meaning, the method expects the points to be sampled from the surface, but the provided point cloud also has many points on the inside of the object. You can try kitten.xyz, e.g., for better results.

Thank you about your suggestion, but may i ask you to tell the specific location where I can add the code that you said ,I think i am not very familar with CGAL, and It wasn't long before I started learning it，if possible, could you give me a example use my code, I really appreciate your help，Thank you so much！

**Comment by soesau** [comment]
For adding the normal map property, you add
`points.add_normal_map();`
between
`points.collect_garbage();`
and
`CGAL::jet_smooth_point_set<CGAL::Sequential_tag>(points, 24);`

And to change the dataset you change
`char v2[] = "D:/Programs/dev/CGAL-5.5.1/data/points_3/blobby.xyz";`
to
`char v2[] = "D:/Programs/dev/CGAL-5.5.1/data/points_3/kitten.xyz";`

The actual path depends on your installation. And also if you actually provide an argument to the executable or not.

**Comment by Dwight98** [comment]
> For adding the normal map property, you add `points.add_normal_map();` between `points.collect_garbage();` and `CGAL::jet_smooth_point_set<CGAL::Sequential_tag>(points, 24);`
> 
> And to change the dataset you change `char v2[] = "D:/Programs/dev/CGAL-5.5.1/data/points_3/blobby.xyz";` to `char v2[] = "D:/Programs/dev/CGAL-5.5.1/data/points_3/kitten.xyz";`
> 
> The actual path depends on your installation. And also if you actually provide an argument to the executable or not.

Thank you very much ! You really helped a lot，These suggestions are very useful。Learn from you, my esteemed sir。

**Comment by Dwight98** [comment]
> For adding the normal map property, you add `points.add_normal_map();` between `points.collect_garbage();` and `CGAL::jet_smooth_point_set<CGAL::Sequential_tag>(points, 24);`
> 
> And to change the dataset you change `char v2[] = "D:/Programs/dev/CGAL-5.5.1/data/points_3/blobby.xyz";` to `char v2[] = "D:/Programs/dev/CGAL-5.5.1/data/points_3/kitten.xyz";`
> 
> The actual path depends on your installation. And also if you actually provide an argument to the executable or not.

Hello,sir,I am so sorry to bother you again, but I just want to ask you whether you can give me some suggestions about the Parallel computing method. Through using you last suggestion, I can implement a model reconstruction of "kitten.xyz".However, my own data set is very large, with about 100 million points, could you please tell me how to use parallel computing methods to achieve model reconstruction of my own data set， Sincerely ask for your advice！
