### ISSUE TITLE
BGL - add `Face_filtered_graph` constructor from boolean property map

### ISSUE THREAD

**Issue by janetournois** [CGAL/cgal#7570]
## Issue Details

Would it be difficult/would it make sense to add a constructor `Face_filtered_graph(const Graph& g, FaceIsSelectedPmap f_bool_pmap)` that constructs the filtered graph wrt selected-or-not status of every facet, similarly to the patch-id based constructor?

cc @sloriot @ipadjen

**Comment by sloriot** [comment]
IIUC, you can already do that using `FaceIsSelectedPmap` as third parameter and a bool as second parameter.

**Comment by afabri** [comment]
Which third parameter?
