### ISSUE TITLE
document 3rd template parameter of `CGAL::Apollonius_graph_vertex_base_2< Gt, StoreHidden >`

### ISSUE THREAD

**Issue by stla** [CGAL/cgal#7579]
## Issue Details

The class [`CGAL::Apollonius_graph_vertex_base_2< Gt, StoreHidden >`](https://doc.cgal.org/latest/Apollonius_graph_2/classCGAL_1_1Apollonius__graph__vertex__base__2.html) has a third template parameter which is not documented. 

This third template parameter can be `CGAL::Triangulation_vertex_base_with_info_2<myinfo, myKernel>` which is very useful.

**Comment by lrineau** [comment]
Fixed by PR #7619.
