### ISSUE TITLE
documentation problem about the dual face for Apollonius graph.

### ISSUE THREAD

**Issue by stla** [CGAL/cgal#7582]
According to [the documentation](https://doc.cgal.org/latest/Apollonius_graph_2/classCGAL_1_1Apollonius__graph__2.html#a304f5fe797914ddda090095ece7fdd7d), there's a method `dual` which returns an `Object_2` for `Face_handle`, `Finite_faces_iterator`, and `All_faces_iterator`. This is not in agreement with the code: for `Finite_faces_iterator`, the `dual` method always returns a `Site_2`, and for `All_faces_iterator`, there's no method `dual` defined.

https://github.com/CGAL/cgal/blob/6098856af6ad64f8c851d5e98416ccf4ea7b02a6/Apollonius_graph_2/include/CGAL/Apollonius_graph_2.h#L527

https://github.com/CGAL/cgal/blob/6098856af6ad64f8c851d5e98416ccf4ea7b02a6/Apollonius_graph_2/include/CGAL/Apollonius_graph_2.h#L529

**Comment by priyanshu217** [comment]
Assign me this I will work on it

**Comment by afabri** [comment]
Thank you for the bug report.  Note that for `All_faces_iterator` the function for `Face_handle` matches.  So it is not missing in the code.
