### ISSUE TITLE
halfspace_intersection_3.h::is_intersection_dim_3 not smart enough

### ISSUE THREAD

**Issue by bombax** [CGAL/cgal#76]
If you pass the following planes to halfspace_intersection_3 (planes forming a box-thing):

-1 0 0 -11.92
0 -1 0 32.72
0 1 0 -33.28
0 0 -1 0.64
0 0 1 -1.6
1 0 0 11.3599

If I'm not mistaken the intersection is a valid polyhedron cuboid, but the assertion above aggressively (and I would think incorrectly) determines it is not in 3 dimensions.

I think this is because plane1_it = -1 0 0 -11.92 and plane2_it = 1 0 0 11.3599, which are parallel, so they are automatically coplanar with any other vector in the "coplanar" check.

**Comment by sloriot** [comment]
This should is fixed by 6554279e.
See #81

**Comment by lrineau** [comment]
Fixed by #82.
