### ISSUE TITLE
Where is "ui_ImageInterface.h"

### ISSUE THREAD

**Issue by kilasuelika** [CGAL/cgal#7601]
In `CGAL/QT/image_interface.h`, there is a line `#include "ui_ImageInterface.h"`. But I didn't find this file in my vcpkg installation. I also try to download the release version from GitHub and also didn't find this file.

**Comment by sloriot** [comment]
This was fixed by https://github.com/CGAL/cgal/pull/7313, available in CGAL-5.6-beta1

**Comment by lrineau** [comment]
`ui_ImageInterface.h` is generated by Qt's UIC from `ImageInterface.ui`. The build system should caring that task.
