### ISSUE TITLE
problem about Visualization Package 

### ISSUE THREAD

**Issue by Kasi** [CGAL/cgal#7604]
_Please use the following template to help us solving your issue._

## Issue Details

_Describe your issue. Please be specific (compilation error, runtime error, unexpected behavior, wrong results, etc.)._

**When I compiled the code, an error occurred.**

```
Mainwindow.cpp.obj: error LNK2001: Unresolved external symbol 'public: virtual construct QMetaObject const * __cdecl CGAL:: Qt:: GraphicsItem:: metaObject (void) const' (? metaObject@GraphicsItem @ Qt@CGAL @@UEBAPEBUQMetaObject @ @ XZ)
Mainwindow.cpp.obj: error LNK2001: Unresolved external symbol 'public: virtual void * __cdecl CGAL:: Qt:: GraphicsItem: qt_metacast (char const *)' (? qt_metacast@GraphicsItem @ Qt@CGAL @@ UEAAPEAXPEBD@Z ）
Mainwindow.cpp.obj: error LNK2001: Unresolved external symbol 'public: virtual int __cdecl CGAL:: Qt:: GraphicsItem: qt_metacall (enum QMetaObject: Call, int, void * *)' (? qt_metacall@GraphicsItem @ Qt@CGAL @@ UEAAHW4Call@QMetaObject @@ HPEAPEAX@Z ）
Tst1.exe: fatal error LNK1120: 3 unresolved external commands
```
## Source Code

_If your issue arises by using CGAL in your own source code, please provide a minimalist example that we can compile easily to reproduce the bug. If your issue arises from using a CGAL program (demo, example, etc.), please let us know which one. Helping you solving an issue is much easier and efficient if we can reproduce it._

```c++
#include "mainwindow.h"
#include "./ui_mainwindow.h"
#include <iostream>
#include <QMessageBox.h>



#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/Alpha_shape_2.h>
#include <CGAL/Alpha_shape_vertex_base_2.h>
#include <CGAL/Alpha_shape_face_base_2.h>
#include <CGAL/Delaunay_triangulation_2.h>

#include <CGAL/Qt/GraphicsItem.h>
#include <CGAL/Qt/TriangulationGraphicsItem.h>
#include <CGAL/Qt/GraphicsItem.h>
#include <CGAL/Qt/ConstrainedTriangulationGraphicsItem.h>

typedef CGAL::Exact_predicates_inexact_constructions_kernel  K;
typedef K::FT                                                FT;
typedef K::Point_2                                           Point;
typedef K::Segment_2                                         Segment;
typedef CGAL::Alpha_shape_vertex_base_2<K>                   Vb;
typedef CGAL::Alpha_shape_face_base_2<K>                     Fb;
typedef CGAL::Triangulation_data_structure_2<Vb,Fb>          Tds;
typedef CGAL::Delaunay_triangulation_2<K,Tds>                Triangulation_2;
typedef CGAL::Alpha_shape_2<Triangulation_2>                 Alpha_shape_2;

MainWindow::MainWindow(QWidget *parent)
    : QMainWindow(parent)
    , ui(new Ui::MainWindow)
{
    ui->setupUi(this);
}

MainWindow::~MainWindow()
{
    delete ui;
}


void MainWindow::on_pushButton_clicked()
{
    Alpha_shape_2 *as;
    Triangulation_2 *t2=nullptr;
   CGAL::Qt::TriangulationGraphicsItem<Triangulation_2> t(t2); // If this line of code is commented out, the compilation passes

}
```
## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows64
* Compiler: msvc14 ,vs2019
* Release or debug mode:
* Specific flags used (if any):
* CGAL version: latest
* Boost version: latest
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by Kasi** [comment]
qt5  version5.15.10
cmake version 3.5

**Comment by sloriot** [comment]
Do you have  something like`target_link_libraries(my_target public CGAL::CGAL CGAL::CGAL_Qt5)` in you `CMakeList.txt`?

**Comment by Kasi** [comment]
This is my code

**I am trying to add CGAL:: CGAL_ Qt5 but cannot be found**
`

cmake_minimum_required(VERSION 3.5)

project(tst1 VERSION 0.1 LANGUAGES CXX)

set(CMAKE_AUTOUIC ON)
set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTORCC ON)

set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)



set(TS_FILES tst1_zh_CN.ts)


add_executable(tst1
    mainwindow.ui
    mainwindow.h
    mainwindow.cpp
    main.cpp


)


find_package(CGAL REQUIRED)
message(STATUS "Found CGAL v${CGAL_VERSION}. Include dirs: ${CGAL_INCLUDE_DIRS}")
target_link_libraries(tst1 PUBLIC CGAL::CGAL)

find_package(Qt5 COMPONENTS Widgets REQUIRED)
message(STATUS "Found Qt v${CGAL_VERSION}. Include dirs: ${QT_INCLUDE_DIRS}")
target_link_libraries(tst1 PUBLIC Qt5::Widgets)

find_package(Qt5 COMPONENTS Core REQUIRED)
target_link_libraries(tst1 PUBLIC Qt5::Core)

`

> Do you have something like`target_link_libraries(my_target public CGAL::CGAL CGAL::CGAL_Qt5)` in you `CMakeList.txt`?

**Comment by afabri** [comment]
Did you install Qt ?

**Comment by lrineau** [comment]
> ```cmake
> find_package(CGAL REQUIRED)
> ```

You need to search for the Qt5 component of CGAL:
```cmake
find_package(CGAL REQUIRED COMPONENTS Qt5)
```

**Comment by Kasi** [comment]
> ```cmake
> find_package(CGAL REQUIRED COMPONENTS Qt5)
> ```

Yes, 
![Uploading image.png…]()

**Comment by Kasi** [comment]
> > ```cmake
> > find_package(CGAL REQUIRED)
> > ```
> 
> You need to search for the Qt5 component of CGAL:
> 
> ```cmake
> find_package(CGAL REQUIRED COMPONENTS Qt5)
> ```

Why cannot open Qt5.lib ?

**Comment by Kasi** [comment]
this is my code.
[https://github.com/Kasi/cgal-qt5Visualization.git](url)
I have tried multiple schemes but failed

**Comment by lrineau** [comment]
See https://github.com/lrineau/cgal-qt5Visualization. It works for me. There is nothing more we can do for you. Make sure Qt5 is correctly installed on your machine.
