### ISSUE TITLE
offset a polygon multiple times?

### ISSUE THREAD

**Issue by pcace** [CGAL/cgal#7621]
i there, i am trying to find a good way to offset a polygon multiple times ,
so that i get something like this: 

![Bildschirmfoto vom 2023-07-27 16-31-31](https://github.com/CGAL/cgal/assets/1011875/9b2bea63-b007-4fb8-9b84-091daaf122cd)

currently i run this: 

```

  PolygonWithHolesPtrVector offset_poly_with_holes =
      CGAL::create_interior_weighted_skeleton_and_offset_polygons_with_holes_2(
          lOffset, pwh, speeds);
```
again and again with  offset  = offset +1 values until there is no more polygons found. 

is there a more performant way ;) ?

Cheers and thanks a lot!

**Comment by MaelRL** [comment]
You don't need to recompute the skeleton every time: you can compute the skeleton once, and then use the function [create_offset_polygons_2](https://doc.cgal.org/latest/Straight_skeleton_2/group__PkgStraightSkeleton2OffsetFunctions.html#ga80a83d9b770bb3bfda6401b0cc5cc79f).
