### ISSUE TITLE
Polyhedron demo: Meshing a segmented image 

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#7634]
## Issue Details

When meshing a segmented image the tetrahedra should have the color of the segments.

**Comment by ange-clement** [comment]
I have looked a bit, it seems the strategy to choose colors of images and meshes are different.
A meshes (Scene_triangulation_3_item) choose its colors based on its base color.
An Image (Scene_image_item) chooses its colors at the creation with a hard coded value (starting_hue = 45./360.)

Should we make images' colors adapt to their base color?
