### ISSUE TITLE
Tetrahedral isotropic remeshing gives unexpected results

### ISSUE THREAD

**Issue by termi-official** [CGAL/cgal#7636]
## Issue Details

Hi everyone and thanks for providing this interesting library!
I am experimenting around with tetrahedral remeshing of CT data (https://doc.cgal.org/latest/Tetrahedral_remeshing/index.html). However, I get strange results. Sometimes the mesh boundaries collapse in very strange ways. Below is a reproducer.

Edit: I also can see that the boundary facet attribute assignment is broken in the generated mesh (manually inspecting it).

## Source Code

I am using a slight modification of the provided example, trying to confirm that the mesh is not already broken after reading.

```cxx
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>

#include <CGAL/Tetrahedral_remeshing/Remeshing_triangulation_3.h>
#include <CGAL/tetrahedral_remeshing.h>

#include <CGAL/IO/output_to_vtu.h>

#include <fstream>

typedef CGAL::Exact_predicates_inexact_constructions_kernel K;

typedef CGAL::Tetrahedral_remeshing::Remeshing_triangulation_3<K> Remeshing_triangulation;

int main(int argc, char* argv[])
{
  const char* filename = (argc > 1) ? argv[1] : "data/sphere.mesh";
  const double target_edge_length = (argc > 2) ? atof(argv[2]) : 0.1;

  Remeshing_triangulation tr;

  std::ifstream is(filename, std::ios_base::in);
  CGAL::IO::read_MEDIT(is, tr);

  {
    std::ofstream os("before_remeshing.vtu");
    CGAL::Mesh_complex_3_in_triangulation_3<Remeshing_triangulation, int, int> c3t3;
    c3t3.triangulation() = tr;
    c3t3.rescan_after_load_of_triangulation();
    CGAL::IO::output_to_vtu(os, c3t3);
  }

  CGAL::tetrahedral_isotropic_remeshing(tr, target_edge_length);

  {
    std::ofstream os("after_remeshing.vtu");
    CGAL::Mesh_complex_3_in_triangulation_3<Remeshing_triangulation, int, int> c3t3;
    c3t3.triangulation() = tr;
    c3t3.rescan_after_load_of_triangulation();
    CGAL::IO::output_to_vtu(os, c3t3);
  }

  return EXIT_SUCCESS;
}
```

as a rather minimal reproducer I use the following MEDIT mesh.

```
MeshVersionFormatted 1
Dimension 3
Vertices
36
0 0 0 -1
1 0 0 -1
2 0 0 -1
3 0 0 -1
4 0 0 -1
5 0 0 -1
6 0 0 -1
7 0 0 -1
8 0 0 -1
0 1 0 -1
1 1 0 -1
2 1 0 -1
3 1 0 -1
4 1 0 -1
5 1 0 -1
6 1 0 -1
7 1 0 -1
8 1 0 -1
0 0 1 -1
1 0 1 -1
2 0 1 -1
3 0 1 -1
4 0 1 -1
5 0 1 -1
6 0 1 -1
7 0 1 -1
8 0 1 -1
0 1 1 -1
1 1 1 -1
2 1 1 -1
3 1 1 -1
4 1 1 -1
5 1 1 -1
6 1 1 -1
7 1 1 -1
8 1 1 -1
Triangles
68
29 19 20 2
1 20 19 2
20 1 2 2
1 11 2 2
19 29 28 2
28 1 19 2
29 10 28 2
1 28 10 2
10 29 11 2
11 1 10 2
30 20 21 2
2 21 20 2
21 2 3 2
2 12 3 2
20 30 29 2
30 11 29 2
11 30 12 2
12 2 11 2
31 21 22 2
3 22 21 2
22 3 4 2
3 13 4 2
21 31 30 2
31 12 30 2
12 31 13 2
13 3 12 2
32 22 23 2
4 23 22 2
23 4 5 2
4 14 5 2
22 32 31 2
32 13 31 2
13 32 14 2
14 4 13 2
33 23 24 2
5 24 23 2
24 5 6 2
5 15 6 2
23 33 32 2
33 14 32 2
14 33 15 2
15 5 14 2
34 24 25 2
6 25 24 2
25 6 7 2
6 16 7 2
24 34 33 2
34 15 33 2
15 34 16 2
16 6 15 2
35 25 26 2
7 26 25 2
26 7 8 2
7 17 8 2
25 35 34 2
35 16 34 2
16 35 17 2
17 7 16 2
36 26 27 2
8 27 26 2
9 36 27 2
27 8 9 2
36 9 18 2
8 18 9 2
26 36 35 2
36 17 35 2
17 36 18 2
18 8 17 2
Tetrahedra
48
29 1 20 19 1
1 29 20 2 1
29 1 11 2 1
29 1 19 28 1
1 29 10 28 1
29 1 10 11 1
30 2 21 20 1
2 30 21 3 1
30 2 12 3 1
30 2 20 29 1
2 30 11 29 1
30 2 11 12 1
31 3 22 21 1
3 31 22 4 1
31 3 13 4 1
31 3 21 30 1
3 31 12 30 1
31 3 12 13 1
32 4 23 22 1
4 32 23 5 1
32 4 14 5 1
32 4 22 31 1
4 32 13 31 1
32 4 13 14 1
33 5 24 23 1
5 33 24 6 1
33 5 15 6 1
33 5 23 32 1
5 33 14 32 1
33 5 14 15 1
34 6 25 24 1
6 34 25 7 1
34 6 16 7 1
34 6 24 33 1
6 34 15 33 1
34 6 15 16 1
35 7 26 25 1
7 35 26 8 1
35 7 17 8 1
35 7 25 34 1
7 35 16 34 1
35 7 16 17 1
36 8 27 26 1
8 36 27 9 1
36 8 18 9 1
36 8 26 35 1
8 36 17 35 1
36 8 17 18 1
```

which results in the following result (left after reading it in, right after remeshing)

![Screenshot from 2023-08-03 23-53-29](https://github.com/CGAL/cgal/assets/9196588/0750fdc0-4e79-4395-97f0-9c29d9b0f658)

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Linux 64 bit
* Compiler: gcc latest and clang latest
* Release or debug mode: both
* Specific flags used (if any): -
* CGAL version: 5.1, master and https://github.com/CGAL/cgal/pull/7633
* Boost version: 1.81
* Other libraries versions if used (Eigen, TBB, etc.): -

**Comment by janetournois** [comment]
Hello @termi-official
Thank you for your report, I will have a look at it.

**Comment by janetournois** [comment]
Hello @termi-official 

To avoid this shrinking effect of 1-D polyline features, they should be marked as constrained edges. There are several options to do so :
* use `CGAL::make_mesh_3()` to generate the input mesh with features, and take this triangulation with all its metadata as input
* have patch numbers associated to surface patches separated by sharp features, and stored in `surface_patch_index(i)` in the [cell base](https://doc.cgal.org/latest/SMDS_3/classSimplicialMeshCellBase__3.html)
* use the `edge_is_constrained_map` named parameter in [CGAL::tetrahedral_isotropic_remeshing()](https://doc.cgal.org/latest/Tetrahedral_remeshing/group__PkgTetrahedralRemeshingRef.html#gadeec4a90f1b4f8c9bca76eaee9181235)

As an example for the first approach, tet meshing from the beam surface generates this mesh
![image](https://github.com/CGAL/cgal/assets/11311305/08ad1c39-25d1-430b-b978-d33d9db06a73)

and the output of tetrahedral remeshing is as follows
![image](https://github.com/CGAL/cgal/assets/11311305/7cb2c589-925b-4283-852b-26cf6eeb9271)

I hope this helps

**Comment by termi-official** [comment]
Thanks for taking time and the elaboration! This definitely makes sense. I will take a look ASAP.
