### ISSUE TITLE
Compiling Error CGAL 5.6

### ISSUE THREAD

**Issue by adokhugi** [CGAL/cgal#7642]
## Issue Details

After building with CMake, I get many compiling errors for CGAL 5.6 when trying to build it in Visual Studio 2022. I had no problems with CGAL 5.5.2.

When I compile region_growing_on_polyhedron alone I get among others these errors (in total I get 35 errors):
- syntax error: identifier 'Segment_from_edge_descriptor_map' - c:\Users\Claus.Volko\CGAL-5.6\include\CGAL\Shape_detection\Region_growing\Polygon_mesh\Polyline_graph.h - 88
- syntax error: missing ';' before '&' - c:\Users\Claus.Volko\CGAL-5.6\include\CGAL\Shape_detection\Region_growing\Polygon_mesh\Polyline_graph.h - 279
- unexpected token(s) preceding '{'; skipping apparent function body - c:\Users\Claus.Volko\CGAL-5.6\include\CGAL\Shape_detection\Region_growing\Polygon_mesh\Polyline_graph.h - 279
- 'm_segment_map': unknown override specifier - c:\Users\Claus.Volko\CGAL-5.6\include\CGAL\Shape_detection\Region_growing\Polygon_mesh\Polyline_graph.h - 298
- 'const int CGAL::Shape_detection::Polygon_mesh::Polyline_graph<PolygonMesh,VertexPointMap>::Segment_map': redefinition - c:\Users\Claus.Volko\CGAL-5.6\include\CGAL\Shape_detection\Region_growing\Polygon_mesh\Polyline_graph.h - 298	

I get these errors both in debug and release mode. I also tried playing with the versions of the C and C++ language supported, with no effect.

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows 64 bit
* Compiler: Visual Studio 2022
* Release or debug mode: both
* CGAL version: 5.6

**Comment by janetournois** [comment]
Hello @adokhugi 
can you please tell us what example code from CGAL-5.6 (or custom code) you are trying to compile, so that we can reproduce the issue?

**Comment by adokhugi** [comment]
As I wrote, I tried to build the project region_growing_on_polyhedron.

**Comment by soesau** [comment]
What version of boost do you have?
Do the other examples compile, in particular, region_growing_planes_on_polygon_mesh?

**Comment by adokhugi** [comment]
The version of boost is 1.82.0.
The example region_growing_planes_on_polygon_mesh does not compile, either - some of the error messages are the same.

**Comment by adokhugi** [comment]
I have solved the problem. The cause of the error was that cgal had not been properly updated to version 5.6. It did not suffice to run "vcpkg upgrade cgal", I first had to run "git pull" in the vcpkg directory. Now I get no compilation error for region_growing_on_polyhedron.
