### ISSUE TITLE
CGAL warning: check violation!

### ISSUE THREAD

**Issue by WMA302** [CGAL/cgal#7643]
_Please use the following template to help us solving your issue._

## Issue Details

CGAL warning: check violation!
Expression : last_preprocess_successful
File       : D:\Work_Code\3rdParty\CGAL_Use\Includes\include\CGAL/Surface_mesh_deformation.h
Line       : 1206
Explanation:
Refer to the bug-reporting instructions at https://www.cgal.org/bug_report.html
Error in preprocessing, check documentation of preprocess()

## Source Code

_If your issue arises by using CGAL in your own source code, please provide a minimalist example that we can compile easily to reproduce the bug. If your issue arises from using a CGAL program (demo, example, etc.), please let us know which one. Helping you solving an issue is much easier and efficient if we can reproduce it._
## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):Windows11 64 bits
* Compiler:cmake3.27
* Release or debug mode:release
* Specific flags used (if any):5.2.1
* CGAL version:5.2.1
* Boost version:1.72
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by janetournois** [comment]
Hello @WMA302 ,
can you please give provide the code that produces this error, so that we can try to reproduce it?

**Comment by janetournois** [comment]
Note that CGAL has now reached version 5.6, and 5.2.1 is not supported anymore.
