### ISSUE TITLE
Is it possible to perform Boolean operation on linear cell complex?

### ISSUE THREAD

**Issue by JLYang123** [CGAL/cgal#7657]
CGAL Boolean can be performed on Nef_Polyhedron and Polyhedron_3,  is it possible to perform Boolean operation on linear cell complex?
A direct method is to perform Boolean separately for each part, and finally assemble them. But how to deal with duplicate face that overlapped?

**Comment by gdamiand** [comment]
This is not (yet) possible.
The method you suggest is doable (even if it is not the best since you are going to compute the same intersection several times).
To group several parts together, you can call the sew3_same_facets method that will 3-sew all pair of facets having the same geometry.

**Comment by gdamiand** [comment]
There is no automatic repair; the partial overlap need to be solved... by a Boolean operation, which is not yet implemented.
Note that basic functions allowing to insert a vertex in an edge or an edge in a face exist.

**Comment by JLYang123** [comment]
How to specify  two different 3-attributes for each volume in a Linear Cell Complex, it seems each i-cell can only have one i-attribute. If it is possible, could you please show some example code.

**Comment by JLYang123** [comment]
when i add attribute on vertices using following code, the geometry changed. It is a bug?

void add_vertice_attributes(LCC_3& lcc)
{
  LCC_3::One_dart_per_cell_range<0,3> vs = lcc.one_dart_per_cell<0>();
  for(auto it = vs.begin(); it != vs.end(); ++it)
  {
    lcc.set_attribute<0>(it, lcc.create_attribute<0>());
  }
}

**Comment by gdamiand** [comment]
attributes<0> are used to store 3D points associated with vertices of the linear cell complex.
In your code you override all attributes using default constructors for 3D points; thus the geometry is modified.

If you want to associate additional information to vertices, you need to use your own item class and use the Info associated with the cell attribute.

Cf the doc [here](https://doc.cgal.org/latest/Linear_cell_complex/classCellAttributeWithPoint.html) and the [following example](https://doc.cgal.org/latest/Linear_cell_complex/Linear_cell_complex_2linear_cell_complex_3_with_colored_vertices_8cpp-example.html)

**Comment by JLYang123** [comment]
I see.
I tried to set the attributes with Info<1/2/3> before, but it abort for assert " attribute<i>(dart) == nullptr", so i use the set_attribute command. For  0-cell attribute, i will use info<0> directly.

**Comment by gdamiand** [comment]
You need to create and set the attributes before to use them, except for attributes 0 that are created automatically for linear cell complex because of the points.

**Comment by JLYang123** [comment]
> t

Thank you

**Comment by JLYang123** [comment]
How to construct a face with holes? or with other face inside?
add facet command seems not enough

**Comment by gdamiand** [comment]
Create two faces (one for the each border of the face), and use the insert_cell_1_between_two_cells_2 method https://cgal.geometryfactory.com/CGAL/doc/master/Combinatorial_map/classGenericMap.html#aa29570a0812094c7876e24a228373f12

**Comment by JLYang123** [comment]
> Create two faces (one for the each border of the face), and use the insert_cell_1_between_two_cells_2 method https://cgal.geometryfactory.com/CGAL/doc/master/Combinatorial_map/classGenericMap.html#aa29570a0812094c7876e24a228373f12

you mean add a edge between two separate boundaries?  I don't know how to use and failed.

```
#include <CGAL/Linear_cell_complex_for_combinatorial_map.h>
#include <CGAL/Linear_cell_complex_incremental_builder_3.h>
#include <CGAL/draw_linear_cell_complex.h>
#include<set>
typedef CGAL::Linear_cell_complex_for_combinatorial_map<3, 3> LCC_3;
using Point=LCC_3::Point;
void incremental_build(LCC_3& lcc)
{
    CGAL::Linear_cell_complex_incremental_builder_3<LCC_3> ib(lcc);
    ib.add_vertex(Point(0,0,0)); // vertex 0
    ib.add_vertex(Point(1,0,0)); // vertex 1
    ib.add_vertex(Point(1,1,0)); // vertex 2
    ib.add_vertex(Point(0,1,0)); // vertex 3
    ib.add_vertex(Point(0,1,1)); // vertex 4
    ib.add_vertex(Point(0,0,1)); // vertex 5
    ib.add_vertex(Point(1,0,1)); // vertex 6
    ib.add_vertex(Point(1,1,1)); // vertex 7
    ib.add_vertex(Point(0.3,0.7,1)); // vertex 8
    ib.add_vertex(Point(0.3,0.3,1)); // vertex 9
    ib.add_vertex(Point(0.7,0.3,1)); // vertex 10
    ib.add_vertex(Point(0.7,0.7,1)); // vertex 11
    // Create a cube
    ib.begin_surface();
    ib.add_facet({0,1,2,3});   
    ib.add_facet({1,0,5,6});
    ib.add_facet({2,1,6,7});
    ib.add_facet({3,2,7,4});
    ib.add_facet({0,3,4,5});
    auto f1 = ib.add_facet({5,4,7,6});
    auto f2 = ib.add_facet({9,10,11,8});
    ib.end_surface();
    lcc.insert_cell_1_in_cell_2(f1, f2); 
}

int main(int argc, char*argv[])
{
  LCC_3 lcc;
  incremental_build(lcc);
  lcc.display_characteristics(std::cout)<<std::endl;
  CGAL::draw(lcc);
  return EXIT_SUCCESS;
}
```

This is not the result I hoped for, I found the **enclosure tree** in your papaer  "Efficient Data Structures for
Computer Graphics and Image Processing" that solve the enclosed relations is what i want, How to construct it in code ? or does it implemented in linear_cell_complex?

![image](https://github.com/CGAL/cgal/assets/106522728/ddebc8ca-5a4e-45d7-932e-3d3471b427b8)

**Comment by gdamiand** [comment]
> you mean add a edge between two separate boundaries? I don't know how to use and failed.

No. Have a look at the link I gave you (this is a new method in master (insert_cell_1_between_two_cells_2)

**Comment by JLYang123** [comment]
Sorry to bother you again.
Is there any method that can simplify a linear cell complex with several 3-cells and Myitem (delete short edge and coplaner face).
The method below seems only solve the complex with one 3-cell and specific item.
[https://github.com/CGAL/cgal/blob/master/Surface_mesh_simplification/examples/Surface_mesh_simplification/edge_collapse_linear_cell_complex.cpp](url)

**Comment by JLYang123** [comment]
> Sorry to bother you again. Is there any method that can simplify a linear cell complex with several 3-cells and Myitem (delete co-line edge and coplaner face). The method below seems only solve the complex with one 3-cell and specific item. [https://github.com/CGAL/cgal/blob/master/Surface_mesh_simplification/examples/Surface_mesh_simplification/edge_collapse_linear_cell_complex.cpp](url)

for example, how to delete the edge and face below(i want to make two simple tetrahedron)
![截图_选择区域_20231019135548](https://github.com/CGAL/cgal/assets/106522728/fc21b975-2abb-4e20-adce-37a48cabe464)

below is my code

```
#include <CGAL/Linear_cell_complex_for_combinatorial_map.h>
#include <CGAL/Linear_cell_complex_incremental_builder_3.h>
#include <CGAL/draw_linear_cell_complex.h>
#include <CGAL/Polygon_mesh_processing/remesh_planar_patches.h>
#include <CGAL/boost/graph/graph_traits_Linear_cell_complex_for_combinatorial_map.h>

typedef CGAL::Simple_cartesian<double>                                                   Kernel;
typedef CGAL::Linear_cell_complex_traits<3, Kernel>                                      MyTraits;
typedef CGAL::Linear_cell_complex_for_bgl_combinatorial_map_helper<2, 3, MyTraits>::type LCC_3;
using Point=LCC_3::Point;

void simplify_5(LCC_3& lcc)
{
    CGAL::Linear_cell_complex_incremental_builder_3<LCC_3> ib(lcc);
    ib.add_vertex(Point(0,0,0)); // vertex 0
    ib.add_vertex(Point(1,0,0)); // vertex 1
    ib.add_vertex(Point(0,1,0)); // vertex 2
    ib.add_vertex(Point(0,0,1)); // vertex 3
    ib.add_vertex(Point(0,0,-1)); // vertex 4
    ib.add_vertex(Point(0.3,0,0)); // vertex 5

    ib.begin_surface();
    ib.add_facet({0,5,3});  
    ib.add_facet({5,1,3});
    ib.add_facet({1,2,3});
    ib.add_facet({0,3,2});
    ib.add_facet({0,2,5});
    ib.add_facet({5,2,1});
    ib.end_surface();
    ib.begin_surface();
    ib.add_facet({0,4,5});  
    ib.add_facet({5,4,1});
    ib.add_facet({1,4,2});
    ib.add_facet({0,2,4});
    ib.add_facet({0,5,2});
    ib.add_facet({5,1,2});
    ib.end_surface();
    lcc.display_characteristics(std::cout)<<std::endl;

    // for(auto vv = lcc.one_dart_per_cell<1>().begin(); vv != lcc.one_dart_per_cell<1>().end(); ++vv)
    // {
    //     if(lcc.point(vv) == Point(0.3, 0, 0))
    //     {   
    //         for(auto ve = lcc.one_dart_per_incident_cell<1,0>(vv).begin(); ve != lcc.one_dart_per_incident_cell<1,0>(vv).end(); ++ve)
    //         {
    //             lcc.remove_cell<1>(ve);
    //         }
    //         break;
    //     }
    // }
}

int main()
{
  LCC_3 lcc;

  //simplify_1(lcc);
  //simplify_2(lcc);
  //simplify_3(lcc);
  //simplify_4(lcc);
  simplify_5(lcc);
  //simplify_6(lcc);

  lcc.display_characteristics(std::cout)<<std::endl;
  CGAL::draw(lcc);

  return EXIT_SUCCESS;
}
```

**Comment by gdamiand** [comment]
The problem in your code is to modify the lcc during the loop using a one_dart_per_cell iterator.

The solution is to split the loop in two parts:
1) iterate through the lcc, and keep one dart per edge you want to remove in an std::vector
2) iterate through the std::vector and call  emove_cell<1>(

**Comment by JLYang123** [comment]
> The problem in your code is to modify the lcc during the loop using a one_dart_per_cell iterator.
> 
> The solution is to split the loop in two parts:
> 
> 1. iterate through the lcc, and keep one dart per edge you want to remove in an std::vector
> 2. iterate through the std::vector and call  remove_cell<1>

Thanks, it works.
