### ISSUE TITLE
Arrangement:  Missing documentation of CORE_algebraic_number_traits

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#7659]
## Issue Details

The class `CORE_algebraic_number_traits`  is mentioned in the Arrangement [User Manual](https://doc.cgal.org/latest/Arrangement_on_surface_2/index.html) and used in examples without being documented.

Fixes could be added to PR #7660

## Environment

* CGAL version:  master

**Comment by afabri** [comment]
I am also wondering about the link for `is_valid()` [here](https://doc.cgal.org/latest/Arrangement_on_surface_2/classCGAL_1_1Arrangement__on__surface__2.html)

**Comment by efifogel** [comment]
1. Indeed missing. I'll add.
2. This link (to is_valid()) is erroneous. I'll remove it.
   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/
