### ISSUE TITLE
Size overflow for large images

### ISSUE THREAD

**Issue by rdengate** [CGAL/cgal#7664]
Imagine you have an inr file with dimensions 1500 x 1500 x 1500, which you are trying to read in, for mesh generation.

In `ImageIO_impl.h`, from line 1245, we have:
```c++
unsigned long size, nread;

if(im->openMode != OM_CLOSE) {
    size = im->xdim * im->ydim * im->zdim * im->vdim * im->wdim;
```

Let's say `vdim` is 1 and `wdim` is 2. Size should then be 6,750,000,000, but anything over 4,294,967,295 overflows. When the wrong value for size is used, the image is not read in correctly, which later results in an access violation exception.  

If size_t (unsigned long long) is used for size instead of unsigned long, the value of size is stored correctly.

I propose changing this (in three places) in `ImageIO_impl`. If this is an acceptable solution, I'm happy to lodge a pull request.

**Comment by lrineau** [comment]
You are right. We would welcome a pull-request on that issue. Thanks @rdengate

**Comment by rdengate** [comment]
Thanks @lrineau. I have created a pull request, please see https://github.com/CGAL/cgal/pull/7677.
