### ISSUE TITLE
The tree size of a kd tree didn't update after removal of points.

### ISSUE THREAD

**Issue by RomaLzhih** [CGAL/cgal#7676]
## Issue Details

The tree size of a kd tree didn't update after the removal of points. The tree size returned from [interface](https://github.com/CGAL/cgal/blob/v5.5.2/Spatial_searching/include/CGAL/Kd_tree.h#L685) is the length of the points vector stored in the tree, which does not be updated within the [remove function](https://github.com/CGAL/cgal/blob/v5.5.2/Spatial_searching/include/CGAL/Kd_tree.h#L499).   

Change the return value to `tree.root()->num_items()` resolves the problem.

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): centos
* Compiler: clang++
* Release or debug mode: debug
* Specific flags used (if any): tbb parallel tag
* CGAL version: latest
* Boost version: latest
* Other libraries versions if used (Eigen, TBB, etc.): tbb

**Comment by mglisse** [comment]
Calling `root()->num_items()` has a complexity linear in the size of the tree, whereas the current `size()` takes constant time, so we should try to avoid it. One possibility would be to call the costly version only if `removed_` is true (assuming that works). Calling `size()` multiple times on a tree that has had points removed would be costly, so we could make `size()` compact the tree if `removed_`, but that would be bad for the complexity in other scenarios. The best may be to add a field to the tree and maintain its size. Or just document that `size()` may return something too big after removals.
