### ISSUE TITLE
Mesh_criteria_3 does not mention sizing field

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#7679]
The named parameter `edge_size` is not documented as if it could accept a sizing field. It is used in this context in `mesh_polyhedral_domain_with_features_sizing.cpp`. Would it make sense to documented `edge_sizing_field` instead? The code currently works with both. `Sizing_field_with_aabb_tree` mentioned `edge_size` in its doc.

**Comment by lrineau** [comment]
I do not understand your point.

The documentation of `edge_size` is:
> a scalar field (resp. a constant) providing a space varying (resp. a uniform) upper bound for the lengths of curve edges.

See https://doc.cgal.org/5.6/Mesh_3/classCGAL_1_1Mesh__criteria__3.html

So it is already documentation that it can be a scalar field, right?

**Comment by sloriot** [comment]
My bad, I probably misread.
