### ISSUE TITLE
Regression in CGAL 5.6 Mesh_3 with domain derived from Polyhedron_complex_mesh_domain_3

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#7681]
Reverting https://github.com/CGAL/cgal/commit/39c0a9fb33ca2f253dd8db7ed6ba04f5fae90d9e
makes it work.

I suspected that the band aid (https://github.com/CGAL/cgal/commit/1f258bc84d2bf8cd39fbeb80d62118c3f4da3390 should also be applied to Polyhedron_complex_mesh_domain_3 (as I did not touch init functions in my domain) but it inherits also the functor from `Polyhedral_mesh_domain_3`.

**Comment by sloriot** [comment]
@MaelRL investigated and it turns out that the infinite loop is coming from my custom domain. However, he is not sure if the previous behavior was not done on purpose and there might be other domain defined that could be affected by the behavior change. This needs to be discussed with @lrineau and @janetournois .

**Comment by janetournois** [comment]
The remaining questions about initialization have been solved in PR #7552
