### ISSUE TITLE
All face colors are plotted in blue though colors for individual faces are specified

### ISSUE THREAD

**Issue by lxmedai** [CGAL/cgal#7687]
## Issue Details

_Face colors don't change with face color map specification._ ¨
My code is based on the example code for "segmentation_from_sdf_values_SM_example.cpp" with slight modification introducing running time measurement and face color specification. 

Result I got from the console: 
The input mesh has been segmented to 3 parts within 28 ms
Colors for faces exist: 1
f0: 100 100 100 255 f1: 100 100 100 255 f2: 100 100 100 255... (skipped all the rest outputs)
The plotted mesh from the "surface_mesh basic viewer" has only blue faces. 
If I skipped all the color specifications, all faces would have color specification of 0 0 0 255.
I would like to know what should I do to get the correct colors in the plot. Thanks in advance!

## Source Code

```c++
#include <CGAL/Simple_cartesian.h>
#include <CGAL/Surface_mesh.h>
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/mesh_segmentation.h>
#include <CGAL/property_map.h>
#include <CGAL/draw_surface_mesh.h>
#include <CGAL/IO/Color.h>
#include <iostream>
#include <fstream>
#include <chrono>

using namespace std;
using namespace boost;
using namespace CGAL;

typedef Exact_predicates_inexact_constructions_kernel  Kernel;
typedef Kernel::Point_3  Point;
typedef Surface_mesh<Point>  SM;
typedef graph_traits<SM>::face_descriptor  face_descriptor_SM;
typedef graph_traits<SM>::vertex_descriptor  verterx_descriptor_SM;

int segmentation_on_SM(const string filename, const size_t num_of_clusters) {
    //  use number_of_clusters for soft clustering
    SM mesh;
    if (!IO::read_polygon_mesh(filename, mesh) ||
        !is_triangle_mesh(mesh))
    {
        cerr << "Invalid input file." << endl;
        return EXIT_FAILURE;
    }
    typedef SM::Property_map<face_descriptor_SM, double> Facet_double_map;
    Facet_double_map sdf_property_map;
    sdf_property_map = mesh.add_property_map<face_descriptor_SM, double>("f:sdf").first;
    // compute SDF values
    CGAL::sdf_values(mesh, sdf_property_map, 2.0 / 3.0 * CGAL_PI, 25, true);
    // create a property-map for segment-ids
    typedef SM::Property_map<face_descriptor_SM, size_t> Facet_int_map;
    Facet_int_map segment_property_map = mesh.add_property_map<face_descriptor_SM, size_t>("f:sid").first;;
    chrono::steady_clock::time_point time_start = chrono::steady_clock::now();
    //size_t number_of_segments = segmentation_from_sdf_values(mesh, sdf_property_map, segment_property_map);
    const double smoothing_lambda = 0.25;  // importance of surface features, suggested to be in-between [0,1]
    size_t number_of_segments = segmentation_from_sdf_values(mesh, sdf_property_map, segment_property_map, num_of_clusters, smoothing_lambda);
    chrono::steady_clock::time_point time_end = chrono::steady_clock::now();
    std::cout << "The input mesh has been segmented to " << number_of_segments << " parts within " << chrono::duration_cast<chrono::milliseconds>(time_end - time_start).count() << " ms" << endl;
    auto face_color_map = mesh.add_property_map<face_descriptor_SM, CGAL::Color>("f:color").first;
    bool colorExists = mesh.property_map<face_descriptor_SM, CGAL::Color>("f:color").second;
    std::cout << "Colors for faces exist: " << colorExists << endl;
    /*for (face_descriptor_SM fd : faces(mesh)) {
        std::cout << fd << ": " << face_color_map[fd] << " ";
    }*/
     // print segment-ids
    for (face_descriptor_SM fd : faces(mesh)) {
        if (segment_property_map[fd] == 0) {
            put(face_color_map, fd, IO::gray());
        }
        else if (segment_property_map[fd] == 1){
            put(face_color_map, fd, IO::blue());
        }
        else if (segment_property_map[fd] == 2) {
            put(face_color_map, fd, IO::green());
        }
        else if (segment_property_map[fd] == 3) {
            put(face_color_map, fd, IO::red());
        }
        else if (segment_property_map[fd] == 4) {
            put(face_color_map, fd, IO::orange());
        }
        else if (segment_property_map[fd] == 5) {
            put(face_color_map, fd, IO::purple());
        }
        else if (segment_property_map[fd] == 6) {
            put(face_color_map, fd, IO::violet());
        }
        else if (segment_property_map[fd] == 7) {
            put(face_color_map, fd, IO::yellow());
        }
        else if (segment_property_map[fd] == 8) {
            put(face_color_map, fd, IO::deep_blue());
        }
        else if (segment_property_map[fd] == 9) {
            put(face_color_map, fd, IO::black());
        }
        else {
            put(face_color_map, fd, IO::white());
        }
        std::cout << fd <<": " << face_color_map[fd] << " ";
    }
    std::cout << endl;
    CGAL_USE(face_color_map);
    CGAL::draw(mesh);
    return EXIT_SUCCESS;
}

int main()
{
    // create and read Polyhedron
    const string filename = "cactus.off";
    const size_t num_clusters_init = 5;
    int result = segmentation_on_SM(filename, num_clusters_init);
    return EXIT_SUCCESS;
}
```
## Environment

* Operating system (Windows 64 bits):
* Compiler: visual studio-2022
* Release or debug mode:
* Specific flags used (if any):
* CGAL version: 15.6
* Boost version: 1.83
* Other libraries versions if used (Eigen, TBB, etc.): -

**Comment by gdamiand** [comment]
Just press the M key, to disable the mono color mode.
(maybe we can disable this mode by default to avoid this kind of problem)

![image](https://github.com/CGAL/cgal/assets/944526/9125193e-b963-4147-8299-bf4aa12cc9f4)

**Comment by lxmedai** [comment]
> Just press the M key, to disable the mono color mode. (maybe we can disable this mode by default to avoid this kind of problem)

Thanks a lot! It really helps! My second question related to this is, is there a simple way to disable the monochrome mode given the over example code so I can avoid pressing the m key everytime when I am testing different parameters for segmentation?

**Comment by gdamiand** [comment]
For now this is not directly possible. This will be one feature of the next version of basic viewer.
What you can do, copy/paste in your code the code of draw from the file draw_surface_mesh.h (and change its name):
<code>
template<class K>
void mydraw(const Surface_mesh<K>& amesh,
          const char* title="Surface_mesh Basic Viewer",
          bool nofill=false)
{
    CGAL::Qt::init_ogl_context(4,3);
    int argc=1;
    const char* argv[2]={"surface_mesh_viewer", nullptr};
    QApplication app(argc,const_cast<char**>(argv));
    SimpleFaceGraphViewerQt mainwindow(app.activeWindow(), amesh, title, nofill,
                                       Surface_mesh_basic_viewer_color_map<K>(amesh));
/// HERE
    mainwindow.show();
    app.exec();
}
</code>

Then, before to call the show() method, you can modify the parameters of the mainwindow.

For example you can call mainwindow.set_use_mono_color(false). (HERE in the code above)

Note that this is un-official solution that will be broken in the next version, but it can solves your problem for now.

**Comment by lxmedai** [comment]
Thanks a lot for the help! Though I haven't tested it yet, I believe I can close this issue already. Thanks again!
