### ISSUE TITLE
Surface_mesh: stream support

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#769]
The following code compiles:
```
Surface_mesh m;
std::ifstream input("toto.off");
input >> m;
```
but the  mesh stays empty.
This should produce  a  compilation error or work.

@afabri

**Comment by afabri** [comment]
Doesn't it work for a specific file ?
The operator exists, and unless I am wrong we use it in the examples and the testsuite.

**Comment by sloriot** [comment]
I tried with the elephant yesterday and it was not working.

**Comment by sloriot** [comment]
I can no longer reproduce it.
