### ISSUE TITLE
Polygon_mesh_processing: unknown group in documentation

### ISSUE THREAD

**Issue by albert-github** [CGAL/cgal#7692]
Adding a warning to doxygen gives me the warning:
```
.../Polygon_mesh_processing/include/CGAL/polygon_mesh_processing.h:66: warning: Found non-existing group 'namedparameters' for the command '@ingroup', ignoring command
```
and I cannot find `\defgroup` or `\addtogroup` for `namedparameters`.

-    where does this `\ingroup` belong to or should the line be removed?

It now lands on (as it would without the `\ingroup` command): doc_output/Polygon_mesh_processing/polygon__mesh__processing_8h.html

**Comment by afabri** [comment]
@sloriot, do you agree that we can just remove the whole doumentation block [here](https://github.com/lrineau/cgal/blob/d6ebf17baa2191b317fa23aa5da6c2bd4f4c67f9/Polygon_mesh_processing/include/CGAL/polygon_mesh_processing.h#L54)?

**Comment by albert-github** [comment]
The code of https://github.com/doxygen/doxygen/pull/10289 has been integrated in master on GitHub so the results show up in the overnight documentation build.

**Comment by albert-github** [comment]
Might be that here there should be something similar to the BGL Package where we see:
```
BGL/doc/BGL/NamedParameters.txt:\defgroup bgl_namedparameters Named Parameters
```
