### ISSUE TITLE
automatic converting 27-sheeted covering to 1-sheeted covering without warning

### ISSUE THREAD

**Issue by gy114** [CGAL/cgal#7695]
## Issue Details

I established a 3d periodic Delaunay mesh using incremental method. Since there's no initializer to assign `info()` when inserting the points, I have to user `unique_cells_begin()` iterator. Then I need to assign the `info()` to all the virtual points. When large-number of points are inserted, the mesh automatically converts to 1-sheeted covering without warning. This caused memory leak. 

## Source Code (Using CGAL 6.0)

```cpp
void main() 
{
    // Domain specification
    Iso_cuboid domain(0,0,0,1,1,1);
    // Setup the random generator.
    std::random_device rd;
    std::mt19937 gen(rd());
    std::uniform_real_distribution<> dis(0, 1);
    std::uniform_real_distribution<double> azimuth_dis(0.0, 2.0 * CGAL_PI);
    std::uniform_real_distribution<double> polar_dis(-1.0, 1.0);
    P3_Delaunay T(domain);  // Create an empty P3_Delaunay triangulation.
    const int num_points = 10000;
    int count = 0;
    for (int i = 0; i < num_points; ++i) {
        double x = dis(gen);
        double y = dis(gen);
        double z = dis(gen);

        double azimuth = azimuth_dis(gen);
        double cos_polar = polar_dis(gen);
        double polar = std::acos(cos_polar);

        double vx = std::sin(polar) * std::cos(azimuth);
        double vy = std::sin(polar) * std::sin(azimuth);
        double vz = std::cos(polar);

        ExactVector_3 newInfo = ExactVector_3{vx, vy, vz};

        P3_Delaunay::Vertex_handle vh = T.insert(P3_Point(x, y, z));

        vh->info() = newInfo;
        std::cout << count++ << " points generated.\n";
    }

    count = 0;
     // Without the following code, accessing the virtual points may cause memory leak. 
    if (T.is_1_cover()) {
        T.convert_to_27_sheeted_covering();
        cout << "Converted to 27-sheeted covering.\n";
    }

    // Now we go through the unique vertices, and copy its info() to all of its images.
    for (auto vit = T.vertices_begin(); vit != T.vertices_end(); ++vit) {

            auto vh = T.get_original_vertex(vit);
            if (vh != vit)
                vit->info() = vh->info();
            //std::cout << count++ << " images info updated\n";

    }

    // Now we test to add some information to the unique cells.
    unsigned long id = 0;
    for (auto c = T.unique_cells_begin(); c != T.unique_cells_end(); ++c) {
        c->info() = (double)id++;
    }
}
```

**Comment by MaelRL** [comment]
I am not sure I understand: if you are in 1-cover, there are no longer any virtual vertices; you only have each canonical vertex once, and the ranges `all_vertices` and `unique_vertices` are identical. You shouldn't try to access any virtual vertex if you are in 1-cover.

**Comment by MaelRL** [comment]
It is not about the number of points but rather a covering criterion : you need to avoid edges that are connecting periodical copies of the same canonical vertex as this is not representable in a single cover, see Section [Representation](https://doc.cgal.org/latest/Periodic_3_triangulation_3/index.html#title1) of the P3T3 doc.

You can also choose to insert a set of fixed points to ensure that you are in 1-cover, then insert your own points, and remove the scaffolding at the end as to remain in 1-cover the whole time, see Section [Large Point Sets](https://doc.cgal.org/latest/Periodic_3_triangulation_3/index.html#title19).
