### ISSUE TITLE
Appearance of "Set of Faces" in documentation.

### ISSUE THREAD

**Issue by albert-github** [CGAL/cgal#7701]
Looking at the documentation of the Triangulation package (Triangulation/index.html in the 1.8.13 doxygen version as in the 1.9.6 / master version this part is not present see proposed pull request #7700):
![image](https://github.com/CGAL/cgal/assets/5223533/b668f8d0-4947-4a5f-a998-31034971dd00)

the gray background is a bit strange and comes from the fact that a `<blockquote>` is used (in Triangulation/doc/Triangulation/Triangulation.txt).

Probably better would bee something like:
![image](https://github.com/CGAL/cgal/assets/5223533/94fb3290-247a-44df-acf4-56e438fb7edc)

resulting from:

```
Possible values of \f$d\f$ (the <I>current dimension</I> of the triangulation) include
\par
<table cellspacing="0" cellpadding="0">
<tr>
<td><B>\f$d=-2\f$</B><td>&nbsp;<td> This corresponds to an empty
triangulation data structure.
</tr>
<tr>
<td><B>\f$d=-1\f$</B><td>&nbsp;<td> This corresponds to an abstract simplicial
complex reduced to a single vertex.
</tr>
<tr>
 <!---  and a single full cell. In a geometric triangulation, this vertex corresponds to the vertex at infinity. -->
<td><B>\f$d=0\f$</B><td>&nbsp;<td> This corresponds to an abstract simplicial
complex including two vertices, each corresponding to a full cell;
the two full cells being neighbors of each other. This is the unique
triangulation of the \f$ 0\f$-sphere.
</tr>
<tr>
<!--- (geometrically, the finite vertex and the infinite vertex), -->
<td><B>\f$ 0< d \le D\f$</B><td>&nbsp;<td> This corresponds to a triangulation of
the sphere \f$ \mathbb{S}^d\f$.
</tr>
</table>
```

**Comment by albert-github** [comment]
When using just the `<dl>` preceded by a `\par` we get:
![image](https://github.com/CGAL/cgal/assets/5223533/07d63ffe-7b62-45cd-8bd1-c15c9b10b4ec)

This doesn't look bad at all, just that by using a `<table >` it is a bit more compact.
The most important though is, in my opinion, to get ride of the gray area.

**Comment by lrineau** [comment]
And semantically `<blockquote>` was really the wrong element to use.

As for the compactness of `<dl>`, that is just a matter of CSS rules. See for example https://stackoverflow.com/questions/1713048/how-to-style-dt-and-dd-so-they-are-on-the-same-line

**Comment by albert-github** [comment]
- so the `<blockquote>` part is clear
- the `<dl>` styling through css is something I'm not that in favor of. For this case it might work but when applying it generally and having a `<dt>` with a longer part its will (as it would with a table!) take more place for the initial column. In that case a multi line `<dl>` might be better.
