### ISSUE TITLE
copy_face_graph from cartesian to epeck surface mesh produces self-intersection

### ISSUE THREAD

**Issue by pentacular** [CGAL/cgal#7723]
## Issue Details

In some cases graphs test true for self intersection after copy_face_graph from cartesian to epeck surface mesh.

My expectation was that given that cartesian double points are coarser than epeck points that it should be impossible, since there should be a unique epeck point for every cartesian point, and ordering would be preserved.

Is this behavior expected?

If so, why?
And in which circumstances should we expect it?
And what would be the best way to correct it?

If not, please let me know and I will try to find a minimal mesh that produces this behavior.
(So far I can only find very large graphs)

Thanks.

## Source Code

```
typedef CGAL::Simple_cartesian<double> Cartesian_kernel;
typedef Cartesian_kernel::Point_3 Cartesian_point;
typedef std::vector<Cartesian_point> Cartesian_points;
typedef CGAL::Surface_mesh<Cartesian_point> Cartesian_surface_mesh;

typedef CGAL::Exact_predicates_exact_constructions_kernel Epeck_kernel;
typedef Epeck_kernel::Point_3 Point;
typedef CGAL::Surface_mesh<Point> Surface_mesh;

int test(const Cartesian_surface_mesh& cartesian_mesh) {
  if (CGAL::Polygon_mesh_processing::does_self_intersect(cartesian_mesh)) {
    return 2;
  }

  Surface_mesh mesh;
  copy_face_graph(cartesian_mesh, mesh);

  if (CGAL::Polygon_mesh_processing::does_self_intersect(mesh)) {
    return 1;
  }
  
  return 0;
}
```

I expect test to return 0, but find that it sometimes returns 1.

Unfortunately I have not yet found a reasonably small illustrative mesh.

## Environment

#define CGAL_VERSION 6.0-I-900
#define CGAL_VERSION_NR 1060000900
#define CGAL_SVN_REVISION 99999
#define CGAL_RELEASE_DATE 20230901

**Comment by afabri** [comment]
Can you test with `Exact_predicates_inexact_constructions_kernel`, as for the test you need certified predicates.

**Comment by lrineau** [comment]
Andreas suggested that maybe the issue is the first test:
```c++
  if (CGAL::Polygon_mesh_processing::does_self_intersect(cartesian_mesh)) {
    return 2;
  }
```
That line is evaluated using `CGAL::Simple_cartesian<double>`, that does not have exact predicates. Probably `cartesian_mesh` was already self-intersecting. Andreas suggested that you replace `CGAL::Simple_cartesian<double>` by `CGAL::Exact_predicates_inexact_constructions_kernel`, in your code. The later also uses `double` for coordinates.

**Comment by pentacular** [comment]
Yes, I think this is the issue.

Thanks.
