### ISSUE TITLE
Why CGAL::Surface_mesh<KernalCGAL::Point_3> can not add_face?

### ISSUE THREAD

**Issue by StromanStroman** [CGAL/cgal#7741]
_Please use the following template to help us solving your issue._

I have a VTK.
I create a` CGAL::Surface_mesh<KernalCGAL::Point_3>` mesh using the VTK.
I want to insert a face into the mesh.
Finally I want to convert the mesh to a result VTK.
There is a hole in the mesh.The hole is very simple,just a lack of a triangle.So I use the three boundary vertexes value of the hole created a new triangle face cell.I want to insert the new created face into the mesh.
But I can not insert the new created face,using add_face,whether original face or reverse the face.So I get puzzled.
the hole boundary vertex index is 315,316,494.
Here is the VTK file:
[output__1_.zip](https://github.com/CGAL/cgal/files/12710720/output__1_.zip)

How can I insert the face?What reason make me failed?

_Describe your issue. Please be specific (compilation error, runtime error, unexpected behavior, wrong results, etc.)._

```
face_descriptor RepairSurface::RSCGALManager::insertAFace(const vertex_descriptor vertexes[], const size_t LENGTH)
{
	ICOUT << vertexes[0] << "," << vertexes[1] << "," << vertexes[2] << std::endl;
	face_descriptor result = this->mesh.add_face(vertexes[0], vertexes[1], vertexes[2]);
	if (result == Mesh::null_face() || !this->mesh.is_valid(result))
	{
		result = this->mesh.add_face(vertexes[0], vertexes[2], vertexes[1]);
	}
	return result;
}
```

_If your issue arises by using CGAL in your own source code, please provide a minimalist example that we can compile easily to reproduce the bug. If your issue arises from using a CGAL program (demo, example, etc.), please let us know which one. Helping you solving an issue is much easier and efficient if we can reproduce it._

## Environment

* Windows 64 bits:Windows 11
* Compiler:Visual Studio 2022 community
* Release or debug mode:debug mode
* Specific flags used (if any):not any
* CGAL version:5.4
* Boost version:1.79.0
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by afabri** [comment]
Can you please put a self-contained example on gist.github.com, together with data so that we can try to reproduce and fix.

**Comment by StromanStroman** [comment]
> Can you please put a self-contained example on gist.github.com, together with data so that we can try to reproduce and fix.

There are all necessary files [here](https://gist.github.com/StromanStroman/d1cc19e073ac3d0840089593217b0373)
You can put them into a new project using C++.
output__1_.vtk is the input vtk file.
If any questions,please contact me.

**Comment by StromanStroman** [comment]
> Can you please put a self-contained example on gist.github.com, together with data so that we can try to reproduce and fix.

what you need do is just change output_1_.vtk path in cpp source code。

**Comment by afabri** [comment]
Your triangles do not form a 2-manifold.    The patch of 4 triangles I colored green do not conform with the blue surface
![image](https://github.com/CGAL/cgal/assets/3263539/4acfb446-c6b3-4187-877c-b23d7347b736)
What you see in red are non-manifold vertices.

**Comment by afabri** [comment]
In case all you want is to read a vtk file in a `CGAL::Surface_mesh`  you might use the `read_VTK()` function I just added in the PR #7826 and have a look at this [example call](https://gist.github.com/afabri/f435935346b0d7e917d515ba3513ac88).

**Comment by StromanStroman** [comment]
> In case all you want is to read a vtk file in a `CGAL::Surface_mesh` you might use the `read_VTK()` function I just added in the PR #7826 and have a look at this [example call](https://gist.github.com/afabri/f435935346b0d7e917d515ba3513ac88).

Thank you very much.

**Comment by StromanStroman** [comment]
Thank you very much
