### ISSUE TITLE
Reference to moka modeller

### ISSUE THREAD

**Issue by albert-github** [CGAL/cgal#7764]
In the documentation there are 2 references to the moka-modeller:
```
Combinatorial_map/doc/Combinatorial_map/Combinatorial_map.txt
Generalized_map/doc/Generalized_map/Generalized_map.txt
```
In the documentation this is in:
```
Combinatorial_map/index.html
Generalized_map/index.html
```
though the reference is redirected from `https://moka-modeller.sourceforge.net/` to `https://sourceforge.net/directory/research/`

- What is the correct reference?

I found:
- https://github.com/gdamiand/moka
- https://projet.liris.cnrs.fr/moka/index.php

(Maybe @gdamiand can shine a light)

**Comment by gdamiand** [comment]
https://projet.liris.cnrs.fr/moka/index.php is the web site; and https://github.com/gdamiand/moka the source repository.

(indeed references to sourceforge are old).

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request https://github.com/CGAL/cgal/pull/7769
