### ISSUE TITLE
Non existing link to the LASLib / LAStools

### ISSUE THREAD

**Issue by albert-github** [CGAL/cgal#7770]
In  Documentation/doc/Documentation/Third_party.txt(Manual/thirdparty.html) there is a link to:
```
https://rapidlasso.com/lastools
```
but this link does not exist anymore.

- where to link to? (maybe https://rapidlasso.de/product-overview/ ?)

**Comment by lrineau** [comment]
Maybe https://lastools.github.io/

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #7778
