### ISSUE TITLE
Remove RS/RS3 from CGAL (was Non existing link to RS / RS3)

### ISSUE THREAD

**Issue by albert-github** [CGAL/cgal#7771]
In Documentation/doc/Documentation/Third_party.txt(Manual/thirdparty.html) there is a link to:
```
http://vegas.loria.fr/rs/
```
but this link does not exist anymore.

**Comment by afabri** [comment]
I found RS and RS3 on Fabrice Rouiller's [Software](https://who.rocq.inria.fr/Fabrice.Rouillier/software.php) page, but I have no idea about its availability.   @pougetma are you aware of colleagues in Nancy using it?

**Comment by afabri** [comment]
I also sent a mail to Fabrice.

**Comment by albert-github** [comment]
Any progress on this as the link is still present in the documentation (version 6.0) of CGAL (Documentation build CGAL-6.0-I-253)

**Comment by lrineau** [comment]
> I also sent a mail to Fabrice.

@afabri Was there any answer?

**Comment by afabri** [comment]
For licensing reasons Fabrice would have to provide a binary with just the functions we need.  I think we should just remove it.

**Comment by albert-github** [comment]
>  I think we should just remove it.

Do you mean the RS / RS3 usage code from CGAL?

**Comment by afabri** [comment]
Yes, let's just plain remove it as a cleanup.

**Comment by afabri** [comment]
@pougetma do I understand correctly that the only models for the concept [AlgebraicKernel_d_1](https://doc.cgal.org/latest/Algebraic_kernel_d/classAlgebraicKernel__d__1.html)  depend on RS ?

**Comment by afabri** [comment]
I just saw that other classes state that they are model.   [link](https://doc.cgal.org/latest/Algebraic_kernel_d/classCGAL_1_1Algebraic__kernel__d__1.html)

**Comment by afabri** [comment]
Does anybody know where we need NTL  (@sloriot )
