### ISSUE TITLE
Non existing link to open numerical library

### ISSUE THREAD

**Issue by albert-github** [CGAL/cgal#7772]
In Documentation/doc/Documentation/Usage.txt(Manual/usage.html) there is a link to:
```
http://alice.loria.fr/index.php/software/4-library/23-opennl.html
```
but this link does not exist anymore.

**Comment by afabri** [comment]
We should link to https://github.com/BrunoLevy/geogram/wiki/OpenNL

**Comment by albert-github** [comment]
I got the impression that the reference is to the OpenNL library, isn't this a library on top of OpenNL and not the OpenNL library itself?

**Comment by lrineau** [comment]
Why does CGAL still use OpenNL, instead of Eigen? If `CGAL_EIGEN3_ENABLED` is defined, it seems that OpenNL is no longer used.

In my opinion, OpenNL could be removed completely from CGAL.

**Comment by afabri** [comment]
[Here](https://github.com/CGAL/cgal/blob/d5c8582bd2416f84cf01009c7d5e7e6b2760d45f/Surface_mesh_parameterization/include/CGAL/Surface_mesh_parameterization/LSCM_parameterizer_3.h#L144) it is hard coded.
We could probably replace it with a[ least squares solver](https://eigen.tuxfamily.org/dox-devel/group__LeastSquares.html) from Eigen.

**Comment by afabri** [comment]
In fact almost everything can be removed. There is a solver class that would remain but it calls the solver of the traits class which by default is the one using Eigen.   However it might make sense to do a benchmark for the two.
