### ISSUE TITLE
Link to support funding of GUDHI project not found

### ISSUE THREAD

**Issue by albert-github** [CGAL/cgal#7774]
In Triangulation/doc/Triangulation/Triangulation.txt (Triangulation/index.html) there is a link to:
```
https://cordis.europa.eu/project/rcn/111529/factsheet/en
```
but this link does not exist anymore.

Should this be: https://cordis.europa.eu/project/id/339025 ?

(Maybe @cjamin can shine a light on this)

**Comment by mglisse** [comment]
If you remove "factsheet" from the old URL, it redirects to the one suggested here, so that seems right.
