### ISSUE TITLE
CGAL::Polyhedron_3 to CGAL::Nef_polyhedron_3 error

### ISSUE THREAD

**Issue by cppbasketball** [CGAL/cgal#7775]
_Please use the following template to help us solving your issue._

## Issue Details

read stl file to CGAL::Polyhedron_3,create CGAL::Nef_polyhedron_3 by CGAL::Polyhedron_3,CGAL ERROR: assertion violation!

## error info:
CGAL error: assertion violation!
Expression : c.has_on(p1)&&c.has_on(p2)
File       : /opt/homebrew/Cellar/cgal/5.4/include/CGAL/Nef_S2/Sphere_segment.h
Line       : 55
Explanation: 
Refer to the bug-reporting instructions at https://www.cgal.org/bug_report.html
libc++abi: terminating due to uncaught exception of type CGAL::Assertion_exception: CGAL ERROR: assertion violation!
Expr: c.has_on(p1)&&c.has_on(p2)
File: /opt/homebrew/Cellar/cgal/5.4/include/CGAL/Nef_S2/Sphere_segment.h
Line: 55
Signal: SIGABRT (signal SIGABRT)

## Source Code

#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/Polyhedron_3.h>
#include <CGAL/Nef_polyhedron_3.h>
#include <CGAL/IO/STL/STL_reader.h>
#include <CGAL/IO/STL.h>

typedef CGAL::Exact_predicates_inexact_constructions_kernel C_Kernel;
typedef CGAL::Polyhedron_3<C_Kernel> C_Polyhedron;
typedef CGAL::Nef_polyhedron_3<C_Kernel> C_Nef_Polyhedron;

C_Polyhedron poly;
CGAL::IO::read_STL("/Users/ysd/Desktop/test.stl", poly);
C_Nef_Polyhedron nef_poly(poly); // crashes

## Environment

* Operating system: Mac OS M1
* Compiler: CLion
* CGAL version: 5.6
* test.stl file:
[test.stl.zip](https://github.com/CGAL/cgal/files/12852111/test.stl.zip)
<img width="1647" alt="Screenshot 2023-10-10 at 10 29 37" src="https://github.com/CGAL/cgal/assets/147459828/90fb706b-62d2-4b24-9e75-916f801a0d44">

**Comment by lrineau** [comment]
The [documentation of `CGAL::Nef_polyhedron_3`](https://doc.cgal.org/latest/Nef_3/classCGAL_1_1Nef__polyhedron__3.html) says:
> The first parameter requires one of the following exact kernels: [Homogeneous](https://doc.cgal.org/latest/Kernel_23/structCGAL_1_1Homogeneous.html), [Simple_homogeneous](https://doc.cgal.org/latest/Kernel_23/structCGAL_1_1Simple__homogeneous.html), [Extended_homogeneous](https://doc.cgal.org/latest/Nef_2/classCGAL_1_1Extended__homogeneous.html) parametrized with [Gmpz](https://doc.cgal.org/latest/Number_types/classCGAL_1_1Gmpz.html), [leda_integer](https://doc.cgal.org/latest/Number_types/classleda__integer.html) or any other number type modeling Z, or [Cartesian](https://doc.cgal.org/latest/Kernel_23/structCGAL_1_1Cartesian.html), [Simple_cartesian](https://doc.cgal.org/latest/Kernel_23/structCGAL_1_1Simple__cartesian.html), [Extended_cartesian](https://doc.cgal.org/latest/Nef_2/classCGAL_1_1Extended__cartesian.html) parametrized with [Gmpq](https://doc.cgal.org/latest/Number_types/classCGAL_1_1Gmpq.html), [leda_rational](https://doc.cgal.org/latest/Number_types/classleda__rational.html), [Quotient](https://doc.cgal.org/latest/Number_types/classCGAL_1_1Quotient.html)<[Gmpz](https://doc.cgal.org/latest/Number_types/classCGAL_1_1Gmpz.html)> or any other number type modeling Q.

In your code, change `Exact_predicates_inexact_constructions_kernel` to `Exact_predicates_exact_constructions_kernel`.

**Comment by cppbasketball** [comment]
> The [documentation of `CGAL::Nef_polyhedron_3`](https://doc.cgal.org/latest/Nef_3/classCGAL_1_1Nef__polyhedron__3.html) says:
> 
> > The first parameter requires one of the following exact kernels: [Homogeneous](https://doc.cgal.org/latest/Kernel_23/structCGAL_1_1Homogeneous.html), [Simple_homogeneous](https://doc.cgal.org/latest/Kernel_23/structCGAL_1_1Simple__homogeneous.html), [Extended_homogeneous](https://doc.cgal.org/latest/Nef_2/classCGAL_1_1Extended__homogeneous.html) parametrized with [Gmpz](https://doc.cgal.org/latest/Number_types/classCGAL_1_1Gmpz.html), [leda_integer](https://doc.cgal.org/latest/Number_types/classleda__integer.html) or any other number type modeling Z, or [Cartesian](https://doc.cgal.org/latest/Kernel_23/structCGAL_1_1Cartesian.html), [Simple_cartesian](https://doc.cgal.org/latest/Kernel_23/structCGAL_1_1Simple__cartesian.html), [Extended_cartesian](https://doc.cgal.org/latest/Nef_2/classCGAL_1_1Extended__cartesian.html) parametrized with [Gmpq](https://doc.cgal.org/latest/Number_types/classCGAL_1_1Gmpq.html), [leda_rational](https://doc.cgal.org/latest/Number_types/classleda__rational.html), [Quotient](https://doc.cgal.org/latest/Number_types/classCGAL_1_1Quotient.html)<[Gmpz](https://doc.cgal.org/latest/Number_types/classCGAL_1_1Gmpz.html)> or any other number type modeling Q.
> 
> In your code, change `Exact_predicates_inexact_constructions_kernel` to `Exact_predicates_exact_constructions_kernel`.

Thank you very much. The problem has been resolved.
