### ISSUE TITLE
Can the CGAL library be used to solve the shortest distance from the point to the ellipsoid？

### ISSUE THREAD

**Issue by wjiangsheng** [CGAL/cgal#7779]
Can you do that with this function？：CGAL::squared_distance(T1, T2)

**Comment by janetournois** [comment]
All the geometric types `T1` and `T2` available for `CGAL::squared_distance()` are listed [here ](https://doc.cgal.org/latest/Kernel_23/group__squared__distance__grp.html#ga1ff73525660a052564d33fbdd61a4f71)

The documentation also gives some pointers to helper functions
