### ISSUE TITLE
Polyhedron demo: Mesh_3 plugin enforces a strong topological criterion

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#778]
In CGAL-4.8-beta1 and in `master`, the Mesh_3 plugin of the polyhedron demo uses a strong topological criterion. On a labeled image with triple-line, the meshing process will loop endlessly.

Should be fixed by cgal-dev@2a0b90cff1cd0abb5cde7182f7c57a21ee19a23b, pushed in another PR. Maybe we should cherry-pick that commit as soon as possible.

Cc: @afabri @janetournois @sloriot

**Comment by janetournois** [comment]
this has been done, see commit [154ad4](https://github.com/cgal/cgal/commit/
154ad4c29f9bcb44b1651afd1b81f3f3c9db7477)
