### ISSUE TITLE
Polygonal_surface_reconstruction: unknown group in documentation

### ISSUE THREAD

**Issue by albert-github** [CGAL/cgal#7791]
Analogous to the issues #7691, #7692 and #7693 adding a warning to doxygen gives me the warning
```
Polygonal_surface_reconstruction/include/CGAL/Polygonal_surface_reconstruction.h:53: warning: Found non-existing group 'PkgPolygonalSurfaceReconstruction' for the command '@ingroup', ignoring command
```

- where does this `\ingroup` belong to or should the line be removed?

**Comment by afabri** [comment]
I think we have to add the suffix `Ref`   to 'PkgPolygonalSurfaceReconstruction'   and the same in the other reported issues. @sloriot do you agree?
