### ISSUE TITLE
Testsuite errors with g++6 and -O3 CGAL_NDEBUG

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#780]
With the last testsuite of `master`, that was:
https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-132.shtml
the columns of `Ubuntu-latest-GCC6-Release` shows 11 errors.

@afabri @sloriot @sgiraudot I think that should be addressed. Are they all related to the [gcc bug #69553](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=69553)?

Even if that is related, I leave that issue open as a reminder.

**Comment by afabri** [comment]
They are all related, and all we can do is to upgrade the compiler once the bug is fixed.

**Comment by lrineau** [comment]
Should be fixed tonight. The [upstream bug was fixed][bug], and I have rebuild the Docker images.

[bug]: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=69553

**Comment by lrineau** [comment]
Fixed.

See for example the new results at https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-145.shtml
