### ISSUE TITLE
Links on download page are broken

### ISSUE THREAD

**Issue by drewish** [CGAL/cgal#782]
Looking at http://www.cgal.org/download.html the following links redirect to 404s:
* http://www.cgal.org/download/macosx.html
* http://www.cgal.org/download/linux.html
* http://www.cgal.org/download/windows.html

**Comment by lrineau** [comment]
Thanks for the report. My fault!

I am on parental leave but I will try to find a way to fix that today. 

Meanwhile, you can use the download link at the top of release notes.

**Comment by lrineau** [comment]
Fixed by commit https://github.com/CGAL/cgal-web/commit/55f78bcc747f0247290f84bdb282181c89772526 (the `cgal-web` is private).
