### ISSUE TITLE
Include for  CGAL/boost/graph/kruskal_min_spanning_tree.h failed 

### ISSUE THREAD

**Issue by tiesus** [CGAL/cgal#7828]
## Issue Details

I want to use minimal spanning trees to find points of a concave polygon. Therefore i follow this example: https://doc.cgal.org/latest/BGL/BGL_triangulation_2_2emst_8cpp-example.html
My problem is that the include of the CGAL/boost/graph/kruskal_min_spanning_tree.h file fails and the compilation leads to the following error: `fatal error: CGAL/boost/graph/kruskal_min_spanning_tree.h: No such file or directory
   19 | #include <CGAL/boost/graph/kruskal_min_spanning_tree.h>`

I installed the cgal library via `sudo apt-get install libcgal-dev`

Only the include of the boost/graph/kruskal_min_spanning_tree.h headers fails. This header is found for example: `#include <CGAL/boost/graph/graph_traits_Delaunay_triangulation_2.h>`
## Source Code
My cmake: `find_package(CGAL REQUIRED)` find cgal
`target_link_libraries(<my_library> ${catkin_LIBRARIES} gmp CGAL::CGAL)`

## Environment

* Operating system : Linux 64Bit
* Compiler: gcc
* CGAL version: 5.0.2-3 libcgal-dev
* Boost version: 1.71.0.0ubuntu2

**Comment by sloriot** [comment]
Use the doc corresponding to the release you are using:
https://doc.cgal.org/5.0.4/BGL/BGL_triangulation_2_2emst_8cpp-example.html
