### ISSUE TITLE
Surface mesh offset method

### ISSUE THREAD

**Issue by JLYang123** [CGAL/cgal#7829]
Is there any method that can perform offset on 3d surface mesh? I found extrude method is not accurate(no smooth connection around the corner), and the minkowski-sum method is a bit slow.

**Comment by sloriot** [comment]
Maybe https://doc.cgal.org/latest/Alpha_wrap_3 would work for you?

There is also the possibility to define the offset as an implicit function that can be meshed using Mesh_3. There is not header for that but there is a plugin for the Polyhedron demo that is working if you want to give it a try.

**Comment by JLYang123** [comment]
> Maybe https://doc.cgal.org/latest/Alpha_wrap_3 would work for you?
> 
> There is also the possibility to define the offset as an implicit function that can be meshed using Mesh_3. There is not header for that but there is a plugin for the Polyhedron demo that is working if you want to give it a try.

Thanks, it works well.
