### ISSUE TITLE
How to make surface_mesh smoother?

### ISSUE THREAD

**Issue by gatewayFine** [CGAL/cgal#7832]
After triangulating a plane using the Constrained Delaunay Triangulation 2 in the CGAL library, how can the generated plane be made smoother?
![image](https://github.com/CGAL/cgal/assets/124229002/e15bb886-d109-4352-884b-2c815a23edcb)

**Comment by janetournois** [comment]
Hello,
I'm not sure I understand your image. Is this the 2D triangulation + an elevation map?
We need more details to be able to help you

**Comment by gatewayFine** [comment]
Yes,I use the 2D triangulation and give point an elevation .
I used 2D triangulation, assigned elevations to each point, and combined them into Point_3 objects, which I stored in a CGAL::Surface_mesh<Point_3>. The faces generated by CDT form a mesh.

**Comment by janetournois** [comment]
Ok! Then, you can use all the fairing, remeshing, and smoothing functions available in the [Polygon Mesh Processing package](https://doc.cgal.org/latest/Polygon_mesh_processing/index.html#PMPMeshing), on the `Surface_mesh`.

**Comment by gatewayFine** [comment]
I used the CGAL::Polygon_mesh_processing::detect_sharp_edges and CGAL::Polygon_mesh_processing::smooth_shape functions, but there was no effect.
example:
![image](https://github.com/CGAL/cgal/assets/124229002/ca50ada4-3203-45ef-8d4e-7538dc3cd1b7)

**Comment by janetournois** [comment]
Maybe there are too many sharp/constrained edges so smoothing is too much constrained to change things. For experimentation, you should try smoothing without `edge_is_constrained_map`

**Comment by gatewayFine** [comment]
Will angle_and_area_smoothing change the mesh's topological structure? After using this function, I only extract the faces and points from the mesh.

**Comment by janetournois** [comment]
The [documentation](https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__meshing__grp.html#gad5a9a90355bab0613d94a6b9d73d54ed) says "Angle-based smoothing does not change the combinatorial information of the mesh. Area-based smoothing might change the combinatorial information, unless specified otherwise.".
