### ISSUE TITLE
CGAL ridge line detection example does not work with some meshes

### ISSUE THREAD

**Issue by shomedas** [CGAL/cgal#7834]
## Issue Details

CGAL ridge line detection code example  from [CGAL](https://doc.cgal.org/latest/Ridges_3/index.html) does not work with some meshes. The error is like below:

Error1: "Too few points to perform the fitting"

**Kindly suggest how to avoid this error.**

## Source Code

The code is the CGAL code at [CGAL](https://github.com/CGAL/cgal/blob/master/Ridges_3/examples/Ridges_3/Compute_Ridges_Umbilics.cpp). The mesh files are attached herewith (Simple_Chair_triangle_mesh.off).
[Simple_Chair_triangle_mesh.zip](https://github.com/CGAL/cgal/files/13202260/Simple_Chair_triangle_mesh.zip)

## Command used:

Compute_Ridges_Umbilics -f Simple_Chair_triangle_mesh.off -d 4 -m 4 -a 4 -t 4

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Linux 64bits, ubuntu 20.04
* Compiler: g++ 9.4.0
* Release or debug mode: Release
* Specific flags used (if any): None
* CGAL version: 5.6
* Boost version: 1.71
* Other libraries versions if used (Eigen, TBB, etc.): Eigen 3.3.7-2

**Comment by afabri** [comment]
The documentation says that the algorithm works on smooth surfaces.

**Comment by shomedas** [comment]
Does smooth surface mean that the mesh should not have abrupt changes or discontinuities in normals/curvatures. The mechanical part used as for [CGAL demo example](https://doc.cgal.org/latest/Ridges_3/index.html#fig__figmechanical_crest_filteredintro) has abrupt change in the direction of normals. Is it known for what types of mesh the algorithm may fail?

**Comment by afabri** [comment]
The main problem is that your mesh consists of many connected components.
![image](https://github.com/CGAL/cgal/assets/3263539/807b63a0-fb2a-44bb-98ef-7453d4710cd6)
The algorithm collects for a vertex several layers around the vertex to fit a surface. That cannot work on a surface patch with just 8 vertices.  Also when you have neighboring patches the geometric neighbors of a vertex are not neighbors in the halfedge data structure.

**Comment by afabri** [comment]
@shomedas can we close this issue?

**Comment by shomeAvataar** [comment]
Yes. It was a connected component issue. Thanks for the resolution.
