### ISSUE TITLE
Alpha_wrap precondition violation

### ISSUE THREAD

**Issue by tjerkok** [CGAL/cgal#7847]
I'm using CGAL from source code, linking the source code with CMAKE.

Using the exact example and OFF file from the [alpha wrap example](https://doc.cgal.org/latest/Alpha_wrap_3/Alpha_wrap_3_2triangle_mesh_wrap_8cpp-example.html), I get the following error:

`
CGAL error: precondition violation!
Expression : orientation(p0, p1, p2, p3) == POSITIVE
File       : C:\Users\TjerkoKieft\GitHub\Simulator\native_library\vendor\cgal-5.6\include\CGAL/Delaunay_triangulation_3.h
Line       : 1386
Explanation:
Refer to the bug-reporting instructions at https://www.cgal.org/bug_report.html
`

Any idea if this is a bug or some problem on my side?

**Comment by MaelRL** [comment]
Could you please describe your system (OS, compiler, etc.)? Anything specific to it? Any specific compilation flag? Is this CGAL on its own, or is it within a larger project that could also define some specific configuration flags?

**Comment by tjerkok** [comment]
@MaelRL My bad. The system is a x64 Windows, compiled in Visual Studio 2022 with C++17 Standard. No specific compiler flags. The example C++ file is the only file used in a Visual Studio project to build the executable file, with the CGAL source package linked using Cmake

**Comment by tjerkok** [comment]
Solved the issue! It was a problem with dependency linking.

**Comment by Petingo** [comment]
> Solved the issue! It was a problem with dependency linking.

Hello, I encountered the same issue. Do you remember how you solved the problem?

**Comment by tjerkok** [comment]
@Petingo Sorry for the late response. I solved it by placing the libgmp-10.dll and libmpfr-4.dll (found in [the latest release](https://github.com/CGAL/cgal/releases) in the same directory as my build target (which is an executable created with CMake and Visual Studio). There is probably a more elegant way to do this, but this way good enough for my purpose.

**Comment by afabri** [comment]
How can not having a dll in the right place be related to an assertion?

**Comment by tjerkok** [comment]
My bad, didn't explain it totally. The assertion came from not using the correct kernel Exact_predicates_inexact_constructions_kernel, which I couldn't use because that would give me an error of missing dll's when executing my program.

**Comment by Petingo** [comment]
Hi @tjerkok & @afabri,
Thanks a lot for the info and explanation!
I think my situation is different. I'm trying to cross compile AlphaWrap for an Web App using Emscripten, and it seems that the interval_nt arithmetic is producing incorrect result after compiling to WebAssembly. (I found that by running the same program in WebAssembly and my Ubuntu machine and compare the intermediate results.) I'm aware that Emscripten has some issues when handling floating point numbers, but I'm not sure how to resolve this problem at the moment. I'll be very grateful if you have any ideas about my problem!
