### ISSUE TITLE
Issue with CGAL ITK_Support

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#7855]
### Discussed in https://github.com/CGAL/cgal/discussions/7854

<div type='discussions-op-text'>

<sup>Originally posted by **oarcelus** November 10, 2023</sup>
I am trying to build a CGAL program that uses ITK.

I downloaded and setup everything with vcpkg for x64. When trying to configure my Cmake folder the following error appears.

```
CMake Error at C:/dev/vcpkg/installed/x64-windows/share/cgal/CGAL_ITK_support.cmake:4 (set_target_properties):
  Property INTERFACE_LINK_LIBRARIES may not contain link-type keyword
  "optimized".  The INTERFACE_LINK_LIBRARIES property may contain
  configuration-sensitive generator-expressions which may be used to specify
  per-configuration rules.
Call Stack (most recent call first):
  CMakeLists.txt:52 (include)
```

Does this mean that I need to install ITK in ´debug´ or ´general´ mode?</div>

----

That is a bug from about file `CGAL_ITK_support.cmake`. That file should use the imported targets created by `ITKConfig.cmake`.

**Comment by lrineau** [comment]
We should extend our testsuite process. We have loose the testing of all 3rd party libraries on Windows since the switch to `christo`.

**Comment by janetournois** [comment]
However it has been installed manually, not via vcpkg

**Comment by janetournois** [comment]
Hello @oarcelus
thanks for the report.
We have prepared a pull-request that should fix the issue you are facing : #7858 
Can you please give it a try and tell us if it fixes the issue with your local configuration?
Thanks!

**Comment by oarcelus** [comment]
I have changed the CMakeLists.txt file in the same way as in the merge request.
`if(TARGET CGAL::CGAL_ImageIO)

  if(CGAL_ImageIO_USE_ZLIB)

    create_single_source_cgal_program("mesh_from_labeled_3d_array.cpp")
    target_link_libraries(mesh_from_labeled_3d_array PUBLIC CGAL::Eigen3_support) 

    create_single_source_cgal_program("mesh_from_labeled_3d_array_with_subdomain.cpp")
    target_link_libraries(mesh_from_labeled_3d_array_with_subdomain PUBLIC CGAL::Eigen3_support) 

    find_package(ITK NAMES ITK InsightToolkit
                     QUIET COMPONENTS ITKCommon ITKThresholding ITKSmoothing ITKImageIntensity)
    if(ITK_FOUND)
      message(STATUS "ITK found")
      include(${ITK_USE_FILE})
      set(ITK_LIBS ITKCommon ITKSmoothing ITKImageIntensity)

      create_single_source_cgal_program("mesh_from_labeled_3d_array_with_weights.cpp")
      target_link_libraries(mesh_from_labeled_3d_array
                            PUBLIC CGAL::Eigen3_support
                            ${ITK_LIBS})
    endif()
  endif()
else()`

I still get an error when building the last `mesh_from_labeled_3d_array_with_weights.cpp` program. The error log is huge, this is a samplee

mesh_from_labeled_3d_array_with_weights.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) void __cdecl itk::OutputWindowDisplayWarningText(char const *)" (__imp_?OutputWindowDisplayWarningText@itk@@YAXPEBD@Z) referenced in function "protec
ted: virtual class std::vector<double,class std::allocator<double> > __cdecl itk::GaussianOperator<unsigned char,3,class itk::NeighborhoodAllocator<unsigned char> >::GenerateCoefficients(void)" (?GenerateCoefficients@?$GaussianOperator@E$02V?$NeighborhoodAlloc 
ator@E@itk@@@itk@@MEAA?AV?$vector@NV?$allocator@N@std@@@std@@XZ) [C:\Users\oarcelus\ElectrodeBuilder\meshing_cgal\build\mesh_from_labeled_3d_array_with_weights.vcxproj]

**Comment by oarcelus** [comment]
Sorry, I tried installing all of the Mesh_3 programs and there were no errors such as the abovementioned ones. The problem must be on my side.
