### ISSUE TITLE
Options of skeleton in Cgal demo 

### ISSUE THREAD

**Issue by zahrakheyrollahi** [CGAL/cgal#7856]
## Issue Details

Implementation of the three-dimensional skeleton in the CGAL DEMO program has this option 
is medially centered 
run one itteration 
skeletonize 
segment 
What are these options to do?

**Comment by debx4** [comment]
Skeletonize the shape to compute its medial axis.
Refine and verify the skeleton by running iterations and checking if it is medially centered.
Use the skeleton to segment the shape into parts.
