### ISSUE TITLE
emplement Each vertex of the input surface is associated to a skeleton vertex in mean curvature skeleton cgal

### ISSUE THREAD

**Issue by zahrakheyrollahi** [CGAL/cgal#7862]
Access to any entry level vertex associated with the skeleton vertex

Because it is mentioned on the site(  https://doc.cgal.org/latest/Surface_mesh_skeletonization/index.html    ) and it is shown in the output figure
![correspondence-1](https://github.com/CGAL/cgal/assets/147084302/a744cd60-6ab8-4adf-9297-101694f27100)
 that each vertex of the input surface is related to a skeleton vertex.  In which part of the code can I extract the vertices of the input surfaces?

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):wsl ubuntu 22.04
* CGAL version:5.6

**Comment by sloriot** [comment]
Check the last part of the example:
https://doc.cgal.org/latest/Surface_mesh_skeletonization/Surface_mesh_skeletonization_2MCF_Skeleton_sm_example_8cpp-example.html

The generated file correspondance-sm.polylines.txt that can be read by the polyhedron demo contains segments between input vertices and skeleton vertices.
