### ISSUE TITLE
Implementation mean curvature skeleton with polyheedron demo

### ISSUE THREAD

**Issue by zahrakheyrollahi** [CGAL/cgal#7865]
I implemented the skeleton of 3D shapes on polyhedron demo, 
![elephant11](https://github.com/CGAL/cgal/assets/147084302/51c7e42a-f67b-4fd9-affa-6a1bf912a1b0)

   but I want the output as shown below, how can I have it?
![correspondence-1](https://github.com/CGAL/cgal/assets/147084302/debc5228-6c4b-499d-811b-40af6103cacc)
@afabri 
@sloriot

**Comment by sloriot** [comment]
At the end of [this example](https://doc.cgal.org/latest/Surface_mesh_skeletonization/Surface_mesh_skeletonization_2MCF_Skeleton_example_8cpp-example.html) (*Output skeleton points and the corresponding surface points*), the vertex internal proporty of the skeleton is used to access the list of input vertex corresponding to each vertex of the skeleton.

**Comment by zahrakheyrollahi** [comment]
How can I show this output in polyhedron demo?

**Comment by zahrakheyrollahi** [comment]
I don't know, can you give more guidance on how to generate and loaded in the demo?
thank you
@sloriot

**Comment by zahrakheyrollahi** [comment]
i generated the file by example 
![IMG_20231116_225047_401](https://github.com/CGAL/cgal/assets/147084302/339e7104-f762-4664-bcbf-23dd092eb744)
Which loader should I use?
![IMG_20231116_225028_280](https://github.com/CGAL/cgal/assets/147084302/f51c562a-97e9-4859-9e9e-9719aeb9219f)
@sloriot

**Comment by sloriot** [comment]
polyline. If the extension is `.polyline.txt`
