### ISSUE TITLE
Create libCGAL_Qt5.so

### ISSUE THREAD

**Issue by kioplato** [CGAL/cgal#7870]
## Issue Details

I would like to compile libCGAL_Qt5.so locally. I've compiled Qt5, linked it and the next problem is that I can't find libCGAL_Qt5.so to link it. How can I create it on my own? Thanks.

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Gentoo Linux 64-bit
* Compiler: g++ 13.2.1
* Release or debug mode: release
* Specific flags used (if any):
* CGAL version: 5.5
* Boost version: 1.82
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by lrineau** [comment]
Since CGAL version 5.3, CGAL is not a headers-only library: that are no longer compiled libraries like `libCGAL_Qt5.so`. See the [release notes](https://www.cgal.org/2021/07/06/cgal53/).
