### ISSUE TITLE
not connected points

### ISSUE THREAD

**Issue by cesare-corrado** [CGAL/cgal#79]
I generate a inr file segmentation and after I did the same procedure as in the example of the liver for generating a mesh. When I inspect the obtained file .mesh, the number of point is bigger than the number of points belonging to thetraedra. I.E., the cardinality of the number of node is greater than the cardinality of the number of node belonging to tetrahedra. I also checked that these nodes do not belong to triangle. Also refining the problem persists (with 1873672 nodes and 8853179 Tetrahedra there are 85 nodes not connected to any other entities). It is a bug? what are these extra nodes?

**Comment by lrineau** [comment]
Are you talking about the example `CGAL-4.6/examples/Mesh_3/mesh_3D_image.cpp`? Your bug report is not completely clear about that.

**Comment by cesare-corrado** [comment]
Yes, I wrote a code doing the same thing, but I used a segmentation I converted in a inr file instead of  data/liver.inr.gz. the output i referred i obtained by output_to_medit function

**Comment by cesare-corrado** [comment]
Update: I ran CGAL-4.6/examples.Mesh_3/mesh_3D_image.cpp by adopting the following mesh criteria:

 // Mesh criteria
  Mesh_criteria criteria(facet_angle=30, facet_size=1.0, facet_distance=4,
                         cell_radius_edge_ratio=2, cell_size=1);

The meshing process generate 1291347 points. The number of point connected by ThetraHedra is 1291345 (i.e. there are 2 points not connected) These point are nor connected by triangles.

**Comment by lrineau** [comment]
The method that is used to mesh the object (here your segmentation encoded into a `.inr` file) does not guarantee that all the points inserted by the algorithm are actually used in the final mesh (I can give you pointers to scientific articles that present the method, if you want; they are probably already cited in the CGAL manual). Usually, all points are used, but if the geometry of the object have small features, compared to the size of the triangles/tetrahedra, it might be that the Delaunay facets that are selected in the restricted Delaunay triangulation miss some vertices of the triangulation.

If that is an issue for you, then I could modify `output_to_medit` to explicitly skip those vertices in the creation of the output. What is your real problem with those isolated vertices?

**Comment by cesare-corrado** [comment]
I need that the triangluation (where I access to extract the data I need) has only the connected node; i use as input of another code indeed.

**Comment by lrineau** [comment]
So, instead of changing the function `output_to_medit`, you would need a sort of post-processing method like `remove_isolated_vertices(CDT_3&)` that remove those isolated vertices from the triangulation?

**Comment by cesare-corrado** [comment]
yes

**Comment by lrineau** [comment]
@janetournois Do not we already have such a function `remove_isolated_vertices(CDT_3&)` or do I mix it up with another function?

**Comment by janetournois** [comment]
We have, in Polygon Mesh Processing [PMP::remove_isolated_vertices(FaceGraph)](https://cgal.geometryfactory.com/CGAL/Members/Manual_doxygen_test/CGAL-4.8-I-120/output/Polygon_mesh_processing/group__PkgPolygonMeshProcessing.html#ga91c02ef57e638faf2622eae93e7a25e2) coming in the next release.

and in Mesh_3 [remove_far_points_in_mesh_3(C3T3& c3t3)](https://github.com/CGAL/cgal/blob/master/Mesh_3/include/CGAL/remove_far_points_in_mesh_3.h) (which I think is not documented)

**Comment by sloriot** [comment]
@janetournois @lrineau Do you still target 4.8 for the fix?

**Comment by janetournois** [comment]
We just discussed it and will change the milestone to 4.9
It will have a high priority on the 4.9 todo list though

@cesare-corrado we will let you know as soon as it's implemented

**Comment by cesare-corrado** [comment]
Hi @janetournois, @lrineau, @sloriot, 

I implemented a patch to remove these item (I use tetrahedral mesh with triangles on boundary; it acts on part of my code data, on mesh object that I think is not much different from CGAL data)

If you think that it is possible to integrate it within CGAL,  I can provide you copy of the function doing this task (around 80 lines in C++)

Let me know.


Cesare

**Comment by sgiraudot** [comment]
@janetournois What is the status of this feature now? Still in development?

**Comment by sgiraudot** [comment]
@janetournois ping :)

**Comment by sloriot** [comment]
@janetournois I change the milestone to 4.11

**Comment by sloriot** [comment]
I think we should add a `is_in_complex()` for vertex + a function collecting all vertices in complex (that do not call `is_in_complex()` for each vertex but rather iterator over cells).
