### ISSUE TITLE
sharp edge segmentation not working with geometrical primitives like cube, cylinder and cone

### ISSUE THREAD

**Issue by shomeAvataar** [CGAL/cgal#7903]
_Please use the following template to help us solving your issue._

## Issue Details

 [(sharp edge segmentation example)](https://doc.cgal.org/latest/Polygon_mesh_processing/Polygon_mesh_processing_2detect_features_example_8cpp-example.html) gives unexpected behavior with geometric primitives such as cube, cylinder, cone. All the meshes are triangulated meshes.

With all the primitives (cube, cylinder, cone) and with varying angles (30, 60, 90 degrees) the output is the same:

_This mesh contains 0 sharp edges and 1 surface patches._ 

Basically the segmentation using sharp feature does not seem to work.

## Source Code

The source code is a minor modification of the CGAL example titled **Polygon_mesh_processing/detect_features_example.cpp**

How to run: ./main mesh.off angle_bound(in degrees)

Geomteric primitives attached in zip file.

```c++
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/Surface_mesh.h>

#include <CGAL/Polygon_mesh_processing/detect_features.h>
#include <CGAL/Polygon_mesh_processing/IO/polygon_mesh_io.h>

#include <iostream>
#include <string>
#include <cstdlib>

typedef CGAL::Exact_predicates_inexact_constructions_kernel K;
typedef CGAL::Surface_mesh<K::Point_3>                      Mesh;
typedef boost::graph_traits<Mesh>::face_descriptor          face_descriptor;

namespace PMP = CGAL::Polygon_mesh_processing;

int main(int argc, char* argv[])
{
  const std::string filename = (argc > 1) ? argv[1] : CGAL::data_file_path("meshes/P.off");
  
  float angle_bound = atof(argv[2]);
  
  Mesh mesh;
  if(!PMP::IO::read_polygon_mesh(filename, mesh))
  {
    std::cerr << "Invalid input." << std::endl;
    return 1;
  }

  typedef boost::property_map<Mesh, CGAL::edge_is_feature_t>::type EIFMap;
  typedef boost::property_map<Mesh, CGAL::face_patch_id_t<int> >::type PIMap;
  typedef boost::property_map<Mesh, CGAL::vertex_incident_patches_t<int> >::type VIMap;

  EIFMap eif = get(CGAL::edge_is_feature, mesh);
  PIMap pid = get(CGAL::face_patch_id_t<int>(), mesh);
  VIMap vip = get(CGAL::vertex_incident_patches_t<int>(), mesh);

  std::size_t number_of_patches
    = PMP::sharp_edges_segmentation(mesh, angle_bound, eif, pid,
                                    CGAL::parameters::vertex_incident_patches_map(vip));

  std::size_t nb_sharp_edges = 0;
  for(boost::graph_traits<Mesh>::edge_descriptor e : edges(mesh))
  {
    if(get(eif, e))
      ++nb_sharp_edges;
  }

  std::cout << "This mesh contains " << nb_sharp_edges << " sharp edges" << std::endl;
  std::cout << " and " << number_of_patches << " surface patches." << std::endl;

  return 0;
}
```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): ubuntu 20.04.6 LTS
* Compiler: g++ 9.4
* Release or debug mode: Release
* Specific flags used (if any):
* CGAL version: 5.6
* Boost version:  1.71
[primitives.zip](https://github.com/CGAL/cgal/files/13541763/primitives.zip)

* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by kannishk** [comment]
Can I be assigned this? @afabri @MaelRL

**Comment by sloriot** [comment]
There is nothing sharp in your model, edges are rounded.
![Screenshot from 2024-01-15 09-37-48](https://github.com/CGAL/cgal/assets/1224632/01d5e40f-69b4-41bd-aec3-1edb6f68c3db)
