### ISSUE TITLE
faces_around_face never returns a non-null face

### ISSUE THREAD

**Issue by Aadit-Nagori** [CGAL/cgal#7916]
## Issue Details
as per a previous issue on the same topic, [here](https://github.com/CGAL/cgal/issues/6189). I am trying to use the faces_around_face iterator on a surface mesh but was getting an assesrtion error. The previous issue claimed that checking to see if the face from the iterator is not null would solve the issue but now every face from the iterator is apparently null. 

## Source Code
```
Face_index start = cave_faces[0];
    for(auto f: CGAL::faces_around_face(sm.halfedge(start), sm)){
        std::cout<<"test"<<std::endl;
        if(f==Mesh::null_face()){
            std::cout<<"invalid"<<std::endl;
        }
        else{
            std::cout<<"valid"<<std::endl;
            put(surfacecm, f, CGAL::IO::blue());
        }
    }
```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Mac 
* Compiler: gcc
* Release or debug mode: release
* Specific flags used (if any):
* CGAL version: 5.6
* Boost version: 1.83
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by sloriot** [comment]
Is `start` a non-null face?

**Comment by afabri** [comment]
No problem.
