### ISSUE TITLE
polyline_simplification examples gives run time errors

### ISSUE THREAD

**Issue by haluk-pointr** [CGAL/cgal#7918]
## Issue Details

When I try to run the simplify_polygon and simplify_polyline examples I have a run time error which is:
```
CGAL error: assertion violation!
Expression : n >= 2
File       : /opt/homebrew/include/CGAL/Constrained_triangulation_plus_2.h
Line       : 615
Explanation:
Refer to the bug-reporting instructions at https://www.cgal.org/bug_report.html
libc++abi: terminating due to uncaught exception of type CGAL::Assertion_exception: CGAL ERROR: assertion violation!
Expr: n >= 2
File: /opt/homebrew/include/CGAL/Constrained_triangulation_plus_2.h
Line: 615
zsh: abort      ./simplify_polygon
```

## Source Code

Issue can be seen in "CGAL-5.6/examples/Polyline_simplification_2/simplify_polygon.cpp" line 23.

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): MacOS Ventura 13.5.2 
* Compiler:
* Release or debug mode: 
* Specific flags used (if any):
* CGAL version: 5.6 installed with brew.
* Boost version: 1.83.0
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by gdamiand** [comment]
simplify_polygon reads the input file given in the command line arguments, or use data/polygon.wkt if there is no argument.
This file is probably not available from the current directory where you run  ./simplify_polygon.
