### ISSUE TITLE
empty error when reading 3D .wkt out put file of Mean Curvature sleleton 

### ISSUE THREAD

**Issue by zahrakheyrollahi** [CGAL/cgal#7920]
I wrote a code that takes the 3D skeleton from the Mean Curvature Skeleton algorithm as an input to .wkt from tthehe Polyhedron Demo program. It extends to the user with the radius it receives from the user.
![stack2-1](https://github.com/CGAL/cgal/assets/147084302/73e7c005-2138-4c55-b62f-73e190caab4c)

But the error I get is: Error: No LineStrings Found in WKT File
![stack-1](https://github.com/CGAL/cgal/assets/147084302/0676b0b7-2c75-4782-a5d4-bf734bcb7af3)

I have put the data in this:
https://dpaste.org/8wJ5R
The code:
https://dpaste.org/TgMKU
I have changed the functions of Expand, Readwkt and ReadLineStrings and put a condition into their functions as well as main to know why the output file is empty then I get n = 0 and cannot read from the input file I have set my data. Wkt doesn't make sense?
@afabri 
@MaelRL 
@sloriot

**Comment by afabri** [comment]
I didn't find time earlier to look into this.  @zahrakheyrollahi is this still an open problem, or did you find a solution, or workaround, or did you just give up?  If you want me to have a look, can you please update on dpaste.org as the links are outdated.

**Comment by afabri** [comment]
Closed as no reply by the OP.
