### ISSUE TITLE
Read and write 3D data in .wkt format

### ISSUE THREAD

**Issue by zahrakheyrollahi** [CGAL/cgal#7936]
I have a 3D points file in .wkt Multilinestring format  that I want to read and write new points in .wkt format after performing an operation on them.
I also checked the cgal site and found examples only for two-dimensional points: https://doc.cgal.org/latest/Stream_support/Stream_support_2Linestring_WKT_8cpp-example.html#a3
My data is like this:
MULTILINESTRING((0.57583673807723645 0.19677395720887175 0.090627723485811648,0.56600381483685958 0.20525004317922704,...))

**Comment by MaelRL** [comment]
3D points should be supported. Did you encounter an issue?

**Comment by zahrakheyrollahi** [comment]
Yes, I was able to solve this reading and writing problem, but I want to make the 3D skeleton fatter. Is it possible to consider any point of the skeleton as the center and make the skeleton fatter with the desired radius? In cgal, using which function?  Can I do this? I have another idea, that is, for each point of the skeleton, can the normal vector be calculated to make the skeleton fatter based on a certain coefficient of the normal vector? It is necessary, please answer soon.
I have also put the input and output shapes that I want
![Uploading Screenshot_20240116_212707_Gallery.jpg…]()
![input-1](https://github.com/CGAL/cgal/assets/147084302/0adcadfd-a89d-4ca2-86b3-d659b9de11aa)

**Comment by MaelRL** [comment]
You can generate offset surfaces using the 3D Mesh generation package, see for example this code: https://github.com/CGAL/cgal/blob/master/Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Offset_meshing_plugin.cpp.

You will need an AABB tree of segments rather than graph, see https://doc.cgal.org/latest/AABB_tree/classCGAL_1_1AABB__segment__primitive.html.
