### ISSUE TITLE
How can I insert a face?

### ISSUE THREAD

**Issue by StromanStroman** [CGAL/cgal#7937]
## Issue Details

I construct a CGAL::Surface_mesh.I removed a face.I added a new face which has the same vertex_descriptors with the face removed.The add_face api give a max_unsigned int number——4294967295 back to me.
I got confused.The removed face and the added face are two different faces,althought they have same vertexes,they can not be topology error.But they does give me a inexplicably error information which I can not accept.
I just want to add a new face after I remove a face which they have the same vertexes.How can I make it?

## Source Code

```
{
	std::chrono::high_resolution_clock::time_point previousTime = std::chrono::high_resolution_clock::now();
	this->mesh.clear();
	for (size_t index = 0; index < model.vertexes.size(); index++)
	{
		Mesh::Vertex_index vertexIndex = this->mesh.add_vertex(
			KernalCGAL::Point_3(
				std::get<0>(model.vertexes.at(index)->getCoordinate()),
				std::get<1>(model.vertexes.at(index)->getCoordinate()),
				std::get<2>(model.vertexes.at(index)->getCoordinate())
			)
		);
	}
	for (size_t index = 0; index < model.faces.size(); index++)
	{
		Mesh::Vertex_index indexes[3] = {
			Mesh::Vertex_index(model.faces.at(index)->getFirstHalfedgePointer()->getModelVertex()->getIndex()),
			Mesh::Vertex_index(model.faces.at(index)->getFirstHalfedgePointer()->getNextHalfedge()->getModelVertex()->getIndex()),
			Mesh::Vertex_index(model.faces.at(index)->getFirstHalfedgePointer()->getNextHalfedge()->getNextHalfedge()->getModelVertex()->getIndex())
		};
		Mesh::Face_index currentIndex = this->mesh.add_face(
			indexes[0],
			indexes[1],
			indexes[2]
		);
		if (currentIndex == Mesh::null_face())
		{
			currentIndex = this->mesh.add_face(indexes[0], indexes[2], indexes[1]);
		}
		if (currentIndex == Mesh::null_face())
		{
			ICOUT << "Null face has occurred in cgal mesh : <" << indexes[0] << "," << indexes[1] << "," << indexes[2] << ">" << std::endl;
		}
	}
	for (size_t index = 0; index < model.vertexes.size(); index++)
	{
		if (model.vertexes.at(index)->getRemoved() == true)
		{
			this->mesh.remove_vertex(vertex_descriptor(index));
		}
	}
	for (size_t index = 0; index < model.faces.size(); index++)
	{
		if (model.faces.at(index)->getRemoved() == true)
		{
			this->mesh.remove_face(face_descriptor(index));
		}
	}
	ICOUT << "CGAL create mesh : " << Tools::microsecondTillNow(previousTime) << " microseconds" << std::endl;
}
```
```
{
	face_descriptor result = this->mesh.add_face(vertexes[0], vertexes[1], vertexes[2]);
	if (result == Mesh::null_face() || !this->mesh.is_valid(result))
	{
		result = this->mesh.add_face(vertexes[0], vertexes[2], vertexes[1]);
	}
	return result;
}
```

## Environment

* Operating system (Windows 11, 64 bits):
* Compiler: Visual Studio 2022 community
* Release or debug mode: debug mode
* Specific flags used (if any):
* CGAL version: 5.6
* Boost version: 1.79.0
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by sloriot** [comment]
If you read the documentation [here](https://doc.cgal.org/latest/Surface_mesh/classCGAL_1_1Surface__mesh.html#af2311658bf6d730b276b23b5c304f90e), you'll see *removes face f from the halfedge data structure without adjusting anything*, that is it is a raw removal. You should use the [Euler operation](https://doc.cgal.org/latest/BGL/group__PkgBGLEulerOperations.html#gacfae7ff8e782da55b941e4487e86c738) instead if you want pointers to be updated.

**Comment by StromanStroman** [comment]
> If you read the documentation [here](https://doc.cgal.org/latest/Surface_mesh/classCGAL_1_1Surface__mesh.html#af2311658bf6d730b276b23b5c304f90e), you'll see _removes face f from the halfedge data structure without adjusting anything_, that is it is a raw removal. You should use the [Euler operation](https://doc.cgal.org/latest/BGL/group__PkgBGLEulerOperations.html#gacfae7ff8e782da55b941e4487e86c738) instead if you want pointers to be updated.

Thank you very much.It works.
