### ISSUE TITLE
Tet remeshing: wrong link in the user manual

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#7940]
@janetournois This discussion (https://github.com/CGAL/cgal/pull/7909#discussion_r143125656) is still left unsolved. And it seems Albert it right. The result in a local doc compilation is the following:

![Screenshot_20231219_120746](https://github.com/CGAL/cgal/assets/5746675/d797e344-f075-4f3e-b6d0-354e7a486127)

_Originally posted by @lrineau in https://github.com/CGAL/cgal/pull/7909#discussion_r1431256562_

**Comment by afabri** [comment]
I do not see what you want to fix here.   The link contains the package name and that is just fine.

**Comment by sloriot** [comment]
FIxed by 13b5f3676a2a7d5ce8df2ce4cac18535e983bc05
