### ISSUE TITLE
convert Polygon_with_holes_2 To Surface_mesh

### ISSUE THREAD

**Issue by BeginCGAL** [CGAL/cgal#7943]
_Please use the following template to help us solving your issue._

##

 i want convert Polygon_with_holes_2 To Surface_mesh,because Surface_mesh can write to .obj file

## Source Code

hello have anyone could tell me how  Polygon_with_holes_2 convert  To Surface_mesh,or how Polygon_with_holes_2  export to .obj file?

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):Windows
* Compiler:
* Release or debug mode:debug 
* Specific flags used (if any):
* CGAL version: 5.52
* Boost version:1.80
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by pentacular** [comment]
Use CGAL::Polygon_triangulation_decomposition_2 to produce triangles, use Plane_3 to_3d to produce faces, and add_face on the Surface_mesh.

**Comment by pentacular** [comment]
Ah, but it might be faster to just write a function to print a Polygon_with_holes_2 in obj format, as that is very simple.

**Comment by BeginCGAL** [comment]
I am a beginner,could you please write a demo (i could't find the demo about Polygon_triangulation_decomposition_2 )? thank you

**Comment by pentacular** [comment]
Perhaps something like this:
```
bool PolygonsWithHolesToSurfaceMesh(const Plane& plane,
                                    std::vector<Polygon_with_holes_2>& polygons,
                                    Surface_mesh& result,
                                    Vertex_map& vertex_map, bool flip = false) {
  CGAL::Polygon_triangulation_decomposition_2<Kernel> triangulator;
  for (const Polygon_with_holes_2& polygon : polygons) {
    std::vector<Polygon_2> facets;
    triangulator(polygon, std::back_inserter(facets));
    for (auto& facet : facets) {
      if (facet.orientation() != CGAL::Sign::POSITIVE) {
        facet.reverse_orientation();
      }
      std::vector<Vertex_index> vertices;
      for (const auto& point : facet) {
        vertices.push_back(
            ensureVertex(result, vertex_map, plane.to_3d(point)));
      }
      if (flip) {
        std::reverse(vertices.begin(), vertices.end());
      }
      if (result.add_face(vertices) == Surface_mesh::null_face()) {
        return false;
      }
    }   
  }     
  return true;
} 
```

But I think you're still going about this the wrong way.

Generating an OBJ file from a Polygon_with_holes_2 should be simpler. :)

**Comment by BeginCGAL** [comment]
thank you, by the way could you tell me the simpler way Generating an OBJ file from a Polygon_with_holes_2?

**Comment by pentacular** [comment]
```
v  0  0  0
v  1  0  0
v  1  1  0
v  0  1  0
v  0.5  0.5  1.6

f  5  2  3
f  4  5  3
f  6  3  2
f  5  6  2
f  4  6  5
f  6  4  3
```

Just write out the vertices (v) and the faces (f).

You'll still need to do the triangular decomposition since obj doesn't handle holes, but it's very simple.

**Comment by BeginCGAL** [comment]
i know .obj file format, and i know how to get all  vertices . But i don't konw  how to get the vertexIndex of every face such as "f  5 2  3", and how to get  the "vn" value such as "vn -0.116639 0.196368 -0.973568".

**Comment by pentacular** [comment]
Just go through all of the vertices and write them out.
The first vertex you write out has index 1, the second has index 2, and so on.

Next go through all of the triangles, mapping each vertex to its index.

Now you're done.

You don't need to add vertex normals, but vn 0 0 1 should be correct since this is a 2d polygon.

**Comment by BeginCGAL** [comment]
thank you , i have achieved  the aim
