### ISSUE TITLE
Renaming new curve reconstruction package

### ISSUE THREAD

**Issue by sgiraudot** [CGAL/cgal#795]
I am sorry to come up with this issue _after_ the [PR](https://github.com/CGAL/cgal/pull/151) was accepted, but if there is still time before the release 4.8, I would like the name of this new package __2D Reconstruction and Simplification from Point Sets__ to be changed to match the template of the 3 other reconstruction packages:
* Poisson Surface Reconstruction
* Scale-Space Surface Reconstruction
* Advancing Front Surface Reconstruction

That is to say:
* [Method] [object reconstructed] Reconstruction

This normalization of names was done in https://github.com/CGAL/cgal/pull/319.

In this case, why not __Optimal Transportation Curve Reconstruction__? I don't think the "simplification" term is useful in the title as simplification is just part of the process and cannot be applied by itself (I might be wrong but I don't think the algorithm can take a set of line segments as input and simplify them).

**Comment by sloriot** [comment]
@cjamin What do you think? Can you check with @palliez ?

**Comment by cjamin** [comment]
Ok, we both agree.

**Comment by sgiraudot** [comment]
Okay, thanks!

Do I take care of it then?

**Comment by cjamin** [comment]
Sure, go ahead. Thanks!

**Comment by sgiraudot** [comment]
Fixed by https://github.com/CGAL/cgal/pull/804. I'm closing the issue.
