### ISSUE TITLE
Showing the crust, power crust algorithm in the polyhedron demo program

### ISSUE THREAD

**Issue by zahrakheyrollahi** [CGAL/cgal#7952]
## Issue Details

How can I display crust and powercrust algorithm outputs in the polyhedrin demo program with options like the images below?
![Screenshot_20231230_232117_Adobe Acrobat](https://github.com/CGAL/cgal/assets/147084302/a3d598fc-6f48-4584-bbb9-e0e0276e6ed0)

**Comment by sloriot** [comment]
There is no implementation of those algorithms in CGAL.
