### ISSUE TITLE
How to create a surfacemesh?

### ISSUE THREAD

**Issue by StromanStroman** [CGAL/cgal#7964]
I have a vtk including vertex and face including that has been marked removed.
First,I create vertex_descriptor with the given vertex coordinates.
Second,I deal with face one by one.
If it is removed,I will add_face,then remove the face.
Else it is add_face into the mesh.
But some problem happened,there are many null face occurs,and many invalide vertex occurs.
I want to keep the removed face in the mesh,so I insert the face then delete it,using CGAL::Euler::remove_face.
How to create a surfacemesh successfully in my way?
What's the problem in my way?

[21530.20240102095525.1582371929.zip](https://github.com/CGAL/cgal/files/13840189/21530.20240102095525.1582371929.zip)
This is the vtk,there are some fields for removed face which using 1 for removed face.

## Environment

* Operating system (Windows 64 bits):
* Compiler:Visual Studio 2022 community
* Release or debug mode:debug
* Specific flags used (if any):
* CGAL version:5.6
* Boost version:1.79.0
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by afabri** [comment]
Maybe you can put a small self contained C++ program on gist.github.com as your text above is not really clear. Also note that CGAL provides functions to read VTK files.   See [here](https://cgal.geometryfactory.com/CGAL/doc/master/Stream_support/group__PkgStreamSupportIoFuncsVTK.html#gaad7f1c5c10e8700a4a6de88294c5a620)

**Comment by afabri** [comment]
I close this as we wait for four months on an answer
