### ISSUE TITLE
Segmentation fault on insert_segments of Segment Delaunay Graph using exact constructions kernel

### ISSUE THREAD

**Issue by Yvee1** [CGAL/cgal#7972]
## Issue Details
Running the `insert_segments` function of `Segment_Delaunay_graph_2` with the `Exact_predicates_exact_constructions_kernel` gives a segmentation fault.

The error occurs regardless of which segments are inserted. Inserting segments separately with `insert` after `construct_site_2` works fine. When using the `Exact_predicates_inexact_constructions_kernel`, function `insert_segments` does work as expected. 
## Source Code
```c++
typedef CGAL::Exact_predicates_exact_constructions_kernel K;
typedef CGAL::Segment_Delaunay_graph_traits_2<K>          Gt;
typedef CGAL::Segment_Delaunay_graph_2<Gt>                SDG2;

int main() {
    auto segments = std::vector({
        CGAL::Segment_2<K>(
            CGAL::Point_2<K>(0.0, 0.0),
            CGAL::Point_2<K>(1.0, 0.0))
    });

    SDG2 delaunay;
    delaunay.insert_segments(segments.begin(), segments.end());

    return 0;
}
```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): WSL2 on Windows 11, 64 bits
* Compiler: g++
* Release or debug mode: both give a segmentation fault
* CGAL version: 5.4-1
* Boost version: 1.74.0

**Comment by afabri** [comment]
I found the problem and fix, but note that ifor performance reasons it is not really a good idea to use the kernel which does exact constructions.

**Comment by afabri** [comment]
Would be great if you shared data for which you got an assertion, as well your typedefs, so that we can try to reproduce/fix.

**Comment by Yvee1** [comment]
I had some trouble with extracting a minimal example, but I have one now and have opened a new issue (https://github.com/CGAL/cgal/issues/7978)
