### ISSUE TITLE
Point-set normal estimation point inwards

### ISSUE THREAD

**Issue by petrasvestartas** [CGAL/cgal#7982]
## Issue Details

I am running this example:
https://doc.cgal.org/latest/Point_set_processing_3/Point_set_processing_3_2normals_example_8cpp-example.html

Normal estimation point inwards for neighbors less 13 points.
Is there a way to ensure that the points are always pointing outwards?
![PointOrientation](https://github.com/CGAL/cgal/assets/18013985/9a3904ac-c2a1-4cee-853d-ade7badcaad0)

## Source Code

_If your issue arises by using CGAL in your own source code, please provide a minimalist example that we can compile easily to reproduce the bug. If your issue arises from using a CGAL program (demo, example, etc.), please let us know which one. Helping you solving an issue is much easier and efficient if we can reproduce it._

## Environment

* Operating system (Windows):
* Compiler Visual Studio:
* Release mode:
* Specific flags used (if any):
* CGAL version: 5.2
* Boost version: latest
* Other libraries versions if used (Eigen, TBB, etc.): Eigen

**Comment by afabri** [comment]
The points with a wrong normal are relatively far away from the "surface".  
What is inside and outside is hard to decide in general if you only have points with normal.

**Comment by petrasvestartas** [comment]
Hi @afabri ,

I see, I was wondering if there are any simple "tricks" to orient points by measuring distance to a bounding box.
I will keep it that way, already that I get these nicely oriented normals are awesome :)
