### ISSUE TITLE
Bug of Renderer::update_opengl_buffers?

### ISSUE THREAD

**Issue by linbeijianbaoxia** [CGAL/cgal#7995]
_Please use the following template to help us solving your issue._

## Issue Details

I us MeshViewer to show a SurfaceMesh, and use delete_face() to delete some faces, and then call update_mesh(), then received a warning about vector overflow" 或 "Subsequently encountered a warning regarding vector overflow.
![864d46932249d7805695858b66c21a5](https://github.com/CGAL/cgal/assets/50166977/57809334-579b-4774-b996-ab3a76b04715)

Then I used Debug to inspect the source code and identified a bug in Renderer::update_opengl_buffers() that led to a vector overflow. (If I am mistaken, please criticize and correct me, as I am new to CGAL and not familiar with the proper usage practices.)

Taking position_array as an example, it initially reserved memory for 3 times the number of mesh_.n_faces() in mesh_ during initialization. However, during iteration using 'for (auto f : mesh_.faces())', elements were pushed back into position_array without checking whether the current face had been deleted. This resulted in an overflow.
![image](https://github.com/CGAL/cgal/assets/50166977/c4b63798-781f-4822-ae51-d350a026c5e0)

I made the following modifications to the source code of void Renderer::update_opengl_buffers() in renderer.cpp. I am currently researching how to submit my changes to CGAL.
![image](https://github.com/CGAL/cgal/assets/50166977/b04fcc39-8a6e-4ae3-8e28-dccbe7553172)

## Source Code
My test source code was added to the official MPView instance, and the added code is as follows. It was added within MeshProcessingViewer::process_imgui(), as shown in the figure:
![image](https://github.com/CGAL/cgal/assets/50166977/54cd9ffa-9a05-4516-8756-706fe603cc9c)

    if (ImGui::CollapsingHeader("test_test"), ImGuiTreeNodeFlags_DefaultOpen)
    {
        if (ImGui::Button("delete faces through abs_max curvatrue"))
        {
            //! 计算曲率 max_abs
            curvature(mesh_, Curvature::max_abs, 1, true, true);
            const auto curv_mas_abs = mesh_.get_vertex_property<pmp::Scalar>("v:curv");

            //! 计算面的三点曲率和
            std::vector<pmp::Scalar> curv_sum_list;     // 存放所有 face 的曲率和，用于取正则化分母
            curv_sum_list.reserve(mesh_.faces_size());

            auto curv_face = mesh_.add_face_property<pmp::Scalar>("f:curv_max_abs_sum");
            for (const auto& f : mesh_.faces())         // 遍历所有 face
            {
                pmp::Scalar curv_sum = 0.;
                for (const auto& v : mesh_.vertices(f)) // 遍历 face 的所有点
                    curv_sum += curv_mas_abs[v];

                curv_face[f] = curv_sum;

                curv_sum_list.push_back(curv_sum);
            }

            //! 正则化曲率和
            std::sort(curv_sum_list.begin(), curv_sum_list.end());  // 排序曲率和
            const double percentile = 0.95;                         // 取第 95% 大的值用于正则化
            const int idx_reg = static_cast<int>(percentile * curv_sum_list.size());
            const pmp::Scalar reg_curv = curv_sum_list[idx_reg];    // 用于正则化

            if (reg_curv != 0.)                                     // 注意正则化后值域不是[0,1]
                for (const auto& f : mesh_.faces())
                    curv_face[f] /= reg_curv;
            else
                std::cout << "Warning: 用于正则化的 reg_curv 为：" << reg_curv << std::endl;
            
            //! 根据曲率和阈值删除面
            const pmp::Scalar thre_curv_sum = 0.7;
            for (const auto& f : mesh_.faces())
                if (curv_face[f] > thre_curv_sum)
                    mesh_.delete_face(f);

            //curvature_to_texture_coordinates(mesh_);
            //renderer_.use_cold_warm_texture();
            update_mesh();
            set_draw_mode("Texture");
        }
    }

## Environment

* Operating system (Windows, 32/64 bits):
* Compiler:
* Release or debug mode: debug
* Specific flags used (if any):
* CGAL version: 5.6
* Boost version: 
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by lrineau** [comment]
@linbeijianbaoxia You mixed up CGAL and PMP. The code you are referring to is at https://github.com/pmp-library/pmp-library/blob/60b3bd9de38b246e39d487eab598e93b8d1fc085/src/pmp/visualization/renderer.cpp#L237-L319

Please resubmit this bug to https://github.com/pmp-library/pmp-library/.

**Comment by linbeijianbaoxia** [comment]
Very sorry, both are excellent libraries. It's just that I couldn't find a curvature computation tool in CGAL, so I ended up using PMP. I often get confused between the two.

**Comment by sloriot** [comment]
Check https://cgal.geometryfactory.com/CGAL/doc/master/Polygon_mesh_processing/index.html#title60 in the master branch of CGAL. Curvature computation will be released in CGAL 6.0
