### ISSUE TITLE
planes_point_set_3.ply in wrong format

### ISSUE THREAD

**Issue by adokhugi** [CGAL/cgal#7996]
## Issue Details

region_growing_planes_on_point_set_3 creates a file named planes_point_set_3.ply. In this file the colors are stored in a wrong format. If you open the file in MeshLab you will get an error message.

## Source Code

region_growing_planes_on_point_set_3.cpp

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows 64 bit
* Compiler: MS Visual C++ 2022
* Release or debug mode: both
* Specific flags used (if any): -
* CGAL version: 5.6
* Boost version: the latest
* Other libraries versions if used (Eigen, TBB, etc.): the latest

**Comment by afabri** [comment]
Thank you for pointing this out.  Note that it works for the binary mode.
```
std::ofstream out("points.ply", std::ios::binary);
CGAL::IO::set_binary_mode(out);
out << output_range;
out.close();
```
