### ISSUE TITLE
STL File Read Error

### ISSUE THREAD

**Issue by TLCZhaoxi** [CGAL/cgal#7999]
## Issue Details

Surface Mesh file (STL ASCII format) with several small components can not be read completely with the function of "CGAL::IO::read_polygon_mesh()".

INPUT MESH FILE:
![image](https://github.com/CGAL/cgal/assets/117611517/8c6e77d8-a2fd-49f1-8e1f-2580fedf56e4)
OUTPUT MESH FILE:
![image](https://github.com/CGAL/cgal/assets/117611517/009a57f9-e3d5-424d-9207-5da54eb831ab)

## Source Code

                SurfaceMesh msh;
		CGAL::IO::read_polygon_mesh(stlPath, msh);	
		std::ofstream ofs_1(outputPath);
		ofs_1 << msh;																		
		ofs_1.close();

## Environment

* Operating system (Linux, 64 bits): Ubuntu 22.04.1 LTS 
* Compiler: g++ 11.3.0
* Release or debug mode: Release
* CGAL version: 5.5.1

[Error_STL.zip](https://github.com/CGAL/cgal/files/14036018/Error_STL.zip)

**Comment by sloriot** [comment]
Your stl files are not valid polygon mesh. You either have to read them as polygon soup and fix the issues or use the PMP function doing it for you:

https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__IO__grp.html

**Comment by TLCZhaoxi** [comment]
Thanks so much
