### ISSUE TITLE
Package Mesh_3 / example mesh_polyhedral_domain / precondition violation error in AABB_tree.h

### ISSUE THREAD

**Issue by jviviani** [CGAL/cgal#800]
Dear all,
I just install CGAL and try a few examples of my package of interest: 3D mesh generation (mesh_3).
All examples worked except mesh_polyhedral_domain and mesh_polyhedral_domain_with_features. When I launch the exe file via command prompt I have the following error:

CGAL error: precondition violation!
Expression : !empty()
File : C:\dev\CGAL-4.7\include\CGAL/AABB_tree.h
Line : 223
Explanation:
Refer to the bug-reporting intructions at http://www.cgal.org/bug_report.html

I look at other bug reports on this website and on stackoverflow but I didn't find any answer for my problem.

I use Visual C++ express 2010: the compilation of the example was performed both in debug and release with no displayed errors.

I don't know if I had to had all my installation procedure for CGAL, if you need it or any kinds of  informations, feel free to ask!!

Thank you for your time and help!!!

Best regards,

Jérémie

**Comment by lrineau** [comment]
How have you launch the compiled examples? They both open a file:
  - `data/elephant.off` for `mesh_polyhedral_domain.cpp`, and
  - `data/fandisk.off` for `mesh_polyhedral_domain_with_features.cpp`.

If they are launched in a directory that does not contain those the `data/` sub-directory, then the examples crash. We should probably deal with I/O errors explicitly.

**Comment by jviviani** [comment]
Thank you a lot for your answer! 
I just put the elephant.off and fandisk.off in the debug folder instead of putting them in subfolder data!
Many thanks!
