### ISSUE TITLE
`CGAL::Polygon_mesh_processing::self_intersections` returns invalid intersection

### ISSUE THREAD

**Issue by OpenByteDev** [CGAL/cgal#8020]
## Issue Details

`CGAL::Polygon_mesh_processing::self_intersections` returns an invalid intersection in this mesh:
[debug.zip](https://github.com/CGAL/cgal/files/14181954/debug.zip)
![image](https://github.com/CGAL/cgal/assets/22861309/22495e44-9771-4e3f-8543-038aa14a9499)
I isolated the two triangles into a mesh:
![image](https://github.com/CGAL/cgal/assets/22861309/eb1fecf6-cda1-44ab-a360-67a0a2d9d57f)
The vertex is indeed shared between the triangles (and not duplicated).
I also tried using `CGAL::Polygon_mesh_processing::stitch_borders` on the mesh as mentioned in some other issue.

## Source Code

```
#include <CGAL/Polygon_mesh_processing/self_intersections.h>
#include <CGAL/Simple_cartesian.h>
#include <CGAL/Surface_mesh/Surface_mesh.h>
#include <CGAL/boost/graph/IO/polygon_mesh_io.h>

typedef CGAL::Simple_cartesian<double> Kernel;
typedef Kernel::Point_3 Point3;
typedef CGAL::Surface_mesh<Point3> SurfaceMesh;
typedef boost::graph_traits<SurfaceMesh>::face_descriptor FaceDescriptor;

void main() 
    SurfaceMesh mesh = /* load mesh from gltf */;

    std::vector<std::pair<FaceDescriptor, FaceDescriptor>> intersected_tris;
    CGAL::Polygon_mesh_processing::self_intersections(mesh, std::back_inserter(intersected_tris));
    std::cout << intersected_tris.size() << " pairs of triangles intersect." << std::endl;
    // CGAL::Polygon_mesh_processing::does_self_intersect(cgal_mesh)
}
```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): WSL 2.0 Ubuntu 22.04.3 LTS
* Compiler: GCC 12.3.0 x86_64-linux-gnu
* Release or debug mode: Both
* Specific flags used (if any):
* CGAL version: 5.4-1
* Boost version: 1.74.0.3ubuntu7

* Other libraries versions if used (Eigen, TBB, etc.): Eigen 3.4.0-2ubuntu2

**Comment by sloriot** [comment]
Try replacing `CGAL::Simple_cartesian<double>` by `CGAL::Exact_predicates_inexact_constructions_kernel`
