### ISSUE TITLE
Regression in Mesh_3?

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#8050]
There seems to be a regression, the doc says you should get as output from mesh_3D_image_with_input_features.cpp
https://doc.cgal.org/latest/Mesh_3/index.html#fig__mesh3protectionimage3D

while I get:

![Screenshot from 2024-02-28 11-19-40](https://github.com/CGAL/cgal/assets/1224632/e40ca1d2-4ef4-4d01-bc51-2f557d039829)

I have the same bad output with CGAL-5.6 release and the example is not present in CGAL 5.5

**Comment by ange-clement** [comment]
The examples `mesh_3D_image_with_input_features.cpp` and `mesh_3D_image_with_features.cpp` are not the same.
I believe `mesh_3D_image_with_input_features.cpp` is not documented and does not detect features on bbox.
Running `mesh_3D_image_with_features.cpp` gives me the expected result.
@janetournois Maybe we should rename  `mesh_3D_image_with_input_features.cpp` to something different like  `mesh_3D_image_with_only_input_features_no_bbox.cpp` ?

**Comment by sloriot** [comment]
Ah my bad, I mixed up things. Thanks for checking!

**Comment by janetournois** [comment]
> @janetournois Maybe we should rename `mesh_3D_image_with_input_features.cpp` to something different like `mesh_3D_image_with_only_input_features_no_bbox.cpp` ?

Good idea!
