### ISSUE TITLE
Error for CGAL::Draw with Arrangement_2

### ISSUE THREAD

**Issue by zucchi99** [CGAL/cgal#8055]
## Issue Details

Hi I installed on Ubuntu my machine (wsl2 for Win10 actually) CGAL and Qt5 libraries:
`apt-get install libcgal-dev libcgal-qt5-dev`
Everything works fine: CGAL functions, also `CGAL::draw()` on a simple polygon is displayed correctly.
I tried to display an Arrangement_2 but I received the error of missing header:
`#include <CGAL/draw_arrangement_2.h>`

I checked on my CGAL library and it was missing.
I found it on your official GitHub page and added to the CGAL lib folder.

Then, after recompiling, I received a similar error for header `Basic_viewer_qt.h`.
Similarly, I found it on GitHub and added to the CGAL/Qt lib folder.

Error raised by make:
`/usr/include/CGAL/draw_arrangement_2.h:274:51: error: no type named ‘Approximate_point_2’ in ‘CGAL::Arrangement_2<CGAL::Arr_segment_traits_2<CGAL::Epick> >::Geometry_traits_2’ {aka ‘class CGAL::Arr_segment_traits_2<CGAL::Epick>’}`

It seems an internal problem of CGAL / Qt.
I tried to run the example from the manual but the compiler raises always the same error.

Of course I tried to uninstall and reinstall CGAL / Qt but the problem persists.

## Source Code

Any CGAL::draw(arrangement) fails, including the example on the manual `draw_arr.cpp`.
Files attached: 
 - [CMakeLists.txt](https://github.com/CGAL/cgal/files/14469062/CMakeLists.txt)
 - [std_out_err.log](https://github.com/CGAL/cgal/files/14469063/std_out_err.log) (obtained by redirecting stdout and stderr of cmake and make). Here you can see the whole error trace. (Note that the error is raised by make, cmake works fine).

## Environment

* Operating system: Ubuntu 22.04.4 LTS (via wsl from Win10 64 bits)
* Compiler: g++ 11.4.0
* Release or debug mode: either mode same problem
* Specific flags used (if any):
* CGAL version: 5.4-1

**Comment by efifogel** [comment]
I guess that your version of CGAL does not support
draw(Arrangement_on_surface_2& aos) yet.
Wait for the next release or get the latest sources from git. If you do the
latter, you will have to switch to Qt6.
   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/
