### ISSUE TITLE
Simple drawing fails with Qt6 6.8.0

### ISSUE THREAD

**Issue by efifogel** [CGAL/cgal#8058]
## Issue Details

All the example programs that use the simple drawing mechanism end with a segmentation fault, e.g., Polygon/draw_polygon, Arrangement_2/draw_arrangement, Surface_mesh/sm_draw_small_faces. Other programs that are based on Qt6 work fine. This is, of course, not a proof that the problem is in our code, but it's suspicious...

There is another problem:
`find_package(CGAL REQUIRED COMPONENTS Core OPTIONAL_COMPONENTS Qt6)`
is not enough. I need to precede it with:
`find_package(Qt6 REQUIRED COMPONENTS Core Gui Widgets)`
Otherwise CGAL_Qt6_FOUND is not found.
If this is intentional, then all the CMakeLists.txt files (in example directories) that are used to build examples programs that use the dimple drawing must be fixed.

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Ubuntu 20.04
* Compiler: gcc
* Release or debug mode: both
* Specific flags used (if any):
* CGAL version: Latest (from the repo.)
* Boost version: 1.78, but it is irrelevant
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by lrineau** [comment]
Qt6 version 6.8 is [planned for 25.09.2024](https://wiki.qt.io/Qt_6.8_Release). Are you currently using a build of the `dev` branch of Qt6?

**Comment by efifogel** [comment]
I've directly installed it from the Qt site:
I downloaded the installation executable
(qt-unified-linux-x64-4.7.0-online.run) and marked the 6.8.0 modules (from
dev). I realize that the 2 problems I encountered might be because of Qt....
   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by efifogel** [comment]
I've used the same installation executable to install Qt6 6.6.2.
The first problem is gone; that is, the programs do not crash anymore.
However, the 2nd problem (find_package...) persists.
   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by lrineau** [comment]
There is indeed something wrong with Qt 6.7.0 (currently beta3). and Qt 6.8.0 (preview).

I have use the online installer `qt-unified-linux-x64-4.7.0-online.run`, to install the following:

![Screenshot_20240304_162408](https://github.com/CGAL/cgal/assets/5746675/213c16c3-50a2-4c85-874e-773c70f8a1cc)

Then I tried to compile and run with all three versions of Qt, and only the version 6.6.2 worked. For the other two, I got a segfault:

```
[lrineau@fernand]~/tmp/build-Arr_2% ./circles-qt-6.6.2 
The vertex with maximal degree in the arrangement is: v_max = (4 3) with degree 6.
Using OpenGL context 4.6 GL
[lrineau@fernand]~/tmp/build-Arr_2% ./circles-qt-6.7.0 
The vertex with maximal degree in the arrangement is: v_max = (4 3) with degree 6.
Using OpenGL context 4.6 GL
zsh: segmentation fault (core dumped)  ./circles-qt-6.7.0
```
