### ISSUE TITLE
Isotropic meshing: missing requirements

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#806]
The doc does not mention that the `halfedge_descriptor` must be a model of [`Hashable`](http://doc.cgal.org/4.8/STL_Extension/classHashable.html).

cc @janetournois

**Comment by sloriot** [comment]
Actually `face_descriptor` must also be a model of `Hashable`

**Comment by afabri** [comment]
I would suggest that this becomes part of the Descriptor concept.

**Comment by sloriot** [comment]
For now I only encountered the need for one function in PMP (not in Euler, not in Helpers).

**Comment by afabri** [comment]
You will encounter it whenever we have a  hash map as an implementation detail.

Note also that we do not say in [Descriptor](http://doc.cgal.org/latest/STL_Extension/classDescriptor.html) that it must be [LessThanComparable](http://en.cppreference.com/w/cpp/concept/LessThanComparable)

**Comment by afabri** [comment]
On the practical side, do we check that the OpenMesh descriptors are hashable??
