### ISSUE TITLE
Index of bounds in Surface Mesh Parameterization

### ISSUE THREAD

**Issue by seirios** [CGAL/cgal#8062]
## Issue Details

Runtime assertion fails when running code to perform authalic surface mesh parameterization:

```
Flatten_Authalic: /usr/include/eigen3/Eigen/src/Core/DenseCoeffsBase.h:410: Eigen::DenseCoeffsBase<Derived, 1>::Scalar& Eigen::DenseCoeffsBase<Derived, 1>::operator[](Eigen::Index) [with Derived = Eigen::Matrix<double, -1, 1>; Scalar = double; Eigen::Index = long int]: Assertion `index >= 0 && index < size()' failed.
```

This on a Debug build. A Release build crashes with a memory access fault error.

The input mesh is smooth and has a single boundary, as required by the algorithm. The mesh is part of ongoing research and can be provided for testing purposes on request.

## Source Code

Source code can be found [here](https://github.com/BlueBrain/atlas-enhancement/blob/cerebellum/flatmap/code/surf_cgal/Flatten_Authalic.cxx).

The same code works well with other input meshes, so it must be something about the interaction with the input mesh.

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Linux 64-bit
* Compiler: GCC 13.1.1
* Release or debug mode: Debug
* Specific flags used (if any):
* CGAL version: 5.6.1
* Boost version: 1.81.0
* Other libraries versions if used (Eigen, TBB, etc.): Eigen 3.4.0

**Comment by afabri** [comment]
Please  put the mesh somewhere and let us know, either with a URL in this issue, or in a mail to contact@cgal.org

**Comment by seirios** [comment]
@afabri , I've sent the mesh by email just now. Thank you.

**Comment by seirios** [comment]
But I got an error from the mail server `<contact@cgal.org>: Recipient address rejected: User unknown (in reply to RCPT TO command)`. Can you please provide me with another email address?

**Comment by afabri** [comment]
You can send it to me andreas.fabri@geometryfactory.com

**Comment by seirios** [comment]
Thanks, done.

**Comment by afabri** [comment]
So far I only visualized your mesh and noticed that it has a non-manifold vertex (red). Can you check what happens there. Not sure that this is the source of your problem though. 
![image](https://github.com/CGAL/cgal/assets/3263539/63ccb4e3-0d0b-4c86-b1e6-3e6f62bf39b3)

**Comment by lrineau** [comment]
> Please put the mesh somewhere and let us know, either with a URL in this issue, or in a mail to [contact@cgal.org](mailto:contact@cgal.org)

Its `info@cgal.org`. There is no `contact@cgal.org`.

**Comment by seirios** [comment]
Thank you for spotting this @afabri ! Indeed, this non-manifold vertex pointed to the issue of two pairs of overlapping vertices nearby. After merging these (in Blender), authalic SMP works.

I have two questions then: 
+ Is it possible to check for non-manifold geometry in CGAL? 
+ Is it possible to merge duplicate vertices in CGAL?

This way I could avoid feeding bad meshes to SMP.

**Comment by seirios** [comment]
Nevermind, I found `PMP::repair_polygon_soup()` and `PMP::is_non_manifold_vertex()`. Thank you!

**Comment by MaelRL** [comment]
[PMP::duplicate_non_manifold_edges_in_polygon_soup](https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__orientation__grp.html#ga2aa4f7b500dc51d1fc4747705a050946) might also be of interest.
