### ISSUE TITLE
METIS/partition_graph.h:23:10: fatal error: metis.h: No such file or directory    23 | #include <metis.h>

### ISSUE THREAD

**Issue by monkeybuttlipstick** [CGAL/cgal#8068]
## Issue Details

I followed this instruction [here](https://tudelft3d.github.io/geogeeks/cpp/wslclion/) to install CGAL.
I tried to use metis to partition the surface mesh and I tried the demo code [here](https://doc.cgal.org/latest/BGL/BGL_surface_mesh_2surface_mesh_partition_8cpp-example.html).
However, when compiling it, it shows error: 

/usr/include/CGAL/boost/graph/METIS/partition_graph.h:23:10: fatal error: metis.h: No such file or directory
   23 | #include <metis.h>
      |          ^~~~~~~~~
compilation terminated.
gmake[3]: *** [CMakeFiles/tiling_mesh.dir/build.make:76: CMakeFiles/tiling_mesh.dir/main.cpp.o] Error 1
gmake[2]: *** [CMakeFiles/Makefile2:83: CMakeFiles/tiling_mesh.dir/all] Error 2
gmake[1]: *** [CMakeFiles/Makefile2:90: CMakeFiles/tiling_mesh.dir/rule] Error 2
gmake: *** [Makefile:124: tiling_mesh] Error 2

## Environment
* Compiler: WSL
* Release or debug mode: debug
* CGAL version: Lastest
* Boost version: BOOST_VERSION 107400, BOOST_LIB_VERSION "1_74"

**Comment by lrineau** [comment]
You need to install METIS, in your WSL, with:

```shellsession
sudo apt-get install libmetis-dev
```

**Comment by monkeybuttlipstick** [comment]
Yes it solves my problem ^^ Thank you!
