### ISSUE TITLE
SMS::edge_collapse() Behaves Unexpectedly

### ISSUE THREAD

**Issue by qwerty10086** [CGAL/cgal#8069]
_Please use the following template to help us solving your issue._

## Issue Details

I find that "SMS::edge_collapse()" seems behave unexpectedly when being called with a visitor. This is the example in document: [https://doc.cgal.org/latest/Surface_mesh_simplification/Surface_mesh_simplification_2edge_collapse_visitor_surface_mesh_8cpp-example.html](url). The comment in this example says that if the "placement" parameter of "OnCollapsing()" is absent, then the edge will be left uncollapsed. However, I find this doesn't work correctly.

## Source Code

```
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/Surface_mesh.h>
#include <CGAL/polygon_mesh_processing.h>

#include <CGAL/Surface_mesh_simplification/Edge_collapse_visitor_base.h>
#include <CGAL/Surface_mesh_simplification/Policies/Edge_collapse/Count_stop_predicate.h>
#include <CGAL/Surface_mesh_simplification/edge_collapse.h>

typedef CGAL::Epick CgalKernel_t;
typedef CgalKernel_t::Point_3 CgalPoint_t;
typedef CGAL::Surface_mesh<CgalPoint_t> CgalSurfaceMesh_t;

struct SVisitor : CGAL::Surface_mesh_simplification::Edge_collapse_visitor_base<CgalSurfaceMesh_t>
{
    void OnCollapsing(const Profile& vProfile, boost::optional<Point>& vioPlacement)
    {
        vioPlacement.reset();
    }
};

int main()
{
    CgalSurfaceMesh_t Mesh;
    CGAL::make_hexahedron<CgalSurfaceMesh_t, CgalPoint_t>
    (
        { 0.0,0.0,0.0 }, { 1.0,0.0,0.0 }, { 1.0,1.0,0.0 }, { 0.0,1.0,0.0 },
        { 0.0,1.0,1.0 }, { 0.0,0.0,1.0 }, { 1.0,0.0,1.0 }, { 1.0,1.0,1.0 },
        Mesh
    );
    CGAL::Polygon_mesh_processing::triangulate_faces(Mesh);

    CGAL::Surface_mesh_simplification::Count_stop_predicate<CgalSurfaceMesh_t> Stop(4);
    SVisitor Visitor;
    CGAL::Surface_mesh_simplification::edge_collapse(Mesh, Stop, CGAL::parameters::visitor(Visitor));
    Mesh.collect_garbage();

    std::cout << Mesh.num_faces() << std::endl;

    return 0;
}
```
This code is supposed to output "12", because the "vioPlacement" of every edge is set to null and thus no edge will be collapsed. However, it actually output "4", which means the "OnCollapsing()" doesn't affect whether an edge is to be collapsed. In contrast, "OnSelected()" works correctly. If I add the following code into "struct SVisitor", the output will be "12".
```
void OnSelected(const Profile& vProfile, boost::optional<FT>& vioCost, size_type, size_type)
{
    vioCost.reset();
}
```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows 64 bits
* Compiler: MSVC
* Release or debug mode: both
* Specific flags used (if any): 
* CGAL version: 5.5.2
* Boost version: 1.82.0
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by sloriot** [comment]
It's too late when you are in OnCollapsing, the collapsing decision is already made. The only thing you can influence is the position of the points. If `nullopt` it will not be set but the edge will be collapsed. The doc should be updated
