### ISSUE TITLE
Nef_3 pakage : transform() with abnormal memory usage

### ISSUE THREAD

**Issue by AstroJoke** [CGAL/cgal#8074]
## Issue Details

When invoke `CGAL::Nef_polyhedron_3::transform( const Aff_transformation_3& aff)` with multi-times, the memory will  increase sharply. And it will reproduce by arbitrary mesh.

The memory usage picture in the vs shows on the diagnostic tool as follow
![memory picture](https://github.com/CGAL/cgal/assets/44517212/e3277f3d-006b-45c4-8b7c-be3966f90861)

i try to debug and find that if i comment out line 1715 of the file `Nef_3/include/CGAL/Nef_polyhedron_3.h`, the memory will increase less than before. seems that new something and not delete. 

it seems that i should use the `Suface_mesh` with `PMP::transform` then convert it? 

## Source Code

```c++
#include <fstream>

#include <CGAL/Surface_mesh.h>
#include <CGAL/Nef_polyhedron_3.h>
#include <CGAL/OFF_to_nef_3.h>

#include <CGAL/Exact_predicates_exact_constructions_kernel.h>

using Exact_kernel = CGAL::Exact_predicates_exact_constructions_kernel;
using Nef_polyhedron = CGAL::Nef_polyhedron_3<Exact_kernel>;
using Surface_mesh = CGAL::Surface_mesh<Exact_kernel::Point_3>;
using Affine_transformation_3 = CGAL::Aff_transformation_3<Exact_kernel>;

int main(int argc, char** argv)
{
	std::string filePath = R"(C:\Users\Administrator\Desktop\a.off)";
	Affine_transformation_3 affTrans((0), (1), (0), (0),
									(1), (0), (0), (0),
									(0), (0), (1), (0));
	Surface_mesh mesh;
	Nef_polyhedron nef;
	std::ifstream ifs(filePath );
	CGAL::OFF_to_nef_3(ifs, nef);
	for (int i = 0; i < 360; i++)
	{
		nef.transform(affTrans);
	}
	return 0;
}

```
## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): windows 11, 64bits
* Compiler: msvc 172
* Release or debug mode: debug
* Specific flags used (if any): none
* CGAL version: latest ( 5.6.1), 
* Boost version: 1.84
* Other libraries versions if used (Eigen, TBB, etc.): none

**Comment by sloriot** [comment]
Underlying EPECK  there is a DAG that is keeping track of all operations done on geometry object to postpone exact computation to when it's needed. With this iterative update you are generating a deep DAG. You can collapse it by iterating over vertices of the Nef and calling `exact(vh->point())` to trigger exact computations. Note that memory will still increase as the exact number type will nonetheless require more precision to exactly encode the transformation.

**Comment by AstroJoke** [comment]
sorry that i am not clear about iterating 'over vertices of the Nef'. not mean i shuouldt invoke the

**Comment by AstroJoke** [comment]
@sloriot i try to add some code like as follow but seems the memory has no change compared with before
```c++
            SNC_structure& rSnc = this->snc();
            Vertex_iterator v0;
            for (v0 = rSnc.vertices_begin(); v0 != rSnc.vertices_end(); ++v0)
            {
                Point_3& p1 = v0->point();
                auto temp = CGAL::exact(p1);
            }
```

**Comment by sloriot** [comment]
You are right, it is not enough.
Adding
```
    for (auto hf = nef.halffacets_begin(); hf != nef.halffacets_end(); ++hf)
    {
      CGAL::exact(hf->plane());
    }
```
is better but still not enough. There is another lazy object somewhere.

Maybe using  `CGAL::Simple_cartesian<CGAL::Gmpq>` as `Exact_kernel` is an option for you.

**Comment by AstroJoke** [comment]
@sloriot yeah i attemped to write the code yesterday and find the memory increase less than before, but there are still not enough as you said.

Ii have another problem that if i replace `CGAL::Simple_cartesian<CGAL::Gmpq>` as `Epeck` , which let the memory not increase, the boolean operation it will be slower than `Epeck`?（I am sorry that i have not test   the speed of boolean diff by using `Epeck`).
