### ISSUE TITLE
Timeout in Triangulation_3 testsuite

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#808]
On Windows 64bit, VC12, Release we have testsuites with timeouts
* [Ic-138](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-138.shtml): test and examples
* [Ic-139] no timeout
* [Ic-140](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-140.shtml): examples

The examples use random data, and it is probably parallel code that hangs.
I will add printout of the seed, and a CGAL::Timer for each example, so that we can see which examples hangs.

**Comment by sloriot** [comment]
The problem has been fixed as it no longer shows up in the testsuite
