### ISSUE TITLE
Got strange exception when segment intersection

### ISSUE THREAD

**Issue by ChenKe404** [CGAL/cgal#8101]
## Issue Details

I want to do polygon intersect with segment, i use polygon's edges to do this, but sometime i get this exception...

Exception at 0x7fffebb3cf19, code: 0xe06d7363: C++ exception, flags=0x1 (execution cannot be continued) (first chance) at D:\Develop\depends\include\CGAL\Uncertain.h:114

exception happened:
![image](https://github.com/CGAL/cgal/assets/75658944/de9c04fd-33f2-4d12-97b0-facae3fcd60c)

polygon like this, the little one(5) have a point ON_BOUNDARY of big one(4):
![image](https://github.com/CGAL/cgal/assets/75658944/6833b768-c3d9-4220-8f91-9d4ed0c7a8fe)

## Source Code
```
template <class Kernel>
inline bool do_intersect(const CGAL::Polygon_2<Kernel>& pgn, const CGAL::Segment_2<Kernel>& seg)
{
    for(const auto& e : pgn.edges())
    {
        //  just do intersect edge with segment
        CGAL::Object res = CGAL::intersection(e,seg);    // exception right here but catched, i dont get any message
        if(CGAL::object_cast<CGAL::Segment_2<Kernel>>(&res))
            continue;
        else if (const auto pt = CGAL::object_cast<CGAL::Point_2<Kernel>>(&res))
        {
            if(is_on_segment(*pt,e) || is_on_segment(*pt,seg))
                continue;
            
            if(extremity_of_segemnt(e,*pt) || extremity_of_segemnt(seg,*pt))
                continue;
        }
    }
    return false;
}
```

## Environment

* Operating system (Windows 10 64 bits):
* Compiler: MSVC 2019
* Release or debug mode: debug
* Specific flags used (if any):
* CGAL version: 5.6.1
* Boost version: 1.83
* Other libraries versions if used (Eigen, TBB, etc.):

sorry about my english. >_<

**Comment by sloriot** [comment]
What Kernel are you using?

**Comment by ChenKe404** [comment]
@sloriot  Exact_predicates_exact_constructions_kernel

**Comment by sloriot** [comment]
Do you have an example I can compile and run to reproduce the error? Did you disable exception handling?

**Comment by ChenKe404** [comment]
maybe I can make an example, and the exception handling is enabled.

**Comment by sloriot** [comment]
Could you please try to provide a single .cpp doing only the operation that is failing?

**Comment by ChenKe404** [comment]
[example_1.zip](https://github.com/CGAL/cgal/files/14782806/example_1.zip)
@sloriot  single cpp right here, must run in debug mode, release mode is normal.

**Comment by sloriot** [comment]
Thanks for your effort to reduce it. However I'm afraid you reduced it a bit too much. When compiling and running with CGAL 5.6 I got no issue. It's printing "is point". Do you have something different?

**Comment by ChenKe404** [comment]
Thanks for your reply. 
When i run it in release mode, it just print "is point", it's fine. 
But when i run in debug mode, it just print execption message and exit immediately, if I put a breakpoint at calling "CGAL::intersection" and run in debug mode, i can get a execption message box and exit, no "is point" at all.

**Comment by sloriot** [comment]
What if you replace `Exact_predicates_exact_constructions_kernel` with `CGAL::Simple_cartesian<CGAL::Gmpq>`? What error do you get?

**Comment by ChenKe404** [comment]
![image](https://github.com/CGAL/cgal/assets/75658944/641892ee-ac1f-4fe1-9d60-7f469125b6da)
No breakpoint and no "is point"(sad)
![image](https://github.com/CGAL/cgal/assets/75658944/df17d842-436e-4155-97b1-3726a01d5b5f)
Put breakpoint and no "is point"(sad again)

**Comment by ChenKe404** [comment]
I'll try.

**Comment by ChenKe404** [comment]
if I use CGAL::Simple_cartesian<double>, it's work fine.  when I use CGAL::Simple_cartesian<CGAL::Gmpq>, I can't construct points and segments like normally. What should I do with this kernel?
![image](https://github.com/CGAL/cgal/assets/75658944/7b40e252-8de2-42ea-8b34-9d496919cc4f)

**Comment by sloriot** [comment]
```
#include <iostream>
#include <CGAL/Segment_2.h>
#include <CGAL/Exact_predicates_exact_constructions_kernel.h>

// using K = CGAL::Exact_predicates_exact_constructions_kernel;
using K = CGAL::Simple_cartesian<CGAL::Gmpq>;
using FT = K::FT;
using Point_2 = K::Point_2;
using Segment_2 = K::Segment_2;

using namespace std;

int main()
{
    Segment_2 seg_0(K::Point_2(FT(23.0),FT(174.0)), K::Point_2(FT(66.0), FT(57.0)) );
    Segment_2 seg_1(K::Point_2(FT(100.0) , FT(193.0) ), K::Point_2( FT(41.040738833826744), FT(124.91240828935513) ) );

    CGAL::Object res = CGAL::intersection(seg_0,seg_1);

    if(CGAL::object_cast<Segment_2>(&res))
        cout << "is segment" << std::endl;
    else if(CGAL::object_cast<Point_2>(&res))
        cout << "is point" << std::endl;

    return 0;
}
```

**Comment by ChenKe404** [comment]
Thanks , it work fine like kerenl ```CGAL::Simple_cartesian<double>```

**Comment by sloriot** [comment]
OK so I suspect you do have issue with exception handling. EPECK is using exceptions for doing filtered robust computation. I'm not familiar with MSVC but maybe it's because you run the program in MSVC rather than stand alone.

**Comment by ChenKe404** [comment]
Thanks, this reminds me. I switched toolchain to MinGW and it's work fine now. I think it's possible that Microsoft's CDB debugger is having a problem here, as this only occurs in debug mode.

**Comment by ChenKe404** [comment]
Thanks again. And can you help me with this issue? -> https://github.com/CGAL/cgal/issues/8102.
It bothered me for a long time. 
I'll be appreciate.
