### ISSUE TITLE
A point projected on line, but "bounded_side_2" returned not ON_BOUNDARY sometime

### ISSUE THREAD

**Issue by ChenKe404** [CGAL/cgal#8102]
## Issue Details

I have a line and a point(A), i calling "line_project_pointC2" to get a projected point(B), but when I call "bounded_side_2" with the line and point "B" as arguments, sometime(not always) return not ON_BOUNDARY

polygon like this:
![image](https://github.com/CGAL/cgal/assets/75658944/b4008dc1-dace-421d-b0a3-173ff1a4b3c2)

actually, the line is a edge of polygon 4, the point "B" is polygon 5's <that> point.
PS: "sometime" mean: i drawing one or more little polygon in a big one, every little one have one or more point on boundary of the big one, then i use "bounded_side_2" to get those point is on boundary or not, result is some points are on boundary and some points not.

## Source Code

```
// this function get distance from point to line, and output the projected point.
// a: a point
// b0, b1: two point on line
// out_dp: output projected point
// type of x and y is double
double plybn::disPnt2Lne(const Point &a, const Point &b0, const Point &b1, Point *out_dp)
{
    double A,B,C;
    CGAL::line_from_pointsC2(b0.x,b0.y,b1.x,b1.y,A,B,C);
    double o_x,o_y;
    CGAL::line_project_pointC2(A,B,C,a.x,a.y,o_x,o_y);
    if(out_dp) *out_dp = { o_x,o_y };
    return distanceC2(a.x,a.y,o_x,o_y);
}
```

## Environment

* Operating system (Windows 10 64 bits):
* Compiler: MSVC2019
* Release or debug mode: debug
* Specific flags used (if any):
* CGAL version: 5.6.1
* Boost version: 1.83
* Other libraries versions if used (Eigen, TBB, etc.):

Sorry about my english

**Comment by ChenKe404** [comment]
[example_2.zip](https://github.com/CGAL/cgal/files/14785633/example_2.zip)
Here is example, made a polygon and a point in center, then make center point projected on polygon's edge.

**Comment by MaelRL** [comment]
In your example you are using `CGAL::Exact_predicates_inexact_constructions_kernel`. With this kernel, there is no guarantee that your projection on the line is actually on the line due to numerical errors.

Do you get errors with the exact constructions kernel?

**Comment by ChenKe404** [comment]
Thanks for your reply. 
In fact, When I using ```CGAL::Exact_predicates_exact_constructions_kernel```, I dont know how to use ```CGAL::line_project_point``` to get projected point, so I use this code:
```
    template<class T>
    inline double dbl(const T& v)
    { return CGAL::to_double(v); }
......
    std::vector<std::pair<Point_2,bool>> pts;
    for(const auto& e : pgn.edges())
    {
        const auto& st = e.start();
        const auto& en = e.end();

        double A,B,C;
        CGAL::line_from_pointsC2(dbl(st.x()),dbl(st.y()),dbl(en.x()),dbl(en.y()),A,B,C);
        double x,y;
        CGAL::line_project_pointC2(A,B,C,dbl(p.x()),dbl(p.y()),x,y);

        // I can't construct point or line like this.
        // auto dp = CGAL::line_project_point(LineC2{A,B,C},PointC2{p.x(),p.y()});   
        pts.push_back(std::make_pair(Point_2{x,y},false));
    }
......
```
to get that, but the result is wrong.
so I tried ```CGAL::Exact_predicates_inexact_constructions_kernel```, but this result is wrong too.

**Comment by ChenKe404** [comment]
```
using K = CGAL::Exact_predicates_exact_constructions_kernel;
using Point_2 = K::Point_2;
using Line_2 = K::Line_2;
using PointC2 = CGAL::PointC2<K>;
using LineC2 = CGAL::LineC2<K>;
using Polygon_2 = CGAL::Polygon_2<K>;
......
LineC2 l0{A,B,C};   // error: no member named 'Handle' in 'CGAL::Epeck'; Line_2.h:38:33: error occurred here
```
```CGAL::line_project_point``` unsupport Point_2 and Line_2, need PointC2 and LineC2 when using ```CGAL::Exact_predicates_exact_constructions_kernel```, but I can't construct them.

**Comment by ChenKe404** [comment]
Silly me, I just have to call Line_2's member function "projection(Point_2)" or use the kernel function object "Construct_projected_point_2(Line_2,Point_2)". But, I still want know: why "CGAL::line_project_point" can't do this same?

**Comment by ChenKe404** [comment]
New question, how do I save the xy coordinates of projection point to double, and keep it exact?

**Comment by MaelRL** [comment]
If you go back to doubles, you'll lose the exactness except if the number fits without approximation within a double.

Some number can have their exact value dumped (for example as two integers for exact rationals), but that will usually not be compatible with means of reading the data. So, it depends what you want to do with the values once saved.
