### ISSUE TITLE
The vertex order of the bounding box outputted by CGAL::oriented_bounding_box() is not fixed.

### ISSUE THREAD

**Issue by linbeijianbaoxia** [CGAL/cgal#8110]
_Please use the following template to help us solving your issue._

## Issue Details

"I am using CGAL 5.6. I call CGAL::oriented_bounding_box to compute the OBB for a Surface_mesh, but when running the same program, I get two different orderings of the eight vertices of the bounding box, which confuses me. One ordering matches the parameter order of the CGAL::make_hexahedron() function, while the other seems to have no particular order."
![image](https://github.com/CGAL/cgal/assets/50166977/0918e2f0-9cb1-40db-9da9-5645dd75fe03)
![image](https://github.com/CGAL/cgal/assets/50166977/d2188ccd-44c2-468c-9c92-d2d83b65e9a9)

## Environment

* Operating system (Windows/64 bits):
* Compiler:
* Release or debug mode:
* Specific flags used (if any):
* CGAL version: 5.6

**Comment by MaelRL** [comment]
Can you please provide the code & input data?

**Comment by linbeijianbaoxia** [comment]
> Can you please provide the code & input data?
This is my code, similar to the example code. I apologize for the inconvenience, but it's not convenient for me to share my input model.
std::array<Point, 8> obb_of_mesh(const Mesh& sm)
{
    std::array<Point, 8> obb_points;
    CGAL::oriented_bounding_box(sm, obb_points,
        CGAL::parameters::use_convex_hull(true));

    return obb_points;
}

**Comment by sloriot** [comment]
Note that you can share only the points on the convex hull (if the input is confidential), the output will be identical.

**Comment by sloriot** [comment]
You can use this example for that: https://doc.cgal.org/latest/Convex_hull_3/Convex_hull_3_2extreme_points_3_sm_8cpp-example.html

**Comment by linbeijianbaoxia** [comment]
> 您可以使用此示例：https://doc.cgal.org/latest/Convex_hull_3/Convex_hull_3_2extreme_points_3_sm_8cpp-example.html

You're very welcome! I'll give it a try.

**Comment by MaelRL** [comment]
Both have the correct order, as described in the make_hexahedron function. Note that points are given in an order that is not related to the canonical axes (for example, the face P0-P3 has no reason to be the bottom face along the Z axis).

![image](https://github.com/CGAL/cgal/assets/5074170/ef42b32b-fd0b-47ee-9120-72b1ee4b91c7)

![image](https://github.com/CGAL/cgal/assets/5074170/5581e812-e8e3-4d99-9f3a-f8d6f6d8f643)

**Comment by linbeijianbaoxia** [comment]
> Both have the correct order, as described in the make_hexahedron function. Note that points are given in an order that is not related to the canonical axes (for example, the face P0-P3 has no reason to be the bottom face along the Z axis).
> 
> ![image](https://private-user-images.githubusercontent.com/5074170/318025038-ef42b32b-fd0b-47ee-9120-72b1ee4b91c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3NzE2NjUsIm5iZiI6MTcxMTc3MTM2NSwicGF0aCI6Ii81MDc0MTcwLzMxODAyNTAzOC1lZjQyYjMyYi1mZDBiLTQ3ZWUtOTEyMC03MmIxZWU0YjkxYzcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMzBUMDQwMjQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGE4Nzk5MWU3OWQxYzUwNGY3MjU1YmMxMmMwZGIzNTYzOGI3Y2IyYzZiMDI3MjQxZTc0Mzg0NWMzOWZlZmRkZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ZCQ0BzORzhaVN2tHUzntIsWcKH0tMXe8aL1wcjVV0WY)
> 
> ![image](https://private-user-images.githubusercontent.com/5074170/318005763-5581e812-e8e3-4d99-9f3a-f8d6f6d8f643.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3NzE2NjUsIm5iZiI6MTcxMTc3MTM2NSwicGF0aCI6Ii81MDc0MTcwLzMxODAwNTc2My01NTgxZTgxMi1lOGUzLTRkOTktOWYzYS1mOGQ2ZjZkOGY2NDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMzBUMDQwMjQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Njk2YWZmN2Y2OGVkMGU3YjlkODI4MGY1ZDU1ZGEzNTk1OTM4NGQwMDc0ZjUwMWM3ZTUxZWJjYWU4ODY4ZjhlOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-tgnQt9XaDMav6zuAqyOGWy2dGP5XGwhnH5PPCxowcU)

Hello, actually, I'm calculating the bounding box to obtain the center point of the OBB, along with its three directional vectors and their corresponding half-lengths. These eight vertices cannot provide me with the information I need. I wonder if CGAL has other suitable tools.

**Comment by MaelRL** [comment]
The vertices are given in the order shown on the figure of the documentation of [CGAL::make_hexahedron()](https://doc.cgal.org/latest/BGL/group__PkgBGLHelperFct.html#gad9df350e98780f0c213046d8a257358e).

You can get directional vertices and half lengths with `PX - P0` and the center of the OBB with `P0 + 0.5 * (P1 - P0) + 0.5 * (P3 - P0) + 0.5 * (P5 - P0)`.
