### ISSUE TITLE
LAStools support

### ISSUE THREAD

**Issue by mbredif** [CGAL/cgal#8111]
LAStools has evolved since CGAL forked it in https://github.com/CGAL/LAStools. I think we can now try to use it directly.

- LAStools now supports Cmake natively
- Among other new features, LAStools now support the COPC extension, which enables embedding an octree section in the las/laz (a VLR) for efficient pruning of the point range given a query 3D bbox. 
- Version 240319 introduces a breaking change in the constructor of all `LASreader`s. They now expect a `LASreadOpener*` argument : https://github.com/LAStools/LAStools/commit/c3012b6e94ba7abc90236faa4899bf34d38b4dc8    See also this reported [issue](https://github.com/LAStools/LAStools/issues/193)
- Missing functions in the dll. See this [pull request](https://github.com/LAStools/LAStools/pull/194)

**Comment by afabri** [comment]
@soesau can you check if we can switch to the latest version.
