### ISSUE TITLE
Documentation in CGAL::Polyline_simplification_2::Stop_above_cost_threshold Class

### ISSUE THREAD

**Issue by lryan599** [CGAL/cgal#8114]
**Documentation in CGAL::Polyline_simplification_2::Stop_above_cost_threshold Class**

![Y%EM7H2@PFM ITKXF2EFHAP](https://github.com/CGAL/cgal/assets/77947703/c88229aa-a16c-4602-a26b-12bffd2b4808)

![image](https://github.com/CGAL/cgal/assets/77947703/b95b6389-635c-4c6c-942c-9835a220f3c9)

I believe that it should be _Returns true when cost is greater or equal than the threshold_.

**Comment by Madhusri02** [comment]
What changes should be made here.. can i get some detailed explanation

**Comment by lryan599** [comment]
> What changes should be made here.. can i get some detailed explanation

`Stop_above_cost_threshold` class need to return true if the cost given by a cost function ***greater than or equal*** to a threshold `mThres`. See the source code. But the document was written as ***smaller or equal than*** the threshold. This is just a small mistake.

**Comment by afabri** [comment]
Thank you for pointing this out @lryan599
