### ISSUE TITLE
Automatic summary page with all warnings and errors, with a link to the corresponding entry in the result matrix.

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#8162]

**Comment by lrineau** [comment]
This issue is now almost done. @SaillantNicolas Can you please give the URL to the summary page?

Maybe it is now time to introduce that page in the official test results page?

**Comment by SaillantNicolas** [comment]
The first version of the summary page already exists in the testsuite, a link is present towards this summary page on the testsuite page. 

However, a Pull Request exists with features for this summary page.

**Comment by lrineau** [comment]
> The first version of the summary page already exists in the testsuite, a link is present towards this summary page on the testsuite page.
> 
> However, a Pull Request exists with features for this summary page.

That is right. I had not seen it. [Here is it](https://cgal.geometryfactory.com/CGAL/testsuite/results-6.0-Ic-229.shtml):
![Screenshot_20240425_102318](https://github.com/CGAL/cgal/assets/5746675/c44d6bea-2330-4a85-962b-0613c170e1de)

**Comment by lrineau** [comment]
The pull-request is https://github.com/CGAL/cgal/pull/8127. Is there somewhere we can see the result of that pull-request, to review the modifications?

**Comment by SaillantNicolas** [comment]
The version of this Pull Request can be reviewed at [this link](https://cgal.geometryfactory.com/~nsaillant/testsuite/TESTRESULTS/).
