### ISSUE TITLE
No function `square_free_factorize` 1/2

### ISSUE THREAD

**Issue by stla** [CGAL/cgal#8182]
Hello,

The [documentation](https://doc.cgal.org/latest/Polynomial/group__PkgPolynomialFunctions.html#ga58d5d7c20cbbe6bddf320483f44fb53d) mentions two functions `square_free_factorize` in the **Polynomial package**. The first one, with three arguments, does not exist. I tried and I got a *"no match for call to ..."* error when compiling, and I also searched  for this function in the code. But we can use `PolynomialTraits_d::Square_free_factorize`.

**Comment by lrineau** [comment]
Now fixed by https://github.com/CGAL/cgal/pull/8189 merged in `master`. @stla The title of this issue is strange (`1/2`). Should we expect a second part of it?

**Comment by stla** [comment]
> @stla The title of this issue is strange (`1/2`). Should we expect a second part of it?

No. `1/2` refers to the documentation. There is the function `square_free_factorize` (1/2)  and the function `square_free_factorize` (2/2). The missing one is `1/2`.
