### ISSUE TITLE
Document issue about generalized map's insert 2-cell in 3-cell

### ISSUE THREAD

**Issue by eiiijiiiy** [CGAL/cgal#8195]
[The example of inserting a 2-cell in a 3 cell given in the user manual of Package Generalized Maps](https://doc.cgal.org/latest/Generalized_map/index.html#ssecoperationsgmap) lists the inserted 2-cell as `std::vector{dh1, ..., dh8}`, as shown in the figure below. However, if I understand it correctly, the implementation of `is_insertable_cell_2_in_cell_3` and [the other example of gm operations](https://doc.cgal.org/latest/Generalized_map/Generalized_map_2gmap_3_operations_8cpp-example.html) indicate it should be `std::vector{dh1, dh3, dh5, dh7}` instead of the full loop from `dh1` to `dh8`. The latter actually fails the assertion of `is_insertable_cell_2_in_cell_3`.
<img width="1139" alt="image" src="https://github.com/CGAL/cgal/assets/68719911/2d9b7cb2-7e41-4276-a5be-1950f582bad0">

**Comment by gdamiand** [comment]
Thanks for the issue: this is indeed a bug in the doc. Fixed in #8199.

**Comment by lrineau** [comment]
@eiiijiiiy Thanks. That is now merged and fixed in CGAL `master` branch. PR https://github.com/CGAL/cgal/pull/8199

**Comment by eiiijiiiy** [comment]
thanks all!!
