### ISSUE TITLE
`QOpenGLContext::functions()`, the d-pointer is null (was QScopedPointer exception)

### ISSUE THREAD

**Issue by 271812697** [CGAL/cgal#8209]
_Please use the following template to help us solving your issue._

## Issue Details

I build CGAL with Cmake,After building, all project concerning with Qt will appear exception,for example when i run AABB_demo, an exception occurs as follow

## Picture

<img width="1274" alt="异常" src="https://github.com/CGAL/cgal/assets/38773493/9358067e-738b-4d99-acca-544eb3296c85">

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):
* Compiler:
* Release or debug mode:
* Specific flags used (if any):
* CGAL version:
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by lrineau** [comment]
Hi buranya (@271812697), from what I can see, and guess, from your issue report, the error is probably on your side. It seems you generated a Visual Studio project, using CMake, as it should be. Probably from CGAL-5.6.1, but I am not sure.

We need the following information, to help you:

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): It seems to be Windows. **32 or 64 bits?**
* Compiler: probably Visual C++, **right**? **Which version of Visual Studio, and which compiler toolkit?**
* Release or debug mode: **?**
* Specific flags used (if any): unless you specified additional flags yourself, forget this.
* CGAL version: CGAL-5.6.1, **please confirm**
* Boost version: 
* Other libraries versions if used (Eigen, TBB, etc.): **please tell us which Qt version**

**Comment by 271812697** [comment]
Thank you so much，I compile CGAL with following environment:
### Environment

- Operation system(Windows,64 bits)
- Compiler:Visual C++,Visual Studio 2022
- Debug
- Specific flags used: use CMake GUI'default settings,with demo selected,with examples selected
- CGAL verison:CGAL-5.6.1
- Boost version:1.7.2
- Other libraries version:Qt 6.7.0

The projects concerning with Qt compile successfully,but will occur exception,the stack is as following:
![image](https://github.com/CGAL/cgal/assets/38773493/737362e3-47c7-44d3-9e6d-c25f7fc14058)
![image](https://github.com/CGAL/cgal/assets/38773493/6a90cf62-a72d-400a-b525-cb41bc1a13c5)



![image](https://github.com/CGAL/cgal/assets/38773493/8db02743-7046-457c-a804-65a73036f2d2)

**Comment by lrineau** [comment]
@271812697 Thanks for the information. There is an issue, though: you mention that you are use CGAL-5.6.1, and Qt-6.7.0. However, CGAL-5.6.1 is not compatible with Qt6, but only with Qt5. Can you please verify?

**Comment by 271812697** [comment]
Thank you so much,as you say, This exception is indeed caused by the incompatibility of the Qt version.
When I changed the Qt version, the problem was solved!
