### ISSUE TITLE
Three/demo/Three is not compiled by the testsuite

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#825]
@sloriot @maxGimeno 

We can see [here](https://cgal.geometryfactory.com/CGAL/Members/testsuite/#Three_Demo) that the example plugin in `Three/demo/Three` is not compiled by the testsuite.

**Comment by maxGimeno** [comment]
I think it is caused byt the line 

find_package(CGAL_polyhedron_demo
  HINTS "${CGAL_DIR}" "${CGAL_DIR}/Polyhedron/demo/Polyhedron-build"
  )

which doesn't work.

**Comment by sgiraudot** [comment]
As far as I can see on the latest testsuite, the issue is still not solved.

On the #846 PR, @lrineau said:

> Actually, I do not see how we can make it work in the testsuite. We should discuss and work on that topic next week.

(Next week was the developer meeting of last spring.)

What is the conclusion? Do we still need to compile the example plugin for the testsuite? Do we keep this issue opened?

**Comment by lrineau** [comment]
That topic was not raise during the last developers meeting (Zurich'16). I should be discussed between us (@maxGimeno).

**Comment by sloriot** [comment]
ping @maxGimeno

**Comment by maxGimeno** [comment]
Still no news about that.

**Comment by sloriot** [comment]
@maxGimeno Actually I don't understand what this issue is about. What are you missing? Why does it seems to be OK on some platforms?

**Comment by maxGimeno** [comment]
The examples need the polyhedron demo to be fully compiled to work, but are located in the package Tree. AFAIK we have no way to tell the testsuite to manage this kind of situation.
