### ISSUE TITLE
Install OpenMesh in our Docker images

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#826]
@sloriot @bo0ts 

We can see [here](https://cgal.geometryfactory.com/CGAL/Members/testsuite/#BGL_OpenMesh_Examples) that the OpenMesh bindings are not tested by the testsuite. We should install OpenMesh is a few Docker images, and on Windows. @janetournois, can you easily activate the support for OpenMesh in the testsuite of SOSNO?

**Comment by janetournois** [comment]
It should not be too hard on sosno, since I already have OpenMesh available.
I'll try to do it before tonight's testsuite

**Comment by lrineau** [comment]
@janetournois As far as I can see [OpenMesh is still not detected in today's SONOS test results][1].

[1]: https://cgal.geometryfactory.com/CGAL/Members/testsuite/CGAL-4.8-Ic-148/BGL_OpenMesh_Examples/TestReport_jtournois_x64_Cygwin-Windows8_MSVC2015-Release-64bits.gz

**Comment by janetournois** [comment]
I made the changes, it should be OK tonight

**Comment by janetournois** [comment]
Still not working. I made some more changes that will hopefully fix it

**Comment by janetournois** [comment]
OpenMesh is now tested on Sosno (msvc 2015), at last!
