### ISSUE TITLE
How do I get a pdf or html doc of the manuals?

### ISSUE THREAD

**Issue by wanfuse123** [CGAL/cgal#8288]
## Issue Details

_Describe your issue. Please be specific (compilation error, runtime error, unexpected behavior, wrong results, etc.)._
NEED DIRECTIONS ON HOW TO BUILD THE MANUAL FROM THE SOURCE the C++ API USERS /DEVELOPERS GUIDES

FOR DEBIAN 12

**Comment by MaelRL** [comment]
See https://github.com/CGAL/cgal/wiki/Building-the-Documentation
