### ISSUE TITLE
stitch_borders_example output error

### ISSUE THREAD

**Issue by citystrawman** [CGAL/cgal#8300]
_Please use the following template to help us solving your issue._

## Issue Details

I am studying the polygon mesh processing stitch_borders_example, and I think this example shows that by using stitch_borders(), it will stitch the duplicated nodes, I ran this program and from the off file we can see that it actually does merge duplicated nodes:
```
quads_to_stich.off:
OFF
20 8 0
1 0 0
0.75 0 0
0.5 0 0
0.25 0 0
0 0 0
0 1 0
0.25 1 0
0.5 1 0
0.75 1 0
1 1 0
1 1 0
0.75 1 0
0.5 1 0
0.25 1 0
0 1 0
0 2 0
0.25 2 0
0.5 2 0
0.75 2 0
1 2 0
4  5 6 3 4
4  3 6 7 2
4  1 2 7 8
4  1 8 9 0
4  15 16 13 14
4  13 16 17 12
4  11 12 17 18
4  11 18 19 10
```

```
mesh_stitched.off:
OFF
15 8 0

1 0 0
0.75 0 0
0.5 0 0
0.25 0 0
0 0 0
0 1 0
0.25 1 0
0.5 1 0
0.75 1 0
1 1 0
0 2 0
0.25 2 0
0.5 2 0
0.75 2 0
1 2 0
4  5 6 3 4
4  3 6 7 2
4  1 2 7 8
4  1 8 9 0
4  10 11 6 5
4  6 11 12 7
4  8 7 12 13
4  8 13 14 9
```

however, in the terminal output, it is shown as follows:
```
Before stitching :
         Number of vertices  :  15
         Number of halfedges :  44
         Number of facets    :  8
Stitching done :
         Number of vertices  :  15
         Number of halfedges :  44
         Number of facets    :  8
```
I dont know if this is a bug ?

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):
* Compiler:
* Release or debug mode:
* Specific flags used (if any):
* CGAL version:
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by MaelRL** [comment]
You are probably using a CGAL::Surface_mesh and getting the number of elements through [`num_vertices()`](https://doc.cgal.org/latest/BGL/classVertexListGraph.html#a77e742c910da6a8230a45273186b130b) and similar functions.

As [the doc](https://doc.cgal.org/latest/BGL/classVertexListGraph.html#a77e742c910da6a8230a45273186b130b) indicates:

> [num_vertices()](https://doc.cgal.org/latest/BGL/classVertexListGraph.html#a77e742c910da6a8230a45273186b130b) may return a number larger than std::distance(vertices(g).first, vertices(g).second). This is the case for implementations only marking vertices deleted in the vertex container.

This is because the surface mesh will have "garbage" (removed elements), which are not purged from memory unless you call [`collect_garbage()`](https://doc.cgal.org/latest/Surface_mesh/classCGAL_1_1Surface__mesh.html#aea69dbef8122b1acf050c19063f935f2).

If you want the exact number of elements, you can use the [number_of_vertices](https://doc.cgal.org/latest/Surface_mesh/classCGAL_1_1Surface__mesh.html#a10ba0d4fbb6ffaf0be57c5a088cc922b) member function of the CGAL::surface_mesh, or `std::distance(...)`, or `vertices(sm).size()`, or `CGAL::internal::exact_num_vertices(sm)`, ...

**Comment by citystrawman** [comment]
> You are probably using a CGAL::Surface_mesh and getting the number of elements through [`num_vertices()`](https://doc.cgal.org/latest/BGL/classVertexListGraph.html#a77e742c910da6a8230a45273186b130b) and similar functions.
> 
> As [the doc](https://doc.cgal.org/latest/BGL/classVertexListGraph.html#a77e742c910da6a8230a45273186b130b) indicates:
> 
> > [num_vertices()](https://doc.cgal.org/latest/BGL/classVertexListGraph.html#a77e742c910da6a8230a45273186b130b) may return a number larger than std::distance(vertices(g).first, vertices(g).second). This is the case for implementations only marking vertices deleted in the vertex container.
> 
> This is because the surface mesh will have "garbage" (i.e., removed elements) after calling `PMP::stitch_borders` duplicate elements have been removed during stitching. In `CGAL::Surface_mesh`, these are not purged from memory unless you call [`collect_garbage()`](https://doc.cgal.org/latest/Surface_mesh/classCGAL_1_1Surface__mesh.html#aea69dbef8122b1acf050c19063f935f2) and thus the number of elements through `num_vertices(sm)` is unchanged.
> 
> If you want the exact number of elements without collecting garbage, you can use the [number_of_vertices](https://doc.cgal.org/latest/Surface_mesh/classCGAL_1_1Surface__mesh.html#a10ba0d4fbb6ffaf0be57c5a088cc922b) member function of the CGAL::surface_mesh, or `std::distance(...)`, or `vertices(sm).size()`, or `CGAL::internal::exact_num_vertices(sm)`, ...

but the output shows the numbe of vertex after stitching, not before stitching, which is weired

**Comment by afabri** [comment]
@citystrawman can you please put a self contained example on gist.github.com so that we can reproduce/fix.

**Comment by citystrawman** [comment]
> @citystrawman can you please put a self contained example on gist.github.com so that we can reproduce/fix.
> 
> You refer to an example, but the [example for stitching](https://doc.cgal.org/latest/Polygon_mesh_processing/Polygon_mesh_processing_2stitch_borders_example_8cpp-example.html) uses `Polyhedron` and not `Surface_mesh`.

Hi, this issue is explained by MaelRL. Thank you!
