### ISSUE TITLE
How to do Minkowski Sum inside a 2D polygon?

### ISSUE THREAD

**Issue by KraftOreo** [CGAL/cgal#8303]
## Issue Details

I am trying to find the Minkowski sum of two polygons where the summation happens inside one of the two polygons. Basically, I am trying to shrink the first polygon by the second one. The way I do it now is to change the first polygon to the clockwise orientation and then call the regular function `CGAL::minkowski_sum_2()`. However, this approach results in a wrong representation of the Minkowski sum.  In the following code, `polygon2` is the final result, and I drew them out in the following figures:
![robotSum](https://github.com/CGAL/cgal/assets/38533691/bdaf9437-11d0-4650-824d-b8aeb33eeb6b)
![sum](https://github.com/CGAL/cgal/assets/38533691/2aefbd36-daf6-4a4f-85ea-3d2ceb29a813)
The dark cyan polygon is the `polygon0` in the code, and the pink polygon in the first picture is the other polygon to be summed, which is the `polygon1` in the following code.  The pink polygon in the second image is the final result, which includes some unnecessary/redundant points. A workaround I can think of is: 

1. Wrap the dark cyan polygon with a larger boundary and then do a convex decomposition
2. Do Minkowski sum between each pair of the convex component and the pink polygon
3. Merge all the sums together and then take the inner hole of the sum as the final result.

But this workaround seems somehow too complicated, so I am wondering if there are any better ways to do this?

Also, I have a side question: I am doing the Minkowski sum so that I can calculate the Visibility Graph of all the summed polygons later. Right now, I am using the Triangular_expansion_2 function to calculate the visible area of each vertex of all polygons, and then every vertex is checked for whether they are in this area. If so, they are connected and stored in a graph data structure. I just want to ask if there are any better ways to retrieve the visible vertices directly or faster ways to calculate the visibility graph. 

Thanks in advance for all your help and effort!

Best regards
 

## Source Code
```cpp
#include <CGAL/convex_hull_2.h>
#include <CGAL/Convex_hull_traits_adapter_2.h>
#include <CGAL/minkowski_sum_2.h>
#include <CGAL/Polygon_convex_decomposition_2.h>
#include <CGAL/Polygon_triangulation_decomposition_2.h>
#include <CGAL/Boolean_set_operations_2.h>
#include <CGAL/draw_polygon_2.h>

typedef CGAL::Exact_predicates_exact_constructions_kernel K;
typedef K::Point_2 Point_2;
typedef CGAL::Polygon_2<K> Polygon_2;
typedef CGAL::Polygon_with_holes_2<K> Polygon_with_holes_2;
typedef CGAL::Convex_hull_traits_adapter_2<K, CGAL::Pointer_property_map<Point_2>::type> Convex_hull_traits_2;

int main()
{
    std::vector<Point_2> vertices0 = {
        Point_2(-10, 10),
        Point_2(-5, 10),
        Point_2(-5, 6),
        Point_2(5, 6),
        Point_2(5, 10),
        Point_2(10, 10),
        Point_2(10, -10),
        Point_2(-10, -10)};

    std::vector<Point_2> vertices1 = {
        Point_2(-0.500000, -1.000000),
        Point_2(0.066987, -1.116025),
        Point_2(0.500000, -1.000000),
        Point_2(0.933013, -0.616025),
        Point_2(0.500000, 1.000000),
        Point_2(-0.066987, 1.116025),
        Point_2(-0.500000, 1.000000),
        Point_2(-0.933013, 0.616025),
    };
    Polygon_2 polygon0(vertices0.begin(), vertices0.end());
    Polygon_2 polygon1(vertices1.begin(), vertices1.end());
    std::string robotDrawScript;

    if (polygon0.is_clockwise_oriented())
    {
        polygon0.reverse_orientation();
    }
    if (polygon1.is_clockwise_oriented())
    {
        polygon1.reverse_orientation();
    }

    polygon0.reverse_orientation();
    Polygon_with_holes_2 sum = CGAL::minkowski_sum_by_reduced_convolution_2(polygon0, polygon1);
    Polygon_2 polygon2 = sum.outer_boundary();

    return 0;
}
```

## Environment

* Operating system: Ubuntu 22.04 64bits
* Compiler: gcc 11.4
* Release or debug mode: Both Release and Debug
* Specific flags used (if any):
* CGAL version: 5.6.1
* Boost version: Version: 1.74.0.3ubuntu7
* Other libraries versions if used (Eigen, TBB, etc.): None

**Comment by efifogel** [comment]
1. A clockwise oriented polygon is an invalid input
2. What you call a workaround is a solid method. Make sure that you use the
CGAL::Polygon_set class template to carry out the final unions, and try to
decompose the polygon with the hole into as few as possible simple polygons.
3. You can construct the complement of the first polygon using the
CGAL::complement() free function.
This would yield an object the type of which is an instance of the
CGAL::Polygon_with_holes_2 template.
Then, you can compute the Minkowski sum of the resulting polygon and your
offset polygon.
However, you will be constrained using the Minkowski sum functions that
support polygons with holes as one of the summands. (Not all do.)
4. Check out the 2D Visibility CGAL package.
   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by KraftOreo** [comment]
Thanks! Then I'll try it out. Thanks for clarifying everything!
