### ISSUE TITLE
Mesh_3 deprecated mesh domains removed in CGAL 6.0 Beta 1

### ISSUE THREAD

**Issue by joachim-reichel** [CGAL/cgal#8311]
Compiling pygalmesh from Debian unstable against CGAL 6.0 Beta 1 fails since <CGAL/Implicit_mesh_domain_3.h> is missing. Please check whether it is possible to include a legacy header including the replacement headers with a suitable deprecation message. Otherwise, it might be a good idea to describe in the release notes how to modify the affected code.

Compiling octave-iso2mesh from Debian unstable against CGAL 6.0 Beta 1 fails since <CGAL/Labeled_image_mesh_domain_3.h> is missing. Please check whether it is possible to include a legacy header including the replacement headers with a suitable deprecation message. Otherwise, it might be a good idea to describe in the release notes how to modify the affected code.

**Comment by MaelRL** [comment]
Here is the commit removing the three deprecated (since 4.13) labeled mesh domains: [`b3fe07a` (#7445)](https://github.com/CGAL/cgal/pull/7445/commits/b3fe07a51d8673fd7dcac79433510cd1f453956b)

**Comment by afabri** [comment]
Hello @joachim-reichel,
As pointed out by @MaelRL these files are deprecated for a while now and had a deprecation warning. Changing the major release number seems a good time to clean up and remove. The downstream projects have to upgrade. Are they aware of it? Do we have to file an issue in the respective projects?  What do you consider as best practice?

**Comment by joachim-reichel** [comment]
Since I didn't know the downstream projects and just tried to build them I wasn't aware that there were already deprecation warnings with CGAL 5.x. All projects that I pointed out in the thread on cgal-develop have now patches filed (some merged/released, others still unmerged/unreleased). So I think we are good as far as reverse dependencies in the Debian repository are concerned.

**Comment by sloriot** [comment]
Should be fixed by https://github.com/fangq/iso2mesh/pull/79

**Comment by sloriot** [comment]
The PR has been merged, I'm closing the issue.
