### ISSUE TITLE
CGALlab.zip cannot download in CGAL 6.0 beta

### ISSUE THREAD

**Issue by liu411417492** [CGAL/cgal#8316]
_Please use the following template to help us solving your issue._

## Issue Details

CGALlab.zip cannot download in CGAL 6.0 beta
It report 404 not found in url: https://www.cgal.org/demo/CGALlab.zip
when other demo can download normally

**Comment by lrineau** [comment]
Fixed now: https://www.cgal.org/demo/6.0/CGALlab.zip
