### ISSUE TITLE
Reachability of file ftp://ftp.mpi-sb.mpg.de/pub/outgoing/CGAL/Ridges_3_datafiles.tgz

### ISSUE THREAD

**Issue by albert-github** [CGAL/cgal#8327]
In the file Ridges_3/doc/Ridges_3/Ridges_3.txt we have the code:
```
\cgalFootnote{Model data may be downloaded via ftp://ftp.mpi-sb.mpg.de/pub/outgoing/CGAL/Ridges_3_datafiles.tgz . The mechanical part model has been provided courtesy of Dassault System to produce \cgalFigureRef{figmechanical_crest_filteredintro}, due to copyright issues the available model is not the same, it is provided by the AIM\@SHAPE Shape Repository.}
```

I was not able to retrieve this linked ftp file.
Wouldn't it be better to have this file somewhere on a CGAL server or is this not possible due to copyright restrictions?

**Comment by sloriot** [comment]
@pougetma do you have some files locally or in your archives?

**Comment by afabri** [comment]
There are more things to fix: 

-  "cgal:p-gd-01"      in the sentence "the reader may consult [[3]](https://doc.cgal.org/latest/Ridges_3/citelist.html#CITEREF_cgal:hgygm-ttdpf-99),cgal:p-gd-01, as well as"
- The examples in the User Manual do as if a `data` directory existed
