### ISSUE TITLE
Compilation failure with operator << and CGAL_Core/include/CGAL/CORE/RealRep.h

### ISSUE THREAD

**Issue by efifogel** [CGAL/cgal#8333]
## Issue Details

The example program below causes a compilation warning with g++ and a compilation failure with MSVC.  At first glance it seems like a compiler bug, but it  happens on completely 2 different compilers, so probably a bug in CGAL code. What is even more strange is that if I remove the parameter from the constructor of Arc (replace lines 5 and 6) the code compiles flawlessly with both compilers. In any case, I believe that the CGAL code can be altered to avoid this issue altogether. 

Also, notice that the the error is from CGAL_Core/include/CGAL/CORE/RealRep.h so to reproduce you probably need to configure CGAL with Core:

`find_package(CGAL REQUIRED COMPONENTS Core`

```
#include <CGAL/Exact_predicates_exact_constructions_kernel.h>

class Arc {
public:
  Arc(int index) {};
  // Arc() {};
};

namespace std {
template <typename OutputStream>
inline OutputStream& operator<<(OutputStream& os, const Arc& arc) { return os; }
}

int main() { return 0; }
```

Attached are files that contain the warning and error messages from VC and g++, respectively.
[vc_error.txt](https://github.com/user-attachments/files/16086449/vc_error.txt)
[g++_warning.txt](https://github.com/user-attachments/files/16086450/g%2B%2B_warning.txt)

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows, Ubuntu 22.04
* Compiler: VC 2022 (17.9.5.7608), g++ (11.4.0)
* Release or debug mode:
* Specific flags used (if any):
* CGAL version: latest
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by mglisse** [comment]
Couldn't the bug be in your testcase? Adding random overloads in namespace std is bound to cause problems.

**Comment by efifogel** [comment]
It's an isolated bug; see the simple program that reproduces it.
The overloads are not random but rather needed....
The problem can be eliminated by changing the code in RealRep.h...and this
is probably what needs to be done.
   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by mglisse** [comment]
```c++
#include <sstream>

struct Arc {
  Arc(int index) {};
};

namespace std {
template <typename OutputStream>
inline OutputStream& operator<<(OutputStream& os, const Arc& arc) { return os; }
}

int main() {
  std::stringstream s;
  s << 42;
}
```
already gives the same warning with g++ and an error with MSVC.

**Comment by efifogel** [comment]
ok, now I get it. Thanks!
If I add 'explicit':

explicit Arc(int index) {};

the error goes away.
Close the issue.
   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/
