### ISSUE TITLE
Segment_2 has_on returns unexpected results

### ISSUE THREAD

**Issue by barulicm** [CGAL/cgal#8346]
## Issue Details

`Segment_2::has_on` can return the wrong answer given segments that are slightly off axis. In some cases, the order of the segment points changes the answer given.

We are getting the points passed to `has_on` from a projection to the segment's supporting line. The order of the segment points does not appear to change the projected point.

## Source Code

```
#include <iostream>
#include <CGAL/Simple_cartesian.h>

using Kernel = CGAL::Simple_cartesian<double>;
using Point = Kernel::Point_2;
using Segment = Kernel::Segment_2;

int main() {
  Point p{-3.0, 1.0};

  Segment s{
    Point{0.0, 0.0},
    Point{-7.0, 1e-4}
  };
  // Expected true, actually returns true
  std::cout << s.has_on(s.supporting_line().projection(p)) << "\n";

  Segment s2{
    Point{-7.0, 1e-4},
    Point{0.0, 0.0}
  };
  // Expected true, actually returns false
  std::cout << s2.has_on(s2.supporting_line().projection(p)) << "\n";

  Point p2{-1.0, 1.0};

  Segment s3{
    Point{-2.0, 1e-4},
    Point{0.0, 0.0}
  };
  // Expected true, actually returns false
  std::cout << s3.has_on(s3.supporting_line().projection(p2)) << "\n";

  Segment s4{
    Point{0.0, 0.0},
    Point{-2.0, 1e-4}
  };
  // Expected true, actually returns false
  std::cout << s4.has_on(s4.supporting_line().projection(p2)) << "\n";

  return 0;
}
```

## Environment

* Operating system: Ubuntu 22.04 
* Compiler: g++
* Release or debug mode: happens in both Debug and Release
* Specific flags used (if any): n/a
* CGAL version: 5.4 (git hash: c58ac97e93c838ebfb1e8adaf23ff4fd185dc8e4)
* Boost version: 1.74
* Other libraries versions if used (Eigen, TBB, etc.): n/a

**Comment by sloriot** [comment]
Replacing `using Kernel = CGAL::Simple_cartesian<double>;` by `using Kernel = CGAL::Exact_predicates_exact_constructions_kernel;` should fix the wrong results.

See all this [FAQ entry](https://www.cgal.org/FAQ.html#inexact_NT)

**Comment by barulicm** [comment]
Thanks for the info!
