### ISSUE TITLE
Suspicious repeated lines

### ISSUE THREAD

**Issue by mglisse** [CGAL/cgal#8348]
Inspired by #8347, I looked for identical consecutive lines in CGAL headers. Some are completely normal, some are harmlessly redundant, some really look like they were supposed to be different.

https://github.com/CGAL/cgal/blob/847df9a0c9cbfee1168b4d3f969e082d431a39c9/Periodic_3_triangulation_3/include/CGAL/Periodic_3_regular_triangulation_3.h#L932-L934

https://github.com/CGAL/cgal/blob/847df9a0c9cbfee1168b4d3f969e082d431a39c9/Triangulation_2/include/CGAL/Triangulation_2/insert_constraints.h#L87-L88

etc. I think it would be worth it if someone could take a look to check that none are real bugs like the one in Triangulation.

**Comment by afabri** [comment]
As far as the periodic one goes I would guess that it should be `2`  instead of `1` in line 934. @MaelRL can you confirm?

**Comment by MaelRL** [comment]
yes it should, it's a bad copy paste.

**Comment by afabri** [comment]
Concerning the 2D triangulation, blame lists me. Reading it several times I do not see what else could be there, so I suggest to remove the duplicate.
