### ISSUE TITLE
draw_nef_3.cpp demo does not work with two passed filenames

### ISSUE THREAD

**Issue by Hermann-SW** [CGAL/cgal#8363]
## Issue Details

because of index error P1 and P2 get read from same file, and N1-N2 results in empty display always.

## Source Code

https://github.com/CGAL/cgal/blob/master/Nef_3/examples/Nef_3/draw_nef_3.cpp#L19
```
  std::ifstream ifs2((argc > 1) ? argv[1] : CGAL::data_file_path("meshes/beam.off"));
```
needs to be
```
  std::ifstream ifs2((argc > 2) ? argv[2] : CGAL::data_file_path("meshes/beam.off"));
```
  
## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Linux
* Compiler: g++
* Release or debug mode: release
* Specific flags used (if any): see CGAL cmake file
* CGAL version: 5.6.1
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by sloriot** [comment]
Thanks for the report!
