### ISSUE TITLE
CGAL_Precondition failed on Polygon_2 intersection with double coordinates.

### ISSUE THREAD

**Issue by MaartenHilferink** [CGAL/cgal#8391]
## Issue Details
When calling intersection on  CGAL::Polygon_set_2<CGAL::Exact_predicates_inexact_constructions_kernel >
having double coordinates, with the input coordinates being integer in the range 10000 ... 290000 (x) and 300000 ... 625000, (y), I get 

CGAL ERROR: precondition violation!Expr: (m_traits.compare_y_at_x_2_object()(p, cv) == EQUAL) && compare_xy(cv.left(), p) == SMALLER && compare_xy(cv.right(), p) == LARGER
File: C:\dev\GeoDMS\vcpkg_installed\x64-windows\x64-windows\include\CGAL\Arr_segment_traits_2.h

See code from CGAL 5.6.1

![image](https://github.com/user-attachments/assets/f51da508-e593-4ff1-901c-86f7a376fa97)

And the following values for `p` and `cv.m_ps` and `cv.m_pt`, according to visual studio, indicate near collinearity with a deviation of 1 unit on approximately 2^50 units, which should be acceptable, given the inexact nature of floating point division, and the fact that a line-segment (aka curve) may have been displaced slightly due to earlier processed segment-splittings (which seems not to be the case here according to the integer values of m_ps and m_pt).

![image](https://github.com/user-attachments/assets/b0aaa7c0-e647-4381-9d44-98b2046445d4)

![image](https://github.com/user-attachments/assets/73f6591f-f4da-4599-9d5e-727f84c5857b)

I saw with blame that the precondition used to be (in Arr_segment_triats_2.h)

![image](https://github.com/user-attachments/assets/d81098f3-50b8-43ee-a424-a648ff8e1243)
until 24-10-2014 and taking into account if divisibility is exact sounds more reasonable here.

## Environment

* Windows 11
* MSVC 17.10.x
* Debug
* Specific flags used (if any):
* CGAL version: 5.9.1
* Boost version: 1.84.0

**Comment by MaartenHilferink** [comment]
Only use CGAL::Polygon_set_2<CGAL::Exact_predicates_exact_constructions_kernel >

**Comment by sloriot** [comment]
You cannot use this package with a kernel with double coordinates.

Please have a look at this FAQ entry:
https://www.cgal.org/FAQ.html#inexact_NT
