### ISSUE TITLE
cgal.geometryfactory.com git repos

### ISSUE THREAD

**Issue by MaelRL** [CGAL/cgal#8394]
## Issue Details

Using git repos gives the following error: `fatal: '/xxx/yyy' does not appear to be a git repository`

Updating the remote to the new name doesn't fix it.

**Comment by lrineau** [comment]
fixed

**Comment by lrineau** [comment]
> fixed

Well... not sure. @MaelRL What is the URL of the remote you use?

**Comment by lrineau** [comment]
Should be fixed, now. On the `cgal` machine, the file `/etc/gitconfig` (system git config) now has:

```shell
[safe]
        directory = /repo/Data
```
