### ISSUE TITLE
Meshing thread in the demo

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#842]
The mesh generation happens in its own thread in the demo, but the progess popup window is modal and blocks the API.

It would be better if one could continue doing something in the GUI.
Also instead of a popup window it should be a widget docked like the console.

The meshing parameters too, should not be in a pop-up window, but in a tool window just as we do it for selection, deformation,....

This applies not only to the mesh generator.

**Comment by maxGimeno** [comment]
The modal pop-up is wanted. It keeps the user from manipulating the items being created, which could make the demo crash.
