### ISSUE TITLE
trying to remove all edges around a vertex but got infinite loop

### ISSUE THREAD

**Issue by citystrawman** [CGAL/cgal#8428]
_Please use the following template to help us solving your issue._

## Issue Details

I am trying to remove all edges around a vertex, but got infinite loop

## Source Code

```
\\ find vertex v to be deleted...

for (halfedge_descriptor h : CGAL::halfedges_around_source(v, mesh)) {
    mesh.remove_edge(edge(h, mesh));
}

```

I added a break point in this for loop and found that halfedge h keeps jumping between two halfedges(in my example, halfedge 16644 and 16647), and I can't imagine what is going on here. 

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):
* Compiler:
* Release or debug mode:
* Specific flags used (if any):
* CGAL version:
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by sloriot** [comment]
collect edges first in a container and remove them iterating on the container

**Comment by afabri** [comment]
> collect edges first in a container and remove them iterating on the container

But even that is probably not enough to have a valid mesh.    @citystrawman you  should read the source code of the Euler operations to get an understanding for what has to be done as soon as you use the low level API.

**Comment by citystrawman** [comment]
> collect edges first in a container and remove them iterating on the container

Thank you @sloriot , so if I want to delete vertices as well as its connecting edges and faces, then should I first collect vertices, edges and faces in 3 containers, and then remove them? does the sequence (the sequence in each container as well as the sequence of deleting vertices, edges and faces)matters?
