### ISSUE TITLE
CGAL::Euler::join_vertex( ) throws exception

### ISSUE THREAD

**Issue by citystrawman** [CGAL/cgal#8446]
_Please use the following template to help us solving your issue._

## Issue Details

I am using `CGAL::Euler::join_vertex() `to remove halfedges in a mesh. Here's the screenshot that caused this issue:
![image](https://github.com/user-attachments/assets/4ddcf6d0-d11d-491d-bb52-3d95ab9a9eb9)

Before running into this issue, **I have already successfully joined 63 small edge segments in the Mesh**, so I think my way of joining small edges is applicable. 
Here I want to remove the yellow halfedges that includes h1 and h2 (their direction are from left to right)
when I use 
```
//here vec includes h1 and h2
for (size_t i = 0; i < vec.size(); i++) {
    auto h = vec[i];
    CGAL::Euler::join_vertex(h, mesh);
}
```
in the first loop, `join_vertex() `executes without error, which means that h1 is joined successfully; then in the second loop, `join_vertex() ` throws error as follows:
![image](https://github.com/user-attachments/assets/65e27e99-25db-4fe7-9575-983d6e2869fa)
the error is located at:
![image](https://github.com/user-attachments/assets/98a799ba-2b7d-4228-9a60-e1133ed4d4ca)

and here's the screenshot after the loop successfully joined h1:
![image](https://github.com/user-attachments/assets/06135410-07ca-4c3f-bc12-676103d42077)

May I know what is the problem here? I appreciate if anyone could handle this problem. Thank you so much! 

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):
* Compiler:
* Release or debug mode:
* Specific flags used (if any):
* CGAL version:
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by sloriot** [comment]
If you look at the doc you see that there is a precondition: `The size of the faces incident to h and opposite(h,g) is at least 4.` One of the incident face is a triangle so it does not respect the requirement of the method.

**Comment by citystrawman** [comment]
> If you look at the doc you see that there is a precondition: `The size of the faces incident to h and opposite(h,g) is at least 4.` One of the incident face is a triangle so it does not respect the requirement of the method.

From [the definition of halfedge](https://doc.cgal.org/latest/HalfedgeDS/index.html) , in my above example, h1 and its opposite has only 2 incident faces, but why h1 is joined successfully?

**Comment by sloriot** [comment]
size of a face = number of vertices

**Comment by citystrawman** [comment]
> size of a face = number of vertices

![image](https://github.com/user-attachments/assets/ea9c08ea-127d-431c-aa87-3eff4bb85263)
Do you mean by the vertices that I draw red circle on ?  isn't the number of vertices 4?

**Comment by sloriot** [comment]
if the halfedge is incident to a triangle you cannot call this method

**Comment by citystrawman** [comment]
> if the halfedge is incident to a triangle you cannot call this method

Sorry, but I am still not clear. For a triangle mesh,  isn't it always true that any halfedge(except border) is incident to a triangle?

**Comment by afabri** [comment]
Maybe you look for [`collapse_edge()`](https://cgal.geometryfactory.com/CGAL/doc/master/BGL/group__PkgBGLEulerOperations.html#ga0c5f86e550583b25e9daa477315ab919)

**Comment by citystrawman** [comment]
> Maybe you look for [`collapse_edge()`](https://cgal.geometryfactory.com/CGAL/doc/master/BGL/group__PkgBGLEulerOperations.html#ga0c5f86e550583b25e9daa477315ab919)

Hi @afabri , I used collapse_edge() and the program crashes at the same point. 
To debug this, I wrote a code to detect halfedge h, its opposite hop and hprev, gprev, hnext and gnext, as well as v_t0_remove and v:
```
for (size_t i = 0; i < vec.size(); i++) {
    auto h = vec[i];
    if (j == 64 && i == 1) {
        halfedge_descriptor hop = opposite(h, mesh2_clip)
            , hprev = prev(hop, mesh2_clip)
            , gprev = prev(h, mesh2_clip)
            , hnext = next(hop, mesh2_clip)
            , gnext = next(h, mesh2_clip);
        vertex_descriptor v_to_remove = target(hop, mesh2_clip)
            , v = target(h, mesh2_clip);
        put(ecm2, edge(h, mesh2_clip), CGAL::IO::blue());
        put(vcm2, v_to_remove, CGAL::IO::green());
        put(vcm2, v, CGAL::IO::red());
        CGAL::draw(mesh2_clip);
    }
    CGAL::Euler::join_vertex(h, mesh2_clip);    //method2: use CGAL::Euler::collapse_edge(edge(h, mesh2_clip), mesh2_clip);
}
```
I compared two methods which uses `join_vertex `and `collapse_edge` respectively, and here's the difference:

Using `join_vertex `:
h: 148863; 
hop:148862; 
hprev:**148874**; 
gprev: 148861; 
hnext: **148874**; 
gnext: 148859
![image](https://github.com/user-attachments/assets/74b88edc-e5c9-462f-a773-26c08d8edccb)
here hprev and hnext has same idx_

using  `collapse_edge`:
h: 148863; 
hop:148862; 
hprev:**148874**; 
gprev: 148861; 
hnext: **148872**; 
gnext: 148859
![image](https://github.com/user-attachments/assets/974dbd38-c7c0-425a-8013-a3b3d9be328a)
here hprev and hnext  are different, but h (which should be blue in mesh wireframe) is not found in mesh.

I am thinking what is the problem here......

**Comment by afabri** [comment]
Did you solve the problem?

**Comment by citystrawman** [comment]
> Did you solve the problem?

Yes.
