### ISSUE TITLE
mesh.point(vertex) returns different points for same vertex

### ISSUE THREAD

**Issue by citystrawman** [CGAL/cgal#8466]
_Please use the following template to help us solving your issue._

## Issue Details

I am debugging my code and I found that `mesh.point(vertex)` returns different points for same vertex.
I printed out the infomation in my code as follows. 
When code runs at the first part,  the halfedge **`h151067`** has its source vertex's coordinate as follows:

![image](https://github.com/user-attachments/assets/0902104b-cf2c-4e81-8a86-816015d1aa8e)

Then, when the code runs at second part, the halfedge **`h151067`**  has its source vertex's coordinate got changed: 
![image](https://github.com/user-attachments/assets/1b9d31a4-5ec8-415b-8b86-85731aae5595)

between the two parts, what I have done only is to collapse the halfedge that is **previous to** h , in the documentation it is said that when collapse an edge, the edge's source will be removed and the target will be retained, so that means h's source vertex should not be changed.

I am not sure why this wired situation happens.

## Source Code

_If your issue arises by using CGAL in your own source code, please provide a minimalist example that we can compile easily to reproduce the bug. If your issue arises from using a CGAL program (demo, example, etc.), please let us know which one. Helping you solving an issue is much easier and efficient if we can reproduce it._

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):
* Compiler:
* Release or debug mode:
* Specific flags used (if any):
* CGAL version:
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by afabri** [comment]
Can you please provide the lines of code before and after the collapse.

**Comment by citystrawman** [comment]
> Can you please provide the lines of code before and after the collapse.

I have already solved this problem. Thank you!
