### ISSUE TITLE
How to properly use merge_duplicated_vertices_in_boundary_cycles() ? 

### ISSUE THREAD

**Issue by citystrawman** [CGAL/cgal#8469]
_Please use the following template to help us solving your issue._

## Issue Details

Here I have a surface mesh that has two bondry cycles whose vertices are in same position:
![image](https://github.com/user-attachments/assets/72749279-aa6c-46f8-a8ac-4ee1fe1337a5)

what I want to do is "seam" the two boundries into one: that is , remove each duplicated vertex.

I found in CGAL a method called `merge_duplicated_vertices_in_boundary_cycles()` but there's no example code. I tried it on the surface mesh but there's nothing changed. 

`CGAL::Polygon_mesh_processing::merge_duplicated_vertices_in_boundary_cycles(mesh);`

May I know if I use this method correctly? if not, how can I remove the duplicated vertices?  
Thank you.

**Comment by sloriot** [comment]
Please provide the input mesh and the calling code.

**Comment by afabri** [comment]
If I understand it correctly you should use [`stitch_borders()`](https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__combinatorial__repair__grp.html#ga740c417af0ef24a16faebb23727d089c)

**Comment by afabri** [comment]
And please read the documentation more carefully before posting issues. The function you call is explicit that it deals with the vertices in a single boundary cycle.
