### ISSUE TITLE
return value of PMP::remove_almost_degenerate_faces()

### ISSUE THREAD

**Issue by raphaelsulzer** [CGAL/cgal#8476]
## Issue Details

I would like to know if `PMP::remove_almost_degenerate_faces(mymesh)` modifies mymesh or not. The documentation states that the function returns 

> true if no almost degenerate face could not be removed (due to topological constraints), and false otherwise.

Thus, the function returns true if all caps and needles can be removed. However, the function also returns true if the thresholds I pass to the function are such that no caps and needles are removed.
If only edges of cap triangles are flipped, I can also not simply track mymesh.num_faces() to know if the mesh was changed. 

I tried to use the optional filter parameter like this

```
struct ModificationTracker{

    bool was_modified = false;

    template <typename Point_3>
    bool operator()(const Point_3& p1, const Point_3& p2, const Point_3& p3) const {

        was_modified = true;

        return true;

    }
};

ModificationTracker tracker;

PMP::remove_almost_degenerate_faces(mymesh.faces(),mymesh, 
PMP::parameters::collapse_length_threshold(max_edge_length)
// PMP::parameters::needle_threshold(needle_angle_threshold)
.cap_threshold(cap_angle_threshold)
.filter(tracker)
);  

BOOST_LOG_TRIVIAL(debug) << "modified? " << tracker.was_modified;
```
but since a const function object is expected for the filter parameter this will not compile.

Effectively, the only solution I see is to iterate over the mesh faces beforehand and check if there are any caps or needles. This seems wasteful.

## Environment

* CGAL version: 5.6.1

**Comment by MaelRL** [comment]
Make the Boolean `mutable` and you can modify it in the const function.

Named parameters make copies of whatever you give them, so you need to give a reference of your tracker, otherwise the modification will only happen to a copy and not to your original object. So: `.filter(std::ref(tracker))`

**Comment by raphaelsulzer** [comment]
> you need to give a reference of your tracker, otherwise the modification will only happen to a copy and not to your original object. So: .filter(std::ref(tracker))

That was the part that I was missing. Now it is working. Thank you, Mael!

One more thing to note is that one still needs to keep track of the number of faces. In case only border edges are modified, the tracker is not called, because no new triangle is created. So in the end I still need to do something like below to get the final answer if the mesh is modified or not.

`bool was_modified = tracker.was_modified || (num_faces_before != _triangle_mesh.num_faces());`
