### ISSUE TITLE
The exe installer/uninstaller delete files and codes in install directory

### ISSUE THREAD

**Issue by shyzhxpyl** [CGAL/cgal#8482]
1. Download CGAL exe installer(version 5.1), my system is windows.
2. Choose a destination folder, here is the key mistake, I choose a folder with many other project instead of create a new destination folder.
3. I found this is wrong while after installing I do the uninstall.
4. Many of my project files within this folder are deleted, including .git file, .pcd files, cpp code files etc. 
5. This is terrible, how can I get my files back. Seems not in my system's recycle bin.

**Comment by lrineau** [comment]
Dear @shyzhxpyl, we are really sorry for what happened.

- That "CGAL installer" was created in 2003, for the [release of CGAL-3.0](https://www.cgal.org/2003/11/01/cgal-30/), using [NSIS](https://nsis.sourceforge.io/Main_Page). That software was shinny at the time (20 years ago), but its source code was difficult to maintain, and a real burden.
- Five years ago, in 2019. CGAL-5.0 was published as a header-only library, and the need for the installer was close to zero.
- That is why in 2021, we decided to remove the Windows installer, with the pull-request https://github.com/CGAL/cgal/pull/5451.

CGAL-5.1.2 ande CGAL-5.2.0 were the last versions of CGAL with the Windows installer executable. We are really sorry for what happened on your system. As far as the CGAL project is concerned, that issue has already been solved 3 years ago.

I sincerely hope you will manage to recover the missing files and directories on your system, but there is nothing we can do now in the CGAL project.
