### ISSUE TITLE
CGAL Performance too slow (Skeletonize as example)

### ISSUE THREAD

**Issue by satabol** [CGAL/cgal#8506]
CGAL 6.0 (master, 2024.09.27), Windows 11, example **cgal\Straight_skeleton_2\examples\Straight_skeleton_2**

![image](https://github.com/user-attachments/assets/d4de0fe3-2f30-4ae1-8454-1e9f14dd072b)

cgal docs: https://doc.cgal.org/latest/Straight_skeleton_2/index.html

Mesh and result:
![image](https://github.com/user-attachments/assets/798b0f1b-3bfa-4e3d-8764-c06fe815ee9f)

Visual Studio Profiler:
![image](https://github.com/user-attachments/assets/562f135e-0a6b-4ad9-8810-94a01d22bb19)

in console it takes 23sec.
![image](https://github.com/user-attachments/assets/40af2c52-54e6-49dc-81a7-0d725fa7f2ba)
![image](https://github.com/user-attachments/assets/6f004b17-9b8b-40df-908d-7ae63c24fdb4)
result is good but it is too slow (((

Source data:
[SrcCoordsAndAngles.zip](https://github.com/user-attachments/files/17180192/SrcCoordsAndAngles.zip)
```
extrude_skeleton.exe -i plane_skeleton_out.dat -a plane_skeleton_out.dat.angles
```
Question: Is a way to exceed performance to 100% on one core of CPU ? Or may be is a way to use multithreading?

**Comment by satabol** [comment]
I think I find out what the problem!

I build example by recipe in doc https://doc.cgal.org/latest/Manual/installation.html#ssec_installation_build_ex_demos:
![image](https://github.com/user-attachments/assets/9c2b621e-990f-4738-a54d-3706993dcabb)

In another packages I used in my cases this is has no influence to performance. But now in Visual Studio Profiler was shown:

![image](https://github.com/user-attachments/assets/b5d33588-e2e2-4fd3-9084-2235bbbf0408)

And after that moment I try to rebuild with Release mode and got excellent results:
![image](https://github.com/user-attachments/assets/2522b750-57ff-4e2e-8a85-31f9f4ed4f2d)
x10 times! Super!!!


But... Is there any other way to speed up the performance?

**Comment by afabri** [comment]
Debug mode is for debugging purposes and not required to be fast.   What do you want to achieve?

**Comment by satabol** [comment]
I want to do a preview in realtime on user mesh in Blender addon (free). 3D graphics computer are powerfull usually. Is Skeleton function multithreaded or a single threaded? Or is a way to use CUDA?

**Comment by afabri** [comment]
My question was what prevents you from running it in Release mode.

**Comment by satabol** [comment]
I can run in release mode. No problem. )))

**Comment by afabri** [comment]
The algorithm is inherently sequential.  Let me close the issue.

**Comment by satabol** [comment]
Thank you.
