### ISSUE TITLE
CGAL6.0 Point_set_3 std::bad_optional_access

### ISSUE THREAD

**Issue by ipadjen** [CGAL/cgal#8517]
## Issue Details

Assignment operator and copy constructor of the Point_set_3 assume there is available normal map so std::optional throws std::bad_optional_access exception if add_normal_map() hasn't been called before.

https://github.com/CGAL/cgal/blob/4305f01384659ecc200db2c41f41aa48d43e92d2/Point_set_3/include/CGAL/Point_set_3.h#L248

and

https://github.com/CGAL/cgal/blob/4305f01384659ecc200db2c41f41aa48d43e92d2/Point_set_3/include/CGAL/Point_set_3.h#L260

## Source Code

```c++
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/Point_set_3.h>

typedef CGAL::Exact_predicates_inexact_constructions_kernel Kernel;
typedef Kernel::Point_3 Point;
typedef CGAL::Point_set_3<Point> Point_set;

int main (int, char**)
{
  Point_set point_set;

  // Add points
  point_set.insert (Point (0., 0., 0.));
  point_set.insert (Point (0., 0., 1.));
  point_set.insert (Point (0., 1., 0.));

  Point_set point_set_2 = point_set;

 return 0;
}
```

Compared to

```c++
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/Point_set_3.h>

typedef CGAL::Exact_predicates_inexact_constructions_kernel Kernel;
typedef Kernel::Point_3 Point;
typedef CGAL::Point_set_3<Point> Point_set;

int main (int, char**)
{
  Point_set point_set;

  // Add points
  point_set.insert (Point (0., 0., 0.));
  point_set.insert (Point (0., 0., 1.));
  point_set.insert (Point (0., 1., 0.));

  point_set.add_normal_map();
  Point_set point_set_2 = point_set;

 return 0;
}
```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): macOS
* Compiler: AppleClang 15
* Release or debug mode: N/A
* Specific flags used (if any): N/A
* CGAL version: 6.0
* Boost version: 1.86.0
* Other libraries versions if used (Eigen, TBB, etc.): N/A

**Comment by sloriot** [comment]
Hi! thanks for the report. Should be fixed by https://github.com/CGAL/cgal/issues/8517
