### ISSUE TITLE
Skeleton endless calculation on simple mesh.

### ISSUE THREAD

**Issue by satabol** [CGAL/cgal#8524]
Hi.
Skeleton is great! I'm stuck on next simple mesh that I got from SVG. I convert it to mesh:

![image](https://github.com/user-attachments/assets/0762ebdc-4f57-4c76-b1fc-167f8c728d08)

and apply example of skeleton and got next issue:
![image](https://github.com/user-attachments/assets/069ad482-a1dd-4dda-8890-d57b74f0f18b)
Skeleton occupied all memory and not finish. I break it.
I think the problem is in mesh:
![image](https://github.com/user-attachments/assets/92a48065-6624-496a-b645-31a8596f839e)

Do you have test touching of neighbors edges ? If no can you add this condition ? (If this is a core of problem)

Files for tests (points and angles):
[issue.CGAL.data.to.tests.zip](https://github.com/user-attachments/files/17280134/issue.CGAL.data.to.tests.zip)
```
extrude_skeleton.exe -i issue.CGAL.001.dat -a issue.CGAL.001.dat.angles
```

**Comment by MaelRL** [comment]
As the warning message says, it should work with a strictly simple polygon.

Are you running extrude_polygon.cpp without any change (i.e., with kernel being `Exact_predicates_inexact_constructions_kernel`)?

**Comment by satabol** [comment]
>Are you running extrude_polygon.cpp without any change
I add some printf messages only.

Wow!!! Great!!! I do not understood it! I think to convert this warning into try/catch block! Is it good enough?

**Comment by satabol** [comment]
Now all work as expected! that leaf marked as error:

![image](https://github.com/user-attachments/assets/b3619eb9-1750-4d7a-ad0c-6b5a8505595b)

One can close this issue?
