### ISSUE TITLE
Do not use internal namespace in examples

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#8534]
* `Alpha_wrap_3/examples/Alpha_wrap_3/successive_wraps.cpp`
  * `101:  using Oracle = CGAL::Alpha_wraps_3::internal::Triangle_mesh_oracle<K>;`
  * `102:  using Wrapper = CGAL::Alpha_wraps_3::internal::Alpha_wrapper_3<Oracle>;`

* `Alpha_wrap_3/examples/Alpha_wrap_3/volumetric_wrap.cpp`
  * `29:namespace AW3i = CGAL::Alpha_wraps_3::internal;`
  * `101:  using Oracle = CGAL::Alpha_wraps_3::internal::Triangle_soup_oracle<K>;`
  * `106:  CGAL::Alpha_wraps_3::internal::Alpha_wrapper_3<Oracle, Delaunay_triangulation> aw3(oracle);`

* `Alpha_wrap_3/examples/Alpha_wrap_3/pause_and_resume_wrapping.cpp`
  * `42:  : public AW3::internal::Wrapping_default_visitor`
  * `44:  using Base = AW3::internal::Wrapping_default_visitor;`
  * `112:  using Oracle = CGAL::Alpha_wraps_3::internal::Triangle_soup_oracle<K>;`
  * `115:  CGAL::Alpha_wraps_3::internal::Alpha_wrapper_3<Oracle> aw3(oracle);`

* `Alpha_wrap_3/examples/Alpha_wrap_3/mixed_inputs_wrap.cpp`
  * `94:  using TS_Oracle = CGAL::Alpha_wraps_3::internal::Triangle_soup_oracle<K>;`
  * `95:  using SS_Oracle = CGAL::Alpha_wraps_3::internal::Segment_soup_oracle<K, TS_Oracle>;`
  * `96:  using Oracle = CGAL::Alpha_wraps_3::internal::Point_set_oracle<K, SS_Oracle>;`
  * `106:  CGAL::Alpha_wraps_3::internal::Alpha_wrapper_3<Oracle> aw3(oracle);`

* `Periodic_3_mesh_3/examples/Periodic_3_mesh_3/mesh_periodic_polyhedral_domain.cpp`
  * `58:    const Point_3 cp = P3T3::internal::robust_canonicalize_point(p, m_gt);`

* `Shape_detection/examples/Shape_detection/region_growing_with_custom_classes.cpp`
  * `72:    using Region_unordered_map = std::unordered_map<Item, std::size_t, CGAL::Shape_detection::internal::hash_item<Item> >;`

* `Straight_skeleton_2/examples/Straight_skeleton_2/include/CGAL/input_helpers.h`
  * `39:  if(CGAL::IO::internal::get_file_extension(filename) == "poly")`
  * `112:  std::string ext = CGAL::IO::internal::get_file_extension(filename);`

**Comment by afabri** [comment]
The alpha wrap examples are "inofficial".  I know that this status does not exist, but they are not linked to in the  User Manual, because not in `examples.txt.

**Comment by afabri** [comment]
@soesau can you propose something for Shape Detection.

**Comment by afabri** [comment]
Concerning  `CGAL::IO::internal::get_file_extension` we might use  [ `std::filesystem::path::extension()`](https://en.cppreference.com/w/cpp/filesystem/path/extension), but I am not sure if  `std:>:filesystem`   is well supported on all platfoms we use.

**Comment by sloriot** [comment]
> Concerning `CGAL::IO::internal::get_file_extension` we might use [ `std::filesystem::path::extension()`](https://en.cppreference.com/w/cpp/filesystem/path/extension), but I am not sure if `std::filesystem` is well supported on all platfoms we use.

it is! There is also one example in the Isosurfacing branch using it (if you do the update in master). Thanks!

**Comment by MaelRL** [comment]
`mesh_periodic_polyhedral_domain.cpp` is also an undocumented example from me.

I am not really in favor of moving these undocumented examples into `/tests` because:
- it's not a test.
- `/tests` is usually denser, not as clean, and not looked as often. Thus, the example loses visibility for both users and for devs.

But I don't really have a nice solution, I think `/undocumented_examples` or `/wip` or whatever would be pollution. The examples could have a `[...]_undocumented.cpp` + disclaimer at the top?

For `CGAL::IO::internal::get_file_extension`, it needs to be updated to filesystem.

**Comment by afabri** [comment]
Concerning `std::filesystem` please have a look at this [file](https://github.com/CGAL/cgal/blob/3deebceb97bc7c1026622113315b0a311a1e4bb5/Polygon_repair/test/Polygon_repair/draw_test_polygons.cpp#L5)

Either this is outdated, or it is still true.
