### ISSUE TITLE
Transition between CGAL 5.6.1 and 6.1 CMake

### ISSUE THREAD

**Issue by petrasvestartas** [CGAL/cgal#8568]
_Please use the following template to help us solving your issue._

## Issue Details

My old cmake does not work anymore.
My short question:  what should include in CMake and main C++ header to completely get rid of gmp/mpfr ?

## Source Code

https://github.com/petrasvestartas/wood/blob/main/install_ubuntu.sh
## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Ubuntu
* Compiler: GCC13
* Release or debug mode: Release
* Specific flags used (if any): 
* CGAL version: 6.1
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

CMake Output:

How do you get rid of GMP, for boolean mesh methods this is still causing problems:
`
/usr/bin/ld: cgal_mesh_boolean.cpp:(.text._ZNK4CGAL21Side_of_triangle_meshINS_12Surface_meshINS_7Point_3INS_5EpickEEEEENS_5EpeckENS_23Polygon_mesh_processing12Corefinement34Node_vector_exact_vertex_point_mapISt13unordered_mapINS_15SM_Vertex_indexEmSt4hashISB_ESt8equal_toISB_ESaISt4pairIKSB_mEEENS5_12Property_mapISB_S4_EENS8_18Intersection_nodesIS5_SM_SM_Lb1ELb0EEEEENS_9AABB_treeINS_13AABB_traits_3IS6_NS_34AABB_face_graph_triangle_primitiveIS5_SP_St17integral_constantIbLb1EEST_IbLb0EEEENS_7DefaultEEEEEEclERKNS2_IS6_EE[_ZNK4CGAL21Side_of_triangle_meshINS_12Surface_meshINS_7Point_3INS_5EpickEEEEENS_5EpeckENS_23Polygon_mesh_processing12Corefinement34Node_vector_exact_vertex_point_mapISt13unordered_mapINS_15SM_Vertex_indexEmSt4hashISB_ESt8equal_toISB_ESaISt4pairIKSB_mEEENS5_12Property_mapISB_S4_EENS8_18Intersection_nodesIS5_SM_SM_Lb1ELb0EEEEENS_9AABB_treeINS_13AABB_traits_3IS6_NS_34AABB_face_graph_triangle_primitiveIS5_SP_St17integral_constantIbLb1EEST_IbLb0EEEENS_7DefaultEEEEEEclERKNS2_IS6_EE]+0x1414): undefined reference to `__gmpq_clear'`

**Comment by lrineau** [comment]
@petrasvestartas You have found a solution?
