### ISSUE TITLE
`CGAL::CGAL_Basic_viewer` enforces the definition of the preprocessor macro  `QT_NO_KEYWORDS`

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#8574]
That is because `CGAL::CGAL_Basic_viewer` enforces the definition of the preprocessor macro  [`QT_NO_KEYWORDS`](https://doc.qt.io/qt-6/qtglobal.html#QT_NO_KEYWORDS).

That means you need to replace:
  - `slots` by `Q_SLOTS`
  - `signals` by `QSIGNALS`,
  - `emit` by `Q_EMIT`, and
  - `foreach` by `Q_FOREACH`.

... I wonder if that should be considered as a bug for CGAL. We should not enforce our choices to CGAL users.

_Originally posted by @lrineau in https://github.com/CGAL/cgal/discussions/8572#discussioncomment-11050792_

**Comment by lrineau** [comment]
I think we define `QT_NO_KEYWORDS` for two reasons:
  - [x long ago, we used the name `forearch`, with Boost foreach, and there was a conflict, if I remember well, but that it something of the past,
  - [ ] the macro `emit` conflicts with TBB: see https://github.com/oneapi-src/oneTBB/issues/547

**Comment by gdamiand** [comment]
The conflict with TBB is blocking for us.

**Comment by lrineau** [comment]
> The conflict with TBB is blocking for us.

I agree in CGAL Qt application, we need to define `QT_NO_KEYWORDS`. But maybe not force users of `CGAL::CGAL_Basic_viewer` to modify their source code because we enforce `QT_NO_KEYWORDS`.
