### ISSUE TITLE
Clip problem

### ISSUE THREAD

**Issue by AlexGrig55** [CGAL/cgal#8590]
CGAL 6.0.1, Windows 10

I am trying to clip the closed mesh with another closed mesh and I get an incorrect result. 
With CGAL::parameters::default_values().clip_volume(false) the result is correct.

clipper:
![Image](https://github.com/user-attachments/assets/30961ae1-8b14-4a7b-a6d5-d492690135de)

target:
![Image](https://github.com/user-attachments/assets/6944ce43-cf7b-471e-a0f1-9e123eed9909)

result:
![Image](https://github.com/user-attachments/assets/6be2fe72-1fb0-4aa7-ba8c-59eba202ab2d)

correct result:
![Image](https://github.com/user-attachments/assets/54b68f86-559a-44a6-bef3-d73d4eef46bc)

clipper file:
[clipper.off.txt](https://github.com/user-attachments/files/17644174/clipper.off.txt)

target file:
[target.off.txt](https://github.com/user-attachments/files/17644180/target.off.txt)

code:
```
#include <CGAL/Polygon_mesh_processing/clip.h>
#include <CGAL/boost/graph/copy_face_graph.h>
#include <CGAL/Polygon_mesh_processing/merge_border_vertices.h>
#include <CGAL/Polygon_mesh_processing/stitch_borders.h>
#include <CGAL/Simple_cartesian.h>
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/Surface_mesh.h>
#include <CGAL/Polygon_mesh_processing/corefinement.h>
#include <CGAL/Polygon_mesh_processing/IO/polygon_mesh_io.h>

namespace PMP = CGAL::Polygon_mesh_processing;
typedef CGAL::Exact_predicates_inexact_constructions_kernel K;
typedef K::Point_3 Point_3;
typedef CGAL::Surface_mesh<Point_3> Mesh;

void CheckMeshValidation(const Mesh& mesh)
{
	if (CGAL::Polygon_mesh_processing::does_self_intersect(mesh))
		throw std::exception();
	if(!CGAL::Polygon_mesh_processing::does_bound_a_volume(mesh))
		throw std::exception();
}

void ClipTest()
{
	std::string targetPath = CGAL::data_file_path("target.off");
	std::string clipperPath = CGAL::data_file_path("clipper.off");

	Mesh target;
	Mesh clipper;

	PMP::IO::read_polygon_mesh(targetPath, target);
	PMP::IO::read_polygon_mesh(clipperPath, clipper);

	CheckMeshValidation(target);
	CheckMeshValidation(clipper);

	PMP::clip(target, clipper, CGAL::parameters::default_values().clip_volume(true));

	std::ofstream out("result.off");
	out.precision(17);
	out << target << std::endl;
}
```

**Comment by sloriot** [comment]
target.off is oriented inside-out. It means that it represent the whole space minus the shape. So when calling with `close_volume=true`, you intersect the whole space minus the shape with the cube. So you end-up with the cube minus the shape. If not closing the volume, you get only the faces inside the cube. If you can [`PMP::reverse_face_orientations(target)`](https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__orientation__grp.html#gad8a3439883e3e76651f96d15ba58b2bc) you should get what you expect.
