### ISSUE TITLE
Failure in using CGAL::poisson_surface_reconstruction_delaunay() on macOS

### ISSUE THREAD

**Issue by Canjia-Huang** [CGAL/cgal#8615]
The error message "Undefined symbols for architecture arm64" occurred when compiling the example code from the documentation at [Poisson_surface_reconstruction_3/poisson_reconstruction_function.cpp](https://doc.cgal.org/latest/Poisson_surface_reconstruction_3/Poisson_surface_reconstruction_3_2poisson_reconstruction_function_8cpp-example.html) on macOS.

According to my investigation, the issue I encountered is caused by the use of the `CGAL::poisson_surface_reconstruction_delaunay()` function.

I have already installed the CGAL library (version 6.0.1) and the GMP and MPFR libraries using Homebrew on macOS system, and I can successfully run other CGAL functions.

The partial error message  is as follows:

Undefined symbols for architecture arm64:
  "___gmpn_add_n", referenced from:
      CGAL::Mpzf::aors(CGAL::Mpzf const&, CGAL::Mpzf const&, int) in test_main.cpp.o
      CGAL::Mpzf::aors(CGAL::Mpzf const&, CGAL::Mpzf const&, int) in test_main.cpp.o
  "___gmpn_copyi", referenced from:
      CGAL::Mpzf::aors(CGAL::Mpzf const&, CGAL::Mpzf const&, int) in test_main.cpp.o
      CGAL::Mpzf::aors(CGAL::Mpzf const&, CGAL::Mpzf const&, int) in test_main.cpp.o
      CGAL::Mpzf::aors(CGAL::Mpzf const&, CGAL::Mpzf const&, int) in test_main.cpp.o
      CGAL::Mpzf::aors(CGAL::Mpzf const&, CGAL::Mpzf const&, int) in test_main.cpp.o
      CGAL::Mpzf::aors(CGAL::Mpzf const&, CGAL::Mpzf const&, int) in test_main.cpp.o
      CGAL::Mpzf::aors(CGAL::Mpzf const&, CGAL::Mpzf const&, int) in test_main.cpp.o
      CGAL::Mpzf::aors(CGAL::Mpzf const&, CGAL::Mpzf const&, int) in test_main.cpp.o
      CGAL::Mpzf::aors(CGAL::Mpzf const&, CGAL::Mpzf const&, int) in test_main.cpp.o
      CGAL::Mpzf::aors(CGAL::Mpzf const&, CGAL::Mpzf const&, int) in test_main.cpp.o
      ...

I hope you can provide me with some assistance.

Thanks.

**Comment by sloriot** [comment]
could it be that you are not linking with libgmp? Are you using cmake ?

**Comment by sloriot** [comment]
Note that if you are using CGAL, linking your targets with the target `CGAL::CGAL` should automatically pull gmp and mpfr.
