### ISSUE TITLE
Is the point data of 3D Point Set stored contiguously in memory?

### ISSUE THREAD

**Issue by DapengFeng** [CGAL/cgal#8630]
## Issue Details

I follow the tutorial about the 3D Point Set at https://doc.cgal.org/latest/Point_set_3/index.html#Chapter_Point_Set_3. And I want to convert the Point Set to a libtorch tensor , which manages the data in the contiguous memory. However, I can not find the pointer pointing to the stored memory of Point Set.

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):
* Compiler:
* Release or debug mode:
* Specific flags used (if any):
* CGAL version:
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by mglisse** [comment]
Whether it is contiguous depends on the type of points, it may even depend on the OS.
`Point_set_3` has a method `point_map`. The resulting `Point_map` seems to have an undocumented method `data` that may return what you want.

**Comment by DapengFeng** [comment]
Hi, @MaelRL @mglisse.

I require further clarification regarding this issue. For instance, I have logged the memory address of the point_map in the following manner:
```
 [2024-12-13 18:35:02.672] [debug] [pointcloud.hpp:105] Address: 0x5612aaafdd40  
[2024-12-13 18:35:02.672] [debug] [pointcloud.hpp:106] Address point_map()[0]: 0x5612aaafdd40 point_map()[0][0]: 0x5612ab466220
[2024-12-13 18:35:02.672] [debug] [pointcloud.hpp:107] Address point_map()[1]: 0x5612aaafdd48 point_map()[1][0]: 0x5612ac0639e0
[2024-12-13 18:35:02.672] [debug] [pointcloud.hpp:108] Address point_map()[2]: 0x5612aaafdd50 point_map()[2][0]: 0x5612aae41ae0
```

- [ ] Why `point_map()[x]` is not equal to `point_map()[x][0]`?
- [ ] Is there a way to make sure that point_map()[x] is equal to point_map()[x][0]?

**Comment by DapengFeng** [comment]
Additionally, I tested a simple piece of code on the Godbolt Compiler Explorer, which can be accessed at [this link](https://godbolt.org/z/W3nnEon9G).

```c++
struct Color {
    std::array<float, 4> rgba;

    float& operator[](int idx) {
        return rgba[idx];
    }
};

int main() {
    std::vector<Color> vec;
    vec.emplace_back(Color({1, 2, 3, 4}));
    vec.emplace_back(Color({2, 3, 4, 5}));

    std::cout << &vec.data()[0] << std::endl;
    std::cout << &vec.data()[0][0] << std::endl;
    std::cout << std::endl;
    std::cout << &vec.data()[1] << std::endl;
    std::cout << &vec.data()[1][0] << std::endl;

    return 0;
}
```

It outputs that the address of vec.data()[x] is equal to vec.data()[x][0].

**Comment by mglisse** [comment]
We can't help if you don't show a compilable example.

**Comment by mglisse** [comment]
That's not **compilable**, it is missing headers, functions, etc.
Don't use `Cartesian`, use `Simple_cartesian` (or better Epick).

**Comment by DapengFeng** [comment]
This issue might arise because `Point_3` in the `Cartesian` class does not store the actual data but only maintains a pointer to the data, as indicated by `sizeof(Point_3)` being equal to `8UL`.

**Comment by DapengFeng** [comment]
> Don't use `Cartesian`, use `Simple_cartesian` (or better Epick).

Thank you for your assistance. I have solved my problem by switching `Cartesian` to `Simple_cartesian.`
