### ISSUE TITLE
Action "Statistics" is shown in the menu even when no statistics can be computed!

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#864]
@maxGimeno @janetournois 

When I have a `Scene_c3t3_item` object, the context menu of it displays the action "Statistics", but the dialog that pops up is empty! The menu should not show such a useless action.

Related to #586.

**Comment by janetournois** [comment]
actually we should add some stats about the c3t3 in there...

**Comment by lrineau** [comment]
Why not. But by objection holds for *all* item types but the `Scene_polyhedron_item`.

**Comment by janetournois** [comment]
the "Statistics" menu should not be made available before statistics are actually available.
One option would be to have a popup saying "No statistics available for this type of item".
cc @maxGimeno

**Comment by lrineau** [comment]
Note that this bug has a low priority, compared to other ones I have filled recently: I have assigned it to CGAL-4.9, instead of CGAL-4.8 (that should be published next week).
