### ISSUE TITLE
Feature Request: Extract Periodic Element and Access Matching Faces in Periodic Triangulations

### ISSUE THREAD

**Issue by CristinaGL** [CGAL/cgal#8654]
Hello CGAL developers,

Thank you for the continuous development of CGAL!

I am working with periodic triangulations generated by CGAL in the context of particle packings.  I have encountered some limitations when attempting to isolate a single periodic element (see Figure 1)  from a particle packing such that the faces of the tetrahedrons at the periodic boundaries seamlessly connect (see Figure 2).

![Image](https://github.com/user-attachments/assets/abbf1e34-d96e-49ab-af3f-7752f057d8cd)
*Figure 1: Single periodic element.*
![Image](https://github.com/user-attachments/assets/4569efc9-a38e-41c7-84b0-02610f9bc497)
*Figure 2: The periodic boundaries seamlessly connect*

Feature Request

  -  **Isolate a periodic element**: I would like to isolate one periodic element from a particle packing, such that the faces of the tetrahedron match perfectly with the corresponding faces in the opposite direction. Currently, CGAL's periodic triangulation code lacks built-in functionality to directly extract this "periodic element." This feature would be very useful for extracting well-defined periodic domains from particle packings.

   - **Access matching faces across domains**: Additionally, it would be beneficial to extend the functionality of CGAL to include access to the "matching face" in the adjacent periodic domain.

Current Limitations

At the moment, the functionality to extract such an element or identify matching faces is not readily available. Implementing this feature would streamline workflows that require periodic boundary conditions and improve support for particle packing simulations, particularly those that require periodic constraints.

Suggested Approach

One possible approach could be to provide:

  -  A method to extract and isolate a periodic cell that respects the periodic boundary conditions.
  -  An API that allows querying the periodic domain and retrieving the matching face indices or connections between adjacent periodic cells.

I would appreciate any feedback on this request or suggestions for potential workarounds using the existing codebase. 

Thank you for your time and consideration!

Best regards,
Cristina García Llamas

**Comment by MaelRL** [comment]
I am not sure I understand your questions.

If you want to isolate a single instance of the periodic triangulation, you can use the `Unique_vertex/cell_iterator`s:
```cpp
    typedef typename Triangulation::Unique_vertex_iterator Unique_vertex_iterator;

    for (Unique_vertex_iterator ovit = T.unique_vertices_begin(); ovit != T.unique_vertices_end(); ++ovit)
    {
      Vertex_handle vh = ovit;
      std::cout << T.point(vh) << std::endl;

      Cell_handle c = vh->cell(); // cell incident to vh
    }

    typedef typename Triangulation::Unique_cell_iterator Unique_cell_iterator;

    for (Unique_cell_iterator ocit = T.unique_cells_begin(); ocit != T.unique_cells_end(); ++ocit)
    {
      Cell_handle ch = ocit;
      for (int i=0; i<4; ++i)
        std::cout << T.point(ch, i) << std::endl; // position of vertex ch->vertex(i)
      for (int i=0; i<4; ++i)
        std::cout << ch->neighbor(i) << std::endl; // cell neighbor of ch, opposite of i-th vertex
    }

  etc.
```

These triangulation *are* periodic, so you can by default walk from cell to neighboring cell infinitely in any direction using `cell->neighbor(int)`, and by construction the interfaces of each instance match other instances periodically.

Feel free to provide some pseudo code if that helps clarify your questions.

**Comment by CristinaGL** [comment]
Thank you so much for your prompt reaction! 

To help the discussion, I sketch an example of a 2D periodic unit that I would like to isolate:

![Image](https://github.com/user-attachments/assets/b5bd2363-9987-46ff-bead-0241a9cbc8cd)

As you can see, this periodic unit contains the original points (particles) and some of the copied points with offset (0,1), (1,0) and (1,1). Including these points is required to ensure that the edges (faces in 3D) mirror the ones on the opposite side of the domain. 

I could not find a direct way of extracting this periodic unit using the existing functionality of CGAL. Therefore, I am using the following strategy: 

- I define as target_offset: (0,0,0)
- I loop over the faces and I include in my output those faces with a "valid face offset"
- The function face_has_valid_offset returns true if:
I) the face contains any point with target_offset and a maximum offset: target_offset + 1
II) the face is connecting three periodic domains with target_offset + 1

```cpp
Rt::Offset target_offset(0, 0, 0);
// Loop over the faces and include it if face is within offset range
for (auto fit = T.finite_facets_begin(); fit != T.finite_facets_end(); ++fit) {
        vtkSmartPointer<vtkTriangle> triangle = vtkSmartPointer<vtkTriangle>::New();

        // Get the cell that contains this facet
        Rt::Cell_handle cell = fit->first;
        int face_index = fit->second;

        // Get the vertex offsets of the facet's vertices
        std::array<Point, 3> vertices;
        std::array<Rt::Offset, 3> offsets;
        bool is_face_offset_valid = face_has_valid_offset(*fit, target_offset, extended_box_size, T);
        if (!is_face_offset_valid) {
            continue;
        } else {
     // Include face in output
     }
}
```
Unfortunately, the logic I implemented in face_has_valid_offset is not general enough and some faces and points are missed. 

If I use, for example, Unique_vertex_iterator to iterate through the points, I am not including the particle copies required to obtained the mirrored edges (faces in 3D) between periodic domains.

**Comment by MaelRL** [comment]
If you use the unique cell iterator, these extra points will be present: each cell is 4 vertex handle (i.e., ids) + their local offsets *in the cell*. See https://doc.cgal.org/latest/Periodic_3_triangulation_3/index.html#fig__P3Triangulation3figoffsets.

A call to `T.point(cell_handle, int)` is not simply returning the position of the vertex handle; rather, the function takes into account the local offset of the vertex into the cell, and shifts the vertex if required as to create the expected cell (which possibly crosses over the boundary of the periodic domain).

**Comment by CristinaGL** [comment]
Alright! thank you so much for your answer! I will then try with the unique cell iterator
