### ISSUE TITLE
Mesh_3 in CGAL-4.8 cannot deal with a triangulation of dimension()==2.

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#866]
The modification was introduced in #534.

If the mesh domain has no volume, and is an exact coplanar surface, then the triangulation will be of `dimension()==2`. And all the duals of facets will be of type `Line_3`, a case that is no longer handled by the new code (see https://github.com/CGAL/cgal/pull/534#commitcomment-16442137).

In my opinion that is not really a regression, because such a mesh domain for Mesh_3 is meaningless, at least until we officially support the remeshing of surfaces using Mesh_3 (see PR #303 that triggers CGAL-4.9).

But that could be an issue that we have to keep in mind, when we give experimental pieces of code to users. We have already provided the solution of the PR #303 to a few of them. If they try to remesh a coplanar surface using CGAL-4.8, that will crash!

@afabri @janetournois

**Comment by sgiraudot** [comment]
Is this issue still present in more recent versions of `Mesh_3`?

**Comment by lrineau** [comment]
Unfortunately yes. Maxime found that out yesterday while trying to mesh a simple triangulated square.

**Comment by lrineau** [comment]
@afabri: it is actually you who introduced the bug, in #534: you skipped on purpose the case where the dual of a facet is a `Line_3`.

**Comment by lrineau** [comment]
A few years later, I can say that I was completely wrong. When the `dimension()` of the triangulation is 2, then the duals of facets are not lines, but points. The whole code of Mesh_3 is incapable to deal with `tr.triangulation()==2`.

The PR #4157 fixes that issue by enabling the use of "far points" on a sphere when `dimension()==2`, even if TBB is not used.
