### ISSUE TITLE
PMP::isotropic_remeshing(). Result mesh does not match the original.

### ISSUE THREAD

**Issue by yDF8EPJN8** [CGAL/cgal#8663]
## Issue Details

In the final mesh, edges appear whose endpoints are on the original mesh but whose midpoints are outside/inside the mesh.

Left: original mesh; right: result mesh.
![Image](https://github.com/user-attachments/assets/596c0287-e548-48ca-9ae3-d22f1f35b3fe)

I hope this behaviour of the algorithm was not intended.

## Source Code

```c++
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/Surface_mesh.h>
#include <CGAL/Polygon_mesh_processing/detect_features.h>
#include <CGAL/Polygon_mesh_processing/remesh.h>
#include <CGAL/Polygon_mesh_processing/IO/polygon_mesh_io.h>

#include <CGAL/draw_surface_mesh.h>
#include <CGAL/Qt/Basic_viewer.h>
#include <QMainWindow>
#include <QHBoxLayout>

typedef CGAL::Exact_predicates_inexact_constructions_kernel   K;
typedef CGAL::Surface_mesh<K::Point_3>                        Mesh;

typedef boost::graph_traits<Mesh>::face_descriptor            face_descriptor;

namespace PMP = CGAL::Polygon_mesh_processing;

void draw_2_scenes(CGAL::Graphics_scene& scene1, CGAL::Graphics_scene& scene2)
{
  int argc = 1;
  const char* argv[2] = { "Draw several windows example","\0" };
  QApplication app(argc, const_cast<char**>(argv));

  QMainWindow* mainWindow = new QMainWindow;
  QWidget* centralWidget = new QWidget(mainWindow);
  QHBoxLayout* layout = new QHBoxLayout(mainWindow);

  CGAL::Qt::Basic_viewer bv1(mainWindow, scene1);
  CGAL::Qt::Basic_viewer bv2(mainWindow, scene2);

  layout->addWidget(&bv1);
  layout->addWidget(&bv2);

  centralWidget->setLayout(layout);
  mainWindow->setCentralWidget(centralWidget);

  mainWindow->show();
  app.exec();
}

int main()
{
  std::string filename = CGAL::data_file_path("meshes/couplingdown.off");

  Mesh mesh;
  if (!PMP::IO::read_polygon_mesh(filename, mesh) || !CGAL::is_triangle_mesh(mesh))
  {
    std::cerr << "Invalid input." << std::endl;
    return 1;
  }

  // save original mesh in scene1 
  CGAL::Graphics_scene scene1;
  CGAL::add_to_graphics_scene(mesh, scene1);

  double target_edge_length = PMP::average_edge_length(mesh);

  std::cout << "Split long edges..." << std::endl;

  PMP::split_long_edges(mesh.edges(), target_edge_length, mesh);

  std::cout << "Detect features..." << std::endl;

  using EIFMap = boost::property_map<Mesh, CGAL::edge_is_feature_t>::type;
  EIFMap eif = get(CGAL::edge_is_feature, mesh);
  PMP::detect_sharp_edges(mesh, 45, eif);

  std::cout << "Start remeshing of " << filename
    << " (" << num_faces(mesh) << " faces)..." << std::endl;

  PMP::isotropic_remeshing(mesh.faces(), target_edge_length, mesh, 
    CGAL::parameters::edge_is_constrained_map(eif)
    .protect_constraints(true)
  );

  std::cout << "Remeshing done." << std::endl;

  // save remeshed mesh in scene2
  CGAL::Graphics_scene scene2;
  CGAL::add_to_graphics_scene(mesh, scene2);

  draw_2_scenes(scene1, scene2);

  return EXIT_SUCCESS;
}
```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows 64 bits
* Compiler: visual c++
* Release or debug mode:
* Specific flags used (if any):
* CGAL version: 6.0.1
* Boost version: 1.86
* Other libraries versions if used (Eigen, TBB, etc.):
Qt 6.7.3
Everything is installed via vcpkg (classic mode).

**Comment by janetournois** [comment]
Hello @yDF8EPJN8 
can you please send your data set so that we can try to reproduce the issue?

**Comment by yDF8EPJN8** [comment]
Hello @janetournois 
This example uses a model from the CGAL data. 

https://github.com/CGAL/cgal/blob/master/Data/data/meshes/couplingdown.off

**Comment by janetournois** [comment]
Your issues comes from the sharp edge angle bound you chose for this model.
As you can see on this closeup, the outer "edge" is not that sharp.![Image](https://github.com/user-attachments/assets/fb17d583-9db8-4a62-adcd-011de0842c05)

If you change for `PMP::detect_sharp_edges(mesh, 30, eif);`, features are nicely protected.

**Comment by yDF8EPJN8** [comment]
Indeed, if the angle is 30 degrees, the features, are preserved. 
But let's look at the hole in the figure. 
![Image](https://github.com/user-attachments/assets/53c96ca6-cc5b-45cb-930e-1d72c92f4649)
Here the problem remains. 
There are edges, the endpoints of which are on the original mesh, but the midpoints are not. 
We can set the angle equal to 10 degrees, then the edges along the cylindrical hole will become constrained, and there will be no edges with midpoints outside the surface.
But under such conditions the triangles are elongated, i.e. have poor quality, then the `isotropic_remeshing` function becomes meaningless to call.
I thought it would be easy to insert into the code a predicate for checking if a point belongs to the surface.
![Image](https://github.com/user-attachments/assets/28b5e668-9e3a-40ec-8774-4f24e9b0f67e)
