### ISSUE TITLE
Basic Viewer. Incorrect edges redrawing.

### ISSUE THREAD

**Issue by yDF8EPJN8** [CGAL/cgal#8664]
%%
Basic Viewer. Incorrect edges redrawing.
%%

## Issue Details

The first time you open the Viewer window, the edges are drawn as in the picture, which I think is correct.

![Image](https://github.com/user-attachments/assets/dbb8003e-c17d-44e1-87f2-d8f291fa995e)

When I press the 'E' key, the edges disappear. When I press the 'E' button again, the edges appear. But they are different from the first time.

![Image](https://github.com/user-attachments/assets/331af4e7-a06a-4269-a177-084c38c3a7cb)

I don't think it should be like this. Edges should always be drawn the same way.

## Source Code

```cmake
cmake_minimum_required(VERSION 3.14)

project(draw_surface_mesh)

find_package(CGAL REQUIRED OPTIONAL_COMPONENTS Qt6)

add_executable(${PROJECT_NAME} draw_surface_mesh.cpp)

target_link_libraries(${PROJECT_NAME} PUBLIC CGAL::CGAL_Basic_viewer)
```

```c++
#include <CGAL/Simple_cartesian.h>
#include <CGAL/Surface_mesh.h>
#include <CGAL/draw_surface_mesh.h>
#include <fstream>
 
typedef CGAL::Simple_cartesian<double>                       Kernel;
typedef Kernel::Point_3                                      Point;
typedef CGAL::Surface_mesh<Point>                            Mesh;
 
int main(int argc, char* argv[])
{
  const std::string filename = CGAL::data_file_path("meshes/couplingdown.off");
 
  Mesh sm;
  if(!CGAL::IO::read_polygon_mesh(filename, sm))
  {
    std::cerr << "Invalid input file: " << filename << std::endl;
    return EXIT_FAILURE;
  }

  CGAL::draw(sm);
 
  return EXIT_SUCCESS;
}
```

After the executable is compiled I run the following commands
- in release
```cmd
"%VCPKG_ROOT%\installed\x64-windows\tools\Qt6\bin\windeployqt.exe" draw_surface_mesh.exe
```
- in debug
```cmd
"%VCPKG_ROOT%\installed\x64-windows\tools\Qt6\bin\windeployqt.debug.bat" draw_surface_mesh.exe
```
## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows 64 bits
* Compiler: visual c++
* Release or debug mode: Release and debug
* Specific flags used (if any):
* CGAL version: 6.0.1
* Boost version: 1.86
* Other libraries versions if used (Eigen, TBB, etc.):
Qt 6.7.3
Everything is installed via vcpkg (classic mode).

**Comment by gdamiand** [comment]
This looks like a bug in opengl shaders; I do not observe this problem with my computer.

By the way we plan to change the method to draw segments: you can try the unofficial branch:
https://github.com/tgrillon/cgal/tree/gsoc2024-basic_viewer_glfw-tgrillon

**Comment by yDF8EPJN8** [comment]
I tried [unofficial branch](https://github.com/tgrillon/cgal/tree/gsoc2024-basic_viewer_glfw-tgrillon). There is no bug in the unofficial branch. I hope that the new method of drawing segments will appear in the main branch very soon.

**Comment by gdamiand** [comment]
ping @lrineau we need to plan some time to work on this branch, if possible in january.
