### ISSUE TITLE
Improve API of outlier removal in Point Set Processing

### ISSUE THREAD

**Issue by sgiraudot** [CGAL/cgal#868]
I am working on improving the API of the [outlier removal function](http://doc.cgal.org/4.7/Point_set_processing_3/group__PkgPointSetProcessing.html#ga91496d3e7b81fbfa3585aef1b4569743): so far, this function requires the user to give a percentage of points to remove. This is rather counter-intuitive, as the user usually does not know how many outliers are present.

The algorithm sorts the points according to the average squared distance to their K nearest neighbors and returns the N% of points with the highest values. Another possibility would be to give a threshold on this value and to return all the points that are above. The main advantage is that the parameter would then not be a percentage of points but something homogeneous to a squared distance: it seems easier to give a spacing parameter (by analyzing an outlier-free region with `CGAL::compute_average_spacing` for example) than a number of points.

For backwards compatibility reasons, we cannot simply replace the old API by the new (especially because the current parameter `percentage_threshold` and the proposed one `distance_threshold` have the same type, so the change of API would not even raise an error and be invisible to user, which is not good).

I would like to simply add an alternative to the function with the distance parameter. Is this a good idea? The current function is called `remove_outliers()`: how should I call the alternative? `remove_outliers_with_distance_threshold()`? `remove_unknown_number_of_outliers()`? All the names I can think of are a bit long :-)

**Comment by sloriot** [comment]
What about introducing named parameters as we did in the package `Polygon_mesh_processing`?
You could have both behavior depending on the options set, with the same function name. The old signature could be kept for backward compatibility.

**Comment by sgiraudot** [comment]
This issue has been also raised by other users.

After discussion with @afabri, it seems like a good solution would be to use a single function that has both parameters (the current `percentage_threshold` _and_ the new proposed `distance_threshold`). The function would remove as many outliers as needed so that both threshold are satisfied. This way:
- Putting `percentage_threshold=0` would allow the user to only use the distance threshold
- Puttign `distance_threshold=0` would allow the user to only use the percentage threshold (current behavior, that could be made default)

Any opinion on this solution? Do I make a pull request or do I need to do a small feature? (this is a change of API, so I guess a small feature is required)

**Comment by lrineau** [comment]
A small feature is required, to communicate the proposal to other CGAL developers, and maybe improve the proposal during a discussion.

**Comment by sgiraudot** [comment]
Fixed by #1647
