### ISSUE TITLE
autotest_cgal uses CGAL-I incorrectly

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#87]
When a daily testsuite is not finished while another start, as `localtest_script` uses `CGAL-I` instead of `CGAL_RELEASE_DIR`, the code of a release can interfere with the results of the next release.

**Comment by lrineau** [comment]
The bug is that in [`setup_dir()`](https://github.com/CGAL/cgal/blob/b7becbcdb80921ed1661742fb026f585c9562c91/Scripts/developer_scripts/autotest_cgal#L380), the variable `CGAL_DIR` is set to `${CGAL_ROOT}/CGAL-I`. Somehow, that variable is used later by `localtest_script`.

**Comment by sloriot** [comment]
#507 should fix this issue
