### ISSUE TITLE
NOTICE: This demo requires CGAL and Qt5, and will not be compiled.

### ISSUE THREAD

**Issue by freud14** [CGAL/cgal#885]
Hi, 
I'm trying to compile the Qt demos but I received the errors:

> NOTICE: This demo requires CGAL and Qt5, and will not be compiled.

The CGAL compilation works well even for the libCGAL_Qt5 package that requires Qt.  I'm running on Ubuntu 15.10. My version of CGAL source code is the last one on the Github repository. My Qt version is 5.4.2 and my cmake version is 3.2.2.

Thank you.

**Comment by freud14** [comment]
Alright, never mind, I just installed this bunch of paquets from the suggested list of paquets of libcgal-demo and it works: 

> libeigen3-dev libmpfi-dev libntl-dev libtbb-dev qtscript5-dev qttools5-dev qttools5-dev-tools libqt5opengl5-dev libqt5svg5-dev libqt5sql5-sqlite libglew-dev libqglviewer-dev libipe-dev libmagick++-dev liblapack-dev geomview libatlas-base-dev gfortran

I'll just let that here in case there is other people interested in the answer.

**Comment by afabri** [comment]
Is this list of Qt packages the minimal list to solve the problem, or just everything?

**Comment by freud14** [comment]
I installed everything that was suggested for the package. I don't know if some of them are optional.

**Comment by sloriot** [comment]
This is already documented [here](http://doc.cgal.org/4.8/Manual/installation.html#title20)

**Comment by freud14** [comment]
I tried to install the packages listed in the CMakeList of the CGAL package I was trying to install but it would not work.
