### ISSUE TITLE
Cleanup doxygen comments in Surface_mesh

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#889]
**update:** see the description in https://github.com/CGAL/cgal/issues/889#issuecomment-278311562 -- @lrineau

**Comment by lrineau** [comment]
In BGL as well.

**Comment by lrineau** [comment]
https://cgal.geometryfactory.com/CGAL/Members/wiki/Meetings/Sophia16#.7B.7BTick.7D.7D_Doxygen_comments_in_source_files

**Comment by lrineau** [comment]
Andreas, do you remember what you meant? Expect for the title, this issue is empty.

**Comment by maxGimeno** [comment]
@afabri can you elaborate ?

**Comment by afabri** [comment]
I don't remember and when I look at the header file I don't see anything particular. So let me close the issue.

**Comment by sloriot** [comment]
I guess it has to do Edge_index`, `Face_index`, and `Halfedge_index` that have specific documention+code. However, the code is not used. I guess we simply need to say that it's a model of Index and that it is convertible to `size_type`. The same kind of thing is probably done in BGL as Laurent pointed out originally.
