### ISSUE TITLE
Concept for geometry

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#906]
@gdamiand 
https://cgal.geometryfactory.com/CGAL/Members/wiki/Meetings/Sophia16#.E2.9C.94_Concept_for_geometry

**Comment by sgiraudot** [comment]
The issue is ticked in the wiki, but I think that just means the issue _was_ discussed, not solved. So I guess this issue is still a valid issue?

**Comment by lrineau** [comment]
I have re-added the "dev-meeting", that I created for issues created to track discussions of the developer meetings, so that at the following meetings they can be discussed again, until we reach a conclusion.

@gdamiand You created the topic. Do you want to keep it alive?

**Comment by lrineau** [comment]
@gdamiand Is that still a topic you want to discuss or address? It was created by you in the CGAL developers meeting, Sophia-Antipolis, 2016.

**Comment by gdamiand** [comment]
Ce can close it. It seems a too complicated effort...
