### ISSUE TITLE
Automatic table generation for small features

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#907]
This issue will track progress and issues of the automatic generation of (small) features tables.
@lrineau
@MoniqueTeillaud

**Comment by MoniqueTeillaud** [comment]
see bug in column "Comments" of the big table for small features: some entries appear twice, even though they are written only once in the table of the corresponding small features

**Comment by lrineau** [comment]
The reason is that those pages have both `Pre-approval=` and `|Comments=` in the argument of the template `{{feature}}`. You can see that in the source code of the wiki page, and no longer in the "edit with form".

This page lists the wiki pages that still use the old syntax:
https://cgal.geometryfactory.com/CGAL/Members/wiki/Property:Pre-approval

**Comment by sloriot** [comment]
@lrineau we can close this issue, right?

**Comment by lrineau** [comment]
Yes! :-)
