### ISSUE TITLE
Spectra and geodesic distances

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#908]
https://cgal.geometryfactory.com/CGAL/Members/wiki/Meetings/Sophia16#.E2.9C.94_Spectra_and_geodesic_distances

**Comment by sloriot** [comment]
@sgiraudot @palliez IIRC spectra will be merged into Eigen. If I'm right, shall we close this issue?

**Comment by sgiraudot** [comment]
I think there is stll the question of adding wrappers in CGAL to access the Spectra functions (similarly to what is done with Eigen in `Solver_interface`). @palliez, what do you think?

**Comment by janetournois** [comment]
@palliez up :)

**Comment by sgiraudot** [comment]
@palliez any news on this issue? Is there a work in progress to add wrappers to Spectra functions in CGAL?

**Comment by MaelRL** [comment]
@palliez  will ask Gaël Guennebaud what is the status of the integration of Spectra into Eigen.

**Comment by MaelRL** [comment]
From Gaël's answer, Spectra won't be integrated in the near future.

**Comment by sloriot** [comment]
Spectra being a header only library, using it in a CGAL package is not a problem. A simple cmake find module should be written.
I close this issue now.
