### ISSUE TITLE
CGAL::Polyhedron_incremental_builder_3 throws from it's destructor

### ISSUE THREAD

**Issue by burnpanck** [CGAL/cgal#91]
In general, it is considered bad practice to throw from destructors, particularly, since destructors that throw during stack unwinding may lead to the runtime terminating the program. In this particular case, 
the destructor has a simple `CGAL_assert( check_protocoll == 0 );` that is probably mainly intended to help debugging: It should notify the user that the usage protocol was not properly followed. However, in my case, that lead to program termination which is much worse for debugging, since the failure causing data is essentially lost.

I propose to move the protocol check into `end_surface`, (with the risk of not getting notified if someone forgets end_surface), and possibly stick with a notification to stderr (personally, I don't like those) in the destructor.

**Comment by sloriot** [comment]
Which version of CGAL are you using?

**Comment by burnpanck** [comment]
That was CGAL 4.6 built from official release tarballs. But the analysis above comes from looking at the source, not running any code. It's as simple as looking at https://github.com/CGAL/cgal/blob/master/Polyhedron/include/CGAL/Polyhedron_incremental_builder_3.h#L199 in master, to see that it has a `CGAL_assertion` in it's destructor, which is a bad thing.

**Comment by burnpanck** [comment]
See also: http://stackoverflow.com/questions/130117/throwing-exceptions-out-of-a-destructor

**Comment by sloriot** [comment]
A CGAL_assertion is not meant to be used as an exception but really for debugging purpose.
I was asking the question about the version because an issue with Nef_3 was reported, and this class was indeed throwing an exception but it was a bug in the code of Nef_3.

Thanks for taking time to report.

**Comment by burnpanck** [comment]
But we agree that, ideally, that assert should not be there, but rather somewhere else? Particularly, since it is meant for debugging purposes, the fact that it does throw makes it particularly unsuitable to put in a destructor.

**Comment by lrineau** [comment]
I tend to agree with the reporter of the bug. Destructors should not throw, and the assertions of CGAL are not always used during debugging. I know users of CGAL, even among GeometryFactory customers, who activate the assertions of CGAL even in production.

**Comment by lrineau** [comment]
@burnpanck Can say again what what your proposal? The best would be you even fill a pull-request in Github. That would speed up the resolution of this bug.

**Comment by burnpanck** [comment]
My proposal is to just move the corresponding assertion from the destructor to the end of `end_surface`. There, it would capture all protocol violations except for actually forgetting to call `end_surface`. So, if you really think that there is need for debugging help against that kind of mistake, then also check for protocol violations in the destructor and issue a message to std::cerr if that is the case.
Unfortunately, I'm quite busy now... bump me in a week and I'll do a PR.

**Comment by sloriot** [comment]
Somehow fixed by #451
