### ISSUE TITLE
Polyhedro demo: `Plugins/Mesh_3/` vs `Plugins/Mesh_2_plugin/`

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#912]
The PR #844 has renamed the directory `Plugins/Mesh_3_plugin/` to `Plugins/Mesh_3`. Meanwhile, the PR #859 has added a new plugin, in the sub-directory `Plugins/Mesh_2_plugin/`.

  - `Plugins/Mesh_2_plugin/`
  - `Plugins/Mesh_3/`

That is not consistent. In my opinion, the Mesh_2 plugin directory should be renamed as well.

**Comment by sloriot** [comment]
They were done in parallel thus the inconsistency. Fixed by #913
