### ISSUE TITLE
Non-reproducible runtime error of test/Point_set_processing/vcm_all_test.cpp

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#919]
While comparing the test results from today and yesterday, I found that the test `vcm_all_test` sometimes has runtime errors, without any visible reason (nothing in the history of the branch can explain why the test suddenly failed).
For example:
* https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.8-Ic-160/Point_set_processing_3/TestReport_afabri_x64_Cygwin-Windows8_MSVC2012-Release-32bits.gz
* https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.8-I-146/Point_set_processing_3/TestReport_cgaltester_x86-64_Darwin-13.0_Apple-clang-5.0_Release.gz

Is that test random? Do you see a reason why the test can exit with an error without displaying any useful message?

Cc: @afabri, @palliez, @sgiraudot

**Comment by afabri** [comment]
Remember my PR where I printout the seed of default_random ??  Its integration is scheduled for 4.9

**Comment by sgiraudot** [comment]
`vcm_all_test` is performed on a loaded point set and I don't see any randomness in the test. I'll check if there is randomness in the VCM algorithm.

The code of the main function is pretty simple:

```
int main ()
{
  bool res1=test_fandisk();
  if (res1)
    std::cout << "fandisk tests OK\n";
  else
    std::cout << "fandisk tests KO\n";

  bool res2 = true;

  if (!res1 || !res2) return 1;
  return 0;
}
```

I guess `res2` was designed to test something else... But anyway, there should be _fandisk tests KO_ displayed if `test_fandisk` was failing. Is it possible it is not displayed because of using `std::cout` instead of `std::cerr`?

**Comment by lrineau** [comment]
No. The display to `std::cout` is sufficient, because nothing can interrupt the test after the display to `cout`: the normal interruption of `main` with `return` will flush `std::cout`.
I think the test is interrupted inside `test_fandisk()`. That is strange that there is nothing displayed, on the Windows platform. But that platform is a `Release` platform: no assertion inside the CGAL algorithms, but only `assert` calls in the tests. Maybe `abort()` is called directly by the algorithm, or by a third party library that is used.

In the second link, there is an assertion:
```------------------------------------------------------------------
- ProgramOutput.vcm_all_test.x86-64_Darwin-13.0_Apple-clang-5.0_Release
------------------------------------------------------------------
=== test_fandisk ===
 Test compute vcm without convolution
 Test compute vcm with convolution
CGAL error: assertion violation!
Expression : is_finite(d)
File       : /Users/cgaltester/cgal_test/CGAL-4.8-I-146/include/CGAL/GMP/Gmpq_type.h
Line       : 168
Explanation: 
Refer to the bug-reporting instructions at http://www.cgal.org/bug_report.html
libc++abi.dylib: terminating with uncaught exception of type CGAL::Assertion_exception: CGAL ERROR: assertion violation!
Expr: is_finite(d)
File: /Users/cgaltester/cgal_test/CGAL-4.8-I-146/include/CGAL/GMP/Gmpq_type.h
Line: 168
./cgal_test_with_cmake: line 69: 76119 Abort trap: 6           ./vcm_all_test

```

**Comment by lrineau** [comment]
Also in:
* https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.9-Ic-1/Point_set_processing_3/TestReport_afabri_x64_Cygwin-Windows8_MSVC2012-Release-32bits.gz
* https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.9-Ic-3/Point_set_processing_3/TestReport_afabri_x64_Cygwin-Windows8_MSVC2012-Release-32bits.gz

**Comment by lrineau** [comment]
Another one, on Windows:
* https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.9-I-14/Point_set_processing_3/TestReport_afabri_x64_Cygwin-Windows8_MSVC2012-Release-32bits.gz
* https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.9-I-14/Point_set_processing_3/TestReport_afabri_x64_Cygwin-Windows8_MSVC2013-Release-32bits.gz|

But this time we have the seed of `CGAL::get_default_random()`. That will help to reproduce.
