### ISSUE TITLE
CGAL::Euler::join_vertex() : graph broken

### ISSUE THREAD

**Issue by maxGimeno** [CGAL/cgal#925]
In this configuration : 
![join_vertex](https://cloud.githubusercontent.com/assets/11310805/13879323/2a64440a-ed17-11e5-9a39-68a9cae6fea7.png)
from off file :
[test.txt](https://github.com/CGAL/cgal/files/179803/test.txt)

When joining the vertices of the red halfedge, the altered graph is somehow broken by `CGAL::Euler::join_vertex()`, although the function from `Polyhedron_3` seems to work. I think a halfedge is not deleted when it should, because when debugging we see that its facet and vertex are both NULL.

**Comment by lrineau** [comment]
@janetournois @sloriot

**Comment by sloriot** [comment]
@afabri

**Comment by afabri** [comment]
The BGL and Surface_mesh_simplification testsuite is green now.

**Comment by lrineau** [comment]
Fixed by #926.
