### ISSUE TITLE
Isotropic remeshing: assertion failure

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#927]
Running the remeshing on the attached data set  with edge protection ON triggers:
```
CGAL ERROR: assertion violation!
Expr: PMP::is_degenerated(h, mesh_, vpmap_, GeomTraits())
File: Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Isotropic_remeshing/remesh_impl.h
Line: 1297
```
[data.zip](https://github.com/CGAL/cgal/files/179896/data.zip)

cc @janetournois

**Comment by lrineau** [comment]
Fixed by PR #948.

@janetournois has signaled that the code is still buggy for other degenerates cases. The fix for those other cases will probably wait for 4.8.1.
