### ISSUE TITLE
Path Selection

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#930]
In the selection tool I would like to mark two vertices p and q for the mesh below

![selectionpq](https://cloud.githubusercontent.com/assets/3263539/13896682/bb335e16-ed95-11e5-9eb4-68f95f8769e0.jpg)

in order to add the feature line (which is not sharp enough).  
Note that the shortest path would be the dotted black line.
- We might have the dihedral angle at edges as a weight for the distance.
- The user might select an intermediate vertex where the path from p to q has to pass through.

**Comment by lrineau** [comment]
@maxGimeno Is that addressed by recent pull-requests?

**Comment by maxGimeno** [comment]
I have a local branch that contains the finished work but it is based on Euler_operations-rebase-GF which is not yet merged, so I made no PR yet.
