### ISSUE TITLE
Polyhedron demo clipping plugin - reverse plane

### ISSUE THREAD

**Issue by janetournois** [CGAL/cgal#932]
The clip_polyhedron_plugin does a nice job but it would be nice to be able to revert the "blue" and "yellow" sides of the clipping plane.
todo : add a button that changes the orientation of the plane to swap blue and yellow sides

cc @sloriot @maxGimeno

**Comment by afabri** [comment]
Once you are at it, can you please also offer the possibility to just cut it into 2 polyhedra.

**Comment by maxGimeno** [comment]
@afabri I find it weird to add a feature that does not clip a polyhedron to
a plugin called "Clip polyhedron".

2016-03-21 12:04 GMT+01:00 Andreas Fabri <notifications@github.com>:

**Comment by janetournois** [comment]
@maxGimeno it does clip it, but it clips it to two sub-polyhedra (into two Scene_polyhedron_item's)

**Comment by maxGimeno** [comment]
Ok, my bad. I will work on this this afternoon.

2016-03-21 12:13 GMT+01:00 Jane Tournois <notifications@github.com>:

**Comment by afabri** [comment]
It could be split or clip

**Comment by maxGimeno** [comment]
There is already a plugin for splitting, I thought we could add this
feature to this one, like "automatic split // manual split"

2016-03-21 12:28 GMT+01:00 Andreas Fabri <notifications@github.com>:

**Comment by afabri** [comment]
The split you refer to is about connected components.

**Comment by maxGimeno** [comment]
Yes indeed. Anyway, I will do as you said.

2016-03-21 12:30 GMT+01:00 Andreas Fabri <notifications@github.com>:

**Comment by lrineau** [comment]
The key <bkd>T</bkd> already reverses the camera. Maybe <bkd>Ctrl+T</bkd> could reverse the manipulated frame. That would not be specific to the clip plane.

Unfortunately, <bkd>Ctrl+T</bkd> is already assigned to "Draw two sides" but I think we could change the binding.

**Comment by maxGimeno** [comment]
Seems like a good idea. Do we really need a binding for draw two sides, or
is the sufficient ?

2016-03-21 13:03 GMT+01:00 Laurent Rineau <notifications@github.com>:

**Comment by lrineau** [comment]
I think <kbd>Ctrl+T</kbd> for "draw two sides" is more know and used than the <kbd>T</kbd> binding for "turn the camera by 180°". Maybe the later should be changed. "R" for "reverse" is already used by QGLViewer, for "rotate". Would could be the good binding?

**Comment by lrineau** [comment]
I could be "U" like a "u-turn". :-)

**Comment by afabri** [comment]
The approach we take to finding letters for shortcuts is too adhoc, or greedy.

**Comment by lrineau** [comment]
Unless you come up with a better proposal, the ad-hoc greedy approach is the best we have.

**Comment by afabri** [comment]
no shortcut

**Comment by janetournois** [comment]
Why does adding a "reverse plane" button hurt?
Shortcuts are nice, but I would probably not have found it (however it had been chosen) when I wanted to reverse the plane

**Comment by lrineau** [comment]
Fixed by #934.
