### ISSUE TITLE
Polygon_mesh_processing::orient_polygon_soup() fails on a degenerate case

### ISSUE THREAD

**Issue by efifogel** [CGAL/cgal#935]
Take a tetrahedron and duplicate one of its triangles:

Points: 0 0 0, 0 1 0, 1 0 0, 0 0 1
Indices: 0 1 2, 0 2 3, 0 3 1, 1 3 2, 0 1 2

So the last triangle is a duplication of the first.
I would expect to get 7 points, where point [0], [1], and [2] are duplicated and 2 disconnected components. More precisely, I expect to get something like:

Points: 0 0 0, 0 1 0, 1 0 0, 0 0 1, 0 0 0, 0 1 0, 1 0 0
Indices: 0 1 2, 0 2 3, 0 3 1, 1 3 2, 4 5 6

but I get:

Points:  0, 0, 0 0, 1, 0 1, 0, 0 0, 0, 1 0, 0, 0 0, 0, 0 0, 1, 0 0, 1, 0 1, 0, 0 1, 0, 0 
Indices: 0 1 2, 4 8 3, 4 3 6, 6 3 8, 5 7 9

Notice that I get 3 disconnected components.

**Comment by sloriot** [comment]
This is the expected behavior described in the original publication. The algorithm could be improved with some post-processing, merging duplicated vertices (or more generally stitch edges) that are in the same connected component after the split.

**Comment by efifogel** [comment]
It doesn't make sense. I start with a tetrahedron and a triangle, say t. I
end up with 3 connected components: two ccs that  cosist of just one
triangle each---the same as t,  and one cc that consists of only 3
triangles---the original input tetrahedron minus t. If this is the expected
behavior,  then the expected behavior should change...

**Comment by sloriot** [comment]
You can double check the original publication. I already tried to come up with an improved algorithm but it was failing on some cases so I decided to stick to the original one for the time being. Note that I tagged the issue as "feature request". I'll come back to it as soon as I have time.

**Comment by efifogel** [comment]
Fair enough.  I'll take a look at the publication.

**Comment by sloriot** [comment]
@MaelRL I guess the issue reported by @efifogel is fixed by `PMP::repair_polygon_soup()`. Shall we close it?

**Comment by MaelRL** [comment]
Sure
