### ISSUE TITLE
Runtime error in Optimal_transportation_reconstruction_2 (formerly Reconstruction_simplification_2)

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#939]
https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.9-Ic-3/Optimal_transportation_reconstruction_2/TestReport_lrineau_Fedora-32-Release.gz
```
------------------------------------------------------------------
- ProgramOutput.test_vertex_edge.Fedora-32-Release
------------------------------------------------------------------
test_num_of_vertices_in_triangulation
test_edge_collapse
insert loose bbox...done (4 vertices, 4.9927e-06 s)
init...done (164 vertices, 0.000207911 s)
assign samples...done (0.000880115 s)
./cgal_test_with_cmake: line 69: 11016 Floating point exception(core dumped) ./test_vertex_edge
```

Cc: the authors (@cjamin @palliez), and GeometryFactory (@afabri @sgiraudot)

**Comment by lrineau** [comment]
Another one, today:
https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.8-I-163/Optimal_transportation_reconstruction_2/TestReport_lrineau_Fedora-32-Release.gz
```
------------------------------------------------------------------
- ProgramOutput.test_vertex_edge.Fedora-32-Release
------------------------------------------------------------------
test_num_of_vertices_in_triangulation
test_edge_collapse
insert loose bbox...done (4 vertices, 4.10294e-06 s)
init...done (164 vertices, 0.000149002 s)
assign samples...done (0.000592917 s)
./cgal_test_with_cmake: line 69: 10172 Floating point exception(core dumped) ./test_vertex_edge
```

**Comment by afabri** [comment]
@cjamin It might make sense to replace the call to rand()  with `CGAL::Random`

**Comment by cjamin** [comment]
Thanks, Andreas. And you changed `CGAL::Random` recently so that we'll get the seed value in the testsuite next time, am I right?

I have this bug in my TODO-list, but I don't have time right now to look into it. And I'm afraid I won't be able to reproduce it on my platform.

**Comment by lrineau** [comment]
The PR #986 is new merged in `master`. In next test results, from tonight, the seed of the random generator will be displayed.

**Comment by sloriot** [comment]
@cjamin Any chance you can fix it before the end of the week or shall we postpone it to 4.9?

**Comment by cjamin** [comment]
It's in my TODO-list, but I won't have time to look into it this week. So let's post-pone it.
Do you have a link to such an error with the seed printed?

**Comment by sloriot** [comment]
This [testsuite](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.9-Ic-92/Optimal_transportation_reconstruction_2_Examples/TestReport_lrineau_CentOS5.gz) has the error. I tried to reproduce the pb in the container but gdb was not able to tell me where the segfault occurs.

**Comment by lrineau** [comment]
"Floating point exception". That is not a segmentation fault, but an asynchronous exception raised by the FP unit. It indicates that there has been a division by zero, either `x/y` for floating point numbers, or `x%y` between integral values, with `y==0`.

**Comment by cjamin** [comment]
Fixed in #1322

**Comment by lrineau** [comment]
Fixed in `master`, for 4.9.

@sgiraudot Do we want to backport the fix for the branch that targets 4.8.2?

**Comment by sgiraudot** [comment]
It seems to me that the floating point bug (https://github.com/CGAL/cgal/issues/939) was introduced in 4.9 when switching to the `boost::optional` behavior. The code of 4.8 looks like this:

```
    FT Dqt = (std::numeric_limits<FT>::max)();
    CGAL::Object result = CGAL::intersection(lab, lts);
    const Point* iq = CGAL::object_cast<Point>(&result);
    if (iq)
      Dqt = CGAL::sqrt(geom_traits().compute_squared_distance_2_object()(*iq, pt));
```
So the test `if(iq)` was already there and there shouldn't be a bug.

I don't know about the other bug about CImg linking (https://github.com/CGAL/cgal/issues/965), but it's probably not critical as it's in a demo.

**Comment by lrineau** [comment]
You are right.Thanks.
