### ISSUE TITLE
Bézier Arrangements bug report - segmentation fault upon insertion of a Bézier curve

### ISSUE THREAD

**Issue by myirci** [CGAL/cgal#94]
I provide a simple program which yields a segmentation fault when inserting Bézier curves to a Bézier Arrangement. I believe this error is related to the kernel used within the Bézier arrangement. I've shared the details at the following link which includes the detailed information, a very simple program, an image to display the error condition and the stack trace.

Please check the link for the shared files. For anything related to this issue, you can contact to me via e-mail: myirci@gmail.com

https://drive.google.com/file/d/0ByXhUOvsZStITS1iaDFFT2NxVjg/view?usp=sharing

**Comment by efifogel** [comment]
Hi Myirci,

The program ex_Bezier_curves.cpp
<http://acg.cs.tau.ac.il/cgal-arrangement-book/examples/chapter-5/ex_Bezier_curves.cpp>,
which is a very similar version of a distributed example listed in the
manual, works just fine with your input.
It may require other header files, which you can find here:
http://acg.cs.tau.ac.il/cgal-arrangement-book/source-code-data-and-miscellaneous-files
<http://acg.cs.tau.ac.il/cgal-arrangement-book/source-code-data-and-miscellaneous-files>
You are probably doing something wromg in your code.

Best,
Efi
   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by myirci** [comment]
Hi Efi,

There is a difference between the program that you gave the link and mine. In my program I insert the curves one by one and in the given one all of them are inserted at once. After I adapted my program similarly it also worked. Thus, there must be something wrong with the insert (arr, curve, point location) API.

I also updated the sample code I provided before. In this version, two different approaches (insert all at once, and insert one by one) are coded. Insert at once works but, insert one by one fails. The updated sample code can be accessed by the following:
https://drive.google.com/file/d/0ByXhUOvsZStIdzJqMl9ObjdKcGc/view?usp=sharing
 
Best Regargs,
Murat

**Comment by efifogel** [comment]
Hi Murat,

You are correct!
There is a bug with the incremental insertion of Bezier curves.
The aggregate insertion seems to work fine.
Apparently, even the 4 curves bellow reproduce the error.
Notice that they all have the same denominator, so the program flow should
be the same without the denominators (or with all equal to 1).
However, with the denominators equal to 10 I get the assertion bellow.
I'll see what I can do.
If you have more insights, please share.

Thanks,
Efi

// Assertion
terminate called after throwing an instance of 'CGAL::Assertion_exception'
  what():  CGAL ERROR: assertion violation!
Expr: roots.size()==1
File:
/home/efif/trees/cgal_dev/Arrangement_on_surface_2/include/CGAL/Arr_geometry_traits/Bezier_x_monotone_2.h
Line: 967

// Curves:
2 3791/10  3546/10 3354/10 3426/10
3 3222/10  3592/10 3284/10 3508/10 3354/10 3426/10
3 3308/10  2922/10 3308/10 3168/10 3354/10 3426/10
2   52/10 15042/10 4188/10  122/10

// Code:
#include "arr_Bezier.h"
#include "arr_print.h"
#include "read_objects.h"

int main(int argc, char* argv[])
{
  const char* filename = (argc > 1) ? argv[1] : "Bezier.dat";
  std::list<Bezier_curve>  curves;
  read_objects<Bezier_curve>(filename, std::back_inserter(curves));
  Arrangement arr;
#if 0
  CGAL::insert(arr, curves.begin(), curves.end());
#else
  std::list<Bezier_curve>::const_iterator it = curves.begin();
  for (; it != curves.end(); ++it) CGAL::insert(arr, *it);
#endif
  print_arrangement_size(arr);
  return 0;
}


   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by myirci** [comment]
Hi Efi,

I added an observer to the simple program to check the intersecting points. It seems that the error case occurs when the intersecting point is algebraic for both set of curves. However I know that every algebraic intersecting point does not cause an error. 

The stack trace shows a number of function calls and the segmentation fault comes down to the following lines in the /CGAL/CORE/BigInt.h. 

90  explicit BigIntRep(mpz_srcptr z) {
91  mpz_init_set(mp, z);
92 }

However I have no idea  at which point the error is introduced within these functions calls. 

And here is the print out from the observer:
curve-1 begin	: OK
curve-1 end	: OK
********************************************
curve-2 begin	: OK
curve-2 end	: OK
********************************************
curve-3 begin	: OK
curve-3 end	: OK
********************************************
curve-4 begin	: OK
before_split_edge: 
source: 322.2 359.2
target: 335.4 342.6
split point: algebraic ~322.8510529960894 ~358.321443253952
control points of the supporting curve for the halfedge: 
1611/5 1796/5
1642/5 1754/5
1677/5 1713/5
-----------------------------------
after_split_edge
-----------------------------------

Regards,

Murat

**Comment by sloriot** [comment]
@efifogel  did you make any progress on this issue?

**Comment by efifogel** [comment]
No, sorry. Doing other things....

   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by sgiraudot** [comment]
@efifogel Is there any news about this issue? Is somebody else able to take care of it if you don't have the time?

**Comment by efifogel** [comment]
I haven't developed the Bezier traits and the authors are long gone.
I will not be able to handle it within the next couple of months.

   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by sgiraudot** [comment]
Okay, thank you for the update!

**Comment by theartful** [comment]
I'll take a stab at this issue to familiarize myself more with the package
