### ISSUE TITLE
Polyhedron demo: more verbose isotropic remeshing plugin

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#941]
The isotropic remeshing plugin is able to handle (in parallel) the remeshing of all the polyhedron items selected. It would be useful to display when the remeshing of a model is done (and started?) to get an idea of the progression. A display on the console would be sufficient to me.

cc @maxGimeno @janetournois

**Comment by janetournois** [comment]
the PR has been merged, this issue can be closed
@lrineau

**Comment by lrineau** [comment]
Fixed by #959.
