### ISSUE TITLE
Compilation error of examples/Surface_mesh_shortest_path with OpenMesh, on Linux Fedora 23

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#942]
Until last night, OpenMesh was not tested anywhere in our testsuite. Yesterday, I have installed OpenMesh in one of our Docker images, the one named `Fedora`. There is a compilation error, here:
https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.9-Ic-5/Surface_mesh_shortest_path_Examples/TestReport_lrineau_Fedora.gz

@CGAL/geometryfactory

**Comment by sloriot** [comment]
This should be fixed by CGAL/cgal-dev@309f91f1

**Comment by lrineau** [comment]
I think that commit should be cherry-picked in a pull-request for `releases/CGAL-4.8-branch`.

**Comment by sloriot** [comment]
See #945

**Comment by lrineau** [comment]
The PR #945 is merged. It is supposed to fix this issue.
