### ISSUE TITLE
Triangulation_file_input.h, similar to copy_TDS

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#946]
On one hand, there is that accepted small feature: https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/More_general_copy_tds

On the other hand, there is the file [`Polyhedron/demo/Polyhedron/include/CGAL/Triangulation_file_input.h`](https://github.com/CGAL/cgal/blob/releases/CGAL-4.8-beta2/Polyhedron/demo/Polyhedron/include/CGAL/Triangulation_file_input.h) that uses a similar method, with different names.

I suggest that we unify the API of the two, and submit the improved `Triangulation_file_input.h`.

To: @sloriot @janetournois 
Cc: @afabri

**Comment by maxGimeno** [comment]
Appart from renaming Update_vertex and Update_cell, I don't see what is to be done. The two functions are not that similar, one is an IO free function that works with an inputstream, the other is a member function that works with a CDT. How is it possible to unify them ?

**Comment by lrineau** [comment]
Both functions convert one triangulation type to another:
- [`TDS::copy_tds`] copies from a triangulation in memory to another triangulation in memory
- [`file_input` from `demo/Polyhedron/include/CGAL/Triangulation_file_input.h`][2] takes the triangulation stored in a file, and copies (or loads) to a triangulation in memory.
In both cases, there are conversion functors that are invoked, to convert the `Vertex` and `Cell` type from a triangulation type to another.

[`TDS::copy_tds`]: https://doc.cgal.org/4.11/TDS_3/classTriangulationDataStructure__3.html#aac784b676421bd590612bb08c0a84f89
[2]: https://github.com/CGAL/cgal/blob/releases/CGAL-4.11.1/Polyhedron/demo/Polyhedron/include/CGAL/Triangulation_file_input.h

The fact that one is a member function template, whereas the other is a function template, is not important:  none of them uses any private data of the TDS/triangulation types.

The task of this issue is:
1. Unify the API,
2. Submit a small feature to add `TDS::file_input`.

You already said that the first point is rather trivial. Good.

**Comment by lrineau** [comment]
But before you start, I suggest we wait for approval/comments from @sloriot, @janetournois, and @afabri.

**Comment by sloriot** [comment]
What is ` file_input()` supposed to be compared to `operator>>()`?

**Comment by lrineau** [comment]
The same difference as between `TDS::copy_tds()` and and the copy constructor `TDS(const TDS& TDS)`:
- the signature of `operator>>` is constrained by the C++ norm: `istream& operator>>(istream&, TDS&)` (
- `file_input` is a function template (or a function template member), and can have more parameters: in particular it has two optional functors that convert the `Vertex` and `Cell` types, so that one can load a file that was a dump of a triangulation type `T1`, to another triangulation type `T2`.

**Comment by lrineau** [comment]
As for the use cases, in `Polyhedron_demo_c3t3_binary_io_plugin::try_load_other_binary_format`:
https://github.com/CGAL/cgal/blob/27859944b4d96797030fc018892d5123b7cba0b2/Polyhedron/demo/Polyhedron/Plugins/Mesh_3/C3t3_io_plugin.cpp#L478-L482

**Comment by lrineau** [comment]
`file_input` could be implemented by a normal load of a TDS/Triangulation_3, and then `copy_tds` to convert the types, but that would mean having two copies of the TDS in memory, whereas `file_input` does the conversion on the fly, when vertices and cells are loaded.

**Comment by janetournois** [comment]
I would have only one question/suggestion/request...

As you know, @MaelRL and I have been working on a function that reads a triangulation from a `.mesh` file, whether or not the triangulation covers the convex hull of the set of points.
Could it be (I don't know how yet) unified with that new function?

**Comment by lrineau** [comment]
I want to point out that I still need that. From time to time I need that function [`file_input` from `demo/Polyhedron/include/CGAL/Triangulation_file_input.h`][2] takes the triangulation stored in a file, and copies (or loads) to a triangulation in memory, and that would be nice to have it documented with a proper API.

[2]: https://github.com/CGAL/cgal/blob/releases/CGAL-4.11.1/Polyhedron/demo/Polyhedron/include/CGAL/Triangulation_file_input.h
