### ISSUE TITLE
Concurrency in 2D Triangulation

### ISSUE THREAD

**Issue by orzechow** [CGAL/cgal#95]
Using the `Concurrency_tag` on the `Triangulation_data_structure_3` one can enable parallel execution of vertex operations etc. thus boosting performance.

I'm waiting for this feature to come for 2D Triangulations!
Is it planned there or do I have to unnecessarily switch to 3D versions?

**Comment by lrineau** [comment]
Unfortunately, there are no ongoing work on that topic. Triangulation_2 is considered as a low-priority. We do not know any use-cases where the efficiency of 2D triangulations in CGAL can be an issue.

[Inria](http://www.inria.fr), the research institute that owns the CGAL triangulations code does not plan to fund any work on the parallelism of 2D triangulations, and [GeometryFactory](http://geometryfactory.com) will not either, unless there is a customer who asks for that feature and pays for it.

I have to close that bug report as "wontfix". I am sorry.

**Comment by orzechow** [comment]
I am using the 2D triangulation on feature points extracted from (a lot of) images, therefore 2D data.
As it is not planned, I will get along without this feature and parallelize other processing steps in order to use all resources available.

Thank you anyway!

**Comment by lrineau** [comment]
The parallelization of the 3D triangulation has showed that the contention between the different threads is significant: when N threads operate on on 3D triangulation, then the gain of speed is lower than N. See [the section "Parallel Performance" of the CGAL documentation of 3D triangulations](http://doc.cgal.org/4.6/Triangulation_3/#title26).

If you have multiple images, and therefor certainly multiple triangulations, you will gain more by adding the parallelism at a higher level. That way, your threads will operate on different triangulations, and that will remove one source of contention.

**Comment by orzechow** [comment]
Okay, I see. Implemeting the paralellism on a low level is not as good.
Yes, I have multiple triangulations and already implemented the higher level parallelism a couple of days ago. It performs pretty well.
