### ISSUE TITLE
Polyhedron demo: buggy draw of `Scene_segmented_image_item.cpp`

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#950]
From the file [`2×2×2.inr`](https://cgal.geometryfactory.com/~lrineau/2%c3%972%c3%972.inr), the loaded `Scene_segmented_image_item` is cleary wrong.
![222-wrong](https://cloud.githubusercontent.com/assets/5746675/14043918/276db010-f28a-11e5-8cfc-10e22315dcbb.png)
The real object encoded by the 3D image is more like that 3D mesh, produced by Mesh_3:
![222-object](https://cloud.githubusercontent.com/assets/5746675/14043935/5e740064-f28a-11e5-852a-8780a4a40160.png)

If both the mesh and the 3D  image are drawn at the same time, with the image in wireframe, that gives:
![222-both](https://cloud.githubusercontent.com/assets/5746675/14043963/c2786ae6-f28a-11e5-8a84-d966a586d766.png)
![222-both-from-z](https://cloud.githubusercontent.com/assets/5746675/14043964/c5f66db2-f28a-11e5-8c0a-193e72a728d8.png)

**Comment by sloriot** [comment]
@maxGimeno  is this fixed?

**Comment by lrineau** [comment]
I have updated my first comment to add the link to the [2×2×2.inr][222] file.

[222]: https://cgal.geometryfactory.com/~lrineau/2%c3%972%c3%972.inr

**Comment by maxGimeno** [comment]
It's not fixed yet

**Comment by lrineau** [comment]
#1270 does not really fixes the issue. The display of the box is now coherent with the display of the facets of the image, but that is still not coherent with the object that can be meshed from the image.

**Comment by lrineau** [comment]
I reopen again this bug, because the #1301 does not fix the color issue.

**Comment by lrineau** [comment]
Let's close it now, and reopen another issue for the remaining color problem.
