### ISSUE TITLE
Orthogonal_k_neighbor_search.cpp prints errors

### ISSUE THREAD

**Issue by mglisse** [CGAL/cgal#953]
Looking at a random run of the testsuite: https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.9-Ic-6/Spatial_searching/TestReport_lrineau_CentOS6-CXX11-Boost157.gz the test Orthogonal_k_neighbor_search prints many lines of the form

> Error: Point -0.999521 -0.662093 at distance 1.43741  >  0.442363

The test still returns 0 and the testsuite shows up green. Is this output expected? If so, it would be nice to reformulate it so it doesn't look so much like there is a bug... And if it isn't expected, then you know...

**Comment by sloriot** [comment]
@afabri the commit that introduced the regression is af343d92

**Comment by sloriot** [comment]
Most probably in `Spatial_searching/include/CGAL/Orthogonal_k_neighbor_search.h ` since the nearest is working fine.

**Comment by lrineau** [comment]
Andreas, the bug was introduce during the internship of Markus, that was optimizing the speed of the kd-tree package. Now, it is faster, but the testsuite reports errors. it seems that it does no longer always return the closest points.

KD-tree is an important tool in CGAL. You just told me so yesterday.

**Comment by sloriot** [comment]
Working on it, it's the further point that is not correct. Error is indeed in the aforementioned file

**Comment by afabri** [comment]
This morning I gave Sebastien a file with just 13 points that produces the bug.

**Comment by lrineau** [comment]
Communicate in the issue tracker instead of private communications. That would avoid troubles like that.
