### ISSUE TITLE
src/CGAL_ImageIO/bmp.cpp:119]: (error) Resource leak: fp

### ISSUE THREAD

**Issue by dcb314** [CGAL/cgal#954]
Source code is

    filePos = ftell(fp);
    rc = readUINT16little(fp, &fileType);
    if (rc != 0) {
      if ( _VERBOSE_BMP_ )
        fprintf( stderr, "%s: error in getting file type %s\n", proc, name );
      return( (void*)NULL );
    }

Suggest call fclose in the if statement.

**Comment by lrineau** [comment]
Thanks. That will be fixed in CGAL-4.9, by the commit  ff515d7.

**Comment by lrineau** [comment]
By the way, @dcb314, how have you found out that issue? Was it by chance or have you use a kind of code analyzer?

**Comment by dcb314** [comment]
I used the cppcheck static analyser. It is available from sourceforge.
