### ISSUE TITLE
Bug in BGL test_Euler_operations

### ISSUE THREAD

**Issue by gdamiand** [CGAL/cgal#955]
Two bugs: see my commits https://github.com/CGAL/cgal-dev/commit/17a1cde689e3f226b1cd04c0acad436162a65758 and https://github.com/CGAL/cgal-dev/commit/bb88d311ae8510260c10d0e90c13af298ac456ca

**Comment by lrineau** [comment]
It seems you already have a fix. You should open a pul-request with a cherry-pick of the two commits.

**Comment by gdamiand** [comment]
Here https://github.com/CGAL/cgal/pull/958.

**Comment by lrineau** [comment]
Fixed by #958.
