### ISSUE TITLE
Integrate <CGAL/Mesh_3/squared_distance_Point_3_Triangle_3.h> in the kernel

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#967]
@afabri

The function `squared_distance(Point_3, Triangle_3)` is not in the kernel. As far as I know, it is only defined in `<CGAL/Mesh_3/squared_distance_Point_3_Triangle_3.h>`.

It should be integrated in the kernel, with the other distance functions.

**Comment by afabri** [comment]
See #969
