### ISSUE TITLE
2D Arrangements Observer Notification Related to Aggregated Insertion Function

### ISSUE THREAD

**Issue by myirci** [CGAL/cgal#97]
Hello,

When incremental global insertion function is used to insert curves into an arrangement, the observer attached to that Arrangement gives notifications as expected. However, when aggregated global insertion function is used to insert curves into an arrangement, the notifications for edge splitting does not work.  I've tested this with both segments Bézier arrangements. Below is a very simple program which displays the issue for segments arrangement.

<pre>
#include &lt;vector&gt;
#include &lt;CGAL/Cartesian.h&gt;
#include &lt;CGAL/Quotient.h&gt;
#include &lt;CGAL/MP_Float.h&gt;
#include &lt;CGAL/Arr_segment_traits_2.h&gt;
#include &lt;CGAL/Arrangement_2.h&gt;
#include &lt;CGAL/Arr_observer.h&gt;

typedef CGAL::Quotient&lt;CGAL::MP_Float&gt;       Number_type;
typedef CGAL::Cartesian&lt;Number_type&gt;         Kernel;
typedef CGAL::Arr_segment_traits_2&lt;Kernel&gt;   Traits_2;
typedef Traits_2::Point_2                    Point_2;
typedef Traits_2::X_monotone_curve_2         Segment_2;
typedef CGAL::Arrangement_2&lt;Traits_2&gt;        Arrangement_2; 

class observer : public CGAL::Arr_observer&lt;Arrangement_2&gt; {
public:
    observer (Arrangement_2& arr) : CGAL::Arr_observer&lt;Arrangement_2&gt; (arr) { }

    virtual void before_split_edge(Halfedge_handle heh, Vertex_handle vh, const X_monotone_curve_2& c1, const X_monotone_curve_2& c2) {
        std::cout << "before_split_edge: " << std::endl;
    }
    virtual void after_split_edge(Halfedge_handle he1, Halfedge_handle he2) {
        std::cout << "after_split_edge" << std::endl;
    }
    virtual void before_split_face (Face_handle fh, Halfedge_handle e) {
        std::cout << "before_split_face" << std::endl;
    }
    virtual void after_split_face(Face_handle fh1, Face_handle fh2, bool is_hole) {
        std::cout << "after_split_face" << std::endl;
    }
};

int main () {
    Arrangement_2 arrangement1;
    Arrangement_2 arrangement2;
    observer ob1(arrangement1);
    observer ob2(arrangement2);

    Point_2 pt1(1,1), pt2(4,1), pt3(4,4), pt4(1,4);
    Segment_2 s1(pt1, pt2), s2(pt2, pt3), s3(pt3, pt4), s4(pt4, pt1), s5(pt1, pt3), s6(pt4, pt2);

    // INCREMENTAL INSERTION
    std::cout << "************************************************" << std::endl;
    CGAL::insert(arrangement1, s1);
    CGAL::insert(arrangement1, s2);
    CGAL::insert(arrangement1, s3);
    CGAL::insert(arrangement1, s4);
    CGAL::insert(arrangement1, s5);
    CGAL::insert(arrangement1, s6);
    std::cout << "************************************************" << std::endl;
    // AGGREGATE INSERTION
    std::vector<Segment_2> segments { s1, s2, s3, s4, s5, s6 };
    CGAL::insert(arrangement2, segments.begin(), segments.end());
    std::cout << "************************************************" << std::endl;
    return 0;
}
</pre>

And the output of this program is:
<pre>
************************************************
before_split_face
after_split_face
before_split_face
after_split_face
before_split_edge: 
after_split_edge
before_split_face
after_split_face
before_split_face
after_split_face
************************************************
before_split_face
after_split_face
before_split_face
after_split_face
before_split_face
after_split_face
before_split_face
after_split_face
************************************************
</pre>

Observe that <b><i>before_split_edge </i></b> and <b><i>after_split_edge </i></b> is not called when aggregated insert function is used.

Regards,
Murat Yirci

**Comment by efifogel** [comment]
Hi Murat,

Right, and *before_split_edge * and *after_split_edge *are not expected to
be called when aggregated insert function is used.
The events are different for the two methods.
When inserting using a sweep, the curves are intersected before they are
actually inserted, so an edge split does not occur.

Add the notification functions bellow, and it will become clear to you.

  virtual void before_create_vertex(const Point_2& p)
  { std::cout << "before__create_vertex: " << p << std::endl; }
  virtual void before_create_edge (const X_monotone_curve_2& c,
                                   Vertex_handle /* v1 */,
                                   Vertex_handle /* v2 */)
  { std::cout << "before__create_edge: " << c << std::endl; }

Efi

   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by myirci** [comment]
Hi Efi,

Thank you very much for your explanation. It's clear for me now.

Murat
