### ISSUE TITLE
PMP::triangulate_refine_and_fair_hole() results with seemingly bad triangulation

### ISSUE THREAD

**Issue by efifogel** [CGAL/cgal#981]
Attached are the following files:

base.wrl - the input file

base.jpg - a view of the model
base_back.jpg - a back view of the model
base_wire.jpg  - a view of the model in wire frame

base_fair.jpg - a view of the result
base_wire_fair.jpg - - a view of the result in wire frame

Notice the triangle that sticks out. It looks like a bug.
[base.zip](https://github.com/CGAL/cgal/files/201488/base.zip)

**Comment by janetournois** [comment]
Hi Efi,

thanks for your bug report
Can you please tell me the parameters you are using? 

I can't reproduce this bug. See below what I get in the Polyhedron demo
![base_no_hole](https://cloud.githubusercontent.com/assets/11311305/14245389/51480d66-fa61-11e5-88d4-cc5490573940.jpg)

**Comment by efifogel** [comment]
Hi Jane,

I would like to get this... It seems that only one vertex is added. I
wonder what parameters are used by the demo.
Anyhow, I'm using the default parameters.

You can try the example Polygon_mesh_processing/hole_filling_example.cpp
<http://doc.cgal.org/latest/Polygon_mesh_processing/Polygon_mesh_processing_2hole_filling_example_8cpp-example.html>
This time you will need an off file. It is attached.
It also uses the default parameters and it also produces a seemingly wrong
polyhedron.

The printed out messages:

 Number of facets in constructed patch: 24
 Number of vertices in constructed patch: 3
 Fairing : succeeded

I've also tried: triangulate_and_refine_hole().
The number of newly constructed facets and vertices is the same (i.e., 24 &
3, resp).
This time the polyhedron looks good, but if I get 3 new vertices, I expect
to get only 8 new facets (and not 24). Maybe this should give a clue.
Also, why do I get 3 new vertices to start with?

Efi





   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by efifogel** [comment]
Now it is attached.
[base.off.zip](https://github.com/CGAL/cgal/files/203053/base.off.zip)

**Comment by afabri** [comment]
The corners of the hole are probably not what you expect. When in the Polyhedron demo, perform Operations -> Polygon Mesh Processing -> Show Boundaries and you get:
![corner](https://cloud.githubusercontent.com/assets/3263539/14271346/69288bbc-faf8-11e5-86fb-0c1d0ee485f4.JPG)

With Operations Surface Mesh Deformation you can pick and move a vertex to see the real topology
![deformed](https://cloud.githubusercontent.com/assets/3263539/14271387/eaa0869a-faf8-11e5-826c-70bd6a8573de.JPG)
 
I tried to stitch the border, but that did not help, so I guess the "corner point" exists several time, but with slightly different coordinates. Shift left click close to the corner point prints the coordinate on the console. And in fact, in the file I find  4 0 86,  4 7.80626e-15 86,   and  4 3.46945e-15 86  

Note that when I load the off file I also get a message about 4 isolated vertices.

**Comment by janetournois** [comment]
Interesting... 

I had already converted the polyhedron you sent to `off`, using [meshconv](http://www.cs.princeton.edu/~min/meshconv/). Here is what I got [base.zip](https://github.com/CGAL/cgal/files/204006/base.zip)

The default options of this tool removes duplicate vertices, and zero area polygons. It seems that it has been enough to fix your input and get a nicely filled hole...

**Comment by efifogel** [comment]
I've downloaded and tried out the meshconv tool and was able to reproduce
the 'good' triangulation that you got.

I came to the conclusion that the function
triangulate_refine_and_fair_hole() is simply not robust when it uses an
inexact construction kernel. I simply replaced the coordinate 3.46945e-15
with 0.01234 and then again with -0.01234 and in both cases the change
fixed the problem.

I cannot confirm my theory, because one cannot use Epec (yet :). Notice
that triangulate_and_refine() does not suffer from this problem, even
though it also introduces new vertices. In any case, since construction do
occur, even if not intermediate, then Epec should be supported with both
triangulate_refine_and_fair_hole() and triangulate_and_refine().

First, the code should be fixed so that it is not (or at least less)
sensitive to inexact construction if possible, and by possible, I mean
simple fixes.

Secondly, there is, and always have been, a tradeoff performance and
robustness, and I assume that when it comes to polyhedrons in 3D, where the
average size of the input is one magnitude larger than the average size of
input in 2D, it's even harder to justify the penalty we get for robustness.
However, if indeed, this is the case, and if indeed we want to follow a
path that compromise robustness, it should be addressed in a global manner
and documented accordingly.

Regarding the experiment with meshconv. This tool not only removes
duplicate vertices, but also collapses similar adjacent vertices into one.
The original file has 20 border vertices. The output of meshconv has 4
vertices that define a nice large square. I don't know what criterion it
uses to determine whether points should be collapsed, but I can tell you
that the following 5 vertices, for example,

126     3.46945e-15 4      # 0
126     0.060769 3.30541   # 1
126     2.60209e-15 4      # 2
126.626 0.0492466 4        # 3
126     3.46945e-15 4      # 4

got replaced by

126 0 4

BW, Scratch my previous comment and question regarding the number of newly
created vertices and facets in the patch.



   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by afabri** [comment]
Efi, did you read my comment?  Your input is self-intersecting with vertices that should  be snapped first. Snapping is definitely something we should offer, but that is another topic.

**Comment by efifogel** [comment]
Yes, I did.
Have read mine?
It could be because the model is self-intersecting, but I suspect that it
has to do with robustness.
I re-iterate, when a certain coordinate, namely 3.46945e-15 is replaced
with with a different coordinate that is close but sufficiently far,
everything works as expected. Otherwise, you get some weird triangles
sticking out.

   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by cebe** [comment]
I have a similar issue, described in #978 where I am getting a zero area facet using another method. Using the `Exact_predicates_exact_constructions_kernel` (which I am), shouldn't this avoid these issues?

**Comment by sgiraudot** [comment]
@janetournois did you investigate this issue any more? Do we hope to solve it soon?
