### ISSUE TITLE
Delaunay Triangulation crash in threaded environment - incorrect static declaration?

### ISSUE THREAD

**Issue by etrinh** [CGAL/cgal#991]
Hi,

During our evaluation of CGAL prior to licensing.
We have maybe noticed the cause of the crash when we were using CGAL in a multi-threaded application (1 independent object's instance per thread).
In Delaunay_triangulation.h:783
There is a static instantiation of an object which is cleared just after. It seems to be the root of our troubles. At first reading, this static seems dangerous. I tried to remove the static, and it seems to work. But I can't validate whether the patch is correct anyway.

Thanks,
Best Regards,
Eric

**Comment by cjamin** [comment]
Hi,
You are right, this "static" keyword can be removed safely.
It's already fixed in a development branch I'm working on, so it should be fixed in CGAL 4.9.
Best.

**Comment by lrineau** [comment]
The `static` keyword seems to be an optimization, to avoid that a new vector is reallocated at each call to the function.

Should not the variable be a thread-local variable?

@afabri Can `<CGAL/tss.h>` be used here?

**Comment by lrineau** [comment]
@cjamin Remember that fixes should be against the last release branch, thus `releases/CGAL-4.8-branch`, an maybe even against `releases/CGAL-4.7-branch` if the bug was already in CGAL-4.7.

**Comment by afabri** [comment]
See  #992

**Comment by lrineau** [comment]
The PR #992 has been merged in the release branch for CGAL-4.8.1.
